autotest/tp-libvirt

libvirt/tests/cfg/migration/migrate_options_shared.cfg
libvirt/tests/src/migration/migrate_options_shared.py

Test migration with pty channel is working well.

migrate_options_shared: Add pty channel migration

---

libvirt/tests/src/controller/pcibridge.py

Fix typo: replace ',' with '%'

---

v2v/tests/cfg/function_test_esx.cfg
v2v/tests/src/function_test_esx.py

Add new v2v case for RHEL-134430

---

v2v/tests/cfg/convert_vm_to_ovirt.cfg
v2v/tests/src/convert_vm_to_ovirt.py

Support -it vddk for v2v

---

libvirt/tests/src/virsh_cmd/domain/virsh_domtime.py

Seems hwclock output format has changed in recent distributions,
let's handle it.

Fixup: Handle new hwclock format

---

libvirt/tests/cfg/sriov/sriov.cfg
libvirt/tests/src/sriov/sriov.py

Add support for mlx and i40e sriov driver card

---

libvirt/tests/src/virsh_cmd/pool/virsh_pool_autostart.py

Fix dir/scsi pool failures in virsh_pool_autostart

Fix dir/scsi pool failures in virsh_pool_autostart

---

libvirt/tests/src/bios/virsh_boot.py
libvirt/tests/src/virsh_cmd/domain/virsh_blockcommit.py
libvirt/tests/src/virsh_cmd/domain/virsh_blockpull.py
libvirt/tests/src/virsh_cmd/pool/virsh_pool_auth.py
libvirt/tests/src/virtual_disks/virtual_disks_ceph.py
libvirt/tests/src/virtual_disks/virtual_disks_luks.py

Fix ceph cases false warning error message issue by creating /etc/ceph/ceph.conf

Fix ceph cases false warning error message issue by creating ceph.conf

---

v2v/tests/cfg/convert_vm_to_libvirt.cfg
v2v/tests/cfg/convert_vm_to_ovirt.cfg
v2v/tests/cfg/specific_kvm.cfg
v2v/tests/src/function_test_esx.py
v2v/tests/src/v2v_options.py

v2v: Replace --password-file with -ip

---

v2v/tests/cfg/v2v_options.cfg

v2v: add case mix options --password-file and -ip

---

libvirt/tests/src/libvirt_hooks.py

Attach failure is caused by 'insufficient' pci controller
Add corresponding pci controller for both 'q35' and 'i440fx' VM
Detach failure is caused by 'timeout' issue
Add 'timeout' for both Attach and Detach operation

Fix Attach and Detach failure in 'network_hook' test

---

v2v/tests/cfg/convert_vm_to_libvirt.cfg
v2v/tests/cfg/function_test_esx.cfg
v2v/tests/src/convert_vm_to_libvirt.py
v2v/tests/src/function_test_esx.py

1) Add vddk support for convert_vm_to_libvirt
2) Add vddk support for function_test_esx

Add vddk support for more esx cases

---

libvirt/tests/cfg/sriov/sriov.cfg
libvirt/tests/src/sriov/sriov.py

Modify nfv cases to support both q35 and pc machine_type

---

libvirt/tests/cfg/cpu/vm_features.cfg
libvirt/tests/src/cpu/vm_features.py

- Verify hv_frequencies, hv_reenlightenment and hv-tlbflush
enlightenments works
depends on https://github.com/avocado-framework/avocado-vt/pull/2037

Add new case of cpu management

---

libvirt/tests/cfg/usb_device.cfg
libvirt/tests/src/usb_device.py

Test usb feature based on the following matrix:
the combination usage of machine type q35/i440fx, pci/pcie
bus controller and usb controller
bus controller on q35 machine:
1, pcie-root,pcie-root-port,pcie-to-pci-bridge,pci-bridge
2, pcie-root,pcie-root-port,pcie-switch-upstream-port, pcie-switch-downstream-port
3, pcie-root,dmi-to-pci-bridge,pci-bridge
bus controller on i440fx machine:
1, pci-root,pci-bridge
usb30_controller:
nec-xhci
qemu-xhci
usb20_controller:
ich9-ehci1,ich9-uhci1,ich9-uhci2,ich9-uhci3

add test case usb_device

---

libvirt/tests/cfg/papr_hpt.cfg
libvirt/tests/src/papr_hpt.py

- Set HPT guest with maxpagesize 16M/64K with hugepage and numa
node setting
- Set HPT guest with maxpagesize 16M/64K without hugepage setting

Add hpt cases for pseries

---

libvirt/tests/cfg/usb_device.cfg
libvirt/tests/src/usb_device.py

1. cold-plug/unplug usb host device to/from vm
2. hot-plug/unplug usb host device to/from vm

add usb host device test scenarios

---

libvirt/tests/cfg/virtual_network/iface_network.cfg
libvirt/tests/src/virtual_network/iface_network.py

- Update the QoS setting in interface by update-device

Add Qos case

---

libvirt/tests/src/controller/pcibridge.py

It need to wait a few seconds to check dumpxml after detaching interface

pcibridge: add wait time

---

v2v/tests/cfg/function_test_esx.cfg
v2v/tests/cfg/function_test_xen.cfg

Add function tests for suse guests

---

v2v/tests/cfg/function_test_esx.cfg

Add new case for resume=/dev/mapper/xxx

---

v2v/tests/cfg/v2v_options.cfg
v2v/tests/src/v2v_options.py

v2v: Add case for --print-estimate

---

libvirt/tests/src/papr_hpt.py

Cancel test of maxpagesize if qemu version is too low

---

libvirt/tests/src/sriov/sriov.py

Modify the wait time for generating max vfs

---

v2v/tests/cfg/function_test_esx.cfg
v2v/tests/src/function_test_esx.py

Add testcases for esx uri with vddk

---

libvirt/tests/src/sriov/sriov.py

Adjust the script to get the net list at the right time

---

libvirt/tests/src/npiv/npiv_snapshot.py

Sometimes the first lun found in /dev/disk/by-path connected by
newly created vhba is not the first vol in scsi pool. This will
cause problem. This fix is to make sure using the correct block
device.

Fix npiv snapshot issue

---

libvirt/tests/src/migration/migrate_vm.py

migrate_vm: Fix the wrong msg format

---

libvirt/tests/src/migration/migrate_vm.py

migrate_vm: Fix test param missing

---

provider/v2v_vmcheck_helper.py
v2v/tests/cfg/convert_vm_to_libvirt.cfg
v2v/tests/cfg/function_test_esx.cfg

Add metadata libosinfo checking for v2v

---

libvirt/tests/src/virsh_cmd/volume/vol_concurrent.py

Update the module name queue to Queue
Signed-off-by: jgao <jgao@redhat.com>

update module name queue for python3

---

libvirt/tests/cfg/libvirt_scsi_hostdev.cfg
libvirt/tests/src/libvirt_scsi_hostdev.py

Hotplug/unplug, coldplug or edit xml will be used to add scsi
hostdev, and all hostdev attrs will be covered.

Add cases to cover scsi host device passthough

---

libvirt/tests/src/virsh_cmd/host/virsh_maxvcpus.py

virsh maxvcpus reporting is not same across distributions
and some distributions uses both maxvcpus from domcapabilities
and system capabilities xml for different types qemu, kvm.
So let's relax the assertion includes maxvcpu values
from both places.
Reference: https://bugzilla.redhat.com/show_bug.cgi?id=1455363

Relax maxvcpu assertion with maxvcpu from capabilities xml

---

provider/v2v_vmcheck_helper.py

A temporary workaround for new features which doesn't
support in slow train

Checking if the featured is supported before using

---

libvirt/tests/src/virtual_disks/virtual_disks_iscsi.py

After attach disk to vm, disk name is changed sometimes in s390 arch.
So assign 'serial' when attach disk,and then check disk by serial string
in VM. But lun devices do not support serial property, keep 'old' style
for lun devices related cases.

virtual_disks_iscsi: Update to check attached disk by serial string

---

libvirt/tests/src/virtual_network/iface_network.py

As libvirt 5.1 introduce the patch "Create private chains for virtual
network firewall rules", the chain name changed. Update the script the
be compatible for both new and old versions.

Check the private chains for iptables rules

---

libvirt/tests/src/virtual_device/input_devices.py

- Add debug logs for future debugging
- One var named 'error' is not defined
- Fix that fail to add input device when it's pseries vms

Add logs and fix a var not defined error

---

libvirt/tests/src/graphics/graphics_functional.py

"Debug the issues of graphics_functional.py"
Fix the value error "ValueError: not enough values to unpack
(expected 2, got 1)" which is caused because the same regular
expressions "-vnc\s*(\S*)" can not match the right vnc relevant
arguments in qemu command line of RHEL 8.0

  "Debug the issues of graphics_functional.py"

---

v2v/tests/cfg/convert_from_file.cfg

Correct the expected results for case84967 as previous results are
wrong.

Modify the expected result for virt-v2v case84967

---

libvirt/tests/cfg/virtual_device/vsock.cfg

Modify the variable name to match the name used in .py file

---

libvirt/tests/cfg/conf_file/qemu_conf/set_virtlogd.cfg
libvirt/tests/src/conf_file/qemu_conf/set_virtlogd.py

Start guest with spice graphic, and then reload virtlogd.service.

set_virtlogd: Add case for test reload virtlogd

---

libvirt/tests/src/virsh_cmd/domain/virsh_migrate_copy_storage.py

After migration, attached disks need be verified for I/O operations.

virsh_migrate_copy_storage: Add checking disks in vm

---

provider/v2v_vmcheck_helper.py
v2v/tests/cfg/convert_from_file.cfg
v2v/tests/src/convert_from_file.py
v2v/tests/src/v2v_options.py

1) Support genid checking for windows guests
2) Support vmx and vmx_ssh in convert_from_file

Add genid and vmx and vmx_ssh support

---

libvirt/tests/cfg/bios/virsh_boot.cfg
libvirt/tests/src/bios/virsh_boot.py

format a qcow2 usb virtual disk and boot vm from this disk

add libvirt test case - vm boot from usb virtual disk

---

libvirt/tests/cfg/nwfilter/filter_aready_present_binding.cfg
libvirt/tests/src/nwfilter/filter_aready_present_binding.py

Senario 1: start vm with nwfilterred defined in xml
Senario 2: start vm with nwfilterred do not defined in xml

new case: Create nwfilter-binding when aready present

---

libvirt/tests/cfg/controller/multiple_controller_ppc.cfg
libvirt/tests/src/controller/multiple_controller_ppc.py

Add some mphb cases

---

libvirt/tests/src/virsh_cmd/domain/virsh_domblkerror.py

Allow selinux to permit libvirt to access file from NFS else virsh
attach-device fails with permission denied issue as selinux blocks
libvirt and testcase will errors out.

virsh_domblkerror: set `virt_use_nfs=on` for selinux to permit libvirt

---

libvirt/tests/cfg/virtual_device/tpm_device.cfg
libvirt/tests/src/virtual_device/tpm_device.py

Automate tpm passthrough cases. Need tpm.py file in
avocado-vt/pull/2011.

tpm_device: automate tpm passthrough cases

---

libvirt/tests/cfg/virtual_disks/virtual_disks_multidisks.cfg
libvirt/tests/src/virtual_disks/virtual_disks_multidisks.py

As per bugs:Bug 1043374, Bug 1043436, attaching operation need fail

add test case to cover USB virtual disk attached to PCI controller

---

libvirt/tests/cfg/libvirt_usb_hotplug_controller.cfg
libvirt/tests/src/libvirt_usb_hotplug_controller.py

disordered usb controller can be reorganized by index group

add disordered usb2.0 companion controllers cases

---

libvirt/tests/src/svirt/dac_nfs_disk.py
libvirt/tests/src/virsh_cmd/pool/virsh_pool_autostart.py
libvirt/tests/src/virsh_cmd/volume/virsh_volume.py

TypeError: catching classes that do not inherit from BaseException
is not allowed

Fix exception: TypeError

---

libvirt/tests/cfg/virtual_device/video_devices.cfg
libvirt/tests/src/virtual_device/video_devices.py

Add the cases for virtual video devices

---

libvirt/tests/cfg/virt_admin/management/virt_admin_server_threadpool_set.cfg
libvirt/tests/src/virt_admin/management/virt_admin_server_threadpool_set.py

1. Refactor the code to increase its extensibility
2. Add some cases server_threadpool_pool

Add some cases of server_threadpool_pool of virt_admin

---

libvirt/tests/cfg/virsh_cmd/domain/virsh_create.cfg
libvirt/tests/src/virsh_cmd/domain/virsh_create.py

Added the cases for the "--validate" option of virsh create

Add the cases for virsh create

---

libvirt/tests/cfg/virsh_cmd/network/virsh_net_destroy.cfg
libvirt/tests/src/virsh_cmd/network/virsh_net_destroy.py

Check vm status after transisent network destroyed and libvirtd restart.

Check vm status after network destroyed

---

libvirt/tests/cfg/virsh_cmd/domain/virsh_migrate_vm_cfg.cfg
libvirt/tests/src/virsh_cmd/domain/virsh_migrate_vm_cfg.py

Add virsh_migrate_vm_cfg.cfg and virsh_migrate_vm_cfg.py, which tests
--persistent, --persistent-xml, --xml, --dname, --undefinesource and
with/without graphic passwd, multiplied by p2p/tunnelled/normal
migraiton, precopy/postcopy, src vm status and src vm persistency.

Add new test cases for migration.

---

libvirt/tests/src/remote_access/remote_access.py

Add the port of firewall instead of flushing the iptables rules
is more suitable for security

Add the corresponding port of firewall for tls/tcp connection

---

libvirt/tests/cfg/virtual_disks/at_dt_iscsi_disk.cfg
libvirt/tests/src/virtual_disks/at_dt_iscsi_disk.py

create lvm based on vm,then attach to VM,and ensure
VM can started and device can be found.

add attach lvm block device to VM case

---

v2v/tests/cfg/convert_from_file.cfg

Add a switch to control vm checking for gating cases

---

libvirt/tests/cfg/nwfilter/nwfilter_binding_delete.cfg
libvirt/tests/src/nwfilter/nwfilter_binding_delete.py

to test virsh command nwfilter-binding-delete

new case: nwfilter-binding-delete test

---

libvirt/tests/cfg/libvirt_mem.cfg

Set cases of memory align to 256m as ppc only

---

v2v/tests/cfg/function_test_esx.cfg
v2v/tests/cfg/function_test_xen.cfg
v2v/tests/cfg/specific_kvm.cfg
v2v/tests/src/function_test_esx.py
v2v/tests/src/function_test_xen.py
v2v/tests/src/specific_kvm.py

1. Support rhv_upload and vddk for function_test_esx
2. Support rhv_upload for function_test_xen
3. Support rhv_upload and vddk for specific_kvm

Add rhv_upload and vddk support for function cases

---

libvirt/tests/cfg/bios/boot_integration.cfg
libvirt/tests/cfg/bios/virsh_boot.cfg
libvirt/tests/cfg/bios/virsh_boot_tseg.cfg

remove the machine varient from test case cfg file

update test case bios

---

libvirt/tests/src/channel/channel_functional.py

Fix removing tmp_dir before assignment issue

---

v2v/tests/cfg/v2v_options.cfg

Add one negative case for '-o glance --no-copy'

---

libvirt/tests/cfg/migration/migrate_options_shared.cfg
libvirt/tests/src/migration/migrate_options_shared.py

Automated 2 P2P migration cases in this Patch.
This Patch checks migration behavior with keepalive protocol.

migration: Add 2 keepalive related cases

---

libvirt/tests/cfg/migration/migrate_options_shared.cfg

It displays different error message in target in some cases, so
update it accordingly.

migration: update error message

---

libvirt/tests/cfg/virsh_cmd/pool/virsh_pool.cfg
libvirt/tests/cfg/virsh_cmd/pool/virsh_pool_create.cfg
libvirt/tests/src/bios/virsh_boot.py
libvirt/tests/src/migration/migrate_vm.py
libvirt/tests/src/svirt/dac_vm_per_image_start.py
libvirt/tests/src/virsh_cmd/domain/virsh_blockcommit.py
libvirt/tests/src/virsh_cmd/domain/virsh_blockpull.py
libvirt/tests/src/virsh_cmd/pool/virsh_pool.py
libvirt/tests/src/virsh_cmd/pool/virsh_pool_autostart.py
libvirt/tests/src/virsh_cmd/pool/virsh_pool_create.py
libvirt/tests/src/virsh_cmd/snapshot/virsh_snapshot_create_as.py
libvirt/tests/src/virsh_cmd/snapshot/virsh_snapshot_disk.py
libvirt/tests/src/virsh_cmd/volume/virsh_volume.py
libvirt/tests/src/virtual_disks/virtual_disks_gluster.py
libvirt/tests/src/virtual_disks/virtual_disks_luks.py

Give more params to gluster related func to pass gluster server related info

Update for outside gluster server

---

libvirt/tests/src/virsh_cmd/network/virsh_net_start.py

virsh_net_start: Prettify error message

---

libvirt/tests/src/cpu/setvcpu.py

setcpu: Remove topology setting to avoid conflict with cpu count

---

provider/v2v_vmcheck_helper.py

Fix a spelling error

---

libvirt/tests/cfg/virsh_cmd/domain/virsh_migrate_vm_cfg.cfg
libvirt/tests/src/virsh_cmd/domain/virsh_migrate_vm_cfg.py

Fixup for commit "f090029 Add new test cases for migration."

---

v2v/tests/cfg/function_test_xen.cfg
v2v/tests/src/function_test_xen.py

Becase there is no virtio drivers for the win2003 guest,skip
the checkpoints.

Skip check guest for v2v case12987

---

libvirt/tests/src/cpu/max_vcpus.py

This failure is caused by VM will be defined failed with negative vcpu conf in RHEL-8.1 AV; which will result in the case failed in advance at vmxml.sync() for RHEL-8.1 AV.
However; VM still can be defined suyccessfully for libvirt lower that 5.6.0. So added related judgement for these 2 situations.

Fix defining VM failed in vmxml.sync() for RHEL-8.1 AV

---

libvirt/tests/src/virsh_cmd/domain/virsh_migrate.py

Fix issue "local variable 'detail' referenced before assignment"

---

libvirt/tests/src/virsh_cmd/domain/virsh_vncdisplay.py

virsh_vncdisplay: Fixup a ShellTimeoutError issue

---

libvirt/tests/src/virsh_cmd/domain/virsh_start.py
libvirt/tests/src/virsh_cmd/monitor/virsh_dommemstat.py

Fix 'ShellTimeoutError' for virsh_start and virsh_dommemstat.

Fixup two remote test problems

---

libvirt/tests/src/migration/migrate_options_shared.py

On RHEL 7, firewall direct rules cannot broken migration connection,
so update to use iptables.

migration: update firewall rule for keepalive cases on rhel7

---

libvirt/tests/cfg/migration/migrate_vm.cfg

Update expected error message to make it pass.

Update err_msg for local storage migration without copy-storage-all/nic

---

libvirt/tests/src/virsh_cmd/domain/virsh_blkiotune.py

Bfq scheduler will have different cgroup files for blkio
controller, update it.

Fix blkiotune case failures when host OS using bfq scheduler

---

libvirt/tests/src/virsh_cmd/domain/virsh_vcpupin.py

Fix error as avocado-vt module changed

---

libvirt/tests/cfg/migration/migrate_options_shared.cfg
libvirt/tests/src/migration/migrate_options_shared.py

Add 2 migration cases which check events during migration.

migration: 2 new cases to check event during migration

---

v2v/tests/cfg/v2v_options.cfg
v2v/tests/src/v2v_options.py

The shell file for installing guest is invaild so use ova to
replace, and fix the pool creation problem.

Fix the pool creation problem for v2v case13098

---

libvirt/tests/cfg/virsh_cmd/domain/virsh_domuuid.cfg

Fix test case naming from commit f2b5f93

Fix test case naming

---

libvirt/tests/cfg/virsh_cmd/pool/virsh_find_storage_pool_sources.cfg
libvirt/tests/cfg/virsh_cmd/pool/virsh_find_storage_pool_sources_as.cfg
libvirt/tests/src/virsh_cmd/pool/virsh_find_storage_pool_sources.py
libvirt/tests/src/virsh_cmd/pool/virsh_find_storage_pool_sources_as.py

Add iscsi-pool for find-storage-pool-sources/-as
Signed-off-by: meinaLi <meili@redhat.com>

Add iscsi-direct pool for find-storage-pool-sources/-as

---

v2v/tests/cfg/function_test_esx.cfg

Add v2v function test case152745.
Signed-off-by: liuzi <zili@redhat.com>

v2v_case_152745 query package with epoch

---

v2v/tests/cfg/specific_kvm.cfg

Fix wrong target problem for a rhev case

---

provider/v2v_vmcheck_helper.py

Fix the logic of getting expected video types

---

libvirt/tests/cfg/virtual_network/iface_options.cfg
libvirt/tests/src/virtual_network/iface_options.py

User type interface can have custom ip address set in interface. Add
test cases about setting ip address into interface section.

Add test for user type interface

---

libvirt/tests/cfg/virtual_network/iface_update.cfg
libvirt/tests/src/virtual_network/iface_update.py

Add 2 more scenarios for live update filterref except for add filterref:
update filterref, del filterref.

Update filterref by update-device

---

v2v/tests/src/function_test_xen.py

Fix code error "'remote_disk_image' is missing" which 
is reported in auto testing.

Modify error "remote_disk_image' is missing" for v2v case12993

---

libvirt/tests/cfg/nwfilter/nwfilter_binding_create.cfg
libvirt/tests/src/nwfilter/nwfilter_binding_create.py

nwfilter_binding_create case code
and cfg file is add.

case about nwfilter_binding_create

---

libvirt/tests/cfg/nwfilter/nwfilter_binding_list.cfg
libvirt/tests/src/nwfilter/nwfilter_binding_list.py

automation about nwfilter-binding-list

new case: nwfilter-binding-list check

---

libvirt/tests/cfg/nwfilter/vm_destroy_with_nwfilter.cfg
libvirt/tests/src/nwfilter/vm_destroy_with_nwfilter.py

while vm destroy with nwfilter, libvirtd.log
will get error before. and get check

new case about vm destroy with nwfilter

---

libvirt/tests/cfg/nwfilter/nwfilter_binding_dumpxml.cfg
libvirt/tests/src/nwfilter/nwfilter_binding_dumpxml.py

test virsh command nwfilter_binding_dumpxml

new case: nwfilter_binding_dumpxml test

---

v2v/tests/cfg/function_test_esx.cfg

The warning info for case is wrong in code, so correct it.

Fix warning info for v2v case84636

---

libvirt/tests/cfg/serial/serial_functional.cfg

This is a positive case and pseries does not support spice

Remove 1 spice related case from pseries

---

libvirt/tests/src/virsh_cmd/domain/virsh_reboot.py

It requires 'password' when execute 'virsh reboot' command line.
So setup ssh connection to fix this issue.

Fix remote access issue for virsh.reboot test

---

libvirt/tests/src/migration/migrate_options_shared.py

1. update TestSkipError to TestCancel
2. delete object to recover remote configuration files correctly

Fixup 2 minor issues in migrate_options_shared

---

v2v/tests/cfg/specific_kvm.cfg

Add new auto cases for v2v RHEL-134137 and  RHEL-130632.
Signed-off-by: liuzi <zili@redhat.com>

add 2 new cases about selinuxtype testing

---

libvirt/tests/cfg/virsh_cmd/pool/virsh_pool.cfg
libvirt/tests/src/virsh_cmd/pool/virsh_pool.py

Add lifecycle test of iSCSI-direct based storage pool

Add lifecycle test of iSCSI-direct based storage pool

---

libvirt/tests/cfg/virtual_disks/at_dt_iscsi_disk.cfg
libvirt/tests/src/virtual_disks/at_dt_iscsi_disk.py

1. add volume disk testing in iscsi pool with chap auth
2. add volume disk testing in iscsi-direct pool
Signed-off-by: meinaLi <meili@redhat.com>

Add volume disk testing in iscsi-direct pool

---

libvirt/tests/cfg/bios/virsh_boot.cfg
libvirt/tests/src/bios/virsh_boot.py

1. Add new case in os firmware element
2. Fix an error in with_nvram_template but not with_template
Signed-off-by: Meina Li <meili@.redhat.com>

BIOS: add new case in os firmware element

---

libvirt/tests/src/virsh_cmd/domain/virsh_blkiotune.py

On s390x first device is 'dasda'. The path to I/O scheduler is now
a global variable whose value is set depending on arch. I made it
global because it's used in many functions in the script.
* Test run on s390x
JOB ID     : 4659cbc4a6bbececc906e757bf1fecad49b50942
JOB LOG    : /root/avocado/job-results/job-2019-09-27T13.06-4659cbc/job.log
(1/1) type_specific.io-github-autotest-libvirt.virsh.blkiotune.positive.get_blkio_parameter.running_guest.options.none: PASS (9.71 s)
JOB TIME   : 11.29 s
JOB ID     : ab5d02279916aa13bf4f0c0998ec004a626429d6
JOB LOG    : /root/avocado/job-results/job-2019-09-27T13.06-ab5d022/job.log
(1/1) type_specific.io-github-autotest-libvirt.virsh.blkiotune.positive.set_blkio_parameter. …

Make I/O scheduler path arch dependent

---

libvirt/tests/cfg/virtio_transitional/virtio_transitional_blk.cfg
libvirt/tests/src/virtio_transitional/virtio_transitional_blk.py

1. Matrix of virtio/virtio-transitional/virtio-non-transitional
2. Basic boot test
3. Hot plug/unplug/cold plug test
4. Snapshot test
5. Matrix of virtio-blk/virtio-scsci

virtio_transitional: Add test cases for block device

---

libvirt/tests/cfg/virsh_cmd/network/virsh_net_define_undefine.cfg
libvirt/tests/src/virsh_cmd/network/virsh_net_define_undefine.py

Add reliability test about define-start-destroy-undefine network for
1000 times.

Add reliability test about define-undefine network

---

libvirt/tests/cfg/virtual_network/iface_network.cfg
libvirt/tests/src/virtual_network/iface_network.py

Add test for forwarder check in network dnsmasq config file.

Add test for forwarder

---

libvirt/tests/src/virtual_disks/virtual_disks_luks.py

virtual_disks_luks: Fix typo of function name

---

libvirt/tests/src/virtual_network/iface_options.py

With the refactor to get default gateway in a single function, update
the function name as well.

Update the function name as it is changed in utils_net

---

v2v/tests/cfg/convert_from_file.cfg
v2v/tests/cfg/v2v_options.cfg
v2v/tests/src/convert_from_file.py
v2v/tests/src/convert_vm_to_libvirt.py
v2v/tests/src/convert_vm_to_ovirt.py
v2v/tests/src/function_test_esx.py
v2v/tests/src/function_test_xen.py
v2v/tests/src/specific_kvm.py

Add --mac support for v2v

---

v2v/tests/cfg/convert_vm_to_libvirt.cfg
v2v/tests/cfg/convert_vm_to_ovirt.cfg
v2v/tests/cfg/function_test_esx.cfg

1) Move sles cases from function to matrix testing
2) Add more guests to convert_vm_to_ovirt

Add more guests to v2v matrix testing

---

v2v/tests/cfg/specific_kvm.cfg

Add rhev output for "mem_alloc" case in specific_kvm job

---

libvirt/tests/src/virtual_device/input_devices.py

s390x doesn't support PS/2, USB bus types. Skip tests.
Extracted method to improve readability of test code.
Run tests:
```bash
JOB ID     : 88cc125549a512d2258d572679d120ec288c3629
JOB LOG    : /root/avocado/job-results/job-2019-10-18T09.20-88cc125/job.log
(1/1) type_specific.io-github-autotest-libvirt.virtual_devices.input_devices.positive_test.bus_type_ps2.input_type_mouse: CANCEL: bus types ps2, usb not supported on s390x (7.32 s)
RESULTS    : PASS 0 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 1
JOB TIME   : 10.55 s
JOB ID     : 5b2b97808bfa89884dd31abd11a4acedfe724dcf
JOB LOG    : /root/avocado/job-results/job-2019-10-18T09.20-5b2b978/job.log
(1/1) type_specific.io-github-autotest-libvirt.virtual_devices.input_devices.positive_test.bus_type_usb.input_type_keyboard: …
```

Skip input device bus types on s390x

---

libvirt/tests/cfg/virsh_cmd/volume/vol_concurrent.cfg

Increate volume size to give thread more time to make volume operation and shrink useless volume number
Signed-off-by: jgao12345 <jgao@redhat.com>

fix volume write error_test

---

libvirt/tests/src/virsh_cmd/domain/virsh_migrate_stress.py

`post_migration_check()` is moved to MigrationTest(), adopt the
changes in testcase and argument changes for `ping_vm()`.

virsh_migrate_stress: refactor code to adopt MigrationTest() API

---

libvirt/tests/src/virtio_transitional/virtio_transitional_blk.py

As for network interface it will report error as do not
update the source part

Remove update for iface type

---

libvirt/tests/cfg/cpu/vm_features.cfg
libvirt/tests/src/cpu/vm_features.py

This PR adds cpu pmu test - check if vm start up with
pmu enable/disable or not.
Depends on https://github.com/avocado-framework/avocado-vt/pull/2308

Add pmu tests

---

libvirt/tests/cfg/conf_file/qemu_conf/auto_dump.cfg
libvirt/tests/src/conf_file/qemu_conf/auto_dump.py

And make pseries cases only pseries

auto_dump:Use wait_for to wait until get pid

---

libvirt/tests/src/virsh_cmd/domain/virsh_dumpxml.py

On s390x virsh dumpxml --update-cpu can only be used to add host-model
features as required; match=minimum is not supported, s. https://github.com/libvirt/libvirt/blob/master/src/cpu/cpu_s390.c
1. Cancel test early when match=minimum
2. check_cpu: expect elements to not be updated for custom cpu model
Tests on s390x:
```bash
JOB ID     : 33965763941146953079934ffa81957c957df800
JOB LOG    : /root/avocado/job-results/job-2019-10-29T12.02-3396576/job.log
(01/12) type_specific.io-github-autotest-libvirt.virsh.dumpxml.normal_test.non_acl.vm_shutoff.with_cpu.minimum_match.domname: CANCEL: Minimum mode not supported on s390x (4.62 s)
(02/12) type_specific.io-github-autotest-libvirt.virsh.dumpxml.normal_test.non_acl.vm_shutoff.with_cpu.minimum_match.domuuid: CANCEL: Minimum mode not supported on …
```

Fix virsh_dumpxml on s390x

---

libvirt/tests/src/virsh_cmd/domain/virsh_attach_detach_interface.py

On s390x interfaces have address types ccw which don't allow for
rom tuning.
1. get_formatted_iface_dict:
a. Moved list creation to own function to
improve readability.
b. Add rom tuning only if guest is not s390x
2. logging.info/params_format:
a. Moved logging before and after calling function into function
to improve readability
Tests were run both on x86_64 and s390x, libvirt 4.5.0/qemu-kvm 2.12.0
x86_64:
```bash
JOB ID     : b2598690367eab841cbb19a01515e740990858b0
JOB LOG    : /root/avocado/job-results/job-2019-10-24T19.19-b259869/job.log
(1/1) type_specific.io-github-autotest-libvirt.virsh.attach_detach_interface.normal_test.vm_running.direct.at_detach_device.domname: PASS (30.12 s)
JOB TIME   : 31.72 …
```

Fix attach_interface on s390x

---

v2v/tests/src/convert_from_file.py

Fix dest_dir error in v2v convert_from_file job

---

libvirt/tests/src/virtual_device/video_devices.py

On s390x virtio video devices are always translated to virtio-gpu-ccw
```bash
JOB ID     : 41678a0f37b76444b13a0d9c7fa7b1da9952362a
JOB LOG    : /root/avocado/job-results/job-2019-10-30T11.10-41678a0/job.log
(1/3) type_specific.io-github-autotest-libvirt.virtual_devices.video_devices.positive_test.primary_video.virtio.secondary_video.virtio.model_test: PASS (6.11 s)
(2/3) type_specific.io-github-autotest-libvirt.virtual_devices.video_devices.positive_test.primary_video.virtio.secondary_video.virtio.heads_test.default_heads: PASS (6.65 s)
(3/3) type_specific.io-github-autotest-libvirt.virtual_devices.video_devices.positive_test.primary_video.virtio.secondary_video.virtio.heads_test.specified_heads: PASS (5.72 s)
RESULTS    : PASS 3 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | …
```

Fix video_devices on s390x

---

provider/v2v_vmcheck_helper.py

Remove 'L' suffix for python2 long int value

---

libvirt/tests/cfg/cpu/vcpu_misc.cfg
libvirt/tests/src/cpu/vcpu_misc.py

This PR covers test to check if snapshot func works well for vm
with host-mode cpu mode.

Add test for cpu snapshot

---

libvirt/tests/cfg/backingchain/blockcommand.cfg
libvirt/tests/src/backingchain/blockcommand.py

- when guest image with "file" disk has "block" backing file
- when guest image with "file" disk has "gluster" backing file
- when guest image with "block" disk has "block" backing file

Add blockpull/blockcommit cases

---

v2v/tests/cfg/function_test_esx.cfg

Signed-off-by: liuzi <zili@redhat.com>

fix failed v2v function test case

---

v2v/tests/cfg/convert_vm_to_libvirt.cfg
v2v/tests/cfg/convert_vm_to_ovirt.cfg

Adjuest case name and guest version for v2v matrix testing

---

v2v/tests/src/convert_from_file.py

Fix coye failure when destination directory already exists

---

v2v/tests/cfg/convert_vm_to_ovirt.cfg
v2v/tests/cfg/function_test_xen.cfg

Fix wrong usage of value change by filter

---

libvirt/tests/cfg/graphics/graphics_functional.cfg
libvirt/tests/src/graphics/graphics_functional.py

graphics_functional: Add cases for clipboard

---

libvirt/tests/cfg/graphics/graphics_functional.cfg
libvirt/tests/src/graphics/graphics_functional.py

graphics_functional: Add cases for filetransfer

---

libvirt/tests/cfg/graphics/graphics_functional.cfg
libvirt/tests/src/graphics/graphics_functional.py

graphics_functional: Add case for streaming

---

libvirt/tests/src/virsh_cmd/domain/virsh_setmem.py

Some vm's dmidecode will return memory size in 'MB' but others
using 'GB'. The original code only deal with 'MB', this will cause
case failures if vm using 'GB' or 'KB'.

Fix a memory size issue in setmem cases

---

libvirt/tests/cfg/virsh_cmd/domain/virsh_sendkey.cfg
libvirt/tests/src/virsh_cmd/domain/virsh_sendkey.py

1. Add crash test
2. Add qnum codeset test

Add test for sendkey

---

libvirt/tests/cfg/virsh_cmd/pool/virsh_pool.cfg
libvirt/tests/src/virsh_cmd/pool/virsh_pool.py

update the matrix and the test content with new virsh cmd option protocol_ver

update test case for netfs pool with new cmd protocol_ver

---

libvirt/tests/cfg/virtio_transitional/virtio_transitional_nic.cfg
libvirt/tests/src/virtio_transitional/virtio_transitional_nic.py

virtio_transitional: Add test case for virtio nic device

---

libvirt/tests/src/migration/migrate_vm.py

The test defines an iscsi target as shared storage for guest image. The guest couldn't be started because the fileio didn't contain the guest image.
Proposal: Add test image to emulated-iscsi.
1. import data_dir:
a. use data_dir to make vm image available on shared
iscsi storage
2. get_virtual_size:
a. get the virtual image size
b. use expression e.g. "10G" because byte precision from
image_info_dict["vsize"] led to disk out of space exception
during libvirt.setup_or_cleanup_iscsi
3. redefine_vm_with_iscsi_target:
a. extract method for readability
4. update_host_ip:
a. extract method for readability
5. create_image_on_iscsi:
a. new method to create the vm image on the shared iscsi storage
6. gluster_disk:
a. move definition to top to avoid cleanup to fail if iscsi_setup
fails
7. fixed …

Fix ipv6 iscsi live migration

---

v2v/tests/cfg/function_test_esx.cfg
v2v/tests/src/function_test_esx.py

Add new case for qemu-guet-agent

---

libvirt/tests/cfg/virtio_transitional/virtio_transitional_blk_negative.cfg
libvirt/tests/src/virtio_transitional/virtio_transitional_blk_negative.py

Boot rhel6 guest with unexpected model for disk and scsi controller

virtio_transitional: Negative test for block device

---

libvirt/tests/src/migration/migrate_options_shared.py
libvirt/tests/src/virsh_cmd/domain/virsh_migrate_vm_cfg.py

migrate_options_shared, virsh_migrate_stress, virsh_migrate_vm_cfg: Made changes w.r.t "check_vm_state".

migrate_options_shared, virsh_migrate_stress, virsh_migrate_vm_cfg: Made changes w.r.t "check_vm_state".

---

libvirt/tests/cfg/graphics/graphics_functional.cfg
libvirt/tests/src/graphics/graphics_functional.py

graphics_functional: Add cases for defaultMode

---

libvirt/tests/src/virsh_cmd/domain/virsh_blkiotune.py

If I/O scheduler is e.g. bfq blkio device weights are not supported
and virsh will return an error:
https://github.com/libvirt/libvirt/commit/7e8a1a6e21cee67f6fa5bd2126ec17f96e5857d6
https://github.com/libvirt/libvirt/commit/035ebe9390a630964f391816f05c9cc7792212ad
The test now passes logging expected error message.
Test run:
JOB ID     : 66b7b57011e52ff8a2968d9ddbad5fba3538800d
JOB LOG    : /root/avocado/job-results/job-2019-09-27T18.33-66b7b57/job.log
(01/76) type_specific.io-github-autotest-libvirt.virsh.blkiotune.positive.get_blkio_parameter.running_guest.options.none: PASS (6.64 s)
(02/76) type_specific.io-github-autotest-libvirt.virsh.blkiotune.positive.get_blkio_parameter.running_guest.options.live: PASS (6.32 s)
(03/76) type_specific.io-github-autotest-libvirt.virsh.blkiotune.posit …

Fix test expectation if I/O scheduler is not cfq

---

libvirt/tests/src/virsh_cmd/domain/virsh_domiftune.py

In case test can't continue after crash

domiftune: Add detection of crash after command executed

---

libvirt/tests/src/libvirt_qemu_cmdline.py

The failure is caused by the qemu cmd line for pv_eoi hyper_features
with disable/enable has changed from -/+ to off/on

Fix failure for pv_eoi hyper_features since RHEL-8.1

---

libvirt/tests/cfg/virsh_cmd/domain/virsh_save_image_edit.cfg
libvirt/tests/src/virsh_cmd/domain/virsh_save_image_edit.py

1. Add no_option test and add xml back/recover step
2. Also update cfg format for save-image-define

Add no_option test for save-image-edit

---

provider/v2v_vmcheck_helper.py

Virtio RNG supports from kernel-2.6.26, check the kernel version of
VM before add RNG checkpoint.
Reference:
[1] https://wiki.qemu.org/Features/VirtIORNG

Add kernel checking for RNG checkpoint

---

libvirt/tests/cfg/virsh_cmd/domain/virsh_detach_device_alias.cfg
libvirt/tests/src/virsh_cmd/domain/virsh_detach_device_alias.py

Add detach-device-alias test for hostdev,controller,redirdev and channel

---

libvirt/tests/cfg/virsh_cmd/domain/virsh_attach_detach_disk.cfg
libvirt/tests/src/virsh_cmd/domain/virsh_attach_detach_disk.py

Attach one disk, then change its systemlink,then reattach,
it should succeed.

Add case to cover: attach disk with systemlink change

---

libvirt/tests/src/virsh_cmd/domain/virsh_blockcommit.py

This is due to bz1741456. When image has xattr left after vm
destroyed, vm cannot be started anymore until we clear these
xattrs. This will block all followed up cases when happened.
This commit is to report the error and clear the xattr within
the problematic case, not blocking followed up cases.

Avoid xattr left on image blocking all followed up cases

---

libvirt/tests/cfg/migration/migrate_options_shared.cfg
libvirt/tests/src/migration/migrate_options_shared.py

This PR adds 4 migration cases with different vcpu number.

migration: add cases to test migration with 1-16 VCPUs

---

libvirt/tests/cfg/libvirt_pci_passthrough.cfg
libvirt/tests/src/libvirt_pci_passthrough.py

Implemented the Guest Lifecycle (Shutdown, Start, Suspend, Resume) with device pass-through.
The guest life-cycle can be achieved for the desired iterations along with device pass-through.

Implemented the Guest Lifecycle (Shutdown, Start, Suspend, Resume) with device pass-through.

---

libvirt/tests/src/virsh_cmd/domain/virsh_reboot.py

In the test of reboot testing, only check the guest
is running can not prove that the guest is been rebooted.
Since the guest may never shutdown, i.e., the guest
never responds to the reboot operation. Then the guest
still would be in running state.
Now, we add a checkpoint of checking guest boot up time.
The boot up time after reboot operation greater than
that before reboot make sure the guest been rebooted
successfully indeed.

[virsh.reboot]Fix the checkpoint of virsh reboot cases

---

libvirt/tests/cfg/libvirt_cputune.cfg
libvirt/tests/src/libvirt_cputune.py

Add test cases about memtune and cachetune in domain xml

---

libvirt/tests/cfg/virsh_cmd/domain/virsh_schedinfo_qemu_posix.cfg
libvirt/tests/src/virsh_cmd/domain/virsh_schedinfo_qemu_posix.py

1. Add multiple set at one time
2. Add readonly mode
3. Add --current info show
4. Add shutdown guest testing

Add test for schedinfo

---

libvirt/tests/cfg/virsh_cmd/domain/virsh_restore.cfg
libvirt/tests/src/virsh_cmd/domain/virsh_restore.py

Add --xml test for restore

---

libvirt/tests/src/libvirt_rng.py

On s390x qemu device for rng is virtio-rng-ccw.
1. run:
a. Get guest arch early to determine expected device model in qemu cmd.
b. Add new key "rng_device" to test params (for single and multiple rng cases).
2. get_rng_device:
a. Return the expected rng device in qemu cmd
b. Only known models are virtio, virtio-transitional, virtio-non-transitional.
3. check_qemu_cmd:
a. Use new test param "rng_device" to build expression for qemu cmdline check.
```bash
JOB ID     : 28427e386011fca5d703e81d193787866919692e
JOB LOG    : /root/avocado/job-results/job-2019-11-21T12.31-28427e3/job.log
(1/4) type_specific.io-github-autotest-libvirt.libvirt_rng.backend_tcp: PASS (89.24 s)
(2/4) type_specific.io-github-autotest-libvirt.libvirt_rng.rng_rate.back_tcp: PASS (78.21 s)
(3/4) …
```

Fix libvirt_rng on s390x

---

libvirt/tests/src/virtual_network/iface_options.py

1. iface_options.cfg: Use iface_model "virtio" which is available on all platforms.
2. iface_options.py:
a. host_arch: Use host architecture info to set expected command line option
b. pci in model_option: vectors argument only valid for PCI
```bash
JOB ID     : 4d5f4b1dcf56537f6b6011ff53f64eab3082503a
JOB LOG    : /root/avocado/job-results/job-2019-12-17T12.36-4d5f4b1/job.log
(01/15) type_specific.io-github-autotest-libvirt.virtual_network.iface_options.iface_source_default: PASS (113.23 s)
(02/15) type_specific.io-github-autotest-libvirt.virtual_network.iface_options.iface_driver.driver_txmode_iothread: PASS (60.73 s)
(03/15) type_specific.io-github-autotest-libvirt.virtual_network.iface_options.iface_driver.driver_txmode_timer: PASS (74.40 s)
(04/15) …
```

Fix iface_options on s390x

---

libvirt/tests/cfg/virsh_cmd/monitor/virsh_domblkinfo.cfg
libvirt/tests/src/virsh_cmd/monitor/virsh_domblkinfo.py

--all and --human are new options added to virsh domblkinfo
and related output format need to be checked

add --all and --human cases into virsh domblkinfo

---

libvirt/tests/cfg/libvirt_mem.cfg
libvirt/tests/src/libvirt_mem.py

Add memory discard related test cases

---

libvirt/tests/cfg/virsh_cmd/host/virsh_uri.cfg
libvirt/tests/src/virsh_cmd/host/virsh_uri.py

1. Add invalid uri test
2. Add non_root_user test

Add test for uri test

---

libvirt/tests/src/virtual_disks/virtual_disks_encryption.py

In some case, dirty secret and volume will lead to next case execution failure
The way to fix them is to clean up dirty secret and volumes if they have

Add secret and volume cleanup before testing started

---

libvirt/tests/cfg/libvirt_mem.cfg
libvirt/tests/cfg/libvirt_rng.cfg
libvirt/tests/cfg/virsh_cmd/domain/virsh_detach_device.cfg
libvirt/tests/src/libvirt_mem.py
libvirt/tests/src/libvirt_rng.py
libvirt/tests/src/virsh_cmd/domain/virsh_detach_device.py

depends on 
https://github.com/avocado-framework/avocado-vt/pull/1724 
https://github.com/avocado-framework/avocado-vt/pull/1723 
https://github.com/avocado-framework/avocado-vt/pull/1722
Above all merged
new depends on
https://github.com/avocado-framework/avocado-vt/pull/2222
Also merged

Detach alias test for memory, disk, interface and rng device

---

libvirt/tests/cfg/virsh_cmd/volume/virsh_vol_download_upload.cfg
libvirt/tests/src/virsh_cmd/volume/virsh_vol_download_upload.py

with sparse option, the upload or downloaded image size is much lesser than virtual size

add vol upload and download case with sparse option

---

libvirt/tests/src/migration/migrate_vm.py

Inconsistency on the variable image_size. This variable should be a string rather than a number.

fixed type error: Added letter 'G' to image_size

---

libvirt/tests/cfg/backingchain/blockcopy.cfg
libvirt/tests/src/backingchain/blockcopy.py

- with option 'reuse-external'

Add blockcopy cases

---

libvirt/tests/cfg/cpu/vcpu_misc.cfg
libvirt/tests/src/cpu/vcpu_misc.py

These cases check vcpu configuration with topology limit via
cmd 'virsh edit'.

Add case to check maximum vcpus number with topology limit

---

libvirt/tests/cfg/virtio_transitional/virtio_transitional_vsock.cfg
libvirt/tests/src/virtio_transitional/virtio_transitional_base.py
libvirt/tests/src/virtio_transitional/virtio_transitional_vsock.py

Depends on https://github.com/avocado-framework/avocado-vt/pull/2310 and https://github.com/avocado-framework/avocado-vt/pull/2311

Virtio_transitional: Add test cases for vsock device

---

libvirt/tests/src/libvirt_mem.py

Increase the consumed memory for testing memory binding

---

libvirt/tests/cfg/virtual_disks/virtual_disks_luks.cfg
libvirt/tests/src/virtual_disks/virtual_disks_luks.py

Validate luks is working on volume created on dir base pool.

add test cases to cover luks on dir_based pool

---

libvirt/tests/cfg/libvirt_rng.cfg
libvirt/tests/src/libvirt_rng.py

Add hotplug/unplug test for rng_device for backend rdm,tcp,udp

---

libvirt/tests/cfg/virtio_transitional/virtio_transitional_serial.cfg
libvirt/tests/src/virtio_transitional/virtio_transitional_serial.py

virtio_transitional: Add test case for virtio-serial

---

libvirt/tests/cfg/virtio_transitional/virtio_transitional_rng.cfg
libvirt/tests/src/virtio_transitional/virtio_transitional_rng.py

virtio_transitional: Add test case for device rng

---

libvirt/tests/cfg/virtio_transitional/virtio_transitional_mem_balloon.cfg
libvirt/tests/src/virtio_transitional/virtio_transitional_mem_balloon.py

virtio_transitional: Add test cases for memory balloon

---

libvirt/tests/cfg/virtio_transitional/virtio_transitional_mem_balloon.cfg
libvirt/tests/src/virtio_transitional/virtio_transitional_mem_balloon.py

Refer to https://github.com/autotest/tp-libvirt/pull/2443 comments

Update for the comments in previous review for transitional memory balloon test

---

v2v/tests/cfg/function_test_esx.cfg

Update guest for case device_map and esx_snapshot

---

provider/v2v_vmcheck_helper.py
v2v/tests/src/convert_from_file.py
v2v/tests/src/convert_vm_to_libvirt.py
v2v/tests/src/convert_vm_to_ovirt.py
v2v/tests/src/function_test_esx.py
v2v/tests/src/function_test_xen.py
v2v/tests/src/specific_kvm.py
v2v/tests/src/v2v_options.py

Debug xen problems

---

libvirt/tests/cfg/migration/migrate_vm.cfg

Add detailed error information to check proper error message.

update error message for migration test with non-exist xml

---

libvirt/tests/src/virtual_disks/virtual_disks_multipath.py

Tests failed with 'No newly added multipath devices found.' because
The service restart takes some time.
Add 'wait_for', starting after 0.5 sec, for at most 60 sec, to avoid
early false failure.
Test run:
```bash
JOB ID     : 172d5a7d5b6ea1586622f8b029943d966f8a7e06
JOB LOG    : /root/avocado/job-results/job-2020-01-21T12.20-172d5a7/job.log
(1/1) type_specific.io-github-autotest-libvirt.virtual_disks.multipath.rawio_yes.sgio_filtered.coldplug: PASS (170.89 s)
JOB TIME   : 174.81 s
```

Fix virtual_disk multipath

---

libvirt/tests/cfg/cpu/vm_features.cfg

pmu is not supported by pseries

---

libvirt/tests/cfg/migration/migrate_ceph.cfg
libvirt/tests/src/migration/migrate_ceph.py

For enable auth in ceph disk, it need setup the secret uuid in client and server host

add ceph VM migration cases with auth

---

libvirt/tests/src/virtual_network/iface_options.py

This PR requires https://github.com/avocado-framework/avocado-vt/pull/2329
1. del_seclabel:
a. If original domain xml had dac security driver the test will fail
for unprivileged user because dac is not available in this case.
The test now removes the dac security driver from the domain.xml
of unprivileged user. This is what a real user would have to do,
too.
2. virsh.remove_domain:
a. Removed extra option as in this case it doesn't remove the image
because the image is created below /tmp and not registered as volume.
b. Remove test image but emit warning if there was an issue.
3. fixed regex as required by inspektor
Test run on s390x with <seclabel model='dac'.../> in domain.xml:
```bash
JOB ID     : 29fedc5c7ad8f88c04485ffcd0d761769ebd608c
JOB LOG    : …
```

Fix iface_options unprivileged

---

libvirt/tests/cfg/virsh_cmd/domain/virsh_numatune.cfg
libvirt/tests/src/virsh_cmd/domain/virsh_numatune.py

Add negative test for numatune

---

provider/v2v_vmcheck_helper.py
v2v/tests/src/specific_kvm.py

Fix has no attribute virsh_instance error

---

libvirt/tests/src/virsh_cmd/domain/virsh_migrate_stress.py

Fix syntax error

---

provider/v2v_vmcheck_helper.py

Fix potential failure for v2v

---

libvirt/tests/src/cpu/vcpu_affinity.py

To avoid influence on test results

Clean up topology/numatune settings in certain test cases

---

libvirt/tests/cfg/virsh_cmd/domain/virsh_sendkey.cfg
libvirt/tests/src/virsh_cmd/domain/virsh_sendkey.py

Add holdtime test for sendkey

---

tp-libvirt_review_comment_summary.rst

1. Define best practice to work with timeouts
2. Minor formatting update

Update review doc

---

v2v/tests/cfg/convert_from_file.cfg
v2v/tests/src/convert_from_file.py

Add a variant to control v2v debug printing

---

v2v/tests/cfg/function_test_esx.cfg
v2v/tests/cfg/v2v_options.cfg
v2v/tests/src/v2v_options.py

[V2V] Add two negative cases for bz1759441

---

libvirt/tests/src/virsh_cmd/domain/virsh_numatune.py

Fix failure for numa test

---

libvirt/tests/src/migration/migrate_vm.py

The error is "TestError: Image size provided is not in valid format,
specify proper units [K|M|G".
setup_or_cleanup_iscsi call iscsi.py which needs image size is ended
with an unit. So this fix is to provide a virtual size with an unit.

Fix qemu-img error

---

libvirt/tests/src/conf_file/qemu_conf/set_virtlogd.py

set_virtlog: Update match message

---

v2v/tests/cfg/convert_vm_to_libvirt.cfg
v2v/tests/cfg/convert_vm_to_ovirt.cfg
v2v/tests/cfg/function_test_esx.cfg
v2v/tests/cfg/function_test_xen.cfg
v2v/tests/cfg/specific_kvm.cfg
v2v/tests/src/convert_vm_to_libvirt.py
v2v/tests/src/convert_vm_to_ovirt.py
v2v/tests/src/function_test_esx.py
v2v/tests/src/function_test_xen.py
v2v/tests/src/specific_kvm.py

Add a v2v_debug switch to control the debug logs of v2v commands

---

libvirt/tests/src/virtio_transitional/virtio_transitional_blk_negative.py

There were several issues in this scripts:
1. only update blk_source_name if the disk images is downloaded
2. incorrect exception
3. error when getting output from console

Fix some issues in virtio_transitional negative tests

---

libvirt/tests/src/migration/migrate_ceph.py
libvirt/tests/src/migration/migrate_gluster.py
libvirt/tests/src/migration/migrate_options_shared.py
libvirt/tests/src/migration/migrate_vm.py
libvirt/tests/src/migration/migrate_with_legacy_guest.py
libvirt/tests/src/virsh_cmd/domain/virsh_migrate.py

Remove methods of 52lts compatiblitylayer from migration scripts

---

libvirt/tests/src/virtio_transitional/virtio_transitional_nic.py

Network was unreachable after interface  detached in some cases.
So fix it in PR.

Fix network issue in virtio transitional model case

---

libvirt/tests/src/migration/migrate_ceph.py

add install ceph-common on remote migration host

---

libvirt/tests/src/virtual_disks/virtual_disks_gluster.py

skip gluster transport protocol 'rdma' case

---

libvirt/tests/src/virtual_disks/virtual_disks_ceph.py

Fix ceph check qemu command failures due to blockdev introduction

---

provider/v2v_vmcheck_helper.py
v2v/tests/src/convert_from_file.py
v2v/tests/src/convert_vm_to_ovirt.py
v2v/tests/src/function_test_esx.py
v2v/tests/src/function_test_xen.py
v2v/tests/src/specific_kvm.py
v2v/tests/src/v2v_options.py

Remove 52lts compatiblity layer in v2v

---

libvirt/tests/src/virsh_cmd/domain/virsh_cpu_compare.py

It should report more proper error if VM is failed to start.

Update to check if VM is started before getting vm id

---

v2v/tests/cfg/specific_kvm.cfg
v2v/tests/src/specific_kvm.py

Force open v2v_debug for the cases requries '-v -x'

---

provider/v2v_vmcheck_helper.py
v2v/tests/cfg/function_test_esx.cfg
v2v/tests/src/convert_from_file.py
v2v/tests/src/convert_vm_to_libvirt.py
v2v/tests/src/convert_vm_to_ovirt.py
v2v/tests/src/function_test_esx.py
v2v/tests/src/function_test_xen.py
v2v/tests/src/specific_kvm.py

Add a series of cases for --no-copy of v2v

---

libvirt/tests/src/virsh_cmd/domain/virsh_domiftune.py

1. Restart service only if `libvirtd` crashed: the original code created a race
condition where the restart happened while the test also tried to log into
the guest on serial console for dmesg verification; this caused the console
to be disconnected. The login never succeeded but timed out and dmesg could
not be verified.
Don't catch exception from `start`: if this fails all other test steps won't
be executed correctly, so letting error pass at this point will avoid late
test failure.
2. `check_libvirtd`: create method to check and handle if `libvirtd` crashed.
Use the same error message because test name already determines which case
was run.
3. Move service restart to crash checker: the restart is only necessary
if later code requires it to be running, e.g. when reestablishing
the …

Fix domiftune teardown

---

libvirt/tests/src/virsh_cmd/domain/virsh_cpu_stats.py
libvirt/tests/src/virsh_cmd/domain/virsh_schedinfo_qemu_posix.py

It's more helpful if the correct error message is reported.

Update to report more proper error messages

---

libvirt/tests/src/virtual_disks/virtual_disks_multidisks.py

After blockdev introduced, copy-on-read=off option will get nothing output
from qemu command output, and copy-on-read=on will get json format output

Fix virtual disk failure in copy-on-read

---

libvirt/tests/src/virtual_disks/virtual_disks_nbd.py

Remove unnecessary save operation

Fix nbd backend save and restore failures

---

libvirt/tests/src/migration/migrate_vm.py

Updates according to https://github.com/avocado-framework/avocado-vt/pull/2495

Fix io_throttling for migration

---

libvirt/tests/src/cpu/powerpc_hmi.py
libvirt/tests/src/daemon/kill_started.py
libvirt/tests/src/guest_resource_control/control_cgroup.py
libvirt/tests/src/libvirt_cputune.py
libvirt/tests/src/libvirt_pci_passthrough_hotplug.py

Remove 52TLS dependance

---

libvirt/tests/src/virtual_disks/virtual_disks_multidisks.py

Add sleep a few seconds between two continuous detach device operations

---

v2v/tests/cfg/v2v_options.cfg

Add version check before running the cases of print-estimate

---

libvirt/tests/src/migration/migrate_options_shared.py

Hpt cases should only run on Power8

---

libvirt/tests/src/virtual_disks/virtual_disks_luks.py

Previous case may leave dirty file in ceph server,
add pre clean up before case is exectuing actually.

Fix file alreadly exists issue in luks

---

libvirt/tests/cfg/virtual_disks/virtual_disks_luks.cfg
libvirt/tests/src/virtual_disks/virtual_disks_luks.py

Move clean up operation to aligh with whole ceph backend testing

Fix clean up dirty file under disable auth

---

libvirt/tests/cfg/virsh_cmd/domain/virsh_blkdeviotune.cfg
libvirt/tests/src/virsh_cmd/domain/virsh_blkdeviotune.py

1. Hotplug disk with iotune setting and check blkdeviotune values
2. Start guest with/without alias and iotune and different disk types

Add cases for blkdeviotune

---

libvirt/tests/cfg/virtual_disks/virtual_disks_multidisks.cfg

Add one controller with multifunction on to allow more pci slots available

Fix no more available PCI slots issue

---

libvirt/tests/src/virsh_cmd/domain/virsh_domxml_to_native.py

virsh.domxml_to_native outputs as below:
-blockdev '{"driver":"file",...,"discard":"unmap"}'
But qemu command line is like below:
-blockdev {"driver":"file",...,"discard":"unmap"}
Old script compared them directly, so it failed.
Now we have to handle the additional single quote before comparing them.

Fix -blockdev inconsistency

---

libvirt/tests/src/virtual_network/mtu.py

Fix the pkg install waiting for openvswitch

---

libvirt/tests/src/virtual_disks/virtual_disks_multidisks.py

Extend certain waiting time by utils_misc.wait_for

Fix virtio_disk_hot_unplug_event_watch case

---

libvirt/tests/src/virsh_cmd/domain/virsh_change_media.py

Prevous cases use one iso file as block device, but after block-dev introduced
one error will be thrown with:
unable to execute QEMU command 'blockdev-add': 'host_device' driver expects either a character or block device
In order to fix this issue, create one iSCSI block to replace previous ISO file.

Fix change media cases failures

---

libvirt/tests/src/virsh_cmd/domain/virsh_restore.py

This is to fix the error when exexcuting virsh.restore
error: Failed to open file '/var/tmp/xxx.xml': Permission denied
The root cause is the un-priveledge user has no access to xxx.xml.

Fix restore permission deny

---

libvirt/tests/src/conf_file/libvirtd_conf/unix_sock.py

Modify the default perms of socket file after 5.6.0

---

libvirt/tests/src/daemon/kill_starting.py

Restart libvirtd.socket after starting libvirtd foreground

---

libvirt/tests/cfg/virtual_network/iface_options.cfg
libvirt/tests/src/virtual_network/iface_options.py

depends on https://github.com/avocado-framework/avocado-vt/pull/2028

Add test for vhostuser+dpdk

---

libvirt/tests/src/virsh_cmd/domain/virsh_attach_detach_interface.py

1. add pcie-to-pci-bridge for rtl8139 model
2. add missing vm_pause scenario

Fix attach-detach-interface failure

---

libvirt/tests/cfg/migration/migrate_options_shared.cfg

Error message has been updated.

Update error message for migration with disable keepalive case

---

libvirt/tests/src/graphics/graphics_functional.py

The expected result is define guest failed with following error:
"... TLS is disabled ..."

graphics_functional: Fix spice_tls_disabled_tlsport_set failure

---

libvirt/tests/src/virsh_cmd/domain/virsh_blockcommit.py

It's caused by new feature - add index for the active
layer in disk chain.

Correct index for blockcommit.top_inactive test

---

libvirt/tests/src/migration/migrate_vm.py

Update to clean up vm on detination before migration.

migration: Fix destination vm is already active issue

---

v2v/tests/cfg/function_test_esx.cfg
v2v/tests/src/function_test_esx.py

Add scenario 'check resume info in rhel6' for v2v case134430

---

libvirt/tests/src/migration/migrate_options_shared.py

This PR fixes 2 issues:
1. the checking of destination domstate eliminated
2. destination vm needs some time to be in running status

Fix migration domstate checking case

---

libvirt/tests/cfg/graphics/graphics_functional.cfg
libvirt/tests/src/graphics/graphics_functional.py

Start a guest with graphic listening to ipv6 network.

graphic_functional: Add ipv6 network test

---

libvirt/tests/src/virtual_network/iface_options.py

1. move the log place
2. change all destory to gracefully

Fix the failure of mcast

---

libvirt/tests/src/migration/migrate_gluster.py

It did not set postcopy in previous code, update to
run virsh.migrate_postcopy for postcopy migration.
BTW, also update to use common checks in libvirt.MigrationTest.

migration: correct postcopy operation in migrate_gluster

---

libvirt/tests/src/nwfilter/nwfilter_vm_start.py

match destination could be ipaddress or hostname by iptables -L

Fix nwfilter vm start case failure

---

v2v/tests/cfg/function_test_esx.cfg

Automate v2v case175071

---

libvirt/tests/cfg/virtual_device/tpm_device.cfg
libvirt/tests/src/virtual_device/tpm_device.py

Add vtpm test, which backend type is 'emulator'.

tpm_dev: vtpm auto

---

libvirt/tests/src/virsh_cmd/domain/virsh_attach_detach_interface.py
libvirt/tests/src/virsh_cmd/domain/virsh_detach_device_alias.py
libvirt/tests/src/virtio_transitional/virtio_transitional_base.py
libvirt/tests/src/virtio_transitional/virtio_transitional_blk.py
libvirt/tests/src/virtio_transitional/virtio_transitional_nic.py
libvirt/tests/src/virtio_transitional/virtio_transitional_rng.py
libvirt/tests/src/virtio_transitional/virtio_transitional_serial.py
libvirt/tests/src/virtio_transitional/virtio_transitional_vsock.py

Update according to https://github.com/avocado-framework/avocado-vt/pull/2479

Update usage of contr create func

---

libvirt/tests/src/graphics/graphics_functional.py

graphics_functional: Fix ipv6 address compressed issue

---

libvirt/tests/cfg/virsh_cmd/domain/virsh_define.cfg
libvirt/tests/src/virsh_cmd/domain/virsh_define.py

These cases are trully the cases for defining vms
from xml

Add the cases of virsh define

---

libvirt/tests/src/libvirt_hooks.py

libvirt_hooks: Update network hooks message

---

v2v/tests/cfg/function_test_esx.cfg
v2v/tests/src/function_test_esx.py

Automated virt-v2v testcase RHEL-172941:Convert a ubuntu guest with open-vm-tools vmware-tools and ubuntu-server installed
Signed-off-by: Zi Liu <zili@redhat.com>

Add virt-v2v new testcase for ubuntu open-vm-tools

---

libvirt/tests/src/daemon/crash_regression.py

Remove socket file to avoid libvirtd autostart by virsh connection

---

libvirt/tests/src/guest_resource_control/control_cgroup.py

Fix wrongly used 'test.fail'

---

libvirt/tests/src/virsh_cmd/volume/virsh_vol_download_upload.py

The data is too small to test, so expand the size to 200M.

Fix sparse volume download/upload case

---

libvirt/tests/src/virtual_network/iface_ovs.py

Add check for cmd exists or not for ovs-vsctl

---

libvirt/tests/src/virsh_cmd/domain/virsh_attach_device.py

Add more controllers into VM before do quite a few block device attach operation
And the change only applys small part of scenarios to avoid bring unnecessary regression

Fix no more pc slots issue in attach block device

---

libvirt/tests/src/virtio_transitional/virtio_transitional_blk.py

It does not return True even the images downloaded correctly in
previous code. Fix it in this PR.

virtio_transitional_blk: download images via download.get_file

---

libvirt/tests/src/virsh_cmd/domain/virsh_attach_detach_disk.py

Add wait time until match string is found on log file or timeout exit

Fix detach disk test audit check failure

---

libvirt/tests/cfg/virt_admin/management/virt_admin_server_clients_set.cfg
libvirt/tests/src/virt_admin/management/virt_admin_server_clients_set.py

(1)Refactor the code to increase its extensibility
(2)Add some cases server_clients_set

Add some cases of server_clients_set of virt_admin

---

v2v/tests/cfg/function_test_esx.cfg

Create new guest for v2v case 'migrated_vm'

---

libvirt/tests/src/virsh_cmd/domain/virsh_sendkey.py

virsh_sendkey: Add check for rsyslog restart

---

libvirt/tests/src/virsh_cmd/volume/virsh_vol_download_upload.py

Fix incorrect error message in virsh_vol_download_upload

---

libvirt/tests/cfg/usb_device.cfg

add some scenarios for pc machine type

update the usb_device cfg file

---

v2v/tests/src/specific_kvm.py

1) If machine is pc-q35-rhel8, cancel the test
2) Format adjustment

Fix isa-fdc is not supported error with pc-q35-rhel8

---

libvirt/tests/src/virsh_cmd/domain/virsh_attach_device.py

Need add controller prefix for any given parameter in controller creation

Fix controller key parameter issue

---

provider/v2v_vmcheck_helper.py

When convert a latest version os guest on a lower v2v server host,
the libosinfo may don't have the short_id of the converted guest.
e.g. Convert a rhel8.2 guest on a rhel8.0 host. In this case, we
can guess the expected long id based on the general rule of libosinfo
by short_id, and compare it with the real long id in guest's xml.

Do not fail if libosinfo doesn't have expected short_id of guest

---

v2v/tests/cfg/function_test_esx.cfg
v2v/tests/cfg/v2v_options.cfg
v2v/tests/src/function_test_esx.py

1) Add cases for bz1791240
2) Remove obsolete cases(v2v_options..custom).

Add new cases for rhv-cafile optional function

---

v2v/tests/cfg/pyvmomi/query_changed_disk_areas.cfg
v2v/tests/src/pyvmomi/query_changed_disk_areas.py

Add a case for python-pyvmomi

---

v2v/tests/cfg/libnbd/libnbd.cfg
v2v/tests/cfg/libnbd/nbdfuse.cfg
v2v/tests/src/libnbd/libnbd.py
v2v/tests/src/libnbd/nbdfuse.py

Add some libnbd cases for v2v

---

libvirt/tests/cfg/virtual_disks/virtual_disks_ceph.cfg
libvirt/tests/src/virtual_disks/virtual_disks_ceph.py

This feature is supported with libvirt version 6.0.0 afterwards

Add blockcopy rbd backend cases

---

libvirt/tests/src/usb_device.py

the usb hub device in host should not be passthroughed to vm
Signed-off-by: jil <jil@redhat.com>

filter out usb hub device in usb device test

---

libvirt/tests/src/bios/virsh_boot.py

virsh_boot: fix console output issue

---

libvirt/tests/cfg/controller/pcibridge.cfg

Update error message in pcibridge.cfg

Update error message in pcibridge.cfg

---

libvirt/tests/cfg/npiv/npiv_image_from_pool.cfg
libvirt/tests/cfg/npiv/npiv_nodedev_create_destroy.cfg
libvirt/tests/cfg/npiv/npiv_pool_vol.cfg
libvirt/tests/cfg/npiv/npiv_snapshot.cfg
libvirt/tests/cfg/npiv/npiv_virtual_disk.cfg

Signed-off-by: jgao <jgao@localhost.localdomain>

Modify the wwnn number since the changes from IT

---

libvirt/tests/src/virsh_cmd/domain/virsh_attach_detach_disk.py

All more PCI controllers to allow attach multiple disk devices

Fix attach disk no more pci slots issue

---

libvirt/tests/src/conf_file/sysconfig_libvirt_guests/libvirt_guests.py

We need the vm to do future testing.

Do not ignore status when doing vm clone

---

libvirt/tests/cfg/libvirt_cputune.cfg

Remove unsupported cases from pseries

---

libvirt/tests/cfg/virsh_cmd/domain/virsh_sendkey.cfg
libvirt/tests/src/virsh_cmd/domain/virsh_sendkey.py

Set panic_model to 'pseries' for ppc tests

---

libvirt/tests/src/libvirt_cputune.py

Fix the return code of find func issue

---

libvirt/tests/src/virtual_disks/virtual_disks_multidisks.py

Keep up-to-dated minimal VM xml

Sync up minimal VM xml

---

libvirt/tests/src/virsh_cmd/domain/virsh_event.py

On ppc machines, detach interface will cost more time. If doing
attach before detach fully completed, then 'add' will be in front
of 'remove' in the later virsh event output, which will cause failures
of tests. Add a wait_for to wait untill detach completed.

Fix virsh event case failure

---

libvirt/tests/cfg/conf_file/qemu_conf/auto_dump.cfg
libvirt/tests/src/conf_file/qemu_conf/auto_dump.py

The value of flag was set wrong.

Fix the issue of fail to compare flags

---

libvirt/tests/src/nwfilter/filter_aready_present_binding.py
libvirt/tests/src/nwfilter/nwfilter_update_vm_running.py
libvirt/tests/src/nwfilter/nwfilter_vm_attach.py
libvirt/tests/src/nwfilter/nwfilter_vm_start.py
libvirt/tests/src/nwfilter/vm_destroy_with_nwfilter.py
libvirt/tests/src/smt.py
libvirt/tests/src/svirt/dac_vm_per_image_start.py
libvirt/tests/src/svirt/svirt_attach_disk.py

Remove dependency of compat_52lts

---

libvirt/tests/cfg/virtual_disks/virtual_disks_multidisks.cfg

No error happened when do vm.save and snapshot with ahci disk

Add one AHCI disk case

---

libvirt/tests/src/nwfilter/nwfilter_vm_start.py

Previous bug fix bring logic change for this case, need backout change for this

Fix nwfilter_vm_start possitive_test new_filter ipset_test

---

libvirt/tests/cfg/svirt/dac_nfs_save_restore.cfg

To align with original case info

Change 1 case of svirt from negative to positive

---

libvirt/tests/cfg/virtual_network/iface_unprivileged.cfg
libvirt/tests/src/virtual_network/iface_unprivileged.py

- [bridge] Connect <interface> to a pre-created host tap device
in unprivileged libvirt
- [direct] connect <interface> to a pre-created host macvtap device
in unprivileged libvirt
depend on https://github.com/avocado-framework/avocado-vt/pull/2515

Add cases of iface operation with unprivileged user

---

libvirt/tests/src/virsh_cmd/domain/virsh_domif_setlink_getlink.py

To avoid getting outdated iface status.

Wait for a few seconds to get iface status

---

libvirt/tests/src/memory/nvdimm.py

Fixed the shell cmd failure issue in nvdimm test

---

libvirt/tests/cfg/virsh_cmd/domain/virsh_blockcommit.cfg
libvirt/tests/src/virsh_cmd/domain/virsh_blockcommit.py

It reports "File exists" while converting data sometimes.
So update to remove image before conversion and do not use fixed
image name.

Fix error while converting raw in virsh_blockcommit

---

libvirt/tests/src/migration/migrate_ceph.py

Fix ceph migrate command typo

---

libvirt/tests/src/virtual_device/filesystem_device.py

Modify the number of hugepages allocated

---

libvirt/tests/src/migration/migrate_vm.py

Update type of items in processors' list

---

libvirt/tests/src/migration/migrate_gluster.py

It required password for local vm access if set vm connection uri
to src_uri.

Reset uri to original value in cleanup_dest_vm()

---

libvirt/tests/cfg/libvirt_cputune.cfg
libvirt/tests/src/libvirt_cputune.py

For new feature, add memory bandwidth monitor test case

Add memory bandwidth monitor test case

---

libvirt/tests/src/virtual_network/iface_hotplug.py

Check libvirt do not crash during detach interface even the interface
if not exists in the vm.

Detach non-exists interface from vm should not crash the libvirtd

---

libvirt/tests/cfg/virsh_cmd/domain/virsh_managedsave.cfg
libvirt/tests/src/virsh_cmd/domain/virsh_managedsave.py

Fail test if vm is not shutdown as expected

---

libvirt/tests/cfg/virtual_device/filesystem_device.cfg

Fix only pattern for two_guests

---

libvirt/tests/cfg/virtual_disks/virtual_disks_multidisks.cfg

Got error: internal error: qemu does not support SGA

Remove unsupported case for pseries

---

libvirt/tests/cfg/remote_access/remote_with_unix.cfg

remote_access: Add new case for socket activation mode

---

libvirt/tests/src/virsh_cmd/domain/virsh_vcpucount.py

1. split `need_agent` into three parameters depending on intended action
2. pass `channel=False` explicitly in order to set `start`
3. don't try (re)install guest agent and pm-utils after the domain has been
reset the first time
4. fix some column width issues

Speed up vcpucount test cases

---

libvirt/tests/cfg/remote_access/remote_with_tls.cfg

failed to connect to the hypervisorerror: authentication failed:
Failed to verify peer's certificate

remote_access: Fix a certificate issue

---

v2v/tests/cfg/function_test_esx.cfg
v2v/tests/src/function_test_esx.py

Add windows and linux guests support for qemu-guest-agent feature

Add qemu-guest-agent support for v2v on rhel8

---

libvirt/tests/src/libvirt_mem.py

Skip checking memory alignment of currentMemory

---

libvirt/tests/cfg/remote_access/remote_with_unix.cfg
libvirt/tests/src/remote_access/remote_access.py

remote_access: cache a ticket for GSSAPI authentication

---

libvirt/tests/cfg/virsh_cmd/domain/virsh_setvcpus.cfg

acpi is not supported by pseries

---

v2v/tests/src/v2v_options.py

1) Guest is not cleaned up if output is rhv
2) Fix v2v error warp length problem(set to 76)

v2v: fix issue that guest is not cleaned up on rhv server

---

libvirt/tests/src/virtual_device/filesystem_device.py

Adjust the hugepages for two guests

---

v2v/tests/src/v2v_options.py

When create a pool in qemu:///session by normal user, sometimes
'virsh pool-create-as xxx' returns success but the pool cannot
be found. It might be libvirt bug.
This patch is a workaround  to this problem, it tries to create
it until sucess or timeout, so that v2v testing will not be blocked.

v2v: Fix the problem that testing pool cannot be found

---

v2v/tests/src/v2v_options.py

v2v debug code

---

libvirt/tests/cfg/virsh_cmd/domain/virsh_hypervisor_cpu_compare.cfg
libvirt/tests/src/virsh_cmd/domain/virsh_hypervisor_cpu_compare.py

The output message is different on different machines.

Update patterns to search in virsh_hypervisor_cpu_compare

---

v2v/tests/cfg/function_test_esx.cfg
v2v/tests/src/function_test_esx.py

Add a case which allows Windows virtio ISO to be a block device

---

libvirt/tests/cfg/cpu/vcpu_misc.cfg

ppc result is different with x86

Modify expected mode to host-model for ppc test

---

libvirt/tests/src/virsh_cmd/domain/virsh_setvcpus.py

Since test could hit BZ1426220 if topology not removed.

Remove topology if test does not require

---

libvirt/tests/cfg/virsh_cmd/domain/virsh_vcpupin.cfg
libvirt/tests/src/virsh_cmd/domain/virsh_vcpupin.py

cputune settings will affect affinity output
Also move some code inside 'try' block to avoid exceptions

Remove cputune settings before affinity test

---

libvirt/tests/src/virtual_device/tpm_device.py

Check vm's existance before removing it

---

libvirt/tests/src/virsh_cmd/host/virsh_maxvcpus.py

Result of comparing the amount of maxvcpu depends on the output of
capabilities of host, but it should be remote host, not local host
when the connection is to remote host.

Fix issue of calulating maxvcpu from local instead of remote host

---

libvirt/tests/cfg/virtual_network/iface_bridge.cfg
libvirt/tests/src/virtual_network/iface_bridge.py

Add attach-interface/device to active vm cases.

Add hotplug bridge type interface and device cases

---

libvirt/tests/src/svirt/svirt_start_destroy.py

Only need modify disk ownership when no_sec_relabel and non_sec_type

---

libvirt/tests/src/virsh_cmd/filter/virsh_nwfilter_define.py
libvirt/tests/src/virsh_cmd/filter/virsh_nwfilter_dumpxml.py
libvirt/tests/src/virsh_cmd/filter/virsh_nwfilter_list.py
libvirt/tests/src/virsh_cmd/filter/virsh_nwfilter_undefine.py
libvirt/tests/src/virsh_cmd/host/virsh_hostname.py
libvirt/tests/src/virsh_cmd/host/virsh_maxvcpus.py
libvirt/tests/src/virsh_cmd/host/virsh_nodecpustats.py
libvirt/tests/src/virsh_cmd/host/virsh_nodeinfo.py
libvirt/tests/src/virsh_cmd/host/virsh_uri.py
libvirt/tests/src/virsh_cmd/host/virsh_version.py
libvirt/tests/src/virsh_cmd/interface/virsh_iface.py
libvirt/tests/src/virsh_cmd/monitor/virsh_domblkinfo.py
libvirt/tests/src/virsh_cmd/monitor/virsh_domstate.py
libvirt/tests/src/virsh_cmd/monitor/virsh_domstats.py
libvirt/tests/src/virsh_cmd/network/virsh_net_define_undefine.py
libvirt/tests/src/virsh_cmd/network/virsh_net_destroy.py
libvirt/tests/src/virsh_cmd/network/virsh_net_dhcp_leases.py
libvirt/tests/src/virsh_cmd/network/virsh_net_dumpxml.py
libvirt/tests/src/virsh_cmd/network/virsh_net_list.py
libvirt/tests/src/virsh_cmd/network/virsh_net_start.py
libvirt/tests/src/virsh_cmd/nodedev/virsh_nodedev_create_destroy.py
libvirt/tests/src/virsh_cmd/nodedev/virsh_nodedev_detach_reattach.py
libvirt/tests/src/virsh_cmd/nodedev/virsh_nodedev_dumpxml.py
libvirt/tests/src/virsh_cmd/nodedev/virsh_nodedev_list.py

Update to call libvirt_version from avocado-vt.virttest

---

libvirt/tests/src/virsh_cmd/pool/virsh_find_storage_pool_sources.py
libvirt/tests/src/virsh_cmd/pool/virsh_find_storage_pool_sources_as.py
libvirt/tests/src/virsh_cmd/pool/virsh_pool.py
libvirt/tests/src/virsh_cmd/pool/virsh_pool_acl.py
libvirt/tests/src/virsh_cmd/pool/virsh_pool_auth.py
libvirt/tests/src/virsh_cmd/pool/virsh_pool_autostart.py
libvirt/tests/src/virsh_cmd/pool/virsh_pool_capabilities.py
libvirt/tests/src/virsh_cmd/pool/virsh_pool_create.py
libvirt/tests/src/virsh_cmd/secret/virsh_secret_define_undefine.py
libvirt/tests/src/virsh_cmd/secret/virsh_secret_dumpxml.py
libvirt/tests/src/virsh_cmd/secret/virsh_secret_list.py
libvirt/tests/src/virsh_cmd/snapshot/virsh_snapshot_create_as.py
libvirt/tests/src/virsh_cmd/snapshot/virsh_snapshot_disk.py
libvirt/tests/src/virsh_cmd/volume/virsh_vol_clone_wipe.py
libvirt/tests/src/virsh_cmd/volume/virsh_vol_create.py
libvirt/tests/src/virsh_cmd/volume/virsh_vol_create_from.py
libvirt/tests/src/virsh_cmd/volume/virsh_vol_download_upload.py
libvirt/tests/src/virsh_cmd/volume/virsh_vol_resize.py
libvirt/tests/src/virsh_cmd/volume/virsh_volume.py

Update libvirt_version from avocado-vt.virttest

---

libvirt/tests/src/npiv/npiv_hostdev_passthrough.py

Signed-off-by: jgao <jgao@localhost.localdomain>

Fix problem of NPIV multipathd unable to start

---

provider/v2v_vmcheck_helper.py

Set windows VM session to None after session close

---

libvirt/tests/cfg/remote_access/remote_with_unix.cfg

remote_access: Add support for traditional mode

---

libvirt/tests/src/svirt/svirt_start_destroy.py

1.It only contained selinux label restore before;
2.Add checkpoint for ownership restore since bug#547546 fixed;

Add checkpoint for ownership restore:

---

libvirt/tests/cfg/remote_access/remote_with_tcp.cfg

Add parameters for TCP setup

---

libvirt/tests/cfg/migration/migrate_options_shared.cfg
libvirt/tests/src/migration/migrate_options_shared.py

This is to execute save/restore vm on remote host after migration.

Add case for migration save/restore

---

libvirt/tests/src/migration/migrate_options_shared.py

Fix for commit 5ac4ed2dc57d0fb0a67e408e3f8214a0211e8341

A fix for migration

---

libvirt/tests/src/virtual_network/iface_unprivileged.py

Current test result shows that there's a little messy when running
through different unprivileged users using virsh instance. But I'm
not 100% sure changing to virsh params could fix this problem, since
the problem cannot reproduced by me. But even it will not fix this
specific issue, it's a better way to conduct these virsh operations.

Replace operations using virsh instance with using params

---

libvirt/tests/src/remote_access/remote_access.py

Fix TLS connection setup issue

---

libvirt/tests/cfg/virsh_cmd/domain/virsh_event.cfg
libvirt/tests/src/virsh_cmd/domain/virsh_event.py

Add rtc-change and metadata-change events.

virsh_event: add more events

---

libvirt/tests/cfg/virsh_cmd/domain/virsh_blockcommit.cfg
libvirt/tests/src/virsh_cmd/domain/virsh_blockcommit.py

blockcommit can specifiy bandwidth with bytes
positive and negative scenarios are covered

Add blockcommit bandwidth in bytes cases

---

libvirt/tests/cfg/virtual_network/iface_update.cfg
libvirt/tests/src/virtual_network/iface_update.py

Live update the nwfilter with parameters. Depends on https://github.com/avocado-framework/avocado-vt/pull/2598

Update nwfilter with parameters

---

libvirt/tests/cfg/virtual_disks/virtual_disks_ceph.cfg
libvirt/tests/src/virtual_disks/virtual_disks_ceph.py

Allow ceph to create external snapshot and check the snapshot attributes

Add ceph external snapshots case

---

libvirt/tests/src/migration/migrate_vm.py

To compile netperl, the automake package needs to be installed
on source and target host.

Fix netperl compilation failure

---

libvirt/tests/src/virsh_cmd/virsh_connect.py

Fix the failure like "error: Unable to resolve address 'TLSServer'".

virsh_connect: Fix a connect issue

---

libvirt/tests/src/libvirt_pci_passthrough_hotplug.py
libvirt/tests/src/virsh_cmd/domain/virsh_set_user_password.py

Python3: Update 2 left files to fit for python3

---

v2v/tests/cfg/function_test_esx.cfg

Add version required for some cases

---

libvirt/tests/src/libvirt_mem.py
libvirt/tests/src/libvirt_pci_passthrough_hotplug.py
libvirt/tests/src/libvirt_qemu_cmdline.py
libvirt/tests/src/libvirt_rng.py
libvirt/tests/src/virtual_device/input_devices.py
libvirt/tests/src/virtual_device/sound_device.py
libvirt/tests/src/virtual_device/video_devices.py
libvirt/tests/src/virtual_disks/at_dt_iscsi_disk.py
libvirt/tests/src/virtual_disks/startup_policy.py
libvirt/tests/src/virtual_disks/virtual_disks_ceph.py
libvirt/tests/src/virtual_disks/virtual_disks_encryption.py
libvirt/tests/src/virtual_disks/virtual_disks_iscsi.py
libvirt/tests/src/virtual_disks/virtual_disks_luks.py
libvirt/tests/src/virtual_disks/virtual_disks_multidisks.py
libvirt/tests/src/virtual_disks/virtual_disks_multivms.py
libvirt/tests/src/virtual_disks/virtual_disks_scsi3_persistent_reservation.py
libvirt/tests/src/virtual_network/iface_coalesce.py
libvirt/tests/src/virtual_network/iface_network.py
libvirt/tests/src/virtual_network/iface_options.py

Replace version compare function of provider with the one of virttest

---

libvirt/tests/src/virsh_cmd/domain/virsh_event.py

Fix typo in virsh_event

---

libvirt/tests/src/virsh_cmd/domain/virsh_dump.py

To avoid following failure:
cat: /proc//fdinfo/1: No such file or directory

Update for virsh_dump

---

libvirt/tests/cfg/cpu/vcpu_feature.cfg
libvirt/tests/src/cpu/vcpu_feature.py

This PR adds a case to check if cpu feature policy work as
expected with cpu mode=passthrough.

Add a cpu feature case

---

libvirt/tests/src/bios/boot_integration.py
libvirt/tests/src/bios/virsh_boot.py
libvirt/tests/src/bios/virsh_boot_tseg.py
libvirt/tests/src/conf_file/libvirtd_conf/unix_sock.py
libvirt/tests/src/conf_file/qemu_conf/auto_dump.py
libvirt/tests/src/conf_file/qemu_conf/seccomp_sandbox.py
libvirt/tests/src/conf_file/qemu_conf/set_virtlogd.py
libvirt/tests/src/cpu/max_vcpus.py
libvirt/tests/src/cpu/vm_features.py
libvirt/tests/src/daemon/daemon_functional.py
libvirt/tests/src/graphics/graphics_functional.py
libvirt/tests/src/guest_kernel_debugging/nmi_test.py
libvirt/tests/src/migration/migrate_ceph.py
libvirt/tests/src/migration/migrate_vm.py
libvirt/tests/src/numa/guest_numa.py
libvirt/tests/src/nwfilter/nwfilter_edit_uuid.py
libvirt/tests/src/nwfilter/nwfilter_update_lock.py
libvirt/tests/src/remote_access/remote_access.py
libvirt/tests/src/serial/serial_functional.py
libvirt/tests/src/svirt/dac_per_disk_hotplug.py

Signed-off-by: kylazhang <weizhan@redhat.com>

Change the libvirt_version usage from tp-libvirt to avocado-vt

---

libvirt/tests/cfg/virsh_cmd/domain/virsh_blockcommit.cfg
libvirt/tests/src/virsh_cmd/domain/virsh_blockcommit.py

blockcommit can still succeed after VM destroy and start again

Add reuse external snapshots scenarios in case blockcommit

---

libvirt/tests/src/virsh_cmd/domain/virsh_attach_detach_interface_matrix.py
libvirt/tests/src/virsh_cmd/domain/virsh_attach_device.py
libvirt/tests/src/virsh_cmd/domain/virsh_blockresize.py
libvirt/tests/src/virsh_cmd/domain/virsh_console.py
libvirt/tests/src/virsh_cmd/domain/virsh_cpu_compare_xml.py
libvirt/tests/src/virsh_cmd/domain/virsh_detach_serial_device_alias.py
libvirt/tests/src/virsh_cmd/domain/virsh_domdisplay.py
libvirt/tests/src/virsh_cmd/domain/virsh_domid.py
libvirt/tests/src/virsh_cmd/domain/virsh_domuuid.py
libvirt/tests/src/virsh_cmd/domain/virsh_hypervisor_cpu_compare.py
libvirt/tests/src/virsh_cmd/domain/virsh_migrate_set_get_speed.py
libvirt/tests/src/virsh_cmd/domain/virsh_migrate_setmaxdowntime.py
libvirt/tests/src/virsh_cmd/domain/virsh_qemu_monitor_blockjob.py
libvirt/tests/src/virsh_cmd/domain/virsh_reset.py
libvirt/tests/src/virsh_cmd/domain/virsh_save.py
libvirt/tests/src/virsh_cmd/domain/virsh_screenshot.py
libvirt/tests/src/virsh_cmd/domain/virsh_suspend.py
libvirt/tests/src/virsh_cmd/domain/virsh_update_device.py
libvirt/tests/src/virsh_cmd/domain/virsh_update_device_matrix.py
libvirt/tests/src/virsh_cmd/domain/virsh_vcpuinfo.py

Use new libvirt_version in avocado-vt

---

libvirt/tests/cfg/memory/nvdimm.cfg
libvirt/tests/src/memory/nvdimm.py

Add nvdimm lifecycle test case

---

v2v/tests/cfg/function_test_esx.cfg

Add a case that checking pnp_wait.exe warning for windows guests

---

libvirt/tests/src/nwfilter/nwfilter_binding_create.py
libvirt/tests/src/nwfilter/nwfilter_binding_delete.py

Fix the non-exists function name.

Fix the function name issue

---

libvirt/tests/cfg/nwfilter/filter_aready_present_binding.cfg
libvirt/tests/src/nwfilter/filter_aready_present_binding.py

Edit the cfg file as the expected error messages changes. And update the
case name to be more understandable. Also fix the the function name
about check_cmd_output. And install the package in case it may not
exists in the system.

Fix issue as error messages changes

---

libvirt/tests/cfg/virsh_cmd/domain/virsh_dump.cfg
libvirt/tests/src/virsh_cmd/domain/virsh_dump.py

virsh_dump: Add document test case

---

libvirt/tests/cfg/migration/migrate_bandwidth.cfg

The messages in the libvirtd log have changed in the latest version.

Update expected message for migrate_bandwidth cases

---

libvirt/tests/src/migration/migrate_options_shared.py
libvirt/tests/src/multifunction.py
libvirt/tests/src/sriov/sriov.py
libvirt/tests/src/storage_discard.py
libvirt/tests/src/vfio.py
libvirt/tests/src/virsh_cmd/domain/virsh_domblkerror.py
libvirt/tests/src/virtual_device/vsock.py

These two arugments are duplicated with the arugments domainarg and
filearg.

src: Drop domain_opt and file_opt

---

libvirt/tests/cfg/virtual_network/iface_hotplug.cfg
libvirt/tests/src/virtual_network/iface_hotplug.py

The mac address of "0xFE" is supported in the vm.

Start vm or hotplug interface with mac address start with "0xFE"

---

libvirt/tests/cfg/conf_file/qemu_conf/set_virtlogd.cfg
libvirt/tests/src/conf_file/qemu_conf/set_virtlogd.py

set_virtlogd: Add test for restart virtlogd.service

---

libvirt/tests/cfg/migration/migrate_bandwidth.cfg
libvirt/tests/src/migration/migrate_bandwidth.py

depends on https://github.com/avocado-framework/avocado-vt/pull/2671
https://github.com/avocado-framework/avocado-vt/pull/2674

Update migrate_bandwidth cases to support modular daemons

---

libvirt/tests/cfg/incremental_backup/incremental_backup_pull_mode.cfg
libvirt/tests/cfg/incremental_backup/incremental_backup_push_mode.cfg
libvirt/tests/src/incremental_backup/incremental_backup_pull_mode.py
libvirt/tests/src/incremental_backup/incremental_backup_push_mode.py

Incremental backup function is introduced by
Bug 1207659 - RFE: QEMU Incremental live backup (libvirt)

Add test cases for incremental backup

---

libvirt/tests/cfg/memory/nvdimm.cfg

Fix the issue that guest can't login after reboot

---

libvirt/tests/cfg/virtual_network/iface_update.cfg
libvirt/tests/src/virtual_network/iface_update.py

Add nwfilter with parameters with update-device and check the rules in
host. Also add check point for delete network filter, we should not only
check the xml, but also ensure the rules are deleted.

Adding nwfilter with parameters

---

libvirt/tests/cfg/conf_file/qemu_conf/set_virtlogd.cfg
libvirt/tests/src/conf_file/qemu_conf/set_virtlogd.py

Add case for set_virtlogd

---

libvirt/tests/src/nwfilter/nwfilter_update_vm_running.py
libvirt/tests/src/nwfilter/nwfilter_vm_start.py

Before executing test cases, clean up dirty newfilter binding first

Fix binding 'vnet0' already exists issue

---

provider/v2v_vmcheck_helper.py
v2v/tests/cfg/convert_from_file.cfg
v2v/tests/cfg/function_test_esx.cfg
v2v/tests/cfg/specific_kvm.cfg
v2v/tests/cfg/v2v_options.cfg
v2v/tests/src/convert_from_file.py
v2v/tests/src/convert_vm_to_libvirt.py
v2v/tests/src/convert_vm_to_ovirt.py
v2v/tests/src/function_test_esx.py
v2v/tests/src/function_test_xen.py
v2v/tests/src/specific_kvm.py

1) Rename some variant's name
2) Add public checkpoints for '-o local' and '-o json'
3) Improve the logic of  check_result functions
4) Add new cases for '-o json'

v2v: improve codes and add new -o json cases

---

libvirt/tests/cfg/bios/boot_integration.cfg
libvirt/tests/src/bios/boot_integration.py

1. seabios not supported on arch, filter out
2. add test case display of qemu boot menu
3. add test case booting non default entry

Add test case for s390 boot menu

---

provider/v2v_vmcheck_helper.py

Add public checkpoint for 'cache=none'

---

libvirt/tests/src/virsh_cmd/domain/virsh_attach_detach_disk.py

To move adding controller logic outside to cover more scenarios

Fix new merged no more pci slots issue

---

libvirt/tests/cfg/sriov/sriov.cfg
libvirt/tests/src/sriov/sriov.py

Add test case of attaching/detaching PCI passthough dev with restarting libvirtd.
Including interface, pool & hostdev types.

Add test case of attach/detach PCI passth dev after restarting libvirtd

---

libvirt/tests/cfg/libvirt_rng.cfg
libvirt/tests/src/libvirt_rng.py

Add cases for rng builtin with rate

---

libvirt/tests/cfg/migration/migrate_options_shared.cfg

The error message has been updated recently, so modify it
accordingly.

Update error message for multifd tunnelled_migration

---

libvirt/tests/cfg/virsh_cmd/domain/virsh_guestinfo.cfg
libvirt/tests/src/virsh_cmd/domain/virsh_guestinfo.py

Signed-off-by: iccaszhulili <lizhu@redhat.com>

Add virsh guestinfo cases

---

libvirt/tests/cfg/libvirt_package.cfg
libvirt/tests/src/libvirt_package.py

Add cases for libvirt_package

---

libvirt/tests/cfg/nwfilter/nwfilter_binding_create.cfg
libvirt/tests/cfg/nwfilter/nwfilter_binding_delete.cfg
libvirt/tests/src/nwfilter/nwfilter_binding_create.py
libvirt/tests/src/nwfilter/nwfilter_binding_delete.py

Update the restart libvirtd function to fix the modular run issue.

Update the restart libvirtd function

---

libvirt/tests/cfg/migration/migrate_options_shared.cfg

The error messages were updated recently, so update them in this
PR.

migration: Update error message for disable_keepalive cases

---

libvirt/tests/cfg/virsh_cmd/domain/virsh_blockcommit.cfg

Add cases to cover more checking points

---

libvirt/tests/cfg/guest_kernel_debugging/nmi_test.cfg
libvirt/tests/src/guest_kernel_debugging/nmi_test.py

Fix the issue about failed to reboot guest for nmi_test

---

libvirt/tests/cfg/virsh_cmd/domain/virsh_dump.cfg
libvirt/tests/src/virsh_cmd/domain/virsh_dump.py

virsh_dump: Remove whitespace for man virsh

---

libvirt/tests/src/daemon/kill_starting.py

Use "utils_libvirtd.Libvirtd" to restart socket service

---

libvirt/tests/cfg/virt_cmd/virt_xml_validate.cfg
libvirt/tests/src/virt_cmd/virt_xml_validate.py

virt_xml_validate: Update case for test secret

---

libvirt/tests/cfg/virsh_cmd/domain/virsh_blockcommit.cfg
libvirt/tests/src/virsh_cmd/domain/virsh_blockcommit.py

Add case to validate Bug 1857735

---

libvirt/tests/cfg/virtual_network/virtual_network_multivms.cfg
libvirt/tests/src/virtual_network/virtual_network_multivms.py

- Test vm interface with port isolated settings
- Test network with port isolated settings
- Test attaching interface with port isolated settings
- Test live update interface with port isolated settings

Add network cases of port isolated

---

libvirt/tests/src/migration/migrate_vm.py

In modular daemon environment, remote mode is set to 'direct' by
default, which is not supported for SSH transport.
depends on: https://github.com/avocado-framework/avocado-vt/pull/2674
https://github.com/avocado-framework/avocado-vt/pull/2680

Update socket mode for SSH transport if it's not supported

---

libvirt/tests/cfg/serial/serial_functional.cfg
libvirt/tests/src/serial/serial_functional.py

Fix incorrect usage according to
https://github.com/avocado-framework/avocado-vt/pull/2642

Fix incorrect usage

---

libvirt/tests/cfg/virsh_cmd/domain/virsh_blockcopy.cfg
libvirt/tests/src/virsh_cmd/domain/virsh_blockcopy.py

Add cases to cover multiple snapshots scenarios before blockcopy

---

libvirt/tests/cfg/virsh_cmd/domain/virsh_blockcommit.cfg
libvirt/tests/src/virsh_cmd/domain/virsh_blockcommit.py

Cover invalid timeout,top without active option,and keep-overlay scenarios

Add multiple blockcommit cases

---

libvirt/tests/cfg/migration/migrate_options_shared.cfg
libvirt/tests/cfg/migration/migrate_vm.cfg

The messages in the libvirtd log have changed in the latest version.

Update expected message in log file for some migration cases

---

libvirt/tests/cfg/virtual_network/iface_update.cfg
libvirt/tests/src/virtual_network/iface_update.py

Add 2 more scenarios about update alias by difference: only by mac
or only by pci address.

Add 2 more scenarios about update alias

---

libvirt/tests/src/conf_file/libvirtd_conf/host_uuid.py

Add config file with split daemon for host_uuid cases

---

libvirt/tests/cfg/conf_file/qemu_conf/set_virtlogd.cfg
libvirt/tests/src/conf_file/qemu_conf/set_virtlogd.py

Check virtlogd status after libvirtd is stoped.

Add new case for set_virtlogd

---

libvirt/tests/src/daemon/kill_started.py

Add pidfile for split daemon mode

---

libvirt/tests/src/migration/migrate_options_shared.py
libvirt/tests/src/migration/migrate_vm.py
libvirt/tests/src/migration/sriov_migrate.py

Due to the API is moved to a new place, we update the cases accordingly.

Update func invoke usage

---

v2v/tests/cfg/function_test_esx.cfg
v2v/tests/src/function_test_esx.py
v2v/tests/src/v2v_options.py

v2v: Add a new case about reducing v2v log size

---

libvirt/tests/cfg/incremental_backup/incremental_backup_checkpoint_cmd.cfg
libvirt/tests/src/incremental_backup/incremental_backup_checkpoint_cmd.py

Add cases to cover pure checkpoint commands for backup function

---

libvirt/tests/src/virsh_cmd/filter/virsh_nwfilter_undefine.py

If the the case return in the check result part, it will not check and recover
the env. Add the try...finally to recover the env in all cases.

Add try...finally to recover the env in all cases

---

v2v/tests/cfg/nbdkit/nbdkit.cfg
v2v/tests/src/nbdkit/nbdkit.py

v2v: Add a new case about nbdkit-stats-filter leaks an fd

---

libvirt/tests/src/virsh_cmd/network/virsh_net_destroy.py

There is check libvirtd pid operation in the test case, update the daemon
name related operation to fit the split daemon.

Update the check daemon operation to fit split daemon

---

v2v/tests/cfg/function_test_esx.cfg
v2v/tests/src/function_test_esx.py

1) Add several luks cases
2) Add a case that without '-ip' in command line

v2v: Add some new cases(luks, '-ip')

---

libvirt/tests/cfg/virtual_network/iface_bridge.cfg
libvirt/tests/src/virtual_network/iface_bridge.py

Start VM with bridge type interface with multiqueue or hotplug bridge
tyep interface with multiqueue, then check on guest.

Hotplug bridge interface with multiqueue

---

libvirt/tests/src/controller/controller_functional.py
libvirt/tests/src/controller/multiple_controller_ppc.py
libvirt/tests/src/libvirt_mem.py
libvirt/tests/src/memory/memory_discard.py
libvirt/tests/src/memory/nvdimm.py
libvirt/tests/src/numa/guest_numa.py
libvirt/tests/src/papr_hpt.py
libvirt/tests/src/sriov/sriov.py
libvirt/tests/src/virsh_cmd/domain/virsh_migrate.py
libvirt/tests/src/virtual_network/iface_options.py

The implement of numa_cell is being changed, this modification is
to fit the change.

Update usage of cpu.numa_cell

---

libvirt/tests/cfg/virsh_cmd/domain/virsh_blockcommit.cfg
libvirt/tests/src/virsh_cmd/domain/virsh_blockcommit.py

Allow create block type disk on file backing file,and do blockcommit on snapshots

Add case to cover creating block type disk on file backing file

---

libvirt/tests/src/migration/migrate_options_shared.py
libvirt/tests/src/migration/migrate_vm.py
libvirt/tests/src/migration/sriov_migrate.py
libvirt/tests/src/virsh_cmd/domain/virsh_migrate_copy_storage.py

Due to the function add_remote_disks_checking() API is change, the case need updates.

virsh_migrate_copy_storage: update invoking a function

---

libvirt/tests/src/virsh_cmd/volume/virsh_vol_download_upload.py

The manual case was updated to:
1. compare the disk size after virsh vol-download command with
the data size generated by 'dd'
2. compare the disk size after virsh vol-upload command with
the data size generated by 'dd'
The file's disk size did not increase linearly with the size of
the new created data, so we changed the case.

Update sparse volume_download_upload case

---

libvirt/tests/src/controller/controller_functional.py

Change the usage according to avocado-vt PR 2685.

Fix controller target

---

libvirt/tests/cfg/incremental_backup/incremental_backup_backing_chain.cfg
libvirt/tests/src/incremental_backup/incremental_backup_backing_chain.py

To test incremental backup with backing chain management functions:
blockpull, blockcommit and blockcopy.

Add integration test cases for backup and backing chain

---

libvirt/tests/src/daemon/crash_regression.py

When modular daemons enabled, we need to update command and
service from "libvirtd" to "virtqemud".
depends on https://github.com/avocado-framework/avocado-vt/pull/2733

Fix crash_regression cases for modular daemons env

---

libvirt/tests/src/virsh_cmd/domain/virsh_blockcopy.py

Fix libvirtd conf issue in split daemon

Fix libvirtd conf issue in split daemon

---

libvirt/tests/cfg/memory/nvdimm.cfg
libvirt/tests/src/memory/nvdimm.py

To check device inside vm, a new namespace should be created by
ndctl

Update nvdimm hotplug case to support pseries

---

libvirt/tests/cfg/migration/migrate_options_shared.cfg

This is to use correct vtmp model on PPC

Fix vtpm on ppc

---

libvirt/tests/src/migration/migrate_vm.py

The configuration in libvirt.conf should be updated before
run_migr_back. And update to use remove_key_for_modular_daemon()
in virttest.utils_libvirt.libvirt_config.

migrate_vm: the libvirt.conf should be updated earlier

---

libvirt/tests/cfg/virsh_cmd/domain/virsh_attach_detach_interface.cfg
libvirt/tests/cfg/virsh_cmd/domain/virsh_change_media.cfg
libvirt/tests/cfg/virsh_cmd/domain/virsh_detach_device.cfg
libvirt/tests/cfg/virsh_cmd/domain/virsh_event.cfg

Fix wrong format of setting params for specific machine type

---

libvirt/tests/src/virsh_cmd/domain/virsh_migrate_copy_storage.py

The direct mode is unsupported for SSH transport when the modular
daemon is enabled, so update it in copy storage migration script.

Fix direct mode issue for virsh_migrate_copy_storage

---

libvirt/tests/src/virsh_cmd/domain/virsh_migrate.py

It was introduced by avocado-vt 2070.

Correct the usages of VMManager.check_network

---

libvirt/tests/cfg/virsh_cmd/domain/virsh_event.cfg
libvirt/tests/src/virsh_cmd/domain/virsh_event.py

Add device-removal-failed event.

virsh_event: add device-removal-failed event

---

libvirt/tests/cfg/virsh_cmd/domain/virsh_managedsave.cfg
libvirt/tests/src/virsh_cmd/domain/virsh_managedsave.py

- Managedsave-remove for a domain NOT in saved state but with a
corrupt saved file

Add a case of managedsave-remove

---

libvirt/tests/cfg/migration/migrate_mem.cfg
libvirt/tests/src/migration/migrate_mem.py

Add migration vm with memory device and memory balloon device test
cases.

Add migration test cases about memory balloon device

---

libvirt/tests/cfg/virsh_cmd/domain/virsh_managedsave.cfg
libvirt/tests/src/virsh_cmd/domain/virsh_managedsave.py

Managedsave-remove test for domain not in saved state, and in saved state
but without saved file.

Add 2 cases for managedsave-remove

---

libvirt/tests/src/virtual_disks/at_dt_iscsi_disk.py

Virsh snapshot-revert is not supported on combined internal and external snapshots
See more details from,https://bugzilla.redhat.com/show_bug.cgi?id=1733173
Moreover, add logic to fix no more pci slots issue encountered in certain cases

Fix snapshot-revert case failures

---

libvirt/tests/src/virsh_cmd/domain/virsh_attach_device.py

Since hotplug scsi disk with ibmvscsi controller is not supported,
replacing with virtio-scsi model could fix it.

Update scsi controller on ppc vms to support scsi hotplug

---

v2v/tests/cfg/function_test_esx.cfg
v2v/tests/src/function_test_esx.py

v2v: add cases about logs when vcenter or esxi address is invalid

---

libvirt/tests/src/virsh_cmd/domain/virsh_event.py

vmxml_cpu.numa_cell get value issue from numa_dict_list

fix error in device-removal-failed event

---

v2v/tests/cfg/convert_vm_to_ovirt.cfg
v2v/tests/src/convert_vm_to_ovirt.py

v2v: add skip_vm_check for convert_vm_to_ovirt

---

libvirt/tests/src/virsh_cmd/domain/virsh_guestinfo.py

1)The block used-bytes of guest may change by about 16000Kib
after boot or during login to the guest. we just need to
make sure the size difference will not exceed then 17000KiB.
2) Refactor a little for avoiding code redundancy.

Fix get filesystem info failure by limiting used-bytes difference

---

libvirt/tests/cfg/virsh_cmd/domain/virsh_event.cfg
libvirt/tests/src/virsh_cmd/domain/virsh_event.py

Check events for I/O errors and manual RESUME.

virsh_event: add io-error event

---

libvirt/tests/cfg/sriov/sriov.cfg

Remove the extra cases for hostdev

---

libvirt/tests/cfg/virtual_network/iface_network.cfg
libvirt/tests/src/virtual_network/iface_network.py

- Clone domain with direct type interface

Add new case of cloning vm with direct type interface

---

libvirt/tests/cfg/svirt/dac_vm_per_image_start.cfg

The bugzilla bug fix one issue failing to start a guest with disk in nfs dir with root-squash

Add test case to validate bugzilla bug:1804672

---

libvirt/tests/cfg/nwfilter/nwfilter_vm_start.cfg
libvirt/tests/src/nwfilter/nwfilter_vm_start.py

The nwfilter clean-traffic-gateway will block the vms connected to the
same bridge to access to each other.

Test the function of filter clean traffic gateway

---

libvirt/tests/cfg/virtual_device/filesystem_device.cfg
libvirt/tests/src/virtual_device/filesystem_device.py

1. Restore the host's hugepages after the test
2. Make add extra hugepages configurable
Signed-off-by: Yihuang Yu <yihyu@redhat.com>

filesystem_device: Make add extra hugepages configurable

---

libvirt/tests/cfg/virtual_network/iface_options.cfg
libvirt/tests/src/virtual_network/iface_options.py

Add new case for nfv performance check

---

libvirt/tests/cfg/controller/controller_functional.cfg
libvirt/tests/src/controller/controller_functional.py

As the guest xml has new device attaching to the bus, I have to adjust
the controller's index to contain the disk the case needs to attach.

controller_functional: Fix wrong bus number

---

libvirt/tests/cfg/virtual_network/iface_update.cfg
libvirt/tests/src/virtual_network/iface_update.py

- update-device for interface defined with not supported live-update
configurations

Add new case of updating iface

---

v2v/tests/cfg/function_test_esx.cfg
v2v/tests/src/function_test_esx.py

v2v: add bandwidth cases

---

v2v/tests/cfg/function_test_esx.cfg
v2v/tests/src/function_test_esx.py

Add new cases about v2v --key option

---

libvirt/tests/cfg/controller/pcie_controllers.cfg
libvirt/tests/src/controller/pcie_controllers.py

Add new cases to multiple hotplug devices to pcie-root-port controller
with hotplug_option 'on' and 'off' respecitively.

pcie_controllers: new case for multiplug

---

libvirt/tests/src/incremental_backup/incremental_backup_checkpoint_cmd.py

Since libvirt-6.6.0-1.el8, libvirt starts to support '--size'
for 'checkpoint-dumpxml', this patch is to test it.

Add case to test checkpoint-xml with --size

---

provider/v2v_vmcheck_helper.py

v2v: fix boottype checking issue on rhv4.4

---

libvirt/tests/cfg/virt_admin/monitor/virt_admin_srv_clients_info.cfg
libvirt/tests/cfg/virt_admin/monitor/virt_admin_srv_list.cfg
libvirt/tests/cfg/virt_admin/monitor/virt_admin_srv_threadpool_info.cfg
libvirt/tests/src/virt_admin/monitor/virt_admin_srv_clients_info.py
libvirt/tests/src/virt_admin/monitor/virt_admin_srv_list.py
libvirt/tests/src/virt_admin/monitor/virt_admin_srv_threadpool_info.py

As the server name changed under split daemon mode, the config
file is also changed, update them.

[Batch 1] Fix Admin API cases for split daemon mode

---

libvirt/tests/cfg/virt_admin/management/virt_admin_client_disconnect.cfg
libvirt/tests/cfg/virt_admin/management/virt_admin_server_clients_set.cfg
libvirt/tests/cfg/virt_admin/management/virt_admin_server_threadpool_set.cfg
libvirt/tests/src/virt_admin/management/virt_admin_client_disconnect.py
libvirt/tests/src/virt_admin/management/virt_admin_server_clients_set.py
libvirt/tests/src/virt_admin/management/virt_admin_server_threadpool_set.py

As the server name changed under split daemon mode, the config
file is also changed, update them.

[Batch 2] Fix Admin API cases for split daemon mode

---

libvirt/tests/cfg/virsh_cmd/domain/virsh_blockcopy_xml.cfg
libvirt/tests/cfg/virsh_cmd/domain/virsh_domblkthreshold.cfg
libvirt/tests/cfg/virtual_disks/virtual_disks_ceph.cfg
libvirt/tests/cfg/virtual_disks/virtual_disks_luks.cfg

This is the step to move ceph pool name separation

Update ceph pool or image name as per validation feature

---

libvirt/tests/cfg/virtual_network/iface_network.cfg
libvirt/tests/src/virtual_network/iface_network.py

- nat for ipv6 is supported
- Start vm with 2 interfaces connected to 2 different nat network
and check net-dhcp-leases

Add new cases of nat 

---

libvirt/tests/cfg/virsh_cmd/domain/virsh_attach_detach_interface.cfg
libvirt/tests/src/virsh_cmd/domain/virsh_attach_detach_interface.py

- hotplug / unplug an network interface with multiqueue

Add 1 case of attach/detach interface with multiqueue

---

libvirt/tests/cfg/controller/controller_functional.cfg
libvirt/tests/src/controller/controller_functional.py

This is to add new case to check 'multifunction' will be inserted when
two scsi controllers with same bus and slot exist.

Add case for scsi multifunc

---

libvirt/tests/cfg/incremental_backup/incremental_backup_push_mode.cfg
libvirt/tests/src/incremental_backup/incremental_backup_push_mode.py

Reorg ceph server config info in script, will control them in CI yaml.

Update ceph server auth key info

---

libvirt/tests/src/virtual_network/iface_network.py

- Add version check for nat ipv6 test
- Remove ipv6 nat check when not setting nat ipv6 to 'yes'
- Use 'wait_for' for dhcp lease check test

Fix: remove unnecessary check of nat cases

---

libvirt/tests/cfg/virsh_cmd/domain/virsh_attach_detach_interface.cfg
libvirt/tests/src/virsh_cmd/domain/virsh_attach_detach_interface.py

- attach-device and attach-interface with multiple options or
elements for bridge type interface

Add new case of attaching iface with multiple options

---

v2v/tests/cfg/function_test_esx.cfg
v2v/tests/src/function_test_esx.py

v2v: add two negative --mac <mac>:ip:xxx cases

---

libvirt/tests/cfg/virtual_network/iface_options.cfg
libvirt/tests/src/virtual_network/iface_options.py

Add virtio packed test case in interface devices

Add virtio packed test case in interface devices

---

libvirt/tests/src/remote_access/remote_access.py

Digest md5 cases need cyrus-sasl-md5 package, so install it before
test to avoid authentication failure.

Fix digest_md5 authentication issue

---

libvirt/tests/src/virtual_disks/virtual_disks_multivms.py

As per https://bugzilla.redhat.com/show_bug.cgi?id=1609701,
use virsh.domblkerror to check whether disk error report policy  works or not

Fix error_policy_report case failure

---

libvirt/tests/cfg/virtual_disks/virtual_disks_luks.cfg
libvirt/tests/src/virtual_disks/virtual_disks_luks.py

File based disk supports slice attribute in luks encryption

Add luks disk with slice attribute support

---

libvirt/tests/cfg/memory/nvdimm.cfg

Fix memory qemu cmd mapping pattern for new version

---

libvirt/tests/cfg/virtual_device/input_devices.cfg
libvirt/tests/cfg/virtual_device/video_devices.cfg
libvirt/tests/src/virtual_device/input_devices.py
libvirt/tests/src/virtual_device/video_devices.py

Add virtio packed test cases in:
1) input device
2) video device

Add virtio packed test cases in input and video devices

---

libvirt/tests/cfg/libvirt_rng.cfg
libvirt/tests/cfg/virsh_cmd/domain/virsh_setmem.cfg
libvirt/tests/src/libvirt_rng.py
libvirt/tests/src/virsh_cmd/domain/virsh_setmem.py

Add virtio packed test cases in rng and memballoon devices

Add virtio packed test cases in rng and memballoon devices

---

libvirt/tests/cfg/memory/hmat.cfg
libvirt/tests/src/memory/hmat.py

Add memory HMAT related test cases, including hmat and cell distances

Add memory HMAT related test cases

---

libvirt/tests/src/virsh_cmd/network/virsh_net_update.py

Extend the internal timeout for serial_login

---

libvirt/tests/cfg/numa/guest_numa.cfg
libvirt/tests/src/numa/guest_numa.py

- Start vm with missing vcpus in NUMA topology

Add 1 case of cpu management of numa

---

libvirt/tests/cfg/virsh_cmd/domain/virsh_blockcopy.cfg
libvirt/tests/src/virsh_cmd/domain/virsh_blockcopy.py

Cover auth in source or in disk scenarios, various option as well

Add enabled auth iscsi blockcopy cases

---

libvirt/tests/cfg/embedded_qemu/embedded_qemu.cfg
libvirt/tests/src/embedded_qemu/embedded_qemu.py

1.Test cmd options;
2.Test starting qemu process;
3.Test second driver supported;

Add testcases for embedded qemu driver

---

libvirt/tests/cfg/memory/hmat.cfg

Fix the hmat cache check changing

---

libvirt/tests/cfg/numa/guest_numa.cfg

PR #3196 fix this issue before but
#3159 revert it. So need to resubmit

Fix mapping pattern again for numa as some PR revert it

---

libvirt/tests/src/svirt/svirt_attach_disk.py

Replace old scsi controller with virtio-scsi controller to support
hotplug/unplug

Set controller for ppc test to support hotplug/unplug

---

v2v/tests/cfg/function_test_esx.cfg

Add a new checkpoint on an existing case for bz#1616226.

v2v: add a new rhv disk checkpoint for bz#1616226

---

v2v/tests/cfg/nbdkit/nbdkit.cfg
v2v/tests/src/nbdkit/nbdkit.py

Add a new case for nbdkit --run + vddk + esx7.0.

v2v: add a case for nbdkit --run+vddk+esx7.0

---

libvirt/tests/src/sriov/sriov.py

Add pcie slots to vm before attaching device to avoid errors like
"Not enough slots"

Fix up: pcie slots not enough for devices attaching

---

libvirt/tests/cfg/memory/hmat.cfg
libvirt/tests/src/memory/hmat.py

Fix the level value in qemu commandline check string

---

libvirt/tests/cfg/virtio_transitional/virtio_transitional_mem_balloon.cfg
libvirt/tests/src/virtio_transitional/virtio_transitional_mem_balloon.py

Add memory stats for virtio-{non}-transitional memballoon

Add memory stats for virtio-{non}-transitional memballoon

---

libvirt/tests/cfg/virsh_cmd/volume/virsh_vol_clone_wipe.cfg
libvirt/tests/cfg/virsh_cmd/volume/virsh_vol_resize.cfg
libvirt/tests/src/virsh_cmd/volume/virsh_vol_clone_wipe.py
libvirt/tests/src/virsh_cmd/volume/virsh_vol_resize.py

Add clone and resize volume cases for qcow2 encryption volume

Add clone and resize volume cases for qcow2 encryption volume

---

libvirt/tests/src/virsh_cmd/domain/virsh_migrate_copy_storage.py

This fix depends on https://github.com/avocado-framework/avocado-vt/pull/2866
1. Fix broken tear down
If `utlv.attach_disks` fails, `cp_mig` is not defined. Therefore, teardown breaks.
As a result, the second vm (suffix "_smtest") will still exist and break the next test
if it also tries to define a new vm with the same name.
2. Improve logging
The current log can be confusing as it shows
"Bug 1249587: error: Operation not supported: pre-creation of storage targets for incremental storage migration is not supported"
although it's only checking for that value in the command output.
Prepend the log message to explicitly state it's being checked.
3. Use lvm disk type and clean up
Using 'block' worked before but will now lead to an exception in `create_local_disk`.
Use 'lvm' instead.
'block' …

[virsh_migrate_copy_storage] Fix multi-disk lvm_image test cases

---

libvirt/tests/cfg/virtual_disks/virtual_disks_multidisks.cfg

Fix virtual_disks_multidisks test on aarch64

---

libvirt/tests/cfg/cpu/vm_features.cfg
libvirt/tests/src/cpu/vm_features.py

- Test vm with settings of feature: kvm poll-control

Add 1 case of vm features: kvm poll-control

---

libvirt/tests/cfg/controller/multiple_controller_ppc.cfg

Set multiple_controller_ppc tests to only run on pseries

---

libvirt/tests/src/virsh_cmd/host/virsh_sysinfo.py

virsh_sysinfo: add debug info

---

libvirt/tests/src/virtual_disks/virtual_disks_scsi3_persistent_reservation.py

Remove code for temporary workaround for bz 1658988

---

v2v/tests/src/function_test_xen.py
v2v/tests/src/specific_kvm.py
v2v/tests/src/v2v_options.py

This patch fixes the incorrect function name in
21dde01ecc5b12974c42cdb93d3f083e5dcce578.

v2v: update incorrect function name

---

libvirt/tests/cfg/virsh_cmd/domain/virsh_blockpull.cfg
libvirt/tests/src/virsh_cmd/domain/virsh_blockpull.py

It reports "File exists" when converting data sometimes. Update to
use a random image name and remove it before conversion.

virsh_blockpull: Fix an error while converting raw

---

provider/v2v_vmcheck_helper.py

v2v did some changes on rhel9 about the guest biostype, this patch
adapts the change.

v2v: fix boottype error on rhel9

---

v2v/tests/cfg/convert_vm_to_libvirt.cfg
v2v/tests/cfg/convert_vm_to_ovirt.cfg

Delete win7 and kvm info from v2v jobs

---

v2v/tests/cfg/nbdkit/nbdkit.cfg
v2v/tests/src/nbdkit/nbdkit.py

Add a case for checking max disk size change by memory plugin.

nbdkit: add a case for checking max disk size

---

v2v/tests/cfg/function_test_esx.cfg

Add a new case about copy_on_read.
Reference: bz#1466563

v2v: add a new case about copy_on_read

---

libvirt/tests/src/libvirt_scsi_hostdev.py

Update controller of ppc vms to support hotplug/unplug of scsi device

---

libvirt/tests/src/sriov/sriov.py

Package 'pciutils' provides command 'lspci'

sriov: install pkg 'pciutils' before command 'lspci'

---

libvirt/tests/cfg/virtual_disks/virtual_disks_luks.cfg
libvirt/tests/src/virtual_disks/virtual_disks_luks.py

RHEL-115615: cover both scenarios with luks encryption in source and out source

Add  luks disk blockcopy cases

---

libvirt/tests/cfg/libvirt_scsi_hostdev.cfg
libvirt/tests/src/libvirt_scsi_hostdev.py

RHEL-196550:Enable initiator in iscsi hostdev

Add case to cover initiator in iscsi hostdev

---

libvirt/tests/src/virtual_network/iface_update.py

- RHEL7-97268 - [update-device][link state] update interface link
status by update-device

Add case of update iface link

---

tp-libvirt_review_comment_summary.rst

1. remove a tag from domain definition and define from scratch instead of updating existing
2. make sure comments are still valid
3. wait don't sleep

[code review guide] extend review guide

---

libvirt/tests/src/migration/migrate_options_shared.py

1. Ping_vm is unstable. It's not a mandatory checkpoint for
migration cases, so we decide to remove it.
2. Update to access the migrated vm via console.
```
JOB ID     : ecd8c846d443b88f2ceccb498f9fa47d123d146c
JOB LOG    : /root/avocado/job-results/job-2021-03-22T03.22-ecd8c84/job.log
(1/1) type_specific.io-github-autotest-libvirt.virsh.migrate_options_shared. …
```

migrate_options_shared: some enhancements

---

v2v/tests/cfg/function_test_esx.cfg
v2v/tests/src/function_test_esx.py

v2v: add a new case about env leak

---

libvirt/tests/cfg/guest_agent.cfg
libvirt/tests/src/guest_agent.py

1) Added some cases of guest agent about guest agent state
check after restart libvirtd or guest life-cycle operation.
2) Added some cases of guest agent about hotunplug guest agent

Added some cases of guest agent

---

libvirt/tests/src/svirt/dac_nfs_disk.py
libvirt/tests/src/svirt/dac_nfs_save_restore.py

By replacing tmp_dir with data_dir

Fix errors caused by tmpfs

---

libvirt/tests/src/nwfilter/nwfilter_vm_start.py

There has been changes of function modify_vm_iface() to keep align,
therefore the value of param del_mac needs update.

nwfilter_vm_start: params value update for modify_vm_iface()

---

libvirt/tests/cfg/graphics/graphics_functional.cfg

Add testcase for vnc port 5900

---

libvirt/tests/cfg/virsh_cmd/domain/virsh_attach_detach_interface.cfg
libvirt/tests/src/virsh_cmd/domain/virsh_attach_detach_interface.py

- RHEL7-91214 - [attach-device][coalesce] hotplug with coalesce
settings in interface, then save and restore

Add new case of attaching iface with coalesce

---

libvirt/tests/cfg/cpu/vm_features.cfg
libvirt/tests/src/cpu/vm_features.py

Test Case: RHEL7-17930
This is to test enable or disable kvm hidden state vm feature.

Add cases for kvm hidden state

---

libvirt/tests/src/cpu/vcpu_hotpluggable.py

The command 'lscgroup' does not work well when cgroup v2 is enabled,
so update to use libvirt_cgroup.
_Before fix:_
```
(1/1) type_specific.io-github-autotest-libvirt.vcpu_hotpluggable.positive_test.vcpus_with_order: ERROR: Command 'lscgroup| grep cpuset| grep vm1| grep vcpu0' failed.\nstdout: b''\nstderr: b"cgroups can't be listed: Cgroup is not mounted\n"\nadditional_info: None (35.64 s)
```
_After fix:_
```
cgroup v2:
JOB LOG    : /root/avocado/job-results/job-2021-04-22T02.12-e30a63a/job.log
(1/1) type_specific.io-github-autotest-libvirt.vcpu_hotpluggable.positive_test.vcpus_with_order: PASS (29.81 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | …
```

Cgroup V2: update vcpu_hotpluggable cases

---

libvirt/tests/src/virsh_cmd/domain/virsh_attach_detach_disk.py

Fix attach_detach disk by switching get_tmp_dir to get_data_dir

---

libvirt/tests/cfg/virtual_network/iface_update.cfg
libvirt/tests/src/virtual_network/iface_update.py

Add new case of update interface with coalesce

---

libvirt/tests/cfg/virtual_network/iface_update.cfg
libvirt/tests/src/virtual_network/iface_update.py

- RHEL7-99419: [update-device][bandwidth] update the QoS setting
in interface by update-device with big value, negative value, or
floor without setting qos in network

Add case of updating iface

---

v2v/tests/cfg/function_test_esx.cfg

Add a new case for v2v --keys-from-stdin.

v2v: Add a new case about --keys-from-stdin

---

libvirt/tests/cfg/virtual_disks/virtual_disks_multidisks.cfg
libvirt/tests/src/virtual_disks/virtual_disks_multidisks.py

virtual_disks_multidisks: Fix "No more PCI slots" error for aarch64

---

v2v/tests/cfg/v2v_options.cfg
v2v/tests/src/v2v_options.py

Add a new case for weak dependency of libguestfs-xfs.

v2v: add a new case for weak denpendency of libguestfs-xfs

---

libvirt/tests/cfg/virsh_cmd/domain/virsh_attach_device.cfg
libvirt/tests/src/virsh_cmd/domain/virsh_attach_device.py

virsh_attach_device: Fix "No more PCI slots" error

---

libvirt/tests/cfg/memory/memory_hotplug.cfg
libvirt/tests/src/memory/memory_hotplug.py

- RHEL7-49082: Report memory hotunplug failure

Add memory hotplug test case

---

contributor_reviewer_maintainer_guidelines.rst

Add contributor,reviewer and maintainers guidelines

---

libvirt/tests/src/conf_file/qemu_conf/set_virtlogd.py

set_virtlogd: Update match message

---

libvirt/tests/cfg/numa/guest_numa.cfg

Already get approve with feature owner
```
(1/1) type_specific.io-github-autotest-libvirt.guest_numa.possitive_test.hugepage.per_node.2M.topology.numatune_memnode.m_strict.numatune_mem: PASS (46.08 s)
```

Remove the qemu cmd line check for guest_numa

---

libvirt/tests/cfg/virsh_cmd/domain/virsh_guestinfo.cfg
libvirt/tests/src/virsh_cmd/domain/virsh_guestinfo.py

Added the case for the option --disk of guestinfo

virsh_guestinfo: Added the the case of virsh guestinfo

---

libvirt/tests/src/virsh_cmd/domain/virsh_change_media_matrix.py

Depends on https://github.com/avocado-framework/avocado-vt/pull/2985

Add wait_for_event for change-media operation

---

v2v/tests/cfg/function_test_esx.cfg
v2v/tests/src/function_test_esx.py

v2v: add a case about vmware tools uninstallation

---

v2v/tests/cfg/convert_from_file.cfg

v2v: add a new case about unknown_vmware_controller_type

---

libvirt/tests/src/conf_file/qemu_conf/auto_dump.py

auto_dump: Fix the failure on /tmp dir

---

libvirt/tests/src/incremental_backup/incremental_backup_checkpoint_cmd.py

Description:
Checking the result of checkpoints deletion as the last step
of test cases. Otherwise we may miss the issue as bz1941600.
Polarion Case: RHEL-201477
Test result: PASS
signed-off-by: Yi Sun <yisun@redhat.com>

incremental_backup: Check the result of checkpoints deletion

---

libvirt/tests/src/virtual_network/iface_bridge.py

Use functions in utils_net to create or delete linux bridge. And deprecate the iface-unbridge usage because it is not supported on rhel9.

Use the functions in utils_net

---

libvirt/tests/cfg/virtual_disks/virtual_disks_vhostuser.cfg
libvirt/tests/src/virtual_disks/virtual_disks_vhostuser.py

RHEL-200286,RHEL-201775 vhostuser is new features to provison disk backend using vsock

Add vhostuser disk cases

---

libvirt/tests/cfg/virsh_cmd/domain/virsh_set_get_user_sshkeys.cfg
libvirt/tests/src/virsh_cmd/domain/virsh_set_get_user_sshkeys.py

link to 3 cases
RHEL-201779
RHEL-204986
RHEL-204987

virsh_set_get_user_sshkeys: Add cases for set/get-user-sshkeys commands

---

libvirt/tests/cfg/migration/live_migration.cfg
libvirt/tests/src/migration/live_migration.py

[RHEL-199044] [Migration][migrate_tls_force] Enable/disable
forced encrtypted migration in conf file

migration: Add migrate_tls_force case

---

libvirt/tests/src/virtual_disks/virtual_disks_multidisks.py

Replace data_dir.get_tmp_dir() with data_dir.get_data_dir

Fix filesystem does not support O_DIRECT issue on multidisk

---

libvirt/tests/cfg/virsh_cmd/domain/virsh_event.cfg
libvirt/tests/src/virsh_cmd/domain/virsh_event.py

Auto block-job(-2) event for blockcommit and blockcopy.

virsh_event: blockcommit and blockcopy

---

libvirt/tests/cfg/bios/virsh_boot.cfg

The error messages were updated recently, so update them.

virsh_boot: Update error message

---

libvirt/tests/cfg/virtual_disks/virtual_disks_blockcopy_options.cfg
libvirt/tests/src/virtual_disks/virtual_disks_blockcopy_options.py

RHEL-114380,RHEL-114485,RHEL-114486,RHEL-114498,RHEL-114499,RHEL-114942

Add blockcopy cases on transient_guest with various options

---

libvirt/tests/src/virsh_cmd/domain/virsh_memtune.py

Do cgroup2 compatible fix for memtune test

---

libvirt/tests/src/virsh_cmd/nodedev/virsh_nodedev_list.py

nodedev-list doesn't list devices that are not online but possibly
in use by other LPARs. Update code to only expect online devices to
be listed.

[nodedev-list] minor fix on ccw devices

---

libvirt/tests/src/virsh_cmd/network/virsh_net_dhcp_leases.py

Fix the format error

---

libvirt/tests/src/virtual_network/iface_bridge.py

Fix function name error

---

v2v/tests/cfg/convert_from_file.cfg
v2v/tests/src/convert_from_file.py

v2v: add a case of running v2v with sudo and regular user

---

v2v/tests/cfg/convert_from_file.cfg
v2v/tests/src/convert_from_file.py

see: polarion#RHEL-134140, bz#1570407

v2v: add new case for ova missing file

---

provider/v2v_vmcheck_helper.py
v2v/tests/cfg/function_test_esx.cfg
v2v/tests/src/function_test_esx.py

See: polarion_id#RHEL-241703 and bz#1868690

v2v: add a new case for converting a guest to a local block device

---

libvirt/tests/cfg/virsh_cmd/network/virsh_net_dhcp_leases.cfg

As the erroe message changes in new version of libvirt, update the error message.

Update the error message

---

libvirt/tests/cfg/memory/memory_discard.cfg

Increase current memory size to avoid vm crash in memory_discard

Increase current memory size

---

provider/migration/migration_base.py

migration_base: Fix None parameter

---

libvirt/tests/cfg/virtual_network/iface_stat.cfg
libvirt/tests/src/virtual_network/iface_stat.py

- RHEL7-103794: [domifstat] domiflist, domifstat, domifaddr for
direct type interface

Add new case of comparing iface stat

---

libvirt/tests/src/migration/migrate_vm.py

migrate_vm: Fix local variable 'xml_path' referenced before assignment

---

libvirt/tests/src/daemon/daemon_functional.py

Modular daemon: fix run daemon foreground  issues

---

libvirt/tests/src/cpu/aarch64_cpu_sve.py

[Minor fix] aarch64_cpu_sve.py: Fixup the pep8 error

---

v2v/tests/cfg/function_test_esx.cfg
v2v/tests/src/function_test_esx.py

Update the cases based on bz#1789279.

v2v: update rhv-disk-uuid cases

---

libvirt/tests/cfg/virtual_network/network_misc.cfg
libvirt/tests/src/virtual_network/network_misc.py

- RHEL-152038: [Virtual networks][zone] config the zone for the
libvirt manged bridge
- RHEL-152037: [Virtual networks][zone] libvirt nat network with
firewalld > v0.6.0

Add new cases of network zone

---

v2v/tests/cfg/function_test_esx.cfg
v2v/tests/cfg/function_test_xen.cfg
v2v/tests/src/function_test_esx.py

1) Update some code postions for improvement
2) Update some case configurations for script failure

v2v: update some code positons for improvement

---

libvirt/tests/cfg/cpu/vcpu_misc.cfg
libvirt/tests/src/cpu/vcpu_misc.py

Case ID: RHEL-242822
This case is to test maximum cpu mode.

vcpu_misc: Add case for max cpu mode

---

libvirt/tests/src/sriov/sriov_net_failover.py

Update to check tcpdump's output during ping cmd.
Furthermore, '8.8.8.8' was unreachable in some cases, so update
to get IP address to ping according to Env setup.
Test results: The failed case is caused by BZ.
```
+++++++++++++1+++++++++++++
JOB ID     : 4f41d7f3c3bbdeca6e77dca1b0d7a882e4b0f84c
JOB LOG    : /root/avocado/job-results/job-2021-07-08T02.41-4f41d7f/job.log
(1/3) …
```

sriov_net_failover: Add tcpdump checks

---

libvirt/tests/src/guest_resource_control/control_cgroup.py

[minorfix] control_cgroup: fix typo

---

libvirt/tests/cfg/migration/migrate_mem.cfg

Fix the qemu cmd line change related to memory in rhel9

Fix the qemu cmd line change in rhel9

---

libvirt/tests/cfg/libvirt_cputune.cfg
libvirt/tests/src/libvirt_cputune.py

Case ID: RHEL-115010
Test batch scheduler for vcpusched/emulatorsche
BTW, reorganize the existing codes for better structure and update a cache value rule for with cachetune test.

libvirt_cputune: add case for scheduler check

---

libvirt/tests/cfg/virsh_cmd/network/virsh_net_start.cfg
libvirt/tests/src/virsh_cmd/network/virsh_net_start.py

Add 2 test scenario about start default network after firewalld restart.

Start default network after firewalld service restart

---

provider/v2v_vmcheck_helper.py

In different v2v and rhel versions, the video and qxl driver may
be set to different values, and since the qxl are going to be
removed on rhel9, the old code won't adapt those changes and is
difficult to maintain. This patch makes a change to ease the pain.
1) Move the logic of detecting virtio-win to a single function, it
can be reused by other functions.
2) Separate the expected video logic per different target, and Modifies
the logic of expected video.
3) Fixes the expected qxl driver error in windows guests when video is
not 'qxl'.
4) Give one more try when exception happens during the checkping of windows guest.

v2v: refactor the video and qxl driver checkpoints

---

libvirt/tests/cfg/virsh_cmd/nodedev/crypto_nodedev_create_destroy.cfg
libvirt/tests/src/virsh_cmd/nodedev/crypto_nodedev_create_destroy.py

crypto: add crypto test case for nodedev-create and nodedev-destroy on
s390x
ID: 1865933
Signed-off-by: Boqiao Fu <bfu@redhat.com>

crypto: Add crypto test case on s390x

---

libvirt/tests/src/guest_resource_control/control_cgroup.py

For some systemd versions, the io.bfq.weight will be recaculated
to input_value/10, this will cause current script failures. This
patch is to cover this scenario. Detailed info about this action
can be found at bz1970830.

guest_resource_control: Deal with io.bfq.weight recaculation

---

libvirt/tests/src/sriov/sriov_net_failover.py

If the bridge interface is hot-plugged, the network accessibility
is unstable. And it's not a checkpoint of the case, so change to
cold-plug it. And update ping destination for
save_restore_hostdev_iface_with_teaming case.
Test result:
```
(1/4) type_specific.io-github-autotest-libvirt.sriov_net_failover.hotplug_hostdev_iface_with_teaming: PASS (115.54 s)
(2/4) type_specific.io-github-autotest-libvirt.sriov_net_failover.hotplug_hostdev_iface_with_teaming: PASS (114.15 s)
(3/4) type_specific.io-github-autotest-libvirt.sriov_net_failover.hotplug_hostdev_iface_with_teaming: PASS (114.47 s)
(4/4) type_specific.io-github-autotest-libvirt.sriov_net_failover.hotplug_hostdev_iface_with_teaming: PASS (115.57 s)
```
save-restore case fails because of a …

sriov: Fixup network connection unstable issues

---

v2v/tests/cfg/function_test_esx.cfg

Auto v2v case13018

---

v2v/tests/cfg/function_test_esx.cfg

see bz#1967941 or polarion#RHEL-254347

v2v: support installing qemu-guest-agent in rhel9

---

v2v/tests/cfg/function_test_esx.cfg

see bz#1959055 or case#RHEL-254341

v2v: add a new case about windows bitlocker disk

---

tp-libvirt_review_comment_summary.rst

Added conclusions from latest PR review meeting.

[code_review_guide] update with latest discussion items

---

v2v/tests/cfg/function_test_esx.cfg

check bz #1789279 and case RHEL-247914

v2v: add a scenario for option rhv-disk-uuid=UUID

---

v2v/tests/cfg/convert_from_file.cfg

Check bz#1964324 and case RHEL-247882.

v2v: add the case of converting ova image with folder ends with '/'
