autotest/tp-libvirt

- libvirt/tests/src/remote_access/remote_access.py
In remote acess testing, it reports "ERROR: local variable
'firewalld_port' referenced before assignment" once it fails to setup
ipv6 enviroment. The error message is unclear. So update it.
> minorfix: fix firewall_port UnboundLocalError

- libvirt/tests/src/virsh_cmd/snapshot/virsh_snapshot_create_as.py
Libvirt-5.5.0-2 commit 68e1a05f starts to allow --no-metadata and
--print-xml to be used together. So the expected failure will not
happen after the change.
> Fix a snapshot case failure due to libvirt change

- libvirt/tests/src/virsh_cmd/domain/virsh_blkiotune.py
There are more parameters for virsh.blkiotune now.
> Fix the virsh.blkiotune usage in case

- libvirt/tests/src/cpu/guestpin.py
- libvirt/tests/src/cpu/max_vcpus.py
- libvirt/tests/src/cpu/ppccpucompat.py
- libvirt/tests/src/cpu/setvcpu.py
- libvirt/tests/src/cpu/vcpu_affinity.py
- libvirt/tests/src/cpu/vcpu_hotpluggable.py
- libvirt/tests/src/libvirt_bench/libvirt_bench_vcpu_hotplug.py
- libvirt/tests/src/libvirt_vcpu_plug_unplug.py
- libvirt/tests/src/migration/migrate_vm.py
- libvirt/tests/src/numa/guest_numa.py
- libvirt/tests/src/numa/numa_memory.py
- libvirt/tests/src/numa/numa_memory_migrate.py
- libvirt/tests/src/resource_abnormal.py
- libvirt/tests/src/virsh_cmd/domain/virsh_dumpxml.py
- libvirt/tests/src/virsh_cmd/domain/virsh_emulatorpin.py
- libvirt/tests/src/virsh_cmd/domain/virsh_guestvcpus.py
- libvirt/tests/src/virsh_cmd/domain/virsh_migrate.py
- libvirt/tests/src/virsh_cmd/domain/virsh_numatune.py
- libvirt/tests/src/virsh_cmd/domain/virsh_setvcpu.py
- libvirt/tests/src/virsh_cmd/domain/virsh_setvcpus.py
- libvirt/tests/src/virsh_cmd/domain/virsh_vcpupin.py
- libvirt/tests/src/virsh_cmd/host/virsh_nodecpustats.py
- libvirt/tests/src/virsh_cmd/host/virsh_nodeinfo.py
- libvirt/tests/src/vm_boot_with_kernel_param.py
Let's modify the cpu library functions used in the
tests to match the re-order and grouping of library functions
addressed by below Patch(PR).
https://github.com/avocado-framework/avocado-vt/pull/2150
> Fixup: Modify cpu library functions

- libvirt/tests/src/virsh_cmd/domain/virsh_create.py
s390x don't have 'devices/video'. The test just checks for valid domxml.
Therefore, using disk device instead which is more common. Running the tests
manually passed.
> Fix invalid domxml check to be less platform dependent

- libvirt/tests/src/libvirt_qemu_cmdline.py
> Change mlock to mem-lock in qemu cmdline from libvirt 5.3

- libvirt/tests/cfg/virsh_cmd/domain/virsh_domrename.cfg
- libvirt/tests/src/virsh_cmd/domain/virsh_domrename.py
Rename a domain that configured as autostart. Make sure new
symlink is created, and domain can be autostarted well.
> virsh_domrename: rename vm with autostart set

- libvirt/tests/cfg/migration/migrate_vm.cfg
There are 2 unsupported cases in positive testing category.
So move them to negative_test, and update error message pattern for
the cases which have similar scenario.
> migration: move unsupported cases to negative_test

- libvirt/tests/src/migration/migrate_vm.py
- libvirt/tests/src/remote_access/remote_access.py
- libvirt/tests/src/virsh_cmd/domain/virsh_migrate_vm_cfg.py
TLS/TCP configurations cannot be recovered correctly before,
fix in this PR.
BTW, the error message is not clear in these tests,
so update it also.
> Fix environment recovery issue for remote_access

- libvirt/tests/cfg/virsh_cmd/domain/virsh_domid.cfg
- libvirt/tests/cfg/virsh_cmd/domain/virsh_domjobinfo.cfg
- libvirt/tests/cfg/virsh_cmd/domain/virsh_domuuid.cfg
- libvirt/tests/cfg/virsh_cmd/domain/virsh_domxml_to_native.cfg
- libvirt/tests/cfg/virsh_cmd/domain/virsh_managedsave.cfg
- libvirt/tests/cfg/virsh_cmd/domain/virsh_restore.cfg
- libvirt/tests/cfg/virsh_cmd/domain/virsh_shutdown.cfg
- libvirt/tests/cfg/virsh_cmd/monitor/virsh_domstate.cfg
- libvirt/tests/src/virsh_cmd/domain/virsh_domjobinfo.py
From libvirt 5.6.0 on issuing these commands won't result in error but succeed if the
rest of the paramters are valid. Blacklisting in CI will filter out those applicable
to each libvirt version.
This change must not be merged before blacklisting is set up.
Manual avocado runs showed that tests will pass. Will add CI run to PR comment.
> Add cases to test that libvirtd is automatically started

- libvirt/tests/cfg/libvirt_pci_passthrough.cfg
- libvirt/tests/src/libvirt_pci_passthrough.py
The PciAssignable class uses the "host_pf_filter" for the PCI Devices
to be pass-through'ed, and the same can be used in the test-case.
Now the user also have the flexibilty to create the desired no.of Virtual Functions,
for each Physical Function incase of SR-IOV.
Removed the device_name params for comparision of the PCI devices
before/after passthrough.
>  libvirt_pci_passthrough: refactor tests to use `host_pf_filter` for device pass-through.

- libvirt/tests/cfg/migration/migrate_options_shared.cfg
- libvirt/tests/src/migration/migrate_options_shared.py
All the cache modes are safe since libvirt 5.6.0-2 + qemu-kvm-4.0.0.
So update cases accordingly.
> Update cache mode related migration cases

- libvirt/tests/cfg/virtual_disks/virtual_disks_multivms.cfg
Since q35 machine types do not support ide controller, use sata disk
instead.
> virtual_disks_multivms: Replace ide cdrom with sata cdrom

- libvirt/tests/src/smt.py
Fixup below invalid Exception statement
```
except Exception, e:
^
SyntaxError: invalid syntax
```
> Fixup python3: Invalid Exception statement

- libvirt/tests/src/virtual_disks/startup_policy.py
For the cases of startup_policy...volume.dir_pool, virtual disk file
backend is moved when being used. Since Libvirt 5.6 introduces xattrs to
record file disk refcount, the actions above will cause VM start failure
due to refcount after moving the file disk back.
So I destroy VM before the file disk move.
> virtual_disks: Do not rename disk when it is being used

- libvirt/tests/src/virsh_cmd/domain/virsh_blockresize.py
The virtual size from output of qemu-img info changed from
"xxxG" to "xxx GiB", so the original re pattern failed to get the
size info.
> Fix a re pattern for virtual disk size

- libvirt/tests/src/virsh_cmd/domain/virsh_attach_detach_interface.py
- libvirt/tests/src/virsh_cmd/domain/virsh_attach_detach_interface_matrix.py
Removed check for 'brctl' because this dependency is not necessary.
Create a bridge interface on the host if none is available.
All failing tests passed on CI w/ this commit:
error_test.attach_with_script.type_br.non_exist
normal_test.vm_paused.exist_bridge.domid
normal_test.vm_paused.exist_bridge.domname
normal_test.vm_paused.exist_bridge.domuuid
normal_test.vm_running.exist_bridge.domid
normal_test.vm_running.exist_bridge.domname
normal_test.vm_running.exist_bridge.domuuid
> Fix missing bridge host configuration

- libvirt/tests/src/sriov/sriov.py
Correcting pci directory path to allow more than one root complex
Signed-off-by: Vishnu Pajjuri <vishnu.pajjuri@amperecomputing.com>
> SRIOV: correct pci driver directory path for SRIOV pci devices

- libvirt/tests/cfg/virsh_cmd/host/virsh_capabilities.cfg
- libvirt/tests/src/virsh_cmd/host/virsh_capabilities.py
This problem is introduced since RHEL-8.1AV; Running any virsh cmd will activate libvirtd service automatically on RHEL-8, so it is not possible to get expected result that virsh cmd will fail
after stop libvirtd.
After checking with libvirtd feature owner; manual cases will be added and this kind of auto case (check virsh cmd after stopping libvirtd) should be deleted.
> Fix failures caused by libvirt is activated automatically

- libvirt/tests/src/virtual_device/sound_device.py
Original error message would inform "VM pid file missing."
New behavior is to not continue test if vm cannot be started.
> Make tests fail if vm cannot be started

- libvirt/tests/cfg/sriov/sriov.cfg
The x710 is the device model name, and i40e is the driver name.
To keep the naming rules to be consistent, update the name accordingly.
> Update the config file to keep consistence

- libvirt/tests/cfg/virtual_network/iface_network.cfg
- libvirt/tests/src/virtual_network/iface_network.py
As libvirt 5.5 add the check that virtualport 802.1Qbg/h are only
supported in certain networks, the origianl unsupported setting
will fail to start. Delete the unsupported setting in nat networks.
> Delete the unsupported virtualport element in nat network

- libvirt/tests/cfg/virsh_cmd/network/virsh_net_update.cfg
- libvirt/tests/src/virsh_cmd/network/virsh_net_update.py
net_update.py: some network section do not support live update, so the
update command will report error. These cases were skipped before, update
the test resule to be pass. And add several negative cases.
> Fix: update unsupported case from skip to pass

- libvirt/tests/cfg/virsh_cmd/domain/virsh_domid.cfg
- libvirt/tests/cfg/virsh_cmd/domain/virsh_domjobinfo.cfg
- libvirt/tests/cfg/virsh_cmd/domain/virsh_domuuid.cfg
- libvirt/tests/cfg/virsh_cmd/domain/virsh_domxml_to_native.cfg
- libvirt/tests/cfg/virsh_cmd/domain/virsh_managedsave.cfg
- libvirt/tests/cfg/virsh_cmd/domain/virsh_restore.cfg
- libvirt/tests/cfg/virsh_cmd/domain/virsh_shutdown.cfg
- libvirt/tests/cfg/virsh_cmd/domain/virsh_undefine.cfg
- libvirt/tests/cfg/virsh_cmd/host/virsh_uri.cfg
- libvirt/tests/cfg/virsh_cmd/monitor/virsh_domstate.cfg
- libvirt/tests/src/virsh_cmd/domain/virsh_domid.py
- libvirt/tests/src/virsh_cmd/domain/virsh_domjobinfo.py
- libvirt/tests/src/virsh_cmd/domain/virsh_domuuid.py
- libvirt/tests/src/virsh_cmd/domain/virsh_domxml_to_native.py
- libvirt/tests/src/virsh_cmd/domain/virsh_managedsave.py
- libvirt/tests/src/virsh_cmd/domain/virsh_restore.py
- libvirt/tests/src/virsh_cmd/domain/virsh_save.py
- libvirt/tests/src/virsh_cmd/domain/virsh_shutdown.py
- libvirt/tests/src/virsh_cmd/domain/virsh_undefine.py
- libvirt/tests/src/virsh_cmd/host/virsh_hostname.py
- libvirt/tests/src/virsh_cmd/host/virsh_nodeinfo.py
- libvirt/tests/src/virsh_cmd/host/virsh_uri.py
- libvirt/tests/src/virsh_cmd/host/virsh_version.py
- libvirt/tests/src/virsh_cmd/monitor/virsh_domstate.py
libvirtd is restarted after issuing virsh commands from libvirt
version 5.6.0 on.
Removed separate libvirtd_auto_restart test definition from previous
PR.
Also, reviewed the libvirtd off test configuration has reasonable
parameters that should make the test pass if libvirtd is restarted
but should also pass if libvirtd is not restarted.
Tests now expect to pass if libvirtd was stopped but libvirt is at
least version 5.6.0 and before command was expected to fail.
> Fix test expectations when libvirtd is off

- libvirt/tests/cfg/virtual_network/iface_bridge.cfg
- libvirt/tests/src/virtual_network/iface_bridge.py
Use ip command to create bridge to replace the original iface-bridge
command as it is not stable. Execute the commands in tmux to avoid
breaking the host network. And newtork.service is not
recommended, replace it with NetworkManager service.
> Fix the network issue in iface_bridge.py

- v2v/tests/src/v2v_options.py
v2v prints multiple records into estimate file, json.load will reports
error. This patch search the related content before checking.
> Fix json read error for print-estimate in v2v

- libvirt/tests/src/virsh_cmd/domain/virsh_blockcopy.py
The bug mentioned in the script is already fixed in
libvirt-1.3.2-1.el7, but the failure message will always
be "Hit on bug xxx" if some errors captured. This will make
the log confusing if error happened. The fix here is to make
the log describe the problem more pricisely.
> Correct the failure message of block copy case

- libvirt/tests/cfg/cpu/max_vcpus.cfg
- libvirt/tests/cfg/cpu/vcpu_affinity.cfg
- libvirt/tests/cfg/virsh_cmd/domain/virsh_guestvcpus.cfg
- libvirt/tests/src/cpu/max_vcpus.py
- libvirt/tests/src/cpu/vcpu_affinity.py
1: Changing timeout from 60 to 180 for "vm.wait_for_login(timeout=start_timeout).close()"
to avoid some timeout expiring err in  vcpu_affinity.py and  vcpu_affinity.cfg file.
2: Changing max_vcpus.positive_test.i440fx_test.hotplug case as kernel performance:
Hot-plugging vcpus to 50 to VM after starting VM with 2 current vcpus and 240 total vcpus
3: For "# virsh guestvcpus --domain" negative cmd; the checking msg is wrong; so modify it
for case "virsh.guestvcpus.error_test.invalid_dom.no_dom"
> Fix 3 failures caused by short timeout; hotplugging vcpus performancec and err msg pattern

- libvirt/tests/src/remote_access/remote_access.py
It used old CA even there is a new one created in previous script.
So fix it.
> Fixup CA regenerate issue

- libvirt/tests/cfg/virtual_network/iface_options.cfg
- libvirt/tests/src/virtual_network/iface_options.py
Target dev can set in the guest interface xml including direct type and
network type interface. The name with prefix as "vnet" or "macvtap" may
be override.
> Check the target dev set in the interface xml

- libvirt/tests/src/virsh_cmd/domain/virsh_detach_device.py
The right tmp folder should referred to data_dir.get_tmp_dir
> Fix readonly mode disk test file type permission deny issue

- libvirt/tests/src/bios/virsh_boot.py
- libvirt/tests/src/migration/migrate_vm.py
- libvirt/tests/src/svirt/dac_vm_per_image_start.py
- libvirt/tests/src/virsh_cmd/domain/virsh_blockcommit.py
- libvirt/tests/src/virsh_cmd/domain/virsh_blockpull.py
- libvirt/tests/src/virsh_cmd/snapshot/virsh_snapshot_create_as.py
- libvirt/tests/src/virsh_cmd/snapshot/virsh_snapshot_disk.py
- libvirt/tests/src/virsh_cmd/volume/virsh_volume.py
- libvirt/tests/src/virtual_disks/virtual_disks_gluster.py
- libvirt/tests/src/virtual_disks/virtual_disks_luks.py
The function get_host_ipv4_addr and setup_or_cleanup_gluster are moved
from utils_test/libvirt, so update related scripts.
> Update scripts which call setup_or_cleanup_gluster or get_host_ipv4_addr

- libvirt/tests/cfg/migration/migrate_gluster.cfg
- libvirt/tests/src/migration/migrate_gluster.py
This PR automates a migration case which migrate vm with
mounted glusterfs.
So far, most of migration cases are based on NFS,
hence create a new py for migration with gluster cases.
> migration: automate migration with gluster backend disk case

- libvirt/tests/src/virsh_cmd/domain/virsh_domxml_to_native.py
LIBVIRTAT-5329,LIBVIRTAT-4626 New variables have been added to
domxml_to_native command. See
[libvirt][PATCH 0/3] Define XDG variables
https://www.redhat.com/archives/libvir-list/2019-March/msg00323.html
Test run output after this fix:
JOB ID     : 3616337bdc07ad1ae7e4963c170f229d104b6481
JOB LOG    : /var/lib/libvirt/qemu/domain--1-avocado-vt-vm1/avocado/job-results/job-2019-09-24T08.00-3616337/job.log
(1/1) type_specific.io-github-autotest-libvirt.virsh.domxml_to_native.negative_test.expected_option: PASS (95.14 s)
JOB TIME   : 96.68 s
JOB ID     : ca2dce59af362ac57f4386fec9d85313f6c36db4
JOB LOG    : /var/lib/libvirt/qemu/domain--1-avocado-vt-vm1/avocado/job-results/job-2019-09-24T08.02-ca2dce5/job.log …
> Add new variables to expected output for domxml-to-native

- libvirt/tests/src/papr_hpt.py
The original code is to create new cpu xml then set hpt/numa info
which could lead to info missing from original cpu xml. Now modify
to update original cpu xml which should fix the problem.
> Fix cpu xml attrs missing

- libvirt/tests/src/virsh_cmd/network/virsh_net_update.py
On rhel7.6 auto test, the hostname command on guest return the FDQN
(hostname+domain name), while on other releases, the "hostname" command
on guest return the only the hostname. The script only compare the hostname.
So update the string to only include the hostname.
> Fix the hostname not match issue

- libvirt/tests/src/remote_access/remote_access.py
Libvirtd on remote is failed to startup sometimes.
It's hard to reproduce in local environment. So add output of
'journalctl -xe' for future debugging.
> Update error message for future debugging

- libvirt/tests/src/virtual_disks/virtual_disks_multidisks.py
- libvirt/tests/src/virtual_network/iface_network.py
Since qemu v4.0.0(commit ee5d0f89de3), qemu disallows reboot-timeout set
beyond 0~0xffff. Because reboot-timeout is disabled by default, just
remove rebootTimeout for disabling.
> Do not set rebootTimeout to -1

- libvirt/tests/cfg/virtual_network/mtu.cfg
- libvirt/tests/src/virtual_network/mtu.py
Add interface model type as virtio, so it will hotplug to pcie slot
on Q35 machine type. If do not add specify the model type as virtio,
it will use rtl8139 and hotplug to pcie-to-pci bridge which may not
exists on the vm, which will cause hotplug failure.
> Fix the hotplug no pci slot issue

- libvirt/tests/cfg/virtual_network/iface_network.cfg
- libvirt/tests/src/virtual_network/iface_network.py
Libvirt has add the netmask to all ipv4 dhcp-range options since 5.1.
Check the netmask in dnsmasq config file.
> Check the netmask in network config file

- libvirt/tests/cfg/virtual_network/iface_network.cfg
- libvirt/tests/src/virtual_network/iface_network.py
Start guest with direct type interface when there are existing macvtap
devices created by other than libvirt.
> Start guest with direct type interface

- libvirt/tests/cfg/virtual_network/iface_hotplug.cfg
- libvirt/tests/src/virtual_network/iface_hotplug.py
Detach interface device can match by mac address or pci address, if both
are specified, both will be checked.
> Detach interface by different match

- libvirt/tests/cfg/virsh_cmd/network/virsh_net_start.cfg
- libvirt/tests/src/virsh_cmd/network/virsh_net_start.py
add only 1 case: type_specific.io-github-autotest-libvirt.virsh.net_start.route_test
all test cases pass:
$ run type_specific.io-github-autotest-libvirt.virsh.net_start
JOB ID     : 0663af4574e9318be583526d7dedba8770ffe935
JOB LOG    : /root/avocado/job-results/job-2018-09-05T18.42-0663af4/job.log
(01/12) type_specific.io-github-autotest-libvirt.virsh.net_start.normal_test.non_acl.valid_netname: PASS (8.63 s)
(02/12) type_specific.io-github-autotest-libvirt.virsh.net_start.normal_test.non_acl.valid_netuuid: PASS (7.43 s)
(03/12) type_specific.io-github-autotest-libvirt.virsh.net_start.normal_test.acl_test.valid_netname: PASS (9.91 s)
(04/12) type_specific.io-github-autotest-libvirt.virsh.net_start.normal_test.acl_test.valid_netuuid: PASS (9.73 s)
(05/12) …
> Check route

- libvirt/tests/src/virsh_cmd/domain/virsh_migrate.py
On s390x 'Model name' is not defined in lscpu. Set test to not support
compat_guest_migrate on s390x.
Test still fails on s390x with libvirt 5.4, qemu-kvm 2.12 but not due to change:
JOB ID     : 4771dd11927d42fe9efb8c5c15f0ee771dfdd690
JOB LOG    : /root/avocado/job-results/job-2019-10-16T05.11-4771dd1/job.log
(1/1) type_specific.io-github-autotest-libvirt.virsh.migrate.migrate_postcopy.without_cpu_hotplug.compat_migration.non_compat_migration.with_postcopy: ERROR: Command '/usr/bin/virsh migrate-setspeed avocado-vt-vm1 10 --postcopy' failed.\nstdout: b'\n'\nstderr: b"error: internal error: unable to execute QEMU command 'migrate-set-parameters': Parameter 'max-postcopy-bandwidth' is unexpected\n"\nadditional_info: Non... (374.39 s)
RESULTS    : PASS 0 | ERROR 1 | FAIL 0 | SKIP 0 | WARN …
> Safeguard Model name access on s390x

- libvirt/tests/cfg/virsh_cmd/domain/virsh_guestvcpus.cfg
- libvirt/tests/src/virsh_cmd/domain/virsh_guestvcpus.py
Error messages can be different at times
based on the additional commandline options or
libvirt version, let's add it in list to
handle multiple error messages.
in this case `nodomain name` testcase can have two error
messages based on domain option is passed or not.
```
error: command 'guestvcpus' requires <domain> option
error: expected syntax: --domain <string>
```
> Add support for multiple error messages

- libvirt/tests/src/virsh_cmd/domain/virsh_attach_device_matrix.py
For this test case:
Detach a device from paused vm, then resume it, wait 3 seconds then
check the detach result.
3 seconds is not enough for qemu to finish the detach actions after
resume. Extend it to 10 seconds.
> virsh_attach_device_matrix: Wait longer time after vm resume

- libvirt/tests/src/virtual_disks/virtual_disks_multidisks.py
The device ide-cd is introduced very early at qemu v0.15.0(commit 1f56e32a).
And no build configration to disable it. We can think it is defaultly
supported.
> virtual_disks_multidisks: Do not check ide-cd

- libvirt/tests/src/cpu/powerpc_hmi.py
Let's decode the dmesg output as text before using because
python3 complains the same.
> Fixup: python3: TypeError: a bytes-like object is required, not 'str'

- libvirt/tests/src/cpu/ppccpucompat.py
A recently patch has added virttest.cpu into this file, which has
the same name as avocado.utils.cpu, caused massive failures.
Rename one module to avoid this kind of conflict.
> Rename imported cpu module from avocado to avoid conflict

- libvirt/tests/src/virsh_cmd/domain/virsh_edit.py
virsh edit test cases uses vi editor regex to edit vmxml
if editor is not configured or if virsh uses other editor
like nano, all the tests fails.
> virsh_edit: set vim as $EDITOR in os.environ to use its regex

- libvirt/tests/src/virsh_cmd/domain/virsh_domxml_to_native.py
https://github.com/libvirt/libvirt/commit/2d69af29073aa3dc2dc5b79afcecaa703b81125a introduced new variables from 5.2.0.
https://github.com/autotest/tp-libvirt/pull/2338 made tests fail on older versions.
Added libvirt version switch to make pass in both versions.
Executed tests:
libvirt 4.5/qemu-kvm 2.12
```bash
JOB ID     : 09d7eaadf15d2c7ab582449b8c98a8c1feacf1e0
JOB LOG    : /root/avocado/job-results/job-2019-10-23T20.22-09d7eaa/job.log
(1/3) type_specific.io-github-autotest-libvirt.virsh.domxml_to_native.positive_test.id_option: PASS (26.31 s)
(2/3) type_specific.io-github-autotest-libvirt.virsh.domxml_to_native.positive_test.uuid_option: PASS (35.28 s)
(3/3) type_specific.io-github-autotest-libvirt.virsh.domxml_to_native.positive_test.name_option: PASS (33.91 s)
RESULTS    : PASS 3 | …
```
> Add version switch for domxml_to_native

- v2v/tests/cfg/function_test_esx.cfg
- v2v/tests/src/function_test_esx.py
Add new auto case for rhel-170557:Virt-v2v can convert guest which has a file without file_architecture
Signed-off-by: liuzi <zili@redhat.com>
> add new auto case for v2v RHEL-170557

- libvirt/tests/src/cpu/vcpu_hotpluggable.py
platform.dist() is removed from python3.8 version, let's
replace it with avocado.utils, distro.detect() method to
handle it for all python versions.
> Fixup: replace platform.dist deprecated method

- libvirt/tests/src/virsh_cmd/domain/virsh_domdisplay.py
on rhel8, the server-key.pem and ca-key.pem generated by default
only have 600 file permission. Here change them to 644 to avoid
test failures. And exchange the function description between
clean_ssl_env() and prepare_ssl_env().
> virsh_domdisplay.py: fix 'r' mod for *-key.pem

- libvirt/tests/cfg/virsh_cmd/monitor/virsh_domstats.cfg
- libvirt/tests/src/virsh_cmd/monitor/virsh_domstats.py
nowait option enable domstats result can returned quickly although
the other thread may concurrently operate on the same virtual machine
> add nowait option for virsh domstats commands

- v2v/tests/cfg/convert_from_file.cfg
- v2v/tests/src/convert_from_file.py
Copy ova before converting to save time and add rhev output to
cover ova cases of convert_from_file in rhel8 AV and rhel7-rhev
jobs.
> Add copy function and rhev output for v2v ova cases

- libvirt/tests/src/virsh_cmd/domain/virsh_vcpuinfo.py
- libvirt/tests/src/virsh_cmd/host/virsh_nodecpustats.py
From libvirt version 5.6.0 libvirt service will start even
if the service is stopped while running virsh commands, let's
handle it for the negative tests which expects the command
failure when libvirt service is stopped.
> Handle automatic libvirtd start while running virsh commands

- libvirt/tests/src/virsh_cmd/domain/virsh_managedsave.py
From libvirt-5.6.0, libvirtd can be auto started by systemd socket
activation, which makes vm autostart work unexpectedly. A fix in
rhbz#1755303 resolves this, "/run/libvirt/qemu/autostarted" can
make sure vm autostart only once when host reboot. Here, remove
this file before start libvirtd, to achieve vm autostart without
host reboot.
> managedsave.py: rm a file to make vm autostart

- libvirt/tests/cfg/migration/migrate_options_shared.cfg
migrate_options_shared.cfg: The actual charchannel index depends on the
domain xml. With s390-virtio domain xml channel index is 0. I couldn't find a
reason why this index should be pass/fail criterion, therefore, using less restrictive
regular expression for qemu cmd check.
Tests on s390x:
```bash
JOB ID     : 3faac2a63bf0545fcfaccfb8357dd0f7b355344b
JOB LOG    : /root/avocado/job-results/job-2019-11-04T16.50-3faac2a/job.log
(1/2) type_specific.io-github-autotest-libvirt.virsh.migrate_options_shared.positive_test.pty_channel.with_postcopy: PASS (200.68 s)
(2/2) type_specific.io-github-autotest-libvirt.virsh.migrate_options_shared.positive_test.pty_channel.without_postcopy: PASS (214.47 s)
JOB TIME   : …
```
> Ignore channel index in qemu command

- libvirt/tests/src/virsh_cmd/domain/virsh_undefine.py
when `attach-disk` fails then subsequent virsh undefine with
`--remove-storage` will not work/remove the storage as it not
attached to VM. This will fail the test without proper reason,
so check the return status for virsh attach-disk and error out
appropriately.
> virsh_undefine: check for virsh attach-disk return value

- libvirt/tests/src/graphics/graphics_functional.py
When start guest with '0 < (port = tlsPort) <= 65535', the error
message is "internal error: Failed to reserve port XXX".
> graphics_functional: Add a fail pattern

- libvirt/tests/cfg/virtual_device/watchdog.cfg
- libvirt/tests/src/virtual_device/watchdog.py
On s390x only watchdog model is diag288.
1. watchdog.cfg:
a. diag288 only supported on s390x
b. hotplugging watchdog device is not supported on s390x
2. watchdog.py:
a. extract method to try load watchdog kernel module to be reusable
b. diag288_wdt doesn't emit messages. Add output to test log but
don't fail test if watchdog driver doesn't emit messages.
Sample logged message: 
```bash
2019-10-30 17:43:59,080 watchdog         L0049 INFO | dmesg watchdog messages: [    2.061611] i6300esb: Intel 6300ESB WatchDog Timer Driver v0.05
[    2.069133] i6300esb: initialized (0xffffaf8c401fd000). heartbeat=30 sec (nowayout=0)
```
Tests on s390x
```bash
JOB ID     : 6251658b562704825caa982faac6fb7024bbf3f6
JOB LOG    : /root/avocado/job-results/job-2019-10-30T15.14-6251658/job.log
(1/7) …
```
> Add watchdog for s390x

- libvirt/tests/src/virsh_cmd/snapshot/virsh_snapshot_disk.py
In rhel8, when attach a disk during vm booting process, the disk
could not be used in vm, this is a potential bug. Change the code
to bypass it.
> Workaround a disk attaching issue

- libvirt/tests/cfg/virsh_cmd/nodedev/virsh_nodedev_dumpxml.cfg
Device type pci is not available on s390x.
> Fix nodedev_dumpxml on s390x

- libvirt/tests/cfg/cpu/vcpu_cache.cfg
- libvirt/tests/src/cpu/vcpu_cache.py
Add some virtual L3 cache tests in this PR.
1. L3 cache with host-model cpu mode
2. L3 cache with host-passthrough cpu mode
3. L3 cache with none cpu mode
4. invalid cache info
depends on https://github.com/avocado-framework/avocado-vt/pull/2303.
> Add L3 cache cases

- libvirt/tests/cfg/migration/migrate_options_shared.cfg
- libvirt/tests/src/migration/migrate_options_shared.py
This PR covers below cases:
live migration with parallel network connections:
a. default network connections
b. specified connection number
c. boundary values of connection number
d. without enabling parallel capability
> Add new cases for multiple File Descriptor support

- libvirt/tests/cfg/serial/serial_functional.cfg
- libvirt/tests/src/serial/serial_functional.py
1. cfg:
a. type_dev_sclplm: add case to test line mode console
b. type_pty_pci_serial: pci-serial not supported on arch
c. type_spiceport: spice not supported on arch
2. py:
a. set_targets: set default target, use target_model to test
line mode console explicitly
b. check_qemu_cmdline: provide test expectations on platform for
sclp-serial
c. new locals to hold value for new test case
4. fixed escape sequences issues for W605
Test run on s390x
```bash
JOB ID     : 9c63a1ce0245be03259c3dfafd5ebb1f140d1092
JOB LOG    : /root/avocado/job-results/job-2019-11-06T09.21-9c63a1c/job.log
(01/18) type_specific.io-github-autotest-libvirt.serial.functional.type_dev: PASS (6.39 s)
(02/18) type_specific.io-github-autotest-libvirt.serial.functional.type_dev_sclplm: PASS (6.55 s)
(03/18) …
```
> Fix serial_functional on s390x

- libvirt/tests/src/virsh_cmd/domain/virsh_sendkey.py
This fix requires https://github.com/avocado-framework/avocado-vt/pull/2312
On s390x running zipl command is required after updating boot loader entries
(with grubby), see https://bugzilla.redhat.com/show_bug.cgi?id=1764306#c2
In other words, running grubby and then rebooting without zipl won't change
cmdline.
Tests on s390x, libvirt 4.5/qemu-kvm 2.12
```bash
JOB ID     : 41da65922c8a2ca09e86429b87bc15002d9fd28a
JOB LOG    : /root/avocado/job-results/job-2019-10-28T12.54-41da659/job.log
(01/30) type_specific.io-github-autotest-libvirt.virsh.sendkey.params_test.non_acl.without_codeset: PASS (164.55 s)
(02/30) type_specific.io-github-autotest-libvirt.virsh.sendkey.params_test.non_acl.linux_keycode: PASS (128.51 s)
(03/30) type_specific.io-github-autotest-libvirt.virsh.sendkey.params_test.non …
```
> Pass vm_arch_name to ensure zipl is called on s390x guest

- libvirt/tests/cfg/bios/virsh_boot.cfg
- libvirt/tests/cfg/controller/controller_functional.cfg
- libvirt/tests/cfg/libvirt_bench/libvirt_bench_usb_hotplug.cfg
- libvirt/tests/cfg/libvirt_usb_hotplug_controller.cfg
- libvirt/tests/cfg/libvirt_usb_hotplug_device.cfg
- libvirt/tests/cfg/usb_device.cfg
- libvirt/tests/cfg/usb_passthrough.cfg
- libvirt/tests/cfg/virsh_cmd/domain/virsh_attach_device.cfg
- libvirt/tests/cfg/virtual_device/input_devices.cfg
- libvirt/tests/cfg/virtual_disks/at_dt_iscsi_disk.cfg
- libvirt/tests/cfg/virtual_disks/virtual_disks_multidisks.cfg
- libvirt/tests/cfg/virtual_disks/virtual_disks_usb.cfg
On s390x USB is not available. Adding filter to avoid running them
in the first place.
> Do not test usb on s390x

- libvirt/tests/cfg/graphics/graphics_functional.cfg
- libvirt/tests/src/graphics/graphics_functional.py
3 cases added:
1. Set valid and existing 'vnc_tls_x509_secret_uuid' in qemu.conf;
2. Set invalid 'vnc_tls_x509_secret_uuid' in qemu.conf;
3. Set valid but non-existing 'vnc_tls_x509_secret_uuid' in qemu.conf;
> Add testcases for 'vnc_tls_x509_secret_uuid' in qemu.conf

- libvirt/tests/cfg/migration/migrate_options_shared.cfg
- libvirt/tests/src/migration/migrate_options_shared.py
So far, firewall cleanup part will be executed by every cases in
migrate_options_shared, which is redundancy. So fix up this issue
in this PR.
> migration: Update to set firewall for special cases only

- libvirt/tests/src/virsh_cmd/snapshot/virsh_snapshot_create_as.py
Found the wrong syntax in the code and fixed the same
```
TypeError: not enough arguments for format string
```
Signed-off-by: Kalaiarasan Panneerselvam <panneer1@in.ibm.com>
> virsh_snapshot_create_as: Fix syntax error in formatting string

- libvirt/tests/cfg/virsh_cmd/pool/virsh_pool_capabilities.cfg
- libvirt/tests/src/virsh_cmd/pool/virsh_pool_capabilities.py
Check the pool capability information and execute with wrong option and libvirtd offline.
Signed-off-by: jgao12345 <jgao@redhat.com>
JOB ID     : 9c506b45ed13427723d4325032a56ea5b73c36a2
JOB LOG    : /root/avocado/job-results/job-2019-09-27T03.32-9c506b4/job.log
(1/3) type_specific.io-github-autotest-libvirt.virsh.pool_capabilities.no_option: PASS (4.58 s)
(2/3) type_specific.io-github-autotest-libvirt.virsh.pool_capabilities.unexpect_option: PASS (5.43 s)
(3/3) type_specific.io-github-autotest-libvirt.virsh.pool_capabilities.with_libvirtd_stop: PASS (6.50 s)
JOB TIME   : 22.25 s
> Check output of command "virsh pool-capability"

- v2v/tests/cfg/function_test_esx.cfg
- v2v/tests/src/function_test_esx.py
Because v2v code changed on 2018.11.01
https://github.com/libguestfs/virt-v2v/commit/c1c4ed4c16e83a83d6d2835e05d6adf97836db70#diff-31c097437346a8f33915e8de88c011d2
we need to delete related cases which use parameter copy_to_local to convert guest from ESXI.
> Delete v2v cases about parameter copy_to_local

- libvirt/tests/src/virsh_cmd/domain/virsh_console.py
To avoid influence from slow shutdown process such as ppc vms.
It sometimes takes more than 60s(default) to completely shutdown
a ppc vm.
Otherwise case will fail as timeout waiting for shutdown command
to complete.
> Set timeout of shutdown command to 120s

- libvirt/tests/cfg/migration/migrate_with_legacy_guest.cfg
- libvirt/tests/src/migration/migrate_with_legacy_guest.py
This PR adds 2 migration cases:
1. Migrate RHEL6 guest with virtio-transitional model disk and
controller
2. Migrate guest with virtio/-transitional model
type interface to another rhel8 host
> migration: add cases about disk/interface virtio-transitional model

- libvirt/tests/src/virsh_cmd/domain/virsh_sendkey.py
Reverts autotest/tp-libvirt#2394
Depends on avocado-vt 2312
> Revert "Pass vm_arch_name to ensure zipl is called on s390x guest"

- libvirt/tests/cfg/migration/migrate_vm.cfg
- libvirt/tests/src/migration/migrate_vm.py
Below cases are included in this PR:
1. negative testing:
1) migration vm without shareable/cache when target image is/isn't present on target host
2) migration vm with shareable and none/directsync cache when target image is/isn't present on target host
2. positive testing:
1) migration vm with --unsafe option when target image is present on target host.
> Add migration with local filesystem backed disk cases

- v2v/tests/cfg/convert_from_file.cfg
- v2v/tests/cfg/function_test_xen.cfg
- v2v/tests/cfg/specific_kvm.cfg
- v2v/tests/src/convert_from_file.py
- v2v/tests/src/function_test_xen.py
- v2v/tests/src/specific_kvm.py
1) If skip_check is set, VM will not be cleaned from ovirt server.
This patch fixed it.
2) Update skip_check to skip_vm_check
> Fix vm cleanup issue when skip checking

- provider/v2v_vmcheck_helper.py
- v2v/tests/cfg/function_test_xen.cfg
- v2v/tests/src/function_test_esx.py
- v2v/tests/src/function_test_xen.py
1) Add checking for Suse and Debian based systems
2) Add memory and rng device checking for all targets
3) Remove Xorg log checking, only check video by lspci
4) A fix to format_convert
5) Replace params[x] with params.get(x) to avoid exception
> Adjust checkpoints for linux guests

- libvirt/tests/src/virsh_cmd/domain/virsh_migrate.py
All the cache modes are safe since libvirt 5.6.0-2 + qemu-kvm-4.0.0.
So udpate it.
> migration: update cache unsafe cases

- libvirt/tests/src/remote_access/remote_access.py
It reports error AttributeError at end of execution even it passed.
The objects need to be removed dirrectly in finally block for remote
access cases, so update to skip cleanup in GC.
> Fix AttributeError for remote_access

- libvirt/tests/cfg/conf_file/qemu_conf/auto_dump.cfg
- libvirt/tests/src/conf_file/qemu_conf/auto_dump.py
1. cfg:
a. Define s390x specific model test and exclude from all others
because this is the only valid panic model
2. py/run:
a. Remove duplicated code
b. Add s390x for same conditions
Run tests on s390x:
```bash
JOB ID     : 7ac39fe99119874e70e1449f2c8bf57415f934b1
JOB LOG    : /root/avocado/job-results/job-2019-12-04T11.01-7ac39fe/job.log
(1/3) type_specific.io-github-autotest-libvirt.conf_file.qemu_conf.auto_dump.s390_model.default_bypass_cache: PASS (68.29 s)
(2/3) type_specific.io-github-autotest-libvirt.conf_file.qemu_conf.auto_dump.s390_model.enable_bypass_cache: PASS (72.32 s)
(3/3) type_specific.io-github-autotest-libvirt.conf_file.qemu_conf.auto_dump.s390_model.disable_bypass_cache: PASS (63.14 s) …
```
> Fix qemu_conf test on s390x

- libvirt/tests/cfg/cpu/vcpu_misc.cfg
- libvirt/tests/src/cpu/vcpu_misc.py
This PR adds 2 cpu vendor_id cases -
Start VM with AuthenticAMD/GenuineIntel vendor_id attribute.
depends on https://github.com/avocado-framework/avocado-vt/pull/2350
> Add cases about cpu vendor_id

- libvirt/tests/src/virsh_cmd/domain/virsh_autostart.py
- libvirt/tests/src/virsh_cmd/domain/virsh_domrename.py
From libvirt-5.6.0, libvirtd can be auto started by systemd socket
activation, which makes vm autostart work unexpectedly. A fix in
rhbz#1755303 resolves this, "/run/libvirt/qemu/autostarted" can
make sure vm autostart only once when host reboot. Here, remove
this file before start libvirtd, to achieve vm autostart without
host reboot.
> virsh_autostart:  rm a file to make vm autostart

- libvirt/tests/cfg/cpu/vm_features.cfg
- libvirt/tests/src/cpu/vm_features.py
Automated below 2 cases in this PR:
1. start VM with/without pvspinlock feature
2. start VM with/without relaxed feature
Since some of qemu command line changed from libvirt 5.x,
updated expected pattern for hyperv feature accordingly.
> Add 2 cases about pvspinlock and relaxed feature

- libvirt/tests/cfg/cpu/vcpu_cache.cfg
> CPU cache specification is not supported for 'ppc64le' architecture

- provider/v2v_vmcheck_helper.py
- v2v/tests/cfg/convert_from_file.cfg
- v2v/tests/src/convert_from_file.py
By default, v2v will try to connect to source hypervisor
to get vm information, like disk path in esx, etc.
But in some testing envrionment, it don't have source
hypervisor, such as gating envrionment, we need to skip
the step of connecting to the hypervisor.
> Fix gating failure in OSP

- libvirt/tests/cfg/virsh_cmd/domain/virsh_migrate.cfg
- libvirt/tests/src/virsh_cmd/domain/virsh_migrate.py
currently utils_package can fail to install `stress` tool as it
may not available in the repo, using VMStress() install and run it.
> virsh_migrate: reuse VMStress() to trigger stress in VM

- libvirt/tests/cfg/virsh_cmd/domain/virsh_migrate.cfg
currently postcopy test will run with just enabling postcopy
flag but without actual postcopy migration. add option
`--postcopy-after-precopy` to perform postcopy migration.
> virsh_migrate: add --postcopy-after-precopy for postcopy tests

- libvirt/tests/cfg/virsh_cmd/pool/virsh_pool.cfg
I need to use fixed 'pool_source-name' for usage with a static gluster server.
Add parameter explicitly (with default value) to test configuration in order
to easily replace 'pool_source_name' to existing name.
Executed test:
```bash
JOB ID     : 3fdd87d5e4f523e3b1e35e15151cd316b2f5b215
JOB LOG    : /root/avocado/job-results/job-2019-12-18T15.55-3fdd87d/job.log
(1/1) type_specific.io-github-autotest-libvirt.virsh.pool.positive_test.pool_type_netfs.source_format_glusterfs: PASS (9.51 s)
JOB TIME   : 11.11 s
```
> Add paramter explicitly to test config

- libvirt/tests/cfg/virsh_cmd/pool/virsh_pool_autostart.cfg
I need to use a fixed 'pool_source_name' for usage with a static gluster server.
Add parameter explicitly to test configuration (with default value) in order to easily replace
'pool_source_name' to existing name.
Executed tests:
```bash
JOB ID     : 0ecb6a12b63fb08f8fe6e9f0a11600217f739293
JOB LOG    : /root/avocado/job-results/job-2019-12-18T12.39-0ecb6a1/job.log
(1/4) type_specific.io-github-autotest-libvirt.virsh.pool_autostart.positive_test.name_option.pool_type_netfs.source_format_glusterfs: PASS (6.69 s)
(2/4) type_specific.io-github-autotest-libvirt.virsh.pool_autostart.positive_test.name_option.pool_type_gluster: PASS (7.88 s)
(3/4) type_specific.io-github-autotest-libvirt.virsh.pool_autostart.positive_test.uuid_option.pool_type_netfs.source_format_glusterfs: PASS (6.95 s)
(4/4) …
```
> Add parameter explicitly to test config

- libvirt/tests/cfg/controller/controller_functional.cfg
- libvirt/tests/src/controller/controller_functional.py
On s390x default controller address type is ccw.
1. get_controller_addr:
a. Use same pattern for addr_string to join values for ccw
b. New parameter to determine which bus type to test for
2. check_controller_addr:
a. New parameter to determine which bus type to test for
b. Confirm virtio-ccw devices must
have their cssid set to 0xfe.
3. check_guest:
a. Extract method to improve readability
b. Add method to cover bus type ccw on s390x
4. check_ccw_bus_type:
a. Check that device is present in guest by its number using
s390x specific lszdev command
```bash
JOB ID     : 7262f676746f5e05deb8d90df25238ace435396e
JOB LOG    : /root/avocado/job-results/job-2019-12-04T06.58-7262f67/job.log
(1/1) type_specific.io-github-autotest-libvirt.controller.functional.positive_tests.virtio …
```
> Handle controller address on s390x

- libvirt/tests/cfg/cpu/vcpu_misc.cfg
- libvirt/tests/src/cpu/vcpu_misc.py
One case in vendor_id must be skipped due to compatibility problem
in previous code. Fix it to set vendor_id according to host info.
> Fix cpu vendor_id case skipping issue

- libvirt/tests/cfg/virsh_cmd/domain/virsh_blockcopy.cfg
- libvirt/tests/src/virsh_cmd/domain/virsh_blockcopy.py
if --transient-job option is given, even acting blockcopy job is interupted by accident,
the job doesn't recover.
> add --transient-job option case in blockcopy

- libvirt/tests/cfg/virtual_disks/virtual_disks_ceph.cfg
- libvirt/tests/src/virtual_disks/virtual_disks_ceph.py
After libvirt 3.9.0, auth element can be placed in source part, as
well as disk directly.
> add auth is placed in source part when using ceph

- libvirt/tests/src/virsh_cmd/snapshot/virsh_snapshot_create_as.py
1. s390-ccw-virtio uses virtio 1.0 per default in QEMU. This means
if disk device is 'lun' the target bus must be 'scsi' instead of
'virtio', see https://bugzilla.redhat.com/show_bug.cgi?id=1365823
test run on s390x:
```bash
JOB ID     : ffdf2e262e43e96b5c5c1cbd21354182afddfc69
JOB LOG    : /root/avocado/job-results/job-2019-12-23T05.54-ffdf2e2/job.log
(1/1) type_specific.io-github-autotest-libvirt.virsh.snapshot_create_as.negative_tests.network_disk.iscsi.device_lun: PASS (173.22 s)
JOB TIME   : 174.82 s
```
> Fix snapshot_create_as device_lun on s390-ccw-virtio

- libvirt/tests/cfg/virsh_cmd/domain/virsh_event.cfg
- libvirt/tests/src/virsh_cmd/domain/virsh_event.py
1. lifecycle_events.general:
a. .general currently contains all lifecycle events. This leads to
long test run and low test precision.
b. Proposal is to test at most two related lifecycle events in the
same test case to improve test precision.
2. wait_for_shutoff:
a. If no_timeout test failed before vm actually had shut off. This
took longer on z/VM. Added wait-for loop to avoid early failure.
```bash
JOB ID     : c259599ce946ad26459467767b2932b678a563d9
JOB LOG    : /root/avocado/job-results/job-2019-12-03T06.25-c259599/job.log
(1/8) type_specific.io-github-autotest-libvirt.virsh.event.positive_test.virsh_event.test_events.lifecycle_events.create_destroy.no_timeout.loop: PASS (19.21 s)
(2/8) type_specific.io-github-autotest-libvirt.virsh.event.positive_test.virsh_event.t …
```
> Split general lifecycle_events into groups

- v2v/tests/cfg/convert_from_file.cfg
- v2v/tests/cfg/convert_vm_to_libvirt.cfg
- v2v/tests/cfg/convert_vm_to_ovirt.cfg
- v2v/tests/cfg/function_test_esx.cfg
- v2v/tests/cfg/function_test_xen.cfg
- v2v/tests/cfg/specific_kvm.cfg
- v2v/tests/cfg/v2v_options.cfg
- v2v/tests/src/v2v_options.py
1) Remove customized ssh_key setup function and use v2v_setup_ssh_key
in utils_v2v instead.
2) Remove all plain passwords in cfg files.
3) Some code formats changes by autopep8
> Use v2v_setup_ssh_key in utils_v2v instead of customized function

- libvirt/tests/src/virtual_disks/virtual_disks_multivms.py
Hardcode controller index may lead to conflict
and cause VM definition failure
> Fix multiple vm case failures

- libvirt/tests/cfg/virtual_disks/virtual_disks_gluster.cfg
- libvirt/tests/src/virtual_disks/virtual_disks_gluster.py
if third party gluster server is provisioned, this can be specified
in cfg file.
> enable specified gluster server in config file

- libvirt/tests/src/virtual_device/vsock.py
1. remove_all_vsocks:
a. When domain xml already had <vsock> communication tests failed because
originally <vsock> was only removed from xml but not from domain.
2. alias_name:
a. Use uuid instead of string module to simplify code.
3. global variables:
a. Setup in env_setup can take quite some time as it depends both
on machine performance and connectivity. Avoid early timeouts by
using CMD_TIMEOUT on all setup commands.
b. nc-vsock:
i.) use variables to build paths and commands for reusability and
readability
ii.) put input and output files below /tmp/nc-vsock to assure
they are removed, too
4. env_setup:
a. no need to use index to iterate over commands
b. use status and output to fail early instead of executing all
c. create/rename methods to make code more readable
d. time.sleep: the …
> Fix vsock tests on s390x

- libvirt/tests/src/virsh_cmd/domain/virsh_schedinfo_qemu_posix.py
when restarting VM after setting schedinfo with --config
- rhel.virsh.schedinfo_qemu_posix.normal_test.set_cpu_param.set_cpu_shares
- value_negative.set_by_cmd.config.valid_domid.running_guest
- value_zero.set_by_cmd.config.valid_domid.running_guest
- value_normal.set_by_cmd.config.valid_domid.running_guest
- value_maximum.set_by_cmd.config.valid_domid.running_guest
- value_exceed.set_by_cmd.config.valid_domid.running_guest
> Fix the schedinfo_valid_domid cases by getting right domid

- libvirt/tests/src/virsh_cmd/domain/virsh_detach_device_alias.py
The following cases will be influenced:
- rhel.virsh.detach_device_alias.live.hostdev
- rhel.virsh.detach_device_alias.config.hostdev
- rhel.virsh.detach_device_alias.current.hostdev
> Fix err caused by no "lsusb" cmd for hostdev cases

- libvirt/tests/src/virsh_cmd/domain/virsh_detach_device_alias.py
The cmd "detach-device-alias" will return "Device detach request sent successfully" immediately,
which may cause that the related device info will not take effect in the dumpxml/guest os that fast.
So add some wait time for this cmd.
The following two cases will be influenced:
- virsh.detach_device_alias.current.controller
- virsh.detach_device_alias.live.controller
> Fix err caused by no wait time for "virsh detach-alias" cmd

- libvirt/tests/cfg/virsh_cmd/domain/virsh_setvcpu.cfg
Cases with 2_threads will be running only on PPC64.
The following cases will be influenced:
rhel.virsh.setvcpu.normal_test.guest_on.with_comma.with_2_threads.id_option.option_enable_live
rhel.virsh.setvcpu.normal_test.guest_on.with_comma.with_2_threads.id_option.option_enable
rhel.virsh.setvcpu.normal_test.guest_on.with_comma.with_2_threads.id_option.option_enable_current
rhel.virsh.setvcpu.normal_test.guest_on.with_comma.with_2_threads.id_option.option_disable_live
rhel.virsh.setvcpu.normal_test.guest_on.with_comma.with_2_threads.id_option.option_disable
rhel.virsh.setvcpu.normal_test.guest_on.with_comma.with_2_threads.id_option.option_disable_current
rhel.virsh.setvcpu.normal_test.guest_on.with_comma.with_2_threads.name_option
rhel.virsh.setvcpu.normal_test.guest_on.with_comma.with_2_thr …
> Fix err caused by "virsh setvcpu" with two threads running on X86_84

- libvirt/tests/cfg/migration/migrate_with_legacy_guest.cfg
- libvirt/tests/src/migration/migrate_with_legacy_guest.py
This PR adds migration tests for rng/mem balloom virtio
transitional model.
depends on https://github.com/avocado-framework/avocado-vt/pull/2310
> migration: Add virtio transitional model tests for rng/mem

- libvirt/tests/cfg/guest_resource_control/control_cgroup.cfg
- libvirt/tests/src/guest_resource_control/control_cgroup.py
Now we have cgroup v2 enabled in rhel8, there are some cases about
guest resource control devided in virsh_cmd folder, and these cases
using cgroup v1 as a background. Here the new scripts are suitable
for both cgroup v1 and v2, and orgnized together. This will be
easier to be maintained.
> Add cases for guest resource control

- libvirt/tests/cfg/virsh_cmd/domain/virsh_setvcpus.cfg
- libvirt/tests/src/virsh_cmd/domain/virsh_setvcpus.py
This PR adds setvcpus related cases.They are as follows:
1. Update "maximum/current" vcpus numbers by setvcpus
2. Hot-plug/unplug vCPU without <acpi> feature
3. Restart VM after changing inactive maxvcpu/current vcpus conf
4. Check maximum vcpus number with topology settings when guest is
shutdown/running
> cpu: Add setvcpus cases

- libvirt/tests/src/controller/controller_functional.py
one error message:Invalid PCI address 0000:04:00.0. slot must be >= 1
will be thrown if slot is <1
> fix controller slot is less than zero issue

- libvirt/tests/cfg/virsh_cmd/domain/virsh_detach_serial_device_alias.cfg
- libvirt/tests/src/virsh_cmd/domain/virsh_detach_serial_device_alias.py
virsh_detach_device_alias is used to detach device by its alias name.
> add new cases to cover virsh command:virsh_detach_device_alias

- libvirt/tests/cfg/libvirt_rng.cfg
Also remove the timeout as default is 600s and 30s may
not enough for the cmd return
> Update the period for rng rate test

- libvirt/tests/src/migration/migrate_vm.py
Reverting https://github.com/autotest/tp-libvirt/pull/2485
1. `get_virtual_size` always returns string, a match of `(\d+\w)` e.g. 10G
2. Currently, test fails:
```bash
JOB ID     : b561dadcdc32865e7e53416fb4f772fd96f400b9
JOB LOG    : /root/avocado/job-results/job-2020-01-08T02.57-b561dad/job.log
(1/1) type_specific.io-github-autotest-libvirt.virsh.migrate_vm.positive_testing.live_migration.iscsi.ipv6.with_postcopy: ERROR: invalid literal for int() with base 10: '10G' (31.77 s)
```
Test run after reverting:
```bash
JOB ID     : 39efd349460c779c781273f1f69f00ab68fd9b2a
JOB LOG    : /root/avocado/job-results/job-2020-01-08T03.09-39efd34/job.log
(1/1) type_specific.io-github-autotest-libvirt.virsh.migrate_vm.positive_testing.live_migration.iscsi.ipv6.with_postcopy: PASS (205.20 s)
RESULTS …
```
> Revert 'fixed type error: Added letter 'G' to image_size'

- libvirt/tests/src/virsh_cmd/nodedev/virsh_nodedev_event.py
It reports "IndexError: list index out of range" during nodedev
event test. Event is not received if detach action
coming after reattch action without any standby period.
So increase the waiting time between 'reattach' and 'detach' and
add size checking to avoid IndexError.
> Fix IndexError for nodedev event

- provider/v2v_vmcheck_helper.py
- v2v/tests/cfg/convert_from_file.cfg
- v2v/tests/cfg/convert_vm_to_libvirt.cfg
- v2v/tests/cfg/convert_vm_to_ovirt.cfg
- v2v/tests/cfg/function_test_esx.cfg
- v2v/tests/cfg/function_test_xen.cfg
- v2v/tests/cfg/specific_kvm.cfg
- v2v/tests/cfg/v2v_options.cfg
1) Changed the way of checking video module
2) Fixed checking RNG device fail problem on old RHEL guests
3) Hidden guest password from cfg files.
4) Delete sles from xen cases, sles11 has very low priority,
sles12 has been covered in matrix testing
> Fix some checking issues in public checkpoint

- libvirt/tests/src/svirt/dac_start_destroy.py
After libvirt-5.6.0, libvirt will restore the label after guest shutdown.
> Modify the lable checking after libvirt-5.6.0

- libvirt/tests/cfg/virsh_cmd/domain/virsh_detach_device_alias.cfg
On s390x there's no USB. Redirdev is only for USB device.
> Remove redirdev test for s390x

- libvirt/tests/cfg/cpu/vcpu_cache.cfg
CPU cache specification is not supported for 's390x' architecture
> Remove vcpu_cache test for s390x

- libvirt/tests/src/virsh_cmd/domain/virsh_attach_detach_disk.py
Currently, tests fail when `at_dt_disk_additional_lvs` is not defined
in test cfg with message `AttributeError: 'NoneType' object has no attribute 'split'`
Define default value `""`.
Test run:
```bash
JOB ID     : 8b50cae645885ed0c867c1a383e5ace44cd4ab1e
JOB LOG    : /root/avocado/job-results/job-2020-01-09T14.07-8b50cae/job.log
(1/2) type_specific.io-github-autotest-libvirt.virsh.attach_detach_disk.detach_disk.error_test.no_vm_name: PASS (38.34 s)
(2/2) type_specific.io-github-autotest-libvirt.virsh.attach_detach_disk.detach_disk.normal_test.host_block_vm_id: PASS (29.49 s)
JOB TIME   : 69.20 s
```
> Fix virsh_attach_detach_disk

- libvirt/tests/cfg/vm_boot_with_kernel_param.cfg
- libvirt/tests/src/vm_boot_with_kernel_param.py
On s390x BOOT_IMAGE is not populated by qemu bootloader,
s. https://bugzilla.redhat.com/show_bug.cgi?id=1782026
1. cfg: Add test case. Expect to hold for all archs.
2. py: Add switch to check guest cmdline.
Test run on x86_64:
```bash
JOB ID     : 33e99a1f69c1977d77f5a8f7ac540a803fe7a754
JOB LOG    : /root/avocado/job-results/job-2019-12-12T16.39-33e99a1/job.log
(1/1) type_specific.io-github-autotest-libvirt.vm_boot_with_kernel_param.check_kernel_cmdline: PASS (15.50 s)
JOB TIME   : 16.88 s
```
Test run on s390x (fails as expected due to bz):
```bash
JOB ID     : 67594feb217b73a73a5c97d81bcfc69a5ed75e77
JOB LOG    : /root/avocado/job-results/job-2019-12-12T10.49-67594fe/job.log
(1/1) …
```
> Check cmdline for subexpression

- libvirt/tests/cfg/virsh_cmd/domain/virsh_attach_device.cfg
- libvirt/tests/src/virsh_cmd/domain/virsh_attach_device.py
On s390x only one single serial is allowed per model (sclpconsole|sclplmconsole).
If the domain xml already has a serial of that type defined a second one cannot
be attached.
1. serial, no s390-virtio:
a. Skip default test cases in favor of specific tests for s390-virtio (s. below)
2. serial_s390x, sclp_twice, sclplm_twice:
a. Implemenet new arch specific test cases:
|First device target model|Second device target model|Expected result|
|-------------------------|--------------------------|---------------|
|no device|sclpconsole|OK - attach and start|
|no device|sclplmconsole|OK - attach and start|
|sclpconsole|sclpconsole|ERROR "Multiple VT220 operator consoles are not supported"|
|sclplmconsole|sclplmconsole|ERROR "Multiple line-mode operator consoles are not supported"| …
> Fix attach_devices serial on s390x

- libvirt/tests/src/virsh_cmd/domain/virsh_schedinfo_qemu_posix.py
For some negative tests, it tries to get non-existing items from
schedinfo's output. In this case, an empty list will be returned,
so checking the list is necessary in finally block.
> Fix IndexError for virsh schedinfo tests

- libvirt/tests/src/libvirt_vcpu_plug_unplug.py
It reports UnboundLocalError: local variable 'bt' referenced
before assignment, so fixup this issue.
> Fix the issue of local variable 'bt' referenced before assignment

- libvirt/tests/src/migration/migrate_vm.py
In finally block, it removed disk resource but not vm on remote.
Fix this issue in this PR.
> Need to cleanup vm on remote for migration test

- libvirt/tests/src/virsh_cmd/pool/virsh_pool_autostart.py
Remove the pool autostart management file so that we can test the status of pool without rebooting the host.
Signed-off-by: jgao <jgao@localhost.localdomain>
> Fix the pool-autostart status failed

- libvirt/tests/cfg/virsh_cmd/domain/virsh_cpu_compare_xml.cfg
Incorrect error message makes automation case failed. Update it.
> Update error message for invalid case of virsh_cpu_compare_xml

- libvirt/tests/cfg/libvirt_bench/libvirt_bench_vcpu_hotplug.cfg
These pkgs are necessary for these test, they should be installed
inside vm before test.
> Add dependency pkgs to libvirt_bench stress tests

- v2v/tests/cfg/convert_vm_to_libvirt.cfg
- v2v/tests/cfg/convert_vm_to_ovirt.cfg
- v2v/tests/cfg/function_test_esx.cfg
- v2v/tests/cfg/specific_kvm.cfg
The vddk_libdir_src settings are moved to avocado-vt.
avocado-vt:
backends/v2v/cfg/convert_source.cfg
> Delete vddk_libdir_src from tp-libvirt

- libvirt/tests/src/virtual_disks/virtual_disks_multidisks.py
On s390x addresses are of type 'ccw'. The attribute
reflecting order of attachment is 'devno' instead
test run on s390x:
```bash
JOB ID     : 609085704e0aa5c339f7ebae2bb29fa1294524de
JOB LOG    : /root/avocado/job-results/job-2020-01-20T10.19-6090857/job.log
(1/1) type_specific.io-github-autotest-libvirt.virtual_disks.multidisks.coldplug.multi_disks_test.virtio_disks_order: PASS (104.12 s)
JOB TIME   : 107.32 s
```
> Fix disk order test on s390x

- libvirt/tests/src/virtual_device/tpm_device.py
When tpm_v got from dmesg is none, the further judge in
get_host_tpm_bef will encounter issue if use 'elif'. Replace it
with 'if'. Also the tpm_real_v need be initialized.
> tpm_dev: fix judge in get_host_tpm_bef

- libvirt/tests/cfg/virtual_network/iface_coalesce.cfg
- libvirt/tests/cfg/virtual_network/iface_hotplug.cfg
On s390x only interface model available is 'virtio'.
> Restrict interface model on s390x

- libvirt/tests/cfg/virsh_cmd/domain/virsh_attach_detach_disk.cfg
On s390x cdrom are connected via SCSI, IDE is not available.
test run on s390x:
```bash
JOB ID     : 816b99f0e06073549782f942e024437d5a6a2ddb
JOB LOG    : /root/avocado/job-results/job-2020-01-20T13.00-816b99f/job.log
(1/1) type_specific.io-github-autotest-libvirt.virsh.attach_detach_disk.attach_disk.normal_test.cdrom_eject_control: PASS (210.90 s)
JOB TIME   : 212.42 s
JOB ID     : 29c27ecc04f6141256781ec43f1cb32bac1db98e
JOB LOG    : /root/avocado/job-results/job-2020-01-20T13.09-29c27ec/job.log
(1/2) type_specific.io-github-autotest-libvirt.virsh.attach_detach_disk.attach_disk.normal_test.cdrom: PASS (202.53 s)
(2/2) type_specific.io-github-autotest-libvirt.virsh.attach_detach_disk.detach_disk.normal_test. …
```
> Fix cdrom device on s390x

- libvirt/tests/cfg/virtual_disks/startup_policy.cfg
On s390x cdrom are attached through 'scsi' bus.
Tests run
```bash
JOB ID     : 8d08c48f6ef56454a046616f3a9e9ee573d83138
JOB LOG    : /root/avocado/job-results/job-2020-01-21T09.47-8d08c48/job.log
(1/7) type_specific.io-github-autotest-libvirt.startup_policy.startupPolicy.mandatory.device_type.cdrom.file.default: PASS (178.19 s)
(2/7) type_specific.io-github-autotest-libvirt.startup_policy.startupPolicy.mandatory.device_type.cdrom.file.update_policy.default.live: PASS (102.72 s)
(3/7) type_specific.io-github-autotest-libvirt.startup_policy.startupPolicy.mandatory.device_type.cdrom.file.update_policy.default.config: PASS (89.12 s)
(4/7) type_specific.io-github-autotest-libvirt.startup_policy.startupPolicy.mandatory.device_type.cdrom.file.update_policy.default.persistent: PASS (98.22 s) …
```
> Fix startup_policy on s390x

- libvirt/tests/src/virsh_cmd/snapshot/virsh_snapshot_edit.py
1. Got index error from debug logging; avoid this by making index access safe.
Originally, due to environment issue I got 
```bash
2020-01-31 10:57:40,872 stacktrace       L0047 ERROR|   File "/var/lib/avocado/data/avocado-vt/test-providers.d/downloads/io-github-autotest-libvirt/libvirt/tests/src/virsh_cmd/snapshot/virsh_snapshot_edit.py", line 178, in run
2020-01-31 10:57:40,872 stacktrace       L0047 ERROR|     after_xml.split()[i].lstrip())
2020-01-31 10:57:40,872 stacktrace       L0047 ERROR| IndexError: list index out of range
```
During test execution. But test passes now; however, the code should avoid `IndexError` in the future.
Test execution s390x
```bash
JOB ID     : 90a0bfa34b46c2752222946523f18f09d29c2cf4
JOB LOG    : …
```
> Safeguard debug logging

- libvirt/tests/src/libvirt_mem.py
1. Missing parameters in function call:
`ERROR: check_qemu_cmd() missing 2 required positional arguments: 'max_mem_rt' and 'tg_size'`
Add params to function call.
Test run
```bash
JOB ID     : cc237c0963a7175bb982f50efde7aa1c958f2209
JOB LOG    : /root/avocado/job-results/job-2020-01-10T16.40-cc237c0/job.log
(1/3) type_specific.io-github-autotest-libvirt.libvirt_mem.positive_test.mem_basic.discard: PASS (42.28 s)
(2/3) type_specific.io-github-autotest-libvirt.libvirt_mem.positive_test.hugepages.no_numatune.discard: PASS (51.94 s)
(3/3) type_specific.io-github-autotest-libvirt.libvirt_mem.positive_test.hugepages.with_numatune.discard: PASS (47.40 s)
JOB TIME   : 143.12 s
```
> Fix libvirt_mem..discard

- libvirt/tests/cfg/virsh_cmd/domain/virsh_detach_device.cfg
Libvirt disabled virtio bus as cdrom device since v5.1.0(commit
5d884f3d3). Update tp-libvirt script accordingly.
> virsh_detach_device: Don't use virtio bus for cdrom

- libvirt/tests/cfg/serial/serial_functional.cfg
- libvirt/tests/src/serial/serial_functional.py
If the domain xml already defines a console of target type virtio,
the test correctly fails.
Allow for explicit removal of console devices from configuration, instead.
This way, in case of an existing virtio console we can have the test remove
it before continuing making the test pass.
No impact on existing tests.
```bash
JOB ID     : 066ed731a847e5d5a13fc921126aa5f7b0a650cf
JOB LOG    : /root/avocado/job-results/job-2020-02-03T11.36-066ed73/job.log
(1/3) type_specific.io-github-autotest-libvirt.serial.functional.type_pty: PASS (5.96 s)
(2/3) type_specific.io-github-autotest-libvirt.serial.functional.console_target_type_virtio: PASS (5.44 s)
(3/3) type_specific.io-github-autotest-libvirt.serial.functional.test_only_first_console_be_serial: PASS (4.60 s)
RESULTS    : PASS 3 | ERROR 0 | …
```
> Add configuration parameter to serial functional

- libvirt/tests/cfg/cpu/max_vcpus.cfg
The maxvcpus depends on many factors and should not be a fixed value
for pseries or s390x.
> The output of maxvcpu is not consistent among multi-archs

- libvirt/tests/cfg/cpu/setvcpu.cfg
- libvirt/tests/cfg/virsh_cmd/domain/virsh_attach_detach_interface.cfg
The original start_time was set to 60s which might be sufficient
for x86 vms but not pseries vms. In 60s ppc vms might not finish
booting up yet. Setting timeout to 240s could easily fix this
problem
> Set start_time to 240s for pseries to fix ip missing issue

- libvirt/tests/src/libvirt_rng.py
1. Use available timeout config value everywhere
2. VirtTest doesn't have 'skip'. Use 'test.cancel' to skip
> Fix libvirt_rng

- libvirt/tests/cfg/virsh_cmd/domain/virsh_sendkey.cfg
- libvirt/tests/src/virsh_cmd/domain/virsh_sendkey.py
1. On s390x panic device is automatically added. Avoid adding device.
```bash
(.libvirt-ci-venv-ci-runtest-50xirU) [root@ibm-z-101 tp-libvirt]# avocado run --vt-type libvirt --vt-machine-type s390-virtio --vt-connect-uri qemu:///system virsh.sendkey.sysrq.non_acl.crash_guest
JOB ID     : 7772a889c5427d38d09ec34b3d00e69dc14025ca
JOB LOG    : /root/avocado/job-results/job-2020-01-21T10.53-7772a88/job.log
(1/1) type_specific.io-github-autotest-libvirt.virsh.sendkey.sysrq.non_acl.crash_guest: PASS (478.88 s)
JOB TIME   : 483.69 s
(.libvirt-ci-venv-ci-runtest-50xirU) [root@ibm-z-101 tp-libvirt]# avocado run --vt-type libvirt --vt-machine-type s390-virtio --vt-connect-uri qemu:///system …
```
> Fix virsh_sendkey on s390x

- libvirt/tests/cfg/virtual_disks/virtual_disks_multivms.cfg
On s390x cdrom is connected through scsi.
Test run:
```bash
JOB ID     : 90b3bbed49169840834b2edd90332d11c0fd4ab1
JOB LOG    : /root/avocado/job-results/job-2020-01-22T11.50-90b3bbe/job.log
(1/1) type_specific.io-github-autotest-libvirt.virtual_disks.multivms.coldplug.vms_readonly_test: PASS (267.95 s)
JOB TIME   : 270.28 s
```
> Fix virtual_disks multivms on s390x

- libvirt/tests/cfg/virtual_disks/virtual_disks_iscsi.cfg
- libvirt/tests/src/virtual_disks/virtual_disks_iscsi.py
On s390x addresses are type ccw by default and don't allow for partial definition.
The test uses `controller_addr_options` exclusively for valid controller
definition, i.e. it's not a test condition.
Therefore, on s390x allow libvirt to add valid address by not setting any.
```bash
JOB ID     : ae1b4ef61c019c1d70b04a01c57f0864a5310b02
JOB LOG    : /root/avocado/job-results/job-2020-01-21T11.22-ae1b4ef/job.log
(1/1) type_specific.io-github-autotest-libvirt.virtual_disks.iscsi.iscsi_test.normal_test.device_lun.auth_uuid.auth_place_in_source: PASS (309.37 s)
JOB TIME   : 312.89 s
```
> Fix virtual_disk device_lun on s390x

- libvirt/tests/cfg/libvirt_mem.cfg
- libvirt/tests/src/libvirt_mem.py
Fix checking the memory-backing-file for non-file memory device issue and attach  devices more than one time with unique alias issue.
> Fix the check_qemu_cmd function issue

- libvirt/tests/cfg/numa/guest_numa.cfg
Now the qemu cmd line changed from
4,sockets=2,cores=2,threads=1
to
4,sockets=2,dies=1,cores=2,threads=1
> Fix for libvirt new configure CPU 'dies'

- libvirt/tests/cfg/cpu/guestpin.cfg
- libvirt/tests/cfg/cpu/powerpc_hmi.cfg
Stress tests requires stress test tool installed which requies
pkgs 'gcc, make' installed inside vms.
> Add pkg dependency list to powerpc_hmi and guestpin stress tests

- libvirt/tests/src/numa/numa_memory_migrate.py
In case cannot get vm state correctly and qemu thread will continue
to exist which will effect future tests.
> Shutdown vm before libvirtd exit

- v2v/tests/cfg/function_test_esx.cfg
- v2v/tests/src/function_test_esx.py
For this case, guest can't boot into os without selecting by user
after v2v conversion, so skip checking guest
> Skip checkpoint for v2v option_root.dev_sdx case

- libvirt/tests/cfg/cpu/iothread.cfg
- libvirt/tests/src/cpu/iothread.py
This PR adds cases as follows:
1) configuration tests for iothreadids,iothreads,iothreadpin
and iothreadsched
2) check for iothreadadd/del/pin operation
3) check for iothread with disk attached
4) set and check iothread parameters when vm is running
5) configure iothread_quota/iothread_period for vm
without defining iothreads
depends on: https://github.com/avocado-framework/avocado-vt/pull/2399 and https://github.com/avocado-framework/avocado-vt/pull/2398
> Add iothread cases

- libvirt/tests/cfg/virsh_cmd/domain/virsh_attach_detach_disk.cfg
- libvirt/tests/cfg/virtual_disks/startup_policy.cfg
The usage of `machine_type == X` has been found to have side effects,
s. https://github.com/autotest/tp-libvirt/pull/2523#discussion_r375134579
Fix as described.
Did not run tests because the change was tested on referenced PRs.
> Fix test configuration

- libvirt/tests/cfg/virsh_cmd/domain/virsh_attach_detach_disk.cfg
Depends on https://github.com/avocado-framework/avocado-vt/pull/2427
On s390x disks are attached per default as ccw.
test execution on s390x
```bash
JOB ID     : c4e4cda240df20b5db1fbe63b4e1047e59a22983
JOB LOG    : /root/avocado/job-results/job-2020-02-10T14.11-c4e4cda/job.log
(1/3) type_specific.io-github-autotest-libvirt.virsh.attach_detach_disk.attach_disk.normal_test.vm_shutdown_config: PASS (632.01 s)
(2/3) type_specific.io-github-autotest-libvirt.virsh.attach_detach_disk.attach_disk.normal_test.twice_multifunction: PASS (671.05 s)
(3/3) type_specific.io-github-autotest-libvirt.virsh.attach_detach_disk.attach_disk.normal_test.twice_multifunction_with_shareable: PASS (625.14 s)
JOB TIME   : 1950.83 s …
```
> Fix address check attach disk s390x

- libvirt/tests/cfg/migration/migrate_options_shared.cfg
In previous libvirt code, VIR_DOMAIN_EVENT_SUSPENDED_POSTCOPY
event was wrongly added on the destination host. It got fixed
recently, so update in migration test accordingly.
> migration: remove SUSPENDED_POSTCOPY event on the destination

- libvirt/tests/cfg/timer_management.cfg
> timer type 'platform' is not supported by pseries

- v2v/tests/src/convert_vm_to_libvirt.py
- v2v/tests/src/convert_vm_to_ovirt.py
- v2v/tests/src/function_test_xen.py
- v2v/tests/src/v2v_options.py
The original code created a new VMChecker instance to cleanup
the VM. But this way cannot close virsh session correclty.
The code should use the primary instance to cleanup.
> Fix issue of wrong usage cleanup function in VMChecker

- libvirt/tests/cfg/virtual_disks/virtual_disks_multidisks.cfg
- libvirt/tests/src/virtual_disks/virtual_disks_multidisks.py
Depends on https://github.com/avocado-framework/avocado-vt/pull/2415
1. .py:
a. minimal_xml: Currently, hard-coded domain xml refers to x86_64 arch
and pc machine type. Read these values from params dictionary instead.
b. test_bus_device_option: Construct cmd differently when address type ccw.
Note that by default "libvirt will assign a free bus address with cssid=0xfe and ssid=0"
https://libvirt.org/formatdomain.html#elementsAddress
Therefore `dev_id_prefix` is taken here to be constant.
c. ccw_address expected failure: Since qemu 2.12 ccsid values are unrestricted,
s. https://wiki.qemu.org/Features/Channel_I/O_Passthrough#QEMU_.28since_2.12.29
d. check_readonly:
i. If IDE is not available (e.g. q35, s390x) cdrom is mounted as scsi
which normally should start with 'sd'.
ii. Add check for …
> Fix multidisks on s390x

- libvirt/tests/src/virsh_cmd/domain/virsh_console.py
In order to ease timeout tuning on slow environments
1. extract command timeout value
2. increase hard coded value
```bash
JOB ID     : b7494845bbacdcbda2bd844f766724a875782cd9
JOB LOG    : /root/avocado/job-results/job-2020-02-17T07.47-b749484/job.log
(1/1) type_specific.io-github-autotest-libvirt.virsh.console.normal_test.non_acl.valid_domname: PASS (357.30 s)
JOB TIME   : 376.60 s
```
> Extract timeout variable

- libvirt/tests/src/virsh_cmd/snapshot/virsh_snapshot_disk.py
when test case is trying to attach the disk to the VM, it got cancelled.
Actually it should throw the error if it is not able to attach it.
So this test case code has modified from CANCEL to ERROR.
Suggested-by: Balamuruhan S <bala24@linux.ibm.com>
Signed-off-by: Kalaiarasan Panneerselvam <panneer1@in.ibm.com>
> virsh_snapshot_disk: modified the test case status from CANCEL to ERROR

- libvirt/tests/src/virsh_cmd/domain/virsh_domtime.py
Recent distributions like Ubuntu 20.04, date command
output format changed, hence the below error,
ValueError: time data 'Sat 08 Feb 2020 01:00:25 IST' does not match format '%a %b %d %H:%M:%S %Y
So let's handle it by forcing the date command output with
a format string, though this can be generic for all distributions,
there may be some old distributions might not support format string
with date command, so let's handle it in failure path not to break
tests in other environments.
> Handle date output format change

- v2v/tests/cfg/convert_vm_to_ovirt.cfg
- v2v/tests/cfg/function_test_esx.cfg
- v2v/tests/src/function_test_esx.py
1) The default value of rhv-verifypeer is false, explicitly add cases
for rhv-verifypeer=true.
2) Add one case when rhv-verifypeer=true but rhv-cafile is an invalid
ca file.
> Add rhv-verifypeer=true cases and one invalid pem case

- libvirt/tests/src/libvirt_vcpu_plug_unplug.py
test.warn is undefined from avocado and according to comments of
this piece of code, we could replace 'warn' with 'cancel'
> Replace 'warn' with 'cancel' of libvirt_vcpu_plug_unplug

- libvirt/tests/cfg/virsh_cmd/domain/virsh_sendkey.cfg
- libvirt/tests/src/virsh_cmd/domain/virsh_sendkey.py
Original codes sets kernel option for guest image with graphic mode.
But if the guest image is already text mode installed, there is no
need to set this option. In addition, sometimes setting kernel option
will randomly fail with unclear reason. So the fix is to make the
setting kernel option optionally.
> virsh_sendkey: make kernel option set optional

- libvirt/tests/src/virtual_disks/virtual_disks_luks.py
The setup_or_cleanup_gluster function comes from gluster module rather than libvirt
> Fix no attribute 'setup_or_cleanup_gluster' error in libvirt module

- provider/v2v_vmcheck_helper.py
- v2v/tests/src/specific_kvm.py
In commit 22f08263986429f7376b5ca1ecf5c1e236cfd021, vmxml was removed.
But some lines still use it and the lines were forgot to be modified.
so the wrong global vmxml variant was used.
This patch fixes the error.
> Fix using wrong xml as a checking source

- v2v/tests/cfg/v2v_options.cfg
1.RHV only support one special character；'_',so the case about specail_name only need to convert to libvirt.
2.Guest storage has been changed.
Signed-off-by: Zi Liu <zili@redhat.com>
> Fix 2 auto failed case

- libvirt/tests/cfg/virsh_cmd/domain/virsh_detach_device_alias.cfg
- libvirt/tests/src/virsh_cmd/domain/virsh_detach_device_alias.py
On s390x there are not usb devices, update test to work with scsi using scsi_debug device.
Depends on https://github.com/avocado-framework/avocado-vt/pull/2443
Executed test:
```bash
JOB ID     : e91fd4f92c0f58940f872b64721c1cb721306283
JOB LOG    : /root/avocado/job-results/job-2020-02-24T12.15-e91fd4f/job.log
(1/1) type_specific.io-github-autotest-libvirt.virsh.detach_device_alias.live.hostdev: PASS (76.82 s)
JOB TIME   : 78.88 s
```
> Fix hostdev detach device by alias on s390x

- libvirt/tests/cfg/migration/migrate_options_shared.cfg
- libvirt/tests/src/migration/migrate_options_shared.py
This patch adds below cases:
1. positive_test: break network during migration and recovers it
before keepalive timeout
2. negative_test: break network during migration and recovers it
after keepalive timeout
> add migration case with disabled keepalive in source

- libvirt/tests/cfg/virsh_cmd/domain/virsh_change_media_matrix.cfg
- libvirt/tests/cfg/virsh_cmd/domain/virsh_update_device_matrix.cfg
- libvirt/tests/src/virsh_cmd/domain/virsh_change_media_matrix.py
IDE is not supported by q35, update bus to SCSI which is supported.
> Update conf of disk dev and bus to support q35 and pseries

- libvirt/tests/cfg/migration/migrate_options_shared.cfg
The option "--parallel-connections" was missed from cfg file,
so fix it in this PR.
> migration: Fix missing option issue

- libvirt/tests/src/limit.py
Seems letters from string module is deprecated in python3, so below error
ERROR: cannot import name 'letters' from 'string' (/usr/lib/python3.8/string.py)
Let's fix it by changing it to supported one.
> Fixup: incorrect module import for python3

- libvirt/tests/src/virsh_cmd/domain/virsh_metadata.py
Overwrite timeout default value with constant to allow for slower
environments.
```bash
JOB ID     : e1daf13f3722c76e1a6f9ef3cf23b9926ef2ff9d
JOB LOG    : /root/avocado/job-results/job-2020-03-03T12.31-e1daf13/job.log
(1/1) type_specific.io-github-autotest-libvirt.virsh.metadata.positive_test.edit_option: WARN: Test passed but there were warnings during execution. Check the log for details. (50.64 s)
RESULTS    : PASS 0 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 1 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 71.62 s
```
> Add timeout constant

- libvirt/tests/src/virsh_cmd/domain/virsh_change_media_matrix.py
- libvirt/tests/src/virsh_cmd/domain/virsh_update_device_matrix.py
Xml usually does not have 'source' tag if the source file is not specified.
But now a tag like <source index='3' /> is being created, which is affecting test.
Therefore skip check if this happens.
> Skip check when source tag has no 'file' attr

- v2v/tests/cfg/function_test_esx.cfg
- v2v/tests/cfg/v2v_options.cfg
Some unreasonable cases was listed by wrong cartesian filter, this
patch fixes the problem.
> Update filter expression for some negative cases of v2v

- libvirt/tests/src/virsh_cmd/domain/virsh_memtune.py
There's no result-checking in original code. The command could
fail.
> Check result after executing virsh.memtune_set

- libvirt/tests/src/virsh_cmd/network/virsh_net_autostart.py
This is a new behavior of libvirt since 5.6.0.
That is before restarting libvirtd, we need remove the existing
/var/run/libvirt/network/autostarted file in order for the virtual networks
to be restarted which has autostart setting.
> Fix network auto restart error

- libvirt/tests/src/migration/migrate_with_legacy_guest.py
It reports 'migration_test' UnboundLocalError if migration is not
started by some reason. So fix it in this PR.
> migration: fix 'migration_test' UnboundLocalError

- libvirt/tests/cfg/virtual_disks/virtual_disks_nbd.cfg
- libvirt/tests/src/virtual_disks/virtual_disks_nbd.py
TLS and without TLS are both supported, and VM operations includes whole VM
lifecycle operation, as well as snapshot,save/restore.
> add cases to cover scenarios that VM images are exported by NBD server.

- libvirt/tests/src/migration/migrate_with_legacy_guest.py
On rhel8+ host, it failed to log into rhel6 guest without virtio
transitional model interface. In previous code, it does not
update the domain xml based on the interface's modification.
> migration: fix login timeout issue on rhel6 guest

- libvirt/tests/src/virtio_transitional/virtio_transitional_blk.py
- libvirt/tests/src/virtio_transitional/virtio_transitional_blk_negative.py
- libvirt/tests/src/virtio_transitional/virtio_transitional_mem_balloon.py
- libvirt/tests/src/virtio_transitional/virtio_transitional_nic.py
- libvirt/tests/src/virtio_transitional/virtio_transitional_rng.py
- libvirt/tests/src/virtio_transitional/virtio_transitional_serial.py
- libvirt/tests/src/virtio_transitional/virtio_transitional_vsock.py
This feature is introduced from 5.0.0.
> Skip virtio transitional cases if libvirt version < 5.0

- libvirt/tests/src/virtual_network/iface_network.py
1. Add missing step for ldlinux.c32 copy
2. Remove the failure of debug output
from get_stripped_output to avoid error
ERROR: [1S is not included in the known console codes list
which is caused in aexpect and not fixed now. please check
https://github.com/avocado-framework/aexpect/pull/48 for detailed info
> Fix virtual network pxe boot failure

- libvirt/tests/cfg/migration/migrate_options_shared.cfg
- libvirt/tests/src/migration/migrate_options_shared.py
This PR adds tests about tls-destination option which can
specific the hostname of destination server_cn in certificate
verification.
> migration: add tls-destination related tests

- libvirt/tests/src/limit.py
- libvirt/tests/src/virsh_cmd/network/virsh_net_dhcp_leases.py
- libvirt/tests/src/virsh_cmd/network/virsh_net_update.py
- libvirt/tests/src/virsh_cmd/nodedev/virsh_nodedev_event.py
- libvirt/tests/src/virsh_cmd/pool/virsh_find_storage_pool_sources.py
- libvirt/tests/src/virsh_cmd/pool/virsh_find_storage_pool_sources_as.py
- libvirt/tests/src/virsh_cmd/pool/virsh_pool_acl.py
- libvirt/tests/src/virtual_disks/virtual_disks_ceph.py
- libvirt/tests/src/virtual_network/iface_network.py
Remove any reference to results_stdout_52lts,results_stderr_52lts,decode_to_text from
compat_52lts.py under avocado-vt
> Remove 52lts compatiblity layer dependences

- libvirt/tests/src/virtual_disks/virtual_disks_gluster.py
After block-dev introduced, qemu-cmd doesn't output gluster.*=format information
> Fix gluster failures due to qemu-cmd checking

- libvirt/tests/src/virsh_cmd/domain/virsh_blkiotune.py
- libvirt/tests/src/virsh_cmd/domain/virsh_blockcopy.py
- libvirt/tests/src/virsh_cmd/domain/virsh_domblklist.py
- libvirt/tests/src/virsh_cmd/domain/virsh_domxml_to_native.py
- libvirt/tests/src/virsh_cmd/monitor/virsh_domifstat.py
- libvirt/tests/src/virsh_cmd/network/virsh_net_define_undefine.py
libvirt/tests/src/virsh_cmd/domain/virsh_blkiotune.py
libvirt/tests/src/virsh_cmd/domain/virsh_blockcopy.py
libvirt/tests/src/virsh_cmd/domain/virsh_domblklist.py
libvirt/tests/src/virsh_cmd/domain/virsh_domxml_to_native.py
libvirt/tests/src/virsh_cmd/monitor/virsh_domifstat.py
libvirt/tests/src/virsh_cmd/network/virsh_net_define_undefine.py
```
JOB ID     : d9700a309c0f2be206927ee513d237656760eacf
JOB LOG    : /root/avocado/job-results/job-2020-03-23T14.49-d9700a3/job.log
(1/1) type_specific.io-github-autotest-libvirt.virsh.blkiotune.positive.get_blkio_parameter.running_guest.options.none: PASS (14.07 s)
JOB TIME   : 23.83 s
JOB ID     : 82fadab9df7794d3e593957e4050a35423b6f2e3
JOB LOG    : …
```
> Remove 52lts dependency for some case

- libvirt/tests/cfg/virsh_cmd/domain/virsh_update_device_matrix.cfg
- libvirt/tests/src/virsh_cmd/domain/virsh_update_device_matrix.py
1. On s390x, IDE is not available. Use SCSI instead.
2. skip_release_check: allow for skipping the release check to
speed up testing; specifically, s390x wasn't supported on RHEL
before version 7.
```bash
JOB ID     : f8fc0cca6947142df9e2d7374bf8852153156adc
JOB LOG    : /root/avocado/job-results/job-2020-03-20T11.45-f8fc0cc/job.log
(1/1) type_specific.io-github-autotest-libvirt.virsh.update_device_matrix.pre_vm_state_running.dt_option_live.at_option_live.dt_okay_at_okay: PASS (220.31 s)
JOB TIME   : 222.93 s
```
```bash
JOB ID     : d0e5c1e00706ebbb797bdaf08f56575375b91ed7
JOB LOG    : /root/avocado/job-results/job-2020-03-22T12.52-d0e5c1e/job.log
(1/2) …
```
> Fix update device matrix on s390x

- v2v/tests/cfg/function_test_esx.cfg
Guest can't boot into first os without selecting by user after
v2v conversion, so skip checking guesit.
> Skip checkpoint for v2v option_root.first case

- libvirt/tests/cfg/virsh_cmd/domain/virsh_update_device.cfg
1. error_test: on s390x use scsi bus
2. updatedevice_twice: remove unnecessary value assignment
> Fix update device on s390x

- libvirt/tests/src/virsh_cmd/snapshot/virsh_snapshot_create_as.py
- libvirt/tests/src/virsh_cmd/snapshot/virsh_snapshot_disk.py
We do not support rdma with libvirt and qemu for now.
> Skip gluster rdma cases in snapshot function

- libvirt/tests/src/virtual_disks/virtual_disks_multidisks.py
After blockdev is introduced, qemu output related to blockdev part will be packed in json format
Use wild matching patterns to let cases be compatible with previous version
> Fix iothreads and discard failures

- libvirt/tests/src/timer_management.py
It reports define error since libvirt 6.0 for unsupported timer
type. Fix it in this PR.
> Fix define error for timer management tests

- libvirt/tests/src/virtio_transitional/virtio_transitional_blk_negative.py
The original checkpoint is "check if vm boot up failed".
It's already covered by wait_for_serial_login.
Remove "kernel panic" pattern checking because it's unstable in
CI env for now.
> Remove an unstable checking from virtio_transitional tests

- libvirt/tests/src/virsh_cmd/domain/virsh_update_device_matrix.py
https://github.com/autotest/tp-libvirt/pull/2607 introduced an optimization
However, originally the guest was always destroyed; therefore the attach
disk operation was always run on a shutoff machine and the disk available
on the guest in any state that was established later (`pre_vm_state`).
Make sure vm is always destroyed before test setup is started.
No exception handling required (just as before) because `vm.destroy`
doesn't raise even if executed on dead machine.
> fix update device matrix

- libvirt/tests/src/virtual_network/iface_network.py
The pid-file path change from "/var/run" to "/run" in rhel8.2
> Fix the pid-file path change issue in rhel8.2 

- libvirt/tests/cfg/libvirt_mem.cfg
- libvirt/tests/src/libvirt_mem.py
In some cases, doing managedsave/save too soon will cause failures
after restoring.
> Wait some time before doing managedsave/save for pseries vms

- libvirt/tests/src/virtual_disks/virtual_disks_multidisks.py
that 'host_device' driver expects either a character or block device
> Fix failure brought by block dev change

- libvirt/tests/src/virtual_disks/virtual_disks_multidisks.py
driver=bus_id is not found in qemu output, instead of hardcoded to drive=libvirt-1-format
> Fix driver string checking failures due to block-dev change

- libvirt/tests/cfg/virsh_cmd/domain/virsh_shutdown.cfg
Add timeout parameter explicitly to config in order to easily
substitute on slower systems
> Add timeout to config

- libvirt/tests/src/virtual_disks/virtual_disks_multidisks.py
After block-dev introduced, cold config duplicate scsi controller with same index not allow
> Fix duplicate scsi controller index error

- libvirt/tests/cfg/migration/migrate_vm.cfg
- libvirt/tests/src/migration/migrate_vm.py
The virtual size from qemu-img info's output changed from "xxG"
to "xx GiB", so update the command line to get it in cfg.
And In some case, the expected value which comes from users' input
is float,but we get it in int, so format the values before checking.
BTW, fix an indexError in get_virtual_size.
> Fix the way to get and check virtual disk size

- libvirt/tests/cfg/sriov/sriov.cfg
Current timeout is 2h and sometimes it's still not enough, that's
when one loop costs 90s. Therefore cut the number to 50.
> Reduce loop times from 100 to 50

- libvirt/tests/src/virsh_cmd/domain/virsh_blockpull.py
Transport protocol 'rdma' is not yet supported for now.
> Skip gluster rdma cases in blockpull tests

- libvirt/tests/src/virsh_cmd/domain/virsh_blockcommit.py
Transport protocol 'rdma' is not yet supported for now.
> Skip gluster rdma cases in blockcommit feature

- libvirt/tests/src/backingchain/blockcommand.py
1. An empty //disk/backingStore is equivalent to no backingStore.
Allow for test to pass if it's missing after successfull blockcommand.
2. Improve debug messaging.
> Fix blockcommand test

- libvirt/tests/cfg/bios/virsh_boot.cfg
The purpose of these seabios cases is mainly testing usb bus of the disk to boot, so we can only change block disk to file disk in virsh_boot.cfg
> Fix 'host_device' issue because of enable -blockdev in virsh_boot.cfg

- libvirt/tests/cfg/virtual_disks/virtual_disks_multidisks.cfg
- libvirt/tests/src/virtual_disks/virtual_disks_multidisks.py
IDE device bus type is not applicable on q35 machine type
> Fix cdrom device bus type error on q35

- libvirt/tests/src/virtual_network/iface_network.py
After libvirt 6.0.0, the directory path of the network pid changes
from "/var/run/..." to "/run/...".
> Modify the directory path of network pid

- v2v/tests/cfg/specific_kvm.cfg
Case 'specific_kvm.positive_test.linux.virtioscsi_disk' is
duplicated with case 'function_test_xen.positive_test.rhev.
scsi_disk'
> Delete virtioscsi_disk case in sepcific_kvm job

- libvirt/tests/cfg/virtual_disks/virtual_disks_multidisks.cfg
And filter one case where Device isa-fdc is not supported with machine type pc-q35-rhel8.2.0
> Fix disk virtio bootorder snapshot issue

- libvirt/tests/src/virtual_disks/virtual_disks_multidisks.py
After blockdev feature introduced, the qemu output is changed accordingly.
> Fix sata bus disk failure issue

- libvirt/tests/src/virtual_network/iface_network.py
Sometimes the default time is not enough
previous fail with
```
(1/1) type_specific.io-github-autotest-libvirt.virtual_network.iface_network.net_forward.net_route: ERROR: Unknown error occurred while looking for patterns ['[Aa]re you sure', '[Pp]assword:\\s*', '\\(or (press|type) Control-D to continue\\):\\s*$', '[Gg]ive.*[Ll]ogin:\\s*$', '(?<![Ll]ast )[Ll]ogin:\\s*$', '[Cc]onnection.*closed', '[Cc]onnection.*refused', '[P... (47.82 s)
```
Now pass
```
JOB ID     : 8ef47c07c2806a5143443d6ee1f2880fa420be80
JOB LOG    : /root/avocado/job-results/job-2020-04-09T07.34-8ef47c0/job.log
(1/1) type_specific.io-github-autotest-libvirt.virtual_network.iface_network.net_forward.net_route: PASS (67.03 s)
JOB TIME   : …
```
> Add timeout for serial login

- libvirt/tests/src/virsh_cmd/domain/virsh_domiftune.py
Fix error: ERROR: check_libvirtd() missing 1 required positional argument: 'libvirtd' 
> Fix syntax error

- libvirt/tests/src/virsh_cmd/domain/virsh_blockpull.py
It's caused by new feature - add index for the active layer in
disk chain.
> Fix domain image backing chain check failure in virsh_blockpull

- libvirt/tests/src/virsh_cmd/domain/virsh_blockcommit.py
It reports "Permission denied" when vm start up.
Fixup this error in this PR.
depends on https://github.com/avocado-framework/avocado-vt/pull/2512
> Fix xml error for blockcommit multiple_chain tests

- libvirt/tests/cfg/virsh_cmd/domain/virsh_restore.cfg
After libvirt-5.6.0, more polkit rules are needed which are already
support in avocado-vt. Here we only need to add a new parameter to
configure it.
> Fix polkit policy

- libvirt/tests/src/virsh_cmd/domain/virsh_blockpull.py
Fix the error "could not find backing store index 1 in chain"
in this PR. It's caused by new feature - add index for the active
layer in disk chain.
> Fix backing store index not found error

- libvirt/tests/src/virsh_cmd/domain/virsh_detach_device_alias.py
PR 2566 causes other cases except hostdev cases are failed.
This is to recover the original case structure of original design.
> Fix hostdev not handled err

- libvirt/tests/cfg/virsh_cmd/domain/virsh_migrate.cfg
- libvirt/tests/src/virsh_cmd/domain/virsh_migrate.py
When stress_install_from_repo = yes, the stress package should be installed from repo. But it also requires 'stress_package' parameter. This parameter is missed in the case.
> Fix incorrect param name

- v2v/tests/cfg/function_test_esx.cfg
The guest whose nanme contains special charecter can't be power on
rhv so skip rhv output for the case.
> Block rhv output for special_name case

- libvirt/tests/src/migration/migrate_options_shared.py
Test failed with "Enable postcopy with migrate_set_capability
before the start of migration" even the state of vm was 'paused'.
It needs some time. So add wait_for to avoid this kind of failure.
> Fix 'virsh migrate-postcopy' command failure

- libvirt/tests/src/migration/migrate_options_shared.py
The firewall-cmd command will be failed without firewalld package.
So fix it.
> Update to install firewalld

- libvirt/tests/cfg/libvirt_mem.cfg
- libvirt/tests/src/libvirt_mem.py
The memory device xml should not include the alias, so remove it and the number for max
hotplug memory should be 255 since there is a cold plug memory device also.
> Fix the hot unplug max slots memory device can't find issue

- libvirt/tests/src/serial/serial_functional.py
Original codes made guest xml's devices removed accidently.
So it got an error as below when adding a device:
- TypeError: 'NoneType' object is not iterable
> Fix serial func not iterable

- libvirt/tests/cfg/migration/migrate_options_shared.cfg
The variant 'defualt_connection' should be 'default_connection'.
> Fix typo in multifd tests

- libvirt/tests/cfg/backingchain/blockcommand.cfg
- libvirt/tests/src/backingchain/blockcommand.py
Introduction of `-blockdev` has unmasked a failure in the test script.
The backing chain that was created originally for `disk_type=block` consisted
only of files instead of block devices. This didn't lead to issues before
introduction of `-blockdev` because of https://bugzilla.redhat.com/show_bug.cgi?id=1821663
The test intention is to use block devices (volumes) for all snapshots.
Therefore, create volumes for all files in the chain beforehand to make
sure snapshots are created to block device with backing file another block
device, that is
`/dev/HostVG/vol1 <-- /dev/HostVG/vol2 <-- ... <-- /dev/HostVG/vol5`
for 4 snapshots, attaching `vol1` as base.
The test case should use `vol1` as `raw`.
`.py`:
1. `vol_size`: introduce variable for reuse
2. `driver_type`: introduce variable in order …
> Fix blockcommand test for block device

- libvirt/tests/src/virsh_cmd/volume/virsh_volume_application.py
It reports "target is busy" when the pool is destroyed directly
after the disk is detached. It needs some time to detach disk
correctly.
> Fix pool destory failure in volume_application

- libvirt/tests/cfg/virsh_cmd/domain/virsh_blockcopy.cfg
- libvirt/tests/src/virsh_cmd/domain/virsh_blockcopy.py
Don't test that the blockcopy job finishes when bandwidth is set minimal.
Setting it minimal is mainly useful for debugging scenarios but
doing so leads to a long running test case that most probably will timeout.
Considering that all other tests with 'val=0', i.e. '..bandwidth.max',
'..finish_async_option', '..finish_option' et al. already cover that job finishes
this check can be safely removed.
> Don't check blockcopy job finishes with minimal bandwidth

- libvirt/tests/src/virsh_cmd/volume/virsh_vol_download_upload.py
Comparing manual cases, missing pool refresh action in script.
> Fix no vol in pool issue

- libvirt/tests/cfg/libvirt_mem.cfg
For there is a cold plugged memory device, change attach_times to 255 from 256.
Restore the attach_gt_max to 257 from a mistake change.
> Change attach_times to 255 from 256 for the max_slots

- libvirt/tests/src/virsh_cmd/volume/virsh_vol_create_from.py
The original item in pre_disk_vol is too small, so update to 2M.
> Fix "Cannot grow device files" error

- libvirt/tests/src/virtual_disks/virtual_disks_gluster.py
In QEMU[1], gluster+rdma scheme will be regarded as tcp tranport. That
has been duplicated to gluster tcp cases. The cancel will be revoked after
gluster rdma are really supported in QEMU.
[1]:
https://github.com/qemu/qemu/blob/762fa6d79aa30e1a713444da0399739423f8d00e/block/gluster.c#L375
> virtual_disks_gluster: Cancel all gluster rdma tests

- libvirt/tests/cfg/migration/migrate_options_shared.cfg
- libvirt/tests/src/migration/migrate_options_shared.py
This PR adds migration cases about vtpm device.
1. Migrate[p2p/tunnelled/postcopy] a guest with vtpm device
2. Migrate guest with encrypted vtpm to target host with different
secret value set
depends on https://github.com/avocado-framework/avocado-vt/pull/2480 and https://github.com/avocado-framework/avocado-vt/pull/2481
> RFE: Add migration cases about vtpm device

- libvirt/tests/src/libvirt_pci_passthrough.py
Changed the usage and name of pci_lable_from_address in avocado-vt.
Update accordingly.
depends on https://github.com/avocado-framework/avocado-vt/pull/2529
> Update pci_lable_from_address func name

- libvirt/tests/src/virsh_cmd/host/virsh_freepages.py
When no pagesize is available on the host, we should skip the test
instead of raising errors.
The error is like ' page size 1048576 is not available on node 0'.
> Fix no pagesize on node

- libvirt/tests/cfg/backingchain/blockcommand.cfg
Gluster is Not supported on pseries.
> Remove gluster-related cases for pseries

- libvirt/tests/src/virtual_disks/virtual_disks_multipath.py
Some cases occasionally failed with error message "the device is not scsi device"
Enable more output for multipath devices
> Add debug information for multipath

- libvirt/tests/cfg/numa/guest_numa.cfg
- libvirt/tests/src/numa/guest_numa.py
When we set memnode attached to one node using strict mode, the memory
pages may not be enough for the guest RAM. So this is to allocate all
huge pages on the host numa node which is attached to which can avoid
of below error when starting the guest.
`Insufficient free host memory pages available to allocate guest RAM.`
> Fix insuffient mem pages

- libvirt/tests/cfg/migration/migrate_vm.cfg
- libvirt/tests/src/migration/migrate_vm.py
Error message 'nbd-server-add': Block node is read-only' is as expected,
Put it into negative test.
qemu-kvm 2.10.0 is a too old version, so we need not to judge it any more.
> Fix minor issue

- libvirt/tests/src/migration/migrate_ceph.py
- libvirt/tests/src/migration/migrate_gluster.py
- libvirt/tests/src/migration/migrate_options_shared.py
- libvirt/tests/src/migration/migrate_vm.py
- libvirt/tests/src/migration/migrate_with_legacy_guest.py
- libvirt/tests/src/virsh_cmd/domain/virsh_domjobabort.py
- libvirt/tests/src/virsh_cmd/domain/virsh_migrate.py
- libvirt/tests/src/virsh_cmd/domain/virsh_migrate_compcache.py
- libvirt/tests/src/virsh_cmd/domain/virsh_migrate_copy_storage.py
- libvirt/tests/src/virsh_cmd/domain/virsh_migrate_multi_vms.py
- libvirt/tests/src/virsh_cmd/domain/virsh_migrate_set_get_speed.py
- libvirt/tests/src/virsh_cmd/domain/virsh_migrate_stress.py
- libvirt/tests/src/virsh_cmd/domain/virsh_migrate_virtio_scsi.py
- libvirt/tests/src/virsh_cmd/domain/virsh_migrate_vm_cfg.py
- libvirt/tests/src/virsh_cmd/domain/virsh_migration.py
- libvirt/tests/src/virsh_cmd/domain/virsh_qemu_monitor_blockjob.py
change all the migration testcases that uses utils_test.libvirt
to migration.py for `MigrationTest`.
> migration: adopt utils_test.libvirt to migration

- libvirt/tests/src/virsh_cmd/domain/virsh_detach_device.py
Add wait operations until device detached really disappear
> Fix virsh detach device alias failures

- libvirt/tests/src/nwfilter/nwfilter_vm_start.py
libvirtd is now using systemd socket activation by default.
> Fix Failed to kill libvirtd issue

- libvirt/tests/cfg/migration/migrate_options_shared.cfg
- libvirt/tests/src/migration/migrate_options_shared.py
Migrate the timer device, and the check the vm and
source host time after migration
> [timer] Added the case of timer migration

- libvirt/tests/src/virsh_cmd/domain/virsh_console.py
1. Pass architecture argument to make sure zipl is run on s390x
when kernel parameters are updated by test.
2. Wrap some lines to not surpass 80 columns.
> Fix virsh console for s390x

- libvirt/tests/cfg/virtual_network/mtu.cfg
- libvirt/tests/src/virtual_network/mtu.py
Extend waiting time for pseries during login.
Extend waiting time after boot up, before login, to wait for services
of network fully started.
> Fix login timeout error after saving on pseries

- libvirt/tests/cfg/timer_management.cfg
On s390x 'inject-nmi' causes restart and kernel dump. Therefore,
'inject-nmi' can't be used to put stress on guest because it cannot
be run more than once immediately one after another.
Don't run test case on s390x.
> Mark inject-nmi stress test case invalid on s390x

- libvirt/tests/cfg/cpu/vm_features.cfg
Listed features are not available on s390x.
Blacklist test cases.
> Blacklist hyperv feature tests on s390x

- libvirt/tests/cfg/libvirt_qemu_cmdline.cfg
EOI requires APIC; not available on s390x.
Blacklist test case.
> Blacklist APIC test case on s390x

- libvirt/tests/src/migration/migrate_vm.py
It requires password authentication if vm.connect_uri contains
ip address of localhost.
> Fix vm access issue

- libvirt/tests/cfg/conf_file/sysconfig_libvirt_guests/libvirt_guests.cfg
- libvirt/tests/src/conf_file/sysconfig_libvirt_guests/libvirt_guests.py
Test whether the nfs backend image guest can be suspended on shutdown,
and can be started on next reboot.
> Add libvirt-guests cases for nfs backend image guest

- libvirt/tests/cfg/virsh_cmd/domain/virsh_blkiotune.cfg
- libvirt/tests/src/virsh_cmd/domain/virsh_blkiotune.py
In d43a4a3b0b34ec0eb85709d1abe1ac508e74fa09 I stated that on s390x
the first disk device is /dev/dasda. This is not always true, a system
can also have SCSI and no DASD.
Therefore, make the path configurable and use /dev/sda like before as default.
> Make scheduler path configurable

- libvirt/tests/cfg/migration/migrate_vm.cfg
On s390x RoCE works differently, e.g. no udp package transfer.
Migration is not supported currently.
> Blacklist RDMA migration on s390x

- libvirt/tests/cfg/virsh_cmd/domain/virsh_update_device.cfg
- libvirt/tests/cfg/virtual_disks/startup_policy.cfg
- libvirt/tests/cfg/virtual_disks/virtual_disks_multidisks.cfg
Fix the  IDE controller which is not supported in q35 machine type issues
> Fix IDE controller which is not supported in q35 machine type issues

- libvirt/tests/src/virsh_cmd/domain/virsh_reboot.py
avoid error
aexpect.exceptions.ShellProcessTerminatedError: Shell process terminated while waiting for command to complete: 'uptime --since'
> Fix occasional "uptime --since" exception

- libvirt/tests/src/virsh_cmd/domain/virsh_blockcommit.py
It reports 'element tag "backingStore" not found' in libvirt 4.x.
Add libvirt version check to make pass in both versions.
> Add version check for bs xml creation

- v2v/tests/cfg/function_test_esx.cfg
- v2v/tests/cfg/specific_kvm.cfg
- v2v/tests/src/specific_kvm.py
1.Add scenario to check selinux type mls
2.Can't find the manual case for selinux_type case of
function_test_esx job and related guest has no setting about selinux
type, so delete the case.
> Add v2v new case 'check selinux type mls'

- libvirt/tests/src/virsh_cmd/domain/virsh_blockcommit.py
It was caused by commit fbe768e7.
The value of blockcommit_options was updated incorrectly for
top active cases.
> Fix UnboundLocalError - top_index

- libvirt/tests/src/migration/migrate_options_shared.py
- libvirt/tests/src/migration/migrate_with_legacy_guest.py
1. Some function in migration test scipts are already implemented
in avocado-vt. So update 2 migration scripts in this PR.
2. Add action to destroy vm in source in finally
> Enhancement: update to reuse methods in MigrationTest

- libvirt/tests/src/virtual_network/iface_hotplug.py
Non-negative tests are failing with message "TypeError: 'in <string>' requires string as left operand, not NoneType".
`err_msg_rom` doesn't need to be checked for non-negative test cases, s. 9c92eb66444c3a5247d07c8449e3fc11869cfb2f
Only check it if defined.
> Fix interface hotplug

- libvirt/tests/src/virsh_cmd/domain/virsh_detach_device.py
By allowing for certain time to waiting for event,then check the detach result
> Fix detach device with alias failure issues

- libvirt/tests/cfg/bios/virsh_boot.cfg
- libvirt/tests/src/bios/virsh_boot.py
Adjust the test topology of OVMF feature
1. Add cases to start ovmf guest with released version and secure boot enabling
2. Adjust the test step to start guest with non-released version
3. Fix failures in virsh.boot.by_ovmf.negative_test.non_released_version
> Adjust the test topology of OVMF feature

- libvirt/tests/cfg/migration/sriov_migrate.cfg
- libvirt/tests/src/migration/sriov_migrate.py
This PR adds below migration cases:
1. migrate vm with hostdev type interface
2. postcopy migrate vm with hostdev type interface
3. cancel during miration with hostdev type interface
depends on 
https://github.com/avocado-framework/avocado-vt/pull/2555
https://github.com/avocado-framework/avocado-vt/pull/2530
https://github.com/avocado-framework/avocado-vt/pull/2510
https://github.com/avocado-framework/avocado-vt/pull/2529
https://github.com/avocado-framework/avocado-vt/pull/2526
https://github.com/avocado-framework/avocado-vt/pull/1783
> RPL: Add migration cases about net failover

- libvirt/tests/src/virsh_cmd/snapshot/virsh_snapshot_edit.py
Use `min` to avoid list index out of range.
> Fix index range error

- libvirt/tests/src/virsh_cmd/domain/virsh_start.py
From 5.6.0 libvirt daemon is automatically restarted.
Fix test expectation.
> Fix virsh start error case for recent versions

- libvirt/tests/cfg/virsh_cmd/domain/virsh_attach_detach_interface.cfg
Use virtio as only supported option in this case for s390x.
> Fix virsh_attach_detach_interface s390x

- libvirt/tests/cfg/virsh_cmd/domain/virsh_save_image_edit.cfg
By manpage "Normally, restoring a saved image will use the state recorded in the save image to decide  between  running  or  paused."
The `no_option` test currently fails because `restore_state` is not set.
Set 'running' as expected according to manpage.
> Fix restore result no options

- libvirt/tests/cfg/libvirt_hugepage.cfg
Add parameters to assure kvm hugepage support can be activated by
setting `kvm_module_parameters = 'hpage=1'` if necessary.
> Fix libvirt_hugepage on s390x

- libvirt/tests/src/virtual_network/iface_network.py
The explicitly set timeout might be too small.
Remove hard coded value in order to use class default value
for more consistent value configuration.
> Use class level timeout for serial login

- libvirt/tests/src/virtio_transitional/virtio_transitional_blk.py
- libvirt/tests/src/virtio_transitional/virtio_transitional_rng.py
- libvirt/tests/src/virtio_transitional/virtio_transitional_serial.py
This PR fixes below issues:
1. make adjustment for the newly introduced libvirt.add_controller()
2. xml cannot be recovered if there is a problem getting the index
of the newly added controller
3. network was unreachable in some cases
> Fix issues in virtio_transitional_blk/rng/serial

- v2v/tests/cfg/convert_vm_to_libvirt.cfg
- v2v/tests/cfg/convert_vm_to_ovirt.cfg
V2V only need to convert tier2 guests from latest ESXi host
> Add source esx7.0 and change source of v2v tier2 guests to esx7.0

- provider/v2v_vmcheck_helper.py
SLES15SP1 guest which is installed minimal OS doesn't support
'lspci' and 'lshw' command, so add command 'hwinfo --gfxcard' to
check the video device of guest.
> Add another command to check video device of sles guest

- libvirt/tests/cfg/virsh_cmd/domain/virsh_detach_device_alias.cfg
spicevmc is not supported by pseries.
> Remove spicevmc cases from pseries tests

- libvirt/tests/src/papr_hpt.py
- 16M pagesize is not supported by power9
- Remove topology when setting vcpu to avoid confliction
> hpt:skip unsupported case and remove topology

- libvirt/tests/cfg/virtual_disks/virtual_disks_luks.cfg
- libvirt/tests/src/virtual_disks/virtual_disks_luks.py
Add tests of qcow2 image with native luks encryption
```
JOB ID     : 8891b73993fd0d83260f0b9866c43ed1100c5734
JOB LOG    : /root/avocado/job-results/job-2020-04-02T22.38-8891b73/job.log
(1/2) type_specific.io-github-autotest-libvirt.virtual_disks.luks.positive_test.coldplug.device_disk.dir_pool_test.target_format_qcow2.encryption_in_source: PASS (101.63 s)
(2/2) type_specific.io-github-autotest-libvirt.virtual_disks.luks.positive_test.coldplug.device_disk.dir_pool_test.target_format_qcow2.encryption_out_source: PASS (184.83 s)
JOB TIME   : 289.04 s
[root@jgao-test1 ~]# avocado run --vt-type libvirt type_specific.io-github-autotest-libvirt.virtual_disks.luks.negative_test.duplicated_encryption.coldplug.device …
```
> Add cases of qcow2 image with native luks encryption

- libvirt/tests/cfg/virtual_device/filesystem_device.cfg
- libvirt/tests/src/virtual_device/filesystem_device.py
1.Start guest with 1/2 virtiofs filesystem devices.
2.Start 2 guest with the same virtiofs filesystem device.
3.Coldplug/Coldunplug virtiofs filesystem device
4.Share data between guests and host.
5.Lifecycle for guest with virtiofs filesystem device.
> Add testcases for virtiofs filesystem device:

- libvirt/tests/cfg/virsh_cmd/network/virsh_net_update.cfg
- libvirt/tests/src/virsh_cmd/network/virsh_net_update.py
Check libvirtd should not crash during net_update even in negative test
with XML error.
> Check libvirtd should not crash during net-update

- libvirt/tests/cfg/libvirt_mem.cfg
- libvirt/tests/src/libvirt_mem.py
- The time that vm's log file being released could be later than
vm being shutdown, starting vm before log file released could face
errors. Wait for some time and retry several times on starting vm
- host_known_unplug_errors updated
> Fix error of mem cases

- libvirt/tests/cfg/virtual_disks/virtual_disks_multidisks.cfg
- libvirt/tests/src/virtual_disks/virtual_disks_multidisks.py
This implements two scenarios:
1. Coldplug/cold-unplug a disk with copy_on_read=on
2. Hotplug/hotunplug a disk with copy_on_read=on
> Add new case for copy_on_read attach disk

- libvirt/tests/cfg/virsh_cmd/domain/virsh_restore.cfg
- libvirt/tests/src/virsh_cmd/domain/virsh_restore.py
To make sure network services are all active, to avoid unable to
login after restore.
> Need to wait some time before save

- libvirt/tests/src/sriov/sriov.py
When there's pcie-root-port, no longer add pci-bridge
> Fix issue of adding pci-bridge incorrectly

- libvirt/tests/cfg/migration/migrate_bandwidth.cfg
- libvirt/tests/src/migration/migrate_bandwidth.py
This PR adds the following migration cases:
1) Set both precopy and postcopy bandwidth by virsh migrate parameter
2) Set bandwidth before migration starts by migrate parameter --postcopy-bandwidth
3) Set bandwidth when migration is in post-copy phase
4) Set bandwidth when migration is in pre-copy phase
5) Set bandwidth when guest is running and before migration starts
6) Set bandwidth before migration starts by migrate parameter --bandwidth
7) Set bandwidth when guest is running and before migration starts
8) Set bandwidth when guest is shutoff
9) Do live migration with default max bandwidth
depends on https://github.com/avocado-framework/avocado-vt/pull/2563
> Add migration with bandwidth cases

- libvirt/tests/src/virtual_network/iface_bridge.py
Add force_ipv4=True to use ipv4 in all the ping test.
> Force ping to use ipv4

- libvirt/tests/src/virtual_network/iface_options.py
According to BZ1350772, the memory could not be to large for vms
created by unprivileged users.
Also set wait time to 60s to avoid timeout when vm starting too
slow.
> Set vm memory to 2G to avoid permission error

- libvirt/tests/cfg/virtual_device/filesystem_device.cfg
- libvirt/tests/src/virtual_device/filesystem_device.py
The default value of vcpus per numa cell is 2, since ppc hosts usually
have more cpus than x86 hosts, we would set the number to a larger
value to have less numa cells during test.
> Allow pseries to configure the amount of numa cells separatedly

- libvirt/tests/cfg/virtual_disks/virtual_disks_multidisks.cfg
unsupported configuration: piix3-usb-uhci not supported in this QEMU binary
> Remove unsupported case from pseries tests

- libvirt/tests/src/virsh_cmd/domain/virsh_migrate.py
Update options of new_from_dumpxml to migrate using xml.
> Fix xml error for virsh_migrate

- libvirt/tests/src/migration/migrate_options_shared.py
Vm is expected to start up successfully,
even if host cpu number < vm vcpu number.
So remove the checking whether to skip case.
> Remove unnecessary checking for migration

- libvirt/tests/src/migration/migrate_gluster.py
It's required by feature owner.
> Update options for migrate_gluster

- libvirt/tests/cfg/migration/migrate_options_shared.cfg
- libvirt/tests/src/migration/migrate_options_shared.py
1. Check migraion with default maxdowntime
2. Set maxdowntime before migration
> migration: Add 2 maxdowntime related cases

- libvirt/tests/src/migration/migrate_bandwidth.py
To set post-copy migration bandwidth,
need to add the '--postcopy' option.
> Add missing postcopy option

- libvirt/tests/cfg/numa/guest_numa.cfg
guest_numa: update test with only use node 0
To avoid empty node and not skip testing, use only node 0 for
it's with most chance as memory not empty.
> Apply an old patch of pseries settings of numa tests

- libvirt/tests/cfg/virsh_cmd/domain/virsh_detach_device_alias.cfg
'spicevmc' is not available on s390x. Use 'pty' instead.
Signed-off-by: root <root@ibm-z-107.rhts.eng.bos.redhat.com>
> Fix channel detach on s390x

- libvirt/tests/cfg/virsh_cmd/domain/virsh_blockcommit.cfg
- libvirt/tests/src/virsh_cmd/domain/virsh_blockcommit.py
Ceph server is not prepared locally on the test machine, so the
timeout=1 will easily trigger a blockjob abort, and cause some
random failures for ceph cases. Set timeout=10 for ceph cases
will avoid the failures.
> Fix a timeout issue for blockcommit with ceph storage

- libvirt/tests/src/virtual_network/iface_network.py
Last attempt to fix the file path issue is wrong. As in both libvirt
version, the pid path of "/var/run/libvirt/network" and
"/run/libvirt/network" exists. And with libvirt > 6.0.0, the path in
config file changes. So we need to judge by libvirt version, not by
the existence of the file path.
> Fix the file path issue

- libvirt/tests/cfg/virtual_device/tpm_device.cfg
- libvirt/tests/src/virtual_device/tpm_device.py
Vtpm only supports uefi firmware, so if default guest is on bios
without nvram, replace its os, features, disk image.
> tpm_device: replace os and disk for vtpm

- libvirt/tests/src/virtual_disks/virtual_disks_multivms.py
Depends on https://github.com/avocado-framework/avocado-vt/pull/2565
During test teardown, scsi_debug module might still be in use when trying to delete it.
Tests fail due to issue in teardown with "RuntimeError: Module scsi_debug is still in use. Can not unload it."
Instead, retry deleting the scsi device until timeout.
> Wait for scsi_debug

- libvirt/tests/cfg/libvirt_mem.cfg
According to Bug 1780506. This negative case is no longer aplicable
on pseries.
> Memory size will automatically align to 256m on pseries

- libvirt/tests/cfg/daemon/daemon_functional.cfg
It usually cost more time than x86
> Extend exit timeout for pseries

- libvirt/tests/src/cpu/ppccpucompat.py
Now that xive as interrupt controller
becomes default from Power9 processor and
all Distribution support the same has the
relevant Software, let's enable check for
xive.
> Update check for xive

- libvirt/tests/cfg/sriov/sriov.cfg
As the config file changes, the original pattern can not match any
test cases in the error test part. Update the pattern to fix it.
> Fix the error test miss issue

- libvirt/tests/src/virsh_cmd/domain/virsh_dumpxml.py
1. Extract determining if feature supported on host into method
in order to improve readibility.
2. Make custom cpu generation generic and add new function to
deliver values.
3. Use previously set model configuration values to decide which
model to expect per default.
4. Use previously set feature policy configuration to decide
which policy to expect for optional features.
5. Use previously set feature policy configuration to decide
which policy to expect for non-optional features.
> Fix dumpxml cpu-update for s390x

- v2v/tests/cfg/function_test_esx.cfg
- v2v/tests/src/function_test_esx.py
Add virt-v2v new test case RHEL-149829 - [Network]v2v can convert guest on rhel8 when v2v conversion server doesn't have bridge ' virbr0'
Signed-off-by: Zi Liu <zili@redhat.com>
> Add virt-v2v test case RHEL-149829

- libvirt/tests/cfg/virsh_cmd/domain/virsh_blkdeviotune.cfg
- libvirt/tests/src/virsh_cmd/domain/virsh_blkdeviotune.py
```
JOB ID     : f9da567336e78ed9c0f27dd5cd33d575a2ca6042
JOB LOG    : /root/avocado/job-results/job-2020-05-13T23.21-f9da567/job.log
(01/10) type_specific.io-github-autotest-libvirt.virsh.blkdeviotune.positive_testing.attach_disk.hotplug.slice_test: PASS (22.98 s)
(02/10) type_specific.io-github-autotest-libvirt.virsh.blkdeviotune.positive_testing.attach_disk.hotplug.not_slice_test: PASS (15.54 s)
(03/10) type_specific.io-github-autotest-libvirt.virsh.blkdeviotune.positive_testing.attach_disk.coldplug.with_alias.bus_virtio.slice_test: PASS (61.37 s)
(04/10) type_specific.io-github-autotest-libvirt.virsh.blkdeviotune.positive_testing.attach_disk.coldplug.with_alias.bus_virtio.not_slice_test: PASS (45.85 s)
(05/10) type_specific.io-github-autotest-libvirt.virsh.blkdeviotune.positive_testing …
```
> Add cases of blkdeviotune test with slice image

- libvirt/tests/cfg/cpu/iothread.cfg
ppc hosts usually have more cpus, 100 is not enough to be out of
range
> Update params setting of test out_of_range

- v2v/tests/src/v2v_options.py
When v2v uses nbdkit, the disk displays as below:
disks:
nbd:unix:/tmp/v2vnbdkit.B79f0i/nbdkit1.sock:exportname=/ (raw) [scsi]
A new disk checking pattern should be added to adapto the change.
> Add a new disk pattern for --print-source checking

- libvirt/tests/cfg/migration/migrate_options_shared.cfg
- libvirt/tests/cfg/migration/sriov_migrate.cfg
The variables "vtpm_without/with_postcopy" and "pre/postcopy"
are not available in these two cfg files. So fix them in this PR.
> Fix errors in migrate_options_shared.cfg and sriov_migrate.cfg

- libvirt/tests/src/virsh_cmd/volume/virsh_vol_download_upload.py
To avoid IndexError, update to check 'virsh vol-list' command's
output first.
> Update to check output of vol-list

- libvirt/tests/cfg/cpu/guestpin.cfg
- libvirt/tests/cfg/cpu/ppccpucompat.cfg
- libvirt/tests/cfg/libvirt_vcpu_plug_unplug.cfg
- libvirt/tests/src/cpu/guestpin.py
- libvirt/tests/src/cpu/ppccpucompat.py
- libvirt/tests/src/libvirt_vcpu_plug_unplug.py
Commit bb8c86a introduces additional mandatory
function argument testlist for run_avocado_bg()
method, let's update it.
Depends on: https://github.com/avocado-framework/avocado-vt/pull/2580
> Fixup: Add testlist params to avocado tests method

- libvirt/tests/src/virsh_cmd/domain/virsh_domfstrim.py
To avoid throwing out RuntimeError
> Add exception detection when trying to unload a linux module

- libvirt/tests/cfg/virtual_device/tpm_device.cfg
PPC only support one tpm model: tpm-spapr while other models are only supported on q35 for x86_64.
> Add cases for vtpm on ppc

- libvirt/tests/cfg/papr_hpt.cfg
- libvirt/tests/src/papr_hpt.py
Content of dmesg output is not constant, dmesg checking could be
dropped.
> Drop code of dmesg checking for hpt tests

- libvirt/tests/cfg/libvirt_qemu_cmdline.cfg
The 'eoi' attribute of the 'apic' feature is not supported for
architecture 'ppc64le' or machine type 'pseries-xxxxx'
> Remove pv_eoi cases from pseries

- libvirt/tests/src/libvirt_mem.py
Pagesizes on power8 and power9 hosts are different
> Set correct hugepage size for power8 and power9 hosts

- libvirt/tests/cfg/migration/migrate_options_shared.cfg
- libvirt/tests/src/migration/migrate_options_shared.py
This PR adds a test about migration with memory compression -
XBZRLE compression.
> Add a migration test with XBZRLE compression

- libvirt/tests/src/libvirt_rng.py
Send random data to tcp bind server, otherwise reading data from
guest /dev/hwrng actually will get nothing. And current 'nc -l' is
only suitable for tcp connect mode. Also add wait_remove_event in
attach_device to avoid hotplug failure.
> Add random source for tcp bind mode

- libvirt/tests/src/virsh_cmd/domain/virsh_attach_detach_disk.py
Allow more pci slots to be pre-allocated while VM creation
> Fix no more pci slots issue

- libvirt/tests/src/virtual_disks/virtual_disks_ceph.py
Ceph readonly snapshot can be supported on libvirt 6.0.0
> Fix ceph snapshot readonly issue

- libvirt/tests/cfg/migration/migrate_options_shared.cfg
- libvirt/tests/src/migration/migrate_options_shared.py
This PR covers a test case which pauses a domain during migration.
> Add migration tests

- libvirt/tests/cfg/virtual_network/iface_hotplug.cfg
- libvirt/tests/src/virtual_network/iface_hotplug.py
There is a bug that when attach-device with --live and --config but
no mac address for the interface, it will generate 2 different mac
address separately to live and inactive xml, which will cause the mac
changes after a vm destroy-start. Add the test scenario into the hotplug
tests.
> Check mac address when attach interface with --live --config

- libvirt/tests/cfg/migration/migrate_options_shared.cfg
- libvirt/tests/src/migration/migrate_options_shared.py
Fixup below problems in this PR:
1. Run stress before migration to extend downtime
2. Check domjobinfo after migration
3. Check time gap before backward migration
> Fix some problems in migrate_options_shared..timer

- provider/v2v_vmcheck_helper.py
- v2v/tests/cfg/convert_from_file.cfg
- v2v/tests/cfg/convert_vm_to_ovirt.cfg
- v2v/tests/cfg/function_test_esx.cfg
- v2v/tests/cfg/function_test_xen.cfg
- v2v/tests/cfg/specific_kvm.cfg
- v2v/tests/cfg/v2v_options.cfg
- v2v/tests/src/convert_from_file.py
- v2v/tests/src/convert_vm_to_ovirt.py
- v2v/tests/src/function_test_esx.py
- v2v/tests/src/function_test_xen.py
- v2v/tests/src/specific_kvm.py
1) When vm starts failed on rhv, the vm cannot be cleaned up.
This is because VMChecker is initialized after import_vm_to_ovirt.
But if import_vm_to_ovirt failed, VMChecker will have no chance
to run, and if put VMChecker ahead of import_vm_to_ovirt, the
VMChecker will fail at virsh.dumpxml in __init__. Because the VM
only can be seen when it's started on rhv, so it must be put after
import_vm_to_ovirt.
This patch breaks the dead loop of above relationship. Now the
VMChecker can be initialized at anywhere, so the vm can be cleaned
up at the end of the script.
2) Set import_vm_to_ovirt timeout to -1 which means no timeout.
When it's timeout, it doesn't mean import_vm_to_ovirt failed. If
the script is interupted forcely, the vm will be left on rhv and
may cause upcoming scripts fail. …
> v2v: Fix VMChecker initialization problem when converting to ovirt

- v2v/tests/cfg/specific_kvm.cfg
Before rhel8.2, it's like:
virt-v2v: error: internal error: invalid argument: libvirt domain
‘avocado-vt-vm1’ is running or paused.  It must be shut down in order
to perform virt-v2v conversion
In rhel8.3, it's like:
virt-v2v: error: libvirt domain ‘avocado-vt-vm1’ is running or paused.
It must be shut down in order to perform virt-v2v conversion
> Fix error message matching problem when converting a running guest

- v2v/tests/src/specific_kvm.py
Sometimes the --mac argument cannot be set correctly. This is because
the bridge or network parameter is deleted from params dictionay
object before passing to v2v_cmd function. Then when composing
--mac option, if the deleted net type is chosed, the value will be
None, then following wrong parameter will be set.
wrong setting:
--mac 52:54:00:b9:9b:db:network:None
> Fix randomly getting ip address failure problem

- v2v/tests/src/function_test_esx.py
The windows guest will reboot after intalling qemu-ga. But the rebooting
process cannot be controled in the whole checking process and it's not a
good idea to add it into public checking process.
The economic way to fix the problem is put check_windows_ogac function
before all public checkpoing checking process. Because in check_windows_ogac,
it will keep checking until the reboot success.
> Check windows qemu-ga before all public checkpoints

- libvirt/tests/src/backingchain/blockcopy.py
Signed-off-by: kylazhang <weizhan@redhat.com>
> Fix the blockcopy error when target size larger than source

- libvirt/tests/src/virtual_device/watchdog.py
Fix the failure 
```
TypeError: '&gt;' not supported between instances of 'NoneType' and 'str'&#10;
```
when running code
```
return second_boot_time > first_boot_time
```
As when get value failed, it will compare the first_boot_time(str) with second_boot_time(None) which cause this error
Signed-off-by: kylazhang <weizhan@redhat.com>
> Change the default value to avoid failure

- libvirt/tests/src/cpu/vcpu_affinity.py
It makes some cases fail if the host has less than 8 CPUs.
There will be some limitations in picking up proper machines in CI,
but still add codes in script.
> Skip vcpu_affinity test if the host has less than 8 CPUs

- libvirt/tests/cfg/virsh_cmd/domain/virsh_attach_detach_disk.cfg
- libvirt/tests/src/virsh_cmd/domain/virsh_attach_detach_disk.py
Commit 00d0c03d568174510c691fe01e62d4b92d61399d added code to add pci controllers.
On s390x, this doesn't apply.
Add a configuration parameter for s390-virtio to switch this behavior off.
> Fix attach disk pci issues on s390x

- libvirt/tests/cfg/migration/migrate_bandwidth.cfg
- libvirt/tests/cfg/migration/migrate_options_shared.cfg
- libvirt/tests/cfg/migration/migrate_vm.cfg
Some migration cases need to test both non-p2p and p2p, so update
the missing part.
> migration: add some p2p migration cases

- libvirt/tests/cfg/virtual_network/iface_network.cfg
Add negative test scenario: define macvtap network with duplicate
dev will fail as expeced.
> Add test scenario of define macvtap network with duplicate dev

- libvirt/tests/cfg/libvirt_mem.cfg
- libvirt/tests/src/libvirt_mem.py
PPC hosts have different hugepage size from x86, therefore the number
of hugepages on ppc should not be fixed to 2000 as x86. Set to a
smaller number to avoid memory size exceeds.
> Set different hugepage number other than 2000 on ppc hosts

- libvirt/tests/cfg/controller/controller_functional.cfg
- libvirt/tests/src/controller/controller_functional.py
These cases include below scenarios:
- Set custom alias in pci controllers of pc machine type
- [PCI] Hot-plug/Hot-unplug an device to pci-root
- Start VM with pcie-root-port/dmi-to-pci-bridge/pcie-expander-bus attached to pcie-root
- Generic PCIe Root Ports support BZ1408808
- Use generic PCIe Root Ports by default when available
- Attach dmi-to-pci-bridge/pcie-root-port to pcie-expander-bus
- Assign valid numa node to pcie-expander-bus
- Q35 machine will automatically fill pci/pcie controllers
- Auto assign busNr and model to pcie-expander-bus
- Assign e1000e NIC to pcie controllers by default
> Add cases for pci/pcie devices

- libvirt/tests/cfg/usb_device.cfg
- libvirt/tests/src/usb_device.py
set the suitable addr for usb controller, to attach usb controller into right pci endpoint
> Attach usb controller into right pci endpoint

- libvirt/tests/src/virsh_cmd/domain/virsh_sendkey.py
Jul 13 16:09:30 localhost.localdomain systemd[921]: rsyslog.service: Failed to execute command: Exec format error
Jul 13 16:09:30 localhost.localdomain systemd[921]: rsyslog.service: Failed at step EXEC spawning /usr/sbin/rsyslogd: Exec format error
-- Subject: Process /usr/sbin/rsyslogd could not be executed
> Update for failed to restart rsyslog

- libvirt/tests/cfg/svirt/svirt_start_destroy.cfg
- libvirt/tests/src/svirt/svirt_start_destroy.py
1.Start 2 guests using the same disk image;
2.The xattr should be the same after trying starting the second guest;
3.The xattr should be cleaned after guest shutoff;
> Add test for checking xattr added by libvirt

- libvirt/tests/cfg/virsh_cmd/domain/virsh_blkdeviotune.cfg
- libvirt/tests/src/virsh_cmd/domain/virsh_blkdeviotune.py
Modify the variable 'disk_slice' to 'disk_slice_enabled' and add
a new dict param 'disk_slice' to match avocado-vt patch 2952.
/root/.libvirt-ci-venv-ci-runtest-jZYIZh/lib/python3.6/site-packages/avocado_framework-80.0-py3.6.egg/avocado/plugins/run.py:292: FutureWarning: The following arguments will be changed to boolean soon: sysinfo, output-check, failfast and keep-tmp. 
FutureWarning)
JOB ID     : c76eb0df70d4a53216ab0714a0f6a563cf409e54
JOB LOG    : /root/avocado/job-results/job-2020-07-15T05.23-c76eb0d/job.log
(1/5) type_specific.io-github-autotest-libvirt.virsh.blkdeviotune.positive_testing.attach_disk.hotplug.slice_test: PASS (109.52 s)
(2/5) type_specific.io-github-autotest-libvirt.virsh.blkdeviotune.positive_testing.attach_disk.coldplug.with_alias.bus_virtio.slice_test: PASS …
> Fix blkdeviotune slice test error

- libvirt/tests/cfg/virsh_cmd/domain/virsh_managedsave_extra.cfg
- libvirt/tests/src/virsh_cmd/domain/virsh_managedsave_extra.py
- On readonly mode, some operations should fail.
> Add new case of managedsave-edit/dumpxml/define command

- libvirt/tests/cfg/virsh_cmd/domain/virsh_blockcopy.cfg
Based on change on libvirt:
qemu: Forbid non-raw images for disk type='lun' with vitio-blk frontend
https://gitlab.com/libvirt/libvirt/-/commit/b40ec75296769884ba873d2a72cdda01c2c03c24
> Update image type to raw for lun tests

- libvirt/tests/cfg/migration/migrate_storage.cfg
- libvirt/tests/src/migration/migrate_storage.py
1) Do storage migration(copy-storage-all/copy-storage-inc) with
TLS encryption - NBD transport
2) Cancel storage migration with TLS encryption
3) Copy only the top image for storage migration with backing chain
depends on https://github.com/avocado-framework/avocado-vt/pull/2593
> Add some storage migration cases

- v2v/tests/cfg/libnbd/libnbd.cfg
- v2v/tests/src/libnbd/libnbd.py
1) Add cases for libnbd is_zero, bz1809216
2) Reform libnbd.py and libnbd.cfg to support more test scenarios.
> Add cases for libnbd is_zero

- libvirt/tests/src/svirt/dac_start_destroy.py
- libvirt/tests/src/svirt/dac_vm_per_image_start.py
- libvirt/tests/src/svirt/svirt_attach_disk.py
- libvirt/tests/src/virsh_cmd/domain/virsh_attach_detach_disk.py
- libvirt/tests/src/virsh_cmd/domain/virsh_destroy.py
- libvirt/tests/src/virsh_cmd/domain/virsh_domfsfreeze.py
- libvirt/tests/src/virsh_cmd/domain/virsh_domiftune.py
- libvirt/tests/src/virsh_cmd/domain/virsh_domjobinfo.py
- libvirt/tests/src/virsh_cmd/domain/virsh_domxml_to_native.py
- libvirt/tests/src/virsh_cmd/domain/virsh_dumpxml.py
- libvirt/tests/src/virsh_cmd/domain/virsh_event.py
- libvirt/tests/src/virsh_cmd/domain/virsh_managedsave.py
- libvirt/tests/src/virsh_cmd/domain/virsh_migrate.py
- libvirt/tests/src/virsh_cmd/domain/virsh_sendkey.py
- libvirt/tests/src/virsh_cmd/domain/virsh_shutdown.py
- libvirt/tests/src/virsh_cmd/domain/virsh_start.py
- libvirt/tests/src/virsh_cmd/domain/virsh_undefine.py
Those changes are part of efforts to maintain only one place libvirt_version across all python files
> Update libvirt_version imported module from provider to virttest

- .travis.yml
- requirements-travis.txt
- Update travis requirements, remove outdated ones, and make a few
version upgrades
- Set checking version from python 3.4 to 3.6
- Set ignore python version from 3.4 to None
> Update travis setting

- libvirt/tests/src/migration/migrate_vm.py
Parameter server_setup_local is removed from server_setup() of
TLSConnection object, so do modification accordingly here.
> Modify the function call after the function definition changes

- libvirt/tests/src/migration/migrate_options_shared.py
This PR fixes 2 issues:
1. virsh secret-set-value returns 1 with some error messages which
was marked as WONTFIX
2. unable to get vm's ip address if it takes too much time to
check network connection
> migration: Fix getting ip failure and secret-set-value issue

- libvirt/tests/cfg/virtual_device/tpm_device.cfg
- libvirt/tests/src/virtual_device/tpm_device.py
From tpm2-tools-4.0, tpm2_getrandom needs -T to specify /dev/tpm0
as file for TCTI device. And its output changed to be binary, so
needs --hex for readable. Second, replace vm_xml.sync() with
virsh.define to better show the failure msg. Finally, add a step
to clean the decompressed dir /root/linux-* in guest os.
> tpm_device: adapt to new tpm2-tools, add fixes

- libvirt/tests/src/remote_access/remote_access.py
Added a new parameter in Libvirtd() class, so update cases
accordingly.
depends on https://github.com/avocado-framework/avocado-vt/pull/2646
> Update remote_access that uses utils_libvirtd.Libvirtd()

- libvirt/tests/cfg/virsh_cmd/domain/virsh_dumpxml.cfg
On s390x cpu match "minimum" is not supported.
Set default "exact" if not subtest "with_cpu" to avoid tests being skipped.
> Fix dumpxml default value for s390x

- libvirt/tests/cfg/libvirt_qemu_cmdline.cfg
- libvirt/tests/src/libvirt_qemu_cmdline.py
There has been an error message update on this feature, which is
the test focuses on.
Unlike x86, eoi is not supported by pseries, the result of virsh
define command should reflect this info.
> Update pv_eoi cases for pseries

- v2v/tests/cfg/v2v_options.cfg
- v2v/tests/src/v2v_options.py
The new case is mainly test the following warning.
virt-v2v: warning: no support for remote libvirt connections to '-ic
qemu+ssh://localhost/system'.  The conversion may fail when it tries to
read the source disks.
> v2v: Add new case for remote libvirt connection

- libvirt/tests/cfg/virsh_cmd/domain/virsh_event.cfg
- libvirt/tests/src/virsh_cmd/domain/virsh_event.py
JOB ID     : 5196dadab1ce656e9623fbb4703d6d7edbea8575
JOB LOG    : /root/avocado/job-results/job-2020-06-21T23.43-5196dad/job.log
(1/4) type_specific.io-github-autotest-libvirt.virsh.event.positive_test.virsh_event.test_events.block-threshold_event.qcow2_test.no_timeout.loop: PASS (75.80 s)
(2/4) type_specific.io-github-autotest-libvirt.virsh.event.positive_test.virsh_event.test_events.block-threshold_event.qcow2_test.timeout.loop: PASS (139.27 s)
(3/4) type_specific.io-github-autotest-libvirt.virsh.event.positive_test.virsh_event.test_events.block-threshold_event.raw_test.no_timeout.loop: PASS (69.41 s)
(4/4) type_specific.io-github-autotest-libvirt.virsh.event.positive_test.virsh_event.test_events.block-threshold_event.raw_test.timeout.loop: PASS (123.05 s)
RESULTS    : PASS 4 | ERROR 0 …
> Add tests of block threshold event check of raw and qcow2 format

- libvirt/tests/cfg/libvirt_rng.cfg
- libvirt/tests/src/libvirt_rng.py
```
JOB ID     : 6452c6a8c0722959e6ac1cf115f8e8185bd1df8a
JOB LOG    : /root/avocado/job-results/job-2020-07-21T15.16-6452c6a/job.log
(1/3) type_specific.io-github-autotest-libvirt.libvirt_rng.backend_builtin.hotplug_unplug.positive.no_options: PASS (62.64 s)
(2/3) type_specific.io-github-autotest-libvirt.libvirt_rng.backend_builtin.hotplug_unplug.positive.persistent: PASS (65.06 s)
(3/3) type_specific.io-github-autotest-libvirt.libvirt_rng.backend_builtin.device_assign: PASS (55.66 s)
JOB TIME   : 190.54 s
```
> Add test for rng-builtin

- libvirt/tests/src/bios/virsh_boot.py
Fix ovmf secure boot failed issue for block/rbd/gluster disk
The previous script didn't use released image when changed image to block/rbd/gluster disk by 'qemu-img convert', which leaded to guest secure boot failed. So add released image to fix it.
> Fix ovmf secure boot failed issue for block/rbd/gluster disk

- libvirt/tests/cfg/usb_device.cfg
for polarion case RHEL7-103600, need add cases for dmi-to-pci-bridge controller
> add cases for dmi-to-pci-bridge controller

- libvirt/tests/cfg/memory/nvdimm.cfg
- libvirt/tests/src/memory/nvdimm.py
- nvdimm requires label on pseries
- discard is not supported
> Add new case of nvdimm

- libvirt/tests/src/virtual_disks/virtual_disks_multidisks.py
After libvirt 6.5.0 version, transient disks configuration is not supported
> Fix transient disks issue

- libvirt/tests/src/libvirt_hooks.py
> libvirt_hooks: Wait for a few seconds to get log

- libvirt/tests/cfg/virtual_disks/virtual_disks_multidisks.cfg
- libvirt/tests/src/virtual_disks/virtual_disks_multidisks.py
Mainly add two test scenarios:
- Move auth element out of disk source element because it's a preference setting
- Coldplug network disk
- Hotplug and coldplug an overlay image based on chap authorized iscsi
> Attach an overlay image based on chap authorized iscsi

- libvirt/tests/cfg/virtual_device/tpm_device.cfg
- libvirt/tests/src/virtual_device/tpm_device.py
1. When no version is provided, the default version 2.0 for crb and spapr will be created now
instead of returning an error.
2. if version is set to 1.2 for spapr, an error will be returned now instead of being accepted
in libvirt, but not supported in qemu-kvm SLOF layer.
> Fix vtpm default version

- libvirt/tests/cfg/virtual_device/tpm_device.cfg
Incorrect format introduced by tp-libvirt 2977.
The incorrect format will make the xml_errmsg be 'TPM 1.2 is not supported with the SPAPR device mode' even on x86_64.
> Fix incorrect format

- provider/v2v_vmcheck_helper.py
The 'ipconfig /renew' might change the IP address of the VM and
cause shell session disconnect.
The error is like below.
aexpect.exceptions.ShellProcessTerminatedError: Shell process terminated
while waiting for command to complete: 'ipconfig /renew'    (status: 1,
output: '\nWindows IP Configuration\n\nNcat: Connection reset by peer.\n')
Because not every ip renew will change the IP address, the problem may
happens occasionally. IMHO, this checkpoint is not necessary. The VM
has IP address and can be connected have already proved the network driver
is working well.
> v2v: delete 'ipconfig /renew' operation for windows checking

- libvirt/tests/src/virtual_network/iface_bridge.py
The previous way of getting xml file is to get from a returned obj
which is the attribute of an iface obj created but not returned,
which means the iface obj could be destroyed during test running.
Therefore no guarantee of the xml file's keeping existing. Fix by
creating another iface obj which is able to go through the whole
test, in that way, the xml file should not be missing any more.
> Fixup: iface xml file missing after created

- libvirt/tests/cfg/serial/serial_functional.cfg
Device nodes for passthrough updated according to https://www.ibm.com/support/knowledgecenter/en/linuxonibm/com.ibm.linux.z.lgdd/lgdd_r_console_assure_nodes.html
Tests passed previously a) because they were run on z/VM (ttyS0 available) and b) tests don't check console type/driver.
> Fix console device nodes for s390x

- libvirt/tests/cfg/virsh_cmd/domain/virsh_update_device.cfg
- libvirt/tests/src/virsh_cmd/domain/virsh_update_device.py
```
JOB ID     : c5b228e0f4e00488f75d86ee49cf2ea551a2a750
JOB LOG    : /root/avocado/job-results/job-2020-04-29T23.08-c5b228e/job.log
(01/34) type_specific.io-github-autotest-libvirt.virsh.update_device.normal_test.id_option.no_option.scsi_option.slice_test: PASS (195.26 s)
(02/34) type_specific.io-github-autotest-libvirt.virsh.update_device.normal_test.id_option.no_option.scsi_option.not_slice_test: PASS (37.92 s)
(03/34) type_specific.io-github-autotest-libvirt.virsh.update_device.normal_test.id_option.force_option.scsi_option.slice_test: PASS (203.78 s)
(04/34) type_specific.io-github-autotest-libvirt.virsh.update_device.normal_test.id_option.force_option.scsi_option.not_slice_test: PASS (40.77 s)
(05/34) type_specific.io-github-autotest-libvirt.virsh.update_device.normal_test.id_option …
```
> Add tests of update device for cdrom slice test

- libvirt/tests/src/virtual_disks/virtual_disks_multidisks.py
scsi_debug module might still be in use when trying to unload for
the first time in test tear down.
Wait for it like shown in commit 6f2bbce4374c9e6c8b7cb7e3afe5af930a0ed943
> Retry scsi_debug unload on tear down

- libvirt/tests/cfg/bios/virsh_boot.cfg
- libvirt/tests/src/bios/virsh_boot.py
Depends on https://github.com/avocado-framework/avocado-vt/pull/2653
On s390x, an optional `loadparm` can be passed to be used
when booting from disk. The parameter can be used to select
the boot entry.
Add a test that uses `lsreipl` to determine if the parameter
is passed correctly.
> Add test cases for boot/loadparm

- libvirt/tests/src/virtual_disks/at_dt_iscsi_disk.py
- libvirt/tests/src/virtual_disks/virtual_disks_ceph.py
- libvirt/tests/src/virtual_disks/virtual_disks_encryption.py
- libvirt/tests/src/virtual_disks/virtual_disks_gluster.py
- libvirt/tests/src/virtual_disks/virtual_disks_multidisks.py
- libvirt/tests/src/virtual_disks/virtual_disks_nbd.py
- libvirt/tests/src/virtual_disks/virtual_disks_scsi3_persistent_reservation.py
- libvirt/tests/src/virtual_disks/virtual_disks_usb.py
The wait_remove_event, introduced from c4904fe6[1] of avocado-vt, will be
applied in detach_disk and detach_device. It will help to resolve the
false positive issues caused by the waiting for confirmation of pcie device[2]
detach and the asynchronicity of detach device API[3].
[1]: https://github.com/avocado-framework/avocado-vt/pull/2418
[2]:
https://lists.nongnu.org/archive/html/qemu-discuss/2019-04/msg00063.html
[3]:
https://gitlab.com/libvirt/libvirt/-/blob/master/src/libvirt-domain.c#L8350
> virtual_disks: Apply wait_remove_event for disk hot unplug

- libvirt/tests/cfg/migration/migrate_options_shared.cfg
This PR adds a case - Do live migration with mixed options
--p2p --comp-methods xbzrle --parallel --parallel-connections
> Add a migration case about xbzrle comp method and parallel

- libvirt/tests/cfg/migration/migrate_options_shared.cfg
- libvirt/tests/src/migration/migrate_options_shared.py
This PR adds a case - Do live postcopy migration for a paused VM.
> migration: Add a case for a paused VM postcopy migration

- libvirt/tests/src/virsh_cmd/host/virsh_nodecpustats.py
It raises an error message 'Invalid cpuNum in
virHostCPUGetStatsLinux' for invalid cpu num from libvirt 6.2,
so update code accordingly.
> Update error message for "virsh nodecpustats --cpu <invalid cpunum>"

- libvirt/tests/src/virt_cmd/virt_xml_validate.py
stderr: b'/bin/sh: 0: command not found\n'.
> Update case for virt_xml_validate

- libvirt/tests/src/libvirt_hooks.py
When failed to attach qemu process, we need to clean 'qemu-kvm'
process to avoid following cases failed.
> Update for libvirt_hooks case

- libvirt/tests/src/bios/virsh_boot.py
Fix "Property '.loadparm' not found" error in bios
> Fix "Property '.loadparm' not found" error in bios

- libvirt/tests/src/virtio_transitional/virtio_transitional_blk.py
Fix restart libvirtd issue in split daemon mode
> Fix restart libvirtd issue in split daemon mode

- libvirt/tests/cfg/virsh_cmd/domain/virsh_hypervisor_cpu_compare.cfg
- libvirt/tests/src/virsh_cmd/domain/virsh_hypervisor_cpu_compare.py
Depends on https://github.com/avocado-framework/avocado-vt/pull/2610
Test review revealed issue https://bugzilla.redhat.com/show_bug.cgi?id=1850614
Construct host cpu based on domcapabilities host-model info as expected behavior.
Use cpu element for guest cpu from dumpxml instead of the full domain xml.
> Fix hypervisor_cpu_compare

- libvirt/tests/src/virsh_cmd/snapshot/virsh_snapshot_create_as.py
When modular daemon enabled, we need to config virtqemud instead of
libvirtd.
> Fix missing libvirtd log issue when enable modular libvirt daemon

- libvirt/tests/src/migration/migrate_vm.py
The signal SIGINT can not stop migration process correctly, so
modify it to SIGKILL.
> Fixup a migration case that kills by signal.SIGINT

- libvirt/tests/src/migration/migrate_vm.py
It was introduced by add3f94401.
The function was changed in avocado-vt.
> Fix error in remove_key_in_conf

- libvirt/tests/cfg/virsh_cmd/domain/virsh_iothreadadd.cfg
- libvirt/tests/cfg/virsh_cmd/domain/virsh_iothreaddel.cfg
- libvirt/tests/cfg/virsh_cmd/domain/virsh_iothreadinfo.cfg
- libvirt/tests/cfg/virsh_cmd/domain/virsh_iothreadpin.cfg
The original parameter value in cfg limited the host cpu number  must be not less
than 5. That limitation will cause the tests fail in some test machines. But the
limitation can be decreased to smaller value which will make the tests pass in
most test machines, and at same time, this change will not effect the test points.
Original failure message is like:
---  error: Invalid value '0-4' for 'cpuset.cpus': Invalid argument
> Fix invalid cpu in iothread

- libvirt/tests/src/virsh_cmd/pool/virsh_pool.py
- libvirt/tests/src/virsh_cmd/pool/virsh_pool_autostart.py
Depends on https://github.com/avocado-framework/avocado-vt/pull/2729
Is related to https://github.com/autotest/tp-libvirt/pull/2513
Objects are started only once since 5.9.
virsh_pool.py
Add test step to make sure daemon will start pool simulating
system boot behavior in order to avoid test failure
'FAIL: Expect pool 'virsh_pool_test' doesn't exist.'
virsh_pool_autostart.py
Use library function.
> Fix pool autostart test step

- libvirt/tests/src/virsh_cmd/snapshot/virsh_snapshot_create_as.py
This is a regression issue of tp-libvirt PR3012.
The 'libvirtd_conf' used in 'finally' part, but it's not defined
in some scenarios, so put this line back to file.
> Fix variable missing issue in snapshot_create_as

- libvirt/tests/cfg/virsh_cmd/domain/virsh_migrate_setmaxdowntime.cfg
The expected output was changed from migrate_set_downtime to
downtime-limit in latest libvirt version.
> Update expected log output for virsh_migrate_setmaxdowntime

- libvirt/tests/src/nwfilter/nwfilter_binding_create.py
The nwfilter binding should be deleted after the test to avoid the issue
in flowing test.
> Delete the created binding after test

- libvirt/tests/src/virsh_cmd/volume/virsh_volume_application.py
'attach' tests will detach the volume. If this happens while the
fs is still working in the background there will be errors, e.g.
[Thu Aug 27 00:04:20 2020] EXT4-fs error (device vdb1): ext4_journal_check_start:61: Detected aborted journal
[Thu Aug 27 00:04:20 2020] EXT4-fs (vdb1): Remounting filesystem read-only
Avoid these errors by properly unmounting the partition before
detaching the volume.
> Fix dmesg errors at teardown

- libvirt/tests/src/libvirt_mem.py
- Power8 and power9 have different pagesize, page numbers need
to be different when power8 machines have small total memory
power9 machines don't have this kind of problems.
- Print numa info before starting vm
> libvirt_vm:set different page number to power8 and power9

- libvirt/tests/cfg/nwfilter/nwfilter_binding_list.cfg
- libvirt/tests/src/nwfilter/nwfilter_binding_list.py
The original script do not check the output of the virsh command, add
the check in the patch. And libvirt-daemon-config-nwfilter is needed.
>  Fix the issue when list nwfilter-binding test

- libvirt/tests/cfg/migration/migrate_vm.cfg
The auto script for p2p/tunnelled migration with ssh/tcp/tls is already
there, and can be re-used for normal live migration with ssh/tcp/tls.
> migrate_vm: Add test matrix for normal live_migration with ssh/tcp/tls

- libvirt/tests/cfg/cpu/setvcpu.cfg
- libvirt/tests/src/cpu/setvcpu.py
This PR adds a case - Disable/Enable vCPU which is followed by
non-hotpluggable online vcpus with "virsh setvcpu --config" cmd.
> Add a setvcpu case

- libvirt/tests/src/guest_kernel_debugging/nmi_test.py
To fix following error:
ShellTimeoutError: Timeout expired while waiting for shell command
to complete ...
> nmi_test: extend timeout value

- libvirt/tests/cfg/virsh_cmd/domain/virsh_hypervisor_cpu_compare.cfg
- libvirt/tests/src/virsh_cmd/domain/virsh_hypervisor_cpu_compare.py
Depends on 
https://github.com/avocado-framework/avocado-vt/pull/2609
https://github.com/autotest/tp-libvirt/pull/2890
virsh_hypervisor_cpu_compare.py:
* on s390x only hypervisor-cpu-(compare|baseline) are supported
use 'hypervisor-cpu-baseline' instead of plain 'cpu-baseline'
virsh_hypervisor_cpu_compare.cfg:
* set config value to use 'hypervisor' to provide baseline on s390x
> Fix hypervisor-cpu-compare on s390x

- libvirt/tests/cfg/nwfilter/nwfilter_binding_list.cfg
- libvirt/tests/src/nwfilter/nwfilter_binding_list.py
The case fail as no pci slot issue when hotplug, add pcie device
virtio model type to fix the issue. And during debug, I found the
binding can not be deleted immediately after the detach interface,
so I added the wait time.
> Fix the no pci slot issue

- libvirt/tests/cfg/nwfilter/nwfilter_vm_start.cfg
The clean-traffic nwfilter is a built-in network filter.
It should not be undefined during test.
> Fix the clean-traffic nwfilter missing issue

- libvirt/tests/cfg/nwfilter/nwfilter_binding_dumpxml.cfg
In set_env() function, there is attach_interface operation to prepare
the env, but it fails sometimes as no available pci slots. Add the model
option to attach virtio device will avoid this error.
> Fix the attach interface issue

- libvirt/tests/cfg/virsh_cmd/domain/virsh_event.cfg
- libvirt/tests/src/virsh_cmd/domain/virsh_event.py
TestFail: Not find expected event:event 'lifecycle' for domain
avocado-vt-vm1: Resumed Unpaused. Is your guest too slow to
get started in Nones?
> virsh_event: Extend timeout value

- libvirt/tests/cfg/virtual_network/iface_options.cfg
- libvirt/tests/src/virtual_network/iface_options.py
Add 2 more scenarios about disable offloads: disable tcp and disable
udp. And refer to
https://bugzilla.redhat.com/show_bug.cgi?id=1387477#c6, as tso and ufo
depends on gso, to disable tso and ufo, we need to disable gso as well.
> Add 2 more scenarios about offloads

- libvirt/tests/src/virsh_cmd/domain/virsh_migrate.py
It fails to get VM's IP address via get_address() without 'remote
session' after migration, and the IP address of VM will not change
during the migration process, so updte to use the value that obtained
in the previous step directly.
> Fix a problem to check network connectivity correctly after migaration

- libvirt/tests/src/conf_file/qemu_conf/auto_dump.py
To avoid following failure:
TestError: Cannot get pid by running;
pgrep -f /var/tmp/avocado_4j8h3yp7/dump
> Update for auto_dump

- libvirt/tests/src/conf_file/qemu_conf/auto_dump.py
FileNotFoundError: [Errno 2] No such file or directory:
'/proc/145646/cmdline'
> auto_dump: Move debug information

- libvirt/tests/src/migration/migrate_options_shared.py
It needs to get VM's IP address with session after migration.
> Fix VM IP address obtain failure in pty channel migration test

- libvirt/tests/cfg/virsh_cmd/domain/virsh_attach_device.cfg
- libvirt/tests/src/virsh_cmd/domain/virsh_attach_device.py
On s390x, maximally two serial consoles can be present and they must
be different (covered by virsh.attach_device..serial_s390x).
Therefore, virsh.attach_device..VirtualDiskBasic_SerialFile_SerialPipe
fails with 'Multiple VT220 operator consoles are not supported'.
On this arch, attach the consoles with <console> and target type 'virtio'
instead while using the same type (file, pipe).
> Fix virsh_attach_device on s390x

- libvirt/tests/src/libvirt_qemu_cmdline.py
The old version of 6.2.0 is not correct.
> Correct version of eoi support to 6.0.0

- libvirt/tests/src/nwfilter/nwfilter_vm_attach.py
- libvirt/tests/src/nwfilter/nwfilter_vm_start.py
There is checkpoint to check libvirtd status after attach interface,
update the daemon name to be compatible with split daemon. And for
the test case to kill libvirtd with specific signal, skip the case.
> Fix the issue when run as split daemon

- libvirt/tests/cfg/migration/migrate_vm.cfg
- libvirt/tests/src/migration/migrate_vm.py
Also updated "grep_str_from_local_libvirt_log" to adapt the
change about migrate-set-downtime in libvirt-6.5.0.
> migrate_vm: Update conf config to include split daemon

- libvirt/tests/cfg/memory/nvdimm.cfg
- libvirt/tests/src/memory/nvdimm.py
- Support file backed nvdimm with label size + access shared
- Define a vm with file backed nvdimm device with an uuid specified
and access private
- Define a vm with file backed nvdimm device with target_size smaller
than 256MiB + label_size
> Add nvdimm cases of ppc

- libvirt/tests/src/migration/migrate_options_shared.py
It fails to execute firewall-cmd in the latest firewalld version.
The option "--zone" is unsupported with "--direct" for now.
The value of 'zone' was set to 'public' by default when calling
Firewall_cmd.get(). And before deleting the firewalld direct
rules, it checked the rules via Firewall_cmd.get(), after that
the firewall-cmd command reported an error "--zone is an
invalid option with --direct". So the added rules were not removed.
Update 'zone' to None to make sure there is no '--zone' option in
this PR.
> Fix a firewall-cmd error

- v2v/tests/cfg/function_test_xen.cfg
function_test_xen..encryped is deprecated.
It is replaced with new case 'function_test_esx..luks'.
> v2v: delete case function_test_xen..encryped

- libvirt/tests/cfg/controller/pcie_controllers.cfg
- libvirt/tests/src/controller/pcie_controllers.py
New cases are to test with 'hotplug=on/off' in pcie-root-port controller.
For example,
```
<controller index="6" model="pcie-root-port" type="pci">
<target hotplug="off" />
</controller>
```
Case scenarios:
1. Hotplug a disk to the controller with hotplug=on/off
2. Coldplug a disk + hotunplug a disk from the controller with hotplug=on/off
3. Save and restore vm + restart libvirtd with hotplug=on/off
4. Hotplug disks for many times and ensure the controller with hotplug=off is not attached
> Add cases for pcie hotlug option

- libvirt/tests/cfg/virsh_cmd/domain/virsh_blockcopy_xml.cfg
- libvirt/tests/src/virsh_cmd/domain/virsh_blockcopy_xml.py
Cover different backend storage such as file,block,iscsi,rbd,nbd,ceph and gluster
> Add blockcopy xml test cases

- libvirt/tests/cfg/nwfilter/filter_aready_present_binding.cfg
- libvirt/tests/cfg/nwfilter/nwfilter_binding_delete.cfg
- libvirt/tests/src/nwfilter/nwfilter_binding_delete.py
- libvirt/tests/src/nwfilter/nwfilter_binding_dumpxml.py
- libvirt/tests/src/nwfilter/nwfilter_binding_list.py
Libvirt patch 95089f481e003 now introduced 1 feature change to assign tap device
names using a monotonically increasing integer. For some cases, update the check
point to check 'vnet\d+' instead of 'vnet0'/'vnet1', for other cases, update the
target name from 'auto generate' to manually assigned. It will avoid the failure
and no impact for old libvirt version.
> Fix the nwfilter test cases as the feature changes

- libvirt/tests/src/virtual_network/iface_options.py
Libvirt now has a feature change that the traget dev name with prefix
of "macvtap" and "macvlan" will be ignored even with network type. As it
is also backported, so the version check is not needed.
> Update the expected result as libvirt feature changes

- v2v/tests/src/function_test_esx.py
V2V won't do any change if qemu-guest-agent exists in guest, therefore
it will not update qemu-guest-agent version in guest. so let's remove
the version checking of qemu-guest-agent.
> v2v: remove qemu-guest-agent version checking in VM

- cfg_file_definition_convention.rst
In order to provide one consistent, human-readable, maintainable test case names, it is necessary to
apply some conventions rules to Cartesian Configuration format.
> Add cfg file definition conventions

- libvirt/tests/src/virsh_cmd/domain/virsh_update_device.py
This failures is brought by privous commit where default slice_test
is changed to 'yes'
Moreover, remove some deprecated usage of data_dir
> Fix virsh update device failures cases

- libvirt/tests/src/controller/multiple_controller_ppc.py
The original way is to get an xml element object, which is not an
object of VMCPUXML. The new way is to create new cpu xml if cannot
find one in vmxml, then set numa_cells
> Fix xml error when setting numa_cell to vmcpuxml

- libvirt/tests/cfg/virsh_cmd/domain/virsh_migrate_option_mix.cfg
- libvirt/tests/src/virsh_cmd/domain/virsh_migrate_option_mix.py
So the virsh command error message can be throwed out which is
convenient for debugging
Also changed the cfg and py file name to avoid confusion.
> Check migration result after do_migration

- libvirt/tests/src/migration/migrate_bandwidth.py
- libvirt/tests/src/migration/migrate_gluster.py
- libvirt/tests/src/migration/migrate_options_shared.py
- libvirt/tests/src/migration/migrate_storage.py
- libvirt/tests/src/migration/migrate_with_legacy_guest.py
- libvirt/tests/src/migration/sriov_migrate.py
- libvirt/tests/src/virsh_cmd/domain/virsh_migrate.py
If the modular daemon is enabled, direct remote_mode is not
supported for SSH transport.
I just updated migration cases which are executed by ci and ssh related.
depends on https://github.com/avocado-framework/avocado-vt/pull/2736
> Fix remote_mode issue that is not supported for SSH

- libvirt/tests/src/incremental_backup/incremental_backup_backing_chain.py
- libvirt/tests/src/incremental_backup/incremental_backup_pull_mode.py
- libvirt/tests/src/incremental_backup/incremental_backup_push_mode.py
Data generation method changed in avocado-vt, also need to
update it here.
> Correct dd_data_to_vm usage

- libvirt/tests/cfg/virtual_disks/virtual_disks_encryption.cfg
- libvirt/tests/src/virtual_disks/virtual_disks_encryption.py
Previously in the virtual disk script, it used the pool+volume method
to prepare the test image, but in fact it should not mix the two features
of storage and virtual disk, so here change the preparation method of
the test image from "vol-create" change to "qemu-img create".
In addition, the nagetive test that should belong to the storage part is removed.
Signed-off-by: jgao <jgao@redhat.com>
JOB ID     : bc92a45da73fc33d9b6239a2601447c38e4f4a84
JOB LOG    : /root/avocado/job-results/job-2020-09-21T23.20-bc92a45/job.log
(1/8) type_specific.io-github-autotest-libvirt.virtual_disks.encryption.hotplug.qcow2_internal.normal_test.encryption_in_source: PASS (70.19 s)
(2/8) type_specific.io-github-autotest-libvirt.virtual_disks.encryption.hotplug.qcow2_internal.normal_test.encryption_out_source: …
> Change the way of preparing test image

- libvirt/tests/src/virsh_cmd/domain/virsh_update_device.py
Add attribute of "readonly" or "shareable" when create disk xml with "slice".
Signed-off-by: root <root@localhost.localdomain>
Test result:
JOB ID     : 27120a9ea15e0fe6f2153c33af5a8495b9929946
JOB LOG    : /root/avocado/job-results/job-2020-09-23T03.56-27120a9/job.log
(01/27) type_specific.io-github-autotest-libvirt.virsh.update_device.normal_test.id_option.no_option.scsi_option.slice_test_qcow2: PASS (113.33 s)
(02/27) type_specific.io-github-autotest-libvirt.virsh.update_device.normal_test.id_option.no_option.scsi_option.slice_test_raw: PASS (119.16 s)
(03/27) type_specific.io-github-autotest-libvirt.virsh.update_device.normal_test.id_option.no_option.scsi_option.not_slice_test: PASS (37.90 s)
(04/27) type_specific.io-github-autotest-libvirt.virsh.update_device.normal_test.id_option.for …
> Virsh_update_device:Fix slice test with sharable error

- libvirt/tests/src/migration/migrate_vm.py
It needs get VM's IP address with remote session after migration.
> Fix an issue that VM's IP address can't be obtained after migration

- libvirt/tests/cfg/cpu/max_vcpus.cfg
- libvirt/tests/src/cpu/max_vcpus.py
It reports error when the vm starts with 384 max cpus since
libvirt 6.6.0-6. And the error message is updated.
> Update error message for max_vcpus.negative_test.ioapic_iommu

- libvirt/tests/cfg/migration/migrate_vm.cfg
- libvirt/tests/src/migration/migrate_vm.py
The original hardcoded hugepage number is based on vm memory 1024M's assumption.
But when more vm memory is used, the defined hugepage number does not meet the
requirement which causes vm fails to start due to insufficient allocated memory.
> Fix hugepage migration

- libvirt/tests/src/virsh_cmd/domain/virsh_migrate.py
In previous code, the conf libvirt.conf was updated only for
migration cases with postcopy, so correct it to update the
configurations for all cases.
> virsh_migrate: Fix unsupported direct socket mode issue

- libvirt/tests/cfg/cpu/max_vcpus.cfg
- libvirt/tests/src/cpu/max_vcpus.py
There is an update in the latest libvirt's version, so update the
script accordingly.
> max_vcpus: Update the maxCpus value of pc-q35-rhel8.3.0

- libvirt/tests/src/migration/migrate_vm.py
1. Update to get IP address with remote session
2. Correct the usages of remote.VMManager.run_command()
> Fix the problems in check_vm_disk_after_migration

- libvirt/tests/src/virsh_cmd/domain/virsh_migrate.py
If the status of virsh define is ignored and the auto case fail in
the following test steps, it will be much harder for us to locate
the problem.
> virsh_migrate: Don't ignore status of virsh define

- libvirt/tests/cfg/virtual_disks/virtual_disks_ceph.cfg
- libvirt/tests/src/virtual_disks/virtual_disks_ceph.py
Add test to ensure rbd disk with enabled authentication can
be hotplugged as virtio-scsi device in a vm.
Signed-off-by: jgao <jgao@localhost.localdomain>
> Add tests of virtio_scsi device for rbd storage

- libvirt/tests/cfg/sriov/sriov.cfg
- libvirt/tests/src/sriov/sriov.py
As hostdev interface supports vlan tag, add vlan tag configuration. This is depends on https://github.com/avocado-framework/avocado-vt/pull/2597
> Add vlan tag into the interface xml

- libvirt/tests/cfg/virsh_cmd/domain/virsh_event.cfg
- libvirt/tests/src/virsh_cmd/domain/virsh_event.py
Add watchdog events, details: paused, reset. And for paused, need
check guest can be resumed successfully.
> virsh_event: add watchdog event

- libvirt/tests/cfg/virtual_disks/virtual_disks_multidisks.cfg
The device='lun' with block type source has been rejected since libvirt
v1.3.5-rc1 (commit bd9d7078). Remove these positive cases.
> virtual_disks_multidisks: Remove volume_lun cases

- libvirt/tests/src/daemon/kill_starting.py
Some cases need to create a LibvirtdSession() object with the
service virtnetworkd, virtinterfaced and so on when the modular
daemon is enabled, so update the case accordingly.
> Modular daemon: Fix kill_starting cases error

- libvirt/tests/src/numa/guest_numa.py
Since machine type pc-q35-rhel8.3.0, the expected qemu command line
was changed for no numatune setting. So this is to introduce the new
qemu command line checking.
> guest_numa: Fix incorrect qemu cmd line

- libvirt/tests/cfg/migration/migrate_network.cfg
- libvirt/tests/src/migration/migrate_network.py
This PR adds a case -- migrate guest with bridge type interface
connected to ovs bridge.
depends on https://github.com/avocado-framework/avocado-vt/pull/2738
https://github.com/avocado-framework/avocado-vt/pull/2703
> migration: Add a case about ovs bridge

- libvirt/tests/cfg/virsh_cmd/domain/virsh_restore.cfg
- libvirt/tests/src/virsh_cmd/domain/virsh_restore.py
This PR adds 2 cases:
1. Restore vm with --xml from file located on no_root_squash nfs
2. Save/Restore guest from/to a block device with qemu namespace
depends on https://github.com/avocado-framework/avocado-vt/pull/2767
They are **high priority** cases.
> Add 2 save/restore cases

- libvirt/tests/cfg/virsh_cmd/domain/virsh_blkdeviotune.cfg
Modify the parameter 'disk_slice' to 'disk_slice_enabled' which has not used now.
Signed-off-by: Jianan Gao <jgao@redhat.com>
JOB ID     : 882ff2560bb6a0169729b7d85b8a06952c81dba0
JOB LOG    : /root/avocado/job-results/job-2020-10-10T02.50-882ff25/job.log
(01/10) type_specific.io-github-autotest-libvirt.virsh.blkdeviotune.positive_testing.attach_disk.hotplug.slice_test: PASS (191.56 s)
(02/10) type_specific.io-github-autotest-libvirt.virsh.blkdeviotune.positive_testing.attach_disk.hotplug.not_slice_test: PASS (17.97 s)
(03/10) type_specific.io-github-autotest-libvirt.virsh.blkdeviotune.positive_testing.attach_disk.coldplug.with_alias.bus_virtio.slice_test: PASS (211.23 s)
(04/10) type_specific.io-github-autotest-libvirt.virsh.blkdeviotune.positive_testing.attach_disk.coldplug.with_alias.bu …
> Virsh blkdeviotune:Fix the matrix error of slice test

- libvirt/tests/cfg/bios/virsh_boot.cfg
The code tries to install unnavailable packages because `boot_type`
has default value `seabios` leading to test error
'seabios package install failed'
Set parameter explicitly to `ipl` on s390x to avoid any execution
conditional on `boot_type`.
> Fix virsh_boot on s390x

- libvirt/tests/cfg/virsh_cmd/domain/virsh_domblkthreshold.cfg
- libvirt/tests/src/virsh_cmd/domain/virsh_domblkthreshold.py
Test under mirroring of blockcommit and blockcopy, threshold setting
can work normally
> Add set threshold for disk mirroring node BZ1807741 cases

- libvirt/tests/cfg/virsh_cmd/domain/virsh_blockcopy.cfg
change the block+lun test scenaro mapping from qcow2+virtio to raw+scsi as it do not supported with the old mapping
> Update test params for blockcopy

- libvirt/tests/src/virtual_disks/virtual_disks_multidisks.py
After libvirt 6.6.0, scsi=on/off flag is removed from qemu command line after libvirt 6.6.0,
so set device_option .* to make code compatible
> Fix disk_bus_virtio.device_disk.default case failure

- libvirt/tests/cfg/virsh_cmd/domain/virsh_restore.cfg
If you mount an NFS without "rw,no_root_squash" option, an error
is reported.
> Add the missing configuration for virsh_restore test

- libvirt/tests/cfg/virtual_disks/virtual_disks_encryption.cfg
- libvirt/tests/src/virtual_disks/virtual_disks_encryption.py
Add slice attribute to disk xml to add slice test for different
disk format.
Signed-off-by: jgao <jgao@redhat.com>
]# avocado run --vt-type libvirt type_specific.io-github-autotest-libvirt.virtual_disks.encryption
JOB ID     : 6a65a5f17ac62855f73da50bc103c25fa964f96b
JOB LOG    : /root/avocado/job-results/job-2020-09-23T21.46-6a65a5f/job.log
(01/16) type_specific.io-github-autotest-libvirt.virtual_disks.encryption.hotplug.slice_test.qcow2_internal.normal_test.encryption_in_source: PASS (86.76 s)
(02/16) type_specific.io-github-autotest-libvirt.virtual_disks.encryption.hotplug.slice_test.qcow2_internal.normal_test.encryption_out_source: PASS (98.59 s)
(03/16) type_specific.io-github-autotest-libvirt.virtual_disks.encryption.hotplug.slice_test.raw_luks.normal_test.encryption_in_source: PASS …
> add cases:Add slice test with different disk format

- libvirt/tests/src/npiv/npiv_hostdev_passthrough.py
After attaching disk the VM session will be closed,so the partiton check
later will fail because of the session close.Add the detect of vm session
and start the session if session in closed status.
Signed-off-by: jgao <jgao@redhat.com>
> Fix npiv_hostdev_passthrough.py session close error

- libvirt/tests/cfg/virsh_cmd/pool/virsh_pool_auth.cfg
Ceph settings will be updated in ci, so update the value of
ceph_disk_name to EXAMPLE_DISK_NAME which will be replaced by ci.
> Update ceph_disk_name to EXAMPLE_DISK_NAME

- libvirt/tests/src/virsh_cmd/nodedev/virsh_nodedev_event.py
When we do nodedev reattach for interface devices, system will create it
as "eth0" then rename it to the actual device name. It is acceptable.
Update the script to fix the event not match issue.
> Fix the nodedev event not match issue

- libvirt/tests/cfg/nwfilter/nwfilter_vm_start.cfg
- libvirt/tests/src/nwfilter/nwfilter_vm_start.py
Check the parameters defined in clean-traffic should take precedence. If
no parameters is defined, the mac and ip of the own interface will then
be used in the rules.
> Define parameters in clean-traffic nwfilter

- libvirt/tests/src/virsh_cmd/domain/virsh_attach_detach_disk.py
The controller settings including pcie is not supported by ppc.
> attach_detech_disk: q35 controller settings are not for pseries

- libvirt/tests/cfg/controller/pcie_controllers.cfg
- libvirt/tests/src/controller/pcie_controllers.py
This is to support the newly added controller can be detected with
an index automatically instead of defining a fix number for its index
in order to avoid of below error in future when vm xml is changed.
error: XML error: Attempted double use of PCI Address 0000:06:00.0"
> pcie_controllers: support auto index

- libvirt/tests/cfg/virsh_cmd/domain/virsh_detach_device.cfg
- libvirt/tests/src/virsh_cmd/domain/virsh_detach_device.py
Since libvirt detach device APIs(detach-device, detach-device-alias)
works asynchronously, that means every call returns before the detach
operation returns.This patch is to test multiple continuous detach to
make sure a detach call will not be interrupted by other calls.
> Add new cases for mixed detach disk

- libvirt/tests/cfg/virsh_cmd/domain/virsh_hypervisor_cpu_compare.cfg
Using <cpu> node from 'virsh capabilities' is not supported on s390x,
s. https://bugzilla.redhat.com/show_bug.cgi?id=1850654
> Filter out hypervisor-cpu-compare on s390x

- libvirt/tests/cfg/virsh_cmd/domain/virsh_hypervisor_cpu_compare.cfg
On s390x, the expected comparison result is
"CPU described in <cpu-xml-filename> is identical to the CPU provided by hypervisor on the host",
s. https://bugzilla.redhat.com/show_bug.cgi?id=1850680
> Fix hypervisor-cpu-compare for host-processor on s390x

- libvirt/tests/src/migration/migrate_options_shared.py
Some exceptions are catched meaninglessly, which increased the debug
workloads greatly.
> migrate_options_shared: Remove meaningless exceptions catch

- libvirt/tests/cfg/migration/migrate_vm.cfg
This case doesn't make sense. When hugemem on src host is less than
vm mem, vm will fail to start in the first place, migration can't
be performed at all.
> migrate_vm: Remove case *.source_hugemem_less_than_vm_mem.*

- libvirt/tests/src/migration/migrate_vm.py
Libvirtd will be restarted immediately by systemd when it crashed,
so it is meaningless to do "libvirtd crash" check.
> migrate_vm: Remove meaningless "libvirtd crash" check

- libvirt/tests/cfg/migration/migrate_vm.cfg
Make the migration process longer by setting migration's speed to
have enough time to perform other checks.
> migrate_vm: Update to set migration speed

- libvirt/tests/src/numa/guest_numa.py
Issue, where automated tests were failing due to: _IndexError: list index out of range on libvirt/tests/src/numa/guest_numa.py", line 72, in replace_qemu_cmdline_ is fixed by this patch. The root cause is when the cmdline parameter is empty and the code is trying to parse it. This causes IndexError exception, that is now captured, and the code for replacing is skipped (there is no replacing needed, when the parameter is empty).
> Fix for "IndexError: list index out of range" 

- libvirt/tests/cfg/migration/migrate_with_virtual_devices.cfg
- libvirt/tests/src/migration/migrate_with_virtual_devices.py
The following rng backend are covered:
tcp(bind, connect), udp(bind_connect, connect), rdm, builtin
> Add migration test with rng device

- libvirt/tests/cfg/incremental_backup/incremental_backup_pull_mode.cfg
- libvirt/tests/src/incremental_backup/incremental_backup_pull_mode.py
Since libvirt-6.6.0-1.el8(bz1822631), libvirt starts to support pull mode
backup with tls enbaled. This patch is to add related test cases.
> Add cases for pull mode backup with tls enabled

- libvirt/tests/cfg/virtual_disks/virtual_disks_nbd.cfg
- libvirt/tests/src/virtual_disks/virtual_disks_nbd.py
After libvirt 6.6.0, client private key encryption is now supported
> Add client private key encryption cases on nbd

- libvirt/tests/cfg/svirt/libvirt_keywrap.cfg
- libvirt/tests/src/svirt/libvirt_keywrap.py
Depends on https://github.com/avocado-framework/avocado-vt/pull/2772
On s390x, QEMU supports control of dea/aes wrapping.
Per default they are enabled. Linux guests can generate
protected key tokens through the pkey kernel module if
the wrapping key is enabled.
Add test cases to minimally confirm that protected keys of
some aes type can be generated if wrapping key is available.
This way, we can confirm that disabling the wrapping key works.
> Add test cases for keywrap support on s390x

- libvirt/tests/cfg/memory/nvdimm.cfg
```
JOB ID     : 6f055a31ff8d0a011c4a28f10074e9819322301e
JOB LOG    : /root/avocado/job-results/job-2020-11-12T06.40-6f055a3/job.log
(1/1) type_specific.io-github-autotest-libvirt.nvdimm.back_file.no_label: PASS (128.84 s)
JOB TIME   : 130.50 s
```
> Fix the failure for nvdimm memory case as the qemu cmd line changed in the new version

- libvirt/tests/src/incremental_backup/incremental_backup_backing_chain.py
Now we use nbd_params to save nbd related configs for full
backup data download. This is modified by avocado-vt PR 2807.
So we need to use the new way to pass nbd configs when download
data.
> Use new way to prepare nbd configs for full backup data download

- libvirt/tests/src/virsh_cmd/host/virsh_maxvcpus.py
initialize gic_version to empty first
errors appear when running type_specific.io-github-autotest-libvirt.virsh.domblkerror.undefinded_error on aarch64
Signed-off-by: Li Zhijian <lizhijian@cn.fujitsu.com>
> Fix local variable 'gic_version' referenced before assignment

- libvirt/tests/cfg/virsh_cmd/nodedev/virsh_nodedev_dumpxml_chain.cfg
- libvirt/tests/src/virsh_cmd/nodedev/virsh_nodedev_dumpxml_chain.py
The dumpxml information is used to set up a vfio_ccw passthrough device.
The device hierarchy by cap is dasd -> ccw -> css. The css id is used to
configure the mdev.
Test minimally that the chain is valid and that the device are
of the right type for dasd passthrough.
> [nodedev-dumpxml] add dasd support on s390x

- libvirt/tests/src/nwfilter/nwfilter_vm_start.py
There is a negative test which undefine the clean-traffic nwfilter,
which will cause the 'clean-traffic' nwfilter missing. This will cause
many case needs 'clean-traffic' fail. Fix the issue by not undefine it.
> Fix the 'clean-traffic' nwfilter missing issue

- libvirt/tests/src/migration/migrate_vm.py
We should always do testing with selinux mode set to enforcing, or
we may miss bugs related to libvirt sVirt or selinux-policy.
> migrate_vm: Remove steps of setting selinux mode to permissive

- libvirt/tests/src/cpu/vcpu_affinity.py
On avocado:82lts online(cpu) returns False if cpu is already online.
Therefore check whether a cpu is in online_list before online it.
> vcpu_affinity: check cpu status before online cpu

- libvirt/tests/cfg/bios/virsh_boot_sysinfo.cfg
- libvirt/tests/src/bios/virsh_boot_sysinfo.py
Add fwcfg type of sysinfo element test cases
1) Define/start guest with fw_cfg sysinfo
2) Define/start guest with invaild entry value for fw_cfg type sysinfo
> Add fwcfg type of sysinfo element test cases

- libvirt/tests/src/conf_file/qemu_conf/auto_dump.py
func 'kill' of multiprocessing.Process was brought in from python3.7
therefore not availabe on python3.6. Replacing with 'terminate' could
allow test running on python3.6 without throwing out error like:
`AttributeError: 'Process' object has no attribute 'kill'`
> auto_dump: replace process.kill with process.terminate

- libvirt/tests/cfg/virt_cmd/virt_xml_validate.cfg
The pool name was set incorrectly. This is to fix it by setting correct
default libvirt pool name.
> Update incorrect param

- libvirt/tests/src/migration/migrate_options_shared.py
Original test.cancel was not thrown by the avocado framework which is
because another invalid file removing in final cleanup phase fails. So
this is to avoid of that invalid removing step in order to throw the
original exception.
> Fix test.cancel was not thrown

- libvirt/tests/cfg/svirt/libvirt_ap_passthrough.cfg
- libvirt/tests/src/svirt/libvirt_ap_passthrough.py
Depends on https://github.com/avocado-framework/avocado-vt/pull/2780
Add test cases for single device passthrough hot- and coldplug.
This feature is only available on s390x.
> Add vfio-ap test cases

- libvirt/tests/cfg/incremental_backup/incremental_backup_multidisk.cfg
- libvirt/tests/src/incremental_backup/incremental_backup_multidisk.py
When vm has new disk attached, the backup mode should be different
for different disks. e.g. The first disk may do a incremental backup
and new disk can only have a full backup. This script is to test
multiple disks with different backup modes.
> Add case for multiple disks backup

- libvirt/tests/cfg/usb_device.cfg
- libvirt/tests/src/usb_device.py
Start guest without usb cotroller in guest xml. The default usb controller will be added into xml automatically.
For q35 guest, will add usb3.
Check if the controller is added as expected.
> Add cases for starting guest without usb cotroller in guest xml

- libvirt/tests/cfg/migration/migrate_options_shared.cfg
- libvirt/tests/src/migration/migrate_options_shared.py
This PR adds a migration case - cancel a concurrent migration.
In this case, a VM will be migrated concurrently. It will kill one
of the migration processes to check if the other is working well.
> Add a case for concurrent migration

- libvirt/tests/cfg/controller/pcie_controllers.cfg
- libvirt/tests/src/controller/pcie_controllers.py
This is to add new cases for hotplug_option by attaching disk device twice
with specified same pci address for both hotplug_option=on and off.
> Add cases for hotplug_option

- libvirt/tests/cfg/virsh_cmd/domain/virsh_numatune.cfg
- libvirt/tests/src/virsh_cmd/domain/virsh_numatune.py
The tests working with numatune parameter may failed on setups with nodeset != 0,1. This fix is getting numa nodes with memory dynamically and therefore it allows to pass the tests with any setup with at least two numa nodes.
> Fix virsh numatune

- libvirt/tests/src/virsh_cmd/domain/virsh_attach_detach_interface.py
Tests sometimes fail with 'Detach Failed: xml still exist after detach'
which should be fixed after waiting for detach event to check vm xml.
> virsh_attach_detach_interface: wait for detach event to finish cmd

- libvirt/tests/cfg/cpu/max_vcpus.cfg
- libvirt/tests/src/cpu/max_vcpus.py
Maximum CPUs changed from 384 to 512, so update VM vcpus accordingly.
> Update the value of guest's vcpus for ioapic_iommu test

- libvirt/tests/cfg/timer_management.cfg
Remove tsc cases for pseries.
Configuring the 'tsc' timer is not supported for virtType=kvm
arch=ppc64le machine=pseries-rhelx.x.x guests.
> tsc timer is not supported on pseries

- libvirt/tests/cfg/virsh_cmd/nodedev/virsh_nodedev_dumpxml_chain.cfg
Depending on the kernel, the output of commands `nodedev-list` and
`nodedev-dumpxml` is slightly different but equivalent.
> [nodedev-dumpxml] Remove kernel-dependent check for dasd

- libvirt/tests/cfg/virsh_cmd/nodedev/virsh_nodedev_list.cfg
- libvirt/tests/src/virsh_cmd/nodedev/virsh_nodedev_list.py
Use the partial comparison for s390x only
-----------------------------------------
A dasd block device identifier listed by nodedev-list
has a different format. Allow for non-exact comparison of
identifiers from sysfs and nodedev-list in order to avoid
reimplementing the identifier creation logic in the test.
For example, info from sysfs block_dasda will match
block_dasda_IBM_750000000FRB71_0230_0c.
Add css and ccw caps check
--------------------------
dasd block devices have ccw parents that hold important information
for passthrough configuration, e.g. driver and subchannel id.
ccw devices have css that hold information to check if a device
has already been assigned to passthrough driver or not.
Requires cio_ignore=all
--------------------------------
Tests might fail if subchannel io …
> [nodedev-list] add support for dasd on s390x

- libvirt/tests/cfg/virsh_cmd/secret/virsh_secret_set_get.cfg
- libvirt/tests/src/virsh_cmd/secret/virsh_secret_set_get.py
This PR adds 3 cases:
1) Set a secret value with --file option.
2) Set a secret value with --file and --plain option.
3) Set a secret value with --interactive option.
depends on 
https://github.com/avocado-framework/avocado-vt/pull/2832
https://github.com/avocado-framework/avocado-vt/pull/2833
> Add cases to check secret-set-value --file and --interactive 

- libvirt/tests/cfg/numa/guest_numa.cfg
Before
```
JOB ID     : ee6dfa5f59ea40535b1e1392f623ae8b2fe96403
JOB LOG    : /root/avocado/job-results/job-2020-12-10T06.06-ee6dfa5/job.log
(1/1) type_specific.io-github-autotest-libvirt.guest_numa.possitive_test.hugepage.per_node.2M.topology.numatune_memnode.m_strict.numatune_mem: FAIL: (?:id=ram-node0),prealloc=yes,mem-path=\S+,size=\d+M?|prealloc=yes,mem-path=\S+,size=\d+M?,(?:id=ram-node0) not found in vm qemu cmdline (42.17 s)
JOB TIME   : 43.59 s
```
After
```
JOB ID     : cd5fe3f71c0f542e150f6a5306d8455ad60acd6f
JOB LOG    : /root/avocado/job-results/job-2020-12-10T06.13-cd5fe3f/job.log
(1/1) type_specific.io-github-autotest-libvirt.guest_numa.possitive_t …
```
> Add more mapping pattern as new libvirt version change the qemu cmd line

- libvirt/tests/cfg/svirt/libvirt_keywrap.cfg
- libvirt/tests/src/svirt/libvirt_keywrap.py
Depends on https://github.com/avocado-framework/avocado-vt/pull/2836
Tests from 42a00e3b32258d64900997ee1b4628f9a68ffc1d passed
because all commands were executed on host.
It also looks like there was a regression introduced by
force pushing local changes to remote before merge.
1. Use the VMXML instance to manipulate the domain xml.
2. Use correct test parameter names.
> Fix keywrap test

- libvirt/tests/src/virtual_network/iface_network.py
[1] fixes the issue of virsh net-dhcp-leases not showing
all leases from time to time which is tested with the 'with_2net'
test case (doing 20 rounds, s. cfg).
The test would therefore fail before 6.5 with message
'DCHP lease not found <round-number>'.
Skip this test before 6.5.
[1] libvirt upstream patch 876211ef4a192df1603b45715044ec14567d7e9f
> Skip virtual network test before libvirt 6.5

- libvirt/tests/src/migration/migrate_options_shared.py
Some secrets may not be deleted correctly in some cases, so clean
up the environment before creating a secret.
> migration: Delete the secret before creating it

- libvirt/tests/cfg/virtual_device/watchdog.cfg
Added new variable to configuration file which allows leaked clusters after the test. This is a safe option in a case, when the VM is closed unexpectedly(from QEMU perspective) by test and this is required by test. Also, when no data is harmed. Leaked clusters happen in 90% of executions of this test, but with no harm to data.
> Clusters may leak after the watchdog test.

- libvirt/tests/src/libvirt_rng.py
The test code timed out the command reading entropy wiht hexdump after
3 seconds. This led to the test never ending on my environments, possibly
because of the created load of reading with hexdump endlessly.
Instead, only read 100 bytes to confirm virtio device delivers entropy.
> [libvirt_rng] Fix brittle test

- libvirt/tests/src/virsh_cmd/domain/virsh_setvcpus.py
'cpu' could be removed in previous steps, therefore check its
existance before removing it.
> Check whether 'cpu' exists before removing it

- libvirt/tests/cfg/cpu/diagnose_data.cfg
- libvirt/tests/src/cpu/diagnose_data.py
By having bigger SCCB size, diag318 data can be recorded for more
than 240 vcpus.
> Add test case for extended SCCB support on s390x

- libvirt/tests/cfg/virtual_disks/at_dt_iscsi_disk.cfg
- libvirt/tests/src/virtual_disks/at_dt_iscsi_disk.py
1. Add packed attribute test in virtio disk driver
2. Add packed attribute test in virtio-scsi controller
> Add virtio packed test cases in disk and scsi controller

- libvirt/tests/cfg/libvirt_mem.cfg
- libvirt/tests/src/libvirt_mem.py
For old version, the scenario
libvirt_mem.negative_test.start_error.invalid_slot
libvirt_mem.negative_test.setmem_error.without_numa
will cause start error but in new version, it will cause define error, just fix it
> Fix define error for pervious start error cases

- libvirt/tests/src/incremental_backup/incremental_backup_checkpoint_cmd.py
Since libvirt-6.6.0-9.el8 (ref: bz1901830), libvirts starts to allow
redefine VM backup checkpoint without the domain XML. This will fail
our existing case, which expected a failure when dmoain XML not
provided. So update the script to align with the change.
> Allow redefine checkpoint without domain XML

- libvirt/tests/cfg/numa/numa_memory.cfg
- libvirt/tests/src/numa/numa_memory.py
This fix introduced a possibility to update numa nodes and cpu sets dynamically per setup. This should fix failing cases on setups, that differ from default (0,1..). Cpus are choosen randomly based on a number of available cpu cores, numa nodes per index of available nodes.
> Fix parameters that are static and may differ from default system setup (CPUs, Numa nodes)

- libvirt/tests/cfg/numa/guest_numa.cfg
- libvirt/tests/src/numa/guest_numa.py
The numa guest tests were failing on some setups, where the numa memory nodes were not allocated to nodes 0 and 1. This update make this test more robust to different setups and update it's config dynamically per current setup.
> Dynamic numa guest nodes fix

- libvirt/tests/cfg/cpu/diagnose_data.cfg
- libvirt/tests/src/cpu/diagnose_data.py
Check debug_stats is now available for a higher number of cpus.
AssertionError doesn't have field message. Use exception directly.
In case of failure the result will be reported as
"FAIL: Test failed: Expected counters to be none zero, got: diag 318 [...]"
> [diagnose_data] update supported vcpu number

- libvirt/tests/cfg/virtual_device/filesystem_device.cfg
- libvirt/tests/src/virtual_device/filesystem_device.py
1. Destroy a virtiofs guest
2. Modify guest domain, add invalid option '-foo' and start guest.
Guest start failure is expected.
3. Correct guest domain and start guest.
Related BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1897105
This issue has been fixed in libvirt-6.10.0-1.el8.
> Add testcase for virtiofs guest startup process

- libvirt/tests/cfg/virsh_cmd/domain/virsh_migrate_setmaxdowntime.cfg
- libvirt/tests/src/virsh_cmd/domain/virsh_migrate_setmaxdowntime.py
Translation of conf_type from monolithic daemon mode to modular daemon
mode is complex and depends on the parameter to be configured heavily,
while the reverse translation is much more simple by tranlating all the 
conf_type of modular daemon mode to "libvirtd". This commit sets the 
conf_type to the value of modular daemon mode in <test>.cfg and the 
<test>.py or avocado-vt utils will translate to "libvirtd" if test env 
is monolithic daemon mode.
> virsh_migrate_setmaxdowntime: Fix conf issue in modular daemon mode

- libvirt/tests/src/virtual_network/iface_unprivileged.py
Before:
```
JOB ID     : 35dfd22071dd366a95f4a03883a2a56016ba5878
JOB LOG    : /root/avocado/job-results/job-2020-12-23T03.38-35dfd22/job.log
(1/1) type_specific.io-github-autotest-libvirt.virtual_network.iface_unprivileged.precreated.host_macvtap: ERROR: Login timeout expired    (output: '\x1b[?25l\x1b[m\x1b[H\x1b[J\x1b[1;1H\x1b[20;7H\x1b[mUse the ^ and v keys to change the selection.                       \n      Press \'e\' to edit the selected item, or \'c\' for a command prompt.   \x1b[4;80H \x1b[7m\x... (85.14 s)
JOB TIME   : 87.16 s
```
After
```
JOB ID     : 18d65f29baf1cf527fa496f1a05e7523724a5b71
JOB LOG    : /root/avocado/job-results/job-2020-12-23T05.18-18d65f2/job.log
(1/1) …
```
> Extend the timeout for unprivilaged login

- libvirt/tests/src/virtual_device/watchdog.py
The test listens to events with the 'virsh event' command.
libvirt accepted passing both '--all' and '--event' but will now report
"Options --all and --event are mutually exclusive" and not start.
The test code uses 'aexpect.client.sendline' which can't report on error.
Therefore the test fails the command silently leading to later test failure.
As watchdog events are a subset of all events use only '--all'.
> [watchdog] Fix virsh command line

- libvirt/tests/src/migration/migrate_vm.py
Device hotplugging will fail if there is no extra pcie-root-port
for q35 vm. And pcie-root-port controller can't be hotplugged,
so we need to cold plug pcie-root-port controllers before vm starts.
> migrate_vm: Cold plug two pcie-root-port controllers for q35 vm

- libvirt/tests/src/virsh_cmd/domain/virsh_migrate.py
Device hotplugging will fail if there is no extra pci slot
for q35 vm. So we need to cold plug a pcie-to-pci-bridge 
controller before vm starts.
> virsh_migrate: Cold plug pcie-to-pci-bridge controller for q35 vm

- libvirt/tests/cfg/controller/pcie_controllers.cfg
Extra quote caused the string match failed. This fix is to remove those quote.
> pcie_controllers:fix incorrect quote

- libvirt/tests/cfg/numa/guest_numa.cfg
Fix numa issue in guest_numa.cfg: 
TestFail: ...host-nodes=[0-9,],policy=bind not found in vm qemu cmdline
> Fix numa issue in guest_numa.cfg

- libvirt/tests/cfg/virsh_cmd/pool/virsh_pool.cfg
- libvirt/tests/src/virsh_cmd/pool/virsh_pool.py
Support --source-initiator option in iscsi-direct pool:
1. Add libvirt version_compare
2. Update iscsi_initiator to source_initiator to match the option
> Support --source-initiator option in iscsi-direct pool

- libvirt/tests/src/papr_hpt.py
The function 'get_cpu_arch()' is changed on avocado:82. To adapt to
the change and keep 69lts working, we call new function if it's
available.
> papr_hpt:use new func 'get_family()' provided by avocado:82

- v2v/tests/cfg/function_test_esx.cfg
- v2v/tests/src/function_test_esx.py
1) Add a new postive case for --mac xxx:ip:xxx option.
Notes: This case requires the guest has at least two interfaces
in order to connect to the VM normally.
2) Update the way of passing paramters for invalid_mac_ip case
> v2v: add a new positive --mac static ip case

- libvirt/tests/cfg/migration/migrate_options_shared.cfg
- libvirt/tests/src/migration/migrate_options_shared.py
Translation of conf_type from monolithic daemon mode to modular daemon
mode is complex and depends on the parameter to be configured heavily,
while the reverse translation is much more simple by tranlating all the
conf_type of modular daemon mode to "libvirtd". This commit sets the
conf_type to the value of modular daemon mode in <test>.cfg and the
<test>.py or avocado-vt utils will translate to "libvirtd" if test env
is monolithic daemon mode.
> migrate_options_shared: Update the conf file logic for modular daemon

- libvirt/tests/cfg/incremental_backup/incremental_backup_pull_mode.cfg
- libvirt/tests/src/incremental_backup/incremental_backup_pull_mode.py
Now libvirt supports to encrypt scratch data of pull-mode backup.
This patch adds cases to cover luks encryption scenarios.
> Add cases for luks enabled pull-mode backup

- libvirt/tests/cfg/virt_admin/management/virt_admin_server_update_tls.cfg
- libvirt/tests/src/virt_admin/management/virt_admin_server_update_tls.py
This PR adds a case as below:
[server-update-tls] notify server to update TLS related files online
depends on:
https://github.com/avocado-framework/avocado-vt/pull/2855
https://github.com/avocado-framework/avocado-vt/pull/2854
> Add a case about virt-admin server-update-tls

- libvirt/tests/cfg/migration/migrate_vm.cfg
- libvirt/tests/src/migration/migrate_vm.py
The qmp command nbd-server-add has been deprecated and replaced
with block-export-add on qemu5.2, so update accordingly.
> migrate_vm: Replace nbd-server-add with block-export-add

- libvirt/tests/src/memory/nvdimm.py
ppc tests requires pkg ndctl. The installation of the pkg might
fail sometimes. Stop testing if pkg cannot be installed.
> Check whether pkg is successfully installed

- libvirt/tests/cfg/virsh_cmd/domain/virsh_domblkthreshold.cfg
block_threshold value need to be less than image size filled up
> Fix domblkthreshold mirror mode blockcommit cases

- libvirt/tests/cfg/virsh_cmd/domain/virsh_event.cfg
- libvirt/tests/src/virsh_cmd/domain/virsh_event.py
- IDE is not supported by pseries, update to scsi
- Removal of dimm device should succeed on pseries
- The range of numa cells should be contiguous
> Fix errors of virsh_event tests

- libvirt/tests/src/virsh_cmd/domain/virsh_blockcopy.py
- libvirt/tests/src/virsh_cmd/domain/virsh_blockjob.py
- libvirt/tests/src/virsh_cmd/domain/virsh_create.py
As of now, nvram option will be automatically added in vm.undefine if
needed.
> Remove duplicated nvram option

- libvirt/tests/cfg/virsh_cmd/domain/virsh_detach_device.cfg
On s390x, cdrom is attached through scsi. Fix test configuration.
> [detach_device][cdrom] fix test for s390x

- libvirt/tests/cfg/virsh_cmd/domain/virsh_domrename.cfg
- libvirt/tests/src/virsh_cmd/domain/virsh_domrename.py
domrename guest with snapshots is supported after
libvirt-6.10.0.
> Fix the case for domrename guest with snapshots

- libvirt/tests/cfg/virtual_device/filesystem_device.cfg
- libvirt/tests/src/virtual_device/filesystem_device.py
virtio-fs requires memory backing in one of the following ways:
1. by hugepages
2. by file
The current test suite only covers 1.
For 2. no hugepages must be configured. The qemu.conf value `memory_backing_dir` has a valid default value,
e.g. on RHEL `/var/lib/libvirt/qemu/ram`.
More details on https://libvirt.org/kbase/virtiofs.html.
> [virtual_devices][filesystem_device] add variant file backed

- libvirt/tests/src/virtual_device/tpm_device.py
before 
Domain avocado-vt-vm1 defined from xxx
after
Domain 'avocado-vt-vm1' defined from xxx
> Fix for matching failure as '' added in output around vm name

- libvirt/tests/cfg/virsh_cmd/domain/virsh_create.cfg
- libvirt/tests/cfg/virsh_cmd/domain/virsh_define.cfg
- libvirt/tests/cfg/virsh_cmd/domain/virsh_domrename.cfg
- libvirt/tests/src/virsh_cmd/domain/virsh_create.py
- libvirt/tests/src/virsh_cmd/domain/virsh_domrename.py
New automated test cases added to check if the virsh utility is able to create, define and domrename the VM with a dot(.) in the name.
> Add case to support dot(.) in vm name

- libvirt/tests/cfg/cpu/vcpu_feature.cfg
Feature cr8legacy is not supported by pseries.
> vcpu_feature:Remove case unsupported by pseries

- libvirt/tests/cfg/incremental_backup/incremental_backup_checkpoint_cmd.cfg
- libvirt/tests/src/incremental_backup/incremental_backup_checkpoint_cmd.py
Since bz1874846, libvirt starts to support checking if image has correct
bitmaps when redefine libvirt checkpoint. This is to make sure the
libvirt's checkpoint metadata and qcow2 image have exactly same bitmap
info.
> Add cases to check image having correct bitmap when redefine checkpoint

- libvirt/tests/cfg/virsh_cmd/domain/virsh_change_media_matrix.cfg
IDE controllers are unsupported for machine type 'aarch', therefore
change it to 'scsi'
> virsh_change_media_matrix: Set device bus to 'scsi' for aarch tests

- libvirt/tests/src/libvirt_mem.py
> libvirt_mem:replace function get_cpu_arch with get_family

- libvirt/tests/cfg/virtual_device/filesystem_device.cfg
- libvirt/tests/src/virtual_device/filesystem_device.py
NUMA is not available on s390x. Shared memory without NUMA has been fully
supported since libvirt commit bff2ad5d6b1f25da02802273934d2a519159fec7.
Skip NUMA configuration on s390x. The new config value defaults to "yes" to
maintain current behavior, that is, create NUMA configuration by default.
> [virtual_device][filesystem_device] allow for shared memory without numa

- libvirt/tests/src/virsh_cmd/domain/virsh_dumpxml.py
with_cpu test will customize cpu. Different platforms require special
customization.
Currently only s390 and x86_64 have added customized info. So cancel
with_cpu tests on unsupported platform.
> Cancel virsh_dumpxml with_cpu tests on unsupported platform

- libvirt/tests/src/virsh_cmd/network/virsh_net_define_undefine.py
- libvirt/tests/src/virsh_cmd/network/virsh_net_start.py
Recently the dhcp/range has added a element expiry time, so the
definition change from dict to a class. Update some network
define functions in libvirt.py file accordingly.
> Update the dhcp/range as the definition changes

- libvirt/tests/cfg/migration/migrate_network.cfg
- libvirt/tests/src/migration/migrate_network.py
This PR adds a case as below:
1. check if a VM with direct type interface assigned from
virtual network can be migrated correctly.
(auto-generated macvtap device name + macvtap device name already
exists on dest host)
depends on https://github.com/avocado-framework/avocado-vt/pull/2842
> Add a case to migrate VM with direct type interface

- libvirt/tests/src/virsh_cmd/domain/virsh_domblkerror.py
Install dependent packages to ensure shell command runs well.
> Fix virsh_domblkerror.py command not found error

- libvirt/tests/src/incremental_backup/incremental_backup_backing_chain.py
- libvirt/tests/src/incremental_backup/incremental_backup_checkpoint_cmd.py
- libvirt/tests/src/incremental_backup/incremental_backup_multidisk.py
- libvirt/tests/src/incremental_backup/incremental_backup_pull_mode.py
- libvirt/tests/src/incremental_backup/incremental_backup_push_mode.py
Some failed cases may leave checkpoints metadata, and they will
block future test due to checkpoint name conflict. This patch
is to make sure to remove any existing checkpoits metadata before
test.
> Clean up checkpoints metadata before create new one

- libvirt/tests/cfg/virtual_network/iface_rename.cfg
- libvirt/tests/src/virtual_network/iface_rename.py
There should not be error message in libvirtd log when rename
veth interface immediately after it is created.
> Check the libvirtd log when rename the veth interface

- libvirt/tests/cfg/migration/migrate_options_shared.cfg
It was introduced by 8a7d92931a5232a.
The values of remote libvirtd configuration should be updated.
> migration: fix remote libvirtd service startup failure

- libvirt/tests/cfg/cpu/vcpu_feature.cfg
Feature cr8legacy is not supported by aarch64.
> vcpu_feature: Remove case unsupported by aarch64

- libvirt/tests/src/memory/hmat.py
```
JOB ID     : b35f4a8196b45bf8f596137717f1706ceb9da0de
JOB LOG    : /root/avocado/job-results/job-2021-01-25T21.04-b35f4a8/job.log
(1/1) type_specific.io-github-autotest-libvirt.hmat.hmat: ERROR: local variable 'vm' referenced before assignment (6.56 s)
```
Signed-off-by: Li Zhijian <lizhijian@cn.fujitsu.com>
> Fix local variable 'vm' referenced before assignment

- libvirt/tests/src/incremental_backup/incremental_backup_backing_chain.py
- libvirt/tests/src/incremental_backup/incremental_backup_multidisk.py
- libvirt/tests/src/incremental_backup/incremental_backup_push_mode.py
This is to align with avocado-vt PR2852. Now the 'target' and
'scratch' tag can have subelement 'encryption'.
> Use new target and scratch param structure for incremental backup

- libvirt/tests/cfg/virtual_disks/startup_policy.cfg
- libvirt/tests/cfg/virtual_disks/virtual_disks_multivms.cfg
IDE controllers are unsupported for machine type 'aarch', therefore
change it to 'scsi'
Fix following tests:
startup_policy.startupPolicy.mandatory.device_type.cdrom.file.default
startup_policy.startupPolicy.mandatory.device_type.cdrom.file.update_policy.default.live
startup_policy.startupPolicy.mandatory.device_type.cdrom.file.update_policy.default.config
startup_policy.startupPolicy.mandatory.device_type.cdrom.file.update_policy.default.persistent
startup_policy.startupPolicy.mandatory.device_type.cdrom.file.update_policy.policy_and_source
startup_policy.startupPolicy.mandatory.device_type.cdrom.volume.dir_pool
startup_policy.startupPolicy.optional.device_type.cdrom.file.default
startup_policy.startupPolicy.optional.device_type.cdrom.file.update_policy.default.live …
> startup_policy: Set device bus to 'scsi' for aarch tests

- libvirt/tests/cfg/virtual_disks/virtual_disks_multidisks.cfg
check_readonly() in virtual_disks_multidisks treats device target 'hdc' as a cdrom
```
$ avocado run --vt-type libvirt --vt-arch aarch64 --vt-machine-type arm64-mmio $tests
JOB ID     : f37ff4462ab0dea0803ac9ec5fd66d704d619d9c
JOB LOG    : /root/avocado/job-results/job-2021-01-26T21.53-f37ff44/job.log
(1/3) type_specific.io-github-autotest-libvirt.virtual_disks.multidisks.coldplug.single_disk_test.disk_readonly_nfs_cdrom.co …
```
> virtual_disks_multidisks: fix incorrect device target on aarch64

- libvirt/tests/src/cpu/guestpin.py
Fix the following issue
------
2021-01-26 09:16:26,300 stacktrace       L0045 ERROR| checking for gcc... no
2021-01-26 09:16:26,300 stacktrace       L0045 ERROR| checking for cc... no
2021-01-26 09:16:26,300 stacktrace       L0045 ERROR| checking for cl.exe... no
2021-01-26 09:16:26,301 stacktrace       L0045 ERROR| configure: error: in `/home/stress-1.0.4':
2021-01-26 09:16:26,301 stacktrace       L0045 ERROR| configure: error: no acceptable C compiler found in $PATH
------
> Install gcc to build stress tool

- libvirt/tests/cfg/virsh_cmd/domain/virsh_hypervisor_cpu_compare.cfg
https://www.redhat.com/archives/libvir-list/2020-October/msg00696.html
------
On some architectures, e.g. aarch64 and s390x, the output of
`virsh capabilities` is not suitable for use in
`virsh hypervisor-cpu-baseline`. 
------
> Filter out hypervisor-cpu-compare on aarch64

- libvirt/tests/cfg/virsh_cmd/domain/virsh_blockcopy.cfg
Allow multiple times snapshots before call blockcopy
> Add blockcopy shallow option case

- libvirt/tests/cfg/virsh_cmd/network/virsh_net_dhcp_leases.cfg
- libvirt/tests/src/virsh_cmd/network/virsh_net_dhcp_leases.py
Support set lease info in network definition
lease is supported for ip/dhcp/range and ip/dhcp/host since
libvirt-6.2. Add the test cases for network leases.
> Add test cases for network leases

- libvirt/tests/src/virtual_device/video_devices.py
Only virtio devices support packed virtqueues, added the element
packed to the virtio video devices xml instead other kinds of
video devices xml snippet.
> Fix the case with qxl secondary video device with packed virtqueues

- libvirt/tests/src/virsh_cmd/host/virsh_freepages.py
Since there are setups, where the NUMA nodes with memory can be assigned
in other than linear order, test must support these setups as well.
Therefore, this fix is comming with an assignmnent of NUMA nodes with
memory to the list for checking.
Since there is an existing bug which prevents from execution tests on
setups with other than linear order, this fix adds part for canceling
tests that would not work until the bug is fixed.
Signed-off-by: Kamil Varga <kvarga@localhost.localdomain>
> Dynamic Numa nodes usage added into freepages function

- libvirt/tests/src/virsh_cmd/domain/virsh_dumpxml.py
We should get the guest cpu related info from virsh domcapabilities
instead of virsh capabilities
> Update the API for retrieving guest cpu related info

- libvirt/tests/src/bios/boot_integration.py
```
JOB ID     : e91974da8e2d3afa3582443d66b8a43bc9655165
JOB LOG    : /root/avocado/job-results/job-2021-01-28T01.33-e91974d/job.log
(1/1) type_specific.io-github-autotest-libvirt.boot_integration.by_ovmf.boot_dev.define_start_destroy_save_restore_undefine: PASS (60.45 s)
JOB TIME   : 61.61 s
(.libvirt-ci-venv-ci-runtest-PyWYH0) [root@dell-per730-66 tp-libvirt]# avocado run --vt-type libvirt --vt-machine-type q35 boot_integration.by_ovmf.boot_order.define_start_destroy_save_restore_undefine
JOB ID     : 1a1a3a6688f211c6e06011daec3a82070f336a59
JOB LOG    : /root/avocado/job-results/job-2021-01-28T01.36-1a1a3a6/job.log
(1/1) type_specific.io-github-autotest-libvirt.boot_integration.by_ovmf.boot_order.define_s …
```
> Update mapping pattern for bios cases

- libvirt/tests/src/virtual_network/iface_coalesce.py
old version:
```
Coalesce parameters for macvtap0:
Cannot get device coalesce settings: Operation not supported
```
New version:
```
netlink error: Operation not supported
```
Test result:
```
JOB ID     : 3b17ff42c282894aa443bbf6b0ac58d89f0c19fe
JOB LOG    : /root/avocado/job-results/job-2021-01-28T01.00-3b17ff4/job.log
(1/1) type_specific.io-github-autotest-libvirt.virtual_network.iface_coalesce.positive_testing.net_macvtap.iface-network: PASS (6.73 s)
JOB TIME   : 8.16 s
```
> Fix the err msg mapping for new release

- libvirt/tests/cfg/migration/migrate_options_shared.cfg
Two settings for remote libvirtd log configuration were missing
in previous code.
> migration: Add missing settings

- libvirt/tests/cfg/virsh_cmd/domain/virsh_vcpupin.cfg
To avoid misconfiguration issues, add 'vms' to subtest cfg.
> Add 'vms' to vcpupin..multi_dom

- libvirt/tests/cfg/daemon/kill_started.cfg
- libvirt/tests/src/daemon/kill_started.py
During the testing on aarch64, we found that it takes more than 1 second to
finish the libvirtd restarting with signal SIGABRT and SIGSEGV
Signed-off-by: Li Zhijian <lizhijian@cn.fujitsu.com>
> kill_started: wait a little longer for SIGABRT and SIGSEGV

- libvirt/tests/cfg/virsh_cmd/network/virsh_net_autostart.cfg
- libvirt/tests/src/virsh_cmd/network/virsh_net_autostart.py
Restarting libvirtd without host reboot will not turn the
autostart network status from inactive to active.
> Add one more scenario about network autostart

- libvirt/tests/cfg/virtual_network/iface_bridge.cfg
- libvirt/tests/src/virtual_network/iface_bridge.py
When update an <interface>, and the interface type changed from type='network'
where the network was an unmanaged bridge (so actualType == bridge) to type='bridge'
(i.e. actualType also == bridge), the update without the recently fix would fail
due to the perceived change in type. Add the test case about updating bridge type
interface with network type xml.
> Update bridge type interface with network type xml

- libvirt/tests/cfg/virsh_cmd/volume/virsh_vol_create_from.cfg
Fix "insufficient free space" in logical pool
> Fix "insufficient free space" in logical pool

- libvirt/tests/src/incremental_backup/incremental_backup_backing_chain.py
- libvirt/tests/src/incremental_backup/incremental_backup_checkpoint_cmd.py
- libvirt/tests/src/incremental_backup/incremental_backup_multidisk.py
- libvirt/tests/src/incremental_backup/incremental_backup_pull_mode.py
- libvirt/tests/src/incremental_backup/incremental_backup_push_mode.py
enable_inc_backup_for_vm() added in avocado-vt/virttest/utils_backup.py.
Use it to make code clean.
> Use enable_inc_backup_for_vm method to make code clean

- libvirt/tests/cfg/virsh_cmd/domain/virsh_change_media.cfg
- libvirt/tests/cfg/virsh_cmd/domain/virsh_detach_device.cfg
- libvirt/tests/cfg/virsh_cmd/domain/virsh_update_device.cfg
- libvirt/tests/cfg/virsh_cmd/domain/virsh_update_device_matrix.cfg
IDE controllers are unsupported for aarch64.
a) Skip IDE option tests on aarch64
b) Replace IDE device with SCSI
> Fix IDE related tests on aarch64

- v2v/tests/cfg/function_test_esx.cfg
- v2v/tests/src/function_test_esx.py
1) Improve checkpoint usage, so mutiple checkpoint can be used easily.
2) Add spice-ga and rhev-apt checkpoint.
3) Add signature checkpoint for rhev-apt.exe in windows guest.
> v2v: update checkpoint for windows guests

- v2v/tests/cfg/v2v_options.cfg
The vms requires guest 'avocado-vt-vm1' which is not used by v2v.
It's annoying when running it on local host manually.
> v2v: clean vms variant for v2v_options job

- v2v/tests/src/function_test_esx.py
The qemu-guest-agent service name is not 'qeme-guest-agent' or
'qemu-ga', it's "qemu-ga@virtio\x2dports-org.qemu.guest_agent.0.service".
> v2v: fix qemu-ga service not found on SUSE

- libvirt/tests/src/controller/controller_functional.py
avocado-vt only use virt machine type on aarch64
> Fix wrong machine type on aarch64

- v2v/tests/src/function_test_esx.py
When VM boots up and the 'ipconfig /all' may not contain any
static ip values, it will cause execption.
> v2v: fix IndexError when static IP is not found

- libvirt/tests/src/serial/serial_functional.py
This test parses qemu cmd line to get serial option and diff it with
expect serial info.
Add expect serial info of aarch64.
I use below cmd to start a aarch64 guest, then check qemu cmdline to get default
serial info.
------
avocado run --vt-type libvirt --vt-arch aarch64 --vt-machine-type arm64-mmio \
unattended_install.import.import.default_install.aio_native
------
> Add expect serial info of aarch64.

- libvirt/tests/cfg/memory/nvdimm.cfg
- libvirt/tests/src/memory/nvdimm.py
The old behavior is throwing out error when starting vm. Currently
defining vm would fail. The case needs update to move the check
ahead to defining step.
> nvdimm:check minimum target size when defining vm

- libvirt/tests/cfg/virtual_device/input_devices.cfg
ps2 is not supported by pseries.
> Remove tests of input devices with ps2 bus from pseries tests

- libvirt/tests/cfg/migration/migrate_options_shared.cfg
The default value of migrate_tls_x509_verify was changed to '1',
so set it as '0' for native_tls.no_verify_client test.
> Set migrate_tls_x509_verify to '0' to disable peer verification

- libvirt/tests/cfg/virsh_cmd/domain/virsh_update_device.cfg
> Fix the IDE controller which is not supported on aarch64

- libvirt/tests/src/virsh_cmd/snapshot/virsh_snapshot_disk.py
The bug 1083345 said this error output was expected. So we'd better to
log the information instead of raising an exception.
> virsh_snapshot_disk: use log not cancel

- libvirt/tests/src/virtual_device/filesystem_device.py
Because of exsiting issue, need to recover the env manually.
> Fix the edit_start case of virtiofs

- libvirt/tests/cfg/svirt/svirt_virt_install.cfg
- libvirt/tests/src/svirt/svirt_virt_install.py
a) virt-install model vga is unsupported on aarch64, use virtio
b) set undefine nvram option on aarch64
> Fix svirt.virt_install on aarch64

- libvirt/tests/src/virsh_cmd/domain/virsh_event.py
1) The guest name returned by virsh cmds has been added with quote marks
now. Need to fix it to avoid regex failure.
2) The guest with only memory hotplug enabled xml snippet can not be
defined. Need to config the numa node before defining the guest now.
> Fix the virsh event issues

- .github/pull_request_template.md
Add the github a pull request template[1] for bug fixes, new cases, and tiny
fixes. They will help the contributors provide necessary information of their
pull requests.
[1]:
https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/creating-a-pull-request-template-for-your-repository
> github: Add a template for the new pull requests

- libvirt/tests/cfg/virsh_cmd/volume/virsh_vol_create.cfg
- libvirt/tests/src/virsh_cmd/volume/virsh_vol_create.py
Add test cases for qcow2 volume with luks encryption
1. Create qcow2 volume with luks encryption
2. Start vm with this volume
> Add test cases for qcow2 volume with luks encryption

- libvirt/tests/cfg/virtual_disks/virtual_disks_multidisks.cfg
- libvirt/tests/src/virtual_disks/virtual_disks_multidisks.py
transient disk feature is brought back after libvirt version 6.8.0
but only file-based backend is supported
> Enable transient disk feature on file based backend

- libvirt/tests/src/virtual_network/iface_bridge.py
In 5ceba88, I have added 2 negative cases with 1 clean up step. But
the clean up step is not suitable for the existing cases, which will
cause no key error. Fix it by adding one condition.
> Fix the issue in the final clean up steps

- libvirt/tests/src/ppc_device.py
Check vm 'define' instead of 'start' after libvirt-7.0.0
> Update case of ppc panic device

- provider/v2v_vmcheck_helper.py
- v2v/tests/cfg/convert_vm_to_libvirt.cfg
- v2v/tests/cfg/convert_vm_to_ovirt.cfg
- v2v/tests/cfg/function_test_esx.cfg
- v2v/tests/src/convert_vm_to_ovirt.py
Because of bz1902635, the qxl checkpoint should be updated
for all windows guests.
> v2v: update qxl checkpoints for windows guests

- libvirt/tests/src/virsh_cmd/network/virsh_net_dhcp_leases.py
Add the libvirt version check for negative case at the beginning. If it is
on the unsupported version, skip the test.
> Skip the negative lease related case on unsupported version

- libvirt/tests/cfg/memory/memory_discard.cfg
1. aarch64 doesn't support host-model, set cpu mode host-passthrough for aarch64
2. Skip memory hotplug tests for aarch64
```
memory_discard.common.numa_cell.discard_yes
CmdError: Command '/bin/virsh start avocado-vt-vm1 ' failed.stdout: b'\n'stderr: b&quot;error: Failed to start domain 'avocado-vt-vm1'\nerror: unsupported configuration: CPU mode 'host-model' for aarch64 kvm domain on aarch64 host is not supported by hypervisor\n&quot;additional_info: None&#10;
```
```
JOB ID     : d71f18a7f9134aec98df21636c6b4f8ccd984b59
JOB LOG    : /root/avocado/job-results/job-2021-02-18T20.54-d71f18a/job.log
(1/6) type_specific.io-github-autotest-libvirt.memory_discard.common.numa_cell.discard_yes: PASS (37.01 s)
(2/6) …
```
> memory_discard: Adapt memory_discard test on aarch64

- libvirt/tests/cfg/incremental_backup/incremental_backup_event_monitor.cfg
- libvirt/tests/src/incremental_backup/incremental_backup_event_monitor.py
Since libvirt-7.0.0-1.el8 (RFE:bz1913315), libvirt supports to monitor
block-threshold event for pull-mode backup's scratch file/device. This
patch is to add related cases.
> Add cases for monitoring backup strach file block-threshold

- libvirt/tests/cfg/virsh_cmd/domain/virsh_schedinfo_qemu_posix.cfg
- libvirt/tests/src/virsh_cmd/domain/virsh_schedinfo_qemu_posix.py
The max value of cpu quota has changed to 17592186044415 since libvirt 6.0,
so update the script accordingly.
> Update max value of cpu quota

- libvirt/tests/cfg/cpu/max_vcpus.cfg
libvirt gets the maximum from the kernel, so the output of maxvcpu is
not consistent among multi-archs.
Skip maxvcpus tests on aarch64 since the default report_num is
incorrect for aarch64.
> max_vcpus: Skip virsh_maxvcpus on aarch64

- provider/v2v_vmcheck_helper.py
When virtio-win is installed, windows VM may reboot automatically
during driver checking. This cause an invalid checker session which
will not work for getting driver info in VM.
> v2v: fix not getting driver info problem when checking windows VM

- libvirt/tests/src/virtual_device/video_devices.py
```
JOB ID     : 7ad4be11d1911d0a65c9b6c2fe91adf89ec6bd19
JOB LOG    : /root/avocado/job-results/job-2021-02-22T03.26-7ad4be1/job.log
(1/1) type_specific.io-github-autotest-libvirt.virtual_devices.video_devices.positive_test.primary_video.virtio.no_secondary_video.model_test.with_packed_on: FAIL: Can not find the primary virtio video device in qemu cmd line. (10.49 s)
JOB TIME   : 11.19 s
```
aarch64 only supports virtio-gpu-pci
After this fix
```
JOB ID     : 99fda55010733c69b99af5d4b1fc001b063b53c7
JOB LOG    : /root/avocado/job-results/job-2021-02-22T03.41-99fda55/job.log
(1/1) type_specific.io-github-autotest-libvirt.virtual_devices.video_devices.positive_test.primary_video.virtio.no_secondary_video.model …
```
> video_devices: Fix no_secondary_video.model_test for aarch64

- libvirt/tests/src/virtual_disks/at_dt_iscsi_disk.py
scsi packed feature is supported after libvirt 6.3.0 afterwards
> Add libvirt version checking for scsi packed feature case

- libvirt/tests/src/virsh_cmd/domain/virsh_migrate_option_mix.py
If vm with same uuid exists on dest host, migration will fail. Previous
code only considered the situation when vm with same name exists on dest
host.
> migration: Cleanup vm on dest host before migration

- libvirt/tests/src/virtual_device/video_devices.py
aarch64 only supports virtio
```
JOB ID     : 6c2431b4d0842c3a42ca00e5b756cc29743e0eaa
JOB LOG    : /root/avocado/job-results/job-2021-02-23T03.51-6c2431b/job.log
(1/1) type_specific.io-github-autotest-libvirt.virtual_devices.video_devices.positive_test.primary_video.virtio.no_secondary_video.heads_test.default_heads: FAIL: The heads number of the primary virtio video device in not correct. (10.64 s)
JOB TIME   : 11.28 s
```
After this fix
```
JOB ID     : 4afe721a6cf31241ec6ed179d36f1e31998e348c
JOB LOG    : /root/avocado/job-results/job-2021-02-23T03.52-4afe721/job.log
(1/1) type_specific.io-github-autotest-libvirt.virtual_devices.video_devices.positive_test.primary_video.virtio.no_secondary_video.heads_tes …
```
> video_devices: Fix no_secondary_video.heads_test for aarch64

- libvirt/tests/cfg/cpu/vm_features.cfg
- libvirt/tests/cfg/virtual_device/input_devices.cfg
- libvirt/tests/cfg/virtual_device/sound_device.cfg
- libvirt/tests/cfg/virtual_device/watchdog.cfg
a) Skip kvm_poll_control on pseries/aarch64
b) Skip bus_type_ps2, model_i6300esb sound_model ac97 ich6 ich9 on aarch64
> Skip some pseries/aarch64 unsupported tests

- libvirt/tests/cfg/virsh_cmd/domain/virsh_attach_detach_disk.cfg
aarch64 doesn't support IDE, replace it with SCSI.
```
JOB ID     : 5c33be83c5e98d04551cfe30d87469b0f52d56c3
JOB LOG    : /root/avocado/job-results/job-2021-02-23T08.32-5c33be8/job.log
(1/1) type_specific.io-github-autotest-libvirt.virsh.attach_detach_disk.attach_disk.normal_test.cdrom_eject_control: ERROR: VM 'avocado-vt-vm1' failed to start: error: Failed to start domain 'avocado-vt-vm1'\nerror: unsupported configuration: IDE controllers are unsupported for this QEMU binary or machine type (62.32 s)
JOB TIME   : 62.98 s
```
```
JOB ID     : 0c8701136efd50390748b281337e9d1ee325bc83
JOB LOG    : /root/avocado/job-results/job-2021-02-23T08.36-0c87011/job.log …
```
> virsh_attach_detach_disk: Fix unsupported controllers for aarch64

- libvirt/tests/cfg/migration/migrate_over_unix.cfg
- libvirt/tests/src/migration/migrate_over_unix.py
1) Migrate vm over unix socket
2) Migrate vm over unix socket - libvirt tunnelled(--tunnelled)
3) Migrate vm over unix socket - enable multifd(--parallel)
4) Migrate vm with copy storage over unix socket - one disk
5) Migrate vm with copy storage over unix socket - multiple disks
6) Abort migration over unix socket and migrate again
7) Abort migration with copy storage over unix socket, and migrate again
8) Migrate vm with copy storage over unix socket - multiple disks
- enable multifd(--parallel)
depends on: 
https://github.com/avocado-framework/avocado-vt/pull/2891
https://github.com/avocado-framework/avocado-vt/pull/2892
https://github.com/avocado-framework/avocado-vt/pull/2894
https://github.com/avocado-framework/avocado-vt/pull/2915
Signed-off-by: Yingshun …
> Add some cases to check migration over unix socket

- libvirt/tests/cfg/virsh_cmd/domain/virsh_memtune.cfg
- libvirt/tests/src/virsh_cmd/domain/virsh_memtune.py
The virsh memtune set value deviates from the actual value, and the default acceptable minus is 8.
But real swap_hard_limit and cmdline setting value differ by 21, so normal_7 test failed.
```
hard_limit     : 1111104
soft_limit     : 222208
swap_hard_limit: 3333312
```
Call utils_memory.getpagesize to set acceptable_minus instead of hard code.
```
JOB ID     : 6f6078a6d5c5a82062d06b89adc92f579302667a
JOB LOG    : /root/avocado/job-results/job-2021-02-20T03.20-6f6078a/job.log
(1/1) type_specific.io-github-autotest-libvirt.virsh.memtune.positive_test.normal_7: PASS (41.00 s)
JOB TIME   : 41.68 s
```
> virsh_memtune: Call utils_memory.getpagesize to set acceptable_minus

- v2v/tests/src/function_test_xen.py
- v2v/tests/src/specific_kvm.py
- v2v/tests/src/v2v_options.py
When VM has cdrom disk, the xml may be as following:
<disk type='file' device='disk'>
<source file='[esx6.7-matrix] xxx/xxx-xxx.vmdk'/>
<target dev='sda' bus='scsi'/>
<address type='drive' controller='0' bus='0' target='0' unit='0'/>
</disk>
<disk type='file' device='cdrom'>
<target dev='sda' bus='sata'/>
<address type='drive' controller='0' bus='0' target='0' unit='0'/>
</disk>
Above xml may not work when calling get_disk_all function, this patch
fixes the problem by specifying the device value to only return desired
disks.
> v2v: fix incorrect disk count problem when vm has cdrom disk

- v2v/tests/cfg/convert_from_file.cfg
- v2v/tests/cfg/convert_vm_to_libvirt.cfg
- v2v/tests/cfg/convert_vm_to_ovirt.cfg
- v2v/tests/cfg/function_test_esx.cfg
As esx5.5 is not supported by v2v now, move source esxi5.5 from
v2v jobs and use the other vmware source to replace it.
e.g
> Remove source esx5.5 from v2v functional jobs

- libvirt/tests/cfg/virtual_device/sound_device.cfg
- libvirt/tests/cfg/virtual_device/watchdog.cfg
Some virtual devices are not supported by RHEL qemu-kvm but upstream
qemu-system-aarch64 (I checked on qemu-4.2.0-7.fc32) supports them.
So skip these cases on tp-libvirt upstream is incorrect, remove these
incorrect skip cases.
> Remove incorrect skip aarch64 cases

- libvirt/tests/cfg/virtual_network/iface_network.cfg
RHEL qemu-kvm doesn't support rtl8139, replace default iface_model rtl8139 with virtio on aarch64
```
> virtual_network.iface_network.net_portgroup.default_portgroup \
> virtual_network.iface_network.net_portgroup.specific_portgroup \
> virtual_network.iface_network.net_portgroup.overwriting_bandwidth
JOB ID     : 4f1223696f35056360b2ebab8d04d82d1dc73b6b
JOB LOG    : /root/avocado/job-results/job-2021-02-25T03.07-4f12236/job.log
(1/3) type_specific.io-github-autotest-libvirt.virtual_network.iface_network.net_portgroup.default_portgroup: FAIL: VM failed to start:\nVM 'avocado-vt-vm1' failed to start: error: Failed to start domain 'avocado-vt-vm1'\nerror: internal error: process exited while connecting to monitor: 2021-02-25T08:07:21.528305Z qemu-kvm: -device …
```
> virtual_network: Fix iface_network for aarch64

- v2v/tests/cfg/function_test_xen.cfg
The matching string in expected result should be updated in
case function_test_xen..unset.
> v2v: fix error comparing string in xen cfg file

- v2v/tests/src/function_test_xen.py
- v2v/tests/src/specific_kvm.py
The ',' should be '%' in test.error.
> v2v: fix incorrect parameter counts in test.error

- v2v/tests/src/function_test_esx.py
In rhel6, the service name must not include wildcard, such as
'service qemu-ga* status', it will not work.
> v2v: fix getting qemu-ga service failure in rhel6 guest

- v2v/tests/src/function_test_esx.py
Any check before the windows reboots may cause command execution
timeout. There are alreay session reconnections in windows service
checking and in windows drivers checking. Put the signature checking
after them may reduce the probability of the failure.
If the problem still happens, we should update the structure of the
signature checking function. Right now we don't have much resources
to do that.
> v2v: move windows signature checking after common point checkpoints

- libvirt/tests/cfg/migration/migrate_bandwidth.cfg
- libvirt/tests/src/migration/migrate_bandwidth.py
To perform some operations during migration, need to make it slow,
so update to load stress in VM.
depends on https://github.com/avocado-framework/avocado-vt/pull/2918
> migrate_bandwidth: Run the stress tool to slow down migration process

- libvirt/tests/src/virtual_disks/virtual_disks_multidisks.py
On libvirt 6.0.0, VM with this feature enablement can not be started due to not supported feature
> Fix transient feature failure on libvirt 6.0.0

- libvirt/tests/cfg/virsh_cmd/network/virsh_net_list.cfg
- libvirt/tests/src/virsh_cmd/network/virsh_net_list.py
- RHEL7-86681 - [virsh cmd] net-list by different options
> Add cases of virsh net-list

- libvirt/tests/cfg/virtio_transitional/virtio_transitional_blk.cfg
- libvirt/tests/cfg/virtio_transitional/virtio_transitional_blk_negative.cfg
- libvirt/tests/cfg/virtio_transitional/virtio_transitional_mem_balloon.cfg
- libvirt/tests/cfg/virtio_transitional/virtio_transitional_nic.cfg
- libvirt/tests/cfg/virtio_transitional/virtio_transitional_rng.cfg
- libvirt/tests/cfg/virtio_transitional/virtio_transitional_serial.cfg
- libvirt/tests/cfg/virtio_transitional/virtio_transitional_vsock.cfg
On s390x all disks (and more generally most devices) are
attached not as PCI but as CCW. Virtio (non-)transitional is PCI-only.
Therefore, filter out those test cases for s390x.
> [virtio-transitional][s390x] add no filter on s390x

- libvirt/tests/cfg/conf_file/qemu_conf/auto_dump.cfg
qemu aarch64 doesn't support ISA panic device
E.g.
```
JOB ID     : e330aba6f2dc803a28660b5e092176910e22909b
JOB LOG    : /root/avocado/job-results/job-2021-03-01T03.09-e330aba/job.log
(1/1) type_specific.io-github-autotest-libvirt.conf_file.qemu_conf.auto_dump.isa_model.model_only.default_bypass_cache: ERROR: Failed to define avocado-vt-vm1 for reason:\nerror: Failed to define domain from /tmp/xml_utils_temp_4bij0p3l.xml\nerror: unsupported configuration: the QEMU binary does not support the ISA panic device\n (8.92 s)
JOB TIME   : 9.57 s
```
> auto_dump: Skip ISA model test on aarch64

- libvirt/tests/cfg/virsh_cmd/domain/virsh_event.cfg
a) Skip crash_panic test. qemu-kvm aarch64 doesn't support ISA panic device
b) Set device_target_bus scsi for aarch64
```
JOB ID     : deb3ef9dd525651968f9f9623a9dff2f49970847
JOB LOG    : /root/avocado/job-results/job-2021-03-01T06.46-deb3ef9/job.log
(1/1) type_specific.io-github-autotest-libvirt.virsh.event.positive_test.virsh_event.test_events.tray-change_event.no_timeout.loop: ERROR: VM 'avocado-vt-vm1' failed to start: error: Failed to start domain 'avocado-vt-vm1'\nerror: unsupported configuration: IDE controllers are unsupported for this QEMU binary or machine type (41.47 s)
JOB TIME   : 42.12 s
```
```
JOB ID     : 4c424545b0751b838d49f1bd708bac7e96f88eac
JOB LOG    : …
```
> virsh_event: Multiple fixup for aarch64

- libvirt/tests/cfg/controller/controller_functional.cfg
Multifunction is PCI related. On s390x SCSI works over channel system
that doesn't have this concept. Filter those test cases out.
> controller_functional: remove multifunction test case for s390x

- libvirt/tests/cfg/remote_access/remote_with_unix.cfg
The guest name returned by virsh cmds has been added with quote marks
now. Need to fix it to avoid regex failure.
> remote_with_unix: Fix the regex issue of unix connection test
