- libvirt/tests/cfg/virsh_cmd/domain/virsh_attach_passthrough_no_bus.cfg
- libvirt/tests/src/virsh_cmd/domain/virsh_attach_passthrough_no_bus.py
This commit adds new test case which performs attach-device operation with a generic
passthrough device defined without a definition of a bus type. This bus type should be
assigned to virtio by deafult and this is also verified.
> Add new test case for passthrough device hotplug without bus defined

- libvirt/tests/cfg/migration/migrate_storage.cfg
- libvirt/tests/src/migration/migrate_storage.py
This PR adds below case:
RHEL-196406 - Migrate vm with copy storage - Native TLS(--tls)
- inconsistent CN and server hostname
depends on: https://github.com/avocado-framework/avocado-vt/pull/2941
> migration: Add a tls related case

- libvirt/tests/cfg/cpu/max_vcpus.cfg
- libvirt/tests/src/cpu/max_vcpus.py
This PR is to add The maxCpus value of pc-q35-rhel8.4.0.
> max_vcpus: Update q35_max_vcpus_num in virsh_capa

- libvirt/tests/cfg/controller/controller_functional.cfg
- libvirt/tests/src/controller/controller_functional.py
This is to fix a vm define error like below. This error happened due
to a new libvirt parsing behavior in 7.0.0-x. But the fix is compatible
to old libvirt versions.
```
XML error: The PCI controller with index='0' must be model='pcie-root'
for this machine type, but model='pci-bridge' was found instead
```
> controller_functional: fix vm define error

- libvirt/tests/cfg/cpu/max_vcpus.cfg
The max vcpu was changed, so the guest vcpu setting should be
updated.
> max_vcpus: Fix an issue in negative_test.ioapic_iommu

- libvirt/tests/cfg/virsh_cmd/domain/virsh_schedinfo_qemu_posix.cfg
- libvirt/tests/src/virsh_cmd/domain/virsh_schedinfo_qemu_posix.py
This is to verify 'virsh schedinfo vm <options>' using below options and different values and
compare to cgroup files.
- vcpu_period/vcpu_quota
- emulator_period/emulator_quota
- global_period/global_quota
- iothread_period/iothread_quota
Case ID:  RHEL-114504 RHEL-115015
And this patch also removes some unnecessary test cases after confirming with feature owner,
such as
- cpu.share will not accept 0 and negative value any more
- --current cases
- domid cases
> Add cases for schedinfo

- v2v/tests/cfg/function_test_esx.cfg
Add a new case about vmware vmx file without fileName setting.
See: bz#1815269
> v2v: add a new case about vmx file without fileName

- v2v/tests/cfg/convert_from_file.cfg
- v2v/tests/src/convert_from_file.py
Add a new checkpoint for '-i vmx -it ssh', verify '-T' option is enabled.
> v2v: add a new checkpoint for vmx -it ssh (-T)

- libvirt/tests/src/virsh_cmd/domain/virsh_guestinfo.py
When the test failed during the execution of test, some variables might remain
unreferenced and therefore this fix is adding their initialization prior the
try, except finally statement to make sure they are existing during cleanup.
> virsh_guestinfo: Test cleanup fix

- libvirt/tests/cfg/remote_access/remote_with_unix.cfg
The guest name returned by virsh cmds has been added with quote marks
now. Need to fix it to avoid regex failure.
> remote_with_unix: Complete fix the regex issue of unix connection test

- libvirt/tests/cfg/migration/migrate_mem.cfg
Since the qemu command changed from 8.2 to 8.3, the different comparation strings
is needed for 8.2 as the source of the migration.
> To support cross migration from 8.2 to 8.3, the qemu cmdline has some change

- libvirt/tests/src/virtual_disks/virtual_disks_scsi3_persistent_reservation.py
Replace old scsi controller with virtio-scsi controller to support
hotplug/unplug.
> Update controller of ppc vms to support hotplug/unplug

- libvirt/tests/src/virtual_disks/virtual_disks_multidisks.py
keep the origin loader/loader_readonly/loader_type if vmx has acpi
feature
Signed-off-by: Li Zhijian <lizhijian@fujitsu.com>
e.g
> virtual_disks_multidisks: Fix: unsupported configuration: ACPI requires UEFI on this architecture

- libvirt/tests/src/virtual_network/mtu.py
Fix the following issue
```
2021-03-23 22:35:35,294 stacktrace       L0045 ERROR| Traceback (most recent call last):
2021-03-23 22:35:35,295 stacktrace       L0045 ERROR|   File "/var/lib/avocado/data/avocado-vt/virttest/test-providers.d/downloads/io-github-autotest-libvirt/libvirt/tests/src/virtual_networ
k/mtu.py", line 179, in run
2021-03-23 22:35:35,295 stacktrace       L0045 ERROR|     utils_package.package_install(new_pkg)
2021-03-23 22:35:35,295 stacktrace       L0045 ERROR| UnboundLocalError: local variable 'new_pkg' referenced before assignment
```
Before this fix
```
JOB ID     : 53814485585d082c888b7a86e75e478e50e912e9
JOB LOG    : /root/avocado/job-results/job-2021-03-23T23.55-5381448/job.log
(1/1) …
```
> virtual_network: fix mtu UnboundLocalError

- libvirt/tests/cfg/virtual_disks/virtual_disks_multidisks.cfg
disk_virtio_pci_bridge_controller is too old and has already been skipped on s390 and q35.
Skip it on aarch64 too.
> virtual_disks_multidisks: skip disk_virtio_pci_bridge_controller test on aarch64

- libvirt/tests/cfg/virtual_disks/virtual_disks_multidisks.cfg
Signed-off-by: Li Zhijian <lizhijian@fujitsu.com>
e.g
> virtual_disks_multidisks: expect to attach successfully on aarch64

- libvirt/tests/cfg/virsh_cmd/snapshot/virsh_snapshot_disk.cfg
- libvirt/tests/src/virsh_cmd/snapshot/virsh_snapshot_disk.py
RHEL-196449:Snapshot and backing file share the same cluster size
> Add case to validate disk cluster size set

- libvirt/tests/src/virtual_network/iface_rename.py
Add the bug fixed version into the error message, it can reduce the
debugging time.
> Add the bug fixed version into the error message

- libvirt/tests/cfg/bios/virsh_boot.cfg
virsh_boot: Update usb controller and loader path to the default
> virsh_boot: Update usb controller and loader path to the default

- libvirt/tests/src/virsh_cmd/domain/virsh_sendkey.py
> Ignore case distinctions in 'grep' for expected pattern

- libvirt/tests/cfg/virsh_cmd/domain/virsh_detach_serial_device_alias.cfg
upstream qemu doesn't support isa-serial
```
\# /usr/libexec/qemu-system-aarch64 --version
QEMU emulator version 5.2.90 (v6.0.0-rc0-16-gec2e6e016d)
Copyright (c) 2003-2021 Fabrice Bellard and the QEMU Project developers
\# /usr/libexec/qemu-system-aarch64 --machine virt --device help | grep -serial
name "pci-serial", bus PCI
name "pci-serial-2x", bus PCI
name "pci-serial-4x", bus PCI
name "usb-serial", bus usb-bus
name "virtconsole", bus virtio-serial-bus
name "virtio-serial-device", bus virtio-bus
name "virtio-serial-pci", bus PCI, alias "virtio-serial"
name "virtio-serial-pci-non-transitional", bus PCI
name "virtio-serial-pci-transitional", bus PCI
name "virtserialport", bus virtio-serial-bus
```
> virsh_detach_serial_device_alias: skip isa-serial for aarch64

- libvirt/tests/src/backingchain/blockcopy.py
Fix undefine error, vm.undefine will  add undefine "--nvram" option
automatically for aarch64 machine.
Before
```
JOB ID     : 7f02aa89fb492ebafc1f18c9988148d26a643c7b
JOB LOG    : /root/avocado/job-results/job-2021-04-01T22.46-7f02aa8/job.log
(1/1) type_specific.io-github-autotest-libvirt.backingchain.blockcopy.positive_test.reuse_external: ERROR: Command '/usr/bin/virsh undefine avocado-vt-vm1' failed.\nstdout: b'\n'\nstderr: b"error: Failed to undefine domain 'avocado-vt-vm1'\nerror: Requested operation is not valid: cannot undefine domain with nvram\n"\nadditional_info: None (9.47 s)
JOB TIME   : 10.19 s
```
After
```
JOB ID     : …
```
> blockcopy: replace virsh.undefine with vm.undefine

- libvirt/tests/cfg/virsh_cmd/domain/virsh_detach_device_alias.cfg
Sometimes pci_id may be empty then create_hostdev_xml failed on below
issue.
```
IndexError: list index out of range
```
Add a check for pci_id/device to avoid this issue.
Since create_hostdev_xml depends on pci_id/device, cancel test if pci_id/device
is empty.
Before
```
JOB ID     : 7fe65df58bc794ff98c846141e2f0dfa1f7a570f
JOB LOG    : /root/avocado/job-results/job-2021-03-31T03.44-7fe65df/job.log
(1/1) type_specific.io-github-autotest-libvirt.virsh.detach_device_alias.live.hostdev: ERROR: list index out of range (44.11 s)
JOB TIME   : 44.81 s
```
After
```
JOB ID     : d61e0a15185ebbcc1ff0189392b4f961b4062891
JOB LOG    : …
```
> virsh_detach_device_alias: Fix hostdev detach device by alias on aarch64

- libvirt/tests/src/svirt/libvirt_ap_passthrough.py
Depends on https://github.com/avocado-framework/avocado-vt/pull/2925
The test case loads the vfio_ap module. This would block
reloading the kvm module later.
Unload the vfio_ap module at teardown.
Tested via:
1. lsmod|grep vfio_ap >> empty
2. avocado run --vt-type libvirt --vt-machine-type s390-virtio libvirt_ap_passthrough.hotplug --vt-connect-uri qemu:///system
3. lsmod|grep vfio_ap >> empty
> [libvirt_ap_passthrough] Unload module at teardown

- libvirt/tests/cfg/virsh_cmd/domain/virsh_attach_device.cfg
The configuration option `remove_all_chardev` has been used to remove
all chardevs from vm before running test. The need to remove all chardevs
before running test however, is not arch-dependent but depends on the
domain definition before starting the test. Let's move this option to global
scope to allow for removal for all test cases. The default value is `no`
as before (s. corresponding script `virsh_attach_device.py`)
> [virsh.attach_device] Allow for chardev removal globally

- libvirt/tests/cfg/migration/migrate_vm.cfg
- libvirt/tests/src/migration/migrate_vm.py
Some hosts might load kvm without hugepage support, e.g. on s390x
because hugepage support is currently incompatible with nested support.
Add logic to test cases `with_hugepages` so that kvm is reloaded with
hugepage support on source and/or target host, if configured.
Default is "no", that is the code will work as before.
> [migrate_vm] enable kvm hpage via configuration

- libvirt/tests/cfg/migration/migrate_network.cfg
- libvirt/tests/cfg/migration/migrate_options_shared.cfg
- libvirt/tests/src/migration/migrate_ceph.py
- libvirt/tests/src/migration/migrate_gluster.py
- libvirt/tests/src/migration/migrate_mem.py
- libvirt/tests/src/migration/migrate_network.py
- libvirt/tests/src/migration/migrate_options_shared.py
- libvirt/tests/src/migration/migrate_vm.py
- libvirt/tests/src/migration/migrate_with_legacy_guest.py
One of the migration jobs needs to enable VM migration back for all
cases, so update the parameter to migrate_vm_back that already
exists in base.cfg.
> migration: Use a parameter in base.cfg to enable VM migration back

- libvirt/tests/cfg/virtual_disks/virtual_disks_multidisks.cfg
> Fix usb disk error_test4 failure by adding define_error = yes

- libvirt/tests/cfg/svirt/dac_nfs_save_restore.cfg
- libvirt/tests/cfg/svirt/dac_per_disk_hotplug.cfg
- libvirt/tests/cfg/svirt/dac_start_destroy.cfg
- libvirt/tests/cfg/svirt/svirt_start_destroy.cfg
aarch64 guest use firmware efi which requires nvram file.
E.g
```
<os>
<type arch='aarch64' machine='virt-rhel8.4.0'>hvm</type>
<loader readonly='yes' type='pflash'>/usr/share/edk2/aarch64/QEMU_EFI-silent-pflash.raw</loader>
<nvram>/var/lib/libvirt/qemu/nvram/avocado-vt-vm1_VARS.fd</nvram>
<boot dev='hd'/>
</os>
```
Some tests set user/group as qemu and disable dynamic_ownership in qemu.conf.
There is a permission conflict when we disable dynamic_ownership and set qemu
user/group as qemu:
Run qemu process as user qemu but nvram belongs to root.
So skip these tests for aarch64
Signed-off-by: Liu <liuyd.fnst@fujitsu.com>
> svirt: skip some tests for aarch64

- libvirt/tests/cfg/migration/migrate_storage.cfg
- libvirt/tests/src/migration/migrate_storage.py
This PR adds 2 migration cases:
1. RHEL-196401: Migrate vm with copy storage over TCP transport - Specified IP
2. RHEL-196402: Migrate vm with copy storage over TCP transport - Specified IP+Port
3. RHEL-196392: [--disks-uri] Migrate vm with copy storage over  TCP transport - Specified IP+Port
depends on:
https://github.com/avocado-framework/avocado-vt/pull/2958
https://github.com/avocado-framework/avocado-vt/pull/2957
```
WARNING:root:No python imaging library installed. PPM image conversion to JPEG disabled. In order to enable it, please install python-imaging or the equivalent …
```
> migration: Add 3 migration cases to check disks port option

- libvirt/tests/src/migration/migrate_network.py
The package 'dhcp-client' is not installed by default on the
guest. This makes dhclient commands fail.
_Before fix_:
```
JOB LOG    : /root/avocado/job-results/job-2021-04-06T23.27-0df524a/job.log
(1/1) type_specific.io-github-autotest-libvirt.virsh.migrate_network.direct.macvtap_exists_dest.without_postcopy: ERROR: Shell command failed: 'dhclient -r; dhclient'    (status: 127,    output: '-bash: dhclient: command not found\n-bash: dhclient: command not found\n') (162.03 s)
JOB TIME   : 162.64 s
```
_After fix:_
```
JOB ID     : 6bfa1159d19239ca5322df6422b906e502456717
JOB LOG    : /root/avocado/job-results/job-2021-04-06T23.51-6bfa115/job.log …
```
> migration: Fix dhclient command not found problem

- libvirt/tests/cfg/cpu/vcpu_cache.cfg
The output of 'lscpu' has been updated. It contains a space between
size and the unit than before, and the unit may be 'MiB'.
**Before fix:**
` (1/1) type_specific.io-github-autotest-libvirt.vcpu_cache.positive_test.L3.host_model: FAIL: The string 'L3 cache:\s+\d+K' is not included in L1d cache:                       64 KiB\nL1i cache:                       64 KiB\nL2 cache:                        8 MiB\nL3 cache:                        32 MiB (26.11 s)`
**After fix:**
`rhel9:` 2 failed cases are caused by BZ 1925384.
```
(01/10) type_specific.io-github-autotest-libvirt.vcpu_cache.positive_test.L3.no_cpu_mode: ERROR: No ipv4 DHCP lease for MAC 52:54:00:6a:1f:84 (246.62 s)
(02/10) type_specific.io-github-autotest-libvirt.vcpu_cache.positive_tes …
```
> vcpu_cache: Fix a regex problem

- libvirt/tests/src/libvirt_mem.py
- libvirt/tests/src/numa/guest_numa.py
without it on new version test will cause kernel panic
```
JOB ID     : f4b88785fb26f951aa18d764d3838bf51a5b94e9
JOB LOG    : /root/avocado/job-results/job-2021-04-01T08.37-f4b8878/job.log
(1/1) type_specific.io-github-autotest-libvirt.guest_numa.possitive_test.hugepage.per_node.2M.topology.numatune_memnode.m_strict.numatune_mem: PASS (52.13 s)
JOB TIME   : 52.87 s
JOB ID     : 24339f1437c9cd6ee1887387210f8cf14c5aa4d6
JOB LOG    : /root/avocado/job-results/job-2021-04-01T08.38-24339f1/job.log
(1/1) type_specific.io-github-autotest-libvirt.libvirt_mem.positive_test.with_source: PASS (66.77 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 …
```
> update cpu xml with host-model

- v2v/tests/cfg/function_test_esx.cfg
- v2v/tests/src/function_test_esx.py
Some guests like rhel5 cannot be logged in on rhel9 by default
because of crypto policies problem.
In order to fix the problem, a switch variant should be added
to indicate if legacy crypto policies should be enabled.
> v2v: add a switch for legacy crypto policies

- v2v/tests/src/function_test_esx.py
rhev_apt.exe is removed from v2v on rhel9, so the service don't need
to be checked any more.
> v2v: remove rhev_apt service check on rhel9

- libvirt/tests/cfg/guest_kernel_debugging/nmi_test.cfg
AArch64 (aka arm64 in the Linux tree) does not provide architected NMIs
```
\# avocado run --vt-type libvirt --vt-arch aarch64 --vt-machine-type arm64-mmio guest_kernel_debugging.nmi_test.positive_testing.send_nmi
JOB ID     : 0169905ac3599e0f59a031730f04075c4c47475f
JOB LOG    : /root/avocado/job-results/job-2021-04-13T22.12-0169905/job.log
(1/1) type_specific.io-github-autotest-libvirt.guest_kernel_debugging.nmi_test.positive_testing.send_nmi: ERROR: Can not run 'grep NMI /proc/interrupts' in guest:  (133.79 s)
JOB TIME   : 134.53 s
```
> nmi_test: skip nmi test on aarch64

- libvirt/tests/cfg/virsh_cmd/domain/virsh_blockjob.cfg
- libvirt/tests/src/virsh_cmd/domain/virsh_blockjob.py
1. The tests start a blockjob (blockcopy) and then execute
several blockjob commands often expecting the blockjob to be
running.
2. The test waits 3 seconds after starting the blockjob.
As a result, if the blockjob ends before 3 seconds have passed
there will be no blockjob and the domain will have been stopped.
Therefore, the test will fail.
Introduce the bandwidth parameter value. It will cause the blockjob
to take more time. Value 300 was chosen to not slow down the .with_pivot
subcase too much as it waits for the job to finish.
Test results:
```bash
JOB ID     : 86c1c6cb8a041e87e33ead58f6be461c3694b9f4
JOB LOG    : /root/avocado/job-results/job-2021-04-14T12.36-86c1c6c/job.log
(01/14) …
```
> [virsh_blockjob] Introduce configuration to slow down blockjob

- libvirt/tests/cfg/migration/migrate_options_shared.cfg
RHEL-201634: Do VM migration for a paused VM - p2p migration
```
JOB ID     : fb2a4cd932653d09d1365c81127c2d28409cf177
JOB LOG    : /root/avocado/job-results/job-2021-04-02T02.22-fb2a4cd/job.log
(1/1) type_specific.io-github-autotest-libvirt.virsh.migrate_options_shared.positive_test.p2p_migration.pause_vm_before_migration.without_postcopy: PASS (155.22 s)
JOB TIME   : 158.40 s
```
> migraion: Add a case to check p2p precopy migration of the paused VM

- provider/v2v_vmcheck_helper.py
on rhel8:
When '-o rhv' is used, 'i440fx+bios' will be set in rhv server >= 4.4.
When '-o rhev_upload' is used, 'q35+bios' will be set in rhv server >= 4.4.
When rhv server < 4.4, 'i440fx+bios' will be set.
on rhel9:
'q35+bios' will set in rhv server.
> v2v: only update expected biso type when '-o rhv_upload' is used.

- libvirt/tests/cfg/migration/migrate_over_unix.cfg
- libvirt/tests/cfg/migration/migrate_storage.cfg
- libvirt/tests/cfg/virsh_cmd/domain/virsh_migrate_copy_storage.cfg
- libvirt/tests/src/migration/migrate_bandwidth.py
- libvirt/tests/src/migration/migrate_gluster.py
- libvirt/tests/src/migration/migrate_network.py
- libvirt/tests/src/migration/migrate_options_shared.py
- libvirt/tests/src/migration/migrate_over_unix.py
- libvirt/tests/src/migration/migrate_storage.py
- libvirt/tests/src/migration/migrate_with_legacy_guest.py
- libvirt/tests/src/migration/sriov_migrate.py
- libvirt/tests/src/virsh_cmd/domain/virsh_migrate_copy_storage.py
- libvirt/tests/src/virsh_cmd/domain/virsh_migrate_multi_vms.py
- libvirt/tests/src/virsh_cmd/domain/virsh_migrate_option_mix.py
1. MigrationTest.do_migration changes to check result
2. Update vm cleaning part
3. Fix typo
https://github.com/avocado-framework/avocado-vt/pull/2979
one case failed due to BZ 1806856, and one case was cancelled because it's unsupported.
```
(01/13) type_specific.io-github-autotest-libvirt.virsh.migrate_option_mix.persistent.no_persistent_xml.no_xml.no_dname.undefinesource.src_vm_running.src_vm_persistent.graphic_passwd.tunnelled.precopy.live: PASS (375.92 s)
(02/13) type_specific.io-github-autotest-libvirt.virsh.migrate_set_get_speed.normal_test.zero: PASS (47.37 s)
(03/13) type_specific.io-github-autotest-libvirt.virsh.migrate_set_get_speed.error_test.uint64_max: PASS (43.80 s)
(04/13) …
```
> migraion: refactor code to adopt MigrationTest/libvirt_migraion

- libvirt/tests/cfg/remote_access/remote_with_ssh.cfg
- libvirt/tests/src/remote_access/remote_access.py
New case added for invalid transportation parameter.
Case_description:
Connect to the hypervisor over an invalid transportations, error tip should be properly given.
Introduced in:
https://libvirt.org/uri.html
https://libvirt.org/remote.html
Case_ID: 
RHEL-174720
test_result: 
<pre>avocado run --vt-type libvirt virsh.remote_with_ssh.negative_testing.invalid_transport
<font color="#2A7BDE">JOB ID     : …
> remote_access:New case added for invalid transportation parameter.

- libvirt/tests/cfg/virsh_cmd/domain/virsh_schedinfo_qemu_posix.cfg
- libvirt/tests/src/virsh_cmd/domain/virsh_schedinfo_qemu_posix.py
Cgroup v2 is enabled by default on rhel9, so update cases to
support cgroup v1 and v2.
https://github.com/avocado-framework/avocado-vt/pull/3004
https://github.com/avocado-framework/avocado-vt/pull/2924
**test results:**
_rhel 9:_
```
(001/110) type_specific.io-github-autotest-libvirt.virsh.schedinfo_qemu_posix.normal_test.show_schedinfo.for_show.set_by_self.valid_domname.running_guest: PASS (5.48 s)
(002/110) type_specific.io-github-autotest-libvirt.virsh.schedinfo_qemu_posix.normal_test.show_schedinfo.for_show.set_by_self.valid_domuuid.running_guest: PASS (5.41 s)
(003/110) type_specific.io-github-autotest-libvirt.virsh.schedinfo_qemu_posix.normal_test.set_multi_params.for_multi.set_by_self.valid_domname.running_guest: PASS …
```
> Cgroup V2: Update virsh_schedinfo cases

- libvirt/tests/cfg/virsh_cmd/domain/virsh_attach_device.cfg
- libvirt/tests/src/virsh_cmd/domain/virsh_attach_device.py
1. Using `SerialPipe` will set first chardev to a non-pty.
2. Per default 'virsh console' will select the first chardev and
the system can't be logged into.
Therefore, login will fail if using `SerialPipe`.
Use simple `SerialPty` for `single_serial` to assure test can log in.
`SerialPipe` is still covered in suite `single_serial_lm`.
This change only affects s390x, ie. by configuration only
subcases `serial_s390x.single_serial`. However, the new `SerialPty` can
be used for any platform.
> [virsh_attach_device] fix single_serial on s390x

- libvirt/tests/src/ppc_device.py
- libvirt/tests/src/sriov/sriov.py
- libvirt/tests/src/vfio.py
- libvirt/tests/src/virsh_cmd/domain/virsh_detach_device_alias.py
Adjust the invoke method for the utility function in avocado-vt 2988.
> virsh_detach_device_alias: Fix tmp file removed

- libvirt/tests/cfg/virsh_cmd/domain/virsh_emulatorpin.cfg
- libvirt/tests/src/virsh_cmd/domain/virsh_emulatorpin.py
Test case: RHEL-114425
Test scenario:
- Set emulatorpin to subset of host cpus
- Check the emulatorpin result and cgroup result
- Set emulatorpin to all of host cpus
- Check result again
Test case: RHEL7-63519
Test scenario:
- Set emulatorpin to non-exist host cpu via virsh command
- Set emulatorpin to non-exist host cpu via vm xml
> Add case to pin all cpu

- libvirt/tests/src/virsh_cmd/domain/virsh_blockcopy.py
To avoid failures caused by tmpfs
> blockcopy: Replace tmp_dir with data_dir

- libvirt/tests/cfg/virsh_cmd/domain/virsh_schedinfo_qemu_posix.cfg
- libvirt/tests/src/virsh_cmd/domain/virsh_schedinfo_qemu_posix.py
Test Case: RHEL-198260
- Set invalid value and check error message is correct
- Other scenarios are tested in tp-libvirt 3360
> Add case for global quota

- libvirt/tests/cfg/virtual_disks/virtual_disks_metadatacache.cfg
- libvirt/tests/src/virtual_disks/virtual_disks_metadatacache.py
RHEL-197470 and RHEL-197469 cover blockcopy,snapshot,and blockcommit operations on disk with metadata_cache attribute
> Add cases to cover disk metadata_cache feature

- libvirt/tests/cfg/remote_access/remote_tls_priority.cfg
- libvirt/tests/src/remote_access/remote_tls_priority.py
New test has been added to test the TLS priorities between the remote server and
local client.
Test Case Info:
- 1.Test the tls_priority config in the libvirt.conf;
2.Test the tls_priority override in the URI;
- Introduced in:
https://libvirt.org/uri.html
https://libvirt.org/remote.html
- case_id:
RHEL7-79998
- Test Result:
<pre>avocado run --vt-type libvirt virsh.remote_tls_priority
WARNING:root:No python imaging library installed. PPM image conversion to JPEG disabled. In order to enable it, please install python-imaging or the equivalent for your …
> remote_access: Add test case for TLS priorities

- libvirt/tests/src/controller/controller_functional.py
'host-model' is recommended to use in <cpu> configuration in vm xml.
Otherwise, vm might fail to start under some circumstances. So this
pr is to add it to the guest xml.
> controller_functional: fix host-model missing

- libvirt/tests/cfg/cpu/vcpu_affinity.cfg
- libvirt/tests/src/cpu/vcpu_affinity.py
After discussion with function owner, there is no need to write
the machine_cpuset_path in the "finally" block.
_Before fix:_
```
(1/1) type_specific.io-github-autotest-libvirt.vcpu_affinity.positive_test.vcpu: ERROR: Command 'echo '0-31' > /sys/fs/cgroup/cpuset/machine.slice/cpuset.cpus' failed.\nstdout: b''\nstderr: b'/bin/sh: line 1: /sys/fs/cgroup/cpuset/machine.slice/cpuset.cpus: No such file or directory\n'\nadditional_info: None (31.57 s)
```
_After fix:_
```
WARNING:root:No python imaging library installed. Screendump and Windows guest BSOD detection are disabled. In order to enable it, please install python-imaging or the equivalent for …
```
> Cgroup V2: Update vcpu_affinity cases

- libvirt/tests/cfg/virtual_network/iface_options.cfg
- libvirt/tests/src/virtual_network/iface_options.py
depends on https://github.com/avocado-framework/avocado-vt/pull/3006 
case ID: RHEL-197483 RHEL-197487
```
JOB ID     : 7b0f45e843af1fc738341ee2b250ed4399b8724f
JOB LOG    : /root/avocado/job-results/job-2021-04-14T08.08-7b0f45e/job.log
(1/1) type_specific.io-github-autotest-libvirt.virtual_network.iface_options.iface_type.type_vhostuser.vhost_client: PASS (46.71 s)
JOB TIME   : 48.35 s
```	
And also test 2 other cases to make sure no effect to others
```
JOB ID     : b099acb801d42e87303c0338ef464e906606f027
JOB LOG    : /root/avocado/job-results/job-2021-04-15T07.14-b099acb/job.log
(1/1) type_specific.io-github-autotest-libvirt.virtual_network.iface_options.ifac …
```
> Add 2 new cases for "get vhost-user VNIC stats by domstats" and "vhostuser with dpdk"

- libvirt/tests/cfg/virsh_cmd/domain/virsh_attach_detach_disk.cfg
- libvirt/tests/src/virsh_cmd/domain/virsh_attach_detach_disk.py
Before
```
> virsh.attach_detach_disk.attach_disk.normal_test.twice_diff_target \
> virsh.attach_detach_disk.attach_disk.normal_test.twice_diff_target_with_shareable
JOB ID     : bb3e8143c3ccb32d139bc383fb9b6ff3e73525f4
JOB LOG    : /root/avocado/job-results/job-2021-03-29T04.54-bb3e814/job.log
(1/2) type_specific.io-github-autotest-libvirt.virsh.attach_detach_disk.attach_disk.normal_test.twice_diff_target: FAIL: virsh attach-disk failed. (65.58 s)
(2/2) type_specific.io-github-autotest-libvirt.virsh.attach_detach_disk.attach_disk.normal_test.twice_diff_target_with_shareable: FAIL: virsh attach-disk failed. (64.74 s)
RESULTS    : PASS 0 | ERROR 0 | FAIL 2 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 131.08 s
```
After this fix …
> virsh_attach_detach_disk: Fix "No more PCI slots" error

- libvirt/tests/cfg/migration/migrate_with_virtual_devices.cfg
- libvirt/tests/src/migration/migrate_with_virtual_devices.py
This commit includes 2 fixes:
1. Remove native_tls from test matrix
2. Add step to remove rng device from vm xml before start vm in case
vm already has a rng device.
> migration: fixup for migration with rng devices

- libvirt/tests/cfg/backingchain/blockcopy.cfg
- libvirt/tests/src/backingchain/blockcopy.py
Case description: Use a qcow2 image with customized cluster size
in vm, and blockcopy it to a target path. Check the target image
has same cluster size as source image.
Case ID: RHEL-196451
Test result: PASSED with libvirt-7.0.0-4.el9.x86_64
> blockcopy: add case to check image cluster size after blockcopy

- libvirt/tests/src/virtual_network/iface_bridge.py
There is a preparation step to backup the iface-* files, but it should
check the existence of the file first.
> Fix the ifcfg-* not exists issue

- libvirt/tests/cfg/guest_resource_control/control_cgroup.cfg
- libvirt/tests/src/guest_resource_control/control_cgroup.py
- Description:
We need to recheck cgroup values When reload daemons after setting
vm's cgroup values, issues happened before.
- Case ID:
RHEL-202437
- Test result (rhel9):
PASSED with memtune&blkiotune cases
FAILED with schedinfo cases, expected due to bz1798463 not fixed
on rhel9
> guest_resource_control: Do extra operations when set cgroup values

- libvirt/tests/src/virsh_cmd/domain/virsh_emulatorpin.py
Cgroup v2 is enabled by default on rhel9, so update cases to
support cgroup v1 and v2.
_cgroup v1:_
` (1/1) type_specific.io-github-autotest-libvirt.virsh.emulatorpin.positive_testing.set_emulatorpin_parameter.running_guest.cpulist.emulatorpin_options.live.comma_list: PASS (9.79 s)`
_cgroup v2:_
```
JOB LOG    : /root/avocado/job-results/job-2021-04-24T23.23-16a2c7e/job.log
(1/7) type_specific.io-github-autotest-libvirt.virsh.emulatorpin.positive_testing.get_emulatorpin_parameter.running_guest.emulatorpin_options.none: PASS (7.40 s)
(2/7) type_specific.io-github-autotest-libvirt.virsh.emulatorpin.positive_testing.get_emulatorpin_parameter.running_guest.emulatorpin_options.live: PASS (7.48 s)
(3/7) …
```
> Cgroup V2: Update virsh_emulatorpin cases

- v2v/tests/src/function_test_xen.py
By default, ssh connection will fail to rhel5 host, see
man virt-v2v-input-xen(1). so all execution must be ran in
legacy mode.
> v2v: update the code order of delete ssh_banner from xen host

- libvirt/tests/cfg/remote_access/remote_with_unix.cfg
Regular expression in config file was wrong for
virsh.remote_with_unix.negative_testing.allow_sasl_user_with_readonly
test and caused an error: multiple repeat at position 13. This commit fixes 
the regular expression, so the test can pass.
> remote_access:Fix remote unix readonly sasl

- libvirt/tests/cfg/migration/migrate_vm.cfg
RHEL-201640: [Migration][--migrate-disks] Specify the disks to be
migrated for storage migration - p2p
> Add p2p migration case for with_migrate_disks

- libvirt/tests/cfg/migration/live_migration.cfg
- libvirt/tests/src/migration/live_migration.py
1. RHEL-196112 - [Migration][--migrateuri] Specify migrate URI for
live migration - TCP - IP address + port
2. RHEL-199037 - [Migration][--listen-address] Specify a listen
address for incoming migration connections - 1 - p2p migration
3. RHEL-201638 - [Migration][--migrateuri] Specify migrate URI for
live migration - TCP - IP address - p2p migration **(critical case)**
4. RHEL-201653: [Migration][--listen-address] Specify a listen
address for incoming migration connections - 1 - non-p2p
depends on: https://github.com/avocado-framework/avocado-vt/pull/2979
https://github.com/avocado-framework/avocado-vt/pull/3018
```
WARNING:root:No python imaging library installed. Screendump and Windows guest BSOD …
```
> migration: Add some live migration cases

- libvirt/tests/cfg/migration/migrate_storage.cfg
RHEL-201639 - [Migration] [--disks-ports] Do storage migration with
specified port - p2p
```
JOB ID     : 6fdd801213a88f1d978d56adc96a5895897ae5e1
JOB LOG    : /root/avocado/job-results/job-2021-04-25T03.46-6fdd801/job.log
(1/1) type_specific.io-github-autotest-libvirt.virsh.migrate_storage.disks_port.copy_storage_all: PASS (142.28 s)
RESULTS    : PASS 1 | …
```
> migration: Add a disks_port related case

- libvirt/tests/cfg/migration/migrate_vm.cfg
RHEL-202913 - [Migration][--timeout]Set timeout for live
migration - default action(suspend guest after timeout)
- p2p migration - precopy
```
(1/1) type_specific.io-github-autotest-libvirt.virsh.migrate_vm.positive_testing.p2p_migration.timeout.without_postcopy: PASS (167.21 s)
JOB TIME   : 168.20 s
```
> Add timeout related p2p migration case

- libvirt/tests/src/virsh_cmd/snapshot/virsh_snapshot_create_as.py
- libvirt/tests/src/virsh_cmd/snapshot/virsh_snapshot_disk.py
This is to use alternative directory instead of /tmp to avoid some failures due to
tmpfs issues.
> virsh_snapshot_create_as: replace /tmp with new dir

- libvirt/tests/cfg/remote_access/remote_with_tls.cfg
- libvirt/tests/src/remote_access/remote_access.py
- Description of the case:
RHEL-7 is the only system where gnutls is too old to support @LIBVIRT specifier
- Introduced in:
https://libvirt.org/remote.html
Case_ID:
RHEL-152181
<pre>avocado run --vt-type libvirt virsh.remote_with_tls.positive_testing.default_tls_priority_specifier
<font color="#2A7BDE">JOB ID     : …
> remote_access:Added a new case for the @KEYWORD specifier support in the libvirt.

- .travis.yml
Since avocado, avocado-vt and aexpect are all not support python2
any more. tp-libvirt should go forward as well. Let's remove python2
from travis.
> Remove python2 from travis

- libvirt/tests/src/virtual_network/mtu.py
depends on https://github.com/avocado-framework/avocado-vt/pull/2973
```
JOB ID     : 09ddbd90e9fe39f807850e241e0f9b53336709af
JOB LOG    : /root/avocado/job-results/job-2021-03-24T07.57-09ddbd9/job.log
(1/1) type_specific.io-github-autotest-libvirt.virtual_network.mtu.negative_test.not_support.network.net_define.macvtap_type: PASS (6.07 s)
JOB TIME   : 7.58 s
JOB ID     : 7809efd6fd3ae7db857cc850644c36c4ca632751
JOB LOG    : /root/avocado/job-results/job-2021-03-24T08.03-7809efd/job.log
(1/1) type_specific.io-github-autotest-libvirt.virtual_network.mtu.negative_test.not_support.network.net_create.bridge_type: PASS (5.05 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 …
```
> Add wait for writing file success before return

- libvirt/tests/cfg/virsh_cmd/domain/virsh_blockcommit.cfg
- libvirt/tests/cfg/virsh_cmd/domain/virsh_blockpull.cfg
- libvirt/tests/cfg/virsh_cmd/snapshot/virsh_snapshot_create_as.cfg
- libvirt/tests/cfg/virsh_cmd/snapshot/virsh_snapshot_disk.cfg
- libvirt/tests/src/virsh_cmd/domain/virsh_blockcommit.py
- libvirt/tests/src/virsh_cmd/domain/virsh_blockpull.py
- libvirt/tests/src/virsh_cmd/snapshot/virsh_snapshot_create_as.py
- libvirt/tests/src/virsh_cmd/snapshot/virsh_snapshot_disk.py
The reasons for remove 'rdma' protocol:
1. From libvirt 6.0.0, the transport protocol 'rdma' is  not yet supported
2. Before libvirt 6.0.0, actually it's also not supported because it just transfer into tcp protocol.
3. No need to update polarion test cases
> virsh_blockcommit/blockpull/snapshot: remove transport protocol 'rdma' in gluster disk test

- libvirt/tests/src/virtual_device/tpm_device.py
If no tpm version info in dmesg, should try to test by tpm-tools
then tpm2-tools. So installation failure of tpm-tools should not
report error, but let it continue to try later tpm2-tools.  Also
fix another error that extra dependency fails swtpm* install, 
change to only install swtpm and swtpm-tools, that's enough.
e.g
> tpm_device: fix unexpected error

- libvirt/tests/cfg/libvirt_mem.cfg
```
(1/1) type_specific.io-github-autotest-libvirt.libvirt_mem.positive_test.with_source: PASS (64.50 s)
```
> Disable qemu-cmd-check for libvirt_mem basic test

- libvirt/tests/cfg/incremental_backup/incremental_backup_pull_mode.cfg
- libvirt/tests/src/incremental_backup/incremental_backup_pull_mode.py
Description:
When vm is destroyed or killed, its backup job should be canceled,
otherwise a deadlock will happen when vm started again.
Polarion Case: RHEL-199902 (pull mode part)
Test result: PASS
> incremental_backup: Check backup canceled when vm killed or destroyed

- libvirt/tests/src/virtual_device/tpm_device.py
```
(1/1) type_specific.io-github-autotest-libvirt.virtual_devices.tpm_device.normal_test.tpm-crb_model.emulator.encrypted.basic: PASS (97.97 s)
```
> Fix the tpm failure on /tmp dir

- libvirt/tests/cfg/virsh_cmd/domain/virsh_blkiotune.cfg
- libvirt/tests/src/virsh_cmd/domain/virsh_blkiotune.py
- Existing script does not aplly to cgroup2. So this is to enable
the test script to support both cgroup V1 and V2 and cfq/bfq as well.
- Some hosts are using vda instead sda for the hard disk. So this is
to dynamicly detect the disk and decide which scheduler file to be read.
Before fix:
```
TestError: Doesn't support controller &lt;blkio&gt;&#10;
```
> Fix blkiotune cgroup2 issues

- libvirt/tests/cfg/virtual_network/iface_options.cfg
- libvirt/tests/src/virtual_network/iface_options.py
Multiqueue is supported on direct type interface, add 1 test case
about it. And add the checkpoint for interface with multiqueue to
check the channel info in vm, and set the channel info. Also add 1
check point about qdisc check.
> Add one case about test multiqueue on direct type interface

- libvirt/tests/cfg/virtual_device/tpm_device.cfg
- libvirt/tests/src/virtual_device/tpm_device.py
Upstream libvirt support tpm emulator tpm-tis since 7.1.0.
```
commit 7cf60006ce1e9898b960d7810f146ac6c89f6bb0
Author: Jim Fehlig <jfehlig@suse.com>
Date:   Tue Feb 9 14:57:22 2021 -0700
qemu: Fix swtpm device with aarch64
Starting a VM with swtpm device fails with qemu-system-aarch64.
E.g. with TPM device config
<tpm model='tpm-tis'>
<backend type='emulator' version='2.0'/>
</tpm>
QEMU reports the following error
error: internal error: process exited while connecting to monitor:
2021-02-07T05:15:35.378927Z qemu-system-aarch64: -device
tpm-tis,tpmdev=tpm-tpm0,id=tpm0: 'tpm-tis' is not a valid device model name
Indeed the TPM device name is 'tpm-tis-device' [1][2] for aarch64,
versus the shorter 'tpm-tis' for x86. The devices are the same from
a functional POV, i.e. they both emulate a TPM …
```
> tpm_device: Enable emulator tpm-tis tests for aarch64

- libvirt/tests/src/virsh_cmd/domain/virsh_blockpull.py
Replace tmp_dir with data_dir to avoid the problem that filesystem
does not support O_DIRECT.
` (1/1) type_specific.io-github-autotest-libvirt.virsh.blockpull.normal_test.block_disk.notimeout.nobase.async: PASS (147.08 s)`
> virsh_blockpull: Update to use data_dir

- libvirt/tests/src/sriov/sriov.py
In cases 'cold_plug.nfv..', we need to set the numa node for the vm.
So there is a function add_numa(), which will delete the original cpu
setting and initiate the cpu part to '<cpu><numa/></cpu>' which ignored
the cpu mode setting, it will default to 'qemu64', which has bug
on some releases. Workaround it to be 'host-model' which is the original
vm setting.
> Fix the vm can not login issue

- libvirt/tests/src/virsh_cmd/domain/virsh_blockcommit.py
Replace tmp_dir with data_dir to avoid the problem that filesystem
does not support O_DIRECT.
_Before fix:_
(1/1) type_specific.io-github-autotest-`libvirt.virsh.blockcommit.normal_test.single_chain.file_disk.local.no_ga.notimeout.nobase.top_active.with_pivot: FAIL: Failed to make snapshots for disks! (23.69 s)`
_After fix:_
` (1/1) type_specific.io-github-autotest-libvirt.virsh.blockcommit.normal_test.single_chain.file_disk.local.no_ga.notimeout.nobase.top_active.with_pivot: PASS (25.70 s)`
> virsh_blockcommit: Update to use data_dir

- v2v/tests/cfg/function_test_esx.cfg
A better solution is replacing the marco with real value in libvirt-ci,
but '\n' in the string will cause a malform testcase cfg file in
tp-libvirt.
e.g.
variant:
- case1:
env_settings = "echo -e '${{{{luks_password}}}}
${{{{luks_password}}}}
${{{{luks_password}}}}
${{{{luks_password}}}}
' |"
- case2:
env_settings = "wrold"
There is not a good solution for keeping the '\n', meanwhile, don't
append the '\n' at the end of the string.
And this is not a typical senario, let's just set the real value to
avoid the risk of breaking libvit-ci.
> v2v: set an initial setting for luks password

- libvirt/tests/cfg/virtual_disks/virtual_disks_relative_blockcommit.cfg
- libvirt/tests/src/virtual_disks/virtual_disks_relative_blockcommit.py
RHEL-114368,RHEL-114379, RHEL-115480,RHEL-117812, RHEL-188186
cover iscsi,ceph backend storage with active/pause/restart_libvirtd scenarios
> Add blockcommit relative path cases

- provider/v2v_vmcheck_helper.py
- v2v/tests/cfg/function_test_esx.cfg
- v2v/tests/cfg/function_test_xen.cfg
- v2v/tests/cfg/specific_kvm.cfg
- v2v/tests/src/function_test_esx.py
- v2v/tests/src/function_test_xen.py
- v2v/tests/src/specific_kvm.py
This patch mainly move the windows cases from xen to esx because
the windows version which are supported on the xen host are not in
testing plan, those test scenaroes must be migrated to newer windows
version and so must be migrated to esx server, too.
The changes in this patch are:
1) Fix the expect_adapter setting when virtio-win is not installed but
users set in by env VIRTIO_WIN.
2) Migrate virtio_win cases from function_test_xen to function_test_esx
and adapt the codes.
3) Migrate rhsrvany_md5 from function_test_xen to function_test_esx and
adapt the codes.
4) Migrate default_install from xen to esx and rename it to win_rootonlinux
and change the output_mode to local only, because the win2003 guest is too
old and the spical guest cannot be made in other windows versions. so just …
> v2v: move windows cases from xen to esx

- libvirt/tests/cfg/migration/live_migration.cfg
- libvirt/tests/src/migration/live_migration.py
- provider/migration/migration_base.py
1. Add test scenario below - RHEL-201595
- Check port and cancel migration job, then migrate again and check
the port can be reused.
2. Some minor adjustments for migration speed in order to adapt to
different test environments.
3. Enable not to convert image for migration in order to save
execution time.
4. Create a new common package for migration cases shared usage
> add case for cancel migration

- libvirt/tests/src/virsh_cmd/domain/virsh_blockcopy.py
virsh_blockcopy.py: move get_tmp_dir() to get_data_dir()
Signed-off-by: Meina Li meili@redhat.com
> virsh_blockcopy.py: move get_tmp_dir() to get_data_dir()

- libvirt/tests/src/graphics/graphics_functional.py
libvirt auto-populate <audio> elements for vnc since 7.2.0
```
commit e88367095f3cad2cf80a687fd599dfaeb3073841
Author: Daniel P. Berrangé <berrange@redhat.com>
Date:   Wed Feb 24 14:24:10 2021 +0000
qemu: populate <audio> element with default config
Currently the QEMU driver secretly sets the QEMU_AUDIO_DRV env variable
- VNC - set to "none", unless passthrough of host env variable is set
- SPICE - always set to "spice"
- SDL - always passthrough host env
- No graphics - set to "none", unless passthrough of host env variable is set
The setting of the QEMU_AUDIO_DRV env variable is done in the code which
configures graphics.
If no <audio> element is present, we now auto-populate <audio> elements
to reflect this historical default config. This avoids need to set audio
env when processing …
```
> graphics_functional: Fix vnc expect option check

- libvirt/tests/cfg/virsh_cmd/domain/virsh_attach_detach_interface.cfg
virsh_attach_detach_interface: Use virtio as only supported option in this case for aarch64.
Signed-off-by: Ma Xinjian <maxj.fnst@cn.fujitsu.com>
e.g
test on rhel, qemu-kvm doesn't support e1000e or rtl8139
`
$ /usr/libexec/qemu-kvm -M virt -device help | grep e1000
`
`
$ /usr/libexec/qemu-kvm -M virt -device help | grep rtl8139
`
before: 
`
$ avocado run --vt-type libvirt --vt-arch aarch64 --vt-machine-type arm64-mmio   virsh.attach_detach_interface.normal_test.vm_running.default_network.default.domid
JOB ID     : ee459cb451c65ddefead9d4063daaff43c66a8ea
JOB LOG    : /root/avocado/job-results/job-2021-05-27T03.10-ee459cb/job.log
(1/1) type_specific.io-github-autotest-libvirt.virsh.attach_detach_interface.normal_test.vm_running.defa …
> Fix virsh_attach_detach_interface aarch64

- libvirt/tests/src/migration/live_migration.py
Due to the function name is wrongly checked, the two ports comparison
does not really happen. So this is to fix the wrong name.
> Fix port checking ignored

- libvirt/tests/cfg/virsh_cmd/domain/virsh_blkdeviotune.cfg
- libvirt/tests/src/virsh_cmd/domain/virsh_blkdeviotune.py
'qemu-img create' fails due to no enough space in certain environment.
In these cases, we do not need to create big image, 1G is enough. And
we should delete it after the case execution is done.
> Fix no space error

- libvirt/tests/cfg/virsh_cmd/network/virsh_net_dhcp_leases.cfg
- libvirt/tests/src/virsh_cmd/network/virsh_net_dhcp_leases.py
The error msg of <dhcp><lease "expiry" can't be parsed has changed since
libvirt 7.1.0.
https://bugzilla.redhat.com/show_bug.cgi?id=1918674
Tested on libvirt-7.3.0-1
Before this commit
```
JOB ID     : e2fc39039ba7d1bc8abbdc6f4b4b8581b7fe584d
JOB LOG    : /root/avocado/job-results/job-2021-05-23T23.50-e2fc390/job.log
(1/1) type_specific.io-github-autotest-libvirt.virsh.net_dhcp_leases.negative_test.blank_lease: ERROR: fail() takes from 1 to 2 positional arguments but 3 were given (10.64 s)
JOB TIME   : 11.36 s
[snip]
2021-05-23 23:51:00,651 test             L0917 ERROR| virttest.libvirt_xml.xcepts.LibvirtXMLError: Failed to create transient network …
```
> virsh_net_dhcp_leases: Update expect msg of negative_test blank_leases

- libvirt/tests/cfg/memory/memory_discard.cfg
The format of qemu cmdline memory-backend-file has changed since
qemu-kvm 6.0.0
Before qemu-kvm 6.0.0:
-object memory-backend-file,id=ram-node0,\
mem-path=/var/lib/libvirt/qemu/ram/1-avocado-vt-vm1/ram-node0,\
discard-data=yes,share=yes,size=536870912
Since qemu-kvm 6.0.0:
-object {"qom-type":"memory-backend-file","id":"ram-node0",\
"mem-path":"/var/lib/libvirt/qemu/ram/1-avocado-vt-vm1/ram-node0",\
"discard-data":true,"share":true,"size":536870912}
Update the regexp of qemu_checks to fix error that casued by the upgrade
of qemu-kvm.
> memory_discard: update the regexp of qemu_check cmdline

- libvirt/tests/cfg/memory/memory_discard.cfg
Increase memory size for the vm in case vm crash some time
> Increase memory size to fix vm crash some time

- libvirt/tests/src/migration/migrate_options_shared.py
Update to check the result of migration process.
_Before fix:_
` (1/1) type_specific.io-github-autotest-libvirt.virsh.migrate_options_shared.positive_test.native_tls.verify_client.no_post_after_precopy.without_postcopy: FAIL: The string '"dir":"/etc/pki/qemu","endpoint":"client","verify-peer":true' is not included in /var/log/libvirt/libvirtd.log (203.20 s)`
_After fix:(It's a known bug.)_
` (1/1) type_specific.io-github-autotest-libvirt.virsh.migrate_options_shared.positive_test.native_tls.verify_client.no_post_after_precopy.without_postcopy: FAIL: error: internal error: unable to execute QEMU command 'object-add': Parameter 'props' is unexpected (182.60 s)
`
> migration: No result check for some migration cases

- libvirt/tests/cfg/virsh_cmd/domain/virsh_emulatorpin_mix.cfg
- libvirt/tests/src/virsh_cmd/domain/virsh_emulatorpin_mix.py
Test Case: RHEL-114490
When vcpu placement is auto, test any of vcpupin,iothreadpin,emulatorpin is changed,
other two command results will not be impacted. The default values of three commands
should be same.
> Add case for vcpupin/emulatorpin/iothreadpin

- libvirt/tests/cfg/virtual_network/iface_network.cfg
- libvirt/tests/src/virtual_network/iface_network.py
When interface set without bandwidth, the default qdisc type should be
"noqueue". If the bandwidth is not set, the qdisc type should be "htb".
> Add the check for noqueue tun device

- libvirt/tests/src/virtual_network/iface_options.py
As the function has been moved to utils_net, fix the reference.
> One name fix

- libvirt/tests/cfg/libvirt_mem.cfg
- libvirt/tests/src/libvirt_mem.py
Fix qemu cmd change, it affects below test cases
JOB ID     : 412834442e235178a310625caf8ef3fa1cb513c3
JOB LOG    : /root/avocado/job-results/job-2021-05-24T01.52-4128344/job.log
(1/1) type_specific.io-github-autotest-libvirt.libvirt_mem.positive_test.mem_basic.discard: PASS (104.64 s)
avocado run --vt-type libvirt libvirt_mem.positive_test..with_source 
JOB ID     : 412834442e235178a310625caf8ef3fa1cb513c3
JOB LOG    : /root/avocado/job-results/job-2021-05-24T01.52-4128344/job.log
(1/1) type_specific.io-github-autotest-libvirt.libvirt_mem.positive_test.mem_basic.discard: PASS …
> Fix qemu cmd change for new version

- libvirt/tests/src/migration/live_migration.py
When config_object parameter in libvirt.customize_libvirt_config
is None, libvirt.customize_libvirt_config will return None and
don't restore configuration.
> live_migration: Fix remote qemu conf restore issue

- libvirt/tests/src/migration/migrate_over_unix.py
Update the number of VM's pci if needed.
**depends on**: https://github.com/avocado-framework/avocado-vt/pull/3068
_Before fix:_
` (1/1) type_specific.io-github-autotest-libvirt.virsh.migrate_over_unix.positive_testing.with_copy_storage.default.multi_disks.p2p_live_migration.without_postcopy: FAIL: error: Failed to attach device from /tmp/avocado_neocfhcb/xml_file\nerror: internal error: No more available PCI slots\n (18.65 s)
`
_After fix:_
` (1/1) type_specific.io-github-autotest-libvirt.virsh.migrate_over_unix.positive_testing.with_copy_storage.default.multi_disks.p2p_live_migration.without_postcopy: PASS (92.29 s)`
> migration: Fix "No more available PCI slots" problem

- v2v/tests/cfg/function_test_esx.cfg
> Remove win7 scenario from v2v job as win7 is not supported anymore

- v2v/tests/src/v2v_options.py
If some error happens, virt-v2v may be uninstalled unexpectedly.
In order to aovid failure of subsequent scripts, virt-v2v should
be installed no matter it was uninstalled or not.
> v2v: always install virt-v2v package when recovering envrionment

- libvirt/tests/cfg/migration/sriov_migrate.cfg
- libvirt/tests/src/migration/sriov_migrate.py
This PR adds 3 cases as below:
RHEL-198861 - migrate vm with hostdev device - VF
RHEL-205050 - postcopy migrate vm with hostdev device(VF) and
teaming setting
RHEL-205051 - Cancel migration for vm with hostdev device(VF)
and teaming setting
And update to access the migrated VM via the virsh session, because
the ssh connection from the target host to the migrated VM
is not stable sometimes.
avocado-framework/avocado-vt#3055
avocado-framework/avocado-vt#3054
avocado-framework/avocado-vt#3061
**Test results:** 4 cases are failed because of the known bugs
```
WARNING:root:No python imaging library installed. Screendump and Windows guest BSOD detection are disabled. In order to enable it, please install python-imaging or the …
```
> sriov_migration: Add 3 cases

- libvirt/tests/src/virtual_disks/virtual_disks_ceph.py
- libvirt/tests/src/virtual_disks/virtual_disks_gluster.py
- libvirt/tests/src/virtual_disks/virtual_disks_iscsi.py
- libvirt/tests/src/virtual_disks/virtual_disks_luks.py
- libvirt/tests/src/virtual_disks/virtual_disks_multivms.py
- libvirt/tests/src/virtual_disks/virtual_disks_usb.py
data_dir.get_tmp_dir() need to be replaced by data_dir.get_data_dir()
> Fix data_dir.get_tmp_dir() permission deny issue

- libvirt/tests/src/virtual_device/filesystem_device.py
Test cases without NUMA are supported only since 7.0.
Add switch in order to cancel test execution on earlier versions.
libvirt commit:
bff2ad5d6b1f25da02802273934d2a519159fec7
https://gitlab.com/libvirt/libvirt/-/commit/bff2ad5d6b1f25da02802273934d2a519159fec7
> [filesystem_device][virtio-fs] Add version switch

- libvirt/tests/cfg/sriov/sriov_net_failover.cfg
- libvirt/tests/src/sriov/sriov_net_failover.py
RHEL-200521 - hotplug/unplug a hostdev interface with teaming setting
RHEL-199084 - hotplug/unplug a hostdev device with teaming setting
RHEL-187001 - save & restore for vm with hostdev type interface and
teaming setting
depends on:
https://github.com/avocado-framework/avocado-vt/pull/3087
https://github.com/avocado-framework/avocado-vt/pull/3086
https://github.com/avocado-framework/avocado-vt/pull/3085
https://github.com/avocado-framework/avocado-vt/pull/3055
https://github.com/avocado-framework/avocado-vt/pull/3054
https://github.com/avocado-framework/avocado-vt/pull/3061
Test results: 1 case is failed due to BUGS.
```
(1/3) type_specific.io-github-autotest-libvirt.sriov_net_failover.hotplug_hostdev_device_with_team …
```
> SRIOV: Add 3 net failover cases

- libvirt/tests/src/virsh_cmd/domain/virsh_migrate.py
The error message was unclear if migration failed, so update to
provide a proper error message.
Before fix:
` (1/1) type_specific.io-github-autotest-libvirt.virsh.migrate.migrate_postcopy.without_cpu_hotplug.compat_migration.non_compat_migration.default: FAIL (160.50 s)`
After fix:
` (1/1) type_specific.io-github-autotest-libvirt.virsh.migrate.migrate_postcopy.without_cpu_hotplug.compat_migration.non_compat_migration.default: FAIL: error: internal error: unable to execute QEMU command 'migrate-set-capabilities': Postcopy is not supported (160.67 s)
`
> virsh_migrate: Update to catch a CmdError

- libvirt/tests/src/incremental_backup/incremental_backup_push_mode.py
This patch fixes 2 things:
1. Use get_data_dir() instead of get_tmp_dir() to avoid potential
issue on rhel9.
2. Clean local backup files after case execution to make sure other
cases not blocked by existing backup file.
> incremental_backup: use datadir as tmpdir and clean local backup file

- v2v/tests/cfg/function_test_xen.cfg
Because the windows guests is too old on xen server, they were
removed in 9a600c4df4b194d34ec8d800f12dacc9f50c3f21, but the
windows pre-configuration were left by mistake, this patch fixes
the problem.
> v2v: delete all windows configuration from xen

- libvirt/tests/cfg/virtual_network/iface_update.cfg
As libvirt use PCI address as one of the items to match the interface
device, update it makes no sense. Delete this kind of scenario.
> Delete one invalid case for update device

- libvirt/tests/src/virsh_cmd/domain/virsh_blockcopy.py
> Add debug logs to virsh.blockcopy tests

- libvirt/tests/cfg/remote_access/remote_with_ssh.cfg
- libvirt/tests/src/remote_access/remote_access.py
The new test cases added to test uri default and uri aliases.
- Description of the cases: custom uri aliases and uri default
- case ID: RHEL7-18304
<pre>WARNING:root:No python imaging library installed. Screendump and Windows guest BSOD detection are disabled. In order to enable it, please install python-imaging or the equivalent for your distro.
<font color="#2A7BDE">JOB ID     : 095e334a76344f8b7d924ab0d8242c27ca83beba</font>
<font color="#2A7BDE">JOB LOG    : /root/avocado/job-results/job-2021-05-31T03.22-095e334/job.log</font>
(1/1) …
> remote_access: new tests added for uri aliases/default

- libvirt/tests/cfg/cpu/vcpu_cache.cfg
The error message was updated, so update it accordingly.
Test result:
Before fix:
` (1/1) type_specific.io-github-autotest-libvirt.vcpu_cache.negative_test.passthrough_with_host_model.host_model: FAIL: Expect should fail with one of ["error: unsupported configuration: CPU cache mode 'passthrough' can only be used with 'host-passthrough' CPUs"], but failed with:\n\n\nerror: Failed to define domain from /tmp/xml_utils_temp_ybv8evo0.xml\nerror: unsupported con... (4.38 s)`
After fix: libvirt 7.4:
` (1/1) type_specific.io-github-autotest-libvirt.vcpu_cache.negative_test.passthrough_with_host_model.host_model: PASS (4.87 s)`
libvirt 7.0:
```
(1/1) type_specific.io-github-autotest-libvirt.vcpu_cache.negative_test.passthrough_with_host_model.host_mod …
```
> vcpu_cache: Update the error message

- libvirt/tests/src/virtio_transitional/virtio_transitional_blk_negative.py
The expected exception should be updated to cover
remote.LoginTimeoutError.
_Before fix:_
```
(1/1) type_specific.io-github-autotest-libvirt.virtio_transitional_blk_negative.with_virtio_blk.virtio: ERROR: Login timeout expired    (output: 'exceeded 240 s timeout') (259.15 s)
```
_After fix:_
```
JOB LOG    : /root/avocado/job-results/job-2021-06-15T03.04-f86a1de/job.log
(1/1) type_specific.io-github-autotest-libvirt.virtio_transitional_blk_negative.with_virtio_blk.virtio: PASS (259.17 s)
JOB TIME   : 259.65 s
```
> virtio_transitional_blk_negative：Correct the exception

- libvirt/tests/src/backingchain/blockcommand.py
- libvirt/tests/src/virsh_cmd/domain/virsh_blockcommit.py
It failed to create a block type snapshot for now, so update the
option of virsh snapshot-create-as command.
> blockcommand: Add stype=type to virsh snapshot-create-as

- libvirt/tests/cfg/migration/migrate_network.cfg
- libvirt/tests/src/migration/migrate_network.py
RHEL-189837 - Migrate vm with direct type interface assigned from
virtual network (auto-generated macvtap device name + fake tap
device exists on dst host).
```
JOB ID     : 362814ebb6c5c766f605d052d640b34d61784405
JOB LOG    : /root/avocado/job-results/job-2021-06-07T21.30-362814e/job.log
(1/1) type_specific.io-github-autotest-libvirt.virsh.migrate_network.direct.fake_macvtap_exists_dest.without_postcopy: PASS (175.11 s)
JOB TIME   : 176.59 s
```
>  Add a migration case to check the VM with direct type interface 

- libvirt/tests/src/conf_file/sysconfig_libvirt_guests/libvirt_guests.py
When undefine the guest, there could be managed save image.
Need to add --managed-save option.
> [libvirt_guests]Undefine the guest with --managed-save option

- libvirt/tests/cfg/remote_access/remote_with_unix.cfg
- libvirt/tests/src/remote_access/remote_access.py
The new case for SSH connection to the hypervisor has been added per
RHEL7-18313. Deprecated function for remote libvirt control replaced
by the supported one.
- Description of the case:
Connect to the hypervisor running on host over an SSH connection with sasl plain authentication 
- Introduced in:
https://libvirt.org/remote.html
- Case_ID:
RHEL7-18313
<pre>avocado run --vt-type libvirt virsh.remote_with_ssh.positive_testing.sasl_plain_auth
WARNING:root:No python imaging library installed. PPM image conversion to JPEG disabled. In order to enable it, please install python-imaging …
> remote_access: New case for SSH with SASL plain

- libvirt/tests/cfg/virtual_network/mtu.cfg
- libvirt/tests/src/virtual_network/mtu.py
- RHEL-198271: [pre-created tap] Set mtu for pre-created tap device
and start vm with another mtu setting and managed='no'
> Add 1 network case of mtu

- libvirt/tests/src/migration/migrate_with_virtual_devices.py
There is no "module" or "scrmod" in qemu version's output since
rhel9, so update is_rhev to False to return the correct value.
rhel9: QEMU emulator version 6.0.0 (qemu-kvm-6.0.0-5.el9)
Before fix:
```
>>> utils_misc.compare_qemu_version(4, 2, 0)
False
```
After fix:
```
>>> utils_misc.compare_qemu_version(4, 2, 0, False)
True
```
rhel8.4: QEMU emulator version 5.2.0 (qemu-kvm-5.2.0-16.module+el8.4.0+10806+b7d97207)
```
>>> utils_misc.compare_qemu_version(4, 2, 0)
True
>>> utils_misc.compare_qemu_version(4, 2, 0, False)
True
>>> 
```
> Correct compare_qemu_version

- libvirt/tests/cfg/migration/migrate_options_shared.cfg
The error message was updated, so update it.
Before fix:
` (1/1) type_specific.io-github-autotest-libvirt.virsh.migrate_options_shared.negative_test.multifd.inavalid_connect_num.set_cross_border.without_postcopy: FAIL: Can not find the expected patterns 'error: internal error: unable to execute QEMU command 'migrate-set-parameters': Parameter 'multifd_channels' expects is invalid, it should be in the range of 1 to 255' in output 'error: internal error: unable to execute... (138.35 s)`
After fix:
```
(1/1) type_specific.io-github-autotest-libvirt.virsh.migrate_options_shared.negative_test.multifd.inavalid_connect_num.set_cross_border.without_postcopy: PASS (130.57 s)
(1/1) type_specific.io-github-autotest-libvirt.virsh.migrate_options_shared.ne …
```
> migration: Update the error message for negative multifd cases

- libvirt/tests/src/cpu/iothread.py
The value of iothread_quota was changed, so update the code
accordingly.
Before fix:
```
JOB LOG    : /root/avocado/job-results/job-2021-06-17T02.15-a149309/job.log
(1/1) type_specific.io-github-autotest-libvirt.cpu.iothread.negative_test.iothread_quota_period_without_iothreads: FAIL: Unable to find expected value iothread_quota:-1 from command: '/bin/virsh schedinfo avocado-vt-vm1 '\nexit_status: 0\nduration: 0.016992568969726562\ninterrupted: False\npid: 265584\nencoding: 'UTF-8'\nstdout: 'Scheduler      : posix\ncpu_shares     : 100\nvcpu... (23.72 s)
```
After fix:
```
JOB LOG    : /root/avocado/job-results/job-2021-06-17T02.26-9a57335/job.log
(1/1) …
```
> iothread: Update the value of iothread_quota

- libvirt/tests/cfg/controller/controller_functional.cfg
- libvirt/tests/cfg/controller/pcibridge.cfg
- libvirt/tests/src/controller/pcibridge.py
- libvirt/tests/src/serial/serial_functional.py
Due to libvirt-7.4.0 new changes, some incorrect configrations are detected
earlier when defining the vm with different error messages. So this is to
update the error messages. In addition, checking qemu command line is
unneccessary, so I remove it to avoid of future errors.
> controller_functional: fix err messages

- libvirt/tests/cfg/incremental_backup/incremental_backup_migration.cfg
- libvirt/tests/src/incremental_backup/incremental_backup_migration.py
Case ID: RHEL-200250
Do copy storage migration when a vm has existing checkpoints
in its disk, and check the checkpoints are identical after
migration by verifying their hash values.
> incremental_backup: Add case to cover migration with storage

- libvirt/tests/cfg/virsh_cmd/interface/virsh_iface_list.cfg
- libvirt/tests/src/virsh_cmd/interface/virsh_iface_list.py
As netcf is deprecated on rhel 9, only 4 virsh commands are still supported, includes
iface-list, iface-mac, iface-name, iface-dumpxml. And all the information is got
from udev. On rhel 8, as it is not recommended to use iface-* commands to manage
host interface, cancel the test on rhel 8.
> Add test case about iface-* on rhel xx

- libvirt/tests/cfg/libvirt_ccw_passthrough.cfg
- libvirt/tests/src/libvirt_ccw_passthrough.py
Depends on https://github.com/avocado-framework/avocado-vt/pull/3064
1. Test device is visible inside guest.
2. Test device is removed gracefully when all channel paths
are removed.
> [vfio_ccw] Add ccw passthrough tests

- libvirt/tests/cfg/cpu/aarch64_cpu_sve.cfg
- libvirt/tests/src/cpu/aarch64_cpu_sve.py
SVE is the next-generation SIMD extension of the Arm v8-A AArch64
instruction set.
It  provided it is a multiple of 128 bits and does not exceed the architectural
maximum of 2048 bits.
Each processor may support different vector length. This test works on Fugaku
processor(A64FX) announced to support 512bit.
- Positive test:
1) Enable sve in domain xml. Expect guest support SVE. The length
should be sve512 by default
```
<feature policy='require' name='sve'/>
[root@localhost ~]# dmesg | grep -i sve
[    0.010220] SVE: maximum available vector length 64 bytes per vector
[    0.010229] SVE: default vector length 64 bytes per vector
```
2) Disable sve in domain xml. Expect guest doesn't support SVE
```
<feature policy='disable' name='sve'/>
[root@localhost ~]# dmesg | grep -i sve …
```
> cpu: Add aarch64_cpu_sve test

- libvirt/tests/cfg/migration/live_migration.cfg
- libvirt/tests/src/migration/live_migration.py
- provider/migration/migration_base.py
Case ID :RHEL-196368
Test matrix for default/migrate_tls_x509_verify with qemu native
TLS encryption migration. Different combinations are to test if
the verifying client x509 cert is required and migration can be
succeeded.
> Add cases for tls verify client migration

- libvirt/tests/cfg/virtual_network/iface_nss.cfg
- libvirt/tests/src/virtual_network/iface_nss.py
Introduce 2 test cases about the libvirt-nss module. For libvirt managed network,
such as forward mode is nat, route, isolated, or open, which dnsmasq will assigns
IP address to domains, libvirt provides plugin for the NSS ecosystem. So we can
resolve the domain name with libvirt_guest, and resolve the guest's hostname with
libvirt module.
> Test the libvirt-nss module

- provider/v2v_vmcheck_helper.py
See bz1961945.
Because of above bug, the chipset setting was broken in rhv4.4.6.8.
And it blocks all our testing. A temporary workaround is done to
avoid all scripts failure. Once it's fixed, a better solution will
replace this one.
> v2v: fix chipset type checkpoint in rhv4.4.6.8

- libvirt/tests/cfg/virsh_cmd/domain/virsh_domfsinfo.cfg
Added an error message to the config file as the message was reworded
in a newer versions of the libvirt.
> virsh_domfsinfo:fix for error message rewording in new version of libvirt.

- v2v/tests/cfg/nbdkit/nbdkit.cfg
- v2v/tests/src/nbdkit/nbdkit.py
The old testing step is wrong. when qemu >= 5.2.0.3, it can handle
'2**63 - 2**30' and when qemu < 5.2.0.3, it can handle '2**63 - 512'.
> v2v: fix failure of max_disk_size

- libvirt/tests/src/virsh_cmd/domain/virsh_managedsave.py
The output of libvirt-guests differs between products, therefore
the regex of pattern needs update.
> Fixup: update regex for managedsave case

- libvirt/tests/cfg/virsh_cmd/domain/virsh_domiftune.cfg
- libvirt/tests/src/virsh_cmd/domain/virsh_domiftune.py
Since libvirt-7.3.0, the outbound average value was changed.
So this is to update with new outbound value.
> virsh_domiftune: Fix outbound value

- libvirt/tests/src/virsh_cmd/nodedev/virsh_nodedev_list.py
Vlan devices are not expected to be used for passthrough via hostdev.
They are not listed with nodedev-list. Remove them from test
expectation.
> [nodedev-list] Ignore vlan devices

- libvirt/tests/src/libvirt_scsi_hostdev.py
Load modprobe sg manually since kernel not load it automatically,see [1] for further reference
Skip unpriv_sgio check since feature change,see [2] for more details 
[1]https://bugzilla.redhat.com/show_bug.cgi?id=1962482
[2]https://bugzilla.redhat.com/show_bug.cgi?id=1810667
> Fix scsi sgio issue on latest libvirt version by below steps

- libvirt/tests/src/virtual_disks/virtual_disks_vhostuser.py
Wrongly use test.fail() format
> Fix test.fail()format issue in vhost-user case

- libvirt/tests/cfg/virtual_device/tpm_device.cfg
- libvirt/tests/src/virtual_device/tpm_device.py
The persistent_state attribute indicates whether 'swtpm' TPM state
is kept or not when a transient domain is powered off. Supported
from libvirt 7.0.0. Work with pr: avocado-vt/pull/3091. RHEL-197332
> tpm_device: add test for persistent_state

- libvirt/tests/src/libvirt_scsi_hostdev.py
It need return True directly if previously skip checks
> Fix libvirt_hostdev sgio related cases failure

- v2v/tests/cfg/function_test_esx.cfg
- v2v/tests/src/function_test_esx.py
1) The pnp_wait.exe message is hidden in bz1903960.
https://bugzilla.redhat.com/show_bug.cgi?id=1903960
2) rhev-apt.exe doesn't exist any more on rhel9
> v2v: fix rhev-apt.exe and pnp_wait.exe checking error

- v2v/tests/src/function_test_esx.py
From the backtrace, aexpect.exceptions.ShellStatusError is returned
instead of ShellProcessTerminatedError, so the guest reboot process
was not captured.
> v2v: fix qemu-ga service not found issue

- v2v/tests/cfg/function_test_esx.cfg
- v2v/tests/src/function_test_esx.py
The warning displays because of fstrim failure to the partiion of
the guest, it's no harm to the real convertion. And now on rhel9
the fstrim operation can success, it may be related to the kernel
change. Let's just ignore this warning checking.
> v2v: don't check fstrim warning on rhel9

- v2v/tests/cfg/function_test_esx.cfg
> v2v: don't test to rhv when VIRITO_WIN or virtio-win is not set

- libvirt/tests/src/virsh_cmd/domain/virsh_attach_device.py
On lastest RHEL, /var/log/libvirt has write permisison issue
so change  to /var/lib/libvirt instead
> Fix Virtualdiskbasic serialFile serialpipe failure

- libvirt/tests/src/virtual_disks/virtual_disks_usb.py
Some error from tp-libvirt:unsupported configuration: vt82c686b-usb-uhci not supported in this QEMU binary
if not cancel them
> Skip vt82c686b-usb-uhci case in libvirt 7.4.0 afterwards

- libvirt/tests/src/conf_file/qemu_conf/auto_dump.py
The package 'lsof' is not installed by default on host. So install
it.
> auto_dump: Fix 'lsof' command not found problem

- libvirt/tests/src/virtual_network/iface_stat.py
Before:
```
(1/1) type_specific.io-github-autotest-libvirt.virtual_network.iface_stat.compare.direct_type: ERROR: Shell command failed: 'ping www.redhat.com -c 20'    (status: 1,    output: 'PING www.redhat.com(g2600-1417-0076-0592-0000-0000-0000-0d44.deploy.static.akamaitechnologies.com (2600:1417:76:592::d44)) 56 data bytes\nFrom 2620:52:0:4972::1fe (2620:52:0:4972... (44.65 s)
```
After:
```
(1/1) type_specific.io-github-autotest-libvirt.virtual_network.iface_stat.compare.direct_type: PASS (45.49 s)
```
> Fix the ping error inside vm

- libvirt/tests/src/virsh_cmd/domain/virsh_domxml_to_native.py
In libvirt commit d96fb5cb31b, QEMU_AUDIO_DRV is replaced by -audiodev argument.
So we need not to check it after libvirt 7.3.0. In addition, some minor changes
are also updated and ignore to check.
> virsh_domxml_to_native: Fix env variable

- libvirt/tests/src/virtual_network/iface_options.py
The format changed from '\"name\"' to 'name' so need to change and compatible with the old one
Before:
```
(1/1) type_specific.io-github-autotest-libvirt.virtual_network.iface_options.iface_type.type_vhostuser.multi_guests.statistics_check: ERROR: name 'vhost' is not defined (99.08 s)
```
After:
```
(1/1) type_specific.io-github-autotest-libvirt.virtual_network.iface_options.iface_type.type_vhostuser.multi_guests.statistics_check: PASS (130.91 s)
```
> Fix the error for the output format change on ovs list

- libvirt/tests/cfg/serial/serial_functional.cfg
- libvirt/tests/cfg/virsh_cmd/domain/virsh_detach_serial_device_alias.cfg
- libvirt/tests/src/serial/serial_functional.py
- libvirt/tests/src/virsh_cmd/domain/virsh_attach_device.py
The serial source path can't use /var/log in rhel9 for having permission issues
> Fix the serial source path permission issues in rhel9

- libvirt/tests/cfg/memory/nvdimm.cfg
- libvirt/tests/src/memory/nvdimm.py
Fix nvdimm mount command on rhel9, add umount before reboot vm and fix the qemu
command line check for the changes in new version
> Fix nvdimm on qemu command line change on new version

- v2v/tests/src/function_test_xen.py
The test.fail argument number is wrong.
> v2v: fix argument number error in test.fail

- libvirt/tests/src/migration/migrate_vm.py
Avocado-vt commit f5b2953ca adjusted the folder path for temporary
image files to use `data_dir.get_data_dir()`.
Therefore, the test failed as it copied the machine image for iscsi
to a different location and the vm couldn't start from that empty image.
Update the path correspondingly.
> [migrate_vm] fix iscsi image path

- libvirt/tests/cfg/npiv/npiv_virtual_disk.cfg
- libvirt/tests/src/npiv/npiv_virtual_disk.py
The npiv storage is actually a block device. Previously libvirt
allows to use a block device with "device_type='file'". But it's
forbidden in rhel9. So change the device_type='file' to
device_type='block' to avoid this issue.
> npiv: Fix device type problem

- libvirt/tests/cfg/virsh_cmd/virsh_connect.cfg
- libvirt/tests/src/virsh_cmd/virsh_connect.py
New case added for checking if the connection to virsh is still
alive, after the wrong attempt.
- Description of the cases: libvirt connection shouldn't be broken after connect a bad hypervisor
- Case IDs: RHEL7-18310
<pre>avocado run --vt-type libvirt --vt-machine-type q35 virsh.connect.local_connect.normal_test.connection_alive
<font color="#2A7BDE">JOB ID …
> remote_access: Check the connection to virsh after wrong attempt

- libvirt/tests/src/sriov/sriov_net_failover.py
The message was incorrect, so fix it.
```
(1/1) type_specific.io-github-autotest-libvirt.sriov_net_failover.hotplug_hostdev_iface_with_teaming: FAIL: Unable to get expected interface. The interface {'bridge'} should be {'bridge', 'hostdev'}. (44.58 s)
```
> sriov_net_failover: Correct the err messge

- libvirt/tests/src/graphics/graphics_functional.py
The short-form boolean options in qemu cmdline like
"disable-ticketing" are deprecated. Use normal form boolean
options with value "on" or "off". So use "disable-ticketing=on"
instead.
> graphics_functional: Update option value

- libvirt/tests/src/sriov/sriov.py
Cancel the test if the driver does not match.
```
(1/2) type_specific.io-github-autotest-libvirt.sriov.normal_test.info_check.vf_info.driver.ixgbe: PASS (108.06 s)
(2/2) type_specific.io-github-autotest-libvirt.sriov.normal_test.info_check.vf_info.driver.i40e: CANCEL: Driver i40e is not supported on this host. (27.27 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 1
JOB TIME   : 137.01 s
```
> sriov: Checking driver before testing

- libvirt/tests/src/virtual_disks/virtual_disks_multidisks.py
Current logic only open virt_use_nfs for file and floppy. We failed to attach
an nfs iso to guest in RHEL since the default virt_use_nfs is false
> virtual_disks_multidisks: Enable virt_use_nfs for nfs related cases

- libvirt/tests/cfg/incremental_backup/incremental_backup_migration.cfg
Nfs setup is enabled in base.cfg as glocal setting, but this case
uses local storage, so need to disable nfs setup in this case.
e.g
> increm_mig: Disable nfs setup

- libvirt/tests/cfg/sriov/sriov_net_failover.cfg
- libvirt/tests/src/sriov/sriov_net_failover.py
RHEL-187001 - [save/restore][net failover] Save & restore for vm
with hostdev type interface and teaming setting
Test result: Failed because of BZ1815426.
` (1/1) type_specific.io-github-autotest-libvirt.sriov_net_failover.save_restore_hostdev_iface_with_teaming: ERROR: Command '/usr/bin/virsh save avocado-vt-vm1 /tmp/avocado_t4n0wh7t/save_file ' failed.\nstdout: b''\nstderr: b''\nadditional_info: None (188.27 s)`
> sriov: Add 1 net failover case

- libvirt/tests/cfg/sriov/sriov_capabilities.cfg
- libvirt/tests/src/sriov/sriov_capabilities.py
This PR adds a case:
RHEL-144331 - [Capabilities] check virsh capabilites output
includes iommu support element
**Depends on:** 
https://github.com/avocado-framework/avocado-vt/pull/3115
` (1/1) type_specific.io-github-autotest-libvirt.sriov.capabilities.intel_iommu: PASS (3.50 s)`
> sriov: Add a case to check iommu

- libvirt/tests/src/migration/live_migration.py
It was introduced by 104ad96260c.
_Before fix:_
` (1/1) type_specific.io-github-autotest-libvirt.virsh.live_migration.listen_address.specific_ipv6_addr.migrateuri_ipv4_addr.non_p2p_live.without_postcopy: FAIL: Migrated VMs failed to be in running state at destination (176.47 s)`
_After fix:_
` (1/1) type_specific.io-github-autotest-libvirt.virsh.live_migration.listen_address.specific_ipv6_addr.migrateuri_ipv4_addr.non_p2p_live.without_postcopy: PASS (173.64 s)`
> live_migration: Update to do post checks when migration is successful

- libvirt/tests/cfg/sriov/sriov_nodedev.cfg
- libvirt/tests/src/sriov/sriov_nodedev.py
This PR adds a case:
RHEL7-17994 - Reattach/reset/detach a pci device when it is used
in guest.
**Depends on:** 
https://github.com/avocado-framework/avocado-vt/pull/3113
` (1/1) type_specific.io-github-autotest-libvirt.sriov_nodedev.pf: PASS (8.95 s)`
> sriov: Add a case to test reattach/reset a pci device

- libvirt/tests/cfg/virtual_network/iface_network.cfg
As we will update the first interface to be the one exists on the host,
and do not care the others(the others will not be used by the guest, so
it is acceptable), if we test duplicate dev, we should ensure the others
are duplicate. For net_private test, no need 2 deivces as it may cause
error on certain systems.
> Make the cfg file more robust

- libvirt/tests/cfg/migration/migrate_options_shared.cfg
As of now, the load of aarch64 guest that created by stress tool is too
small. Migration finished too fast.
When test check the num of established connection, migration was
finishd so the number always be 0.
Increase the load of guest during migration to fix the issue.
Before
```
(.libvirt-ci-venv-ci-runtest-TzvLnZ) [root@hpe-moonshot-02-c20 ~]# avocado run --vt-type libvirt --vt-machine-type arm64-pci virsh.migrate_options_shared.positive_test.multifd.default_connection.with_postcopy  --vt-connect-uri qemu:///systm
JOB ID     : 1fe5a7b90e0ce52335136e2c88337191fef17d8a
JOB LOG    : /root/avocado/job-results/job-2021-07-09T04.31-1fe5a7b/job.log
(1/1) type_specific.io-github-autotest-libvirt.virsh.migrate_options_shared.positive_test.multifd …
```
> migrate_options_shared: Fix aarch64 unexpected established con num

- libvirt/tests/cfg/virtual_network/iface_network.cfg
- libvirt/tests/src/virtual_network/iface_network.py
8.8.8.8 is useless now. Change it to use one of host dns nameservers.
And add dig test inside guest to verify the configurations really work.
RHEL7-18747.
e.g
> iface_network: add dig test for net_dns_host

- libvirt/tests/cfg/libvirt_mem.cfg
- libvirt/tests/src/libvirt_mem.py
Increase the inital memory size and numa config to avoid crashing
> Increase the init memory size and numa config to avoid vm crash

- libvirt/tests/src/channel/channel_functional.py
The ported created by the rule changed in rhel9 and use the first port found
> Fix the port created is not really exist issue

- libvirt/tests/src/incremental_backup/incremental_backup_push_mode.py
When test job executed, some other cases may fail to cleanup env and
leave unremoved backup file in tmp_dir. This will cause rest cases
failed due to 'backup file already exists' error. This patch is to
fix this kind of failures.
> incremental_backup: Fix 'backup file already exists' issue

- libvirt/tests/cfg/incremental_backup/incremental_backup_push_mode.cfg
The original case is to destroy vm or kill qemu process to make
sure ongoing backup can be canceled normally. But case has random
failures when the backup job is finished too quickly. This fix is
to generate a larger file (1000M) to make sure the backup job
won't finish before destroy_vm/kill_process happens.
> incremental_backup: Fix backup job not canceled issue

- libvirt/tests/src/incremental_backup/incremental_backup_pull_mode.py
When qemu killed, the checkpoint's metadata will be inconsistent
with the checkpoint data in image files. This cause failures when
undefine vm during cleanup process. This patch is to fix this
problem.
> incremental_backup: Fix checkpoint metadata issue when qemu killed

- libvirt/tests/cfg/cpu/diagnose_spinlock_yield_forward.cfg
- libvirt/tests/src/cpu/diagnose_spinlock_yield_forward.py
Spinlock yield forwarding can potentially let the host solve
spinlocks in the guest by forwarding diag9c. The test confirms
the forwarding. Testing the rate value is out of scope (non-functional
test). However, we choose a high value to make sure yields are forwarded
because during testing lower rate settings didn't seem to be functional
as they didn't forward anything.
More info: https://www.kernel.org/doc/html/latest/virt/kvm/s390-diag.html
> [cpu/diagnose] Add test for spinlock yield forwarding 

- libvirt/tests/cfg/virsh_cmd/network/virsh_net_define_undefine.cfg
- libvirt/tests/src/virsh_cmd/network/virsh_net_define_undefine.py
Add some negative test cases about create bridge or direct type network. Some elements
are only available for libvirt managed network such as nat, route, isolated, open, they
can not be used in bridge or direct type network.
> Add some negative test cases about network define

- libvirt/tests/src/virsh_cmd/network/virsh_net_define_undefine.py
Fix inspektor violation " E231 missing whitespace after ','"
> [virsh_net_define_undefine] fix inspektor violation

- libvirt/tests/cfg/conf_file/qemu_conf/set_virtlogd.cfg
- libvirt/tests/src/conf_file/qemu_conf/set_virtlogd.py
aarch64 console log is different with x86, set matched_msg for aarch64. 
Before
```
[root@hpe-apollo80-01-n00 ~]# avocado run --vt-type libvirt --vt-machine-type arm64-mmio conf_file.qemu_conf.set_virtlogd.positive_test.reload.vm_with_console_log
JOB ID     : 7fece0a29d7e10831b661d12f49336cd16319e2d
JOB LOG    : /root/avocado/job-results/job-2021-07-15T04.03-7fece0a/job.log
(1/1) type_specific.io-github-autotest-libvirt.conf_file.qemu_conf.set_virtlogd.positive_test.reload.vm_with_console_log: FAIL: Failed to get VM started log from VM log file: /var/log/libvirt/qemu/avocado-vt-vm1-console.log. (57.06 s)
JOB TIME   : 57.81 s
```
After
``` …
```
> set_virtlogd: Set matched_msg for aarch64

- libvirt/tests/cfg/virsh_cmd/domain/virsh_guestvcpus.cfg
On AMD machine, vcpu0 is not offlinable as designed. So the error message
should be enhanced.
> virsh_guestvcpus: fix vcpu0 on AMD

- libvirt/tests/cfg/migration/migrate_storage.cfg
Slow down the migration process to do 'cancel' operation during
the migration.
_Before fix:_
```
rhel.virsh.migrate_storage.with_tls.cancel_migration.copy_storage_inc
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```
_After fix:_ failed caused by BZ 1978526.
` (1/1) type_specific.io-github-autotest-libvirt.virsh.migrate_storage.with_tls.cancel_migration.copy_storage_inc: FAIL: The string '"execute":"blockdev-add","arguments":{"driver":"nbd","server":{"type":"inet","host":".*","port":"49153"},"export":"drive-virtio-disk0","tls-creds":"objlibvirt_migrate_tls0"' is not included in /var/log/libvirt/libvirt_daemons.log (297.83 s)`
> migration: Add bandwidth opt to cancel_migration case

- libvirt/tests/cfg/virtual_network/iface_hotplug.cfg
- libvirt/tests/src/virtual_network/iface_hotplug.py
When there are 2 interfaces with duplicate mac address, detach by
mac address will fail. So libvirt add one more match method to match
interface by alias. Add 2 test cases both positive and negative to
test the match method.
> Detach interface match by alias

- libvirt/tests/src/cpu/iothread.py
The value of iothread_quota is different in rhel9 and rhel8.5, so
it shouldn't check libvirt version.
_rhel8.5, libvirt 7.5.0-1:_
```
(01/21) type_specific.io-github-autotest-libvirt.cpu.iothread.positive_test.iothread_config.only_iothread_id: PASS (51.11 s)
(02/21) type_specific.io-github-autotest-libvirt.cpu.iothread.positive_test.iothread_config.only_iothread_num: PASS (47.13 s)
(03/21) type_specific.io-github-autotest-libvirt.cpu.iothread.positive_test.iothread_config.both_iothread_id_num: PASS (48.00 s)
(04/21) type_specific.io-github-autotest-libvirt.cpu.iothread.positive_test.iothreadpin: PASS (51.86 s)
(05/21) type_specific.io-github-autotest-libvirt.cpu.iothread.positive_test.iothread_poll: PASS (52.87 s)
(06/21) …
```
> cpu: Update iothread_quota's value

- libvirt/tests/cfg/bios/boot_integration.cfg
- libvirt/tests/src/bios/boot_integration.py
Description of the cases: 
Create snapshot for a OVMF/seabios domain with 'boot order' or 'boot dev' element
Links of case IDs:
https://polarion.engineering.redhat.com//polarion/#/project/RedHatEnterpriseLinux7/workitem?id=RHEL7-45939
https://polarion.engineering.redhat.com//polarion/#/project/RedHatEnterpriseLinux7/workitem?id=RHEL7-45937
https://polarion.engineering.redhat.com//polarion/#/project/RedHatEnterpriseLinux7/workitem?id=RHEL7-45938
https://polarion.engineering.redhat.com//polarion/#/project/RedHatEnterpriseLinux7/workitem?id=RHEL7-45940
> BIOS: add case for creating snapshot with boot dev/order

- libvirt/tests/cfg/sriov/sriov_managed.cfg
- libvirt/tests/src/sriov/sriov_managed.py
- provider/sriov/sriov_base.py
RHEL7-18519 - [network] Start vm with VF from VF Pool
with "managed=no" or default setting
RHEL7-43422 - [attach-device] Hotplug/unplug VF with managed='no'
https://github.com/avocado-framework/avocado-vt/pull/3133
https://github.com/avocado-framework/avocado-vt/pull/3136
https://github.com/avocado-framework/avocado-vt/pull/3137
https://github.com/avocado-framework/avocado-vt/pull/3138
```
(1/3) type_specific.io-github-autotest-libvirt.sriov.managed.networks.managed_no: PASS (109.36 s)
(2/3) type_specific.io-github-autotest-libvirt.sriov.managed.networks.default: PASS (170.95 s)
(3/3) type_specific.io-github-autotest-libvirt.sriov.managed.device_hotplug.managed_no: PASS (40.63 s)
RESULTS    : PASS 3 | ERROR 0 …
```
> sriov: Add 2 'managed' related cases

- libvirt/tests/src/virsh_cmd/domain/virsh_attach_passthrough_no_bus.py
This test needs passthrough host device to guest and uses
/dev/input/event1 by default.
Add a check for default passthrough deivce, cancel test if host doesn't
have test device.
Before
An aarch64 host which doesn't have /dev/input/event1, test fail
```
[root@hpe-apollo80-01-n00 ~]# avocado run  --vt-type libvirt --vt-arch aarch64 --vt-machine-type arm64-mmio virsh.attach_passthrough_no_bus
JOB ID     : e82ef14308b050c102b3de5e25c48198091bfbcf
JOB LOG    : /root/avocado/job-results/job-2021-07-21T04.05-e82ef14/job.log
(1/1) type_specific.io-github-autotest-libvirt.virsh.attach_passthrough_no_bus: ERROR: error: Failed to attach device from /tmp/xml_utils_temp_wutd2jev.xml\nerror: Path '/dev/input/event1' is not accessible: No such file or …
```
> virsh_attach_passthrough_no_bus: Check host passthrough device

- libvirt/tests/cfg/virsh_cmd/nodedev/crypto_nodedev_create_destroy.cfg
- libvirt/tests/src/virsh_cmd/nodedev/crypto_nodedev_create_destroy.py
'ap_matrix' device support has been added in libvirt 7.0.0
(s. libvirt commit 53cc4951792f809ace308187c327758ffc64c831).
Cancel test run if earlier version.
> crypto_nodedev_create_destroy: add version switch

- libvirt/tests/src/virtual_network/iface_coalesce.py
When the connection is "--", it means there is no connection for this
interface, the interface is available for macvtap interface.
> Fix the script error when connection is "--"

- provider/v2v_vmcheck_helper.py
When converting guest to rhv by v2v + rhv-upload, there are different
result:
1. when rhv < 4.4.6.8, the chipset is set to Q35
2. when 4.4.6.8 < rhv < 4.4.7.6, the chipset is set to BIOS, see bz1961945,
it is fixed in 4.4.7.6.
3. when rhv >= 4.4.7.6, the chipset is set to Q35 when converting from ESX server.
But it is set to BIOS when converting from XEN or Libvirt. see bz1983610. The
issue is target to 4.4.8 right now.
> v2v: update expected chipset settings against different rhv server

- libvirt/tests/cfg/sriov/sriov_ro_sysfs.cfg
- libvirt/tests/src/sriov/sriov_ro_sysfs.py
RHEL-182382: Hot-plug VF to VM when the PCI configuration file is
in read-only mode
```
JOB ID     : 41d829fc9e733a23753f46f49ccc2bebf0e47848
JOB LOG    : /root/avocado/job-results/job-2021-07-14T02.22-41d829f/job.log
(1/1) type_specific.io-github-autotest-libvirt.sriov.ro_sysfs.vf_hotplug: PASS (31.21 s)
JOB TIME   : 32.82 s
```
> sriov: Add a case to test VF under the ro mode sys

- libvirt/tests/cfg/migration/migrate_vm.cfg
Compile netperf meet following error:
gcc -o netperf netperf.o netlib.o netsh.o nettest_bsd.o nettest_dlpi.o nettest_unix.o nettest_xti.o nettest_sctp.o nettest_sdp.o nettest_omni.o net_uuid.o dscp.o netcpu_none.o netrt_none.o netdrv_none.o netslot_none.o netsys_none.o netsec_none.o -lm
/usr/bin/ld: nettest_omni.o:(.bss+0x398): multiple definition of loc_nodelay'; nettest_bsd.o:(.bss+0x20): first defined here /usr/bin/ld: nettest_omni.o:(.bss+0x39c): multiple definition of rem_nodelay'; nettest_bsd.o:(.bss+0x24): first defined here
/usr/bin/ld: nettest_omni.o:(.bss+0x3a0): multiple definition of loc_sndavoid'; nettest_bsd.o:(.bss+0x30): first defined here /usr/bin/ld: nettest_omni.o:(.bss+0x3a4): multiple definition of loc_rcvavoid'; nettest_bsd.o:(.bss+0x34): first defined here …
> migrate_vm: Update netperf version

- libvirt/tests/cfg/sriov/sriov_net_failover.cfg
Net fail over feature is supported for q35 only.
> sriov: limit net fail over cases to q35 only

- provider/v2v_vmcheck_helper.py
When hypervisor is kvm and input_mode is ova, the chipset is still
Q35 in rhv server.
> v2v: fix chipset error when input_mode is ova

- provider/v2v_vmcheck_helper.py
If setup_session failed and raised an exception, the vm will not
be cleaned up by normal in finnaly clause. This patch clean it
asap.
> v2v: clean up the guest when setup_session raise exception

- libvirt/tests/cfg/virtual_disks/virtual_disks_transient_disk.cfg
- libvirt/tests/src/virtual_disks/virtual_disks_transient_disk.py
Add support for the following libvirt new features:
```
v7.4.0
qemu: Add support for sharing base image of <transient/> disks
Users can use <transient shareBacking='yes'/> to tell the qemu driver
to never open the base image in write mode thus multiple VMs can share
the same image. Note that the disk will be hotplugged during startup.
```
Signed-off-by: Ma Xinjian <maxj.fnst@fujitsu.com>
e.g
https://libvirt.org/news.html#v7-4-0-2021-06-01
```
$ avocado run --vt-type libvirt --vt-arch aarch64 --vt-machine-type arm64-mmio type_specific.io-github-autotest-libvirt.virtual_disks.multivms..vms_transient_sharebacking_test
JOB ID     : 1891acc1f89bbb4c52174d4509840c12df89eb16
JOB LOG    : …
```
> Add transient sharebacking test cases

- libvirt/tests/cfg/sriov/sriov.cfg
- libvirt/tests/src/sriov/sriov.py
- libvirt/tests/src/sriov/sriov_net_failover.py
- libvirt/tests/src/sriov/sriov_nodedev.py
PF is got from the given driver in the previous code. If the driver
does not exist, it will not work, so update to get it directly
from the system.
depends on https://github.com/avocado-framework/avocado-vt/pull/3146
Test results:
```
(1/2) type_specific.io-github-autotest-libvirt.sriov_nodedev.pf: PASS (11.15 s)
(2/2) type_specific.io-github-autotest-libvirt.sriov_net_failover.hotplug_hostdev_device_with_teaming: PASS (136.45 s)
(001/110) type_specific.io-github-autotest-libvirt.sriov.normal_test.guest_with_vf.hotplug.default.resume_suspend.vf.managed_no: PASS (98.91 s)
(002/110) type_specific.io-github-autotest-libvirt.sriov.normal_test.guest_with_vf.hotplug.default.resume_suspend.vf.managed_yes: PASS (97.19 s)
(003/110) …
```
> sriov: Update to get pf from pf info dict

- libvirt/tests/cfg/memory/memballoon.cfg
- libvirt/tests/src/memory/memballoon.py
- RHEL-135026: Start vm with specified alias for memballoon device
> Add new case of memballoon

- libvirt/tests/cfg/memory/memory_hotplug.cfg
According to the feature itself
> Set one memory hotplug case to x86 only

- libvirt/tests/cfg/virsh_cmd/volume/virsh_vol_clone_wipe.cfg
- libvirt/tests/cfg/virsh_cmd/volume/virsh_vol_download_upload.cfg
- libvirt/tests/cfg/virsh_cmd/volume/virsh_vol_resize.cfg
- libvirt/tests/src/virsh_cmd/volume/virsh_vol_clone_wipe.py
- libvirt/tests/src/virsh_cmd/volume/virsh_vol_download_upload.py
- libvirt/tests/src/virsh_cmd/volume/virsh_vol_resize.py
Polarion case:
RHEL-249798 - Volume lifecycle test with cluster size in dir pool
> Storage: add vol-resize/clone/download/upload cases with clusterSize

- libvirt/tests/cfg/controller/controller_functional.cfg
aarch64 use pcie_root by default. Skip this test for aarch64
> controller_functional: skip pci_root for aarch64

- provider/v2v_vmcheck_helper.py
When qxldod.inf is not found in virtio-win.iso, virtio_win_installed
will be set to False incorrectly. Acutally, virtio_win_installed
should only related to the rpm virtio-win and VIRIO_WIN env, either
one is true, the virtio_win_installed should be true.
> v2v: fix expected video erro when qxldod is not in virtio-win

- libvirt/tests/src/sriov/sriov_ro_sysfs.py
Fix the occasional failure caused by the vm not boot successfully,
or vf not initialized successfully.
> Wait a while to confirm the vf initialize and vm boot

- libvirt/tests/cfg/virtual_network/iface_network.cfg
- libvirt/tests/src/virtual_network/iface_network.py
- libvirt/tests/src/virtual_network/iface_options.py
Qdisc noqueue is supported since libvirt 7.0.0, add the versoin check before
the noqueue check.
> Fix: add a libvirt version check

- libvirt/tests/cfg/daemon/libvirt_guests_service.cfg
- libvirt/tests/src/daemon/libvirt_guests_service.py
This PR adds 3 cases:
1. RHEL-255437 - Start libvirt-guests while libvirtd is stopped
2. RHEL-254524 - Stop libvirt-guests while libvirtd is stopped
3. RHEL-254332 - Restart libvirtd with running vm
> daemon: Add 3 libvirt-guests service related cases

- libvirt/tests/cfg/virsh_cmd/volume/virsh_vol_create.cfg
- libvirt/tests/src/virsh_cmd/volume/virsh_vol_create.py
Description of the cases:
RHEL-249800 - Create volume with cluster size in netfs pool
RHEL-249799 - Start the guest with volume disk created with cluster size
Related RFE Bug:
Bug 1945401 - RFE: Add support for specifying cluster_size/subcluster allocation for qcow2 volumes via virStorageVolCreateXML
> Storage: add clusterSize element cases to volume

- libvirt/tests/cfg/numa/numa_memory_spread.cfg
- libvirt/tests/src/numa/numa_memory_spread.py
Added a new test to check if the memory is spread across multiple
nodes, when needed.
Description of the case:
virsh numatune --nodeset does not get respected by a running qemu process - bug 1206625
Links of libvirt features, libvirt bugs or case IDs:
RHEL7-22941
Test results:
<pre>avocado run --vt-type libvirt --vt-machine-type q35 numa_memory_spread
<font color="#2A7BDE">JOB …
> NUMA:New Test for memory spread

- libvirt/tests/cfg/numa/numa_config_with_auto_placement.cfg
- libvirt/tests/src/numa/numa_config_with_auto_placement.py
New case added for NUMA auto placement check.
- Description of the cases:
Check numatune/ vcpupin/ emulatorpin configure information after set vcpu placement='auto' and memory placement='auto' - bug 1365779, bug1445325
- Case IDs:
RHEL7-91370
<pre>avocado run --vt-type libvirt --vt-machine-type q35 numa_config_with_auto_placement
<font color="#2A7BDE">JOB ID …
> NUMA: New case added for NUMA auto placement check.

- libvirt/tests/src/virsh_cmd/domain/virsh_set_user_password.py
Since the version OpenSSL 3.0 there is no -crypt parameter available and
therefore this fix adds check for the OpenSSL version and update command
accordingly.
Test results prior fix:
L0930 ERROR| ERROR 1-type_specific.io-github-autotest-libvirt.virsh.set_user_password.normal_test.normal_user.encrypted -> CmdError: Command 'openssl passwd -crypt aredhat' failed.stdout: b''stderr: b'passwd: Unknown option: -crypt\npasswd: Use -help for summary.\n'additional_info: None
Test result after the fix:
<pre>avocado run --vt-type libvirt --vt-machine-type q35 virsh.set_user_password.normal_test.root.encrypted
WARNING:root:No python imaging library installed. Screendump and Windows guest BSOD detection are disabled. In order to enable it, please install …
> Guest_Agent:Fix for the OpenSSL version as there is no -crypt parameter

- v2v/tests/src/v2v_options.py
> v2v: add checkpoint for glance deprecate on RHEL9

- libvirt/tests/src/npiv/npiv_hostdev_passthrough.py
In rhel9, the sg mod is not probed by default, and this will make
scsi hostdev passthrough failed. This fix is to add a 'modprobe sg'
step to make sure sg mod is probed.
> npiv: Fix the scsi hostdev case when sg mod not probed

- libvirt/tests/cfg/passthrough/ccw/libvirt_ccw_passthrough_read_write.cfg
- libvirt/tests/src/passthrough/ccw/libvirt_ccw_passthrough_read_write.py
- provider/vfio/ccw.py
Move helpers into module for reuse in new test cases.
Add a basic test case to confirm the attached DASD can be used.
> [ccw_passthrough_read_write] Add test case for read/write operations

- provider/v2v_vmcheck_helper.py
Bug 1983610 was fixed, the ovirt-engine version should be updated.
> v2v: update fixed ovirt-engine version

- libvirt/tests/src/graphics/graphics_functional.py
Some options in qemu cmdline updated from libvirt 7.3. So update
code.
> graphics_functional: Update expected option

- libvirt/tests/src/incremental_backup/incremental_backup_pull_mode.py
The 'error_operation' could be existing but None, so the
'"kill_qemu" in error_operation' could lead to a 'NoneType is not
iterable' error. This patch is to fix this.
> incremental_backup: fix 'NoneType is not iterable' error

- libvirt/tests/cfg/virtual_network/iface_bridge.cfg
- libvirt/tests/src/virtual_network/iface_bridge.py
- libvirt/tests/src/virtual_network/iface_network.py
Test Qos for bridge type interface and networks. Move the tc rule
check function from the iface_network.py into avocado-vt for sharing.
Depends on https://github.com/avocado-framework/avocado-vt/pull/3124
> Add Qos test for bridge type interface

- libvirt/tests/cfg/sriov/sriov_nodedev.cfg
- libvirt/tests/src/sriov/sriov_nodedev.py
RHEL-250626 - Reattach/detach a vf when it is used in guest
depends on: https://github.com/avocado-framework/avocado-vt/pull/3161
```
JOB ID     : 25f3a8ced7c14674bf880aea0cc048b3131a7e4a
JOB LOG    : /root/avocado/job-results/job-2021-08-02T02.01-25f3a8c/job.log
(1/2) type_specific.io-github-autotest-libvirt.sriov_nodedev.pf: PASS (8.83 s)
(2/2) type_specific.io-github-autotest-libvirt.sriov_nodedev.vf: PASS (13.71 s)
```
> sriov: Add a case to test vf detach/reattach

- libvirt/tests/cfg/conf_file/libvirtd_conf/prefix_num.cfg
- libvirt/tests/src/conf_file/libvirtd_conf/prefix_num.py
[RHEL7-111013]
[libvirtd][config]Check the prefix of libvirtd.conf in
/usr/lib/sysctl.d/
> libvirtd: Add case for check the prefix of libvirtd.conf

- libvirt/tests/src/remote_access/remote_access.py
As mentioned in the Bug 1931723, the legacy support must be enabled
in RHEL >= 9 as follows: update-crypto-policies --set LEGACY.
This is also documented in the man page:
https://libguestfs.org/virt-v2v-input-xen.1.html#ssh-authentication
-  Test results:
<pre>avocado run --vt-type libvirt --vt-machine-type q35 virsh.remote_with_ssh.positive_testing.xen_uri_with_root_user …
> Remote Access: Fix for Xen cases

- libvirt/tests/cfg/graphics/graphics_functional.cfg
Prepare spice cert is unneccessary for vnc. So update cfg file.
> graphics_functional: Remove extra steps for vnc

- libvirt/tests/cfg/virsh_cmd/domain/virsh_domif_setlink_getlink.cfg
- libvirt/tests/src/virsh_cmd/domain/virsh_domif_setlink_getlink.py
Add restart_libvirtd, save_restore post actions test after set iface
link. Auto RHEL7-97270.
e.g
> domif_setlink: add restart_libvirtd, save_restore

- libvirt/tests/src/virsh_cmd/domain/virsh_event.py
7494d48d91b9e7d75a8b76b3ef9a79b05f4c796e changed the regex
to match error messages against to reflect newer versions
that use "'". However, older versions now have a test failure.
Instead of introducing a switch over the actual libvirt
version have a less strict regex to confirm that the domain
name is part of the error message independently from the usage
of "'".
Test cases failed with message "FAIL: Not find expected event:event 'lifecycle' for domain 'avocado-vt-vm1'[...]"
> virsh_event: relax regex

- libvirt/tests/cfg/libvirtd/libvirtd_multi_conn.cfg
- libvirt/tests/src/libvirtd/libvirtd_multi_conn.py
[RHEL7-17510] - [libvirtd] Open multiple connections to libvirtd
- bug 983026
> libvirtd: Add case to check netlink

- libvirt/tests/src/virtual_disks/virtual_disks_snapshot_blockpull.py
The called method in libvirt_disk.py change from fill_sth_in_vm to fill_null_in_vm
> Fix one failure in snapshot blockcopy

- libvirt/tests/src/virsh_cmd/domain/virsh_attach_device.py
tmp_data_dir has existed o_direct permission issue
> Fix issue by switching image folder from tmp_data_dir to data_dir

- libvirt/tests/cfg/virsh_cmd/domain/virsh_blockcopy.cfg
- libvirt/tests/src/virsh_cmd/domain/virsh_blockcopy.py
Based on the reproduce steps of
https://bugzilla.redhat.com/show_bug.cgi?id=924151
Set virt_use_nfs on to fix selinux issue
------
stderr: 'error: Failed to start domain \'avocado-vt-vm1\'\nerror: internal error: qemu unexpectedly closed the monitor: 2021-07-27T07:56:48.770625Z qemu-kvm: -blockdev {"driver":"file","filename":"/var/lib/avocado/data/avocado-vt/nfs-mount/nfs-img","node-name":"libvirt-1-storage","cache":{"direct":true,"no-flush":false},"auto-read-only":true,"discard":"unmap"}: Could not open \'/var/lib/avocado/data/avocado-vt/nfs-mount/nfs-img\': Permission denied\n'
------
Before
```
[root@hpe-moonshot-02-c25 ~]# avocado run --vt-type libvirt --vt-arch aarch64 --vt-machine-type arm64-mmio …
```
> virsh_blockcopy: Fix selinux issue

- libvirt/tests/cfg/virsh_cmd/domain/virsh_domif_setlink_getlink.cfg
- libvirt/tests/src/virsh_cmd/domain/virsh_domif_setlink_getlink.py
The set link up and down are related with the interface driver.
So expand the test coverage to test all current supported models.
> Add more model to the domif-setlink test

- libvirt/tests/cfg/virtual_network/iface_bridge.cfg
- libvirt/tests/src/virtual_network/iface_bridge.py
When a tap device is attached to a host shared bridge, and the tap
device is in use, delete and create the bridge will break the connection.
But libvirt can reconnect it to the bridge with a restart.
> Add 3 test cases about tap device connection check

- libvirt/tests/cfg/virtual_network/iface_network.cfg
- libvirt/tests/src/virtual_network/iface_network.py
A network destroy and start will make all the connected tap devices detached.
And libvirtd service restart can recover it.
> Restart libvirtd will re-connect the detached tap device

- libvirt/tests/cfg/migration/migrate_event.cfg
- libvirt/tests/src/migration/migrate_event.py
- provider/migration/migration_base.py
Case ID: RHEL-198888
Check events when cancelling migration in PerformPhase and after
src vm is paused.
> migrate_event: Add case for migration event

- libvirt/tests/src/passthrough/ccw/libvirt_ccw_passthrough.py
- provider/vfio/ccw.py
1. Improve tear down
On older kernel versions[1] the teardown might get stuck.
Improve teardown to pass tests also on older kernel versions.
[1] Kernel (5.11+):
bccce80bbd44 vfio-ccw: Wire in the request callback
a15ac665b9e9 vfio-mdev: Wire in a request handler for mdev parent
2. Improve formatting
Add `--force` flag to avoid interference between tests. Without it
the tool might consider the disk in use due to recent use in other
tests and tests would fail.
> libvirt_ccw_passthrough: Improve test stability

- libvirt/tests/cfg/virtual_network/iface_options.cfg
As s390x do not support openvswitch, skip the test which has
openvswitch dependency.
> Exclude s390x for vhostuser related test

- libvirt/tests/cfg/virsh_cmd/host/virsh_deprecate_api.cfg
- libvirt/tests/src/virsh_cmd/host/virsh_deprecate_api.py
New deprecated API is available from the libvirt 7.3.0-1 and this API
provides an information about deprecated machine type and devices by QMP
messages and taint messages in virsh. This test is about to test these
APIs for cpu, vm and machine-types.
- Description of the cases:
defined in RHEL-242185
- Case IDs:
RHEL-242184, RHEL-242186, RHEL-242187
<pre>avocado run --vt-type libvirt --vt-machine-type q35 virsh.deprecate_api
WARNING:root:No python imaging library installed. PPM image conversion to JPEG disabled. In order to enable it, …
> virsh_cmd:New cases added to test deprecated API

- libvirt/tests/cfg/virtual_network/iface_options.cfg
Reverts autotest/tp-libvirt#3724
After discussed with others, we prefer to add these cases into skiplist instead, as the openvswitch+s390x can be in upstream.
> Revert "Exclude s390x for vhostuser related test"

- libvirt/tests/src/virsh_cmd/domain/virsh_domif_setlink_getlink.py
Bring up the interface need more time than expected sometimes.
Extend the wait time to 20s.
> Extend the wait time when bring up the interface

- libvirt/tests/cfg/bios/virsh_boot.cfg
- libvirt/tests/src/bios/virsh_boot.py
Polarion cases:
RHEL-203277 - Boot OVMF guest with signed image - secure-boot/enrolled-key enabled/disabled
RHEL-203278 - Boot OVMF guest with non-signed image - secure-boot/enrolled-key enabled/disabled
> BIOS: add feature related cases of firmware to os

- libvirt/tests/src/virtual_network/iface_update.py
Update the rom file path as the qemu changes in bug 1980139. qemu has drop all /usr/share/qemu-kvm rom symlinking in the spec file since qemu-kvm-6.0.0-11.el9. So the original file path  "/usr/share/qemu-kvm" will no longer used. To support it, ipxe also change a bit since ipxe-20200823-5.git4bd064de.el9. As it will be easier to check the ipxe version than qemu(qemu version differs in different releases), add the version check based on the package ipxe-roms-qemu.
> Update the rom file path if needed

- libvirt/tests/src/virtual_network/mtu.py
As "ifconfig" which is provided by "net-tools" is not installed in some guest's images, change to use more common command ip
to get the mtu information.
> Replace "ifconfig" command by "ip link" command

- provider/sriov/sriov_base.py
It failed to get the vf without waiting for a period of time after
setting it.
Before fix:
` (1/1) type_specific.io-github-autotest-libvirt.sriov.attach_from_network.active.networks.macvtap_passthrough: ERROR: Unable to get VF. status: 2, stdout: . (13.17 s)`
After fix:
` (1/1) type_specific.io-github-autotest-libvirt.sriov.attach_from_network.active.networks.macvtap_passthrough: PASS (42.13 s)`
> sriov: Update to check vf's setting

- libvirt/tests/src/incremental_backup/incremental_backup_checkpoint_cmd.py
- libvirt/tests/src/virsh_cmd/domain/virsh_managedsave_extra.py
Add graphics if guest doesn't have to fix IndexError
Before
```
[root@hpe-apollo80-01-n00 ~]# avocado run --vt-type libvirt --vt-arch aarch64 --vt-machine-type arm64-mmio \
> virsh.managedsave_extra.positive_test.dumpxml.secure_info \
> incremental_backup.checkpoint_cmd.checkpoint-dumpxml.security-info
JOB ID     : 9c3bc33694952c44f4f9017ac2b4c09f3f258723
JOB LOG    : /root/avocado/job-results/job-2021-08-23T02.34-9c3bc33/job.log
(1/2) type_specific.io-github-autotest-libvirt.virsh.managedsave_extra.positive_test.dumpxml.secure_info: ERROR: list index out of range (8.87 s)
(2/2) type_specific.io-github-autotest-libvirt.incremental_backup.checkpoint_cmd.checkpoint-dumpxml.security-info: ERROR: list index out of range (42.06 s)
```
After …
> virsh_managedsave_extra: Fix IndexError: list index out of range

- provider/migration/migration_base.py
If 'expected_event_src' is empty, it will cause local variable
'virsh_session' referenced before assignment. So update code.
> Fix local variable 'virsh_session' referenced before assignment

- libvirt/tests/cfg/cpu/vcpu_nested.cfg
- libvirt/tests/src/cpu/vcpu_nested.py
Case ID： RHEL-190499
Check the timestamp within the vm after vm cpu model is changed with
nested virt setup
> vcpu_nested: add case for cpu change

- v2v/tests/cfg/function_test_esx.cfg
Conversion succeeds with --no-copy after virt-v2v-1.45.3-1.el9
> v2v: conversion succeeds with --no-copy after virt-v2v-1.45.3-1.el9

- provider/sriov/sriov_base.py
Add timeout parameter to recover_vf().
` (1/1) type_specific.io-github-autotest-libvirt.sriov.scalability.max_vfs: PASS (362.73 s)`
> sriov: Add timeout to recover_vf

- v2v/tests/cfg/function_test_esx.cfg
- v2v/tests/src/function_test_esx.py
-os dir in original script is /tmp and TC failed due to insufficient space in /tmp folder.
Modify the folder to /var/lib/libvirt/images and add the cleanup dir.
> v2v: modify dir location for -o json and add cleanup

- libvirt/tests/cfg/virtual_disks/virtual_disks_vhostuser.cfg
- libvirt/tests/src/virtual_disks/virtual_disks_vhostuser.py
Since QEMU 5.2 (commit a4eef0711b2)[1] the default queues of
vhost-user-blk-pci will be set to the numbers of smp. In case it is over
the default queues value 1 in qemu-storage-daemon, set it to 1.
Fix the 
[1]: https://gitlab.com/qemu/qemu/-/commit/a4eef0711b2cf7a7476c3e2c202a414b68a1baa0
> virtual_disks_vhostuser: Set queues of vhost blk to 1

- libvirt/tests/cfg/virtual_network/iface_network.cfg
- libvirt/tests/src/virtual_network/iface_network.py
Virtual network can be set as disable dns or dhcp, add 3 cases to test
the function includes: disable_dns, disable_dhcp, disable_dns_dhcp. The
main checkpoint is to check the dnsmasq config file and the listening
port opened by dnsmasq.
> Add 3 cases for virtual network about dnsmasq

- libvirt/tests/src/virsh_cmd/domain/virsh_guestinfo.py
In the past, there were no _hostname_ command available in some images
and therefore the _hostnamectl_ was used instead. The _hostname_ is available
again and the _hostnamectl_ causing issues right now and therefore the
_hostname_ command was added back, but the _hostnamectl_ is there as a backup
for images, where the _hostname_ might not be available.
- Test results before the fix:
<pre>avocado run --vt-type libvirt --vt-machine-type q35 virsh.guestinfo.positive.hostname_info
WARNING:root:No python imaging library installed. PPM image conversion to …
> guest_agent: Fix the guest_agent guestinfo case for hostname

- libvirt/tests/cfg/virtual_disks/virtual_disks_rotation_rate.cfg
- libvirt/tests/src/virtual_disks/virtual_disks_rotation_rate.py
Case ID:
RHEL-201842: Start vm with scsi bus and rotation_rate disk
RHEL-201843: Start vm with sata bus and rotation_rate disk
RHEL-201844: Hotplug/unplug rotation_rate disk on scsi bus
RHEL-254338: Set various values for rotation_rate for disk on SCSI bus
> virtual_disks_rotation_rate: Add case for disk rotation

- libvirt/tests/cfg/cpu/vcpupin.cfg
- libvirt/tests/src/cpu/vcpupin.py
Automate below two cases:
RHEL-114432	[vcpupin] Test vcpupin cmd with --live
- vcpupin with --live whem vm is active
- vcpupin with --live --config when vm is active
RHEL-114431	[vcpupin] Test vcpupin cmd with --current
- vcpupin with --current when vm is active
- vcpupin with --current when vm is inactive
> virsh_vcpupin: Add case for vcpupin

- libvirt/tests/cfg/sriov/sriov_vf_pool.cfg
- libvirt/tests/src/sriov/sriov_vf_pool.py
- provider/sriov/sriov_base.py
This PR adds:
1. RHEL7-18529: Attach/detach interfaces from macvtap network
with passthrough mode
2. RHEL7-103842: Attach VF in direct passthrough mode with PF is down
```
(1/2) type_specific.io-github-autotest-libvirt.sriov.vf_pool.active.at_dt.macvtap_passthrough: PASS (36.60 s)
(2/2) type_specific.io-github-autotest-libvirt.sriov.vf_pool.inactive.at_dt.macvtap_passthrough: PASS (46.42 s)
```
> SR-IOV: Add 2 macvtap passthrough related cases

- libvirt/tests/cfg/cpu/aarch64_cpu_sve.cfg
- libvirt/tests/src/cpu/aarch64_cpu_sve.py
1. Add positive case of setting multiple vector length.
2. Add negative case of setting conflict sve policy.
3. Fix the wrong logic that caused the test to be cancelled.
```
> aarch64_cpu_sve.positive_test.vector_length_test.valid_length.mutiple_vector \
> aarch64_cpu_sve.negative_test.vector_length_test.conflict_length
JOB ID     : 807025b478216feca36e553ff316ae9eca656a65
JOB LOG    : /root/avocado/job-results/job-2021-09-09T22.52-807025b/job.log
(1/2) type_specific.io-github-autotest-libvirt.aarch64_cpu_sve.positive_test.vector_length_test.valid_length.mutiple_vector: PASS (79.12 s)
(2/2) type_specific.io-github-autotest-libvirt.aarch64_cpu_sve.negative_test.vector_length_test.conflict_length: PASS (44.59 s)
RESULTS    : PASS 2 | ERROR …
```
> aarch64_cpu_sve: Add sve cases

- libvirt/tests/src/virsh_cmd/network/virsh_net_update.py
> Remove checking for daemon crash which is not the checkpoint

- libvirt/tests/cfg/virtual_network/iface_network.cfg
- libvirt/tests/src/virtual_network/iface_network.py
This was fixed only with 7.0.0 and confirmed with devs
there are no plans to backport at this point because there's
a workaround.
> iface_network: add version switch

- libvirt/tests/src/numa/numa_memory_spread.py
This test needs at least 2 numa nodes.
Before
```
JOB ID     : a8f28dd3b9994ab764ced92f26a802e477aaa070
JOB LOG    : /root/avocado/job-results/job-2021-09-14T23.40-a8f28dd/job.log
(1/1) type_specific.io-github-autotest-libvirt.numa_memory_spread.default: ERROR: local variable 'neighbour' referenced before assignment (20.47 s)
JOB TIME   : 21.10 s
```
After
```
JOB ID     : b83e7da48c05a98e987c758929976bda6bad913e
JOB LOG    : /root/avocado/job-results/job-2021-09-14T23.38-b83e7da/job.log
(1/1) type_specific.io-github-autotest-libvirt.numa_memory_spread.default: CANCEL: This test needs at least 2 available numa nodes (10.54 s)
RESULTS    : PASS 0 | ERROR 0 | …
```
> [minor fix] numa_memory_spread: Add numa nodes check

- libvirt/tests/cfg/daemon/kill_qemu.cfg
- libvirt/tests/cfg/daemon/kill_started.cfg
- libvirt/tests/src/daemon/kill_qemu.py
- libvirt/tests/src/daemon/kill_started.py
> Clean coredump info for cases generating coredump during test

- libvirt/tests/src/virtual_network/iface_rename.py
It is better to use test.cancel() than test.fail() when the libvirt
version without the fix.
> Update the test.fail() to test.cancel()

- libvirt/tests/cfg/virtual_disks/virtual_disks_nbd.cfg
Default nbd 10001 is pre-occupied,change to another one
> Fix nbd default port pre-occupied issue

- libvirt/tests/cfg/migration/live_migration.cfg
RHEL7-17349 - [Migration] Do non-live migration - bug 1265902
> live_migration: Add case about non-live migration

- provider/sriov/sriov_base.py
The 'tail' command in the VM was changed to 'taiil' unexpectedly.
It's not 100% repeatable, but occurs in some environments. So, as
a workaround, shorten the command.
` (1/1) type_specific.io-github-autotest-libvirt.sriov.vf_pool.active.at_dt.macvtap_passthrough: FAIL: Failed to ping ip route |awk -F '/' '/^[0-9]/, /dev enp1s0/ {print $1}' |taiil -1\n10.73.32.1! status: 127, output: ping ip route |awk -F '/' '/^[0-9]/, /dev enp1s0/ {print $1}'' |taiil -1\n-bash: taiil: command not found\nping: route: Name or service not kn... (39.05 s)`
After:
```
(1/1) type_specific.io-github-autotest-libvirt.sriov.vf_pool.active.at_dt.macvtap_passthrough: PASS (39.02 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN …
```
> sriov: Fix a command failure

- libvirt/tests/src/virsh_cmd/host/virsh_deprecate_api.py
Raise cancel and fail exceptions otherwise all exceptions will be
treated as test.error.
Before
```
JOB ID     : e659776f2580a48bcfcb3401c120fd4e9107141b
JOB LOG    : /root/avocado/job-results/job-2021-09-15T23.26-e659776/job.log
(1/1) type_specific.io-github-autotest-libvirt.virsh.deprecate_api.domain_deprecated_info.positive_test.cpu_machine_type: ERROR: Unexpected error: There is no deprecated cpu or machine type in current qemu version, skipping the test. (48.09 s)
JOB TIME   : 48.85 s
```
After
```
JOB ID     : 16266ed1981263e3992dbddbf5304e45c6f77859
JOB LOG    : /root/avocado/job-results/job-2021-09-15T23.35-16266ed/job.log
(1/1) …
```
> [minor fix] virsh_deprecate_api: Raise cancel and fail exceptions

- libvirt/tests/cfg/virtual_network/iface_options.cfg
- libvirt/tests/src/virtual_network/iface_options.py
The vhost_dpdk case is to cover the bug 1767013 which was fixed on
libvirt-7.0.0-1. So add the version check in the case.
> Add version check the the vhost_dpdk case

- libvirt/tests/cfg/virtual_device/tpm_device.cfg
On rhel product, the error msg when passhthrough multiple tpm
devices would be different from rhel-av. Update the error msg to
adapt to more situations.
e.g
> tpm_dev: passthrough error msg fix

- libvirt/tests/cfg/virsh_cmd/domain/virsh_sendkey.cfg
- libvirt/tests/src/virsh_cmd/domain/virsh_sendkey.py
Part of sysrq tests failed since sysrq doesn't work. The root cause is
the lack of keyboard device.
Refer to BZ#1526862.
> virsh_sendkey: Fix sysrq doesn't work

- libvirt/tests/cfg/virsh_cmd/domain/virsh_cpu_xml.cfg
- libvirt/tests/deps/cap_mix.xml
- libvirt/tests/deps/capabilities.xml
- libvirt/tests/deps/capability_cpu.xml
- libvirt/tests/deps/cpu.xml
- libvirt/tests/deps/domcapabilities.xml
- libvirt/tests/src/virsh_cmd/domain/virsh_cpu_xml.py
RHEL-150995: Test "virsh {hypervisor-}cpu-{baseline,compare}" cmds with XML file with XML declaration
RHEL-139122: Test 'virsh hypervisor-cpu-baseline' cmd with <cpu>/domcapabilities/capabilities XML
RHEL-139119: Test 'virsh cpu-baseline' cmd with <cpu> definition / capabilities XML
> virsh_cpu_xml: add cases for cpu

- libvirt/tests/src/virtual_disks/virtual_disks_ceph.py
slice_offset+slice_size need be equal to size of src_img
as per description in [1]
[1]https://github.com/autotest/tp-libvirt/issues/3751
> Fix blockcopy slice case failure

- libvirt/tests/cfg/virsh_cmd/domain/virsh_hypervisor_cpu_baseline.cfg
- libvirt/tests/src/virsh_cmd/domain/virsh_hypervisor_cpu_baseline.py
RHEL-136603: Test parameters for 'virsh hypervisor-cpu-baseline' cmd
> virsh_hypervisor_cpu_baseline: add new cases

- provider/v2v_vmcheck_helper.py
- spell.ignore
The name of 'Red Hat VirtIO Ethernet Adapte' was changed in
db35d6b5aa60c5f9862c54d0d98be4b56f479836. This is a typo issue in
driver. We should keep it when checking the name.
> v2v: fix 'Red Hat VirtIO Ethernet Adapte' driver checking failure

- libvirt/tests/src/sriov/sriov.py
It takes some time to attach a device, so wait 10s before detaching
it.
`
(1/1) type_specific.io-github-autotest-libvirt.sriov.normal_test.guest_with_vf.cold_plug.nop.hostdev.managed_no: FAIL: The hostdev device detach failed from xml\n (112.10 s)
`
After the fix:
```
(1/2) type_specific.io-github-autotest-libvirt.sriov.normal_test.guest_with_vf.cold_plug.nop.hostdev.managed_yes: PASS (58.38 s)
(2/2) type_specific.io-github-autotest-libvirt.sriov.normal_test.guest_with_vf.cold_plug.nop.hostdev.managed_no: PASS (57.30 s)
```
> sriov: Fix device detach failure

- libvirt/tests/src/memory/memory_misc.py
Before
```
JOB ID     : 37d5b707b55605e751da1db52717c61b7f38dffc
JOB LOG    : /root/avocado/job-results/job-2021-09-22T22.31-37d5b70/job.log
(1/1) type_specific.io-github-autotest-libvirt.memory_misc.edit_mem.forbid_0.set_with_numa: ERROR: 'member_descriptor' object has no attribute 'getroot' (8.92 s)
JOB TIME   : 9.72 s
```
After
```
JOB ID     : 3773e73a670438fa7e1417c64c5ea95c90506849
JOB LOG    : /root/avocado/job-results/job-2021-09-22T22.33-3773e73/job.log
(1/1) type_specific.io-github-autotest-libvirt.memory_misc.edit_mem.forbid_0.set_with_numa: PASS (9.39 s)
JOB TIME …
```
> [minor fix] memory_misc: Fix 'member_descriptor' object has no attribute 'getroot'

- libvirt/tests/src/virtual_disks/virtual_disks_vhostuser.py
Regarding disk object, driver attribute need to be set as whole dict,
rather than single dict key
> Fix driver queues attribute doesn't take effect issue

- libvirt/tests/src/virtual_disks/virtual_disks_multidisks.py
Previous iso_url is not existed any more
> Fix multi_disks_test disks boot nfs pool failure

- libvirt/tests/src/virsh_cmd/domain/virsh_change_media_matrix.py
By extending timeout for this event, this will give more confidence to wait for expected event
> Fix virsh.change_media_matrix..default.eject_update case failure

- libvirt/tests/cfg/virtual_device/filesystem_device.cfg
- libvirt/tests/src/virtual_device/filesystem_device.py
Bug link: https://bugzilla.redhat.com/show_bug.cgi?id=1940276
- RHEL-281745
Check virtiofsd process exit before 'virsh destroy' cmd return.
> filesystem_device: Add case for BZ#1940276

- libvirt/tests/src/virsh_cmd/nodedev/crypto_nodedev_create_destroy.py
We found that due to performance issues with older mdevctl versions
the test might fail because it takes libvirt longer to identify the
ap_matrix device.
In order to avoid code to become more complex add a note about
pre-conditions for anybody who might run into this.
> nodedev-create-destroy: add comment about precondition

- libvirt/tests/src/sriov/sriov_managed.py
- libvirt/tests/src/sriov/sriov_net_failover.py
- libvirt/tests/src/virsh_cmd/domain/virsh_detach_device.py
- libvirt/tests/src/virsh_cmd/domain/virsh_detach_device_alias.py
- libvirt/tests/src/virtual_disks/virtual_disks_ceph.py
- libvirt/tests/src/virtual_disks/virtual_disks_encryption.py
- libvirt/tests/src/virtual_disks/virtual_disks_gluster.py
- libvirt/tests/src/virtual_disks/virtual_disks_metadatacache.py
- libvirt/tests/src/virtual_disks/virtual_disks_multidisks.py
- libvirt/tests/src/virtual_disks/virtual_disks_nbd.py
- libvirt/tests/src/virtual_disks/virtual_disks_scsi3_persistent_reservation.py
- libvirt/tests/src/virtual_disks/virtual_disks_usb.py
- libvirt/tests/src/virtual_disks/virtual_disks_vhostuser.py
- libvirt/tests/src/virtual_network/iface_target.py
- libvirt/tests/src/virtual_network/virtual_network_multivms.py
Update the parameter name from "wait_remove_event" to "wait for event".
Depends on https://github.com/avocado-framework/avocado-vt/pull/3225.
> Update one parameter name of func detach_device()

- libvirt/tests/src/nwfilter/nwfilter_binding_list.py
Unplugging a PCI device properly requires cooperation from the guest OS.
If the guest OS isn't running yet, the unplug won't complete, so qemu
(and libvirt) still show the device as plugged into the guest. Add
serail_login() to make sure guest is running when detach interface.
> Fix the detach interface fail issue

- libvirt/tests/cfg/numa/numa_nodeset.cfg
- libvirt/tests/src/numa/numa_nodeset.py
Test case comes from: report invalid Host nodeset for memnode -
bug 1186175. The test verifies the error message, when invalid
nodeset is used.
- Description of the case:
report invalid Host nodeset for memnode - bug 1186175
- case IDs:
RHEL7-16419
<pre>avocado run --vt-type libvirt --vt-machine-type q35 numa_invalid_nodeset
<font color="#2A7BDE">JOB ID     : …
> NUMA:Add case for NUMA numatune with invalid nodeset.

- libvirt/tests/cfg/sriov/sriov_vf_pool.cfg
- libvirt/tests/src/sriov/sriov_vf_pool.py
1. RHEL7-18531 - Check the number of connections on hostdev
network during hotplug / unplug
2. RHEL7-98468 - Check the the connections of macvtap network
with VF
**depends on** https://github.com/avocado-framework/avocado-vt/pull/3207
```
(1/4) type_specific.io-github-autotest-libvirt.sriov.vf_pool.active.at_dt.macvtap_passthrough: PASS (38.85 s)
(2/4) type_specific.io-github-autotest-libvirt.sriov.vf_pool.active.connection.macvtap_passthrough: PASS (38.20 s)
(3/4) type_specific.io-github-autotest-libvirt.sriov.vf_pool.active.connection.hostdev: PASS (40.73 s)
(4/4) type_specific.io-github-autotest-libvirt.sriov.vf_pool.inactive.at_dt.macvtap_passthrough: PASS (46.89 s)
```
> sriov: Add 2 cases about network connections

- libvirt/tests/cfg/virsh_cmd/domain/virsh_cpu_xml.cfg
computing baseline hypervisor CPU is not supported for arch ppc64le
> Remove hypervisor_cpu_baseline cases from pseries tests

- libvirt/tests/cfg/cpu/vm_features.cfg
- libvirt/tests/src/cpu/vm_features.py
Installing a package via an external url causes unstatblity sometimes.
We recommend to use local repo to install those packages.
> vm_features: install cpuid

- libvirt/tests/src/virsh_cmd/monitor/virsh_domstate.py
Extend the wait time for test as it need more time to complete
the kill action.
> virsh_domstate: Extend the wait time for kill action

- libvirt/tests/src/nwfilter/nwfilter_update_lock.py
1.No need to start libvirtd in foreground using libvirtd started by systemctl instead;
2.Libvirtd and virtlogd need to start in the same method;
e.g
> Delete starting libvirtd in foreground

- libvirt/tests/cfg/virsh_cmd/network/virsh_net_start.cfg
- libvirt/tests/src/virsh_cmd/network/virsh_net_start.py
It needs 'network' driver instead of 'QEMU' when modular daemons
are enabled.
https://github.com/avocado-framework/avocado-vt/pull/3266
_modular daemons:_
```
JOB ID     : 95e46068065edf8b35abf1a0f2754a3cc251fcc9
JOB LOG    : /root/avocado/job-results/job-2021-11-03T21.01-95e4606/job.log
(01/14) type_specific.io-github-autotest-libvirt.virsh.net_start.normal_test.non_acl.valid_netname: PASS (6.85 s)
(02/14) type_specific.io-github-autotest-libvirt.virsh.net_start.normal_test.non_acl.valid_netuuid: PASS (6.84 s)
(03/14) type_specific.io-github-autotest-libvirt.virsh.net_start.normal_test.acl_test.valid_netname: PASS (8.90 s)
(04/14) type_specific.io-github-autotest-libvirt.virsh.net_start.normal_test.acl_test.v …
```
> net_start: Fix polkit setting

- libvirt/tests/cfg/virtual_network/iface_update.cfg
- libvirt/tests/src/virtual_network/iface_update.py
If interface type='network' connected to a direct type network,
the live xml will changed to interface type='direct', then do
interface update, it should not reject the update. It is to automate
RHEL-190487. related bug: 1887775.
> Update the interface device with different iface type

- v2v/tests/cfg/convert_vm_to_libvirt.cfg
- v2v/tests/cfg/convert_vm_to_ovirt.cfg
Add the latest windows version: win2022 into auto testing.
> v2v: add windows2022 to matrix of auto testing

- libvirt/tests/cfg/virsh_cmd/filter/virsh_nwfilter_define.cfg
- libvirt/tests/cfg/virsh_cmd/filter/virsh_nwfilter_undefine.cfg
- libvirt/tests/cfg/virsh_cmd/network/virsh_net_define_undefine.cfg
- libvirt/tests/cfg/virsh_cmd/network/virsh_net_destroy.cfg
- libvirt/tests/cfg/virsh_cmd/pool/virsh_find_storage_pool_sources.cfg
- libvirt/tests/cfg/virsh_cmd/pool/virsh_pool_acl.cfg
- libvirt/tests/cfg/virsh_cmd/secret/virsh_secret_define_undefine.cfg
- libvirt/tests/cfg/virsh_cmd/volume/virsh_vol_clone_wipe.cfg
- libvirt/tests/cfg/virsh_cmd/volume/virsh_vol_create.cfg
- libvirt/tests/cfg/virsh_cmd/volume/virsh_vol_download_upload.cfg
- libvirt/tests/cfg/virsh_cmd/volume/virsh_vol_resize.cfg
- libvirt/tests/src/virsh_cmd/filter/virsh_nwfilter_define.py
- libvirt/tests/src/virsh_cmd/filter/virsh_nwfilter_undefine.py
- libvirt/tests/src/virsh_cmd/network/virsh_net_define_undefine.py
- libvirt/tests/src/virsh_cmd/network/virsh_net_destroy.py
- libvirt/tests/src/virsh_cmd/pool/virsh_find_storage_pool_sources.py
- libvirt/tests/src/virsh_cmd/pool/virsh_pool_acl.py
- libvirt/tests/src/virsh_cmd/secret/virsh_secret_define_undefine.py
- libvirt/tests/src/virsh_cmd/volume/virsh_vol_clone_wipe.py
- libvirt/tests/src/virsh_cmd/volume/virsh_vol_create.py
- libvirt/tests/src/virsh_cmd/volume/virsh_vol_download_upload.py
- libvirt/tests/src/virsh_cmd/volume/virsh_vol_resize.py
Some tests need sub-driver instead of 'QEMU' when modular daemons
are enabled.
> Fixup acl test

- libvirt/tests/src/virsh_cmd/domain/virsh_event.py
Modify metadata-change event output per libvirt-7.10.
e.g
> virsh_event: modify metadata-change event output

- libvirt/tests/cfg/remote_access/virsh_non_root_polkit.cfg
- libvirt/tests/src/remote_access/virsh_non_root_polkit.py
New cases added to verify the polkit with virsh for non-root access via ssh or
local connection.
Signed-off-by: kvarga <kvarga@redhat.com>
-  Description of the cases:
using polkit with virsh for non-root access should work via ssh or locally
-  Case ID:
RHEL7-18311
<pre>avocado run --vt-type libvirt --vt-machine-type q35 virsh.non_root_polkit
<font color="#2A7BDE">JOB ID     : 16eb075cf24472903b06eef8034c1a1a9382fbb1</font>
<font …
> Remote Access:New case for a virsh connect polkit with a non-root user

- libvirt/tests/cfg/numa/numa_numanode_cpu_info.cfg
- libvirt/tests/src/numa/numa_numanode_cpu_info.py
Start VM with 1 numa node defined in numatune and without numanode
info in cpu when vm have hugepage settings, when the memory in
this node is not enough, VM should start failed.
- Description of the cases:
Start VM with 1 numa node defined in numatune and without numanode info in cpu when vm have hugepage settings, when the memory in this node is not enough, VM should start failed.
- Case IDs:
RHEL-171445
<pre>avocado run --vt-type libvirt --vt-machine-type q35 numa_numanode_cpu_info
No python imaging library installed. PPM image conversion to JPEG disabled. In order to enable it, please …
> NUMA: Add new test for numanode not defined in cpu info

- libvirt/tests/cfg/controller/controller_functional.cfg
- libvirt/tests/src/controller/controller_functional.py
libvirt support pcie_expander_bus on aarch64 since 7.7.0.
1. RHEL8 qemu doesn't support ich9 sound device on aarch64, use rng device.
2. RHEL8 qemu doesn't support host-model on aarch64, use host-passthrough.
libvirt7.6.0
```
JOB ID     : 4981e78c57a136ca54f37660ccd7e8bbc4f2fa09
JOB LOG    : /root/avocado/job-results/job-2021-10-28T23.30-4981e78/job.log
(1/3) type_specific.io-github-autotest-libvirt.controller.functional.positive_tests.pcie_expander_bus_numa: CANCEL: transient disk share is not supported on current build (6.81 s)
(2/3) type_specific.io-github-autotest-libvirt.controller.functional.positive_tests.pcie_expander_bus_busNr.default_busNr: CANCEL: transient disk share is not supported on current build (6.72 s)
(3/3) type_specific.io-github-autotest-libvirt.controller.functional. …
```
> Enable pcie_expander_bus related cases for aarch64

- libvirt/tests/cfg/virsh_cmd/nodedev/virsh_nodedev_create_destroy.cfg
- libvirt/tests/cfg/virsh_cmd/nodedev/virsh_nodedev_detach_reattach.cfg
- libvirt/tests/cfg/virsh_cmd/nodedev/virsh_nodedev_dumpxml.cfg
- libvirt/tests/cfg/virsh_cmd/nodedev/virsh_nodedev_list.cfg
- libvirt/tests/src/virsh_cmd/nodedev/virsh_nodedev_create_destroy.py
- libvirt/tests/src/virsh_cmd/nodedev/virsh_nodedev_detach_reattach.py
- libvirt/tests/src/virsh_cmd/nodedev/virsh_nodedev_dumpxml.py
- libvirt/tests/src/virsh_cmd/nodedev/virsh_nodedev_list.py
As acl setting in split daemon is different, update the cfg file and py file.
> Fix nodedev split daemon polkit setting

- libvirt/tests/cfg/cpu/vcpu_nested.cfg
- libvirt/tests/src/cpu/vcpu_nested.py
1 - Checking log is sometimes not statble. After confirming with feature
owner, this step is not required for this case. So I remove it to
make the script stabler.
2 - After libvirt packages are installed in L1, to make the default
libvirt daemons start automatically, we have 2 ways. One is rebooting
the vm, the other is to explicitly start the service names according
to different libvirt versions to judge monolithic vs. modular daemons
to use. It seems the first way is easier.
> vcpu_nested: adapt for modular daemons

- libvirt/tests/cfg/daemon/daemon_functional.cfg
- libvirt/tests/src/daemon/daemon_functional.py
1.Will run all the testcases for sub-daemons in modular daemon mode
and cancel testcases for legacy libvirtd;
2.Will run testcases for libvirtd in legacy libvirtd mode and cancel
testcases for modular daemon;
e.g
> Add testcase for all the sub-daemons starting in foreground

- libvirt/tests/cfg/remote_access/remote_with_unix.cfg
- libvirt/tests/src/remote_access/remote_access.py
This commit is a fix for remote_with_unix.negative_testing.socket_with_polkit_ro
test case, where response from the libvirt has changed with the recent version
and therefore password prompt is showing up with error message and requiring
root account instead of polkit account which is denied. This fix add root
password to pass through the login prompt and code to check for the new error
message.
Test results before the fix is applied:
<pre>avocado run --vt-type libvirt --vt-machine-type q35 virsh.remote_with_unix.negative_testing.socket_with_polkit_ro
No python …
> remote_access:Fix unix negative test for polkit ro

- libvirt/tests/cfg/virtual_interface/interface_hotplug.cfg
- libvirt/tests/src/virtual_interface/interface_hotplug.py
- provider/interface/interface_base.py
- provider/interface/vdpa_base.py
This PR adds:
RHEL-196261: hotplug/unplug vdpa type interface
**Depends on**: https://github.com/avocado-framework/avocado-vt/pull/3260
```
(1/2) type_specific.io-github-autotest-libvirt.interface_hotplug.vdpa.simulator: PASS (41.79 s)
(2/2) type_specific.io-github-autotest-libvirt.interface_hotplug.vdpa.mellanox: PASS (91.56 s)
```
> vDPA: Add a test to check hotplug/unplug vdpa type interface

- libvirt/tests/cfg/migration/live_migration.cfg
- libvirt/tests/src/migration/live_migration.py
RHEL7-17384 - [Migration] Do live VM migration with the minimum
available migration port occupied by other app
> live_migration: Add case about migration_port_min

- libvirt/tests/cfg/virsh_cmd/domain/virsh_cpu_baseline.cfg
- libvirt/tests/src/virsh_cmd/domain/virsh_cpu_baseline.py
Case ID: RHEL7-20178
Case Title: [cmd/cpu-baseline] Obtain cpu baseline with "--migratable"
through XML contains invtsc from "virsh capabilities"
This case requires the host has 'invtsc' feature.
This case is to test no 'invtsc' feature outputed in virsh.cpu_baseline
> virsh_cpu_baseline: new case --migratable

- libvirt/tests/src/libvirtd_start.py
1.Keep using 'libvirtd' in legacy libvirtd mode;
2.Using 'virtnetworkd' in modular daemon mode;
e.g
> Modify to start 'virtnetworkd' to do the test in the modular daemon mode

- libvirt/tests/cfg/migration/migrate_service_control.cfg
- libvirt/tests/src/migration/migrate_service_control.py
- provider/migration/migration_base.py
1. RHEL-130259 - [Migration] Kill dst qemu during Perform Phase of
live migration - p2p migration
2. RHEL7-31564 - [Migration] Kill DST libvirtd during Perform Phase
of live migration - p2p migration
3. RHEL-130061 - [Migration] Kill SRC libvirtd during Perform Phase
of live migration - p2p migration
> migrate_service_control: Add 3 cases about kill service

- libvirt/tests/src/virtual_disks/virtual_disks_gluster.py
When detach gluster disk device, device-removed may not be sent out
> Fix gluster disk device detach event issue

- libvirt/tests/src/virsh_cmd/domain/virsh_qemu_monitor_command.py
From libvirt-7.9.0, run invalid qemu_monitor_command will return 0.
For libvirt-7.9.0:
{"id":"libvirt-390","error":{"class":"CommandNotFound","desc":"The command {system_reset} has not been found"}}
0
For libvirt-7.8.0:
error: internal error: cannot parse json {system_reset}: lexical error: invalid char in json text.
{system_reset}
(right here) ------^
1
> virsh_qemu_monitor_command: Update error message

- libvirt/tests/src/virsh_cmd/domain/virsh_blockcopy.py
virsh_blockcopy.py: remove libvirtd status check to adapt to the split daemon mode
Fix error: Libvirtd service is dead
The libvirtd status check is standing alone and not dependent on other codes. It's only a check of libvirtd service. So remove it to adapt to the split daemon mode.
> virsh_blockcopy.py: remove libvirtd status check

- libvirt/tests/cfg/virtual_interface/domain_lifecycle.cfg
- libvirt/tests/src/virtual_interface/domain_lifecycle.py
- provider/interface/check_points.py
- provider/interface/vdpa_base.py
This PR adds below case:
RHEL-196259: Test vm lifecycle with vdpa type inteface
**depends on**: https://github.com/avocado-framework/avocado-vt/pull/3260
```
JOB ID     : 30c01b9a5637b79401b33ab9287d9e035af6f7fb
JOB LOG    : /root/avocado/job-results/job-2021-10-29T03.42-30c01b9/job.log
(1/2) type_specific.io-github-autotest-libvirt.iface.domain_lifecycle.vdpa.simulator: PASS (76.15 …
```
> vDPA: Add a case to test domain lifecycle

- libvirt/tests/src/numa/numa_numanode_cpu_info.py
'>' is a shell construct meaning that the command needs to be run as input to
a shell.
```
echo {} >
/sys/devices/system/node/node{}/hugepages/hugepages-2048kB/nr_hugepages
```
If we don't set shell=True, process just echo this cmd instead of
writing the nr_hugepages.
Before
```
JOB ID     : 8f1e1130ecd01b148207f3495fa50ae075ae4f4f
JOB LOG    : /root/avocado/job-results/job-2021-11-22T05.09-8f1e113/job.log
(1/1) type_specific.io-github-autotest-libvirt.numa_numanode_cpu_info.default: ERROR: Setting 900 hugepages on node 0 was unsuccessful (9.08 s)                                             
JOB TIME   : 9.78 s
```
After
```
JOB ID     : …
```
> numa_numanode_cpu_info: Run bash cmd in subshell

- libvirt/tests/src/passthrough/ap/libvirt_ap_passthrough.py
- libvirt/tests/src/virsh_cmd/nodedev/crypto_nodedev_create_destroy.py
The test didn't assign the devices back to host correctly
which caused test failure in libvirt_ap_passthrough if run
afterwards.
Restore the matrix device at tear down and add an additional
log message to help determine host state for passthrough test
if it fails again.
> crypto_nodedev_create_destroy: restore matrix device

- libvirt/tests/src/virsh_cmd/domain/virsh_cpu_stats.py
The value of the total time and the sum of user and system time
are allowed to be the same.
Test result:
` (1/1) type_specific.io-github-autotest-libvirt.virsh.cpu_stats.positive_test.option2: PASS (259.89 s)`
> cpu_stats: Correct the cpu time checking

- libvirt/tests/src/nwfilter/nwfilter_binding_dumpxml.py
- libvirt/tests/src/virsh_cmd/snapshot/virsh_snapshot_disk.py
Before
```
> virsh.snapshot_disk.no_delete.negative_test.pool_vol.fs_pool.attach_img_raw.snapshot_from_xml.disk_internal.memory_none \                                                                  
> virsh.snapshot_disk.no_delete.negative_test.pool_vol.iscsi_pool.attach_img_raw.snapshot_default.no_current                                                                                                   
JOB ID     : 78a8f43ea2e7d1b7538030f7613c3775d45d699c
JOB LOG    : /root/avocado/job-results/job-2021-11-22T03.26-78a8f43/job.log
(1/2) type_specific.io-github-autotest-libvirt.virsh.snapshot_disk.no_delete.negative_test.pool_vol.fs_pool.attach_img_raw.snapshot_from_xml.disk_internal.memory_none: ERROR: Failed to attach disk …
```
> Fix No more available PCI slot

- libvirt/tests/src/virsh_cmd/volume/virsh_vol_create.py
Add secret setting in poklit rule when action_lookup="connect_driver: storage" in split daemon mode
> virsh_vol_create.py: fix secret issue in storage volume with acl test

- libvirt/tests/src/migration/migrate_vm.py
Fix error:
UnboundLocalError: local variable 'uri' referenced before assignment
> migrate_vm: Fix variable 'uri' reference issue

- libvirt/tests/cfg/virsh_cmd/domain/virsh_event.cfg
- libvirt/tests/src/virsh_cmd/domain/virsh_event.py
Lifecycle event "Stopped Failed" if kill domain qemu process.
> virsh_event: Stopped failed event if kill qemu

- libvirt/tests/cfg/migration/live_migration.cfg
- libvirt/tests/src/migration/live_migration.py
RHEL7-17410 - [Migration][domjobabort] Abort migration in
PerformPhase on source host and migrate again - non-p2p migration
> live_migration: Add case about abort migration

- libvirt/tests/cfg/virsh_cmd/network/virsh_net_update.cfg
- libvirt/tests/src/virsh_cmd/network/virsh_net_update.py
Expecting fail when add ip-dhcp-range on nonexist index.
e.g
> net_update: add ip-dhcp-range on nonexist index

- libvirt/tests/cfg/migration/migrate_with_various_hostname.cfg
- libvirt/tests/src/migration/migrate_with_various_hostname.py
1. [RHEL-123618] - [Migration] Do live VM migration - source and
dest host with hostname "localhost.localdomain"
2. [RHEL-123620] - [Migration] Do live VM migration - source and
dest with FQDN hostname(with "." in hostname)
3. [RHEL-123619] - [Migration] Do live VM migration - source and
dest host with short hostname(no "." in hostname)
> migrate_with_various_host_env: Add 3 cases about set hostname

- libvirt/tests/cfg/virtual_network/iface_network.cfg
- libvirt/tests/src/virtual_network/iface_network.py
Vm with direct type bridge mode interface with vlan tag will start
fail.
e.g
> iface_network: direct br iface with vlan

- v2v/tests/src/function_test_esx.py
If os_directory was set in cfg file, the directory would not be
cleaned up correctly. This patch fixes the issue.
> v2v: cleanup the os_directory content at the end

- requirements-travis.txt
Inspekt check fails with the latest pylint, so fix to a stable
version as a workaround.
> Fix up inspekt check failure

- libvirt/tests/cfg/bios/virsh_boot.cfg
There're some change in error info for virsh.boot.by_ovmf.negative_test.non_released_version. So update it.
> virsh_boot.cfg: update error info of negative case

- libvirt/tests/cfg/virsh_cmd/domain/virsh_domjobinfo.cfg
- libvirt/tests/src/virsh_cmd/domain/virsh_domjobinfo.py
Test --keep-completed option for completed domjobinfo, take live dump
action as a demo.
> virsh_domjobinfo: test --keep-completed option

- libvirt/tests/src/virtual_device/tpm_device.py
Expose error details when test suite failed, since it has more
than one tests.
> tpm_device: Expose error when test suite failed

- libvirt/tests/cfg/remote_access/remote_tls_multiple_certs.cfg
- libvirt/tests/src/remote_access/remote_tls_multiple_certs.py
- spell.ignore
This commit is adding the tests for chained CA certificates for remote TLS
connection.
-Description of the cases:
libvirtd can succeed to verify chained CA certs when the .pem file contains more than two certs
- Case ID:
RHEL7-18278
<pre>vocado run --vt-type libvirt --vt-machine-type q35 virsh.remote_tls_multiple_certs
<font color="#2A7BDE">JOB ID     : …
> remote_access:Add new test for TLS with multiple certs

- libvirt/tests/src/numa/numa_memory_spread.py
This test uses memhog to cost memory. The guest may be killed by host
OS due to OOM. So we need to check whether the guest is alive during
memhog running. Otherwise the cmd doesn't return when OOM and test will be
aborted by TIMEOUT exception.
Run a thread to run guest mmehog and keep checking whether guest is alive.
If guest died, that means memory doesn't spread across multiple nodes, test fail.
If cmd timeout, just raise an error. Increase guest memory or timeout
may fix this error.
Before: When guest crashed due to OOM, the session.cmd keep waiting memhog cmd return until timeout.
```
JOB ID     : 63217680ce14bb36d882fb693d6c7dce9329a30d
JOB LOG    : /root/avocado/job-results/job-2021-11-25T05.21-6321768/job.log
(1/1) …
```
> numa_memory_spread: Fix session exception handling

- libvirt/tests/src/virsh_cmd/snapshot/virsh_snapshot_disk.py
Before
```
l.disk_external.sys_checkpoint.default.memory_external                                                                                     
JOB ID     : c1e8b0a668ba64476707d5fde48ad6e8aa9f3e62                                                                                                                                         
JOB LOG    : /root/avocado/job-results/job-2021-11-30T04.14-c1e8b0a/job.log                                                                          
(1/1) type_specific.io-github-autotest-libvirt.virsh.snapshot_disk.no_delete.positive_test.no_pool.attach_img_raw.snapshot_from_xml.disk_external.sys_checkpoint.default.memory_external: FAI
L: Failed to create snapshot. Error:error: XML error: memory state …
```
> Start guest after reset guest PCI

- libvirt/tests/cfg/migration/migrate_vm.cfg
To create a backing file, the option '-F' is required, so update
accordingly.
Test result:
(1/1) type_specific.io-github-autotest-libvirt.virsh.migrate_vm.negative_testing.live_storage_migration.backing_file_with_copy_storage_inc.without_postcopy: PASS (98.56 s)
> migrate_vm: Add '-F' option to qemu-img create command

- libvirt/tests/src/controller/controller_functional.py
On ppc, there is only pci-root model, not pcie-root-port model.
> controller_functional: Fix model for ppc

- libvirt/tests/src/virsh_cmd/domain/virsh_event.py
There're still 2 areas of metadata-change event output not updated.
Fix them this time.
e.g
> virsh_event: metadata-change event output fix

- libvirt/tests/cfg/virtual_disks/virtual_disks_dasd.cfg
- libvirt/tests/src/virtual_disks/virtual_disks_dasd.py
- provider/vfio/ccw.py
Add test case to confirm dasd partition tables can be
read when using virtio-blk.
> virtual_disks_dasd: add test case

- libvirt/tests/src/virsh_cmd/domain/virsh_blockcopy.py
As the old method will ignore the cmd err check so when it happened it will timeout
```
(1/1) type_specific.io-github-autotest-libvirt.virsh.blockcopy.positive_test.non_acl.block_disk.disk_t.default.block_type.blockdev.no_shallow.no_option: PASS (200.64 s)
JOB TIME   : 201.52 s
```
> Add cmd status check for blockcopy

- libvirt/tests/cfg/virsh_cmd/domain/virsh_detach_serial_device_alias.cfg
- libvirt/tests/src/virsh_cmd/domain/virsh_detach_serial_device_alias.py
In avocado-vt machine.cfg, there is another serial_type definition for pseries which is used
by tp-qemu and not suitable for libvirt test. So this is to rename the variable to avoid
naming overlap.
> virsh_detach_serial_device_alias: fix serial type ppc

- libvirt/tests/cfg/migration/migrate_options_shared.cfg
Before
```
virsh.migrate_options_shared.positive_test.p2p_migration.check_domstats.without_postcopy
Error Details
TestError: No migration result is returned.&#10;
virsh.migrate_options_shared.positive_test.check_domjobinfo.without_postcopy
Error Details
Result message not found. Please check log instead.
```
After
```
virsh.migrate_options_shared.positive_test.p2p_migration.check_domstats.without_postcopy: PASS
virsh.migrate_options_shared.positive_test.check_domjobinfo.without_postcopy: PASS
```
> migrate_options_shared: Increase slow_speed for aarch64

- libvirt/tests/src/virsh_cmd/pool/virsh_pool_autostart.py
Some cases need to restart virtstoraged instead of virtqemud when
modular daemons are enabled.
_Before fix:_
_(1/1) type_specific.io-github-autotest-libvirt.virsh.pool_autostart.positive_test.uuid_option.pool_type_iscsi.ipv6_target: FAIL: Pool State isn't active as expected (53.13 s)_
_After fix:_
```
JOB LOG    : /root/avocado/job-results/job-2021-12-07T02.00-c0fa3ab/job.log
(01/34) type_specific.io-github-autotest-libvirt.virsh.pool_autostart.positive_test.name_option.pool_type_disk.source_format_dos: PASS (52.33 s)
(02/34) type_specific.io-github-autotest-libvirt.virsh.pool_autostart.positive_test.name_option.pool_type_disk.source_format_dvh: PASS (52.67 s)
(03/34) …
```
> virsh_pool_autostart: Restart virtstoraged in modular deamons mode

- libvirt/tests/src/virsh_cmd/volume/virsh_vol_download_upload.py
The virsh vol-download command was failed due to a known issue
but the error message of this case was incorrect. So update to
check virsh command to report a proper error message.
Before fix:
` (1/1) type_specific.io-github-autotest-libvirt.virsh.vol_download_upload.mix_download_upload.dir_pool.sparse: ERROR: Fail to get information of /tmp/avocado_i66gkatt/download-sparse.raw:\nCommand 'qemu-img info /tmp/avocado_i66gkatt/download-sparse.raw -U' failed.\nstdout: b''\nstderr: b"qemu-img: Could not open '/tmp/avocado_i66gkatt/download-sparse.raw': Could not open '... (52.39 s)`
After fix:
` (1/1) type_specific.io-github-autotest-libvirt.virsh.vol_download_upload.mix_download_upload.dir_pool.sparse: FAIL: error: cannot receive data from volume …
> Update to check the result of virsh vol-download command

- libvirt/tests/src/daemon/daemon_functional.py
> Fix virt-admin connect uri for libvirtd daemon

- libvirt/tests/src/virtual_device/filesystem_device.py
The test uses systemd-run to start a virtiofsd process, then change
permession and selinux security context.
But if above operations failed, there is no codes to clean up the remaing
virtiofsd process.
The other tests which need to check the virtiofsd process may fail.
E.g.
```
TestFail: Expected 'cache=none,xattr,flock,no_posix_lock' was not found
in output of 'ps aux | grep virtiofsd | head -n 1'
```
Before
```
> virtual_devices.filesystem_device.positive_test.hugepages_backed.nop.externally_launched_fs_test.launched_mode \                                                                           
> virtual_devices.filesystem_device.positive_test.hugepages_backed.nop.fs_test.xattr_on.flock_on.lock_posix_off.cache_mode_none.one_fs.one_gue …
```
> filesystem_device: clean up virtiofsd

- libvirt/tests/cfg/virsh_cmd/domain/virsh_emulatorpin.cfg
The error message has changed, so update it accordingly.
Before fix:
` (1/1) type_specific.io-github-autotest-libvirt.virsh.emulatorpin.negative_testing.set_emulatorpin_parameter.running_guest.change_emulatorpin.emulatorpin_options.current.noexist.set_by_xml: FAIL: Expect should fail with one of ['cannot set CPU affinity on process.*: Invalid argument'], but failed with:\n\n\nerror: Failed to start domain 'avocado-vt-vm1'\nerror: Unable to write to '/sys/fs/cgroup/machine.slice/machine-qemu\x2d2\x2davocado\x2dvt\x2dvm1.... (31.56 s)`
After the fix:
```
JOB LOG    : /root/avocado/job-results/job-2021-12-08T02.10-a9caa74/job.log
(1/3) type_specific.io-github-autotest-libvirt.virsh.emulatorpin.negative_testing.set_emulatorpin_parameter.running_gu …
```
> emulatorpin: Update the error message

- libvirt/tests/cfg/svirt/dac_vm_per_image_start.cfg
- libvirt/tests/src/svirt/dac_vm_per_image_start.py
'virt_use_nfs' should be on when libvirt use nfs.
> dac_vm_per_image_start: fix virt_use_nfs missing

- libvirt/tests/src/virsh_cmd/domain/virsh_change_media_matrix.py
pre_vm_state_paused make the guest paused. But vm.is_alive() judge paused guest
as alive. So pre_vm_state_paused cased failed due to TIMEOUT when we try to
login it.
Before
```
JOB ID     : 04a32029b857be947788560252fb647d93263021                                                                                                                                        
JOB LOG    : /root/avocado/job-results/job-2021-12-09T02.48-04a3202/job.log
(1/1) type_specific.io-github-autotest-libvirt.virsh.change_media_matrix.pre_vm_state_paused.cdrom_test.config.action_twice.force.insert_update: ERROR: Login timeout expired    (output: 'ex
ceeded 240 s timeout, last failure: Could not verify DHCP lease: 52:54:00:43:50:16 --> 192.168.122.87') (449.08 s) …
```
> virsh_change_media_matrix: Fix pre_vm_state_paused TIMEOUT issue

- libvirt/tests/cfg/virtual_disks/virtual_disks_rotation_rate.cfg
- libvirt/tests/cfg/virtual_disks/virtual_disks_vhostuser.cfg
- scsi bus does not support hotplug on ppc
- vhostuser does not support on ppc
> virtual_disks_vhostuser: skip cases on ppc

- libvirt/tests/cfg/remote_access/remote_with_unix.cfg
Add root password to pass through the login prompt.
> remote_access: Add root password to fix type error

- libvirt/tests/cfg/virsh_cmd/nodedev/virsh_nodedev_detach_reattach.cfg
- libvirt/tests/src/virsh_cmd/nodedev/virsh_nodedev_detach_reattach.py
Update 2 items: 1) update the polkit rule with QEMU and nodedev both;
2) update the logic of pci_device_address() to find a interface without
any connection. It is more safe to detach an interface which is not in use.
Signed-off-by: ‘Yalan <yalzhang@redhat.com>
> Fix the polkit rule set under split daemon mode

- libvirt/tests/src/virtual_device/filesystem_device.py
Before
```
JOB ID     : 0d4c065e312bd03e3561b1b32d813f38111f19d4
JOB LOG    : /root/avocado/job-results/job-2021-12-16T04.19-0d4c065/job.log
(1/1) type_specific.io-github-autotest-libvirt.virtual_devices.filesystem_device.positive_test.hugepages_backed.nop.externally_launched_fs_test.launched_mode: FAIL: Command 'chown qemu:qemu /var/tmp/vm001.socket' failed.\nstdout: b''\nstderr: b"chown: cannot access '/var/tmp/vm001.socket': No such file or directory\n"\nadditional_info: None (39.83 s)                          
JOB TIME   : 41.44 s
```
After
```
JOB ID     : f0cf43d0ede66fc845f364000fa27b4ed28b59b3
JOB LOG    : …
```
> [minor fix] filesystem_device: fix "chown: cannot access '/var/tmp/vm001.socket

- libvirt/tests/src/sriov/sriov_nodedev.py
The VF's mac address may be changed in some drivers.
Checked with feature owner, it's not a checkpoint of this case,
so update to log a message as error level.
` (1/1) type_specific.io-github-autotest-libvirt.sriov_nodedev.vf: FAIL: MAC address changed from '9a:4a:27:b3:ad:b3' to '2a:78:eb:1e:b8:cc' after reattaching vf. (20.85 s)`
After the fix:
` (1/1) type_specific.io-github-autotest-libvirt.sriov_nodedev.vf: PASS (24.18 s)`
> sriov_nodedev: Ignore mac address change of VF

- libvirt/tests/src/virt_admin/monitor/virt_admin_srv_threadpool_info.py
1)Now, we need to specify daemon name, otherwise utils_libvirtd.Libvirtd()
will connect to virtqemud by default. In this script, there is
other server called 'admin'. It is not suitable to use the server_name
as daemon_name. Hence, we need to specify the daemon name
2)Remove VirtadminPersistent, as under split daemon, connection
will be disconnected when stop/restart daemon
> [virt_admin]Fix some issues according to current change

- libvirt/tests/cfg/virt_admin/management/virt_admin_client_disconnect.cfg
- libvirt/tests/cfg/virt_admin/management/virt_admin_server_clients_set.cfg
- libvirt/tests/cfg/virt_admin/monitor/virt_admin_srv_clients_info.cfg
- libvirt/tests/src/virt_admin/management/virt_admin_client_disconnect.py
- libvirt/tests/src/virt_admin/management/virt_admin_server_clients_set.py
- libvirt/tests/src/virt_admin/monitor/virt_admin_srv_clients_info.py
1)Now, we can not connect to virtproxyd by ssh connection,
the original ssh connection is acctually connected to virtqemud.
Hence, now we can only connect to virtproxyd by tls/tcp.
2)Now, we need to specify server_name, otherwise utils_libvirtd.Libvirtd()
will connect to virtqemud by default
3)Remove VirtadminPersistent, as under split daemon, connection
will be disconnected when stop/restart daemon
> [virt_admin]Fix some issues about split daemon changes

- libvirt/tests/cfg/virtual_device/filesystem_device.cfg
Use avocado-vt's env_process to make sure hugepages are
supported for kvm on s390x.
Details s. avocado-vt/virttest/utils_kernel_module.
> filesystem_device: reload kvm for hugepages on s390x

- libvirt/tests/cfg/virsh_cmd/domain/virsh_event.cfg
- libvirt/tests/src/virsh_cmd/domain/virsh_event.py
Add "(Un)Defined Renamed" domain lifecycle event.
e.g
> virsh_event: domrename lifecycle event

- provider/v2v_vmcheck_helper.py
See bz#1961107.
Because the spice is depracated on rhel9, v2v also did some
changes to adapte that, and tp-libvirt as well.
> v2v: adapte the changes about default graphic and video type

- libvirt/tests/cfg/virtual_device/filesystem_device.cfg
- libvirt/tests/src/virtual_device/filesystem_device.py
Test cases: RHEL-285215 RHEL-285255 RHEL-286256 RHEL-286733
Bug: 1897708
Test result:
No python imaging library installed. Screendump and Windows guest BSOD detection are disabled. In order to enable it, please install python-imaging or the equivalent for your dis
tro.
JOB ID     : 5a856d58ed721159f6fe0b18768cff7191c080b1
JOB LOG    : /root/avocado/job-results/job-2021-11-28T21.39-5a856d5/job.log
(001/260) type_specific.io-github-autotest-libvirt.virtual_devices.filesystem_device.positive_test.hugepages_backed.nop.externally_launched_fs_test.launched_mode: PASS (28.02 s)
(002/260) …
> [filesystem_device]Add the cases of hotplug_unplug filesystem device

- libvirt/tests/cfg/serial/serial_pty_log.cfg
- libvirt/tests/src/serial/serial_pty_log.py
Before
```
JOB ID     : b8840ab359bab88704856ba104411807a835822a
JOB LOG    : /root/avocado/job-results/job-2021-12-15T01.50-b8840ab/job.log
(1/2) type_specific.io-github-autotest-libvirt.serial.pty.log.file: ERROR: Unexpected error: Failed to find the vm login prompt from /var/lib/libvirt/console1.log (86.22 s)                
(2/2) type_specific.io-github-autotest-libvirt.serial.pty.log.logd: ERROR: Unexpected error: Failed to find the vm login prompt from /var/lib/libvirt/console1.log (86.05 s)                
RESULTS    : PASS 0 | ERROR 2 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 173.87 s
```
After
aarch64:
```
JOB ID     : 9df4b9c30fcd96a1d67fe7355cba79c5b40114b7
JOB LOG    : …
```
> serial_pty_log: Adjust test for aarch64

- provider/v2v_vmcheck_helper.py
From the comment, the machine type will not changed to Q35 by rhv.
https://bugzilla.redhat.com/show_bug.cgi?id=1983610#c8
> v2v: fix expected machine type error when hypervisor is kvm

- libvirt/tests/src/virtual_device/watchdog.py
The used qemu interface for watchdog devices has changed from
version 6.1 to 6.2.
Compare
6.1: -device diag288,id=watchdog0 -watchdog-action inject-nmi
6.2: -device {"driver":"diag288","id":"watchdog0"} -watchdog-action
inject-nmi
Therefore, tests failed with qemu 6.2 because they checked the qemu
cmdline according to 6.1 interface.
Update the test code to only check if the name is listed. This should
sufficient, esp. considering that the actual actions are tested later
on. The variable 'watchdog_device' is only used for the cmdline check.
> watchdog: relax qemu cmdline check

- libvirt/tests/src/virtual_device/input_devices.py
The used qemu interface for devices has changed from version 6.1 to 6.2.
Tests will failed with qemu 6.2 during qemu commandline check.
Update the test code to allow for both 6.1 and 6.2 API.
> input_devices: relax qemu cmdline check

- libvirt/tests/cfg/virtual_network/mtu.cfg
The mtu '6000' or '4096' both can set successfully on x86 systems.
But on big endian systems, '4096' is judged as invalid as one kernel
bug 2026234. Update this test parameter to '4096' to cover this bug.
> Update mtu 4096

- libvirt/tests/src/virtual_device/tpm_device.py
The used qemu interface for devices has changed from version 6.1 to 6.2.
Update the test code to allow for both 6.1 and 6.2 API.
e.g
> tpm_device: relax qemu cmdline check

- libvirt/tests/src/libvirt_rng.py
The used qemu interface for devices has changed from version 6.1 to 6.2.
Update the test code to allow for both 6.1 and 6.2 API.
e.g
> libvirt_rng: relax qemu cmdline check

- libvirt/tests/cfg/virtual_interface/connectivity_check.cfg
- libvirt/tests/src/virtual_interface/connectivity_check.py
- provider/interface/interface_base.py
This PR adds:
RHEL-284762 - network connectivity check for vdpa type interface
```
JOB ID     : 5f7d364cab86ad72b8e4f052b80a5e6ac9947b50
JOB LOG    : /root/avocado/job-results/job-2021-11-29T01.12-5f7d364/job.log
(1/2) type_specific.io-github-autotest-libvirt.iface.connectivity_check.vdpa.simulator: PASS (30.19 s)
(2/2) type_specific.io-github-autotest-libvirt.iface.connectivity_check.vdpa.mellanox: PASS (71.37 s)
JOB TIME   : 103.03 s
```
> vdpa: Add a case to check network connectivity

- libvirt/tests/cfg/cpu/vcpu_misc.cfg
- libvirt/tests/src/cpu/vcpu_misc.py
- spell.ignore
* Add new case for RHEL7-17959: Check domain cpu xm is not updated after Managedsave and restore
* **Test results** : 
/usr/local/bin/avocado run --vt-type libvirt --vt-machine-type q35 vcpu_misc.positive_test.managedsave_restore --vt-connect-uri qemu:///system
JOB ID     : 94b232838f0a0d7dd1b54c65c300621f14bbf192
JOB LOG    : /root/avocado/job-results/job-2021-12-15T15.10-94b2328/job.log
(1/1) type_specific.io-github-autotest-libvirt.vcpu_misc.positive_test.managedsave_restore: PASS (4.64 s)
JOB TIME   : 5.07 s
> vcpu_misc: Check cpu xml after managedsave and restore 

- libvirt/tests/src/virtual_device/filesystem_device.py
```
(1/6) type_specific.io-github-autotest-libvirt.virtual_devices.filesystem_device.positive_test.hugepages_backed.hotplug_unplug.detach_device_alias.fs_test.xattr_on.flock_on.lock_posix_on.cache_mode_none.multiple_fs.one_guest: PASS (74.51 s)
(2/6) type_specific.io-github-autotest-libvirt.virtual_devices.filesystem_device.positive_test.hugepages_backed.hotplug_unplug.detach_device.fs_test.xattr_on.flock_on.lock_posix_on.cache_mode_none.multiple_fs.one_guest: PASS (82.01 s)
(3/6) type_specific.io-github-autotest-libvirt.virtual_devices.filesystem_device.positive_test.file_backed.hotplug_unplug.detach_device_alias.fs_test.xattr_on.flock_on.lock_posix_on.cache_mode_none.multiple_fs.one_guest: PASS (72.22 s)
(4/6) …
```
> Fix No more available PCI slots for virtual devices

- libvirt/tests/cfg/virsh_cmd/domain/virsh_event.cfg
- libvirt/tests/src/virsh_cmd/domain/virsh_event.py
- libvirt/tests/src/virtual_device/watchdog.py
Depends on https://github.com/avocado-framework/avocado-vt/pull/3309
1. Make sure watchdog is available
Move logic for module load to avocado-vt
2. Memory hot-(un)-plug not available, don't run
3. Use SCSI controller for cdrom
> virsh_event: fix test cases for s390x

- libvirt/tests/src/virsh_cmd/domain/virsh_managedsave.py
Previous timeout 5 seconds may not be enough in extreme case
> Fix managesave multi_guests case failure

- libvirt/tests/cfg/virtual_interface/hotplug_mem.cfg
- libvirt/tests/src/virtual_interface/hotplug_mem.py
This PR adds:
RHEL-283024 - hotplug memory with vdpa type interface
```
(1/6) type_specific.io-github-autotest-libvirt.iface.hotplug_mem.at_memory_to_vm_with_iface.vdpa.simulator: PASS (27.75 s)
(2/6) type_specific.io-github-autotest-libvirt.iface.hotplug_mem.at_memory_to_vm_with_iface.vdpa.mellanox: PASS (51.62 s)
(3/6) type_specific.io-github-autotest-libvirt.iface.hotplug_mem.at_memory_to_vm_with_iface_and_locked_mem.vdpa.simulator: PASS (27.61 s)
(4/6) type_specific.io-github-autotest-libvirt.iface.hotplug_mem.at_memory_to_vm_with_iface_and_locked_mem.vdpa.mellanox: PASS (51.06 s)
(5/6) type_specific.io-github-autotest-libvirt.iface.hotplug_mem.at_iface_and_memory.vdpa.simulator: PASS (43.55 s)
(6/6) …
```
> vDPA: Add a case to test memory hotplug

- libvirt/tests/cfg/migration/migrate_gluster.cfg
- libvirt/tests/src/migration/migrate_gluster.py
Don't support driver gluster in new version of libvirt, so update
disk type from 'network' to 'file'.
> migrate_gluster: Update disk type

- libvirt/tests/src/virtual_disks/virtual_disks_multidisks.py
After libvirt 7.9.0 version and afterwards, qemu wwn output is changed to decimal
instead of hex
> Fix wwn cases failure due to qemu output format change for json

- libvirt/tests/src/virtual_disks/virtual_disks_multipath.py
Allow time to enable multipathd alive after restart
> Fix fail to get SG_IO device issue

- libvirt/tests/src/virtual_device/sound_device.py
Test all pass on old and new qemu-kvm version. Remove AC97 test as not supported
```
(2/7) type_specific.io-github-autotest-libvirt.virtual_devices.sound_device.positive_test.sound_model_ich6.no_codec_type: PASS (8.72 s)
(3/7) type_specific.io-github-autotest-libvirt.virtual_devices.sound_device.positive_test.sound_model_ich6.codec_type_duplex: PASS (15.12 s)
(4/7) type_specific.io-github-autotest-libvirt.virtual_devices.sound_device.positive_test.sound_model_ich6.codec_type_micro: PASS (13.95 s)
(5/7) type_specific.io-github-autotest-libvirt.virtual_devices.sound_device.positive_test.sound_model_ich9.no_codec_type: PASS (14.55 s)
(6/7) type_specific.io-github-autotest-libvirt.virtual_devices.sound_device.positive_test.sound_model_ich9.codec_t …
```
> Fix qemu-cmd-line issue for sound device

- libvirt/tests/src/virtual_network/iface_network.py
VM use "/usr/share/seabios/bios-256k.bin" both on rhel 8&9.
Correct the path of the loader.
> Update the path of the loader

- libvirt/tests/src/cpu/diagnose_data.py
The diag 318 might not be available in some older kernels.
Handle that situation and improve the log.
> diagnose_data: improve failure message

- libvirt/tests/cfg/memory/allocpages.cfg
- libvirt/tests/src/memory/allocpages.py
Depends on: https://github.com/avocado-framework/avocado-vt/pull/3289
Add test caste to set huge pages via 'virsh' command.
> memory/allocpages: test huge pages can be allocated on s390x

- libvirt/tests/cfg/virsh_cmd/domain/virsh_undefine.cfg
aarch64 requires '--nvram' option to undefine guest and that conflicts with
no_option. So skip this test for aarch64
> [minor fix] virsh_undefine: skip no_option test for aarch64

- libvirt/tests/src/cpu/iothread.py
It reports an error - "Failed to detach diskerror: internal error:
unable to execute QEMU command 'device_del': Hot-unplug failed:
guest is busy (power indicator blinking)", if a disk is detached
shortly after attaching it. So update to wait for disk to attach
correctly.
` (1/1) type_specific.io-github-autotest-libvirt.cpu.iothread.positive_test.disk_attach: PASS (94.96 s)`
> iothread: Fix detach disk error

- libvirt/tests/src/virtual_device/video_devices.py
Test pass on both qemu-kvm version, remove the qxl test as it is not supported
```
(01/12) type_specific.io-github-autotest-libvirt.virtual_devices.video_devices.positive_test.primary_video.virtio.no_secondary_video.model_test.with_packed_on: PASS (9.91 s)
(02/12) type_specific.io-github-autotest-libvirt.virtual_devices.video_devices.positive_test.primary_video.virtio.no_secondary_video.model_test.default: PASS (15.19 s)
(03/12) type_specific.io-github-autotest-libvirt.virtual_devices.video_devices.positive_test.primary_video.virtio.no_secondary_video.heads_test.default_heads: PASS (15.92 s)
(04/12) type_specific.io-github-autotest-libvirt.virtual_devices.video_devices.positive_test.primary_video.virtio.no_secondary_video.heads_test.specified_ …
```
> Fix video devices qemu cmd check failure

- libvirt/tests/cfg/virsh_cmd/domain/virsh_setmem.cfg
- libvirt/tests/src/virsh_cmd/domain/virsh_setmem.py
Pass on both old and new qemu-kvm package
```
(1/1) type_specific.io-github-autotest-libvirt.virsh.setmem.memballoon_option.with_packed_on: PASS (60.79 s)
JOB TIME   : 61.48 s
(1/1) type_specific.io-github-autotest-libvirt.virsh.setmem.memballoon_option.with_packed_on: PASS (60.74 s)
JOB TIME   : 61.46 s
```
> Fix the setmem case qemu-cmd-line match error

- libvirt/tests/cfg/memory/memory_misc.cfg
- libvirt/tests/src/memory/memory_misc.py
2 qemu-kvm version results all pass
```
(1/1) type_specific.io-github-autotest-libvirt.memory_misc.dimm.multiop: PASS (11.28 s)
JOB TIME   : 12.01 s
(1/1) type_specific.io-github-autotest-libvirt.memory_misc.dimm.multiop: PASS (11.02 s)
JOB TIME   : 11.71 s
```
> fix qemu cmd line check failure for memory_misc

- libvirt/tests/cfg/bios/boot_integration.cfg
No bios.bin file in new seabios-bin package. So update to use
bios-256k.bin.
> boot_integration: Update seabios file

- libvirt/tests/src/virsh_cmd/domain/virsh_event.py
Fix following error:
Failed to detach diskerror: internal error: unable to execute
QEMU command 'device_del': Hot-unplug failed: guest is busy
(power indicator blinking)
> virsh_event: Fix detach disk error

- libvirt/tests/cfg/cpu/vcpu_feature.cfg
Update the error message to only match the name of cr8legacy.
` (1/1) type_specific.io-github-autotest-libvirt.vcpu_feature.negative_test.host_without_cr8legacy.host_passthrough.policy_require: FAIL: Expect should fail with one of ["guest CPU doesn't match specification: missing features: cr8legacy"], but failed with:\n\n\nerror: Failed to start domain 'avocado-vt-vm1'\nerror: operation failed: guest CPU doesn't match specification: missing features: hle,... (7.98 s)`
_After fix:_
` (1/1) type_specific.io-github-autotest-libvirt.vcpu_feature.negative_test.host_without_cr8legacy.host_passthrough.policy_require: PASS (8.09 s)`
> vcpu_feature: Update error message for host_without_cr8legacy

- libvirt/tests/cfg/virsh_cmd/domain/virsh_migrate_option_mix.cfg
Update the vnc password 8 characters because of BZ 1506689.
`(1/1) type_specific.io-github-autotest-libvirt.virsh.migrate_option_mix.persistent.no_persistent_xml.xml.no_dname.undefinesource.src_vm_running.src_vm_persistent.graphic_passwd.p2p.precopy.live: ERROR: Failed to define avocado-vt-vm1 for reason:\nerror: Failed to define domain from /tmp/xml_utils_temp_nag1lth8.xml\nerror: unsupported configuration: VNC password is 9 characters long, only 8 permitted\n (395.28 s)
`
` (1/1) type_specific.io-github-autotest-libvirt.virsh.migrate_option_mix.persistent.no_persistent_xml.xml.no_dname.undefinesource.src_vm_running.src_vm_persistent.graphic_passwd.p2p.precopy.live: PASS (340.35 s)
`
> virsh_migrate_option_mix: Update vnc pwd

- libvirt/tests/src/migration/migrate_vm.py
Fix error:
UnboundLocalError: local variable 'remote_session' referenced
before assignment
> migrate_vm: Fix variable 'remote_session' reference issue

- libvirt/tests/src/virtual_disks/virtual_disks_ccw_addr.py
Initialize ori_pid_libvirtd=None at early stage of logic
> Fix local variable 'ori_pid_libvirtd' referenced before assignment issue

- libvirt/tests/cfg/virtual_disks/virtual_disks_iothread.cfg
- libvirt/tests/src/virtual_disks/virtual_disks_iothread.py
Case ID: RHEL7-110503
Case title: [virtual disks][iothread] take actions with IOThread when attaching disk
Scenario:
- Start vm
- Attempt to attach disk with --iothread 0, ensure an error is returned
- Attach disk with --subdriver qcow2 --iothread 2
- Check iothread has been set to 2 in vm XML
- Delete an IOThread which was assigned to a disk, ensure an error is returned
- Detach the disk attached in a previous step
- Stop vm
[root@libvirt-rhel-8-6-x86-64-virtual-disk-rdu-redhat-com ~]# /usr/local/bin/avocado run --vt-type libvirt type_specific.io-github-autotest-libvirt.virtual_disks.iothread.iothread_test …
> iothread: Adding virtual disk attach & detach cases

- provider/v2v_vmcheck_helper.py
- v2v/tests/cfg/function_test_xen.cfg
- v2v/tests/src/function_test_xen.py
Add vga device into v2v helper. And remove the graphics checks in
sdl case. This is duplicate with the public checkpoint.
> v2v: adapt vga device in v2v helper

- provider/interface/check_points.py
- provider/interface/interface_base.py
- provider/interface/vdpa_base.py
- provider/migration/migration_base.py
- provider/vfio/ccw.py
Because of logging changes in Avocado, update to use avocado
namespace for logging. For details, please see avocado commit
b2459dd55.
> provider: Update to use avocado namespace for logging

- libvirt/tests/src/sriov/sriov_vf_pool.py
Update to check the connections after the interface is removed
properly.
depends on: https://github.com/avocado-framework/avocado-vt/pull/3326
_before the fix:_
` (1/1) type_specific.io-github-autotest-libvirt.sriov.vf_pool.active.connection.hostdev: FAIL: Unable to get the expected connection number. Expected: 3, Actual: 4. (67.17 s)`
_after the fix:_
```
(1/1) type_specific.io-github-autotest-libvirt.sriov.vf_pool.active.connection.hostdev: PASS (51.36 s)
(1/1) type_specific.io-github-autotest-libvirt.sriov.vf_pool.active.connection.macvtap_passthrough: PASS (47.75 s)
```
> sriov_vf_pool: Wait device_removed event for detach-interface

- libvirt/tests/src/virsh_cmd/domain/virsh_attach_detach_interface.py
The function detach_interface has been updated to use wait_for_event
to check the event, so update the code accordingly.
depends on https://github.com/avocado-framework/avocado-vt/pull/3326
> detach_interface: Replace wait_remove_event to wait_for_event

- libvirt/tests/cfg/libvirt_rng.cfg
- libvirt/tests/src/libvirt_rng.py
The guest kernel selects per default an rng device based
on the available devices' priorities.
On s390x, guest kernels will choose the s390-trng device
available through the CPU feature msa 7 and selected, ref.
https://github.com/torvalds/linux/commit/d041315ef75cf52df19613f56a2da2c5911c163c
This will make tests fail with message
"Failed to check rng file on guest"
Add a config switch to force usage of the virtio rng device.
The default is not to force, ie. the current behavior isn't changed
for other architectures.
> libvirt_rng: add config to force virtio device usage

- libvirt/tests/src/virsh_cmd/domain/virsh_blockcommit.py
- libvirt/tests/src/virsh_cmd/domain/virsh_blockpull.py
If the case does not finish normally for some reasons(bug or
cancelled by user), the rbd image might unexpectedly remain in
the ceph server. To avoid using too many quotas, update to name
the image with distribution details.
Case failed due to a known issue, but the image name is updated as expected.
```
[root@libvirtceph ~]# rbd ls blockcommit-pool    
rbd_rhel_8_<release>_x86_64.img                   <-----the img exists before a case is executed, <release> is release version.
[root@libvirtceph ~]# rbd ls blockcommit-pool      <---- the image is deleted and recreated during the case execution
[root@libvirtceph ~]# rbd ls blockcommit-pool
rbd_rhel_8_<release>_x86_64.img
```
> blockcommit_blockpull: Rename rbd image name

- libvirt/tests/cfg/numa/numa_memory_migrate.cfg
- libvirt/tests/cfg/numa/numa_memory_spread.cfg
- libvirt/tests/cfg/virsh_cmd/domain/virsh_numatune.cfg
- libvirt/tests/src/numa/numa_memory_migrate.py
- libvirt/tests/src/numa/numa_memory_spread.py
libvirt has forbidden migrating memory for <numatune/> mode='strict' since
libvirt 8.0. Use restrictive mode to test memory migration.
Fix https://bugzilla.redhat.com/show_bug.cgi?id=2014369
Reference: libvirt 06f405c627 qemu: Explicitly forbid live changing
nodeset for strict numatune
Before
```
> virsh.numatune.positive_testing.set_numa_parameter.running_guest.change_nodeset.options \
> numa_memory_spread.default \
> numa_memory_migrate.mem_auto …
```
> Fix bz 2014369

- libvirt/tests/cfg/virsh_cmd/monitor/virsh_domstats.cfg
- libvirt/tests/src/virsh_cmd/monitor/virsh_domstats.py
Case ID: RHEL-180191
Case title: [iothread-domstats] Check iothread id info through "virsh domstats"
Scenario:
- Start vm
- Add some iothreads
- Check domstats output for the iothread info
- Delete some iothreads
- Check domstats output for updated iothread info
> virsh_domstats: add case for iothread

- libvirt/tests/cfg/incremental_backup/incremental_backup_checkpoint_cmd.cfg
- libvirt/tests/src/incremental_backup/incremental_backup_checkpoint_cmd.py
Since libvirt commit 27c1d06b, at most 8 chars can be used for
vnc password. So the original test script will be failed due to
password is too long. Now change it to a valid value.
> inc_backcup: Fix vnc password issue

- libvirt/tests/cfg/virsh_cmd/domain/virsh_setmem.cfg
- libvirt/tests/src/virsh_cmd/domain/virsh_setmem.py
- libvirt/tests/src/virtual_device/video_devices.py
pass on new and old qemu-kvm version
```
(1/1) type_specific.io-github-autotest-libvirt.virsh.setmem.memballoon_option.with_packed_on: PASS (62.01 s)
(1/1) type_specific.io-github-autotest-libvirt.virsh.setmem.memballoon_option.with_packed_on: PASS (62.02 s)
(2/4) type_specific.io-github-autotest-libvirt.virtual_devices.video_devices.positive_test.primary_video.vga.secondary_video.virtio.model_test.with_packed_on: PASS (28.45 s)
(3/4) type_specific.io-github-autotest-libvirt.virtual_devices.video_devices.positive_test.primary_video.cirrus.secondary_video.virtio.model_test.with_packed_on: PASS (29.67 s)
(4/4) type_specific.io-github-autotest-libvirt.virtual_devices.video_devices.positive_test.primary_video.virtio.secondary_video.virtio.model_te …
```
> Fix cmd line mapping error for qemu-kvm change again

- libvirt/tests/src/virsh_cmd/nodedev/virsh_nodedev_create_destroy.py
Original code will always use nodedev:///system driver to destroy
the node device, even if split daemon not enabled. The fix makes
sure to use qemu:///system driver if split daemon not enabled.
> nodedev: Fix nodedev driver issue

- v2v/tests/cfg/v2v_options.cfg
'yum deplist xxx' sometimes cannot query out correct result because
the db is not latest. I'm not sure how it happens. e.g. if you install
the pkg by a url link instead of repos, it always query from the old
package. so I think 'rpm -qR xxx' is better than that in this case.
> v2v: update the dependency checking command

- provider/vfio/ccw.py
- spell.ignore
- virttools/README.md
- virttools/tests/cfg/virt_install/hostdev_mdev.cfg
- virttools/tests/src/virt_install/hostdev_mdev.py
Depends on avocado-vt PR https://github.com/avocado-framework/avocado-vt/pull/3270
1. /virttools:
Add new test type for tools from virt-manager repository; by
using avocado-vt we get access to many useful test functions
ready to use for qemu/libvirt testing. The test type assumes
the same default setup as for tp-libvirt/libvirt and builds
on top of that. During testing, switching from a bootstrapped
libvirt environment to a bootstrapped virttools environment
worked and the test case passed.
2. hostdev_mdev:
Add a new test case.
a. 'run': This virt-install test case is currently ccw device
specific but other types on other platforms can be
implemented by creating a subclass for the
MdevHandler for the desired mdev_type.
b. 'clean_up/sleep': The introduction of 1sec sleep is
necessary to …
> virttools: add new test type and virt-install test

- v2v/tests/cfg/convert_vm_to_libvirt.cfg
- v2v/tests/cfg/convert_vm_to_ovirt.cfg
Add the new guest RHEL9.0 to the matrix of auto testing
> v2v:add the latest RHEL9 to matrix of auto testing

- provider/v2v_vmcheck_helper.py
The video value is hard coded to 'vga' in rhel9 for '-o json'.
We should check it in case this changes someday.
> v2v: add video check for -o json in rhel9

- libvirt/tests/src/virsh_cmd/domain/virsh_managedsave.py
From libvirt-8.0.0-2, the sysconfig file will be removed because of Bug 2042529 - backport sysconfig file removal. So it will cause that "Path for config file /etc/sysconfig/libvirt-guests don't exists" if we want to test managedsave. So create a libvirt-guests file manually to test it.
> virsh_managedsave.py: fix libvirt-guests file don't exists issue

- provider/v2v_vmcheck_helper.py
- v2v/tests/src/convert_vm_to_ovirt.py
For rhel9, we don't need to do any qxl check because it's not supported.
For rhel8, because 1997446 and 2012658, the win11 and win2022 are
inspected to win10 and win2016 unexpectedly by libguestfs, and this is
not going to be fixed in rhel8. so the qxl driver is installed for win11
and win2022 by mistake. BTW, virtio-win has already removed qxldod
driver for win11 and win2022. Because this problem, in order to make
out test run successfully, we'll continue checking the qxl for win11 and
win2022, but for the qxl warning message in v2v debug log, the scrip
will skip checking it. This warning is not that important and will make
the logic more complicate to understand.
> v2v: fix qxl check for win11 and win2022 guests

- libvirt/tests/src/virsh_cmd/domain/virsh_attach_detach_interface.py
Before:
```
(1/1) type_specific.io-github-autotest-libvirt.virsh.attach_detach_interface.normal_test.vm_running.default_network.at_option_config.domname: ERROR: Not found event device-removed after 60 seconds (120.67 s)
```
After:
```
(1/1) type_specific.io-github-autotest-libvirt.virsh.attach_detach_interface.normal_test.vm_running.default_network.at_option_config.domname: PASS (64.15 s)
```
> Remove event check for detach with --config

- libvirt/tests/cfg/virsh_cmd/domain/virsh_numatune.cfg
The default numa_mode of this test is restrictive and libvirt has
forbidden migrating memory for <numatune/> mode='strict' since libvirt
8.0.
So remove restrictive mode negative test from change_mode series.
Remove case so there is no rt.
> virsh_numatune: Remove meaningless negative test

- libvirt/tests/src/virsh_cmd/domain/virsh_edit.py
When the "vim" is not installed in the machine, the path exception
should be used correctly
e.g
> fix path exception error

- libvirt/tests/cfg/migration/live_migration.cfg
RHEL7-17296: [Migration][--migrateuri] Specify an unreachable
migrate URI for live migration - bug 720269
> live_migration: Add case for an unreachable migrate URI

- libvirt/tests/cfg/memory/memory_misc.cfg
```
(1/1) type_specific.io-github-autotest-libvirt.memory_misc.memorybacking.mem_lock.hard_limit: PASS (8.69 s)
```
> Resolve the mem case have coredump issue

- libvirt/tests/cfg/backingchain/blockcommit_basic_function.cfg
- libvirt/tests/src/backingchain/blockcommit_basic_function.py
- provider/backingchain/blockcommand_base.py
- provider/backingchain/check_functions.py
**Add** new case for RHEL7-16568:test blockcommit from top
to base after creating external disk-only snapshot with "block" disk type
**Inherit from  https://github.com/autotest/tp-libvirt/pull/3981** . 
For case RHEL7-16568 ,original pr is https://github.com/autotest/tp-libvirt/pull/3981 . However , I cannot reply to reviewer's comment in that page today , I try to find some methods to fix ,such as upgrade ,logout>login, reset passwords and so on, but still not success.So I create this pr.
/usr/local/bin/avocado run --vt-type libvirt --vt-machine-type q35 backingchain.blockcommit.basic_function.commit_tb.block_disk --vt-connect-uri qemu:///system
No python imaging library installed. Screendump and Windows guest BSOD detection are …
> backingchain:add case for blockcommit with block disk

- libvirt/tests/cfg/cpu/vcpu_feature.cfg
- libvirt/tests/cfg/cpu/vm_features.cfg
Test cases are invalid on s390x.
> vm_features/vcpu_feature: disable test cases on s390x

- libvirt/tests/cfg/virtual_device/filesystem_device.cfg
Enable kvm hugepage support to make test pass.
> filesystem_device: enable kvm hugepage support

- v2v/tests/cfg/convert_vm_to_libvirt.cfg
- v2v/tests/cfg/convert_vm_to_ovirt.cfg
Those guests were not setup in those very old hypervisors. And they will
not be tested, either.
> v2v: filter the rhel9,win11,win2022 guests from xen and esx6.0 in matrix

- libguestfs/tests/guestfs_list_operations.py
libguestfs/tests/guestfs_list_operations.py always fails because of "missing 1 required positional argument: 'params'"
```
...
JOB ID     : 707f75ecc937e27de3ceb18e1e190bac7f35b911
JOB LOG    : /root/avocado/job-results/job-2021-12-09T14.58-707f75e/job.log
(1/1) type_specific.io-github-autotest-libvirt.guestfs_list_operations.list_with_mount: STARTED
(1/1) type_specific.io-github-autotest-libvirt.guestfs_list_operations.list_with_mount: ERROR: test_list_with_mount() missing 1 required positional argument: 'params' (15.56 s)
JOB TIME   : 20.58 s
#
```
That's because the testcases require three arguments, however they get two arguments actually.
Let's fix it as same way as …
> libguestfs: Fix the arguments for the testcases of guestfs_list_operations.py

- libvirt/tests/cfg/migration/live_migration.cfg
- libvirt/tests/src/migration/live_migration.py
RHEL-133371 - [Migration] Do live migration again after last
live migration succeeds.
> live_migration: Add case for live migration twice

- libvirt/tests/cfg/virtual_interface/iface_nodedev_info.cfg
- libvirt/tests/src/virtual_interface/iface_nodedev_info.py
This PR adds:
RHEL-196262: nodedev-list/nodedev-dumpxml for vdpa devices
```
JOB LOG    : /root/avocado/job-results/job-2022-01-26T03.35-e1d4743/job.log
(1/2) type_specific.io-github-autotest-libvirt.iface.nodedev_info.vdpa.simulator: PASS (7.44 s)
(2/2) type_specific.io-github-autotest-libvirt.iface.nodedev_info.vdpa.mellanox: PASS (31.93 s)
JOB TIME   : 40.95 s
```
> vDPA: Add a case to check nodedev-info

- libvirt/tests/cfg/sriov/sriov_pf_down.cfg
- libvirt/tests/src/sriov/sriov_pf_down.py
This PR adds RHEL7-18513 - Start VM with VF or hotplug VF while PF
is down.
```
JOB LOG    : /root/avocado/job-results/job-2022-01-10T02.11-51512c0/job.log
(1/2) type_specific.io-github-autotest-libvirt.sriov.pf_down.at_dt.hot: PASS (11.67 s)
(2/2) type_specific.io-github-autotest-libvirt.sriov.pf_down.at_dt.cold: PASS (11.23 s)
JOB TIME   : 24.49 s
```
> SR-IOV: Add a case to check vf when PF is down

- libvirt/tests/cfg/virtual_network/iface_hotplug.cfg
- libvirt/tests/src/virtual_network/iface_hotplug.py
Qemu has add power indicator blink check since v6.2.0(commit 81124b3c7a).
It will cause the hot-unplug interface immediately after hotplug fail.
Add sleep 3s before the hot-unplug operation in our test script.
> Sleep 3s before hot-unplug an interface

- libvirt/tests/cfg/migration/migrate_storage.cfg
If ip_address in server.info is empty, we will meet following error:
#certtool --generate-certificate --load-privkey server-key.pem
--load-ca-certificate ca-cert.pem --load-ca-privkey ca-key.pem
--template server.info --outfile server-cert.pem
Generating a signed certificate...
Error in IPv4 address
> migrate_storage: Fix IPv4 address error

- libvirt/tests/cfg/virsh_cmd/domain/virsh_cpu_xml.cfg
- libvirt/tests/src/virsh_cmd/domain/virsh_cpu_xml.py
When comparing cpu, the result depends on the real Host cpu. So sometimes
the virsh command result is zero and return output message is superset.
> virsh_cpu_xml: fix superset host cpu

- libvirt/tests/src/virsh_cmd/domain/virsh_define.py
virsh xml operation slow down on libvirt-7.10.0-1
This bug was fixed in libvirt-8.0.0
Test on libvirt 8.0.0-2
```
JOB ID     : 20b0dfb6099bc8fc9566a3b3a40c68ba94e2ed52
JOB LOG    : /root/avocado/job-results/job-2022-02-11T03.15-20b0dfb/job.log
(1/1) type_specific.io-github-autotest-libvirt.virsh.define.positive_test.timeout: PASS (5.70 s)
JOB TIME   : 6.22 s
```
Test on libvirt 7.10.0-1
```
JOB ID     : 2f600f472dc59c3b14a0cd1a7920637a64fc1f37
JOB LOG    : /root/avocado/job-results/job-2022-02-11T02.43-2f600f4/job.log
(1/1) type_specific.io-github-autotest-libvirt.virsh.define.positive_test.timeout: FAIL: Define timeout: expected no more than 3s; actually spends …
```
> virsh_define: update test case for BZ#2030119

- libvirt/tests/src/virsh_cmd/network/virsh_net_event.py
```
(1/1) type_specific.io-github-autotest-libvirt.virsh.net_event.positive_test.no_timeout.loop.lifecycle_event.default: PASS (7.58 s)
```
> Add sleep between event track and trigger

- libvirt/tests/cfg/virtual_network/iface_options.cfg
- libvirt/tests/src/virtual_network/iface_options.py
Start vm with virtio driver option page_per_vq set as on or off.
> Add cases about virtio driver option page_per_vq

- libvirt/tests/src/sriov/sriov_nodedev.py
Ater re-attching the device, i40e driver needs more time to make
it work. So update to check the driver before comparing mac address.
` (1/1) type_specific.io-github-autotest-libvirt.sriov_nodedev.vf: ERROR: Unable to get iface name of 0000:3b:02.0. (16.25 s)`
` (1/1) type_specific.io-github-autotest-libvirt.sriov_nodedev.vf: PASS (24.68 s)`
> sriov: Update to check driver after re-attaching the device

- libvirt/tests/src/conf_file/sysconfig_libvirt_guests/libvirt_guests.py
In some case, /etc/sysconfig/libvirt-guests maybe not exist at the beginning
Therefore it need create if not existed
> Fix libvirt guests config in libvirt_guests.py

- libvirt/tests/src/backingchain/virtual_disks_relative_blockcommit.py
Make sure the guest boot successfully before snapshot-create-as.
Otherwise the test will get stuck.
Before
Test got stuck.
```
(1/1) type_specific.io-github-autotest-libvirt.virtual_disks.relativepath.blockcommit.normal_test.network_disk.iscsi.relative_path.validate_delete_option.shallow.top_active: ERROR: Command '/bin/virsh snapshot-create-as avocado-vt-vm1 relativesnap_4 relativesnap4-desc --diskspec  vda,snapshot=external,file=/var/lib/avocado/data/avocado-vt/images/jeos-27-aarch64.relativesnap4  --disk-only --atomic' failed.\nstdout: b'\n'\nstderr: b'err... (539.96 s)
```
After
```
(1/1) type_specific.io-github-autotest-libvirt.virtual_disks.relativepath.blockcommit.normal_test.network_disk.iscsi.relative_path.validate_delete_option.s …
```
> virtual_disks_relative_blockcommit: Fix snapshot-create-as hang

- libvirt/tests/cfg/numa/numa_memory_spread.cfg
- libvirt/tests/src/numa/numa_memory_spread.py
Tested with libvirt-8.0.0-1.el8.aarch64
```
JOB LOG    : /root/avocado/job-results/job-2022-01-21T04.53-c469e66/job.log
(1/2) type_specific.io-github-autotest-libvirt.numa_memory_spread.positive_test.default: STARTED                                                                                            
(1/2) type_specific.io-github-autotest-libvirt.numa_memory_spread.positive_test.default: PASS (84.04 s)                                                                                     
(2/2) type_specific.io-github-autotest-libvirt.numa_memory_spread.negative_test.strict_memory_mode: STARTED                                                                                 
(2/2) …
```
> numa_memory_spread: Add negative test for strict mode

- libvirt/tests/src/virtual_disks/virtual_disks_multidisks.py
Make sure that VM is completely booted before detach operation
> Fix disks_duplicate_target_different_bus_error_test case failure

- libvirt/tests/src/sriov/sriov.py
Some drivers need more time to make vfs work.
` (1/1) type_specific.io-github-autotest-libvirt.sriov.normal_test.guest_with_vf.hotplug.default.restart_libvirtd.vf_pool.vf_list: FAIL: Get net list with 'virsh nodedev-list' failed\n (338.48 s)`
```
(1/1) type_specific.io-github-autotest-libvirt.sriov.normal_test.guest_with_vf.hotplug.default.restart_libvirtd.vf_pool.vf_list: PASS (80.43 s)
(1/1) type_specific.io-github-autotest-libvirt.sriov.normal_test.guest_with_vf.hotplug.default.nop.vf_vlan.managed_yes: PASS (141.80 s)
```
> sriov: Extend sleep time before checking initialization of VFs

- libvirt/tests/cfg/virsh_cmd/host/virsh_nodecpustats.cfg
- libvirt/tests/src/virsh_cmd/host/virsh_nodecpustats.py
Reorg the original cases because of not pretty good readability
virsh_xxx functions logics are not changed, just moved outside of run()
Add new case: RHEL7-17029
Scenario 1: Test for all host cpus separately with all options,
like --cpu, --percent
Scenario 2: Disable one cpu, test nodecpustats command, then
enable this cpu and test nodecpustats again
Scenario 3: Test with invalid command option, like '--xyz'
Scenario 4: Test with invalid cpu
Scenario 5: Test with stopped libvirt daemons
> virsh_nodecpustats: add case disable cpu

- libvirt/tests/src/virsh_cmd/monitor/virsh_domblkinfo.py
Should retrieve the domblkinfo after disk attached successfully,
or the domblkinfo of vda could be changed during attaching disk.
> virsh.domblkinfo: Retrieve the domblkinfo after disk attached

- libvirt/tests/cfg/virtual_device/tpm_device.cfg
- libvirt/tests/src/virtual_device/tpm_device.py
Add active_pcr_banks normal tests for emualtor backend tpm device.
e.g
> tpm_device: add active_pcr_banks test

- libvirt/tests/cfg/backingchain/blockcopy_options.cfg
- libvirt/tests/src/backingchain/blockcopy_options.py
- provider/backingchain/blockcommand_base.py
- provider/backingchain/check_functions.py
add case for blockcopy with extended_l2 on disk
Signed-off-by: nanli [nanli@redhat.com](mailto:nanli@redhat.com)
**depend on**:  https://github.com/avocado-framework/avocado-vt/pull/3357 
**Test number** :RHEL-288642
root@dell-per740-33 tp-libvirt]# /usr/local/bin/avocado run --vt-type libvirt --vt-machine-type q35 backingchain.blockcopy_options.positive_test.extended_l2_on.not_encrypt_disk --vt-connect-uri qemu:///system
JOB ID …
> add case for blockcopy with extended_l2 on disk

- libvirt/tests/cfg/backingchain/blockresize.cfg
- libvirt/tests/src/backingchain/blockresize.py
- provider/backingchain/check_functions.py
**add** blockresize case: add blockresize case with b,mb,gb unit disk
**Test number** : RHEL-133310
**Depend on ** :
https://github.com/avocado-framework/avocado-vt/pull/3357 
https://github.com/autotest/tp-libvirt/pull/4062 
**Influence other case file** : `libvirt/tests/src/virtual_disks/ at_dt_iscsi_disk.py virtual_disks_ceph.py, virtual_disks_multidisks.py`  RUN PASSED https://github.com/autotest/tp-libvirt/pull/4059 
**Test result :**
**[root@nanli tp-libvirt]**# /usr/local/bin/avocado run --vt-type libvirt --vt-machine-type q35 backingchain.blockresize.positive_test.raw_image.size_mb --vt-connect-uri qemu:///system
RESULTS : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME : 13.26 s
**[root@nanli tp-libvirt]**# …
> blockresize: add blockresize case

- libvirt/tests/cfg/virtual_interface/vdpa_attach_duplicated_device.cfg
- libvirt/tests/src/virtual_interface/vdpa_attach_duplicated_devices.py
- spell.ignore
This PR adds a case as below:
RHEL-283966: Start vm or hotplug with duplicate vdpa device or VF device
Test results: A case was failed because of a product issue.
```
(1/7) type_specific.io-github-autotest-libvirt.iface.vdpa.attach_duplicated_devices.coldplug_2_vdpa.mellanox: PASS (32.68 s)
(2/7) type_specific.io-github-autotest-libvirt.iface.vdpa.attach_duplicated_devices.coldplug_2_vdpa.simulator: PASS (7.78 s)
(3/7) type_specific.io-github-autotest-libvirt.iface.vdpa.attach_duplicated_devices.coldplug_vdpa_vf.mellanox: PASS (34.29 s)
(4/7) type_specific.io-github-autotest-libvirt.iface.vdpa.attach_duplicated_devices.hotplug_same_vdpa_to_vm_with_vdpa_dev.mellanox: PASS (52.10 s)
(5/7) …
```
> vDPA: Add tests to check vDPA device and VF exclusive

- libvirt/tests/src/virsh_cmd/volume/virsh_vol_create_from.py
**Fix  create_vol_from  no space error**
Reduce the source volume size from 16M to 10M
Confirmed with meina ,may due to guest disk size .For feature owner ,they always met this kind of error, They will reduce the size and recreate vol to test. Not a bug.  
avocado run --vt-type libvirt --vt-machine-type q35 virsh.vol_create_from.positive_test.dest_vol_format.v_qcow2_with_prealloc.src_vol_format.v_raw.dest_pool_type.fs.src_pool_type.fs --vt-connect-uri qemu:///system
JOB ID     : db3e451762191d79b648247bd281a5fc84253377
JOB LOG    : /root/avocado/job-results/job-2022-03-06T08.32-db3e451/job.log
(1/1) type_specific.io-github-autotest-libvirt.virsh.vol_create_from.positive_test.dest_vol_format.v_qcow2_with_prealloc.src_vol_format.v_raw.dest_pool_type.fs.src_pool_type.fs: …
> virsh_vol_create_from: fix create vol from no space error

- libvirt/tests/src/sriov/sriov.py
The maxCount settings are different in different drivers.
Confirmed with dev that this is not a bug. And it's not related
to pf infomation checking test, so delete it.
` (1/1) type_specific.io-github-autotest-libvirt.sriov.normal_test.info_check.pf_info: PASS (53.70 s)`
> sriov: Remove maxCount checking in pf_info test

- libvirt/tests/src/sriov/sriov.py
The split separator should be any whitespace.
` (1/1) type_specific.io-github-autotest-libvirt.sriov.normal_test.guest_with_vf.cold_plug.nfv.two_nic.vf.managed_yes: FAIL: The vf is not attached to numa node 0\n (357.55 s)`
` (1/1) type_specific.io-github-autotest-libvirt.sriov.normal_test.guest_with_vf.cold_plug.nfv.two_nic.vf.managed_yes: PASS (56.96 s)`
> sriov: Update string split separator for check_numa function

- libvirt/tests/src/numa/numa_config_with_auto_placement.py
'systemd-cgls cpuset' output format is changed in new version of
systemd package systemd-250-4.el9.x86_64. So this is to update
the parsing for the output.
Old format is like:
```
`-machine.slice
`-machine-qemu\x2d2\x2davocado\x2dvt\x2dvm1.scope
```
New format is like:
```
`-machine.slice (#5408)
-> trusted.invocation_id: c4971d14d18345f4b8a0322f2e047b29
`-machine-qemu\x2d2\x2davocado\x2dvt\x2dvm1.scope ... (#10849)
```
> numa_config_with_auto_placement: fix output parse

- libvirt/tests/src/backingchain/virtual_disks_snapshot_blockpull.py
- libvirt/tests/src/embedded_qemu/embedded_qemu.py
- libvirt/tests/src/incremental_backup/incremental_backup_event_monitor.py
- libvirt/tests/src/incremental_backup/incremental_backup_pull_mode.py
- libvirt/tests/src/migration/migrate_options_shared.py
- libvirt/tests/src/virsh_cmd/domain/virsh_blockcopy.py
- libvirt/tests/src/virsh_cmd/domain/virsh_blockcopy_xml.py
- libvirt/tests/src/virsh_cmd/domain/virsh_domblkthreshold.py
- libvirt/tests/src/virt_cmd/virt_xml_validate.py
- libvirt/tests/src/virtual_disks/virtual_disks_nbd.py
The functions in utils_secret.py are implemented with virsh command. This kind of functions should be put into utils_libvirt/libvirt_secret.py. So we decide to rename utils_secret.py to libvirt_secret.py
**Depend on** 
https://github.com/avocado-framework/avocado-vt/pull/3368
> update file after rename utils_secret.py to libvirt_secret.py

- libvirt/tests/src/virtual_disks/virtual_disks_gluster.py
Previous logic will remove VM system disk, which leads to login timeout in VM itself
So remove these logic
> Fix virtual_disks gluster default_pool cases failures

- libvirt/tests/src/virtual_disks/virtual_disks_multidisks.py
It doesn't make sense that event will be received when detach disk with option "--config"
> Fix detach-disk event not found issue when option contains "--config"

- libvirt/tests/src/virsh_cmd/volume/virsh_vol_create_from.py
Fix no large enough free extent in scsi/iscsi pool which caused by https://github.com/autotest/tp-libvirt/pull/4079.
> virsh_vol_create_from.py: update the image size to fix scsi/iscsi issue

- v2v/tests/cfg/convert_from_file.cfg
- v2v/tests/cfg/convert_vm_to_libvirt.cfg
- v2v/tests/cfg/convert_vm_to_ovirt.cfg
- v2v/tests/cfg/function_test_esx.cfg
- v2v/tests/cfg/specific_kvm.cfg
- v2v/tests/src/convert_from_file.py
- v2v/tests/src/convert_vm_to_libvirt.py
- v2v/tests/src/convert_vm_to_ovirt.py
- v2v/tests/src/function_test_esx.py
- v2v/tests/src/specific_kvm.py
- v2v/tests/src/v2v_options.py
There are some changes about SHA1 in recent openssh package, it
blocks the connection to old guest, such as rhel6. A workaround
is enable LEGACY policy in order to connect to those guests.
> v2v: enable crypto policy to LEGACY for old guests

- libvirt/tests/cfg/virsh_cmd/domain/virsh_destroy.cfg
- libvirt/tests/src/virsh_cmd/domain/virsh_destroy.py
- spell.ignore
libvirt-8.0.0-2
```
(1/1) type_specific.io-github-autotest-libvirt.virsh.destroy.normal_test.non_acl.no_option.clean_domain_socket: FAIL: Failed to start guest: error: Failed to start domain 'avocado-vt-vm1'\nerror: cannot open /dev/null: Too many open files\n (72.72 s)
```
libvirt-8.0.0-5
```
(1/1) type_specific.io-github-autotest-libvirt.virsh.destroy.normal_test.non_acl.no_option.clean_domain_socket: PASS (122.57 s)
```
> virsh_destroy: Add testcase for BZ#2045879

- libvirt/tests/cfg/numa/numa_memory_spread.cfg
Original codes use numa node 0 to test, but on some numa hosts,
node 0 has no memory, so the vm will fail to start with it.
This is a fix to use the first available numa node with memory for
testing.
> numa_memory_spread: use first numa node with mem

- libvirt/tests/src/virtual_network/iface_ovs.py
- libvirt/tests/src/virtual_network/iface_target.py
```
(1/1) type_specific.io-github-autotest-libvirt.virtual_network.iface_target.flush_after_detach.flush_with_occupation.default: PASS (57.17 s)
(1/1) type_specific.io-github-autotest-libvirt.virtual_network.iface_ovs.net_ovs.ovs_qos.hotplug_iface: PASS (8.14 s)
```
> Fix the attach xml can not find error for virtual network

- libvirt/tests/cfg/migration/migrate_with_legacy_guest.cfg
- libvirt/tests/src/migration/migrate_with_legacy_guest.py
Need 'LEGACY' crypto-policy to access rhel6 guests because SHA1
is disabled in openssl by default for now.
Test results:
```
(1/5) type_specific.io-github-autotest-libvirt.virsh.migrate_with_legacy_guest.test_interface.rhel6_guest.virtio_transitional: PASS (182.51 s)
(2/5) type_specific.io-github-autotest-libvirt.virsh.migrate_with_legacy_guest.test_disk.with_virtio_scsi.disk_raw.rhel6_guest.unspecified_model: PASS (251.40 s)
(3/5) type_specific.io-github-autotest-libvirt.virsh.migrate_with_legacy_guest.test_disk.with_virtio_blk.disk_qcow2.rhel6_guest.virtio_transitional: PASS (244.48 s)
(4/5) type_specific.io-github-autotest-libvirt.virsh.migrate_with_legacy_guest.test_memballoon.rhel6_guest.virtio_transitional: PASS (184.06 s)
(5/5) …
```
> migration: Fix VM login failure

- libvirt/tests/src/libvirt_hooks.py
When hotplug interface, it will use rtl8139 as the default model.
Add this interface device will be plugged into 'pcie-to-pci-bridge'.
If no such controller on guest, the hotplug interface will fail.
For example:
#virsh attach-interface vm1 --type network --source default
error: Failed to attach interface
error: internal error: No more available PCI slots
If set model to 'virtio', it will succeed. Because it will be
plugged into pcie slot(pcie-root-port).
> Fix no more available PCI slots for interface device

- libvirt/tests/cfg/backingchain/blockjob_options.cfg
- libvirt/tests/src/backingchain/blockjob_options.py
- provider/backingchain/blockcommand_base.py
- provider/backingchain/check_functions.py
**add** case for blockjob with raw option
**Test** number RHEL-114623
root@nanli tp-libvirt]# avocado list --vt-type libvirt backingchain.blockjob.options
VT type_specific.io-github-autotest-libvirt.backingchain.blockjob.options.option_raw
[root@nanli tp-libvirt]# /usr/local/bin/avocado run --vt-type libvirt --vt-machine-type q35 backingchain.blockjob.options.option_raw --vt-connect-uri qemu:///system
JOB ID     : 1b5928dfe6b1fb9a9286439c952edd9438fbb825
JOB LOG    : /root/avocado/job-results/job-2022-02-12T19.34-1b5928d/job.log
(1/1) type_specific.io-github-autotest-libvirt.backingchain.blockjob.options.option_raw: PASS (109.62 s)
JOB TIME   : 116.24 s
> add case for blockjob with raw options

- libvirt/tests/cfg/virtio_transitional/virtio_transitional_blk.cfg
- libvirt/tests/cfg/virtio_transitional/virtio_transitional_mem_balloon.cfg
- libvirt/tests/cfg/virtio_transitional/virtio_transitional_nic.cfg
- libvirt/tests/cfg/virtio_transitional/virtio_transitional_rng.cfg
- libvirt/tests/cfg/virtio_transitional/virtio_transitional_serial.cfg
- libvirt/tests/src/virtio_transitional/virtio_transitional_blk.py
- libvirt/tests/src/virtio_transitional/virtio_transitional_mem_balloon.py
- libvirt/tests/src/virtio_transitional/virtio_transitional_nic.py
- libvirt/tests/src/virtio_transitional/virtio_transitional_rng.py
- libvirt/tests/src/virtio_transitional/virtio_transitional_serial.py
Need 'LEGACY' crypto-policy to access rhel6 guests because SHA1
is disabled in openssl by default for now.
```
avocado run --vt-type libvirt --vt-machine-type q35 virtio_transitional_blk virtio_transitional_serial virtio_transitional_mem_balloon virtio_transitional_nic virtio_transitional_rng virtio_transitional_blk_negative
JOB ID     : 108955e5643f949525c07ba5877af48bc74b82b8
JOB …
```
> virtio_transitional: Fix rhel6 guest login failure

- libvirt/tests/src/virsh_cmd/domain/virsh_migrate.py
It reports UnboundLocalError: local variable 'scsi_disk'
referenced before assignment, so update script.
> virsh_migrate: Fix 'scsi_disk' UnboundLocalError

- libvirt/tests/cfg/numa/numa_memory_migrate.cfg
- libvirt/tests/src/numa/numa_memory_migrate.py
Orignal codes use LibvirtdSession to start daemon in foreground which
does have problem on modular daemon mode. This is to change to use
backgroupd daemon start as well as changing the log message verifying.
> numa_memory_migrate: remove foreground daemon

- libvirt/tests/cfg/numa/numa_memory.cfg
- libvirt/tests/src/numa/numa_memory.py
Orignal codes use LibvirtdSession to start daemon in foreground which
does have problem on modular daemon mode. This is to change to use
backgroupd daemon start as well as changing the log message verifying.
depend on https://github.com/avocado-framework/avocado-vt/pull/3386
> numa_memory: fix foreground libvirtd start

- libvirt/tests/src/guest_kernel_debugging/nmi_test.py
Sometimes start kdump service failure leads to case failed, so
add debug information.
> nmi_test: Add debug log

- libvirt/tests/src/numa/numa_memory_spread.py
Test compares numa_memory['nodeset'] to online_nodes which have memory
to get neighbour node.
numa_memory['nodeset'] is a str but online_nodes is a int array.
Convert online_nodes element to str to avoid problems caused by
unmatched type.
Before
```
(1/1) type_specific.io-github-autotest-libvirt.numa_memory_spread.positive_test.default: FAIL: The VM crashed when memhog was executed. (57.61 s)
```
After
```
(1/1) type_specific.io-github-autotest-libvirt.numa_memory_spread.positive_test.default: PASS (63.40 s)
```
> [minor fix] numa_memory_spread: Fix wrong neighbour node

- libvirt/tests/cfg/backingchain/blockcopy_options.cfg
- libvirt/tests/src/backingchain/blockcopy_options.py
add case for blockcopy with --synchronous-writes option
**id** : RHEL-289790: 
/usr/local/bin/avocado run --vt-type libvirt --vt-machine-type q35 backingchain.blockcopy_options.positive_test.synchronous_writes --vt-connect-uri qemu:///system
JOB ID     : 4fcd77a14ebd7378a63907b957812c35e3f7d8a6
JOB LOG    : /root/avocado/job-results/job-2022-03-07T08.06-4fcd77a/job.log
(1/1) …
> add case for blockcopy with sync writes option

- libvirt/tests/cfg/cpu/vcpu_nested.cfg
- libvirt/tests/src/cpu/vcpu_nested.py
1.Add new case to check whether feature nested virt is enabled at run-time.
2.Add return value of function run_domcap_in_guest as needed.
3.Create separate functions for cases, add descriptions.
Polarion ID:RHEL-150289
> Add case to check nested feature at run-time

- libvirt/tests/src/numa/numa_memory.py
This is to fix the wrong value assignment. A string value is expected,
but not a list value.
> numa_memory: fix bitmap error

- v2v/tests/cfg/convert_vm_to_ovirt.cfg
This only works when converting guest from esx to ovirt by rhv-upload.
Other scenarios are not supported in automation.
> v2v: allow v2v execution by non-root user

- libvirt/tests/cfg/backingchain/blockcopy_options.cfg
- libvirt/tests/src/backingchain/blockcopy_options.py
- provider/backingchain/blockcommand_base.py
add case for encrypted disk wth extended l2 on status
**case id** : RHEL-288643
**Depend on** :  https://github.com/avocado-framework/avocado-vt/pull/3368/
avocado-framework/avocado-vt#3370 
/usr/local/bin/avocado run --vt-type libvirt --vt-machine-type q35 backingchain.blockcopy_options.positive_test.extended_l2_on.encrypt_disk --vt-connect-uri qemu:///system
JOB ID     : 7d62c328bb9cf8e141aa663750b802a04a947442
JOB LOG    : …
> add case for encrypted disk wth extended l2 on status

- libvirt/tests/cfg/migration/migrate_storage.cfg
- libvirt/tests/src/migration/migrate_storage.py
RHEL-289786 - Copy inremental storage migration with
--copy-storage-synchronous-writes BZ2026812
> migrate_storage: Add case for --copy-storage-synchronous-writes

- libvirt/tests/src/virtual_device/tpm_device.py
'--pid' and '--daemon' is not used by libvirt anymore from libvirt
v8.1.0. So skip these two params checkng in pattern_list, and get
swtpm process id by grep 'swtpm socket' words instead of pid file
name. Since these checking do not affect function, no need to judge
libvirt_version.
e.g
> tpm_device: modify swtpm pid grep

- libvirt/tests/cfg/controller/controller_functional.cfg
- libvirt/tests/cfg/controller/pcibridge.cfg
- libvirt/tests/src/controller/controller_functional.py
libvirt uses json format for qemu command line by default from libvirt 8.1.0.
This is to fix the checking compatible to both format.
> controller_functional: fix json format

- libvirt/tests/src/backingchain/blockresize.py
not found event after disk detached due to disk attached before vm finished start
**test result** 
(.libvirt-ci-venv-ci-runtest-OYdoZi) [root@dell-per730-62 tp-libvirt]# 
(.libvirt-ci-venv-ci-runtest-OYdoZi) [root@dell-per730-62 tp-libvirt]# **/usr/local/bin/avocado run --vt-type libvirt --vt-machine-type q35 backingchain.blockresize.positive_test.raw_image.size_mb --vt-connect-uri qemu:///system**
JOB ID …
> fix device_removed event not found in blockresize

- libvirt/tests/cfg/bios/virsh_boot.cfg
virsh_boot.cfg: fix boot error in BIOS negative test
> virsh_boot.cfg: fix boot error in BIOS negative test

- libvirt/tests/cfg/virsh_cmd/nodedev/virsh_nodedev_persistence_mdev.cfg
- libvirt/tests/src/virsh_cmd/nodedev/virsh_nodedev_persistence_mdev.py
- spell.ignore
Depends on https://github.com/avocado-framework/avocado-vt/pull/3333
Depends on https://github.com/avocado-framework/avocado-vt/pull/3384
Add a roundtrip test case to cover the lifecycle of a ccw mdev device
that's set up persistently via libvirt's nodedev API.
As avocado can't restart the host and continue the test run,
the autostart configuration is only covered to be correctly set.
All other commands are expected to fail if there was any issue.
> nodedev_persistence: add test case for nodedev persistent setup API

- libvirt/tests/cfg/virtual_device/tpm_device.cfg
- libvirt/tests/src/virtual_device/tpm_device.py
Add two cases: restart vm with pcrbank removed, modify pcrbank for
managedsaved vm.
e.g
> tpm_device: add pcrbank modify scenarios

- libvirt/tests/cfg/daemon/check_daemon_after_remove_pkgs.cfg
- libvirt/tests/src/daemon/check_daemon_after_remove_pkgs.py
> Add test for checking daemons are removed after removing libvirtd pkgs

- v2v/tests/cfg/function_test_esx.cfg
Because rhv is not new enough for including the fix of bz1924972,
the '-o rhv/rhv_upload' will not work at the moment.
So change the target to 'libvirt' to cover this case.
> v2v: change the target of the lvm_multiple_disks

- v2v/tests/cfg/function_test_esx.cfg
Because the dir_permission case only works in rhel9. We should make
sure it won't fail in rhel8.
> v2v: seperate the dir permission from usr_partition case

- libvirt/tests/cfg/virtual_device/filesystem_device.cfg
- libvirt/tests/src/virtual_device/filesystem_device.py
When setting stdio_handler as default, the process to write log is virtlogd;
while setting stdio_handler as file, the process should be virtiofsd.
Case ID: RHEL-288048
JOB ID     : e60419e14dfec643527a1e38f8f70b4e8345a0f2                                                                                                                             
JOB LOG    : /root/avocado/job-results/job-2022-03-05T05.03-e60419e/job.log                                                                                                       
(001/272) type_specific.io-github-autotest-libvirt.virtual_devices.filesystem_device.positive_test.hugepages_backed.nop.externally_launched_fs_test.launched_mode: PASS (36.12 s)
......
(271/272) …
> [filesystem_device]Add the cases to test the stdio_handler

- libvirt/tests/src/virt_admin/management/virt_admin_server_update_tls.py
Check virtproxyd service on remote host to avoid following error:
virt-admin # uri
error: Failed to connect to the admin server
error: no valid connection
error: Failed to connect socket to
'/run/libvirt/libvirt-admin-sock': Connection refused
> Update to start virtproxyd service

- libvirt/tests/cfg/sriov/sriov_attach_hostdev.cfg
- libvirt/tests/src/sriov/sriov_attach_hostdev.py
- provider/sriov/check_points.py
RHEL-288445: Hotplug hostdev interface with 'unassigned'
address type
RHEL-288444: Start vm with hostdev interface with 'unassigned'
address type
RHEL-134143: Hotplug hostdev interface with duplicate custom alias
**depends on** https://github.com/avocado-framework/avocado-vt/pull/3362
**Test results:** 2 cases are failed due to a known BZ.
```
(1/5) type_specific.io-github-autotest-libvirt.sriov.attach_hostdev.unassigned_address.hostdev_device.cold_plug: PASS (35.28 s)
(2/5) type_specific.io-github-autotest-libvirt.sriov.attach_hostdev.unassigned_address.hostdev_device.hot_plug: FAIL: hostdev xml(address) comparison failed.Expected "{'type': 'unassigned'}",got "{'bus': '0x01', 'domain': '0x0000', 'function': '0x0', …
```
> sriov: Add 3 cases

- libvirt/tests/cfg/backingchain/domblkthreshold.cfg
- libvirt/tests/src/backingchain/domblkthreshold.py
RHEL-189080: Do domblkthreshold for a device which is not the active layer image
(p3-ve) [root@nanli tp-libvirt]# /usr/local/bin/avocado run --vt-type libvirt --vt-machine-type q35 backingchain.domblkthreshold.positive_test.inactivate_layer --vt-connect-uri qemu:///system
JOB ID     : 06cd8794169551a81a84da8103a97db1ffcc220b
JOB LOG    : /root/avocado/job-results/job-2022-03-28T17.59-06cd879/job.log
(1/1) type_specific.io-github-autotest-libvirt.backingchain.domblkthreshold.positive_test.inactivate_layer: PASS (21.86 s)
JOB TIME   : 28.07 s
> add case for domblkthreshold inactive layer

- v2v/tests/cfg/function_test_esx.cfg
Because '-o json' is removed in upstream of v2v, and nobody will
use them in rhel9, so add a new '-o local' target to replace the
'-o json' target. The '-o json' will be kept but skipped during
running.
> v2v: replace output '-o json' with '-o local'

- libvirt/tests/cfg/virtual_interface/interface_update_device_offline_domain.cfg
- libvirt/tests/cfg/virtual_interface/interface_update_device_running_domain.cfg
- libvirt/tests/src/virtual_interface/interface_update_device_offline_domain.py
- libvirt/tests/src/virtual_interface/interface_update_device_running_domain.py
- provider/interface/check_points.py
- provider/interface/interface_base.py
This PR adds:
1. RHEL-286748 - Update an interface by update-device with different options on
inactive domain
2. RHEL-286741 - Update an interface by update-device with different options on
running domain
```
(01/16) type_specific.io-github-autotest-libvirt.iface.update_device.running_domain.device_exists.opts_affect_running_vm.live: PASS (7.99 s)
(02/16) type_specific.io-github-autotest-libvirt.iface.update_device.running_domain.device_exists.opts_affect_running_vm.current: PASS (8.08 s)
(03/16) type_specific.io-github-autotest-libvirt.iface.update_device.running_domain.device_exists.opts_affect_offline_vm.config: PASS (12.69 s)
(04/16) type_specific.io-github-autotest-libvirt.iface.update_device.running_domain.device_exists …
```
> virtual_interface: Add 2 cases to check update-device

- libvirt/tests/cfg/remote_access/virsh_non_root_polkit.cfg
- libvirt/tests/src/remote_access/virsh_non_root_polkit.py
Unable to list cases of virsh_non_root_polkit.
It reports "__init__() got multiple values for argument 'uri'".
```
(1/4) type_specific.io-github-autotest-libvirt.virsh.non_root_polkit.positive_testing.virsh_connect_non_root: STARTED
(1/4) type_specific.io-github-autotest-libvirt.virsh.non_root_polkit.positive_testing.virsh_connect_non_root: PASS (9.50 s)
(2/4) type_specific.io-github-autotest-libvirt.virsh.non_root_polkit.positive_testing.virsh_connect_non_root_over_ssh: STARTED
(2/4) type_specific.io-github-autotest-libvirt.virsh.non_root_polkit.positive_testing.virsh_connect_non_root_over_ssh: PASS (20.47 s)
(3/4) type_specific.io-github-autotest-libvirt.virsh.non_root_polkit.positive_testing.virsh_connect_non_root_over_ssh …
```
> virsh_non_root_polkit: Change 'uri' to 'virsh_uri'

- libvirt/tests/cfg/backingchain/blockjob_options.cfg
- libvirt/tests/src/backingchain/blockjob_options.py
add case for blockjob with async option  
**ID**: RHEL-114624 
**Test result :**
(p3-ve) [root@nanli tp-libvirt]# /usr/local/bin/avocado run --vt-type libvirt --vt-machine-type q35 backingchain.blockjob.options.option_async --vt-connect-uri qemu:///system
JOB ID     : 2188799d8a4dc4e7a948d96721451db4d8867bfb
JOB LOG    : /root/avocado/job-results/job-2022-03-28T11.31-2188799/job.log
(1/1) type_specific.io-github-autotest-libvirt.backingchain.blockjob.options.option_async: PASS (4.49 s)
JOB TIME   : 7.92 s
> add case for blockjob with async option

- libvirt/tests/src/numa/numa_numanode_cpu_info.py
The required numa node number is 2, but the code is requiring a number bigger than 2.
So this is not consistent with the original purpose and over required. This PR is to
make 2 numa nodes host also be able to run the case instead of skipping.
> numa_numanode_cpu_info: fix incorrect skip

- provider/vfio/ccw.py
I suspect fdasd might succeed sometimes despite a non-zero
status code though I couldn't reproduce it. This made the test
case fail. (I think this could happen because of a warning
when the disk is detected as used by several hosts.)
Add the status report to the log in case this reproduces.
> provider/vfio/ccw: improve logging

- libvirt/tests/src/migration/migrate_with_various_hostname.py
Fix error:
UnboundLocalError: local variable 'old_dst_hostname' referenced
before assignment
> Fix variable referenced before assignment error

- libvirt/tests/cfg/host_hypervisor/domcapabilities_output.cfg
- libvirt/tests/src/host_hypervisor/domcapabilities_output.py
- spell.ignore
Case ID: RHEL-202492
Test scenario:
Remove ovmf directory and check domcapabilities output does not
include that entry and does include when it comes back.
> domcapabilities_output: add case to remove ovmf path

- v2v/tests/cfg/convert_from_file.cfg
See#bz1984938.
The 'qemu-nbd' will be used in v2v when converting a qcow2 disk by
'-i disk' or ova file by '-i ova'. Both ways can verify the bug.
> v2v: new case for converting ova file by non-root user

- libvirt/tests/cfg/virtual_network/network_misc.cfg
Before failure with
```
TestFail: Expect should fail with one of ['Expected integer value'], but failed with:error: Failed to attach device from /tmp/xml_utils_temp_fvs6yf5p.xmlerror: XML error: Invalid value for attribute 'index' in element 'acpi': '-2'. Expected non-negative integer value
```
After pass
```
(1/2) type_specific.io-github-autotest-libvirt.virtual_network.network_misc.iface_acpi.value_test.negative_test.-2: PASS (24.34 s)
(2/2) type_specific.io-github-autotest-libvirt.virtual_network.network_misc.iface_acpi.value_test.negative_test.empty: PASS (24.33 s)
```
> Fix virtual network err msg failure

- libvirt/tests/cfg/bios/virsh_boot.cfg
Before failure is 
```
TestFail: Expect should fail with one of ['error: unsupported configuration: unknown boot device'], but failed with:error: Failed to define domain from /tmp/xml_utils_temp_k6o4pe3h.xmlerror: XML error: Invalid value for attribute 'dev' in element 'boot': 'noexist'
```
After
``` 
(1/1) type_specific.io-github-autotest-libvirt.virsh.boot.by_ovmf.negative_test.invalid_boot_dev: PASS (12.00 s)
```
> Add more error message for mapping new result

- libvirt/tests/cfg/memory/memory_attach_device.cfg
- libvirt/tests/cfg/memory/memory_update_device.cfg
- libvirt/tests/src/memory/memory_attach_device.py
- libvirt/tests/src/memory/memory_update_device.py
This PR adds:
RHEL-288949: Start VM with virtio-mem device
RHEL-288950: Hotplug a virtio-mem device
RHEL-288951: update memory device for virtio-mem device
https://github.com/avocado-framework/avocado-vt/pull/3377
https://github.com/avocado-framework/avocado-vt/pull/3376
```
(1/3) type_specific.io-github-autotest-libvirt.memory_update_device.virtio_mem: PASS (42.25 s)
(2/3) type_specific.io-github-autotest-libvirt.memory_attach_device.virtio_mem.cold_plug: PASS (39.91 s)
(3/3) type_specific.io-github-autotest-libvirt.memory_attach_device.virtio_mem.hot_plug: PASS (37.06 s)
```
> memory: Add cases about virtio-mem device

- libvirt/tests/src/cpu/vcpu_hotpluggable.py
Cgroup utils package is no longer needed.
```
(01/11) type_specific.io-github-autotest-libvirt.vcpu_hotpluggable.positive_test.vcpus_with_order: PASS (38.69 s)
(02/11) type_specific.io-github-autotest-libvirt.vcpu_hotpluggable.positive_test.enable: PASS (31.87 s)
(03/11) type_specific.io-github-autotest-libvirt.vcpu_hotpluggable.positive_test.disable: PASS (31.27 s)
(04/11) type_specific.io-github-autotest-libvirt.vcpu_hotpluggable.positive_test.unplug.live: PASS (32.39 s)
(05/11) type_specific.io-github-autotest-libvirt.vcpu_hotpluggable.positive_test.unplug.config.running_vm: PASS (31.45 s)
(06/11) type_specific.io-github-autotest-libvirt.vcpu_hotpluggable.positive_test.unplug.config.shutoff_vm: PASS (11.05 s)
(07/11) …
```
> vcpu_hotpluggable: Remove cgroup utils installation

- libvirt/tests/cfg/virsh_cmd/domain/virsh_detach_device_alias.cfg
- libvirt/tests/src/virsh_cmd/domain/virsh_detach_device_alias.py
**add case for detached_watchdog_by_alias**    
RHEL-148238: detached watchdog by alias with --live and --config option
**Test** result:
[root@dell-per730-62 tp-libvirt]# /usr/local/bin/avocado run --vt-type libvirt --vt-machine-type q35 virsh.detach_device_alias..watchdog --vt-connect-uri qemu:///system
JOB ID     : 65e7a7df01cc9578c580f1ad5b28eed310e5747e
JOB LOG    : …
> add case for detached watchdog by alias

- libvirt/tests/cfg/bios/virsh_boot_reset_nvram.cfg
- libvirt/tests/src/bios/virsh_boot_reset_nvram.py
This is to test the support for --reset-nvram.
RHEL-292783
TC1: Start a destroyed vm successfully with the option and nvram file is recreated
TC2: Start a managedsaved vm successfully with the option and nvram file is recreated
TC3: Restore a saved vm successfully with this option and nvram file is recreated
TC4: Create a destroyed vm successfully with this option and nvram file is recreated
> virsh_boot_reset_nvram: add case for reset-nvram

- libvirt/tests/src/passthrough/pci/libvirt_pci_passthrough.py
Since Python 3.3+ provides `ipaddress` as the standard library for
IPv4/IPv6 manipulation, let's replace the third-party one (`netaddr`)
with it for a better maintainability.
Signed-off-by: Xu Han <xuhan@redhat.com>
> replace netaddr with ipaddress

- libvirt/tests/cfg/remote_access/remote_with_unix.cfg
- libvirt/tests/src/remote_access/remote_access.py
In modular daemon environment, 'virsh -c qemu+unix:///system' will
connect to virtqemud directly. So need config virtqemud.conf.
> remote_with_unix: Fix UNIX connection issues

- libvirt/tests/src/virsh_cmd/domain/virsh_attach_device.py
In previous versions of libvirt duplicate devices could be mounted on
single port. This is no longer possible on the newest versions of
libvirt. This commit changes the port numbering so that devices are
always attached on sequentially ordered ports regardless of type.
In previous versions of libvirt duplicate devices could be mounted on
single port. This is no longer possible on the newest versions of
libvirt. This commit changes the port numbering so that devices are
always attached on sequentially ordered ports regardless of type.
```
avocado run --vt-type libvirt virsh.attach_device.character.serial.multi_type.normal_test.cold_attach_cold_vm.persistent.name_ref.file_argument.domain_argument
No python imaging library installed. Screendump and Windows guest BSOD detection are disabled. …
```
> virsh_attach_device: Attach character devices on sequential ports

- libvirt/tests/src/virsh_cmd/pool/virsh_pool.py
- libvirt/tests/src/virsh_cmd/pool/virsh_pool_autostart.py
The disk pool will be active after restart libvirtd/virtstoraged even though we set no autostart to it. It's an intended behavior now as the dir pool. So update the disk pool status from inactive to active.
> virsh_pool_autostart.py: update disk pool status from inactive to active

- libvirt/tests/cfg/remote_access/remote_with_tls.cfg
- libvirt/tests/src/remote_access/remote_access.py
A cert created in new version libvirt needs a reversed setting.
> remote_access: Update case for BZ#2018488

- libvirt/tests/src/virsh_cmd/domain/virsh_cpu_stats.py
This PR fix the "No such file" error which caused by
reading the domain file when the domain is not start.
> Fix the failures when running negative tests

- libvirt/tests/src/virsh_cmd/domain/virsh_detach_device_alias.py
fix detach device alias get params error 
convert dict to str
**Test result** 
[root@dell-per740xd-11 ~]#  avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 virsh.detach_device_alias --vt-connect-uri qemu:///system
JOB ID     : 4b95d6b4cdc86f795970a005e11f362b09d4239a
JOB LOG    : /var/lib/avocado/job-results/job-2022-05-06T00.31-4b95d6b/job.log
(01/14) …
> virsh_detach_device_alias.py: fix detach device alias get params error

- libvirt/tests/src/migration/live_migration.py
The connection to the target host may be broken if the IP addr
set in the previous case is inaccessible. So update to recover
/etc/hosts for the source host.
hosts contains `<ipv6 addr> <target host cn>` after executing 'live_migration.migration_host.set_src_hosts_ipv6.p2p_live.without_postcopy'
After the fix:
There's no `<ipv6 addr> <target host cn>` in /etc/hosts.
> migration: Update to recover the source host's hosts file

- v2v/tests/src/specific_kvm.py
It's fine that the rpmdb files are removed blindly. This will make
sure the corrupt rpmdb file '__db.001' be created.
> v2v: improve creating corrupt rpmdb logic

- v2v/tests/src/function_test_esx.py
The output file name is different between '-o json' and '-o local'.
so the code should be changed to reflect that. If not, the test
will be invalid.
> v2v: fix block_dev case issue

- libvirt/tests/src/backingchain/domblkthreshold.py
fix get no event after domblkthreshold
There are two problems here 
1. Need wait time to get event
2. The patten to match event list needs to update
**Depend on** https://github.com/avocado-framework/avocado-vt/pull/3403 
**Test result** 
[root@dell-per730-62 ~]# /usr/local/bin/avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 backingchain.domblkthreshold.positive_test.inactivate_layer --vt-connect-uri qemu:///system
JOB ID     : 9fad959c892235f2b77557a43290ef8028843684
JOB LOG    : /root/avocado/job-results/job-2022-05-05T21.31-9fad959/job.log
(1/1) type_specific.io-github-autotest-libvirt.backingchain.domblkthreshold.positive_test.inactivate_layer: PASS (41.59 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | …
> domblkthreshold.py: fix get no event after domblkthreshold

- libvirt/tests/cfg/virsh_cmd/domain/virsh_save.cfg
- libvirt/tests/src/virsh_cmd/domain/virsh_save.py
'paused_state' is better than 'paused_option' which is duplicated
with later options. And add domstate to display vm status better
for readers in log.
> virsh_save: change to paused_state pattern name

- libvirt/tests/cfg/virtual_disks/virtual_disks_cdrom_device.cfg
- libvirt/tests/src/virtual_disks/virtual_disks_cdrom_device.py
When domain with cdrom attach and then eject, then virsh domstats,
Libvirtd/Virtqemud should not crash[1]
start a guest with lun device + scsi bus + qcow2 format [2]
[1]https://bugzilla.redhat.com/show_bug.cgi?id=1420718
[2]https://bugzilla.redhat.com/show_bug.cgi?id=1379196
> Add case to cover validating libvirtd/virtqemud crash scenarios

- libvirt/tests/src/serial/serial_pty_log.py
For some low-performance machines, the running speed is slow, the log has no `login prompt` input within 3s, and the case will fail. This PR extends the timeout to 6s.
Before:
```
JOB ID     : da036dd6cdb6b8f36390e27275636279d25699a3                            
JOB LOG    : /var/lib/avocado/job-results/job-2022-05-12T21.50-da036dd/job.log     
(1/1) type_specific.io-github-autotest-libvirt.serial.pty.log.file: ERROR: Unexpected error: Failed to find the vm login prompt from /var/lib/libvirt/console1.log (52.05 s)
JOB HTML   : /var/lib/avocado/job-results/job-2022-05-12T21.50-da036dd/results.html
JOB TIME   : 52.82 s
```
After:
```
JOB ID     : …
```
> serial_pty_log: Extend the timeout for getting login prompt

- libvirt/tests/src/virsh_cmd/domain/virsh_domxml_to_native.py
In virsh_domxml_to_native.py, when exporting setup from xml,
for some arguments quotes are added. The testing script removes them but
the list of arguments that is supposed to be removed is edited manually.
One of the missing arguments is -device arguments that this commit adds.
Similar commit is bab218c2074e3537db1b18e0d0c8e1c4bbc9cd04
https://github.com/autotest/tp-libvirt/commit/bab218c2074e3537db1b18e0d0c8e1c4bbc9cd04
e.g
> virsh_domxml_to_native: Add -device to list of args with redundant quotes

- libvirt/tests/cfg/migration/migrate_mem.cfg
- libvirt/tests/src/migration/migrate_mem.py
Test scenario: migration with maxmemory and check no specified error in libvirt daemon log
VIRT-38151
> migrate_mem: add case maxmemory

- libvirt/tests/src/numa/numa_memory_spread.py
This is to remove the dependency for unused package.
The package is not available in new compose.
> numa_memory_spread: no need this package

- libvirt/tests/cfg/sriov/sriov_attach_hostdev.cfg
- libvirt/tests/src/sriov/sriov_attach_hostdev.py
This pr fixes 2 problems:
1. The unassigned address changed to only support hostdev device
2. VM login failure
```
(1/5) type_specific.io-github-autotest-libvirt.sriov.attach_hostdev.unassigned_address.hostdev_device.cold_plug: PASS (46.20 s)
(2/5) type_specific.io-github-autotest-libvirt.sriov.attach_hostdev.unassigned_address.hostdev_device.hot_plug: PASS (47.62 s)
(3/5) type_specific.io-github-autotest-libvirt.sriov.attach_hostdev.unassigned_address.hostdev_interface.cold_plug: PASS (20.05 s)
(4/5) type_specific.io-github-autotest-libvirt.sriov.attach_hostdev.unassigned_address.hostdev_interface.hot_plug: PASS (22.76 s)
(5/5) type_specific.io-github-autotest-libvirt.sriov.attach_hostdev.duplicated_cust_alias.hot_plug: …
```
> sriov: Fix 2 issues in unassigned_address cases

- libvirt/tests/src/virtual_device/filesystem_device.py
The default `event_timeout` for `detach_device_alias` is 7s, but on ARM, it spends about 7.01s. So the test cases always fails.
This PR extends the `event_timeout` to 8s.
Befor:
```
JOB ID     : 344d9c91b181df747a6d036670d7fe82c8b29a09
JOB LOG    : /root/avocado/job-results/job-2022-05-13T02.42-344d9c9/job.log
(1/1) type_specific.io-github-autotest-libvirt.virtual_devices.filesystem_device.positive_test.hugepages_backed.hotplug_unplug.detach_device_alias.stdio_handler.file.fs_test.xattr_on.flock_on.lock_posix_on.cache_mode_none.one_fs.one_gues
t: ERROR: Not found event device-removed after 7 seconds (64.67 s)
JOB HTML   : …
```
> misc_virtual_devices: Extend event_timeout for detach_device_alias

- libvirt/tests/cfg/virtual_device/vsock.cfg
- libvirt/tests/src/virtual_device/vsock.py
Hotunplug vsock device with virsh detach-device-alias
**case id** :  RHEL-145277
[root@hpe-xl220agen8v2-02 tp-libvirt]# /usr/local/bin/avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 vsock.normal_test.hotplug.detach_device_alias.static_cid --vt-connect-uri qemu:///system
JOB ID     : a4cc1a6ad8a2044ddf5c22fd1c2766095576bad5
JOB LOG    : /var/lib/avocado/job-results/job-2022-05-11T09.58-a4cc1a6/job.log
(1/1) type_specific.io-github-autotest-libvirt.vsock.normal_test.hotplug.detach_device_alias.static_cid: PASS (69.92 s)
RESULTS    : **PASS** 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /var/lib/avocado/job-results/job-2022-05-11T09.58-a4cc1a6/results.html
JOB TIME   : 71.02 s …
> add case for Hotunplug vsock device by device alias

- libvirt/tests/src/libvirt_vcpu_plug_unplug.py
The pm setting should be enabled by s3/s4 related cases, hence
removing it from general test steps.
```
(01/39) type_specific.io-github-autotest-libvirt.libvirt_vcpu_plug_unplug.positive_test.vcpu_set.live.vm_operate.no_operation: PASS (66.05 s)
(02/39) type_specific.io-github-autotest-libvirt.libvirt_vcpu_plug_unplug.positive_test.vcpu_set.live.vm_operate.save: PASS (68.89 s)
(03/39) type_specific.io-github-autotest-libvirt.libvirt_vcpu_plug_unplug.positive_test.vcpu_set.live.vm_operate.managedsave: PASS (72.69 s)
(04/39) type_specific.io-github-autotest-libvirt.libvirt_vcpu_plug_unplug.positive_test.vcpu_set.live.vm_operate.suspend: PASS (63.41 s)
(05/39) type_specific.io-github-autotest-libvirt.libvirt_vcpu_plug_unplug.pos …
```
> cpu: Remove pm setting

- libvirt/tests/cfg/virtual_interface/hotplug_mem.cfg
- libvirt/tests/src/virtual_interface/hotplug_mem.py
- provider/interface/interface_base.py
This PR adds 'hostdev interface' and 'hostdev device' types test in
RHEL-283024: hotplug memory to vm with vdpa/hostdev type interface.
```
JOB ID     : b57739faae31a46edff35a76a7c65769b7559333
JOB LOG    : /root/avocado/job-results/job-2022-03-22T00.36-b57739f/job.log
(1/6) type_specific.io-github-autotest-libvirt.iface.hotplug_mem.at_memory_to_vm_with_iface.hostdev_device: PASS …
```
> hostdev: Add memory hot plugging cases

- libvirt/tests/cfg/numa/numa_memory_migrate.cfg
- libvirt/tests/src/numa/numa_memory_migrate.py
Hardcoded numa node limits the case's adaptibility on different
numa hosts. The enhancement will increase the adaptibilty with
dynamically setting the numa node.
Depends on https://github.com/avocado-framework/avocado-vt/pull/3378
> numa_memory_migrate: enhance to use available numa node

- libvirt/tests/cfg/virsh_cmd/domain/virsh_numatune.cfg
- libvirt/tests/src/virsh_cmd/domain/virsh_numatune.py
This is to enable all positive cases supporting dynamic numanode selection.
This enhancement will improve the cases to run with more numa hosts which
have different numa node configurations.
depends on https://github.com/avocado-framework/avocado-vt/pull/3378
> virsh_numatune: fix_numa_nodeset

- libvirt/tests/cfg/memory/nvdimm.cfg
- libvirt/tests/src/memory/nvdimm.py
- spell.ignore
Test scenario: support pmem, alignsize and readonly in nvdimm memory device
RHEL-160330
Depend on https://github.com/avocado-framework/avocado-vt/pull/3401
> nvdimm: add case for pmem and alignsize and readonnly

- libvirt/tests/src/virtual_device/vsock.py
Similar to #4212 
The [default 7s](https://github.com/avocado-framework/avocado-vt/blob/master/virttest/virsh.py#L1880-L1881) is not enough for `detach_device_alias` in case `rhel.vsock.normal_test.hotplug.detach_device_alias.static_cid` on ARM. I tested several times and it spent about 8.64s every time. This PR extends the `event_timeout` to 20s.
> vsock: Extend event_timeout for detach_device_alias

- libvirt/tests/src/virtual_network/iface_options.py
- libvirt/tests/src/virtual_network/iface_unprivileged.py
The vmxml of vm created by unprivileged user was copied from vm created
by root user. The nvram tag might contain path that unprivileged users
are not allowed to access. Therefore remove the tag and let libvirt to
create it automatically after define.
> iface_unprivileged:Remove nvram tag to avoid permission issue

- libvirt/tests/src/svirt/dac_nfs_save_restore.py
- libvirt/tests/src/svirt/dac_start_destroy.py
Destroy vm before other cleanup steps to avoid leaving VARS.fd
file which will cause permission issue in future tests.
> svirt:Destroy vm after test to avoid permission issue

- libvirt/tests/cfg/sriov/vm_lifecycle/sriov_vm_lifecycle_start_destroy.cfg
- libvirt/tests/src/sriov/vm_lifecycle/sriov_vm_lifecycle_start_destroy.py
- provider/sriov/check_points.py
- provider/sriov/sriov_base.py
This PR adds below case:
VIRT-292833 - Start vm with an hostdev device or hostdev interface
depends on https://github.com/autotest/tp-libvirt/pull/4120
```
(01/13) type_specific.io-github-autotest-libvirt.sriov.vm_lifecycle.start_destroy.hostdev_interface.vf_address.managed_yes: PASS (50.04 s)
(02/13) type_specific.io-github-autotest-libvirt.sriov.vm_lifecycle.start_destroy.hostdev_interface.vf_address.managed_no: PASS (50.23 s)
(03/13) type_specific.io-github-autotest-libvirt.sriov.vm_lifecycle.start_destroy.hostdev_interface.vf_address.without_managed: PASS (50.03 s)
(04/13) type_specific.io-github-autotest-libvirt.sriov.vm_lifecycle.start_destroy.hostdev_interface.vf_address.vlan: PASS (47.04 s)
(05/13) …
```
> sriov: Add a vm lifecycle case

- libvirt/tests/cfg/virsh_cmd/domain/virsh_emulatorpin.cfg
- libvirt/tests/src/virsh_cmd/domain/virsh_emulatorpin.py
Add case to start vm with cpuset config and live update emulatorpin
This case start guest with overall cpuset setting
but without emulatorpin setting, and check whether allowed list
is expected before and after live update emulatorpin.
Polarion ID:RHEL-114491
> Add case to start vm with cpuset config and live update emulatorpin

- libvirt/tests/cfg/migration/live_migration.cfg
- provider/migration/migration_base.py
To fix following error:
'host_device' driver requires
'/var/lib/libvirt/migrate/jeos-27-x86_64.qcow2' to be either
a character or block device
> live_migration: Fix wrong disk type

- libvirt/tests/src/virsh_cmd/domain/virsh_blockcopy.py
1.  Give different emulated_iamge name 
2.  Clean backingstore in snapxml  as feature owner required
```
(1/2) type_specific.io-github-autotest-libvirt.virsh.blockcopy.positive_test.non_acl.block_disk.disk_t.default.block_type.blockdev.shallow.pivot_option: PASS (246.27 s)
(2/2) type_specific.io-github-autotest-libvirt.virsh.blockcopy.positive_test.non_acl.block_disk.disk_t.default.volume_type.blockdev.shallow.pivot_option: PASS (296.28 s)
```
**Other related case**
Rerun job with this pr , **All Passed**
block_copy_shallow/12/
> virsh_blockcopy:fix selinux already in use

- libvirt/tests/src/usb_device.py
Use compatible search pattern for both json and old format of qemu cmd line.
> usb_device: fix with compatible match

- libvirt/tests/cfg/migration/migrate_service_control.cfg
Restart SRC libvirtd during Perform Phase of live migration.
> Add case about restart SRC libvirtd during migration

- libvirt/tests/cfg/virsh_cmd/domain/virsh_detach_device_alias.cfg
- libvirt/tests/src/virsh_cmd/domain/virsh_detach_device_alias.py
RHEL-148231: Detach virtual disk by alias with --live and --config
/usr/local/bin/avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 virsh.detach_device_alias..virtual_disk  --vt-connect-uri qemu:///system
(1/2) type_specific.io-github-autotest-libvirt.virsh.detach_device_alias.live.virtual_disk: PASS (53.09 s)
(2/2) type_specific.io-github-autotest-libvirt.virsh.detach_device_alias.config.virtual_disk: PASS (53.12 s)
> add case for detach virtual disk by alias

- libvirt/tests/cfg/virsh_cmd/domain/virsh_cpu_xml.cfg
- libvirt/tests/deps/caps_skylake_server_cascadelake_server.xml
- libvirt/tests/deps/domcaps_skylake_client_cascadelake_server.xml
- libvirt/tests/deps/domcaps_skylake_server_cascadelake_server.xml
- libvirt/tests/src/virsh_cmd/domain/virsh_cpu_xml.py
The test scenarios:
Between domcapabilities and capbilities xml for hosts with skylake and cascadelake cpu
, cpu_baseline and hypervisor_cpu_basline commands should return skylake cpu info(old cpu)
instead of cascadelake cpu info (new cpu).
> virsh_cpu_xml: add case comparing skylake cascadelake

- libvirt/tests/src/bios/virsh_boot.py
- libvirt/tests/src/bios/virsh_boot_tseg.py
For ovmf job, the previous script mainly depends on seabios os xml, which is different with ovmf os xml. So after we changing it to ovmf guest, the loader and nvram parts of os element wil affect some test cases, especially some negative cases. So here update the guest xml.
> ovmf: update the guest xml to keep consistent with the previous script

- provider/v2v_vmcheck_helper.py
When os_version is not set, the default value is None. This causes
the exception 'TypeError: argument of type 'NoneType' is not iterable'.
Let's set it to '' instead of None.
> v2v: fix nonetype iteration issue

- libvirt/tests/cfg/memory/memory_misc.cfg
- libvirt/tests/src/memory/memory_misc.py
The old way of comparing 2 xmls could get incorrect result of test.
We'll only compare the setup values instead of the whole xml object.
> memory_misc:update comparing method of 2 xmls

- libvirt/tests/cfg/migration/sriov_migrate.cfg
- libvirt/tests/src/migration/sriov_migrate.py
As the existing bug 1789206 block the checkpoints, skip it in
current cases, and add 2 more case which will fail by this checkpoint
to track the bug status.
> Skip one checkpoints for some cases

- libvirt/tests/cfg/memory/memory_misc.cfg
- libvirt/tests/src/memory/memory_misc.py
- Start a vm with hugepage memory preallocated by multiple threads
depends on https://github.com/avocado-framework/avocado-vt/pull/3418
> Add new case of memorybacking

- libvirt/tests/src/migration/migrate_event.py
Fix a OSError as follows:
[stderr] Exception in thread tail_thread_I1QJja8d_virsh -c q:
[stderr] Traceback (most recent call last):
[stderr]   File "/usr/lib64/python3.6/threading.py", line 937, in _bootstrap_inner
[stderr]     self.run()
[stderr]   File "/usr/lib64/python3.6/threading.py", line 885, in run
[stderr]     self._target(*self._args, **self._kwargs)
[stderr]   File "/usr/local/lib/python3.6/site-packages/aexpect/client.py", line 650, in _tail
[stderr]     _print_line(line)
[stderr]   File "/usr/local/lib/python3.6/site-packages/aexpect/client.py", line 615, in _print_line
[stderr]     self.output_func(*out_params)
[stderr]   File "/var/tmp/libvirt-ci/runtest/avocado-vt/avocado-vt/virttest/utils_misc.py", line 448, in log_line
[stderr]     _open_log_files[base_file].flush() …
> migrate_event: Fix OSError

- v2v/tests/src/specific_kvm.py
The default 'avocado-vt-vm1' guest was changed to q35+uefi in
RHEL9.1. This change impacts the expected boottype value in v2v
tests which are using 'avocado-vt-vm1' as default main_vm.
> v2v: fix wrong expected boottype value in RHEL9.1

- libvirt/tests/src/conf_file/sysconfig_libvirt_guests/libvirt_guests.py
To avoid list out of range error if the output is not expected.
> libvirt_guests:Check the lenth of list before getting its item

- libvirt/tests/cfg/backingchain/blockjob_options.cfg
- libvirt/tests/src/backingchain/blockjob_options.py
Test sometimes fails on pseries because of a short delay. Set a
timeout for the case and allow the short delay and the problem
is gone.
> blockjob_options:Set timeout to wait for blockjob to be aborted

- libvirt/tests/cfg/backingchain/blockcommit/blockcommit_conventional_chain.cfg
- libvirt/tests/src/backingchain/blockcommit/blockcommit_conventional_chain.py
- provider/backingchain/blockcommand_base.py
- provider/backingchain/check_functions.py
- provider/virtual_disk/disk_base.py
Add case for modular redesign backingchain 
Case id: VIRT-292832
[root@dell-per730-62 tp-libvirt]# /**usr/local/bin/avocado run --vt-type libvirt --vt-machine-type q35 backingchain.blockcommit.conventional_chain --vt-connect-uri qemu:///system**
JOB ID     : 291a6f75d12ea9734925f93c6eb0e4a2286e8e97
JOB LOG    : /root/avocado/job-results/job-2022-04-25T07.23-291a6f7/job.log
(01/20) …
> Add case for modular redesign backingchain

- libvirt/tests/cfg/memory/memory_misc.cfg
BIOS serial console only supported on x86 architectures
> memory_misc:Remove unsupported tests from other archs

- libvirt/tests/src/backingchain/virtual_disks_blockcopy_options.py
- libvirt/tests/src/lxc/lxc_life_cycle.py
- libvirt/tests/src/multifunction.py
- libvirt/tests/src/numa/numa_preferred_undefine.py
- libvirt/tests/src/passthrough/pci/vfio.py
- libvirt/tests/src/svirt/svirt_start_destroy.py
- libvirt/tests/src/svirt/svirt_undefine_define.py
- libvirt/tests/src/virsh_cmd/domain/virsh_define.py
- libvirt/tests/src/virsh_cmd/domain/virsh_domif_setlink_getlink.py
- libvirt/tests/src/virsh_cmd/domain/virsh_event.py
- libvirt/tests/src/virsh_cmd/domain/virsh_managedsave.py
- libvirt/tests/src/virsh_cmd/domain/virsh_migrate_virtio_scsi.py
- libvirt/tests/src/virsh_cmd/domain/virsh_qemu_agent_command.py
- libvirt/tests/src/virsh_cmd/domain/virsh_undefine.py
- libvirt/tests/src/virsh_cmd/domain/virsh_vcpucount.py
- libvirt/tests/src/virsh_cmd/network/virsh_net_destroy.py
- libvirt/tests/src/virtual_disks/virtual_disks_luks.py
- libvirt/tests/src/virtual_network/iface_unprivileged.py
--nvram is needed for ovmf guest from RHEL 9.x. And it also does not have side effect
on seabios guest. This option was supported since RHEL7.x which is enough old. The
assumption is that it is no value to test RHEL6 host with libvirt.
Depend on https://github.com/avocado-framework/avocado-vt/pull/3423
> fix to use --nvram in virsh undefine

- libvirt/tests/cfg/libvirt_rng.cfg
- libvirt/tests/src/libvirt_rng.py
… /dev/urandom
A new automation scirpt is added one that adds automation for checking
RNG device.
We need to improve our test coverage when attaching random number generation devices. Previously we did not check with enough detail.
The polarion case that is being automated is [VIRT-98310](https://polarion.engineering.redhat.com/polarion/#/project/RHELVIRT/workitem?id=VIRT-98310).
Jira Case: https://issues.redhat.com/browse/LIBVIRTAT-12924
Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1347642
Test results:
```
No python imaging library installed. PPM image conversion to JPEG disabled. In order to …
```
> libvirt_rng: Add case for virtio-rng device /dev/urandom backend

- libvirt/tests/cfg/virsh_cmd/domain/virsh_detach_device_alias.cfg
- libvirt/tests/src/virsh_cmd/domain/virsh_detach_device_alias.py
RHEL-148232:Detach device by 'virsh detach-device-alias' cmd while use network interface
Depend on https://github.com/avocado-framework/avocado-vt/pull/3420 
[root@dell-per740-07 tp-libvirt]# **/usr/local/bin/avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 virsh.detach_device_alias.live.network_interface  --vt-connect-uri qemu:///system**
(1/1) type_specific.io-github-autotest-libvirt.virsh.detach_device_alias.live.network_interface: PASS (64.74 s)
RESULTS    : **PASS 1** | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /var/lib/avocado/job-results/job-2022-05-20T03.52-72c27c7/results.html
[root@dell-per740-07 tp-libvirt]# **/usr/local/bin/avocado run --vt-type libvirt --test-runner=runner …
> Add case for detach virtual network interface by alias

- libvirt/tests/cfg/virtual_disks/virtual_disks_ccw_addr.cfg
Despite their name, these tests are meant to be run
on a system that uses PCI per default and check their behaviour.
Almost all of these tests are negative. They do not apply
to s390x where CCW is the default. Therefore, disable them.
> virtual_disks.ccw_addr: disable tests on s390x

- libvirt/tests/cfg/virsh_cmd/domain/virsh_setmem.cfg
s390x uses bus ccw; fix cmdline check accordingly.
> virsh_setmem: fix cmdline for s390x

- libvirt/tests/cfg/virsh_cmd/domain/virsh_cpu_xml.cfg
On s390x, the virsh commands 'cpu-baseline' and 'cpu-compare'
are not valid. Instead, use 'hypervisor-cpu-baseline' and
'hypervisor-cpu-compare'. Correspondingly, filter test cases.
> virsh_cpu_xml: disable test cases for s390x

- libvirt/tests/cfg/memory/memory_discard.cfg
Test cases require memory hotplug which is not
supported on s390x at this point.
> memory_discard: disable tests on s390x

- libvirt/tests/cfg/memory/memory_misc.cfg
On s390x, no DIMM or NUMA support. Therefore, disable
test cases.
> memory_misc: disable test cases on s390x

- libvirt/tests/cfg/memory/hmat.cfg
The test suite requires NUMA which is not available
on s390x. Disable test cases.
> hmat: disable tests on s390x

- libvirt/tests/cfg/libvirt_cputune.cfg
On s390x,
- cpu flag 'mba' is not available
- numad is not supported by libvirt
Disable tests accordingly.
> libvirt_cputune: disable tests on s390x

- libvirt/tests/cfg/libvirt_vcpu_plug_unplug.cfg
The test case requires a vcpu hot-unplug which is
not supported on s390x.
> libvirt_vcpu_plug_unplug: disable test on s390x

- libvirt/tests/src/migration/network_data_transports/migration_network_data_transports_tcp.py
- provider/migration/migration_base.py
TypeError: setup_conn_obj() missing 1 required positional
argument: 'test'
> migration: Fix a TypeError

- libvirt/tests/src/virtual_disks/virtual_disks_multidisks.py
1. Remove 'scsi=off' from check: It's the default value and
recent libvirt versions don't set it explicitly anymore,
s. also 435fc297e505412dd25e6b7acfa33486b8c97bcd
In the team we agreed that the qemu commandline does not
need to be checked in general. So, relax the expression
searched for to reduce brittleness and avoid libvirt
version specific code.
2. Remove dead code: There was code below the first condition
where it checks for arch == s390x. That code could never
have been executed because the block requires device bus
to be 'virtio'.
> virtual_disks_multidisks: fix virtio bus check on s390x

- libvirt/tests/src/virsh_cmd/domain/virsh_attach_device_matrix.py
After OVMF as default bios setting, VM undefine need use --nvram option
> Fix attach device matrix failure due to vm.undefine

- libvirt/tests/src/virsh_cmd/domain/virsh_change_media_matrix.py
After OVMF as default bios setting, VM undefine need use --nvram option
> Fix virsh change_media_matrix cases failure due to vm.undefine

- libvirt/tests/src/virsh_cmd/domain/virsh_detach_device_alias.py
use wrong function , due to merge without depend on pr
avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 virsh.detach_device_alias.live.network_interface --vt-connect-uri qemu:///system
JOB ID     : d0d1a1bf26fb7ffb663787aab92d91214b1bd115
JOB LOG    : /var/lib/avocado/job-results/job-2022-06-15T02.08-d0d1a1b/job.log
(1/1) type_specific.io-github-autotest-libvirt.virsh.detach_device_alias.live.network_interface: PASS (56.47 s)
> virsh_detach_device_alias.py:fix detach iface alias error

- libvirt/tests/src/virsh_cmd/domain/virsh_blockcopy.py
need nvram option while undefine
```
avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 virsh.blockcopy.positive_test.non_acl.block_disk.disk_t.default.block_type.no_blockdev.no_shallow.mirror_state_lock --vt-connect-uri qemu:///system
(1/1) type_specific.io-github-autotest-libvirt.virsh.blockcopy.positive_test.non_acl.block_disk.disk_t.default.block_type.no_blockdev.no_shallow.mirror_state_lock: PASS (60.12 s)
(1/1) type_specific.io-github-autotest-libvirt.virsh.blockcopy.positive_test.non_acl.block_disk.disk_t.default.volume_type.no_blockdev.shallow.no_option: PASS (142.91 s)
(1/1) type_specific.io-github-autotest-libvirt.virsh.blockcopy.positive_test.non_acl.block_disk.disk_t.default.volume_type.no_blockdev.no_shallow.mirror_ …
```
> fix blockcopy job undefine with --nvram option

- libvirt/tests/src/virsh_cmd/domain/virsh_update_device_matrix.py
- libvirt/tests/src/virtual_disks/virtual_disks_ceph.py
Add '--nvram' option in case of the following undefine failure
for VM with UEFI:
error: Failed to undefine domain 'avocado-vt-vm1'
error: Requested operation is not valid: cannot undefine domain with nvram
> libvirt: Add '--nvram' option to vm.undefine

- libvirt/tests/src/virsh_cmd/domain/virsh_attach_detach_disk_matrix.py
Need add '--nvram' option when undefine VM
> Fix attach detach_disk matrix cases failure due to undefine VM

- libvirt/tests/src/backingchain/blockcopy.py
- libvirt/tests/src/virsh_cmd/domain/virsh_blockjob.py
need  nvram option
```
avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 backingchain.blockcopy.positive_test.reuse_external --vt-connect-uri qemu:///system
(1/1) type_specific.io-github-autotest-libvirt.backingchain.blockcopy.positive_test.reuse_external: PASS (10.59 s)
```
> blockcopy, virsh_blockjob :fix undefine domain with nvram

- v2v/tests/cfg/specific_kvm.cfg
- v2v/tests/src/v2v_options.py
1. The way of creating corrupt rpmdb in avocado-vt-vm1 doesn't work
since RHEL9.1(maybe?). See developer's comment:
https://bugzilla.redhat.com/show_bug.cgi?id=2089623#c12
So we use a rhel8 guest in esx server to test this case.
2. Extend the timeout of waiting for import images.
> v2v: update corrupt rpmdb guest source and fix import timeout issue

- libvirt/tests/src/virsh_cmd/domain/virsh_domrename.py
the new created ovmf guest undefine would be failed without “--nvarm” and affect other cases. 
Signed-off-by: zhentang <zhetang@redhat.com>
> fix virsh_domerename failed cases by add '--nvram' in virsh undefine

- libvirt/tests/cfg/virsh_cmd/domain/virsh_emulatorpin_mix.cfg
- libvirt/tests/src/virsh_cmd/domain/virsh_emulatorpin_mix.py
Add new case to check whether the commands which not require
cgroup will work well when disable them in configure file.
Polarion ID:RHEL7-19570
> Add case to check commands work well when disable cpuset 

- libvirt/tests/cfg/migration/migrate_over_unix.cfg
- libvirt/tests/src/migration/migrate_over_unix.py
1. Add stress to in vm for postcopy tests to slow down migration
further; otherwise, the migration might finish before test
sockets can be checked. Don't do this when migrating without
postcopy as it will prevent migration from converging.
2. Retry socket check in case it fails initially.
3. Move part of the socket check comman into python code for
easier debugging in case the check fails.
4. Reduce bandwidth a bit further to give test more time to
check sockets.
> migrate_over_unix: stabilize postcopy tests

- libvirt/tests/cfg/sriov/vm_lifecycle/direct_passthrough_vm_lifecycle_start_destroy.cfg
- libvirt/tests/cfg/sriov/vm_lifecycle/sriov_vm_lifecycle_iommu_at_dt_hostdev.cfg
- libvirt/tests/src/sriov/sriov_vf_pool.py
- libvirt/tests/src/sriov/vm_lifecycle/direct_passthrough_vm_lifecycle_start_destroy.py
- libvirt/tests/src/sriov/vm_lifecycle/sriov_vm_lifecycle_iommu_at_dt_hostdev.py
- provider/sriov/check_points.py
- provider/sriov/sriov_base.py
This PR adds:
1. VIRT-293144 - Start vm with direct type + passthrough mode
interface with vf
2. VIRT-293920 - Start vm with IOMMU device and hostdev
interface/device, hotunplug and hotplug
BTW, refactor the code for check_vm_network_accessed and default
setup/teardown changes.
**Depends on**: https://github.com/avocado-framework/avocado-vt/pull/3421
**Test results:**  The failed case is caused by a known issue.
```
(1/3) type_specific.io-github-autotest-libvirt.direct_passthrough.vm_lifecycle.start_destroy.direct_interface.vf_name.default: PASS (49.72 s)
(2/3) type_specific.io-github-autotest-libvirt.direct_passthrough.vm_lifecycle.start_destroy.direct_interface.vf_name.vlan: FAIL: Unable to get vlan value from 'ip l show enp59s0f0 '! (43.82 …
```
> sriov: Add 2 cases about vm lifecycle

- libvirt/tests/cfg/sriov/vm_lifecycle/sriov_vm_lifecycle_reboot.cfg
- libvirt/tests/cfg/sriov/vm_lifecycle/sriov_vm_lifecycle_suspend_resume.cfg
- libvirt/tests/src/sriov/vm_lifecycle/sriov_vm_lifecycle_reboot.py
- libvirt/tests/src/sriov/vm_lifecycle/sriov_vm_lifecycle_suspend_resume.py
This PR adds:
VIRT-293134 - Reboot vm with a hostdev interface/device
VIRT-292863 - Suspend and resume vm with an interface/device
of hostdev type
**depends on:** https://github.com/autotest/tp-libvirt/pull/4253
**test results:**
```
(01/16) type_specific.io-github-autotest-libvirt.sriov.vm_lifecycle.suspend_resume.hostdev_interface.vf_address.managed_yes.with_iommu: PASS (167.29 s)
(02/16) type_specific.io-github-autotest-libvirt.sriov.vm_lifecycle.suspend_resume.hostdev_interface.vf_address.managed_yes.without_iommu: PASS (45.65 s)
(03/16) type_specific.io-github-autotest-libvirt.sriov.vm_lifecycle.suspend_resume.hostdev_interface.vf_address.managed_no.without_iommu: PASS (45.50 s)
(04/16) …
```
> sriov: Add reboot/suspend_resume cases

- libvirt/tests/src/virtio_transitional/virtio_transitional_base.py
- libvirt/tests/src/virtio_transitional/virtio_transitional_blk.py
- libvirt/tests/src/virtio_transitional/virtio_transitional_blk_negative.py
- libvirt/tests/src/virtio_transitional/virtio_transitional_mem_balloon.py
- libvirt/tests/src/virtio_transitional/virtio_transitional_nic.py
- libvirt/tests/src/virtio_transitional/virtio_transitional_rng.py
- libvirt/tests/src/virtio_transitional/virtio_transitional_serial.py
- libvirt/tests/src/virtio_transitional/virtio_transitional_vsock.py
The rhel6 guest should not be configured with nvram options, so
removing it in this PR.
```
05/38) type_specific.io-github-autotest-libvirt.virtio_transitional_rng.rhel6_guest.default.boot_test.virtio_transitional: PASS (49.53 s)
(06/38) type_specific.io-github-autotest-libvirt.virtio_transitional_rng.rhel6_guest.default.hotplug_test.virtio_transitional: PASS (113.63 s)
(07/38) type_specific.io-github-autotest-libvirt.virtio_transitional_rng.rhel6_guest.with_pcie_to_pci_bridge.boot_test.virtio: PASS (115.00 s)
(08/38) type_specific.io-github-autotest-libvirt.virtio_transitional_rng.rhel6_guest.with_pcie_to_pci_bridge.boot_test.virtio_transitional: PASS (123.79 s)
(09/38) …
```
> virtio_transitional: Remove nvram setting for rhel6 guest

- libvirt/tests/src/migration/migrate_with_legacy_guest.py
The nvram settings should be removed for rhel6 guest.
```
(17/38) type_specific.io-github-autotest-libvirt.virsh.migrate_with_legacy_guest.test_interface.rhel6_guest.virtio_transitional: PASS (188.88 s)
(18/38) type_specific.io-github-autotest-libvirt.virsh.migrate_with_legacy_guest.test_disk.with_virtio_scsi.disk_raw.rhel6_guest.unspecified_model: PASS (245.39 s)
(19/38) type_specific.io-github-autotest-libvirt.virsh.migrate_with_legacy_guest.test_disk.with_virtio_blk.disk_qcow2.rhel6_guest.virtio_transitional: PASS (244.68 s)
(20/38) type_specific.io-github-autotest-libvirt.virsh.migrate_with_legacy_guest.test_memballoon.rhel6_guest.virtio_transitional: PASS (198.04 s)
(21/38) …
```
> migration: Remove nvram for rhel6 guest

- virttools/tests/src/virt_install/kernel_cmdline.py
The last test runs failed although the failure message confirmed
the status was correct. It seemed this was a type issue.
Cast all values in test condition to string to make sure type
issue cannot occur.
> virttools/virt_install.kernel_cmdline: fix test condition

- libvirt/tests/cfg/memory/memory_update_device.cfg
- libvirt/tests/src/memory/memory_update_device.py
```
JOB ID     : 63f5a58222b3464e341fcb5ad1e73ac41ecc3da6
JOB LOG    : /root/avocado/job-results/job-2022-06-24T04.56-63f5a58/job.log
(1/1) type_specific.io-github-autotest-libvirt.memory_update_device.virtio_mem: STARTED
(1/1) type_specific.io-github-autotest-libvirt.memory_update_device.virtio_mem: PASS (109.37 s)
JOB HTML   : /root/avocado/job-results/job-2022-06-24T04.56-63f5a58/results.html
JOB TIME   : 113.73 s
```
> memory_update_device: Enable test on aarch64

- libvirt/tests/src/virtual_disks/at_dt_iscsi_disk.py
Fix qemu command line output change issue due to json format as default
driver_packed value change from on|off to true|false, and key=value equation become key: value format
those checking operation is already covered in libvirt upstream CI test[1] ,so remove qemu command line checking here
[1]https://gitlab.com/libvirt/libvirt/-/blob/master/tests/qemuxml2argvdata/virtio-options-disk-packed.x86_64-latest.args
> Fix qemu command line output change issue due to json format as default

- libvirt/tests/cfg/migration/migrate_options_shared.cfg
The default log_filters is "2:\*" if the `log_level` is not assigned with `libvirtd_debug_level`.
Specify `log_filters` as "1:\*" to get the debug log "qemuProcessHandleMigrationStatus" in /var/log/libvirt/libvirtd.log
Before:
```
JOB ID     : a1a4c9cf6e55031741a7e0d73b510944590088af                                                                                                                                                                                         
JOB LOG    : /var/lib/avocado/job-results/job-2022-06-23T05.20-a1a4c9c/job.log                                                                                                                                                                
(1/1) …
```
> migration: specify log_filters as "1:*" of some case

- libvirt/tests/cfg/backingchain/blockcommit/blockcommit_all_block_chain.cfg
- libvirt/tests/src/backingchain/blockcommit/blockcommit_all_block_chain.py
- provider/backingchain/blockcommand_base.py
add case for backingchain modular redesign: blockcommit with all block chain
**VIRT-293510:** Do shallow active/inactive blockcommit with all block disks in chain
**Two scenarios:**
1. Do shallow inactive blockcommit : **Failed**, Expected chain is incorrect , confirmed with meina and she filed this bug [2094205](https://bugzilla.redhat.com/show_bug.cgi?id=2094205 ), 
```
avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 backingchain.blockcommit.all_block_chain.shallow_inactive
(1/1) backingchain.blockcommit.all_block_chain.shallow_inactive: FAIL: Expect source file to be ['/dev/vg0/lv4', '/dev/vg0/lv3', '/dev/vg0/lv2', '/dev/vg0/lv0'], but got ['/dev/vg0/lv4', '/dev/vg0/lv3', '/dev/vg0/lv2', '/dev/vg0/lv1', '/dev/vg0/lv0'] …
```
> add case for backingchain modular redesign: blockcommit with all block chain

- libvirt/tests/cfg/virtual_device/tpm_device.cfg
- libvirt/tests/src/virtual_device/tpm_device.py
Use tpm_testsuite_url instead to download from internal
server. It will speed up downloads. And we can manage test suite
updating to required version at specific time after manual test
succeed, which are all transparent to tp-libvirt code.
> tpm_device: use tpm_testsuite_url to download

- libvirt/tests/src/virsh_cmd/domain/virsh_attach_detach_interface_matrix.py
Update the vm.undefine() to vm.undefine(options='--nvram') to
adapt to ovmf guest. And it works well for pc guest, too.
> Update the vm.undefine() to adapt to ovmf guest

- libvirt/tests/src/migration/migrate_vm.py
> migration: Fix undefine VM failure

- libvirt/tests/cfg/backingchain/blockcopy/blockcopy_with_backingfile.cfg
- libvirt/tests/src/backingchain/blockcopy/blockcopy_with_backingfile.py
- provider/backingchain/blockcommand_base.py
- provider/virtual_disk/disk_base.py
VIRT-293778:  Do blockcopy with --shallow and --reuse-external option to file/block destination with backing file
```
/usr/local/bin/avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 backingchain.blockcopy.blockcopy_with_backingfile.shallow_and_reuse_external
(1/2) type_specific.io-github-autotest-libvirt.backingchain.blockcopy.blockcopy_with_backingfile.shallow_and_reuse_external.file_disk.pivot_after_blockcopy: PASS (24.03 s)
(2/2) type_specific.io-github-autotest-libvirt.backingchain.blockcopy.blockcopy_with_backingfile.shallow_and_reuse_external.file_disk.abort_after_blockcopy: PASS (17.06 s)
(3/4)type_specific.io-github-autotest-libvirt.backingchain.blockcopy.blockcopy_with_backingfile.shallow_and_reuse_ex …
```
> add case for blockcopy with backingfile

- libvirt/tests/src/virtual_network/iface_options.py
For OVMF guest, without the "--nvram" option, domain can not be
removed successfully. Then the domain will be kept and it may
interfere futher cases.
> Add "--nvram" to the virsh.remove_domain()

- libvirt/tests/src/virtual_network/iface_network.py
When undefine an ovmf guest, it needs the option "--nvram". Otherwise
the guest will not be removed successfully.
> Add "--nvram" to virsh.remove_domain()

- libvirt/tests/src/virsh_cmd/domain/virsh_change_media_matrix.py
Fix virsh change-media failure after creating transient VM
Change media operation need to be applied after VM completely booted
Fix this issue by adding check whether VM completely booted after transient VM is created
> Fix virsh change-media failure after creating transient VM

- libvirt/tests/cfg/memory/memory_misc.cfg
- libvirt/tests/src/memory/memory_misc.py
- Check the memory balloon size after restoring a managed save guest
> Add new case of memory and replace logging with test.log

- libvirt/tests/cfg/sriov/vm_lifecycle/sriov_vm_lifecycle_managedsave.cfg
- libvirt/tests/cfg/sriov/vm_lifecycle/sriov_vm_lifecycle_unmanaged.cfg
- libvirt/tests/src/sriov/vm_lifecycle/sriov_vm_lifecycle_managedsave.py
- libvirt/tests/src/sriov/vm_lifecycle/sriov_vm_lifecycle_unmanaged.py
This PR adds:
1. VIRT-293788 - Start vm with hostdev interface/device with
managed=no or ignored
2. VIRT-293133 - Managedsave vm with a hostdev interface/device
```
(1/2) type_specific.io-github-autotest-libvirt.sriov.vm_lifecycle.managedsave.hostdev_interface.vf_address.managed_yes: PASS (42.46 s)
(2/2) type_specific.io-github-autotest-libvirt.sriov.vm_lifecycle.managedsave.hostdev_device.vf_address.managed_yes: PASS (41.79 s)
(01/14) type_specific.io-github-autotest-libvirt.sriov.vm_lifecycle.unmanaged.cold_plug.hostdev_interface.vf_address.managed_no: PASS (15.35 s)
(02/14) type_specific.io-github-autotest-libvirt.sriov.vm_lifecycle.unmanaged.cold_plug.hostdev_interface.vf_address.without_managed: PASS (15.54 s)
(03/14) …
```
> sriov: Add cases about managedsave and unmanaged

- libvirt/tests/cfg/migration/memory_copy_mode/migration_memory_copy_mode_postcopy.cfg
- libvirt/tests/cfg/migration/memory_copy_mode/migration_memory_copy_mode_precopy.cfg
- libvirt/tests/src/migration/memory_copy_mode/migration_memory_copy_mode.py
Add two cases:
1. VIRT-293931 - VM live migration - precopy + p2p/non-p2p
2. VIRT-293930 - VM live migration - postcopy
> migration: Add cases about memory copy mode

- libvirt/tests/cfg/backingchain/blockpull/blockpull_conventional_chain.cfg
- libvirt/tests/src/backingchain/blockpull/blockpull_conventional_chain.py
- provider/backingchain/check_functions.py
VIRT-294004: Do blockpull for conventional chain
```
[root@dell-per730-59 ~]# /usr/local/bin/avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 backingchain.blockpull.conventional_chain
(1/6) type_specific.io-github-autotest-libvirt.backingchain.blockpull.conventional_chain.file_disk.with_base: PASS (20.72 s)
(2/6) type_specific.io-github-autotest-libvirt.backingchain.blockpull.conventional_chain.file_disk.without_base: PASS (22.02 s)
(3/6) type_specific.io-github-autotest-libvirt.backingchain.blockpull.conventional_chain.block_disk.with_base: PASS (44.13 s)
(4/6) type_specific.io-github-autotest-libvirt.backingchain.blockpull.conventional_chain.block_disk.without_base: PASS (44.78 s)
(5/6) …
```
> add case for backingchain modular design: blockpull convention chain

- libvirt/tests/cfg/conf_file/systemd_config/systemd_config.cfg
- libvirt/tests/src/conf_file/systemd_config/systemd_config.py
Add testcase for systemd config file:
1.Automation for case VIRT-19536.
2.Test result:
$ avocado run systemd_config --vt-type libvirt
JOB ID     : 88e39df5cfea6dd1f38ebb44a995e2346bf5e7ff
JOB LOG    : /var/lib/avocado/job-results/job-2022-05-19T22.50-88e39df/job.log
(01/11) type_specific.io-github-autotest-libvirt.conf_file.systemd_config.set_exec_args.daemon_mode.modular_daemon.virtqemud: STARTED
(01/11) …
> Add testcase for systemd config file

- libvirt/tests/cfg/backingchain/blockcommit/blockcommit_with_delete_option.cfg
- libvirt/tests/src/backingchain/blockcommit/blockcommit_with_delete_option.py
- provider/backingchain/blockcommand_base.py
VIRT-293928: Do blockcommit with --delete option
```
[root@cloud-qe-02 tp-libvirt]# /usr/local/bin/avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 backingchain.blockcommit.delete_option.file_disk
(1/4) type_specific.io-github-autotest-libvirt.backingchain.blockcommit.delete_option.file_disk.mid_to_mid: PASS (33.85 s)
(2/4) type_specific.io-github-autotest-libvirt.backingchain.blockcommit.delete_option.file_disk.top_to_base: PASS (39.77 s)
(3/4) type_specific.io-github-autotest-libvirt.backingchain.blockcommit.delete_option.file_disk.top_to_mid: PASS (45.95 s)
(4/4) type_specific.io-github-autotest-libvirt.backingchain.blockcommit.delete_option.file_disk.mid_to_base: PASS (41.86 s)
```
> add case for blockcommit with delete option

- libvirt/tests/cfg/virsh_cmd/domain/virsh_detach_device_alias.cfg
- libvirt/tests/src/virsh_cmd/domain/virsh_detach_device_alias.py
RHEL-148239: Rng device can be detached by alias through 'virsh detach-device-alias' cmd
```
/usr/local/bin/avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 virsh.detach_device_alias..rng
(1/2) type_specific.io-github-autotest-libvirt.virsh.detach_device_alias.live.rng: PASS (33.60 s)
(2/2) type_specific.io-github-autotest-libvirt.virsh.detach_device_alias.config.rng: PASS (24.11 s)
```
> add case for detach rng with alias

- libvirt/tests/cfg/memory/memory_misc.cfg
Enable managedsave test for rhel8.7 aarch64:
1. Set cpu mode as host-passthrough for aarch64.
2. Update currentMemory to a multiple of 64 as the pagesize of rhel8.7 aarch64 is 64 KiB.
Test result:
(1/1) type_specific.io-github-autotest-libvirt.memory_misc.managedsave.size_check: PASS (47.40 s)
> memory_misc: Enable managedsave test for aarch64

- libvirt/tests/cfg/virtual_device/virtio_rng.cfg
- libvirt/tests/src/virtual_device/virtio_rng.py
- provider/virtio_rng/check_points.py
This test file serves to test RHEL-112408 as well as a basis for
migration of other RNG device tests.
The case simply tests if a rng device can be cold-plugged and unplugged.
```
[root@dell-per740xd-08 tp-libvirt]# avocado run --vt-type libvirt virtio_rng.coldplug_unplug
JOB ID     : a7ae71091be689c14338ab0b48111ddc1b224c73
JOB LOG    : /var/lib/avocado/job-results/job-2022-06-24T13.52-a7ae710/job.log
(1/1) …
```
> virtio_rng: Cold-plug/unplug a random backend virtio-rng device	

- libvirt/tests/src/virtual_device/tpm_device.py
Fix a 'Please provide the URL EXAMPLE_UEFI_DISK_URL' error due to
'nvram' not found by also searching 'efi' since new feature.
And fix a 'TPM result for CMD_INIT: 0x101' error of vm start failure
due to an default tpm exists by adding xml.sync() after remove all
previous tpm.
> tpm_device: fix nvram find and vm start failures

- libvirt/tests/src/virtual_device/tpm_device.py
Change a way to find 'nvram' or 'efi' for uefi guest xml. Previous
one fails sometimes.
> tpm_device: fix nvram find method

- libvirt/tests/cfg/backingchain/blockcommit/blockcommit_conventional_chain.cfg
- libvirt/tests/src/backingchain/blockcommit/blockcommit_conventional_chain.py
- provider/virtual_disk/disk_base.py
rbd disk qemu-img hung for long time due to no keyring
```
/usr/local/bin/avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 backingchain.blockcommit.conventional_chain.rbd_with_auth_disk  --vt-connect-uri qemu:///system
(1/4)backingchain.blockcommit.conventional_chain.rbd_with_auth_disk.mid_to_mid: PASS (34.56 s)
(2/4)backingchain.blockcommit.conventional_chain.rbd_with_auth_disk.top_to_base: PASS (32.09 s)
(3/4)backingchain.blockcommit.conventional_chain.rbd_with_auth_disk.top_to_mid: PASS (32.21 s)
(4/4)backingchain.blockcommit.conventional_chain.rbd_with_auth_disk.mid_to_base: PASS (32.81 s)
```
> fix qemu-img --backingchain hung error

- libvirt/tests/cfg/backingchain/blockcommit/blockcommit_with_bandwith.cfg
- libvirt/tests/src/backingchain/blockcommit/blockcommit_with_bandwith.py
VIRT-293987: Do blockcommit with  [bandwidth] or --bytes options:
```
[root@cloud-qe-02 avocado-vt]# /usr/local/bin/avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 backingchain.blockcommit.with_bandwith
(1/4) type_specific.io-github-autotest-libvirt.backingchain.blockcommit.with_bandwith.positive_test.bandwith_mb: PASS (29.10 s)
(2/4) type_specific.io-github-autotest-libvirt.backingchain.blockcommit.with_bandwith.positive_test.bandwith_bytes: PASS (37.63 s)
(3/4) type_specific.io-github-autotest-libvirt.backingchain.blockcommit.with_bandwith.negative_test.invalid_str: PASS (41.48 s)
(4/4) type_specific.io-github-autotest-libvirt.backingchain.blockcommit.with_bandwith.negative_test.invalid_int: PASS (48.77 s) …
```
> add case for blockcommit with setting bandwith

- libvirt/tests/cfg/backingchain/blockcommit/blockcommit_with_async_option.cfg
- libvirt/tests/src/backingchain/blockcommit/blockcommit_with_async_option.py
VIRT-293141:Do blockcommit with --async options
```
avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 backingchain.blockcommit.async_option.file_disk
(1/2) type_specific.io-github-autotest-libvirt.backingchain.blockcommit.async_option.file_disk.async: PASS (14.38 s)
(2/2) type_specific.io-github-autotest-libvirt.backingchain.blockcommit.async_option.file_disk.async_timeout: PASS (21.33 s)
```
> add case for blockcommit with async option

- libvirt/tests/cfg/memory/memory_misc.cfg
- libvirt/tests/src/memory/memory_misc.py
- Start vm with or hotplug memory device backed by hugepages without
hugepage memoryBacking- bug 1455819
> Add new case of memory

- libvirt/tests/cfg/sriov/vm_lifecycle/sriov_vm_lifecycle_start_negative.cfg
- libvirt/tests/src/sriov/vm_lifecycle/sriov_vm_lifecycle_start_negative.py
VIRT-293914 - Start vm with hostdev interface/device - some negative scenarios
**depends on:** https://github.com/avocado-framework/avocado-vt/pull/3456
```
(1/8) type_specific.io-github-autotest-libvirt.sriov.vm_lifecycle.start.negative.hostdev_interface.vlan_trunk: PASS (16.39 s)
(2/8) type_specific.io-github-autotest-libvirt.sriov.vm_lifecycle.start.negative.hostdev_interface.inactive_pf: PASS (16.50 s)
(3/8) type_specific.io-github-autotest-libvirt.sriov.vm_lifecycle.start.negative.hostdev_interface.inactive_network: PASS (17.02 s)
(4/8) type_specific.io-github-autotest-libvirt.sriov.vm_lifecycle.start.negative.hostdev_interface.pf_address: PASS (16.43 s)
(5/8) type_specific.io-github-autotest-libvirt.sriov.vm_lifecycle.s …
```
> sriov: Add a negative lifecycle case

- libvirt/tests/src/virsh_cmd/domain/virsh_blockcommit.py
When we remove --pivot option in virsh blockommit, the blockjob will always have an active job there. Then we can get the expected error info in this negative scenario. But if we use --pivot option, it may execute so quickly that it's hard to get error info, we can only get: ......expect fail, but run successfully. 
> virsh_blockcommit.py: fix case which is hard to get expected result

- libvirt/tests/src/virsh_cmd/host/virsh_nodecpumap.py
This test has used cpu.online/offline, turn_off_on_cpu is unused.
```
(1/4) type_specific.io-github-autotest-libvirt.virsh.nodecpumap.no_option: STARTED
(1/4) type_specific.io-github-autotest-libvirt.virsh.nodecpumap.no_option: PASS (6.18 s)
(2/4) type_specific.io-github-autotest-libvirt.virsh.nodecpumap.pretty_option: STARTED
(2/4) type_specific.io-github-autotest-libvirt.virsh.nodecpumap.pretty_option: PASS (6.17 s)
(3/4) type_specific.io-github-autotest-libvirt.virsh.nodecpumap.unexpect_option: STARTED
(3/4) type_specific.io-github-autotest-libvirt.virsh.nodecpumap.unexpect_option: PASS (6.09 s)
(4/4) type_specific.io-github-autotest-libvirt.virsh.nodecpumap.cpu_off_on: STARTED
(4/4) type_specific.io-github-autotest-libvirt.virsh.nodecpumap.cpu_off_on: PASS (6.73 s)
```
> [minor fix] virsh_nodecpumap: Remove unused func turn_off_on_cpu

- libvirt/tests/cfg/memory/memory_attach_device.cfg
Test rt.
```
(1/2) type_specific.io-github-autotest-libvirt.memory_attach_device.virtio_mem.cold_plug: STARTED
(1/2) type_specific.io-github-autotest-libvirt.memory_attach_device.virtio_mem.cold_plug: PASS (94.16 s)
(2/2) type_specific.io-github-autotest-libvirt.memory_attach_device.virtio_mem.hot_plug: STARTED
(2/2) type_specific.io-github-autotest-libvirt.memory_attach_device.virtio_mem.hot_plug: PASS (94.20 s)
```
> memory_attach_device: Enable test for aarch64

- libvirt/tests/cfg/backingchain/blockjob_options.cfg
- libvirt/tests/src/backingchain/blockjob_options.py
TestFail: After blockjob with --async, the blockcopy not aborted immediately, spent 6.51890412100056 seconds.
---Change "Check run time less than 2 seconds" to "Check BLOCK_JOB_CANCELLED event in qemu-monitor-event". Because the previous checkpoints were not rigorous in auto tests. This lead to the different results between manual and auto test. Manual case has already been updated.
error: invalid argument: disk vda does not have an active block job
---Update def teardown_blockjob_async() part. Because for blockjob with --async, no need to use --abort to cancel the block job again.
> blockjob_options: fix --async option failure with new checkpoint

- libvirt/tests/src/backingchain/blockcommand.py
Make sure the guest boot successfully before creating snapshot, otherwise it may fail.
Test Results:
(1/4) type_specific.io-github-autotest-libvirt.backingchain.blockcommand.blockpull.base_top.positive_test.file_disk.block_bk: PASS (59.95 s)
(2/4) type_specific.io-github-autotest-libvirt.backingchain.blockcommand.blockpull.base_top.positive_test.block_disk.block_bk: PASS (63.87 s)
(3/4) type_specific.io-github-autotest-libvirt.backingchain.blockcommand.blockcommit.base_top.positive_test.file_disk.block_bk: PASS (58.67 s)
(4/4) type_specific.io-github-autotest-libvirt.backingchain.blockcommand.blockcommit.base_top.positive_test.block_disk.block_bk: PASS (63.64 s)
> block_job_commit_pull: Make sure the guest boot successfully before snapshot-create-as

- libvirt/tests/src/migration/migrate_with_legacy_guest.py
- libvirt/tests/src/virtio_transitional/virtio_transitional_base.py
The rhel6 guest should not be configured with efi os_firmware.
```
(1/1) type_specific.io-github-autotest-libvirt.virtio_transitional_mem_balloon.rhel6_guest.virtio_transitional: PASS (163.84 s)
(1/1) type_specific.io-github-autotest-libvirt.virsh.migrate_with_legacy_guest.test_interface.rhel6_guest.virtio_transitional: PASS (194.41 s)
```
> rhel6_guest: Remove efi os_firmware

- libvirt/tests/src/svirt/svirt_virt_install.py
--osinfo/--os-variant is required after virt-install-4.* in default,
So disable osinfo detect to get the old behavior back.
e.g
> Disable osinfo detect in virt-install

- libvirt/tests/cfg/migration/migrate_options_shared.cfg
The checking operation is covered in libvirt upstream unit test. So
remove it.
> migration: Remove qemu command line checking

- libvirt/tests/cfg/controller/pcibridge.cfg
- libvirt/tests/src/controller/pcibridge.py
Fix 2 problems:
- slot is occupied by other devices (pci-bridge controller)
- index number should be in decimal, not hex.
> pcibridge: fix incorrect index

- libvirt/tests/src/controller/controller_functional.py
decimal number is used in qemu command line now for id instead of hex.
> controller_functional: fix incorrect num

- libvirt/tests/cfg/virsh_cmd/domain/virsh_iothreadpin.cfg
- libvirt/tests/src/virsh_cmd/domain/virsh_iothreadpin.py
Case ID: VIRT-292858
Pin iothread to invalid cpuset fails, and vm xml is not impacted.
> virsh_iothreadpin: new case for disallowed cpuset

- provider/v2v_vmcheck_helper.py
- v2v/tests/cfg/convert_vm_to_libvirt.cfg
Whether a VM suppots vsock or not depends on the vm's kernel, it's
difficult in our script to check it and not necessary. For most of
cases, the vsock check can be ignored except the matrix and acceptance
and signoff testing.
So we can enabled the check in convert_vm_to_libvirt but other files
to avoid unexpected vsock checking failure.
> v2v: add a variant to control the vsock checking

- provider/backingchain/blockcommand_base.py
if other cases not clean snap file successfully, existed file will
influence many cases
1. create existed snap file
2. run test 
3. passed
```
avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 backingchain.blockpull.conventional_chain.rbd_with_auth_disk.with_base --vt-connect-uri qemu:///system
(1/1) type_specific.io-github-autotest-libvirt.backingchain.blockpull.conventional_chain.rbd_with_auth_disk.with_base: PASS (63.00 s)
```
> blockcommand_base: remove existed snap file

- libvirt/tests/cfg/virtual_device/filesystem_device.cfg
- libvirt/tests/src/virtual_device/filesystem_device.py
1) As shown in https://bugzilla.redhat.com/show_bug.cgi?id=2057882#c9,
posix/flock is not supported, some import scenarios in only tested when
posix/flock=on before, and these scenarios have be added into skiplist.
We should change posix/flock to off in these scenarios.
2) If I run the cases on my local machine, there would be a process of
avocado contains "virtiofsd". If one just grep the first process of
virtiofsd, it is not the virtiofsd process itself.
> Fix the issues about flock/posix

- libvirt/tests/cfg/virsh_cmd/domain/virsh_attach_detach_disk.cfg
- libvirt/tests/src/virsh_cmd/domain/virsh_attach_detach_disk.py
VIRT-85116 and VIRT-294590 : Add positive and negative addresses cases
(p3-ve) [root@nanli tp-libvirt]# /**usr/local/bin/avocado run --vt-type libvirt --vt-machine-type q35 virsh.attach_detach_disk..twice_same_target_diff_scsi_address  --vt-connect-uri qemu:///system**
JOB ID     : 62f6a91498a59e0d994b9847fbb19148b742a376
JOB LOG    : /root/avocado/job-results/job-2022-05-17T16.47-62f6a91/job.log
(1/1) type_specific.io-github-autotest-libvirt.virsh.attach_detach_disk.attach_disk.normal_test.twice_same_target_diff_scsi_address: PASS (40.55 s)
RESULTS    : **PASS** 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB TIME   : 46.74 s
(p3-ve) [root@nanli tp-libvirt]# **/usr/local/bin/avocado run --vt-type libvirt …
> Add case for hot-plug with different addresses

- libvirt/tests/src/svirt/dac_nfs_disk.py
… dynamic_ownership='0'
Ownership of swtpm.socket will not be chaneged dynamically when dynamic_ownership='0'.
So need to set swtpm_user/swtpm_group the same with user/group in qemu.conf to avoid the
permission issue.
e.g
> Set swtpm_user/swtpm_group in qemu.conf if dynamic_ownership='0' 

- libvirt/tests/cfg/cpu/iothread.cfg
Some aarch64 hosts have more cpus, 100 is not enough to be out of range.
> CPU: Update params setting of test out_of_range for aarch64

- libvirt/tests/src/virsh_cmd/domain/virsh_blockcopy.py
If the guest starts, make sure it boot successfully before creating snapshot, otherwise it may fail.
Test Result:
(1/1) type_specific.io-github-autotest-libvirt.virsh.blockcopy.negative_test.shallow_raw.no_blockdev: PASS (36.29 s)
> virsh_blockcopy: Make sure the guest boot successfully before snapshot-create

- libvirt/tests/cfg/virtual_device/virtio_rng.cfg
- libvirt/tests/src/virtual_device/virtio_rng.py
- provider/virtio_rng/check_points.py
This commit adds automated version of polarion case RHEL-112411. It
tests Rng device type egd coldplugging and unplugging. Both bind mode
and connect mode are tested.
Feature: virtio_rng
```
JOB ID     : e65494bfaf6c4a2ae7d325847ca2857e5905d22a
JOB LOG    : /root/avocado/job-results/job-2022-07-15T21.47-e65494b/job.log
(1/3) type_specific.io-github-autotest-libvirt.virtio_rng.coldplug_unplug_random_backend: STARTED
(1/3) …
```
> virtio_rng: Cold-plug/unplug a egd backend virtio-rng device - TCP connect/bind mode	

- libvirt/tests/cfg/controller/pcibridge.cfg
- libvirt/tests/src/controller/pcibridge.py
Due to more controllers added, the fixed bus of the iface device is attached
to a wrong controller which makes attaching succeeded. This is to remove the
fixed bus info of iface device and get the desired index of pcie-to-pci-bridge
controller as target bus to attach.
> pcibridge: fix attach bus error
