autotest/tp-libvirt

libvirt/tests/cfg/virsh_cmd/domain/virsh_managedsave.cfg
libvirt/tests/src/virsh_cmd/domain/virsh_managedsave.py

Test bypass_cache option
Test bypass_cache and start_delay option in libvirt-guests configuration file.

Add tests for managedsave command.

---

libvirt/tests/cfg/virsh_cmd/domain/virsh_blockcopy.cfg
libvirt/tests/src/virsh_cmd/domain/virsh_blockcopy.py

blockcopy: Extend case to copy disk to NFS and local disk

---

libvirt/tests/src/virsh_cmd/volume/virsh_volume_application.py

For nfs or some cases limited by selinux, installation may be failed because permission denied.
So simply setting it to permissive(setenforce 0).
Signed-off-by: Yu Mingfei <yumingfei@cn.fujitsu.com>

volume_application: Set selinux to permissive to avoid disturbance.

---

libvirt/tests/cfg/virsh_cmd/pool/virsh_pool.cfg
libvirt/tests/src/virsh_cmd/pool/virsh_pool.py

virsh.pool: Test various pool source formats

---

libguestfs/tests/cfg/guestfish_fs_mount.cfg
libguestfs/tests/cfg/guestfish_fs_swap.cfg
libguestfs/tests/guestfish_fs_mount.py
libguestfs/tests/guestfish_fs_swap.py

1. add command: mount, mount_loop, mount_options, mountpoints, mount_ro, mounts, mount_vfs, umount, umount_all

add "mount command"

---

libvirt/tests/cfg/virtual_disks/virtual_disks_multidisks.cfg
libvirt/tests/src/virtual_disks/virtual_disks_iscsi.py
libvirt/tests/src/virtual_disks/virtual_disks_multidisks.py

wwn may contain 0x prefix in qemu-kvm command line.
set serail console to kernel boot parameters for serial tests.
update disk format probe mothed.

Improve code implementation.

---

libvirt/tests/src/conf_file/libvirtd_conf/unix_sock.py

To test whether readonly socket is working, this commit change the virsh
test command from `list` to `net-define`.

conf_file..unix_sock: Change test command to net-define

---

libvirt/tests/cfg/libvirt_bench/libvirt_bench_serial_hotplug.cfg
libvirt/tests/src/libvirt_bench/libvirt_bench_serial_hotplug.py

libvirt_bench: add stress cases for serial device hotplug

---

libvirt/tests/cfg/virsh_cmd/volume/virsh_vol_create.cfg
libvirt/tests/cfg/virsh_cmd/volume/virsh_volume.cfg
libvirt/tests/src/virsh_cmd/pool/virsh_pool.py
libvirt/tests/src/virsh_cmd/volume/virsh_vol_create.py
libvirt/tests/src/virsh_cmd/volume/virsh_volume.py

1.virsh.volume: Add test for encryption volume and netfs pool
2.virsh.vol_create: Add a negative to test overcommit storage

virsh.volume: Add test for encryption volume and netfs pool

---

libvirt/tests/src/nwfilter/nwfilter_update_vm_running.py
libvirt/tests/src/nwfilter/nwfilter_vm_attach.py
libvirt/tests/src/nwfilter/nwfilter_vm_start.py
libvirt/tests/src/virsh_cmd/domain/virsh_attach_device.py
libvirt/tests/src/virsh_cmd/domain/virsh_blkdeviotune.py
libvirt/tests/src/virsh_cmd/domain/virsh_managedsave.py
libvirt/tests/src/virtual_disks/virtual_disks_gluster.py
libvirt/tests/src/virtual_network/iface_network.py
libvirt/tests/src/virtual_network/iface_options.py

Fixes for the new problems that the latest pylint and PEP8 checks started finding in our codebase.

Pep8 fixes

---

libvirt/tests/src/virsh_cmd/host/virsh_nodecpumap.py

Remove checking present cpu num with /sys/devices/system/cpu/present

---

libvirt/tests/src/svirt/svirt_start_destroy.py

please refer to the link for more details:
https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/6
/html/Security-Enhanced_Linux
/sect-Security-Enhanced_Linux-SELinux_Contexts_Labeling_Files
-Persistent_Changes_semanage_fcontext.html

svirt: Using semanage set context persistently

---

libvirt/tests/cfg/virsh_cmd/domain/virsh_numatune.cfg
libvirt/tests/src/virsh_cmd/domain/virsh_numatune.py

numatune: Fix problems and update get numa parameter method

---

libvirt/tests/src/hotplug_serial.py

* use test.tmpdir to get the path
* remove the entire temporary directory at last

hotplug_serial: improve the way of getting temp directory

---

libvirt/tests/cfg/libvirt_vcpu_plug_unplug.cfg
libvirt/tests/cfg/virsh_cmd/domain/virsh_dompmsuspend.cfg
libvirt/tests/src/libvirt_vcpu_plug_unplug.py
libvirt/tests/src/virsh_cmd/domain/virsh_blockcommit.py
libvirt/tests/src/virsh_cmd/domain/virsh_blockpull.py
libvirt/tests/src/virsh_cmd/domain/virsh_domfstrim.py
libvirt/tests/src/virsh_cmd/domain/virsh_dompmsuspend.py
libvirt/tests/src/virsh_cmd/domain/virsh_qemu_agent_command.py
libvirt/tests/src/virsh_cmd/domain/virsh_qemu_agent_command_fs.py
libvirt/tests/src/virsh_cmd/domain/virsh_reboot.py
libvirt/tests/src/virsh_cmd/domain/virsh_setmem.py
libvirt/tests/src/virsh_cmd/domain/virsh_shutdown.py
libvirt/tests/src/virsh_cmd/domain/virsh_vcpucount.py
libvirt/tests/src/virsh_cmd/snapshot/virsh_snapshot_create_as.py

There patches update the guest agent related tests to follow the new
method for preparation of guest agent. And some small fixes included.
This PR depends on https://github.com/autotest/virt-test/pull/1961.

Update with guest agent related changes

---

libvirt/tests/src/virsh_cmd/domain/virsh_vcpupin.py
libvirt/tests/src/virsh_cmd/host/virsh_nodecpustats.py

similar with https://github.com/autotest/tp-libvirt/pull/397

Modify for machine parts of cpus offline situation

---

libvirt/tests/cfg/virsh_cmd/pool/virsh_pool.cfg
libvirt/tests/cfg/virsh_cmd/volume/virsh_vol_create.cfg
libvirt/tests/cfg/virsh_cmd/volume/virsh_vol_create_from.cfg
libvirt/tests/cfg/virsh_cmd/volume/virsh_vol_download_upload.cfg
libvirt/tests/cfg/virsh_cmd/volume/virsh_vol_resize.cfg
libvirt/tests/src/virsh_cmd/pool/virsh_pool.py
libvirt/tests/src/virsh_cmd/pool/virsh_pool_create.py
libvirt/tests/src/virsh_cmd/pool/virsh_pool_create_as.py
libvirt/tests/src/virsh_cmd/pool/virsh_pool_edit.py
libvirt/tests/src/virsh_cmd/volume/virsh_vol_clone_wipe.py
libvirt/tests/src/virsh_cmd/volume/virsh_vol_create.py
libvirt/tests/src/virsh_cmd/volume/virsh_vol_create_from.py
libvirt/tests/src/virsh_cmd/volume/virsh_vol_download_upload.py
libvirt/tests/src/virsh_cmd/volume/virsh_vol_resize.py
libvirt/tests/src/virsh_cmd/volume/virsh_volume.py
libvirt/tests/src/virsh_cmd/volume/virsh_volume_application.py

Fix several storage related bugs

---

libvirt/tests/cfg/virtual_network/iface_options.cfg
libvirt/tests/src/virtual_network/iface_hotplug.py
libvirt/tests/src/virtual_network/iface_options.py

Add interface macvtap tests; update some fucntions.

virtual_network.iface_options: Add interface macvtap tests

---

libvirt/tests/src/virtual_network/iface_hotplug.py

Attach-interface operation don't support "--live" option,
Error messages differ from rhel7 to rhel6.

Fix issues for rhel6 test.

---

libvirt/tests/src/timer_management.py

1). Get numeric timezone automatically as some timezones may have
use DST.
2). Rectify the expected result between timezone and UTC time in VM.

timer_management: Get numeric timezone automatically and a bug fix

---

libvirt/tests/src/virsh_cmd/domain/virsh_cpu_compare.py

virsh_cpu_compare: Add a new cpu element if it not exist

---

libvirt/tests/cfg/virsh_cmd/domain/virsh_metadata.cfg
libvirt/tests/src/virsh_cmd/domain/virsh_metadata.py

virsh: Add test case for metadata

---

libvirt/tests/cfg/virsh_cmd/host/virsh_domcapabilities.cfg
libvirt/tests/src/virsh_cmd/host/virsh_domcapabilities.py

virsh: Add test case for domcapabilities command

---

libvirt/tests/cfg/virsh_cmd/host/virsh_freepages.cfg
libvirt/tests/src/virsh_cmd/host/virsh_freepages.py

libvirt: Add test case for freepages command

---

libvirt/tests/src/virsh_cmd/domain/virsh_blockcommit.py
libvirt/tests/src/virsh_cmd/domain/virsh_console.py
libvirt/tests/src/virsh_cmd/domain/virsh_cpu_compare.py
libvirt/tests/src/virsh_cmd/domain/virsh_domblkerror.py
libvirt/tests/src/virsh_cmd/domain/virsh_metadata.py
libvirt/tests/src/virsh_cmd/domain/virsh_migrate_copy_storage.py
libvirt/tests/src/virsh_cmd/domain/virsh_migrate_multi_vms.py
libvirt/tests/src/virsh_cmd/domain/virsh_migrate_set_get_speed.py
libvirt/tests/src/virsh_cmd/domain/virsh_migrate_stress.py
libvirt/tests/src/virsh_cmd/domain/virsh_migrate_virtio_scsi.py
libvirt/tests/src/virsh_cmd/domain/virsh_qemu_attach.py
libvirt/tests/src/virsh_cmd/domain/virsh_qemu_monitor_blockjob.py
libvirt/tests/src/virsh_cmd/domain/virsh_qemu_monitor_command.py
libvirt/tests/src/virsh_cmd/domain/virsh_schedinfo_qemu_posix.py
libvirt/tests/src/virsh_cmd/domain/virsh_ttyconsole.py

remove unused import for sub-directory libvirt/tests/src/virsh_cmd/domain

Remove unused import

---

libvirt/tests/src/virtual_disks/virtual_disks_gluster.py

replace check_vm_guestagent() with prepare_guest_agent.

virtual_disks_gluster: start ga by prepare_guest_agent

---

libvirt/tests/src/libvirt_bench/libvirt_bench_serial_hotplug.py
libvirt/tests/src/storage_discard.py

The following would call the common function create_channel_xml,
which implemented at virttest.utils_test.libvirt
* libvirt_bench/libvirt_bench_serial_hotplug.py
* storage_discard
This patch requests virt-test/#2000

Using unified function to create channel xml file

---

libvirt/tests/src/virsh_cmd/domain/virsh_reboot.py

* qemu-guest-agent is not supported on RHEL5.
and all of cases about qemu-guest-agent should skip, not fail.
* remove 'FIXME' and catch the specific exception

virsh_reboot: improve and perfect the exception handling

---

libvirt/tests/src/perf_kvm.py

run_dd_on_guest never be used, so delete it

perf_kvm: remove the unused function run_dd_on_guest

---

libvirt/tests/cfg/virsh_cmd/host/virsh_cpu_models.cfg
libvirt/tests/src/virsh_cmd/host/virsh_cpu_models.py

libvirt: Add test case for cpu-models command

---

libvirt/tests/cfg/virsh_cmd/monitor/virsh_domstats.cfg
libvirt/tests/src/virsh_cmd/monitor/virsh_domstats.py

libvirt: Add test case for domstats command

---

libvirt/tests/cfg/virsh_cmd/network/virsh_net_dhcp_leases.cfg
libvirt/tests/src/virsh_cmd/network/virsh_net_dhcp_leases.py

virsh: Add test case for net-dhcp-leases

---

libvirt/tests/cfg/virsh_cmd/domain/virsh_event.cfg
libvirt/tests/src/virsh_cmd/domain/virsh_event.py

Including two commands: virsh event and virsh qemu-monitor-event

virsh: Add test case for event&qemu-monitor-event

---

libvirt/tests/cfg/controller/controller_functional.cfg
libvirt/tests/src/controller/controller_functional.py

1) Define the VM with specified controller device and check result
meets expectation
2) Start the guest and check if start result meets expectation
3) Test the function of started controller device
4) Shutdown the VM and clean up environment
This PR depends on https://github.com/autotest/virt-test/pull/2026

Add test for basic controller device function

---

libvirt/tests/src/virsh_cmd/domain/virsh_change_media.py

A check is added to filter out the floppy test cases

virsh_change_media.py: Fix for floppy test issues (after PR #542)

---

libvirt/tests/src/virsh_cmd/network/virsh_net_dhcp_leases.py

E701 means multiple statements on one line (colon)

virsh_net_dhcp_leases: fix pep8 E701

---

libvirt/tests/src/virsh_cmd/domain/virsh_dompmsuspend.py

Fix virt_clone_cmd parameter problem.

Wait for vm is started before save/pmsuspend operation.

---

libvirt/tests/src/virsh_cmd/domain/virsh_domfstrim.py

1. Change the disk_path as /dev/disk/by-path can not be find anymore
2. Add judgement for scsi disk exist for current guest and then do different operation
3. Add vm.shutdown as for guest agent vm destroy will crash the guest agent in guest

Modify domfstrim cases

---

libvirt/tests/cfg/virsh_cmd/domain/virsh_change_media.cfg

change_media: simplify the cfg with less hierarchy

---

libvirt/tests/src/virsh_cmd/pool/virsh_pool.py

New version libvit has already changed back as before. @waynesun09

Change back for dir pool autostart strategy modified 

---

libvirt/tests/cfg/virsh_cmd/host/virsh_nodecpustats.cfg
libvirt/tests/src/virsh_cmd/host/virsh_nodecpustats.py

virsh nodecpustats: add negative case.

---

libvirt/tests/src/numa/numa_memory.py
libvirt/tests/src/numa/numa_memory_migrate.py

Deal with inconsistent node like fix in numa_memory.

numa_memory_migrate: Fix inconsistent node problem

---

libvirt/tests/src/virsh_cmd/domain/virsh_create.py

virsh.create "console_autodestroy_paused" case may return fail：
ERROR| TestFail: Guest still exist with options --console --autodestroy --paused
so delay to check vm status is necessary.

virsh_create: sleep a while to make sure guest is destroyed

---

libvirt/tests/src/libvirt_bench/libvirt_bench_vcpu_hotplug.py

1) Preparing agent and increasing pressure operatings are
not in the same virtual machine.
preparing agent for the VM that obtained by env.get_vm(),
increasing pressure on the VM that created by libvirt_vm.VM()
2) Update the check string for dmesg of RHEL6.7beta.

libvirt_bench_vcpu_hotplug: bugfix

---

libvirt/tests/cfg/virsh_cmd/domain/virsh_domfstrim.cfg
libvirt/tests/src/virsh_cmd/domain/virsh_domfstrim.py

Add negative case about no prepared qemu guest agent
when testing virsh domfstrim.

Add negative case for virsh domfstrim.

---

libvirt/tests/src/guest_kernel_debugging/nmi_test.py
libvirt/tests/src/remote_access/remote_access.py
libvirt/tests/src/virsh_cmd/domain/virsh_blockjob.py
libvirt/tests/src/virsh_cmd/domain/virsh_cpu_baseline.py
libvirt/tests/src/virsh_cmd/domain/virsh_domdisplay.py
libvirt/tests/src/virsh_cmd/domain/virsh_migrate_copy_storage.py
libvirt/tests/src/virsh_cmd/domain/virsh_migrate_multi_vms.py
libvirt/tests/src/virsh_cmd/domain/virsh_migrate_set_get_speed.py
libvirt/tests/src/virsh_cmd/domain/virsh_migrate_stress.py
libvirt/tests/src/virsh_cmd/domain/virsh_qemu_monitor_blockjob.py
libvirt/tests/src/virsh_cmd/interface/virsh_iface_trans.py
libvirt/tests/src/virsh_cmd/network/virsh_net_dhcp_leases.py
libvirt/tests/src/virsh_cmd/nodedev/virsh_nodedev_create_destroy.py
libvirt/tests/src/virsh_cmd/pool/virsh_find_storage_pool_sources.py
libvirt/tests/src/virsh_cmd/secret/virsh_secret_set_get.py
libvirt/tests/src/virsh_cmd/snapshot/virsh_snapshot_disk.py
libvirt/tests/src/virsh_cmd/snapshot/virsh_snapshot_edit.py
libvirt/tests/src/virsh_cmd/snapshot/virsh_snapshot_par_cur.py
libvirt/tests/src/virsh_cmd/volume/virsh_vol_create_from.py
libvirt/tests/src/virsh_cmd/volume/virsh_vol_download_upload.py
libvirt/tests/src/virt_cmd/virt_xml_validate.py

1. Fix skip message for TestNAError() and TestFail()
please refer to the commit beacb9d for more details.
2. remote_access.py: fix %s in message
The '%s' which in exception string should be replaced
with variable 'pattern'.

fix exception message

---

libvirt/tests/src/virsh_cmd/domain/virsh_domblkerror.py

Fix pre_pool option and iscsi iamge name.
Backup xml before run and restore after even though live update not
affect config file, be cautious for failure.
Adjust timeout for check status.

domblkerror: problem fix

---

libvirt/tests/src/virsh_cmd/domain/virsh_destroy.py

If there's no valid ssh key between local and remote host,
The case will encounter the following error,
ShellTimeoutError:
Timeout expired while waiting for shell command to complete:
'virsh -c qemu+ssh://10.167.225.120/system destroy vm1
In fact, it waits for inputing the password of local host.
This patch fix the problem by ssh_key.setup_remote_ssh_key().

virsh_destroy: bugfix for destroy local VM from remote machine

---

libvirt/tests/src/virsh_cmd/domain/virsh_migrate_setmaxdowntime.py

setting max downtime can only be used during migration with
old version of libvirt.
so, if setting max downtime successfully when VM is not during
migration, we can regards it as TestFail.
But it allow setting migration max downtime any time since 1.2.9,
so it's better to check the version before raise TestFail.

virsh_migrate_setmaxdowntime: allow setting downtime any time

---

libvirt/tests/src/virsh_cmd/domain/virsh_migrate_virtio_scsi.py

setup_remote_ssh_key can provides complete functionality
to support autologin without password.
set_remote_vm_autologin() is redundant and unnecessary，
so replace it with setup_remote_ssh_key.

virsh_migrate_virtio_scsi: Use setup_remote_ssh_key

---

v2v/tests/cfg/v2v_options.cfg
v2v/tests/src/v2v_options.py

v2v: New test case for virt-v2v options

---

libvirt/tests/cfg/virsh_cmd/network/virsh_net_event.cfg
libvirt/tests/src/virsh_cmd/network/virsh_net_event.py

BTW, this PR dependent on https://github.com/autotest/virt-test/pull/2135

virsh: Add test case for net-event

---

libguestfs/tests/cfg/virt_cat.cfg
libguestfs/tests/virt_cat.py

Test virt-cat command.
Signed-off-by: Ditang Chen \<chendt.fnst@cn.fujitsu.com\>

libguestfs: Add new case for virt-cat

---

libvirt/tests/cfg/virt_cmd/virt_top.cfg
libvirt/tests/src/virt_cmd/virt_top.py

test some invalid option: "virt-top -0" and "virt-topi --xyz"

virt_top: Add some negative case

---

.travis.yml

We have updated the autotest package distro
version, so let's reflect that in .travis.yml.
Signed-off-by: Lucas Meneghel Rodrigues <lmr@redhat.com>

.travis.yml: Update autotest distro version

---

v2v/tests/src/vm_check.py

v2v.vm_check: Move windows VM init part to utils module

---

libvirt/tests/src/virsh_cmd/pool/virsh_pool.py
libvirt/tests/src/virsh_cmd/pool/virsh_pool_acl.py
libvirt/tests/src/virsh_cmd/secret/virsh_secret_define_undefine.py

The function check_exit_status() used to check libvirt command
has been declared at virttest/utils_test/libvirt.py.
so it's better to use it and no need to re-write it respectively.

use API function to check the result of libvirt command

---

libvirt/tests/cfg/virsh_cmd/domain/virsh_domiflist.cfg
libvirt/tests/src/virsh_cmd/domain/virsh_domiflist.py

virsh domiflist has a new option '--inactive',
so add a test case for this.

Add test case for virsh domiflist --inactive.

---

libvirt/tests/src/virsh_cmd/domain/virsh_domblklist.py

Change the autotest/tp-libvirt#552 to this branch.
When the domain has a none source cdrom driver, new_disk.source would
point to no object. And sometimes the output from xml and command output's
order is different, so we should order them and then compare them.

Bugfix: Fix the cases NG when the domain has cdrom in virsh-domblklist

---

libvirt/tests/src/svirt/dac_nfs_disk.py
libvirt/tests/src/svirt/dac_nfs_save_restore.py

Fix a couple of new pylint errors.

Fix new pylint warnings

---

libvirt/tests/src/virsh_cmd/interface/virsh_iface_bridge.py
requirements-travis.txt

Now we're going to start being picky about unused imports. Brace yourselves.

Update to inspektor 0.2.0

---

.travis.yml

Signed-off-by: Lucas Meneghel Rodrigues <lmr@scylladb.com>

.travis.yml: Add python 2.6 to the test matrix

---

CODING_STYLE
README.rst

s/describle/describe
s/Readbility/Readability
s/indepentently/independently

Fix typos in CODING_STYLE and README

---

libvirt/tests/src/virsh_cmd/domain/virsh_setmem.py

Usually there's certain amount memory reserved by kernel which is not
usable, and 'MemTotal' in /proc/meminfo only show the usable memory, so
we should minus the unusable memory to get expected memory inside VM
after do 'virsh setmem'.

virsh_setmem: Correct the memory check logic

---

libvirt/tests/src/virsh_cmd/network/virsh_net_create.py

virsh_net_create: Replace error.CmdError with process.CmdError.

---

libvirt/tests/src/virsh_cmd/domain/virsh_blockpull.py

Skip snapshot for cdrom disk.

---

libvirt/tests/src/virsh_cmd/domain/virsh_setmem.py

virsh.setmem: Only minus unusable memory when memory changed tests

---

libvirt/tests/src/migration/migrate_vm.py

Signed-off-by: Lucas Meneghel Rodrigues <lmr@scylladb.com>

libvirt/tests - migrate_vm.py: Organize and clean up imports

---

libvirt/tests/src/numa/numa_memory.py
libvirt/tests/src/numa/numa_memory_migrate.py

get temporary dir by data_dir.get_tmp_dir(),
and remove unsed variable.

numa: get temp path by get_tmp_dir

---

libvirt/tests/src/virsh_cmd/host/virsh_domcapabilities.py

At present, the case just test the first arch, we should test all.

virsh_domcapabilities: traverse all arch and not just test the first.

---

libvirt/tests/cfg/virsh_cmd/domain/virsh_event.cfg
libvirt/tests/src/libvirt_mem.py
libvirt/tests/src/virsh_cmd/domain/virsh_domdisplay.py
libvirt/tests/src/virsh_cmd/domain/virsh_event.py
libvirt/tests/src/virsh_cmd/domain/virsh_setmaxmem.py
libvirt/tests/src/virsh_cmd/snapshot/virsh_snapshot_create_as.py
libvirt/tests/src/virsh_cmd/snapshot/virsh_snapshot_edit.py
libvirt/tests/src/virtual_disks/virtual_disks_gluster.py
libvirt/tests/src/virtual_disks/virtual_disks_multidisks.py

Get the disk source from domain xml instead of config; use utils_misc
module to do mount/umount operation.

Fix some code bugs.

---

v2v/tests/src/convert_vm_to_ovirt.py

v2v: fix a wrong func name

---

libvirt/tests/src/virsh_cmd/snapshot/virsh_snapshot_edit.py

Strip each line in xml before comparison;
Remove delete operation in edit command, it may delete other description
section in domain xml.

Fix snapshot_edit bugs.

---

libvirt/tests/src/virsh_cmd/pool/virsh_pool.py

The pool info with 'Capacity', 'Allocation' and 'Available' are
caculated from bytes to GiB, deviation in 1% will happen, so fix
this problem in check and deviation in 1% will not fail testing.

Fix virsh pool info check deviation problem

---

libvirt/tests/src/virsh_cmd/monitor/virsh_domstate.py

1. There is a middle state 'crashed (panicked)' for 'coredump-destroy'
and 'coredump-restart', so wait 60 seconds for final state.
2. Create the dump path to avoid domain dump fail.
3. Use exist module to config qemu.conf.

virsh_domstate: Bugs fix and case enhancement

---

libvirt/tests/src/virsh_cmd/domain/virsh_emulatorpin.py

emulatorpin: Fix an expression error

---

libvirt/tests/src/virsh_cmd/domain/virsh_setvcpus.py

The set_vm_vcpus did not take effect since the vmxml obj not
updated, fix it by reset it.
The feature part may not exist in xml, e.g. on ppc testing, so
caught the exception and make test ongoing.

setvcpus: Fix vm xml update problem

---

libvirt/tests/src/virsh_cmd/host/virsh_nodeinfo.py

Update check on CPU frequency, CPU(s) and CPU Sockets.
The CPU frequency in ppc is under clock, update the check for it.
The CPU(s) in nodeinfo is Online threads in the system, check it
with all online cpu in sysfs.
The CPU Sockets in nodeinfo is Total sockets in each node, check
it with sockets number from one node.

nodeinfo: Fix nodeinfo check problem

---

libvirt/tests/src/virsh_cmd/host/virsh_nodeinfo.py

The CPU(s) in nodeinfo is online threads in the system, while on
ppc kvm the secondary threads of a core is offline on the host. The
kvm scheduler brings the secondary threads online in the guest
context.
In nodeinfo on ppc, the show offline cpus under sysfs is calculated
into online threads with complicated check in libvirt. While the
turn out result could only be match the online number under sysfs,
or all cpus under sysfs. Base on this, for our testing, did not
translate complicated c function into python here but only focus on
the result check as it's an either/or problem.

nodeinfo: Fix CPUs number check on ppc

---

libvirt/tests/src/libvirt_vcpu_plug_unplug.py

In ppc, the online cpu list mostly are not with incremental as 1,
which make vcpu pin with '-' and '^' not valid in a range.
To make pin work in all circumstances, if cpu number list with
'-' and incremental as 1 could not be found in online cpu, use
'x-x' which equals 'x', and if cpu number list with '^', use
'x,y,^x' when incremental as 1 could not be found in online cpu.
In reverse, when incremental as 1 could be found, use 'x-y' and
'x-y,^y' instead.

libvirt_vcpu_plug_unplug: Fix vcpu pin without incremental as 1

---

libvirt/tests/cfg/conf_file/qemu_conf/auto_dump.cfg
libvirt/tests/src/conf_file/qemu_conf/auto_dump.py

Panic new attribute model was introduced in libvit 1.3.1, update
test to support it.

auto_dump: support new panic model attribute

---

libvirt/tests/src/virsh_cmd/host/virsh_nodeinfo.py

As on RHEL6 the online file could missing under cpu0, and offline
it is not allowed on cpu0, the calculation is wrong then. Fix it
by check the online path under cpu0 and add 1 in both total and
online if not found.

nodeinfo: Fix check with online and total cpus

---

libvirt/tests/src/virtual_disks/virtual_disks_encryption.py
libvirt/tests/src/virtual_disks/virtual_disks_multidisks.py

Run 'partprobe' command after adding new partitions for the change take effect.

Fix partition couldn't be found problem.

---

v2v/tests/cfg/v2v_options.cfg
v2v/tests/src/v2v_options.py

Left only v2v options-related cases, will move those cases to
athother case file.

Remove non-option-related cases

---

libvirt/tests/src/daemon/restart_consist.py
libvirt/tests/src/nwfilter/nwfilter_vm_start.py
libvirt/tests/src/virsh_cmd/domain/virsh_domif_setlink_getlink.py
libvirt/tests/src/virtual_network/iface_hotplug.py
libvirt/tests/src/virtual_network/iface_network.py
libvirt/tests/src/virtual_network/iface_options.py

- Batch update for wait_for_serial_login failure
- iface_hotplug: hotplug after vm fully started

Fix wait_for_serial_login arguments problem

---

libvirt/tests/src/numa/numa_memory.py
libvirt/tests/src/virsh_cmd/domain/virsh_domiftune.py
libvirt/tests/src/virsh_cmd/domain/virsh_numatune.py

Only one vm needed in these tests, so use main_vm for get
vm.

Update use main_vm in tests

---

libvirt/tests/src/virsh_cmd/domain/virsh_domif_setlink_getlink.py

Some tests failed with ShellStatusError when check with session,
the command excuted succeed but following 'echo $?' command check
status failed.
To avoid this failure, catch the exception and put the func in
wait_for with multiple try.

domif_setlink_getlink: Avoid ShellStatusError for session check

---

libvirt/tests/src/virsh_cmd/monitor/virsh_domstate.py

Parameter `libvirtd` is shadowed by a following assignment of libvirtd
service instance. Thus later comparison with `"off"` will fail
definitely.
This patch also removed autotest dependency and fixed some style issues.

virsh.domstate: Fix shadowed variable and remove autotest dependency

---

libvirt/tests/src/virtual_disks/virtual_disks_gluster.py

Check vm state before login;
Use process module to run a command.

virtual_disks_gluster: bug fix

---

libvirt/tests/src/virsh_cmd/domain/virsh_attach_detach_disk.py

virsh.attach_detach_disk: PV cleanup

---

libvirt/tests/src/virsh_cmd/domain/virsh_domif_setlink_getlink.py

Not only could exit status check fail in serial login, also could
get ShellTimeoutError after can't get expected prompt but cmd did
succeed.
Fix this by check the cmd output with regex to confirm the command
succeed and do not fail the testing.

domif_setlink_getlink: Fix cmd check with serial login

---

libvirt/tests/src/virtual_disks/at_dt_iscsi_disk.py

In some case, volume info cann't be got immediately after pool-create
operation, add time wait for this case.

at_dt_iscsi_disk: Wait for a while to get the volume info.

---

libvirt/tests/cfg/virsh_cmd/domain/virsh_update_device.cfg
libvirt/tests/src/virsh_cmd/domain/virsh_update_device.py

virsh_update_device: Make sure vm is stopped before testing.

---

libvirt/tests/cfg/virsh_cmd/domain/virsh_migrate_setmaxdowntime.cfg
libvirt/tests/src/virsh_cmd/domain/virsh_migrate_setmaxdowntime.py

- Add NFS configuration to do migration
- Add guest XML backup, update and restore
- Add configuration to libvirtd.log and restore
- Add a checkpoint that is to match a pattern in libvirtd.log.

virsh_migrate_setmaxdowntime: multiple fixes

---

v2v/tests/cfg/specific_kvm.cfg
v2v/tests/src/specific_kvm.py

All cases here are converting kvm guests, follow the steps of
1.prepare the kvm guest for converting
2.execute virt-v2v
3.check converted guest

Add specific_kvm for os-specific cases on kvm

---

libvirt/tests/src/virsh_cmd/volume/virsh_vol_clone_wipe.py

virsh_vol_clone_wipe: Infinity loop fix

---

libvirt/tests/src/migration/migrate_vm.py
libvirt/tests/src/virsh_cmd/domain/virsh_migrate_copy_storage.py

refer to 47d5fc0.
Signed-off-by: Wei Jiangang <weijg.fnst@cn.fujitsu.com>

Use interpolation for TestNAError()

---

provider/v2v_vmcheck_helper.py
v2v/tests/cfg/convert_vm_to_libvirt.cfg
v2v/tests/src/convert_vm_to_ovirt.py

Signed-off-by: chloerh <haizhao@redhat.com>

convert_vm_to_ovirt: set type of v2v_timeout to int

---

libvirt/tests/cfg/virsh_cmd/domain/virsh_migrate.cfg
libvirt/tests/src/virsh_cmd/domain/virsh_migrate.py

Added test scenarios for Hugepage and Hugepage pinning
This patch enables hugepage, hugepage pinning for covering following scenarios
1. migration with only HP
2. migration with numa node and HP
3. migration with numa node and HP pin
4. migration with numa pinning and HP
5. migration with numa pinning and HP pin

Added test scenarios for Hugepage and Hugepage pinning

---

libvirt/tests/cfg/libvirt_mem.cfg

libvirt_mem: Fix max memory configuration for memory hotplug test

---

libvirt/tests/cfg/virsh_cmd/domain/virsh_migrate.cfg
libvirt/tests/src/virsh_cmd/domain/virsh_migrate.py

Added offline migration test case

Offline migration

---

libvirt/tests/src/virsh_cmd/volume/virsh_vol_clone_wipe.py

The 'get_vol_list' function return a dict, what we want here is the
first key value.
And fix the message when raise an exception.

Fix the wrong assignment

---

libvirt/tests/src/virsh_cmd/domain/virsh_save_image_define.py

Use libvirt.check_exit_status to check command output

---

provider/v2v_vmcheck_helper.py

For ncat connection might be reset before any commands could be
sent, or during the sleeping time while waiting for drivers to be
fully installed.Therefore close and recreate session and send one
test command to make sure the connection works fine.
Also, create virsh SASL session might timeout rarely, therefore
retry it several times till get the expected result.

Close and recreate session to avoid connection reset on windows

---

v2v/tests/cfg/v2v_options.cfg
v2v/tests/src/v2v_options.py

Add cases of conflict paramters, convert from xen guest and check
output format, quiet mode case convert from xen without output
format, check length of each line of v2v error message.
Update code, use avocado instead of autotest.

Add v2v case of paramters

---

libvirt/tests/src/virsh_cmd/domain/virsh_migrate_stress.py

Signed-off-by: Wei Jiangang <weijg.fnst@cn.fujitsu.com>

virsh_migrate_stress: Use utils_test.check_dest_vm_network

---

v2v/tests/src/function_test_esx.py

Check common checkpoints first and then check specific checkpoints
and merge errors to a list instead of raising exception immediately.

Update code of v2v function test on esx

---

v2v/tests/cfg/specific_kvm.cfg
v2v/tests/src/specific_kvm.py

2 with spice type
1 with wrong fstab file
3 with selinux configuration

Add 6 v2v function cases

---

libvirt/tests/cfg/migration/migrate_vm.cfg
libvirt/tests/src/migration/migrate_vm.py

migrate_vm: Add 3 test cases for --migrate_disks

---

libvirt/tests/cfg/virsh_cmd/domain/virsh_migrate.cfg
libvirt/tests/src/virsh_cmd/domain/virsh_migrate.py

virsh.migrate: Add one case for timeout-suspend

---

libvirt/tests/cfg/migration/migrate_vm.cfg
libvirt/tests/src/migration/migrate_vm.py

migrate_vm: Add a case for disks-port option

---

libvirt/tests/cfg/virsh_cmd/domain/virsh_migrate.cfg
libvirt/tests/src/virsh_cmd/domain/virsh_migrate.py

Added postcopy migration scenarios
1. --postcopy-after-precopy : starts postcopy automatically after precopy migration
2.  --postcopy which starts precopy migration and have to trigger postcopy with migrate-postcopy

Added Postcopy migration test cases

---

libvirt/tests/src/virsh_cmd/domain/virsh_emulatorpin.py

Before this patch if VM fails to start after a vcpu placement
changes in xml, it leaves the buggy xml in the system and results in
further tests failing, this patch will restore the backupxml incase
of failout.

virsh.emulatorpin: Restore VM xml incase of failure for vcpu placement

---

libvirt/tests/src/numa/numad_vcpupin.py

As bug 1218149 closed as not a bug, workaround this as in bug
comment 12.

numad_vcpupin: Fix numad can't start problem

---

libvirt/tests/src/numa/numa_memory.py
libvirt/tests/src/numa/numa_memory_migrate.py

As libvirtd session start with root and virtlogd by default start
by systemd, when start vm will get selinux denial as change
virtlogd to unconfined type from default virt_t type. Resolve this
by also start virtlogd with root as unconfined.

Fix start vm failure when use libvirtd session

---

libvirt/tests/src/virsh_cmd/domain/virsh_attach_device.py

attach_device: Throw out detail when VM can't start

---

libvirt/tests/cfg/virsh_cmd/domain/virsh_dompmsuspend.cfg

modified hardcoded vm name with ${main_vm}

Fixup virsh_dompmsuspend

---

libvirt/tests/src/virsh_cmd/domain/virsh_vcpucount.py

Added try block to catch error situation and recover
guest xml

Fixup: to recover guest xml incase of error

---

v2v/tests/cfg/convert_from_file.cfg
v2v/tests/src/convert_from_file.py

Including
- convert common ova file
- convert ova file with special configurations

Add v2v function cases of converting from file

---

libvirt/tests/src/virsh_cmd/domain/virsh_blockcopy.py

1. Reset-failed for virtlogd before restart it
As systemd restrict the frequency to attempted a service, this step may
failed as:
Job for virtlogd.service failed because start of the service was
attempted too often. See "systemctl status virtlogd.service" and
"journalctl -xe" for details
This patch add a workaround to reset the counter before restart virtlogd.
2. Wait 5 sec to let the new emulated iSCSI disk show up.
3. Remove the wait_for() mothod when run blockcopy command, once the
command has return, we need go on the test to check it.
4. Always check if the blockcopy job exist when waiting for the job finish.
5. Print more log when raise exception.

blockcopy: several bugs fix

---

libvirt/tests/cfg/vfio.cfg
libvirt/tests/src/vfio.py

vfio: Add tests for attach hostdev interface with managed option

---

libvirt/tests/cfg/virsh_cmd/domain/virsh_iothreadadd.cfg
libvirt/tests/cfg/virsh_cmd/domain/virsh_iothreaddel.cfg
libvirt/tests/cfg/virsh_cmd/domain/virsh_iothreadinfo.cfg
libvirt/tests/cfg/virsh_cmd/domain/virsh_iothreadpin.cfg
libvirt/tests/src/virsh_cmd/domain/virsh_iothreadadd.py
libvirt/tests/src/virsh_cmd/domain/virsh_iothreaddel.py
libvirt/tests/src/virsh_cmd/domain/virsh_iothreadinfo.py
libvirt/tests/src/virsh_cmd/domain/virsh_iothreadpin.py

Add iothread commands tests

---

libvirt/tests/cfg/migration/migrate_vm.cfg
libvirt/tests/src/migration/migrate_vm.py

- Add TLS reverse migration case
- Replace error.Test* in autotest with exceptions.Test* in avocado

migrate_vm: add one TLS reverse test case

---

libvirt/tests/cfg/channel/channel_functional.cfg
libvirt/tests/src/channel/channel_functional.py

1) Define the VM with specified channel device and check result
meets expectation;
2) Start the guest and check if start result meets expectation;
3) Test the function of started channel device;
4) Shutdown the VM and clean up environment.

Add test for basic channel device function.

---

libvirt/tests/src/virsh_cmd/domain/virsh_console.py

This update enhance the test of virsh console to:
1) Enable testing libvirt handling of duplicated console
with or without --force option.
2) Enable testing libvirt disconnection of console when VM is
shutdown with active console.

virsh.console: Check console duplication and disconnection

---

libvirt/tests/src/virsh_cmd/domain/virsh_undefine.py

virsh.domain_exists() immediately after vm.destroy() returns True even with
undefined domain due to timing issue and leads to test failure, 2 secs of
sleep time ensures to check virsh.domain_exists() after vm got destroyed.
sync() tries to undefines and define the xml to sync but virsh_undefine
test would have undefined already may lead to error out.
This patch fixes these issues.

Fixup virsh_undefine

---

libvirt/tests/src/virsh_cmd/host/virsh_maxvcpus.py

maxvcpu output has been changed to match the output from
capabilities xml, this patch addresses it.
reference libvirt commit:
1ec22be550eacc929a6cfb61d42ee594b9f1ce7

Fixup: Changed maxvcpus value based on libvirt commit

---

libvirt/tests/cfg/virsh_cmd/domain/virsh_dump.cfg
libvirt/tests/src/virsh_cmd/domain/virsh_dump.py

Added option to specify dump location in cfg

virsh_dump.py: Added option for dump location

---

libvirt/tests/src/virsh_cmd/domain/virsh_domiflist.py

Basically, the new attached interface will get IP address after VM
started, so we should use this one to login.

virsh_domiflist: Using new interface to login

---

libvirt/tests/src/virsh_cmd/domain/virsh_migrate.py

"unsupported configuration" error got from the migration command is due
to the test environment. So we should skip this error.

virsh_migrate: Skip the special migration error

---

v2v/tests/cfg/function_test_xen.cfg
v2v/tests/src/function_test_xen.py

- convert vm with sound card
- convert vm with libvirtxml and convert format

Add function case for xen and update code

---

libvirt/tests/src/virsh_cmd/domain/virsh_iothreadadd.py
libvirt/tests/src/virsh_cmd/domain/virsh_iothreaddel.py
libvirt/tests/src/virsh_cmd/domain/virsh_iothreadinfo.py
libvirt/tests/src/virsh_cmd/domain/virsh_iothreadpin.py

virsh.iothread: Fix skip exception name

---

v2v/tests/cfg/v2v_options.cfg
v2v/tests/src/v2v_options.py

- Check v2v dependency
- convert vm with libvirtxml and convert format

Add function cases for v2v_options

---

libvirt/tests/src/virsh_cmd/domain/virsh_detach_device.py

Make sure domain is successfully recovered if any thing unexpected
happens.
Replace wait_for_login with wait_for_serial_login since it's possible
the IP address is assigned to new attached interface.

virsh.detach_device: Ensure cleanup and use serial to log in

---

libvirt/tests/cfg/virsh_cmd/host/virsh_uri.cfg
libvirt/tests/src/virsh_cmd/host/virsh_uri.py

1. Forming uri using API.
2. ssh autologin is handled.

Fixup virsh_uri

---

libvirt/tests/src/virsh_cmd/domain/virsh_domblkerror.py

fdisk is not friendly as a non-interactive command and will cause issue
when target disk is in unexpected shape. We should use more reliable
command parted to replace it.
Another thing fixed here is that several commands to prepare disk in
guest should not be added into a forgiving try...except block since
their failures are not forgivable.

domblkerror: Use parted instead of fdisk

---

libvirt/tests/src/virsh_cmd/domain/virsh_managedsave.py

The bypass cache flag O_DIRECT is arch based, so it's different
base on platforms.
Update use os.O_DIRECT and bitwise AND with flags find in fdinfo
which will work on all platforms.

managedsave: Fix O_DIRECT flags check

---

libvirt/tests/src/virsh_cmd/domain/virsh_change_media.py

And also correct a parameter name.

change_media: Fix a module not import bug

---

libvirt/tests/src/virtual_network/iface_hotplug.py

s/check_cmd/check_cmds/
this is failing the testing.

iface_hotplug: Fix the typo

---

libvirt/tests/cfg/virsh_cmd/monitor/virsh_list.cfg
libvirt/tests/src/virsh_cmd/monitor/virsh_list.py

1. ssh autologin was not handled to execute commands remotely.
2. clean up and recovering the environment was not handled.
This patch fixes it.
Signed-off-by: Balamuruhan S bala24@linux.vnet.ibm.com

Fixup virsh_list.py

---

libvirt/tests/src/virtual_network/iface_hotplug.py

virtual_network.iface_hotplug: Fix a typo

---

libvirt/tests/cfg/virsh_cmd/network/virsh_net_list.cfg
libvirt/tests/src/virsh_cmd/network/virsh_net_list.py

- New options: uuid, name, table
- Other options: persistent, transient, autostart, no-autostart
Signed-off-by: chhu <chhu@redhat.com>

Add test for net-list options

---

libvirt/tests/src/virsh_cmd/domain/virsh_shutdown.py

Autologin from remote machine to test machine was not handled
to run commands remotely.

Fixup virsh_shutdown.py

---

libvirt/tests/cfg/virtual_disks/virtual_disks_ceph.cfg
libvirt/tests/src/virtual_disks/virtual_disks_ceph.py

fixup ceph related cases

---

libvirt/tests/src/virsh_cmd/host/virsh_freepages.py

For some ppc machines, not all nodes are provided with memory,
freepages command will fail when with '--all' in such situation,
which I think is acceptable.
Fix this fail situation by update status_error value.

virsh.freepages: Fix fail when node without memory

---

libvirt/tests/src/virsh_cmd/domain/virsh_dompmsuspend.py

And remove the inappropriate step for agent_error_test

dompmsuspend: Add two more fail conditions

---

libvirt/tests/src/virsh_cmd/domain/virsh_attach_device.py

Added index option in controller xml to be attached to the guest. Without index, the test cases fails with, "Cannot parse controller index -1"
Signed-off-by: Harish S <harisrir@linux.vnet.ibm.com>

Fix: attach_device.py: added index option in controller xml

---

v2v/tests/cfg/function_test_esx.cfg
v2v/tests/src/function_test_esx.py

- convert EFI windows system from esx to RHEV
- convert windows vm with GPO and Anti-virus installed
- convert guest with '#' in name to kvm
- convert guest with vmware tools installed

Add function case on hypervisor esx

---

libvirt/tests/src/virsh_cmd/host/virsh_capabilities.py

Update both check use guest capabilities dict, and check wordsize
from dict same as libvirt struct.

capabilities: Fix wordsize and default hypervisor check

---

libvirt/tests/src/virsh_cmd/pool/virsh_find_storage_pool_sources.py
libvirt/tests/src/virsh_cmd/pool/virsh_find_storage_pool_sources_as.py

Update check command result with virttest function, also switch
autotest to avocado utils.

find_storage_pool_sources: Update check command result

---

libvirt/tests/cfg/virsh_cmd/domain/virsh_vcpupin.cfg
libvirt/tests/src/virsh_cmd/domain/virsh_vcpupin.py

Added test to check initial vcpupin affinity and
added support for validating the virsh vcpupin command
output for vcpu affinity check.

Added test to check initial vcpupin affinity

---

libvirt/tests/cfg/npiv/npiv_image_from_pool.cfg
libvirt/tests/src/npiv/npiv_image_from_pool.py

Create a libvirt npiv pool from a device mapper device and create a volume out of the newly created pool and attach it to a guest, mount it, reboot and check persistence after reboot.
Dependent on #868.

Added NPIV image from pool test case

---

libvirt/tests/cfg/npiv/npiv_virtual_disk.cfg
libvirt/tests/src/npiv/npiv_virtual_disk.py

Use npiv lun in /dev/disk/by-[uuid|id|path] as source dev of a
virtual disk and test hotplug/unplug virtual disks.
Sign-off by: Yi Sun (lentosun@163.com)

Add script to cover npiv virtual disk cases

---

libvirt/tests/cfg/npiv/npiv_snapshot.cfg
libvirt/tests/src/npiv/npiv_snapshot.py

npiv.snapshot.diskonly.virtual_disk_scsi_vol
npiv.snapshot.diskonly.virtual_disk_mpath
npiv.snapshot.diskonly.virtual_disk_by_path
npiv.snapshot.internal.virtual_disk_scsi_vol
npiv.snapshot.internal.virtual_disk_mpath
npiv.snapshot.internal.virtual_disk_by_path
sign-offed by: Yi Sun (lentosun@163.com)
This depends on https://github.com/avocado-framework/avocado-vt/pull/859

Add cases to cover NPIV and Snapshot cross test cases

---

libvirt/tests/src/libvirtd_start.py

This patch fixes the issue of libvirtd service failing due to autostart of inactive storage pools,
which is irrelevant to the current test-cases of iptables/firewalld start and stop along with libvirtd.
Also modified the testcase to SKIP where Selinux needs to be in enforcing mode, as its not supported
on certain distributions like Ubuntu.

libvirtd_start.py: Added autostart of inactive storage pools to the list of accepted errors.

---

libvirt/tests/cfg/virt_admin/virt_admin_itself.cfg
libvirt/tests/src/virt_admin/virt_admin_itself.py

This commit contains two kinds of tests: normal_test and error_test.
The general commands are: echo, cd, pwd, exit, quit.

Add the cases of the general commands supported by virt-admin

---

libvirt/tests/src/virsh_cmd/network/virsh_net_create.py

It will raise LibvirtXMLError when create network by an invalid XML.

virsh_net_create: Catch LibvirtXMLError

---

libvirt/tests/src/virt_cmd/virt_top.py

Reverts autotest/tp-libvirt#993

Revert "virt_top.py: Added option to install "virt-top" package, if missing."

---

libvirt/tests/cfg/virt_admin/monitor/virt_admin_srv_clients_info.cfg
libvirt/tests/src/virt_admin/monitor/virt_admin_srv_clients_info.py

Add the case of srv-clients-info for virt-admin

---

libvirt/tests/src/virt_cmd/virt_top.py

This patch enables the test-case to install the "virt-top" package from the repo, before test-case execution.
It's ideal to initially check for the package installed and later the command present, before execution.
Also replaced the Autotest API's with Avocado API's.

virt_top.py: Enabled option to install the "virt-top" package , if missing. 

---

libvirt/tests/src/virsh_cmd/domain/virsh_migrate.py

1. there_and_back migration was not enabled but cfg had the params for it.
2. pre migration setup and cleanup done using APIs

virsh.migrate: enabled there_and_back migration

---

libvirt/tests/cfg/virt_admin/monitor/virt_admin_srv_list.cfg
libvirt/tests/src/virt_admin/monitor/virt_admin_srv_list.py

Add the case of srv-list for virt-admin

---

libvirt/tests/src/libvirt_mem.py

Added support for handling multiple memory hotplug requests
Signed-off-by: Nageswara R Sastry rnsastry@linux.vnet.ibm.com

libvirt_mem: Added support for multiple memory hotplug

---

libvirt/tests/src/libvirt_hugepage.py
libvirt/tests/src/libvirt_rng.py
libvirt/tests/src/virsh_cmd/domain/virsh_sendkey.py
libvirt/tests/src/virtual_disks/virtual_disks_ceph.py
libvirt/tests/src/virtual_network/iface_network.py
libvirt/tests/src/virtual_network/iface_options.py

The yum_install function could only work with yum package manager,
new package_install support apt, zapper, dnf with avocado package
manager module.

Update cases with new package_install function

---

libvirt/tests/src/virsh_cmd/pool/virsh_find_storage_pool_sources.py
libvirt/tests/src/virsh_cmd/pool/virsh_find_storage_pool_sources_as.py

pool: Run command in shell

---

libvirt/tests/cfg/virtual_disks/virtual_disks_multidisks.cfg
libvirt/tests/src/virtual_disks/virtual_disks_multidisks.py

When using "type=usb,bus=2,port=2" in address attribute
the expected result is domain define error

Fix domain define error issue

---

v2v/tests/cfg/function_test_esx.cfg
v2v/tests/src/function_test_esx.py

- guest with device pass through
- guest with empty cdrom image
- guest with multiple system, using --root option

Add function cases of v2v on esx

---

v2v/tests/cfg/v2v_options.cfg
v2v/tests/src/v2v_options.py

- with duplicated options -b, -n and -oa

Add v2v function cases

---

libvirt/tests/cfg/conf_file/qemu_conf/set_virtlogd.cfg
libvirt/tests/src/conf_file/qemu_conf/set_virtlogd.py

Change stdio_handler value in qemu.conf to configure qemu logging
Check associated log is written into log file correctly.

Add qemu logging config test cases

---

libvirt/tests/cfg/virt_admin/management/virt_admin_client_disconnect.cfg
libvirt/tests/src/virt_admin/management/virt_admin_client_disconnect.py

Add the case of client-disconnect for virt-admin

---

libvirt/tests/src/virsh_cmd/domain/virsh_dumpxml.py

libvirt commit 3b6be3c0 rework cpuUpdate, so the expect result also need
update.
This patch also rework the test case:
1). Skip case early when check libvirt version for ACL testing;
2). Simplify running command and checking test result part;
3). Remove autotest dependency;
4). Add more debug messages.

dumpxml: Case update according to libvirt change

---

libvirt/tests/cfg/migration/migrate_vm.cfg
libvirt/tests/src/migration/migrate_vm.py

Enable iothread function on disk,
Then verify it still works after vm migration

Add iothread case into migration_vm

---

libvirt/tests/src/virsh_cmd/domain/virsh_migrate.py

we have params for image_name, image_format and nfs_mount_dir using
which shared image path can be retrieved without depending on the
user input for migrate_shared_storage which avoids redundancy of
getting input from user.

virsh_migrate: retrieve migrate_shared_storage with available params

---

libvirt/tests/src/virsh_cmd/domain/virsh_save_image_edit.py

After do save-imamge-edit, we expect the XML file can be saved
successfully, and if it can't save, session will raise Timeout
exception.
And, also correct the way to raise test error/fail.

save-image-edit: Catch the expected ouput

---

libvirt/tests/cfg/virsh_cmd/domain/virsh_vcpucount.cfg
libvirt/tests/src/virsh_cmd/domain/virsh_vcpucount.py

Refactored vcpucount testcase to take
user defined vcpu numbers and topology aware.

Refactored vcpucount testcase

---

libvirt/tests/src/virsh_cmd/domain/virsh_domblkerror.py

when NFS is not mounted and test reaches cleanup, unmount errors the test
as check to whether NFS is mounted was not handled.

virsh_domblkerror: cleanup errored to umount nfs if not mounted

---

libvirt/tests/src/libvirt_mem.py

Existing logic need to be change when tried cold plug many times.

Fix cold plug issue with many times

---

provider/v2v_vmcheck_helper.py
v2v/tests/cfg/convert_vm_to_libvirt.cfg
v2v/tests/cfg/convert_vm_to_ovirt.cfg
v2v/tests/src/convert_vm_to_libvirt.py
v2v/tests/src/convert_vm_to_ovirt.py

Since the public configurations are already stored in shared cfgs,
they are no longer needed in case config files.
Update os of test vms according to change of test plan

Update code for v2v matrix cases to adapt to public config file

---

libvirt/tests/cfg/virt_admin/management/virt_admin_server_threadpool_set.cfg
libvirt/tests/src/virt_admin/management/virt_admin_server_threadpool_set.py

Add the case of server-threadpool-set for virt-admin

---

libvirt/tests/src/virsh_cmd/host/virsh_nodecpustats.py

1. Refactored expected logic to assert from /proc/stat
instead of uptime, which was not right.
2. Removed autotest dependancy for assertion.

Fixup nodecpustats testcase

---

libvirt/tests/src/virsh_cmd/domain/virsh_domtime.py

virsh.domtime: Fix the pattern to get correct datetime

---

libvirt/tests/src/virsh_cmd/domain/virsh_dompmsuspend.py

sleep states ACPI S3, S4 errors the tests if it is unsupported, instead skip the tests

virsh_dompmsuspend: skip tests for unsupported ACPI sleep states

---

libvirt/tests/src/virsh_cmd/monitor/virsh_domstate.py

when virsh domstate returns unexpected domain state then error is raised instead of
failing the test case.

virsh_domstate: test failure is considered as error

---

libvirt/tests/cfg/virtual_disks/virtual_disks_gluster.cfg
libvirt/tests/src/virtual_disks/virtual_disks_gluster.py

Orchestrate gluster_disk.cfg to scale different attach mode,e.g attach-disk

Add hotplug cases into gluster disk

---

v2v/tests/src/convert_vm_to_ovirt.py

Check guests with win8, win8.1, win10, win2012 and win2012r2

Add case of check warning of QXL drivers after conversion

---

libvirt/tests/src/conf_file/qemu_conf/auto_dump.py

Changes made to pick ppc64le fdinfo flags. Also the failure reporting method.
Signed-off-by: Sudeesh John <sudeesh@linux.vnet.ibm.com>

Changes made to pick ppc64le fdinfo flags.

---

libvirt/tests/cfg/virsh_cmd/domain/virsh_setvcpu.cfg
libvirt/tests/src/virsh_cmd/domain/virsh_setvcpu.py

Added testcase to verify setvcpu virsh command
Addresses github issue: https://github.com/autotest/tp-libvirt/issues/998

Added testcase to verify setvcpu virsh command

---

libvirt/tests/cfg/virsh_cmd/domain/virsh_setvcpus.cfg
libvirt/tests/src/virsh_cmd/domain/virsh_setvcpus.py

1. Added expected output check in all related virsh APIs.
2. Removed autotest dependancy.
3. Modified maximum vcpu change based on a upstream bug,
details in the code comment.
4. few more minor fixes.

Refactored setvcpus testcase

---

libvirt/tests/cfg/smt.cfg
libvirt/tests/src/smt.py

Added guest SMT testcase for powerpc, which validates
different SMT levels of guest with combinations of
different topology levels.

Added guest SMT testcase for powerpc

---

libvirt/tests/src/virtual_disks/virtual_disks_multivms.py

Need output real reason for debugging Vm start failures

Fix suppress Vm start error message issue

---

v2v/tests/cfg/convert_from_file.cfg
v2v/tests/src/convert_from_file.py

- convert guests from aws
- convert to check ova manifest parsing
- check error info about permission when converting ova file
Also update config file to match with public config files

Add v2v cases of convert from ova files

---

libvirt/tests/cfg/virtual_disks/virtual_disks_multidisks.cfg
libvirt/tests/src/virtual_disks/virtual_disks_multidisks.py

Addressing Bugzilla:1006662,961854
virtio-scsi support vhdx disk format

Add support vhdx disk format cases

---

v2v/tests/cfg/v2v_options.cfg
v2v/tests/src/v2v_options.py

To match with lately updated function utils_v2v.check_log
Modify cfg file to retrieve 2 lost cases.

Update code about log checking for v2v_options cases

---

libvirt/tests/src/virsh_cmd/domain/virsh_attach_detach_disk.py

Change the constant to variable due to the stale data.
Signed-off-by: hsmj1412 <ljx1412@gmail.com>

Update code about case virsh_attach_detach_disk

---

libvirt/tests/src/virtual_disks/virtual_disks_multidisks.py

Fix duplicate add image issue

---

libvirt/tests/cfg/virsh_cmd/domain/virsh_event.cfg
libvirt/tests/src/virsh_cmd/domain/virsh_event.py

Only life-cycle events are tracked.

Add the case for tracking all events for multiple domains.

---

libvirt/tests/cfg/virt_admin/management/virt_admin_server_clients_set.cfg
libvirt/tests/src/virt_admin/management/virt_admin_server_clients_set.py

Add the case of server-clients-set for virt-admin

---

libvirt/tests/src/conf_file/qemu_conf/set_virtlogd.py

fix vm shutdown timeout issue in extreme case

---

libvirt/tests/cfg/virtual_disks/virtual_disks_ceph.cfg
libvirt/tests/src/virtual_disks/virtual_disks_ceph.py

Moreover,add rbd port and readonly disk snapshot cases

Enable hotplug ceph disk cases

---

libvirt/tests/src/virsh_cmd/domain/virsh_managedsave.py

1. change all virsh.xxx(xxx) to virsh.xxx(xxx, debug=True)
2. use test.fail/error/cancel to replace old exception rasing method
sign-offed by: Yi Sun (yisun@redhat.com)

Enable debug info for virsh and abandon old exception rasing

---

libvirt/tests/cfg/virtual_disks/virtual_disks_multidisks.cfg
libvirt/tests/src/virtual_disks/virtual_disks_multidisks.py

Fix occasional bus port conflict issue

---

libvirt/tests/cfg/virtual_disks/virtual_disks_ceph.cfg
libvirt/tests/src/virtual_disks/virtual_disks_ceph.py

Ceph support internal snapshot,and attaching front end disk created
by json pseudo protocol

Add internal snapshot_and json pseudo protocol cases

---

v2v/tests/cfg/convert_from_file.cfg
v2v/tests/src/convert_from_file.py

For future clean up process could proceed.

Modify code to keep vm obj when skip guest check

---

libvirt/tests/cfg/virt_admin/management/virt_admin_server_threadpool_set.cfg
libvirt/tests/src/virt_admin/management/virt_admin_server_threadpool_set.py

Increase the minWorkers of libvirtd to a value greater than maxWorkers.

Add a negative test of command server_threadpool_set of virt_admin

---

libvirt/tests/src/libvirt_rng.py

The change was due to the namespace support, thus /dev/random is re-created in a different path so that it can be passed into the correct namespace monut, the device node is re-created in a diffent place, and then re-mount that directory in a separate namespace to /dev/ for that process, so the file qemu seems differs from the actual /dev/random by inode, thus lsof does not show it but lsof|grep /dev/random will show

Fix libvirt_rng failure issues

---

v2v/tests/cfg/specific_kvm.cfg
v2v/tests/src/specific_kvm.py

Add case:
- with less than 1G space left on conversion server
- with spice/vnc and cirrus/qxl mix match
Update code:
- move error message content to cfg file controlled by 2 params to
make check log function more clear
- modify function of create large file to adapt to the need of
creating large file in host
- replace 'elif' with 'if'

Add v2v function case and update code of check log

---

v2v/tests/cfg/function_test_xen.cfg
v2v/tests/src/function_test_xen.py

Convert vm
- with vdsm installed on conversion server
- is encryped
- with multiple disks
- with rhel6.2 os
Also update cfg to work with public config

Add v2v function case on xen

---

v2v/tests/cfg/v2v_options.cfg
v2v/tests/src/v2v_options.py

Removed invalid cases
Update code to fix failed cases
Add case of
- converting from vmx
- replace '-o rhev' to '-o rhv'

Update code and add cases

---

v2v/tests/cfg/function_test_esx.cfg
v2v/tests/src/function_test_esx.py

Convert guests
- with snapshot
- with host setting up http&https proxy
- with /usr in different partition

Add cases of converting from esx

---

libvirt/tests/src/svirt/dac_vm_per_image_start.py

The guest failed to start as expected,details see:
https://bugzilla.redhat.com/show_bug.cgi?id=1165485

Don't skip the invalid disk label case

---

libvirt/tests/src/migration/migrate_vm.py

It is unreasonable that the domjobinfo when completion on source host
should be equal to that on target host because some fields may have
differences and other values should be equal on both sides.

migrate_vm: Fix domjobinfo comparison

---

libvirt/tests/cfg/virtual_disks/virtual_disks_multidisks.cfg
libvirt/tests/src/virtual_disks/virtual_disks_multidisks.py

Add multi driver sub elements in controller

Add disk read only snapshot cases

---

libvirt/tests/src/virsh_cmd/host/virsh_nodeinfo.py

virsh nodeinfo output didn't match Core(s) per socket from host OS for
special host  which have multiple numa nodes per physical socket, such
as AMD Bulldozer 62XX familly

Patch for virsh nodeinfo output for special numa arch

---

libvirt/tests/src/virsh_cmd/domain/virsh_dump.py

1. Change the fork place to make it more accurate for the child process executing
2. Add wait_for_login for test as it need more time to get the status during dump
3. Remove redundant kill and change the order for kill as it may cause error

fix dump bypass_cache failure

---

libvirt/tests/src/virsh_cmd/interface/virsh_iface_edit.py

Get the interface script independent of the distro

---

libvirt/tests/src/virsh_cmd/domain/virsh_qemu_agent_command.py

To avoid error of not responding that caused by inactive service.

Check whether qemu-guest-agent is active before sending command

---

libvirt/tests/src/virsh_cmd/domain/virsh_change_media.py

To make sure finally could be executed if any exception thrown out.
Also shutdown vm before any xml modifications.

Move more code to "try" block

---

libvirt/tests/src/daemon/crash_regression.py

When starting libvirtd foreground, it needs to start virtlogd foregroud
too. Also modify the function run_kill_virsh_while_managedsave() to
exit the gdb correctly.

Start both virtlogd and libvirtd foreground

---

v2v/tests/src/convert_from_file.py
v2v/tests/src/function_test_esx.py
v2v/tests/src/function_test_xen.py
v2v/tests/src/specific_kvm.py
v2v/tests/src/v2v_options.py

Replace test.skip() with test.cancel for v2v cases

---

libvirt/tests/cfg/virtual_network/iface_hotplug.cfg
libvirt/tests/src/virtual_network/iface_hotplug.py

iface_hotplug: Added time delay to take effect after detachment

---

libvirt/tests/src/numa/guest_numa.py

add some code to make sure numa 1G hugepages could be set successfully before vm start. Also update all exceptions like error.xxx to test.xxx

Fix numa memory allocate issue with 1G hugepages

---

libvirt/tests/src/virsh_cmd/domain/virsh_managedsave.py

After test finished, there's no need to start or resume test vm.
Restart libvirtd.service to avoid un-updated domain status to affect
future tests.

Modify cleanup code for virsh managedsave

---

.travis.yml
README.rst
libvirt/tests/src/migration/migrate_vm.py
libvirt/tests/src/svirt/dac_start_destroy.py
libvirt/tests/src/vfio.py
libvirt/tests/src/virsh_cmd/domain/virsh_attach_detach_disk_matrix.py
libvirt/tests/src/virsh_cmd/domain/virsh_attach_detach_interface_matrix.py
libvirt/tests/src/virsh_cmd/domain/virsh_attach_device_matrix.py
libvirt/tests/src/virsh_cmd/domain/virsh_migrate.py
libvirt/tests/src/virsh_cmd/domain/virsh_migrate_copy_storage.py
libvirt/tests/src/virsh_cmd/host/virsh_nodecpustats.py
libvirt/tests/src/virsh_cmd/host/virsh_nodeinfo.py
libvirt/tests/src/virsh_cmd/volume/virsh_vol_create.py
libvirt/tests/src/virtual_disks/virtual_disks_multidisks.py
provider/v2v_vmcheck_helper.py
requirements-travis.txt

Update CI scripts to the latest inspektor 0.4.5.

Inspektor 045

---

libvirt/tests/cfg/virsh_cmd/domain/virsh_set_user_password.cfg
libvirt/tests/src/virsh_cmd/domain/virsh_set_user_password.py

Signed-off-by: chhu <chhu@redhat.com>

virsh.set_user_password: Add test cases for set-user-password

---

libvirt/tests/src/virsh_cmd/domain/virsh_dumpxml.py

virsh_dumpxml:replace test.skip with test.cancel

---

v2v/tests/cfg/v2v_options.cfg
v2v/tests/src/v2v_options.py

- cannot install vm in 'ic' test
- wrong params for esx test

v2v_options:fix some case failures

---

libvirt/tests/cfg/virsh_cmd/domain/virsh_guestvcpus.cfg
libvirt/tests/src/virsh_cmd/domain/virsh_guestvcpus.py

Signed-off-by: chhu <chhu@redhat.com>

virsh.guestvcpus: Add test cases for guestvcpus

---

libvirt/tests/src/npiv/npiv_concurrent.py

Fix npiv_concurrent case error

---

libvirt/tests/src/virsh_cmd/domain/virsh_reset.py

Add time delay for virsh.reset to take effect

---

libvirt/tests/src/virsh_cmd/domain/virsh_migrate.py

virsh_migrate: Fix variable initialize issue

---

libvirt/tests/cfg/serial/serial_functional.cfg
libvirt/tests/src/serial/serial_functional.py
libvirt/tests/src/virsh_cmd/domain/virsh_attach_device.py

This test if used for checking basic serial character device function
for various type of serial devices.
1) Define the VM with specified serial device and define result meets
expectation.
2) Test whether defined XML meets expectation
3) Start the guest and check if start result meets expectation
4) Test the qemu command line meets expectation
5) Test the function of started serial device
6) Shutdown the VM and check whether cleaned up properly
7) Clean up environment

Add test for checking serial device function.

---

libvirt/tests/src/virsh_cmd/domain/virsh_vcpupin.py

There is some difference between cpu_max and online_cpu_max when part of cpus are offline

virsh_vcpupin: Fix the max cpus

---

libvirt/tests/src/libvirt_hooks.py

libvirt_hooks: Fix qemu-kvm command error in ppc64

---

libvirt/tests/src/virsh_cmd/host/virsh_maxvcpus.py

According to BZ 1455363 comment #10, we should compare virsh.maxvcpus to
virsh.domcapabilities instead of virsh.capabilities for max vcpu number.
The old way is inaccurate for PPC case. So this is to fix the problem.

virsh_maxvcpus: Fix maxvcpu comparision method

---

libvirt/tests/cfg/cpu/vcpu_hotpluggable.cfg
libvirt/tests/src/cpu/vcpu_hotpluggable.py

<vcpus>
<vcpu id='0' enabled='yes' hotpluggable='no' order='1'/>
<vcpu id='1' enabled='yes' hotpluggable='yes' order='3'/>
<vcpu id='2' enabled='no' hotpluggable='yes'/>
<vcpu id='3' enabled='yes' hotpluggable='yes' order='2'/>
<vcpu id='4' enabled='no' hotpluggable='yes'/>
<vcpu id='5' enabled='yes' hotpluggable='yes' order='4'/>
</vcpus>
Signed-off-by: Chenli Hu <chhu@redhat.com>

vcpu_hotpluggable: Add vcpu hotpluggable and order tests

---

libvirt/tests/src/virsh_cmd/domain/virsh_domblkerror.py

virsh_domblkerror:cleanup tmp folder after test run

---

libvirt/tests/src/svirt/dac_vm_per_image_start.py

Since with the libvirt version not lower than 3.1.0, libvirt will create namespaces
for each domain started. And libvirt will only relable the block type disk in the
domain's namespace. Therefore, we need to check the context of block type disk in
the domain's namespace too.
For more details, see bug:
https://bugzilla.redhat.com/show_bug.cgi?id=1404952

Fix the context checking for block type disk

---

libvirt/tests/cfg/libvirt_pci_passthrough.cfg
libvirt/tests/src/libvirt_pci_passthrough.py

Existing test case supports single function pass-through for nic and storage adaptor, now i am adding multifunction support for nic adaptors.
Signed-off-by: prudhvi <mprudhvi@linux.vnet.ibm.com>

Adding multifunction support for nic adaptors while passthrough to guest

---

libvirt/tests/src/virsh_cmd/domain/virsh_domblkerror.py

when iscsi setup is not proper, test cleanup errors with,
Attribute error: 'NoneType' object has no attribute 'export_flag'.
This patch handles this condition

virsh_domblkerror: cleanup is not done properly

---

libvirt/tests/cfg/limit.cfg
libvirt/tests/src/limit.py

Added test to validate resource limits(i.e cpu, memory,
network, disk etc) for guest

Added test to validate resource limits for guest

---

libvirt/tests/cfg/libvirt_vcpu_plug_unplug.cfg
libvirt/tests/src/libvirt_vcpu_plug_unplug.py

Added cpuhotplug with avocado test(stress) in background
and test to run multiple iterations.

Added cpuhotplug with stress tests and iterations

---

v2v/tests/cfg/convert_from_file.cfg
v2v/tests/cfg/specific_kvm.cfg
v2v/tests/src/convert_from_file.py
v2v/tests/src/specific_kvm.py

Rename guest on v2v conversion

---

libvirt/tests/src/virsh_cmd/domain/virsh_dump.py

Use process.run from avocado instead.Therefore test log won't be
printed in console.

virsh_dump: remove os.system and utils.run

---

libvirt/tests/cfg/virtual_disks/at_dt_iscsi_disk.cfg

fix indent alignment issue in at iscsi disk

---

v2v/tests/cfg/convert_vm_to_libvirt.cfg
v2v/tests/cfg/convert_vm_to_ovirt.cfg

Support vmware esx6.5 hypervisor convert by v2v.
Signed-off-by: Kun Wei <kuwei@redhat.com>

Add esx6.5 matrix testing

---

libvirt/tests/cfg/virsh_cmd/domain/virsh_domrename.cfg
libvirt/tests/src/virsh_cmd/domain/virsh_domrename.py

"domrename" is a newly involved virsh command from rhel7.3.
Here add normal tests for it.

Add domrename tests

---

libvirt/tests/src/migration/migrate_vm.py

The firewalld service is started on source host, so migration from
target host to source host will fail due to some required ports
disabled. This is to enable those ports before this kind of migration
is executes.

migrate_vm: Enable required ports for migration

---

libvirt/tests/src/virsh_cmd/host/virsh_maxvcpus.py

The two options were forgotten

Fix missing options

---

v2v/tests/cfg/convert_from_file.cfg
v2v/tests/src/v2v_options.py

Add 'kernel-rt' package not dependence by virt-v2v chenckpoint.
Add two guest from different ova file compress method

V2v dependence

---

v2v/tests/src/convert_vm_to_ovirt.py

Check whether vga info in v2v log.

Additional log check for windows guests

---

libvirt/tests/src/virsh_cmd/domain/virsh_migrate.py

virsh migrate-postcopy needs a breathe time to trigger postcopy migration
that makes the VM in destination to be in running state.

virsh_migrate: migrate-postcopy takes 1~2 seconds to trigger postcopy

---

libvirt/tests/src/virsh_cmd/domain/virsh_domiftune.py

https://github.com/avocado-framework/avocado-vt/pull/1205

update as call in avocado-vt changed for further usage

---

libvirt/tests/src/virsh_cmd/domain/virsh_suspend.py

As a cleanup bring back the vm after suspend test is done,
remove autotest error module dependency.

virsh_suspend: resume the vm on suspend test completion

---

libvirt/tests/cfg/virsh_cmd/network/virsh_net_name.cfg

Skipping guest dmesg verify for host test

---

libvirt/tests/src/virtual_disks/at_dt_iscsi_disk.py

1. Disk xml info is already logged in libvirt.create_disk_xml(),
no need to be logged again.
2. Starting/Destroying a vm could be put at beginning to avoid
waste of time to prepare env such as iscsi backend if vm got
failure.
Signed-of-by: Yi Sun <yisun@redhat.com>

Remove unnecessary log and rearrange code steps

---

libvirt/tests/cfg/virsh_cmd/domain/virsh_domrename.cfg
libvirt/tests/src/virsh_cmd/domain/virsh_domrename.py

Add negative tests for domrename, including invalid_vm_status,
invalid_dom_name and invalid_new_name.

Add negative tests for domrename

---

v2v/tests/src/specific_kvm.py

This could fix the problem of can't get correct output with 'df'
command.

Update code for getting size of available space

---

v2v/tests/cfg/function_test_esx.cfg
v2v/tests/src/function_test_esx.py

- Convert esx guest that has vmtools installed

Add v2v function case of converting from esx

---

libvirt/tests/cfg/virtual_disks/virtual_disks_multidisks.cfg
libvirt/tests/src/virtual_disks/virtual_disks_multidisks.py

Also add qed format and lvm cases

Enable discard feature cases in multi disk

---

libvirt/tests/src/virsh_cmd/domain/virsh_domiftune.py

Fix variable referenced before assignment

Fix domiftune case

---

libvirt/tests/src/virsh_cmd/domain/virsh_qemu_monitor_command.py

starting vm which is running tracebacks with VMStartError as previous test
didn't clean the vm and destroy vm on cleanup for proper test execution.

virsh_qemu_monitor_command: ensure to start vm only if it is not alive

---

libvirt/tests/src/migration/migrate_vm.py

This is to change the machine type to alias value in order to leverage
libvirt to automatically create the machine type for the guest. This is
required when qemu-kvm and qemu-kvm-rhev are installed one by one which
have different machine type.

migrate_vm: Fix the machine type for remote guest

---

libvirt/tests/src/virtual_disks/virtual_disks_multidisks.py

Fix a spelling mistake

---

libvirt/tests/cfg/virtual_disks/startup_policy.cfg
libvirt/tests/src/virtual_disks/startup_policy.py

Add startup policy cases associatd with volume and disk
Add update policy by update-device command cases

startup_policy: Reconstruct to accommodate more options

---

libvirt/tests/src/virtual_network/iface_hotplug.py

Need more sleep for attachment take effect on ppc

Update iface_hotplug sleep time

---

libvirt/tests/src/virsh_cmd/host/virsh_domcapabilities.py

https://github.com/avocado-framework/avocado-vt/pull/1240 is closed, so
revert the changes which depends on it.

virsh_domcapabilities: backcommit the changes due to dependent patch

---

v2v/tests/cfg/specific_kvm.cfg
v2v/tests/src/specific_kvm.py

1.Prepare a bogus kernel image for testing
2.Update multi kernel case
Signed-off-by: weikunzz <1525690718@qq.com>

Modify two v2v cases from specific kvm

---

README.rst
tp-libvirt_review_comment_summary.rst

this doc may provide some kind of checklist
before submitting PR

add review comment summary document

---

libvirt/tests/src/virsh_cmd/host/virsh_capabilities.py

This is to fix the missing of ''

virsh_capabilities: Fix grep string

---

libvirt/tests/src/numa/numa_capabilities.py
libvirt/tests/src/numa/numa_memory.py
libvirt/tests/src/numa/numa_memory_migrate.py
libvirt/tests/src/numa/numad_vcpupin.py

There are some numa node without memory, so need to use the new function

Update numa cases for non-memory node

---

v2v/tests/src/convert_vm_to_libvirt.py
v2v/tests/src/convert_vm_to_ovirt.py

As bug1518517 has been verified,so move the env
back again.Thanks
Signed-off-by: weikunzz <kuwei@redhat.com>

Back the v2v libguestfs environment again

---

libvirt/tests/src/virsh_cmd/domain/virsh_domid.py

Use setup_remote_ssh_key to setup ssh autologin.

virsh_domid: Use setup_remote_ssh_key

---

libvirt/tests/cfg/virsh_cmd/domain/virsh_guestvcpus.cfg
libvirt/tests/src/virsh_cmd/domain/virsh_guestvcpus.py

Signed-off-by: Chenli Hu <chhu@redhat.com>

Modify the max vcpu number to adapt to the ppc default xml

---

libvirt/tests/src/virsh_cmd/domain/virsh_domdisplay.py

For spice with ssl case, spice tls should be configured in
qemu conf file, while for spice without ssl case, no spice
tls configuration is expected.
For environment restore, qemu and libvirtd should be restored
first, then restore vm.
So refine code to achieve above logicality.

Clean ssl qemu conf for without ssl case and refine code

---

libvirt/tests/src/virtual_network/iface_network.py

##avocado run --vt-type libvirt virtual_network.iface_network.qos_test
JOB ID     : 89a50259305829092bd9529ae872a6b6727d1474
JOB LOG    : /root/avocado/job-results/job-2017-12-12T07.52-89a5025/job.log
(1/3) type_specific.io-github-autotest-libvirt.virtual_network.iface_network.qos_test.qos_option_bandwidth.positive_test: PASS (30.80 s)
(2/3) type_specific.io-github-autotest-libvirt.virtual_network.iface_network.qos_test.qos_option_bandwidth.negtive_start_test: PASS (7.85 s)
(3/3) type_specific.io-github-autotest-libvirt.virtual_network.iface_network.qos_test.qos_option_bandwidth.negtive_remove_test: PASS (28.61 s)

fix as the unit can be optional for both 'K' and 'M' for all values

---

libvirt/tests/src/virsh_cmd/domain/virsh_numatune.py

- Expect failure when try to modify numatune mode when vm is alive
- Update code to fix the bad logic with cgroup cases

Fix failures for memtune cases

---

libvirt/tests/src/daemon/init_scripts.py

user virt-test is not available

Fix init_scripts case user bug

---

libvirt/tests/cfg/virtual_disks/virtual_disks_iscsi.cfg
libvirt/tests/src/virtual_disks/virtual_disks_iscsi.py

libvirt 3.9.0 afterwards,auth can be placed in source beside disk directly

add auth place in source element support

---

libvirt/tests/src/virsh_cmd/domain/virsh_qemu_agent_command.py

1) Fix "VM is dead" issue for error_test.no_ga, the root
cause is VM is not started. Fixup by start vm withou
qemu-guest-agent
2) Fix Login timeout Error when with error_test.vm_halt
and error_test.vm_paused,  it is normal that vm can't be
login when vm is paused or halt. Fix by add judgement
before wait_for_login.

qemu-agent-command: Fix two issues

---

libvirt/tests/src/virtual_disks/startup_policy.py

due to duplicated function calling

Fix startup policy update device case failures

---

MAINTAINERS

let us update the maintainers list for tp-libvirt

MAINTAINERS: update tp-libvirt maintainers list

---

libvirt/tests/src/virsh_cmd/network/virsh_net_autostart.py

virsh_net_autostart.py : Removing autotest dependency.

---

libvirt/tests/src/serial/serial_functional.py

Update for new serial dev format

---

libvirt/tests/cfg/virsh_cmd/host/virsh_cpu_models.cfg
libvirt/tests/src/virsh_cmd/host/virsh_cpu_models.py

Use complete_uri() to get remote uri.

virsh_cpu_models: Fix connect remote issue

---

libvirt/tests/src/virsh_cmd/host/virsh_domcapabilities.py

Local test don't need set remote_ip. So change the order for
remote test.

virsh_domcapabilities: Change the code order for remote test

---

libvirt/tests/src/virsh_cmd/domain/virsh_attach_detach_interface_matrix.py

case should wait for boot completation

Update for attach_detach_interace_matrix

---

v2v/tests/cfg/convert_vm_to_libvirt.cfg
v2v/tests/cfg/convert_vm_to_ovirt.cfg
v2v/tests/cfg/function_test_xen.cfg

v2v update xen, rhvm password
Signed-off-by: weikunzz <kuwei@redhat.com>

v2v update some resource host password

---

libvirt/tests/cfg/cpu/ppccpucompat.cfg
libvirt/tests/src/cpu/ppccpucompat.py

Add test to verify cpu compat mode guests in ppc

Add test to verify cpu compat mode guests in ppc

---

libvirt/tests/src/bios/virsh_boot.py

1) Fixup the failure of case negative_test.no_loader_type,
by adding timeout in virsh.start. This is because the
return of virsh.start sometimes is not integrated. The
cmd returned so quickly that not all of stream output
had been collected before that.
2) Add adaptation to depends PR in avocado-vt. the param in
set_os_attrs updated to **attrs

Fix some minor issues to virsh.boot

---

libvirt/tests/src/virsh_cmd/host/virsh_nodeinfo.py

On aarch64, the BogoMIPS value is used as frequency info.
Also remove dependency on autotest.

nodeinfo: Update check for aarch64

---

libvirt/tests/src/virsh_cmd/domain/virsh_domxml_from_native.py

Use the function to raise test failure and simplify code.

domxml_from_native: Update use check_exit_status

---

libvirt/tests/src/cpu/guestpin.py

This patch adds a workaround for fixing cgroup cpuset of guest vms after
host cpu hotunplug/plug sequence.
Details on the issue can be found under this link
https://www.ibm.com/developerworks/community/wikis/home?lang=en#!/wiki/W51a7ffcf4dfd_4b40_9d82_446ebc23c550/page/SMT%20and%20cgroup%20cpusets

Fixup: Workaround the cgroup issue during host cpu hotplug

---

libvirt/tests/src/virsh_cmd/domain/virsh_vcpuinfo.py

Add set_remote_ssh_key to setup autologin.

virsh_vcpuinfo: Use setup_remote_ssh_key

---

libvirt/tests/src/virsh_cmd/domain/virsh_dump.py

It is different value between x86_64 and ppc64

Update virsh_dump case for PPC

---

libvirt/tests/cfg/virsh_cmd/pool/virsh_pool_create.cfg
libvirt/tests/src/virsh_cmd/pool/virsh_pool_create.py

Add some negative cases for pool_create
Besides, update some deprecated code

Add new cases for storage pool create

---

libvirt/tests/cfg/virsh_cmd/domain/virsh_migration.cfg
libvirt/tests/src/virsh_cmd/domain/virsh_migration.py

As virsh_migrate.py grew up and difficult to maintain, added testcases
in new file for further development.
Suggested-by: Dan Zheng <dzheng@redhat.com>

virsh_migration: Migration testcases development

---

v2v/tests/cfg/v2v_options.cfg

The change has commit before but missing the part,
Commit again,sorry for the message.
Signed-off-by: Kun Wei <kuwei@redhat.com>

v2v update xen host password

---

libvirt/tests/src/virsh_cmd/domain/virsh_dump.py

Fix the dump flag value on PPC

---

libvirt/tests/cfg/libvirt_mem.cfg
libvirt/tests/src/libvirt_mem.py

Add memory hot-unplug feature
Tested on ppc64le architecture

libvirt_mem: Add memory hot-unplug feature

---

libvirt/tests/cfg/virsh_cmd/monitor/virsh_domstate.cfg
libvirt/tests/src/virsh_cmd/monitor/virsh_domstate.py

1. Add case for check guest's domstate reason after guest core
dumped by 'virsh dump'.
2. Add case for check guest's domstate reason after reboot and
crash guest by 'kill -9'

Add case for domstate

---

libvirt/tests/src/virsh_cmd/domain/virsh_reboot.py

when extra args are not available virsh command formed is not
appropriate.

virsh_reboot: form virsh reboot command appropriate

---

libvirt/tests/src/virsh_cmd/monitor/virsh_domstate.py

with on_crash as preserve, guest will be in crashed (panicked) state after
triggering crash, with virsh reset guest state changes to paused (crashed)
and requires virsh resume for reboot to proceed.
https://bugzilla.redhat.com/show_bug.cgi?id=1269575

virsh_domstate: virsh resume required for guest to reboot preserved vm

---

libvirt/tests/cfg/virsh_cmd/monitor/virsh_domstate.cfg
libvirt/tests/src/virsh_cmd/monitor/virsh_domstate.py

Add test for 'rename-restart' crash action.

virsh_domstate: Add rename-restart test

---

libvirt/tests/src/virsh_cmd/domain/virsh_domblkerror.py

unspecified_error testcase uses nfs setup to simulate the error,
check for nfs package available before starting the test.

virsh_domblkerror: check to install nfs packages

---

libvirt/tests/cfg/virsh_cmd/domain/virsh_attach_detach_disk.cfg
libvirt/tests/src/virsh_cmd/domain/virsh_attach_detach_disk.py

fix_twice_diff_error_in_attach_detach_disk

---

libvirt/tests/src/libvirt_mem.py

libvirt_mem: Fix the file nonexistent and adapt x86_64

---

libvirt/tests/cfg/libvirt_pci_passthrough_hotplug.cfg
libvirt/tests/src/libvirt_pci_passthrough_hotplug.py

This Test Case will do hotplug the single function of NIC or Infinibd adapter then it will ping to ouside world from hotplugged interface, guest life cylce, flood ping, virsh dump
then it will hotunplug the device.
Signed-off-by: prudhvi mprudhvi@linux.vnet.ibm.com

 Single function hostdev hotplug

---

libvirt/tests/src/virsh_cmd/filter/virsh_nwfilter_edit.py

nwfilter_edit: fix the arguments error

---

libvirt/tests/src/virtual_disks/at_dt_iscsi_disk.py
libvirt/tests/src/virtual_disks/startup_policy.py
libvirt/tests/src/virtual_disks/virtual_disks_ceph.py
libvirt/tests/src/virtual_disks/virtual_disks_encryption.py
libvirt/tests/src/virtual_disks/virtual_disks_gluster.py
libvirt/tests/src/virtual_disks/virtual_disks_iscsi.py
libvirt/tests/src/virtual_disks/virtual_disks_multidisks.py
libvirt/tests/src/virtual_disks/virtual_disks_multivms.py

PY3 : Port to python3 virtual disks

---

libvirt/tests/cfg/virsh_cmd/volume/virsh_vol_resize.cfg
libvirt/tests/src/virsh_cmd/volume/virsh_vol_resize.py

Sign-offed by: Yi Sun(lentosun@163.com)

Cover LUKS encryption volumes with vol-resize

---

libvirt/tests/cfg/virsh_cmd/volume/virsh_vol_download_upload.cfg
libvirt/tests/src/virsh_cmd/volume/virsh_vol_download_upload.py

Sign-offed by: Yi Sun (lentosun@163.com)

Add cases to cover luks vol-download and vol-upload

---

libvirt/tests/cfg/virtual_disks/virtual_disks_usb.cfg
libvirt/tests/src/virtual_disks/virtual_disks_usb.py

1. remove all usb devices from vm
2. add usb controllers to vm
3. plug usb virtual disk to vm
4. check disk in vm
5. unplug disk from vm

Cover usb virtual disk plug/unplug cases

---

libvirt/tests/src/virsh_cmd/domain/virsh_attach_detach_disk.py

fix twice_diff_with_shareable error in virsh_attach_detach_disk

---

libvirt/tests/src/virsh_cmd/domain/virsh_migrate.py
libvirt/tests/src/virsh_cmd/domain/virsh_migrate_compcache.py
libvirt/tests/src/virsh_cmd/domain/virsh_migrate_set_get_speed.py
libvirt/tests/src/virsh_cmd/domain/virsh_vncdisplay.py
libvirt/tests/src/virsh_cmd/host/virsh_version.py
libvirt/tests/src/virsh_cmd/volume/virsh_vol_clone_wipe.py
libvirt/tests/src/virsh_cmd/volume/virsh_vol_create_from.py
libvirt/tests/src/virsh_cmd/volume/virsh_vol_download_upload.py
libvirt/tests/src/virsh_cmd/volume/virsh_vol_resize.py
libvirt/tests/src/virsh_cmd/volume/virsh_volume.py

- Remote autotest reference
- Replace exceptions.Test* with test.*
- Other updates according to rules

Python 3: Port to Python3 for 10 pys

---

libvirt/tests/src/virt_admin/management/virt_admin_server_clients_set.py
libvirt/tests/src/virt_admin/virt_admin_itself.py
libvirt/tests/src/virt_cmd/virt_clone.py
libvirt/tests/src/virt_cmd/virt_top.py
libvirt/tests/src/virt_cmd/virt_what.py
libvirt/tests/src/virt_cmd/virt_xml_validate.py

1. Port to Python3
2. Remove autotest dependency

Python 3: Port virt_admin and virt_cmd

---

libvirt/tests/src/conf_file/qemu_conf/set_virtlogd.py
libvirt/tests/src/controller/controller_functional.py
libvirt/tests/src/cpu/vcpu_hotpluggable.py
libvirt/tests/src/libvirt_hugepage.py
libvirt/tests/src/libvirt_mem.py
libvirt/tests/src/libvirt_usb_hotplug_controller.py
libvirt/tests/src/libvirt_vcpu_plug_unplug.py
libvirt/tests/src/numa/guest_numa.py
libvirt/tests/src/numa/numa_memory_migrate.py
libvirt/tests/src/svirt/dac_nfs_disk.py
libvirt/tests/src/svirt/dac_vm_per_image_start.py
libvirt/tests/src/svirt/svirt_attach_disk.py
libvirt/tests/src/virtual_disks/at_dt_iscsi_disk.py
libvirt/tests/src/virtual_disks/virtual_disks_ceph.py
libvirt/tests/src/virtual_disks/virtual_disks_encryption.py
libvirt/tests/src/virtual_disks/virtual_disks_iscsi.py
libvirt/tests/src/virtual_disks/virtual_disks_multidisks.py
libvirt/tests/src/virtual_disks/virtual_disks_multivms.py
libvirt/tests/src/virtual_network/iface_network.py
libvirt/tests/src/virtual_network/iface_ovs.py

Python 3: Port non virsh cmd py files to PY3
1) Remove autotest dependency
2) Port to PY3

Python 3: Port others py files of acceptance case to PY3

---

libvirt/tests/src/channel/channel_functional.py
libvirt/tests/src/conf_file/libvirtd_conf/host_uuid.py
libvirt/tests/src/conf_file/libvirtd_conf/unix_sock.py
libvirt/tests/src/conf_file/qemu_conf/auto_dump.py
libvirt/tests/src/conf_file/qemu_conf/clear_emulator_capabilities.py
libvirt/tests/src/conf_file/qemu_conf/seccomp_sandbox.py
libvirt/tests/src/conf_file/qemu_conf/set_process_name.py
libvirt/tests/src/conf_file/sysconfig_libvirtd/libvirtd_config.py

All py files under src/conf_file are porting
compatible with py2 and py3, and removed autotest
dependancies

Python 3: Port src/conf_file

---

libvirt/tests/src/cpu/guestpin.py
libvirt/tests/src/cpu/ppccpucompat.py

Python 3: Port cpu

---

libvirt/tests/src/svirt/dac_nfs_disk.py

dac_nfs_disk: Fix the file error

---

libvirt/tests/src/hotplug_serial.py
libvirt/tests/src/kernel_panic.py
libvirt/tests/src/limit.py
libvirt/tests/src/macvtap.py
libvirt/tests/src/multifunction.py
libvirt/tests/src/multiqueue.py
libvirt/tests/src/perf_kvm.py
libvirt/tests/src/remove_guest.py
libvirt/tests/src/resource_abnormal.py
libvirt/tests/src/smt.py
libvirt/tests/src/storage_discard.py
libvirt/tests/src/timer_management.py
libvirt/tests/src/usb_passthrough.py
libvirt/tests/src/vfio.py

Porting to Python 3 compatible with Python2, and remove
autotest dependencies

Port 3: Port another 14 files

---

libvirt/tests/src/virsh_cmd/domain/virsh_attach_detach_disk.py

Fix the ERROR in virsh_attach_detach_disk with detach test problem

---

libvirt/tests/src/virsh_cmd/domain/virsh_attach_detach_disk_lxc.py
libvirt/tests/src/virsh_cmd/domain/virsh_create_lxc.py
libvirt/tests/src/virsh_cmd/domain/virsh_domfsfreeze_domfsthaw.py
libvirt/tests/src/virsh_cmd/domain/virsh_domfsthaw.py
libvirt/tests/src/virsh_cmd/domain/virsh_domtime.py
libvirt/tests/src/virsh_cmd/domain/virsh_domxml_to_native.py
libvirt/tests/src/virsh_cmd/domain/virsh_migrate_copy_storage.py
libvirt/tests/src/virsh_cmd/domain/virsh_migrate_setmaxdowntime.py
libvirt/tests/src/virsh_cmd/domain/virsh_migrate_virtio_scsi.py
libvirt/tests/src/virsh_cmd/domain/virsh_numatune.py
libvirt/tests/src/virsh_cmd/domain/virsh_qemu_agent_command.py
libvirt/tests/src/virsh_cmd/domain/virsh_qemu_monitor_blockjob.py
libvirt/tests/src/virsh_cmd/domain/virsh_schedinfo_xen_credit.py
libvirt/tests/src/virsh_cmd/host/virsh_nodesuspend.py
libvirt/tests/src/virsh_cmd/interface/virsh_iface_bridge.py
libvirt/tests/src/virsh_cmd/nodedev/virsh_nodedev_create_destroy.py
libvirt/tests/src/virsh_cmd/pool/virsh_pool_acl.py
libvirt/tests/src/virsh_cmd/snapshot/virsh_snapshot_disk.py
libvirt/tests/src/virsh_cmd/virsh_connect.py
libvirt/tests/src/virsh_cmd/virsh_help.py
libvirt/tests/src/virsh_cmd/virsh_itself.py
libvirt/tests/src/virsh_cmd/volume/virsh_volume_application.py

Changes:
1) Remove autotest dependency
2) Port to Python 3

Python 3: Port left virsh_cmd py files

---

libvirt/tests/src/numa/numa_memory_migrate.py

numa_memory_migrate: Fix the list error

---

libvirt/tests/src/virtual_disks/at_dt_iscsi_disk.py
libvirt/tests/src/virtual_disks/virtual_disks_multivms.py

PY3 : Remove autotest dependency in virtual_disks

---

libvirt/tests/src/cpu/guestpin.py

Looks like libvirt cgroup path is different for
ubuntu distro, so handle multiple paths to resolve
libvirt cgroup folders.

Fixup: Handle cgroup path for different distros

---

libvirt/tests/src/virtual_network/iface_options.py

1) Remove autotest dependency
2) Port to Python3

Python 3: Port virtual_network/iface_options.py

---

libvirt/tests/src/libvirt_hooks.py
libvirt/tests/src/libvirt_mem.py
libvirt/tests/src/libvirt_network_bandwidth.py
libvirt/tests/src/libvirt_pci_passthrough.py
libvirt/tests/src/libvirt_qemu_cmdline.py
libvirt/tests/src/libvirt_rng.py
libvirt/tests/src/libvirt_scsi.py
libvirt/tests/src/libvirt_usb_hotplug_device.py

Python 3: Port libvirt_*.py and 2 misc py files

---

libvirt/tests/src/virsh_cmd/domain/virsh_create_lxc.py
libvirt/tests/src/virsh_cmd/domain/virsh_reset.py
libvirt/tests/src/virsh_cmd/nodedev/virsh_nodedev_dumpxml.py
libvirt/tests/src/virsh_cmd/secret/virsh_secret_define_undefine.py
libvirt/tests/src/virsh_cmd/secret/virsh_secret_dumpxml.py
libvirt/tests/src/virsh_cmd/secret/virsh_secret_list.py
libvirt/tests/src/virsh_cmd/snapshot/virsh_snapshot_create_as.py

Python 3: replace commands with process for several virsh_cmd dirs

---

v2v/tests/src/install.py

Remove 'autotest' from v2v test script: install.py

---

libguestfs/tests/guestfish_augeas.py
libguestfs/tests/guestfish_block_dev.py
libguestfs/tests/guestfish_file_dir.py
libguestfs/tests/guestfish_fs_attr_ops.py
libguestfs/tests/guestfish_fs_mount.py
libguestfs/tests/guestfish_fs_swap.py
libguestfs/tests/guestfish_lvm.py
libguestfs/tests/guestfish_misc.py
libguestfs/tests/guestfs_add.py
libguestfs/tests/guestfs_block_operations.py
libguestfs/tests/guestfs_file_operations.py
libguestfs/tests/guestfs_inspect_operations.py
libguestfs/tests/guestfs_list_operations.py
libguestfs/tests/guestfs_operated_disk.py
libguestfs/tests/guestfs_part_operations.py
libguestfs/tests/guestfs_volume_operations.py
libguestfs/tests/guestmount.py
libguestfs/tests/virt_cat.py
libguestfs/tests/virt_edit.py
libguestfs/tests/virt_file_operations.py
libguestfs/tests/virt_inspect_operations.py
libguestfs/tests/virt_list_operations.py
libguestfs/tests/virt_part_operations.py
libguestfs/tests/virt_sysprep.py
libguestfs/tests/virt_sysprep_opt.py
libguestfs/tests/virt_volume_operations.py
libguestfs/tests/virt_win_reg.py

1) Remove autotest dependency
2) Use 2to3 to do some port

Python 3: remove autotest dependency and do some porting for libguestfs

---

libvirt/tests/cfg/libvirt_pci_passthrough_hotplug.cfg
libvirt/tests/src/libvirt_pci_passthrough_hotplug.py

This patch will add the flood ping test to hot plugged guest with host device.
Signed-off-by: prudhvi <mprudhvi@linux.vnet.ibm.com>

This patch will add the flood ping test to hot plugged guest with host device

---

libvirt/tests/src/virtual_network/iface_ovs.py

This will install openvswitch package and start the daemon if it is not active.

iface_ovs.py: openvswitch package installation.

---

libvirt/tests/cfg/sriov/sriov.cfg
libvirt/tests/src/sriov/sriov.py

Add test for sriov:
1.Create vfs;
2.Check the node device info of the pf and vf;
3.Plug/unPlug vfs;
4.Do operatoin with guest having vfs;
Signed-off-by: yafu <yafu@redhat.com>

Add test for sriov

---

provider/v2v_vmcheck_helper.py
v2v/tests/src/convert_from_file.py
v2v/tests/src/convert_vm_to_libvirt.py
v2v/tests/src/convert_vm_to_ovirt.py
v2v/tests/src/function_test_esx.py
v2v/tests/src/function_test_xen.py
v2v/tests/src/specific_kvm.py
v2v/tests/src/v2v_options.py

Python3 : v2v cases

---

libvirt/tests/src/multifunction.py
libvirt/tests/src/virsh_cmd/domain/virsh_blockresize.py
libvirt/tests/src/virsh_cmd/domain/virsh_create.py
libvirt/tests/src/virsh_cmd/domain/virsh_dump.py
libvirt/tests/src/virsh_cmd/interface/virsh_iface_trans.py

Python 3: re-update for autotest commands removal

---

libvirt/tests/cfg/virsh_cmd/nodedev/virsh_nodedev_event.cfg
libvirt/tests/src/virsh_cmd/nodedev/virsh_nodedev_event.py

(1) nodedev-event --list
(2) nodedev-event --event lifecycle
(3) nodedev-event --loop
(4) nodedev-event --timeout

Add test for nodedev-event

---

libvirt/tests/cfg/virtual_network/iface_hotplug.cfg

Add e1000e model type for interface device for hotplug interface or
device.

Add model type 'e1000e' for interface

---

libvirt/tests/cfg/virsh_cmd/domain/virsh_attach_device.cfg
libvirt/tests/src/virsh_cmd/domain/virsh_attach_device.py

https://github.com/avocado-framework/avocado-vt/pull/1450

add alias test for attach device

---

libvirt/tests/src/virsh_cmd/domain/virsh_attach_detach_interface_matrix.py

attach_detach_interface_matrix: Update for console_manager

---

libvirt/tests/cfg/virsh_cmd/monitor/virsh_perf.cfg
libvirt/tests/src/virsh_cmd/monitor/virsh_perf.py

Add performance monitor events test cases

---

libvirt/tests/src/virsh_cmd/domain/virsh_dumpxml.py

Since libvirt 3.9, libvirt query qemu/kvm to get one feature support
or not by qemu, all supported features are given by host model + features
list in domcapabilities.xml. host model is one set of feature lists
defined in /usr/lib/libvirt/cpu_map.xml
While on older version, libvirt directly query host /proc/cpuinfo to get
whether host cpu support one feature or not. If one feature is found, 
means it is supported, which is unbelievable when this feature can't
be simulated by qemu.
Change:
Query domcapabilites and cpu_map.xml to get one feature support
or not.

dumpxml: --update-cpu with query qemu/kvm for feature support query

---

v2v/tests/cfg/function_test_xen.cfg
v2v/tests/src/function_test_esx.py

v2v:modify function_xen re string and remove function_esx snapshot
1.Modify function_xen re string,case has update.
2.No need to check snapshot file,and remove it
Signed-off-by: kuwei <kuwei@redhat.com>

v2v:modify function_xen re string and remove function_esx snapshot 

---

libvirt/tests/src/libvirt_hooks.py

Minorfix: Fixup misspell

---

provider/v2v_vmcheck_helper.py
v2v/tests/src/convert_from_file.py
v2v/tests/src/convert_vm_to_libvirt.py
v2v/tests/src/convert_vm_to_ovirt.py
v2v/tests/src/function_test_esx.py
v2v/tests/src/function_test_xen.py
v2v/tests/src/specific_kvm.py
v2v/tests/src/v2v_options.py

Add lxc hook tests to libvirt_hooks

---

libvirt/tests/cfg/virsh_cmd/domain/virsh_cpu_stats.cfg
libvirt/tests/src/virsh_cmd/domain/virsh_cpu_stats.py

changes in this commit:
1. add powpc cases
2. add case with no vm start
3. several negative cases
4. add error message checking for negative cases

virsh_cpu_stats: add new cases and more strict result checking

---

libvirt/tests/cfg/libvirt_mem.cfg

Add param value for 'vcpu'

---

libvirt/tests/cfg/controller/multiple_controller_ppc.cfg
libvirt/tests/src/controller/multiple_controller_ppc.py

Add multiple controller case

---

libvirt/tests/cfg/virtual_network/iface_options.cfg
libvirt/tests/src/virtual_network/iface_options.py

1. Test the rx_queue_size/tx_queue_size can only be a power
of 2 between 256 and 1024
2. Test invalid value setting for rx_queue_size/tx_queue_size

Add case for rx/tx queue size

---

libvirt/tests/src/virsh_cmd/domain/virsh_cpu_stats.py

fix count error in cpu_stats

---

libvirt/tests/cfg/virsh_cmd/domain/virsh_migrate.cfg

virsh_migrate: Fix the missing param for nfs

---

libvirt/tests/cfg/libvirt_mem.cfg

libvirt_mem:Add comments to be replaced on p9

---

libvirt/tests/cfg/nwfilter/nwfilter_vm_start.cfg

Modify nwfilter clean-traffic check condition

---

libvirt/tests/cfg/virtual_device/input_devices.cfg
libvirt/tests/src/virtual_device/input_devices.py

Add the test cases for input devices

---

libvirt/tests/src/serial/serial_functional.py

Fix the address already in use issue in serial

---

libvirt/tests/cfg/serial/serial_functional.cfg
libvirt/tests/src/serial/serial_functional.py

Add test for only the first console can be a serial

---

libvirt/tests/src/virsh_cmd/domain/virsh_domiftune.py

Update some variant name by comments on #1538

Modify the domiftune by the comments on #1538

---

libvirt/tests/src/virtual_network/iface_options.py

In the error test, we should unload the vhost-net module and remove the
/dev/vhost_net character device as well. And the device will be
recovered with "modprobe vhost-net". So don't need to modify the driver
module in kernel.

Fix issue in iface_driver error test

---

libvirt/tests/src/virtual_disks/virtual_disks_luks.py

One except clause issue and one bool value issue.

Python 3: Fix python 3 issues for virtual_disks_luks script

---

libvirt/tests/cfg/controller/controller_functional.cfg
libvirt/tests/src/controller/controller_functional.py

Add some more test cases for pci bridges.

controller_functional: Add cases for pci-bridge

---

libvirt/tests/src/virsh_cmd/domain/virsh_domfsinfo.py

Python 3: Minorfix domfsinfo Typo issue

---

libvirt/tests/src/virsh_cmd/volume/virsh_vol_clone_wipe.py
libvirt/tests/src/virsh_cmd/volume/virsh_vol_create.py
libvirt/tests/src/virsh_cmd/volume/virsh_vol_resize.py

Python 3: Fix base64 encoding for virsh_vol_xx

---

libvirt/tests/cfg/virtual_disks/virtual_disks_multidisks.cfg
libvirt/tests/src/virtual_disks/virtual_disks_multidisks.py

case cover attach disk provisioned by nfs pool volume
also cover iteratively attach disk scenarios

add nfs pool disk cases

---

libvirt/tests/src/cpu/vcpu_hotpluggable.py

Remove influence from topology settings

---

libvirt/tests/cfg/libvirt_vcpu_plug_unplug.cfg
libvirt/tests/src/libvirt_vcpu_plug_unplug.py

Modify topology correction to use from method as
currently it implements the check if given additional
argument.

Modify topology correction to use from method

---

libvirt/tests/src/virsh_cmd/volume/virsh_vol_create_from.py

Check if libvirtd crash when vol_create_from
a qcow2 vol to a raw vol

vol_create_from: Automate bz 1363636

---

libvirt/tests/src/virsh_cmd/domain/virsh_blockcommit.py

To make sure we get disk, not cdrom

---

libvirt/tests/cfg/smt.cfg
libvirt/tests/src/smt.py

Added negative testcase scenarios and
changed to local smp param as it might
get wrong value from other global configs.

Add negative test case scenarios

---

libvirt/tests/src/virtual_device/sound_device.py

Deal with situation that vm's pid file not exists

---

libvirt/tests/src/conf_file/qemu_conf/set_virtlogd.py
libvirt/tests/src/virsh_cmd/domain/virsh_domfstrim.py

[python3] Fix the oct and stdout issues

---

libvirt/tests/src/virsh_cmd/volume/virsh_vol_resize.py

When secret define and get error in base64 operation, as uuid is not returned
recover step for secret undefine will not be executed, so fix it by split func
create_luks_secret in 2 part

Fix the recover for secret undefine

---

libvirt/tests/cfg/cpu/vcpu_hotpluggable.cfg
libvirt/tests/src/cpu/vcpu_hotpluggable.py

Signed-off-by: Chenli Hu <chhu@redhat.com>

Add test for vcpu hotpluggable using setvcpu

---

libvirt/tests/cfg/virtual_disks/virtual_disks_ceph.cfg
libvirt/tests/src/virtual_disks/virtual_disks_ceph.py

when using sanlock for virtualdisk, snapshots can be taken normally.

add sanlock snapshot case

---

libvirt/tests/src/virtual_disks/virtual_disks_multidisks.py

Replace 'skip' with 'cancel'

---

libvirt/tests/cfg/virsh_cmd/domain/virsh_cpu_stats.cfg
libvirt/tests/cfg/virsh_cmd/domain/virsh_detach_device.cfg
libvirt/tests/cfg/virsh_cmd/domain/virsh_reboot.cfg
libvirt/tests/cfg/virsh_cmd/domain/virsh_suspend.cfg
libvirt/tests/src/virsh_cmd/domain/virsh_detach_device.py
libvirt/tests/src/virsh_cmd/domain/virsh_reboot.py
libvirt/tests/src/virsh_cmd/domain/virsh_suspend.py

RHEL7-17076
virsh.reboot
RHEL7-17121
virsh.suspend
work in progress now

Automate some simple cases. 

---

libvirt/tests/src/conf_file/sysconfig_libvirt_guests/libvirt_guests.py

1) Now, there will be some selinux logs during restart libvirt-guests.service.
So the msg about guests parallel shutdown are not always stick togther.
Hence, modified the old checking method.
2) One checking point is missed, when on_shutdown = shutdown, on_boot=ignore,
the guest should be in shutdown status after restarting libvirt-guests.service.
So, add a checking point named check_on_shutdown_vm_status

Fix 2 issues in the libvirt-guests cases:

---

libvirt/tests/src/virsh_cmd/volume/virsh_vol_resize.py

Add info of stderr to fail reason

---

libvirt/tests/cfg/virsh_cmd/network/virsh_net_define_undefine.cfg
libvirt/tests/src/virsh_cmd/network/virsh_net_define_undefine.py

Add more scenarios about undefine networks to cover different status of
networks.

Add more scenarios for network undefine

---

libvirt/tests/src/migration/migrate_vm.py

Minorfix: load_stress function is changed

---

libvirt/tests/cfg/virtual_network/iface_network.cfg
libvirt/tests/src/virtual_network/iface_network.py

1. Add open forward mode test
2. Add checking rules of iptables for nat, isolated, route forward mode
3. Add check for dnsmasq process
4. Add check for missing part in dnsmasq conf

Update for net forward and dnsmasq test

---

v2v/tests/cfg/convert_vm_to_ovirt.cfg

1.A word is wrong, fix it again.Sorry
Signed-off-by: kuwei <kuwei@redhat.com>

V2V: A small error update in convert_vm_ovirt.cfg

---

libvirt/tests/src/migration/migrate_vm.py

Python3: Replace has_key() with in

---

libvirt/tests/cfg/libvirt_vcpu_plug_unplug.cfg
libvirt/tests/src/libvirt_vcpu_plug_unplug.py

Add vcpu hotplug with VM reboot test scenario

Add vcpu hotplug with VM reboot test scenario

---

libvirt/tests/src/virsh_cmd/domain/virsh_setmem.py

Need more wait for set_mem take effect on ppc

Update set_mem wait time

---

libvirt/tests/src/virtual_network/iface_coalesce.py

[Python3] Small fix for stderr

---

libvirt/tests/src/virtual_disks/virtual_disks_ceph.py

Error Message update from 'Connection reset by peer'
to 'Could not create file: Permission denied'

Fix error message change issue from libvirt

---

libvirt/tests/cfg/virsh_cmd/monitor/virsh_perf.cfg

Remove test cases about cmt mbml mbmt events

---

libvirt/tests/cfg/serial/serial_functional.cfg
libvirt/tests/src/serial/serial_functional.py

Add tls related test cases for serial device

---

v2v/tests/cfg/function_test_esx.cfg
v2v/tests/cfg/v2v_options.cfg
v2v/tests/src/v2v_options.py

1.Add esxi case in function_esx.py
2.Add vmx_ssh case in v2v-option
3.Add negative_test in v2v-option
4.Add case simulate nfs in local in v2v-option
Signed-off-by: kuwei <kuwei@redhat.com>

V2v:Add 4 new cases

---

libvirt/tests/src/npiv/npiv_restart_libvirtd.py

fix "Undefined variable 'test'" problems in tp-libvirt/libvirt/tests/src/npiv/npiv_restart_libvirtd.py

Fix test undefine error in npiv_restart_libvirtd.

---

libvirt/tests/cfg/virsh_cmd/domain/virsh_domxml_to_native.cfg
libvirt/tests/src/virsh_cmd/domain/virsh_domxml_to_native.py

Automate some virsh domxml-to-native cases

---

libvirt/tests/src/libvirt_bench/libvirt_bench_vcpu_hotplug.py

This patches tries to port this test to work in powerpc
host/guest and cleaned stress inside guest during test end.

Port test for ppc

---

libvirt/tests/cfg/virsh_cmd/pool/virsh_pool.cfg
libvirt/tests/src/virsh_cmd/pool/virsh_pool.py

the new cases are special_pool_name,
invalid_pool_name, same_iqn and 
multiple_iqn. 
Also update some deprecated code.

virsh.pool: add some new cases

---

libvirt/tests/cfg/npiv/npiv_hostdev_passthrough.cfg
libvirt/tests/src/npiv/npiv_hostdev_passthrough.py

1. hot attach hot detach
2. cold attach hot detach
Signoff: Yi Sun (lentosun@163.com)
depend on avocado-framework/avocado-vt#797
https://github.com/avocado-framework/avocado-vt/pull/826

Add script to cover npiv hostdev passthrough cases

---

libvirt/tests/src/npiv/npiv_hostdev_passthrough.py

There are some script issues in this script and it was merged before
I update the original pr#938. So make a quick fix up here.

Fix npiv hostdev script issues

---

libvirt/tests/src/virtual_network/iface_network.py

change the place for parameter definition

Fix iface network error

---

libvirt/tests/cfg/sriov/sriov.cfg
libvirt/tests/src/sriov/sriov.py

Add two cases in sriov test:
1.Attach the VF of VF Pool to the guest with VFIO driver with "managed=no";
2.Define network with duplicate vf list;
3.Add alias name in the interface xml;
Signed-off-by: yafu <yafu@redhat.com>

Add three cases in sriov test

---

libvirt/tests/src/virsh_cmd/domain/virsh_domblklist.py
libvirt/tests/src/virsh_cmd/domain/virsh_domjobinfo.py

[python3] Fix domain related cmd compatible issues

---

libvirt/tests/cfg/numa/numa_capabilities.cfg
libvirt/tests/cfg/numa/numa_preferred_undefine.cfg
libvirt/tests/cfg/numa/numad_vcpupin.cfg

Update the cfg for numa cases

---

libvirt/tests/src/virsh_cmd/snapshot/virsh_snapshot_create_as.py

In python3, string.lowercase removed

Python 3: string.lowercase fixup

---

provider/v2v_vmcheck_helper.py

Python3: stdout_text to stdout in v2v vmcheck

---

libvirt/tests/cfg/virsh_cmd/volume/virsh_vol_clone_wipe.cfg
libvirt/tests/cfg/virsh_cmd/volume/virsh_vol_create.cfg
libvirt/tests/src/virsh_cmd/volume/virsh_vol_clone_wipe.py
libvirt/tests/src/virsh_cmd/volume/virsh_vol_create.py

This case is for bug 1291035, about create/clone
volume with "/" in volume name.

vol create/clone: Add one negative case

---

libvirt/tests/cfg/virtual_device/watchdog.cfg
libvirt/tests/src/virtual_device/watchdog.py

Test for watchdog device:
1.Add watchdog device to the guest
2.Start the guest
3.Trigger the watchdog in the guest
4.Confirm the guest status

Add test for watchdog device

---

libvirt/tests/src/virtual_disks/virtual_disks_ceph.py

By copying one disk xml for additional guest VM.

Fix No such file or directory when attaching disk xml

---

libvirt/tests/src/conf_file/libvirtd_conf/unix_sock.py

[python3] Modify for div oper changed

---

libvirt/tests/cfg/bios/virsh_boot.cfg

Update the error msg to be more common

virsh.boot: Fixup pattern match failed

---

provider/v2v_vmcheck_helper.py

Python3: stdout to stdout_text in vmcheck of v2v

---

libvirt/tests/src/conf_file/sysconfig_libvirt_guests/libvirt_guests.py

1. Match patten changed to libvirt-guests.sh[xxx]: so update mapping rule
2. Start rsyslog service when absent
3. Sleep more time to get completed messages
4. Add more debug info
depends on https://github.com/avocado-framework/avocado-vt/pull/1616

Fix for libvirt_guests test

---

libvirt/tests/src/virtual_disks/virtual_disks_multipath.py

Fix test.fail issue for virtual_disk_multipath

---

libvirt/tests/src/npiv/npiv_concurrent.py
libvirt/tests/src/npiv/npiv_virtual_disk.py

Fix some npiv script issues

---

libvirt/tests/src/conf_file/qemu_conf/set_virtlogd.py

Fix a qemu_conf set_virtlogd issue

---

libvirt/tests/src/virsh_cmd/nodedev/virsh_nodedev_event.py

[python3]Fix for nodedev testing

---

libvirt/tests/cfg/multivm_stress/multivm_cpustress.cfg
libvirt/tests/src/multivm_stress/multivm_stress.py

Add host stress combinations for multivm stress tests

multivm_stress: Add host stress test combinations

---

libvirt/tests/cfg/virsh_cmd/network/virsh_net_autostart.cfg
libvirt/tests/src/virsh_cmd/network/virsh_net_autostart.py

virsh_net_autostart: Add readonly test

---

libvirt/tests/cfg/virsh_cmd/domain/virsh_domxml_to_native.cfg
libvirt/tests/src/virsh_cmd/domain/virsh_domxml_to_native.py

virsh_domxml_to_native: Add readonly test

---

libvirt/tests/cfg/virsh_cmd/network/virsh_net_start.cfg
libvirt/tests/src/virsh_cmd/network/virsh_net_start.py

start network when readonly is enabled

virsh_net_start: Add readonly test

---

libvirt/tests/cfg/virsh_cmd/domain/virsh_save.cfg
libvirt/tests/src/virsh_cmd/domain/virsh_save.py

Add readonly test for save

---

libvirt/tests/cfg/virsh_cmd/nodedev/virsh_nodedev_reset.cfg
libvirt/tests/src/virsh_cmd/nodedev/virsh_nodedev_reset.py

virsh_nodedev_reset: Add readonly test

---

libvirt/tests/cfg/virsh_cmd/host/virsh_hostname.cfg
libvirt/tests/src/virsh_cmd/host/virsh_hostname.py

virsh_hostname: Add test to connect to a remote hypervisor

---

libvirt/tests/cfg/virsh_cmd/domain/virsh_domjobabort.cfg
libvirt/tests/src/virsh_cmd/domain/virsh_domjobabort.py

if domjobabort operate under readonly mode, operation will be denied

add domjob abort readonly case

---

libvirt/tests/cfg/serial/serial_functional.cfg

Change serial_functional tls client config

---

libvirt/tests/cfg/libvirt_mem.cfg
libvirt/tests/src/libvirt_mem.py

Added tests scenarious to cover max_slots.

Enable tests for max slots.

---

libvirt/tests/src/migration/migrate_vm.py

migrate_vm: minor fix for migration

---

libvirt/tests/src/virsh_cmd/domain/virsh_migrate_setmaxdowntime.py

Refer https://github.com/autotest/tp-libvirt/pull/1741

virsh_migrate_setmaxdowntime: Update params

---

v2v/tests/src/convert_from_file.py
v2v/tests/src/convert_vm_to_ovirt.py

Some function will get sasl_user from original params. So
we need to update the original sasl_user.

Update sasl_user in orignal params

---

libvirt/tests/cfg/virsh_cmd/network/virsh_net_event.cfg
libvirt/tests/src/virsh_cmd/network/virsh_net_event.py

Add timestamp test for net-event

---

libvirt/tests/cfg/virsh_cmd/monitor/virsh_domblkstat.cfg

virsh_domblkstat: Add cases for no device option test

---

v2v/tests/cfg/convert_vm_to_ovirt.cfg
v2v/tests/src/convert_vm_to_ovirt.py

Add -o rhv-upload option for convert_vm_to_ovirt file.

Support -o rhv-upload option for virt-v2v

---

v2v/tests/src/convert_from_file.py

Only set sasl_user when output_mode is rhev

---

libvirt/tests/cfg/migration/migrate_options_shared.cfg
libvirt/tests/src/migration/migrate_options_shared.py

migrate_options_shared: Add hpt resize PPC case

---

libvirt/tests/cfg/virtual_network/iface_hotplug.cfg
libvirt/tests/src/virtual_network/iface_hotplug.py

The error message check should be applicable for all the scenario's of "iface_attach".

The error message check should be applicable for all the scenario's of "iface_attach".

---

v2v/tests/cfg/function_test_esx.cfg
v2v/tests/src/convert_vm_to_libvirt.py
v2v/tests/src/convert_vm_to_ovirt.py
v2v/tests/src/function_test_esx.py

Use general function to cleanup constant files

---

v2v/tests/cfg/function_test_esx.cfg
v2v/tests/cfg/v2v_options.cfg

Fix some error commands and prompts for v2v

---

libvirt/tests/cfg/virsh_cmd/domain/virsh_blockcopy.cfg

invalid format case scenarios are missed in this situation

add invalid format negative scenarios into block copy

---

libvirt/tests/cfg/virsh_cmd/domain/virsh_setmem.cfg
libvirt/tests/src/virsh_cmd/domain/virsh_setmem.py

Add readonly test for setmem

---

libvirt/tests/src/virsh_cmd/network/virsh_net_edit.py

net_edit: make sure the network is active before net-dumpxml to get the
live xml.

Make sure the network is active before live dump

---

libvirt/tests/src/virsh_cmd/domain/virsh_blockcommit.py

If with shadow option,add additional check after blockcommit

add block job checking after executing blockcommit

---

libvirt/tests/src/libvirt_mem.py

Fix total memory not changed after memory dev hot plug

---

libvirt/tests/cfg/libvirt_mem.cfg
libvirt/tests/src/libvirt_mem.py

Change get_totalmem_sys function to get memory both online and offline

---

libvirt/tests/src/migration/migrate_options_shared.py

Remove duplicated code for postcopy_options

---

libvirt/tests/cfg/virsh_cmd/domain/virsh_domjobinfo.cfg
libvirt/tests/src/virsh_cmd/domain/virsh_domjobinfo.py

Add save, managedsave, crash dump operations in domjobinfo test.

Add save/managedsave/crash_dump domjobinfo test

---

libvirt/tests/src/cpu/guestpin.py

Add debug logging for cpustats value

Add debug logging for cpustats value

---

libvirt/tests/src/libvirt_mem.py

Added create_mem_xml to utils_hotplug so that it can be used by
others too. Hence changing the libvirt_mem to use generic function.

Used generic functions from utils_hotplug

---

v2v/tests/cfg/function_test_esx.cfg
v2v/tests/src/convert_from_file.py
v2v/tests/src/convert_vm_to_ovirt.py
v2v/tests/src/function_test_esx.py

1) Fix vm is not cleaned up if start failed
2) Update windows version list
3) Update converted OS for multi system

Fix cleanup vm problem and update converted OS

---

libvirt/tests/src/libvirt_rng.py

On rhel8, the default guest xml generated by virt-install has rng
dev, which not exist on rhel7. Remove this extra rng dev before
testing. And open debug=True for each virsh command to log more
details in jobs.

libvirt_rng.py: Remove extra rng dev bef test

---

libvirt/tests/src/virsh_cmd/domain/virsh_blkiotune.py

Update: The cfq scheduler is removed from 4.18 kernel

---

libvirt/tests/cfg/virsh_cmd/domain/virsh_domtime.cfg
libvirt/tests/src/virsh_cmd/domain/virsh_domtime.py

virsh_domtime: Add cases for 'readonly' test

---

libvirt/tests/src/virsh_cmd/domain/virsh_attach_detach_disk.py

Shareable options is introduced afterwards libvirt 3.9.0.
So if libvirt version below 3.9.0, should cancel related test cases
otherwise it would get failure like
"vm start failed. lockIs another process using the image"

attach_detach_disk: Update judgement for shareable test

---

libvirt/tests/cfg/virsh_cmd/host/virsh_node_memtune.cfg
libvirt/tests/src/virsh_cmd/host/virsh_node_memtune.py

1) Add cases for options combination test
2) Add case for virsh manual check

virsh_node_memtune: Add cases for options combination test

---

libvirt/tests/cfg/virsh_cmd/domain/virsh_domcontrol.cfg
libvirt/tests/src/virsh_cmd/domain/virsh_domcontrol.py

virsh_domcontrol: Add 'uri' test

---

libvirt/tests/cfg/virtual_network/iface_bridge.cfg
libvirt/tests/src/virtual_network/iface_bridge.py

Create a new bridge with a physical nic,
and connect it to multiple vms, test if
the vms, host, and remote ip can ping
each other succeed

Add test for shared physical network

---

libvirt/tests/cfg/virsh_cmd/domain/virsh_migrate.cfg
libvirt/tests/src/virsh_cmd/domain/virsh_migrate.py

This PR depends on avocado-vt #1661

virsh_migrate: Add 'readonly' test

---

libvirt/tests/src/virsh_cmd/domain/virsh_domuuid.py

domain uuid should comply with RFC4122 format

add domain uuid check whether it comply with RFC4122

---

libvirt/tests/src/numa/numa_memory.py

Minorfix: Fixup the div in Python3

---

libvirt/tests/cfg/virsh_cmd/pool/virsh_find_storage_pool_sources.cfg
libvirt/tests/src/virsh_cmd/pool/virsh_find_storage_pool_sources.py

find_storage_pool_sources: Add cases for local host and no srcSpec test

---

libvirt/tests/cfg/virsh_cmd/host/virsh_nodecpumap.cfg
libvirt/tests/src/virsh_cmd/host/virsh_nodecpumap.py

virsh_nodecpumap: Add test for cpu turn off and on

---

libvirt/tests/cfg/virsh_cmd/domain/virsh_cpu_compare_xml.cfg
libvirt/tests/src/virsh_cmd/domain/virsh_cpu_compare_xml.py

Support cpu_compare with domxml, domcapa_xml and capa_xml

---

libvirt/tests/cfg/virsh_cmd/monitor/virsh_perf.cfg
libvirt/tests/src/virsh_cmd/monitor/virsh_perf.py

Add perf test case with values of events set to no

---

libvirt/tests/src/migration/migrate_vm.py

It's meaningless to create or destroy target storage pool when
target_pool_name is None, and it will fail if target libvirtd is
stopped in some negative test cases

Only create or destroy target pool when target_pool_name is not None

---

libvirt/tests/cfg/bios/boot_integration.cfg
libvirt/tests/src/bios/boot_integration.py

Boot Uefi/Seabios guest, and test
vm undefine/define/start/destroy/save/restore
operations

Add bios boot integration cases

---

libvirt/tests/cfg/virsh_cmd/pool/virsh_pool_auth.cfg
libvirt/tests/src/virsh_cmd/pool/virsh_pool_auth.py

Since 3.9.0, auth info can be in place of source part

Add pool test with authentication

---

libvirt/tests/src/virsh_cmd/host/virsh_hostname.py

The old script use vm session for remote test, but it's not
applicable when testing on remote server. So change to
remote.wait_for_login to compat all cases

virsh_remote: Use server session instead of vm session

---

libvirt/tests/src/serial/serial_functional.py

Minorfix: Try to catch the BrokenPipeError

---

libvirt/tests/src/virtual_network/iface_network.py

The brctl-utils package is deprecated on rhel8. Replace the "brctl"
command with ip command which is effective on both rhel7 and rhel8.

Replace the brctl command

---

libvirt/tests/src/migration/migrate_vm.py

This is to add more debug information for trouble shooting.

migrate_vm: Add dumpxml for remote guest

---

libvirt/tests/src/virsh_cmd/domain/virsh_blkiotune.py

add debug information in blkiotune for troubleshooting

---

libvirt/tests/src/virsh_cmd/domain/virsh_hypervisor_cpu_compare.py

Minorfix: Fixup the spelling mistake

---

libvirt/tests/src/virsh_cmd/network/virsh_net_update.py

As new release use nftables as backend of firewalld, the guest can not get
dhcp ip address from nat network. Current workaround is to add the
bridge interface into the libvirt zone.

Fix the no ip issue on new libvirt version

---

libvirt/tests/cfg/virsh_cmd/domain/virsh_migrate_copy_storage.cfg
libvirt/tests/src/virsh_cmd/domain/virsh_migrate_copy_storage.py

Reverts autotest/tp-libvirt#1801
Above PR need to add TLS setup. So I revert it now.

Revert "virsh_migrate_copy_storage: Add tls option tests"

---

libvirt/tests/src/virsh_cmd/network/virsh_net_edit.py

For negative test, do not need to check the network status after the
test. And as uuid is an attribute, the cmd should be different.

Fix the net_edit script issue

---

libvirt/tests/src/virtual_network/iface_coalesce.py

Replace the brctl command with nmcli command.

Replace the "brctl" command

---

libvirt/tests/src/virsh_cmd/domain/virsh_vcpupin.py

Minorfix: Fixup the strip mistake

---

libvirt/tests/src/svirt/svirt_start_destroy.py

Fix the issue caused by selinux label defined checking which added rhel8

---

libvirt/tests/src/virsh_cmd/domain/virsh_domfstrim.py
libvirt/tests/src/virsh_cmd/domain/virsh_sendkey.py

Add or increase the wait seconds to make the cases more stable on
certain arches.

Minor fixes for command effect delay

---

libvirt/tests/src/virsh_cmd/domain/virsh_managedsave.py

Make sure 'lsof' is installed

---

libvirt/tests/src/svirt/svirt_start_destroy.py

Try to delete the label and ignore the error

---

libvirt/tests/src/migration/migrate_vm.py

This is to fix an incorrect modification for remote guest xml.

migrate_vm: fix remote guest cache issue

---

libvirt/tests/src/virsh_cmd/domain/virsh_save.py

Set debug=True to make debug easier

---

libvirt/tests/src/virsh_cmd/domain/virsh_attach_detach_interface.py

Wait 5 seconds to fully detach interface

---

libvirt/tests/src/virsh_cmd/domain/virsh_migrate.py

Improve logging in virsh_migrate.py

---

libvirt/tests/src/virsh_cmd/domain/virsh_reboot.py

Add domstate to check guest status after rebooting

Add domstate to check guest status after rebooting

---

libvirt/tests/cfg/svirt/svirt_attach_disk.cfg
libvirt/tests/src/svirt/svirt_attach_disk.py

Add testcase for disk device seclabel:
1.For file type disk;
2.For block type disk;

Add testcase for disk device seclabel.

---

libvirt/tests/src/virtual_disks/virtual_disks_multivms.py

Set debug=True when attatch devices

---

libvirt/tests/cfg/virtual_network/mtu.cfg
libvirt/tests/src/virtual_network/mtu.py

- Set mtu in network/interface
- Set mtu in different type of network, macvtap, bridge, etc
check mtu value in vm and qemu command line

Add mtu cases

---

libvirt/tests/cfg/libvirt_mem.cfg
libvirt/tests/src/libvirt_mem.py

- cold-plug memory device
- hot-plug memory device

Add memory cases: memory should align with 256

---

libvirt/tests/cfg/conf_file/qemu_conf/set_virtlogd.cfg
libvirt/tests/src/conf_file/qemu_conf/set_virtlogd.py

Add test for:
1. Check virtlogd after reloading virtlogd.
2. Check virtlogd after restarting libvirtd.

Add check for virtlogd

---

libvirt/tests/cfg/virsh_cmd/domain/virsh_managedsave_extra.cfg
libvirt/tests/src/virsh_cmd/domain/virsh_managedsave_extra.py

- managedsave-dumpxml
- managedsave-define
- managedsave-edit
based on https://github.com/avocado-framework/avocado-vt/pull/1732

Add cases of virsh managedsave

---

libvirt/tests/src/virsh_cmd/network/virsh_net_update.py

To avoid influence on future tests.
Depend on: https://github.com/avocado-framework/avocado-vt/pull/1744

Backup and restore accept_ra file in test

---

libvirt/tests/src/virtual_network/iface_coalesce.py

iface_coalesce.py: the name of the connections on the system varies on
different system. The robust way is to get the connection name by the
outputs in the dev information.

Fix script issue in iface_coalesce.py

---

libvirt/tests/src/virsh_cmd/domain/virsh_blockresize.py

Minorfix: Fixup the division gap with python2&3

---

libvirt/tests/src/virsh_cmd/domain/virsh_dump.py

Install lsof pkg if not installed

---

libvirt/tests/src/virsh_cmd/domain/virsh_event.py

Shutdown reason was distinguished from qemu 2.9.0-9 in bug1418927.
Add judgement to adapt testing with new libvirt and old qemu.

virsh_event.py: distinguish shutdown reason

---

libvirt/tests/cfg/cpu/ppc_cpu_mode.cfg
libvirt/tests/src/cpu/ppc_cpu_mode.py

Guest can start with different cpu mode setting and do managedsave

Add ppc cases of cpu mode

---

libvirt/tests/cfg/sriov/sriov.cfg
libvirt/tests/src/sriov/sriov.py

Add test for vf bond to numa node:
1.Add one vf bond to numa node;
2.Add two vfs both bond to numa node;

Add test for vf bond to numa node

---

libvirt/tests/src/serial/serial_functional.py

Fix vm start failure in virtio test and tcp server char translation issue

---

libvirt/tests/src/numa/guest_numa.py

Enable code to run the tests on PPC with the same config. The
numa numbers in the config will act as the index value for the
numa list for PPC. Modified required qemu commands als to validate
the same.

Fixed numa numbering issue for PPC

---

libvirt/tests/cfg/bios/virsh_boot.cfg

Distinguish with machine type for boot tests

---

libvirt/tests/src/conf_file/qemu_conf/auto_dump.py

Minorfix: Fixup the pep8 error

---

v2v/tests/cfg/function_test_esx.cfg

v2v_case13000_lvm_multiple_disks

---

v2v/tests/cfg/function_test_xen.cfg
v2v/tests/cfg/v2v_options.cfg

Update error message for --in-place

---

libvirt/tests/cfg/papr_hpt.cfg
libvirt/tests/src/papr_hpt.py

- set hpt resizing to 'disabled'
- set hpt resizing to 'enabled' and do memory hotplug
- set hpt resizinzg on non-ppc hosts

Add new cases of papr hpt

---

libvirt/tests/cfg/memory/nvdimm.cfg
libvirt/tests/src/memory/nvdimm.py

- Boot a VM with NVDIMM backed by a file in host
- Boot a VM with NVDIMM label backed by a file in host
- hot-plug/hot-unplug nvdimm device to VM

Add nvdimm cases

---

libvirt/tests/src/numa/numa_memory.py

Enable code to run the tests on PPC with the same config. The
numa numbers in the config will act as the index value for the
numa list for PPC.

Enable numa_memory on ppc.

---

libvirt/tests/cfg/bios/virsh_boot.cfg

virsh_boot.cfg: Update pattern of error message

virsh_boot.cfg: Update pattern of error message

---

libvirt/tests/src/migration/migrate_vm.py

Add port by firewall-cmd before do migration

---

libvirt/tests/src/virtual_disks/virtual_disks_multipath.py

When prepare multipath.conf, the original code will create the conf
if it doesn't exist. But the conf file just left there, and this
will effect some other cases. So change the code to remove the
multipath.conf file, if it doesn't existing at beginning.

Make sure multipath.conf removed if not exsiting at first

---

libvirt/tests/cfg/daemon/kill_started.cfg
libvirt/tests/src/daemon/kill_started.py

Add a new case for sigsegv

---

libvirt/tests/cfg/virtual_device/vsock.cfg
libvirt/tests/src/virtual_device/vsock.py

Add testcases for vsock device:
1.Edit/start guest with vsock device.
2.Hotplug/hotunplug vsock device.
3.Coldplug/Coldunplug vsock device

Add testcases for vsock device

---

libvirt/tests/src/cpu/ppccpucompat.py

gcc is necessary since command 'cc' is used in the checking command.
Print out some debug info about vm xml, and command output for
future debugging.

Install gcc before check isa feature

---

libvirt/tests/src/virsh_cmd/volume/virsh_vol_create.py

Should use secret driver in ACL for the encrypted volume creation

Should use secret driver in ACL for the encrypted volume creation

---

v2v/tests/cfg/v2v_options.cfg

Use guests in esx server instead of local guests

---

v2v/tests/cfg/v2v_options.cfg
v2v/tests/src/v2v_options.py

add_more_support_for_print_source

---

v2v/tests/cfg/function_test_esx.cfg

Update guest for case fstab_comma of v2v

---

libvirt/tests/src/conf_file/sysconfig_libvirt_guests/libvirt_guests.py

There are two fix in this commit
1) The first one is add the checkpoint of fresh boot by using the
command "uptime"
2) fix the minor log changes of libvirt-guests for the negative
case.

Add the checkpoint of fresh boot

---

v2v/tests/cfg/function_test_esx.cfg

Add case for win7 guest with AntiVirus installed

---

libvirt/tests/cfg/virtual_disks/virtual_disks_multidisks.cfg

remove pci-bridge case for q35 test

---

libvirt/tests/cfg/bios/virsh_boot.cfg

virsh_boot.cfg: Add new checkpoint for error message

virsh_boot.cfg: Add new checkpoint for error message

---

libvirt/tests/src/virsh_cmd/domain/virsh_domcontrol.py

Need to start remote domain for virsh domcontrol remote case.

Add check remote domain status for virsh_domcontrol

---

libvirt/tests/src/npiv/npiv_snapshot.py

The original code has problem on rhel8, replace it by a existing
method.

Use existing code to get disk names in NPIV case

---

libvirt/tests/src/virtual_network/iface_network.py

iface_network.py: in the former version, it will check the ipv4 rules
for 2 times. Edit the function to check ipv4 and ipv6 each and update
some rules.

Fix the func to check the ip6tables rules

---

libvirt/tests/src/virsh_cmd/network/virsh_net_update.py

Fix local variable 'backup_files' referenced before assignment issue.
When there is no enough physical interface on the host, test will be
canceled, but untill then the backup_files is not defined. Another
update is delete the workaround for network issue as the bug is already
fixed.

Fix local variable 'backup_files' issue

---

libvirt/tests/cfg/bios/virsh_boot.cfg
libvirt/tests/cfg/migration/migrate_vm.cfg
libvirt/tests/cfg/svirt/dac_vm_per_image_start.cfg
libvirt/tests/cfg/virsh_cmd/domain/virsh_blockcommit.cfg
libvirt/tests/cfg/virsh_cmd/domain/virsh_blockpull.cfg
libvirt/tests/cfg/virsh_cmd/pool/virsh_pool_autostart.cfg
libvirt/tests/cfg/virsh_cmd/pool/virsh_pool_create.cfg
libvirt/tests/cfg/virsh_cmd/snapshot/virsh_snapshot_create_as.cfg
libvirt/tests/cfg/virsh_cmd/snapshot/virsh_snapshot_disk.cfg
libvirt/tests/cfg/virsh_cmd/volume/virsh_volume.cfg
libvirt/tests/cfg/virtual_disks/virtual_disks_gluster.cfg
libvirt/tests/cfg/virtual_disks/virtual_disks_luks.cfg

It will be used in different cases running at the same time

gluster: Change the gluster vol name

---

libvirt/tests/cfg/controller/pcibridge.cfg
libvirt/tests/src/controller/pcibridge.py

- hotplug/unplug interface to pcie-to-pci-bridge with/without
another device on bridge
- hotplug/unplug interface to pci-bridge with/without another
device on bridge

Add pci/pcie-to-pci bridge cases

---

libvirt/tests/cfg/ppc_device.cfg
libvirt/tests/src/ppc_device.py

- Assign address to panic device
- Passthrough non-available PCI device in guest

Add ppc-only cases

---

v2v/tests/cfg/function_test_xen.cfg

Add new case for polarion id 13043

Add new case for converting a guest installed on block disk

---

libvirt/tests/cfg/bios/virsh_boot_tseg.cfg

Divide cases according to machine type

---

libvirt/tests/src/numa/guest_numa.py

Minorfix: Fixup the nodes are 0 and 1 on ppc

---

libvirt/tests/src/libvirt_mem.py

Minorfix: Fixup the unsupported error

---

provider/v2v_vmcheck_helper.py
v2v/tests/cfg/specific_kvm.cfg
v2v/tests/src/specific_kvm.py

Add support for converting vm from xen and esx to rhv

Support convert vm from xen and esx

---

libvirt/tests/cfg/virsh_cmd/domain/virsh_event.cfg
libvirt/tests/src/virsh_cmd/domain/virsh_event.py

Add 'crash panic' lifecycle event.

virsh_event.py: Add crash panic event

---

v2v/tests/cfg/specific_kvm.cfg
v2v/tests/src/specific_kvm.py

1) Fix cannot copy image file problem
2) Fix wrong version replace problem
3) Fix wrong xen password problem

Fix some problems when converting guest from KVM

---

v2v/tests/cfg/specific_kvm.cfg
v2v/tests/src/specific_kvm.py

1) Support multi_kernel case in esx
2) Support sr0 case in esx

Migrate two cases from kvm to esx

---

v2v/tests/cfg/specific_kvm.cfg

Update multi disks case for windows guest

---

libvirt/tests/cfg/graphics/graphics_functional.cfg
libvirt/tests/src/graphics/graphics_functional.py

Add remote-viewer to check graphic password

---

libvirt/tests/cfg/migration/migrate_options_shared.cfg
libvirt/tests/src/migration/migrate_options_shared.py

During migration, validate migration set/get speed takes effect

migrate_options_shared: Add migrate speed cases

---

libvirt/tests/cfg/graphics/graphics_functional.cfg
libvirt/tests/src/graphics/graphics_functional.py

Add test for password valid time

---

libvirt/tests/src/graphics/graphics_functional.py

graphics_functional: Fix a import issue

---

libvirt/tests/src/virsh_cmd/host/virsh_freepages.py

Minorfix: Fixup some logical error

---

libvirt/tests/cfg/cpu/setvcpu.cfg
libvirt/tests/src/cpu/setvcpu.py

check the vcpu order when hot plug/unplug specific vcpu

add subcase to test case setvcpu

---

libvirt/tests/src/virsh_cmd/host/virsh_freepages.py

Minorfix: The function name has been changed

---

libvirt/tests/cfg/cpu/vcpu_affinity.cfg
libvirt/tests/src/cpu/vcpu_affinity.py

set vcpu affinity for none exists vcpu and check xml result

add subcase to test case vcpu_affinity

---

libvirt/tests/cfg/migration/migrate_options_shared.cfg
libvirt/tests/src/migration/migrate_options_shared.py

This is to test migrate-setmaxdowntime and migrate-getmaxdowntime during
migration.

migrate_options_shared:Test migrate setmaxdowntime
