- v2v/tests/cfg/function_test_esx.cfg
Check bz #1945549 and case RHEL-254337
> v2v: add case on deleting warning info on rhev-apt

- libvirt/tests/cfg/migration/live_migration.cfg
> live_migration:fix err pattern

- libvirt/tests/src/migration/migrate_vm.py
The value of 'remote_target_hugepages' need less than vm mermory.
If this value is too large, migration will successful.
> migrate_vm: Update hugepage number

- libvirt/tests/cfg/virsh_cmd/domain/virsh_domiftune.cfg
- libvirt/tests/src/virsh_cmd/domain/virsh_domiftune.py
Add 4 cases in domiftune to complete automation of RHEL7-45987.
> domiftune: add 4 cases

- libvirt/tests/src/cpu/diagnose_spinlock_yield_forward.py
The attribute name has changed for newer kernel versions.
Use whichever path exists in the kernel under test.
> diagnose_spinlock_yield_forward: support newer kernel versions

- libvirt/tests/cfg/cpu/vcpu_hotpluggable.cfg
- libvirt/tests/src/cpu/vcpu_hotpluggable.py
Case ID: RHEL-112474
Test scenario:
- Cold plug/unplug vcpu with shutoff vm, check xml, restart libvirt, check domain
> vcpu_hotpluggable:add case for cold plug unplug

- libvirt/tests/src/cpu/vcpu_hotpluggable.py
> vcpu_hotpluggable: Fix travis error

- libvirt/tests/cfg/virtual_disks/virtual_disks_snapshot_blockpull.cfg
- libvirt/tests/src/virtual_disks/virtual_disks_snapshot_blockpull.py
Those cases cover ranges of scenarios including options:time, sync
,bandwidth, and various --base source
> Add blockpull with snapshots cases

- v2v/tests/cfg/function_test_esx.cfg
Please check TC: RHEL-242816 and bz #1949147
> v2v:add case on improving the minimum free space for windows guest

- libvirt/tests/cfg/memory/memory_misc.cfg
- libvirt/tests/src/memory/memory_misc.py
- RHEL-144054: verify <access mode='shared'/> is ignored if
no NUMA nodes are configured
- RHEL7-93327: Allow use mlock without hard limit
- RHEL7-18969: [Memory management] forbid to set memory to ZERO
- RHEL-171129: verify dommemstat show right disk cache for
RHEL8 guest
- RHEL7-62155: [Memory management] Edit guest XML with smbios
/sysinfo /idmap /metadata and memory device - 1223631
> Add memory cases

- v2v/tests/cfg/specific_kvm.cfg
> v2v:add case 'Print best kernel in debug'

- libvirt/tests/cfg/lease_device.cfg
- libvirt/tests/src/lease_device.py
- RHEL-242770: Live attach/detach domain lease
- RHEL-242818: Cold attach/detach/start with domain lease
> Add new cases of attaching lease

- libvirt/tests/src/sriov/sriov_net_failover.py
- provider/sriov/sriov_base.py
This function will be used by other sriov cases, so move it to
provider, and update to get an IP address from routing table to
make it more stable.
> SRIOV: Refactor get_ping_dest

- v2v/tests/cfg/function_test_esx.cfg
> v2v: add version control to case win_bitlocker

- libvirt/tests/cfg/libvirt_rng.cfg
- libvirt/tests/src/libvirt_rng.py
aarch64 guest with EGD rng device got stuck during boot.
https://bugzilla.redhat.com/show_bug.cgi?id=1983544
Feed the rng device to fix the error.
> Fix aarch64 guest with EGD rng device got stuck during boot

- libvirt/tests/src/sriov/sriov.py
> Fix the address issue

- v2v/tests/cfg/v2v_options.cfg
- v2v/tests/src/v2v_options.py
Please check TC #RHEL-150296 and bz #1644275 #1850423
Signed-off-by:vwu
> v2v: add case 'virt-v2v depends on platform-python'

- libvirt/tests/src/virsh_cmd/domain/virsh_detach_device_alias.py
The cmd "detach-device-alias" will return "Device detach request sent successfully" immediately,
which may cause that the related device info will not take effect in the dumpxml/guest os that fast.
Simply waiting for few seconds can not make the script stable on different test environments. This
is to enhance it.
> virsh_detach_device_alias: fix detach slow issue

- libvirt/tests/src/virsh_cmd/domain/virsh_define.py
Some tests need to set invalid attribute "foot" to video. If guest xml
doesn't have video device test will hit AttributeError.
Check guest xml and add video device if needed.
Before
```
[root@hpe-apollo80-01-n00 ~]# avocado run --vt-type libvirt --vt-arch aarch64 --vt-machine-type arm64-mmio virsh.define.positive_test.option_none
JOB ID     : fbb474ebdee15aad7394be87055d85ca354a3223
JOB LOG    : /root/avocado/job-results/job-2021-08-20T03.02-fbb474e/job.log
(1/1) type_specific.io-github-autotest-libvirt.virsh.define.positive_test.option_none: ERROR: 'NoneType' object has no attribute 'set' (7.39 s)
JOB TIME   : 8.15 s
```
After
```
[root@hpe-apollo80-01-n00 …
```
> virsh_define: Fix AttributeError

- libvirt/tests/cfg/memory/memory_misc.cfg
- libvirt/tests/src/memory/memory_misc.py
- RHEL7-93110 - Multi-operation for dimm devices
> Add memory case

- v2v/tests/cfg/specific_kvm.cfg
- v2v/tests/src/specific_kvm.py
Delete the parts on the duplicate case#13011  on no_space of host.
More info on the case, refer #RHEL-242816
> v2v: delete the duplicate case on no_space of host

- libvirt/tests/cfg/virtual_device/filesystem_device.cfg
- libvirt/tests/src/virtual_device/filesystem_device.py
> Add test for externally launched virtiofsd

- libvirt/tests/src/virtual_device/video_devices.py
In RHEL8.5, the following tests were failing:
virtual_devices.video_devices.negative_test.qxl.mem_test.ram.empty_value
virtual_devices.video_devices.negative_test.qxl.mem_test.vram.empty_value
virtual_devices.video_devices.negative_test.qxl.mem_test.vgamem.empty_value
since the empty values were "defined" in the XML, but they must be edited
by virsh command. This fix adds virsh edit function for updating
parameters and testing it's output to decide if the test passes or fails.
Before applying fix:
<pre>avocado run --vt-type libvirt --vt-machine-type q35 virtual_devices.video_devices.negative_test.qxl.mem_test.ram.empty_value
WARNING:root:No python imaging library installed. Screendump and Windows guest BSOD detection are …
> misc_virtual_devices:Fix for the qxl video devices with empty values

- v2v/tests/cfg/function_test_esx.cfg
Please check TC #RHEL-254348 and bz #1972708 #1764569
> v2v: add case ‘Check minimum space and inodes for linux guest’

- v2v/tests/src/specific_kvm.py
Check bz# 1316479 and case #RHEL7-12948
> v2v: change the tmp dir to  for host_no_space case

- libvirt/tests/cfg/virsh_cmd/domain/virsh_domblkthreshold.cfg
- libvirt/tests/src/virsh_cmd/domain/virsh_domblkthreshold.py
Add test case to cover set block threshold [1] with with dev or dev[index]
[1]:https://bugzilla.redhat.com/show_bug.cgi?id=1983429
RHEL-276864
> Add test case to cover set block threshold  with with dev

- libvirt/tests/cfg/migration/live_migration.cfg
- libvirt/tests/src/migration/live_migration.py
- provider/migration/migration_base.py
RHEL-265508 - [Migration] Poweroff inside vm on source host during
Perform Phase of live migration - p2p migration
> live_migration: Add new case about poweroff guest

- libvirt/tests/cfg/libvirtd/libvirtd.cfg
- libvirt/tests/src/libvirtd/libvirtd.py
RHEL7-103703: [libvirtd] Restart libvirtd with running guests
-- bug 1422318
> libvirtd: Add new case for restart libvirtd with running guest

- libvirt/tests/cfg/migration/live_migration.cfg
- provider/migration/migration_base.py
RHEL-120213 - [Migration] Suspend virsh during live migration (p2p
migration)
> live_migration: Add new case about suspend virsh client

- libvirt/tests/cfg/virsh_cmd/domain/virsh_cpu_xml.cfg
- libvirt/tests/cfg/virsh_cmd/domain/virsh_hypervisor_cpu_baseline.cfg
- libvirt/tests/src/virsh_cmd/domain/virsh_cpu_xml.py
- libvirt/tests/src/virsh_cmd/domain/virsh_hypervisor_cpu_baseline.py
> virsh_cpu_xml: fix xml missing

- libvirt/tests/cfg/memory/memballoon.cfg
- libvirt/tests/src/memory/memballoon.py
- RHEL7-16778: [Memory management] Present memballoon statistic
period in live xml
> Add memballoon case

- libvirt/tests/src/timer_management.py
> timer_management: Update old usage of VMCLOCKXML

- libvirt/tests/cfg/virtual_network/network_misc.cfg
- libvirt/tests/src/virtual_network/network_misc.py
- RHEL-279587 - [acpi] Set ACPI index for interfaces
- RHEL-281192 - [acpi] Set ACPI index for interfaces:boundary/negative
values
> Add interface cases with acpi

- libvirt/tests/cfg/sriov/sriov_scalability.cfg
- libvirt/tests/src/sriov/sriov_scalability.py
RHEL7-18503 - Hotplug MAX VFs to guest
` (1/1) type_specific.io-github-autotest-libvirt.sriov.scalability.max_vfs: PASS (334.02 s)`
> sriov: Add a case to test max vfs

- libvirt/tests/cfg/virsh_cmd/domain/virsh_domdirtyrate_calc.cfg
- libvirt/tests/src/virsh_cmd/domain/virsh_domdirtyrate_calc.py
- spell.ignore
Case ID: https://polarion.engineering.redhat.com/polarion/#/project/RedHatEnterpriseLinux7/workitem?id=RHEL-279149
Depends on: https://github.com/avocado-framework/avocado-vt/pull/3180
> virsh_domdirtyrate_calc: Add cases of virsh domdirtyrate-calc

- libvirt/tests/src/numa/numa_memory_spread.py
Even if virsh setmem return successfully, guest still need some time to
increase memory.
Before
```
JOB ID     : 83f557a3a0c59aa150f3c6c459f9007d94c60ca4
JOB LOG    : /root/avocado/job-results/job-2021-10-20T05.40-83f557a/job.log
(1/1) type_specific.io-github-autotest-libvirt.numa_memory_spread.default: ERROR: Shell command failed: 'memhog -r1 8649555k'    (status: 1,    output: 'numactl: mmap: Cannot allocate memory\n') (73.80 s)
JOB TIME   : 74.51 s
```
After
```
JOB ID     : e3748056f67e42b33a69e0a363c7aedbf50783ba
JOB LOG    : /root/avocado/job-results/job-2021-10-20T05.44-e374805/job.log
(1/1) type_specific.io-github-autotest-libvirt.numa_memory_spread.d …
```
> numa_memory_spread: Fix numactl: mmap: Cannot allocate memory

- libvirt/tests/src/cpu/vcpu_hotpluggable.py
The previous codes only work for monolithic libvirtd. So update to
use libvirt.customize_libvirt_config() that works for both modular
daemons and monolithic libvirtd.
Before fix:
` (1/1) type_specific.io-github-autotest-libvirt.vcpu_hotpluggable.positive_test.vcpus_with_order: ERROR: Command 'cat /tmp/avocado_fr6s9b2l/libvirtd.log| grep device_add| grep qemuMonitorIOWrite| grep 'vcpu1'' failed.\nstdout: b''\nstderr: b''\nadditional_info: None (324.45 s)`
After the fix:
` (1/1) type_specific.io-github-autotest-libvirt.vcpu_hotpluggable.positive_test.vcpus_with_order: PASS (30.47 s)`
> vcpu_hotpluggable: Update the configure setting

- libvirt/tests/cfg/bios/virsh_boot.cfg
- libvirt/tests/cfg/migration/migrate_storage.cfg
- libvirt/tests/cfg/migration/sriov_migrate.cfg
- libvirt/tests/cfg/sriov/sriov_net_failover.cfg
- libvirt/tests/cfg/virsh_cmd/domain/virsh_domblkthreshold.cfg
- libvirt/tests/cfg/virsh_cmd/volume/virsh_vol_clone_wipe.cfg
- libvirt/tests/cfg/virsh_cmd/volume/virsh_vol_create.cfg
- libvirt/tests/cfg/virsh_cmd/volume/virsh_vol_download_upload.cfg
- libvirt/tests/cfg/virsh_cmd/volume/virsh_vol_resize.cfg
- libvirt/tests/cfg/virtual_disks/virtual_disks_transient_disk.cfg
- libvirt/tests/cfg/virtual_network/iface_target.cfg
depends on: https://github.com/avocado-framework/avocado-vt/pull/3264
> Fix up a typo - unspported_err_msg

- provider/v2v_vmcheck_helper.py
Fix the failed TCs with error 'Not find cirrus device'.
> v2v: fix the failed cases with error 'Not find cirrus device'

- libvirt/tests/src/virsh_cmd/snapshot/virsh_snapshot_create_as.py
- libvirt/tests/src/virsh_cmd/snapshot/virsh_snapshot_dumpxml.py
- libvirt/tests/src/virsh_cmd/snapshot/virsh_snapshot_edit.py
- libvirt/tests/src/virsh_cmd/snapshot/virsh_snapshot_par_cur.py
> snapshot: set timeout for snapshot_create_as

- provider/v2v_vmcheck_helper.py
Reverts autotest/tp-libvirt#3860
> Revert "v2v: fix the failed cases with error 'Not find cirrus device'"

- v2v/tests/cfg/function_test_esx.cfg
See RHEL-241704 and bz1895323.
> v2v: add a new case for datetime format settings in windows

- v2v/tests/cfg/function_test_esx.cfg
- v2v/tests/src/function_test_esx.py
This reverts commit 11e1f0d7037af8a55179d0d1328afe19db0e2e14.
Above commit makes other scripts fail. so revert it.
> Revert ""v2v: modify dir location for -o json""

- libvirt/tests/src/virsh_cmd/domain/virsh_change_media_matrix.py
Regarding hotplug device changes, it need ensure VM is completedly booted
> Fix change media matrix event not received issue

- libvirt/tests/src/virsh_cmd/pool/virsh_pool.py
Update to restart virtstoraged service to fix refresh pool failure
> virsh_pool.py: update to restart virtstoraged service

- libvirt/tests/src/migration/migrate_with_various_hostname.py
> Adjust the order to set hostname

- libvirt/tests/src/virsh_cmd/domain/virsh_blockcommit.py
Sometimes the previous case not clean  env completely:
If left snap file , we will get error  "Failed to make snapshots for disks!"  when create snap ,so we need to rm snap file .
If domain xml is not images/*.qcow2 ,we will raise one test.error("Please check current vm disk source ")
/usr/local/bin/avocado run --vt-type libvirt --vt-machine-type q35 virsh.blockcommit.normal_test.single_chain.file_disk.local.no_ga.notimeout.base_as_middle.top_inactive --vt-connect-uri qemu:///system
No python imaging library installed. PPM image conversion to JPEG disabled. In order to enable it, please install python-imaging …
> Clean snap file and raise unclean xml error

- libvirt/tests/cfg/virtual_disks/virtual_disks_ccw_addr.cfg
- libvirt/tests/src/virtual_disks/virtual_disks_ccw_addr.py
Cases come from Bugzilla: 1258361[1]
RHEL7-110399,RHEL7-110400, RHEL7-110401
[1]https://bugzilla.redhat.com/show_bug.cgi?id=1258361
> Add attaching ccw address devices testing cases

- libvirt/tests/src/virsh_cmd/domain/virsh_migrate_option_mix.py
Fix error:
UnboundLocalError: local variable 'vm_xml_backup' referenced before assignment
> migrate_option_mix: Fix variable 'vm_xml_backup' reference issue

- libvirt/tests/cfg/virsh_cmd/domain/virsh_cpu_xml.cfg
- libvirt/tests/cfg/virsh_cmd/domain/virsh_hypervisor_cpu_baseline.cfg
- libvirt/tests/cfg/virtual_network/network_misc.cfg
> virsh_hypervisor_cpu_baseline: unsupport on ppc

- libvirt/tests/src/virsh_cmd/domain/virsh_domxml_to_native.py
> virsh_domxml_to_native: fix quote missing

- libvirt/tests/cfg/serial/serial_pty_log.cfg
- libvirt/tests/src/serial/serial_pty_log.py
This is to implement test case RHEL-281214
It's to test pty type serial device with log file working well
> Add test case for pty type serial device with log file

- libvirt/tests/cfg/virsh_cmd/domain/virsh_emulatorpin_mix.cfg
- libvirt/tests/src/virsh_cmd/domain/virsh_emulatorpin_mix.py
> virsh_emulatorpin_mix: fix vcpu max num on ppc

- libvirt/tests/src/libvirt_hooks.py
> Add restarting virtnetworkd for network hooks test

- libvirt/tests/src/virsh_cmd/domain/virsh_change_media_matrix.py
Suggested by 
https://github.com/autotest/tp-libvirt/pull/3922#issuecomment-993153985
> [minor fix] virsh_change_media_matrix: only running guest need to wait event

- libvirt/tests/src/virsh_cmd/pool/virsh_pool.py
* virsh_pool: update error msg for invalid pool info
##
avocado run --vt-type libvirt --vt-machine-type q35 virsh.pool.positive_test.pool_type_scsi --vt-connect-uri qemu:///system
JOB ID     : 41b9ed3f147c521b005326f6ddda057e92ad93f5
JOB LOG    : /root/avocado/job-results/job-2021-12-02T05.42-41b9ed3/job.log
(1/1) type_specific.io-github-autotest-libvirt.virsh.pool.positive_test.pool_type_scsi: **FAIL: The value Capacity you checked is not returned …
> update error msg for invalid pool info

- v2v/tests/cfg/convert_vm_to_libvirt.cfg
- v2v/tests/cfg/convert_vm_to_ovirt.cfg
Add windows version: win11 into auto testing.
> v2v: add win11 to matrix of auto testing

- provider/v2v_vmcheck_helper.py
> v2v: add win11/win2022 to vmcheck

- libvirt/tests/src/virtual_network/mtu.py
Update the match to adapt to the new qemu cmdline format.
> Update the qemu cmdline check

- libvirt/tests/cfg/virtual_disks/virtual_disks_ccw_addr.cfg
- libvirt/tests/src/virtual_disks/virtual_disks_ccw_addr.py
RHEL7-103759,two disks can share the same pci slot
> Add case to cover multifunction for disk regarding bug:1350391

- provider/v2v_vmcheck_helper.py
- v2v/tests/src/convert_from_file.py
- v2v/tests/src/convert_vm_to_libvirt.py
- v2v/tests/src/convert_vm_to_ovirt.py
- v2v/tests/src/function_test_esx.py
- v2v/tests/src/function_test_xen.py
- v2v/tests/src/nbdkit/nbdkit.py
- v2v/tests/src/pyvmomi/query_changed_disk_areas.py
- v2v/tests/src/specific_kvm.py
- v2v/tests/src/v2v_options.py
Refer to commit aa044c8633354ad7b5488d7377a584bc12193a57 to update
the v2v part in tp-libvirt.
This solves the issue that v2v's logs were not correctly printed.
> v2v: fix the v2v logging issue

- libvirt/tests/src/libvirt_rng.py
The used qemu interface for devices has changed from version 6.1 to 6.2.
Tests will failed with qemu 6.2 during qemu commandline check.
Update the test code to allow for both 6.1 and 6.2 API.
Use regular expressions inside the python code instead of grep
on shell in order to preserve the actual cmdline for debugging purposes.
This way if a check fails, the log will contain the actual cmdline that was
tested which currently isn't the case.
> libvirt_rng: relax qemu cmdline check

- libvirt/tests/cfg/migration/migrate_options_shared.cfg
Update config file for keepalive setting in modular daemons mode.
> migrate_options_shared: Update config file for keepalive setting

- v2v/tests/cfg/nbdkit/nbdkit.cfg
The package name should be nbdkit-server instead of nbdkit.
> nbdkit: update required nbdkit package name

- libvirt/tests/src/virtual_device/video_devices.py
log() will be used in this script, so rename it to avoid
AttributeError error.
> video_devices: Fix log reuse issue

- v2v/tests/cfg/function_test_esx.cfg
- v2v/tests/cfg/nbdkit/nbdkit.cfg
- v2v/tests/cfg/v2v_options.cfg
- v2v/tests/src/function_test_esx.py
- v2v/tests/src/nbdkit/nbdkit.py
- v2v/tests/src/v2v_options.py
> v2v: fix some spell errors

- v2v/tests/cfg/function_test_esx.cfg
- v2v/tests/cfg/v2v_options.cfg
- v2v/tests/src/specific_kvm.py
- v2v/tests/src/v2v_options.py
> v2v: fix several script issues for modular v2v in rhel9

- v2v/tests/cfg/function_test_esx.cfg
- v2v/tests/cfg/function_test_xen.cfg
- v2v/tests/cfg/v2v_options.cfg
> v2v: fix some script errors for modular v2v in rhel9

- v2v/tests/cfg/v2v_options.cfg
- v2v/tests/src/v2v_options.py
> v2v: add virt-v2v-copy-to-local test case in rhel8

- libvirt/tests/src/virsh_cmd/domain/virsh_attach_detach_disk.py
Add some target check before hot-unplug
> Fix Hot-unplug failed: guest is busy issue

- libvirt/tests/src/backingchain/virtual_disks_relative_blockcommit.py
Fix the permission denied in inappropriate path and the block disk issue in snapshot
> virtual_disks_relative_blockcommit.py: Fix block disk issue in snapshot

- v2v/tests/cfg/function_test_esx.cfg
See: RHEL-288472 and Bug 2032112
> v2v: add new checkpoint for v2v debug message

- v2v/tests/cfg/nbdkit/nbdkit.cfg
- v2v/tests/src/nbdkit/nbdkit.py
> nbdkit: add a new case for data corruption in bdkit-cow-filter

- libvirt/tests/src/migration/migrate_with_various_hostname.py
In some test environment, NetworkManager will update the hostname
with the one provided via DHCP or reverse DNS lookup of the IP
address on the connection with the default route. So disable
NetworkManager service in this case.
> migrate_with_various_hostname: Stop NetworkManager service

- libvirt/tests/src/migration/migrate_options_shared.py
UnboundLocalError: local variable 'runner_on_target' referenced
before assignment
> Fix 'runner_on_target' UnboundLocalError issue

- v2v/tests/cfg/function_test_esx.cfg
> v2v: add admin account case for vpx connection

- v2v/tests/cfg/convert_from_file.cfg
- v2v/tests/cfg/convert_vm_to_ovirt.cfg
- v2v/tests/cfg/function_test_esx.cfg
- v2v/tests/cfg/function_test_xen.cfg
- v2v/tests/cfg/specific_kvm.cfg
> v2v: add rhv_proxy option and update rhv-direct option

- v2v/tests/cfg/function_test_esx.cfg
> v2v: update case env_leak according the changes in libosinfo

- libvirt/tests/cfg/virtual_disks/virtual_disks_multidisks.cfg
- libvirt/tests/src/virtual_disks/virtual_disks_multidisks.py
Fix two issues:
1) Update seabios loader to the default one: bios-256k.bin
2) Update some qemu cmds checkpoint
> virtual_disks_multidisks.py: fix qemu cmd issue

- libvirt/tests/src/bios/virsh_boot.py
When qemu-img converts an image to a rbd:pool_name/image.raw, it will return
'operation not permitted' sometimes which is due to no keyring file is created.
Depends on https://github.com/avocado-framework/avocado-vt/pull/3308
> virsh_boot: add keyring file operation

- libvirt/tests/cfg/daemon/check_daemon_default_status.cfg
- libvirt/tests/src/daemon/check_daemon_default_status.py
> Add testcase to check the default enabled status of daemon

- libvirt/tests/cfg/virtual_network/iface_ovs.cfg
- libvirt/tests/src/virtual_network/iface_ovs.py
Test the inbound and outbound of bridge type interface with ovs bridge.
> Test Qos with ovs bridge

- libvirt/tests/src/libvirt_scsi_hostdev.py
Allow comformatable time to get lun information
> Fix scsi_hostdev failed to get lun information due to timeout

- libvirt/tests/cfg/virsh_cmd/host/virsh_nodeinfo.cfg
- libvirt/tests/src/virsh_cmd/host/virsh_nodeinfo.py
Case ID: RHEL7-17040 - [nodeinfo] - Get node basic information
Add a scenario to disable/enable a host cpu and check nodeinfo
> virsh_nodeinfo: add case disable cpu

- libvirt/tests/cfg/virtual_disks/virtual_disks_cdrom_device.cfg
- libvirt/tests/src/virtual_disks/virtual_disks_cdrom_device.py
Add define guest with scsi LUN device --BZ 1078126, 1201143 and
add https backend as cdrom in the guest
RHEL7-110402, RHEL7-91653, RHEL-118134, RHEL-113536
> Add define guest with scsi LUN device --BZ 1078126, 1201143 case

- libvirt/tests/cfg/daemon/kill_started.cfg
- libvirt/tests/src/daemon/kill_started.py
Fix error:
UnboundLocalError: local variable 'config' referenced before assignment
Signed-off-by: hpan <hpan@redhat.com>
> Fix variable referenced before assignment error

- v2v/tests/cfg/v2v_options.cfg
- v2v/tests/src/v2v_options.py
> v2v: add new case for --wrap option

- libvirt/tests/src/libvirt_hooks.py
This script removes all controllers during test.
If a guest has usb devices, this test will fail due to missing usb
contollers
Before
```
(1/1) type_specific.io-github-autotest-libvirt.libvirt_hooks.vm.network_t: ERROR: Failed to define avocado-vt-vm1 for reason:\nerror: Failed to define domain from /tmp/xml_utils_temp_oz3byw7i.xml\nerror: unsupported configuration: USB is disabled for this domain, but USB devices are present in the domain XML\n
```
After
```
(1/1) type_specific.io-github-autotest-libvirt.libvirt_hooks.vm.network_t: PASS (94.74 s)
```
> [minor fix] libvirt_hooks: Fix guest definition error

- libvirt/tests/src/virtual_device/watchdog.py
```
(1/1) type_specific.io-github-autotest-libvirt.watchdog.action_shutdown.model_i6300esb.hotunplug_test: PASS (29.55 s)
```
> Fix the detach xml can not find error for watchdog

- libvirt/tests/src/numa/numa_node_memory_bind.py
Original codes make test.cancel exposed as test.error finally which is unclear.
So this fix is to expose test.cancel again.
> numa_node_memory_bind: expose test.cancel

- libvirt/tests/src/sriov/sriov.py
If there is no iface_name got by utils_net.get_linux_ifname,
it'll raise TestError, which breaks the iface_name initialization.
The 'Exception' is too common, update to a proper one in try-except
block and correct logging.warning format.
`UnboundLocalError: local variable 'iface_name' referenced before assignment&#10;`
` (1/1) type_specific.io-github-autotest-libvirt.sriov.normal_test.guest_with_vf.hotplug.default.mac_check.vf.managed_no: PASS (66.24 s)`
> sriov: Fix an UnboundLocalError issue - iface_name

- libvirt/tests/src/virsh_cmd/domain/virsh_event.py
Set cpu mode to host-model to avoid bug 1925384.
> virsh_event: Update case for BZ#1925384

- libvirt/tests/cfg/migration/live_migration.cfg
- libvirt/tests/src/migration/live_migration.py
- provider/migration/migration_base.py
RHEL7-17314 - [Migration] Execute libvirt statistics command
during live migration - domblkinfo/domblklist/dommemstat
> live_migration: Add case about execute libvirt statistics command

- libvirt/tests/cfg/virsh_cmd/domain/virsh_guestinfo.cfg
- libvirt/tests/src/virsh_cmd/domain/virsh_guestinfo.py
Test Case: RHEL-287990
JOB ID     : 688b85a3ddac9b3568da8d33b433ffdcada30bcc
JOB LOG    : /root/avocado/job-results/job-2022-03-01T05.15-688b85a/job.log
(1/1) type_specific.io-github-autotest-libvirt.virsh.guestinfo.positive.interface_info: PASS (64.66 s)
JOB TIME   : 66.11 s
> [virsh.guestinfo]Add the case for the interface option

- v2v/tests/cfg/function_test_esx.cfg
> v2v: add a case about guest has greater than 16 disks

- v2v/tests/cfg/function_test_esx.cfg
- v2v/tests/cfg/specific_kvm.cfg
- v2v/tests/src/function_test_esx.py
- v2v/tests/src/function_test_xen.py
- v2v/tests/src/specific_kvm.py
> v2v: set default libguestfs_backend to libvirt

- libvirt/tests/src/virtual_device/filesystem_device.py
1) Should check the guest after detaching
2) Should check whether there is virtiofs after detaching
> [filesystem_device]Should add some checkpoints after detaching

- provider/v2v_vmcheck_helper.py
> v2v: add model='virtio-transitional' check for XML in rhel9

- v2v/tests/src/function_test_esx.py
- v2v/tests/src/function_test_xen.py
- v2v/tests/src/specific_kvm.py
> v2v: update the setting of LIBGEUSTFS_BACKEND

- libvirt/tests/src/sriov/sriov_scalability.py
Update to get PFs by given driver for scalability testing.
` (1/1) type_specific.io-github-autotest-libvirt.sriov.scalability.max_vfs: ERROR: Failed to set vf. (40.83 s)`
` (1/1) type_specific.io-github-autotest-libvirt.sriov.scalability.max_vfs: PASS (237.10 s)`
> sriov: Get PF list by given driver

- v2v/tests/cfg/function_test_esx.cfg
> v2v: add TC 'ESX windows poweroff external'

- libvirt/tests/src/virsh_cmd/domain/virsh_cpu_stats.py
this test point is logically unreasonable, so the commit:
1.Remove "check cpu_time > user_time + system_time"
2.Add test point:check libvirt time and cgroup time
libvirt time should between the pre and next cgroup time
3.Slightly changed a part of structure of the code
> Fix TestFail: total cpu_time < user_time + system_time

- v2v/tests/cfg/convert_from_file.cfg
> v2v new case: username of the ova file includes a blank space

- v2v/tests/cfg/function_test_esx.cfg
> v2v: add TC 'convert guest with sata disk'

- libvirt/tests/cfg/migration/migrate_mem.cfg
- libvirt/tests/src/migration/migrate_mem.py
Add case for nvdimm device migration.
In addition, the codes are restructured for better maintainence.
RHEL7-91734
> migrate_mem: add case for nvdimm and reorg

- libvirt/tests/cfg/migration/migrate_mem.cfg
- libvirt/tests/src/migration/migrate_mem.py
The scenario is to test large memory vm's migration.
RHEL7-17399
> migrate_mem: add case for large mem

- libvirt/tests/src/virsh_cmd/domain/virsh_cpu_stats.py
Cpuacct.stat doesn't exist on cgroup v2, and due to
the code structure, many cases failed. This PR
use cpu.stat as a substitute to fix the errors.
> Fix the FileNotFoundError caused by BZ-1796543

- libvirt/tests/cfg/virsh_cmd/domain/virsh_blkiotune.cfg
- libvirt/tests/src/virsh_cmd/domain/virsh_blkiotune.py
> Add one case to cover set blkiotune values, then start VM --bz 1645471

- libvirt/tests/src/virtual_device/tpm_device.py
Only check_pcrbanks when libvirt>=7.10.0 and swtpm>=0.7.0.
> tpm_device: check_pcrbanks only on new version

- libvirt/tests/cfg/virtual_network/virtual_network_multivms.cfg
- libvirt/tests/src/virtual_network/virtual_network_multivms.py
Test the function of one network option macTableManager=libvirt.
> Add 2 test cases about macTableManager=libvirt

- v2v/tests/cfg/function_test_esx.cfg
> v2v:add TC '-ip option is required when convert guest from VMware without vddk'

- v2v/tests/cfg/function_test_esx.cfg
> v2v:delete the duplicate TC on VM with sata disk

- v2v/tests/cfg/function_test_esx.cfg
> v2v: add case for guest which only root partition is luks encrypted

- v2v/tests/cfg/specific_kvm.cfg
- v2v/tests/src/specific_kvm.py
> v2v:add the required version for TC 'VM with sata disk'

- libvirt/tests/cfg/libvirtd/libvirtd.cfg
- libvirt/tests/src/libvirtd/libvirtd.py
RHEL7-103707 - [libvirtd] Restart libvirtd service bug 1450095
> libvirtd: Add case to test restart libvirtd service

- libvirt/tests/src/virsh_cmd/host/virsh_nodeinfo.py
> virsh_nodeinfo: fix incorrect checkpoints

- libvirt/tests/src/numa/numa_memory.py
- libvirt/tests/src/numa/numa_memory_migrate.py
Depends on https://github.com/avocado-framework/avocado-vt/pull/3406
> numa_memory: fix usage for check_logfile

- libvirt/tests/cfg/libvirtd/libvirtd.cfg
> libvirtd: Update error message

- libvirt/tests/cfg/virtual_disks/virtual_disks_rerror_policy.cfg
- libvirt/tests/src/virtual_disks/virtual_disks_rerror_policy.py
rerror_policy can have at least three values: ignore, report and stop
All of these scenarios are covered
> Add new cases to cover rerror_policy on virtual disk

- libvirt/tests/src/virtual_disks/virtual_disks_multidisks.py
Command output change to json format, and some flexbit change from on to true
or from off to false
> Fix some virtual disk failures due to command output change

- v2v/tests/cfg/convert_vm_to_libvirt.cfg
> v2v:correct rhel8_dev_short_id

- v2v/tests/cfg/function_test_esx.cfg
Add more scenarios to '--mac' cases.
> v2v: add and update --mac cases

- libvirt/tests/cfg/conf_file/qemu_conf/set_virtlogd.cfg
- libvirt/tests/src/conf_file/qemu_conf/set_virtlogd.py
Add test for stdio_handler="file".
> qemu_conf: add test for stdio_handler="file"

- provider/migration/migration_base.py
> migration_base: Fix a name error

- libvirt/tests/cfg/virsh_cmd/domain/virsh_migrate_stress.cfg
- libvirt/tests/cfg/virsh_cmd/domain/virsh_migration.cfg
- libvirt/tests/src/migration/live_migration.py
- libvirt/tests/src/migration/migrate_event.py
- libvirt/tests/src/migration/migrate_mem.py
- libvirt/tests/src/migration/migrate_service_control.py
- libvirt/tests/src/migration/migrate_storage.py
- libvirt/tests/src/migration/migrate_with_various_hostname.py
- libvirt/tests/src/virsh_cmd/domain/virsh_migrate_stress.py
- libvirt/tests/src/virsh_cmd/domain/virsh_migration.py
post_migration_check function in avocado-vt changed, so update
scripts which call this function.
> migration: Update param for post_migration_check function

- libvirt/tests/cfg/migration/network_data_transports/migration_network_data_transports_tcp.cfg
- libvirt/tests/src/migration/network_data_transports/migration_network_data_transports_tcp.py
- provider/migration/base_steps.py
- provider/migration/migration_base.py
> Add case for modular redesign migration

- v2v/tests/cfg/function_test_esx.cfg
- v2v/tests/src/function_test_esx.py
> v2v:add TC 'virsh can generate genid in xml from ESX'

- libvirt/tests/cfg/virsh_cmd/domain/virsh_save.cfg
- libvirt/tests/src/virsh_cmd/domain/virsh_save.py
Add save with --xml option test.
> virsh_save: add save with --xml option test

- libvirt/tests/cfg/virtual_network/iface_ovs.cfg
- libvirt/tests/src/virtual_network/iface_ovs.py
Polarion ID: VIRT-85122
This case test the bridge type interface using openvswitch support
hot plug with attach-device, do not support update-interface.
> Add case to attach/detach interface for bridge type using openvswitch

- libvirt/tests/src/conf_file/sysconfig_libvirt_guests/libvirt_guests.py
- libvirt/tests/src/virsh_cmd/domain/virsh_managedsave.py
> virsh_managedsave:Turn on --nvram option to undefine command

- libvirt/tests/src/numa/numa_config_with_auto_placement.py
> numa_config_with_auto_placement: remove dependency on cgget

- libvirt/tests/src/migration/migrate_vm.py
> migrate_vm: Add --nvram option to fix undefine failure

- v2v/tests/cfg/function_test_esx.cfg
> v2v:add TC 'Convert a guest with nonexistent iso attached'

- libvirt/tests/src/remote_access/virsh_non_root_polkit.py
Make sure no unexpected error shown in log when
connecting qemu:///system with non-root user
Bug: 1945501
JOB ID     : 448e88f0ed6ed6f45e875f2fc491c8dbef6fe487
JOB LOG    : /root/avocado/job-results/job-2022-05-07T03.17-448e88f/job.log
(1/1) type_specific.io-github-autotest-libvirt.virsh.non_root_polkit.positive_testing.virsh_connect_non_root: PASS (21.59 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 …
> Added checkpoint to confirm no error msg shown

- libvirt/tests/src/virtual_disks/virtual_disks_ceph.py
- libvirt/tests/src/virtual_disks/virtual_disks_gluster.py
- libvirt/tests/src/virtual_disks/virtual_disks_multidisks.py
Fix them by adding addtional option:--nvram
> Fix Those issues are relative to vm.define without --nvram option

- libvirt/tests/cfg/remote_access/remote_with_tcp.cfg
- libvirt/tests/src/remote_access/remote_access.py
Bug: 1431589
Case: RHEL-291931 VIRT-293779
> Added the case of tcp_min_ssf

- provider/v2v_vmcheck_helper.py
- v2v/tests/cfg/function_test_esx.cfg
- v2v/tests/src/function_test_esx.py
> v2v: add new case of targe qemu

- v2v/tests/cfg/function_test_esx.cfg
> v2v:add TC 'No useless info printed during conversion'

- libvirt/tests/src/cpu/max_vcpus.py
Add a checkpoint to check the vcpu max value in domcapabilities.
Case iD: VIRT-17891
> max_vcpus: add checkpoint

- libvirt/tests/src/virsh_cmd/domain/virsh_autostart.py
- libvirt/tests/src/virsh_cmd/domain/virsh_create.py
- libvirt/tests/src/virsh_cmd/domain/virsh_desc.py
> virsh_create: fix undefine with nvram

- libvirt/tests/src/virsh_cmd/snapshot/virsh_snapshot_create_as.py
Test scenario: Create external snapshot, check qemu-img info for the backing file info,
check the snaplist.
RHEL-133456
> virsh_snapshot_create_as: add snapshot case to check backing file

- libvirt/tests/cfg/bios/boot_order_seabios.cfg
- libvirt/tests/src/bios/boot_order_seabios.py
check the boot order of seabios guest with boot dev'='hd'
1 positive test scenario and three negative test scenarios
Polarion ID: VIRT-45956
> Add case to check boot order of seabios guest with boot dev'='hd'

- libvirt/tests/src/daemon/crash_regression.py
- libvirt/tests/src/libvirt_network_bandwidth.py
- libvirt/tests/src/virsh_cmd/network/virsh_net_define_undefine.py
- libvirt/tests/src/virsh_cmd/network/virsh_net_dhcp_leases.py
- libvirt/tests/src/virsh_cmd/network/virsh_net_start.py
- libvirt/tests/src/virsh_cmd/network/virsh_net_update.py
- libvirt/tests/src/virtual_network/iface_network.py
> Update test cases to adapt to updated NetworkXML class

- v2v/tests/cfg/function_test_esx.cfg
- v2v/tests/src/function_test_esx.py
> v2v: add a new case for suppressing vddk error msg

- v2v/tests/cfg/convert_from_file.cfg
> v2v: add TC 'Convert guest which is installed on nvme disk'

- libvirt/tests/src/virsh_cmd/host/virsh_nodecpumap.py
> [minor fix] virsh_nodecpumap: Fix wrong keyword

- libvirt/tests/cfg/migration/vm_configuration_and_status/migration_suspend_target_vm.cfg
- libvirt/tests/src/migration/vm_configuration_and_status/migration_vm_configuration_and_status.py
VIRT-293978 - VM live migration - suspend target vm
> migration: Add a case about suspend target vm

- libvirt/tests/cfg/migration/migration_uri/migration_network_data_transport_tcp.cfg
- libvirt/tests/src/migration/migration_uri/migration_network_data_transport_tcp.py
- provider/migration/base_steps.py
VIRT-293806 - VM live migration - network data transport -
TCP - migration_host
> migration: Add the case of migration_host

- libvirt/tests/cfg/migration/migration_uri/migration_network_data_transport_tls.cfg
- libvirt/tests/src/migration/migration_uri/migration_network_data_transport_tls.py
- provider/migration/base_steps.py
VIRT-294377 - VM live migration - network data transport - TLS
VIRT-293875 - VM live migration - network data transport - TLS - tls-destination
> migration: Add cases about network data transport TLS

- v2v/tests/cfg/function_test_esx.cfg
> v2v: add log check for case option_root.ask

- libvirt/tests/src/virtual_network/iface_coalesce.py
**depends on:** https://github.com/avocado-framework/avocado-vt/pull/3456
` (1/1) type_specific.io-github-autotest-libvirt.virtual_network.iface_coalesce.positive_testing.net_ovs.iface-bridge: PASS (10.68 s)
`
> Refactor code for interface virtualport change

- libvirt/tests/src/virtual_disks/startup_policy.py
After libvirt version 8.0.0, this also allows _TYPE_BLOCK volumes to use
startup policy [1].
[1]https://bugzilla.redhat.com/show_bug.cgi?id=2095758
> Fix startupPolicy failure on iscsi volume

- libvirt/tests/src/virsh_cmd/network/virsh_net_dumpxml.py
> Set debug=True for virsh.net_dumpxml tests

- tp-libvirt_review_comment_summary.rst
This tip is borrowed from Complexity part in Google engineering practice[1].
[1]https://google.github.io/eng-practices/review/reviewer/looking-for.html
> Add Complexity handling practices as one tip

- libvirt/tests/src/cpu/vcpu_affinity.py
- libvirt/tests/src/virsh_cmd/host/virsh_nodecpustats.py
- libvirt/tests/src/virsh_cmd/host/virsh_nodeinfo.py
> Revert v1 cgroup cpuset after offline/online cpu

- v2v/tests/cfg/function_test_esx.cfg
> v2v: add a new paritonless device case

- libvirt/tests/src/virsh_cmd/host/virsh_nodeinfo.py
Remove unnecessary checking and update with new checking
> virsh_nodeinfo: fix incorrect checking

- libvirt/tests/src/cpu/vcpu_affinity.py
- libvirt/tests/src/numa/numa_numatune_cpu.py
- libvirt/tests/src/virsh_cmd/host/virsh_nodecpumap.py
- libvirt/tests/src/virsh_cmd/host/virsh_nodecpustats.py
- libvirt/tests/src/virsh_cmd/host/virsh_nodeinfo.py
According to the update in https://github.com/avocado-framework/avocado-vt/pull/3466,
the scripts need to be updated.
> Fix for func entry update

- libvirt/tests/src/sriov/sriov.py
> Update vf_list reference of sriov tests

- libvirt/tests/cfg/virsh_cmd/snapshot/virsh_snapshot_mode.cfg
- libvirt/tests/src/virsh_cmd/snapshot/virsh_snapshot_mode.py
New snapshot mode: mode="manual" is introduced since libvirt version (8, 2, 0)
> Newly add test cases to cover new feature support in virsh snapshot

- libvirt/tests/cfg/migration/migration_uri/migration_network_data_transport_tcp_migrateuri.cfg
VIRT-293800 - VM live migration - network data transport - TCP - --migrateuri
> migration: Add a case about migrateuri

- libvirt/tests/cfg/migration/migration_uri/migration_network_data_transport_tcp_listen_address.cfg
VIRT-293810 - VM live migration - network data transport - TCP - --listen_address
> migration: Add case about listen_address

- libvirt/tests/cfg/migration/migration_uri/migration_network_data_transport_unix_proxy.cfg
VIRT-293885 - VM live migration - network data transport - UNIX+Proxy
> migration: Add a case about network data transport

- libvirt/tests/cfg/migration/migration_uri/migration_network_data_transport_tls_migrate_tls_force.cfg
- libvirt/tests/src/migration/migration_uri/migration_network_data_transport_tls.py
- provider/migration/base_steps.py
XXXX-293816 - VM live migration - network data transport - TLS -
migrate_tls_force
> migrateion: Add a case about migrate_tls_force

- libvirt/tests/cfg/controller/pcie_controllers.cfg
- libvirt/tests/src/controller/pcie_controllers.py
> pcie_controllers: fix incorrect print format

- libvirt/tests/cfg/migration_with_copy_storage/migration_vm_has_no_disk.cfg
- libvirt/tests/src/migration_with_copy_storage/migration_vm_has_no_disk.py
VIRT-294655 - Migrate vm with copy storage - vm has no disk
> Add case for copy storage migration with no disk

- libvirt/tests/src/guest_resource_control/control_cgroup.py
- libvirt/tests/src/libvirt_scsi_hostdev.py
- libvirt/tests/src/migration/migrate_vm.py
- libvirt/tests/src/svirt/dac_start_destroy.py
- libvirt/tests/src/virsh_cmd/domain/virsh_migrate.py
- libvirt/tests/src/virsh_cmd/domain/virsh_migrate_stress.py
- libvirt/tests/src/virsh_cmd/domain/virsh_setmem.py
- libvirt/tests/src/virtual_disks/virtual_disks_iscsi.py
Fix up E275 errors to work with the latest pycodestyle(2.9.0).
> Fix up inspekt check failures

- provider/sriov/sriov_base.py
Update the exception to make it more clear.
> sriov: Update error message for get_ping_dest

- libvirt/tests/cfg/virtual_device/filesystem_device.cfg
- libvirt/tests/src/virtual_device/filesystem_device.py
Case: VIRT-294615
Bug: 2079582
> Add the cases of thread_pool of virtiofs

- libvirt/tests/src/memory/memory_misc.py
> memory_misc: fix log output order

- libvirt/tests/src/sriov/vm_lifecycle/sriov_vm_lifecycle_start_negative.py
This case tends to check 'virsh define' instead of'virsh attach-device',
so udpate the command.
```
JOB ID     : ce5a8b3682f39c422895cff959d0bd99eb26fd26
JOB LOG    : /var/lib/avocado/job-results/job-2022-08-10T03.59-ce5a8b3/job.log
(1/8) type_specific.io-github-autotest-libvirt.sriov.vm_lifecycle.start.negative.hostdev_interface.vlan_trunk: PASS (21.29 s)
(2/8) …
```
> sriov: Update to check 'virsh define'

- v2v/tests/cfg/function_test_esx.cfg
- v2v/tests/cfg/specific_kvm.cfg
- v2v/tests/src/function_test_esx.py
- v2v/tests/src/specific_kvm.py
1) update the checking of qemu-ga for linux guests
2) some other minor fixes.
> v2v: fix some failures for function testing on rhel9.1

- libvirt/tests/cfg/virtual_device/tpm_device.cfg
- libvirt/tests/src/virtual_device/tpm_device.py
- spell.ignore
Add rsaencrypt and rsadecrypt test with various padding schemes.
> tpm_device: add rsaencrypt test

- libvirt/tests/src/graphics/graphics_functional.py
- libvirt/tests/src/virsh_cmd/domain/virsh_migrate.py
> Update references of Graphics

- libvirt/tests/src/libvirt_mem.py
- libvirt/tests/src/memory/memory_discard.py
- libvirt/tests/src/numa/guest_numa.py
- libvirt/tests/src/numa/numa_memAccess.py
- libvirt/tests/src/virsh_cmd/domain/virsh_migrate.py
- libvirt/tests/src/virtual_network/iface_options.py
> Update references of VMHugepagesXML

- libvirt/tests/cfg/controller/pcie_controllers.cfg
- libvirt/tests/src/controller/pcie_controllers.py
Depends on https://github.com/avocado-framework/avocado-vt/pull/3473
> pcie_controller: fix attach to pcie-root-controller dynamically

- libvirt/tests/cfg/graphics/graphics_functional.cfg
- libvirt/tests/src/graphics/graphics_functional.py
Add guest xml comparing according to the case steps
Add case ID: VIRT-60201 to test guest booting with listen type='none'
Update case ID: RHEL-171213 to test guest booting with listening on ipv4 localhost
Add case ID: VIRT-99682 to test guest booting with listen on hostname
Add case ID: VIRT-99680 to test guest booting with default vnc_listen address
> graphics_functional: add case checkpoints

- libvirt/tests/src/backingchain/blockcommit/blockcommit_all_block_chain.py
- libvirt/tests/src/backingchain/blockcommit/blockcommit_base_image_exist_backingfile.py
- libvirt/tests/src/backingchain/blockcommit/blockcommit_conventional_chain.py
- libvirt/tests/src/backingchain/blockcopy/blockcopy_with_backingfile.py
- libvirt/tests/src/backingchain/blockpull/blockpull_conventional_chain.py
need get_hash_value func to replace some sentences
Run with jenkins job ,Passed
> use get_hash_value function

- libvirt/tests/cfg/migration/live_migration.cfg
- libvirt/tests/cfg/migration/migrate_event.cfg
- libvirt/tests/cfg/migration/migrate_vm.cfg
- libvirt/tests/src/migration/migrate_vm.py
Error messages are changed for some cases.
> migration: Update error messages

- v2v/tests/cfg/function_test_esx.cfg
- v2v/tests/src/function_test_esx.py
> v2v: remove unsupported rhev-apt.exe cases for windows guests

- libvirt/tests/src/graphics/graphics_functional.py
Fix following error:
KeyError: 'listens'
> graphics_functional: Fix KeyError

- libvirt/tests/cfg/virtual_device/tpm_device.cfg
Update err msg per libvirt-8.7 changes by its commit#e31fc5bb2a.
> tpm_device: Update some error msgs

- libvirt/tests/src/hotplug_serial.py
hotplug_serial: fix subprocess.Popen() use error
hotplug_serial: don't need delete virtio-serial controller sometime
hotplug_serial: fix inconsistency filename between create and attach
> hotplug_serial：fix some bug

- libvirt/tests/src/memory/memory_misc.py
> Update code according to review comments

- libvirt/tests/cfg/migration/migration_efficiency/migration_vm_cpu_auto_converge.cfg
- libvirt/tests/src/migration/migration_efficiency/migration_efficiency.py
- provider/migration/migration_base.py
VIRT-293939 - VM live migration - guest cpu auto converge(--auto-converge)
> migration: Add case about auto converge

- v2v/tests/cfg/function_test_esx.cfg
> v2v: add new case about ignoring vmlinuz-*.rpmsave

- libvirt/tests/src/sriov/failover/sriov_failover_migration.py
> sriov: Update to scp correct xml file

- v2v/tests/cfg/function_test_esx.cfg
> v2v: add new case for 41 disks of VM

- libvirt/tests/cfg/migration/migration_efficiency/migration_zerocopy.cfg
- libvirt/tests/cfg/migration/migration_efficiency/migration_zerocopy_unsupported_feature_combinations.cfg
- libvirt/tests/cfg/migration/migration_uri/migration_network_data_transport_tls.cfg
migration_zerocopy.cfg: Fix for missing a variant.
migration_network_data_transport_tls.cfg: Fix typo error.
migration_zerocopy_unsupported_feature_combinations.cfg: Update error message.
> migration: Fix variant issue

- v2v/tests/cfg/nbdkit/nbdkit.cfg
- v2v/tests/src/nbdkit/nbdkit.py
Signed-off-by: Ming Xie <mxie@redhat.com>
e.g
> Auto nbdkit case 'RHEL-185339' and 'RHEL-172936'

- libvirt/tests/cfg/migration/migration_performance_tuning/migration_precopy_bandwidth.cfg
- libvirt/tests/src/migration/migration_performance_tuning/migration_precopy_bandwidth.py
- provider/migration/migration_base.py
VIRT-293955 - VM live migration - network bandwidth - precopy
> migration: Add case for precopy bandwidth

- libvirt/tests/cfg/migration/migration_performance_tuning/migration_timeout_action.cfg
- libvirt/tests/src/migration/migration_performance_tuning/migration_performance_tuning.py
- provider/migration/migration_base.py
VIRT-293949 - VM live migration - timeout action
> migration: Add case for timeout action

- libvirt/tests/cfg/svirt/dac_nfs_disk.cfg
- libvirt/tests/cfg/svirt/dac_nfs_save_restore.cfg
- libvirt/tests/src/svirt/dac_nfs_disk.py
- libvirt/tests/src/svirt/dac_nfs_save_restore.py
> Fix tpm device permission issue for the dac nfs related testcases

- provider/v2v_vmcheck_helper.py
> v2v: add TC 'libvirt vmware driver can expose the firmware/efi property'

- provider/v2v_vmcheck_helper.py
Please check bz#1217444 and PR#4532
> v2v: modification for TC ‘ 'libvirt vmware driver can expose the firmware/efi property'’

- libvirt/tests/src/libvirt_rng.py
Send data before vm start, to avoid booting block issue. 
> libvirt_rng: update udp rng test

- libvirt/tests/cfg/virsh_cmd/domain/virsh_emulatorpin_mix.cfg
- libvirt/tests/src/virsh_cmd/domain/virsh_iothreadadd.py
- libvirt/tests/src/virsh_cmd/domain/virsh_iothreaddel.py
- libvirt/tests/src/virsh_cmd/domain/virsh_iothreadinfo.py
- libvirt/tests/src/virsh_cmd/domain/virsh_iothreadpin.py
This is to align with below PR for new structure of iotheadids class. https://github.com/avocado-framework/avocado-vt/pull/3513
> Update cases for new iothreadids class

- libvirt/tests/src/channel/channel_functional.py
- libvirt/tests/src/conf_file/qemu_conf/set_virtlogd.py
- libvirt/tests/src/serial/serial_functional.py
- libvirt/tests/src/serial/serial_pty_log.py
- libvirt/tests/src/svirt/default_dac_check.py
- libvirt/tests/src/virsh_cmd/domain/virsh_detach_serial_device_alias.py
> Update reference of xml classes Serial, Console and Channel

- libvirt/tests/cfg/svirt/selinux_relabel.cfg
- libvirt/tests/src/svirt/selinux_relabel.py
- VIRT-294767 - Set selinux and dac lable for the unix sockets
> Add case of selinux relabel

- libvirt/tests/cfg/controller/controller_functional.cfg
- libvirt/tests/cfg/controller/pcibridge.cfg
The error message is updated in new version of libvirt.
> controller_functional: fix error message match

- libvirt/tests/src/virtual_device/tpm_device.py
swtpm.pid file should not exist after vm destroy, or managedsaved.
> tpm_device: check swtpm.pid file after vm destroy

- libvirt/tests/src/migration/migrate_options_shared.py
> migrate_options_shared.py:Update reference of Channel xml class

- libvirt/tests/src/bios/boot_integration.py
- libvirt/tests/src/bios/virsh_boot_sysinfo.py
ovmf: fix issues caused by firmware autoselection
> ovmf: fix issues caused by firmware autoselection

- libvirt/tests/src/conf_file/sysconfig_libvirt_guests/libvirt_guests.py
The current message output is broken.
> libvirt_guests:Update the regex pattern as a workaround

- libvirt/tests/cfg/migration/guest_lifecycle_operations_during_migration/migration_poweroff_vm.cfg
- libvirt/tests/src/migration/guest_lifecycle_operations_during_migration/migration_poweroff_vm.py
VIRT-294690 - VM live migration - poweroff vm during migration
> migration: Add case for poweroff vm

- libvirt/tests/cfg/migration/destructive_operations_around_live_migration/migration_kill_libvirt_daemon.cfg
- libvirt/tests/src/migration/destructive_operations_around_live_migration/migration_kill_libvirt_daemon.py
- provider/migration/migration_base.py
VIRT-294749 - VM live migration - kill libvirt daemon during PerformPhase of migration
> migration: Add case about kill libvirt daemon

- libvirt/tests/cfg/remote_access/remote_with_ssh.cfg
- libvirt/tests/src/remote_access/remote_access.py
Connecting to xen VM now required additional set before connecting to Xen VM. This commit adds the configuration.
Automation of VIRT-18307.
> remote_access: set up ssh and openssl before connect

- v2v/tests/cfg/function_test_esx.cfg
- v2v/tests/src/function_test_esx.py
> v2v: add a new case for cve_2022_2211

- libvirt/tests/cfg/svirt/dac_vm_per_image_start.cfg
- libvirt/tests/src/svirt/dac_vm_per_image_start.py
> Fix permission deny caused by tpm device for dac_vm_per_image_start

- libvirt/tests/src/virsh_cmd/domain/virsh_start.py
> virsh_start:Add log of vmxml before test start

- libvirt/tests/cfg/graphics/graphics_functional.cfg
- libvirt/tests/deps/hook_qemu_restore.py
- libvirt/tests/src/graphics/graphics_functional.py
Test scenario:
1.start a guest with vnc listening on an address specified by
vnc_listen parameter in qemu.conf
2.Save guest with graphic password restore guest with updated
XML by qemu hook
3. Start a guest with vnc listening on a unix domain socket path
4. Start a guest with graphic listening on ipv6 localhost
Case ID: VIRT-34250 VIRT-60537 VIRT-60236 VIRT-99679
> graphics_functional: add cases

- libvirt/tests/src/virsh_cmd/monitor/virsh_domblkinfo.py
Fix domblkinfo test case failure
These failed due to get different information from
virsh domblkinfo jeos-27-x86_64.qcow2 and virsh domblkinfo vda.
vda is systemd disk, and it tends to be written into some data during operations
By creating separate disk other than system disk, it help enhance this situation
> Fix domblkinfo test case failure

- libvirt/tests/cfg/usb_device.cfg
> usb_device: remove necessary package

- libvirt/tests/cfg/virsh_cmd/domain/virsh_domifaddr.cfg
- libvirt/tests/src/virsh_cmd/domain/virsh_domifaddr.py
- spell.ignore
- VIRT-99481: [domifaddr] get vm's ip address by domifaddr
> Add case of virsh domifaddr

- libvirt/tests/cfg/virsh_cmd/monitor/virsh_backing_chain_domblkinfo.cfg
- libvirt/tests/src/virsh_cmd/monitor/virsh_backing_chain_domblkinfo.py
perform operation: virsh block commit/pull/copy on block device,
then check there is no qemuDomainGetBlockInfo error
> Automate case: Check domblkinfo while operating on block device

- libvirt/tests/cfg/virsh_cmd/domain/virsh_domdirtyrate_calc.cfg
- libvirt/tests/src/virsh_cmd/domain/virsh_domdirtyrate_calc.py
Add the cases of mode dirty-bitmap and dirty-ring of domdirtyrate_calc cmd
Case: VIRT-294833 VIRT-294832
> Add the case of domdirtyrate_calc

- libvirt/tests/cfg/graphics/graphics_functional.cfg
- libvirt/tests/src/graphics/graphics_functional.py
The error is as expected:
Failed to bind socket: Cannot assign requested address
> graphics_functional: fix not assign address

- libvirt/tests/cfg/graphics/graphics_functional.cfg
> graphics_functional: fix spice_tls missing

- v2v/tests/cfg/convert_vm_to_libvirt.cfg
- v2v/tests/cfg/convert_vm_to_ovirt.cfg
> v2v:add ESXi8.0 conf info

- libvirt/tests/cfg/secure_execution_domain/secure_execution.cfg
- libvirt/tests/src/secure_execution/secure_execution.py
Secure execution: Implement SE environment check on s390x
Signed-off-by: Boqiao Fu <bfu@redhat.com>
> Implement SE environment check on s390x

- libvirt/tests/src/migration/migrate_options_shared.py
- libvirt/tests/src/virsh_cmd/domain/virsh_migrate.py
Check serial console before login.
> migration: Fix NoConsoleError

- v2v/tests/cfg/function_test_esx.cfg
Signed-off-by: Ming Xie <mxie@redhat.com>
> Auto case: convert guest with vmware non-admin user

- v2v/tests/cfg/nbdkit/nbdkit.cfg
- v2v/tests/src/nbdkit/nbdkit.py
Signed-off-by: Ming Xie <mxie@redhat.com>
> Add cases for -nbdkit checkwrite and blocksize_policy filters

- libvirt/tests/cfg/graphics/graphics_functional.cfg
- libvirt/tests/src/graphics/graphics_functional.py
Test scenario: Test islated/macvtap/host bridge network for graphics device (VIRT-13206)
> graphics_functional: add network case

- libvirt/tests/cfg/migration/live_migration.cfg
- libvirt/tests/cfg/migration/pause_postcopy_migration_and_recover/pause_and_disruptive_and_recover.cfg
- libvirt/tests/src/migration/pause_postcopy_migration_and_recover/pause_and_disruptive_and_recover.py
- provider/migration/migration_base.py
VIRT-294705 - [postcopy]VM live migration - pause migration->do disruptive operations->recover it
> migration: Add case about pause migration

- libvirt/tests/cfg/virtual_disks/virtual_disks_audit_log_disk.cfg
- libvirt/tests/src/virtual_disks/virtual_disks_audit_log_disk.py
Automate case:audit log related to guest disk
ausearch attach/detach audio log while hot-plug/unplug a disk to guest
> Automate case:audit log related to guest disk

- libvirt/tests/cfg/virsh_cmd/domain/virsh_cpu_xml.cfg
- libvirt/tests/deps/negative_domcapabilities_s390x.xml
Add incompatible cpu definition on s390x for expected error message.
> virsh_cpu_xml: add xml for s390x

- libvirt/tests/cfg/backingchain/hotplug_test/hot_un_plug.cfg
- libvirt/tests/src/backingchain/hotplug_test/hot_un_plug.py
This case add:
VIRT-294571 - Do blockcommit/blockpull/blockcopy after hot-unplug and hotplug the disk
> Backingchain: add case to do hotplug test

- libvirt/tests/cfg/virtual_network/iface_update.cfg
> iface_update:Update error message of negative test

- libvirt/tests/src/virsh_cmd/domain/virsh_set_user_password.py
> Fix the lock file error

- libvirt/tests/cfg/virtual_disks/virtual_disks_nvme.cfg
- libvirt/tests/src/virtual_disks/virtual_disks_nvme.py
- spell.ignore
Automate case:use NVME type virtual disk
VM start/hotplug/hotunplug BZ1519005
> Automate case:use NVME type virtual disk

- v2v/tests/src/function_test_xen.py
> v2v: fix HOME env issue when running in CI

- libvirt/tests/cfg/migration/migrate_mem.cfg
To fix following error:
LoginTimeoutError: Login timeout expired
> migrate_mem: Update the memory of numa cells

- libvirt/tests/src/virsh_cmd/monitor/virsh_domstate.py
Need more time to complete the kill action, so update timeout.
> virsh_domstate: Extend the timeout for kill action

- spell.ignore
- virttools/tests/cfg/virt_install/pxe.cfg
- virttools/tests/src/virt_install/pxe.py
Add a test case to use virt-install for pxe installation.
> virt_install: add pxe installation test

- libvirt/tests/src/virtual_network/iface_stat.py
iface stat on host and vm could be in flux therefore result of one check could not be accurate. Enable multiple checks on iface stat to make sure we get correct test result.
> iface_stat:fix failure of iface stat check

- libvirt/tests/cfg/numa/guest_numa.cfg
> guest_numa: add more memory

- libvirt/tests/src/libvirt_rng.py
Previously there was a test cancel step that stopped the test when multiple RNG devices were created. THis was done due to an existing bug. The bug is resolved and now this commit removes the test cancel.
> Libvirt RNG, remove test cancel due to bug

- libvirt/tests/src/virsh_cmd/domain/virsh_domblklist.py
- libvirt/tests/src/virsh_cmd/domain/virsh_hypervisor_cpu_compare.py
- libvirt/tests/src/virsh_cmd/filter/virsh_nwfilter_define.py
- libvirt/tests/src/virsh_cmd/network/virsh_net_create.py
- libvirt/tests/src/virsh_cmd/network/virsh_net_define_undefine.py
- libvirt/tests/src/virsh_cmd/pool/virsh_pool.py
- libvirt/tests/src/virsh_cmd/pool/virsh_pool_create.py
- libvirt/tests/src/virsh_cmd/virsh_itself.py
- libvirt/tests/src/virt_admin/virt_admin_itself.py
- libvirt/tests/src/virtio_transitional/virtio_transitional_base.py
- libvirt/tests/src/virtio_transitional/virtio_transitional_rng.py
- libvirt/tests/src/virtio_transitional/virtio_transitional_serial.py
- libvirt/tests/src/virtual_network/iface_update.py
Depends on and test results are located at:
- https://github.com/avocado-framework/avocado-vt/pull/3615
> Remove reference of virttest/element_tree.py

- libvirt/tests/cfg/migration/pause_postcopy_migration_and_recover/pause_and_recover_and_disruptive.cfg
Need use wait_for_unattended_mig function to wait unattended migration finished.
> migration: Fix unattended migration error

- libvirt/tests/cfg/migration/pause_postcopy_migration_and_recover/unattended_migration_and_disruptive.cfg
Update need_sleep_time parameter to fix login timeout error.
> migration: Fix LoginTimeoutError

- libvirt/tests/cfg/migration/pause_postcopy_migration_and_recover/pause_and_recover_and_disruptive.cfg
Wrong parameters for action_during_mig and action_during_do_mig.
> migration: Fix parameters issue

- libvirt/tests/cfg/cpu/vcpu_sched_core.cfg
- libvirt/tests/src/cpu/vcpu_sched_core.py
Test scenario: test sched_core with different values
Case ID: VIRT-296168
> vcpu_sched_core: add case for sched_core

- libvirt/tests/src/virtual_disks/virtual_disks_rotation_rate.py
Fix failed to open file '/var/tmp/xml_utils_temp_88tre3pp.xml' issue
python gc may quickly recycle disk object, although disk has one attribute disk.xml,which points to existed file.
So the solution to this is to copy out original disk xml
> Fix failed to open file '/var/tmp/xml_utils_temp_88tre3pp.xml' issue

- libvirt/tests/cfg/passthrough/pci/ism_pci_passthrough.cfg
- libvirt/tests/cfg/passthrough/pci/libvirt_pci_passthrough.cfg
- libvirt/tests/cfg/passthrough/pci/libvirt_pci_passthrough_hotplug.cfg
- libvirt/tests/cfg/passthrough/pci/vfio.cfg
- libvirt/tests/src/passthrough/pci/ism_pci_passthrough.py
1. Add test case to cover compatibility with reboot
2. Add test case to cover that ISM is functional
> ism_pci_passthrough: add additional test cases

- libvirt/tests/src/virsh_cmd/host/virsh_capabilities.py
Description: virsh URI doesn't discriminate between TCG and KVM, so it contains the string "qemu" in both the cases. Which is correct. But when TCG is disabled, there will not be a domain type = 'qemu'.
The correct way to check this is to parse the output of `$QEMU_BIN --accel help` and cross check that with what `virsh capabilities` shows.
> Fix for virsh_capabilities when tcg is disabled on power

- provider/v2v_vmcheck_helper.py
- spell.ignore
- v2v/tests/cfg/function_test_esx.cfg
- v2v/tests/src/function_test_esx.py
Add a test about '-o kubevirt'.
This is a very simple check. It will be enriched in future commit.
> v2v: add -o kubevirt case

- libvirt/tests/cfg/memory/memory_misc.cfg
No NUMA on s390x, disable tests.
> memory_misc: Disable numa tests on s390x

- libvirt/tests/src/virsh_cmd/monitor/virsh_dommemstat.py
Description: libvirtd is restarted after issuing virsh commands from libvirt version 5.6.0 on. Hence need to fix test expectations when libvirtd is off
> Fix for dommemstat error when libvirtd is off

- libvirt/tests/cfg/sriov/vIOMMU/sriov_iommu_alias.cfg
Update to support smmuv3 type iommu device.
> sriov: Add a test about smmuv3 iommu device

- v2v/tests/cfg/function_test_esx.cfg
> v2v:add TC 'Convert linux Rocky guests'

- libvirt/tests/cfg/virsh_cmd/secret/virsh_secret_define_undefine.cfg
- libvirt/tests/src/virsh_cmd/secret/virsh_secret_define_undefine.py
This PR auto:
VIRT-296906 - [secret-define] - Define ephemeral secret and hotplug disk with it
> Secret: add new cases for ephemeral secret

- libvirt/tests/src/backingchain/blockcopy/blockcopy_with_xml_option_to_luks_slice_image.py
blockcopy case need to get xml path when do blockcopy command
> fix blockcopy not find xml

- v2v/tests/cfg/function_test_esx.cfg
> v2v:add TC "Check info 'windows: skipping qemufwcfg stub driver' in debug log"

- libvirt/tests/cfg/virtual_device/tpm_device.cfg
- libvirt/tests/src/virtual_device/tpm_device.py
Add test about undefining vm with --tpm/--keep-tpm flags.
To auto case VIRT-296167.
> tpm_device: add undefine tpmstate tests

- virttools/tests/cfg/virt_install/blk_installation.cfg
- virttools/tests/cfg/virt_install/pxe_installation.cfg
- virttools/tests/cfg/virt_install/vfio_installation.cfg
- virttools/tests/src/virt_install/blk_installation.py
- virttools/tests/src/virt_install/pxe_installation.py
- virttools/tests/src/virt_install/vfio_installation.py
1. Add a test case that will install a distro from url with kickstart into a dasd host device.
2. Add test case that installs a distro with kickstart onto a DASD disk via virtio-blk
3. Rename existing pxe installation test for consistency in test case naming.
> virttools: add distro installation into DASD

- provider/virtual_disk/disk_base.py
Before fixing:
ShellTimeoutError: Timeout expired while waiting for shell command to complete: 'sha256sum /dev/vdb'    (output: '')&#10;
After fixing:
All passed in jenkins jobs
> fix rbd image size issue

- libvirt/tests/cfg/cpu/vcpu_metrics.cfg
- libvirt/tests/src/cpu/vcpu_metrics.py
This is to test unpriviledge user can also get valid result for virsh domstats and virsh cpu_stats.
Case ID: VIRT-296663
> vcpu_metrics: add case with unpriviledged user

- v2v/tests/cfg/function_test_esx.cfg
> v2v:add TC "Check ovirt:id in v2v debug log"

- libvirt/tests/src/virsh_cmd/domain/virsh_detach_device_alias.py
Sometimes it fails when attaching a pci device to vm because the pci device can not support the attaching or its iommu-group has more than one device. So the simple fix is to skip the test when the selected pci is not suitable for the test.
> virsh_detach_device_alias: skip attach error for pci

- libvirt/tests/src/virsh_cmd/domain/virsh_setmem.py
- libvirt/tests/src/virtual_device/input_devices.py
- libvirt/tests/src/virtual_device/video_devices.py
Based on https://github.com/avocado-framework/avocado-vt/pull/3654 to make some updates on memory/input/video device
> Update driver_packed attribute on mem/input/video device

- v2v/tests/cfg/function_test_esx.cfg
Please check the latest failed func TC.
> v2v:fix invalid mac IP address of func testing

- libvirt/tests/cfg/virtual_device/watchdog.cfg
- libvirt/tests/src/virtual_device/watchdog.py
> Add the test of watchdog device tco

- libvirt/tests/src/sriov/nodedev/sriov_nodedev_reattach_detach.py
Test case updated, so update the code accordingly.
` (1/1) type_specific.io-github-autotest-libvirt.sriov.nodedev.nodedev_reattach_detach.vf: PASS (27.03 s)
`
> sriov: Update nodedev case

- libvirt/tests/cfg/conf_file/libvirtd_conf/processing_controls.cfg
- libvirt/tests/src/conf_file/libvirtd_conf/processing_controls.py
> Add the cases of clients test of libvirt daemon

- libvirt/tests/cfg/migration_with_vtpm/migration_with_shared_tpm.cfg
- libvirt/tests/src/migration_with_vtpm/migration_with_shared_tpm.py
VIRT-XXXX - Migrate vm with vtpm device with shared TPM state
> migration: Add case for migration with shared TPM state

- libvirt/tests/src/cpu/vcpu_metrics.py
\<nvram xxx\> in \<os\> is automatically generated by libvirt when defining the vm. Befine defining a vm for unpriviledged user, the nvram setting should be removed in order for libvirt to generate a nvram path under unpriviledged user's home directory.
> vcpu_metrics: fix nvram permission error

- libvirt/tests/src/numa/numa_memory.py
In '/proc/{vm_id}/numa_maps' file, there is a change that prefer mode support many now. So the message is changed like below. This patch is to fix the match pattern.
'7f8113e00000 prefer \*\*(many)\*\*:0 anon=218126 dirty=218126 active=211470 N0=218126 kernelpagesize_kB=4'
> numa_memory: fix prefer error

- libvirt/tests/cfg/mem/memory_allocation/memory_allocation_config_modification.cfg
- libvirt/tests/src/mem/memory_allocation/memory_allocation_config_modification.py
- spell.ignore
VIRT-297052: Memory allocation config modification
> add case for memory allocation modification

- libvirt/tests/cfg/virtual_network/passt/passt_function.cfg
- libvirt/tests/src/virtual_network/passt/passt_function.py
- provider/virtual_network/passt.py
- spell.ignore
- VIRT-297034 - [user][passt] Passt backend interface - check vm interface info and network connectivity
- VIRT-297101 - [user][passt] Passt backend interface - check the portforwarding feature
Depends on:
- https://github.com/avocado-framework/avocado-vt/pull/3667
- https://github.com/avocado-framework/avocado-vt/pull/3668
- https://github.com/avocado-framework/avocado-vt/pull/3673
- https://github.com/avocado-framework/avocado-vt/pull/3676
- https://github.com/avocado-framework/avocado-vt/pull/3678
Test result:
(1/4) type_specific.io-github-autotest-libvirt.virtual_network.passt.interface_function.minimal.root_user: PASS (249.55 s)
(2/4) type_specific.io-github-autotest-libvirt.virtual_network.passt.interface_function.minimal.non_root_user: PASS (175.07 s)
(3/4) …
> Add case of passt

- libvirt/tests/cfg/domain_life_cycle/create_destroy_domain.cfg
- libvirt/tests/src/domain_life_cycle/create_destroy_domain.py
cover domain life cycle operations
xx-116808, xx-152484,xx-196153,xx-17119,xx-17126,xx-39631, xx-46211,xx-49314 ,xx-59081
> Add domain lifecycle test cases

- libvirt/tests/src/virtual_network/iface_update.py
- provider/sriov/check_points.py
Depends on:
- https://github.com/avocado-framework/avocado-vt/pull/3678
> Update arg list due to modification of utils_net.get_linux_iface_info

- libvirt/tests/src/event/virsh_event.py
Fix event case failure
io-error-reason event type is converged into io-error after libvirt version 9.0.0
> Fix event case failure

- v2v/tests/cfg/convert_vm_to_libvirt.cfg
- v2v/tests/cfg/convert_vm_to_ovirt.cfg
> v2v:adjust configuration for adding uefi guests

- libvirt/tests/cfg/snapshot/memory_snapshot_delete.cfg
- libvirt/tests/src/snapshot/memory_snapshot_delete.py
- provider/snapshot/snapshot_base.py
Test scenario:
Delete snapshots for running or paused vm
Case ID: VIRT-297108
> memory_snapshot_delete: add case for memory snapshot deletion

- libvirt/tests/cfg/virtual_disks/virtual_disks_filedescriptor.cfg
- libvirt/tests/src/virtual_disks/virtual_disks_filedescriptor.py
Cover associate fd with for VM Start, Associate fd with for VM disk Attach-Detach Associate fd with for VM Save-Restore
with case id: xx-296997,xx-297300,xx-297299
> Add disk file descriptor cases

- libvirt/tests/src/backingchain/blockcommit/check_allocation_watermark_during_blockcommit.py
Usually before we create different files to the mounted path, we are asked to format the disk once. Or it will get error: ShellTimeoutError: Timeout expired while waiting for shell command to complete....../dev/vdb contains a ext4 file system......Proceed anyway? (y,N). That can block our auto test. So here fix it.
> backingchain: vm's disk need to be formated only for one time

- libvirt/tests/cfg/chardev/connection_and_operation/file_append_option.cfg
- libvirt/tests/src/chardev/connection_and_operation/file_append_option.py
- spell.ignore
> chardev:add case for chardev file append

- libvirt/tests/cfg/chardev/connection_and_operation/data_transfer.cfg
- libvirt/tests/src/chardev/connection_and_operation/data_transfer.py
- provider/chardev/chardev_base.py
- provider/chardev/check_points.py
- spell.ignore
> add case for chardev data transfer

- libvirt/tests/cfg/virtual_network/start_vm_with_duplicate_target_dev_name.cfg
- libvirt/tests/src/virtual_network/start_vm_with_duplicate_target_dev_name.py
According to bug 2144738 and 2166235, add the support version for the duplidate target cases.
> Add the support version for duplicate target cases

- provider/virtual_network/passt.py
The others could not be used by passt test.
Also split function check_proc_info to create get_proc_info for other tests.
Test result:
PASS 1-type_specific.io-github-autotest-libvirt.virtual_network.passt.interface_function.ip_portfw.root_user
> passt:Only get default gateway with dhcp

- libvirt/tests/cfg/numa/guest_numa_topology/various_numa_topology_settings.cfg
- libvirt/tests/src/numa/guest_numa_topology/various_numa_topology_settings.py
- provider/numa/numa_base.py
Case ID :  VIRT-296717 - Various numa topology settings
> various_numa_topology_settings: add case

- libvirt/tests/src/virtual_network/iface_stat.py
The original file is very slow to get, replace it.
> Replace the big file path

- libvirt/tests/cfg/save_and_restore/save_with_formats.cfg
- libvirt/tests/src/save_and_restore/save_with_formats.py
- VIRT-296946: Save vm to file with various formats
> Add case of save with formats

- libvirt/tests/cfg/virtual_disks/virtual_disks_cdrom_device.cfg
- libvirt/tests/src/virtual_disks/virtual_disks_cdrom_device.py
Add cdrom tray reboot/reset cases
Bug 1824722 - cdrom tray state is not updated on VM reset
> Add cdrom tray reboot/reset cases

- provider/virtual_network/passt.py
> Fixup:passt:Set shell=True when running check command

- libvirt/tests/cfg/numa/guest_numa_node_tuning/memory_binding_with_emulator_thread.cfg
- libvirt/tests/src/numa/guest_numa_node_tuning/memory_binding_with_emulator_thread.py
Test scenario:
Test numa memory binding together with emulator thread pin can
work correctly.
> memory_binding_with_emulator_thread: add case

- libvirt/tests/cfg/numa/guest_numa_topology/numa_topology_with_numa_distance.cfg
- libvirt/tests/src/numa/guest_numa_topology/numa_topology_with_numa_distance.py
This is to test guest numa topology with distance is working well.
Case ID: VIRT-296724
> numa_topology_with_numa_distance: add case

- libvirt/tests/src/migration/migrate_ceph.py
- libvirt/tests/src/migration/migrate_vm.py
Migration process number changes from '100 %' to '100.00 %'.
> migration: Fix migration process number issue

- libvirt/tests/src/virtual_disks/virtual_disks_filedescriptor.py
Fix virtual_disks file descriptor failure issue
sleep command is not supported in virsh command, so need remove it
> Fix virtual_disks file descriptor failure issue

- libvirt/tests/cfg/migration/migration_uri/migration_network_data_transport_tcp_migration_port_reuse.cfg
- libvirt/tests/src/migration/migration_uri/migration_network_data_transport_tcp.py
VIRT-XXXX - VM live migration - network data transport -
TCP - migration port reuse
> migration: Add case about migration_port_reuse

- libvirt/tests/cfg/cpu/vcpu_misc.cfg
- libvirt/tests/src/cpu/vcpu_misc.py
- spell.ignore
Add new test scenario for maxphysaddr element.
BTW, restructure the codes.
Case ID: VIRT-298061
> vcpu_misc: add case for maxphysaddr

- libvirt/tests/cfg/numa/guest_numa_node_tuning/memory_binding_setting.cfg
- libvirt/tests/src/numa/guest_numa_node_tuning/memory_binding_setting.py
- provider/numa/numa_base.py
Test scenario: test various host numa memory binding settings
Case ID: VIRT-297112 
> memory_binding_setting: add case

- libvirt/tests/cfg/numa/guest_numa_topology/numa_topology_with_cpu_topology.cfg
- libvirt/tests/src/numa/guest_numa_topology/numa_topology_with_cpu_topology.py
Case ID: VIRT-296723 - Numa topology with cpu topology
> numa_topology_with_cpu_topology: add case

- libvirt/tests/cfg/migration/async_job/migration_domjobinfo.cfg
- libvirt/tests/src/migration/async_job/migration_domjobinfo.py
- provider/migration/migration_base.py
VIRT-XXXX - VM live migration - domjobinfo - migration succeeds
> migration: Add case about domjobinfo

- libvirt/tests/src/chardev/connection_and_operation/data_transfer.py
Put a new method to get check host msg
```
avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 chardev.data_transfer.serial.isa_target.pipe chardev.data_transfer.console.serial_target.pipe --vt-connect-uri qemu:///system
(1/2) type_specific.io-github-autotest-libvirt.chardev.data_transfer.serial.isa_target.pipe: PASS (165.60 s)
(2/2) type_specific.io-github-autotest-libvirt.chardev.data_transfer.console.serial_target.pipe: PASS (177.73 s)
```
> fix data transfer case not find host msg

- libvirt/tests/cfg/virtual_network/passt/passt_reconnect.cfg
- libvirt/tests/src/virtual_network/passt/passt_reconnect.py
- VIRT-297074: [user][passt] Passt backend interface - check the reconnect function
Test result:
(1/2) type_specific.io-github-autotest-libvirt.virtual_network.passt.reconnect.ip_portfw.root_user: PASS (341.52 s)
(2/2) type_specific.io-github-autotest-libvirt.virtual_network.passt.reconnect.ip_portfw.non_root_user: PASS (266.89 s)
> Add new case of passt

- libvirt/tests/cfg/migration/migration_uri/migration_network_data_transport_tcp_migration_address.cfg
- libvirt/tests/src/migration/migration_uri/migration_network_data_transport_tcp.py
- provider/migration/migration_base.py
VIRT-XXXX - VM live migration - network data transport -
TCP - migration_address
> migration: Add case about migration_address

- libvirt/tests/cfg/migration/migration_misc/migration_with_host_hostname.cfg
- libvirt/tests/src/migration/migration_misc/migration_with_host_hostname.py
VIRT-XXXX - VM live migration - various formats for host's hostname
> migration: Add cases about hostname

- libvirt/tests/cfg/migration/abort_precopy_migration/abort_by_domjobabort_on_target.cfg
- libvirt/tests/src/migration/abort_precopy_migration/abort_by_domjobabort_on_target.py
- provider/migration/migration_base.py
VIRT-XXXX - VM live migration - abort job by domjobabort - on target host - precopy/postcopy
> migration: Add case about abort job on target host

- libvirt/tests/cfg/numa/guest_numa_topology/numa_topology_with_hugepage.cfg
- libvirt/tests/src/numa/guest_numa_topology/numa_topology_with_hugepage.py
- provider/numa/numa_base.py
Scenario: Test vm numa backend with different hugepage size
Case ID:  VIRT-297086
> numa_topology_with_hugepage: add case numa topology with hugepage

- libvirt/tests/cfg/migration_with_copy_storage/migration_with_backingchain.cfg
- libvirt/tests/src/migration_with_copy_storage/migration_with_backingchain.py
VIRT-XXXX - VM live migration with copy storage - disk with/without backing chain (basic function)
> migration: Add case for disk with backingchain

- libvirt/tests/cfg/guest_os_booting/ovmf_firmware/ovmf_nvram.cfg
- libvirt/tests/src/guest_os_booting/ovmf_firmware/ovmf_nvram.py
Automate case:
VIRT-297064 - [OVMF] Boot vm with ovmf nvram
> guest_os_booting: add new case for ovmf nvram

- libvirt/tests/cfg/migration_with_copy_storage/network_data_transport/unix_proxy.cfg
- libvirt/tests/src/migration_with_copy_storage/network_data_transport/unix_proxy.py
VIRT-297899 - VM live migration with copy storage - network data
transport - UNIX+Proxy
> migration: Add case to test UNIX+Proxy transport

- libvirt/tests/cfg/migration_with_copy_storage/network_data_transport/tls_destination.cfg
- libvirt/tests/cfg/migration_with_copy_storage/network_data_transport/tls_wrong_cert_configurations.cfg
- libvirt/tests/src/migration_with_copy_storage/network_data_transport/tls.py
- provider/migration/base_steps.py
1. VIRT-297898 - VM live migration with copy storage - network data transport - TLS - tls-destination
2. VIRT-297897 - VM live migration with copy storage- network data transport - TLS - wrong cert configurations
> migration: Add cases about live migration with copy storage

- libvirt/tests/cfg/libvirt_rng.cfg
- libvirt/tests/src/libvirt_rng.py
Add checkpoint to confirm resources are audited
> libvirt_rng: add checkpoint for audit log

- libvirt/tests/cfg/memory/hmat.cfg
- libvirt/tests/src/memory/hmat.py
Test result:
PASS 1-type_specific.io-github-autotest-libvirt.hmat.hmat
> Fixup:update dmesg check list to be compatible with new version

- libvirt/tests/cfg/virtual_device/watchdog.cfg
> watchdog:skip model itco for pseries

- libvirt/tests/cfg/guest_os_booting/ovmf_firmware/ovmf_smm.cfg
- libvirt/tests/src/guest_os_booting/ovmf_firmware/ovmf_smm.py
This PR automate:
VIRT-297068 - [OVMF] Boot vm with ovmf smm
> guest_os_booting: add new case for ovmf smm

- libvirt/tests/cfg/numa/guest_numa_node_tuning/auto_memory_incompatible_guest_binding.cfg
- libvirt/tests/src/numa/guest_numa_node_tuning/auto_memory_incompatible_guest_binding.py
- provider/numa/numa_base.py
Verify error prompts when using auto memory placement with incompatible guest specified binding settings.
Case ID: xxx-297678
> auto_memory_incompatible_guest_binding: new case

- libvirt/tests/cfg/migration/migration_performance_tuning/migration_parallel_connections.cfg
- libvirt/tests/src/migration/migration_performance_tuning/migration_performance_tuning.py
VIRT-XXXX - VM live migration - parallel network connections
> migration: Add case about parallel connections

- v2v/tests/cfg/nbdkit/nbdkit.cfg
- v2v/tests/src/nbdkit/nbdkit.py
1. Test thread_model of filters in vddk plugin
2. Test create options of vddk plugin
3. Test scan, readhead, blocksize filter in vddk plugin
> Add three vddk cases

- libvirt/tests/cfg/scsi/scsi_device.cfg
- libvirt/tests/src/scsi/scsi_device.py
Add scsi hostdev and controller cases
xx-98979,xx-54603,xx-103724,xx-202693,xx-186120,xx-172931,xx-134267
> Add scsi hostdev and controller cases

- libvirt/tests/cfg/memory/memory_allocation/lifecycle_with_memory_allocation.cfg
- libvirt/tests/cfg/memory/memory_allocation/memory_invalid_value.cfg
> memory: disable tests for s390x

- libvirt/tests/cfg/virsh_cmd/domain/virsh_emulatorpin.cfg
- libvirt/tests/cfg/virsh_cmd/domain/virsh_numatune.cfg
- libvirt/tests/src/cpu/guestpin.py
- libvirt/tests/src/cpu/powerpc_hmi.py
- libvirt/tests/src/numa/numa_config_with_auto_placement.py
These changes are to align with below patch.
https://github.com/avocado-framework/avocado-vt/pull/3722
> Update for option format -- added

- libguestfs/tests/guestfish_fs_attr_ops.py
- libvirt/tests/src/graphics/graphics_functional.py
Fixup inspekt checking failures in the latest python 3.8/9 jobs.
> Fixup inspekt checking failures

- libvirt/tests/cfg/guest_os_booting/ovmf_firmware/ovmf_firmware_feature.cfg
- libvirt/tests/src/guest_os_booting/ovmf_firmware/ovmf_firmware_feature.py
This PR automate:
VIRT-297067 - [OVMF] Boot vm with ovmf firmware feature
> guest_os_booting: add new case for ovmf firmware feature

- libvirt/tests/cfg/guest_os_booting/seabios_firmware/seabios_loader.cfg
- libvirt/tests/src/guest_os_booting/seabios_firmware/seabios_loader.py
This PR automate:
VIRT-297115 - Boot vm with seabios loader
> guest_os_booting: add new case for seabios loader

- v2v/tests/cfg/nbdkit/nbdkit.cfg
- v2v/tests/src/nbdkit/nbdkit.py
1. Test statfile option for stat filter
2. Test rate filter
3. Test nbdkit-server rpm package with annocheck tool
> Add three nbdkit cases about stats, rate, annobin

- provider/guest_os_booting/guest_os_booting_base.py
Add a function to choose a vm with different boot os for guest_os_booting cases.
Test:
```
params = {'vms': "avocado-vt-vm1 vm2"}
print(guest_os_booting_base.get_vm(params))
params = {'vms': "avocado-vt-vm1 vm2", "boot_os_type": "seabios"}
print(guest_os_booting_base.get_vm(params))
params = {'vms': "avocado-vt-vm1 vm2", "boot_os_type": "seabioss"}
res = guest_os_booting_base.get_vm(params)
print(res)
```
Test results:
```
avocado-vt-vm1
vm2
Traceback (most recent call last):
File "/var/ci/libvirt-ci/runtest/avocado-vt/tp-libvirt/provider/guest_os_booting/test.py", line 8, in <module>
res = guest_os_booting_base.get_vm(params)
File "/var/ci/libvirt-ci/runtest/avocado-vt/tp-libvirt/provider/guest_os_booting/guest_os_booting_base.py", line 38, in get_vm
raise exceptions.TestError("Unable to …
```
> guest_os_booting: Add a function to get vm

- libvirt/tests/src/migration/migration_performance_tuning/migration_zerocopy.py
According to bug 2169733, multifd and postcopy migration will fail on RHEL 8. So update some parameters for postcopy cases.
> migration: Update case for multifd and postcopy migration

- libvirt/tests/src/memory/memory_devices/lifecycle_of_mixed_memory_devices.py
Test result:
```
[root@dell-per730-59 tp-libvirt]# rpm -q libvirt
libvirt-9.5.0-0rc1.1.el9.x86_64
[root@dell-per730-59 tp-libvirt]# cat /proc/version
Linux version 5.14.0-333.el9.x86_64 (mockbuild@x86-64-01.build.eng.rdu2.redhat.com) (gcc (GCC) 11.4.1 20230605 (Red Hat 11.4.1-2), GNU ld version 2.35.2-42.el9) #1 SMP PREEMPT_DYNAMIC Wed Jun 28 07:51:51 EDT 2023
[root@dell-per730-59 tp-libvirt]# avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 memory.devices.lifecycle.mutiple_mem --vt-connect-uri qemu:///system
(1/1) type_specific.io-github-autotest-libvirt.memory.devices.lifecycle.mutiple_mem: PASS (197.86 s)
```
> fix mutiple memory issue

- libvirt/tests/src/backingchain/blockcopy.py
The original implementation replaced the VM disk. This works only if the VM still boots with an empty disk which is not true for s390x.
Instead add a disk and check that one.
> backingchain: fix test on s390x

- libvirt/tests/cfg/backingchain/blockcommit/blockcommit_relative_path.cfg
Add new test scenario to test --keep-relative and --bandwidth
> backingchain: add case with --keep-relative and --bandwidth

- libvirt/tests/cfg/numa/guest_numa_node_tuning/change_numa_tuning.cfg
- libvirt/tests/src/numa/guest_numa_node_tuning/change_numa_tuning.py
- provider/numa/numa_base.py
Add case to test changing numatune
Case ID: xxx-297113
> change_numa_tuning: add case for changing numatune

- libvirt/tests/cfg/virtual_network/iface_update.cfg
Also accept new error msg for negative_val from libvirt-9.5.0.
> iface_update.cfg: update error msg

- libvirt/tests/cfg/backingchain/blockcopy/blockcopy_with_conventional_chain.cfg
Add new test scenario of nfs_disk for blockcopy
> backingchain: add nfs_disk test for blockcopy

- libvirt/tests/src/numa/guest_numa_topology/numa_topology_with_hugepage.py
Depend on 
- https://github.com/avocado-framework/avocado-vt/pull/3741
> numa_topology_with_hugepage: rename hugepage path param

- v2v/tests/cfg/nbdkit/nbdkit.cfg
- v2v/tests/src/nbdkit/nbdkit.py
1. Auto nbdkit case to test create option of ssh plugin
2. Auto nbdkit case to test delay-close and delay-open options
3. Auto nbdkit case to test cow-on-read options
> Auto nbdkit cases about ssh, delay and cow

- libvirt/tests/cfg/numa/guest_numa_node_tuning/memory_binding_with_emulator_thread.cfg
- libvirt/tests/cfg/numa/guest_numa_node_tuning/specific_numa_memory_bind_hugepage.cfg
- libvirt/tests/src/numa/guest_numa_node_tuning/change_numa_tuning.py
- libvirt/tests/src/numa/guest_numa_node_tuning/memory_binding_with_emulator_thread.py
- libvirt/tests/src/numa/guest_numa_node_tuning/specific_numa_memory_bind_hugepage.py
- provider/numa/numa_base.py
Test scenario: Test numa node memory binding with hugepage
Depend on
- https://github.com/avocado-framework/avocado-vt/pull/3699
> specific_numa_memory_bind_hugepage: add case

- libvirt/tests/cfg/save_and_restore/restore_from_local_file.cfg
- libvirt/tests/src/save_and_restore/restore_from_local_file.py
- spell.ignore
- VIRT-297087 - Restore vm from a saved file - local storage
Test result:
(1/6) type_specific.io-github-autotest-libvirt.save_and_restore.restore_from_local_file.readonly.file_opt: PASS (52.92 s)
(2/6) type_specific.io-github-autotest-libvirt.save_and_restore.restore_from_local_file.normal.file_opt: PASS (59.58 s)
(3/6) type_specific.io-github-autotest-libvirt.save_and_restore.restore_from_local_file.normal.running_opt: PASS (57.10 s)
(4/6) type_specific.io-github-autotest-libvirt.save_and_restore.restore_from_local_file.normal.paused_opt: PASS (56.43 s)
(5/6) type_specific.io-github-autotest-libvirt.save_and_restore.restore_from_local_file.normal.xml_opt: PASS (59.60 s)
(6/6) type_specific.io-github-autotest-libvirt.save_and_restore.restore_from_local_file.normal.bypass_cache_opt: PASS …
> Add new case of restore from file

- v2v/tests/cfg/function_test_esx.cfg
> v2v:fix failed functionalTC- lvm_multiple_disks

- v2v/tests/cfg/function_test_esx.cfg
- v2v/tests/src/function_test_esx.py
> v2v:fix functionalTC-invalid_os_storage

- libvirt/tests/src/numa/numa_memory.py
The current code supports setting nodeset dynamically.
> numa_memory:Remove ppc settings

- libvirt/tests/cfg/migration_with_copy_storage/network_data_transport/tcp_port_reuse.cfg
- libvirt/tests/src/migration_with_copy_storage/network_data_transport/tcp_port_reuse.py
VIRT-297873 - VM live migration with copy storage - network data
transport - TCP - port reuse
> migration: Add case for port reuse

- v2v/tests/cfg/nbdkit/nbdkit.cfg
- v2v/tests/src/nbdkit/nbdkit.py
1. Add case to test cow-block-size option
2. Add case to test cache-on-read option
3. Add case to check if reduce verbosity of debugging
> Auto nbdkit cases about cow, cache filter, debug

- libvirt/tests/cfg/migration/vm_configuration_and_status/persist_target_vm_and_undefine_src_vm_and_abort.cfg
- libvirt/tests/src/migration/vm_configuration_and_status/persist_target_vm_and_undefine_src_vm_and_abort.py
VIRT-293979 - [VM migration] persist target vm and undefine src vm - abort migration
> migration: Add case about persistent vm and abort

- libvirt/tests/cfg/migration/migration_uri/migration_network_data_transport_tls_wrong_cert_configuration.cfg
- libvirt/tests/src/migration/migration_uri/migration_network_data_transport_tls.py
Add new scenario:
1. Server cert and client cert have different cert issuer.
> migration: Update case for wrong cert configuration

- libvirt/tests/src/virsh_cmd/pool/virsh_pool_auth.py
- libvirt/tests/src/virsh_cmd/pool/virsh_pool_autostart.py
- libvirt/tests/src/virsh_cmd/pool/virsh_pool_create.py
- libvirt/tests/src/virtual_disks/at_dt_iscsi_disk.py
- libvirt/tests/src/virtual_disks/startup_policy.py
- libvirt/tests/src/virtual_disks/virtual_disks_multidisks.py
> updates for poolxml changes

- libvirt/tests/cfg/virtio/virtio_page_per_vq.cfg
- libvirt/tests/src/virtio/virtio_page_per_vq.py
This PR is to automate case:
RHEL-291070 - [virtio][page_per_vq]Start guest with virtio page_per_vq attribute - various virtio devices
> virtio: add new case for virtio page_per_vq attribute

- v2v/tests/cfg/function_test_esx.cfg
> v2v:add TC "v2v should recognize partition names like '/dev/mapper/.."

- libvirt/tests/cfg/guest_os_booting/seabios_firmware/seabios_rebootimeout.cfg
- libvirt/tests/src/guest_os_booting/seabios_firmware/seabios_rebootimeout.py
This case automate:
VIRT-297120 - Boot vm with seabios rebootTimeout
> guest_os_booting: add new case for seabios rebootTimeout

- libvirt/tests/cfg/numa/guest_numa_topology/change_vcpu_pin.cfg
- libvirt/tests/src/numa/guest_numa_topology/change_vcpu_pin.py
- libvirt/tests/src/virtual_network/connectivity/connectivity_check_network_interface.py
- provider/numa/numa_base.py
Scenario:  Test vcpupin can pin to different host numa nodes
> change_vcpu_pin: add case numa with vcpupin

- v2v/tests/cfg/v2v_options.cfg
> v2v: add TC "Convert the img which is set immutable bits"

- libvirt/tests/cfg/migration/migration_cmd/setspeed_and_getspeed.cfg
- libvirt/tests/src/migration/migration_cmd/setspeed_and_getspeed.py
VIRT-298170 - [migrate-s(g)etspeed] set/get migration bandwidth limit
> migration: Add case to test migrate-setspeed/getspeed

- libvirt/tests/cfg/virtual_disks/virtual_disks_cdrom_device.cfg
- libvirt/tests/src/virtual_disks/virtual_disks_cdrom_device.py
Add eject the hotplug cdrom media by change-media
xx-298368 - Hot-plug + Eject the media + Unplug an SCSI cdrom device BZ2160435
> Add eject the hotplug cdrom media by change-media

- libvirt/tests/cfg/migration/migration_cmd/setmaxdowntime_and_getmaxdowntime.cfg
- libvirt/tests/src/migration/migration_cmd/setmaxdowntime_and_getmaxdowntime.py
- spell.ignore
VIRT-298169 - [migrate-s(g)etmaxdowntime] set/get vm max downtime
> migration: Add case about setmaxdowntime/getmaxdowntime

- libvirt/tests/cfg/virtio/virtio_page_per_vq.cfg
- libvirt/tests/src/virtio/virtio_page_per_vq.py
Add libvirt version for the attribute page_per_vq of virtio.
> virtio_page_per_vq: add libvirt version

- libvirt/tests/cfg/guest_os_booting/boot_menu/bootmenu.cfg
- libvirt/tests/src/guest_os_booting/boot_menu/bootmenu.py
This PR automate:
VIRT-297117 - Boot vm with bootmenu
> guest_os_booting: add new case for guest bootmenu

- libvirt/tests/cfg/memory/memory_backing/page_locking_and_shared_pages.cfg
- libvirt/tests/src/memory/memory_backing/page_locking_and_shared_pages.py
VIRT-297169: Memory pagelocking and shared pages
Depend on 
- https://github.com/avocado-framework/avocado-vt/pull/3776
> add case for mem pagelock and shared pages cases

- libvirt/tests/src/numa/guest_numa_node_tuning/memory_binding_setting.py
test results on rhel8.9:
(01/12) type_specific.io-github-autotest-libvirt.guest_numa_node_tuning.memory_binding_setting.default_pagesize.mem_mode_strict.single_host_node: PASS (28.62 s)
(02/12) type_specific.io-github-autotest-libvirt.guest_numa_node_tuning.memory_binding_setting.default_pagesize.mem_mode_interleave.single_host_node: PASS (27.66 s)
(03/12) type_specific.io-github-autotest-libvirt.guest_numa_node_tuning.memory_binding_setting.default_pagesize.mem_mode_preferred.single_host_node: PASS (27.76 s)
(04/12) type_specific.io-github-autotest-libvirt.guest_numa_node_tuning.memory_binding_setting.default_pagesize.mem_mode_restrictive.single_host_node: PASS (27.72 s)
(05/12) type_specific.io-github-autotest-libvirt.guest_numa_node_tuning.memory_binding_setting.hugepage.mem_mode_strict …
> memory_binding_setting: Add cgroup v1 adaption for cpuset.mems

- libvirt/tests/cfg/virtual_disks/virtual_disks_io_tuning.cfg
- libvirt/tests/src/virtual_disks/virtual_disks_io_tuning.py
Automate disk io_uring attribute case
xx-298346: Start or hot-plug a disk with io=io_uring BZ1946936
>  Add disk io_uring attribute case

- libvirt/tests/cfg/migration/migration_performance_tuning/migration_precopy_bandwidth.cfg
- libvirt/tests/cfg/migration/migration_performance_tuning/migration_zerocopy.cfg
- libvirt/tests/cfg/migration/migration_resource_limit/migration_postcopy_bandwidth.cfg
- libvirt/tests/cfg/migration/migration_resource_limit/migration_precopy_and_postcopy_bandwidth.cfg
- libvirt/tests/cfg/migration/migration_uri/migration_network_data_transport_tls.cfg
- libvirt/tests/cfg/migration_with_copy_storage/network_data_transport/tls.cfg
- provider/migration/base_steps.py
VIRT-297895: VM live migration with copy storage - network data transport - TLS
> migration: Add vm live migration with copy storage case

- libvirt/tests/cfg/migration/migrate_vm_in_various_status/migrate_paused_vm.cfg
- libvirt/tests/src/migration/migrate_vm_in_various_status/migrate_paused_vm.py
VIRT-298232 - [VM migration] migrate paused vm
> migration: Add case to test paused vm

- libvirt/tests/cfg/migration_with_copy_storage/migrate_vm_disk_on_shared_storage.cfg
- libvirt/tests/src/migration_with_copy_storage/migrate_vm_disk_on_shared_storage.py
xxx - VM live migration with copy storage - migrate vm disk on shared storage
> migration: Add case about vm disk on shared storage

- v2v/tests/cfg/function_test_esx.cfg
Fix the unexpected variants setting in cfg file.
> v2v: fix cfg error

- libvirt/tests/cfg/storage/virsh_pool.cfg
- libvirt/tests/deps/cve_2023_3750.sh
- libvirt/tests/src/storage/virsh_pool.py
- provider/virtual_disk/disk_base.py
This is to test for CVE-2023-3750 using rbd pool.
> virsh_pool: add case with rbd pool

- libvirt/tests/cfg/guest_os_booting/os_configuration/without_default_os_attributes.cfg
- libvirt/tests/src/guest_os_booting/os_configuration/without_default_os_attributes.py
It mainly implements booting vm without default os attributes.
> guest_os_booting: add case booting guest without default attributes

- libvirt/tests/cfg/guest_os_booting/firmware_configuration/os_acpi.cfg
- libvirt/tests/src/guest_os_booting/firmware_configuration/os_acpi.py
This PR mainly automates the function of os acpi in guest.
> guest_os_booting: add new modular case for os acpi test

- libvirt/tests/cfg/daemon/conf_file/libvirtd_conf/virt_admin_logging.cfg
- libvirt/tests/src/daemon/conf_file/libvirtd_conf/virt_admin_logging.py
Add case to check virt-admin default log_outputs in various conditions
RHEL-xx  [libvirtd]Check default log_outputs in various conditions
> Add case to check virt-admin default log_outputs in various conditions

- libvirt/tests/cfg/migration/migration_xml_update.cfg
- libvirt/tests/src/migration/migration_xml_update.py
1. Test that changing the alias works
2. Test that changing the address fails gracefully
> Migrate update xml

- libvirt/tests/src/migration/migrate_options_shared.py
- libvirt/tests/src/migration/migration_performance_tuning/migration_zerocopy.py
Disable postcopy + multifd migration in qemu-kvm-8.1.0. So update
code.
> migration: Update postcopy and multifd case

- libvirt/tests/cfg/migration_with_copy_storage/disk_io_load_in_vm.cfg
- libvirt/tests/src/migration_with_copy_storage/disk_io_load_in_vm.py
XXX-298242 - VM live migration with copy storage - migrate vm with
heavy disk I/O load in vm
> migration: Add case about heavy disk I/O load in vm

- v2v/tests/cfg/v2v_options.cfg
Refer failed cases on v2v-options.
> v2v:modify esx65/67 related testing for v2v-options

- v2v/tests/cfg/convert_from_file.cfg
> v2v:modify esx65/67 related testing for convert-from-file

- libvirt/tests/cfg/migration_with_copy_storage/disk_type_coverage/block_disk.cfg
- libvirt/tests/src/migration_with_copy_storage/disk_type_coverage/block_disk.py
VM live migration with copy stoarge - disk type=block
> migration: Add case to test block disk

- libvirt/tests/cfg/migration_with_copy_storage/precreate_none_target_disk.cfg
- libvirt/tests/src/migration_with_copy_storage/precreate_none_target_disk.py
XXX-297908 - VM live migration with copy storage - don't pre-create target image manually
> migration: Add case about pre-create target image

- libvirt/tests/src/migration/migration_uri/tcp_migration_port_allocation_port_occupied_by_other_app.py
Run 'nc' command failed on remote host, so update code.
> migration: Fix 'nc' command failure

- v2v/tests/cfg/function_test_esx.cfg
> v2v:modify esx65/67 related testing for function-test-esx

- libvirt/tests/cfg/migration_with_copy_storage/migrate_disks.cfg
- libvirt/tests/src/migration_with_copy_storage/migrate_disks.py
XXX-297901 - VM live migration with copy storage - specify which
disks to migrate(-migrate-disks)
> migration: Add case about migrate-disk

- libvirt/tests/cfg/guest_os_booting/ovmf_firmware/ovmf_seclabel_in_nvram.cfg
- libvirt/tests/src/guest_os_booting/ovmf_firmware/ovmf_seclabel_in_nvram.py
This case is to verify the seclabel source in backed nvram: VIRT-299960
> guest_os_booting: new case of booting vm with seclabel in backed nvram

- libvirt/tests/cfg/guest_os_booting/boot_order/boot_from_virtiofs_device.cfg
- libvirt/tests/src/guest_os_booting/boot_order/boot_from_virtiofs_device.py
It mainly implements booting vm from virtiofs device.
> guest_os_booting: add new case of virtiofs device booting

- libvirt/tests/cfg/cpu/vcpu_affinity.cfg
Error message have changed but are still valid.
> vcpu_affinity: fix expected error

- libvirt/tests/src/virsh_cmd/domain/virsh_detach_device.py
Depends on https://github.com/avocado-framework/avocado-vt/pull/3815
The disk tests used the disk target as identifier for the disk inside of the VM. However, the target is not guaranteed to show up in the guest as-is, especially given that the /dev/XdY paths are not persistent and can change between boots.
> virsh_detach_device: fix device discovery

- libvirt/tests/cfg/guest_os_booting/firmware_configuration/smbios_mode.cfg
- libvirt/tests/src/guest_os_booting/firmware_configuration/smbios_mode.py
This case is to verify the smbios element.
> guest_os_booting: add new case of smbios feature

- libvirt/tests/cfg/migration_with_copy_storage/migration_bandwidth_limit.cfg
Wrong event in action_during_mig.
> migration: Fix wrong event

- libvirt/tests/cfg/migration/abort_precopy_migration/abort_by_domjobabort_on_target.cfg
- libvirt/tests/cfg/migration/async_job/abort_migration_with_wrong_api_flag.cfg
- libvirt/tests/src/migration/async_job/async_job.py
- provider/migration/migration_base.py
VIRT-298383 - [VM migration][domjobabort] abort migration job with wrong API flag
> migration: Add case about abort migration

- v2v/tests/cfg/function_test_esx.cfg
Incorrect boottype for this TC.
> v2v: fix 9.4 func testing

- libvirt/tests/src/virtual_network/passt/passt_negative_setting.py
The test assumed the existence of a specific interface on the host. Instead have the test create one for testing to make the test more host-independent.
> passt/negative_setting: create interface for testing

- libvirt/tests/src/cpu/vm_features.py
Start windows VM with hyper-v newly available features and check
qemu command line.
Case ID: xxx-294652
> vm_feature: add case for hyperv

- libvirt/tests/cfg/virtual_network/update_device/unsupported_live_update_add.cfg
- libvirt/tests/cfg/virtual_network/update_device/unsupported_live_update_alter.cfg
- libvirt/tests/cfg/virtual_network/update_device/unsupported_live_update_delete.cfg
- libvirt/tests/src/virtual_network/update_device/unsupported_live_update.py
- provider/virtual_network/network_base.py
- VIRT-298315 - [update-device] Live update unsupported live update attributes or elements - alter
- VIRT-298316 - [update-device] Live update unsupported live update attributes or elements - add optional setting
- VIRT-298317 - [update-device] Live update unsupported live update attributes or elements - delete the optional elements/attributes
> Add new cases of network: update-device

- libvirt/tests/src/memory/memory_allocation/define_value_unit.py
For memory balloon:
On 4k kernel guest, the memory will align up.
On 64k kernel guest, the memory will align down.
Before:
```
(1/1) type_specific.io-github-autotest-libvirt.memory.allocation.define_value_unit.without_numa.positive_test.bytes: FAIL: current_mem should be 1953152 instead of 1953088  (24.59 s)
```
After:
```
JOB ID     : c80ef49daf299dba66ff2f34c645d285ae484a96
JOB LOG    : /root/avocado/job-results/job-2024-01-22T04.19-c80ef49/job.log
(01/16) type_specific.io-github-autotest-libvirt.memory.allocation.define_value_unit.without_numa.positive_test.bytes: PASS (25.52 s)
(02/16) type_specific.io-github-autotest-libvirt.memory.allocation.define_value_unit.without_numa.positive_test.KB: PASS (26.50 s)
(03/16) type_specific.io-github-autotest-libvirt.memory.allocation.define_value_ …
```
> memory: Fix the expected memory size after balloon

- libvirt/tests/cfg/virtual_network/passt/passt_negative_setting.cfg
Update the error message pattern since it changes with new libvirt version.
> The error message changes with new libvirt version

- libvirt/tests/cfg/numa/guest_numa_node_tuning/auto_memory_placement_numad_fail.cfg
- libvirt/tests/src/numa/guest_numa_node_tuning/auto_memory_placement_numad_fail.py
- provider/numa/numa_base.py
This is to verify expected error message when numad service fails
Case ID: xxx-299204
> auto_memory_placement_numad_fail: add case

- libvirt/tests/cfg/memory/memory_allocation/lifecycle_with_memory_allocation.cfg
- libvirt/tests/cfg/memory/memory_balloon/guest_without_mem_balloon.cfg
- libvirt/tests/cfg/memory/memory_balloon/period_config_of_memory_balloon.cfg
No memory hotplug or NUMA on s390x. Disable these.
> memory: disable tests on s390x

- v2v/tests/cfg/convert_vm_to_libvirt.cfg
- v2v/tests/cfg/convert_vm_to_ovirt.cfg
- v2v/tests/cfg/function_test_xen.cfg
Reverts autotest/tp-libvirt#5396
> Revert "Rename main name in v2v jobs"

- libvirt/tests/src/virtual_disks/virtual_disks_filedescriptor.py
The test identified new disks by comparing the list of disks before and after plug. However, a reboot can mess up the non-persistent disk namings /dev/vdX.
> virtual_disks/file_descriptor: fix disk discovery

- libvirt/tests/cfg/numa/guest_numa.cfg
- libvirt/tests/src/numa/guest_numa.py
> guest_numa: fix incorrect cpu mode on arm

- libvirt/tests/src/virsh_cmd/domain/virsh_domdirtyrate_calc.py
The dirty rate under automated test is higher than expected. Also, the dirty rate might take some time to be firstly available and some more time to converge to the expected test value.
Use a wait_for loop over the output with a timeout instead.
> virsh_domdirtyrate_calc: Relax test conditions

- libvirt/tests/cfg/virtual_disks/virtual_disks_cdrom_device.cfg
- libvirt/tests/src/virtual_disks/virtual_disks_cdrom_device.py
Add hotplug empty source cdrom device
xx-300338: Succeed to attach a CDROM without source
> Add hotplug empty source cdrom device

- libvirt/tests/cfg/libvirt_mem.cfg
- libvirt/tests/src/libvirt_mem.py
> libvirt_mem: fix cpu mode on arm

- libvirt/tests/cfg/virtual_network/update_device/unsupported_live_update_delete.cfg
The error message changes for the negative scenario to update the mac address. Update the error message in the cfg file to match it.
> Fix the error message

- libvirt/tests/src/migration/migrate_over_unix.py
QEMU open more connection in postcopy. So update code.
> migration: Fix unix socket number issue

- libvirt/tests/src/virsh_cmd/domain/virsh_attach_detach_disk.py
The code compared old and new listing of impersistent disk names, e.g. 'vdX'. Those names can change between reboots.
Instead, use function to identify new disks that don't mount the root file system.
The function raises an error if there is no such disk, so handle that to confirm that disks are detached correctly.
> attach_detach_disk: fix disk discovery

- libvirt/tests/cfg/virtual_disks/virtual_disks_ccw_addr.cfg
can not use CCW address type for device on q35
> Filter CCW address cases on q35

- libvirt/tests/src/cpu/aarch64_cpu_sve.py
Some arm hardwares do not support sve512 and sve256. So we should handle this special condition.
> aarch64_cpu_sve: fix issues

- libvirt/tests/cfg/virtual_disks/virtual_disks_io_tuning.cfg
queue_size in driver is not supported
> Fix io_uring failure

- libvirt/tests/cfg/migration_with_copy_storage/network_data_transport/tcp_disks_uri.cfg
XXX-297892 - VM live migration with copy storage - network data transport - TCP - --disks-uri
> migration: Add case about disks-uri

- v2v/tests/cfg/convert_vm_to_libvirt.cfg
- v2v/tests/cfg/convert_vm_to_ovirt.cfg
- v2v/tests/cfg/function_test_esx.cfg
> v2v:delete esx6.0/6.5/6.7 from cfg files

- libvirt/tests/cfg/svirt/selinux/selinux_seclabel_per_device.cfg
SCLP serial doesn't support hotplug.
> seclabel/serial: disable unsupported hotplug scenario

- libvirt/tests/cfg/migration_with_copy_storage/network_data_transport/tcp_port_reuse.cfg
- libvirt/tests/src/migration_with_copy_storage/network_data_transport/tcp_port_reuse.py
Add scenario about --disks-port option.
> migration: Update port reuse case

- libvirt/tests/src/virtio/virtio_page_per_vq.py
1. It's not reasonable to start guest without disk device.
2. There are 2 input devices by default both starting the guest directly and hotplugging
> Fix issues with virtio_page_per_vq testcases

- libvirt/tests/cfg/guest_os_booting/boot_order/boot_from_usb_device.cfg
> boot_from_usb_device: correct file path

- libvirt/tests/cfg/migration/abort_precopy_migration/abort_by_domjobabort_on_target.cfg
- libvirt/tests/src/migration/abort_precopy_migration/abort_by_domjobabort_on_target.py
Add libvirt version check for 'domjobabort --postcopy' command.
> migartion: Add libvirt version check for domjobabort

- libvirt/tests/cfg/migration_with_copy_storage/network_data_transport/tcp_migrateuri_and_disks_port.cfg
- libvirt/tests/src/migration_with_copy_storage/network_data_transport/tcp_migrateuri_and_disks_port.py
XXX-297867 - VM live migration with copy storage - network data transport - TCP - --migrateuri & --disks-port
> migration: Add case about migrateuri and disks-port

- libvirt/tests/cfg/scsi/scsi_controller_driver_plug_unplug.cfg
- libvirt/tests/src/scsi/scsi_controller_driver_plug_unplug.py
test scenarios:
- test scsi controllers wi/o driver with plug and unplug operations
Case ID:
xxx-137060
> scsi_controller_driver_plug_unplug: add case

- libvirt/tests/cfg/numa/guest_numa_topology/numa_topology_with_hugepage.cfg
- libvirt/tests/src/numa/guest_numa_topology/numa_topology_with_hugepage.py
- provider/numa/numa_base.py
This is to enable hugepage test for ARM
- 64k: 512M and 2M
- 4k:  2M and 1G
> numa_topology_with_hugepage: fix hugepage for arm

- libvirt/tests/src/snapshot/revert_memory_only_snap.py
original pr is merged before fixed over, leaving some update
```
avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35  snapshot_revert.memory_only_snap
(1/1) type_specific.io-github-autotest-libvirt.snapshot_revert.memory_only_snap: PASS (68.33 s)
```
> snapshot case enhancement

- libvirt/tests/cfg/virtual_network/update_device/update_iface_trustGuestRxFilters.cfg
- libvirt/tests/src/virtual_network/update_device/update_iface_trustGuestRxFilters.py
- VIRT-300484 - [update-device][trustGuestRxFilters] update the trustGuestRxFilters by update-device
Test result:
```
(1/2) type_specific.io-github-autotest-libvirt.virtual_network.update_device.update_iface_trustGuestRxFilters.yes_to_no: PASS (60.57 s)
(2/2) type_specific.io-github-autotest-libvirt.virtual_network.update_device.update_iface_trustGuestRxFilters.no_to_yes:PAASS (54.87 s)
```
> Add network case of update-device:trustGuestRxFilters

- libvirt/tests/src/virsh_cmd/domain/virsh_save.py
> virsh_save: print out error message

- libvirt/tests/cfg/memory/secure_dump.cfg
- libvirt/tests/src/memory/secure_dump.py
- spell.ignore
Add test case that
1. Dumps the SE memory
2. Decrypts the memory
3. Does a minimal check on the decrypted content.
> memory/secure_dump: add test for s390x SE decryption

- v2v/tests/cfg/convert_vm_to_libvirt.cfg
- v2v/tests/cfg/convert_vm_to_ovirt.cfg
adjust guests for rhel9.5/10.0
> v2v: add guests for rhel9.5/10

- libvirt/tests/cfg/migration_with_copy_storage/autoskipped_disks.cfg
- libvirt/tests/src/migration_with_copy_storage/autoskipped_disks.py
XXXX-296262 - VM live migration with copy storage - auto-skipped disks
> migration: Add case to test auto-skipped disks

- libvirt/tests/src/virtual_network/iface_unprivileged.py
Sometimes the permissoin is not set successfully. Update it to ensure it is set correctly.
> Ensure the permission is set correctly

- libvirt/tests/cfg/migration_with_copy_storage/async_job/abort_job.cfg
- libvirt/tests/src/migration_with_copy_storage/async_job/abort_job.py
VIRT-297945 - VM live migration with copy storage - abort job(domjobabort) - on src host
> migration: Add case about abort job

- libvirt/tests/cfg/migration_with_copy_storage/target_image_larger_than_source.cfg
- libvirt/tests/src/migration_with_copy_storage/target_image_larger_than_source.py
XXX-300490 - VM live migration with copy storage - migrate a disk to an equal or larger disk size
> migration: Add case to test disk size

- libvirt/tests/cfg/migration_with_copy_storage/migration_with_vhostvdpa.cfg
- libvirt/tests/src/migration_with_copy_storage/migration_with_vhostvdpa.py
- spell.ignore
XXX-300493 - [vhostvdpa-blk] Migrate vm with disk of vhostvdpa backend
> migration: Add case about vhostvdpa

- provider/guest_os_booting/guest_os_booting_base.py
There may be many vms in env. For different types, update to take the 1st matching vm.
` (1/1) type_specific.io-github-autotest-libvirt.guest_os_booting.ovmf_nvram.positive_test.template_disable_secure: PASS (46.79 s)`
**LOGS:**
```
2024-05-15 06:11:56,901 utils            L0162 DEBUG|     vms = avocado-vt-vm1 vm2
... ... 
2024-05-15 06:12:01,310 guest_os_booting L0034 DEBUG| VMS: {'ovmf': 'avocado-vt-vm1'}
```
> guest_os_booting: Update to take the 1st matching vm

- libvirt/tests/src/guest_os_booting/boot_order/boot_from_cdrom_device.py
- libvirt/tests/src/guest_os_booting/ovmf_firmware/ovmf_loader.py
- libvirt/tests/src/guest_os_booting/ovmf_firmware/ovmf_nvram.py
> guest_os_booting: Skip smm and serial console to enable tests on arm

- libvirt/tests/cfg/migration_with_copy_storage/network_data_transport/tls.cfg
Add precopy/postcopy scenarios.
> migration: Update tls case

- provider/virtual_network/passt.py
- Check whether default gateway of vm is in the list of default gateway of host
- Use vm's default gateway which is unique instead of host's default gateway when checking connection
Depends on:
- https://github.com/avocado-framework/avocado-vt/pull/3915
Test result:
```
(1/1) type_specific.io-github-autotest-libvirt.virtual_network.passt.interface_function.minimal.root_user: STARTED
(1/1) type_specific.io-github-autotest-libvirt.virtual_network.passt.interface_function.minimal.root_user: PASS (268.17 s)
```
```
No python imaging …
```
> passt:support tests when host has multi-path default gateway

- libvirt/tests/cfg/virsh_cmd/domain/virsh_reboot.cfg
> virsh_reboot: disable acpi test on s390x

- libvirt/tests/src/migration/migrate_over_unix.py
The code used the target name to identify disks inside of the VM with their impersistent names (vda, vdb, ...). However, they might change between boots.
Instead use a function to identify new disks as not containing the system root partition.
> migrate_over_unix: fix disk selection

- libvirt/tests/src/virtual_device/filesystem_device_unprivileged.py
The function was moved to another module.
Also apply black to improve formatting.
> filesystem_device_unprivileged: fix wrong import

- v2v/tests/cfg/v2v_options.cfg
Please refer the case RHEL-134831.
> v2v: fix failed case in v2v-options

- libvirt/tests/src/virsh_cmd/domain/virsh_domif_setlink_getlink.py
the session cmd result of 'ip addr show dev' includes extra escape characters, use utils_net.get_linux_iface_info dict to get accurate 'operstate':'DOWN/UP' instead. Implement it in a new funciton: guest_ifstate_check(). And rename another link state function from guest_if_state() to guest_link_state()
> domif_setlink_getlink: get accurate ifstate in vm

- libvirt/tests/cfg/virtual_device/tpm_device.cfg
> tpm_device.cfg: update tpm1.2 error msg

- libvirt/tests/src/virtual_device/tpm_device.py
wget is not installed in guest by default on new product version, add it here.
> tpm_device: install wget in guest

- provider/virtual_network/network_base.py
Add a function to get ip address with ip --json to fix the issue
Test result:
PASS 1-type_specific.io-github-autotest-libvirt.virtual_network.connectivity_check.network_interface.nat
> Fixup:get vm ip address with unexpected characters

- libvirt/tests/src/virsh_cmd/network/virsh_net_dhcp_leases.py
Fix failures by getting accurate vm ip and install dhcp tool.
> net_dhcp_leases: get accurate vm ip, install dhcp

- libvirt/tests/src/virsh_cmd/network/virsh_net_update.py
Fix ping failures by getting accurate ip.
> net_update: get accurate ip

- libvirt/tests/src/virtual_disks/virtual_disks_ceph.py
Previously use qemu-img convert local system disk to ceph server, it is time costing,and sometime it takes more than 1 hour to finish converting operations. And it leads to ci job timeouts related to them
rbd tool provides one function: rbd import, which has stable and reliable uplink feature,so switch to use rbd import to upload system disk to ceph server
> Fix qemu-img convert system disk to ceph timeout issue

- v2v/tests/cfg/convert_vm_to_libvirt.cfg
- v2v/tests/cfg/convert_vm_to_ovirt.cfg
Adding 4 latest version 3rd-party guests.
> v2v: add latest 3rd-party guests in matrix

- libvirt/tests/src/cpu/vcpu_metrics.py
Don't remove the os loader attributes if vmx has acpi feature on aarch64.
Before:
```
(1/1) type_specific.io-github-autotest-libvirt.virsh.vcpu_metrics.normal_test.with_unprivileged_user: ERROR: Command 'su - domstats_testuser -c '/usr/bin/virsh define --file /tmp/domstats_unprivileged_user'' failed.\nstdout: b'\n'\nstderr: b'error: Failed to define domain from /tmp/domstats_unprivileged_user\nerror: unsupported configuration: ACPI requires UEFI on... (6.72 s)
```
After:
```
(1/1) type_specific.io-github-autotest-libvirt.virsh.vcpu_metrics.normal_test.with_unprivileged_user: PASS (8.52 s)
```
> cpu: fix ACPI requires UEFI on aarch64

- libvirt/tests/src/memory/memory_devices/change_virtio_mem_request_size.py
x86_64 test results:
(01/20) type_specific.io-github-autotest-libvirt.memory.devices.virtio_mem.change_memory.file.normal_requested.running_guest: PASS (196.25 s)
(02/20) type_specific.io-github-autotest-libvirt.memory.devices.virtio_mem.change_memory.file.zero_requested.running_guest: PASS (195.87 s)
(03/20) type_specific.io-github-autotest-libvirt.memory.devices.virtio_mem.change_memory.file.bigger_requested.running_guest: PASS (194.92 s)
(04/20) type_specific.io-github-autotest-libvirt.memory.devices.virtio_mem.change_memory.file.not_mutiple_of_block_requested.running_guest: PASS (198.58 s)
(05/20) type_specific.io-github-autotest-libvirt.memory.devices.virtio_mem.change_memory.hugepages.normal_requested.running_guest: PASS (195.96 s)
(06/20) …
> Wait for virtio-mem device memory to be allocated for guest

- libvirt/tests/src/migration/migrate_ceph.py
Previously it use qemu-img convert to upload system disk to ceph server, it is time cost. Instead here it use rbd import function,and it is much reliable and fast
> Fix migration ceph timeout issue

- libvirt/tests/cfg/graphics/graphics_functional.cfg
- libvirt/tests/src/graphics/graphics_functional.py
XXX-60228 - [vnc][ no listen type] Define a guest with no specified listen type for vnc graphic
> graphics: Add case to test no specified listen type for vnc graphic

- libvirt/tests/cfg/daemon/libvirtd/libvirtd.cfg
- libvirt/tests/src/daemon/libvirtd/libvirtd.py
XXXX-55237 - [libvirtd][config]Check the default value of max_anonymous_clients
> libvirtd: Add case to check max_anonymous_clients

- libvirt/tests/cfg/virtual_device/tpm_device.cfg
> tpm_device.cfg: update tpm1.2 errmsg again

- libvirt/tests/src/migration/migrate_options_shared.py
- libvirt/tests/src/virsh_cmd/domain/virsh_migrate_option_mix.py
Update to use run_stress_in_vm() to install stress package.
> migration: Update for stress

- libvirt/tests/cfg/virtual_network/passt/passt_negative_setting.cfg
Update the error message for passt negative scenarios since the error messages changes now.
> Update the error message match

- libvirt/tests/cfg/graphics/graphics_functional.cfg
- libvirt/tests/src/graphics/graphics_functional.py
XXX-103778 - [vnc] Start guest with fips disabled and with vnc password 
XXX-103777 - [vnc] Start guest with fips disabled and without vnc password
> graphics: Add two cases about disable fips

- provider/virtual_network/network_base.py
Test result:
```
PASS 1-type_specific.io-github-autotest-libvirt.virtual_network.connectivity_check.bridge_interface.linux_br.default
```
> network_base:Add timeout for get_vm_ip

- v2v/tests/cfg/convert_from_file.cfg
fix convert_from_file...vmx_default... failed cases.
> v2v: fix rhel10.0 failed func TCs of convert-from-file

- v2v/tests/cfg/function_test_esx.cfg
fix the failed cases of function-test-esx.
> v2v: fix rhel10.0 failed func TCs of function_test_esx

- v2v/tests/cfg/function_test_esx.cfg
Refer https://issues.redhat.com/browse/RHEL-50359
> v2v:fix fstab-comma TC

- libvirt/tests/src/memory/memory_devices/virtio_mem_dynamic_slots.py
test results:
(01/12) type_specific.io-github-autotest-libvirt.memory.devices.virtio_mem.dynamic_slots.default_mb.undefined_dynamic_memory_slots.basic_virtio: PASS (52.64 s)
(02/12) type_specific.io-github-autotest-libvirt.memory.devices.virtio_mem.dynamic_slots.default_mb.enable_dynamic_memory_slots.basic_virtio: PASS (53.86 s)
(03/12) type_specific.io-github-autotest-libvirt.memory.devices.virtio_mem.dynamic_slots.default_mb.disable_dynamic_memory_slots.basic_virtio: PASS (52.18 s)
(04/12) type_specific.io-github-autotest-libvirt.memory.devices.virtio_mem.dynamic_slots.file_mb.undefined_dynamic_memory_slots.basic_virtio: PASS (52.56 s)
(05/12) type_specific.io-github-autotest-libvirt.memory.devices.virtio_mem.dynamic_slots.file_mb.enable_dynamic_memory_slots.basic_virtio: PASS (52.89 s) …
> Wait for hot-plugged virtio-mem memory allocation

- provider/numa/numa_base.py
Add restriction for host numa node picking by minimum memory requirement
Test results:
(1/1) type_specific.io-github-autotest-libvirt.guest_numa_node_tuning.host_guest_mixed_memory_binding.memnode_mode_strict.mem_mode_strict.single_node: PASS (52.25 s)
(1/1) type_specific.io-github-autotest-libvirt.guest_numa_node_tuning.host_guest_mixed_memory_binding.memnode_mode_strict.no_mem_mode.no_node: PASS (50.51 s)
(1/1) type_specific.io-github-autotest-libvirt.guest_numa_node_tuning.host_guest_mixed_memory_binding.memnode_mode_interleave.mem_mode_restrictive.multiple_nodes: PASS (7.98 s)
> Optimize the host node memory checking function

- libvirt/tests/src/numa/numa_config_with_auto_placement.py
result:
(1/1) type_specific.io-github-autotest-libvirt.numa_config_with_auto_placement.memory_bind: PASS (66.11 s)
> Change cgroup check to avoid special charachter issue of cmd "systemd-cgls cpuset" output

- libvirt/tests/src/virtual_network/iface_network.py
The depending check_firewall_backend can not be approved. But new cases exist and not check rules anymore. Just skip but not fix.
> network: revert ip6 masquerade check by nft

- libvirt/tests/cfg/virtual_network/qos/check_actual_network_throughput.cfg
- libvirt/tests/src/virtual_network/qos/check_actual_network_throughput.py
- provider/virtual_network/network_base.py
- VIRT-296327 - [Qos] Check the actual network throughput per bandwidth settings in network/interface
> Add network case of qos

- libvirt/tests/src/virtual_device/filesystem_device.py
Bug RHEL-50329 had been fixed, we should update script accordingly.
> Update the command line of cache_mode

- provider/virtual_network/network_base.py
On our nested systems backed by a virtual NAT network it takes longer for the guest to get a reachable network.
The test was failing at the ping intent with
ping: connect: Network is unreachable
Instead, retry for up to 5 seconds to succeed.
> update_iface_link_state: wait for guest network reset

- libvirt/tests/cfg/virtual_disks/virtual_disks_discard_no_unref.cfg
- libvirt/tests/src/virtual_disks/virtual_disks_discard_no_unref.py
VIRT-301835 - [virtual_disk][discard_no_unref][negative] Update device for guest with discard_no_unref attribute
> Virtual_disk: add new negative case of discard_no_unref

- v2v/tests/cfg/convert_from_file.cfg
> v2v: fix rhel10 failed case of convt-from-file

- libvirt/tests/src/memory/memory_devices/lifecycle_for_file_backed_nvdimm_memory.py
we should check element value one by one
```
avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 memory.devices.file_nvdimm.lifecycle
(1/8) type_specific.io-github-autotest-libvirt.memory.devices.file_nvdimm.lifecycle.with_numa.addr_undefined.target_label.access_shared: PASS (227.87 s)
(2/8) type_specific.io-github-autotest-libvirt.memory.devices.file_nvdimm.lifecycle.with_numa.addr_undefined.target_label.access_private_alignsize: PASS (225.60 s)
(3/8) type_specific.io-github-autotest-libvirt.memory.devices.file_nvdimm.lifecycle.with_numa.addr_undefined.target_readonly.access_shared: PASS (208.04 s)
(4/8) type_specific.io-github-autotest-libvirt.memory.devices.file_nvdimm.lifecycle.with_numa.addr_undefined.target_readonly.access_ …
```
> fix checking nvdimm memory target issue

- v2v/tests/cfg/nbdkit/nbdkit.cfg
nbdkit1.38 new feature. Refer nbdkit1.38 rebase.
> v2v:add new case on vddk8.x support

- libvirt/tests/cfg/virtual_device/tpm_device.cfg
- libvirt/tests/src/virtual_device/tpm_device.py
Test tpm2_sign with different hash algorithms.
> tpm_device: add tpm2_sign test

- libvirt/tests/cfg/migration/guest_lifecycle_operations_during_migration/migration_poweroff_vm.cfg
- libvirt/tests/src/migration/guest_lifecycle_operations_during_migration/migration_poweroff_vm.py
Add a new attribute in test matrix part:
New attribute
NBD
non-NBD
> migration: Update migration_poweroff_vm case

- libvirt/tests/cfg/virtual_network/update_device/update_iface_portgroup.cfg
- libvirt/tests/src/virtual_network/update_device/update_iface_portgroup.py
- spell.ignore
- VIRT-294740 - [update-device][portgroup] Update interface portgroup for nat and bridge network(Qos)
> Add new case of update interface portgroup

- v2v/tests/cfg/convert_vm_to_libvirt.cfg
> v2v: fix shortID for rhel10.0

- libvirt/tests/cfg/migration/migration_misc/migration_with_host_uuid.cfg
- libvirt/tests/src/migration/migration_misc/migration_with_host_uuid.py
XXX-298377 - [VM migration] migrate vm between two hosts with same host_uuid
> migration: Add case to test host_uuid

- libvirt/tests/cfg/virtual_network/network/elements_and_attributes/network_static_route.cfg
- libvirt/tests/src/virtual_network/network/elements_and_attributes/network_static_route.py
Automate VIRT-298910 - [Static route] Start virtual networks with static route defined.
> auto VIRT-298910

- libvirt/tests/cfg/virtual_network/driver/rx_tx_queue_size.cfg
- libvirt/tests/src/virtual_network/driver/rx_tx_queue_size.py
- VIRT-296306 - [driver][rx_queue_size][tx_queue_size] start vm with rx_queue_size and tx_queue_size setting
> Add new network case of rx tx queue size

- v2v/tests/cfg/function_test_esx.cfg
> v2v: add new case on --mac

- libvirt/tests/src/numa/host_numa/host_numa_info.py
test results:
x86_64:
type_specific.io-github-autotest-libvirt.host_numa.numa_info.4k.all_hugepages: PASS (27.51 s)
aarch64:
type_specific.io-github-autotest-libvirt.host_numa.numa_info.64k.all_hugepages: PASS (11.86 s)
> Allow hugepage memory allocated on only one numa node

- libvirt/tests/cfg/graphics/graphics_functional.cfg
- libvirt/tests/src/graphics/graphics_functional.py
XXXX-62543 - [vnc] Query display URI of vnc that has password with/without --include-password
> graphics: Add case to check domdisplay output

- libvirt/tests/cfg/daemon/qemu_monitor_socket_creation_delay.cfg
- libvirt/tests/deps/qemu_wrapper.py
- libvirt/tests/src/daemon/qemu_monitor_socket_creation_delay.py
XXXX-37948 - [libvirtd] Start vm - with qemu monitor socket creation delay
> libvirtd: Add case to test qemu monitor socket

- libvirt/tests/cfg/virtual_network/iface_network.cfg
On s390x, select virtio model.
> iface_network: select iface model on s390x

- provider/save/save_base.py
Sometimes getting the wrong pid, but I haven't reproduced the issue, so update to log the output of ping command for further debugging.
> save_base: Update to log output of ping command

- libvirt/tests/src/memory/memory_devices/change_virtio_mem_request_size.py
Fix parameter matching issue, add % to format the string.
LGTM.Acked-by: Zhenyu Zhang <zhenyzha@redhat.com>
> change_virtio_mem_request_size:Fix parameter matching issue

- libvirt/tests/cfg/virtual_network/qos/check_actual_network_throughput_direct.cfg
- libvirt/tests/src/virtual_network/qos/check_actual_network_throughput_direct.py
- VIRT-296328 - [Qos] Check the actual network throughput for direct type interface
Test result:
```
PASS 1-type_specific.io-github-autotest-libvirt.virtual_network.qos.check_actual_network_throughput.direct.with_network
PASS 1-type_specific.io-github-autotest-libvirt.virtual_network.qos.check_actual_network_throughput.direct.without_network
```
> Add net work case of qos

- v2v/tests/cfg/specific_kvm.cfg
> v2v: add new case on ubuntu22.04 partial efi

- libvirt/tests/src/daemon/libvirtd/libvirtd.py
- libvirt/tests/src/graphics/graphics_functional.py
- libvirt/tests/src/virsh_cmd/volume/vol_concurrent.py
> Removed python2 imports

- libvirt/tests/cfg/migration/async_ops/migrate_vm_again_during_migration.cfg
- libvirt/tests/src/migration/async_ops/migrate_vm_again_during_migration.py
XXX-298375 - [VM migration][async ops] migrate vm again during migration
> migration: Add case to test migrate vm again

- libvirt/tests/cfg/virsh_cmd/domain/virsh_domfsinfo.cfg
Fix fs-freezed failure by refined error message
> Fix fs-freezed failure by refined error message

- libvirt/tests/cfg/bios/virsh_boot.cfg
- libvirt/tests/cfg/bios/virsh_boot_sysinfo.cfg
- libvirt/tests/cfg/bios/virsh_boot_tseg.cfg
No SeaBIOS on s390x, disable tests.
> virsh_boot: disable seabios on s390x

- libvirt/tests/src/daemon/conf_file/libvirtd_conf/virt_admin_logging.py
Fix virt-admin check log failure
Use utils_misc.wait_for to wait for expected message log
> Fix virt-admin check log failure

- libvirt/tests/cfg/virtual_network/passt/passt_attach_detach.cfg
- libvirt/tests/cfg/virtual_network/passt/passt_function.cfg
- libvirt/tests/cfg/virtual_network/passt/passt_lifecycle.cfg
- libvirt/tests/cfg/virtual_network/passt/passt_reconnect.cfg
Modify passt udp listen socket to a shared ipv4/ipv6 one according to:
https://passt.top/passt/commit/?id=e0be6bc2f4762ba8c090aef0f8b85a47a4243356
> Modify passt udp listen socket to a shared ipv4/ipv6 one

- libvirt/tests/src/virsh_cmd/monitor/virsh_domstats.py
xxxx-21749:domstats - get statistics about one or multiple or all domains
```
avocado run --vt-type libvirt --vt-omit-data-loss --vt-machine-type q35 virsh.domstats.normal_test.domain_state.running.option.vcpu.default_print.not_enforce.specific_domain
(1/1) type_specific.io-github-autotest-libvirt.virsh.domstats.normal_test.domain_state.running.option.vcpu.default_print.not_enforce.specific_domain: PASS (96.09 s)
```
Others
```
avocado run --vt-type libvirt --vt-omit-data-loss --vt-machine-type q35 virsh.domstats
303 cases  All PASS
```
> case update: virsh domstats with vcpu.x.wait_sum is  0

- v2v/tests/src/specific_kvm.py
To make ntpd work after rebooting. Adding "enable" line.
> v2v: fix ntpd related tcs

- libvirt/tests/src/virsh_cmd/domain/virsh_set_user_password.py
Fix guest agent get illegal character when getting ip address
Previously,it attempts to login guest and use command to get ipaddress, in some s390x guest, it may pop up some illegal characters while executing those commands, such as [35m192.168.122.21[0m'
Moreover, it need to restore to previous root password, otherwise it affect next case for login
> Fix guest agent get illegal character when getting ip address

- libvirt/tests/cfg/virsh_cmd/domain/virsh_managedsave.cfg
- libvirt/tests/src/virsh_cmd/domain/virsh_managedsave.py
Delete one case 'not_saved_with_file' as the bug
https://bugzilla.redhat.com/show_bug.cgi?id=1689809 is closed as won't fix, so it's not a valid test scenario. And update one parameter in the file.
> Fix managedsave cases about fake managed file

- libvirt/tests/cfg/migration/migration_with_virtiofs/migration_with_internally_launched_virtiofs_dev.cfg
- libvirt/tests/src/migration/migration_with_virtiofs/migration_with_internally_launched_virtiofs_dev.py
XXX-301966 - [virtiofs] Migrate guest with internally launched virtiofs device
> migration: Add case about internally launched virtiofs device

- libvirt/tests/cfg/migration/migrate_options_shared.cfg
No vTPM on s390x. Disable tests.
> migration: disable test with vtpm

- libvirt/tests/cfg/migration/non_live_migration/non_live_migration.cfg
- libvirt/tests/src/migration/non_live_migration/non_live_migration.py
XXX-298167 - [VM migration] non-live migration
> migration: Add non-live migration case

- libvirt/tests/cfg/migration/migrate_options_shared.cfg
- libvirt/tests/cfg/migration/migration_with_vtpm/migration_with_vtpm_dev.cfg
- libvirt/tests/src/migration/migration_with_vtpm/migration_with_external_tpm.py
- libvirt/tests/src/migration/migration_with_vtpm/migration_with_shared_tpm.py
- libvirt/tests/src/migration/migration_with_vtpm/migration_with_vtpm_dev.py
- provider/migration/base_steps.py
Update for following case:
XXX-177314 - Migrate[p2p/tunnelled/postcopy] a guest with vtpm device
> migration: Update vtpm device migration case

- libvirt/tests/src/memory/memory_misc.py
The cleanup step needs to check if the setup is finished successfully.
> memory_misc: fix cleanup error

- provider/sriov/sriov_base.py
This is introduced by c1b4841c82e99d69.
> sriov: Fix error format issue

- libvirt/tests/src/libvirt_hooks.py
According to RHEL-41168, update case.
> libvirt_hooks: update network hooks

- libvirt/tests/cfg/migration/migration_misc/qemu_err_incoming_migration.cfg
- libvirt/tests/src/migration/migration_misc/qemu_err_incoming_migration.py
XXX-298341 - [VM migration] qemu fails with incoming migration
> migration: Add test about qemu fails with incoming migration

- libvirt/tests/src/virtual_network/iface_bridge.py
Test result
(1/1) type_specific.local.virtual_network.iface_bridge.multiqueues.hotplug_device.shared_physical_network: STARTED
(1/1) type_specific.local.virtual_network.iface_bridge.multiqueues.hotplug_device.shared_physical_network: PASS (81.88 s)
> iface_bridge:Fix colored output if ip command

- libvirt/tests/src/numa/guest_numa.py
The Patch fixes almost 67 cases which were failing as Nn numa nodes available in the system.
The provided fix check for all the available numa nodes in the system and figures out which numa node has memory an cpus.
Even the system is having randome numa nodes configurations the fix works for all the manners and gets the list nodes which has memory and cpus.
> Get the proper numa nodes configuration from the system.

- libvirt/tests/src/numa/guest_numa.py
1. Fix undefine error of variable arch
2. Make sure enough huge page memory is allocated for specific host numa node
test results:
(01/67) type_specific.io-github-autotest-libvirt.guest_numa.possitive_test.no_hugepage.no_mem_backend.topology.no_numatune_memnode.numatune_mem: STARTED
(01/67) type_specific.io-github-autotest-libvirt.guest_numa.possitive_test.no_hugepage.no_mem_backend.topology.no_numatune_memnode.numatune_mem: PASS (49.75 s)
(02/67) type_specific.io-github-autotest-libvirt.guest_numa.possitive_test.no_hugepage.no_mem_backend.no_topo.no_numatune_memnode.numatune_mem: STARTED
(02/67) type_specific.io-github-autotest-libvirt.guest_numa.possitive_test.no_hugepage.no_mem_backend.no_topo.no_numatune_memnode.numatune_mem: PASS (51.75 s)
(03/67) …
> Fix two issues

- libvirt/tests/src/virtual_network/connectivity/connectivity_check_ethernet_interface.py
Depends on
- https://github.com/avocado-framework/avocado-vt/pull/4058
Test result:
```
(01/11) type_specific.local.virtual_network.connectivity_check.ethernet_interface.managed_no.positive_test.tap.one_iface.no_mtu.non_root_user: STARTED
(01/11) type_specific.local.virtual_network.connectivity_check.ethernet_interface.managed_no.positive_test.tap.one_iface.no_mtu.non_root_user: PASS (78.43 s)
(02/11) type_specific.local.virtual_network.connectivity_check.ethernet_interface.managed_no.positive_test.tap.one_iface.larger_mtu.non_root_user: STARTED
(02/11) type_specific.local.virtual_network.connectivity_check.ethernet_interface.managed_no.positive_test.tap.one_iface.larger_mtu.non_root_user: PASS (67.34 s)
(03/11) type_specific.local.virtual_network.connectivity_check.ethernet_interface.mana …
```
> ethernet interface: Update iface xml instead of create new one

- v2v/tests/cfg/specific_kvm.cfg
delete duplicate test case with function_test_esx..external_poweroff
> v2v: delete duplicate test case with function_test_esx..external_poweroff

- libvirt/tests/cfg/save_and_restore/restore_from_local_file.cfg
- libvirt/tests/cfg/save_and_restore/save_with_options.cfg
- libvirt/tests/src/save_and_restore/restore_from_local_file.py
- libvirt/tests/src/save_and_restore/save_to_block.py
- libvirt/tests/src/save_and_restore/save_to_nfs.py
- libvirt/tests/src/save_and_restore/save_with_formats.py
- libvirt/tests/src/save_and_restore/save_with_options.py
Remove workaround added by Commit 5c125c2
> save_and_restore:Remove workaound

- libvirt/tests/cfg/virtio_transitional/virtio_transitional_rng.cfg
- libvirt/tests/src/virtio_transitional/virtio_transitional_rng.py
On s390x, pci bridge is not available. Don't attach this.
> transitional_rng: don't attach incompatible controller

- libvirt/tests/cfg/virsh_cmd/network/virsh_net_update.cfg
Updating dns-txt and dns-host of network is supported now
> virsh_net_update:Remove negative cases of update dns-txt dns-host

- libvirt/tests/src/virsh_cmd/domain/virsh_restore.py
> virsh_restore: fix eval error

- libvirt/tests/cfg/migration/async_ops/query_info_during_migration.cfg
- libvirt/tests/src/migration/async_ops/query_info_during_migration.py
- provider/migration/migration_base.py
XXX-298247 - [VM migration][async ops] Query domain information during migration
> migration: Add test about query info during migration

- libvirt/tests/cfg/incremental_backup/incremental_backup_backing_chain.cfg
- libvirt/tests/cfg/incremental_backup/incremental_backup_checkpoint_cmd.cfg
- libvirt/tests/cfg/incremental_backup/incremental_backup_event_monitor.cfg
- libvirt/tests/cfg/incremental_backup/incremental_backup_multidisk.cfg
- libvirt/tests/src/incremental_backup/incremental_backup_backing_chain.py
- libvirt/tests/src/incremental_backup/incremental_backup_checkpoint_cmd.py
- libvirt/tests/src/incremental_backup/incremental_backup_event_monitor.py
- libvirt/tests/src/incremental_backup/incremental_backup_multidisk.py
A new feature data file has been introduced with datastore element. It's important for incremental backup feature. So add this scenario to the scripts.
> Inc_backup: add datastore related test scenarios

- libvirt/tests/cfg/backingchain/with_disk_attributes_test/commit_pull_with_disk_source_attributes.cfg
- libvirt/tests/src/backingchain/with_disk_attributes_test/commit_pull_with_disk_source_attributes.py
Automate case:
VIRT-303303 - Do blockcommit/blockpull with different attributes of source elements
> Backingchain: add 1 new case about datastore element

- libvirt/tests/src/virtio/virtio_page_per_vq.py
> virtio_page_per_vq: fix var reference

- provider/virtual_network/network_base.py
Test result
(1/1) type_specific.local.virtual_network.connectivity_check.bridge_interface.linux_br.default: STARTED
(1/1) type_specific.local.virtual_network.connectivity_check.bridge_interface.linux_br.default: PASS (80.14 s)
> ping_check:Update code to report failures after all checks finish

- libvirt/tests/cfg/virtual_disks/virtual_disks_iothreads_queue.cfg
- libvirt/tests/src/virtual_disks/virtual_disks_iothreads_queue.py
VIRT-300421 - [Virtual disk][Per-virtqueue iothread] Live update disk with //disk/driver/iothreads
> Add test cases for live updating iothread_vq_mapping

- libvirt/tests/src/numa/guest_numa_node_tuning/numa_mem_binding_with_offline_cpu.py
- libvirt/tests/src/numa/guest_numa_topology/change_vcpu_pin.py
- libvirt/tests/src/numa/guest_numa_topology/various_numa_topology_settings.py
- libvirt/tests/src/numa/host_numa/host_numa_info.py
> various_numa_topology_settings: fix var check

- libvirt/tests/src/numa/numa_config_with_auto_placement.py
According to VIRT-91370,
the cpu affinity checking for iothreadinfo command is using host numa node id instead of iothreadid. This is incorrect. Like below, we should use iothread id instead numa node id.
```
IOThread ID     CPU Affinity
---------------------------------------------------
1               0-23
2               0-23
```
> numa_config_with_auto_placement: fix iothreadinfo check

- libvirt/tests/cfg/virsh_cmd/domain/virsh_detach_device_alias.cfg
- libvirt/tests/src/virsh_cmd/domain/virsh_detach_device_alias.py
Resolved script failures caused by recent changes in usbredirection command syntax. Rewritted method "start_usbredirserver" to maintain compatibility with both new and old usbredir command formats.
> hot-plug/unplug: update usbredirct commands to resolve issues

- libvirt/tests/cfg/virtual_disks/virtual_disks_iothreads_queue.cfg
According to the libvirt code changes, let's update the error messages.
> virtual_disks_iothreads_queue: update err message

- v2v/tests/cfg/convert_vm_to_libvirt.cfg
- v2v/tests/cfg/convert_vm_to_ovirt.cfg
> v2v:add 10.0 to latest10

- libvirt/tests/cfg/virtual_disks/virtual_disks_ssh.cfg
- libvirt/tests/src/virtual_disks/virtual_disks_ssh.py
- provider/virtual_disk/disk_base.py
Automate case:
VIRT-304003 - Start guest and hotplug/unplug ssh network disk
> Virtual_disk: add new case about ssh network disk

- libvirt/tests/cfg/migration_with_copy_storage/migration_bandwidth_limit.cfg
According to bug RHEL-7042, update case.
> migration: Update migration_bandwidth_limit case

- libvirt/tests/src/virtual_network/attach_detach_device/attach_mtu_malformed.py
- libvirt/tests/src/virtual_network/connectivity/connectivity_check_bridge_interface.py
- libvirt/tests/src/virtual_network/connectivity/connectivity_check_bridge_interface_unprivileged.py
- libvirt/tests/src/virtual_network/connectivity/connectivity_check_direct_interface.py
- libvirt/tests/src/virtual_network/connectivity/connectivity_check_ethernet_interface.py
- libvirt/tests/src/virtual_network/connectivity/connectivity_check_user_interface.py
- libvirt/tests/src/virtual_network/elements_and_attributes/attribute_port_isolated.py
- libvirt/tests/src/virtual_network/elements_and_attributes/element_coalesce.py
- libvirt/tests/src/virtual_network/iface_bridge.py
- libvirt/tests/src/virtual_network/iface_stat.py
- libvirt/tests/src/virtual_network/link_state/link_state_model_type.py
- libvirt/tests/src/virtual_network/network/net_update_dns.py
- libvirt/tests/src/virtual_network/passt/passt_attach_detach.py
- libvirt/tests/src/virtual_network/passt/passt_connectivity_between_2vms.py
- libvirt/tests/src/virtual_network/passt/passt_function.py
- libvirt/tests/src/virtual_network/passt/passt_negative_setting.py
- libvirt/tests/src/virtual_network/passt/passt_reconnect.py
- libvirt/tests/src/virtual_network/passt/passt_transfer_file.py
- libvirt/tests/src/virtual_network/qos/check_actual_network_throughput_direct.py
- libvirt/tests/src/virtual_network/qos/check_bandwidth_by_domiftune.py
- libvirt/tests/src/virtual_network/update_device/update_device_coalesce.py
- libvirt/tests/src/virtual_network/update_device/update_iface_link_state.py
- libvirt/tests/src/virtual_network/update_device/update_iface_qos.py
- libvirt/tests/src/virtual_network/update_device/update_iface_source.py
- libvirt/tests/src/virtual_network/update_device/update_iface_trustGuestRxFilters.py
- libvirt/tests/src/virtual_network/update_device/update_iface_type_live.py
- libvirt/tests/src/virtual_network/update_device/update_port_isolated.py
- provider/virtual_network/passt.py
Depends on
- https://github.com/avocado-framework/avocado-vt/pull/4082
> Update code to get host_iface

- libvirt/tests/cfg/scsi/scsi_disk_attributes.cfg
- libvirt/tests/src/scsi/scsi_disk_attributes.py
Automate case:
VIRT-302169 - [virtual disks] [SCSI]Start vm with block lun disk(scsi-block) and rawio attribute
> Scsi_device: automate 1 new case for rawio attribute

- libvirt/tests/src/virtiofs/virtiofs.py
Sometimes the mount command or other commmands would time out. In this case, log some information about the processes and retry. If the retry worked we still raise a test error because we expect it on the first try and want to inspect the logged information.
> filesystem_device: add data collection on failing virtiofs usage

- libvirt/tests/cfg/virtual_network/domifaddr.cfg
- libvirt/tests/src/virtual_network/domifaddr.py
- VIRT-299270 - [domifaddr] domifaddr for bridge and network type interface
Test result:
(1/1) type_specific.local.virtual_network.domifaddr.default: STARTED
(1/1) type_specific.local.virtual_network.domifaddr.default: PASS (58.43 s)
> Add new case of virsh domifaddr

- libvirt/tests/src/virsh_cmd/domain/virsh_migrate.py
There were in tests based on virsh_migrate.py not sufficient error message passed to user. 
(e.g.) virsh.migrate.there_and_back.normal_test.without_cpu_hotplug.compat_migration.non_compat_migration.with_postcopy
This commit just pass more information. 
Previous result:
Migration finished with unexpected status.
New info (based on do_migration error message): e.g.
Migration finished with unexpected status Migration failed for avocado-vt-vm1, with stderr: error: operation failed: job 'migration in' failed: load of migration failed: Invalid argument.
> Adding more information to failure message.

- libvirt/tests/cfg/migration/destructive_operations_around_live_migration/kill_virtiofsd_during_performphase.cfg
- libvirt/tests/src/migration/destructive_operations_around_live_migration/kill_virtiofsd_during_performphase.py
Add test for killing virtiofsd during migration perform phase with external virtiofsd
> migration/destructive_operations: kill virtiofsd on source

- libvirt/tests/cfg/incremental_backup/incremental_backup_checkpoint_cmd.cfg
- libvirt/tests/src/incremental_backup/incremental_backup_checkpoint_cmd.py
Automate case:
RHEL-187684 - test 'checkpoint-edit'
> Inc_backup: automate 1 checkpoint-edit backlog case

- libvirt/tests/cfg/virsh_cmd/host/virsh_hypervisor_cpu_models.cfg
- libvirt/tests/src/virsh_cmd/host/virsh_hypervisor_cpu_models.py
Depends on https://github.com/avocado-framework/avocado-vt/pull/4127
New command added in libvirt 11.2.0.
> hypervisor_cpu_models: add test for new command

- libvirt/tests/cfg/migration/migration_with_vtpm/migration_with_external_tpm.cfg
- libvirt/tests/src/migration/migration_with_vtpm/migration_with_external_tpm.py
Running chcon on a read-only system will fail. So update case.
> migration: Update external tpm case

- libvirt/tests/cfg/migration_with_copy_storage/migration_retain_sparsity.cfg
- libvirt/tests/src/migration_with_copy_storage/migration_retain_sparsity.py
According to RHEL-88435, update script.
> migration: Update retain sparsity case

- libvirt/tests/cfg/incremental_backup/incremental_backup_push_mode.cfg
- libvirt/tests/src/incremental_backup/incremental_backup_push_mode.py
Automate case:
RHEL-189084 - [incremental_backup] push mode full backup and incremental backup for a READONLY disk
> Inc_backup: automate one case which is related to readonly disk

- libvirt/tests/cfg/migration_with_copy_storage/migration_bandwidth_limit.cfg
Wait 3 seconds before verifying the bandwidth to make sure it takes effect.
> migration: Sleep to wait bandwidth change

- libvirt/tests/cfg/memory/memory_backing/hugepage_mount_path.cfg
- libvirt/tests/cfg/memory/memory_devices/virtio_mem_with_memory_backing_type.cfg
- libvirt/tests/src/memory/memory_backing/hugepage_mount_path.py
- libvirt/tests/src/memory/memory_devices/virtio_mem_with_memory_backing_type.py
Update according to
https://github.com/avocado-framework/avocado-vt/pull/4153
> Update parameter name in batch

- libvirt/tests/cfg/migration/async_ops/destroy_vm_during_performphase.cfg
- libvirt/tests/cfg/migration/async_ops/pause_resume_vm_during_migration.cfg
- libvirt/tests/cfg/migration/destructive_operations_around_live_migration/kill_qemu_during_performphase.cfg
- libvirt/tests/cfg/migration/destructive_operations_around_live_migration/migration_kill_libvirt_daemon.cfg
- libvirt/tests/cfg/migration/live_migration.cfg
- libvirt/tests/cfg/migration/memory_copy_mode/precopy.cfg
- libvirt/tests/cfg/migration/migrate_service_control.cfg
- libvirt/tests/cfg/migration/migrate_vm_in_various_status/migrate_paused_vm.cfg
- libvirt/tests/cfg/migration/migration_performance_tuning/migration_precopy_bandwidth.cfg
- libvirt/tests/cfg/migration/migration_performance_tuning/migration_timeout_action.cfg
- libvirt/tests/cfg/migration/migration_performance_tuning/migration_zerocopy.cfg
- libvirt/tests/cfg/migration/migration_performance_tuning/migration_zerocopy_abort.cfg
- libvirt/tests/cfg/migration/migration_resource_limit/migration_postcopy_bandwidth.cfg
- libvirt/tests/cfg/migration/migration_resource_limit/migration_precopy_and_postcopy_bandwidth.cfg
- libvirt/tests/cfg/migration/migration_uri/migration_network_data_transport_tcp.cfg
- libvirt/tests/cfg/migration/migration_uri/migration_network_data_transport_tcp_listen_address.cfg
- libvirt/tests/cfg/migration/migration_uri/migration_network_data_transport_tcp_migrateuri.cfg
- libvirt/tests/cfg/migration/migration_uri/migration_network_data_transport_tls.cfg
- libvirt/tests/cfg/migration/migration_uri/migration_network_data_transport_tunnelled.cfg
- libvirt/tests/cfg/migration/migration_uri/migration_network_data_transport_unix_proxy.cfg
- libvirt/tests/cfg/migration/pause_postcopy_migration_and_recover/pause_and_disruptive_and_recover.cfg
- libvirt/tests/cfg/migration/pause_postcopy_migration_and_recover/pause_and_io_error_and_recover.cfg
- libvirt/tests/cfg/migration/pause_postcopy_migration_and_recover/pause_and_recover_and_disruptive.cfg
- libvirt/tests/cfg/migration/pause_postcopy_migration_and_recover/pause_and_recover_twice.cfg
- libvirt/tests/cfg/migration/pause_postcopy_migration_and_recover/pause_by_domjobabort_and_recover.cfg
- libvirt/tests/cfg/migration/pause_postcopy_migration_and_recover/pause_by_network_and_recover.cfg
- libvirt/tests/cfg/migration/pause_postcopy_migration_and_recover/pause_by_proxy_and_recover.cfg
- libvirt/tests/cfg/migration/pause_postcopy_migration_and_recover/unattended_migration.cfg
- libvirt/tests/cfg/migration/pause_postcopy_migration_and_recover/unattended_migration_and_disruptive.cfg
- libvirt/tests/cfg/virsh_cmd/domain/virsh_migrate.cfg
Reverts autotest/tp-libvirt#6431
> Revert "migration_postcopy_bandwidth: fix bandwidth"

- libvirt/tests/cfg/memory/memory_balloon/various_mem_balloons.cfg
- libvirt/tests/src/memory/memory_balloon/various_mem_balloons.py
- provider/virsh_cmd_check/virsh_cmd_check_base.py
Test cases for memory ballooning functionality 
It validates 
- correct configuration for memballoon model in (virtio, virtio-non-transitional, none)
- dynamic memory adjustments,
- lifecycle operations: save, restore
- kill -SIGSTOP & SIGCONT for qemu-kvm
configured for memballoon models: virtio,  virtio-non-transitional, none
> Various memballoons models testing

- libvirt/tests/cfg/incremental_backup/incremental_backup_pull_mode_info.cfg
- libvirt/tests/src/incremental_backup/incremental_backup_pull_mode_info.py
Automate cases:
RHEL-288058 Get scratch's usage info during pull mode backup 
RHEL-284573 Get domblkinfo during pull mode backup
> Inc_backup: add 2 test cases related to info check

- libvirt/tests/cfg/scsi/scsi_controller_driver_plug_unplug.cfg
- libvirt/tests/src/scsi/scsi_controller_driver_plug_unplug.py
Automate new test scnearios in case:
RHEL-137060 - Attach/detach SCSI controller with driver configured should be supported
> Scsi_device: add new queues test to scsi controller

- libvirt/tests/src/daemon/libvirtd/libvirtd.py
Addressed edge cases that caused the older libvirt version to not be found correctly.
**Issues**
1. `\s+(\d+.*\d+)\s+\w+` will also match "Last metadata expiration check: 1:11:34 ago on Thu 15 May 2025 03:16:53 PM EDT." if included in the `dnf list libvirt --showduplicates --available` output. The new regex - `\s+(\d+[^:\s]*\.[^:\s]*\d+)\s+` - will now ensure that between the digits, there may be any characters except a white space character or a `:`. To ensure that simple numbers are not also matched (ex: 2025), also ensured that at least 1 `.` is included (as found in versions).
2. checking if `one_version < installed_version` works in most cases, but not all. For example, if the `installed_version` is "10.10.0-10" but the `one_version` is either "10.10.0-8" or "10.9.0-10", then …
> libvirtd: ensure older libvirt version is correctly found

- libvirt/tests/cfg/save_and_restore/save_image_edit.cfg
- libvirt/tests/src/save_and_restore/save_image_edit.py
This is to automate VIRT-297826.
> Test the virsh command save-image-edit

- libvirt/tests/cfg/migration/migration_misc/qemu_err_incoming_migration.cfg
- libvirt/tests/src/migration/migration_misc/qemu_err_incoming_migration.py
> qemu_err_incoming_migration: fix incorrect hugepage size for arm

- v2v/tests/src/nbdkit/nbdkit.py
Parameterize the file path, so it should not failed by not finding some file
> fix test case cve_starttls

- libvirt/tests/src/sriov/plug_unplug/sriov_attach_detach_device_vfio_variant_driver.py
It was introduced by 15d60aac8249c98.
> sriov: Fix interface's driver setting issue

- libvirt/tests/cfg/incremental_backup/incremental_backup_pull_mode.cfg
- libvirt/tests/src/incremental_backup/incremental_backup_pull_mode.py
Automate case:
RHEL-189085 - [incremental_backup] pull mode full and incremental backup for a READONLY-disk
> Inc_backup: automate new pull mode related readonly cases

- libvirt/tests/cfg/virtual_network/passt/passt_function.cfg
- libvirt/tests/src/virtual_network/passt/passt_function.py
Cover the bug https://issues.redhat.com/browse/RHEL-80533
> passt_function: Add virtqemud warning check for vhostuser

- libvirt/tests/cfg/incremental_backup/incremental_backup_fd_transport.cfg
- libvirt/tests/deps/inc_backup_fdtest_socket.py
- libvirt/tests/src/incremental_backup/incremental_backup_fd_transport.py
Automate new case:
VIRT-304602 - [incremental_backup] pull mode incremental backup from local image with fd transport nbd service
> Inc_backup: add new case for fd group pull mode

- libvirt/tests/src/save_and_restore/save_with_formats.py
Update the directory path to save the vm to avoid the selinux AVC deny issue.
> Update the directory path to save the vm

- libvirt/tests/src/virsh_cmd/domain/virsh_attach_device.py
Pipes have connection state, so qemu can become blocking when they are not read from because it doesn't buffer much. We have seen test cases failing because the guest's boot sequence got stuck when rd.debug was enabled during boot. This is expected behavior.
By reading from the pipe we make sure the guest can boot well.
> virsh_attach_device: fix serial pipe device
