autotest/tp-libvirt

libvirt/tests/cfg/virtual_network/iface_options.cfg
driver_page_per_vq as one network driver attribute is purposedly for  vdpa device
and it is still not supported on s390-virtio,
therefore Vm with this network setting fail to launch with below error:
Property 'virtio-net-ccw.page-per-vq' not found
=> driver_page_per_vq as one network driver attribute is not supported on s390-virtio

libvirt/tests/cfg/virtual_network/network_misc.cfg
Filter acpi network feature cases on s390x
virsh capabilities |grep acpi show acpi is not supported feature on s390x
so those related cases needed to be filter out in s390x
=> Filter acpi network feature cases on s390x

libvirt/tests/src/virtual_disks/at_dt_iscsi_disk.py
Fix utils_misc.wait_for(get_vol) immediate return issue if get_vol() return None firstly
utils_misc.wait_for(get_vol()) is used to get volume information until timeout is met or correctly returned
In terms of utils_misc.wait_for(), first parameter should not be None, otherwise
one error "NoneType' object is not callable" wil be thrown out, and the loop for that will be terminated 
=> Fix utils_misc.wait_for(get_vol) immediate return issue if get_vol() return None firstly

virttools/tests/src/virt_install/hostdev_mdev.py
Since v4.0.0 virt_install requires --osinfo in most cases, so
the test failed since that version. https://github.com/virt-manager/virt-manager/releases/tag/v4.0.0
Add commandline arguments to set previous behavior.
I confirmed this works with v3.2.0, too.
=> virt_install.hostdev: set required --osinfo value

libvirt/tests/cfg/memory/memory_misc.cfg
A) On s390x, there's no NUMA support; disable the test cases.
B) Per default, hugepage support might not be enabled; set
config option to enable it.
=> memory_misc: Fix some cases on s390x

libvirt/tests/cfg/virsh_cmd/domain/virsh_detach_device_alias.cfg
1. Hotunplug of watchdog device not supported on s390x:
FAIL: error: Failed to detach device with alias
ua-50972fe1-44e0-48f8-9d34-416eb879d2a7\nerror: Operation not supported:
hot unplug of watchdog of model diag288 is not supported\n (29.81 s)
2. Fix the watchdog model for s390x, it's diag288.
=> virsh_detach_device_alias: fix for s390x

libvirt/tests/cfg/backingchain/blockcommit/blockcommit_with_keep_overlay.cfg, libvirt/tests/src/backingchain/blockcommit/blockcommit_with_keep_overlay.py
VIRT-294061: Do blockcommit with --keep-overlay option
```
/usr/local/bin/avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 backingchain.blockcommit.keep_overlay
(1/2) backingchain.blockcommit.keep_overlay.positive_test.active: PASS (34.04 s)
(2/2) backingchain.blockcommit.keep_overlay.negative_test.inactive: PASS (52.97 s)
```
=> add case for blockcommit with keep overlay

libvirt/tests/src/virsh_cmd/domain/virsh_migrate.py, libvirt/tests/src/virsh_cmd/domain/virsh_migrate_copy_storage.py, libvirt/tests/src/virsh_cmd/domain/virsh_migrate_option_mix.py, libvirt/tests/src/virsh_cmd/domain/virsh_migrate_setmaxdowntime.py, libvirt/tests/src/virsh_cmd/domain/virsh_migration.py
Add '--nvram' option to avoid 'cannot undefine domain with nvram' error.
```
Before the fix: After 'migrate_option_mix.persistent.no_persistent_xml.no_xml.no_dname.no_undefinesource.src_vm_running.src_vm_transient.graphic_passwd.p2p.precopy.live' is executed, the test VM(avocado-vt-vm1) is not deleted on the target machine: 
Id   Name                    State
----------------------------------------
-    avocado-vt-remote-vm1   shut off
-    avocado-vt-vm1          shut off
After the fix: The VM is deleted.
Id   Name                    State
----------------------------------------
-    avocado-vt-remote-vm1   shut off
```
=> migration: Fix undefine with nvram

libvirt/tests/src/virsh_cmd/domain/virsh_attach_device_matrix.py
Fix no such file or directory error when virsh.detach disk xml
In some occasional cases where detach disk device, cases failed with avocado.core.exceptions.TestFail:
error: Failed to open file '/tmp/xml_utils_temp_cy0umt53.xml': No such file or directory
So by copying original xml file into another backup file, and then do detach operation using copied file
=> Fix no such file or directory error when virsh.detach disk xml

libvirt/tests/src/virtual_disks/virtual_disks_nbd.py
Fix nbd server is not completely started
In some extreme case, disk device may be consumed just after start nbd server
But at this time, nbd server may be not ready
Here use utils_misc.wait_for to allow ndb server more robust for readiness
=> Fix nbd server is not completely started

provider/backingchain/blockcommand_base.py
for reuse type snap, snap file should not be cleaned
```
avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 backingchain.blockcopy.blockcopy_with_backingfile.shallow_and_reuse_external.block_disk.pivot_after_blockcopy --vt-connect-uri qemu:///system
(1/1) type_specific.io-github-autotest-libvirt.backingchain.blockcopy.blockcopy_with_backingfile.shallow_and_reuse_external.block_disk.pivot_after_blockcopy: PASS (214.67 s)
avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 backingchain.blockcommit.all_block_chain.shallow_active --vt-connect-uri qemu:///system
(1/1) type_specific.io-github-autotest-libvirt.backingchain.blockcommit.all_block_chain.shallow_active: PASS (212.73 s)
```
=> fix remove incorrect snap file

libvirt/tests/src/virtual_network/iface_options.py
There is an additional swtpm process which has the guest's name.
So the cmd can not get the correct guest pid anymore, update the
cmd to be more accurate.
=> Fix wrong guest pid

libvirt/tests/cfg/migration/migrate_options_shared.cfg, libvirt/tests/cfg/migration/migrate_service_control.cfg
The error messages are changed for some cases.
` (1/1) type_specific.io-github-autotest-libvirt.virsh.migrate_options_shared.negative_test.p2p_migration.native_tls.tls_destination.without_option.without_postcopy: FAIL: Can not find the expected patterns 'error: internal error: qemu unexpectedly closed the monitor' in output 'error: Domain not found: no domain with matching uuid '045d1838-0204-41ab-936e-e77d1e5c3f94' (avocado-vt-vm1)' (193.68 s)
`
After the fix:
```
(1/1) type_specific.io-github-autotest-libvirt.virsh.migrate_options_shared.negative_test.p2p_migration.kill_qemu_target.with_postcopy: PASS (146.83 s)
(1/1) type_specific.io-github-autotest-libvirt.virsh.migrate_options_shared.negative_test.p2p_migration.native_tls. …
```
=> migration: Update the error messages

v2v/tests/cfg/v2v_options.cfg, v2v/tests/src/function_test_esx.py, v2v/tests/src/function_test_xen.py
1) replace '-oo compressed' with '--compressed' to compatible with
RHEL8.
2) update the hypervisor to 'kvm' in params.
3) skip log check on RHEL8.7
=> v2v: fix some errors for RHEL8.7

libvirt/tests/cfg/virtual_interface/interface_update_device_negative.cfg, libvirt/tests/cfg/virtual_network/address/virtual_network_address_tftp.cfg, libvirt/tests/src/virtual_interface/interface_update_device_negative.py, libvirt/tests/src/virtual_network/address/virtual_network_address_tftp.py
This PR adds 2 network cases:
1. VIRT-294611: Enable tftp service for the network without dhcp
2. VIRT-294448: update the virtio driver attributes "rss" "rss-report"
`Test results:
````
(1/1) type_specific.io-github-autotest-libvirt.virtual_network.address.tftp: PASS (7.85 s)
(1/1) type_specific.io-github-autotest-libvirt.iface.update_device.negative.driver.rss: PASS (8.89 s)
```
=> virtual_network: Add 2 cases about rss and tftp

libvirt/tests/cfg/iommu/iommu_device.cfg, libvirt/tests/src/iommu/iommu_device.py
To better test IOMMU device, add a standalone IOMMU test group.
It's meaningless to test IOMMU alone. IOMMU should be conbined with a
I/O device. Block storage device and interface is good.
This patch only conatins virtio iommu + virtio blk device.
TODO:
1. Add virtio interface test device
2. x86 intel model
3. aarch64 smmuv3 iommu model
```
JOB ID     : 4f6707bbd2239aa5c0df8afcf2424d87f07b0f50
JOB LOG    : /root/avocado/job-results/job-2022-06-20T22.52-4f6707b/job.log
(1/1) type_specific.io-github-autotest-libvirt.iommu_device.test_device.virtual_disk.iommu_model.virtio: STARTED
(1/1) type_specific.io-github-autotest-libvirt.iommu_device.test_device.virtual_disk.iommu_model.virtio: PASS (114.15 s)
RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | …
```
=> [RFC] tests: Add IOMMU test group

libvirt/tests/cfg/sriov/vm_lifecycle/sriov_vm_lifecycle_managedsave.cfg
The error message was updated recently, so update it.
```
(1/2) type_specific.io-github-autotest-libvirt.sriov.vm_lifecycle.managedsave.hostdev_interface.vf_address.managed_yes: PASS (54.94 s)
(2/2) type_specific.io-github-autotest-libvirt.sriov.vm_lifecycle.managedsave.hostdev_device.vf_address.managed_yes: PASS (55.06 s)
```
=> sriov: Update error message for managedsave cases

libvirt/tests/src/bios/virsh_boot.py, libvirt/tests/src/bios/virsh_boot_tseg.py, spell.ignore
Remove firmware='efi' and nvram and loader elements in <os> because cases will add them
Depend on https://github.com/avocado-framework/avocado-vt/pull/3486
=> virsh_boot: remove firmware efi

libvirt/tests/src/virsh_cmd/domain/virsh_undefine.py
Need to add '--nvram' to undefine an ovmf guest.
=> virsh_undefine: Fix undefine error

libvirt/tests/src/virsh_cmd/domain/virsh_domxml_to_native.py
Per the developer's opinion, there is no need to compare the command result
with qemu command line any more. So the comparison step is removed. We only
care about the command return status.
=> virsh_domxml_to_native: remove compare

libvirt/tests/src/virtual_network/iface_unprivileged.py
If define Security driver model 'dac' in vm.xml,  seclabel model="dac" under unprivileged user is not supported
Therefore, one error: unsupported configuration: Security driver model 'dac' is not available will be thrown
Fixing the issue by removing seclabel model="dac" since unprivileged user doesn't support this feature
=> Fix iface security model dac not available issue

libvirt/tests/src/remote_access/remote_access.py
We should check virtproxy status for tcp_min_ssf config.
=> remote_access: Fix incorrect service

libvirt/tests/cfg/backingchain/blockcopy/blockcopy_with_conventional_chain.cfg, libvirt/tests/src/backingchain/blockcopy/blockcopy_with_conventional_chain.py, provider/backingchain/blockcommand_base.py, provider/backingchain/check_functions.py
VIRT-294083:Do blockcopy after creating external snapshots with different disk types:
```
/usr/local/bin/avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35  backingchain.blockcopy.conventional_chain
(1/6) type_specific.io-github-autotest-libvirt.backingchain.blockcopy.conventional_chain.file_disk.with_shallow: PASS (31.57 s)
(2/6) type_specific.io-github-autotest-libvirt.backingchain.blockcopy.conventional_chain.file_disk.without_shallow: PASS (33.63 s)
(3/6) type_specific.io-github-autotest-libvirt.backingchain.blockcopy.conventional_chain.block_disk.with_shallow: PASS (61.19 s)
(4/6) type_specific.io-github-autotest-libvirt.backingchain.blockcopy.conventional_chain.block_disk.without_shallow: PASS (52.78 s)
(5/6) …
```
=> add case for blockcopy conventional chain

libvirt/tests/cfg/backingchain/blockpull/blockpull_with_bandwidth.cfg, libvirt/tests/src/backingchain/blockpull/blockpull_with_bandwidth.py
VIRT-294078:Do blockpull with --bandwidth option
```
/usr/local/bin/avocado run --vt-type libvirt --vt-machine-type q35 backingchain.blockpull.with_bandwidth.
JOB ID     : 15fb22b925d3d0fe6ce215a925feb4ca8572da32
JOB LOG    : /root/avocado/job-results/job-2022-07-21T11.55-15fb22b/job.log
(1/4) type_specific.io-github-autotest-libvirt.backingchain.blockpull.with_bandwidth.positive_test.bandwidth_mb: PASS (15.68 s)
(2/4) type_specific.io-github-autotest-libvirt.backingchain.blockpull.with_bandwidth.positive_test.bandwidth_bytes: PASS (13.36 s)
(3/4) type_specific.io-github-autotest-libvirt.backingchain.blockpull.with_bandwidth.negative_test.invalid_str: PASS (11.60 s)
(4/4) type_specific.io-github-autotest-libvirt.backingchain.blockpull.with_bandwidth. …
```
=> add case for blockpull with bandwidth

libvirt/tests/cfg/backingchain/blockcommit/blockcommit_relative_path.cfg, libvirt/tests/src/backingchain/blockcommit/blockcommit_relative_path.py, provider/backingchain/check_functions.py, provider/virtual_disk/disk_base.py
VIRT-293737: Do blockcommit with --keep-relative and relative path continuously
**Depend on** : https://github.com/avocado-framework/avocado-vt/pull/3484
**Test result:** 
```
/usr/local/bin/avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 backingchain.blockcommit.relative_path
JOB ID     : e142deb055b7cd664f01e95b43a40bce4f7f71d6
JOB LOG    : /root/avocado/job-results/job-2022-08-05T16.04-e142deb/job.log
(1/8) type_specific.io-github-autotest-libvirt.backingchain.blockcommit.relative_path.file_disk.keep_relative.active.vm_started: PASS (20.65 s)
(2/8) type_specific.io-github-autotest-libvirt.backingchain.blockcommit.relative_path.file_disk.keep_relative.active.vm_paused: PASS (22.04 s)
(3/8) …
```
=> add case for blockcommit with relative path

libvirt/tests/src/virtual_network/iface_network.py
Fix virtual_network.iface_network.net_forward.route_test case failure
In terms of this case, occasionally, it failed on s390x platform with below eror message:
VMDeadError: VM is dead    reason: Domain avocado-vt-vm1 is inactive
=> Fix virtual_network.iface_network.net_forward.route_test case failure

libvirt/tests/cfg/migration/migrate_network.cfg, libvirt/tests/cfg/sriov/failover/sriov_failover_abort_migration.cfg, libvirt/tests/cfg/sriov/failover/sriov_failover_migration.cfg, libvirt/tests/cfg/sriov/vm_lifecycle/sriov_vm_lifecycle_reboot.cfg, libvirt/tests/cfg/sriov/vm_lifecycle/sriov_vm_lifecycle_start_destroy.cfg, libvirt/tests/cfg/sriov/vm_lifecycle/sriov_vm_lifecycle_start_negative.cfg, libvirt/tests/cfg/sriov/vm_lifecycle/sriov_vm_lifecycle_suspend_resume.cfg, libvirt/tests/cfg/sriov/vm_lifecycle/sriov_vm_lifecycle_unmanaged.cfg, libvirt/tests/src/migration/migrate_network.py, libvirt/tests/src/sriov/scalability/sriov_scalability_max_vfs.py, libvirt/tests/src/sriov/sriov_managed.py, libvirt/tests/src/sriov/sriov_vf_pool.py, libvirt/tests/src/sriov/vm_lifecycle/sriov_vm_lifecycle_start_destroy.py, libvirt/tests/src/sriov/vm_lifecycle/sriov_vm_lifecycle_start_negative.py
Update configurations and scripts to use the updated create_or_del_network().
https://github.com/avocado-framework/avocado-vt/pull/3498
```
(1/1) type_specific.io-github-autotest-libvirt.virsh.migrate_network.ovs_br.without_postcopy: PASS (597.36 s)
(1/1) type_specific.io-github-autotest-libvirt.virsh.migrate_network.direct.fake_macvtap_exists_dest.with_postcopy: PASS (262.05 s)
(01/88) type_specific.io-github-autotest-libvirt.sriov.vf_pool.active.at_dt.macvtap_passthrough: PASS (56.22 s)
(02/88) type_specific.io-github-autotest-libvirt.sriov.vf_pool.active.connection.macvtap_passthrough: PASS (56.57 s)
(03/88) type_specific.io-github-autotest-libvirt.sriov.vf_pool.active.connection.hostdev: PASS (59.64 s) …
```
=> Refactor code to use create_or_del_network

libvirt/tests/cfg/remote_access/remote_with_unix.cfg
Fix remote access case failures due to auth_pwd not set properly
In remote_access cases, sometime it need send auth_pwd to remote host.
But auth_pwd parameter may be not defined in cfg file ,so it return None in some cases
Therefore, TypeError: unsupported operand type(s) for +: 'NoneType' and 'str can be found
=> Fix remote access case failures due to auth_pwd not set properly

libvirt/tests/cfg/migration/migration_uri/migration_network_data_transport_tls_wrong_cert_configuration.cfg, libvirt/tests/src/migration/migration_uri/migration_network_data_transport_tls.py
VIRT-293985 - VM live migration - network data transport - TLS - wrong cert configuration
=> migration: Add a case about wrong cert configuration

libvirt/tests/src/serial/serial_functional.py, libvirt/tests/src/serial/serial_pty_log.py
When booting OVMF guest, there are some un-decoded special characters in the
console log which caused file reading failed. So the solution is to add this
error='ignore' parameter in order to not raise the error like below:
`UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd9 in position 0: unexpected end of data`
The ignoring will not impact some key strings matched in the log.
=> serial_pty_log: fix log decode failure

libvirt/tests/src/virsh_cmd/domain/virsh_attach_device.py
The code deletes the scsi controller but not replacing with "virtio-scsi" due
to which VM boots fails.
Reference - commit 1473a1a
The comment "Remove old scsi controller, replace with virtio-scsi controller"
is inaccurate. The code is removing the old controller, but it is not
replacing it with anything. It seems to be assuming that libvirt will default
to adding a virtio-scsi controller, but that is not the case. libvirt defaults
to the spapr-vscsi controller on ppc64le, not virtio-scsi. So
update_controllers_ppc should instead explicitly add a virtio-scsi controller.
Signed-off-by: Seeteena Thoufeek s1seetee@linux.vnet.ibm.com
e.g
=> virsh_attach_device: Update scsi controller on ppc vms to support scsi hotplug

libvirt/tests/cfg/migration/memory_copy_mode/migration_memory_copy_mode_postcopy.cfg, libvirt/tests/cfg/migration/memory_copy_mode/migration_memory_copy_mode_precopy.cfg, libvirt/tests/cfg/migration/migration_efficiency/migration_zerocopy.cfg, libvirt/tests/cfg/migration/migration_efficiency/migration_zerocopy_abort.cfg, libvirt/tests/cfg/migration/migration_efficiency/migration_zerocopy_unsupported_feature_combinations.cfg, libvirt/tests/cfg/migration/migration_uri/migration_network_data_transport_tcp.cfg, libvirt/tests/cfg/migration/migration_uri/migration_network_data_transport_tcp_listen_address.cfg, libvirt/tests/cfg/migration/migration_uri/migration_network_data_transport_tcp_migrateuri.cfg, libvirt/tests/cfg/migration/migration_uri/migration_network_data_transport_tls.cfg, libvirt/tests/cfg/migration/migration_uri/migration_network_data_transport_tls_migrate_tls_force.cfg, libvirt/tests/cfg/migration/migration_uri/migration_network_data_transport_tunnelled.cfg, libvirt/tests/cfg/migration/migration_uri/migration_network_data_transport_unix_proxy.cfg, libvirt/tests/src/migration/migration_efficiency/migration_zerocopy.py, provider/migration/base_steps.py, provider/migration/migration_base.py
1. VIRT-294637 - VM live migration - zerocopy - unsupported feature combinations
2. VIRT-294640 - VM live migration - zerocopy
3. VIRT-294638 - VM live migration - zerocopy - abort migration
=> migration: Add cases for zerocopy migration

libvirt/tests/src/virtio_transitional/virtio_transitional_blk.py
Update to use disk device object to avoid "No such file or
directory" issue.
` (1/1) type_specific.io-github-autotest-libvirt.virtio_transitional_blk.rhel6_guest.default.with_virtio_blk.hotplug_test.virtio_transitional: ERROR: [Errno 2] No such file or directory: '/tmp/xml_utils_temp_d6el8jm5.xml' (165.39 s)
`
`(1/1) type_specific.io-github-autotest-libvirt.virtio_transitional_blk.rhel6_guest.default.with_virtio_blk.hotplug_test.virtio_transitional: PASS (163.12 s)`
=> virtio_transitional_blk: Fix up "No such file or directory" issue

libvirt/tests/cfg/backingchain/blockcommit/blockcommit_with_shallow_option.cfg, libvirt/tests/src/backingchain/blockcommit/blockcommit_with_shallow_option.py
VIRT-293921:Do blockcommit with --shallow option
**Depend on** : https://github.com/avocado-framework/avocado-vt/pull/3463 
```
(p3-ve) [root@nanli tp-libvirt]#  /usr/local/bin/avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35  backingchain.blockcommit.shallow_option
(1/4) type_specific.io-github-autotest-libvirt.backingchain.blockcommit.shallow_option.file_disk.snap_type.reuse_external: PASS (23.14 s)
(2/4) type_specific.io-github-autotest-libvirt.backingchain.blockcommit.shallow_option.file_disk.snap_type.disk_only: PASS (18.43 s)
(3/4) type_specific.io-github-autotest-libvirt.backingchain.blockcommit.shallow_option.block_disk.snap_type.reuse_external: PASS (29.84 s)
(4/4) …
```
=> add case for blockcommit with shallow option

libvirt/tests/cfg/svirt/dac_nfs_save_restore.cfg, libvirt/tests/cfg/svirt/dac_start_destroy.cfg, libvirt/tests/src/svirt/dac_nfs_save_restore.py, libvirt/tests/src/svirt/dac_start_destroy.py
Ownership will not be changed dynamically when 'dynamic_ownership'
is disabled. Therefore the ownership of certain files should be
maintained manually to avoid permission issue.
=> Fixup:chown of VARS.fd file to avoid permission issue

libvirt/tests/src/virsh_cmd/domain/virsh_reboot.py
Fix AttributeError: 'str' object has no attribute 'stderr when refering cmdoutput
Need set cmdoutput as global variable, otherwise it is not intialized by _wait_for_reboot_up function
=> Fix  virsh reboot failure case

libvirt/tests/cfg/passthrough/ap/libvirt_ap_passthrough_autostart.cfg, libvirt/tests/src/passthrough/ap/libvirt_ap_passthrough.py, libvirt/tests/src/passthrough/ap/libvirt_ap_passthrough_autostart.py, provider/vfio/ap.py, provider/vfio/mdev_handlers.py, virttools/tests/src/virt_install/hostdev_mdev.py
With [s390-tools v2.22.0](https://github.com/ibm-s390-linux/s390-tools/releases/tag/v2.22.0) crypto passthrough device configurations are now easily persisted.
Add a test case to confirm that the configuration is restored at reboot and that therefore a mediated device is autostarted.
For this the code was refactored:
1. Move `MdevHandler` classes from existing virttools test case into new module under `provider` for re-use in new libvirt test case.
2. Create a new `ApMdevHandler`, refactor existing AP passthrough test case to use it instead.
3. Create new test case.
This change depends on https://github.com/avocado-framework/avocado-vt/pull/3472
=> libvirt_ap_passthrough: new test case to verify autostart of crypto device

libvirt/tests/src/virtual_network/virtual_network_multivms.py, spell.ignore
dhclient may not be installed as default on some arch guest, e.g s390x
virtual network multivms need dhclient, so add some logic to install dhclient package
=> Fix virtual network multivms failure due to dhclient

libvirt/tests/cfg/virtual_device/video_devices.cfg, libvirt/tests/src/virtual_device/video_devices.py
Newly add new cases to cover bochs video model
default_heads and vram default_size attributes are covered
=> Newly add new cases to cover bochs video model

provider/v2v_vmcheck_helper.py, v2v/tests/cfg/convert_vm_to_libvirt.cfg, v2v/tests/cfg/convert_vm_to_ovirt.cfg, v2v/tests/cfg/function_test_esx.cfg, v2v/tests/cfg/v2v_options.cfg, v2v/tests/src/specific_kvm.py
1) update some guests' configuration
2) Remove security check when boot firmare is UEFI.
Signed-off-by: Xiaodai Wang <xiaodwan@redhat.com
=> v2v: fix some script errors on rhel9.1

libvirt/tests/src/virtual_device/filesystem_device.py
Sometimes lsof is not installed on our hosts. To avoid errors further down the line, this PR adds a check to the test to see if lsof is installed and if not the test is cancelled.
```
(p3-ve) [root@yuggoth ~]# avocado run --vt-type libvirt virtual_devices.filesystem_device.positive_test.hugepages_backed.hotplug_unplug.detach_device_alias.stdio_handler.file.fs_test.xattr_on.flock_on.lock_posix_on.cache_mode_none.one_fs.one_guest
JOB ID     : …
```
=> virtual_devices: check lsof availability

libvirt/tests/cfg/sriov/plug_unplug/sriov_attach_detach_device.cfg, libvirt/tests/src/sriov/plug_unplug/sriov_attach_detach_device.py
VIRT-292850: Attach/detach-device a hostdev interface or device to/from guest
**Depends on:** https://github.com/avocado-framework/avocado-vt/pull/3498
```
(01/13) type_specific.io-github-autotest-libvirt.sriov.plug_unplug.attach_detach_device.hostdev_interface.vf_address.managed_yes: PASS (63.01 s)
(02/13) type_specific.io-github-autotest-libvirt.sriov.plug_unplug.attach_detach_device.hostdev_interface.vf_address.managed_no: PASS (64.92 s)
(03/13) type_specific.io-github-autotest-libvirt.sriov.plug_unplug.attach_detach_device.hostdev_interface.vf_address.without_managed: PASS (62.97 s)
(04/13) type_specific.io-github-autotest-libvirt.sriov.plug_unplug.attach_detach_device.hostdev_interface.vf_address.vlan: PASS (60.14 s) …
```
=> sriov: Add a case of attaching hostdev device or interface

libvirt/tests/src/libvirt_hooks.py
Interface can not be hot unplugged immediately after hotplug. 
For q35 and i440fx, IMO no need to detach interface for a sceond time with EventTracker.
Before:
```
JOB ID     : 47a165e7530f21a279662ca11d2cd9572bd980c8                                                                                                              
JOB LOG    : /var/lib/avocado/job-results/job-2022-08-28T23.02-47a165e/job.log     
(1/1) type_specific.io-github-autotest-libvirt.libvirt_hooks.vm.network_t: FAIL: Failed to check network hooks (30.21 s)
RESULTS    : PASS 0 | ERROR 0 | FAIL 1 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0                                                                                                                             
JOB HTML   : …
```
=> hooks: use EventTracker to wait for detach_interface to complete

libguestfs/tests/guestfs_add.py
The cmd_output function in aexpect module trim the last line because it
includes shell prompt.
https://github.com/avocado-framework/aexpect/blob/master/aexpect/client.py#L1202
In this test, the content of guestfs_temp has only one line and it doesn't
include newline at the end. So, the cat output is followed by the next
prompt in one line and trimmed in remove_last_nonempty_line function.
Because of this, the file content seems to be empty and test fails.
This patch adds additional newline after the cat command so that the
contents of the file is not trimmed by the remove_last_nonempty_line
function.
`(25/32) type_specific.io-github-autotest-libvirt.guestfs_add.normal_test.add_disk:  FAIL: {'write_content': 'Write content to file successfully.', 'cat_writed': 'Cat content …
=> guestfs_add: Add a trailing newline when retreive contents

libvirt/tests/src/multifunction.py
This option is removed in beee20f45cbe63b9a6c70a344c1b13097243151d and not work.
Current multifunction test script specifies allow_output_check argument for avocado.utils.process.run() function.
However, this argument was removed in the following patch. So the script always errors because of the type mismatch.
=> Remove allow_output_check option

provider/virtual_disk/disk_base.py
for rbd type in add_vm_disk func, missing source file if secret
```
avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35  backingchain..rbd_with_auth_disk
(1/6) type_specific.io-github-autotest-libvirt.backingchain.blockcommit.conventional_chain.rbd_with_auth_disk.mid_to_mid: PASS (48.01 s)
(2/6) type_specific.io-github-autotest-libvirt.backingchain.blockcommit.conventional_chain.rbd_with_auth_disk.top_to_base: PASS (115.00 s)
(3/6) type_specific.io-github-autotest-libvirt.backingchain.blockcommit.conventional_chain.rbd_with_auth_disk.top_to_mid: PASS (77.50 s)
(4/6) type_specific.io-github-autotest-libvirt.backingchain.blockcommit.conventional_chain.rbd_with_auth_disk.mid_to_base: PASS (90.31 s)
(5/6) …
```
=> fix empty rbd source file

libvirt/tests/cfg/migration/migrate_options_shared.cfg
The log filters on the remote hosts was configed incorrectly,
Fix the issue in this PR.
` (1/1) type_specific.io-github-autotest-libvirt.virsh.migrate_options_shared.positive_test.check_event.event_without_postcopy.without_postcopy: FAIL: The string 'qemuProcessHandleMigrationStatus' is not included in /var/log/libvirt/libvirtd.log (160.71 s)
`
` (1/1) type_specific.io-github-autotest-libvirt.virsh.migrate_options_shared.positive_test.check_event.event_without_postcopy.without_postcopy: PASS (165.31 s)
`
=> migration: Fixup no 'qemuProcessHandleMigrationStatus' issue

libvirt/tests/src/nwfilter/nwfilter_vm_start.py
As the /tpm directoy is also used for tpm device. Using /tmp as
mount point with noexec option will cause the vm failed to start.
Update the mount point to /tmp/mnt.
=> Update the mount point to /tmp/mnt

libvirt/tests/cfg/migration/memory_copy_mode/migration_memory_copy_mode_precopy.cfg
We need to check 'libvirtd' service on RHEL 8. So update it.
=> migration: Fix service name error

libvirt/tests/cfg/backingchain/blockcopy/blockcopy_with_backingfile.cfg, libvirt/tests/src/backingchain/blockcopy/blockcopy_with_backingfile.py
source and target image needs to have same sizes
**Test result on x86 :**
```
avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 backingchain.blockcopy.blockcopy_with_backingfile --vt-connect-uri qemu:///system
(1/4) type_specific.io-github-autotest-libvirt.backingchain.blockcopy.blockcopy_with_backingfile.shallow_and_reuse_external.file_disk.pivot_after_blockcopy: PASS (49.26 s)
(2/4) type_specific.io-github-autotest-libvirt.backingchain.blockcopy.blockcopy_with_backingfile.shallow_and_reuse_external.file_disk.abort_after_blockcopy: PASS (49.70 s)
(3/4) type_specific.io-github-autotest-libvirt.backingchain.blockcopy.blockcopy_with_backingfile.shallow_and_reuse_external.block_disk.pivot_after_blockcopy: PASS (249.73 s)
(4/4) …
```
=> fix source image and dst image have different size

libvirt/tests/cfg/bios/boot_order_seabios.cfg, libvirt/tests/src/bios/boot_order_seabios.py
Add checks for disk boot order element to
libvirt/tests/src/bios/boot_order_ovmf.py. Positive and negative check
is added.
LIBVIRTAT-13216
VIRT-45997
```
JOB ID     : e02186789f56f8d4a76dcd29bbc4477ed0ef1046
JOB LOG    : /root/avocado/job-results/job-2022-07-22T12.12-e021867/job.log
(1/2) type_specific.io-github-autotest-libvirt.boot_order_seabios.positive_test.boot_order_element.hd.file_disk: STARTED
(1/2) …
```
=> Bios: Add disk boot order element checks

libvirt/tests/cfg/backingchain/blockcopy/blockcopy_with_backingfile.cfg, libvirt/tests/src/backingchain/blockcopy/blockcopy_with_backingfile.py
block disk size should use same variable in src and dst image
```
/usr/local/bin/avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 backingchain.blockcopy.blockcopy_with_backingfile.shallow_and_reuse_external..block_disk
(1/2) type_specific.io-github-autotest-libvirt.backingchain.blockcopy.blockcopy_with_backingfile.shallow_and_reuse_external.block_disk.pivot_after_blockcopy: PASS (251.49 s)
(2/2) type_specific.io-github-autotest-libvirt.backingchain.blockcopy.blockcopy_with_backingfile.shallow_and_reuse_external.block_disk.abort_after_blockcopy: PASS (250.57 s)
```
=> fix the block disk size use hard code

libvirt/tests/cfg/migration/migration_uri/migration_network_data_transport_tls.cfg, provider/migration/base_steps.py
Add 'log_filters' on remote host.
=> migration: Fix issue about no expected string in log file

libvirt/tests/cfg/sriov/vm_lifecycle/direct_passthrough_vm_lifecycle_start_destroy.cfg, libvirt/tests/src/sriov/vm_lifecycle/direct_passthrough_vm_lifecycle_start_destroy.py
Fix "no attribute" issue.
` (1/1) type_specific.io-github-autotest-libvirt.direct_passthrough.vm_lifecycle.start_destroy.network_interface.network.vf_name.default: ERROR: Cannot set attribute "net_name" to <class 'virttest.libvirt_xml.network_xml.NetworkXML'> object.There is no such attribute. (15.15 s)
`
` (1/1) type_specific.io-github-autotest-libvirt.direct_passthrough.vm_lifecycle.start_destroy.network_interface.network.vf_name.default: PASS (74.22 s)
`
=> sriov: Fix an AttributeError

libvirt/tests/cfg/channel/channel_functional.cfg
Fix channel functional case failure
channel.functional.positive_tests.auto_gen_port.pty_type, this case will attach channel device with channel type="spicevmc", which is not supported on s390x, so filter out this case on s390x
=> Fix channel functional case failure on 390x

libvirt/tests/cfg/serial/serial_pty_log.cfg
Fix serial console failure on s390x
on s390x, serial console need configure target type='sclp-serial'and  model name='sclpconsole'
=> Fix serial console failure on s390x

libvirt/tests/src/controller/controller_functional.py
Fix functional console invalid_chassisNr failure
In s390x, it use pci_root controller model,otherwise it will return empty index
=> Fix functional console invalid_chassisNr failure on 390x

libvirt/tests/cfg/backingchain/negative_scenario/blockcommit_invalid_top_base.cfg, libvirt/tests/src/backingchain/negative_scenario/blockcommit_invalid_top_base.py, provider/backingchain/blockcommand_base.py
VIRT-294581:Do blockcommit with invalid top/base image
```
[root@dell-per740-33 avocado-vt]# avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 backingchain.negative.blockcommit.invalid_top_base
(1/4) type_specific.io-github-autotest-libvirt.backingchain.negative.blockcommit.invalid_top_base.no_backing.blockcommit_directly: PASS (49.00 s)
(2/4) type_specific.io-github-autotest-libvirt.backingchain.negative.blockcommit.invalid_top_base.no_backing.after_pivot: PASS (57.33 s)
(3/4) type_specific.io-github-autotest-libvirt.backingchain.negative.blockcommit.invalid_top_base.same_image: PASS (50.78 s)
(4/4) type_specific.io-github-autotest-libvirt.backingchain.negative.blockcommit.invalid_top_base.top_without_active: PASS (51.31 s) …
```
=> backingchain: add case for blockcommit with invalid top base

libvirt/tests/cfg/sriov/plug_unplug/sriov_attach_detach_device_after_restarting_service.cfg, libvirt/tests/src/sriov/plug_unplug/sriov_attach_detach_device_after_restarting_service.py, provider/sriov/sriov_base.py
This PR adds:
VIRT-294721: Add one more hostdev interface/device after
restarting libvirtd
```
(1/3) type_specific.io-github-autotest-libvirt.sriov.plug_unplug.attach_detach_device_after_restarting_service.hostdev_interface: PASS (57.11 s)
(2/3) type_specific.io-github-autotest-libvirt.sriov.plug_unplug.attach_detach_device_after_restarting_service.hostdev_device: PASS (56.89 s)
(3/3) type_specific.io-github-autotest-libvirt.sriov.plug_unplug.attach_detach_device_after_restarting_service.network_interface: PASS (57.34 s)
```
=> sriov: Add a plug_unplug case

libvirt/tests/src/npiv/npiv_nodedev_create_destroy.py
The npiv methods were moved to avocado-vt/virttest/npiv_utils.py,
we should clean up the code here.
=> npiv: use existing npiv_utils code in test case

libvirt/tests/cfg/migration/memory_copy_mode/migration_memory_copy_mode_postcopy.cfg, libvirt/tests/cfg/migration/memory_copy_mode/migration_memory_copy_mode_precopy.cfg, libvirt/tests/cfg/migration/migration_efficiency/migration_zerocopy.cfg, libvirt/tests/cfg/migration/migration_efficiency/migration_zerocopy_abort.cfg, libvirt/tests/cfg/migration/migration_efficiency/migration_zerocopy_unsupported_feature_combinations.cfg, libvirt/tests/cfg/migration/migration_uri/migration_network_data_transport_tcp.cfg, libvirt/tests/cfg/migration/migration_uri/migration_network_data_transport_tcp_listen_address.cfg, libvirt/tests/cfg/migration/migration_uri/migration_network_data_transport_tcp_migrateuri.cfg, libvirt/tests/cfg/migration/migration_uri/migration_network_data_transport_tls.cfg, libvirt/tests/cfg/migration/migration_uri/migration_network_data_transport_tunnelled.cfg, libvirt/tests/cfg/migration/migration_uri/migration_network_data_transport_unix_proxy.cfg, provider/migration/migration_base.py
If migration finish too fast, we cann't check port and ip during
migration. So update migration speed.
=> migration: Set migration speed to more low value

libvirt/tests/src/virsh_cmd/domain/virsh_set_user_password.py
Fix set_user_password failure
After adding user user in guest, it also need delete the user at last but sometime it failed due to user is being used by other process, so add -f option when call userdel command
=> Fix set_user_password failure

libvirt/tests/src/migration/migrate_over_unix.py
Fix failure in virsh.migrate_over_unix.positive_testing.with_copy_storage.default.multi_disks.p2p_live_migration.without_postcopy
test case failed at the beginning while calling utils_disk.linux_disk_check with below error message: Error: Partition(s) on /dev/vdb are being used
the root clause may come from reusing existed disk image with partitions
=> Fix failure migrate_over_unix case

libvirt/tests/src/multifunction.py
The XML file to attach a disk is managed by the object named "diskxml" in
create_disk_xml function. But this function returns only diskxml.xml member,
it is a mere a string. So, the diskxml object lose its reference after
the function returning the value.
Because of this, diskxml object may be destroyed by the python gabage
collection.
If the diskxml object is destroyed, it removes related XML files in
its finalizer. It causes test failure with "No such file or directory"
error when it executes virsh attach-device command.
```
(06/26) type_specific.io-github-autotest-libvirt.multifunction.set_type_pci.set_multifunction_on.single_device.function_0:  FAIL: Attach device vdb failed. (3.78 s)
```
After the fix:
```
(06/26) …
```
=> Multifunction: Avoid GC for the diskxml object

libvirt/tests/cfg/sriov/network/sriov_check_net_info_by_network_lifecycle_cmds.cfg, libvirt/tests/cfg/sriov/network/sriov_define_or_start_network_with_pf_addr.cfg, libvirt/tests/src/sriov/network/sriov_check_net_info_by_network_lifecycle_cmds.py, libvirt/tests/src/sriov/network/sriov_define_or_start_network_with_pf_addr.py, provider/sriov/sriov_base.py
This PR adds:
1. VIRT-294816: Define or start 'hostdev' network which
contains PF pci addresses
2. VIRT-293136: Check net info by network lifecycle cmds
```
(1/2) type_specific.io-github-autotest-libvirt.sriov.network.check_net_info_by_network_lifecycle_cmds: PASS (21.84 s)
(2/2) type_specific.io-github-autotest-libvirt.sriov.network.define_or_start_network_with_pf_addr: PASS (20.98 s)
```
=> sriov: Add 2 network cases

libvirt/tests/src/sriov/failover/sriov_failover_migration.py
It reports an error - "No such file or directory" sometimes.
` (1/1) type_specific.io-github-autotest-libvirt.sriov.failover.abort_migration.hostdev_device.with_precopy: PASS (284.36 s)
`
=> sriov_migration: Fixup no xml file issue

libvirt/tests/cfg/bios/boot_order_ovmf.cfg, libvirt/tests/src/bios/boot_order_ovmf.py
Automation of case VIRT-45998
This commit adds scenarios for automating VIRT-45998. Boot order for
disks (not os) is tested on OVMF guests.
```
avocado run --vt-type libvirt boot_order_ovmf
JOB ID     : 9bdf44300d22f187e607109d5415e1253fd81959
JOB LOG    : /var/lib/avocado/job-results/job-2022-08-16T07.44-9bdf443/job.log
(1/2) type_specific.io-github-autotest-libvirt.boot_order_ovmf.bootable_first.boot_order_element: STARTED
(1/2) …
```
=> bios: Boot order test for ovmf guests

libvirt/tests/cfg/sriov/plug_unplug/sriov_attach_detach_device_with_flags.cfg, libvirt/tests/src/sriov/plug_unplug/sriov_attach_detach_device_with_flags.py, provider/sriov/sriov_base.py
This PR adds:
VIRT-294697 - Attach/detach-device a hostdev interface or device
with various flags for vm states
(01/16) type_specific.io-github-autotest-libvirt.sriov.plug_unplug.attach_detach_device_with_flags.hostdev_interface.live.offline_domain: PASS (21.48 s)
(02/16) type_specific.io-github-autotest-libvirt.sriov.plug_unplug.attach_detach_device_with_flags.hostdev_interface.live.running_domain: PASS (34.71 s)
(03/16) type_specific.io-github-autotest-libvirt.sriov.plug_unplug.attach_detach_device_with_flags.hostdev_interface.current.offline_domain: PASS (22.94 s)
(04/16) type_specific.io-github-autotest-libvirt.sriov.plug_unplug.attach_detach_device_with_flags.hostdev_interface.current.running_domain: PASS (34.70 s) …
=> sriov: Add a case to check various flags

provider/virtual_disk/disk_base.py
need skip to get source file if source tage is none
```
Test result:
/usr/local/bin/avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 backingchain.blockpull.conventional_chain.rbd_with_auth_disk.without_base --vt-connect-uri qemu:///system
(1/1) type_specific.io-github-autotest-libvirt.backingchain.blockpull.conventional_chain.rbd_with_auth_disk.without_base: PASS (64.00 s)
/usr/local/bin/avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 backingchain.blockcopy.conventional_chain.rbd_with_auth_disk.without_shallow --vt-connect-uri qemu:///system
(1/1) type_specific.io-github-autotest-libvirt.backingchain.blockcopy.conventional_chain.rbd_with_auth_disk.without_shallow: PASS (64.88 s)
```
=> fix none type get source file

libvirt/tests/src/virsh_cmd/domain/virsh_detach_serial_device_alias.py
Sometimes qemu-kvm process will crash when we unplug the serial device before vm is fully booted. This behavior is not reasonable. So we need to make sure the vm is fully booted and could be logged in.
=> virsh_detach_serial_device_alias: fix_early_unplug

libvirt/tests/cfg/migration/migration_performance_tuning/migration_memory_compression.cfg, libvirt/tests/src/migration/migration_performance_tuning/migration_performance_tuning.py
VIRT-293935 - VM live migration - memory compression(--compressed)
=> migration: Add case for memory compression

libvirt/tests/src/libvirtd/libvirtd.py
Before:
```
(1/1) type_specific.io-github-autotest-libvirt.libvirtd.libvirtd.check_journal: ERROR: fail() takes from 1 to 2 positional arguments but 3 were given (51.13 s)
```
Now:
```
(1/1) type_specific.io-github-autotest-libvirt.libvirtd.libvirtd.check_journal: FAIL: Found error message during libvirtd restarting: -- Logs begin at Sun 2022-09-18 01:59:29 EDT. --\nSep 18 23:19:02 fujitsu-fx700-01-n00.2a2m.lab.eng.bos.redhat.com polkitd[1433]: Registered Authentication Agent for unix-process:271941:9410687 (system bus na... (54.07 s)
```
=> libvirtd.py: Fix arguments error

libvirt/tests/cfg/svirt/dac_per_disk_hotplug.cfg, libvirt/tests/src/svirt/dac_per_disk_hotplug.py
Two factors may cause the permission denied issues:
1.Start guest with existing nvram file when disable dynamic_ownership
2.Start guest with tpm device when disable dynamic_ownership
e.g
=> Fix the permission denied issues for dac_per_disk_hotplug

libvirt/tests/cfg/svirt/dac_start_destroy.cfg, libvirt/tests/src/svirt/dac_start_destroy.py
=> Fix permission issue caused by tpm device when disable dynamic_ownership

libvirt/tests/src/remote_access/remote_access.py
The tls object has been [set up before](https://github.com/autotest/tp-libvirt/blob/master/libvirt/tests/src/remote_access/remote_access.py#L416), no need to [instantiate it again](https://github.com/autotest/tp-libvirt/blob/master/libvirt/tests/src/remote_access/remote_access.py#L520).
Creating a new tls object causes it to back up the conf file that was modified by the old tls object, making it ultimately impossible to restore the conf file to its original state.
Test Result:
(1/1) type_specific.io-github-autotest-libvirt.virsh.remote_with_tls.positive_testing.no_sanity_checks_and_no_verify: PASS (268.93 s)
(1/1) type_specific.io-github-autotest-libvirt.virsh.remote_with_tls.negative_testing.no_sanity_checks_without_no_verify: PASS (260.93 s)
Signed-off-by: Hu Shuai …
=> remote_access: Remove redundant tls object

libvirt/tests/src/virsh_cmd/virsh_connect.py
ConnLoginError: Got a error when login to CLIENT.IP.Error: Host
terminates during login to client.
=> virsh_connect: Fix client_ip parameter issue

libvirt/tests/cfg/virsh_cmd/domain/virsh_start.cfg, libvirt/tests/src/virsh_cmd/domain/virsh_start.py
Automation of RHEL-133902.
This case simply starts a VM and looks for messages in audit.log that with avc label (SElinux permission checks).
```
JOB ID     : 63b27e4d4bda86717749c36d0217ce4321d310d0
JOB LOG    : /var/lib/avocado/job-results/job-2022-09-06T10.44-63b27e4/job.log
(1/1) type_specific.io-github-autotest-libvirt.virsh.start.status_error_no.audit_log_search: STARTED
(1/1) type_specific.io-github-autotest-libvirt.virsh.start.status_error_no …
```
=> Add test case for searching avc errors in audit log

libvirt/tests/src/sriov/plug_unplug/sriov_attach_detach_device.py, libvirt/tests/src/sriov/plug_unplug/sriov_attach_detach_device_after_restarting_service.py, libvirt/tests/src/sriov/plug_unplug/sriov_attach_detach_device_with_flags.py, libvirt/tests/src/sriov/vm_lifecycle/sriov_vm_lifecycle_start_destroy.py, provider/sriov/sriov_base.py
The 'ignore_status' was incorrectly passed as 'ignore_error'.
```
(1/3) type_specific.io-github-autotest-libvirt.sriov.plug_unplug.attach_detach_device_after_restarting_service.hostdev_interface: PASS (66.10 s)
(2/3) type_specific.io-github-autotest-libvirt.sriov.plug_unplug.attach_detach_device_after_restarting_service.hostdev_device: PASS (58.36 s)
(3/3) type_specific.io-github-autotest-libvirt.sriov.plug_unplug.attach_detach_device_after_restarting_service.network_interface: PASS (59.13 s)
```
=> sriov: Correct virsh commands' ignore_status

libvirt/tests/cfg/backingchain/blockcopy/blockcopy_with_syncwrites_option.cfg, libvirt/tests/cfg/backingchain/blockcopy_options.cfg, libvirt/tests/src/backingchain/blockcopy/blockcopy_with_syncwrites_option.py, libvirt/tests/src/backingchain/blockcopy_options.py
VIRT-294535:Do blockcopy with --synchronous-writes option
**Also**: Delete related old auto code which is not modulared
```
[root@cloud-qe-18 tp-libvirt]# /usr/local/bin/avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 backingchain.blockcopy.synchronous_writes.positive_test
(1/1) type_specific.io-github-autotest-libvirt.backingchain.blockcopy.synchronous_writes.positive_test: PASS (35.65 s)
```
=> backingchain: add case for blockcoopy with --synchronous --writes

libvirt/tests/cfg/sriov/plug_unplug/sriov_attach_detach_device_with_unsupported_settings.cfg, libvirt/tests/src/sriov/plug_unplug/sriov_attach_detach_device_with_unsupported_settings.py
This PR adds:
VIRT-293237 - Attach-device of hostdev type to guest with
unsupported settings
```
(1/3) type_specific.io-github-autotest-libvirt.sriov.plug_unplug.attach_detach_device_with_unsupported_settings.hostdev_interface.inactive_pf: PASS (61.90 s)
(2/3) type_specific.io-github-autotest-libvirt.sriov.plug_unplug.attach_detach_device_with_unsupported_settings.hostdev_interface.unassigned_address: PASS (54.49 s)
(3/3) type_specific.io-github-autotest-libvirt.sriov.plug_unplug.attach_detach_device_with_unsupported_settings.hostdev_interface.dup_alias: PASS (59.48 s)
```
=> sriov: Add a negative test about attaching/detaching hostdev

libvirt/tests/src/guest_agent/guest_agent.py
Fix guest_agent case failure
/tmp/xml_utils_temp_w3p0025w.xml': No such file or directory may occasionally throw
when attach guest_agent device since xml object may be gc-ed by python
=> Fix guest_agent case failure

libvirt/tests/cfg/migration/migration_uri/migration_network_data_transport_tls_wrong_cert_configuration.cfg
TestFail: Can not find the expected patterns 'operation failed:
job 'migration out' failed: Cannot write to TLS channel:
Input/output error|unable to execute QEMU command
'object-add': Unable to access credentials
/etc/pki/qemu/client-cert.pem' in output 'error: operation
failed: migration out job: Cannot write to TLS channel:
Input/output error'
=> migration: Update error message

libvirt/tests/cfg/backingchain/blockcopy/blockcopy_with_async_option.cfg, libvirt/tests/src/backingchain/blockcopy/blockcopy_with_async_option.py, provider/backingchain/blockcommand_base.py
VIRT-294531: Do blockcopy with --async option
**Depend on** : https://github.com/avocado-framework/avocado-vt/pull/3517 
```
(p3-ve) [root@nanli tp-libvirt]# /usr/local/bin/avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 backingchain.blockcopy.async_option
(1/2) type_specific.io-github-autotest-libvirt.backingchain.blockcopy.async_option.async: PASS (12.33 s)
(2/2) type_specific.io-github-autotest-libvirt.backingchain.blockcopy.async_option.async_timeout: PASS (19.23 s)
```
=> backingchain: add case for blockcopy with async option

libvirt/tests/cfg/sriov/plug_unplug/sriov_attach_detach_interface_check_connections.cfg, libvirt/tests/src/sriov/plug_unplug/sriov_attach_detach_interface_check_connections.py
This PR adds:
VIRT-294711: Check the number of connections on hostdev network
during hotplug / unplug
` (1/1) type_specific.io-github-autotest-libvirt.sriov.plug_unplug.attach_detach_interface_check_connections: PASS (69.66 s)
`
=> sriov: Add a test to check the network connections

libvirt/tests/cfg/conf_file/libvirtd_conf/set_audit_logging.cfg, libvirt/tests/src/conf_file/libvirtd_conf/set_audit_logging.py
Newly added test cases : disable/enable audit_logging in libvirtd.log
audit_logging = 1 to let audit messages also be sent via libvirt logging infrastructure as well as the auditd logging
=> Newly added test cases : disable/enable audit_logging in libvirtd.log

libvirt/tests/cfg/virsh_cmd/domain/virsh_detach_device_alias.cfg, libvirt/tests/src/virsh_cmd/domain/virsh_detach_device_alias.py
RHEL-148235: Device can also be detached by 'virsh detach-device-alias' cmd.
```
avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 virsh.detach_device_alias..channel
(1/6) type_specific.io-github-autotest-libvirt.virsh.detach_device_alias.live.channel.spicevmc: PASS (49.72 s)
(2/6) type_specific.io-github-autotest-libvirt.virsh.detach_device_alias.live.channel.pty: PASS (62.11 s)
(3/6) type_specific.io-github-autotest-libvirt.virsh.detach_device_alias.live.channel.unix: PASS (61.41 s)
(4/6) type_specific.io-github-autotest-libvirt.virsh.detach_device_alias.config.channel.spicevmc: PASS (60.02 s)
(5/6) type_specific.io-github-autotest-libvirt.virsh.detach_device_alias.config.channel.pty: PASS (60.34 s)
(6/6) …
```
=> hotplug: add case for detach channel with alias

libvirt/tests/src/npiv/npiv_hostdev_passthrough.py
Previously the mpathconf was enabled after vhba created and multipathd restarted. This caused mpath dev not show up in time. With this fix, the sequence is correct to be:
1. enable mpathconf > 2. restart multipathd And new device will be show up in time.
=> npiv: fix a 'no available lun' issue

libvirt/tests/cfg/libvirtd/libvirtd.cfg, libvirt/tests/src/libvirtd/libvirtd.py
The PVR err is output during CPU detection for ARM. Which was caused by the
missing cpu xml in libvirt/src/cpu_map.
CPU detection will (in some cases) report the host CPU in host capabilities,
but that's it. It's not very useful so we could ignore the PVR err.
Otherwise we need to add all arm cpu to libvirt/src/cpu_map.
Ref: https://listman.redhat.com/archives/libvir-list/2022-August/234040.html
=> libvirtd: Ignore PVR err str for aarch64

libvirt/tests/cfg/memory/memory_attach_device.cfg, libvirt/tests/cfg/memory/memory_update_device.cfg
The old memory size is lower than system requirements which would cause start up failure.
=> Fixup:Increase memory size to avoid start up failure

libvirt/tests/cfg/backingchain/blockpull/blockpull_base_image_exist_backingfile.cfg, libvirt/tests/src/backingchain/blockpull/blockpull_base_image_exist_backingfile.py, provider/virtual_disk/disk_base.py
VIRT-294012: Do blockpull when the guest image has backing file
```
avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 backingchain.blockpull.base_image_exist_backingfile
(1/8) type_specific.io-github-autotest-libvirt.backingchain.blockpull.base_image_exist_backingfile.file_disk.file_backing.with_base: PASS (33.76 s)
(2/8) type_specific.io-github-autotest-libvirt.backingchain.blockpull.base_image_exist_backingfile.file_disk.file_backing.without_base: PASS (34.03 s)
(3/8) type_specific.io-github-autotest-libvirt.backingchain.blockpull.base_image_exist_backingfile.file_disk.block_backing.with_base: PASS (53.76 s)
(4/8) type_specific.io-github-autotest-libvirt.backingchain.blockpull.base_image_exist_backingfile.fil …
```
=> backingchain: add case for blockpull with backingfile

libvirt/tests/cfg/backingchain/blockpull/blockpull_relative_path.cfg, libvirt/tests/src/backingchain/blockpull/blockpull_relative_path.py, provider/backingchain/blockcommand_base.py, provider/virtual_disk/disk_base.py
VIRT-294062: Do blockpull with --keep-relative and relative path continuously
```
/usr/local/bin/avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 backingchain.blockpull.relative_path
(1/3) type_specific.io-github-autotest-libvirt.backingchain.blockpull.relative_path.file_disk.keep_relative.inactive: PASS (14.69 s)
(2/3) type_specific.io-github-autotest-libvirt.backingchain.blockpull.relative_path.block_disk.keep_relative.inactive: PASS (36.06 s)
(3/3) type_specific.io-github-autotest-libvirt.backingchain.blockpull.relative_path.rbd_with_auth_disk.keep_relative.inactive: ERROR: Command '/usr/bin/virsh -k0 blockpull avocado-vt-vm1 vdb  --base /var/lib/libvirt/images/c/c --wait --verbose --keep-relative' …
```
=> backingchain: add case for blockpull with relative path

libvirt/tests/cfg/cpu/iothread.cfg, libvirt/tests/src/cpu/iothread.py
Add new case for below scenarios:
- VM can start with defaultiothread element
- iothreadset can work with --thread-pool-min and --thread-pool-max
when vm is shutoff or running
ID: VIRT-294819 , VIRT-294820
=> iothread: new case for thread pool

libvirt/tests/src/virsh_cmd/domain/virsh_cpu_xml.py
Some cases require Skylake host to run. So this is to add the checking.
=> virsh_cpu_xml: fix to skip on not skylake

libvirt/tests/cfg/backingchain/blockcopy/blockcopy_with_blockdev_option.cfg, libvirt/tests/src/backingchain/blockcopy/blockcopy_with_blockdev_option.py, provider/backingchain/blockcommand_base.py, provider/virtual_disk/disk_base.py
VIRT-294520: Do blockcopy with --blockdev option for different disk types
```
/usr/local/bin/avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35  backingchain.blockcopy.blockdev_option
(1/6) type_specific.io-github-autotest-libvirt.backingchain.blockcopy.blockdev_option.file_disk.blockdev: PASS (72.21 s)
(2/6) type_specific.io-github-autotest-libvirt.backingchain.blockcopy.blockdev_option.file_disk.blockdev_and_shallow: PASS (85.27 s)
(3/6) type_specific.io-github-autotest-libvirt.backingchain.blockcopy.blockdev_option.block_disk.blockdev: PASS (75.65 s)
(4/6) type_specific.io-github-autotest-libvirt.backingchain.blockcopy.blockdev_option.block_disk.blockdev_and_shallow: PASS (73.59 s)
(5/6) …
```
=> backingchain: add case for blockcopy with blockdev option

libvirt/tests/cfg/backingchain/blockcopy/blockcopy_with_invalid_destination.cfg, libvirt/tests/src/backingchain/blockcopy/blockcopy_with_invalid_destination.py
VIRT-294592: Do blockcopy with invalid destination file
```
/usr/local/bin/avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35  backingchain.blockcopy.invalid_destination
(1/6) type_specific.io-github-autotest-libvirt.backingchain.blockcopy.invalid_destination.not_exist: PASS (51.73 s)
(2/6) type_specific.io-github-autotest-libvirt.backingchain.blockcopy.invalid_destination.less_image: PASS (52.43 s)
(3/6) type_specific.io-github-autotest-libvirt.backingchain.blockcopy.invalid_destination.relative_path.current: PASS (50.12 s)
(4/6) type_specific.io-github-autotest-libvirt.backingchain.blockcopy.invalid_destination.relative_path.current_dir: PASS (49.88 s)
(5/6) type_specific.io-github-autotest-libvirt.backingchain.blockcopy.inval …
```
=> backingchain: add case for blockcopy with invalid dest file

libvirt/tests/cfg/backingchain/blockjob/blockjob_with_bandwidth_option.cfg, libvirt/tests/src/backingchain/blockjob/blockjob_with_bandwidth_option.py
VIRT-294562: Do blockjob with bandwidth option
```
/usr/local/bin/avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 backingchain.blockjob.bandwidth
(1/1) type_specific.io-github-autotest-libvirt.backingchain.blockjob.bandwidth.value_updated: PASS (12.47 s)
```
=> backingchain: add case for blockjob with bandwidth

libvirt/tests/cfg/backingchain/blockcommit/blockcommit_relative_path.cfg, libvirt/tests/src/backingchain/blockcommit/blockcommit_relative_path.py
feature owner update the case content, which needs to update origin rbd disk xml
**depend on**: https://github.com/autotest/tp-libvirt/pull/4455 
```
/usr/local/bin/avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 backingchain.blockcommit.relative_path
JOB ID     : 94c87c681abd922f2d8d5365af77dbffec5169cf
JOB LOG    : /root/avocado/job-results/job-2022-09-08T19.45-94c87c6/job.log
(1/8) type_specific.io-github-autotest-libvirt.backingchain.blockcommit.relative_path.file_disk.keep_relative.active.vm_started: PASS (12.56 s)
(2/8) type_specific.io-github-autotest-libvirt.backingchain.blockcommit.relative_path.file_disk.keep_relative.active.vm_paused: PASS (13.20 s)
(3/8) …
```
=> blockcommit relative: update new disk xml with backingstore

libvirt/tests/cfg/backingchain/blockjob/blockjob_with_raw_option.cfg, libvirt/tests/src/backingchain/blockjob/blockjob_with_raw_option.py
VIRT-293943: Do blockjob with --raw option
```
/usr/local/bin/avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 backingchain.blockjob.raw.raw_list
JOB ID     : 3e0a0d8b0f43f0f33d9a9e58bea2c600b821a733
JOB LOG    : /root/avocado/job-results/job-2022-09-12T21.17-3e0a0d8/job.log
(1/1) type_specific.io-github-autotest-libvirt.backingchain.blockjob.raw.raw_list: PASS (34.15 s)
```
=> backingchain: add case for blockjob with raw option

libvirt/tests/src/virsh_cmd/domain/virsh_migrate_option_mix.py
Define and start a UEFI vm, then undefine vm with --nvram, then do live migration will fail. A workaround is undefine vm with --keep-nvram.
=> migration: Fix undefine vm issue

libvirt/tests/cfg/backingchain/blockpull/blockpull_with_async.cfg, libvirt/tests/src/backingchain/blockpull/blockpull_with_async.py, provider/backingchain/blockcommand_base.py
VIRT-294081: Do blockpull with --async option
```
avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 backingchain.blockpull.async_option.file_disk.async_timeout
(1/1) type_specific.io-github-autotest-libvirt.backingchain.blockpull.async_option.file_disk.async_timeout: PASS (99.67 s)
```
=> backingchain: add case for blockpull with async option

libvirt/tests/src/migration/migrate_with_virtual_devices.py, spell.ignore
DeviceNotRemovedError: Error in phase POST_MIGRATE_BACK:Device
rng is not removed from vm
tpm device also has a buitin rng device, so after detaching rng device, we can still see /dev/hwrng in vm. So need to remove tpm device from vm xml.
=> migration: Fix rng issue

libvirt/tests/cfg/cpu/iothread.cfg
In https://github.com/autotest/tp-libvirt/pull/4500, this vm state variable is missed for negative cases for thread poll test. This caused some cases fail.
=> iothread: fix var missing

libvirt/tests/cfg/virtual_disks/virtual_disks_snapshot_blockresize.cfg, libvirt/tests/src/virtual_disks/virtual_disks_snapshot_blockresize.py
Newly added cases to cover:do blockresize for device which has backing chain element
Create external disk-only snapshot, resizing block device with backing chain
should work as expected
=> Newly added cases to cover:do blockresize for device which has backing chain element

libvirt/tests/cfg/virtual_disks/virtual_disks_rerror_policy.cfg, libvirt/tests/src/virtual_disks/virtual_disks_rerror_policy.py
Fix virtual_disks set_rerror_policy_report case failure
the anticipated error message content has been changed, related python and cfg files are modified to adapt the change
=> Fix virtual_disks set_rerror_policy_report case failure

requirements-travis.txt
=> Fix travis CI failure on python3.7 due to importlib-metadata

libvirt/tests/src/sriov/failover/sriov_failover_migration.py
` (1/1) type_specific.io-github-autotest-libvirt.sriov.failover.migration.hostdev_device.with_precopy: PASS (468.93 s)
`
=> sriov_migration: Update to use aexpect.remote

libvirt/tests/cfg/virtual_disks/virtual_disks_optional_startuppolicy.cfg, libvirt/tests/src/virtual_disks/virtual_disks_optional_startuppolicy.py
Add case: start VM with optional startupPolicy(xx-294815)
As per BZ[1] using the option startupPolicy='optional' in hard disks backed by a file/block/volume device should work as expected
[1]https://bugzilla.redhat.com/show_bug.cgi?id=2109571
=> Add case: start VM with optional startupPolicy

libvirt/tests/cfg/memory/memory_misc.cfg, libvirt/tests/src/memory/memory_misc.py
- Start /destroy domain which is using hugepages from two numa node
- Verify property <hugepages/> works with source type=memfd
Test result:
```
(01/21) type_specific.io-github-autotest-libvirt.memory_misc.memorybacking.no_numa: CANCEL: This case is not supported by current libvirt. (6.61 s)
(02/21) type_specific.io-github-autotest-libvirt.memory_misc.memorybacking.mem_lock.no_limit: PASS (9.35 s)
(03/21) type_specific.io-github-autotest-libvirt.memory_misc.memorybacking.mem_lock.hard_limit: PASS (9.33 s)
(04/21) type_specific.io-github-autotest-libvirt.memory_misc.memorybacking.prealloc_thread.file_backed: PASS (49.64 s)
(05/21) type_specific.io-github-autotest-libvirt.memory_misc.memorybacking.prealloc_thread.memfd_backed: PASS (48.96 s) …
```
=> Add case of memory

libvirt/tests/cfg/virsh_cmd/domain/virsh_event.cfg, libvirt/tests/src/virsh_cmd/domain/virsh_event.py
This commit adds new test scenario to virsh_event where host is rebooted
via a console command and reboot event is checked to be present.
LIBVIRTAT-13464
VIRT-12705
```
JOB ID     : 40d0f5d54f7f84335c4bba2b513b4580d18f413c
JOB LOG    : /var/lib/avocado/job-results/job-2022-09-13T11.07-40d0f5d/job.log
(1/1) type_specific.io-github-autotest-libvirt.virsh.event.positive_test.virsh_event.test_events.reboot_from_console.no_timeout.loop: STARTED
(1/1) …
```
=> domain_lifecycle: check reboot event from inside guest

libvirt/tests/src/backingchain/blockcopy/blockcopy_with_blockdev_option.py
rm f folder in rhel8.8 get error, need rm rf
```
Get error while rm folder on    rhel 8.8 : d 'rm -f /dev/vg0' failed.\nstdout: b''\nstderr: 
b"rm: cannot remove '/dev/vg0': Is a directory\n"\
Test result after updated:
avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 backingchain.blockcopy.blockdev_option.file_disk.blockdev --vt-connect-uri qemu:///system
(1/1) type_specific.io-github-autotest-libvirt.backingchain.blockcopy.blockdev_option.file_disk.blockdev: PASS (46.62 s)
```
=> fix rm folder error

provider/backingchain/blockcommand_base.py
Snap will not show in virsh snapshot-list if create snap with --no-metadata 
=> fix miss snap in snap list

libvirt/tests/cfg/sriov/plug_unplug/sriov_attach_detach_interface_from_network.cfg, libvirt/tests/src/sriov/plug_unplug/sriov_attach_detach_interface_from_network.py
This PR adds:
VIRT-292861: Attach-interface to guest from a hostdev network
` (1/1) type_specific.io-github-autotest-libvirt.sriov.plug_unplug.attach_detach_interface_from_network: PASS (81.56 s)
`
=> sriov: Add a case about attaching a hostdev interface from network

libvirt/tests/src/virtual_disks/virtual_disks_nbd.py
Use `lsof` instead of `pgrep` to make sure the nbd server is really ready.
`pgrep` will always get the pid of `qemu-nbd` after the nbd server starts, whether or not the nbd server is really ready.
If the nbd server is not ready, the guest will fail to start.
Before:
```
///system
JOB ID : e8dd2f15d799e088b3ca469964cf21fbd368e52e 
JOB LOG : /var/lib/avocado/job-results/job-2022-09-21T10.27-e8dd2f1/job.log 
(1/1) type_specific.io-github-autotest-libvirt.virtual_disks.nbd.coldplug.enable_tls.default.enable_export.domain_operate.snap_shot: FAIL: VM should start but failed: VM 'avocado-vt-vm1' failed to start: error: Failed to start domain 'avocado-vt-vm1'\nerror: internal error: process exited while connecting to monitor: 2022-09-21T14:27:48.296106Z qemu-kvm: -blockdev …
```
=> virtual_disk: Fix nbd server is not ready

libvirt/tests/cfg/backingchain/blockcommit/blockcommit_relative_path.cfg, libvirt/tests/cfg/backingchain/blockpull/blockpull_relative_path.cfg, libvirt/tests/src/backingchain/blockcommit/blockcommit_relative_path.py, libvirt/tests/src/backingchain/blockpull/blockpull_relative_path.py
Need to create secret before add relative path to disk
```
Test error before  updated:
ERROR: VM 'avocado-vt-vm1' failed to start: error: Failed to start domain 'avocado-vt-vm1'\nerror: 
Secret not found: no secret with matching usage 'cephlibvirt' 
```
Test result:
```
avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 backingchain.blockpull.relative_path
(1/3) type_specific.io-github-autotest-libvirt.backingchain.blockpull.relative_path.file_disk.keep_relative: PASS (28.28 s)
(2/3) type_specific.io-github-autotest-libvirt.backingchain.blockpull.relative_path.block_disk.keep_relative: PASS (51.52 s)
(3/3) type_specific.io-github-autotest-libvirt.backingchain.blockpull.relative_path.rbd_with_auth_disk.keep_relative: PASS (33.62 …
```
=> fix relative path secret missed issue

libvirt/tests/cfg/memory/memory_misc.cfg
the hugepage for aarch64 are 2048/524288/16777216
Test Result:
```
JOB ID     : d3451cb6400c53f365ddf4c953f7c1e5ea3a32f2                                                                                                                                                                                        
JOB LOG    : /var/lib/avocado/job-results/job-2022-10-08T05.45-d3451cb/job.log                                                                                                                                                               
(1/2) type_specific.io-github-autotest-libvirt.memory_misc.memorybacking.nodeset_specified.nodeset_0: PASS (4.30 s)                                                                                                                         
(2/2) …
```
=> memory_misc: Enable memorybacking nodeset tests for aarch64

libvirt/tests/cfg/numa/numa_memory.cfg, libvirt/tests/src/numa/numa_memory.py
On special numa hosts, the numa node with memory is not continous. So we need to adjust the usable numa node for test instead of using hardcoded numa node.
=> numa_memory: fix incorrect numa node usage

libvirt/tests/cfg/sriov/plug_unplug/sriov_attach_released_hostdev.cfg, libvirt/tests/src/sriov/plug_unplug/sriov_attach_released_hostdev.py
This PR adds:
VIRT-294869: Hotplug a released hostdev again to the same or
another guest
```
(1/2) type_specific.io-github-autotest-libvirt.sriov.plug_unplug.attach_released_hostdev.to_2nd_vm: PASS (114.11 s)
(2/2) type_specific.io-github-autotest-libvirt.sriov.plug_unplug.attach_released_hostdev.to_itself: PASS (82.18 s)
```
=> sriov: Add a case about hotplug a released hostdev

libvirt/tests/src/virsh_cmd/domain/virsh_blockpull.py
Fix blockpull failure due to low timeout value
In some extreme case, current timeout value:1 second is not enough, so blockpull operation will be aborted
=> Fix blockpull failure due to low timeout value

provider/virtual_disk/disk_base.py
According to https://bugzilla.redhat.com/show_bug.cgi?id=2094205#c8:
We can't commit the contents of /dev/test/lv1 (libvirt-3-format, a qcow2 image of 300M) into /dev/test/lv0 (libvirt-1-format, a raw image of 200M) without first resizing the destination.
In test case, the lv0(raw) is 50M and the lv1(qcow2) is 200M, so update the size to be same.
=> disk_base.py: fix blockcommit failed issue for block disk

libvirt/tests/cfg/bios/boot_order_seabios.cfg, libvirt/tests/src/bios/boot_order_seabios.py
Add checks for boot order when cdrom device is used together with hard
disk. Multiple cdroms are checked. Hard drive fallback is checked.
VIRT-45959
```
(.libvirt-ci-venv-ci-runtest-SREiMk) [root@dell-per740-18 ~]# avocado run --vt-type libvirt boot_order_seabios..cd_dev
JOB ID     : 8b7e15dca98bcea140c9ab1071035e920ad0bba3
JOB LOG    : /var/lib/avocado/job-results/job-2022-08-25T12.58-8b7e15d/job.log
(1/6) …
```
=>  Bios: boot order of seabios guest with cdrom

libvirt/tests/cfg/migration/pause_postcopy_migration_and_recover/no_paused_during_recover_migration.cfg, libvirt/tests/src/migration/live_migration.py, libvirt/tests/src/migration/migrate_event.py, libvirt/tests/src/migration/migrate_service_control.py, libvirt/tests/src/migration/migrate_with_various_hostname.py, libvirt/tests/src/migration/pause_postcopy_migration_and_recover/no_paused_during_recover_migration.py, provider/migration/base_steps.py, provider/migration/migration_base.py
VIRT-294709 - [postcopy]VM live migration - recover migration when it is not paused
=> migration: Add case about recover migration

libvirt/tests/cfg/virtual_network/iface_update.cfg, libvirt/tests/src/virtual_network/iface_update.py
- RHEL7-99440:update portgroup of the interface for nat network
- RHEL-117419:update virtio driver attributes "iommu", "ats" (not support)
Depends on:
- https://github.com/avocado-framework/avocado-vt/pull/3542
- https://github.com/avocado-framework/avocado-vt/pull/3543
Test result:
``` 
(1/2) type_specific.io-github-autotest-libvirt.virtual_network.iface_update.positive_test.update_portgroup: PASS (12.41 s)
(2/2) type_specific.io-github-autotest-libvirt.virtual_network.iface_update.negative_test.update_driver_iommu_ast: PASS (22.17 s)
```
=> Add new cases of iface update

libvirt/tests/cfg/sriov/plug_unplug/sriov_attach_detach_interface_with_flags.cfg, libvirt/tests/src/sriov/plug_unplug/sriov_attach_detach_interface_with_flags.py
This PR adds:
VIRT-292860 - Attach/detach-interface of hostdev type with
various flags for vm states
```
(01/10) type_specific.io-github-autotest-libvirt.sriov.plug_unplug.attach_detach_interface_with_flags.no_option.offline_domain: PASS (21.77 s)
(02/10) type_specific.io-github-autotest-libvirt.sriov.plug_unplug.attach_detach_interface_with_flags.no_option.running_domain: PASS (37.00 s)
(03/10) type_specific.io-github-autotest-libvirt.sriov.plug_unplug.attach_detach_interface_with_flags.live.offline_domain: PASS (21.97 s)
(04/10) type_specific.io-github-autotest-libvirt.sriov.plug_unplug.attach_detach_interface_with_flags.live.running_domain: PASS (37.08 s)
(05/10) …
```
=> sriov: Add a case about attaching/detaching a hostdev interface with flags

libvirt/tests/cfg/sriov/plug_unplug/sriov_attach_detach_interface_special_situations.cfg, libvirt/tests/src/sriov/plug_unplug/sriov_attach_detach_interface_special_situations.py
This PR adds:
VIRT-294519: Attach/detach-interface of hostdev type to/from
guest for some special scenarios
```
(1/4) type_specific.io-github-autotest-libvirt.sriov.plug_unplug.attach_detach_interface_special_situations.no_detach_for_no_managed: PASS (54.74 s)
(2/4) type_specific.io-github-autotest-libvirt.sriov.plug_unplug.attach_detach_interface_special_situations.with_model: PASS (80.63 s)
(3/4) type_specific.io-github-autotest-libvirt.sriov.plug_unplug.attach_detach_interface_special_situations.module_auto_reload: PASS (81.27 s)
(4/4) type_specific.io-github-autotest-libvirt.sriov.plug_unplug.attach_detach_interface_special_situations.to_vm_with_hostdev_ifaces: PASS (82.40 s)
```
=> sriov: Add a case to attach/detach a hostdev interface

libvirt/tests/src/migration/migrate_vm.py
Don't need to check drive-mirror and nbd-server in live storage migration now. So update script.
=> migration: Remove check drive-mirror/nbd-server

virttools/tests/cfg/virt_install/kernel_cmdline.cfg
CentOS 9 now allows for long kernel command lines causing test failure. Use an older Fedora release instead.
=> virttools: Change installation tree location

provider/virtual_disk/disk_base.py
set_disk_xml function duplicate with create_vm_device_by_type
```
[root@dell-per740-07 tp-libvirt]# /usr/local/bin/avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 backingchain.blockcommit.keep_overlay
(1/2) type_specific.io-github-autotest-libvirt.backingchain.blockcommit.keep_overlay.positive_test.active: PASS (66.15 s)
(2/2) type_specific.io-github-autotest-libvirt.backingchain.blockcommit.keep_overlay.negative_test.inactive: PASS (64.75 s)
```
```
/usr/local/bin/avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 backingchain.blockcommit.base_image_exist_backingfile.file_disk
(1/8) type_specific.io-github-autotest-libvirt.backingchain.blockcommit.base_image_exist_backingfile.file_disk. …
```
=> fix set_disk_xml function duplicate

libvirt/tests/src/virtual_device/vsock.py
Device can not be hot unplugged immediately after hotplug.
Before:
```
JOB ID     : 43d3c455478606cf39b44ee8f05b2b1c7301b003                                                                                                                                                                                         
JOB LOG    : /var/lib/avocado/job-results/job-2022-10-17T04.12-43d3c45/job.log                                                                                                                                                                
(1/1) type_specific.io-github-autotest-libvirt.vsock.normal_test.hotplug.nop.auto_cid: FAIL: error: Failed to detach device from /tmp/xml_utils_temp__0pjfaxj.xml\nerror: internal error: unable to execute QEMU command 'device_del': Hot-un
plug failed: …
```
=> virtual_device: use EventTracker to wait for detach_device to complete

libvirt/tests/cfg/sriov/vIOMMU/sriov_virtio_iommu_with_addtional_attributes.cfg, libvirt/tests/src/sriov/vIOMMU/sriov_virtio_iommu_with_addtional_attributes.py
This PR adds:
- VIRT-294974 [virtio iommu] Test virtio iommu with addtional
attributes(unsuppoted)
```
(1/4) type_specific.io-github-autotest-libvirt.sriov.vIOMMU.virtio_iommu.addtional_attributes.caching_mode: PASS (16.28 s)
(2/4) type_specific.io-github-autotest-libvirt.sriov.vIOMMU.virtio_iommu.addtional_attributes.eim: PASS (16.37 s)
(3/4) type_specific.io-github-autotest-libvirt.sriov.vIOMMU.virtio_iommu.addtional_attributes.iotlb: PASS (16.45 s)
(4/4) type_specific.io-github-autotest-libvirt.sriov.vIOMMU.virtio_iommu.addtional_attributes.aw_bits: PASS (16.88 s)
```
=> sriov: Add a case about virtio iommu

libvirt/tests/src/backingchain/blockcommit/blockcommit_relative_path.py, libvirt/tests/src/backingchain/blockpull/blockpull_relative_path.py, provider/virtual_disk/disk_base.py
blockcommit and blockpull relative case miss the ceph config file
```
/usr/local/bin/avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 backingchain.blockcommit.relative_path.rbd_with_auth_disk.keep_relative.active --vt-connect-uri qemu:///system
(1/2) type_specific.io-github-autotest-libvirt.backingchain.blockcommit.relative_path.rbd_with_auth_disk.keep_relative.active.vm_started: PASS (32.47 s)
(2/2) type_specific.io-github-autotest-libvirt.backingchain.blockcommit.relative_path.rbd_with_auth_disk.keep_relative.active.vm_paused: PASS (35.32 s)
```
=> fix missing ceph config file

libvirt/tests/cfg/virsh_cmd/domain/virsh_blockresize.cfg, libvirt/tests/src/virsh_cmd/domain/virsh_blockresize.py
Resize a block size to a value that's not a multiple of 1024,
and actual size need align with a multiple of 1024
=> Automate test case:resize a block size

libvirt/tests/src/remote_access/remote_access.py
Fix below error:
- UnboundLocalError: local variable 'ssh_config_backup_path' referenced before assignment
=> remote_access: fix UnboundLocalError

libvirt/tests/src/remote_access/remote_access.py
Fix below error:
UnboundLocalError: local variable 'openssl_config_path' referenced before assignment
It is similar to https://github.com/autotest/tp-libvirt/pull/4612
=> remote_access: fix not assignment

libvirt/tests/cfg/bios/boot_order_ovmf.cfg, libvirt/tests/src/bios/boot_order_ovmf.py
This PR adds script for automating VIRT-45958. It checks boot
element in <os> part of VMXML. The device is always hd.
```
avocado run --vt-type libvirt boot_order_ovmf..boot_dev
JOB ID     : 9bf86fd8dcf208a7a4ec64da4b827d507a6c4c6c
JOB LOG    : /var/lib/avocado/job-results/job-2022-08-31T08.48-9bf86fd/job.log
(1/4) type_specific.io-github-autotest-libvirt.boot_order_ovmf.positive_test.bootable_dev.boot_dev.hd_dev: STARTED
(1/4) …
```
=> bios: Boot order for OVMF guest with dev=hd

libvirt/tests/cfg/virtual_device/sound_device.cfg, libvirt/tests/src/virtual_device/sound_device.py
This commit adds a check for ich9 sound device. When ich9 sound device is added it's address slot should be 0xb1 by default after VM start.
LIBVIRTAT-13557
VIRT-89396
```
[root@dell-per740-03 ~]# avocado run --vt-type libvirt virtual_devices.sound_device.positive_test.sound_model_ich9.codec_type_duplex
JOB ID     : 6a740a6da99bcf757e6ea5bbd55377e4c73c3e30
JOB LOG    : /var/lib/avocado/job-results/job-2022-10-07T11.11-6a740a6/job.log
(1/1) …
```
=> virtual_devices: Sound dev default address slot

libvirt/tests/cfg/numa/numa_memory.cfg, libvirt/tests/src/numa/numa_memory.py
When vm fails to start, we should check the error message which are included in the manual test cases.
=> numa_memory: add checkpoints for VMStartError

libvirt/tests/cfg/sriov/vIOMMU/sriov_iommu_alias.cfg, libvirt/tests/src/sriov/vIOMMU/sriov_iommu_alias.py, provider/sriov/sriov_base.py
This PR adds:
- VIRT-294976: [vIOMMU] Add alias support for iommu device
Depends on:
- https://github.com/avocado-framework/avocado-vt/pull/3552
- https://github.com/avocado-framework/avocado-vt/pull/3553
```
(1/4) type_specific.io-github-autotest-libvirt.sriov.vIOMMU.iommu.alias.auto_gen.virtio: PASS (19.06 s)
(2/4) type_specific.io-github-autotest-libvirt.sriov.vIOMMU.iommu.alias.auto_gen.intel: PASS (19.31 s)
(3/4) type_specific.io-github-autotest-libvirt.sriov.vIOMMU.iommu.alias.customized.virtio: PASS (19.22 s)
(4/4) type_specific.io-github-autotest-libvirt.sriov.vIOMMU.iommu.alias.customized.intel: PASS (19.15 s)
```
=> sriov: Add a case to test vIOMMU device's alias

libvirt/tests/cfg/migration/migrate_storage.cfg, libvirt/tests/src/migration/migrate_storage.py
RHEL-196405 - [Migration][tls][tls-destination] Migrate vm with
copy storage - Native TLS(--tls) - with specified tls hostname
=> migration: Add case about specified tls hostname

libvirt/tests/src/numa/numa_memory_spread.py
Now the memory of some servers has exceeded 500G, so the memory that the guest needs to consume can reach about 300G in this case. Because across numa nodes, sometimes 120s is not enough for memhog.
Result:
```
JOB ID     : 7c064d9195c45cb96992e94be5b6351ab7018329
JOB LOG    : /root/avocado/job-results/job-2022-10-19T03.04-7c064d9/job.log
(1/1) type_specific.io-github-autotest-libvirt.numa_memory_spread.positive_test.default: PASS (369.98 s)
JOB HTML   : /root/avocado/job-results/job-2022-10-19T03.04-7c064d9/results.html
JOB TIME   : 370.60 s
```
=> numa_memory_spread: extend timeout for memhog

libvirt/tests/cfg/sriov/nodedev/sriov_nodedev_reattach_detach.cfg, libvirt/tests/src/sriov/nodedev/sriov_nodedev_reattach_detach.py
This PR adds:
- VIRT-294650: Nodedev-reattach/detach a VF device to/from host
```
(1/2) type_specific.io-github-autotest-libvirt.sriov.nodedev.nodedev_reattach_detach.vf: PASS (41.60 s)
(2/2) type_specific.io-github-autotest-libvirt.sriov.nodedev.nodedev_reattach_detach.pf: PASS (44.81 s)
```
=> sriov: Add a case about nodedev reatach/detach

libvirt/tests/src/virsh_cmd/domain/virsh_blockcommit.py
do several times blockcommit with pivot get lock error due to run too fast
Before updated:
```
/bin/virsh blockcommit avocado-vt-vm1 vda  --active --pivot '
2022-10-19 00:42:27,539 virsh            L1246 ERROR| Error taking VM avocado-vt-vm1 screenshot. 
You might have to set take_regular_screendumps=no on your tests.cfg config file Command
'/bin/virsh -c 'qemu:///system' screenshot avocado-vt-vm1 /dev/shm/scrdump-2YIdQG-iter0.ppm' 
failed.stdout: b'\n'stderr: b'error: could not take a screenshot of avocado-vt-vm1\nerror: Timed out
during operation: cannot acquire state change lock (held by monitor=remoteDispatchDomainBlockJobAbort)\n
'additional_info: None.  This will be the only logged error message.
2022-10-19 00:42:27,540 env_process      L1969 …
```
=> fix cannot acquire state change lock

libvirt/tests/src/bios/boot_integration.py, libvirt/tests/src/bios/virsh_boot.py
According to xml updates of VMOSXML class
Depends on:
- https://github.com/avocado-framework/avocado-vt/pull/3557
=> Replace nvram_template with nvram_attrs

libvirt/tests/src/virsh_cmd/domain/virsh_cpu_stats.py
It's better to use math.isclose() to check if the floating point numbers are equal, due to precision errors in floating point calculations.
=> virsh_cpu_stats: Fix comparison of floating point numbers

libvirt/tests/cfg/sriov/plug_unplug/sriov_attach_detach_interface.cfg, libvirt/tests/src/sriov/plug_unplug/sriov_attach_detach_interface.py
This PR adds:
VIRT-294710: Attach/detach-interface of hostdev type to/from guest
```
(1/2) type_specific.io-github-autotest-libvirt.sriov.plug_unplug.attach_detach_interface.with_managed: PASS (79.22 s)
(2/2) type_specific.io-github-autotest-libvirt.sriov.plug_unplug.attach_detach_interface.without_managed: PASS (80.79 s)
```
=> sriov: Add a case of attaching hostdev interface

libvirt/tests/cfg/backingchain/blockcopy/blockcopy_with_disk_driver_attributes.cfg, libvirt/tests/src/backingchain/blockcopy/blockcopy_with_disk_driver_attributes.py
VIRT-294782: Do blockcopy to target disk with different attributes of driver elements
```
/usr/local/bin/avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 backingchain.blockcopy.disk.driver_attr.metadata_cache
(1/1) type_specific.io-github-autotest-libvirt.backingchain.blockcopy.disk.driver_attr.metadata_cache: PASS (57.34 s)
```
=> backingchain:add case for blockcopy with disk driver elements

libvirt/tests/cfg/backingchain/negative_scenario/blockpull_with_invalid_base.cfg, libvirt/tests/src/backingchain/negative_scenario/blockpull_with_invalid_base.py
VIRT-294591: Do blockpull with invalid base image
Test result:
```
avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 backingchain.negative.blockpull.invalid_base
(1/2) type_specific.io-github-autotest-libvirt.backingchain.negative.blockpull.invalid_base.active_as_base: PASS (23.57 s)
(2/2) type_specific.io-github-autotest-libvirt.backingchain.negative.blockpull.invalid_base.not_existing_path: PASS (19.72 s)
```
=> backingchain: add case for blockpull with invalid base image

libvirt/tests/cfg/bios/vm_boot_nvram_source.cfg, libvirt/tests/src/bios/vm_boot_nvram_source.py
Depends on:
- https://github.com/avocado-framework/avocado-vt/pull/3557
Test result:
```
PASS 1-type_specific.io-github-autotest-libvirt.vm_boot.nvram_source.file
```
=> Add case of Starting vm with file source backed NVRAM

libvirt/tests/cfg/virtual_disks/virtual_disks_alias.cfg, libvirt/tests/src/virtual_disks/virtual_disks_alias.py
Automate case:live update cdrom device with alias
live update disk alias from current alias to another, and also from current alias to none
=> Automate case:live update cdrom device with alias

libvirt/tests/cfg/backingchain/blockcopy/blockcopy_with_granularity_buf_size_option.cfg, libvirt/tests/src/backingchain/blockcopy/blockcopy_with_granularity_buf_size_option.py
Automate case:
VIRT-294528 - Do blockcopy with --buf-size or --granularity option
Test Result:
```
JOB ID     : ffed7c03cfc3ddc3854e759efa45ca09631a5d6e
JOB LOG    : /var/lib/avocado/job-results/job-2022-10-28T03.06-ffed7c0/job.log
(1/6) type_specific.io-github-autotest-libvirt.backingchain.blockcopy.granularity_buf-size.positive_test.granularity: PASS (72.31 s)
(2/6) type_specific.io-github-autotest-libvirt.backingchain.blockcopy.granularity_buf-size.positive_test.buf-size: PASS (76.59 s)
(3/6) type_specific.io-github-autotest-libvirt.backingchain.blockcopy.granularity_buf-size.negative_test.granularity.little_than_512B: PASS (75.35 s)
(4/6) type_specific.io-github-autotest-libvirt.backingchain.blockcopy.granularity_buf-size.negative_test.granularity.more_than_64MB: PASS (76.22 s)
(5/6) …
```
=> Backingchain: add new case for blockcopy with granularity and buf-size

libvirt/tests/cfg/svirt/selinux_relabel.cfg
The serial->target->type for character device on aarch64 is `system-serial`, and the usable model for system-serial is `pl011`.
Test Result:
```
JOB ID     : db93bc13c4d164747f77442c71e119923c5a7c7c
JOB LOG    : /root/avocado/job-results/job-2022-11-03T03.32-db93bc1/job.log
(1/1) type_specific.io-github-autotest-libvirt.selinux_relabel.unix_socket: PASS (5.50 s)
JOB HTML   : /root/avocado/job-results/job-2022-11-03T03.32-db93bc1/results.html
JOB TIME   : 5.86 s
```
=> svirt: Enable selinux_relabel test for aarch64

libvirt/tests/src/virtual_disks/virtual_disks_scsi3_persistent_reservation.py
The device may not be ready on guest immediately after attaching device, just wait at most 5 seconds here.
Before:
```
JOB ID     : b73830db6845b986fae86339cff1be363fcf9b4f
JOB LOG    : /var/lib/avocado/job-results/job-2022-11-03T11.18-b73830d/job.log
(1/1) type_specific.io-github-autotest-libvirt.virtual_disks.scsi3_persistent_reservation.reservations_managed.hotplug_disk.enable_auth.auth_usage.auth_out_source:  ERROR: list index out of range (65.69 s)
JOB HTML   : /var/lib/avocado/job-results/job-2022-11-03T11.18-b73830d/results.html
JOB TIME   : 66.18 s
```
After:
```
JOB ID     : 6036e69162d2dffe0a5f1b506c1f7a008d3b6768
JOB LOG    : /var/lib/avocado/job-results/job-2022-11-04T05.23-6036e69/job.log
(1/1) …
```
=> virtual_disk: Wait for device is ready on guest after attach-device

libvirt/tests/src/remote_access/remote_access.py
Changes in commit dfe4159a broke test run on RHEL-8 and lower, because the configuration introduced by it works only on RHEL-9 and bigger.
This commit tries to fix the crashes by checking RHEL version before running the updated code.
Related test case: VIRT-18307
=> remote_access, ensure dfe4159a works on older RHEL

libvirt/tests/src/virsh_cmd/domain/virsh_event.py
Fix event block threshold failure due to mkfs.ex4 command timeout
During the testing, it need send mkfs.ex4 to Vm, but timeout happen So extend command timeout value to 90 seconds
=> Fix event block threshold failure due to mkfs.ex4 command timeout

libvirt/tests/cfg/virtual_network/iface_attach_detach.cfg, libvirt/tests/src/virtual_network/iface_attach_detach.py
- VIRT-110831 - hotplug an interface with boot order
Test result:
```
(1/8) type_specific.io-github-autotest-libvirt.virtual_network.iface_attach_detach.boot_order.with_os_boot.hot: PASS (9.78 s)
(2/8) type_specific.io-github-autotest-libvirt.virtual_network.iface_attach_detach.boot_order.with_os_boot.cold: PASS (14.03 s)
(3/8) type_specific.io-github-autotest-libvirt.virtual_network.iface_attach_detach.boot_order.with_boot_disk.hot: PASS (10.26 s)
(4/8) type_specific.io-github-autotest-libvirt.virtual_network.iface_attach_detach.boot_order.with_boot_disk.cold: PASS (16.71 s)
(5/8) type_specific.io-github-autotest-libvirt.virtual_network.iface_attach_detach.boot_order.unsupported_value.-1.hot: PASS (8.96 s)
(6/8) …
```
=> Add new case of attaching iface

provider/sriov/sriov_base.py
VM interface may not exist due to a bug in some cases.
Test result: This case failed due to a bug.
` (1/1) type_specific.io-github-autotest-libvirt.sriov.plug_unplug.attach_detach_device.hostdev_device.pf_address.managed_yes: ERROR: Unable to get VM's interface! (49.62 s)`
=> sriov: Update to check if the vm interface exists

libvirt/tests/src/virtual_disks/virtual_disks_dasd.py
Fix virtual_disks dasd failure on s390x
Sometimes, this case failed in process of disabling dasd So it can enchance this situation by adding explicitly detach disk and gracefully shutdown VM before disabling dasd
=> Fix virtual_disks dasd failure on s390x

libvirt/tests/cfg/backingchain/blockjob/blockjob_pivot_after_irregular_operations.cfg, libvirt/tests/src/backingchain/blockjob/blockjob_pivot_after_irregular_operations.py
VIRT-294594: Do blockjob --pivot after irregular operations
```
usr/local/bin/avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35  backingchain.blockjob.pivot
(1/2) type_specific.io-github-autotest-libvirt.backingchain.blockjob.pivot.before_finish: PASS (192.34 s)
(2/2) type_specific.io-github-autotest-libvirt.backingchain.blockjob.pivot.delete_copy_file: PASS(50.40 s)
```
=> backingchain: add case for blockjob pivot after irregular operation

libvirt/tests/src/virsh_cmd/domain/virsh_start.py
'ausearch -m AVC' will search the entire audit log for AVC errors, here use the `--start` parameter to check only the logs generated for this case.
Test Result:
```
JOB ID     : 63480cd2f7f3c4c47e513d0fc78f247960a772b1
JOB LOG    : /var/lib/avocado/job-results/job-2022-11-07T02.50-63480cd/job.log
(1/1) type_specific.io-github-autotest-libvirt.virsh.start.status_error_no.audit_log_search: PASS (5.11 s)
JOB HTML   : /var/lib/avocado/job-results/job-2022-11-07T02.50-63480cd/results.html
JOB TIME   : 5.51 s
```
=> virsh_start: Just check the audit log generated in this case

libvirt/tests/cfg/passthrough/ap/libvirt_ap_passthrough.cfg, libvirt/tests/cfg/passthrough/ap/libvirt_ap_passthrough_autostart.cfg, libvirt/tests/cfg/passthrough/ap/libvirt_ap_passthrough_hotplug.cfg, libvirt/tests/src/passthrough/ap/libvirt_ap_passthrough_hotplug.py, provider/vfio/ap.py, provider/vfio/mdev_handlers.py, spell.ignore
1. Tidy up libvirt_ap_passthrough test types and names to be more
consistent.
2. Create new test to confirm crypto devices can be hot plugged and
unplugged if set up on a mediated device. As we can't modify the
available crypto devices on an LPAR or z/VM, the test case
creates a mediated device on the host to control device availability
for a KVM guest. It creates another mediated device in that guest
to confirm that the guest_matrix is updated. Therefore, both host
and guest kernel need to support vfio_ap hotplug.
=> ap_passthrough: add hw hotplug test

libvirt/tests/cfg/memory/memory_misc.cfg
memory_misc..size_check requires memory hotplug which is not available on s390x.
=> memory_misc: disable test on s390x

libvirt/tests/cfg/backingchain/blockcopy/blockcopy_with_bandwidth.cfg, libvirt/tests/src/backingchain/blockcopy/blockcopy_with_bandwidth.py
VIRT-294530: Do blockcopy with --bandwidth option
```
/usr/local/bin/avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 backingchain.blockcopy.bandwidth
(1/4) type_specific.io-github-autotest-libvirt.backingchain.blockcopy.bandwidth.positive_test.mb: PASS (48.18 s)
(2/4) type_specific.io-github-autotest-libvirt.backingchain.blockcopy.bandwidth.positive_test.bytes: PASS (50.77 s)
(3/4) type_specific.io-github-autotest-libvirt.backingchain.blockcopy.bandwidth.negative_test.letter: PASS (49.82 s)
(4/4) type_specific.io-github-autotest-libvirt.backingchain.blockcopy.bandwidth.negative_test.number: PASS (48.76 s)
```
=> backingchain:blockcopy with bandwidth option

libvirt/tests/cfg/backingchain/blockcopy/blockcopy_with_xml_option_to_luks_slice_image.cfg, libvirt/tests/src/backingchain/blockcopy/blockcopy_with_xml_option_to_luks_slice_image.py, provider/backingchain/blockcommand_base.py, provider/backingchain/check_functions.py
VIRT-294441: Do blockcopy with --xml option to destination image with luks and slices
```
/usr/local/bin/avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35  backingchain.blockcopy.xml_option.luks_slice_image
(1/4) type_specific.io-github-autotest-libvirt.backingchain.blockcopy.xml_option.luks_slice_image.file_disk.finish_reuse_external: PASS (60.83 s)
(2/4) type_specific.io-github-autotest-libvirt.backingchain.blockcopy.xml_option.luks_slice_image.file_disk.pivot_reuse_external: PASS (62.99 s)
(3/4) type_specific.io-github-autotest-libvirt.backingchain.blockcopy.xml_option.luks_slice_image.block_disk.finish_reuse_external: PASS (61.99 s)
(4/4) type_specific.io-github-autotest-libvirt.backingchain.blockcopy.xml_o …
```
=> backingchain:add case for blockcopy with xml to dest image with luks and slices

libvirt/tests/src/virsh_cmd/nodedev/crypto_nodedev_create_destroy.py
Fix virsh crypto nodedev failure
Sometimes, the mdev device is still found after destroyed 
So it enchance this situation by adding time sleep after destroy
=> Fix virsh crypto nodedev failure

libvirt/tests/src/sriov/plug_unplug/sriov_attach_detach_device_with_flags.py, libvirt/tests/src/sriov/plug_unplug/sriov_attach_detach_interface_with_flags.py
Correct the previous condition for accessing the vm. And the serial session needs to be recreated in some cases, update the code accordingly.
```
(01/26) type_specific.io-github-autotest-libvirt.sriov.plug_unplug.attach_detach_interface_with_flags.no_option.offline_domain: PASS (22.31 s)
(02/26) type_specific.io-github-autotest-libvirt.sriov.plug_unplug.attach_detach_interface_with_flags.no_option.running_domain: PASS (74.78 s)
(03/26) type_specific.io-github-autotest-libvirt.sriov.plug_unplug.attach_detach_interface_with_flags.live.offline_domain: PASS (22.21 s)
(04/26) type_specific.io-github-autotest-libvirt.sriov.plug_unplug.attach_detach_interface_with_flags.live.running_domain: PASS (56.14 s)
(05/26) …
```
=> sriov: Update to attach an interface after the vm is fully started

libvirt/tests/src/virsh_cmd/host/virsh_nodememstats.py
Description: libvirtd is restarted after issuing virsh commands from libvirt version 5.6.0 on. Hence need to fix test expectations when libvirtd is off
=> Fix for nodememstats failure when libvirtd is off

libvirt/tests/cfg/virsh_cmd/domain/virsh_detach_serial_device_alias.cfg
isa-serial and pci-serial are not available on s390x.
=> virsh.detach_serial_device_alias: disable on s390

v2v/tests/src/function_test_xen.py
1. The 'update-crypto-policies --set LEGACY' changes the whole system setting which is not recommended by v2v.
The new way is a new solution of doing same thing.
2. Delete the orphan function set_graphics.
=> v2v: update the way of enabling sha1 algorithm

libvirt/tests/cfg/virtual_disks/virtual_disks_backingstore_disk.cfg, libvirt/tests/src/virtual_disks/virtual_disks_backingstore_disk.py
Automate case: start guest with disk backingStore type = volume [1]
Vm can be started sucessfully when Vm has additional disk with volume backingStore type
[1]https://bugzilla.redhat.com/show_bug.cgi?id=1804603
=> Automate case: start guest with volume backingStore disk

libvirt/tests/cfg/virtual_device/tpm_device.cfg, libvirt/tests/src/virtual_device/tpm_device.py
Including add active_pcr_banks for version default scenario, add invalid tpm model test, add text 'default' value for backend version test.
=> tpm_device: some xml config test of bz2084046

libvirt/tests/cfg/sriov/plug_unplug/sriov_attach_interface_to_vm_with_vf.cfg, libvirt/tests/src/sriov/plug_unplug/sriov_attach_interface_to_vm_with_vf.py
This PR adds a case(VIRT-294712) to attach a hostdev interface while the guest contains VF.
```
(1/1) type_specific.io-github-autotest-libvirt.sriov.plug_unplug.attach_interface_to_vm_with_vf: PASS (51.24 s)
JOB HTML   : /var/lib/avocado/job-results/job-2022-11-09T01.15-ff4aba7/results.html
```
=> sriov: Add a case

libvirt/tests/cfg/memory/memory_misc.cfg, libvirt/tests/src/memory/memory_misc.py
- VIRT-295935 - Mount 1G hugepage path for a running guest vm backed by 2M hugepage memory - bug2123196
Test result:
```
<domain type='kvm' id='1'>
...
<maxMemory slots='16' unit='KiB'>15243264</maxMemory>
<memory unit='KiB'>3145728</memory>
<currentMemory unit='KiB'>3145728</currentMemory>
<memoryBacking>
<hugepages>
<page size='2048' unit='KiB'/>
</hugepages>
</memoryBacking>
<vcpu placement='static'>4</vcpu>
...
<cpu mode='custom' match='exact' check='full'>
<model fallback='forbid'>Haswell-noTSX-IBRS</model>
<vendor>Intel</vendor>
<feature policy='require' name='vme'/>
...
<numa>
<cell id='0' cpus='0-1' memory='1048576' unit='KiB'/>
<cell id='1' cpus='2-3' memory='1048576' unit='KiB'/>
</numa>
</cpu>
...
<memory model='dimm'>
<source> …
```
=> Add new case of memory test

libvirt/tests/cfg/migration/destructive_operations_around_live_migration/migration_kill_libvirt_daemon.cfg, libvirt/tests/cfg/migration/migrate_service_control.cfg, libvirt/tests/cfg/migration/migration_uri/migration_network_data_transport_tls.cfg, libvirt/tests/cfg/migration/pause_postcopy_migration_and_recover/pause_and_recover_and_disruptive.cfg, libvirt/tests/cfg/migration/pause_postcopy_migration_and_recover/pause_and_recover_twice.cfg, libvirt/tests/cfg/migration/pause_postcopy_migration_and_recover/pause_by_domjobabort_and_recover.cfg, libvirt/tests/cfg/migration/pause_postcopy_migration_and_recover/pause_by_network_and_recover.cfg, libvirt/tests/cfg/migration/pause_postcopy_migration_and_recover/pause_by_proxy_and_recover.cfg, libvirt/tests/cfg/migration/pause_postcopy_migration_and_recover/unattended_migration.cfg, libvirt/tests/cfg/migration/pause_postcopy_migration_and_recover/unattended_migration_and_disruptive.cfg, libvirt/tests/src/migration/migrate_service_control.py, libvirt/tests/src/migration/pause_postcopy_migration_and_recover/pause_and_recover_and_disruptive.py, libvirt/tests/src/migration/pause_postcopy_migration_and_recover/pause_and_recover_twice.py, libvirt/tests/src/migration/pause_postcopy_migration_and_recover/pause_by_domjobabort_and_recover.py, libvirt/tests/src/migration/pause_postcopy_migration_and_recover/pause_by_network_and_recover.py, libvirt/tests/src/migration/pause_postcopy_migration_and_recover/pause_by_proxy_and_recover.py, libvirt/tests/src/migration/pause_postcopy_migration_and_recover/unattended_migration.py, libvirt/tests/src/migration/pause_postcopy_migration_and_recover/unattended_migration_and_disruptive.py, provider/migration/base_steps.py, provider/migration/migration_base.py
VIRT-294698 - [postcopy]VM live migration - pause migration by domjobabort->recover it
VIRT-294701 - [postcopy]VM live migration - pause migration due to network issue->recover it
VIRT-294700 - [postcopy]VM live migration - pause migration due to proxy issue->recover it - UNIX+proxy transport
VIRT-294703 - [postcopy]VM live migration - pause migration->recover it and failed->recover it
VIRT-294699 - [postcopy]VM live migration - make migration become unattended migration
VIRT-294708 - [postcopy]VM live migration - make migration become unattended migration->do disruptive operations during unattended migration
=> migration: Add case about pause/recover migration

libvirt/tests/cfg/migration/migrate_graphics.cfg, libvirt/tests/src/migration/migrate_graphics.py, provider/migration/base_steps.py
Test scenario: Test migration with graphic device whose listening type is socket and
socket file could be generated correctly after migration
Case ID: VIRT-89391
=> migration_graphics: add case with graphics socket

libvirt/tests/src/virsh_cmd/domain/virsh_dump.py
Newer version of avocado (>93) depreates use of allow_output_check with various process.<...> api's. Remove this switch to avoid test failures.
=> ras tests: remove deprecated allow_output_check switch

libvirt/tests/cfg/virtual_network/iface_update.cfg, libvirt/tests/src/virtual_network/iface_update.py
- VIRT-99433 - update boot order in interface
Test result:
```
(01/50) type_specific.io-github-autotest-libvirt.virtual_network.iface_update.positive_test.update_bandwidth: PASS (10.21 s)
(02/50) type_specific.io-github-autotest-libvirt.virtual_network.iface_update.positive_test.update_link: PASS (48.32 s)
(03/50) type_specific.io-github-autotest-libvirt.virtual_network.iface_update.positive_test.update_link_with_rom: PASS (48.26 s)
(04/50) type_specific.io-github-autotest-libvirt.virtual_network.iface_update.positive_test.update_link_without_addr: PASS (47.46 s)
(05/50) type_specific.io-github-autotest-libvirt.virtual_network.iface_update.positive_test.update_link_diff_type: PASS (58.77 s)
(06/50) …
```
=> Add new case of interface update

libvirt/tests/cfg/numa/numa_memory.cfg
For aarch64, if the nodeset is out of range, the error message is "Numerical result out of range" when starting the vm.
Before:
```
JOB ID     : 100758afd818d602b89d8ad126f420d6b7644616                                                                                                                                                                                        
JOB LOG    : /var/lib/avocado/job-results/job-2022-12-02T04.21-100758a/job.log                                                                                                                                                               
(1/1) type_specific.io-github-autotest-libvirt.numa_memory.negative_test.out_range.strict: FAIL: Expect should fail with one of ['NUMA node.*unavailable'], but failed with:\nerror: Failed to …
```
=> numa_memory: Check appropriate error messages for aarch64

libvirt/tests/cfg/controller/pcie_root_port_controller.cfg, libvirt/tests/src/controller/pcie_root_port_controller.py
This PR adds checks for target chassis and ports for PCIe controllers.
VIRT-55416
```
[root@dell-per740xd-25 ~]# avocado run --vt-type libvirt pcie_controllers.positive_tests.controllers_different_chassis_same_port.hotplug_off pcie_controllers.negative_tests.controllers_same_chassis_same_port.hotplug_off pcie_controllers.negative_tests.controllers_same_chassis_different_port.hotplug_off
JOB ID     : 590302295e207d3a946f0e78348ecc0ba4086b69
JOB LOG …
```
=> PCIe: pcie-root-port chassis and port checks

libvirt/tests/cfg/virsh_cmd/domain/virsh_detach_device_alias.cfg, libvirt/tests/src/sriov/capabilities/sriov_capabilities_iommu_support.py, libvirt/tests/src/virsh_cmd/domain/virsh_detach_device_alias.py
RHEL-148233: Device can also be detached by 'virsh detach-device-alias' cmd
Depends on : https://github.com/avocado-framework/avocado-vt/pull/3576 
```
/usr/local/bin/avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 virsh.detach_device_alias..hostdev.pci
(1/3) type_specific.io-github-autotest-libvirt.virsh.detach_device_alias.live.hostdev.pci: PASS (93.61 s)
(2/3) type_specific.io-github-autotest-libvirt.virsh.detach_device_alias.config.hostdev.pci: PASS (90.11 s)
(3/3) type_specific.io-github-autotest-libvirt.virsh.detach_device_alias.current.hostdev.pci: PASS (93.19 s)
/usr/local/bin/avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 virsh.detach_device_alias..hostdev.scsi
(1/3) …
```
=> add case for detach hostdev-pci with alias

libvirt/tests/cfg/backingchain/blockjob/blockjob_with_async_option.cfg, libvirt/tests/src/backingchain/blockjob/blockjob_with_async_option.py
This PR adds:
VIRT-294691 - Abort a block job with --async option
```
JOB ID     : 7606e551ada289234c8110fe7f05b9706ddf9528
JOB LOG    : /var/lib/avocado/job-results/job-2022-11-06T22.00-7606e55/job.log
(1/1) type_specific.io-github-autotest-libvirt.backingchain.blockjob.async.async_option: PASS (71.53 s)
JOB HTML   : /var/lib/avocado/job-results/job-2022-11-06T22.00-7606e55/results.html
JOB TIME   : 75.02 s
```
=> Backingchain: add new case for blockjob with --async

libvirt/tests/src/virtual_disks/virtual_disks_multidisks.py
Fix qemu command line output failure on s390x
qemu command is json format output, so need update it on s390x as well
=> Fix qemu command line output failure on s390x

libvirt/tests/cfg/backingchain/virsh_domblk/domblkthreshold_with_backingchain_element.cfg, libvirt/tests/src/backingchain/virsh_domblk/domblkthreshold_with_backingchain_element.py, provider/backingchain/blockcommand_base.py
VIRT-294599: Do domblkthreshold for device with backing chain element
Test result: 
```
/usr/local/bin/avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35  backingchain.virsh_domblk
(1/2) type_specific.io-github-autotest-libvirt.backingchain.virsh_domblk_test.backing_target: PASS (67.25 s)
(2/2) type_specific.io-github-autotest-libvirt.backingchain.virsh_domblk_test.entire_disk: PASS (75.23 s)
```
=> backingchain:add case for domblkthreshold with backing chain element

libvirt/tests/cfg/virtual_disks/virtual_disks_scsi3_persistent_reservation.cfg, libvirt/tests/src/virtual_disks/virtual_disks_scsi3_persistent_reservation.py
For previous virtual_disks.scsi3_persistent_reservation.reservations_managed..enable_auth.auth_usage.auth_in_source, it's actually invalid to test auth feature in this block lun disk with reservation. In order to reduce misleading when debugging, the auth checking has been removed  in this PR.
=> virtual_disk: remove auth checking for block lun disk

libvirt/tests/cfg/backingchain/blockcopy/blockcopy_with_different_qcow2_properties.cfg, libvirt/tests/src/backingchain/blockcopy/blockcopy_with_different_qcow2_properties.py, provider/backingchain/blockcommand_base.py
VIRT-294532: Check qcow2 properties after blockcopy
Test result:
```
/usr/local/bin/avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 backingchain.blockcopy.image_properties
JOB LOG    : /var/lib/avocado/job-results/job-2022-11-21T21.04-9076fbe/job.log
(1/2) type_specific.io-github-autotest-libvirt.backingchain.blockcopy.image_properties.not_encrypt_disk.extended_l2_and_cluster_size: PASS (65.97 s)
(2/2) type_specific.io-github-autotest-libvirt.backingchain.blockcopy.image_properties.encrypt_disk.extended_l2_and_cluster_size: PASS (62.87 s)
```
=> backingchain: add case for blockcopy with different qcow2 properities

libvirt/tests/cfg/virsh_cmd/domain/virsh_cpu_xml.cfg
Change the cpu definition xml back to original file to get the expected error message for the negative test.
=> virsh_cpu_xml: Change cpu xml back to original file for negative test

libvirt/tests/src/virsh_cmd/snapshot/virsh_snapshot_edit.py
Make sure the guest boot successfully before creating snapshot, otherwise it may fail.
Before:
```
snapshot --vt-connect-uri qemu:///system                                                                                                                                                                                                                                                                             
JOB ID     : 75dcc0e77481b4331486d35554502bb1934f06e9                                          
JOB LOG    : /var/lib/avocado/job-results/job-2022-07-06T05.09-75dcc0e/job.log
(1/1) type_specific.io-github-autotest-libvirt.virsh.snapshot_edit.positive_tests.edit_option_rename.edit_option_current_and_snapname.disk_snapshot.with_desc.disk_snapshot: FAIL: Failed to create snapshot. Error:. …
```
=> snapshot: Make sure the guest boot successfully before snapshot-create-as

libvirt/tests/cfg/backingchain/blockcopy/blockcopy_with_disk_driver_attributes.cfg
"drivermetadata" has been changed to "driver_metadatacache" since [#avocado-framework/avocado-vt-3573](https://github.com/avocado-framework/avocado-vt/pull/3573/commits/156ba0e2f506ff01282c39d67c753ef83c9e141a)
Before:
```
stem                                                              
JOB ID     : 66b5fb14ffd695765627d446e384bfd1114df5df
JOB LOG    : /var/lib/avocado/job-results/job-2022-12-28T02.29-66b5fb1/job.log
(1/1) type_specific.io-github-autotest-libvirt.backingchain.blockcopy.disk.driver_attr.metadata_cache: ERROR: Cannot set attribute "drivermetadata" to <class 'virttest.libvirt_xml.devices.disk.Disk'> object.There is no such attribute. (5
.42 s)
JOB HTML   : …
```
=> backingchain: Update the disk attribute according to the modification of avocado-vt

libvirt/tests/src/conf_file/sysconfig_libvirt_guests/libvirt_guests.py
Fix failures to get expected messages in filesystem
Extend sleep more time to allow get more messages from /var/log/messages
=> Fix failures to get expected messages in filesystem on s390x

libvirt/tests/src/virtual_network/iface_options.py
To receive multicast packet, the guest and host must have the udp port 4321 open if firewalld is active. Otherwise, the multicast packet will be blocked.
Signed-off-by: yalzhang
=> Fix the mcast test case

libvirt/tests/src/backingchain/blockcopy/blockcopy_with_conventional_chain.py
clean existed image before blockcopy
```
/usr/local/bin/avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 backingchain.blockcopy.conventional_chain.block_disk
(1/2) type_specific.io-github-autotest-libvirt.backingchain.blockcopy.conventional_chain.block_disk.with_shallow: PASS (71.45 s)
(2/2) type_specific.io-github-autotest-libvirt.backingchain.blockcopy.conventional_chain.block_disk.without_shallow: PASS (72.51 s)
```
=> fix remove existed copy image issue

libvirt/tests/cfg/backingchain/lifecycle_test/check_mirror_with_restart_libvirtd.cfg, libvirt/tests/src/backingchain/lifecycle_test/check_mirror_with_restart_libvirtd.py
This PR adds:
VIRT-294570 - [blockcommit/blockcopy][mirroring] Restart libvirtd and check xml during mirror phase of blockcommit
```
JOB ID     : 16471284d66a68113ad523b2ac29cf45de41fa18
JOB LOG    : /var/lib/avocado/job-results/job-2022-12-01T02.30-1647128/job.log
(1/2) type_specific.io-github-autotest-libvirt.backingchain.lifecycle_test.check_mirror_with_restart_libvirtd.blockcommit: PASS (79.90 s)
(2/2) type_specific.io-github-autotest-libvirt.backingchain.lifecycle_test.check_mirror_with_restart_libvirtd.blockcopy: PASS (80.19 s)
JOB HTML   : /var/lib/avocado/job-results/job-2022-12-01T02.30-1647128/results.html
JOB TIME   : 161.80 s
```
=> backingchain: add case to check mirror xml after restart service

libvirt/tests/cfg/migration/guest_lifecycle_operations_during_migration/migration_poweroff_vm.cfg, libvirt/tests/cfg/migration/pause_postcopy_migration_and_recover/no_paused_during_recover_migration.cfg, libvirt/tests/cfg/migration/pause_postcopy_migration_and_recover/pause_and_disruptive_and_recover.cfg, libvirt/tests/cfg/migration/pause_postcopy_migration_and_recover/pause_and_recover_and_disruptive.cfg, libvirt/tests/cfg/migration/pause_postcopy_migration_and_recover/pause_and_recover_twice.cfg, libvirt/tests/cfg/migration/pause_postcopy_migration_and_recover/pause_by_domjobabort_and_recover.cfg, libvirt/tests/cfg/migration/pause_postcopy_migration_and_recover/pause_by_network_and_recover.cfg, libvirt/tests/cfg/migration/pause_postcopy_migration_and_recover/pause_by_proxy_and_recover.cfg, libvirt/tests/cfg/migration/pause_postcopy_migration_and_recover/unattended_migration.cfg, libvirt/tests/cfg/migration/pause_postcopy_migration_and_recover/unattended_migration_and_disruptive.cfg, libvirt/tests/src/migration/destructive_operations_around_live_migration/migration_kill_libvirt_daemon.py, libvirt/tests/src/migration/pause_postcopy_migration_and_recover/no_paused_during_recover_migration.py, libvirt/tests/src/migration/pause_postcopy_migration_and_recover/pause_and_disruptive_and_recover.py, libvirt/tests/src/migration/pause_postcopy_migration_and_recover/pause_and_recover_and_disruptive.py, libvirt/tests/src/migration/pause_postcopy_migration_and_recover/pause_and_recover_twice.py, libvirt/tests/src/migration/pause_postcopy_migration_and_recover/pause_by_domjobabort_and_recover.py, libvirt/tests/src/migration/pause_postcopy_migration_and_recover/pause_by_network_and_recover.py, libvirt/tests/src/migration/pause_postcopy_migration_and_recover/pause_by_proxy_and_recover.py, libvirt/tests/src/migration/pause_postcopy_migration_and_recover/unattended_migration.py, libvirt/tests/src/migration/pause_postcopy_migration_and_recover/unattended_migration_and_disruptive.py, provider/migration/migration_base.py
1. libvirt support post-copy migration recovery since 8.5.0. So
add libvirt_version.is_libvirt_feature_supported() in some cases.
2. Fix NameError in migration_base.py.
Error message: NameError: name 'base_steps' is not defined
3. Fix SyntaxError in pause_and_recover_and_disruptive.cfg.
Error message: SyntaxError: invalid syntax 
4. Fix wrong function name in action_during_mig.
=> migration: Fix some issues

libvirt/tests/src/virsh_cmd/monitor/virsh_dominfo.py
libvirtd is restarted after issuing virsh commands from libvirt version 5.6.0 on.
Signed-off-by: Anushree Mathur <anushree.mathur2@ibm.com>
=> Fix test failure expectations when libvirtd is off

libvirt/tests/src/virsh_cmd/domain/virsh_vncdisplay.py
libvirtd service is restarted after issuing virsh commands from libvirt version 5.6.0 on.Handled it for the negative tests which expect the command failure when libvirt service is stopped.
Signed-off-by: Anushree Mathur <anushree.mathur2@ibm.com>
=> Fix test failure expectations when libvirtd is off.

libvirt/tests/cfg/backingchain/event_checking_test/commit_pull_copy_event.cfg, libvirt/tests/src/backingchain/event_checking_test/commit_pull_copy_event.py
This PR adds:
VIRT-294605 - Check events when doing blockcommit/blockpull/blockcopy
Test Result:
```
JOB ID     : 9d6548d466c9db166beb43f4d45d13a8278a30ef
JOB LOG    : /var/lib/avocado/job-results/job-2022-11-08T22.43-9d6548d/job.log
(1/3) type_specific.io-github-autotest-libvirt.backingchain.event_checking_event.commit_pull_copy.blockcommit: PASS (67.47 s)
(2/3) type_specific.io-github-autotest-libvirt.backingchain.event_checking_event.commit_pull_copy.blockpull: PASS (109.23 s)
(3/3) type_specific.io-github-autotest-libvirt.backingchain.event_checking_event.commit_pull_copy.blockcopy: PASS (90.40 s)
JOB HTML   : /var/lib/avocado/job-results/job-2022-11-08T22.43-9d6548d/results.html
JOB TIME   : 269.88 s …
```
=> Backingchain: add new case for event checking test

libvirt/tests/cfg/numa/numa_memory.cfg
If the numa node setting is out of range, for aarch64, the error message should also be "NUMA node.*unavailable" which should be rasied in the configuration check.
When memory_mode is "strict" and memory_nodeset is out of range, the guest does not fail to start until it writes to cpuset.mems with the error message "Numerical result out of range", which should be a bug.
=> Revert "numa_memory: Check appropriate error messages for aarch64"

libvirt/tests/cfg/cpu/lifecycle_time.cfg, libvirt/tests/src/cpu/lifecycle_time.py
Add test case to confirm that after suspending and resuming a VM the clock still works as expected.
=> cpu/lifecycle: Test that time works

libvirt/tests/cfg/numa/guest_numa.cfg
numa: increase the page_num_0 value for hugepages2M to fix failure
Otherwise the guest can't start because of the insufficient memory.
=> numa: increase the page_num_0 value for hugepages2M to fix failure

libvirt/tests/src/virtual_network/iface_options.py
The output of qemu command has been upgraded to json format, therefore the searching target should be updated as well.
=> iface_options:Fix error of cannot find vhost options

libvirt/tests/cfg/backingchain/with_disk_attributes_test/commit_pull_with_disk_driver_attributes.cfg, libvirt/tests/src/backingchain/with_disk_attributes_test/commit_pull_with_disk_driver_attributes.py
This PR add:
VIRT-294609: Do blockcommit/blockpull with different attributes of driver elements
Test Result:
```
JOB ID     : 402dc95b928e79712eccbb1f35a8b2fb0281f299
JOB LOG    : /var/lib/avocado/job-results/job-2022-12-08T02.08-402dc95/job.log
(1/8) type_specific.io-github-autotest-libvirt.backingchain.with_disk_attributes_test.with_driver_attributes.blockcommit.with_copy_on_read: PASS (91.04 s)
(2/8) type_specific.io-github-autotest-libvirt.backingchain.with_disk_attributes_test.with_driver_attributes.blockcommit.with_cache_discard: PASS (94.13 s)
(3/8) type_specific.io-github-autotest-libvirt.backingchain.with_disk_attributes_test.with_driver_attributes.blockcommit.with_detect_zeroes: PASS (88.00 s)
(4/8) type_specific.io-github-autotest-libvirt.backingchain.with_disk_attributes_test.w …
```
=> Backingchain: add new case with different disk attributes

libvirt/tests/cfg/controller/pcie_root_port_controller.cfg, libvirt/tests/src/controller/pcie_root_port_controller.py
This commit adds 2 checks that check a situation where pcie-root-port controller index number should be over the bus number it is attached to.
Automation of VIRT-54001
```
[root@dell-per740xd-25 ~]# avocado run --vt-type libvirt pcie_controllers.negative_tests.index_equal_to_bus.hotplug_off pcie_controllers.negative_tests.index_less_than_bus.hotplug_off
JOB ID     : c0e309a258c30ac8c3e14f2487d050a4ec4b5323
JOB LOG    : …
```
=> PCIe Controller, pcie-root-port with index <= bus

libvirt/tests/src/backingchain/blockcopy/blockcopy_with_disk_driver_attributes.py
```
avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 backingchain.blockcopy.disk.driver_attr.metadata_cache --vt-connect-uri qemu:///system
(1/1) type_specific.io-github-autotest-libvirt.backingchain.blockcopy.disk.driver_attr.metadata_cache: PASS (56.91 s)
```
=> fix not find xml path

libvirt/tests/cfg/virsh_cmd/domain/virsh_detach_device_alias.cfg, libvirt/tests/src/virsh_cmd/domain/virsh_detach_device_alias.py
RHEL-148234: Device can also be detached by 'virsh detach-device-alias' cmd. Test the following various input device by this cmd.
Test result:
```
/usr/local/bin/avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35  virsh.detach_device_alias..input
(1/6) type_specific.io-github-autotest-libvirt.virsh.detach_device_alias.live.input.keyboard: PASS (93.34 s)
(2/6) type_specific.io-github-autotest-libvirt.virsh.detach_device_alias.live.input.mouse: PASS (93.09 s)
(3/6) type_specific.io-github-autotest-libvirt.virsh.detach_device_alias.live.input.passthrough: PASS (92.17 s)
(4/6) type_specific.io-github-autotest-libvirt.virsh.detach_device_alias.config.input.keyboard: PASS (91.08 s)
(5/6) …
```
=> add case for detach input device with alias

libvirt/tests/cfg/passthrough/pci/ism_pci_passthrough.cfg, libvirt/tests/src/passthrough/pci/ism_pci_passthrough.py
ISM is a special device on s390x that can be passed through with vfio_pci. It's managed by libvirt as node device.
Add a test case that confirms that the device can be attached and is listed inside the guest.
=> passthrough/pci: add test for ISM device on s390x

libvirt/tests/cfg/libvirt_mem.cfg
libvirt_mem.cfg: update the memory of numa cells to match ovmf guest
Otherwise, the ovmf guest can't boot successfully.
=> libvirt_mem.cfg: update the memory of numa cells to match ovmf guest

libvirt/tests/src/passthrough/pci/ism_pci_passthrough.py
The session variable needs to be initilized so that in case of a failure the conditional doesn't raise
=> passthrough/pci: teard down properly

provider/v2v_vmcheck_helper.py, v2v/tests/cfg/specific_kvm.cfg, v2v/tests/src/specific_kvm.py
The old firmware check is as a public checkpoint, but in fact, not all VMs have that attribute. And the original test case and bug only report the attribute should be show in xml only for vmware guests.
So I moved the check for all test cases and put it into a specific test case.
=> v2v: fix firmware check issue

provider/sriov/check_points.py, provider/sriov/sriov_base.py
Update to wait for some time before checking interface information to avoid no interface issues.
` (1/1) type_specific.io-github-autotest-libvirt.sriov.plug_unplug.attach_detach_device.network_interface.network.pf_name.managed_yes: FAIL: Unable to get VM interface with given mac address - 9a:4d:36:c1:77:26! (39.04 s)`
```
(1/1) type_specific.io-github-autotest-libvirt.sriov.plug_unplug.attach_detach_device.network_interface.network.pf_name.managed_yes: PASS (71.29 s)
(1/1) type_specific.io-github-autotest-libvirt.sriov.plug_unplug.attach_detach_interface_with_flags.live.running_domain: PASS (66.89 s)
```
=> sriov: Fix no interface issues

libvirt/tests/cfg/virsh_cmd/nodedev/virsh_nodedev_dumpxml_chain.cfg, libvirt/tests/src/virsh_cmd/nodedev/virsh_nodedev_dumpxml_chain.py
If the kernel supports it, the css device' attribute "dev_buis" that idenditifes the actual device attached to the channel is displayed in the nodedev xml.
=> virsh_nodedev_dumpxml: add check for s390x device css

libvirt/tests/cfg/virtual_disks/at_dt_iscsi_disk.cfg
Fix iscsi_direct_pool failure due to enable_authentication = "yes"
This partly responds to the change brought by https://github.com/autotest/tp-libvirt/pull/4678/files
=> Fix iscsi_direct_pool failure due to enable_authentication = "yes"

libvirt/tests/src/virsh_cmd/domain/virsh_destroy.py
libvirtd is restarted after issuing virsh commands from libvirt version 5.6.0 on. So we need to fix the test expectations when libvirtd is off
=> virsh_destroy: fix destroy error

libvirt/tests/cfg/controller/pcie_root_port_controller.cfg, libvirt/tests/src/controller/pcie_root_port_controller.py
This case adds checks for devices attached to PCIe controller that have
slot number bigger than one or something else than a number.
VIRT-48333
=> pcie, new case for invalid PCIe slots

libvirt/tests/cfg/virsh_cmd/pool/virsh_pool_auth.cfg, libvirt/tests/src/virsh_cmd/pool/virsh_pool_auth.py
When testing the iscsi pool with auth, it need enable authentication=1 attribute when setup iscsi.
=> virsh_pool_auth: fix authentication failure in iscsi pool

libvirt/tests/cfg/virsh_cmd/domain/virsh_detach_device_alias.cfg, libvirt/tests/src/virsh_cmd/domain/virsh_detach_device_alias.py
Need to get event on host
```
avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 virsh.detach_device_alias..input --vt-connect-uri qemu:///system
(1/6) type_specific.io-github-autotest-libvirt.virsh.detach_device_alias.live.input.keyboard: PASS (174.82 s)
(2/6) type_specific.io-github-autotest-libvirt.virsh.detach_device_alias.live.input.mouse: PASS (167.48 s)
(3/6) type_specific.io-github-autotest-libvirt.virsh.detach_device_alias.live.input.passthrough: PASS (167.37 s)
(4/6) type_specific.io-github-autotest-libvirt.virsh.detach_device_alias.config.input.keyboard: PASS (165.34 s)
(5/6) type_specific.io-github-autotest-libvirt.virsh.detach_device_alias.config.input.mouse: PASS (163.62 s)
(6/6) …
```
=> fix input detach error

libvirt/tests/cfg/virtual_interface/connectivity_check.cfg, libvirt/tests/cfg/virtual_interface/locked_memory_check/mem_lock_limit_multiple_vdpa_interfaces.cfg, libvirt/tests/src/virtual_interface/connectivity_check.py, libvirt/tests/src/virtual_interface/locked_memory_check/mem_lock_limit_multiple_vdpa_interfaces.py
This PR adds:
1. VIRT-296166 - hotplug/unplug memory and multiple vdpa interfaces
2. Add 3 scenarios into connectivity_check test - boot order,
page_per_vq and mutiqueue and multiple vdpa interfaces
Signed-off-by: Yingshun Cui <yicui@yicui.nay.csb>
Depends:
- https://github.com/avocado-framework/avocado-vt/pull/3598
- https://github.com/avocado-framework/avocado-vt/pull/3600
Test results: 
```
(1/7) type_specific.io-github-autotest-libvirt.iface.locked_memory_check.multiple_interfaces.vdpa: FAIL: The string 'fail|error' is included in /var/log/libvirt/qemu/avocado-vt-vm1.log (90.23 s)
(2/7) type_specific.io-github-autotest-libvirt.iface.connectivity_check.vdpa.default.mellanox: PASS (124.59 s)
(3/7) type_specific.io-github-autotest-libvirt.iface.connectivity_check.vdpa.driver_queues.vcpu_g …
```
=> virtual_interface: Add cases about vdpa interface

libvirt/tests/cfg/virtual_interface/locked_memory_check/mem_lock_limit_multiple_mixed_interfaces.cfg, libvirt/tests/src/virtual_interface/locked_memory_check/mem_lock_limit_multiple_mixed_interfaces.py
This PR adds:
VIRT-296323 - Check the mem_lock limit when there is a hostdev
and vdpa interface together
```
(1/2) type_specific.io-github-autotest-libvirt.iface.locked_memory_check.mixed_interfaces.cold_plug.vdpa: PASS (95.65 s)
(2/2) type_specific.io-github-autotest-libvirt.iface.locked_memory_check.mixed_interfaces.hot_plug.vdpa: PASS (97.20 s)
```
=> vdpa: Add a case to check mem_lock limit

libvirt/tests/cfg/graphics/graphics_functional.cfg
This checkpoint is covered in qemu test cases. So remove it.
=> graphics_functional: Remove remote-viewer checkpoint

libvirt/tests/cfg/controller/pcie_root_port_controller.cfg, libvirt/tests/src/controller/pcie_root_port_controller.py
This PR adds checks for PCIe root port controller with invalid name. The check should fail. Automation of VIRT-47650
=> PCIe: pcie-root-port invalid name

libvirt/tests/src/virsh_cmd/domain/virsh_domdirtyrate_calc.py
For dirty ring mode, Sometimes the calculated dirty rate can be as large as 2 times of the set one. Modify the tolerance of the difference between them.
=> [MinorFix]Modify the tolerance of the difference

libvirt/tests/cfg/virsh_cmd/domain/virsh_domdirtyrate_calc.cfg
dirty-ring is not enabled on s390x and aarch64 so far in qemu-kvm.
=> virsh_domdirtyrate_calc: no dirty-ring on s390 and aarch64

libvirt/tests/src/backingchain/blockcommit/blockcommit_relative_path.py, libvirt/tests/src/backingchain/blockpull/blockpull_relative_path.py, provider/virtual_disk/disk_base.py
create rbd image for backingchain case instead of using existed rbd image
Test result:
relative path case
```
avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 backingchain.blockcommit.relative_path  --vt-connect-uri qemu:///system
(1/8) type_specific.io-github-autotest-libvirt.backingchain.blockcommit.relative_path.file_disk.keep_relative.active.vm_started: PASS (40.36 s)
(2/8) type_specific.io-github-autotest-libvirt.backingchain.blockcommit.relative_path.file_disk.keep_relative.active.vm_paused: PASS (42.28 s)
(3/8) type_specific.io-github-autotest-libvirt.backingchain.blockcommit.relative_path.file_disk.keep_relative.inactive.vm_started: PASS (41.35 s)
(4/8) type_specific.io-github-autotest-libvirt.backingchain.blockcommit. …
```
=> deprecate existed rbd image

libvirt/tests/cfg/backingchain/negative_scenario/blockcommit_invalid_top_base.cfg, libvirt/tests/src/backingchain/negative_scenario/blockcommit_invalid_top_base.py
error msg needs to be updated
Confirm with meina and  use this two error msgs
before
`TestFail: Expect should fail with one of [&quot;error: invalid argument: top '/var/lib/avocado/data/avocado-vt/images/jeos-27-x86_64.qcow2' in chain for 'vda' has no backing file&quot;], but failed with:error: invalid argument: could not find base image in chain for 'vda'&#10;`
fixed 
```
avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 backingchain.negative.blockcommit.invalid_top_base.no_backing --vt-connect-uri qemu:///system
(1/2) type_specific.io-github-autotest-libvirt.backingchain.negative.blockcommit.invalid_top_base.no_backing.blockcommit_directly: PASS (37.52 s)
(2/2) type_specific.io-github-autotest-libvirt.backingchain.negative.bl …
```
=> fix negative case error message

libvirt/tests/cfg/migration/guest_lifecycle_operations_during_migration/migration_poweroff_vm.cfg, libvirt/tests/src/migration/guest_lifecycle_operations_during_migration/migration_poweroff_vm.py, provider/migration/migration_base.py
For postcopy, we should send 'poweroff' command to dest host. Fix following issue:
TestFail: Migrated VM failed to be in paused state at source
=> migration: Fix wrong vm state on source

libvirt/tests/cfg/numa/guest_numa.cfg, libvirt/tests/src/numa/guest_numa.py
Since qemu-kvm-7.2.0-1, the vm needs more memory to start. As RHEL offical web page says, 1G memory is too small. 1.5G is required at least. For convenient usage, we use 2G in test.
=> guest_numa: vm needs more memory to start

libvirt/tests/cfg/virsh_cmd/domain/virsh_setvcpus.cfg, libvirt/tests/src/virsh_cmd/domain/virsh_setvcpus.py
Depends on https://github.com/avocado-framework/avocado-vt/pull/3613
s390x doesn't have NUMA, disable checking it when checking vcpus.
=> virsh_setvcpus: Disable NUMA check on s390x

libvirt/tests/cfg/backingchain/lifecycle/block_operation_after_lifecycle.cfg, libvirt/tests/src/backingchain/lifecycle/block_operation_after_lifecycle.py, provider/backingchain/blockcommand_base.py
VIRT-294568: Do blockcommit/blockpull/blockcopy with snapshots after restart the vm/libvirtd
```
/usr/local/bin/avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 backingchain.lifecycle.block_operation
(1/3) type_specific.io-github-autotest-libvirt.backingchain.lifecycle.block_operation.destroy_guest.blockcommit: PASS (31.42 s)
(2/3) type_specific.io-github-autotest-libvirt.backingchain.lifecycle.block_operation.reboot_guest.blockcommit: PASS (24.89 s)
(3/3) type_specific.io-github-autotest-libvirt.backingchain.lifecycle.block_operation.restart_service.blockcommit: PASS (29.41 s)
(1/3) type_specific.io-github-autotest-libvirt.backingchain.lifecycle.block_operation.destroy_guest.blockcopy: PASS (32.91 s)
(2/3) …
```
=> backingchain:add case for block operation after lifecycle

libvirt/tests/cfg/virtual_network/iface_hotplug.cfg, libvirt/tests/cfg/virtual_network/iface_update.cfg
s390x doesn't support ROM. Disable tests.
=> virtual_network: disable ROM test cases for s390x

libvirt/tests/cfg/virtual_network/iface_stat.cfg, libvirt/tests/cfg/virtual_network/iface_unprivileged.cfg, libvirt/tests/cfg/virtual_network/virtual_network_multivms.cfg, libvirt/tests/src/virtual_network/iface_stat.py, libvirt/tests/src/virtual_network/iface_unprivileged.py, libvirt/tests/src/virtual_network/virtual_network_multivms.py
Currently, the several tests select the first host interface. In order to allow for testing with a specific interface in other test environments allow for value to be configured. Don't assign a value in the cfg in order to keep legacy behavior.
=> virtual_network: make interface selection configurable

libvirt/tests/cfg/virsh_cmd/domain/virsh_detach_device_alias.cfg
Filter out pcie-pci-bridge controller type on s390x
unsupported configuration: the 'pcie-pci-bridge' device is not supported by this QEMU binary on s390x
=> Filter out pcie-pci-bridge controller type on s390x

libvirt/tests/cfg/sriov/nodedev/sriov_nodedev_non_driver.cfg, libvirt/tests/src/sriov/nodedev/sriov_nodedev_non_driver.py
This pr adds:
VIRT-295336: Dettach node device from host without device driver
` (1/1) type_specific.io-github-autotest-libvirt.sriov.nodedev.non_driver: PASS (20.03 s)
`
=> sriov: Add a nodedev case

libvirt/tests/src/incremental_backup/incremental_backup_pull_mode.py
With recent certtool, certs generated in tmp dirs don't have 'read' access right for the user 'qemu'. We can use '/etc/pki/' as their parent dir to avoid this issue.
=> [incremental_backup] Fix tls certs 'permission denied' error

libvirt/tests/cfg/controller/pcie_root_port_controller.cfg, libvirt/tests/src/controller/pcie_root_port_controller.py
This commit adds a new test scenarios where invalid PCIe
root_port_controller index is tested to produde VM define command
failure.
VIRT-47643
=>  PCIe Controller, invalid root_port_controller index

libvirt/tests/src/numa/numa_config_with_auto_placement.py
The guest memory may be bound to multiple nodes such as 0-1 or 0-3. It is inappropriate to convert the value of nodeset to int type for comparison.
Before:
```
JOB ID     : 8f484000b04d2fbc84620f261f996c01cbffe205
JOB LOG    : /var/lib/avocado/job-results/job-2023-02-07T00.38-8f48400/job.log
(1/1) type_specific.io-github-autotest-libvirt.numa_config_with_auto_placement.memory_bind: FAIL: Unexpected failure during the test: invalid literal for int() with base 10: '0-3' (67.72 s)                                               
JOB HTML   : /var/lib/avocado/job-results/job-2023-02-07T00.38-8f48400/results.html
JOB TIME   : 68.48 s
```
After:
```
JOB ID     : 78b9bb84eb7fd342695165d83e22b265691f67ff
JOB LOG    : …
```
=> numa: Fix comparison of numa_nodeset

libvirt/tests/src/numa/guest_numa.py
In gating, rhel.guest_numa.possitive_test.hugepage.per_node.2M.topology.numatune_memnode.m_strict.numatune_mem will fail when the host has not enough memory for node1. It may affectthe gating result. So  decided to cancel it in that case。
=> guest_numa.py: cancel test when out of memory for host

libvirt/tests/src/virsh_cmd/domain/virsh_cpu_compare_xml.py
Test result:
```
(1/1) type_specific.io-github-autotest-libvirt.virsh.cpu_compare_xml.cpu_xml.invalid_test: PASS (42.98 s)
JOB HTML   : /var/lib/avocado/job-results/job-2023-02-15T22.26-29d039d/results.html
JOB TIME   : 44.44 s
```
=> virsh_cpu_compare_xml:Fix error of parsing invalid test xml

libvirt/tests/cfg/migration/pause_postcopy_migration_and_recover/pause_and_recover_and_disruptive.cfg
Need add time sleep before virsh.domjobabort() for recover postcopy
migration.
=> migration: Fix recover postcopy migration error

libvirt/tests/cfg/backingchain/repeatability_test/commit_pull_copy_after_snap.cfg, libvirt/tests/src/backingchain/repeatability_test/commit_pull_copy_after_snap.py
This PR adds:
VIRT-294587 - Take turn to create snapshots and do blockcommit/blockpull/blockcopy
repeatedly
=> Backingchain: add case of doing block operations repeatedly

libvirt/tests/src/virsh_cmd/domain/virsh_detach_device_alias.py
Fix two errors:
```
VMStartError: VM 'avocado-vt-vm1' failed to start: error: Failed to start domain 'avocado-vt-vm1'error: internal error: Unexpected address type for 'virtio-mouse'(exit status: 1)&#10;
TypeError: __init__() missing 1 required positional argument: 'type_name'&#10;
```
```
[root@dell-per730-66 tp-libvirt]# avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 virsh.detach_device_alias..input --vt-connect-uri qemu:///system
(1/6) type_specific.io-github-autotest-libvirt.virsh.detach_device_alias.live.input.keyboard: PASS (107.54 s)
(2/6) type_specific.io-github-autotest-libvirt.virsh.detach_device_alias.live.input.mouse: PASS (110.84 s)
(3/6) type_specific.io-github-autotest-libvirt.virsh.detach_device_alias.live.in …
```
=> fix input case  Unexpected address virtio-mouse error

libvirt/tests/cfg/guest_resource_control/control_cgroup.cfg
cfs_quota params can be set as negative values, which means it's unlimited. After bz2037998 fixed, we'll need to add cases to check them.
=> [guest_resource_control] Add cases to check negative cfs_quota values

libvirt/tests/cfg/controller/pcie_root_port_controller.cfg, libvirt/tests/src/controller/pcie_root_port_controller.py
This PR adds test cases for testing invalid values of chassis attribute of target element of pcie-root-port device. All cases are negative tests.
VIRT-47653
=> PCIe contr, invalid pcie-root-port target chassis

libvirt/tests/cfg/passthrough/ccw/libvirt_ccw_passthrough.cfg, libvirt/tests/cfg/passthrough/ccw/libvirt_ccw_passthrough_read_write.cfg, libvirt/tests/cfg/virtual_disks/virtual_disks_dasd.cfg, libvirt/tests/src/passthrough/ccw/libvirt_ccw_passthrough.py, libvirt/tests/src/passthrough/ccw/libvirt_ccw_passthrough_read_write.py, libvirt/tests/src/virtual_disks/virtual_disks_dasd.py, provider/vfio/ccw.py, provider/vfio/mdev_handlers.py, virttools/tests/cfg/virt_install/hostdev_mdev.cfg, virttools/tests/src/virt_install/hostdev_mdev.py
Depends on https://github.com/avocado-framework/avocado-vt/pull/3606
Tests relied on a function in avocado-vt to select a device for testing based on certain assumptions.
Add a parameter to the configurations in order to overwrite that selection and choose a device manually.
=> ccw: Enable DASD device selection via configuration

libvirt/tests/src/libvirt_rng.py
The function get_devices is supposed to be called by a VMXML instance, not the class itself.
=> libvirt_rng:Fix error when calling 'get_devices'

libvirt/tests/cfg/virtual_network/iface_network.cfg
On some lab, when start ipv6 network, it may fail as below: virsh net-start nattest
error: Failed to start network nattest
error: internal error: Check the host setup: interface enc1 has kernel autoconfigured IPv6 routes and enabling forwarding  without accept_ra set to 2 will cause the kernel to flush them, breaking networking.
Refer to https://github.com/autotest/tp-libvirt/blob/master/libvirt/tests/src/virtual_network/iface_network.py#L694, it need enable test_ipv6_address=yes to enforce accept_ra set to 2
=> Fix virtual_network reconnect_tap case failures 

libvirt/tests/cfg/backingchain/blockcopy/blockcopy_with_different_dest_xml.cfg, libvirt/tests/src/backingchain/blockcopy/blockcopy_with_different_dest_xml.py, provider/virtual_disk/disk_base.py
VIRT-294410: Do blockcopy with different dest XML
```
/usr/local/bin/avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 backingchain.blockcopy.dest_xml
(1/8) type_specific.io-github-autotest-libvirt.backingchain.blockcopy.dest_xml.file_disk.finish_reuse_external: PASS (45.10 s)
(2/8) type_specific.io-github-autotest-libvirt.backingchain.blockcopy.dest_xml.file_disk.pivot_reuse_external: PASS (46.90 s)
(3/8) type_specific.io-github-autotest-libvirt.backingchain.blockcopy.dest_xml.block_disk.finish_reuse_external: PASS (63.41 s)
(4/8) type_specific.io-github-autotest-libvirt.backingchain.blockcopy.dest_xml.block_disk.pivot_reuse_external: -ujPASS (64.71 s)
(5/8) type_specific.io-github-autotest-libvirt.backingchain.blockcopy.dest_ …
```
=> backingchain:add case for blockcopy wth different dest xml

libvirt/tests/cfg/sriov/update_device/sriov_update_device.cfg, libvirt/tests/src/sriov/update_device/sriov_update_device.py
This PR adds：
VIRT-294517 - live update hostdev type interface
` (1/1) type_specific.io-github-autotest-libvirt.sriov.update_device: PASS (56.18 s)
`
=> sriov: Add a case about update-device

libvirt/tests/cfg/sriov/nodedev/sriov_reattach_detach_nodedev_in_use.cfg, libvirt/tests/src/sriov/nodedev/sriov_reattach_detach_nodedev_in_use.py
This PR adds:
VIRT-293916: Run nodedev-detach or reattach when vf or PF is in use
```
(1/3) type_specific.io-github-autotest-libvirt.sriov.nodedev.reattach_detach_nodedev_in_use.hostdev_interface.vf: PASS (69.49 s)
(2/3) type_specific.io-github-autotest-libvirt.sriov.nodedev.reattach_detach_nodedev_in_use.hostdev_device.vf: PASS (71.00 s)
(3/3) type_specific.io-github-autotest-libvirt.sriov.nodedev.reattach_detach_nodedev_in_use.hostdev_device.pf: PASS (72.83 s)
```
=> sriov: Add a case about nodedev

libvirt/tests/src/virtual_device/input_devices.py
Fix input device failures due to element order change
After avocado-vt PR:3615 integated, the input element order changed, so need change matched pattern accordingly
=> Fix input device failures due to element order change

libvirt/tests/src/controller/pcibridge.py
Several pcibridge related cases may failed because of "LoginTimeoutError: Login timeout expired" sometimes. The failure may be related to serial port which be occupied  or others. So change it from vm.wait_for_serial_login().close() to vm.wait_for_login().close() to check if it can resolve the failure.
=> pcibridge.py: update the method of login guest to fix timeout

libvirt/tests/src/bios/virsh_boot_sysinfo.py, libvirt/tests/src/virtual_device/input_devices.py
Depends on https://github.com/avocado-framework/avocado-vt/pull/3632
XML attributes are unordered. Therefore, checking multiple values
as strings can fail. Use XPath expressions instead.
=> input_devices, virsh_boot_sysinfo: improve xml check

libvirt/tests/cfg/controller/pcie_root_port_controller.cfg, libvirt/tests/src/controller/pcie_root_port_controller.py
This PR adds automation of tests where pcie-root-port controllers should have target with slot numbered from 1 to 31 (in hexadecimal numbers).
VIRT-55414
=> PCIe, Slots in pcie-root numbered [1,31]

libvirt/tests/src/virtual_device/input_devices.py
9b616bc893e086fd096811185e3ee56f6ba01b7e introduced a new function to check input XML without considering the order. However, the test expectation for `with_packed` was accidentally changed erroneously. The test now verifies correctly that `<driver packed='on'/>` is present.
=> virtual_devices/input_device: fix test with_packed

libvirt/tests/src/migration/migrate_mem.py
Need more time to wait memory balloon to the expected size, so
extend timeout.
=> migrate_mem: Extend timeout for mem_balloon

libvirt/tests/cfg/nwfilter/nwfilter_daemon_restart.cfg, libvirt/tests/src/nwfilter/nwfilter_daemon_restart.py
Add regression test case confirming that VMs keep running if daemons are restarted with access driver configuration.
=> nwfilter: add new test case

libvirt/tests/src/virsh_cmd/domain/virsh_attach_device.py
/dev/vdX in guest may be inconsistent with disk->target@dev in XML, if the old device is not ready in guest before attaching a new device to the guest.
Before:
```
JOB ID : 98178aac2a79dc233e2ed45374cda6fc85a989a8 
JOB LOG : /var/lib/avocado/job-results/job-2022-10-12T14.22-98178aa/job.log 
(1/1) type_specific.io-github-autotest-libvirt.virsh.attach_device.block.multi_virtio_file.with_alias.normal_test.hot_attach_hot_vm_current.name_ref.file_positional.domain_positional: FAIL: Positive pre-boot functionality test failed (285.12 s) 
RESULTS : PASS 0 | ERROR 0 | FAIL 1 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0 
JOB HTML : /var/lib/avocado/job-results/job-2022-10-12T14.22-98178aa/results.html 
JOB TIME : 286.19 s
```
After:
```
JOB ID     : a17c92bbbe012f399746c7d97a6a5caf70119d66
JOB LOG …
```
=> virsh_attach_device: make sure device is ready before attaching a new device

libvirt/tests/cfg/virsh_cmd/domain/virsh_detach_device_alias.cfg, libvirt/tests/src/virsh_cmd/domain/virsh_detach_device_alias.py
For aarch64, no kernel cmd line for iommu. We can use "virsh capabilities | grep iommu" to check whether the host supports iommu. If the 'support' value is 'yes', there is no need to check the kernel cmd line.
And for aarch64, only 'Host bridge' PCI device can be used for hostdev_pci.
Results:
```
JOB ID     : 33936c1ec60061cd59828f5d709ccc04801e67c2
JOB LOG    : /var/lib/avocado/job-results/job-2023-01-09T23.18-33936c1/job.log
(1/3) type_specific.io-github-autotest-libvirt.virsh.detach_device_alias.live.hostdev.pci: PASS (54.33 s)
(2/3) type_specific.io-github-autotest-libvirt.virsh.detach_device_alias.config.hostdev.pci: PASS (47.85 s)
(3/3) type_specific.io-github-autotest-libvirt.virsh.detach_device_alias.current.hostdev.pci: PASS (53.73 s)
RESULTS    : PASS 3 | ERROR 0 | FAIL 0 | …
```
=> console: Enable detach_device_alias of hostdev pci test for aarch64

libvirt/tests/src/virsh_cmd/host/virsh_freecell.py
Description: libvirtd is restarted after issuing virsh commands from libvirt version 5.6.0 on. Hence need to fix test expectations when libvirtd is off
=> Fix for freecell tests failure when libvirtd is off

libvirt/tests/cfg/cpu/iothread.cfg
On some systems the expected error message is different.
=> cpu/iothread: add error message variant

libvirt/tests/src/serial/serial_functional.py
To align with the change in below pull request.
https://github.com/avocado-framework/aexpect/pull/107 
Provide the session prefix when logging sent commands
=> serial_functional: fix missing new parameter

libvirt/tests/src/numa/guest_numa.py
Test will cancel when catching ValueError with expected message, fail when they are unexpected.
=> guest_numa:raise if catch unexpected error

libvirt/tests/cfg/migration/pause_postcopy_migration_and_recover/pause_by_domjobabort_and_recover.cfg
Need to set '--dname' parameter in migration again process. So add
a parameter.
=> migration: Fix failed to get domain

libvirt/tests/src/virsh_cmd/domain/virsh_managedsave.py
Test should not proceed if vm has not been expected state, or test result would be incorrect.
With 10s as timeout:
```
FAIL 1-type_specific.io-github-autotest-libvirt.virsh.managedsave.functional_test.bypass_cache -> TestFail: Wait 10s for vm to be shut off and failed.Current VM state is paused
```
With 120s as timeout:
```
PASS 1-type_specific.io-github-autotest-libvirt.virsh.managedsave.functional_test.bypass_cache
```
=> virsh_managedsave:Fail test if timeout when waiting for certain vm state

provider/sriov/sriov_base.py
If there is no specific rom file, need to build from source code.
` (1/1) type_specific.io-github-autotest-libvirt.sriov.plug_unplug.attach_detach_device_special_situations.hostdev_interface.boot_order: ERROR: This test needs rom file: /usr/share/ipxe/8086154c.rom. (15.57 s)`
` (1/1) type_specific.io-github-autotest-libvirt.sriov.plug_unplug.attach_detach_device_special_situations.hostdev_interface.boot_order: PASS (265.74 s)
`
=> sriov: Fix an issue of no rom file

libvirt/tests/cfg/libvirt_rng.cfg, libvirt/tests/src/libvirt_rng.py
The tests compare the number of available rng devices to confirm attachment. However, some sources can provide rng devices that are not virtio and can be ignored.
Instead of adding logic to the code that ignores one by one, change the code to provide a configurable list of devices that should be ignored.
The criterion to ignore the device 'tpm-rng-0' was its presence in the XML configuration. However, it should always be ignored.
=> libvirt_rng: Ignore non-virtio rng device

libvirt/tests/src/incremental_backup/incremental_backup_push_mode.py
For negative cases which intentionally destroy vm or kill qemu process during backup process, the checkpoints' metadata and qcow2 files' data could be inconsistent. And in this situation when case tries to cleanup checkpoints without '--metadata', error may happen. This fix is to delete chcekpoints with '--metadata' in the cleanup process for these negative cases.
=> [incremental_backup] Fix failures for clean up checkpoints

provider/virtual_disk/disk_base.py
Use `netstat` to make sure the nbd server is ready.
Before:
```
ERROR| ERROR 1-type_specific.io-github-autotest-libvirt.backingchain.blockcopy.dest_xml.nbd_disk.pivot_reuse_external -> CmdError: Command '/bin/virsh blockcopy avocado-vt-vm1 vdb  --pivot  --xml /tmp/xml_utils_temp_eg45andu.xml --transient-job --reuse-external --verbose --wait ' failed.
stdout: b'\n'
stderr: b"error: internal error: unable to execute QEMU command 'blockdev-add': Failed to connect to 'ampere***.com:10808': Connection refused\n"
additional_info: None
```
After:
```
INFO | PASS 1-type_specific.io-github-autotest-libvirt.backingchain.blockcopy.dest_xml.nbd_disk.pivot_reuse_external
```
=> backingchain: Fix nbd server is not ready

libvirt/tests/src/daemon/check_daemon_after_remove_pkgs.py
The libvirt daemon might be reference by other services in their unit files. E.g. RHEL 8 has the kvm-setup.service on some archs.
In these cases the daemon will still be listed but as 'not-found'. This is correct.
Update the test case to allow for this case.
=> daemon/check after remove package: fix in case of dependencies

libvirt/tests/cfg/virtual_device/video_devices.cfg
s390x only supports virtio-gpu.
=> virtual_devices/video_devices: disable unsupported cases on s390x

libvirt/tests/src/conf_file/libvirtd_conf/unix_sock.py
'Libvirtd' object has no attribute 'libvirtd'
Signed-off-by: gjw <guojingwei@inspur.com>
=> libvirtd_conf/unix_sock.py: fix function call error

libvirt/tests/cfg/backingchain/negative_scenario/do_concurrent_operation.cfg, libvirt/tests/src/backingchain/negative_scenario/do_concurrent_operation.py
VIRT-294613:  Do concurrent block operations with relative path
```
/usr/local/bin/avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 backingchain.concurrent_operation
(1/4) type_specific.io-github-autotest-libvirt.backingchain.concurrent_operation.file_disk.during_blockcopy: PASS (46.46 s)
(2/4) type_specific.io-github-autotest-libvirt.backingchain.concurrent_operation.file_disk.during_blockcommit: PASS (65.00 s)
(3/4) type_specific.io-github-autotest-libvirt.backingchain.concurrent_operation.block_disk.during_blockcopy: PASS (101.02 s)
(4/4) type_specific.io-github-autotest-libvirt.backingchain.concurrent_operation.block_disk.during_blockcommit: PASS (95.44 s)
```
=> add case for concurrent block operation

libvirt/tests/cfg/cpu/vm_features.cfg, libvirt/tests/src/cpu/vm_features.py
This is to test all supported hyperv features in domcapabilities can be used to start the vm. And if unsupported hyperv feature is used to start the vm, the vm will fail to start.
Case ID: VIRT-296852
=> vm_features: add case using features in domcap

libvirt/tests/cfg/migration/migrate_options_shared.cfg
Set migrate speed to low value, then we can run 'virsh
migrate-postcopy' during migration.
=> migration: Fix issue about migration speed

libvirt/tests/cfg/cpu/setvcpu.cfg, libvirt/tests/src/cpu/setvcpu.py
Update to use 'login_time' to avoid "Login timeout expired" issue.
` (04/13) type_specific.io-github-autotest-libvirt.cpu.setvcpu.positive_test.hotplug.order: ERROR: Login timeout expired    (output: "exceeded 60 s timeout, last failure: Client said 'connection refused'    (output: 'ssh: connect to host 192.168.122.181 port 22: Connection refused\\n')") (77.87 s)`
```
(01/13) type_specific.io-github-autotest-libvirt.cpu.setvcpu.positive_test.hotplug.enable_config: PASS (72.79 s)
(02/13) type_specific.io-github-autotest-libvirt.cpu.setvcpu.positive_test.hotplug.disable: PASS (79.23 s)
(03/13) type_specific.io-github-autotest-libvirt.cpu.setvcpu.positive_test.hotplug.disable_config: PASS (76.27 s)
(04/13) …
```
=> cpu: Fix vm login timeout issue

libvirt/tests/cfg/svirt/qemu_conf/svirt_qemu_namespace.cfg, libvirt/tests/src/svirt/qemu_conf/svirt_qemu_namespace.py
This PR adds:
VIRT-296970: Start vm with block device with different qemu
namespace settings
` (1/1) type_specific.io-github-autotest-libvirt.svirt.qemu_conf.namespace: PASS (83.83 s)
`
=> svirt: Add a case about qemu namespace setting

libvirt/tests/cfg/cpu/vcpu_cve.cfg, libvirt/tests/src/cpu/vcpu_cve.py, spell.ignore
This is to check guest cpu's CVE status.
Case ID: VIRT-294940
=> vcpu_cve: add case for cve status

libvirt/tests/src/numa/numa_memory_spread.py
Before memhog, make sure free_mem is larger than memory_to_eat.
Actual_mem greater than memory_to_eat does not ensure memhog success.
Before:
```
ERROR| FAIL 1-type_specific.io-github-autotest-libvirt.numa_memory_spread.positive_test.default -> 
TestFail: Failed to run memhog:Shell command failed: 'memhog -r1 36081766k'    (status: 1,    output: 'numactl: mmap: Cannot allocate memory\n')
```
After:
```
INFO | PASS 1-type_specific.io-github-autotest-libvirt.numa_memory_spread.positive_test.default
```
=> numa: make sure free memory is enough for memhog

libvirt/tests/cfg/memory/allocpages.cfg, libvirt/tests/src/memory/allocpages.py, spell.ignore
This is to test virsh allocpages with below options: --add, --all, --cellno and readonly mode.
=> allocpages: add case for more options

libvirt/tests/src/kernel_panic.py
Since the exception type in verify_kernel_crash is updated, 
the exception called by cases is updated synchronously.
ID: 2179829
Signed-off-by: zhenyzha [zhenyzha@redhat.com](mailto:zhenyzha@redhat.com)
=> kernel_panic:Replace exception call type

libvirt/tests/src/kernel_panic.py
Reverts autotest/tp-libvirt#4812 as depends on prs are not all merged
=> Revert "kernel_panic:Replace exception call type"

libvirt/tests/cfg/backingchain/blockcommit/check_allocation_watermark_during_blockcommit.cfg, libvirt/tests/src/backingchain/blockcommit/check_allocation_watermark_during_blockcommit.py
VIRT-294589 - Check the allocation watermark by domstats during blockcommit
```
/usr/local/bin/avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 backingchain.blockcommit.allocation_watermark
(1/4) type_specific.io-github-autotest-libvirt.backingchain.blockcommit.allocation_watermark.file_disk.inactive_layer: PASS (80.41 s)
(2/4) type_specific.io-github-autotest-libvirt.backingchain.blockcommit.allocation_watermark.file_disk.active_layer: PASS (86.73 s)
(3/4) type_specific.io-github-autotest-libvirt.backingchain.blockcommit.allocation_watermark.block_disk.inactive_layer: PASS (105.48 s)
(4/4) type_specific.io-github-autotest-libvirt.backingchain.blockcommit.allocation_watermark.block_disk.active_layer: PASS (101.72 s)
```
=> backingchain: add case for checking allocation during blockcommit

libvirt/tests/cfg/virtual_network/connectivity/connectivity_check_direct_interface.cfg, libvirt/tests/src/virtual_network/connectivity/connectivity_check_direct_interface.py
- VIRT-296210: [direct] Check the connectivity for direct type interface - bridge, vepa, private
Depends on:
- https://github.com/autotest/tp-libvirt/pull/4804
Test result:
```
(1/3) type_specific.io-github-autotest-libvirt.virtual_network.connectivity_check.direct_interface.br: PASS (143.20 s)
(2/3) type_specific.io-github-autotest-libvirt.virtual_network.connectivity_check.direct_interface.private: PASS (150.08 s)
(3/3) type_specific.io-github-autotest-libvirt.virtual_network.connectivity_check.direct_interface.vepa: PASS (147.00 s)
```
=> Add case of Check the connectivity for direct type interface

libvirt/tests/cfg/svirt/dac/dac_seclabel_overall_domain.cfg, libvirt/tests/src/svirt/dac/dac_seclabel_overall_domain.py
This PR adds:
VIRT-296279 - Start vm with overall domain dac setting
```
(01/31) type_specific.io-github-autotest-libvirt.svirt.dac.seclabel.overall_domain.disable_dynamic_ownership.none.relabel_no.with_img_chown: PASS (14.03 s)
(02/31) type_specific.io-github-autotest-libvirt.svirt.dac.seclabel.overall_domain.disable_dynamic_ownership.none.without_relabel.without_img_chown: PASS (12.42 s)
(03/31) type_specific.io-github-autotest-libvirt.svirt.dac.seclabel.overall_domain.disable_dynamic_ownership.dynamic.relabel_yes.with_img_chown: PASS (13.80 s)
(04/31) type_specific.io-github-autotest-libvirt.svirt.dac.seclabel.overall_domain.disable_dynamic_ownership.dynamic.relabel_yes.without_img_chown: PASS (12.32 s)
(05/31) …
```
=> svirt: Add a case about dac

libvirt/tests/cfg/backingchain/blockcommit/check_allocation_watermark_during_blockcommit.cfg
blockcommit too fast and failed to check the allocation changed
```
avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 backingchain.blockcommit.allocation_watermark --vt-connect-uri qemu:///system
(1/4) type_specific.io-github-autotest-libvirt.backingchain.blockcommit.allocation_watermark.file_disk.inactive_layer: PASS (128.69 s)
(2/4) type_specific.io-github-autotest-libvirt.backingchain.blockcommit.allocation_watermark.file_disk.active_layer: PASS (68.03 s)
(3/4) type_specific.io-github-autotest-libvirt.backingchain.blockcommit.allocation_watermark.block_disk.inactive_layer: PASS (86.75 s)
(4/4) type_specific.io-github-autotest-libvirt.backingchain.blockcommit.allocation_watermark.block_disk.active_layer: PASS (88.38 s)
```
=> fix blockcommit low speed

libvirt/tests/cfg/virtual_network/start_vm_with_duplicate_target_dev_name.cfg, libvirt/tests/src/virtual_network/start_vm_with_duplicate_target_dev_name.py
- VIRT-296224: [network device target] start vm with duplicate target dev name
Test result:
```
(1/8) type_specific.io-github-autotest-libvirt.virtual_network.start_vm.with_duplicate_target_dev_name.network.tap: PASS (10.69 s)
(2/8) type_specific.io-github-autotest-libvirt.virtual_network.start_vm.with_duplicate_target_dev_name.network.macvtap: PASS (10.85 s)
(3/8) type_specific.io-github-autotest-libvirt.virtual_network.start_vm.with_duplicate_target_dev_name.network.network: PASS (11.53 s)
(4/8) type_specific.io-github-autotest-libvirt.virtual_network.start_vm.with_duplicate_target_dev_name.network.direct: PASS (11.47 s)
(5/8) type_specific.io-github-autotest-libvirt.virtual_network.start_vm.with_duplicate_target_dev_name.direct.tap: ERROR: Command 'ip l delete test_iface_l8L' …
```
=> Add network case

libvirt/tests/cfg/virtual_network/connectivity/connectivity_check_network_interface.cfg, libvirt/tests/src/virtual_network/connectivity/connectivity_check_network_interface.py
- VIRT-295262: [network] Check the connectivity for network interface type including nat, route, isolated, open
Depends on:
- https://github.com/autotest/tp-libvirt/pull/4804
Test result:
```
(1/4) type_specific.io-github-autotest-libvirt.virtual_network.connectivity_check.network_interface.nat: PASS (119.49 s)
(2/4) type_specific.io-github-autotest-libvirt.virtual_network.connectivity_check.network_interface.route: PASS (119.27 s)
(3/4) type_specific.io-github-autotest-libvirt.virtual_network.connectivity_check.network_interface.isolated: PASS (100.70 s)
(4/4) type_specific.io-github-autotest-libvirt.virtual_network.connectivity_check.network_interface.open: PASS (15.67 s)
```
=> Add network case Check the connectivity for network interface

libvirt/tests/src/virsh_cmd/secret/virsh_secret_define_undefine.py
Device can not be hot unplugged immediately after hotplug.
Before:
```
ERROR 1-type_specific.io-github-autotest-libvirt.virsh.secret_define_undefine.normal_test.non_acl.ephemeral_yes.libvirtd_timeout -> CmdError: Command '/bin/virsh detach-device avocado-vt-vm1 /tmp/xml_utils_temp_yqqnkxc6.xml' failed.
stdout: b'\n'
stderr: b"error: Failed to detach device from /tmp/xml_utils_temp_yqqnkxc6.xml\nerror: internal error: unable to execute QEMU command 'device_del': Hot-unplug failed: guest is busy (power indicator blinking)\n"
additional_info: None
```
After:
```
PASS 1-type_specific.io-github-autotest-libvirt.virsh.secret_define_undefine.normal_test.non_acl.ephemeral_yes.libvirtd_timeout
```
=> secret_disk: use EventTracker to wait for detach_device to complete

libvirt/tests/src/migration/migrate_with_legacy_guest.py
Guest will automatically add firmware feature information to xml when defining a guest. So use
libvirt_bios.remove_bootconfig_items_from_vmos() to remove this firmware feature.
=> migration: Fix define guest error

libvirt/tests/src/virtio_transitional/virtio_transitional_base.py
In remove_rhel6_nvram function of virtio_transitional_base.py, we can directly reuse libvirt_bios.remove_bootconfig_items_from_vmos(vmxml.os) to manage.
=> virtio_transitional: directly use remove_bootconfig_item_from_vmos function

libvirt/tests/src/virtual_network/start_vm_with_duplicate_target_dev_name.py
To avoid error during cleanup when device not created.
=> Ignore status when cleaning up tap/macvtap device

libvirt/tests/cfg/svirt/svirt_start_destroy.cfg, libvirt/tests/src/svirt/svirt_start_destroy.py
Test result:
>  (1/2) type_specific.io-github-autotest-libvirt.svirt_start_destroy.positive_test.off_destroy.d_svirt_img_s0.no_baselabel.relabel_no.st_none.multi_model.with_qemu_conf.unconfined: PASS (11.27 s)
>  (2/2) type_specific.io-github-autotest-libvirt.svirt_start_destroy.positive_test.off_destroy.d_svirt_img_s0.no_baselabel.relabel_no.st_none.multi_model.without_qemu_conf: PASS (11.20 s)
>
=> svirt_start_destroy:Fix permission issue with tpm device

libvirt/tests/cfg/virsh_cmd/domain/virsh_detach_device_alias.cfg, libvirt/tests/src/virsh_cmd/domain/virsh_detach_device_alias.py
RHEL-148240: Detach redirected usb device by alias
```
/usr/local/bin/avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 virsh.detach_device_alias..redirdev
(1/3) type_specific.io-github-autotest-libvirt.virsh.detach_device_alias.live.redirdev.spicevmc: PASS (29.31 s)
(2/3) type_specific.io-github-autotest-libvirt.virsh.detach_device_alias.config.redirdev.spicevmc: PASS (33.57 s)
(3/3) type_specific.io-github-autotest-libvirt.virsh.detach_device_alias.current.redirdev.spicevmc: PASS (34.34 s)
(1/3) type_specific.io-github-autotest-libvirt.virsh.detach_device_alias.live.redirdev.tcp: PASS (48.93 s)
(2/3) type_specific.io-github-autotest-libvirt.virsh.detach_device_alias.config.redirdev.tcp: PASS (51.25 s)
(3/3) …
```
=> add case for detach redirected usb with alias

libvirt/tests/cfg/libvirtd/libvirtd.cfg, libvirt/tests/src/libvirtd/libvirtd.py, spell.ignore
Test scenario: 
After libvirt packages are upgraded, the libvirtd daemon can be started automatically in modular envionment.
Case ID: VIRT-296902
=> libvirtd: add case for upgrading libvirt

libvirt/tests/cfg/virtual_network/iface_stat.cfg, libvirt/tests/src/virtual_network/iface_stat.py, provider/virtual_network/network_base.py
- VIRT-296993: Get interface stats for a domain by domifstat - ethernet with managed=no
Test result:
```
(1/3) type_specific.io-github-autotest-libvirt.virtual_network.iface_stat.compare.direct_type: PASS (86.62 s)
(2/3) type_specific.io-github-autotest-libvirt.virtual_network.iface_stat.compare.ethernet_type.managed_no.tap: PASS (121.53 s)
(3/3) type_specific.io-github-autotest-libvirt.virtual_network.iface_stat.compare.ethernet_type.managed_no.macvtap: FAIL: Iface stat of host and vm should be close. (101.03 s)
```
The failed case was caused by un-fixed bug
=> Add network case of checking iface statistics

libvirt/tests/cfg/migration/pause_postcopy_migration_and_recover/pause_and_recover_and_disruptive.cfg
Don't need to set 'virsh_migrate_destur = "qemu+tcp://${migrate_dest_host}/system"' for unix_proxy case.
=> migration: Remove some redundant params

libvirt/tests/cfg/migration/pause_postcopy_migration_and_recover/pause_and_disruptive_and_recover.cfg, provider/migration/migration_base.py
1. Due to bug 2166856, we need remove poweroff_dest_vm case.
2. Add a new scenario to test destroy vm on dest.
=> migration: Remove poweroff vm case

libvirt/tests/cfg/virsh_cmd/domain/virsh_detach_device_alias.cfg
Newer libvirt versions add watchdog 'itco' always in certain cases resulting in an additional watchdog element and test failure.
Update the checked substring to match only the removed watchdog.
=> virsh_detach_device_alias: fix watchdog test case

libvirt/tests/src/virtual_disks/virtual_disks_nvme.py
Fix nvme case failure due to pre-existed partitions on nvme device
clean up nvme device partitions before attaching to VM
=> Fix nvme case failure due to pre-existed partitions on nvme device

libvirt/tests/cfg/virsh_cmd/domain/virsh_detach_device_alias.cfg, libvirt/tests/src/virsh_cmd/domain/virsh_detach_device_alias.py
A new watchdog device with model="itco" is added to vm xml by libvirt automatically. So this is to align with this change that the checking method for watchdog device should be changed.
=> virsh_detach_device_alias: fix watchdog device checking

libvirt/tests/cfg/svirt/selinux/selinux_seclabel_overall_domain.cfg, libvirt/tests/src/svirt/selinux/selinux_seclabel_overall_domain.py
This PR adds:
VIRT-296646: Start vm with overall domain selinux setting
```
(01/14) type_specific.io-github-autotest-libvirt.svirt.selinux.seclabel.overall_domain.disable_security_driver.model_selinux.dynamic.relabel_yes.without_label.without_baselabel.without_img_chcon: PASS (11.08 s)
(02/14) type_specific.io-github-autotest-libvirt.svirt.selinux.seclabel.overall_domain.disable_security_driver.model_selinux.static.relabel_yes.label_MCS.without_img_chcon: PASS (11.12 s)
(03/14) type_specific.io-github-autotest-libvirt.svirt.selinux.seclabel.overall_domain.enable_security_driver.model_none.dynamic.relabel_yes.without_label.without_baselabel.without_img_chcon: PASS (13.24 s)
(04/14) type_specific.io-github-autotest-libvirt.svirt.selinux.seclabel.overall_domain.enable_securi …
```
=> svirt: Add a case about selinux

libvirt/tests/cfg/migration/pause_postcopy_migration_and_recover/pause_by_domjobabort_and_recover.cfg, provider/migration/migration_base.py
Executing the domain job abort operation during the migration
process will interrupt the established connection. So for
migrateuri case, checking for "ESTABLISHED" with the netstat
command in do_common_check() fails. We can check established
during migration again.
=> migration: Fix check_established error

libvirt/tests/src/numa/guest_numa.py
In '/proc/{vm_id}/numa_maps' file, there is a change that prefer mode support many now. So the message is changed like below. This patch is to fix the match pattern.
'7f8113e00000 prefer (many):0 anon=218126 dirty=218126 active=211470 N0=218126 kernelpagesize_kB=4'
=> guest_numa: fix prefer keyerror

libvirt/tests/cfg/event/virsh_event.cfg, libvirt/tests/src/event/virsh_event.py
aarch64 supports panic since libvirt-9.1.0
Result:
```
PASS 1-type_specific.io-github-autotest-libvirt.virsh.event.positive_test.virsh_event.test_events.lifecycle_events.crash_panic.no_timeout.loop
```
=> misc -> virsh_event: enable crash_panic test for aarch64

libvirt/tests/cfg/mem/memory_allocation/lifecycle_with_memory_allocation.cfg, libvirt/tests/src/mem/memory_allocation/lifecycle_with_memory_allocation.py, spell.ignore
VIRT-297048: Life cycle with memory allocation
```
/usr/bin/python /usr/local/bin/avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 memory.allocation.lifecycle
(1/3) type_specific.io-github-autotest-libvirt.memory.allocation.lifecycle.positive_test.without_maxmemory: PASS (122.21 s)
(2/3) type_specific.io-github-autotest-libvirt.memory.allocation.lifecycle.positive_test.with_numa: PASS (119.04 s)
(3/3) type_specific.io-github-autotest-libvirt.memory.allocation.lifecycle.negative_test.with_maxmemory: PASS (7.00 s)
```
=> add case for lifecycle with memory allocation

tp-libvirt_review_comment_summary.rst
Add copyright and license template into tp-libvirt_review_comment_summary.rst
This is one good practice when contributing to upstream
=> Add copyright and license template into tp-libvirt

libvirt/tests/cfg/virtual_device/tpm_device.cfg, libvirt/tests/src/virtual_device/tpm_device.py
Do tests with external vtpm by start, suspend_resume, managedsave_start vm, and restart_libvirtd. Need to work with 
- https://github.com/avocado-framework/avocado-vt/pull/3658
To auto VIRT-296943.
=> tpm_device: add external vtpm tests

libvirt/tests/cfg/save_and_restore/save_with_options.cfg, libvirt/tests/src/save_and_restore/save_with_options.py, provider/save/save_base.py
- VIRT-296947: Save vm to file with various options
Depends on:
- https://github.com/avocado-framework/avocado-vt/pull/3649
Test result:
```
(01/10) type_specific.io-github-autotest-libvirt.save.save_with_options.readonly.running.option.no_option: PASS (60.87 s)
(02/10) type_specific.io-github-autotest-libvirt.save.save_with_options.normal.running.option.no_option: PASS (70.85 s)
(03/10) type_specific.io-github-autotest-libvirt.save.save_with_options.normal.running.option.verbose: PASS (70.83 s)
(04/10) type_specific.io-github-autotest-libvirt.save.save_with_options.normal.running.option.running: PASS (70.99 s)
(05/10) type_specific.io-github-autotest-libvirt.save.save_with_options.normal.running.option.paused: PASS (71.10 s)
(06/10) …
```
=> Add case of save with options

libvirt/tests/cfg/virtual_device/tpm_device.cfg, libvirt/tests/src/virtual_device/tpm_device.py
Add invalid xml test for external vtpm, including nonexist, empty and invalid values for source_type, source_mode and source_socket.
To auto VIRT-296945.
=> tpm_device: add invalid xml test for external vtpm

libvirt/tests/cfg/svirt/selinux/selinux_seclabel_per_device.cfg, libvirt/tests/src/svirt/selinux/selinux_seclabel_per_device.py
This PR adds:
VIRT-296954 - Start vm or hotplug with per-device selinux <seclabel> setting
**Test results:** Failed cases are due to a known issue.
```
(01/24) type_specific.io-github-autotest-libvirt.svirt.selinux.seclabel.per_device.relabel_no.disk.cold_plug: PASS (8.38 s)
(02/24) type_specific.io-github-autotest-libvirt.svirt.selinux.seclabel.per_device.relabel_no.disk.hot_plug: PASS (47.28 s)
(03/24) type_specific.io-github-autotest-libvirt.svirt.selinux.seclabel.per_device.relabel_no.serial.cold_plug: PASS (8.81 s)
(04/24) type_specific.io-github-autotest-libvirt.svirt.selinux.seclabel.per_device.relabel_no.serial.hot_plug: PASS (47.14 s)
(05/24) type_specific.io-github-autotest-libvirt.svirt.selinux.seclabel.per_device.relabel_yes.without_label.disk.cold_plug: FAIL: Run …
```
=> svirt: Add a case about per-device selinux setting

libvirt/tests/cfg/mem/memory_allocation/memory_invalid_value.cfg, libvirt/tests/src/mem/memory_allocation/memory_invalid_value.py
VIRT-297062:  invalid memory value
```
avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 memory.allocation.invalid_value
(01/10) type_specific.io-github-autotest-libvirt.memory.allocation.invalid_value.memory.zero: PASS (4.92 s)
(02/10) type_specific.io-github-autotest-libvirt.memory.allocation.invalid_value.memory.minus: PASS (4.82 s)
(03/10) type_specific.io-github-autotest-libvirt.memory.allocation.invalid_value.current_memory.zero: PASS (5.83 s)
(04/10) type_specific.io-github-autotest-libvirt.memory.allocation.invalid_value.current_memory.minus: PASS (4.85 s)
(05/10) type_specific.io-github-autotest-libvirt.memory.allocation.invalid_value.mam_memory.zero: PASS (5.02 s)
(06/10) type_specific.io-github-autotest-libvirt.memory.allocation.invalid_value.mam_memory.mi …
```
=> add case for invalid memory value

libvirt/tests/src/virtual_device/tpm_device.py
"if not source_mode, set as 'connect'" is added for invalid external vtpm testing. Modify to check it only when source_attrs_str exists.
=> tpm_device: fix UnboundLocalError

libvirt/tests/cfg/virtual_network/connectivity/connectivity_check_bridge_interface_unprivileged.cfg, libvirt/tests/src/virtual_network/connectivity/connectivity_check_bridge_interface_unprivileged.py
- VIRT-296209: [bridge] Check connectivity for bridge type interface with QEMU network helper for unprivileged users
Depends on:
- https://github.com/autotest/tp-libvirt/pull/4804
Test result:
```
(1/1) type_specific.io-github-autotest-libvirt.virtual_network.connectivity_check.bridge_interface.unprivileged.default: PASS (109.37 s)
```
=> Add new network case of connectivity check

libvirt/tests/cfg/svirt/dac/dac_seclabel_per_device.cfg, libvirt/tests/src/svirt/dac/dac_seclabel_per_device.py
This PR adds a case:
Start vm or hotplug with per-device dac <seclabel> setting
**Test results:** Failures of relabel_yes.without_label are caused by a known issue.
```
(01/20) type_specific.io-github-autotest-libvirt.svirt.dac.seclabel.per_device.relabel_no.disk.cold_plug: PASS (8.52 s)
(02/20) type_specific.io-github-autotest-libvirt.svirt.dac.seclabel.per_device.relabel_no.disk.hot_plug: PASS (47.52 s)
(03/20) type_specific.io-github-autotest-libvirt.svirt.dac.seclabel.per_device.relabel_no.serial.cold_plug: PASS (9.02 s)
(04/20) type_specific.io-github-autotest-libvirt.svirt.dac.seclabel.per_device.relabel_no.serial.hot_plug: PASS (47.48 s)
(05/20) type_specific.io-github-autotest-libvirt.svirt.dac.seclabel.per_device.relabel_yes.without_label.disk.cold_plug: FAIL: Run '/usr/bin/virsh …
```
=> svirt: Add a case about per-device dac

libvirt/tests/src/migration/migrate_options_shared.py
On latest libvirt version, for postcopy case, no
'Expected downtime' in domjobinfo output.
=> migration: Remove 'Expected downtime' in domjobinfo output

libvirt/tests/src/virsh_cmd/domain/virsh_attach_detach_interface.py
The ethtool output format has changed but the value is correct. Normalize the output and expected string.
=> virsh_attach_detach_interface: fix expected string

libvirt/tests/src/virtual_device/tpm_device.py
Qemu patterns of device_path and backend_type were miswritten by tp-libvirt/pull/4840, failures caused. Fix them.
=> tpm_device: fix passthrough errors

libvirt/tests/cfg/virtual_network/connectivity/connectivity_check_bridge_interface.cfg, libvirt/tests/src/virtual_network/connectivity/connectivity_check_bridge_interface.py
- VIRT-296204: [bridge] Check connectivity for bridge type interface
Depends on:
- https://github.com/autotest/tp-libvirt/pull/4804
Test result:
```
(1/4) type_specific.io-github-autotest-libvirt.virtual_network.connectivity_check.bridge_interface.linux_br.default: PASS (119.69 s)
(2/4) type_specific.io-github-autotest-libvirt.virtual_network.connectivity_check.bridge_interface.linux_br.multiqueue.nwfilter: PASS (126.09 s)
(3/4) type_specific.io-github-autotest-libvirt.virtual_network.connectivity_check.bridge_interface.ovs_br.default: PASS (125.44 s)
(4/4) type_specific.io-github-autotest-libvirt.virtual_network.connectivity_check.bridge_interface.ovs_br.multiqueue.default: PASS (123.47 s)
JOB HTML   : …
```
=> Add case of connectivity check for bridge interface

libvirt/tests/cfg/svirt/label_restore_rules/label_restore_rules_disk_access_modes.cfg, libvirt/tests/cfg/svirt/label_restore_rules/label_restore_rules_on_failed_start.cfg, libvirt/tests/src/svirt/label_restore_rules/label_restore_rules_disk_access_modes.py, libvirt/tests/src/svirt/label_restore_rules/label_restore_rules_on_failed_start.py
This PR adds:
VIRT-296956 - Check svirt label and restore rules for different
disk access modes
VIRT-296957 - Start two guests using the same image
**Test results**
```
(1/4) type_specific.io-github-autotest-libvirt.svirt.label_restore_rules.on_failed_start: PASS (9.43 s)
(2/4) type_specific.io-github-autotest-libvirt.svirt.label_restore_rules.disk_access_modes.readonly: PASS (42.63 s)
(3/4) type_specific.io-github-autotest-libvirt.svirt.label_restore_rules.disk_access_modes.shareable: PASS (58.14 s)
(4/4) type_specific.io-github-autotest-libvirt.svirt.label_restore_rules.disk_access_modes.non_shareable: PASS (50.18 s)
```
=> svirt: Add cases about lable restore rules

provider/save/save_base.py
Before:
```
JOB ID     : 78cd70263ef5c782e60d786a4638d616ac298931                                                                                                                                                                                                                                                                        
JOB LOG    : /var/lib/avocado/job-results/job-2023-05-25T03.18-78cd702/job.log                                                                                                                                                                                                                                               
(1/1) type_specific.io-github-autotest-libvirt.save_and_restore.save_with_options.normal.paused_vm.no_opt: ERROR: Timeout expired while waiting for …
```
=> managed_save: Open a new session to get pid of ping

libvirt/tests/cfg/save_and_restore/save_with_options.cfg, libvirt/tests/src/save_and_restore/save_with_options.py
The bypass cache flag O_DIRECT is arch based.
Before:
```
JOB ID     : 35cf7eb01f03bdbfbea6b30085e1adc85b8fb2df                                                                                                                                 
JOB LOG    : /var/lib/avocado/job-results/job-2023-05-26T03.49-35cf7eb/job.log                                                                                     
(1/1) type_specific.io-github-autotest-libvirt.save_and_restore.save_with_options.normal.running_vm.bypass_cache_opt: FAIL: bypass-cache check fail, please check log (27.45 s)
RESULTS    : PASS 0 | ERROR 0 | FAIL 1 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0                     
JOB HTML   : /var/lib/avocado/job-results/job-2023-05-26T03.49-35cf7eb/results.html …
```
=> managadsave: Update the check method of flag to adapt to all platforms

libvirt/tests/cfg/virtio_transitional/virtio_transitional_vsock.cfg
After we start a guest with vsock, we'll get 
```
03:00.0 Communication controller: Red Hat, Inc. Virtio console (rev 01)
07:00.0 Communication controller: Red Hat, Inc. Virtio socket (rev 01)
```
now. So update the script.
=> Virtio_transitional_vsock: fix a checking result change

libvirt/tests/cfg/conf_file/libvirtd_conf/processing_controls.cfg, libvirt/tests/src/conf_file/libvirtd_conf/processing_controls.py
Fixed comparison of max_clients and max_anonymous_clients since libvirt-9.0.0-2
=> libvirtd: Add libvirt version check

libvirt/tests/cfg/svirt/selinux/selinux_seclabel_per_device.cfg
The serial->target->type for character device on aarch64 is system-serial, and the usable model for system-serial is pl011.
=> svirt: Update serial_attrs to enable test for aarch64

libvirt/tests/cfg/svirt/dac/dac_seclabel_per_device.cfg
The serial->target->type for character device on aarch64 is system-serial, and the usable model for system-serial is pl011.
Test Results:
The failed one is caused by a known issue.
```
(1/4) type_specific.io-github-autotest-libvirt.svirt.dac.seclabel.per_device.relabel_yes.without_label.serial.cold_plug: FAIL: Run '/usr/bin/virsh start avocado-vt-vm1 ' expect fail, but run successfully. (5.89 s)
(2/4) type_specific.io-github-autotest-libvirt.svirt.dac.seclabel.per_device.relabel_yes.with_label.s_qemu.serial.cold_plug: PASS (5.52 s)
(3/4) type_specific.io-github-autotest-libvirt.svirt.dac.seclabel.per_device.relabel_yes.with_label.s_non_root.serial.cold_plug: PASS (5.56 s)
(4/4) type_specific.io-github-autotest-libvirt.svirt.dac.seclabel.per_device.relabel_yes.with_label.none_existing_user. …
```
=> svirt_dac: Update serial_attrs to enable test for aarch64

libvirt/tests/src/virtual_network/passt/passt_function.py, provider/virtual_network/passt.py
Calling cmd_output instead of cmd was a workaround since the status of command could not be found then. Drop this workaround since the problem is fixed.
Depends on:
- https://github.com/avocado-framework/avocado-vt/pull/3695
=> passt:replace session funtion cmd_output with cmd

libvirt/tests/cfg/memory/memory_devices/lifecycle_of_mixed_memory_devices.cfg, libvirt/tests/src/memory/memory_devices/lifecycle_of_mixed_memory_devices.py
VIRT-296942: Life cycle of mixed various memory devices 
**Current result : The failure is caused by known issue** 
```
/usr/bin/python /usr/local/bin/avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 memory.devices.lifecycle.mutiple_mem
(1/1) libvirt.mem.devices.lifecycle.mutiple_mem: ERROR: Command '/bin/virsh restore /tmp/avocado-vt-vm1.save ' failed.\nstdout: b'\n'\nstderr: b"error: Failed to restore domain from /tmp/avocado-vt-vm1.save\nerror:
internal error: qemu unexpectedly closed the monitor: 2023-05-10T09:04:25.558558Z qemu-kvm:
Propertity 'memaddr' changed from 0x1e0000000 to 0x100000000 (172.11 s)
```
**Get result while no bug related step**
```
/usr/bin/python /usr/local/bin/avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 …
```
=> Life cycle of mixed various memory devices

libvirt/tests/cfg/virtual_network/passt/passt_attach_detach.cfg, libvirt/tests/src/virtual_network/passt/passt_attach_detach.py
- VIRT-297073 - [user][passt] Passt backend interface - hotplug/unplug
Depends on:
- https://github.com/avocado-framework/avocado-vt/pull/3667
- https://github.com/avocado-framework/avocado-vt/pull/3668
- https://github.com/avocado-framework/avocado-vt/pull/3673
- https://github.com/avocado-framework/avocado-vt/pull/3676
Test result:
(1/6) type_specific.io-github-autotest-libvirt.virtual_network.passt.attach_detach.ip_portfw.attach.root_user: PASS (341.87 s)
(2/6) type_specific.io-github-autotest-libvirt.virtual_network.passt.attach_detach.ip_portfw.attach.non_root_user: PASS (267.66 s)
(3/6) type_specific.io-github-autotest-libvirt.virtual_network.passt.attach_detach.ip_portfw.detach.root_user: PASS (169.29 s)
(4/6) type_specific.io-github-autotest-libvirt.virtual_network.passt.attach_det …
=> Add case of passt hotplug/unplug

libvirt/tests/cfg/virtual_network/iface_stat.cfg, libvirt/tests/src/virtual_network/iface_stat.py
For direct type interface, the bug fixed since libvirt 9.2.0. Add the version check for it.
=> Add version check for direct type interface

libvirt/tests/cfg/virtual_disks/virtual_disks_cdrom_device.cfg
The iso address for fedora34 has been removed, update the iso address to fedora38.
Before:
```
FAIL 1-type_specific.io-github-autotest-libvirt.virtual_disks.cdrom_device.hotplug.https_cdrom_backend.positive_test -> TestFail: VM failed to start.Error: VM 'avocado-vt-vm1' failed to start: error: Failed to start domain 'avocado-vt-vm1'
error: internal error: qemu unexpectedly closed the monitor: 2023-05-29T12:49:25.076181Z qemu-kvm: -blockdev {"driver":"https","url":"https://dl.fedoraproject.org:443/pub/fedora/linux/releases/34/Server/x86_64/iso/Fedora-Server-netinst-x86_64-34-1.2.iso","node-name":"libvirt-1-storage","auto-read-only":true,"discard":"unmap"}: CURL: Error opening file: The requested URL returned error: 404 Not Found(exit status: 1)
```
After:
```
PASS …
```
=> virtual_disk: Update fedore iso url

libvirt/tests/src/virtual_network/passt/passt_attach_detach.py, libvirt/tests/src/virtual_network/passt/passt_function.py, provider/virtual_network/passt.py
Move utilities to provider for future tests
Test result:
(1/2) type_specific.io-github-autotest-libvirt.virtual_network.passt.attach_detach.ip_portfw.attach_detach.root_user: PASS (259.49 s)
(2/2) type_specific.io-github-autotest-libvirt.virtual_network.passt.interface_function.ip_portfw.non_root_user: PASS (419.86 s)
=> passt:move utilities to provider

libvirt/tests/src/backingchain/blockcopy/blockcopy_with_conventional_chain.py, libvirt/tests/src/backingchain/blockjob/blockjob_with_raw_option.py, libvirt/tests/src/backingchain/blockjob_options.py, libvirt/tests/src/virsh_cmd/domain/virsh_blockcopy.py
blockcopy process changes from 100% to 100.00%
```
/usr/local/bin/avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 backingchain.blockcopy.conventional_chain.file_disk.with_shallow backingchain.blockcopy.conventional_chain.file_disk.without_shallow backingchain.blockcopy.conventional_chain.block_disk.with_shallow backingchain.blockcopy.conventional_chain.block_disk.without_shallow backingchain.blockcopy.conventional_chain.rbd_with_auth_disk.with_shallow  backingchain.blockcopy.conventional_chain.rbd_with_auth_disk.without_shallow backingchain.blockjob.raw.raw_list backingchain.blockjob.options.option_raw backingchain.blockcopy.async_option.async
(1/9) type_specific.io-github-autotest-libvirt.backingchain.blockcopy.conventional_ …
```
=> fix blockcopy process num type changes to float

libvirt/tests/cfg/host_hypervisor/capabilities_output.cfg, libvirt/tests/src/host_hypervisor/capabilities_output.py
This PR adds:
VIRT-297680: Check machine types in virsh capabilities
` (1/1) type_specific.io-github-autotest-libvirt.capabilities.output.machine_types: PASS (6.67 s)
`
=> host_hypervisor: Add a case about guest machine types

libvirt/tests/cfg/save_and_restore/save_with_options.cfg
Output updated from 100 % to 100.00 %
Test result:
PASS 1-type_specific.io-github-autotest-libvirt.save_and_restore.save_with_options.normal.running_vm.verbose_opt
=> save_with_options:Update target pattern to search for

libvirt/tests/cfg/migration/migrate_options_shared.cfg, libvirt/tests/src/migration/migrate_options_shared.py
In new libvirt version, compression method 'xbzrle' isn't supported with parallel migration. So update code.
=> migration: Update case for parallel migration

provider/backingchain/check_functions.py
Return correct error message   
```
avocado run --vt-type libvirt --test-runner=runner --vt-machine-type s390-virtio backingchain.blockcommit.shallow_option.file_disk.snap_type.disk_only --vt-connect-uri qemu:///system
(1/1) backingchain.blockcommit.shallow_option.file_disk.snap_type.disk_only: 
FAIL: File:/dev/vdb hash :8565a714dca840f8652c5bae9249ab05f5fb5a4f9f13fbe23304b10f68252da2  /dev/vdb\n is
different from hash before **blockcommit:test:old hash** (64.27 s)
```
=> fix check hash function error msg

libvirt/tests/cfg/domain_life_cycle/create_destroy_domain.cfg, libvirt/tests/src/domain_life_cycle/create_destroy_domain.py
Fix domain_life_cycle.undefine_domain.positive.wipe_storage case failure
"images" pool path may be changed by CI, rather than default:/var/lib/libvirt/images
So it need dynamically get path,then create volume under that
=> Fix domain_life_cycle.undefine_domain.positive.wipe_storage case failure

libvirt/tests/src/backingchain/blockjob/blockjob_pivot_after_irregular_operations.py, libvirt/tests/src/backingchain/blockjob/blockjob_with_raw_option.py, libvirt/tests/src/backingchain/blockjob_options.py, libvirt/tests/src/backingchain/negative_scenario/blockcopy_with_invalid_destination.py, libvirt/tests/src/virsh_cmd/domain/virsh_blockjob.py, libvirt/tests/src/virtual_disks/virtual_disks_metadatacache.py
100% turns to be 100.00%
```
avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35  backingchain.blockjob.pivot virsh.blockjob.positive_test.pivot_option backingchain.blockjob.raw backingchain.blockcopy.invalid_destination..absolute_path
(1/5) type_specific.io-github-autotest-libvirt.backingchain.blockjob.pivot.before_finish: PASS (49.32 s)
(2/5) type_specific.io-github-autotest-libvirt.backingchain.blockjob.pivot.delete_copy_file: PASS (57.49 s)
(3/5) type_specific.io-github-autotest-libvirt.virsh.blockjob.positive_test.pivot_option: PASS (60.29 s)
(4/5) type_specific.io-github-autotest-libvirt.backingchain.blockjob.raw.raw_list: PASS (69.64 s)
(5/5) type_specific.io-github-autotest-libvirt.backingchain.blockcopy.invalid_destinati …
```
=> fix 100 percent match issue

libvirt/tests/cfg/svirt/qemu_conf/svirt_qemu_security_confined.cfg, libvirt/tests/src/svirt/qemu_conf/svirt_qemu_security_confined.py
This PR adds:
virt-296975: Start vm with security confined options in qemu.conf
```
(1/6) type_specific.io-github-autotest-libvirt.svirt.qemu_conf.security_confined.positive_test.seclabel_none.require_confined_0.default_confined_0: |^[[PASS (10.49 s)
(2/6) type_specific.io-github-autotest-libvirt.svirt.qemu_conf.security_confined.positive_test.seclabel_none.require_confined_0.default_confined_1: PASS (10.65 s)
(3/6) type_specific.io-github-autotest-libvirt.svirt.qemu_conf.security_confined.positive_test.default.require_confined_0.default_confined_1: PASS (9.98 s)
(4/6) type_specific.io-github-autotest-libvirt.svirt.qemu_conf.security_confined.positive_test.default.require_confined_1.default_confined_1: PASS (10.17 s)
(5/6) …
```
=> svirt: Add a case about security confined options

libvirt/tests/cfg/guest_agent/domhostname.cfg, libvirt/tests/src/guest_agent/domhostname.py
This PR adds:
Get domain's hostname via guest agent
```
(1/3) type_specific.io-github-autotest-libvirt.guest_agent.domhostname.domain_name: PASS (94.24 s)
(2/3) type_specific.io-github-autotest-libvirt.guest_agent.domhostname.domain_ID: PASS (88.65 s)
(3/3) type_specific.io-github-autotest-libvirt.guest_agent.domhostname.domain_UUID: PASS (89.79 s)
```
- https://github.com/avocado-framework/avocado-vt/pull/3701
=> guest_agent: Add a case about domhostname

libvirt/tests/cfg/svirt/umask_value/svirt_umask_files_accessed_by_qemu.cfg, libvirt/tests/src/svirt/umask_value/svirt_umask_files_accessed_by_qemu.py
This PR adds:
VIRT-296968: Test libvirt creates all the files which could
be accessed by qemu user
` (1/1) type_specific.io-github-autotest-libvirt.svirt.umask.files_accessed_by_qemu: PASS (29.62 s)
`
=> svirt: Add a case about umask value

libvirt/tests/cfg/svirt/shared_storage/svirt_nfs_disk.cfg, libvirt/tests/src/svirt/shared_storage/svirt_nfs_disk.py
This pr adds:
VIRT-296978 [sVirt]Start vm with different virt_use_nfs
settings and no_root_squash/root_squash nfs storage
- https://github.com/avocado-framework/avocado-vt/pull/3703
- https://github.com/avocado-framework/avocado-vt/pull/3704
```
(1/3) type_specific.io-github-autotest-libvirt.svirt.shared_storage.nfs_disk.virt_use_nfs_on.root_squash: PASS (10.61 s)
(2/3) type_specific.io-github-autotest-libvirt.svirt.shared_storage.nfs_disk.virt_use_nfs_on.no_root_squash: PASS (13.54 s)
(3/3) type_specific.io-github-autotest-libvirt.svirt.shared_storage.nfs_disk.virt_use_nfs_off.no_root_squash: PASS (10.71 s)
```
=> svirt: Add a case about nfs storage

libvirt/tests/cfg/guest_agent/guest_agent.cfg, libvirt/tests/src/guest_agent/guest_agent.py
This PR adds:
VIRT-87354 - Hotplug guest agent char device without target type
` (1/1) type_specific.io-github-autotest-libvirt.guest_agent.negative.ga_started.hotplug_ga_without_tgt_type: PASS (63.07 s)`
=> guest_agent: Add a case of attaching invalid device xml

libvirt/tests/src/virtual_disks/virtual_disks_metadatacache.py
Extend job timeout to 500 seconds
Occasionally, block job will be timeout if value is 300
=> Extend job timeout to 500 seconds

libvirt/tests/cfg/migration/migration_performance_tuning/migration_zerocopy_unsupported_feature_combinations.cfg
To test 'zerocopy + parallel + zlib compression'.
Case update:
VIRT-XXXX - VM live migration - zerocopy - unsupported feature combinations
=> migration: Add a scenario to test zlib compression

libvirt/tests/cfg/guest_os_booting/ovmf_firmware/ovmf_loader.cfg, libvirt/tests/src/guest_os_booting/ovmf_firmware/ovmf_loader.py
Now we get "TestFail: XML did not match text '/usr/share/edk2/ovmf/OVMF.amdsev.fd' for the xpath './/loader[@stateless='yes']" error for stateless test. This PR can fix it.
=> guest_os_booting: fix stateless xml don't match error

libvirt/tests/cfg/svirt/shared_storage/svirt_nfs_disk.cfg
`Test results:` 
```
(1/3) type_specific.io-github-autotest-libvirt.svirt.shared_storage.nfs_disk.virt_use_nfs_on.root_squash: PASS (7.47 s)
(2/3) type_specific.io-github-autotest-libvirt.svirt.shared_storage.nfs_disk.virt_use_nfs_on.no_root_squash: PASS (9.65 s)
(3/3) type_specific.io-github-autotest-libvirt.svirt.shared_storage.nfs_disk.virt_use_nfs_off.no_root_squash: PASS (7.58 s)
```
=> svirt: Fix incorrect 'status_error' issue

libvirt/tests/cfg/svirt/shared_storage/svirt_nfs_disk.cfg
Enable nfs settings in svirt_nfs_disk case so as not to affect other cases.
=> svirt: Change nfs settings from global to test case specific

libvirt/tests/cfg/sriov/vIOMMU/iommu_device_settings.cfg, libvirt/tests/src/sriov/vIOMMU/iommu_device_settings.py, provider/sriov/check_points.py, provider/sriov/sriov_base.py
This PR adds:
VIRT-294579: [vIOMMU] Start vm with virtio devices and iommu enabled
**Test results:** the failure is caused by a bug.
```
(01/16) type_specific.io-github-autotest-libvirt.vIOMMU.iommu_device_settings.e1000e.virtio: PASS (94.43 s)
(02/16) type_specific.io-github-autotest-libvirt.vIOMMU.iommu_device_settings.e1000e.intel: PASS (245.47 s)
(03/16) type_specific.io-github-autotest-libvirt.vIOMMU.iommu_device_settings.rtl8139.virtio: PASS (75.76 s)
(04/16) type_specific.io-github-autotest-libvirt.vIOMMU.iommu_device_settings.rtl8139.intel: PASS (246.57 s)
(05/16) type_specific.io-github-autotest-libvirt.vIOMMU.iommu_device_settings.virtio_muti_devices.vhost_on.virtio: PASS (78.44 s)
(06/16) type_specific.io-github-autotest-libvirt.vIOMMU.iommu_device_settings.virtio_muti_devices.v …
```
=> sriov: Add a case about iommu_device_settings

libvirt/tests/src/svirt/umask_value/svirt_umask_files_accessed_by_qemu.py
Update to restart libvirtd to avoid permission issue.
`VMStartError: VM 'avocado-vt-vm1' failed to start: error: Failed to start domain 'avocado-vt-vm1'error: internal error: qemu unexpectedly closed the monitor: 2023-06-25T08:38:19.273408Z qemu-kvm: can't open backing store /dev/hugepages/libvirt/qemu/2-avocado-vt-vm1 for guest RAM: Permission denied(exit status: 1)&#10;`
` (1/1) type_specific.io-github-autotest-libvirt.svirt.umask.files_accessed_by_qemu:PASS (21.09 s)
`
=> svirt: Fix a permission issue

libvirt/tests/cfg/snapshot/memory_snapshot_delete.cfg, libvirt/tests/src/snapshot/memory_snapshot_delete.py
libvirt version checking is missing.
=> memory_snapshot_delete: fix version checking

libvirt/tests/cfg/numa/guest_numa_topology/various_numa_topology_settings.cfg
Enable tests for aarch64 with the following changes:
1. cpu model: aarch64 support host-passthrough
2. target_hugepages: Reduce the number of huge pages to 32, because the default pagesize of aarc64 is 512M, creating 1024 hugepages requires a lot of free memory on the machine
Test Results are as follows, the 3 cases that still fail should be other issues which failed on x86 too.
```
(01/16) type_specific.io-github-autotest-libvirt.guest_numa_topology.various_numa_topology_settings.discard_none.memaccess_none: PASS (42.42 s)
(02/16) type_specific.io-github-autotest-libvirt.guest_numa_topology.various_numa_topology_settings.discard_none.memaccess_shared: PASS (46.75 s)
(03/16) type_specific.io-github-autotest-libvirt.guest_numa_topology.various_numa_topology_settings.discard_none.memaccess_p …
```
=> numa_various_numa_topology_settings: Enable test for aarch64

libvirt/tests/cfg/numa/guest_numa_topology/numa_topology_with_numa_distance.cfg
cpu model: aarch64 support host-passthrough
Test Result:
```
(1/2) type_specific.io-github-autotest-libvirt.guest_numa_topology.numa_topology_with_numa_distance.symmetrical: PASS (105.10 s)
(2/2) type_specific.io-github-autotest-libvirt.guest_numa_topology.numa_topology_with_numa_distance.asymmetrical: PASS (106.04 s)
```
=> numa_topology_with_numa_distance: Enable test for aarch64

libvirt/tests/src/numa/guest_numa_node_tuning/memory_binding_setting.py
This is to fix the different cgroup path for V1.
=> memory_binding_setting: fix cgroup v1 checking

libvirt/tests/cfg/guest_os_booting/ovmf_firmware/ovmf_loader.cfg, libvirt/tests/src/guest_os_booting/ovmf_firmware/ovmf_loader.py, provider/guest_os_booting/guest_os_booting_base.py
Fix two version issues in this PR:
1) --reset-nvram option is not supported in RHEL8 but we need to test
this auto case. So don't use it in the test steps.
2) The stateless is supported from libvirt-8.6.0. So test it from this
version.
=> guest_os_booting: fix the unsupported version issues

libvirt/tests/cfg/svirt/umask_value/svirt_umask_files_accessed_by_qemu.cfg
Reduce the target_hugepages to 4, because the default pagesize of aarc64 is 512M
Before:
```
ERROR 1-type_specific.io-github-autotest-libvirt.svirt.umask.files_accessed_by_qemu -> ValueError: Cannot set the kernel hugepage setting to the target value of 1024 hugepages.
```
After:
```
PASS 1-type_specific.io-github-autotest-libvirt.svirt.umask.files_accessed_by_qemu
```
=> svirt_umask_value: Enable test for aarch64

libvirt/tests/cfg/numa/numa_node_tuning/invalid_nodeset_of_numa_memory_binding.cfg, libvirt/tests/src/numa/numa_node_tuning/invalid_nodeset_of_numa_memory_binding.py
VIRT-297676: Invalid nodeset of numa memory binding settings
Two cases failed : restrictive mode , guest binding get error ,confirmed with lcong: due to bz#2208946, bz#2185184, bz#2138150
```
avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35  guest_numa_node_tuning.invalid_nodeset
(01/16) type_specific.io-github-autotest-libvirt.guest_numa_node_tuning.invalid_nodeset.host.partially_inexistent.strict: PASS (5.43 s)
(02/16) type_specific.io-github-autotest-libvirt.guest_numa_node_tuning.invalid_nodeset.host.partially_inexistent.interleave: PASS (5.92 s)
(03/16) type_specific.io-github-autotest-libvirt.guest_numa_node_tuning.invalid_nodeset.host.partially_inexistent.preferred: PASS (5.78 s)
(04/16) …
```
=> numa: add case for invalid nodeset of numa memory binding

libvirt/tests/cfg/memory/memory_allocation/lifecycle_with_memory_allocation.cfg, libvirt/tests/cfg/memory/memory_allocation/memory_invalid_value.cfg, libvirt/tests/src/memory/memory_allocation/memory_invalid_value.py
**First case:** 
Before fixed
```
avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 memory.allocation.invalid_value.numa.zero --vt-connect-uri qemu:///system
(1/1) type_specific.io-github-autotest-libvirt.memory.allocation.invalid_value.numa.zero: FAIL: XML did not match text '0' for the xpath './/cell[@id='0']' (8.01 s)
```
After fixed, lcong has confirmed that the test should cancel if libvirt version <9.0  for zero &numa scenario
```
avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 memory.allocation.invalid_value.numa.zero --vt-connect-uri qemu:///system
(1/1) type_specific.io-github-autotest-libvirt.memory.allocation.invalid_value.numa.zero: CANCEL: This libvirt version doesn't support this function. (7.36 s)
```
=> fix memory xml not match

libvirt/tests/src/migration/pause_postcopy_migration_and_recover/pause_by_domjobabort_and_recover.py
To fix following issue:
error: Failed to open file '/tmp/xml_utils_temp_q7dt66ez.xml':
No such file or directory'
=> migration: Fix no xml file issue

libvirt/tests/src/conf_file/qemu_conf/seccomp_sandbox.py
Check that a syntax error is logged if an invalid value is set.
=> conf_file/qemu_conf/seccomp: add checkpoint for invalid value

libvirt/tests/src/backingchain/blockcommit/blockcommit_all_block_chain.py, libvirt/tests/src/backingchain/blockcommit/blockcommit_base_image_exist_backingfile.py, libvirt/tests/src/backingchain/blockcommit/blockcommit_conventional_chain.py, libvirt/tests/src/backingchain/blockcommit/blockcommit_with_delete_option.py, libvirt/tests/src/backingchain/blockcommit/blockcommit_with_keep_overlay.py, libvirt/tests/src/backingchain/blockcommit/blockcommit_with_shallow_option.py, libvirt/tests/src/backingchain/blockcopy/blockcopy_with_backingfile.py, libvirt/tests/src/backingchain/blockcopy/blockcopy_with_blockdev_option.py, libvirt/tests/src/backingchain/blockcopy/blockcopy_with_conventional_chain.py, libvirt/tests/src/backingchain/blockpull/blockpull_base_image_exist_backingfile.py, libvirt/tests/src/backingchain/blockpull/blockpull_conventional_chain.py, provider/backingchain/blockcommand_base.py
In s390x, the disk drive number vdb will be changed but not a stable one. So the hash checking will check the bootable disk but not the tested disk. That will cause different hash value contrast. This PR can be fixed to check test disks.
=> backingchain: fix s390x issue by using correct guest disk to check

libvirt/tests/cfg/timer_management.cfg
After modifying the logic in qemu code,it cannot create HPET device, and hpet is disabled by default, so remove the cases.
=> timer_management: Remove hpet related cases.

libvirt/tests/src/numa/numa_memory_spread.py
1. Decrease memory size from the neighbour
2. Drop caches first to make sure host has enough memory
Before:
```
ERROR| ERROR 1-type_specific.io-github-autotest-libvirt.numa_memory_spread.positive_test.default -> CmdError: Command '/usr/bin/virsh start avocado-vt-vm1 ' failed.
stdout: b'\n'
stderr: b"error: Failed to start domain 'avocado-vt-vm1'\nerror: internal error: qemu unexpectedly closed the monitor: 2023-07-03T08:21:57.926073Z qemu-kvm: cannot set up guest memory 'mach-virt.ram': Cannot allocate memory\n"
```
After:
```
INFO | PASS 1-type_specific.io-github-autotest-libvirt.numa_memory_spread.positive_test.default
```
=> numa_memory_spread: Make sure enough memory for guest

libvirt/tests/cfg/memory/memory_devices/lifecycle_of_mixed_memory_devices.cfg, libvirt/tests/src/memory/memory_devices/lifecycle_of_mixed_memory_devices.py
Before fixed
```
avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 memory.devices.lifecycle.mutiple_mem --vt-connect-uri qemu:///system
(1/1) type_specific.io-github-autotest-libvirt.memory.devices.lifecycle.mutiple_mem: ERROR: Failed to define avocado-vt-vm1 for reason:\nsetlocale: No such file or directory\nerror: Failed to define domain from /tmp/xml_utils_temp_6shka80q.xml\nerror: unsupported configuration: virtio-mem isn't supported by this QEMU binary\n (79.04 s)
```
After fixed
```
avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 memory.devices.lifecycle.mutiple_mem --vt-connect-uri qemu:///system
(1/1) type_specific.io-github-autotest-libvirt.memory.devices.lifecycle.mutiple_mem: CANCEL: Got host kernel version:4.18.0-499, which is …
```
=> fix version issue for virtio-mem

libvirt/tests/cfg/numa/guest_numa_topology/numa_topology_with_cpu_topology.cfg
dies is not supported on arm cpu topology
=> numa_topology: skip dies related tests on aarch64

libvirt/tests/cfg/numa/guest_numa_node_tuning/memory_binding_with_emulator_thread.cfg, libvirt/tests/cfg/numa/guest_numa_topology/various_numa_topology_settings.cfg, libvirt/tests/src/numa/guest_numa_node_tuning/memory_binding_with_emulator_thread.py, libvirt/tests/src/numa/guest_numa_topology/various_numa_topology_settings.py
Test on 8 & 9, when set discrad as no, their behavior is different.
on 9.3, the discard-data is false in the qemu cmd line
on 8.9, no discard-data para in the qemu cmd line
Has confirmed with feature owner, both behavior have the same effect.
Before fix on 8:
```
FAIL 1-type_specific.io-github-autotest-libvirt.guest_numa_topology.various_numa_topology_settings.discard_no.memaccess_none -> TestFail: Expecting 'discard-data' does exist in qemu command line, but  notfound
```
After fix on 8.
```
(1/4) type_specific.io-github-autotest-libvirt.guest_numa_topology.various_numa_topology_settings.discard_no.memaccess_none: PASS (48.29 s)
(2/4) type_specific.io-github-autotest-libvirt.guest_numa_topology.various_numa_topology_settings.discard_no.memaccess_shared: PASS (51.14 s)
(3/4) …
```
=> numa: Add version check for discard and emulator tests

libvirt/tests/src/numa/guest_numa_node_tuning/memory_binding_with_emulator_thread.py
The error message is expected on starting the vm instead of defining the vm.
=> memory_binding_with_emulator_thread: fix error message

libvirt/tests/cfg/numa/guest_numa_node_tuning/invalid_nodeset_of_numa_memory_binding.cfg
On 8, when testing for invalid nodeset with host numa nodes, it outputs "error : unsupported...".
There is a space between error and :, remove "error:" to fit tests on all releases.
Results as follows, the failed two cases are caused by a minor known bug, which won't fix on 8. And I have add them to the skiplist in ibvirt_ci.
```
(01/16) type_specific.io-github-autotest-libvirt.guest_numa_node_tuning.invalid_nodeset.host.partially_inexistent.strict: FAIL: Expect 'unsupported configuration: NUMA node 2 is unavailable' in 'VM 'avocado-vt-vm1' failed to start: error: Failed to start domain 'avocado-vt-vm1'\nerror: Invalid value '1-2' for 'cpuset.mems': Invalid argument(exit status: 1)'  (9.47 s)
(02/16) type_specific.io-github-autotest-libvirt.guest_numa_node_tuning.invalid_nodeset.host.parti …
```
=> numa_invalid_nodes: Update error message

libvirt/tests/cfg/sriov/vm_lifecycle/sriov_vm_lifecycle_reboot.cfg, libvirt/tests/src/sriov/vm_lifecycle/sriov_vm_lifecycle_reboot.py, provider/sriov/check_points.py
This PR adds a 2 vfs hostdev interfaces to check ping latency.
```
(01/16) type_specific.io-github-autotest-libvirt.sriov.vm_lifecycle.reboot.hostdev_interface.vf_address.managed_yes.with_iommu: PASS (292.15 s)
(02/16) type_specific.io-github-autotest-libvirt.sriov.vm_lifecycle.reboot.hostdev_interface.vf_address.managed_yes.without_iommu: PASS (127.93 s)
(03/16) type_specific.io-github-autotest-libvirt.sriov.vm_lifecycle.reboot.hostdev_interface.vf_address.managed_no.without_iommu: PASS (101.33 s)
(04/16) type_specific.io-github-autotest-libvirt.sriov.vm_lifecycle.reboot.hostdev_interface.vf_address.without_managed.without_iommu: PASS (101.20 s)
(05/16) type_specific.io-github-autotest-libvirt.sriov.vm_lifecycle.reboot.hostdev_interface.vf_address.vlan.without_iommu: …
```
=> sriov: Add a checkpoint to check ping latency

libvirt/tests/cfg/numa/guest_numa_node_tuning/memory_binding_setting.cfg, libvirt/tests/src/numa/guest_numa_node_tuning/memory_binding_setting.py
The default hugepage pagesize is 512M on aarch64, do some changes to enable tests for it.
Results as follows, the failed cases are other known issues which failed on x86 too.
```
(01/12) type_specific.io-github-autotest-libvirt.guest_numa_node_tuning.memory_binding_setting.default_pagesize.mem_mode_strict.single_host_node: PASS (41.44 s)
(02/12) type_specific.io-github-autotest-libvirt.guest_numa_node_tuning.memory_binding_setting.default_pagesize.mem_mode_interleave.single_host_node: FAIL: Expect cpuset.mems in path '/sys/fs/cgroup/cpuset/machine.slice/machine-qemu\x2d1\x2davocado\x2dvt\x2dvm1.scope/libvirt/emulator/cpuset.mems' to be '', but found '0-1' (43.79 s)
(03/12) type_specific.io-github-autotest-libvirt.guest_numa_node_tuning.memory_binding_setting.default_pagesize.mem_mode_prefe …
```
=> numa_memory_binding_setting: Enable tests for aarch64

libvirt/tests/cfg/libvirt_rng.cfg, libvirt/tests/src/libvirt_rng.py
1. In the past, libvirtd crashed on invalid address.
Checking error message on invalid address setting
confirms libvirtd handles this correctly.
2. Check error message on invalid model.
=> libvirt_rng: add test case with invalid XML

libvirt/tests/cfg/chardev/log/chardev_with_log_file.cfg, libvirt/tests/src/chardev/log/chardev_with_log_file.py
VIRT-296959:chardev with log file
```
avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 chardev.log
(1/2) type_specific.io-github-autotest-libvirt.chardev.log.console.pty: PASS (52.07 s)
(2/2) type_specific.io-github-autotest-libvirt.chardev.log.console.unix: PASS (52.49 s)
```
Depend on https://github.com/avocado-framework/avocado-vt/pull/3717
=> chardev: add case for chardev with log file

libvirt/tests/cfg/cpu/iothread.cfg
The type of iothread's 'poll*' attributes were changed from unsigned int to unsigned long long and the validation of iothread 'poll-' value were removed from codes, so deleting the related cases.
=> cpu: Remove cases about iothread 'poll-' value validation

libvirt/tests/cfg/virtual_network/passt/passt_transfer_file.cfg, libvirt/tests/src/virtual_network/passt/passt_transfer_file.py, spell.ignore
- VIRT-297076: [user][passt] Passt backend interface - transfter a file between guest and host through tcp4/6
Test result:
(01/16) type_specific.io-github-autotest-libvirt.virtual_network.passt.transfer_file.ipv4.host_to_vm.10M.ip_portfw.root_user: PASS (153.82 s)
(02/16) type_specific.io-github-autotest-libvirt.virtual_network.passt.transfer_file.ipv4.host_to_vm.10M.ip_portfw.non_root_user: PASS (84.61 s)
(03/16) type_specific.io-github-autotest-libvirt.virtual_network.passt.transfer_file.ipv4.host_to_vm.1G.ip_portfw.root_user: PASS (225.39 s)
(04/16) type_specific.io-github-autotest-libvirt.virtual_network.passt.transfer_file.ipv4.host_to_vm.1G.ip_portfw.non_root_user: PASS (90.43 s)
(05/16) type_specific.io-github-autotest-libvirt.virtual_network.passt.transfer_file.ipv4.vm_to_host.10M. …
=> Add passt case of transferring file

libvirt/tests/cfg/chardev/connection_and_operation/data_transfer.cfg, libvirt/tests/src/chardev/connection_and_operation/data_transfer.py, provider/chardev/chardev_base.py
This pr did two things:
1. Remove console device and  serial target case, due to it's removed on polarion case
2. Not get transferred message  issue on x86
Before fixed
```
avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 chardev.data_transfer.serial.pci_target.pipe --vt-connect-uri qemu:///system
(1/1) type_specific.io-github-autotest-libvirt.chardev.data_transfer.serial.pci_target.pipe: FAIL: Check host msg failed due to . (139.78 s)
```
After fixed
```
- avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 chardev.data_transfer --vt-connect-uri qemu:///system
(1/8) type_specific.io-github-autotest-libvirt.chardev.data_transfer.console.virtio_target.file: PASS (148.72 s)
(2/8) type_specific.io-github-autotest-libvirt.chardev.data_transfer.conso …
```
=> fix chardev get message failed

provider/guest_os_booting/guest_os_booting_base.py
We use libvirt_bios.remove_bootconfig_items_from_vmos(vmxml.os) in guest_os_booting_base.py. But for some ovmf guest which test the common attributes same with seabios guest. There's no need to run this step. So add a condition here.
=> guest_os_booting_base.py: add firmware_type argument for ovmf guest

libvirt/tests/src/virtual_disks/virtual_disks_multidisks.py
sleep 3s to wait for the disk be ready after attaching the disk to guest
Before:
```
FAIL 1-type_specific.io-github-autotest-libvirt.virtual_disks.multidisks.coldplug.single_disk_test.disk_readonly_nfs_cdrom.coldplug_with_at_dt_disk -> TestFail: Checking disk readonly option failed
```
After:
```
PASS 1-type_specific.io-github-autotest-libvirt.virtual_disks.multidisks.coldplug.single_disk_test.disk_readonly_nfs_cdrom.coldplug_with_at_dt_disk
```
=> virtual_disk: wait for the disk be ready in guest

libvirt/tests/cfg/save_and_restore/save_image_dumpxml.cfg, libvirt/tests/src/save_and_restore/save_image_dumpxml.py
- VIRT-297301 - Dumpxml from saved file by save-image-dumpxml cmd
(1/6) type_specific.io-github-autotest-libvirt.save_and_restore.save_image_dumpxml.readonly.no_opt: PASS (52.49 s)
(2/6) type_specific.io-github-autotest-libvirt.save_and_restore.save_image_dumpxml.readonly.security_info_opt: PASS (49.81 s)
(3/6) type_specific.io-github-autotest-libvirt.save_and_restore.save_image_dumpxml.normal.no_opt: PASS (49.82 s)
(4/6) type_specific.io-github-autotest-libvirt.save_and_restore.save_image_dumpxml.normal.security_info_opt: PASS (52.57 s)
(5/6) type_specific.io-github-autotest-libvirt.save_and_restore.save_image_dumpxml.normal.xpath_opt.default: PASS (56.51 s)
(6/6) type_specific.io-github-autotest-libvirt.save_and_restore.save_image_dumpxml.normal.xpath_opt.wrap: PASS (49.79 s)
RESULTS …
=> Add case of save-image-dumpxml

libvirt/tests/cfg/virtual_device/filesystem_device.cfg, libvirt/tests/src/virtual_device/filesystem_device.py
VIRT-298224: Verify the libvirt can identify shared memory after restart libvirtd/virtqemud
```
avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 virtual_devices.filesystem_device.positive_test.file_backed.lifecycle.restart_service.fs_test.xattr_on.flock_off.lock_posix_off.cache_mode_none.thread_pool_noset.one_fs.one_guest
(1/1) type_specific.io-github-autotest-libvirt.virtual_devices.filesystem_device.positive_test.file_backed.lifecycle.restart_service.fs_test.xattr_on.flock_off.lock_posix_off.cache_mode_none.thread_pool_noset.one_fs.one_guest: PASS (39.41 s)
```
=> virtiofs : add case for restart service after config shared memory

libvirt/tests/src/virtual_network/iface_stat.py
When the traffic is too small, the ratio of iface stat data between host ande guest may be relatively large, increasing the traffic and making the data used for comparison more reliable.
Before:
```
FAIL 1-type_specific.io-github-autotest-libvirt.virtual_network.iface_stat.compare.ethernet_type.managed_no.tap -> TestFail: Iface stat of host and vm should be close.
```
After:
```
PASS 1-type_specific.io-github-autotest-libvirt.virtual_network.iface_stat.compare.ethernet_type.managed_no.tap
```
=> virtual_networks: Increase trafic for comparing iface stat between host and guest

provider/migration/base_steps.py
Updated to use a simpler function to modify the 1st disk of VM.
` (1/1) type_specific.io-github-autotest-libvirt.migration.migration_uri.desturi.ipv4.tcp.p2p: PASS (515.96 s)
`
=> migration: Replace set_vm_disk with modify_vm_device

libvirt/tests/cfg/sriov/vm_lifecycle/sriov_vm_lifecycle_managedsave.cfg
Update error message to handle the latest change.
` (1/1) type_specific.io-github-autotest-libvirt.sriov.vm_lifecycle.managedsave.hostdev_device.vf_address.managed_yes: PASS (49.74 s)`
=> sriov: Fixup an issue due to error message change

libvirt/tests/src/virtual_disks/virtual_disks_multivms.py
Wait for the partition to be ready before making a file system on it.
Before:
```
ERROR 1-type_specific.io-github-autotest-libvirt.virtual_disks.multivms.coldplug.vms_sharable_test.block_type -> CmdError: Command 'mkfs.ext3 -F /dev/sdb1 ' failed
```
After:
```
PASS 1-type_specific.io-github-autotest-libvirt.virtual_disks.multivms.coldplug.vms_sharable_test.block_type
```
=> virtual_disk: Wait for partition to be ready before mkfs

libvirt/tests/src/virsh_cmd/interface/virsh_iface_bridge.py
Description:
- Here the test needs either of the packages to be installed.
- Since there is 'not' in the 'if' condition, it should have 'and' instead of 'or'.
- With the current code, it keeps looking for first one and prints the error message.
- It will never look at the second as first 'True' condition is sufficient for OR.
=> Replaced 'or' with 'and' to Fix a wrong if condition

libvirt/tests/cfg/virtual_network/passt/passt_connectivity_between_2vms.cfg, libvirt/tests/src/virtual_network/passt/passt_connectivity_between_2vms.py
- VIRT-297075: [user][passt] Passt backend interface - check the connectivity between 2 VMs
Test result:
(1/2) type_specific.io-github-autotest-libvirt.virtual_network.passt.connectivity_between_2vms.ip_portfw.root_user: PASS (245.37 s)
(2/2) type_specific.io-github-autotest-libvirt.virtual_network.passt.connectivity_between_2vms.ip_portfw.non_root_user: PASS (90.77 s)
=> Add passt case of connectivity check of 2 vms

libvirt/tests/cfg/save_and_restore/restore_from_nfs_file.cfg, libvirt/tests/src/save_and_restore/restore_from_nfs_file.py
- VIRT-297088 - Restore vm from a saved file - nfs storage
Test result
(1/1) type_specific.io-github-autotest-libvirt.save_and_restore.restore_from_nfs_file: PASS (56.31 s)
=> Add case of restore from file from nfs storage

libvirt/tests/cfg/memory/memory_allocation/memory_invalid_value.cfg, libvirt/tests/src/memory/memory_allocation/lifecycle_with_memory_allocation.py, libvirt/tests/src/memory/memory_allocation/memory_invalid_value.py
The first case
Before fix:
`  L0045 ERROR| avocado.core.exceptions.TestFail: Expecting '-m 2048' does exist in qemu command line, but  notfound`
After fix:
```
[root@dell-per750-30 tp-libvirt]# rpm -q libvirt
libvirt-9.5.0-0rc1.1.el9.x86_64
[root@dell-per750-30 tp-libvirt]# avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 memory.allocation.lifecycle.positive_test.without_maxmemory --vt-connect-uri qemu:///system
(1/1) type_specific.io-github-autotest-libvirt.memory.allocation.lifecycle.positive_test.without_maxmemory: PASS (105.28 s)
```
```
[root@cloud-qe-05 tp-libvirt]# rpm -q libvirt
libvirt-8.0.0-21.module+el8.9.0+19166+e262ca96.x86_64
[root@cloud-qe-05 tp-libvirt]# avocado run --vt-type libvirt --test-runner=runner …
```
=> fix memory case libvirt version issue

libvirt/tests/cfg/chardev/log/chardev_with_log_file.cfg
log_file needs to be log
```
avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 chardev.log
(1/2) type_specific.io-github-autotest-libvirt.chardev.log.console.pty: PASS (49.88 s)
(2/2) type_specific.io-github-autotest-libvirt.chardev.log.console.unix: PASS (49.88 s)
```
=> fix get correct log attr

libvirt/tests/cfg/guest_os_booting/ovmf_firmware/ovmf_loader.cfg, libvirt/tests/cfg/guest_os_booting/ovmf_firmware/ovmf_nvram.cfg, libvirt/tests/src/guest_os_booting/ovmf_firmware/ovmf_loader.py, libvirt/tests/src/guest_os_booting/ovmf_firmware/ovmf_nvram.py
To distinguish ovmf and seabios in test, we add a new variable firmware_type. Here update this variable to previous merged loader/nvram script.
=> guest_os_booting: fix loader/nvram script to use firmware_type

libvirt/tests/cfg/save_and_restore/save_image_dumpxml.cfg, libvirt/tests/src/save_and_restore/save_image_dumpxml.py
libvirt support --xpath for `virsh save-image-dumpxml` since 8.5.0
Before:
```
(1/2) type_specific.io-github-autotest-libvirt.save_and_restore.save_image_dumpxml.normal.xpath_opt.default: FAIL: error: command 'save-image-dumpxml' doesn't support option --xpath\n (26.26 s)
(2/2) type_specific.io-github-autotest-libvirt.save_and_restore.save_image_dumpxml.normal.xpath_opt.wrap: FAIL: error: command 'save-image-dumpxml' doesn't support option --xpath\n (26.94 s)
```
=> managed_save: Add version check for xpath_opt

libvirt/tests/cfg/chardev/virsh_console_operation/prevent_multiple_console.cfg, libvirt/tests/src/chardev/virsh_console_operation/prevent_multiple_console.py
VIRT-296963: prevent multiple console connections
```
avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 chardev.prevent_multiple_console
(1/3) type_specific.io-github-autotest-libvirt.chardev.prevent_multiple_console.console.virtio_target: PASS (55.46 s)
(2/3) type_specific.io-github-autotest-libvirt.chardev.prevent_multiple_console.serial.pci_target: PASS (52.18 s)
(3/3) type_specific.io-github-autotest-libvirt.chardev.prevent_multiple_console.serial.isa_target: PASS (51.63 s)
```
Depend on https://github.com/avocado-framework/avocado-vt/pull/3706
=> chardev: add case for prevent muti console connection

v2v/tests/cfg/function_test_esx.cfg
Fix failed TC.
(1/1) type_specific.io-github-autotest-libvirt.function_test_esx.negative_test.invalid_vddk_thumbprint.esx_70.rhev.rhv_upload.it_vddk.vpx_uri: PASS (79.71 s)
=> v2v:fix 9.3 functional testing for failed TC

libvirt/tests/cfg/libvirt_rng.cfg, libvirt/tests/src/libvirt_rng.py
4cc1a3b3c3c7acd921341e719ae4167078617d25 introduced a new parameter but the type was incompatible for the multiple_rng test variant.
=> libvirt_rng: fix incompatible param type

libvirt/tests/src/numa/numa_memory_migrate.py
"live" --> "--live"
Before:
```
(1/2) type_specific.io-github-autotest-libvirt.numa_memory_migrate.mem_auto: ERROR: Command '/usr/bin/virsh numatune avocado-vt-vm1 live --nodeset 0' failed.\nstdout: b'\n'\nstderr: b'error: Invalid mode: live\n'\nadditional_info: None (40.23 s)
(2/2) type_specific.io-github-autotest-libvirt.numa_memory_migrate.mem_nodeset: ERROR: Command '/usr/bin/virsh numatune avocado-vt-vm1 live --nodeset 1' failed.\nstdout: b'\n'\nstderr: b'error: Invalid mode: live\n'\nadditional_info: None (44.94 s)
```
After:
```
(1/2) type_specific.io-github-autotest-libvirt.numa_memory_migrate.mem_auto: PASS (41.97 s)
(2/2) type_specific.io-github-autotest-libvirt.numa_memory_migrate.mem_nodeset: PASS (39.74 s)
```
=> numa: Fix options for `virsh numatune`

libvirt/tests/cfg/svirt/selinux/selinux_seclabel_per_device.cfg
Default serial device on s390x should be sclpconsole.
=> selinux_seclabel_per_device: set correct device for s390x

libvirt/tests/src/svirt/label_restore_rules/label_restore_rules_disk_access_modes.py
Shareable disks with qemu must have 'raw' image format. 'qcow2' can often work but will fail if host filesystem has blocksize 4096.
=> label_restore_rules: fix image format

libvirt/tests/cfg/svirt/dac/dac_seclabel_per_device.cfg
On s390x, the default serial device is sclpconsole.
=> dac_seclabel_per_device: fix serial config

libvirt/tests/src/svirt/dac/dac_seclabel_overall_domain.py, provider/security/security_base.py
It could be called by other tests.
Test results:
(1/1) type_specific.io-github-autotest-libvirt.svirt.dac.seclabel.overall_domain.enable_dynamic_ownership.static.without_qemu_conf_user_group.107_plus.relabel_yes.without_img_chown: PASS (9.91 s)
=> Move actions related to tpm lib's permissions to provider

libvirt/tests/cfg/virtual_disks/virtual_disks_multivms.cfg
Shareable disks with qemu must have 'raw' format. 'qcow2' can often work but fill fail if host filesystem has blocksize 4096.
=> virtual_disks_multivms: fix image format

libvirt/tests/cfg/svirt/umask_value/svirt_umask_files_accessed_by_qemu.cfg
On s390x, huge pages are not enabled by default in RHEL. Add config parameter to reload module with huge pages support.
=> svirt/umask_value: enable huge pages on s390x

libvirt/tests/cfg/virtual_device/watchdog.cfg
Only supported on q35,
"error: unsupported configuration: itco model of watchdog is only part of q35 machine"
=> watchdog: run tco tests only with q35 machine

libvirt/tests/cfg/backingchain/blockcommit/blockcommit_conventional_chain.cfg, provider/virtual_disk/disk_base.py
This PR automate the new test scenario of raw guest image in: VIRT-292832 - Do blockcommit for conventional chain
=> backingchain: add new test scenario for raw format

provider/virtual_network/passt.py
Test result:
PASS 1-type_specific.io-github-autotest-libvirt.virtual_network.passt.interface_function.minimal.root_user
=> passt:Replace hardcoded 'eno1' with vm_iface

libvirt/tests/src/guest_os_booting/ovmf_firmware/ovmf_smm.py
When disabling the smm, the non-secure boot status should be configured. In fact, the guest still uses the secure boot. So it get error "Unable to find any firmware to satisfy 'efi'". Adjust the xml configuration here.
=> Fix the ovmf smm failure of inconsistency between os xml and smm status

libvirt/tests/cfg/virsh_cmd/host/virsh_nodeinfo.cfg, libvirt/tests/src/virsh_cmd/host/virsh_nodeinfo.py
Skip a case on AMD machine because the cpu topology is different between Intel and AMD.
=> virsh_nodeinfo: skip on AMD

libvirt/tests/cfg/save_and_restore/restore_from_unqualified_file.cfg, libvirt/tests/src/save_and_restore/restore_from_unqualified_file.py
- VIRT-297111 - Restore vm from an unqualified file
Test result:
(1/4) type_specific.io-github-autotest-libvirt.save_and_restore.restore_from_unqualified_file.non_exist: PASS (6.21 s)
(2/4) type_specific.io-github-autotest-libvirt.save_and_restore.restore_from_unqualified_file.invalid: PASS (6.22 s)
(3/4) type_specific.io-github-autotest-libvirt.save_and_restore.restore_from_unqualified_file.to_running_vm: PASS (7.73 s)
(4/4) type_specific.io-github-autotest-libvirt.save_and_restore.restore_from_unqualified_file.image_running_by_another_vm: PASS (10.01 s)
=> Add case of restoring vm from unqualified file

libvirt/tests/cfg/chardev/virsh_console_operation/release_console.cfg, libvirt/tests/src/chardev/virsh_console_operation/release_console.py
VIRT-296962: release virsh console when guest shut down
```
avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35  chardev.release_console
(1/3) type_specific.io-github-autotest-libvirt.chardev.release_console.console.virtio_target: PASS (52.04 s)
(2/3) type_specific.io-github-autotest-libvirt.chardev.release_console.serial.pci_target: PASS (46.95 s)
(3/3) type_specific.io-github-autotest-libvirt.chardev.release_console.serial.isa_target: PASS (49.68 s)
```
=> chardev:add case for chardev release console

libvirt/tests/cfg/virtual_network/connectivity/connectivity_check_direct_interface.cfg
Depends on:
- https://github.com/avocado-framework/avocado-vt/pull/3735
Test result:
(1/3) type_specific.io-github-autotest-libvirt.virtual_network.connectivity_check.direct_interface.br: PASS (95.44 s)
(2/3) type_specific.io-github-autotest-libvirt.virtual_network.connectivity_check.direct_interface.private: PASS (99.22 s)
(3/3) type_specific.io-github-autotest-libvirt.virtual_network.connectivity_check.direct_interface.vepa: PASS (99.79 s)
JOB HTML   : /var/lib/avocado/job-results/job-2023-08-06T23.09-9cb66e4/results.html
JOB TIME   : 295.92 s
=> Fixup:add config for direct type interface to fix ping failure

libvirt/tests/cfg/numa/guest_numa_node_tuning/numa_mem_binding_with_offline_cpu.cfg, libvirt/tests/src/numa/guest_numa_node_tuning/numa_mem_binding_with_offline_cpu.py
VIRT-297677:Numa memory binding with offline cpu
RHEL 9
```
[root@dell-per730-59 tp-libvirt]# rpm -q libvirt
libvirt-9.5.0-0rc1.1.el9.x86_64
[root@dell-per730-59 tp-libvirt]# avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35  guest_numa_node_tuning.cpu_offline
(01/16) type_specific.io-github-autotest-libvirt.guest_numa_node_tuning.cpu_offline.host.related.strict: PASS (7.78 s)
(02/16) type_specific.io-github-autotest-libvirt.guest_numa_node_tuning.cpu_offline.host.related.interleave: PASS (10.40 s)
(03/16) type_specific.io-github-autotest-libvirt.guest_numa_node_tuning.cpu_offline.host.related.preferred: PASS (11.96 s)
(04/16) type_specific.io-github-autotest-libvirt.guest_numa_node_tuning.cpu_offline.host.related.restrictive: …
```
=> numa: add case for numa mem binding with offline cpu

libvirt/tests/cfg/svirt/default_dac_check.cfg, libvirt/tests/src/svirt/default_dac_check.py
On s390x, huge pages are size 1M. Also, the support is not enabled by default on RHEL.
Set parameter `page_size` maintaining legacy behavior by setting default value `2048`.
Enable kvm module reload with huge page support on s390x.
=> default_dac_check: fix hugepage setup on s390x

libvirt/tests/src/scsi/scsi_device.py
Test on 8.0.0, the output of qemu_cmd_line is different, so update the regrex match to fit the test on 8.0.0
Before:
```
FAIL 1-type_specific.io-github-autotest-libvirt.scsi_device_manipulate.coldplug.scsi_hostdev.positive.boot_order -> TestFail: Expecting '"ua-alias_hostdev1","bootindex":2' does exist in qemu command line, but  notfound
```
After:
```
PASS 1-type_specific.io-github-autotest-libvirt.scsi_device_manipulate.coldplug.scsi_hostdev.positive.boot_order
```
=> virtaul_disk: Update regrex for alias_plus_boot_order

libvirt/tests/src/virtual_disks/virtual_disks_multidisks.py
Fix virtual_disks.multidisks.coldplug.multi_disks_test.disk_virtio_scsi_multi_queue fail
In terms of s390x arch, additional step is needed for normal guest boot
See more details from https://bugzilla.redhat.com/show_bug.cgi?id=2214147
=> Fix virtual_disks multidisk multi_queue failure on 390x

libvirt/tests/src/numa/guest_numa_node_tuning/memory_binding_setting.py
The first exception message is below:
`avocado.core.exceptions.TestCancel: Expect 2 numa nodes at least, but found 1.`
But the final exception message is below.
`AttributeError: 'NoneType' object has no attribute 'set_node_num_huge_pages'`
The first exception is root cause , but overwritten by the final one. This is because insufficient handling in teardown function.
This patch is a simple fix for this issue.
=> memory_binding_setting: fix incorrect exception message

libvirt/tests/cfg/numa/guest_numa_node_tuning/auto_memory_nodeset_placement.cfg, libvirt/tests/src/numa/guest_numa_node_tuning/auto_memory_nodeset_placement.py, spell.ignore
Depend on
- https://github.com/avocado-framework/avocado-vt/pull/3716
- https://github.com/avocado-framework/avocado-vt/pull/3722
- https://github.com/autotest/tp-libvirt/pull/5034
Case ID: xxx-296727
=> auto_memory_nodeset_placement: add case auto mem nodeset and placement

libvirt/tests/cfg/migration/migrate_options_shared.cfg
When the low_speed is too small, the migration process may get stuck at 99%.
Before:
```
ERROR 1-type_specific.io-github-autotest-libvirt.virsh.migrate_options_shared.positive_test.p2p_migration.disable_keepalive.on_both.without_postcopy -> TestError: No migration result is returned.
ERROR 1-type_specific.io-github-autotest-libvirt.virsh.migrate_options_shared.positive_test.p2p_migration.disable_keepalive.on_target.without_postcopy -> TestError: No migration result is returned.
```
After:
```
PASS 1-type_specific.io-github-autotest-libvirt.virsh.migrate_options_shared.positive_test.p2p_migration.disable_keepalive.on_both.without_postcopy
PASS 1-type_specific.io-github-autotest-libvirt.virsh.migrate_options_shared.positive_test.p2p_migration.disable_keepalive.on_target.without_postcopy
```
=> migrate_options_shared: Increase low_speed for aarch64

provider/migration/base_steps.py
nfs_mount_dir is None in copy storage migration. So need to add
a default image path for copy storage migration.
=> migration: Fix image path error

libvirt/tests/cfg/virsh_cmd/domain/virsh_detach_device_alias.cfg, libvirt/tests/src/virsh_cmd/domain/virsh_detach_device_alias.py
To avoid affecting other controllers, just modify the controller device defined in controller_dict.
Test Results:
```
(1/3) type_specific.io-github-autotest-libvirt.virsh.detach_device_alias.live.hostdev.pci: PASS (57.93 s)
(2/3) type_specific.io-github-autotest-libvirt.virsh.detach_device_alias.config.hostdev.pci: PASS (49.33 s)
(3/3) type_specific.io-github-autotest-libvirt.virsh.detach_device_alias.current.hostdev.pci: PASS (58.68 s)
```
=> chardev_pcie: Update controller index for modify_vm_device

libvirt/tests/cfg/numa/guest_numa_node_tuning/invalid_nodeset_of_numa_memory_binding.cfg, libvirt/tests/src/numa/guest_numa_node_tuning/invalid_nodeset_of_numa_memory_binding.py
```
avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 guest_numa_node_tuning.invalid_nodeset --vt-connect-uri qemu:///system
(01/16) type_specific.io-github-autotest-libvirt.guest_numa_node_tuning.invalid_nodeset.host.partially_inexistent.strict: FAIL: Expect 'unsupported configuration: NUMA node 2 is unavailable' in 'VM 'avocado-vt-vm1' failed to start: setlocale: No such file or directory\nerror: Failed to start domain 'avocado-vt-vm1'\nerror: Invalid value '1-2' for 'cpuset.mems': Invalid argument(exit... (5.88 s)
(02/16) type_specific.io-github-autotest-libvirt.guest_numa_node_tuning.invalid_nodeset.host.partially_inexistent.interleave: PASS (5.58 s)
(03/16) type_specific.io-github-autotest-libvirt.guest_numa_node_tuning.in …
```
=> fix numa node check and version issue

libvirt/tests/cfg/migration/migration_resource_limit/migration_postcopy_bandwidth.cfg, libvirt/tests/cfg/migration/migration_resource_limit/migration_precopy_and_postcopy_bandwidth.cfg, libvirt/tests/src/migration/migration_performance_tuning/migration_precopy_bandwidth.py, libvirt/tests/src/migration/migration_resource_limit/migration_bandwidth.py, provider/migration/migration_base.py
1. VIRT-293956 - [VM migration] network bandwidth - postcopy
2. VIRT-293957 - [VM migration] network bandwidth - precopy+postcopy
3. Fix a parameter error. We need to use 'compare_to_value'
parameter in libvirt_domjobinfo.check_domjobinfo().
=> migration: Add case about network bandwidth

libvirt/tests/cfg/guest_os_booting/ovmf_firmware/ovmf_firmware_feature.cfg, libvirt/tests/cfg/guest_os_booting/ovmf_firmware/ovmf_smm.cfg, libvirt/tests/cfg/guest_os_booting/seabios_firmware/seabios_loader.cfg, libvirt/tests/src/guest_os_booting/ovmf_firmware/ovmf_firmware_feature.py, libvirt/tests/src/guest_os_booting/ovmf_firmware/ovmf_loader.py, libvirt/tests/src/guest_os_booting/ovmf_firmware/ovmf_nvram.py, libvirt/tests/src/guest_os_booting/ovmf_firmware/ovmf_smm.py, libvirt/tests/src/guest_os_booting/seabios_firmware/seabios_loader.py
Seabios guest and uefi guest use different guest xml and guest images. To select guest automatically, we use a new function get_vm() from provider to supoort it.
=> guest_os_booting: change to select vm based on different guest

libvirt/tests/cfg/migration_with_copy_storage/network_data_transport/tls_destination.cfg, libvirt/tests/cfg/migration_with_copy_storage/network_data_transport/tls_wrong_cert_configurations.cfg
If there is no '--migrateuri' parameter, we will not get the expected error message. So update it.
=> migration: Update migration parameter

v2v/tests/cfg/function_test_esx.cfg
Refer bz#2181235
And refer https://github.com/avocado-framework/avocado-vt/pull/3725/
=> v2v: add TC "Clear error msg when no vpx username"

libvirt/tests/cfg/save_and_restore/save_to_nfs.cfg, libvirt/tests/src/save_and_restore/restore_from_nfs_file.py, libvirt/tests/src/save_and_restore/save_to_nfs.py, provider/save/save_base.py
- VIRT-297050 - Save to root_squash NFS when dynamic_ownership=0
Test result:
(1/1) type_specific.io-github-autotest-libvirt.save_and_restore.save_to_nfs.root_squash.dynamic_ownership_off: PASS (50.62 s)
JOB HTML   : /var/lib/avocado/job-results/job-2023-08-07T21.51-db1905f/results.html
JOB TIME   : 51.90 s
=> Add case of save to NFS

libvirt/tests/cfg/memory/memory_allocation/define_value_unit.cfg, libvirt/tests/src/memory/memory_allocation/define_value_unit.py, provider/memory/memory_base.py
VIRT-297060:Memory value and unit definition
```
/usr/bin/python /usr/local/bin/avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 memory.allocation.define_value_unit                
JOB LOG    : /var/lib/avocado/job-results/job-2023-05-31T00.11-ef25099/job.log
(01/16) type_specific.io-github-autotest-libvirt.memory.allocation.define_value_unit.without_numa.positive_test.bytes: PASS (43.11 s)
(02/16) type_specific.io-github-autotest-libvirt.memory.allocation.define_value_unit.without_numa.positive_test.KB: PASS (51.79 s)
(03/16) type_specific.io-github-autotest-libvirt.memory.allocation.define_value_unit.without_numa.positive_test.KiB: PASS (51.65 s)
(04/16) type_specific.io-github-autotest-libvirt.memory.allocation.define_value …
```
=> memory: add case for mem value unit definition

libvirt/tests/cfg/memory/memory_backing/lifecycle_for_hugepage.cfg, libvirt/tests/src/memory/memory_backing/lifecycle_for_hugepage.py
VIRT-297103: Life cycle with huge page
```
/usr/local/bin/avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 memory.backing.lifecycle.memory_hugepage
(1/5) type_specific.io-github-autotest-libvirt.memory.backing.lifecycle.memory_hugepage.4k: PASS (123.66 s)
(2/5) type_specific.io-github-autotest-libvirt.memory.backing.lifecycle.memory_hugepage.2M: PASS (122.99 s)
(3/5) type_specific.io-github-autotest-libvirt.memory.backing.lifecycle.memory_hugepage.1G: PASS (124.96 s)
(4/5) type_specific.io-github-autotest-libvirt.memory.backing.lifecycle.memory_hugepage.0: PASS (21.23 s)
(5/5) type_specific.io-github-autotest-libvirt.memory.backing.lifecycle.memory_hugepage.scarce_mem:PASS (17.52 s)
```
=> memory: add case for lifecycle with hugepages

libvirt/tests/cfg/numa/numa_node_tuning/auto_mem_placement_with_incompatible_host_nodeset.cfg, libvirt/tests/src/numa/numa_node_tuning/auto_mem_placement_with_incompatible_host_nodeset.py
VIRT-297679: Auto memory placement with incompatible host nodeset binding
```
[root@dell-per750-31 tp-libvirt]# rpm -q libvirt
libvirt-8.0.0-22.module+el8.9.0+19544+b3045133.x86_64
[root@dell-per730-59 tp-libvirt]# rpm -q libvirt
libvirt-9.5.0-0rc1.1.el9.x86_64
avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 guest_numa_node_tuning.incompatible_host_nodeset
(1/4) type_specific.io-github-autotest-libvirt.guest_numa_node_tuning.invalid_nodeset.strict: PASS (7.19 s)
(2/4) type_specific.io-github-autotest-libvirt.guest_numa_node_tuning.invalid_nodeset.interleave: PASS (7.20 s)
(3/4) type_specific.io-github-autotest-libvirt.guest_numa_node_tuning.invalid_nodeset.preferred: PASS (7.02 s)
(4/4) …
```
=> numa: add case for auto mem placement with incompatible host nodeset

libvirt/tests/cfg/guest_os_booting/boot_order/boot_from_disk_device.cfg, libvirt/tests/src/guest_os_booting/boot_order/boot_from_disk_device.py
This PR adds:
VIRT-296938 - Boot vm from disk device
```
(1/8) type_specific.io-github-autotest-libvirt.guest_os_booting.boot_order.disk_device.seabios.os_dev.single_disk: PASS (33.51 s)
(2/8) type_specific.io-github-autotest-libvirt.guest_os_booting.boot_order.disk_device.seabios.os_dev.multi_disks: PASS (266.18 s)
(3/8) type_specific.io-github-autotest-libvirt.guest_os_booting.boot_order.disk_device.seabios.disk_boot_order.single_disk: PASS (31.62 s)
(4/8) type_specific.io-github-autotest-libvirt.guest_os_booting.boot_order.disk_device.seabios.disk_boot_order.multi_disks: PASS (266.57 s)
(5/8) type_specific.io-github-autotest-libvirt.guest_os_booting.boot_order.disk_device.ovmf.os_dev.single_disk: PASS (53.24 s)
(6/8) …
```
=> guest_os_booting: Add a case of boot order

libvirt/tests/cfg/migration/migration_performance_tuning/migration_memory_compression.cfg, libvirt/tests/src/migration/migration_performance_tuning/migration_performance_tuning.py
Add new scenario:
1. Start migration, then set cache size by "virsh migrate-compcache <domain> <n>".
2. Set cache size by "virsh migrate-compcache <domain> <n>", then do migration with option "--compressed --comp-methods xbzrle".
=> migration: Update memory compression case

libvirt/tests/cfg/guest_os_booting/boot_order/boot_order_setting_negative.cfg, libvirt/tests/src/guest_os_booting/boot_order/boot_order_setting_negative.py
This PR adds:
VIRT-297200: [Negative] Define vm with invalid boot order
```
(1/5) type_specific.io-github-autotest-libvirt.guest_os_booting.boot_order.setting.negative.duplicate: PASS (10.74 s)
(2/5) type_specific.io-github-autotest-libvirt.guest_os_booting.boot_order.setting.negative.with_os_boots: PASS (11.19 s)
(3/5) type_specific.io-github-autotest-libvirt.guest_os_booting.boot_order.setting.negative.minus: PASS (11.10 s)
(4/5) type_specific.io-github-autotest-libvirt.guest_os_booting.boot_order.setting.negative.zero: PASS (11.16 s)
(5/5) type_specific.io-github-autotest-libvirt.guest_os_booting.boot_order.setting.negative.string: PASS (11.73 s)
RESULTS    : PASS 5 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
```
=> guest_os_booting: Add negative test about boot order settings

libvirt/tests/cfg/virtual_network/iface_bridge.cfg, libvirt/tests/cfg/virtual_network/iface_options.cfg
After qemu bug 2040509, qemu changed the bahavior when checking the tx_queue_size value. Only for vdpa and vhostuser, the tx_queue_size more than 256 are supported. For other types, it will report error. Before this bug, qemu will ignore the unsupported setting and start the vm anyway and always keep tx_queue_size as 256 in the VM. This may be supported in the future, refer to
https://issues.redhat.com/browse/RHEL-1139. Update this parameter setting as it is not critical for this case.
=> Update the tx_queue_size parameter

libvirt/tests/cfg/guest_os_booting/useserial/useserial.cfg, libvirt/tests/src/guest_os_booting/useserial/useserial.py
This PR automates:
VIRT-297119 - Boot vm with useserial
=> guest_os_booting: add new case for useserial attribute

libvirt/tests/cfg/save_and_restore/save_image_define.cfg, libvirt/tests/src/save_and_restore/save_image_define.py
- VIRT-297827 - Define saved file from xml by save-image-define cmd
Test result:
```
(1/7) type_specific.io-github-autotest-libvirt.virsh.save_image_define.running: PASS (28.76 s)
(2/7) type_specific.io-github-autotest-libvirt.virsh.save_image_define.paused: PASS (29.03 s)
(3/7) type_specific.io-github-autotest-libvirt.save_and_restore.save_image_define.readonly.no_opt: PASS (29.30 s)
(4/7) type_specific.io-github-autotest-libvirt.save_and_restore.save_image_define.normal.no_opt: PASS (41.38 s)
(5/7) type_specific.io-github-autotest-libvirt.save_and_restore.save_image_define.normal.running_opt: PASS (42.25 s)
(6/7) type_specific.io-github-autotest-libvirt.save_and_restore.save_image_define.normal.paused_opt: PASS (42.17 s)
(7/7) type_specific.io-github-autotest-libvirt.save_and_restore.sav …
```
=> Add case of save-image-define

libvirt/tests/cfg/save_and_restore/save_to_block.cfg, libvirt/tests/src/save_and_restore/save_to_block.py
- VIRT-297051 - Save to a block device with qemu namespace settings
Test result:
```
(1/2) type_specific.io-github-autotest-libvirt.save_and_restore.save_to_block.qemu_namespace.enabled: PASS (60.07 s)
(2/2) type_specific.io-github-autotest-libvirt.save_and_restore.save_to_block.qemu_namespace.disabled: PASS (62.94 s)
JOB HTML   : /var/lib/avocado/job-results/job-2023-08-08T05.43-cdca2df/results.html
JOB TIME   : 124.35 s
```
=> Add case of save to block device

libvirt/tests/cfg/memory/memory_backing/hugepage_nodeset.cfg, libvirt/tests/src/memory/memory_backing/hugepage_nodeset.py, spell.ignore
add case for hugepage nodeset
VIRT-297167: Huge page nodeset
```
/usr/local/bin/avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 memory.backing.nodeset
(1/4) type_specific.io-github-autotest-libvirt.memory.backing.nodeset.with_numa.nodeset_0: PASS (54.20 s)
(2/4) type_specific.io-github-autotest-libvirt.memory.backing.nodeset.with_numa.nodeset_not_exist: PASS (24.68 s)
(3/4) type_specific.io-github-autotest-libvirt.memory.backing.nodeset.without_numa.nodeset_0: PASS (56.44 s)
(4/4) type_specific.io-github-autotest-libvirt.memory.backing.nodeset.without_numa.nodeset_not_exist: PASS (17.07 s)
```
=> memory: add case for hugepage nodeset

libvirt/tests/src/migration_with_copy_storage/migration_with_backingchain.py
Need to create image path on the remote host first. Otherwise, image creation will fail.
=> migration: Fix image path issue on remote host

libvirt/tests/src/svirt/dac_nfs_disk.py
Fix dac_nfs_disk failure due to No such file or directory
/var/lib/swtpm-localca may not exist previously, so it need judge before set parameters for it
=> Fix dac_nfs_disk failure due to No such file or directory

libvirt/tests/cfg/backingchain/negative_scenario/interrupt_blockcopy.cfg, libvirt/tests/src/backingchain/negative_scenario/interrupt_blockcopy.py
VIRT-298913: Interrupt block operations and check guest status
```
avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 backingchain.negative.interrupt_blockcopy.with_transient_job
(1/1) type_specific.io-github-autotest-libvirt.backingchain.negative.interrupt_blockcopy.with_transient_job: PASS (9.07 s)
```
=> add case for interrupt blockcopy

libvirt/tests/cfg/guest_os_booting/lifecycle/lifecycle_boot.cfg, libvirt/tests/src/guest_os_booting/lifecycle/lifecycle_boot.py
This PR adds:
VIRT-297865: Do vm lifecycle with boot dev/order
ovmf:
```
(1/2) type_specific.io-github-autotest-libvirt.guest_os_booting.lifecycle.boot.os_dev: PASS (53.41 s)
(2/2) type_specific.io-github-autotest-libvirt.guest_os_booting.lifecycle.boot.boot_order: PASS (57.38 s)
```
seabios:
```
(1/2) type_specific.io-github-autotest-libvirt.guest_os_booting.lifecycle.boot.os_dev: PASS (28.99 s)
(2/2) type_specific.io-github-autotest-libvirt.guest_os_booting.lifecycle.boot.boot_order: PASS (39.74 s)
```
=> guest_os_booting: Add a case about vm lifecycle

libvirt/tests/src/virsh_cmd/interface/virsh_iface_bridge.py
Description: Whenever the test fails/cancels, the test is just coming out where it should have recovered the NetworkManager service.
Added changes required for the same.
=> Recover NM service in case of Failure/Cancel

libvirt/tests/cfg/virsh_cmd/domain/virsh_emulatorpin.cfg
On s390x, there's a different but valid error message. Expect the message alternatively on failure.
=> virsh.emulatorpin: add alternative error msg for negative test

libvirt/tests/cfg/guest_os_booting/lifecycle/lifecycle_reset_nvram.cfg, libvirt/tests/src/guest_os_booting/lifecycle/lifecycle_reset_nvram.py
This PR adds:
VIRT-297866: Reset NVRAM state of ovmf vm
```
(1/4) type_specific.io-github-autotest-libvirt.guest_os_booting.lifecycle.reset_nvram.create: PASS (9.99 s)
(2/4) type_specific.io-github-autotest-libvirt.guest_os_booting.lifecycle.reset_nvram.start.default: PASS (10.07 s)
(3/4) type_specific.io-github-autotest-libvirt.guest_os_booting.lifecycle.reset_nvram.start.managedsave: PASS (10.15 s)
(4/4) type_specific.io-github-autotest-libvirt.guest_os_booting.lifecycle.reset_nvram.restore: PASS (88.42 s)
```
=> guest_os_booting: Add a case about resetting nvram

libvirt/tests/src/virsh_cmd/monitor/virsh_domblkstat.py, libvirt/tests/src/virsh_cmd/monitor/virsh_domifstat.py
Description: libvirtd is restarted after issuing virsh commands from libvirt version 5.6.0 on.
Hence need to fix test expectations when libvirtd is off
=> Fix for domifstat and domblkstat when libvirtd is off

libvirt/tests/cfg/virtual_disks/startup_policy.cfg, libvirt/tests/src/virtual_disks/startup_policy.py, libvirt/tests/src/virtual_disks/virtual_disks_filedescriptor.py, libvirt/tests/src/virtual_disks/virtual_disks_nbd.py
Depends on https://github.com/avocado-framework/avocado-vt/pull/3729
Partition names under /cat/partitions might change
between boots, causing tests to fail in those cases.
Use instead information under /dev/disk/by-path.
Note, that pci disks might be listed twice, e.g.
'virtio-pci-0000:04:00.0-part1' and 'pci-0000:04:00.0-part1'.
Furthermore,
virtual_disk_ndb: remove unused parameter
startupPolicy: disable floppy, sata - not available on s390x
=> virtual_disks: stabilize tests that check a new disk was added

libvirt/tests/cfg/guest_os_booting/ovmf_firmware/ovmf_loader.cfg
Readonly_os issue has been fixed in bug 2196178. So add the libvirt support version.
=> ovmf_loader: add the libvirt support version

libvirt/tests/src/migration/migration_with_vtpm/migration_with_external_tpm.py
Add libvirt_version judge for external vtpm, read params from the cfg file.
=> Add libvirt_version judge for external vtpm

libvirt/tests/cfg/numa/guest_numa_node_tuning/invalid_nodeset_of_numa_memory_binding.cfg, libvirt/tests/src/numa/guest_numa_node_tuning/invalid_nodeset_of_numa_memory_binding.py
Due to bug won't be fixed and feature owner updated the polarion  case
```
avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 guest_numa_node_tuning.invalid_nodeset.
(01/16) type_specific.io-github-autotest-libvirt.guest_numa_node_tuning.invalid_nodeset.host.partially_inexistent.strict: PASS (6.23 s)
(02/16) type_specific.io-github-autotest-libvirt.guest_numa_node_tuning.invalid_nodeset.host.partially_inexistent.interleave: PASS (6.22 s)
(03/16) type_specific.io-github-autotest-libvirt.guest_numa_node_tuning.invalid_nodeset.host.partially_inexistent.preferred: PASS (6.23 s)
(04/16) type_specific.io-github-autotest-libvirt.guest_numa_node_tuning.invalid_nodeset.host.partially_inexistent.restrictive: PASS (6.26 s)
(05/16) …
```
=> fix numa case invalid message

libvirt/tests/cfg/backingchain/blockcopy/blockcopy_with_zero_length_disk.cfg, libvirt/tests/src/backingchain/blockcopy/blockcopy_with_zero_length_disk.py
VIRT-298420: Do blockcopy for transient guest and zero-length disk
```
avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 backingchain.blockcopy.zero_length_disk.with_transient_job
(1/1) type_specific.io-github-autotest-libvirt.backingchain.blockcopy.zero_length_disk.with_transient_job: PASS (7.71 s)
```
=> add case for blockcopy with zero length disk

libvirt/tests/cfg/memory/memory_backing/hugepage_nodeset.cfg
The default huge pagesize is 512M for aarch64.
Test Results:
```
(1/4) type_specific.io-github-autotest-libvirt.memory.backing.nodeset.with_numa.nodeset_0: PASS (35.53 s)
(2/4) type_specific.io-github-autotest-libvirt.memory.backing.nodeset.with_numa.nodeset_not_exist: PASS (9.59 s)
(3/4) type_specific.io-github-autotest-libvirt.memory.backing.nodeset.without_numa.nodeset_0: PASS (40.35 s)
(4/4) type_specific.io-github-autotest-libvirt.memory.backing.nodeset.without_numa.nodeset_not_exist: PASS (9.73 s)
```
=> memory: Enable test for aarch64

libvirt/tests/src/save_and_restore/save_to_block.py
Fix managed save and restore failure on s390x
on s390x, it may grep msg='avc',but not denied message, so this case will be marked as failure
By updating grep message to 'avc:.*denied' to avoid this happening
=> Fix managed save and restore failure on s390x

libvirt/tests/src/libvirt_rng.py
Sometimes,
libvirt_rng.backend_tcp.bind_mode.hotplug_unplug.positive.persistent
fails.
The test provides entropy to the tcp backend via netcat
nc -4 localhost 1024
However, this command will immediately exit if nothing listens on that port.
The test will hotplug an egd device which listens. However, if netcat is issued before the listener is active then netcat will exit and that egd device doesn't receive entropy during the boot. Therefore the boot will wait and the test can't log into the console.
Change execution order to make sure the entropy is provided, that is, first hotplug the listener, then send data with netcat.
I assume that on environments where the test passes, the bgjob is started shortly after device is attached, and that this is possible because it's started asynchronously …
=> libvirt_rng: remove flakiness for tcp bind mode

libvirt/tests/cfg/memory/memory_allocation/define_value_unit.cfg, libvirt/tests/cfg/memory/memory_allocation/memory_allocation_config_modification.cfg, libvirt/tests/cfg/memory/memory_backing/lifecycle_for_hugepage.cfg, libvirt/tests/cfg/virtio/virtio_page_per_vq.cfg, libvirt/tests/src/memory/memory_backing/lifecycle_for_hugepage.py
memory..define_value_unit: disable numa tests on s390x
There's no NUMA on s390x. Disable tests.
memory_backing/lifecycel_for_hugepage: fix tests on s390x
On s390x, supported huge page size for KVM is 1M.
Also, add kvm_module_parameters which allow to set 'hpage=1' to enable hugepage support in CI.
memory_allocation_config: disable numa test on s390x
No NUMA on s390x, disable test.
virtio.virtio_page_per_vq: disable on s390x
virtio-balloon-ccw doesn't support the page-per-vq property. Disable test.
=> memory: fix several tests on s390x

libvirt/tests/src/libvirt_rng.py
The multiple_rng tests set up an edg with udp. However, no source is available. For x86_64 there was a fix by providing a source with socat. Enable this for all architectures.
=> libvirt_rng.multiple_rng: run socat on all archs

libvirt/tests/cfg/virtio/virtio_page_per_vq.cfg
That because virtio pattern is not suitable when searching series of these cases to run.
=> virtio: update virtio pattern to virtio_attributes

libvirt/tests/cfg/numa/guest_numa_node_tuning/change_numa_tuning.cfg, libvirt/tests/src/numa/guest_numa_node_tuning/change_numa_tuning.py
The default kernel pagesize for aarch64 is 64K
Before:
```
FAIL 1-type_specific.io-github-autotest-libvirt.guest_numa_node_tuning.change_numa_tuning.mem_mode_restrictive -> TestFail: The numa_maps should include 'kernelpagesize_kB=4'， but not found
```
After:
```
PASS 1-type_specific.io-github-autotest-libvirt.guest_numa_node_tuning.change_numa_tuning.mem_mode_restrictive
```
=> numa: Enable test for aarch64

libvirt/tests/src/guest_agent/agent_lifecycle.py
Fix agent lifecycle issue
related event may not be received as expected due to timeout issue so extend timeout to 60 seconds
=> Fix agent lifecycle issue

libvirt/tests/src/virsh_cmd/domain/virsh_restore.py, libvirt/tests/src/virsh_cmd/domain/virsh_save.py
If save.file exists, remove it. If not, it can lead to test errors "Permission denied" or "right command failed" and similar issues.
=> virsh_save/restore: improve tear down

libvirt/tests/cfg/cpu/vcpu_misc.cfg, libvirt/tests/cfg/cpu/vm_features.cfg, libvirt/tests/src/cpu/vcpu_metrics.py
vm_features: disable for unsupported archs
Hyper-V is not supported on these architectures, as was already indicated for positive_tests.
Disable the negative_tests, too.
vcpu_misc: disable test for maxphysaddr on s390x
CPU maximum physical address bits specification is not supported for 's390x' architecture
vcpu_metrics: remove seclabel for unprivileged user
seclable dac model is not available for unprivileged users, remove it.
=> cpu: fix several tests on s390x

libvirt/tests/src/event/virsh_event.py
The test
io-error_event.no_timeout.loop
created a small file inside of `tmpdir` and then mounted it upon its parent directory `tmpdir`. While this seems to lead to the desired io error events later, it also seems to lead to conflicts during teardown and the test dies "without reporting status".
Instead, create a subdirectory to test. This makes also sense because tmpdir is used by avocado-vt for vm xmls and other data.
=> virsh_event: change mount-point to avoid conflict at teardown

libvirt/tests/cfg/virsh_cmd/domain/virsh_detach_serial_device_alias.cfg
Previously, an error occurred when attempting to hot-plug or unplug serial devices on the arm64 architecture. This is due to the lack of support for these operations on arm64.
To resolve this issue, this commit refactors the configuration file to exclude hot-plugging and unplugging of serial devices specifically for arm64. By doing so, we ensure better compatibility and prevent unknown errors.
=> Improve compatibility by filtering serial device operations

libvirt/tests/src/virsh_cmd/nodedev/crypto_nodedev_create_destroy.py
Depends on https://github.com/avocado-framework/avocado-vt/pull/3723
`virsh nodedev-dumpxml` didn't list `attr` elements on transient devices. Add checkpoint.
=> crypto_create_destroy: add checkpoint

libvirt/tests/src/libvirt_scsi_hostdev.py
The disk is too large to cause timeout for guest io checking: [stderr] DEBUG:aexpect.client:[192.168.122.64] Sending command: fdisk -l /dev/sdb && mkfs.ext4 -F /dev/sdb && mkdir -p sdb && mount /dev/sdb sdb && echo teststring > sdb/testfile && umount sdb
Error happens when check disk io in vm: Timeout expired while waiting for shell command to complete: 'fdisk -l /dev/sdb && mkfs.ext4 -F /dev/sdb && mkdir -p sdb && mount /dev/sdb sdb && echo teststring > sdb/testfile && umount sdb'
Reduce them from 1G to 100M.
=> libvirt_scsi_hostdev: Reduce the size of create disk

libvirt/tests/src/numa/guest_numa_topology/change_vcpu_pin.py
The failure is expected on starting vm, instead of defining vm.
=> change_vcpu_pin: fix checking error in wrong step

libvirt/tests/src/virsh_cmd/domain/virsh_restore.py
Fix local variable 'tmp_file' referenced before assignment
Before:
```
ERROR 1-type_specific.io-github-autotest-libvirt.virsh.restore.no_option -> UnboundLocalError: local variable 'tmp_file' referenced before assignment
```
After:
```
PASS 1-type_specific.io-github-autotest-libvirt.virsh.restore.no_option
```
=> virsh_restore: Fix variable not assignment

libvirt/tests/src/virsh_cmd/monitor/virsh_domstate.py
virsh.domstate.error_test.kill_vm.after_stopping_libvirtd 
might report 'unknown' or 'daemon' reason if the service stop and restart are executed too quickly. 
Add fix wait time to account for human user and service time to shut down and come up correctly. The expected reason will be 'crashed'.
=> virsh_domstate: Slow test down to remove brittleness

libvirt/tests/src/virtual_disks/startup_policy.py
Remove all files to avoid Permission errors on next test run.
=> startup_policy: fix teardown

libvirt/tests/cfg/bios/virsh_boot.cfg
When testing readonly_no, it's better to only include loader attributes in os. Readonly_no is not an expected operation. So we'd better not to add much config in xml. Otherwise it will have unexpected error.
=> virsh_boot.cfg: add a condition to remove nvram attribute

libvirt/tests/cfg/migration_with_copy_storage/performance_tuning/copy_storage_synchronous_writes.cfg, libvirt/tests/src/migration_with_copy_storage/performance_tuning/copy_storage_synchronous_writes.py, spell.ignore
VIRT-297902 - VM live migration with copy storage - synchronous writes of vm disks(--copy-storage-synchronous-writes)
=> migration: Add case to test copy storage synchronous writes

libvirt/tests/cfg/migration_with_copy_storage/network_data_transport/unix_proxy.cfg, libvirt/tests/src/migration_with_copy_storage/network_data_transport/unix_proxy.py
Before the change, vm has only one disk; after the change, vm has
three disks.
=> migration: Update unix proxy case

libvirt/tests/src/incremental_backup/incremental_backup_pull_mode.py
Sometimes connecting the tls in incremental backup failed with different qemu commands. So here considering two reasons:
- Do backup operation quickly. 
- The tls server used in tls was used by other jobs/people sometimes.
So here adding the sleep time to wait for the tls environment perfection to resolve the first reason.
=> incremental_backup: add timeout before doing the backup.

libvirt/tests/cfg/virtual_network/connectivity/connectivity_check_user_interface.cfg, libvirt/tests/src/virtual_network/connectivity/connectivity_check_user_interface.py
- VIRT-296211 - [user][slirp] Check connectivity for user type interface
Test result:
```
(01/14) type_specific.io-github-autotest-libvirt.virtual_network.connectivity_check.user_interface.positive_test.default.root_user: PASS (137.02 s)
(02/14) type_specific.io-github-autotest-libvirt.virtual_network.connectivity_check.user_interface.positive_test.default.non_root_user: PASS (59.25 s)
(03/14) type_specific.io-github-autotest-libvirt.virtual_network.connectivity_check.user_interface.positive_test.customized_ip.no_prefix.root_user: PASS (197.48 s)
(04/14) type_specific.io-github-autotest-libvirt.virtual_network.connectivity_check.user_interface.positive_test.customized_ip.no_prefix.non_root_user: PASS (59.80 s)
(05/14) type_specific.io-github-autotest-libvirt.virtual_network.connectivity_ch …
```
=> Add new network case of user type interface

libvirt/tests/src/virtual_disks/virtual_disks_filedescriptor.py
Fix virtual_disks filedescriptor failure
utils_disk.get_added_parts_by_path() will get duplicated address for one partition(pci and virto-pci)
instead it need use utils_disk.get_added_parts()
=> Fix virtual_disks filedescriptor failure

libvirt/tests/cfg/virtio/virtio_page_per_vq.cfg
The disk image should be jeos-27-aarch64.qcow2 on aarch64.
Test Result:
```
PASS 1-type_specific.io-github-autotest-libvirt.virtio_attributes.virtio_page_per_vq.disk.default_start
```
=> virtual_disk: Update disk image to enable test on aarch64

libvirt/tests/src/virsh_cmd/domain/virsh_blockcommit.py
The error test executes two blockcommit jobs and expects the second to fail because the first hasn't finished yet. Sometimes, the first job would finish too fast. Instead of touching a file, create one with random content, reusing existing test logic. Hopefully, this will cause blockcommits to take longer.
=> virsh_blockcommit: create file with random contents for error test

libvirt/tests/cfg/guest_os_booting/boot_order/boot_from_cdrom_device.cfg, libvirt/tests/src/guest_os_booting/boot_order/boot_from_cdrom_device.py
This PR adds:
VIRT-297201: Boot vm from cdrom device
```
(01/14) type_specific.io-github-autotest-libvirt.guest_os_booting.boot_order.cdrom_device.seabios.os_dev.without_cdrom: PASS (22.47 s)
(02/14) type_specific.io-github-autotest-libvirt.guest_os_booting.boot_order.cdrom_device.seabios.os_dev.with_cdrom_with_no_src: PASS (263.41 s)
(03/14) type_specific.io-github-autotest-libvirt.guest_os_booting.boot_order.cdrom_device.seabios.os_dev.with_cdrom: PASS (24.20 s)
(04/14) type_specific.io-github-autotest-libvirt.guest_os_booting.boot_order.cdrom_device.seabios.os_dev.multi_cdroms: PASS (274.95 s)
(05/14) type_specific.io-github-autotest-libvirt.guest_os_booting.boot_order.cdrom_device.seabios.cdrom_boot_order.with_cdrom_with_no_src: PASS (263.39 s)
(06/14) …
```
=> guest_os_booting: Add a case about boot order of cdrom device

v2v/tests/cfg/v2v_options.cfg
Original VM is inaccessible and esx6.0 is out of service. update to esx7.0 vm.
=> v2v: fix 8.9 func TC "v2v_options..log_check"

libvirt/tests/src/graphics/graphics_functional.py
On RHEL 8, after run graphics.functional.positive_tests.spice_only .listen_type_network.network_bridge case, a bridge named linux_bridge will be left. This will cause some cases to fail. So update case.
=> graphics: Cleanup env

libvirt/tests/src/libvirt_rng.py
After b03e83f1c, the test provides feeding data on all arches. So remove the aarch64 specific code which is redundant now.
Test Results:
```
(1/6) type_specific.io-github-autotest-libvirt.libvirt_rng.backend_udp.bind_connect_mode.hotplug_unplug.positive.no_options: PASS (101.67 s)
(2/6) type_specific.io-github-autotest-libvirt.libvirt_rng.backend_udp.bind_connect_mode.hotplug_unplug.positive.persistent: PASS (43.01 s)
(3/6) type_specific.io-github-autotest-libvirt.libvirt_rng.backend_udp.bind_connect_mode.device_assign: PASS (37.98 s)
(4/6) type_specific.io-github-autotest-libvirt.libvirt_rng.backend_udp.connect_mode.hotplug_unplug.positive.no_options: PASS (43.89 s)
(5/6) type_specific.io-github-autotest-libvirt.libvirt_rng.backend_udp.connect_mode.hotplug_unplug.positive.persistent: …
```
=> virtio_rng: Remove redundant code for aarch64

libvirt/tests/cfg/guest_os_booting/direct_kernel_boot/direct_kernel_boot.cfg, libvirt/tests/src/guest_os_booting/direct_kernel_boot/direct_kernel_boot.py
This PR mainly automates:
VIRT-297126 - Boot vm with direct kernel
=> guest os booting: add new modular case for direct kernel boot

libvirt/tests/cfg/virtual_network/connectivity/connectivity_check_tcp_tunnel_interface.cfg, libvirt/tests/src/virtual_network/connectivity/connectivity_check_tcp_tunnel_interface.py, provider/virtual_network/network_base.py
- VIRT-296214 - [tcp] check connectivity of tcp tunnel type interface
test result:
(1/2) type_specific.io-github-autotest-libvirt.virtual_network.connectivity_check.tcp_tunnel_interface.no_source_addr: PASS (77.00 s)
(2/2) type_specific.io-github-autotest-libvirt.virtual_network.connectivity_check.tcp_tunnel_interface.with_source_addr: PASS (76.35 s)
JOB HTML   : /var/lib/avocado/job-results/job-2023-08-25T05.09-78ae039/results.html
JOB TIME   : 154.81 s
=> Add network case of connectivity check of tcp tunnel iface

libvirt/tests/cfg/virtual_network/connectivity/connectivity_check_udp_tunnel_interface.cfg, libvirt/tests/src/virtual_network/connectivity/connectivity_check_udp_tunnel_interface.py
- VIRT-296213 - [udp] Check connectivity of udp tunnel type interface
depends on:
- https://github.com/avocado-framework/avocado-vt/pull/3747
- https://github.com/autotest/tp-libvirt/pull/5130
test result:
(1/1) type_specific.io-github-autotest-libvirt.virtual_network.connectivity_check.udp_tunnel_interface: PASS (80.72 s)
JOB HTML   : /var/lib/avocado/job-results/job-2023-08-25T05.50-98c927a/results.html
JOB TIME   : 82.13 s
=> Add network case of connectivity check of udp tunnel iface

libvirt/tests/cfg/virtual_network/elements_and_attributes/element_model.cfg, libvirt/tests/src/virtual_network/elements_and_attributes/element_model.py
- VIRT-296241 - [model] Start vm with different model type
test result:
```
(1/7) type_specific.io-github-autotest-libvirt.virtual_network.elements_and_attributes.model.default: PASS (50.65 s)
(2/7) type_specific.io-github-autotest-libvirt.virtual_network.elements_and_attributes.model.virtio: PASS (82.76 s)
(3/7) type_specific.io-github-autotest-libvirt.virtual_network.elements_and_attributes.model.e1000e: PASS (49.61 s)
(4/7) type_specific.io-github-autotest-libvirt.virtual_network.elements_and_attributes.model.rtl8139: PASS (83.27 s)
(5/7) type_specific.io-github-autotest-libvirt.virtual_network.elements_and_attributes.model.virtio-transitional: PASS (50.79 s)
(6/7) type_specific.io-github-autotest-libvirt.virtual_network.elements_and_attributes.model.virtio-non-transitional: PASS …
```
=> Add network case of start with different model type

libvirt/tests/cfg/save_and_restore/save_with_formats.cfg, libvirt/tests/src/save_and_restore/save_with_formats.py, provider/save/save_base.py
- VIRT-296947: skipping time cost and file size comparison, and need to split case to several separate cases for each format.
- Don't fail test if uptime check failed
Test result:
```
(1/6) type_specific.io-github-autotest-libvirt.save_and_restore.save_with_formats.positive_test.raw: PASS (50.00 s)
(2/6) type_specific.io-github-autotest-libvirt.save_and_restore.save_with_formats.positive_test.lzop: PASS (49.70 s)
(3/6) type_specific.io-github-autotest-libvirt.save_and_restore.save_with_formats.positive_test.gzip: PASS (71.65 s)
(4/6) type_specific.io-github-autotest-libvirt.save_and_restore.save_with_formats.positive_test.bzip2: PASS (118.37 s)
(5/6) type_specific.io-github-autotest-libvirt.save_and_restore.save_with_formats.positive_test.xz: PASS (128.29 s)
(6/6) …
```
=> Update case save_with_formats

libvirt/tests/cfg/numa/guest_numa_node_tuning/invalid_nodeset_of_numa_memory_binding.cfg, libvirt/tests/src/numa/guest_numa_node_tuning/invalid_nodeset_of_numa_memory_binding.py
RH9 & RH8 test result
```
avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35  guest_numa_node_tuning.invalid_nodeset
(01/16) type_specific.io-github-autotest-libvirt.guest_numa_node_tuning.invalid_nodeset.partially_inexistent.host.strict: PASS (7.14 s)
(02/16) type_specific.io-github-autotest-libvirt.guest_numa_node_tuning.invalid_nodeset.partially_inexistent.host.interleave: PASS (7.13 s)
(03/16) type_specific.io-github-autotest-libvirt.guest_numa_node_tuning.invalid_nodeset.partially_inexistent.host.preferred: PASS (7.22 s)
(04/16) type_specific.io-github-autotest-libvirt.guest_numa_node_tuning.invalid_nodeset.partially_inexistent.host.restrictive: PASS (7.17 s)
(05/16) type_specific.io-github-autotest-libvirt.guest_numa_node_tuning.invalid_nodeset.partially_inexist …
```
=> fix numa invalid test with hard code

libvirt/tests/cfg/guest_os_booting/migration/migration_boot.cfg, libvirt/tests/src/guest_os_booting/migration/migration_boot.py, provider/migration/base_steps.py
This PR adds:
VIRT-297947: Migrate vm with boot element
```
(1/2) type_specific.io-github-autotest-libvirt.guest_os_booting.migration.boot.os_dev: PASS (171.11 s)
(2/2) type_specific.io-github-autotest-libvirt.guest_os_booting.migration.boot.boot_order: PASS (171.39 s)
```
=> guest_os_booting: Add a case of migration

libvirt/tests/cfg/sriov/vIOMMU/migration_iommu_device.cfg, libvirt/tests/src/sriov/vIOMMU/migration_iommu_device.py, provider/sriov/sriov_base.py
This PR adds:
VIRT-294806: [vIOMMU] Migrate vm with iommu device
**Test results**: A failed case is due to a known issue.
```
(1/6) type_specific.io-github-autotest-libvirt.vIOMMU.migration.iommu_device.virtio_muti_devices.vhost_on.virtio: PASS (207.00 s)
(2/6) type_specific.io-github-autotest-libvirt.vIOMMU.migration.iommu_device.virtio_muti_devices.vhost_on.intel: ERROR: Login timeout expired    (output: 'exceeded 240 s timeout, last failure: Could not verify DHCP lease: 52:54:00:0d:38:53 --> 192.168.122.146') (594.96 s)
(3/6) type_specific.io-github-autotest-libvirt.vIOMMU.migration.iommu_device.virtio_muti_devices.vhost_off.virtio: PASS (209.01 s)
(4/6) type_specific.io-github-autotest-libvirt.vIOMMU.migration.iommu_device.virtio_muti_devices.vhost_off.intel: PASS (351.59 s)
(5/6) …
```
=> vIOMMU: Add a case of migration

v2v/tests/cfg/function_test_esx.cfg
=> v2v:add TC "Set administrator@vsphere.local as default username"

libvirt/tests/cfg/guest_os_booting/negative/boot_without_bootable_devices.cfg, libvirt/tests/src/guest_os_booting/negative/boot_without_bootable_devices.py
This PR adds:
VIRT-297948 - Boot vm without any bootable devices
` (2/2) type_specific.io-github-autotest-libvirt.guest_os_booting.boot_without_bootable_devices: PASS (48.18 s)
`
=> guest_os_booting: Add a case of booting vm without a bootable device

libvirt/tests/cfg/virtual_network/elements_and_attributes/element_sndbuf.cfg, libvirt/tests/src/virtual_network/elements_and_attributes/element_sndbuf.py, spell.ignore
- VIRT-296263 - [sndbuf] Start vm with sndbuf setting and check the qemu cmd line
Depends on
- https://github.com/avocado-framework/avocado-vt/pull/3773
Test result:
(1/3) type_specific.io-github-autotest-libvirt.virtual_network.elements_and_attributes.sndbuf.0: PASS (43.64 s)
(2/3) type_specific.io-github-autotest-libvirt.virtual_network.elements_and_attributes.sndbuf.1600: PASS (46.42 s)
(3/3) type_specific.io-github-autotest-libvirt.virtual_network.elements_and_attributes.sndbuf.1800: PASS (42.93 s)
=> Add network case of element sndbuf

libvirt/tests/cfg/memory/memory_backing/memory_access_mode.cfg, libvirt/tests/src/memory/memory_backing/memory_access_mode.py
Memory access mode
```
[root@dell-per320-02 tp-libvirt]#  avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 memory.backing.access_mode
(01/84) type_specific.io-github-autotest-libvirt.memory.backing.access_mode.memory_allocation.without_hugepage.numa_access_private.mem_access_private.file: PASS (82.70 s)
(02/84) type_specific.io-github-autotest-libvirt.memory.backing.access_mode.memory_allocation.without_hugepage.numa_access_private.mem_access_private.anonymous: PASS (83.02 s)
(03/84) type_specific.io-github-autotest-libvirt.memory.backing.access_mode.memory_allocation.without_hugepage.numa_access_private.mem_access_private.memfd: PASS (81.78 s)
(04/84) type_specific.io-github-autotest-libvirt.memory.backing.access_mode.memory_ …
```
=> add case for memory access mode

libvirt/tests/src/virtual_network/elements_and_attributes/element_sndbuf.py
The format of sndbuf in qemu cmd line is different on 8 and 9.
Before:
```
(1/3) type_specific.io-github-autotest-libvirt.virtual_network.elements_and_attributes.sndbuf.0: FAIL: Expecting '"sndbuf":0' does exist in qemu command line, but  notfound (49.72 s)
(2/3) type_specific.io-github-autotest-libvirt.virtual_network.elements_and_attributes.sndbuf.1600: FAIL: Expecting '"sndbuf":1600' does exist in qemu command line, but  notfound (55.65 s)
(3/3) type_specific.io-github-autotest-libvirt.virtual_network.elements_and_attributes.sndbuf.1800: FAIL: Expecting '"sndbuf":1800' does exist in qemu command line, but  notfound (55.19 s)
```
After:
```
(1/3) type_specific.io-github-autotest-libvirt.virtual_network.elements_and_attributes.sndbuf.0: PASS (51.73 s)
(2/3) …
```
=> virtual_network: Update the regex of sndbuf

libvirt/tests/cfg/virtual_network/lifecycle/lifecycle_vdpa_interface.cfg, libvirt/tests/src/virtual_network/lifecycle/lifecycle_vdpa_interface.py
The vDPA interface starts to support save/restore, so updating the cases.
` (1/1) type_specific.io-github-autotest-libvirt.virtual_network.lifecycle.vdpa_interface.default.mellanox: FAIL: Run '/usr/bin/virsh save avocado-vt-vm1 /tmp/avocado_2rd5ls9z/avocado-vt-vm1.save ' expect fail, but run successfully. (127.67 s)
`
**after the fix:**
` (1/1) type_specific.io-github-autotest-libvirt.virtual_network.lifecycle.vdpa_interface.default.mellanox: PASS (199.00 s)
`
=> vdpa: Fixup 'save' related failures

libvirt/tests/cfg/guest_os_booting/negative/update_device_boot_order.cfg, libvirt/tests/src/guest_os_booting/negative/update_device_boot_order.py
This PR adds:
VIRT-297949 - [Negative] Update device with boot order
` (1/2) type_specific.io-github-autotest-libvirt.guest_os_booting.update_device.boot_order: PASS (42.66 s)
`
=> guest_os_booting: Add a case of update-device

libvirt/tests/cfg/memory/memory_backing/hugepage_mount_path.cfg, libvirt/tests/src/memory/memory_backing/hugepage_mount_path.py
VIRT-297104: Huge page mount path
```
avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 memory.backing.mount_path
(1/3) type_specific.io-github-autotest-libvirt.memory.backing.mount_path.default: PASS (61.76 s)
(2/3) type_specific.io-github-autotest-libvirt.memory.backing.mount_path.disabled: PASS (25.95 s)
(3/3) type_specific.io-github-autotest-libvirt.memory.backing.mount_path.customized: PASS (29.31 s)
```
Depend on 
- https://github.com/avocado-framework/avocado-vt/pull/3767 
- https://github.com/avocado-framework/avocado-vt/pull/3780
=> memory: add case for hugepage mount path

libvirt/tests/cfg/memory/memory_backing/discard_memory_content_setting.cfg, libvirt/tests/src/memory/memory_backing/discard_memory_content_setting.py
VIRT-298033: Discard memory content
```
[root@dell-per730-59 tp-libvirt]  avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 memory.backing.discard
(01/32) type_specific.io-github-autotest-libvirt.memory.backing.discard.memory_allocation.numa_discard_yes.mem_discard_yes.file: PASS (52.49 s)
(02/32) type_specific.io-github-autotest-libvirt.memory.backing.discard.memory_allocation.numa_discard_yes.mem_discard_yes.anonymous: PASS (55.71 s)
(03/32) type_specific.io-github-autotest-libvirt.memory.backing.discard.memory_allocation.numa_discard_yes.mem_discard_yes.memfd: PASS (55.42 s)
(04/32) type_specific.io-github-autotest-libvirt.memory.backing.discard.memory_allocation.numa_discard_yes.mem_discard_yes.hugepaged_file: PASS (55.10 …
```
=> add case for discard memory content

libvirt/tests/cfg/scsi/scsi_device.cfg, libvirt/tests/src/scsi/scsi_device.py
Add more scsi device case
xx-186123: [SCSI] Hot-plug the same scsi device to two guests with shareable element
xx-145209: [scsi] Check the qemu-pr-helper process can be restarted when vm issue pr cmds
xx-98980:  [scsi] [negative] Generate duplicated addresses for scsi devices -- bug 1210587 (fixe
=> Add  scsi device case

libvirt/tests/cfg/virtual_network/connectivity/connectivity_check_bridge_interface.cfg, libvirt/tests/src/virtual_network/connectivity/connectivity_check_bridge_interface.py, libvirt/tests/src/virtual_network/connectivity/connectivity_check_bridge_interface_unprivileged.py
1. On s390x, ACPI is not available.
2. Remove DAC security driver for unprivileged user if present as it
is not supported for those users.
3. Allow for configuration of host and guest interface names.
=> virtual_network/connectivity: fix test case for s390x

libvirt/tests/cfg/migration/migration_performance_tuning/migration_parallel_connections.cfg, libvirt/tests/cfg/migration/migration_uri/tcp_migration_port_allocation_port_occupied_by_other_app.cfg, libvirt/tests/src/migration/migration_uri/tcp_migration_port_allocation_port_occupied_by_other_app.py
VIRT-298371 - [VM migration] network data transport - TCP - migration
port allocation - port occupied by other app
=> migration: Add case to test port occupied by other app

libvirt/tests/cfg/virtual_network/connectivity/connectivity_check_ethernet_interface.cfg, libvirt/tests/src/virtual_network/connectivity/connectivity_check_ethernet_interface.py, provider/virtual_network/network_base.py
- VIRT-296218 - [ethernet] Check connectivity for ethernet type interface with managed='no'
test result:
```
(1/9) type_specific.io-github-autotest-libvirt.virtual_network.connectivity_check.ethernet_interface.managed_no.positive_test.tap.no_mtu.non_root_user: PASS (77.80 s)
(2/9) type_specific.io-github-autotest-libvirt.virtual_network.connectivity_check.ethernet_interface.managed_no.positive_test.tap.larger_mtu.non_root_user: PASS (84.31 s)
(3/9) type_specific.io-github-autotest-libvirt.virtual_network.connectivity_check.ethernet_interface.managed_no.positive_test.tap.smaller_mtu.non_root_user: PASS (80.90 s)
(4/9) type_specific.io-github-autotest-libvirt.virtual_network.connectivity_check.ethernet_interface.managed_no.positive_test.macvtap.no_mtu.non_root_user: PASS (60.91 s)
(5/9) …
```
=> Add case of connectivity check of ethernet type interface

libvirt/tests/src/virtio/virtio_page_per_vq.py
For now, arm can not create USB controller automatically.
When the device_type is controller, all controllers will be deleted, including the USB controller here. However, arm can not create USB controller automatically now. So it will fail to define the guest then.
Before:
```
ERROR 1-type_specific.io-github-autotest-libvirt.virtio_attributes.virtio_page_per_vq.controller.serial.default_start -> LibvirtXMLError: Failed to define avocado-vt-vm1 for reason:
error: Failed to define domain from /tmp/xml_utils_temp_05fpu947.xml
error: unsupported configuration: USB is disabled for this domain, but USB devices are present in the domain XML
```
After:
```
PASS 1-type_specific.io-github-autotest-libvirt.virtio_attributes.virtio_page_per_vq.controller.serial.default_start
```
=> chardev_pcie: Create USB controller manually for aarch64

libvirt/tests/src/npiv/npiv_virtual_disk.py
In negative test, we only need to check the mkfs result. If it was not permitted, that means it's expected for readonly npiv disk. So here don't use the check_vm_disk() function to check detailly.
=> npiv: update the check result of negative test

libvirt/tests/cfg/memory/memory_attach_device.cfg, libvirt/tests/cfg/memory/memory_update_device.cfg, libvirt/tests/src/memory/memory_attach_device.py, libvirt/tests/src/memory/memory_update_device.py
Fix memory device attachment and update errors.
The block size was too small, requiring a minimum of 524288KiB. 
This commit corrects the issue, allowing successful memory device 
attachment and updates.
Tested with libvirt version 9.5.0
**Results for x86_64** 
**avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 memory_update_device.virtio_mem --vt-connect-uri qemu:///system**
JOB ID     : 270d985bae570287fd62983eeb9c661b13e36868
JOB LOG    : /var/lib/avocado/job-results/job-2023-10-23T03.12-270d985/job.log
(1/1) type_specific.io-github-autotest-libvirt.memory_update_device.virtio_mem: PASS (89.62 s)
**RESULTS    : PASS 1 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0**
JOB HTML   : /var/lib/avocado/job-results/job-2023-10-23T03.12-270d985/results.html …
=> Memory : Fix incorrect block size on arm

libvirt/tests/cfg/scsi/scsi_device.cfg
Add vms = avocado-vt-vm1 vm1 back to scsi_device.cfg
This is an adjustment for PR: https://github.com/autotest/tp-libvirt/pull/5085
=> Add vms = avocado-vt-vm1 vm1 back to scsi_device.cfg

libvirt/tests/cfg/memory/memory_backing/hugepage_mount_path.cfg
The default hugepage size is 512M for aarch64.
Update the test case according to the changes in polarion case for aarch64.
Test Result:
```
(1/3) type_specific.io-github-autotest-libvirt.memory.backing.mount_path.default: PASS (73.04 s)
(2/3) type_specific.io-github-autotest-libvirt.memory.backing.mount_path.disabled: PASS (33.81 s)
(3/3) type_specific.io-github-autotest-libvirt.memory.backing.mount_path.customized: PASS (40.59 s)
```
=> memory_hugepage_mount: Enable test for aarch64

libvirt/tests/cfg/virtual_disks/virtual_disks_filedescriptor.cfg, libvirt/tests/src/virtual_disks/virtual_disks_filedescriptor.py
Add one case to cover hotplug qcow2 image with opened fdgroup by virsh attach-device
Bug 2193315 - Fail to hot-plug a qcow2 image with fdgroup
=> Add one case to cover hotplug qcow2 image with opened fdgroup 

libvirt/tests/cfg/memory/memory_backing/memory_source_and_allocation.cfg, libvirt/tests/src/memory/memory_backing/memory_source_and_allocation.py
VIRT-297914: Memory source and allocation
```
avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 memory.backing.source_and_allocation
(01/32) type_specific.io-github-autotest-libvirt.memory.backing.source_and_allocation.memory_allocation.with_numa.ondemand.page_default.file: PASS (53.33 s)
(02/32) type_specific.io-github-autotest-libvirt.memory.backing.source_and_allocation.memory_allocation.with_numa.ondemand.page_default.anonymous: PASS (57.83 s)
(03/32) type_specific.io-github-autotest-libvirt.memory.backing.source_and_allocation.memory_allocation.with_numa.ondemand.page_default.memfd: PASS (58.69 s)
(04/32) type_specific.io-github-autotest-libvirt.memory.backing.source_and_allocation.memory_allocation.with_numa.ondemand.page …
```
=> add case for memory source and allocation

libvirt/tests/cfg/memory/memory_misc.cfg
Depends on: 
- https://github.com/avocado-framework/avocado-vt/pull/3790
Test result:
(1/1) type_specific.io-github-autotest-libvirt.memory_misc.xml_check.smbios: PASS (6.68 s)
=> memory_misc:update code according to xml class change

libvirt/tests/src/virtual_network/iface_network.py
Tests passed with the updated changes.
(2/9) type_specific.io-github-autotest-libvirt.virtual_network.iface_network.dnsmasq_test.net_dns_forward: PASS (24.47 s)
(3/9) type_specific.io-github-autotest-libvirt.virtual_network.iface_network.dnsmasq_test.net_domain: PASS (25.41 s)
(4/9) type_specific.io-github-autotest-libvirt.virtual_network.iface_network.dnsmasq_test.net_netmask: PASS (25.32 s)
(5/9) type_specific.io-github-autotest-libvirt.virtual_network.iface_network.dnsmasq_test.net_forwarder_full: PASS (24.42 s)
(6/9) type_specific.io-github-autotest-libvirt.virtual_network.iface_network.dnsmasq_test.net_forwarder_domain: PASS (24.94 s)
(7/9) type_specific.io-github-autotest-libvirt.virtual_network.iface_network.dnsmasq_test.net_f …
=> iface_network.py: Fix for pid path checking issue

libvirt/tests/cfg/guest_os_booting/ovmf_firmware/ovmf_backed_nvram.cfg, libvirt/tests/src/guest_os_booting/ovmf_firmware/ovmf_backed_nvram.py
This case is to verify the ovmf different backed nvram source. Now it only cover the file type.
=> guest_os_booting: add new case for backed nvram source

libvirt/tests/src/scsi/scsi_device.py
Fix positional arguments mismatch for test_coldplug_scsi_hostdev_qemu_pr_helper.
Before:
```
ERROR 1-type_specific.io-github-autotest-libvirt.scsi_device_manipulate.coldplug.scsi_hostdev.positive.qemu_pr_helper -> TypeError: test_coldplug_scsi_hostdev_qemu_pr_helper() takes 2 positional arguments but 3 were given
```
After:
```
PASS 1-type_specific.io-github-autotest-libvirt.scsi_device_manipulate.coldplug.scsi_hostdev.positive.qemu_pr_helper
```
=> virtual_disk: fix positional arguments mismatch in function definition and call

libvirt/tests/cfg/virtual_network/elements_and_attributes/attribute_port_isolated.cfg, libvirt/tests/src/virtual_network/elements_and_attributes/attribute_port_isolated.py
- VIRT-296245 - [port isolated] configure port isolsated attribute in interface/network
Test result:
```
(01/10) type_specific.io-github-autotest-libvirt.virtual_network.elements_and_attributes.port_isolated.set_yes.br: PASS (106.64 s)
(02/10) type_specific.io-github-autotest-libvirt.virtual_network.elements_and_attributes.port_isolated.set_yes.network.default.set_iface: PASS (120.26 s)
(03/10) type_specific.io-github-autotest-libvirt.virtual_network.elements_and_attributes.port_isolated.set_yes.network.default.set_network: PASS (69.55 s)
(04/10) type_specific.io-github-autotest-libvirt.virtual_network.elements_and_attributes.port_isolated.set_yes.network.br.set_iface: PASS (109.66 s)
(05/10) type_specific.io-github-autotest-libvirt.virtual_network.elements_and_attributes.port_isolated.set …
```
=> Add new case of port isolated

libvirt/tests/src/daemon/crash_regression.py
Fix the problem that LibvirtXMLError exception cannot be thrown successfully
Before:
```
ERROR 1-type_specific.io-github-autotest-libvirt.daemon.crash_regression.mix_boot_order_os_boot -> LibvirtXMLError: Failed to define avocado-vt-vm1 for reason:error: Failed to define domain from /tmp/xml_utils_temp_8zdo8v4r.xmlerror: XML error: Invalid value for attribute 'order' in element 'boot': Zero is not permitted
ERROR 1-type_specific.io-github-autotest-libvirt.daemon.crash_regression.invalid_interface -> LibvirtXMLError: Failed to define avocado-vt-vm1 for reason:error: Failed to define domain from /tmp/xml_utils_temp_1av1jk2v.xmlerror: internal error: No <source> 'bridge' attribute specified with <interface type='bridge'/>
```
After:
```
PASS …
```
=> libvirtd: Fix LibvirtXMLError exception issue

libvirt/tests/cfg/virtual_network/connectivity/connectivity_check_user_interface.cfg, libvirt/tests/src/virtual_network/connectivity/connectivity_check_user_interface.py
arm does not support acpi index.
remove acpi settings here as the scenario is not for acpi test.
Test Results are as follows, the failed two cases are cause by another issue.
```
(01/14) type_specific.io-github-autotest-libvirt.virtual_network.connectivity_check.user_interface.positive_test.default.root_user: FAIL: default ipv4 gateway not match. Expect 10.0.2.2, but got ip route|grep dhcp | awk '/default/ { print $3 }}'\n10.0.2.2 (51.56 s)                                                   
(02/14) type_specific.io-github-autotest-libvirt.virtual_network.connectivity_check.user_interface.positive_test.default.non_root_user: FAIL: default ipv4 gateway not match. Expect 10.0.2.2, but got ip route|grep dhcp | awk '/default/ { print $3 }}'\n10.0.2.2 (57.93 s) …
```
=> virtual_network: remove acpi settings in connectivity_check_user_interface

libvirt/tests/cfg/memory/memory_balloon/guest_without_mem_balloon.cfg, libvirt/tests/src/memory/memory_balloon/guest_without_mem_balloon.py
VIRT-299022: Check No error msg prompts without guest memory balloon driver
```
avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 memory.balloon.no_balloon
(1/3) type_specific.io-github-autotest-libvirt.memory.balloon.no_balloon.memory_allocation.virtio_model: PASS (40.50 s)
(2/3) type_specific.io-github-autotest-libvirt.memory.balloon.no_balloon.memory_allocation.virtio_trans_model: PASS (42.84 s)
(3/3) type_specific.io-github-autotest-libvirt.memory.balloon.no_balloon.memory_allocation.virtio_non_trans_model: PASS (41.77 s)
```
=> add case for guest without memballoon

libvirt/tests/cfg/virtual_network/connectivity/connectivity_check_mcast_interface.cfg, libvirt/tests/src/virtual_network/connectivity/connectivity_check_mcast_interface.py
- VIRT-294957 - [mcast] Check connectivity of mcast type interface
test result:
(1/1) type_specific.io-github-autotest-libvirt.virtual_network.connectivity_check.mcast_interface.default: PASS (108.24 s)
JOB HTML   : /var/lib/avocado/job-results/job-2023-08-31T23.33-6281078/results.html
JOB TIME   : 109.69 s
=> Add case of connectivity check of mcast interface

libvirt/tests/cfg/virtual_network/update_device/update_iface_type_live.cfg, libvirt/tests/src/virtual_network/update_device/update_iface_type_live.py
- VIRT-298342 - [update-device] live update interface with different interface type - bridge/direct type
Test result
```
(1/2) type_specific.io-github-autotest-libvirt.virtual_network.update_device.iface_type.live.bridge_type: PASS (59.38 s)
(2/2) type_specific.io-github-autotest-libvirt.virtual_network.update_device.iface_type.live.direct_type: PASS (37.35 s)
```
=> Add network case of update device of interface type

libvirt/tests/cfg/virtual_network/attach_detach_device/attach_mtu_malformed.cfg, libvirt/tests/src/virtual_network/attach_detach_device/attach_mtu_malformed.py
- VIRT-299228 - [attach-device][mtu] hotplug with malformed mtu size or to interface type not supported
Test result:
```
(1/5) type_specific.io-github-autotest-libvirt.virtual_network.attach_detach_device.mtu.malformed.network.nat.non_digit_value: PASS (37.71 s)
(2/5) type_specific.io-github-autotest-libvirt.virtual_network.attach_detach_device.mtu.malformed.network.nat.neg_value: PASS (36.99 s)
(3/5) type_specific.io-github-autotest-libvirt.virtual_network.attach_detach_device.mtu.malformed.network.nat.large_value: PASS (37.40 s)
(4/5) type_specific.io-github-autotest-libvirt.virtual_network.attach_detach_device.mtu.malformed.network.direct: PASS (37.00 s)
(5/5) type_specific.io-github-autotest-libvirt.virtual_network.attach_detach_device.mtu.malformed.direct: PASS (36.44 s)
RESULTS    : …
```
=> Add new case of attach interface:mtu

libvirt/tests/cfg/virtual_network/elements_and_attributes/element_coalesce.cfg, libvirt/tests/src/virtual_network/elements_and_attributes/element_coalesce.py
- VIRT-296233: [coalesce] Set coalesce for network and bridge type interface
Test result:
```
(1/9) type_specific.io-github-autotest-libvirt.virtual_network.elements_and_attributes.coalesce.nat_network.virtio.32: PASS (82.72 s)
(2/9) type_specific.io-github-autotest-libvirt.virtual_network.elements_and_attributes.coalesce.nat_network.virtio.big_value: PASS (50.43 s)
(3/9) type_specific.io-github-autotest-libvirt.virtual_network.elements_and_attributes.coalesce.nat_network.virtio.big_value_neg: PASS (7.10 s)
(4/9) type_specific.io-github-autotest-libvirt.virtual_network.elements_and_attributes.coalesce.nat_network.virtio.neg_val: PASS (7.11 s)
(5/9) type_specific.io-github-autotest-libvirt.virtual_network.elements_and_attributes.coalesce.nat_network.virtio.driver_qemu: PASS (50.83 s)
(6/9) …
```
=> Add new case of virtual network:element coalesce

libvirt/tests/src/daemon/conf_file/sysconfig_libvirt_guests/libvirt_guests.py
The test sometimes fails and there's no log for the guest service at all. Add checks for start and restart to succeed and if not, log the service logs with journalctl.
Also, the Tail was called incorrectly leading to (per default unrecorded) TypeError
"can only concatenate str (not "tuple") to str"
The Tail already has a log file where it stores the output. Print its path so it can be inspected if needed.
=> libvirt-guests: Improve test logging

libvirt/tests/cfg/virtual_network/connectivity/connectivity_check_ethernet_interface.cfg
Add a version check since the bug only fixed(bug 2144738) on rhel 9, so we skip the test "managed_no.negative_test.managed_yes" on rhel 8. Since set the macvtap device mtu bigger than 1500 need to set the physical iface's mtu first, so we update the test parameters to set the mtu less than 1500.
=> Add a libvirt version check

libvirt/tests/cfg/numa/guest_numa_node_tuning/memory_binding_with_emulator_thread.cfg
The cpu model supported on arm is host-passthrough instead of host-model.
=> memory_binding_with_emulator_thread: fix cpu model for arm

libvirt/tests/cfg/cpu/iothread.cfg, libvirt/tests/cfg/virsh_cmd/domain/virsh_iothreadadd.cfg, libvirt/tests/cfg/virsh_cmd/domain/virsh_iothreaddel.cfg, libvirt/tests/cfg/virsh_cmd/domain/virsh_iothreadinfo.cfg, libvirt/tests/cfg/virsh_cmd/domain/virsh_iothreadpin.cfg, libvirt/tests/src/cpu/iothread.py, libvirt/tests/src/virsh_cmd/domain/virsh_iothreadadd.py, libvirt/tests/src/virsh_cmd/domain/virsh_iothreaddel.py
This is to test the iothread parameters could be set before vm starts
Case ID: XXX-299032
Depends on 
- https://github.com/avocado-framework/avocado-vt/pull/3791
=> iothread: add case with two iothread inactive

libvirt/tests/cfg/cpu/aarch64_cpu_sve.cfg, libvirt/tests/src/cpu/aarch64_cpu_sve.py
This commit adds a new test case to check
the SVE support on the host. The new
test case checks for the absence of SVE
on the host.
Tested with libvirt version 8.0.0
Test results:
**avocado run --vt-type libvirt --test-runner=runner --vt-machine-type arm64-mmio aarch64_cpu_sve --vt-connect-uri qemu:///system**
(1/9) type_specific.io-github-autotest-libvirt.aarch64_cpu_sve.positive_test.boot_test.enable_sve: CANCEL: Host doesn't support SVE (27.25 s)
(2/9) type_specific.io-github-autotest-libvirt.aarch64_cpu_sve.positive_test.boot_test.disable_sve: CANCEL: Host doesn't support SVE (27.34 s)
(3/9) type_specific.io-github-autotest-libvirt.aarch64_cpu_sve.positive_test.vector_length_test.valid_length.single_vector.sve128: CANCEL: Host doesn't support SVE (29.39 s)
(4/9) …
=> CPU: Add new test case for SVE support.

libvirt/tests/cfg/virtual_network/connectivity/connectivity_check_ethernet_interface.cfg, libvirt/tests/src/virtual_network/connectivity/connectivity_check_ethernet_interface.py
arm does not support acpi index.
remove acpi settings here as the scenario is not for acpi test.
Test results are as follows, the failed 3 cases are caused by other issues.
```
(1/9) type_specific.io-github-autotest-libvirt.virtual_network.connectivity_check.ethernet_interface.managed_no.positive_test.tap.no_mtu.non_root_user: PASS (93.33 s)                                                                                                                                                      
(2/9) type_specific.io-github-autotest-libvirt.virtual_network.connectivity_check.ethernet_interface.managed_no.positive_test.tap.larger_mtu.non_root_user: PASS (91.79 s) …
```
=> virtual_network: remove acpi settings in connectivity_check_ethernet_interface

libvirt/tests/cfg/migration_with_copy_storage/migration_with_backingchain.cfg, libvirt/tests/src/migration_with_copy_storage/migration_with_backingchain.py
Since the image on source host will be compressed and the image on targe host will not be compressed, the disk size of the image will be inconsistent on the source host and target host. So remove disk size checkpoint.
=> migration: Remove disk size checkpoint

libvirt/tests/cfg/guest_os_booting/boot_order/hotplug_device_with_boot_order.cfg, libvirt/tests/src/guest_os_booting/boot_order/hotplug_device_with_boot_order.py
This PR mainly implements the hotpluging of disk/usb/filesystem devices with boot order elements.
=> guest os booting: add hotplug case with boot order element

libvirt/tests/src/libvirt_rng.py
The line intends to select the first virtio rng device that's available. Use a pattern to select it.
=> libvirt_rng: improve regex for virtio device

libvirt/tests/cfg/memory/memory_backing/discard_memory_content_setting.cfg, libvirt/tests/cfg/memory/memory_backing/hugepage_mount_path.cfg, libvirt/tests/cfg/memory/memory_backing/memory_access_mode.cfg, libvirt/tests/cfg/memory/memory_backing/page_locking_and_shared_pages.cfg
1. Enable activating hpage on s390x through kvm_module_parameters (will be set by CI).
2. Memory backing backend on s390x is s390.ram
3. Fix hpage size on s390x.
4. Exclude numa tests on s390x.
5. Exclude mount_path set because
a. it is too tightly coupled with numa
b. it assumes two different hpage sizes are available
c. it assumes availability of mem devices
=> memory_backing: fix on s390x

libvirt/tests/cfg/numa/guest_numa_topology/numa_topology_with_hugepage.cfg, libvirt/tests/src/numa/guest_numa_topology/numa_topology_with_hugepage.py
The support hugepage sizes on aarch64 are 2M, 512M and 16G, and the default pagesize is 512M.
Test Result:
```
(1/4) type_specific.io-github-autotest-libvirt.guest_numa_topology.numa_topology_with_hugepage.2M: PASS (46.30 s)
(2/4) type_specific.io-github-autotest-libvirt.guest_numa_topology.numa_topology_with_hugepage.512M: PASS (44.99 s)
(3/4) type_specific.io-github-autotest-libvirt.guest_numa_topology.numa_topology_with_hugepage.2M_512M: PASS (49.47 s)
(4/4) type_specific.io-github-autotest-libvirt.guest_numa_topology.numa_topology_with_hugepage.scarce_mem: PASS (13.97 s)
```
=> numa_topology_with_hugepage: Enable test for aarch64

libvirt/tests/src/daemon/check_daemon_after_remove_pkgs.py
https://github.com/autotest/tp-libvirt/commit/d9d6fb8d9e5cfea7c585fea18d9022856be9a99b introduced another condition.
However, the command was executed in Bash and either true or false. Now log the output for easier debugging.
Debugging output now:
```
2023-11-28 03:22:56,962 check_daemon_aft L0051 DEBUG|   virtlogd.service                                                                                               loaded    inactive dead      libvirt logging daemon
virtlogd-admin.socket                                                                                          loaded    inactive dead      libvirt logging daemon admin socket
virtlogd.socket                                                                                                loaded    inactive dead      libvirt …
```
=> daemon/remove_pkgs: improve logging

libvirt/tests/src/migration/migrate_vm.py
On latest libvirt version, running 'service libvirtd restart' command will cause virtnetworkd.socket, virtstoraged.socket, etc. to become inactive, which will cause subsequent cases to fail. So update code.
=> migration: Fix libvirtd service issue

libvirt/tests/src/scsi/scsi_device.py
Fix scsi_hostdev.positive.qemu_pr_helper case failure
Since it use uniform pattern: run_test_case(test, params, env) to trigger test method, so all test method has 3 parameters
=> Fix scsi_hostdev.positive.qemu_pr_helper case failure

libvirt/tests/cfg/virtual_network/locked_memory_vdpa/hotplug_mem_to_vm_with_vdpa.cfg, libvirt/tests/src/virtual_network/locked_memory_vdpa/hotplug_mem_to_vm_with_vdpa.py
This PR adds:
RHEL-283024 - [vdpa] hotplug memory to vm with vdpa type
interface and check the memlock limit
```
(1/6) type_specific.io-github-autotest-libvirt.virtual_network.locked_memory.vdpa_interface.hotplug_mem.at_memory_to_vm_with_iface.simulator: PASS (49.73 s)
(2/6) type_specific.io-github-autotest-libvirt.virtual_network.locked_memory.vdpa_interface.hotplug_mem.at_memory_to_vm_with_iface.mellanox: PASS (72.22 s)
(3/6) type_specific.io-github-autotest-libvirt.virtual_network.locked_memory.vdpa_interface.hotplug_mem.at_memory_to_vm_with_iface_and_locked_mem.simulator: PASS (50.74 s)
(4/6) type_specific.io-github-autotest-libvirt.virtual_network.locked_memory.vdpa_interface.hotplug_mem.at_memory_to_vm_with_iface_and_locked_mem.mellanox: PASS (75.29 s)
(5/6) …
```
=> virtual_network: Add a case about memlock limit for vdpa interfaces

libvirt/tests/cfg/numa/host_numa/host_numa_info.cfg, libvirt/tests/src/numa/host_numa/host_numa_info.py, spell.ignore
Case ID:  xxx-297812
Test scenarios:  Verify numa related info could be achieved by allocating hugepages using supported hugepage size,
check numa information by virsh commands, like capabilities, freepages...
=> host_numa_info: add case

provider/virtual_network/network_base.py
The chown command may fail in rhel 8 since the tap device is not ready. Add 2s before the chown command to avoid this issue.
=> Wait 2s after the macvtap device created

libvirt/tests/src/virtual_network/iface_options.py
On hosts with more than one NIC, the default gw is a multiline string with more than one line.
Use regex to match those, too.
=> iface_options: use multiline regex for checks

libvirt/tests/cfg/sriov/scalability/sriov_scalability_max_vf.cfg, libvirt/tests/src/sriov/scalability/sriov_scalability_max_vfs.py
This PR updates scalability test scenarios.
```
(1/2) type_specific.io-github-autotest-libvirt.sriov.scalability.max_vfs.maximum: PASS (485.47 s)
(2/2) type_specific.io-github-autotest-libvirt.sriov.scalability.max_vfs.exceed_maximum: PASS (261.45 s)
```
=> sriov: Add a scalability test

libvirt/tests/cfg/migration_with_copy_storage/migration_bandwidth_limit.cfg, libvirt/tests/src/migration_with_copy_storage/migration_bandwidth_limit.py, provider/migration/migration_base.py
VIRT-297906 - VM live migration with copy storage - bandwidth limit
=> migration: Add bandwidth limit case

libvirt/tests/src/virtual_network/connectivity/connectivity_check_ethernet_interface.py
Get IP from configured host interface.
This is important if more than one interface are available.
=> connectivity_check/ethernet: Select host interface

libvirt/tests/cfg/virtual_network/passt/passt_function.cfg, libvirt/tests/src/virtual_network/passt/passt_function.py, provider/virtual_network/passt.py
- VIRT-297101 - [user][passt] Passt backend interface - check the portforwarding feature
Test result:
```
(1/8) type_specific.io-github-autotest-libvirt.virtual_network.passt.interface_function.minimal.root_user: PASS (243.62 s)
(2/8) type_specific.io-github-autotest-libvirt.virtual_network.passt.interface_function.minimal.non_root_user: PASS (168.62 s)
(3/8) type_specific.io-github-autotest-libvirt.virtual_network.passt.interface_function.ip_portfw.ip_addr.root_user: PASS (489.26 s)
(4/8) type_specific.io-github-autotest-libvirt.virtual_network.passt.interface_function.ip_portfw.ip_addr.non_root_user: PASS (413.99 s)
(5/8) type_specific.io-github-autotest-libvirt.virtual_network.passt.interface_function.ip_portfw.dev_only.root_user: PASS (417.03 s)
(6/8) …
```
=> Add scenario of passt function test

libvirt/tests/cfg/memory/memory_backing/memory_source_and_allocation.cfg, libvirt/tests/src/memory/memory_backing/memory_source_and_allocation.py
1. Fix hpage size
2. Add kvm_module_parameters to enable hpage on CI
3. Disable unsupported scenarios
=> memory_backing: fix source and allocation on s390x

libvirt/tests/src/serial/serial_pty_log.py
Fix serial.pty.log.file failure on s390x
Extend timeout to grab log since it may run under VM
=> Fix serial.pty.log.file failure on s390x

libvirt/tests/src/numa/host_numa/host_numa_info.py
"all_usable_numa_nodes" has been deprecated in db7401a, it uses "online_nodes_withmem" now.
Before:
```
(1/1) type_specific.io-github-autotest-libvirt.host_numa.numa_info.default: ERROR: 'NumaTest' object has no attribute 'all_usable_numa_nodes' (11.21 s)
```
After:
```
(1/1) type_specific.io-github-autotest-libvirt.host_numa.numa_info.default: PASS (14.23 s)
```
=> numa: Update the attribute for online nodes

libvirt/tests/cfg/migration_with_copy_storage/target_image_smaller_than_source.cfg, libvirt/tests/src/migration_with_copy_storage/target_image_smaller_than_source.py
XXX-298334 - VM live migration with copy storage - target image size is smaller than source image size
=> migration: Add case about image size

libvirt/tests/cfg/memory/memory_devices/invalid_virtio_mem_config.cfg, libvirt/tests/src/memory/memory_devices/invalid_virtio_mem_config.py, provider/memory/memory_base.py
xxxx-299162: Invalid virtio-mem memory device config values
Depend on https://github.com/avocado-framework/avocado-vt/pull/3802 
Rhel9 & x86
```
avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 memory.devices.invalid_virtio_mem.with_numa
No python imaging library installed. Screendump and Windows guest BSOD detection are disabled. In order to enable 
(1/7) type_specific.io-github-autotest-libvirt.memory.devices.invalid_virtio_mem.with_numa.over_request_mem: PASS (41.49 s)
(2/7) type_specific.io-github-autotest-libvirt.memory.devices.invalid_virtio_mem.with_numa.max_addr: PASS (40.19 s)
(3/7) type_specific.io-github-autotest-libvirt.memory.devices.invalid_virtio_mem.with_numa.unexisted_node: PASS (43.17 s)
(4/7) …
```
=> add case for invalid virtio-mem config

libvirt/tests/cfg/sriov/vIOMMU/intel_iommu_aw_bits.cfg, libvirt/tests/src/sriov/vIOMMU/intel_iommu_aw_bits.py
This PR adds:
Start vm with different iommu address width values
```
(1/4) type_specific.io-github-autotest-libvirt.vIOMMU.intel_iommu.aw_bits.48: PASS (204.65 s)
(2/4) type_specific.io-github-autotest-libvirt.vIOMMU.intel_iommu.aw_bits.39: PASS (200.77 s)
(3/4) type_specific.io-github-autotest-libvirt.vIOMMU.intel_iommu.aw_bits.36: PASS (168.02 s)
(4/4) type_specific.io-github-autotest-libvirt.vIOMMU.intel_iommu.aw_bits.3423: PASS (167.79 s)
```
=> vIOMMU: Add a case about iommu address width

libvirt/tests/cfg/migration_with_copy_storage/network_data_transport/tcp_listen_address.cfg, libvirt/tests/src/migration_with_copy_storage/network_data_transport/tcp.py
VIRT-297874 - VM live migration with copy storage - network data transport - TCP - --listen-address
=> migration: Add listen address case

libvirt/tests/cfg/memory/memory_balloon/period_config_of_memory_balloon.cfg, libvirt/tests/src/memory/memory_balloon/period_config_of_memory_balloon.py
VIRT-299028: Period config of memory balloon
https://github.com/avocado-framework/avocado-vt/pull/3768 
RHE9 & RHEL8+x86
```
avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35  memory.balloon.period
(1/6) type_specific.io-github-autotest-libvirt.memory.balloon.period.memory_allocation.undefined_period.virtio_model: PASS (26.70 s)
(2/6) type_specific.io-github-autotest-libvirt.memory.balloon.period.memory_allocation.undefined_period.virtio_trans_model: PASS (32.40 s)
(3/6) type_specific.io-github-autotest-libvirt.memory.balloon.period.memory_allocation.undefined_period.virtio_non_trans_model: PASS (32.96 s)
(4/6) type_specific.io-github-autotest-libvirt.memory.balloon.period.memory_allocation.int_period.virtio_model: PASS (32.76 …
```
=> add case for period config of memballoon

libvirt/tests/cfg/memory/memory_devices/invalid_dimm_memory_device_config.cfg, libvirt/tests/src/memory/memory_devices/invalid_dimm_memory_device_config.py
VIRT-299046: Verify error messages prompt with invalid memory device configs
RHEL9& RHEL 8 + x86
```
avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 memory.devices.invalid_dimm
(1/6) type_specific.io-github-autotest-libvirt.memory.devices.invalid_dimm.with_numa.exceed_slot: PASS (15.26 s)
(2/6) type_specific.io-github-autotest-libvirt.memory.devices.invalid_dimm.with_numa.max_addr: PASS (14.97 s)
(3/6) type_specific.io-github-autotest-libvirt.memory.devices.invalid_dimm.with_numa.unexisted_node: PASS (26.26 s)
(4/6) type_specific.io-github-autotest-libvirt.memory.devices.invalid_dimm.with_numa.unexisted_nodemask: PASS (14.41 s)
(5/6) type_specific.io-github-autotest-libvirt.memory.devices.invalid_dimm.with_numa.invalid_pagesi …
```
=> add case for invalid dimm device config

libvirt/tests/cfg/daemon/conf_file/qemu_conf/set_virtlogd.cfg, libvirt/tests/src/daemon/conf_file/qemu_conf/set_virtlogd.py
Add cases to cover start virtlogd with various config
VIRT-xx: virtlogd can be started with specified config by configuring VIRTLOGD_ARGS="--config /etc/libvirt/virtlogd-new.conf"
in  /etc/sysconfig/virtlogd
VIRT-xx: [virtlogd][-t | --timeout] Start virtlogd with --timeout <SECONDS> and without active guests
VIRT-xx: [virtlogd] [Reload] [negative] Virtlogd.service reload failed with invalid configuration
VIRT-xx: [virtlogd][Stop] Stop virtlogd service when guest is running
VIRT-xx: [virtlogd]Check qemu log when guest fails to start due to "qemu process exits" error
VIRT-xx: [virtlogd] Start virtlogd with default max_size and max_backups
VIRT-xx: [virtlogd]Remove the qemu log file when guest is running
VIRT-xx: [virtlogd] [start] [negative] Virtlogd.serivce start failed with invalid …
=> Add case to cover start virtlogd with specified configuration file

libvirt/tests/src/virtual_network/connectivity/connectivity_check_bridge_interface.py
Before:
TestFail: Expect mtu size: 4000, actual output: Device &quot;5&quot; does not exist.
After:
PASS 1-type_specific.io-github-autotest-libvirt.virtual_network.connectivity_check.bridge_interface.linux_br.multiqueue.nwfilter
=> Fix error of failed to get iface in vm from cfg file

libvirt/tests/cfg/memory/memory_update_device.cfg
Introduced by 869c29ebc659c
` (1/1) type_specific.io-github-autotest-libvirt.memory_update_device.virtio_mem: PASS (104.18 s)
`
=> memory: Fix up a virtio-mem device coldplug issue

libvirt/tests/cfg/libvirt_rng.cfg, libvirt/tests/src/libvirt_rng.py
The error message has change but is still
valid as it mentions the device model.
=> libvirt_rng: Add alternative expected error

libvirt/tests/src/daemon/conf_file/qemu_conf/set_virtlogd.py
Test result:
$avocado run conf_file.qemu_conf.set_virtlogd.positive_test.restart --vt-type libvirt
JOB ID     : 73e8c2f7dd614f76a30a0338c1d142fb58ae716d
JOB LOG    : /var/lib/avocado/job-results/job-2023-12-13T03.04-73e8c2f/job.log
(1/1) type_specific.io-github-autotest-libvirt.conf_file.qemu_conf.set_virtlogd.positive_test.restart: STARTED
(1/1) type_specific.io-github-autotest-libvirt.conf_file.qemu_conf.set_virtlogd.positive_test.restart: PASS …
=> Start virtqemud for the modular daemon mode

libvirt/tests/src/migration/migration_uri/migration_network_data_transport_tcp.py
In some cases, the qemu conf is modified and it is restored after the test is completed. But the libvirtd serivce is not restarted which will cause other cases to fail. So update it.
=> migration: Fix issue about assign requested address

libvirt/tests/cfg/memory/memory_devices/virtio_mem_auto_placement.cfg, libvirt/tests/src/memory/memory_devices/virtio_mem_auto_placement.py, provider/memory/memory_base.py
VIRT-299160: Virtio-mem memory device with auto placement numatune
RHEL9+ x86
```
avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35  memory.devices.virtio_mem.auto_placement.with_numa
(1/5) type_specific.io-github-autotest-libvirt.memory.devices.virtio_mem.auto_placement.with_numa.strict: PASS (57.20 s)
(2/5) type_specific.io-github-autotest-libvirt.memory.devices.virtio_mem.auto_placement.with_numa.interleave: PASS (59.28 s)
(3/5) type_specific.io-github-autotest-libvirt.memory.devices.virtio_mem.auto_placement.with_numa.preferred: PASS (58.19 s)
(4/5) type_specific.io-github-autotest-libvirt.memory.devices.virtio_mem.auto_placement.with_numa.restrictive: PASS (58.18 s)
(5/5) …
```
=> add case for virtio-mem auto placement

v2v/tests/cfg/convert_from_file.cfg
Refer the error: FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/libvirt/images/v2v/ova-images//var/lib/libvirt/images/v2v/ova-images/esx6_7-rhel8.3-x86_64.ova'&#10;
=> v2v:fix the failed case in 9.4 functional testing

libvirt/tests/cfg/cpu/vcpu_cve.cfg
aarch64 supports cpu_model "host-passthrough".
Test Result:
```
(1/1) type_specific.io-github-autotest-libvirt.vcpu.cve.guest_cpu_cve_status.host_passthrough: PASS (53.25 s)
```
=> cpu: Skip host-model for aarch64

libvirt/tests/src/cpu/lifecycle_time.py
When running this test several times it sometimes
takes up to 1.029 seconds to sleep for 1 second.
This is still a good test result for the original
issue where we had deviations for 100-10000%.
Use a less strict check to account for this variability.
=> lifecycle_time: relax test condition

libvirt/tests/cfg/memory/memory_misc.cfg, libvirt/tests/src/memory/memory_misc.py
Update the hugepagesize to enable test for aarch64
The test results are as follows, the one failure case is another scripts issue.
```
(01/21) type_specific.io-github-autotest-libvirt.memory_misc.memorybacking.no_numa: CANCEL: This case is not supported by current libvirt. (6.56 s)
(02/21) type_specific.io-github-autotest-libvirt.memory_misc.memorybacking.mem_lock.no_limit: PASS (8.95 s)
(03/21) type_specific.io-github-autotest-libvirt.memory_misc.memorybacking.mem_lock.hard_limit: PASS (8.23 s)
(04/21) type_specific.io-github-autotest-libvirt.memory_misc.memorybacking.prealloc_thread.file_backed: CANCEL: This libvirt version doesn't support this function. (6.14 s) …
```
=> memory_misc: Enable test for aarch64

libvirt/tests/cfg/memory/memory_devices/virtio_mem_access_and_discard.cfg, libvirt/tests/src/memory/memory_devices/virtio_mem_access_and_discard.py
xxxx-299163: Virtio-mem memory device with access and discard settings
rhel9 & x86 
```
avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 memory.devices.virtio_mem.access_and_discard.with_numa
(1/9) type_specific.io-github-autotest-libvirt.memory.devices.virtio_mem.access_and_discard.with_numa.undefined.file: PASS (83.18 s)
(2/9) type_specific.io-github-autotest-libvirt.memory.devices.virtio_mem.access_and_discard.with_numa.undefined.anonymous: PASS (78.08 s)
(3/9) type_specific.io-github-autotest-libvirt.memory.devices.virtio_mem.access_and_discard.with_numa.undefined.memfd: PASS (82.58 s)
(4/9) type_specific.io-github-autotest-libvirt.memory.devices.virtio_mem.access_and_discard.with_numa.shared_and_discard.file: PASS (83.88 …
```
=> add case for virtio-mem access and discard setting

libvirt/tests/cfg/virtual_network/locked_memory_vdpa/mem_lock_limit_multiple_vdpa_interfaces.cfg
The jobs.yaml run vdpa related case in a separate job with a pattern "vdpa_interface". And these cases are excluded from the network job by the pattern "vdpa_interface" since it needs specific hardware.
=> Unify the name of the vdpa cases

libvirt/tests/cfg/guest_os_booting/boot_orer/boot_from_usb_device.cfg, libvirt/tests/src/guest_os_booting/boot_order/boot_from_usb_device.py
This PR mainly implements the boot order checking for the use block device, usb redirdev device and usb hostdev device.
=> guest_os_booting: add new boot order case for usb device

libvirt/tests/cfg/memory/memory_devices/virtio_mem_auto_placement.cfg
```
avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 memory.devices.virtio_mem.auto_placement
(1/5) type_specific.io-github-autotest-libvirt.memory.devices.virtio_mem.auto_placement.with_numa.strict: PASS (100.39 s)
(2/5) type_specific.io-github-autotest-libvirt.memory.devices.virtio_mem.auto_placement.with_numa.interleave: PASS (96.63 s)
(3/5) type_specific.io-github-autotest-libvirt.memory.devices.virtio_mem.auto_placement.with_numa.preferred: PASS (103.85 s)
(4/5) type_specific.io-github-autotest-libvirt.memory.devices.virtio_mem.auto_placement.with_numa.restrictive: PASS (94.96 s)
(5/5) type_specific.io-github-autotest-libvirt.memory.devices.virtio_mem.auto_placement.with_numa.undefined: PASS (100.83 s)
```
=> fix memory numa case name

libvirt/tests/cfg/virtual_disks/virtual_disks_multidisks.cfg, libvirt/tests/src/virtual_disks/virtual_disks_multidisks.py
Depends on https://github.com/avocado-framework/avocado-vt/pull/3815
The tests used the disk target as identifier for the disk inside of the VM. However, the target is not guaranteed to show up in the guest as-is, especially given that the /dev/XdY paths are not persistent and can change between boots.
Finally, the delete_scsi_disk doesn't return any value so it was always looping for the full timeout. Wrap it into a function that confirms if both the module and device have been removed.
=> virtual_disks_multidisks: fix disk discovery

libvirt/tests/src/virtual_disks/virtual_disks_transient_disk.py
Depends on https://github.com/avocado-framework/avocado-vt/pull/3815
The tests used the disk target as identifier for the disk inside of the VM. However, the target is not guaranteed to show up in the guest as-is, especially given that the /dev/XdY paths are not persistent and can change between boots.
=> virtual_disks_transient_disk: fix disk discovery

libvirt/tests/src/virtual_disks/virtual_disks_multivms.py
Depends on https://github.com/avocado-framework/avocado-vt/pull/3815
The tests used the disk target as identifier for the
disk inside of the VM. However, the target is not guaranteed
to show up in the guest as-is, especially given that the
/dev/XdY paths are not persistent and can change between boots.
Use instead a function that identifies a new disk inside of a VM
as the one disk that has no root mount on itself, its partitions
or volumes.
Finally, the `delete_scsi_disk` doesn't return any value so it
was always looping for the full timeout. Wrap it into a function
that confirms if both the module and device have been removed.
=> virtual_disks_multivms: fix disk discovery

libvirt/tests/cfg/virtual_network/elements_and_attributes/element_model.cfg, libvirt/tests/src/virtual_network/elements_and_attributes/element_model.py
On s390x, interfaces are not PCI devices per default. Don't check the pci model.
=> virtual_network/element_model: don't check pci model on s390x

libvirt/tests/cfg/guest_os_booting/boot_order/boot_with_multiple_boot_dev.cfg, libvirt/tests/src/guest_os_booting/boot_order/boot_with_multiple_boot_dev.py
Automate case: VIRT-297198 - Boot vm with more than one boot dev elements
=> guest_os_booting: add new case for multiple boot dev attributes

libvirt/tests/cfg/guest_os_booting/boot_order/boot_with_multiple_boot_order.cfg, libvirt/tests/src/guest_os_booting/boot_order/boot_with_multiple_boot_order.py
Automate case: VIRT-297237 - Boot vm with more than one devices with boot order elements
=> guest_os_booting: add new case for multiple boot order attributes

libvirt/tests/cfg/virtual_network/attach_detach_device/attach_iface_with_boot_order.cfg, libvirt/tests/src/virtual_network/attach_detach_device/attach_iface_with_boot_order.py
- VIRT-299227 - [attach-device][boot order] hotplug an interface with boot order
Test result:
```
(1/4) type_specific.io-github-autotest-libvirt.virtual_network.attach_detach_device.boot_order.vm_with_os_boot: PASS (35.51 s)
(2/4) type_specific.io-github-autotest-libvirt.virtual_network.attach_detach_device.boot_order.dup_boot_order: PASS (37.40 s)
(3/4) type_specific.io-github-autotest-libvirt.virtual_network.attach_detach_device.boot_order.neg_value: PASS (35.68 s)
(4/4) type_specific.io-github-autotest-libvirt.virtual_network.attach_detach_device.boot_order.str_value: PASS (35.87 s)
```
=> Add new case of attach interface with boot order

libvirt/tests/src/virtual_network/connectivity/connectivity_check_direct_interface.py, provider/virtual_network/network_base.py
Use host interface selection for host IP detection to enable testing on hosts with more than one NIC.
=> virtual_network/connectivity_check/direct_interface: select host interface

provider/virtual_network/passt.py
Depends on https://github.com/avocado-framework/avocado-vt/pull/3818
'passt.avx2' is a specialization only for x86_64.
On other architectures the process might just be "passt".
Change the regular expression to match any process containing
"passt".
`check_vm_ip` calculated the guest interface name for x86_64
for other architectures allow for configuration of this value.
Remove zone index when comparing routes as they might differ
between host and guest (e.g. if the interfaces are named differently).
Check gateways by confirming that routes in guest are available on
host instead of confirming they must be exactly the same on both ends.
Pass the target interface name to the check_connection function to
allow for the correct selection of the gateway. When a host
has two interfaces the …
=> provider//passt: add changes for multiarch

libvirt/tests/cfg/virtual_network/passt/passt_connectivity_between_2vms.cfg
No acpi on s390x and interfaces are named differently (qeth and virtio enc+devno).
=> passt/connection_between_2vms: fix config for s390x

libvirt/tests/cfg/virtual_network/passt/passt_reconnect.cfg, libvirt/tests/src/virtual_network/passt/passt_reconnect.py
Depèends on https://github.com/autotest/tp-libvirt/pull/5361
Depends on https://github.com/avocado-framework/avocado-vt/pull/3818
No ACPI on s390x and interfaces are named differently. Pass VM interface name to avoid auto-naming.
Pass Host interface name to restrict gateway selection.
=> passt/reconnect: fix on multi-arch

libvirt/tests/cfg/virtual_network/passt/passt_attach_detach.cfg, libvirt/tests/src/virtual_network/passt/passt_attach_detach.py
Depends on https://github.com/autotest/tp-libvirt/pull/5361
Depends on https://github.com/avocado-framework/avocado-vt/pull/3818
Update test cases to run tests on specific host interface. Fix parameters for s390x.
=> passt_attach_detach: fix for multi-arch

libvirt/tests/src/virsh_cmd/snapshot/virsh_snapshot_disk.py
In libvirt version lesser than 9.0.0 external snapshot deletion was unsupported, but the testcase is failing now with the error message as "Snapshot delete succeed but expect fail" because the deletion is supported now with external disk.
For reference : https://libvirt.org/news.html#v9-0-0-2023-01-16
Signed-off-by: Anushree Mathur <anushree.mathur@linux.vnet.ibm.com>
=> External snapshot deletion failure modification!

libvirt/tests/cfg/cpu/virsh_cpu_compare_xml.cfg, libvirt/tests/src/cpu/virsh_cpu_compare_xml.py
Test scenario:
Test 'virsh cpu-compare' with capabilities XML by obtaining capabilities XML from ‘virsh capabilities’ on host and updating with with different vendor
Case ID: xxx-139109
=> virsh_cpu_compare_xml: add case change cpu vendor

libvirt/tests/src/backingchain/blockcopy_options.py
The tests recorded the list of disks before and after attachment. However /dev/XdY names can change between boots leading to test errors.
=> backingchain/blockcopy_options: fix added disk discovery

libvirt/tests/cfg/virsh_cmd/domain/virsh_cpu_compare.cfg, libvirt/tests/cfg/virsh_cmd/domain/virsh_cpu_stats.cfg, libvirt/tests/cfg/virsh_cmd/domain/virsh_cpu_xml.cfg, libvirt/tests/cfg/virsh_cmd/domain/virsh_vcpuinfo.cfg
To avoid an issue caused by the unexpected ip_set warning in dmesg.
` (1/1) type_specific.io-github-autotest-libvirt.virsh.vcpuinfo.normal_test.name_option: ERROR: Failures occurred while postprocess:\n\n: Guest avocado-vt-vm1 dmesg verification failed: Found unexpected failures in guest dmesg log Please check guest dmesg log in debug log. (31.72 s)`
` (1/1) type_specific.io-github-autotest-libvirt.virsh.vcpuinfo.normal_test.name_option: PASS (9.74 s)
`
=> cpu: Disable host dmesg checks

libvirt/tests/cfg/memory/memory_devices/dimm_memory_with_auto_placement_numatune.cfg, libvirt/tests/src/memory/memory_devices/dimm_memory_with_auto_placement_numatune.py, libvirt/tests/src/memory/memory_devices/virtio_mem_auto_placement.py
xxxx-299044:Dimm memory device with auto placement numatune
x86+RHEL9
```
avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 memory.devices.dimm.auto_placement
(1/5) type_specific.io-github-autotest-libvirt.memory.devices.dimm.auto_placement.with_numa.strict: PASS (46.71 s)
(2/5) type_specific.io-github-autotest-libvirt.memory.devices.dimm.auto_placement.with_numa.interleave: PASS (53.31 s)
(3/5) type_specific.io-github-autotest-libvirt.memory.devices.dimm.auto_placement.with_numa.preferred: PASS (54.30 s)
(4/5) type_specific.io-github-autotest-libvirt.memory.devices.dimm.auto_placement.with_numa.restrictive: PASS (53.57 s)
(5/5) type_specific.io-github-autotest-libvirt.memory.devices.dimm.auto_placement.with_numa.undefined: …
```
=> add case for dimm memory with auto placement numatune

libvirt/tests/cfg/virtual_network/passt/passt_function.cfg, libvirt/tests/src/virtual_network/passt/passt_function.py
Depends on https://github.com/autotest/tp-libvirt/pull/5361
1. Configure values for s390x
2. Get IP addresses by host interface to avoid issues when there's more than one functional NIC.
3. Use the host_iface in several functions to make sure the right interface is tested.
4. The test needs to check the ports on the host not in the guest. Therefore, configure the host_iface.
=> passt/function: fix for multi-arch

v2v/tests/cfg/function_test_esx.cfg
Fix: Incorrect quotation marks cause the variable can't get the value.
v2v_opts = --key "VM_LUKS_PARTITION_EXAMPLE":clevis
=> v2v:fix functional failed TC "luks-partition"

libvirt/tests/cfg/memory/memory_allocation/lifecycle_with_memory_allocation.cfg, libvirt/tests/src/memory/memory_allocation/lifecycle_with_memory_allocation.py
update version for negative cases
Before fixed 
```
avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 memory.allocation.lifecycle.negative_test.with_maxmemory --vt-connect-uri qemu:///system
(1/1) type_specific.io-github-autotest-libvirt.memory.allocation.lifecycle.negative_test.with_maxmemory: FAIL: Expect should fail with one of At least one numa node has to be configured when enabling memory hotplug, but succeeded: Domain 'avocado-vt-vm1' defined from /tmp/xml_utils_temp_vpdb2syi.xml\n\n\n (10.87 s)
```
After fixed : rhel9+rhel8
```
avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 memory.allocation.lifecycle
(1/3) type_specific.io-github-autotest-libvirt.memory.allocation.lifecycle.positive_test.witho …
```
=> fix memory lifecycle memory allocation issue

libvirt/tests/src/migration_with_copy_storage/precreate_none_target_disk.py
Before:
TestFail: error: Storage pool not found: no storage pool with matching target path '/var/lib/libvirt/migrate'
After:
(1/1) type_specific.io-github-autotest-libvirt.migration_with_copy_storage.precreate_none_target_disk.copy_storage_all.raw_format.p2p: PASS (144.27 s)
=> migration: Fix no storage pool issue

libvirt/tests/cfg/memory/memory_devices/invalid_nvdimm_memory_device_config.cfg, libvirt/tests/src/memory/memory_devices/invalid_nvdimm_memory_device_config.py, provider/memory/memory_base.py
xxxx-299194: Invalid nvdimm memory device config values
Rhel9+x86 ,  RHEL8+x86: All passed
```
avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 memory.devices.invalid_nvdimm
(01/10) type_specific.io-github-autotest-libvirt.memory.devices.invalid_nvdimm.with_numa.exceed_slot: PASS (51.35 s)
(02/10) type_specific.io-github-autotest-libvirt.memory.devices.invalid_nvdimm.with_numa.max_addr: PASS (51.39 s)
(03/10) type_specific.io-github-autotest-libvirt.memory.devices.invalid_nvdimm.with_numa.unexisted_node: PASS (49.32 s)
(04/10) type_specific.io-github-autotest-libvirt.memory.devices.invalid_nvdimm.with_numa.unexisted_path: PASS (48.96 s)
(05/10) type_specific.io-github-autotest-libvirt.memory.devices.invalid_nvdimm.with_numa.in …
```
=> add case for invalid nvdimm config

libvirt/tests/cfg/backingchain/blockjob/blockjob_pivot_after_irregular_operations.cfg
Test result:
Before fixed:
`Expect should fail with one of ['not ready for pivot yet'], but failed with:error: invalid argument: disk vda does not have an active block job&#10;`
After fixed
```
avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 backingchain.blockjob.pivot.before_finish --vt-connect-uri qemu:///system
(1/1) type_specific.io-github-autotest-libvirt.backingchain.blockjob.pivot.before_finish: PASS (47.98 s)
```
=> fix blockcopy too fast to test

libvirt/tests/cfg/virsh_cmd/nodedev/virsh_nodedev_list.cfg, libvirt/tests/src/virsh_cmd/nodedev/virsh_nodedev_list.py, spell.ignore
Scm devices are only used in combination with z/OS.
Test result:
JOB ID     : eb5c2c18968651ed63b78547cc593b730cfa5251
JOB LOG    : /var/lib/avocado/job-results/job-2024-01-07T22.27-eb5c2c1/job.log
(1/1) type_specific.io-github-autotest-libvirt.virsh.nodedev_list.valid_option.non_acl.one_cap_option: PASS (5.18 s)
JOB HTML   : /var/lib/avocado/job-results/job-2024-01-07T22.27-eb5c2c1/results.html
JOB TIME   : 5.51 s
=> Ingnore scm devices on S390

libvirt/tests/src/daemon/conf_file/libvirtd_conf/set_audit_logging.py
`libvirt.check_logfile` will raise test failure if expectation unmet. However, the test code delivers more information, so let's not have it raise.
Also, remove the libvirtd.log file at the end of the test so that the next test won't read those log messages. The 'data_dir.get_tmp_dir' seemingly creates a tmp dir per job, that is, tests might share the same tmp_dir.
=> libvirtd_conf: improve test error

libvirt/tests/cfg/cpu/aarch64_gic_version.cfg, libvirt/tests/src/cpu/aarch64_gic_version.py, spell.ignore
**libvirt version-**
libvirtd (libvirt) 9.5.0
**Test result on arm:**
avocado run --vt-type libvirt --test-runner=runner --vt-machine-type arm64-mmio aarch64_gic_version --vt-connect-uri qemu:///system
JOB ID     : 49df7b433ffb40c46d99d0ed6d17d92a0e09fd37
JOB LOG    : /var/lib/avocado/job-results/job-2023-12-15T04.54-49df7b4/job.log
(1/3) type_specific.io-github-autotest-libvirt.aarch64_gic_version.positive_test.gic_version_3: PASS (38.80 s)
(2/3) …
=> Start vm with gic feature

libvirt/tests/src/memory/memory_backing/memory_source_and_allocation.py
The **size** property should be used to check the size of hugepage intead of **hugetlbsize**.
The feature owner has updated the  step 7 of case xxx-297914.
Before:
```
(1/2) type_specific.io-github-autotest-libvirt.memory.backing.source_and_allocation.memory_allocation.with_numa.immediate.hugepage.memfd: FAIL: Expect to get hugepage size '536870912', but got '2097152' (9.33 s)                                                                                                         
(2/2) type_specific.io-github-autotest-libvirt.memory.backing.source_and_allocation.memory_allocation.without_numa.immediate.hugepage.memfd: FAIL: Expect to get hugepage size '536870912', but got '2097152' (10.25 s)
```
After:
```
(1/2) type_specific.io-github-autotest-libvirt.memory.backing.source_and_allocation. …
```
=> memory: Fix property to correctly check hugepage size

provider/save/save_base.py
The uptime since value may be changed slightly for some reasons, so update to log a warning message to avoid stopping tests directly.
=> save: Update to log a warning messgae for uptime mismatch

libvirt/tests/src/timer_management.py, spell.ignore
Since RHEL8, the NTP protocol is implemented only by the chronyd daemon, which is enabled by default. Remove guest interface to prevent network connection, then guest will not sync time automatically to ntp server after boot. Otherwise, guest time will be synced to current real time regardless of guest configurations.
=> Remove existing interfaces when testing timer

libvirt/tests/src/libvirt_rng.py
In some low performance VM, relative big write operation will lead to dd timeout
=> Fix rng dd command timeout issue

libvirt/tests/src/virsh_cmd/domain/virsh_reboot.py
In some low performance guest, it takes more time to get uptime value
=> Fix get bootime timeout issue

libvirt/tests/src/virsh_cmd/nodedev/crypto_nodedev_create_destroy.py
Waiting for udevadm settle doesn't seem to make sure Libvirt has the latest device information.
Instead add a sleep. If this doesn't fix the brittleness we might want to restart virtqemud.
=> crypto_nodedev: improve reliability

libvirt/tests/src/virsh_cmd/domain/virsh_dump.py
Since linux command 'file <file_name>' version 5.44, the memory-only dump formats: 
kdump-zlib, kdump-lzo and kdump-snappy are taken as 'flattened kdump compressed 
dump'
Source: [file-command-flattened-kdump-compress](https://github.com/file/file/commit/65be19044894d012f66e20765a14fea1ee5af973)
In older 'file' version < 5.44 the same dump formats are taken as 'data'
This is leading to the failure of tests 11 and 28 in ras bucket
=> Fix virsh dump memory-only format kdump-* failure

libvirt/tests/cfg/memory/memory_tuning/memory_tuning_settings.cfg, libvirt/tests/src/memory/memory_tuning/memory_tuning_settings.py, spell.ignore
test result on rhel9.3:
(1/3) type_specific.io-github-autotest-libvirt.memory.tuning.normal: PASS (38.49 s)
(2/3) type_specific.io-github-autotest-libvirt.memory.tuning.zero: PASS (10.53 s)
(3/3) type_specific.io-github-autotest-libvirt.memory.tuning.minus: PASS (38.86 s)
JOB HTML   : /root/Code/avocado/avocado/mytest/job-results/job-2023-11-06T03.23-826d3c7/results.html
JOB TIME   : 89.55 s
test result on rhel8.9:
JOB LOG    : /root/Code/testbase/job-results/job-2023-11-06T03.15-59114db/job.log
(1/3) type_specific.io-github-autotest-libvirt.memory.tuning.normal: PASS (29.37 s)
(2/3) type_specific.io-github-autotest-libvirt.memory.tuning.zero: PASS (9.77 s)
(3/3) …
=> memory_tuning: add new case for memory tuning

provider/virtual_network/passt.py
There are some systems with multipath ipv6 route which passt can not recognize. Skip the ipv6 default route check on such system.
=> Skip the ipv6 default route check

libvirt/tests/cfg/storage/virsh_pool_autostart.cfg, libvirt/tests/src/storage/virsh_pool.py, libvirt/tests/src/storage/virsh_pool_autostart.py
VIRT-300253: Logical pool lifecycle from empty vg and restart service. Also because the status of logical pool will keep active after restarting the service. So update another case together.
=> storage: add case for logical pool lifecycle from empty vg

libvirt/tests/src/virsh_cmd/domain/virsh_blkdeviotune.py
The test case needs the output from 'blkdeviotune' on the disk in order to compare it with the XML values.
It was trying to compare with an empty dictionary because the result was empty with an error that was ignored.
Don't continue the test if the block I/O throttle parameters cannot be retrieved. This will show a test error indicating this.
=> blkdeviotune: improve test log

libvirt/tests/src/virtual_network/virtual_network_multivms.py
The guest ip addr may not be obtained within 1 second, extend the timeout to 5.
Before:
```
(1/1) type_specific.io-github-autotest-libvirt.virtual_network.multivms.port_isolated.iface.set_iface.with_net.set_one:  ERROR: Got vm avocado-vt-vm1 ip as None! (129.72 s)
```
After:
```
(1/1) type_specific.io-github-autotest-libvirt.virtual_network.multivms.port_isolated.iface.set_iface.with_net.set_one:  PASS (178.31 s)
```
=> virtual_networks: Extend the timeout for obtaining guest IP

libvirt/tests/cfg/virtual_network/update_device/update_port_isolated.cfg, libvirt/tests/src/virtual_network/update_device/update_port_isolated.py, spell.ignore
- VIRT-294993 - [update-device][port_isolated] live update the port isolated attribute
Test result:
```
(1/6) type_specific.io-github-autotest-libvirt.virtual_network.update_device.port_isolated.default_to_yes.nat_network: PASS (180.33 s)
(2/6) type_specific.io-github-autotest-libvirt.virtual_network.update_device.port_isolated.default_to_yes.linux_br: PASS (171.90 s)
(3/6) type_specific.io-github-autotest-libvirt.virtual_network.update_device.port_isolated.yes_to_no.nat_network: PASS (176.57 s)
(4/6) type_specific.io-github-autotest-libvirt.virtual_network.update_device.port_isolated.yes_to_no.linux_br: PASS (145.68 s)
(5/6) type_specific.io-github-autotest-libvirt.virtual_network.update_device.port_isolated.yes_to_default.nat_network: PASS (176.58 s)
(6/6) …
```
=> Add network case of update device:port isolated

libvirt/tests/src/numa/numa_memory_spread.py
Sometimes memhog fails to eat a big value of memory. In order to make case stable, we decrese the value again.
=> numa_memory_spread: smaller memhog value

libvirt/tests/src/virtual_network/connectivity/connectivity_check_mcast_interface.py
replace() here will cut "xxx.xxx.122.122" to "xxx.xxx" which is not expected.
Before:
```
(1/1) type_specific.io-github-autotest-libvirt.virtual_network.connectivity_check.mcast_interface.default:  FAIL: omping should fail with remote vm firewalld on (76.35 s)
```
After:
```
(1/1) type_specific.io-github-autotest-libvirt.virtual_network.connectivity_check.mcast_interface.default: PASS (99.06 s
```
=> virtual_networks: Fix the cutting of ip addr
