autotest/tp-libvirt

libvirt/tests/cfg/sriov/vIOMMU/attach_iommu_device.cfg, libvirt/tests/src/sriov/vIOMMU/attach_iommu_device.py
This PR adds:
VIRT-294818 - Hotplug or coldplug iommu device to guest
```
(1/8) type_specific.io-github-autotest-libvirt.vIOMMU.attach_iommu_device.cold_plug.virtio: PASS (8.70 s)
(2/8) type_specific.io-github-autotest-libvirt.vIOMMU.attach_iommu_device.cold_plug.intel: PASS (8.61 s)
(3/8) type_specific.io-github-autotest-libvirt.vIOMMU.attach_iommu_device.hot_plug.virtio: PASS (47.83 s)
(4/8) type_specific.io-github-autotest-libvirt.vIOMMU.attach_iommu_device.hot_plug.intel: PASS (44.33 s)
```
=> vIOMMU: Add a case of attach iommu device

libvirt/tests/cfg/sriov/vIOMMU/intel_iommu_without_enabling_caching_mode.cfg, libvirt/tests/src/sriov/vIOMMU/intel_iommu_without_enabling_caching_mode.py
This PR adds:
VIRT-294734 - Check libvirt will prompt error when intel
iommu device with hostdev interface/device but no
caching_mode=on
```
(5/8) type_specific.io-github-autotest-libvirt.vIOMMU.intel_iommu.without_enabling_caching_mode.cold_plug.hostdev_interface: PASS (29.05 s)
(6/8) type_specific.io-github-autotest-libvirt.vIOMMU.intel_iommu.without_enabling_caching_mode.cold_plug.hostdev_device:PASS (27.94 s)
(7/8) type_specific.io-github-autotest-libvirt.vIOMMU.intel_iommu.without_enabling_caching_mode.hot_plug.hostdev_interface: PASS (64.35 s)
(8/8) type_specific.io-github-autotest-libvirt.vIOMMU.intel_iommu.without_enabling_caching_mode.hot_plug.hostdev_device: PASS (62.54 s)
```
=> vIOMMU: Add a case about intel iommu

libvirt/tests/src/backingchain/virsh_domblk/domblkthreshold_with_backingchain_element.py
Give hard wait after creating snaps
Catch inappropriate error
Before fixed
```
avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 backingchain.virsh_domblk.entire_disk --vt-connect-uri qemu:///system
(1/1) type_specific.io-github-autotest-libvirt.backingchain.virsh_domblk.entire_disk: FAIL: Not get correct threshold: block.*.threshold=1 should be in Domain: 'avocado-vt-vm1'\n  state.state=1\n  state.reason=1\n  cpu.time=41739024000\n  cpu.user=35797449000\n  cpu.system=5941575000\n  cpu.cache.monitor.count=0\n  cpu.haltpoll.success.time=96832680\n  ... (56.38 s)
```
After fixed
```
avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 backingchain.virsh_domblk.entire_disk --vt-connect-uri qemu:///system
(1/1) …
```
=> fix not found threshold value

libvirt/tests/src/virtual_disks/virtual_disks_multidisks.py
Depends on https://github.com/avocado-framework/avocado-vt/pull/3840
426de63d8bb0d608c72a3d2f22d918f0c4604391 fixed the disk discovery for most tests. However, the block size check still used the target device names and therefore sometimes failed.
Use the function to discover new disks from within the VM.
=> virtual_disk/multidisks: fix disk discovery

libvirt/tests/src/event/virsh_event.py
The test identified new disks by their target name. However, a reboot can mess up the non-persistent disk namings /dev/vdX.
=> virsh_event: fix disk discovery

libvirt/tests/src/virsh_cmd/domain/virsh_domxml_from_native.py
From python3.7, using '\s' leads to **re ERROR**
In python3.6 and below, the same was treated as DeprecationWarning
Hence replacing '\s' in the code simply with ' ' will work
Source: [github-python/cpython-issues#27030](https://github.com/python/cpython/commit/9bd85b83f66d31e39282244e455275bd9cd91bb1#diff-a0fc71db3d118bcf5fa27a2eb5d4e9c5)
Source: [stack-overflow-bad-escape](https://stackoverflow.com/questions/58328587/python-3-7-4-re-error-bad-escape-s-at-position-0)
=> Fix Error: bad escape \\s at position 0

libvirt/tests/cfg/guest_kernel_debugging/nmi_test.cfg, libvirt/tests/src/guest_kernel_debugging/nmi_test.py
On s390x the inject NMI behavior is different to other archs: It panics and if kdump is configured the kernel will be dumped and the guest reboots.
Both will result in the NMI inject count 0.
A second quick injection will result in a panic because kdump is not up yet.
Skip the qemu-monitor command, only check the libvirt command.
=> nmi_test: disable second inject for s390x

libvirt/tests/src/storage/virsh_pool.py
The logical pool will be active from libvirt-9.9.0 after restarting service. So it need have different results before and after this version. This PR mainly fix the left issue which is not considered before.
=> Storage: fix different results after restarting service for logical pool

libvirt/tests/src/virsh_cmd/domain/virsh_emulatorpin.py
The test case is valuable even if the number of host cpus is not a multiple of 8 which is a special subcase of issue reported in https://bugzilla.redhat.com/show_bug.cgi?id=1227180
Instead of skipping if this is not a case run it still.
We'll have an internal test doc to document the behavior in case of multiple of 8.
=> emulatorpin: enable test case always

v2v/tests/cfg/convert_from_file.cfg
Fix the failed TC:
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/libvirt/images/v2v/ova-images/esx6_7-rhel8.3-x86_64.ova'&#10;
=> v2v:fix cpu-topology TC

v2v/tests/cfg/function_test_esx.cfg
Enabling virtio
"Virtio" is the name for a set of drivers which make disk (block device), network and other guest operations work much faster on KVM.
=> v2v:fix func TC "unset virtio-win"

libvirt/tests/src/virsh_cmd/domain/virsh_attach_detach_interface.py
On a host with VLAN the parent device is in operstate UP and was selected for the test making it fail because the VLAN interface should be used.
Require interface to have an IP for selection.
=> at_dt_interface: fix test on hosts with vlan

libvirt/tests/src/virtual_network/passt/passt_attach_detach.py, libvirt/tests/src/virtual_network/passt/passt_function.py, libvirt/tests/src/virtual_network/passt/passt_reconnect.py, libvirt/tests/src/virtual_network/passt/passt_transfer_file.py, provider/virtual_network/passt.py
The default gateway function in utils_net now will return None when it detects ipv6 multipath.
Update the provider code to fail the test if this is the case. If not, the test case will fail with "NoneType" object has no attribute 'split'".
Also, pass the host interface to be tested to have more control.
=> passt: fix check_default_gw

libvirt/tests/cfg/memory/memory_devices/dimm_memory_with_access_and_discard.cfg, libvirt/tests/src/memory/memory_devices/dimm_memory_with_access_and_discard.py
xxxx-299048:Dimm memory device with access and discard settings
x86+rhel9 & rhel8
```
avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 memory.devices.dimm.access_and_discard
(1/9) type_specific.io-github-autotest-libvirt.memory.devices.dimm.access_and_discard.with_numa.undefined.file: PASS (131.14 s)
(2/9) type_specific.io-github-autotest-libvirt.memory.devices.dimm.access_and_discard.with_numa.undefined.anonymous: PASS (130.06 s)
(3/9) type_specific.io-github-autotest-libvirt.memory.devices.dimm.access_and_discard.with_numa.undefined.memfd: PASS (127.07 s)
(4/9) type_specific.io-github-autotest-libvirt.memory.devices.dimm.access_and_discard.with_numa.shared_and_discard.file: PASS (130.73 s)
(5/9) …
```
=> add case for dimm memory with access and discard setting

libvirt/tests/cfg/virtual_network/attach_detach_device/attach_iface_with_boot_order.cfg
The error messages for the negative tests are different on xxxx-8 and xxxx-9:
On xxxx-8: XML error: Invalid value for attribute 'order' in element 'boot': '-1'. Expected integer value
On xxxx-9: XML error: Invalid value for attribute 'order' in element 'boot': '-1'. Expected non-negative integer value
Test result on xxxx-8:
```
(1/1) type_specific.io-github-autotest-libvirt.virtual_network.attach_detach_device.boot_order.neg_value: PASS (24.13 s)
```
Test result on xxxx-9:
```
(1/1) type_specific.io-github-autotest-libvirt.virtual_network.attach_detach_device.boot_order.neg_value: PASS (32.42 s)
```
=> virtual_networks: Update error message to match more distros

libvirt/tests/src/backingchain/virtual_disks_snapshot_blockpull.py
The test identified new disks by their target name. However, a reboot can mess up the non-persistent disk namings /dev/vdX.
=> backingchain/snapshot_blockpull: fix disk disovery

libvirt/tests/cfg/memory/nvdimm.cfg, libvirt/tests/src/memory/nvdimm.py
The cpu mode is host-passthrough for arm.
Internal snapshots of a VM with pflash based firmware are not supported on arm, so skip this check on arm
The following is the test result on arm, the failed two cases are because arm does not support and they have been skipped in libvirt-ci:
```
(1/6) type_specific.io-github-autotest-libvirt.nvdimm.back_file.label.default: PASS (89.60 s)
(2/6) type_specific.io-github-autotest-libvirt.nvdimm.back_file.label.check_life_cycle: PASS (107.47 s)
(3/6) type_specific.io-github-autotest-libvirt.nvdimm.back_file.label.discard: PASS (10.98 s)
(4/6) type_specific.io-github-autotest-libvirt.nvdimm.back_file.label.pmem_alignsize: ERROR: Command '/usr/bin/virsh start avocado-vt-vm1 ' failed.\nstdout: b'\n'\nstderr: b"error: Failed to start domain …
```
=> memory_nvdimm: Fix cpu mode to enable test for aarch64

libvirt/tests/cfg/memory/virsh_setmem.cfg, libvirt/tests/src/memory/virsh_setmem.py
The previous guest memory setting was 2G, but the half memory test would fail because 1G was not enough to maintain the normal operation of the guest.
Before:
```
(1/1) type_specific.io-github-autotest-libvirt.virsh.setmem.valid_options.running.half_mem.domid.dom_opt_size_opt.no_cmd_flag: ERROR: Login timeout expired    (output: "exceeded 240 s timeout, last failure: Login timeout expired    (output: '')") (419.32 s)
```
After:
```
(1/1) type_specific.io-github-autotest-libvirt.virsh.setmem.valid_options.running.half_mem.domid.dom_opt_size_opt.no_cmd_flag: PASS (72.23 s)
```
=> memory: Increase guest memory to 4G

libvirt/tests/src/save_and_restore/save_to_nfs.py
In some extreme case, folder:nfs_mount_dir may already exist before mkdir()
=> Fix folder exist issue on save_to_nfs

libvirt/tests/cfg/cpu/vcpu_misc.cfg
- change cpu mode
- no vendor information on arm now
- maxphysaddr is not supported on arm
=> vcpu_misc: fix cpu model for arm

libvirt/tests/cfg/controller/controller_functional.cfg
- Add alias for some pcie related controllers and check in qemu command line.
- Enable some cases on arm
=> controller_functional: add alias case

libvirt/tests/cfg/guest_agent/unix_source_path/agent_auto_generated_unix_source_path_session_mode.cfg, libvirt/tests/src/guest_agent/unix_source_path/agent_auto_generated_unix_source_path_session_mode.py
This PR adds:
VIRT-300125: Start a guest without specified source path for guest agent
Depends:
- https://github.com/avocado-framework/avocado-vt/pull/3845
` (1/1) type_specific.io-github-autotest-libvirt.agent.auto_generated.unix_source_path.session_mode: PASS (86.10 s)
`
=> guest_agent: Add a case of session mode

libvirt/tests/src/virtual_network/iface_network.py
iptables-libs changes it's output (at least on s390x) for empty fields:
```
MASQUERADE  tcp      2001:db8:ca2:6::/64 !2001:db8:ca2:6::/64  masq
ports: 1024-65535
MASQUERADE  tcp  --  2001:db8:ca2:6::/64 !2001:db8:ca2:6::/64  masq
ports: 1024-65535
```
Update the regular expression to reflect this.
=> virtual_network/iface_network: fix rule expectation format

libvirt/tests/src/numa/guest_numa_node_tuning/host_guest_mixed_memory_binding.py
If the memory mode and memnode mode are not set, It is unpredictable on which host numa node a guest numa cell will be allocated. So all the host numa nodes should be checked.
The current test only considers the case where the host has two numa nodes. This patch fixes this issue.
Result:
```
FAIL 1-type_specific.io-github-autotest-libvirt.guest_numa_node_tuning.host_guest_mixed_memory_binding.memnode_mode_preferred.no_mem_mode.multiple_nodes -> TestFail: Expect N0 + N1 > 0, but found not
```
Debug log:
```
2023-12-21 04:16:23,407 process          L0658 INFO | Running 'grep -B1 1024000 /proc/`pidof qemu-kvm`/smaps'
2023-12-21 04:16:23,470 process          L0470 DEBUG| [stdout] ffff1d400000-ffff5bc00000 rw-p 00000000 00:00 0 
2023-12-21 04:16:23,471 process          L0740 INFO | Command …
```
=> numa: Fix the check of guest numa cell allaction

libvirt/tests/cfg/memory/virsh_setmem.cfg, libvirt/tests/src/memory/virsh_setmem.py
Fix setmem failure on s390x
Previously fixing by increasing memory doesn't apply on s390x ,which leads to some error:test conditions not met: Inside memory deviated
=> Fix setmem failure on s390x

libvirt/tests/cfg/libvirt_rng.cfg, libvirt/tests/src/libvirt_rng.py
Before commit 40b1324887851acc3abc1c88bc250faea279b032 dd read and wrote 512 bytes at a time (bs default), 100 times. This led to a total size of 51200 bytes = 0.512 KB = 0.000512 MB.
The commit set instead 1M = 1MB to be written and read at a time, 10 times. This would result in a total size of 10 MB which seems to be a typo because 10 MB are 10 000 000 bytes and the set rate limit is 2500 bytes per second in the rng_rate test cases; the test would most definitely timeout because 'dd' will need at least 4000 seconds, that is, more than 1 hr, to finish.
Because of this commit we now experience timeouts on VM that performed well, so revert it.
If there are timeouts with the original command, it is likely because the backends don't create enough entropy. Making sure that rngd is running on …
=> libvirt_rng: revert commit to avoid timeouts

libvirt/tests/src/storage/virsh_pool_autostart.py
```
avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 virsh.pool_autostart.positive_test.name_option.pool_type_iscsi.destroy_pool_used_by_guest --vt-connect-uri qemu:///system
(1/1) type_specific.io-github-autotest-libvirt.virsh.pool_autostart.positive_test.name_option.pool_type_iscsi.destroy_pool_used_by_guest: PASS (111.24 s)
```
=> fix storage case inappropriate message

libvirt/tests/cfg/virtual_network/lifecycle/lifecycle_vdpa_interface.cfg, libvirt/tests/src/virtual_network/lifecycle/lifecycle_vdpa_interface.py
Update code to check libvirt version for saving/restore the VM with vDPA
```
(1/2) type_specific.io-github-autotest-libvirt.virtual_network.lifecycle.vdpa_interface.default.simulator: PASS (121.44 s)
(2/2) type_specific.io-github-autotest-libvirt.virtual_network.lifecycle.vdpa_interface.default.mellanox: PASS (132.18 s)
```
=> vDPA: Add libvirt version check for save/restore

libvirt/tests/cfg/memory/gmap.cfg, libvirt/tests/src/memory/gmap.py
KVM records shadow memory events for a nested guest. Confirm the counters go up.
=> memory/gmap: add test for shadow memory counters

libvirt/tests/cfg/libvirt_rng.cfg
When count is too small, the rng rate can not control accuratly. 
So we tune it bigger to make the case stable.
=> libvirt_rng: fix unstable dd count

libvirt/tests/src/libvirt_rng.py
When aexpect.exceptions.ShellTimeoutError is raised and the case is rng_rate, the UnboundLocalError: local variable 'output' referenced before assignment will be reported.
Because when the timeout happens, the dd rate will not be reported in dd cmdline, it has no way to calc the rate. So it's reasonable to fail the test when timeout happens.
=> libvirt_rng: fix variable 'output' referenced before assignment

libvirt/tests/cfg/guest_kernel_debugging/virsh_dump.cfg, libvirt/tests/src/guest_kernel_debugging/virsh_dump.py
VMs should keep running if dumping them fails because there's no space.
=> virsh_dump: add new case when no space left

libvirt/tests/src/numa/guest_numa_node_tuning/host_guest_mixed_memory_binding.py
Fix parsing of more than two consecutive numa nodes.
Before fixing, [0, 1, 2, 3] --> "0-1"
After fixing, [0, 1, 2, 3] --> "0-3"
Depend on:
- https://github.com/avocado-framework/avocado-vt/pull/3804
Test Results:
Before:
```
(01/11) type_specific.io-github-autotest-libvirt.guest_numa_node_tuning.host_guest_mixed_memory_binding.memnode_mode_strict.mem_mode_strict.single_node: PASS (12.85 s)                                                                                                                                                     
(02/11) type_specific.io-github-autotest-libvirt.guest_numa_node_tuning.host_guest_mixed_memory_binding.memnode_mode_strict.mem_mode_strict.multiple_nodes: PASS (60.44 s) …
```
=> numa: Fix parsing of more than two consecutive numa nodes

libvirt/tests/src/virtual_disks/virtual_disks_transient_disk.py
The second VM disk command reused the first one which could lead to the wrong disk name being used:
"/dev/vda is apparently in use by the system; will not make a filesystem here!"
Make sure to discover the disk again for the second VM.
=> virtual_disk/transient_disk: fix disk discovery for VM1

libvirt/tests/cfg/memory/memory_devices/lifecycle_for_file_backed_nvdimm_memory.cfg, libvirt/tests/src/memory/memory_devices/lifecycle_for_file_backed_nvdimm_memory.py, provider/memory/memory_base.py
VIRT-299192: Life cycle of file backed nvdimm memory device
x86+rhel9
```
avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 memory.devices.file_nvdimm.lifecycle
(1/8) type_specific.io-github-autotest-libvirt.memory.devices.file_nvdimm.lifecycle.with_numa.addr_undefined.target_label.access_shared: PASS (258.50 s)
(2/8) type_specific.io-github-autotest-libvirt.memory.devices.file_nvdimm.lifecycle.with_numa.addr_undefined.target_label.access_private_alignsize: PASS (176.22 s)
(3/8) type_specific.io-github-autotest-libvirt.memory.devices.file_nvdimm.lifecycle.with_numa.addr_undefined.target_readonly.access_shared: PASS (299.23 s)
(4/8) type_specific.io-github-autotest-libvirt.memory.devices.file_nvdimm.lifecycle.with_numa.addr_unde …
```
=> add case for file backed nvdimm memory lifecycle

libvirt/tests/cfg/memory/hmat.cfg
test results on aarch64:
(1/2) type_specific.io-github-autotest-libvirt.hmat.hmat: PASS (31.32 s)
(2/2) type_specific.io-github-autotest-libvirt.hmat.cell_distances: PASS (31.33 s)
=> Change cpu mode to host-passthrough for aarch64

libvirt/tests/cfg/virtual_network/update_device/unsupported_live_update_add.cfg, libvirt/tests/cfg/virtual_network/update_device/unsupported_live_update_alter.cfg, libvirt/tests/cfg/virtual_network/update_device/unsupported_live_update_delete.cfg
On s390x, ROM and ACPI are not available. Don't run these tests.
=> virtual_network/update_device: don't test rom and acpi

libvirt/tests/deps/negative_domcapabilities_s390x.xml
'ctop' has become part of host feature list with QEMU 8.2. Therefore the negative test with hypervisor-cpu-compare failed. Add another feature that's not part of host cpu feature list as returned by domcapabilities.
To find this kind of condition: list all recognized features with qemu-kvm -cpu ?. Then get domcapabilities and check for features that are not listed there.
=> cpu_xml: fix negative case with missing feature

libvirt/tests/src/virsh_cmd/domain/virsh_edit.py
Sometimes the test failed with right command, no additional info. Add some additional logs to help debugging the next time it happens.
=> virsh_edit: add logs

libvirt/tests/cfg/virtual_network/elements_and_attributes/element_mac_specific_addr.cfg, libvirt/tests/src/virtual_network/elements_and_attributes/element_mac_specific_addr.py
- VIRT-296221 - [mac] Start vm or hotplug interface with specific mac address
Test result:
```
(01/12) type_specific.io-github-autotest-libvirt.virtual_network.elements_and_attributes.mac.specific_addr.default.pre_set:PASS (81.23 s)
(02/12) type_specific.io-github-autotest-libvirt.virtual_network.elements_and_attributes.mac.specific_addr.default.hotplug:PASS (82.21 s)
(03/12) type_specific.io-github-autotest-libvirt.virtual_network.elements_and_attributes.mac.specific_addr.starts_with_0xfe.pre_set: PASS (52.19 s)
(04/12) type_specific.io-github-autotest-libvirt.virtual_network.elements_and_attributes.mac.specific_addr.starts_with_0xfe.hotplug: PASS (47.32 s)
(05/12) type_specific.io-github-autotest-libvirt.virtual_network.elements_and_attributes.mac.specific_addr.all_zeros.pre_set: PASS …
```
=> Add new case of start vm with specific mac address

libvirt/tests/cfg/snapshot/memory_snapshot_delete.cfg
xxxx-298190:delete memory only snapshot
(1/2) type_specific.io-github-autotest-libvirt.memory_snapshot.delete.paused.qcow2: PASS (98.62 s)
(2/2) type_specific.io-github-autotest-libvirt.memory_snapshot.delete.running.qcow2: PASS (55.64 s)
=> update version for memory only snap case

libvirt/tests/cfg/sriov/vIOMMU/iommu_device_lifecycle.cfg, libvirt/tests/src/sriov/vIOMMU/iommu_device_lifecycle.py, provider/save/save_base.py
This PR adds:
VIRT-294807 - [vIOMMU] Lifecycle test for vm with iommu device
**Test results:** some cases are failed due to known issues.
```
(01/14) type_specific.io-github-autotest-libvirt.vIOMMU.iommu_device_lifecycle.save_restore.e1000e.virtio: ERROR: Command '/bin/virsh restore /var/tmp/avocado-vt-vm1_Qdi.save ' failed.\nstdout: b'\n'\nstderr: b'error: Failed to restore domain from /var/tmp/avocado-vt-vm1_Qdi.save\nerror: operation failed: domain is not running\n'\nadditional_info: None (61.83 s)
(02/14) type_specific.io-github-autotest-libvirt.vIOMMU.iommu_device_lifecycle.save_restore.e1000e.intel: PASS (252.06 s)
(03/14) type_specific.io-github-autotest-libvirt.vIOMMU.iommu_device_lifecycle.save_restore.virtio_muti_devices.vhost_on.virtio: ERROR: Command '/bin/virsh restore …
```
=> vIOMMU: Add a vm lifecycle test

libvirt/tests/src/virsh_cmd/domain/virsh_domfstrim.py
The guest agent won't be able to fstrim successfully if selinux
is present and enforcing. Set the SELinux boolean persistently
to enable access by the guest agent.
=> domfstrim: grant guest agent SELinux permissions 

libvirt/tests/src/virsh_cmd/domain/virsh_attach_device_matrix.py
Fix attach-detach disk failure
libvirt.create_disk_xml() return embedded object xml, and the parent object: disk_xml may be gc quickly because there is no reference to it
libvirt_disk.create_primitive_disk_xml() return disk_xml itself, since it is assigned to one variable and the reference count is not zero, so it is not gced soon.
=> Fix attach-detach disk failure

libvirt/tests/cfg/cpu/topology.cfg, libvirt/tests/src/cpu/topology.py
Add new test case. There are some tests under guestpin but they are mostly PPC specific.
This test was added for minimal coverage of newly introduced s390x guest topology on qemu level but libvirt level currently is still missing full support.
We can add more tests in this script (e.g. pin cpu, coldplug, lifecycle) later.
=> cpu/topology: add topology hotplug test

libvirt/tests/src/sriov/plug_unplug/sriov_attach_detach_interface_special_situations.py
The module list needs to update on some drivers, so update to remove 'vfio' module directly.
```
(1/4) type_specific.io-github-autotest-libvirt.sriov.plug_unplug.attach_detach_interface_special_situations.no_detach_for_no_managed: PASS (107.27 s)
(2/4) type_specific.io-github-autotest-libvirt.sriov.plug_unplug.attach_detach_interface_special_situations.with_model: PASS (123.06 s)
(3/4) type_specific.io-github-autotest-libvirt.sriov.plug_unplug.attach_detach_interface_special_situations.module_auto_reload: PASS (122.50 s)
(4/4) type_specific.io-github-autotest-libvirt.sriov.plug_unplug.attach_detach_interface_special_situations.to_vm_with_hostdev_ifaces: PASS (162.55 s)
```
=> sriov: Update to remove vfio module

libvirt/tests/cfg/libvirt_mem.cfg, libvirt/tests/cfg/memory/memory_misc.cfg
Test results:
(1/1) type_specific.io-github-autotest-libvirt.libvirt_mem.negative_test.attach_error.attach_nonexist_node: PASS (42.67 s)
(1/1) type_specific.io-github-autotest-libvirt.memory_misc.audit_size.at_dt_mem: PASS (39.59 s)
=> Increase current memory to avoid guest boot failure for short of memory

libvirt/tests/src/virsh_cmd/snapshot/virsh_snapshot_disk.py
Sometimes tests in CI fail with
"""
error: XML error: memory state cannot be saved with offline or disk-only snapshot.
"""
but I cannot reproduce it.
I assume the VM is not in the correct state as disk-only snasphot is not requested in the test case.
Log the VM state before running the snapshot-create command to check it next time the issue arises.
=> virsh_snapshot_disk: log vm state

libvirt/tests/cfg/incremental_backup/incremental_backup_push_mode.cfg
Now the written size in guest is big that it may cause timeout sometimes: Timeout expired while waiting for shell command to complete: 'dd if=/dev/urandom of=/dev/vdb bs=1M seek=10 count=4000; sync'. This PR mainly reduce the size.
=> incremental_backup: fix timeout issue of dd commands in guest

libvirt/tests/src/virtual_disks/at_dt_iscsi_disk.py
The code found new disks by their target name, e.g. 'vdX'. Those names can change between reboots.
Instead, use function to identify new disks that don't mount the root file system.
The function raises an error if there is no such disk, so handle that to confirm that disks are detached correctly.
=> at_dt_iscsi_disk: fix disk_discovery

provider/virtual_network/passt.py
Some systems has ipv6 multipath route which will cause the passt check fail since passt can not recognize the format of it. Skip this check.
=> Skip ipv6 default route check with multipath route

libvirt/tests/src/daemon/conf_file/qemu_conf/set_virtlogd.py
Expand the search scope to find expected message.
Test result:
```
(1/5) type_specific.io-github-autotest-libvirt.conf_file.qemu_conf.set_virtlogd.positive_test.default: PASS (83.68 s)
(2/5) type_specific.io-github-autotest-libvirt.conf_file.qemu_conf.set_virtlogd.positive_test.enable_logd: PASS (83.88 s)
(3/5) type_specific.io-github-autotest-libvirt.conf_file.qemu_conf.set_virtlogd.positive_test.file_handler: PASS (78.99 s)
(4/5) type_specific.io-github-autotest-libvirt.conf_file.qemu_conf.set_virtlogd.positive_test.restart: PASS (85.52 s)
(5/5) type_specific.io-github-autotest-libvirt.conf_file.qemu_conf.set_virtlogd.positive_test.stop_libvirtd: PASS (84.62 s)
RESULTS    : PASS 5 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
```
Before:
```
TestFail: Failed to get VM …
```
=> Fixup:cannot find message in log

libvirt/tests/src/virtio/virtio_page_per_vq.py
The line of vm login is not to create a session, but to wait for vm to bootup. Therefore replace it with serial login to solve the problem.
Test result:
PASS 1-type_specific.io-github-autotest-libvirt.virtio_attributes.virtio_page_per_vq.interface.hotplug
Before:
VMIPAddressMissingError: No ipv4 DHCP lease for MAC 52:54:00:68:e8:d1
=> Fixup: login timeout of virtio_page_per_vq test

libvirt/tests/cfg/serial/serial_functional.cfg
On arrch64, system-serial is supported.
=> Serial: Add a case for testing system-serial on aarch64

libvirt/tests/cfg/virtual_network/elements_and_attributes/element_mac_specific_addr.cfg, libvirt/tests/src/virtual_network/elements_and_attributes/element_mac_specific_addr.py
Since the issue is fixed on libvirt-9.9.0, add the version check for interface with all zeros mac.
=> Add version check for interface with all zeros mac

libvirt/tests/cfg/memory/memory_backing/lifecycle_for_hugepage.cfg, libvirt/tests/src/memory/memory_backing/lifecycle_for_hugepage.py, libvirt/tests/src/numa/guest_numa_topology/numa_topology_with_hugepage.py, provider/numa/numa_base.py
Enable different hugepages supported on ARM.
4k kernel: 2M, 1G, 32M, 64K
64k kernel: 512M, 2M, 16G
=> lifecycle_for_hugepage: update for arm hugepage

libvirt/tests/cfg/sriov/vIOMMU/intel_iommu_without_ioapic.cfg, libvirt/tests/src/sriov/vIOMMU/intel_iommu_without_ioapic.py
This case adds:
VIRT-300349 - [iommu][intel] Define VM with intel iommu but
no <ioapic driver='qemu'/> defined
` (1/1) type_specific.io-github-autotest-libvirt.vIOMMU.intel_iommu.without_ioapic: PASS (148.39 s)
`
=> vIOMMU: Add a case of intel iommu

libvirt/tests/cfg/libvirt_mem.cfg, libvirt/tests/src/libvirt_mem.py
aarch64 64k result：
(01/27) type_specific.io-github-autotest-libvirt.libvirt_mem.positive_test.with_source: PASS (67.53 s)
(02/27) type_specific.io-github-autotest-libvirt.libvirt_mem.positive_test.hugepages.no_numatune.hot_plug: PASS (107.45 s)
(03/27) type_specific.io-github-autotest-libvirt.libvirt_mem.positive_test.hugepages.no_numatune.hot_unplug: PASS (107.14 s)
(04/27) type_specific.io-github-autotest-libvirt.libvirt_mem.positive_test.hugepages.no_numatune.cold_plug: PASS (76.40 s)
(05/27) type_specific.io-github-autotest-libvirt.libvirt_mem.positive_test.hugepages.no_numatune.cold_plug_discard: PASS (76.40 s)
(06/27) type_specific.io-github-autotest-libvirt.libvirt_mem.positive_test.hugepages.no_numatune.discard: PASS (110.34 s)
(07/27) …
=> libvirt_mem add adaption for aarch64

libvirt/tests/cfg/memory/memory_devices/lifecycle_of_mixed_memory_devices.cfg, libvirt/tests/src/memory/memory_devices/lifecycle_of_mixed_memory_devices.py
Test result on aarch64 64k:
(1/1) type_specific.io-github-autotest-libvirt.memory.devices.lifecycle.mutiple_mem: PASS (147.81 s)
Test result on x86_64:
(1/1) type_specific.io-github-autotest-libvirt.memory.devices.lifecycle.mutiple_mem: PASS (155.30 s)
=> Change huge page assignment automatically to adapt for aarch64.

libvirt/tests/cfg/numa/host_numa/host_numa_info.cfg, libvirt/tests/src/numa/host_numa/host_numa_info.py
There are relatively few arm machines with 2 numa nodes that can allocate 16G large pages, so the test for 16G hugepage memory was adjusted to the machine with one numa node.
Test results on one numa node ARM machine:
```
(1/2) type_specific.io-github-autotest-libvirt.host_numa.numa_info.default: CANCEL: Expect 2 numa nodes at least, but found 1 (9.33 s)
(2/2) type_specific.io-github-autotest-libvirt.host_numa.numa_info.16G: PASS (39.34 s)
```
Test results on two numa nodes ARM machine:
```
(1/2) type_specific.io-github-autotest-libvirt.host_numa.numa_info.default: PASS (28.98 s)
(2/2) type_specific.io-github-autotest-libvirt.host_numa.numa_info.16G: CANCEL: Can not set at least one page with pagesize '16777216' on node '0' (42.56 s)
```
=> numa: Enable test for ARM 16G hugepage memory

libvirt/tests/cfg/libvirt_mem.cfg
Test result:
(1/1) type_specific.io-github-autotest-libvirt.libvirt_mem.negative_test.attach_error.attach_nonexist_node: PASS (36.82 s)
=> Increase current memory size to avoid guest crash during bootup

provider/virtual_network/network_base.py
Test runs would fail if
* there were spaces in the values (e.g. '  32' instead of '32')
* missing setting would expect value '0' instead of 'n/a' but consider these equivalent
Therefore, normalize the ethtool output in the function. The function is only used in the update_device_coalesce script add test run log to PR.
=> virtual_network/coalesce: normalize ethtool output

libvirt/tests/src/numa/host_numa/host_numa_info.py
Since in rhel8 the cpu cluster_id is not available from virsh capabilities, so change the comparison logic to checking the cpu topology from virsh capabilities is the subset of result from system
result on rhel9:
(1/1) type_specific.io-github-autotest-libvirt.host_numa.numa_info.default: PASS (8.75 s)
result on rhel8:
(1/1) type_specific.io-github-autotest-libvirt.host_numa.numa_info.default: PASS (10.94 s)
=> Check the cpu topology from virsh capabilities is the subset of result from system

libvirt/tests/src/numa/numa_capabilities.py
Since in latest rhel9.4, cluster_id is introduced into cpu numa node capabilities. So to compromise rhel8, change content comparison to subset. 
Test result on rhel9.4 x86_64:
(1/1) type_specific.io-github-autotest-libvirt.numa_capabilities.default: PASS (12.85 s)
=> Change content comparison to subset

libvirt/tests/src/virtual_disks/virtual_disks_rerror_policy.py
The disk was originally selected by its target name but those names are impersistent and might change in the guest.
The test would then sometimes fail as it would read (without I/O errors) from the system disk instead of the new nbd disk when the system was at vdb.
Instead, discover the new disk as the one that doesn't have the root filesystem.
=> rerror_policy: fix disk selection

libvirt/tests/cfg/numa/guest_numa_node_tuning/memory_binding_setting.cfg, libvirt/tests/cfg/numa/guest_numa_node_tuning/memory_binding_with_emulator_thread.cfg, libvirt/tests/cfg/numa/guest_numa_node_tuning/specific_numa_memory_bind_hugepage.cfg, libvirt/tests/src/numa/guest_numa_node_tuning/memory_binding_setting.py, libvirt/tests/src/numa/guest_numa_node_tuning/memory_binding_with_emulator_thread.py, libvirt/tests/src/numa/guest_numa_node_tuning/specific_numa_memory_bind_hugepage.py, provider/numa/numa_base.py
This is to make the script adapted to different huge pages provided by different arches.
Enable support for kernel 4k and 64k with different default huge page size on ARM.
=> fix multiple numa hugepage cases on arm

libvirt/tests/cfg/virsh_cmd/domain/virsh_managedsave.cfg, libvirt/tests/src/virsh_cmd/domain/virsh_managedsave.py
1) aarch64 doesn't support 'host-model', change it to host-passthrough. 2) Let the script return error instead of cancel when build xml fails.
=> Fix build domain xml error

libvirt/tests/src/virtual_network/passt/passt_transfer_file.py
Passt can not recognize the multipath ipv6 route. Skip the ipv6 test once the host has multipath ipv6 route.
=> Skip ipv6 test once host has multipath ipv6 route

libvirt/tests/src/virtual_network/iface_stat.py
Ignore errors when trying to download a large file. The purpose was not to actually get the file, but to create a lot of network trafic, therefore whether the command succeeds or not doesn't matter.
Test result:
```
(1/2) type_specific.io-github-autotest-libvirt.virtual_network.iface_stat.compare.ethernet_type.managed_no.tap: PASS (274.72 s)
(2/2) type_specific.io-github-autotest-libvirt.virtual_network.iface_stat.compare.ethernet_type.managed_no.macvtap: PASS (424.07 s)
```
Before:
```
ShellTimeoutError: Timeout expired while waiting for shell command to complete: 'curl -O https://avocado-project.org/data/assets/jeos/27/jeos-27-64.qcow2.xz -L'    (output: '  % Total    % Received % Xferd  Average Speed …
```
=> Fixup:Shell command timeout error when running curl

libvirt/tests/cfg/storage/virsh_pool.cfg
Now the ceph variants in virsh_pool.cfg can't be translated to the values in jobs.yaml. That's because the quotes of ceph variant are different between cfg file and jobs.yaml.
=> storage_ceph: update the quotes of ceph variant from '' to "" to match the jobs.yaml

libvirt/tests/cfg/sriov/vm_lifecycle/sriov_vm_lifecycle_start_negative.cfg
This PR mainly automates a new negative scenatio with invalid driver
model for hostdev interface in VIRT-293914.
=> SRIOV: add new negative scenario when start vm with hostdev interface

libvirt/tests/cfg/snapshot/revert_snap_based_on_status.cfg, libvirt/tests/src/snapshot/revert_snap_based_on_status.py
xxxx-300468: Revert snapshots based on different domain and snapshot status
```
avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 snapshot_revert.snap_and_domain_status
(1/4) type_specific.io-github-autotest-libvirt.snapshot_revert.snap_and_domain_status.vm_running.snap_running: PASS (48.78 s)
(2/4) type_specific.io-github-autotest-libvirt.snapshot_revert.snap_and_domain_status.vm_running.snap_shutoff: PASS (16.37 s)
(3/4) type_specific.io-github-autotest-libvirt.snapshot_revert.snap_and_domain_status.vm_shutoff.snap_running: PASS (56.99 s)
(4/4) type_specific.io-github-autotest-libvirt.snapshot_revert.snap_and_domain_status.vm_shutoff.snap_shutoff: PASS (15.73 s)
```
Depend on …
=> add case for reverting snap based on domain and snap status

libvirt/tests/cfg/virsh_cmd/domain/virsh_memtune.cfg, libvirt/tests/src/virsh_cmd/domain/virsh_memtune.py
Before fix, below error for case on rhel9.4 when do post-process for guest vm:
(1/1) type_specific.io-github-autotest-libvirt.virsh.memtune.positive_test.normal_6: ERROR: Failures occurred while postprocess:\n\n: Guest avocado-vt-vm1 dmesg verification failed: Login timeout expired    (output: 'exceeded 240 s timeout')
After fix, test result:
x86_64 rhel9:
(1/8) type_specific.io-github-autotest-libvirt.virsh.memtune.positive_test.normal_1: PASS (34.60 s)
(2/8) type_specific.io-github-autotest-libvirt.virsh.memtune.positive_test.normal_2: PASS (38.76 s)
(3/8) type_specific.io-github-autotest-libvirt.virsh.memtune.positive_test.normal_3: PASS (33.62 s)
(4/8) type_specific.io-github-autotest-libvirt.virsh.memtune.positive_test.normal_4: PASS (33.66 s)
(5/8) …
=> Stop guest start before case execution

libvirt/tests/cfg/snapshot/revert_memory_only_snap.cfg, libvirt/tests/src/snapshot/revert_memory_only_snap.py
xxxx-300470:Revert guest to memory only snapshot.
```
avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 snapshot_revert.memory_only_snap
(1/1) type_specific.io-github-autotest-libvirt.snapshot_revert.memory_only_snap: PASS (63.51 s)
```
=> add case for revert memory only snap

libvirt/tests/cfg/event/virsh_event.cfg, libvirt/tests/src/event/virsh_event.py
Test result on aarch64 64k:
(1/2) type_specific.io-github-autotest-libvirt.virsh.event.positive_test.virsh_event.test_events.device-removal-failed_event.no_timeout.loop: PASS (150.40 s)
(2/2) type_specific.io-github-autotest-libvirt.virsh.event.positive_test.qemu_monitor_event.pretty_option.device-removal-failed_event.no_timeout.loop: PASS (149.08 s)
=> Virsh event add adaption for aarch64

libvirt/tests/cfg/numa/guest_numa.cfg, libvirt/tests/src/numa/guest_numa.py
The excluded libvirt version and machine types are out of date. Those old versions should not in our test scope and should be given up. Instead, we should use new qemu command line not only on q35, but also other arches, like aarch64.
=> guest_numa: fix out of date qemu cmd line update

libvirt/tests/cfg/virtual_network/update_device/update_iface_qos.cfg, libvirt/tests/src/virtual_network/update_device/update_iface_qos.py
- VIRT-294746 - [update-device][qos] Live update interface bandwidth setting by update-device or domiftune
Test result:
```
(01/64) type_specific.io-github-autotest-libvirt.virtual_network.update_device.iface_qos.net_iface_default_net.update-device.add.inbound_outbound: PASS (46.34 s)
(02/64) type_specific.io-github-autotest-libvirt.virtual_network.update_device.iface_qos.net_iface_default_net.update-device.add.inbound_only: PASS (79.46 s)
(03/64) type_specific.io-github-autotest-libvirt.virtual_network.update_device.iface_qos.net_iface_default_net.update-device.add.outbound_only: PASS (79.48 s)
(04/64) type_specific.io-github-autotest-libvirt.virtual_network.update_device.iface_qos.net_iface_default_net.update-device.update.inbound_outbound: PASS (79.49 s)
(05/64) …
```
=> Add new case of update-device of interface qos

libvirt/tests/cfg/virtual_network/update_device/update_iface_source.cfg, libvirt/tests/src/virtual_network/update_device/update_iface_source.py
- VIRT-294747 - [update-device][source] Live update interface source setting
Test result:
```
(1/4) type_specific.io-github-autotest-libvirt.virtual_network.update_device.iface_source.default_net_to_nat: PASS (68.13 s)
(2/4) type_specific.io-github-autotest-libvirt.virtual_network.update_device.iface_source.br_to_br: PASS (99.57 s)
(3/4) type_specific.io-github-autotest-libvirt.virtual_network.update_device.iface_source.direct_vepa_to_br: PASS (50.03 s)
(4/4) type_specific.io-github-autotest-libvirt.virtual_network.update_device.iface_source.default_net_to_direct_net: PASS (83.80 s)
```
=> Add new case of update interface source

libvirt/tests/cfg/virtual_network/update_device/update_iface_qos_invalid.cfg, libvirt/tests/src/virtual_network/update_device/update_iface_qos_invalid.py
- VIRT-294768 - [update-device][qos] Live update the QoS setting by update-device with invalid values
Test result:
```
(1/4) type_specific.io-github-autotest-libvirt.virtual_network.update_device.iface_qos.invalid.neg_value: PASS (77.66 s)
(2/4) type_specific.io-github-autotest-libvirt.virtual_network.update_device.iface_qos.invalid.big_value: FAIL: Expect should fail with one of ['could not convert bandwidth average value|Expected non-negative integer value'], but failed with:\n\n\nerror:  (44.55 s)
(3/4) type_specific.io-github-autotest-libvirt.virtual_network.update_device.iface_qos.invalid.no_mandatory_average: PASS (43.56 s)
(4/4) type_specific.io-github-autotest-libvirt.virtual_network.update_device.iface_qos.invalid.floor_without_bandwidth: PASS (77.40 s)
```
=> Add new case of update-device of iface qos:invalid value

libvirt/tests/cfg/snapshot/revert_snap_for_guest_with_genid.cfg, libvirt/tests/src/snapshot/revert_snap_for_guest_with_genid.py
xxxx-300460:Revert snapshot for guest which includes genid.
```
avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35  snapshot_revert.with_genid
(1/1) type_specific.io-github-autotest-libvirt.snapshot_revert.with_genid: PASS (55.51 s)
```
Depend on https://github.com/avocado-framework/avocado-vt/pull/3886
=> add case for revert snap for guest with genid

libvirt/tests/cfg/snapshot/revert_snap_based_on_state.cfg, libvirt/tests/src/snapshot/revert_snap_based_on_state.py
-   no need to use the new created function: virsh.snapshot_status
- replace snap_status with snap_state 
```
avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 snapshot_revert.snap_and_domain_status
(1/4) type_specific.io-github-autotest-libvirt.snapshot_revert.snap_and_domain_status.vm_running.snap_running: PASS (38.76 s)
(2/4) type_specific.io-github-autotest-libvirt.snapshot_revert.snap_and_domain_status.vm_running.snap_shutoff: PASS (44.38 s)
(3/4) type_specific.io-github-autotest-libvirt.snapshot_revert.snap_and_domain_status.vm_shutoff.snap_running: PASS (53.22 s)
(4/4) type_specific.io-github-autotest-libvirt.snapshot_revert.snap_and_domain_status.vm_shutoff.snap_shutoff: PASS (8.48 s)
```
=> fix snapshot case to use appropirate get snap state function

libvirt/tests/src/virtual_device/input_devices_plug_unplug.py
Before:
```
(1/1) type_specific.io-github-autotest-libvirt.virtual_devices.input_devices_plug_unplug.hot.bus_virtio.tablet_mouse_keyboard: ERROR: Command '/bin/virsh attach-device avocado-vt-vm1 /tmp/xml_utils_temp_cqyyjueb.xml' failed.\nstdout: b'\n'\nstderr: b'error: Failed to attach device from /tmp/xml_utils_temp_cqyyjueb.xml\nerror: internal error: No more available PCI slots\n'\nadditional_info:... (27.21 s)
```
After:
```
(1/1) type_specific.io-github-autotest-libvirt.virtual_devices.input_devices_plug_unplug.hot.bus_virtio.tablet_mouse_keyboard: PASS (50.72 s)
```
=> misc_virtual_devices: fix "No more available PCI slots" error

libvirt/tests/src/snapshot/revert_memory_only_snap.py, libvirt/tests/src/snapshot/revert_snap_based_on_state.py, libvirt/tests/src/snapshot/revert_snap_for_guest_with_genid.py
teardown step should not be executed after check vesrion function is executed
```
avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 snapshot_revert
(1/1) type_specific.io-github-autotest-libvirt.snapshot_revert.memory_only_snap: PASS (52.41 s)
(1/1) type_specific.io-github-autotest-libvirt.snapshot_revert.snap_and_domain_state: PASS (49.21 s)
(1/1) type_specific.io-github-autotest-libvirt.snapshot_revert.with_genid: PASS (56.35 s)
```
=> fix snapshot case the libvirt version issue

libvirt/tests/cfg/guest_agent/guest_agent.cfg, libvirt/tests/src/guest_agent/guest_agent.py
This PR adds a test about a socket path belonging to part of auto-generated path.
```
(1/6) type_specific.io-github-autotest-libvirt.guest_agent.positive.ga_started.ga_state_test: PASS (57.75 s)
(2/6) type_specific.io-github-autotest-libvirt.guest_agent.positive.ga_started.restart_libvirtd: PASS (57.35 s)
(3/6) type_specific.io-github-autotest-libvirt.guest_agent.positive.ga_started.suspend_resume_guest: PASS (57.07 s)
(4/6) type_specific.io-github-autotest-libvirt.guest_agent.positive.ga_started.hotunplug_ga: PASS (55.82 s)
(5/6) type_specific.io-github-autotest-libvirt.guest_agent.positive.ga_started.customize_source_path.auto_gen_path: PASS (57.38 s)
(6/6) type_specific.io-github-autotest-libvirt.guest_agent.positive.ga_started.customize_source_path.random: PASS (57.15 s)
(1/6) …
```
=> guest_agent: Add a case about socket path

libvirt/tests/cfg/virsh_cmd/domain/virsh_start.cfg, libvirt/tests/src/virsh_cmd/domain/virsh_start.py
update audit_log_search case with more validation points
/var/log/messages and auvirt --start recent --all-events should not contain error message related libvirtd or guest itself
=> update audit_log_search case with more validation points

libvirt/tests/cfg/virtual_network/link_state/link_state_model_type.cfg, libvirt/tests/src/virtual_network/link_state/link_state_model_type.py
This PR adds:
VIRT-298009 - Start vm with different interface type with
various model type and link state setting
Depends on:
- https://github.com/avocado-framework/avocado-vt/pull/3887
**Test results:** The failed cases are due to a known issue.
```
(01/27) type_specific.io-github-autotest-libvirt.virtual_network.link_state.model.network.virtio.initial_up: PASS (57.17 s)
(02/27) type_specific.io-github-autotest-libvirt.virtual_network.link_state.model.network.virtio.initial_down: PASS (62.61 s)
(03/27) type_specific.io-github-autotest-libvirt.virtual_network.link_state.model.network.virtio.without_state: PASS (99.20 s)
(04/27) type_specific.io-github-autotest-libvirt.virtual_network.link_state.model.network.e1000e.initial_up: PASS (57.55 s)
(05/27) …
```
=> virtual_network: Add a case of link state

libvirt/tests/cfg/virtual_disks/vhostvdpa_block_backend_type/define_start_vm_with_vhostvdpa_backend_disk.cfg, libvirt/tests/src/virtual_disks/vhostvdpa_block_backend_type/define_start_vm_with_vhostvdpa_backend_disk.py, spell.ignore
This pr adds:
VIRT-300428 - Define&Start vm with disk of vhostvdpa backend
VIRT-300445 - Define/start vm with disk of vhostvdpa backend
- invalid configuration
Depends on:
- https://github.com/avocado-framework/avocado-vt/pull/3893
**Test results:** The failed case is caused by an issue.
```
(1/5) type_specific.io-github-autotest-libvirt.virtual_disk.vhostvdpa.define_start.default.none: PASS (46.15 s)
(2/5) type_specific.io-github-autotest-libvirt.virtual_disk.vhostvdpa.define_start.default.directsync: FAIL: Failed to check disk io for vdb! (51.62 s)
(3/5) type_specific.io-github-autotest-libvirt.virtual_disk.vhostvdpa.define_start.default.no_specified_value: PASS (10.23 s)
(4/5) type_specific.io-github-autotest-libvirt.virtual_disk.vhostvdpa.define_start.without_shared_memory.none: PASS …
```
=> virtual_disks: Add 2 cases of vhostvdpa_block

libvirt/tests/cfg/virtual_network/hotplug/attach_detach_interface/attach_interface_with_model.cfg, libvirt/tests/src/virtual_network/hotplug/attach_detach_interface/attach_interface_with_model.py, provider/interface/interface_base.py
This pr adds:
VIRT-298404: Attach/Detach interface with different model,
and --alias, --mac, --print-xml
```
(1/4) type_specific.io-github-autotest-libvirt.virtual_network.hotplug.attach_interface.model.virtio: PASS (72.05 s)
(2/4) type_specific.io-github-autotest-libvirt.virtual_network.hotplug.attach_interface.model.e1000e: PASS (71.34 s)
(3/4) type_specific.io-github-autotest-libvirt.virtual_network.hotplug.attach_interface.model.igb: PASS (71.79 s)
(4/4) type_specific.io-github-autotest-libvirt.virtual_network.hotplug.attach_interface.model.rtl8139: PASS (71.15 s)
```
=> virtual_network: Add a hotplug case

libvirt/tests/cfg/virtual_network/update_device/update_iface_link_state.cfg, libvirt/tests/src/virtual_network/update_device/update_iface_link_state.py
This PR adds:
VIRT-294737 - Live update interface link state by update-device
**Test results:** The failed cases are due to a known issue.
```
(01/18) type_specific.io-github-autotest-libvirt.virtual_network.update_device.iface_like_state.network.virtio.add: -^[[PASS (100.35 s)
(02/18) type_specific.io-github-autotest-libvirt.virtual_network.update_device.iface_like_state.network.virtio.delete: PASS (64.03 s)
(03/18) type_specific.io-github-autotest-libvirt.virtual_network.update_device.iface_like_state.network.virtio.update: PASS (64.57 s)
(04/18) type_specific.io-github-autotest-libvirt.virtual_network.update_device.iface_like_state.network.e1000e.add: PASS (100.37 s)
(05/18) type_specific.io-github-autotest-libvirt.virtual_network.update_device.iface_like_state.network.e1000e.delete: …
```
=> virtual_network: Add a case of update-device

libvirt/tests/src/virtual_network/hotplug/attach_detach_interface/attach_interface_with_model.py
Waiting for device-removed event takes more time than x86.
` (1/1) type_specific.io-github-autotest-libvirt.virtual_network.hotplug.attach_interface.model.virtio: PASS (68.29 s)
`
=> virtual_network: Extend event_timeout for arm

libvirt/tests/cfg/snapshot/delete_external_snap_with_references.cfg, libvirt/tests/src/snapshot/delete_external_snap_with_references.py
xxxx-300472:Delete snapshots in the parent external snapshots with multiple children.
```
avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 snapshot_delete.multiple_children
(1/3) type_specific.io-github-autotest-libvirt.snapshot_delete.multiple_children.del_parent_snap: PASS (50.88 s)
(2/3) type_specific.io-github-autotest-libvirt.snapshot_delete.multiple_children.del_current_branch: PASS (67.41 s)
(3/3) type_specific.io-github-autotest-libvirt.snapshot_delete.multiple_children.del_non_current_branch.tail_to_head: PASS (68.94 s)
```
=> add case for delete snap in parent external snap with muti children

libvirt/tests/src/virtual_disks/virtual_disks_multidisks.py
There are two problems in virtual_disks_multidisks.py script: 
1) The os xml will change to seabios guest when we testing ovmf guest because of incorrectos xml configuration
2) Internal snapshot is not supportted in ovmf guest.
Fix the above problems by adding os_firmware attribute and skip internal snapshot test for ovmf guest.
=> virtual_disk: fix snapshot issue for ovmf guest

libvirt/tests/cfg/memory/memory_devices/virtio_mem_with_memory_backing_type.cfg, libvirt/tests/src/memory/memory_devices/virtio_mem_with_memory_backing_type.py, provider/memory/memory_base.py
VIRT-299164: Virtio-mem memory device with various memory backing type
RHEL9 + x86 
```
avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 memory.devices.virtio_mem.memory_backing_type
(1/7) type_specific.io-github-autotest-libvirt.memory.devices.virtio_mem.memory_backing_type.with_numa.alloc_ondemand.file: PASS (86.39 s)
(2/7) type_specific.io-github-autotest-libvirt.memory.devices.virtio_mem.memory_backing_type.with_numa.alloc_ondemand.anonymous: PASS (86.36 s)
(3/7) type_specific.io-github-autotest-libvirt.memory.devices.virtio_mem.memory_backing_type.with_numa.alloc_ondemand.memfd: PASS (86.27 s)
(4/7) type_specific.io-github-autotest-libvirt.memory.devices.virtio_mem.memory_backing_type.with_numa.alloc_ondemand.undefined: …
```
=> add case for virtio-mem with memory backing type

libvirt/tests/cfg/memory/memory_devices/change_virtio_mem_request_size.cfg, libvirt/tests/src/memory/memory_devices/change_virtio_mem_request_size.py, provider/memory/memory_base.py
xxxx-299165: Change requested memory of virtio-mem memory device
Depend on https://github.com/avocado-framework/avocado-vt/pull/3907/files 
x86+RHEL9
```
avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 memory.devices.virtio_mem.change_memory
(1/4) type_specific.io-github-autotest-libvirt.memory.devices.virtio_mem.change_memory.undefined.normal_requested.shutoff_guest: PASS (50.99 s)
(2/4) type_specific.io-github-autotest-libvirt.memory.devices.virtio_mem.change_memory.undefined.zero_requested.shutoff_guest: PASS (59.30 s)
(3/4) type_specific.io-github-autotest-libvirt.memory.devices.virtio_mem.change_memory.undefined.bigger_requested.shutoff_guest: PASS (58.27 s)
(4/4) …
```
=> add case for changing requested size value of virtio-mem

libvirt/tests/cfg/virtual_disks/virtual_disks_iothreads_queue.cfg, libvirt/tests/src/virtual_disks/virtual_disks_iothreads_queue.py
Test disk driver iothread feature like below
Scenarios:
- start vm with iothreads
- hotplug a disk with iothreads
- update disk with iothreads
- delete iothread
<disk type='file' device='disk'>
<driver name='qemu' queues='3'>
<iothreads> 
<iothread id='2'> 
<queue id='1'/>
</iothread> 
<iothread id='3'> 
<queue id='0'/>
<queue id='2'/>
</iothread> 
</iothreads> 
</driver>
=> virtual_disks_driver_iothreads: add case

libvirt/tests/cfg/event/virsh_event.cfg
Since on rhel8 section size must be at least 1024MB for 64K base, so plugged memory must equal or bigger than 1024M.
Test result on rhel8 aarch64 64k:
(1/1) type_specific.io-github-autotest-libvirt.virsh.event.positive_test.virsh_event.test_events.device-removal-failed_event.no_timeout.loop: PASS (57.34 s)
=> Adaption for rhel8 aarch64

provider/v2v_vmcheck_helper.py
Add the "skip checking virtio drivers for rhel8.10 issue". Please check #RHEL-30528 #RHEL-17685.
=> v2v: fix the issue "failed to install virtio drivers on rhel8.10"

libvirt/tests/cfg/virtual_network/update_device/update_iface_with_options_active.cfg, libvirt/tests/cfg/virtual_network/update_device/update_iface_with_options_inactive.cfg, libvirt/tests/src/virtual_network/update_device/update_iface_with_options.py, provider/virtual_network/network_base.py
- VIRT-298326 - [update-device] Update an interface by update-device with --live/--config/--current/--persistent on active domain
- VIRT-298319 - [update-device] Update an interface by update-device with --live/--config/--current/--persistent on inactive domain
Test result:
```
(01/20) type_specific.io-github-autotest-libvirt.virtual_network.update_device.with_options.active_vm.live: PASS (64.53 s)
(02/20) type_specific.io-github-autotest-libvirt.virtual_network.update_device.with_options.active_vm.live_persistent: PASS (65.27 s)
(03/20) type_specific.io-github-autotest-libvirt.virtual_network.update_device.with_options.active_vm.live_config: PASS (65.47 s)
(04/20) type_specific.io-github-autotest-libvirt.virtual_network.update_device.with_options.active_vm.live_current: PASS (65.33 s) …
```
=> Add new case of update interface: update-device with options

libvirt/tests/cfg/guest_os_booting/os_configuration/without_default_os_attributes.cfg, libvirt/tests/src/guest_os_booting/os_configuration/without_default_os_attributes.py
The arch type should be obtained from the host.
` (1/1) type_specific.io-github-autotest-libvirt.guest_os_booting.os_configuration.without_arch: PASS (42.79 s)
`
=> guest_os_booting: Fix a hardcode arch type issue

libvirt/tests/cfg/virtual_disks/vhostvdpa_block_backend_type/nodedev_vhostvdpa_disk.cfg, libvirt/tests/src/virtual_disks/vhostvdpa_block_backend_type/nodedev_vhostvdpa_disk.py
This PR adds:
VIRT-300446 - Test nodedev related operations against vhostvdpa disk
- https://github.com/avocado-framework/avocado-vt/pull/3903
- https://github.com/avocado-framework/avocado-vt/pull/3904
` (1/1) type_specific.io-github-autotest-libvirt.virtual_disks.vhostvdpa.nodedev: PASS (9.00 s)
`
=> virtual_disks: Add a vhostvdpa disk nodedev test

libvirt/tests/cfg/virsh_cmd/monitor/virsh_domstate.cfg, libvirt/tests/src/virsh_cmd/monitor/virsh_domstate.py
libvirt8.0.0 test result:
Before:
```
(1/1) type_specific.io-github-autotest-libvirt.virsh.domstate.normal_test.reason.crash_vm.oncrash_destroy: ERROR: Failed to define avocado-vt-vm1 for reason:\nerror: Failed to define domain from /tmp/xml_utils_temp_6885f_ot.xml\nerror: unsupported configuration: unknown panic model 'pvpanic'\n (9.69 s)
(1/1) type_specific.io-github-autotest-libvirt.virsh.domstate.normal_test.reason.crash_vm.oncrash_restart: ERROR: Failed to define avocado-vt-vm1 for reason:\nerror: Failed to define domain from /tmp/xml_utils_temp_uvw1xi7l.xml\nerror: unsupported configuration: unknown panic model 'pvpanic'\n (9.84 s)
(1/1) type_specific.io-github-autotest-libvirt.virsh.domstate.normal_test.reason.crash_vm.oncrash_coredum …
```
=> guest_kernel_debugging: aarch64 supports panic since libvirt-9.1.0

provider/virtual_network/network_base.py
Fixed a bug related to rx_frames comparison.
The issue was that the collected rx_frames contained spaces, while the expected rx_frames did not.
Before:
```
(1/1) type_specific.io-github-autotest-libvirt.virtual_network.update_device.coalesce.nat_net.update_iface_coalesce: FAIL: rx-frames of vnet0 should be 64, not  64 (31.53 s)
```
After:
```
(1/1) type_specific.io-github-autotest-libvirt.virtual_network.update_device.coalesce.nat_net.update_iface_coalesce: PASS (36.08 s)
```
=> virtual_networks: remove spaces before comparing rx_frames

libvirt/tests/src/virtual_disks/vhostvdpa_block_backend_type/nodedev_vhostvdpa_disk.py
` (1/1) type_specific.io-github-autotest-libvirt.virtual_disks.vhostvdpa.nodedev: PASS (7.81 s)
`
=> virtual_disks: Fix vhostvdpa_disk nodedev xml issue

libvirt/tests/src/virtual_disks/virtual_disks_iothreads_queue.py
Add the libvirt version checking.
=> virtual_disks_iothreads_queue: fix version checking

libvirt/tests/cfg/snapshot/revert_snap_with_flags.cfg, libvirt/tests/src/snapshot/revert_snap_with_flags.py
xxxx-300469
```
avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 snapshot_revert.with_flags
(1/1) type_specific.io-github-autotest-libvirt.snapshot_revert.with_flags: PASS (58.50 s)
```
=> add case for snap revert with flags

libvirt/tests/cfg/snapshot/delete_snapshot_metadata.cfg, libvirt/tests/src/snapshot/delete_snapshot_metadata.py
xxxx-298194:delete snapshot's metadata
```
avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 snapshot_delete.metadata.type_qcow2
(1/1) type_specific.io-github-autotest-libvirt.snapshot_delete.metadata.type_qcow2: PASS (58.18 s)
```
=> add case for delete snapshot metadata

libvirt/tests/src/guest_os_booting/boot_order/boot_with_multiple_boot_dev.py
This pr is to fix below error:
**rhel.guest_os_booting.boot_order.boot_with_multiple_boot_dev.network.cdrom.network_bootable**
`UnboundLocalError: local variable 'disk_image' referenced before assignment`
=> guest_ob_booting: Fixup an error of UnboundLocalError: disk_image

libvirt/tests/cfg/migration/migrate_mem.cfg
Fix following error:
LibvirtXMLError: ... Failed to define domain from ... error: unsupported
configuration: Attribute migratable is only allowed for
'host-passthrough' / 'maximum' CPU mode
=> migration: Fix xml error

libvirt/tests/cfg/snapshot/delete_snapshot_after_disk_attached.cfg, libvirt/tests/src/snapshot/delete_snapshot_after_disk_attached.py
xxxx-298191: delete snapshot after disk attached
```
avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 snapshot_delete.disk_attached
(1/1) type_specific.io-github-autotest-libvirt.snapshot_delete.disk_attached: PASS (53.51 s)
```
=> add case for delete snap after disk attached

libvirt/tests/cfg/snapshot/delete_disk_only_snapshot.cfg, libvirt/tests/src/snapshot/delete_disk_only_snapshot.py
xxxx-298192: delete disk only snapshot
Depend on https://github.com/avocado-framework/avocado-vt/pull/3906
```
avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 snapshot_delete.disk_only_snap
(1/1) type_specific.io-github-autotest-libvirt.snapshot_delete.disk_only_snap: PASS (57.01 s)
```
=> add case for delete disk only snapshot

libvirt/tests/cfg/snapshot/check_delete_and_revert_snap_event_in_multiple_branch.cfg, libvirt/tests/src/snapshot/check_delete_and_revert_snap_event_in_multiple_branch.py
xxxx-300473: Delete and revert snapshots and check events in two snapshot branches
```
avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 snapshot_event.multiple_branch.del_and_revert
JOB LOG    : /var/lib/avocado/job-results/job-2024-04-29T01.45-83f3e08/job.log
(1/1) type_specific.io-github-autotest-libvirt.snapshot_event.multiple_branch.del_and_revert: PASS (104.57 s)
```
=> add case for checking delete and revert snap event in multiple branch

libvirt/tests/src/numa/guest_numa_node_tuning/auto_memory_nodeset_placement.py, libvirt/tests/src/numa/guest_numa_node_tuning/memory_binding_setting.py, libvirt/tests/src/numa/numa_memory.py, libvirt/tests/src/numa/numa_memory_migrate.py, libvirt/tests/src/virsh_cmd/domain/virsh_numatune.py
In PR https://github.com/avocado-framework/avocado-vt/pull/3804, a similar bug is fixed by replacing parse_numa_nodeset_to_str with the new convert_all_nodes_to_string function. However, parse_numa_nodeset_to_str is still called at several places. Therefore, in this PR, replace all parse_numa_nodeset_to_str to convert_all_nodes_to_string.
Signed-off-by: Qian Jianhua [qianjh@fujitsu.com](mailto:qianjh@fujitsu.com)
Before:
```
(1/1) type_specific.io-github-autotest-libvirt.guest_numa_node_tuning.auto_memory_nodeset_placement.without_iothread.nodeset_defined.mem_mode_interleave.vcpu_auto: FAIL: Expect cpuset.mems=0-1, but found 0-3 (53.25 s)
(1/1) type_specific.io-github-autotest-libvirt.guest_numa_node_tuning.auto_memory_nodeset_placement.without_iothread.nodeset_defined.mem_mode_interleave. …
```
=> numa: replace parse_numa_nodeset_to_str() to convert_all_nodes_to_string()

libvirt/tests/src/virsh_cmd/domain/virsh_domfstrim.py
virt_qemu_ga_read_nonsecurity_files need reboot guest, it takes more time to finish this in some extreme case
=> Fix setpool virt_qemu_ga_read_nonsecurity_files timeout issue

libvirt/tests/src/libvirt_package.py, libvirt/tests/src/libvirtd_start.py, libvirt/tests/src/save_and_restore/restore_from_local_file.py, libvirt/tests/src/virsh_cmd/domain/virsh_managedsave.py, libvirt/tests/src/virt_cmd/virt_top.py, v2v/tests/src/install.py
Fix ERROR: module 'avocado.utils.software_manager' has no attribute 'SoftwareManager'
Test result of one case:
(1/1) type_specific.io-github-autotest-libvirt.virsh.managedsave.status_error_yes.name_option.transient_vm: PASS (9.60 s)
=> Fixup:SoftwareManager not found

libvirt/tests/cfg/guest_os_booting/boot_menu/bootmenu.cfg, libvirt/tests/cfg/guest_os_booting/boot_order/boot_from_cdrom_device.cfg, libvirt/tests/cfg/guest_os_booting/boot_order/boot_from_disk_device.cfg, libvirt/tests/cfg/guest_os_booting/boot_order/boot_from_usb_device.cfg, libvirt/tests/cfg/guest_os_booting/boot_order/boot_with_multiple_boot_dev.cfg, libvirt/tests/cfg/guest_os_booting/boot_order/boot_with_multiple_boot_order.cfg, libvirt/tests/cfg/guest_os_booting/ovmf_firmware/ovmf_backed_nvram.cfg, libvirt/tests/cfg/guest_os_booting/ovmf_firmware/ovmf_firmware_feature.cfg, libvirt/tests/cfg/guest_os_booting/ovmf_firmware/ovmf_loader.cfg, libvirt/tests/cfg/guest_os_booting/ovmf_firmware/ovmf_nvram.cfg, libvirt/tests/cfg/guest_os_booting/ovmf_firmware/ovmf_seclabel_in_nvram.cfg, libvirt/tests/cfg/guest_os_booting/seabios_firmware/seabios_loader.cfg, libvirt/tests/cfg/guest_os_booting/useserial/useserial.cfg
To enable tests on arm, correct the cfg files in this PR.
Test results: Most of cases are passed, I will fix the reset failures in another pr.
=> guest_os_booting: Correct the supported arch types

libvirt/tests/cfg/memory/memory_devices/dimm_memory_with_memory_alloccation_and_numa.cfg, libvirt/tests/src/memory/memory_devices/dimm_memory_with_memory_alloccation_and_numa.py
xxxx-299047: Dimm memory with various memory allocation and guest numa settings
Rhel9.4+x86 , rhel9+aarch
```
avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 memory.devices.dimm.memory_allocation_and_numa
(01/31) type_specific.io-github-autotest-libvirt.memory.devices.dimm.memory_allocation_and_numa.init_define_with_dimm.no_numa.no_maxmemory: PASS (8.13 s)
(02/31) type_specific.io-github-autotest-libvirt.memory.devices.dimm.memory_allocation_and_numa.init_define_with_dimm.no_numa.no_slot: PASS (7.98 s)
(03/31) type_specific.io-github-autotest-libvirt.memory.devices.dimm.memory_allocation_and_numa.init_define_with_dimm.no_numa.with_slot: PASS (9.72 s)
(04/31) type_specific.io-github-autotest-libvirt.memory.devices.dimm.memory_ …
```
=> add case for dimm with memory allocation and numa

libvirt/tests/cfg/numa/guest_numa_node_tuning/change_numa_tuning.cfg, libvirt/tests/src/numa/guest_numa_node_tuning/change_numa_tuning.py
remove 'kernelpagesize_KB' parameter, and get pagesize with getpagesize().
Before:
```
(1/1) type_specific.io-github-autotest-libvirt.guest_numa_node_tuning.change_numa_tuning.mem_mode_restrictive: FAIL: The numa_maps should include 'kernelpagesize_kB=64'， but not found (123.15 s)
```
After:
```
(1/1) type_specific.io-github-autotest-libvirt.guest_numa_node_tuning.change_numa_tuning.mem_mode_restrictive: PASS (126.90 s)
```
=> numa: remove 'kernelpagesize_kB' parameter

libvirt/tests/cfg/guest_os_booting/boot_order/boot_from_virtiofs_device.cfg, libvirt/tests/cfg/guest_os_booting/boot_order/hotplug_device_with_boot_order.cfg, libvirt/tests/src/guest_os_booting/boot_order/hotplug_device_with_boot_order.py
On s390x, booting from virtiofs is not supported. Expect an error message.
Disable one other test. It would prepare the bootable environment before trying to set/use the boot from virtiofs. The preparation would take about 2 minutes. For this negative error message test on s390x, it's not necessary. Disable instead.
Also, run some reformatting by black.
=> guest_os_booting/boot_order: expect error on s390x

libvirt/tests/src/virsh_cmd/domain/virsh_detach_device_alias.py
Some host don't have input devices. So no /dev/input/event* files exist. If that happens, we just return test error.
=> fix cannot access '/dev/input/event*': No such file or directory

libvirt/tests/cfg/memory/memory_devices/virtio_mem_coldplug_and_unplug.cfg, libvirt/tests/src/memory/memory_devices/virtio_mem_coldplug_and_unplug.py
xxxx-299161:Virtio-mem memory device cold-plug and cold-unplug
x86+rhel9
```
avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 memory.devices.virtio_mem.coldplug_and_unplug
(1/5) type_specific.io-github-autotest-libvirt.memory.devices.virtio_mem.coldplug_and_unplug.with_addr: PASS (37.79 s)
(2/5) type_specific.io-github-autotest-libvirt.memory.devices.virtio_mem.coldplug_and_unplug.source_and_mib: PASS (38.10 s)
(3/5) type_specific.io-github-autotest-libvirt.memory.devices.virtio_mem.coldplug_and_unplug.unplug_none_dev: PASS (37.92 s)
(4/5) type_specific.io-github-autotest-libvirt.memory.devices.virtio_mem.coldplug_and_unplug.plug_exceeded_max_mem: PASS (38.28 s)
(5/5) …
```
=> add case for virtio-mem coldplug and cold unplug

libvirt/tests/src/memory/virsh_setmem.py
Test result on rhel9.5 aarch64:
(1/1) type_specific.io-github-autotest-libvirt.virsh.setmem.valid_options.running.half_mem.domid.dom_arg_size_arg.cmd_flag_current.manipulate_action.none.no_action: PASS (73.42 s)
=> Fix pkg dmidecode missing issue in guest image

libvirt/tests/cfg/virtual_disks/virtual_disks_discard_granularity.cfg, libvirt/tests/src/virtual_disks/virtual_disks_discard_granularity.py
Automate discard_granularity disk attribute cases
scenarios cover normal, negative, boundary and updates 
xx-300179 - Live update disk with //disk/blockio[@discard_granularity
xx-300180 - Define&&Start vm with //disk/blockio[@discard_granularity
xx-300181 - Hotplug/unplug disk with //disk/blockio[@discard_granularity
xx-300202 - Define&&Start vm with //disk/blockio[@discard_granularity]- invalid values 
xx-300203 - Define&&Start vm with //disk/blockio[@discard_granularity] - boundary values
=> Automate discard_granularity disk attribute cases

libvirt/tests/src/numa/guest_numa_node_tuning/memory_binding_setting.py
Fix the failed case on aarch64 with kernel pagesize=4K.
Before:
```
(1/1) type_specific.io-github-autotest-libvirt.guest_numa_node_tuning.memory_binding_setting.hugepage.mem_mode_strict.multiple_host_nodes: FAIL: Expect N0 + N1 = 4 in numa_maps, but found '1024' (132.91 s)
(1/1) type_specific.io-github-autotest-libvirt.guest_numa_node_tuning.memory_binding_setting.hugepage.mem_mode_restrictive.multiple_host_nodes: FAIL: Expect N0 + N1 = 4 in numa_maps, but found '1024' (143.61 s)
```
After:
```
(1/1) type_specific.io-github-autotest-libvirt.guest_numa_node_tuning.memory_binding_setting.hugepage.mem_mode_strict.multiple_host_nodes: PASS (132.45 s)
(1/1) type_specific.io-github-autotest-libvirt.guest_numa_node_tuning.memory_binding_setting.hug …
```
=> numa: use dynamic expected value for different architectures

libvirt/tests/cfg/daemon/check_socket_files_with_services.cfg, libvirt/tests/cfg/daemon/check_virsh_connection_switch_between_monolithic_and_modular.cfg, libvirt/tests/cfg/daemon/enable_disable_daemon_socket_services.cfg, libvirt/tests/src/daemon/check_socket_files_with_services.py, libvirt/tests/src/daemon/check_virsh_connection_switch_between_monolithic_and_modular.py, libvirt/tests/src/daemon/enable_disable_daemon_socket_services.py, provider/libvirtd/libvirtd_base.py
- VIRT-300392 - Enable/disable daemons socket services
- VIRT-300393 - Check the socket files after start/stop daemons' socket service
- VIRT-300394 - Check virsh connection after switching between the legacy monolithic daemon and the modular daemon
Test result:
```
(1/6) type_specific.io-github-autotest-libvirt.daemon.check_virsh_connection_switch_between_monolithic_and_modular: PASS (6.54 s)
(2/6) type_specific.io-github-autotest-libvirt.daemon.enable_disable_daemon_socket_services.main_socket: PASS (14.20 s)
(3/6) type_specific.io-github-autotest-libvirt.daemon.enable_disable_daemon_socket_services.ro_socket: PASS (14.13 s)
(4/6) type_specific.io-github-autotest-libvirt.daemon.enable_disable_daemon_socket_services.admin_socket: PASS (14.20 s)
(5/6) …
```
=> Add new cases of libvirtd

libvirt/tests/cfg/virtual_network/update_device/update_iface_with_identifier.cfg, libvirt/tests/src/virtual_network/update_device/update_iface_with_identifier.py
- VIRT-298320 - [update-device] update an interface by update-device match by mac address, and alias & pci address together
Test result:
```
(01/12) type_specific.io-github-autotest-libvirt.virtual_network.update_device.iface_with_identifier.update.mac_only: PASS (7.92 s)
(02/12) type_specific.io-github-autotest-libvirt.virtual_network.update_device.iface_with_identifier.update.alias_only: PASS (7.96 s)
(03/12) type_specific.io-github-autotest-libvirt.virtual_network.update_device.iface_with_identifier.update.pci_address_only: PASS (7.82 s)
(04/12) type_specific.io-github-autotest-libvirt.virtual_network.update_device.iface_with_identifier.update.right_mac_alias_wrong_pci: PASS (7.82 s)
(05/12) type_specific.io-github-autotest-libvirt.virtual_network.update_device.iface_with_identifier.upd …
```
=> Add network case of update-device

libvirt/tests/cfg/memory/memory_devices/dimm_memory_hotplug.cfg, libvirt/tests/src/memory/memory_devices/dimm_memory_hotplug.py, provider/memory/memory_base.py
xxxx-300402 Dimm memory device hot-plug
```
avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 memory.devices.dimm.hotplug
(1/6) type_specific.io-github-autotest-libvirt.memory.devices.dimm.hotplug.target_and_address: PASS (47.10 s)
(2/6) type_specific.io-github-autotest-libvirt.memory.devices.dimm.hotplug.source_and_mib: PASS (47.47 s)
(3/6) type_specific.io-github-autotest-libvirt.memory.devices.dimm.hotplug.plug_exceeded_max_mem: PASS (45.54 s)
(4/6) type_specific.io-github-autotest-libvirt.memory.devices.dimm.hotplug.duplicate_addr: PASS (45.47 s)
(5/6) type_specific.io-github-autotest-libvirt.memory.devices.dimm.hotplug.duplicate_slot: PASS (45.35 s)
(6/6) type_specific.io-github-autotest-libvirt.memory.devices.dimm.hotplug …
```
=> add case for dimm memory hotplug

libvirt/tests/cfg/virtual_disks/vhostvdpa_block_backend_type/define_start_vm_with_multi_vhostvdpa_backend_disks.cfg, libvirt/tests/src/virtual_disks/vhostvdpa_block_backend_type/define_start_vm_with_multi_vhostvdpa_backend_disks.py
This PR adds:
VIRT-300441: Define&Start vm with two disks of vhostvdpa backend
Depends on:
- https://github.com/avocado-framework/avocado-vt/pull/3893
- https://github.com/autotest/tp-libvirt/pull/5570
```
(1/1) type_specific.io-github-autotest-libvirt.virtual_disk.vhostvdpa.define_start_multi_disks: PASS (56.23 s)
JOB HTML   : /var/lib/avocado/job-results/job-2024-04-18T22.18-67c2b69/results.html
JOB TIME   : 58.10 s
```
=> virtual_disks: Add a vhostvdpa-blk test

libvirt/tests/cfg/virtual_disks/virtual_disks_blockresize.cfg, libvirt/tests/src/virtual_disks/virtual_disks_blockresize.py
Cover blockresize in various scenarios
=> Automate blockresize cases

libvirt/tests/cfg/virtual_device/filesystem_device_unprivileged.cfg, libvirt/tests/src/virsh_cmd/host/virsh_sysinfo.py, libvirt/tests/src/virtual_device/filesystem_device_unprivileged.py, spell.ignore
Depends on: https://github.com/avocado-framework/avocado-vt/pull/3895
Add new test cases checking that non-root users can mount and use a host directory.
Variants:
2 vms, 1 filesystem
1 vm, 1 filesystem
1 vm, 2 filesystems
Notes:
1. use wait_for_serial login because the unprivileged user's VMs
are created with interface type 'user' per default, so there's
no vnet nic and therefore wait_for_login can't get the address
2. Due to 1. it's better to use the 'safe' command functions to avoid
timeouts because there might be kernel messages breaking the
output scan.
3. For hugepages, the unprivileged user needs access to a hugetlbfs
and update their local libvirt configuration. After updating
the configuration, the process needs to be killed to force
the daemon to be loaded with the new …
=> filesystem_device: test usage for unprivileged users

libvirt/tests/src/passthrough/ccw/libvirt_ccw_passthrough.py
The test fails sometimes in CI when trying to start the VM. The mediated device doesn't seem to be present yet. I can't reproduce this but adding sleep of 2 secs to confirm in future runs that it's really about timing.
=> libvirt_ccw_passthrough: add sleep

libvirt/tests/src/virtual_network/update_device/update_device_coalesce.py
On latest rhel 8 system, when coalesce is not set, the default value for rx_frames change to n/a. While on rhel 9, it's 0. Both of them are expectable. Update the check.
=> Update the check about coalesce

libvirt/tests/src/virtual_network/link_state/link_state_model_type.py
2 cases always failed due to not detected 'Link state yes' after domif-setlink. Add sleep before later checkings to wait it taking effect.
=> link_state_model_type:Sleep to wait setlink change

libvirt/tests/cfg/snapshot/delete_external_snap_with_references.cfg
it's related a bug, The bug is fixed now
```
avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 snapshot_delete..head_to_tail
(1/1) type_specific.io-github-autotest-libvirt.snapshot_delete.multiple_children.del_non_current_branch.head_to_tail: PASS (105.73 s)
```
=> enable one snap multi children case

libvirt/tests/cfg/graphics/graphics_functional.cfg, libvirt/tests/src/graphics/graphics_functional.py
Update case:
XXXX-34824 - [vnc] Start a guest with vnc port set to an out-of-range value
=> graphics: Update for vnc port

v2v/tests/src/function_test_esx.py
Only import ovirt module when necessary
=> v2v: fix ovirt module import issue

libvirt/tests/src/virsh_cmd/domain/virsh_emulatorpin.py
```
JOB LOG    : /var/log/avocado/job-results/job-2024-06-06T07.20-402657b/job.log
(1/1) type_specific.io-github-autotest-libvirt.virsh.emulatorpin.positive_testing.set_emulatorpin_parameter.running_guest.cpulist.emulatorpin_options.current.ranges.default: ERROR: invalid mode: 'rU' (7.97 s)
```
` (1/1) type_specific.io-github-autotest-libvirt.virsh.emulatorpin.positive_testing.set_emulatorpin_parameter.running_guest.cpulist.emulatorpin_options.current.ranges.default: PASS (7.99 s)`
=> virsh_emulatorpin: Fix ValueError: invalid mode: 'rU'

libvirt/tests/cfg/virsh_cmd/domain/virsh_managedsave.cfg
On s390x, there are no threads, the value must be 1.
=> managedsave_cpu_mode: fix for s390x

libvirt/tests/cfg/snapshot/revert_snap_for_guest_with_genid.cfg
&lt;genid&gt; is not supported on s390x. (s390x has no ACPI and is Big-Endian, no BIOS, no UEFI.) Disable the test.
=> snapshot_with_genid: not supported on s390x

libvirt/tests/cfg/snapshot/revert_snap_with_flags.cfg, libvirt/tests/src/snapshot/revert_snap_with_flags.py
On s390x, we don't have the vars file for secure boot. Don't check it.
Also, no nvram, so don't run that flag.
=> revert_snap_with_flags: skip secure boot check

libvirt/tests/src/virsh_cmd/domain/virsh_set_user_password.py
This case fail due to the fact that "openssl passwd -crypt %s" % new_passwd is not supported now, and use openssl passwd %s" % new_passwd directly
=> Fix virsh.set_user_password.normal_test.normal_user.encrypted

libvirt/tests/src/cpu/vcpu_nested.py
need to get vmxml again to get vmx
Before fixed
```
avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 vcpu_nested.positive_test.check_nested_capability --vt-connect-uri qemu:///system
(1/1) vcpu_nested.positive_test.check_nested_capability: ERROR: 'vmx' (154.23 s)
```
After fixed
```
avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 vcpu_nested.positive_test.check_nested_capability --vt-connect-uri qemu:///system
(1/1) type_specific.io-github-autotest-libvirt.vcpu_nested.positive_test.check_nested_capability: PASS (140.65 s)
```
=> fix not found vmx

libvirt/tests/cfg/virtual_network/passt/passt_transfer_file.cfg, libvirt/tests/src/virtual_network/passt/passt_transfer_file.py
Since passt support multipath route, resume the test in such situation. And get the guest interface name from the guest os instead of assume it since "acpi index" is not supported by aarch64.
=> Resume the test with ipv6 multipath route

libvirt/tests/cfg/virtual_network/update_device/update_iface_trustGuestRxFilters.cfg, libvirt/tests/src/virtual_network/update_device/update_iface_trustGuestRxFilters.py
- Add version check
- Add xml check after update-device
Test result:
```
(1/2) type_specific.io-github-autotest-libvirt.virtual_network.update_device.update_iface_trustGuestRxFilters.yes_to_no: PASS (60.01 s)
(2/2) type_specific.io-github-autotest-libvirt.virtual_network.update_device.update_iface_trustGuestRxFilters.no_to_yes:PAASS (59.83 s)
```
=> Fixup:trustGuestRxFilters:Add version check and xml check

libvirt/tests/cfg/snapshot/delete_disk_and_memory_snapshot.cfg, libvirt/tests/src/snapshot/delete_disk_and_memory_snapshot.py
xxxx-298193: Verify snapshot-delete disk and memory snapshot.
```
avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 snapshot_delete.disk_and_memory_snap
(1/2) type_specific.io-github-autotest-libvirt.snapshot_delete.disk_and_memory_snap.vm_running.qcow2_format: PASS (56.74 s)
(2/2) type_specific.io-github-autotest-libvirt.snapshot_delete.disk_and_memory_snap.vm_paused.qcow2_format: PASS (59.05 s)
```
=> add case for delete disk and memory snapshot

libvirt/tests/cfg/cpu/aarch64_cpu_sve.cfg, libvirt/tests/cfg/virtual_network/update_device/update_iface_trustGuestRxFilters.cfg, libvirt/tests/src/cpu/aarch64_cpu_sve.py, libvirt/tests/src/virtual_network/update_device/update_iface_trustGuestRxFilters.py
aarch64_cpu_sve: add more tests
- Refine the codes structure
- Dynamically test with all supported sve lengths instead of hardcodes
- Add sve stress test suite in vm
- Add optimized routines test suite in vm
- Add discontinuous enabled sve length test
=> aarch64_cpu_sve: update

v2v/tests/cfg/specific_kvm.cfg
Due to "Wont Do" resolution bugs, skip checking VM after conversion.
=> v2v: fix the failed cases of specific-kvm on rhel9.5

libvirt/tests/cfg/memory/memory_backing/hugepage_nodeset.cfg, libvirt/tests/src/memory/memory_backing/hugepage_nodeset.py, provider/memory/memory_base.py
Test results on multi arch:
x86_64:
(1/4) type_specific.io-github-autotest-libvirt.memory.backing.nodeset.with_numa.nodeset_0.2M: PASS (33.56 s)
(2/4) type_specific.io-github-autotest-libvirt.memory.backing.nodeset.with_numa.nodeset_not_exist.2M: PASS (7.83 s)
(3/4) type_specific.io-github-autotest-libvirt.memory.backing.nodeset.without_numa.nodeset_0.2M: PASS (47.99 s)
(4/4) type_specific.io-github-autotest-libvirt.memory.backing.nodeset.without_numa.nodeset_not_exist.2M: PASS (7.88 s)
aarch64 4k:
(1/8) type_specific.io-github-autotest-libvirt.memory.backing.nodeset.with_numa.nodeset_0.2M: PASS (41.69 s)
(2/8) type_specific.io-github-autotest-libvirt.memory.backing.nodeset.with_numa.nodeset_0.512M: CANCEL: Expected host default huge page size is 524288 KiB, but get 2048 (7.02 s)
(3/8) …
=> Add adaption to support different huge page size for multi arch

libvirt/tests/src/backingchain/blockcopy/blockcopy_with_async_option.py, provider/backingchain/check_functions.py
Need wait some time to check after blockcopy
` (1/1) type_specific.io-github-autotest-libvirt.backingchain.blockcopy.async_option.async: PASS (51.83 s)
`
=> fix incorrect source path after blockcopy

libvirt/tests/cfg/numa/guest_numa_topology/various_numa_topology_settings.cfg, libvirt/tests/src/numa/guest_numa_topology/various_numa_topology_settings.py
On aarch64 with pagesize=4K, the hugepages count is too small to start VM.
Before:
```
(1/1) type_specific.io-github-autotest-libvirt.guest_numa_topology.various_numa_topology_settings.discard_none.memaccess_none: ERROR: VM 'avocado-vt-vm1' failed to start: error: Failed to start domain 'avocado-vt-vm1'\nerror: internal error: process exited while connecting to monitor: 2024-05-30T09:26:58.786400Z qemu-kvm: unable to map backing store for guest RAM: Cannot allocate memory(... (62.76 s)
(1/1) type_specific.io-github-autotest-libvirt.guest_numa_topology.various_numa_topology_settings.discard_none.memaccess_shared: ERROR: VM 'avocado-vt-vm1' failed to start: error: Failed to start domain 'avocado-vt-vm1'\nerror: internal error: process exited …
```
=> numa: fix no enough memory

libvirt/tests/cfg/cpu/vcpu_misc.cfg
Test case "vcpu_misc.positive_test.with_maxphysaddr" fails with error:
VMIPAddressMissingError: No ipv4 DHCP lease for MAC 52:54:00:5c:26:e6&#10;
1) Create a vm xml that does not define the cpu. For example:
```
<domain type='kvm'>
<name>{{domain}}</name>
<memory unit='KiB'>1048576</memory>
<currentMemory unit='KiB'>1048576</currentMemory>
<vcpu placement='static'>1</vcpu>
<os>
<type arch='x86_64' machine='pc'>hvm</type>
<boot dev='hd'/>
</os>
<devices>
<emulator>/usr/libexec/qemu-kvm</emulator>
<disk type='file' device='disk'>
<driver name='qemu' type='qcow2' cache='none'/>
<source file='{{image_path}}'/>
<target dev='vda' bus='virtio'/>
</disk>
<interface type='bridge'>
<mac address='52:54:00:cb:dd:86'/>
<source bridge='virbr0'/>
<model type='virtio'/>
</interface>
<serial type='pty'/> …
```
=> vcpu_misc.cfg, fix for cpu model on maxphysaddr case

libvirt/tests/cfg/cpu/aarch64_cpu_sve.cfg, libvirt/tests/src/cpu/aarch64_cpu_sve.py
Add the error message checking when enable sve in a guest while the host does not support sve feature.
=> aarch64_cpu_sve: fix to add err msg checking

libvirt/tests/cfg/memory/virsh_setmem.cfg, libvirt/tests/src/memory/virsh_setmem.py
DMI/SMBIOS is not available on s390x.
Since be1f9b835b760973dbfe2fe73c4768a59044dc13 the test tries to install the package if the command is not available. However, it will retry on failure, per default for utils_package.PKG_MGR_TIMEOUT (5min) slowing down the test unnecessarily.
On s390x, just skip using dmidecode from the beginning.
Also, log more information when calculating memory deviation for debug and apply reformatting with 'black' for CI checks.
=> virsh_setmem: skip dmidecode on s390x

libvirt/tests/cfg/virtual_disks/vhostvdpa_block_backend_type/hotplug_vhostvdpa_backend_disk.cfg, libvirt/tests/src/virtual_disks/vhostvdpa_block_backend_type/hotplug_vhostvdpa_backend_disk.py
This PR adds:
VIRT-300429 - Hotplug&unplug disk of vhostvdpa backend
**Test results:** the failed case is due to a known issue.
```
(1/3) type_specific.io-github-autotest-libvirt.virtual_disks.vhostvdpa.hotplug.none: PASS (50.18 s)
(2/3) type_specific.io-github-autotest-libvirt.virtual_disks.vhostvdpa.hotplug.directsync: FAIL: Failed to check disk io for vdb! (49.92 s)
(3/3) type_specific.io-github-autotest-libvirt.virtual_disks.vhostvdpa.hotplug.no_specified_value: PASS (53.40 s)
```
=> virtual_disks: Add a vhostvdpa disk hotplug case

libvirt/tests/cfg/virtual_disks/vhostvdpa_block_backend_type/vm_lifecycle_vhostvdpa_backend_disk.cfg, libvirt/tests/src/virtual_disks/vhostvdpa_block_backend_type/vm_lifecycle_vhostvdpa_backend_disk.py
This PR adds:
VIRT-300443 - Vm lifecycle test with disk of vhostvdpa backend
` (1/1) type_specific.io-github-autotest-libvirt.virtual_disks.vhostvdpa.lifecycle: PASS (169.51 s)
`
=> virtual_disks: Add vm lifecycle test for vhostvdpa disk

libvirt/tests/cfg/snapshot/revert_disk_external_snap.cfg, libvirt/tests/src/snapshot/revert_disk_external_snap.py, provider/snapshot/snapshot_base.py
xxxx-16604: Revert guest to disk external snapshot
One error is an existing bug.
```
avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 snapshot_revert.disk_external_snap
(1/2) type_specific.io-github-autotest-libvirt.snapshot_revert.disk_external_snap.disk_only: ERROR: Command '/usr/bin/virsh snapshot-revert avocado-vt-vm1 s2 ' failed.\nstdout: b'\n'\nstderr: b"error: Failed to revert snapshot s2\nerror: internal error: Invalid target domain state 'disk-snapshot'. Refusing snapshot reversion\n"\nadditional_info: None (42.80 s)
(2/2) type_specific.io-github-autotest-libvirt.snapshot_revert.disk_external_snap.disk_and_memory: PASS
```
=> add case for revert disk external snapshot

libvirt/tests/cfg/snapshot/revert_snapshot_after_xml_updated.cfg, libvirt/tests/src/snapshot/revert_snapshot_after_xml_updated.py
xxxx-300471: Revert snapshots after the guest xml is updated
```
avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 snapshot_revert.xml_updated
(1/3) type_specific.io-github-autotest-libvirt.snapshot_revert.xml_updated.hotplug_disk: PASS (62.86 s)
(2/3) type_specific.io-github-autotest-libvirt.snapshot_revert.xml_updated.hotplug_vcpus: PASS (65.27 s)
(3/3) type_specific.io-github-autotest-libvirt.snapshot_revert.xml_updated.blkiotune: PASS (65.18 s)
```
=> add case for revert snap after the guest xml updated

libvirt/tests/src/graphics/graphics_functional.py
The virtqemud service restarts failed when testing vnc_only.vnc_tls_x509_verify related issues. That's because the vnc_tls_x509_verify in qemu_config will be deleted in the next "if vnc_tls_x509_secret_uuid == "not_set" statement. Here update it to the correct one vnc_tls_x509_secret_uuid.
=> graphical_framebuffers: fix virtqemud service failed issue with vnc_tls_x509_verify

libvirt/tests/cfg/snapshot/revert_snap_with_flags.cfg
Now the revert_snap_with_flags test can not be tested in x86 because no flags list in cfg file. Now add it to fix.
=> Snapshot_revert: fix "list index out of range" issue

libvirt/tests/cfg/memory/nvdimm.cfg, libvirt/tests/src/memory/nvdimm.py
pmem not support results:
(1/1) type_specific.io-github-autotest-libvirt.nvdimm.back_file.label.pmem_alignsize: PASS (47.91 s)
pmem support results:
(1/1) type_specific.io-github-autotest-libvirt.nvdimm.back_file.label.pmem_alignsize: PASS (49.21 s)
=> Add nvdimm pmem support check

libvirt/tests/src/virtual_disks/virtual_disks_multivms.py
By specifying label to gpt, instead of msdos
=> Fix mklabel issue in multple VMs case

libvirt/tests/cfg/sriov/vIOMMU/iommu_alias.cfg, libvirt/tests/cfg/sriov/vIOMMU/iommu_device_lifecycle.cfg, libvirt/tests/cfg/sriov/vIOMMU/iommu_device_settings.cfg, libvirt/tests/cfg/sriov/vIOMMU/virtio_iommu_with_addtional_attributes.cfg, libvirt/tests/src/sriov/vIOMMU/intel_iommu_aw_bits.py, libvirt/tests/src/sriov/vIOMMU/iommu_alias.py, libvirt/tests/src/sriov/vIOMMU/iommu_device_lifecycle.py, libvirt/tests/src/sriov/vIOMMU/iommu_device_settings.py, libvirt/tests/src/sriov/vIOMMU/virtio_iommu_with_addtional_attributes.py, provider/sriov/sriov_base.py, provider/viommu/viommu_base.py
Test results - aarch64- build 20: all passed in jenkins or on local machine
(1/1) type_specific.io-github-autotest-libvirt.vIOMMU.iommu_device_settings.virtio_muti_devices.vhost_on.smmuv3: PASS (84.02 s)
(1/1) type_specific.io-github-autotest-libvirt.vIOMMU.iommu_device_lifecycle.reboot_many_times.hostdev_iface.virtio: PASS (340.88 s)
Test results - x86_64- build 17: all passed in jenkins or on local machine except the last one(ip cmd timeout in guest, it's not related to this pr)
(1/1) type_specific.io-github-autotest-libvirt.sriov.plug_unplug.attach_detach_interface_special_situations.with_model: PASS (73.83 s)
(1/1) type_specific.io-github-autotest-libvirt.sriov.vm_lifecycle.reboot.hostdev_interface.vf_address.failover.with_iommu: PASS (288.50 s)
(1/2) …
=> Refactor vIOMMU test code

libvirt/tests/src/sriov/vIOMMU/migration_iommu_device.py
- https://github.com/autotest/tp-libvirt/pull/5711
```
(1/6) type_specific.io-github-autotest-libvirt.vIOMMU.migration.iommu_device.virtio_muti_devices.vhost_on.virtio: PASS (215.73 s)
(2/6) type_specific.io-github-autotest-libvirt.vIOMMU.migration.iommu_device.virtio_muti_devices.vhost_on.intel: PASS (366.61 s)
(3/6) type_specific.io-github-autotest-libvirt.vIOMMU.migration.iommu_device.virtio_muti_devices.vhost_off.virtio: PASS (212.62 s)
(4/6) type_specific.io-github-autotest-libvirt.vIOMMU.migration.iommu_device.virtio_muti_devices.vhost_off.intel: PASS (365.11 s)
(5/6) type_specific.io-github-autotest-libvirt.vIOMMU.migration.iommu_device.scsi_controller.virtio: PASS (213.75 s)
(6/6) type_specific.io-github-autotest-libvirt.vIOMMU.migration.iommu_devi …
```
=> Refactor iommu migration case

libvirt/tests/cfg/memory/memory_allocation/define_value_unit.cfg, libvirt/tests/src/memory/memory_allocation/define_value_unit.py
Test results:
x86_64:
(01/16) type_specific.io-github-autotest-libvirt.memory.allocation.define_value_unit.without_numa.positive_test.bytes: PASS (45.46 s)
(02/16) type_specific.io-github-autotest-libvirt.memory.allocation.define_value_unit.without_numa.positive_test.KB: PASS (47.45 s)
(03/16) type_specific.io-github-autotest-libvirt.memory.allocation.define_value_unit.without_numa.positive_test.KiB: PASS (45.58 s)
(04/16) type_specific.io-github-autotest-libvirt.memory.allocation.define_value_unit.without_numa.positive_test.MB: PASS (45.54 s)
aarch64 64k:
(01/16) type_specific.io-github-autotest-libvirt.memory.allocation.define_value_unit.without_numa.positive_test.bytes: PASS (45.95 s)
(02/16) type_specific.io-github-autotest-libvirt.memory.allocation.define_value_unit.without_numa.posit …
=> Change memory verification to adapt to different page size

provider/interface/vdpa_base.py
` (1/1) type_specific.io-github-autotest-libvirt.virtual_network.connectivity_check.vdpa_interface.driver_queues.page_per_vq.mellanox:FAIL: The multiplier should be 00001000, but got <-s 01:00.0 | awk -F '=' '/multiplier=/ {print $NF}'\n00001000. (69.87 s)`
` (1/1) type_specific.io-github-autotest-libvirt.virtual_network.connectivity_check.vdpa_interface.driver_queues.page_per_vq.mellanox: PASS (91.64 s)
`
=> vdpa: Fix an issue due to cmd output change

libvirt/tests/cfg/memory/memory_misc.cfg
The disk cache result would be more close to the result from real-time counting value.
result:
(1/1) type_specific.io-github-autotest-libvirt.memory_misc.dommemstat.disk_caches: PASS (31.32 s)
=> Decrease memory balloon period to make memory info collection more frequent

libvirt/tests/cfg/memory/memory_misc.cfg, libvirt/tests/src/memory/memory_misc.py
Test results:
x86_64:
(1/1) type_specific.io-github-autotest-libvirt.memory_misc.memorybacking.no_mem_backing.4k.2048: PASS (9.35 s)
(1/2) type_specific.io-github-autotest-libvirt.memory_misc.memorybacking.nodeset_specified.nodeset_0.4k.1048576:PASS (8.17 s)
(2/2) type_specific.io-github-autotest-libvirt.memory_misc.memorybacking.nodeset_specified.nodeset_01.4k.1048576: PASS (8.26 s)
(1/1) type_specific.io-github-autotest-libvirt.memory_misc.memorybacking.mount_hp_running_vm.4k.2048.1048576: PASS (55.11 s)
(1/1) type_specific.io-github-autotest-libvirt.memory_misc.memorybacking.hp_from_2_numa_nodes.4k.2048: PASS (11.37 s)
aarch64 64k:
(1/2) type_specific.io-github-autotest-libvirt.memory_misc.memorybacking.no_mem_backing.4k.2048: CANCEL: Expected host default page size is 4 KiB, but get …
=> Memory misc add multi huge page size config

libvirt/tests/cfg/memory/memory_backing/discard_memory_content_setting.cfg, libvirt/tests/cfg/memory/memory_backing/hugepage_mount_path.cfg, libvirt/tests/cfg/memory/memory_backing/memory_access_mode.cfg, libvirt/tests/cfg/memory/memory_backing/memory_source_and_allocation.cfg, libvirt/tests/cfg/memory/memory_backing/page_locking_and_shared_pages.cfg, libvirt/tests/src/memory/memory_backing/discard_memory_content_setting.py, libvirt/tests/src/memory/memory_backing/hugepage_mount_path.py, libvirt/tests/src/memory/memory_backing/memory_access_mode.py, libvirt/tests/src/memory/memory_backing/memory_source_and_allocation.py, libvirt/tests/src/memory/memory_backing/page_locking_and_shared_pages.py
Test results:
x86_64:
(01/84) type_specific.io-github-autotest-libvirt.memory.backing.access_mode.memory_allocation.without_hugepage.numa_access_private.mem_access_private.file.4k.2048: PASS (49.63 s)
(02/84) type_specific.io-github-autotest-libvirt.memory.backing.access_mode.memory_allocation.without_hugepage.numa_access_private.mem_access_private.anonymous.4k.2048: PASS (49.95 s)
(03/84) type_specific.io-github-autotest-libvirt.memory.backing.access_mode.memory_allocation.without_hugepage.numa_access_private.mem_access_private.memfd.4k.2048: PASS (49.74 s)
(04/84) type_specific.io-github-autotest-libvirt.memory.backing.access_mode.memory_allocation.without_hugepage.numa_access_private.mem_access_private.no_source.4k.2048: PASS (49.98 s)
aarch64 64k:
(001/168) …
=> Memory backing related cases change huge page mult arch config

libvirt/tests/cfg/virtual_network/qos/check_bandwidth_by_domiftune.cfg, libvirt/tests/src/virtual_network/qos/check_bandwidth_by_domiftune.py
- VIRT-299277 - [Qos][domiftune] Check and tune the bandwidth of a interface via domiftune
Depends on:
- https://github.com/avocado-framework/avocado-vt/pull/3936
Test result:
```
(1/3) type_specific.io-github-autotest-libvirt.virtual_network.qos.check_bandwidth_by_domiftune.nat: PASS (51.51 s)
(2/3) type_specific.io-github-autotest-libvirt.virtual_network.qos.check_bandwidth_by_domiftune.direct: PASS (51.06 s)
(3/3) type_specific.io-github-autotest-libvirt.virtual_network.qos.check_bandwidth_by_domiftune.br: PASS (68.64 s)
```
=> Add network case of qos

libvirt/tests/cfg/guest_os_booting/boot_order/boot_from_cdrom_device.cfg, libvirt/tests/src/guest_os_booting/boot_order/boot_from_cdrom_device.py
Update to check ouput during os startup, because some cases will enter to uefi shell instead of os system in aarch64.
```
(1/7) type_specific.io-github-autotest-libvirt.guest_os_booting.boot_order.cdrom_device.ovmf.os_dev.without_cdrom: PASS (41.01 s)
(2/7) type_specific.io-github-autotest-libvirt.guest_os_booting.boot_order.cdrom_device.ovmf.os_dev.with_cdrom_with_no_src: PASS (19.52 s)
(3/7) type_specific.io-github-autotest-libvirt.guest_os_booting.boot_order.cdrom_device.ovmf.os_dev.with_cdrom: PASS (23.18 s)
(4/7) type_specific.io-github-autotest-libvirt.guest_os_booting.boot_order.cdrom_device.ovmf.os_dev.multi_cdroms: PASS (268.16 s)
(5/7) type_specific.io-github-autotest-libvirt.guest_os_booting.boot_order.cdrom_device.ovmf.cdrom_boot_order.with_cdrom_with_no_src: …
```
=> guest_os_booting: Fix up issues of entering uefi shell

libvirt/tests/src/virsh_cmd/host/virsh_capabilities.py
- New scenario to check host cpu topology in capabilities output 
including die_id, socket_id, cluster_id, core_id and siblings
- Refine the code structure for better readability
Case ID: XXX-300596
=> virsh_capabilities: add case to check cpu topo

libvirt/tests/cfg/guest_os_booting/boot_order/boot_from_usb_device.cfg, libvirt/tests/src/guest_os_booting/boot_order/boot_from_usb_device.py
A test related to boot_from_usb_device.py would not pass:
guest_os_booting.boot_order.usb_device.hostdev_device
The test would fail with the following error message
```
LibvirtXMLError: Failed to define avocado-vt-vm1 for reason:error: Failed to define domain from /tmp/xml_utils_temp_l7acogze.xmlerror: unsupported configuration: BIOS serial console only supported on x86 architectures&#10;
```
This test would not pass for two reasons
1) the 'bios_useserial' flag is not compatible with aarch64/edk2
2) The UEFI prints a different string on aarch64 than it does on other platforms. The test looks at this output, so this is bad.
Redefine check_prompt and bootmenu_dict in the *.cfg file.
Console output from hostdev_device passing:
```
(.libvirt-ci-venv-ci-runtest-V9zHvu) …
```
=> boot_from_usb_device: Fix bios serial console unsupported on arm

provider/vfio/ccw.py
Add a "udevadm settle" between the dasdfmt and fdasd
This can help prevent error "DASD /dev/dasda is in use. Unmount it first!"
=> Add a "udevadm settle" between the dasdfmt and fdasd

libvirt/tests/src/controller/controller_functional.py
before fixing
```
LibvirtXMLNotFoundError: Error in Getter for property &quot;address&quot;, element tag &quot;address&quot; not found on parent at xpath &quot;/&quot; in XML&lt;controller type=&quot;pci&quot; index=&quot;0&quot; model=&quot;pcie-root&quot; /&gt;&#10;
```
after fixing
```
avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 controller.functional.positive_tests.pcie_root_children --vt-connect-uri qemu:///system
(1/1) type_specific.io-github-autotest-libvirt.controller.functional.positive_tests.pcie_root_children: PASS (27.67 s)
```
All Other influenced case
```
avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 controller.functional
(01/31) type_specific.io-github-autotest-libvirt.controller.functional.positive_tests.pcie_root: …
```
=> fix controller case use elem.address while no  addr ele

libvirt/tests/src/event/virsh_event.py
From libvirt-9.1, iTCO watchdog are the default watchdog device for q35 guests. The default expirt time of iTCO watchdog are about 60s. As for the event case, we just need to verify that there would be corresponding watchdog events after we trigger the watchdog. It has nothing to do with how much time watchdog devices need to expire. So I extend the watchdog expirt time here.
=> Modify the watchdog expire time

libvirt/tests/src/scsi/scsi_device.py
The error of "error: cannot open directory '/sys/bus/scsi/devices/11:0:0:0/scsi_generic': No such file or directory" is caused by the missing sg module. So add it in script.
=> Virtual_disk: fix no scsi_generic file issue

libvirt/tests/src/passthrough/ccw/libvirt_ccw_passthrough.py
The device_remove test case sometimes still fails. Instead now allow for up to 10 seconds for device to appear and instead use wait_for.
=> libvirt_ccw_passthrough: use wait_for instead of sleep

libvirt/tests/cfg/virtual_disks/virtual_disks_multiattributes.cfg, libvirt/tests/src/virtual_disks/virtual_disks_multiattributes.py
These two cases are to match the cnv scenarios: VIRT-300872 and VIRT-300727.
=> virtual_disk: add new cases for starting guest with multiple driver attributes

libvirt/tests/cfg/migration_with_copy_storage/migrate_disks.cfg, libvirt/tests/cfg/snapshot/revert_snap_for_guest_with_genid.cfg
=> migrate_disks: skip sata case

libvirt/tests/cfg/memory/memory_devices/change_virtio_mem_request_size.cfg, libvirt/tests/src/memory/memory_devices/change_virtio_mem_request_size.py
1. add adaption for aarch64 4k kernel
2. remove kernel parameter change for shut off guest
3. results:
3.1 x86_64
(01/20) type_specific.io-github-autotest-libvirt.memory.devices.virtio_mem.change_memory.file.normal_requested.running_guest: PASS (215.76 s)
(02/20) type_specific.io-github-autotest-libvirt.memory.devices.virtio_mem.change_memory.file.zero_requested.running_guest: PASS (205.89 s)
(03/20) type_specific.io-github-autotest-libvirt.memory.devices.virtio_mem.change_memory.file.bigger_requested.running_guest: PASS (204.23 s)
(04/20) type_specific.io-github-autotest-libvirt.memory.devices.virtio_mem.change_memory.file.not_mutiple_of_block_requested.running_guest: PASS (205.36 s)
(05/20) type_specific.io-github-autotest-libvirt.memory.devices.virtio_mem.change_memory.hugepages.normal_ …
=> Add adaption for aarch64 4k kernel

libvirt/tests/src/sriov/vIOMMU/iommu_device_lifecycle.py
There might be some other outputs after showing 'login:', so update the pattern for checking vm reboot.
` (1/1) type_specific.io-github-autotest-libvirt.vIOMMU.iommu_device_lifecycle.reboot_many_times.hostdev_iface.virtio: ERROR: Timeout expired while looking for pattern '[Ll]ogin:\\s*$'    (output: 'shutdown -r now\n[root@localhost ~]# [   34.816260] vda2: Can\'t mount, would change RO state\n[\x1b[0;32m  OK  \x1b[0m] Started \x1b[0;1;39mShow Plymouth Reboot Screen\x1b[0m.\n[\x1b... (403.37 s)`
` (1/1) type_specific.io-github-autotest-libvirt.vIOMMU.iommu_device_lifecycle.reboot_many_times.hostdev_iface.virtio: PASS (317.94 s)`
=> vIOMMU: Fixup a timeout issue

libvirt/tests/src/sriov/vIOMMU/attach_iommu_device.py
Feature changed to support iommu device cold plug, so update the code.
```
libvirt-10.5.0-1
(1/4) type_specific.io-github-autotest-libvirt.vIOMMU.attach_iommu_device.cold_plug.virtio:PASS (7.86 s)
(2/4) type_specific.io-github-autotest-libvirt.vIOMMU.attach_iommu_device.cold_plug.intel: PASS (8.09 s)
(3/4) type_specific.io-github-autotest-libvirt.vIOMMU.attach_iommu_device.hot_plug.virtio: PASS (36.46 s)
(4/4) type_specific.io-github-autotest-libvirt.vIOMMU.attach_iommu_device.hot_plug.intel: PASS (40.25 s)
(1/4) type_specific.io-github-autotest-libvirt.vIOMMU.attach_iommu_device.cold_plug.virtio: PASS (5.01 s)
(2/4) type_specific.io-github-autotest-libvirt.vIOMMU.attach_iommu_device.cold_plug.smmuv3: PASS (5.06 s)
(3/4) …
```
=> vIOMMU: Update iommu cold plug cases

libvirt/tests/src/memory/memory_backing/lifecycle_for_hugepage.py
give login when first start domain
Before fix
`CmdError: Command '/usr/bin/virsh save avocado-vt-vm1 /tmp/guest.save ' failed.stdout: b'\n'stderr: b&quot;error: Failed to save domain 'avocado-vt-vm1' to /tmp/guest.save\nerror: operation failed: domain is not running\n&quot;additional_info: None&#10;`
After fix
```
avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 memory.backing.lifecycle.memory_hugepage.default_hugepage_size --vt-connect-uri qemu:///system
(1/1) type_specific.io-github-autotest-libvirt.memory.backing.lifecycle.memory_hugepage.default_hugepage_size: PASS (115.52 s)
```
=> fix not running error when save domain

libvirt/tests/src/virsh_cmd/domain/virsh_guestinfo.py
The output of ip command in the VM needs to be updated to avoid format issues.
` (1/1) type_specific.io-github-autotest-libvirt.virsh.guestinfo.positive.interface_info: FAIL: The interface info get from guestinfo cmd is not correct. (70.07 s)`
(1/1) type_specific.io-github-autotest-libvirt.virsh.guestinfo.positive.interface_info: PASS (62.25 s)
=> virsh_guestinfo: Remove color of "ip" output

libvirt/tests/cfg/event/virsh_event.cfg
The kill_qemu test case sends a SIGKILL signal to qemu, then checks to make sure the signal is properly detected
Killing qemu sometimes results in corruption of the qcow2 image in the form of leaked clusters. This is a natural side effect of the test. So, this should not result in a test failure
Suppress the error by setting the skip_cluster_leak_warn option to "yes"
Evidence the kill_qemu case still passes
```
(.libvirt-ci-venv-ci-runtest-NogP17) [root@ampere-mtsnow-altra-02 tp-libvirt]# avocado run --vt-type libvirt --vt-machine-type arm64-mmio --test-runner=runner virsh.event.positive_test.virsh_event.test_events.lifecycle_events.kill_qemu
No python imaging library installed. Screendump and Windows guest BSOD detection are disabled. In order to enable it, please install python-imaging …
```
=> virsh_event: Fix leaked cluster error on kill_qemu

libvirt/tests/cfg/numa/guest_numa.cfg, libvirt/tests/src/numa/guest_numa.py
test results:
on x86:
(01/64) type_specific.io-github-autotest-libvirt.guest_numa.possitive_test.hugepage.per_node.2M.topology.no_numatune_memnode.numatune_mem: PASS (49.22 s)
(02/64) type_specific.io-github-autotest-libvirt.guest_numa.possitive_test.hugepage.per_node.2M.topology.no_numatune_memnode.no_numatune_mem: PASS (49.89 s)
(03/64) type_specific.io-github-autotest-libvirt.guest_numa.possitive_test.hugepage.per_node.2M.topology.numatune_memnode.m_strict.numatune_mem: PASS (47.79 s)
(04/64) type_specific.io-github-autotest-libvirt.guest_numa.possitive_test.hugepage.per_node.2M.topology.numatune_memnode.m_strict.no_numatune_mem: PASS (49.40 s)
(05/64) type_specific.io-github-autotest-libvirt.guest_numa.possitive_test.hugepage.per_node.2M.topology.numatune_memnode.m_preferred.numatune_m …
=> guest numa add aarch64 hugep page adaption

libvirt/tests/cfg/virtual_network/attach_detach_device/attach_user_type_iface.cfg, libvirt/tests/src/virtual_network/attach_detach_device/attach_user_type_iface.py, provider/virtual_network/network_base.py
- VIRT-296615 - [attach-device][user][slirp] attach-device with user type interface
Test result:
```
(1/2) type_specific.io-github-autotest-libvirt.virtual_network.attach_device.user_type_iface.root_user: PASS (63.72 s)
(2/2) type_specific.io-github-autotest-libvirt.virtual_network.attach_device.user_type_iface.non_root_user: PASS (69.04 s)
```
=> Add new network case of attach user type interface

libvirt/tests/cfg/guest_os_booting/boot_order/boot_from_usb_device.cfg, libvirt/tests/src/guest_os_booting/boot_order/boot_from_usb_device.py
boot_from_usb_device: Package is not installed
Regardless of which subtest is run, boot_from_usb_device checks for the existence of usbredirdev and lsusb. 
This check is not required for the block_device test, but block_device still checks for it. This results in a fail on platforms that do not support usbredirdev, such as aarch64.
Parameterize the test, so that each subtest can specify a list of required commands. 
This way block_device and usbredirdev tests can specify their required packages individually. And the lack of a required command for redirdev will not fail block_device
Evidence that block_device passes on aarch64
```
(.libvirt-ci-venv-ci-runtest-JFpiaA) [root@ampere-mtsnow-altramax-52 avocado-vt]# avocado run --vt-type libvirt --vt-machine-type arm64-mmio --test-runner=runner …
```
=> boot_from_usb_device: fix incorrect package checking

libvirt/tests/cfg/memory/memory_devices/dimm_memory_with_memory_alloccation_and_numa.cfg, libvirt/tests/src/memory/memory_devices/dimm_memory_with_memory_alloccation_and_numa.py
latest libvirt add error prompt for cold-plugging memory device without numa node config, so add code adaption
results:
(01/31) type_specific.io-github-autotest-libvirt.memory.devices.dimm.memory_allocation_and_numa.init_define_with_dimm.no_numa.no_maxmemory: PASS (6.51 s)
(02/31) type_specific.io-github-autotest-libvirt.memory.devices.dimm.memory_allocation_and_numa.init_define_with_dimm.no_numa.no_slot: PASS (6.61 s)
(03/31) type_specific.io-github-autotest-libvirt.memory.devices.dimm.memory_allocation_and_numa.init_define_with_dimm.no_numa.with_slot: PASS (8.23 s)
(04/31) type_specific.io-github-autotest-libvirt.memory.devices.dimm.memory_allocation_and_numa.init_define_with_dimm.with_numa.no_maxmemory: PASS (6.66 s)
(05/31) type_specific.io-github-autotest-libvirt.memory.devices.dimm.m …
=> Fix err prompt for no numa node in memory device xml

libvirt/tests/cfg/virtual_network/driver/check_vhost_cpu_affinity_with_emulatorpin.cfg, libvirt/tests/src/virtual_network/driver/check_vhost_cpu_affinity_with_emulatorpin.py
- VIRT-300725 - [cgroup][vhost] Check the vhost* thread's cpu affinity with emulatorpin setting
Test result:
PASS 1-type_specific.io-github-autotest-libvirt.virtual_network.check_vhost_cpu_affinity_with_emulatorpin
=> Add case of cgroup vhost

libvirt/tests/cfg/snapshot/revert_snap_with_flags.cfg
On aarm64, the default nvram file name is different from the one on x86_64.
=> revert_snap_with_flags: fix incorrect nvram file on arm

libvirt/tests/cfg/vm_start_destroy_repeatedly.cfg, libvirt/tests/src/vm_start_destroy_repeatedly.py
Add test for vm start and destroy reliability
Add test vm_startup_reliability. The test follows this procedure
1. Start the vm
2. Verify the vm is alive
3. Log into the vm
4. Log out of the vm
5. Destroy the vm
6. Repeat steps 1-5 128 times
```
avocado run --vt-type libvirt --test-runner=runner vm_startup_reliability
JOB ID     : bdc8c6351bfc354a25af338c85c0cf603ec9645d
JOB LOG    : /var/log/avocado/job-results/job-2024-06-21T13.56-bdc8c63/job.log …
```
=> vm_start_destroy_repeatedly: VM Reliability Test

libvirt/tests/cfg/virtual_network/passt/passt_transfer_file.cfg
In this case, we need to create a temporary file to test the file transfer function. The original /tmp directroy is not enough some times since we need to creat 1G file. So update the file path to be under "/".
=> Update the file path to "/"

libvirt/tests/src/virtual_network/passt/passt_attach_detach.py, libvirt/tests/src/virtual_network/passt/passt_connectivity_between_2vms.py, libvirt/tests/src/virtual_network/passt/passt_reconnect.py
Some passt related cases failed since login timeout issue. It's beacuase the serial login sendkey which paused booting. Sleep 5s in these cases to skip the interruption.
=> Fix the login timeout issue

libvirt/tests/cfg/memory/memory_devices/virtio_mem_hotplug.cfg, libvirt/tests/src/memory/memory_devices/virtio_mem_hotplug.py
xxxx-300399: Virtio-mem memory device hot-plug
```
avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 memory.devices.virtio_mem.hotplug
(1/4) type_specific.io-github-autotest-libvirt.memory.devices.virtio_mem.hotplug.target_and_address: PASS (72.35 s)
(2/4) type_specific.io-github-autotest-libvirt.memory.devices.virtio_mem.hotplug.source_mib_and_hugepages: PASS (87.27 s)
(3/4) type_specific.io-github-autotest-libvirt.memory.devices.virtio_mem.hotplug.plug_exceeded_max_mem: PASS (75.12 s)
(4/4) type_specific.io-github-autotest-libvirt.memory.devices.virtio_mem.hotplug.duplicate_addr: PASS (84.02 s)
```
=> add case for virtio memory hotplug

libvirt/tests/cfg/memory/memory_devices/dimm_memory_hot_unplug.cfg, libvirt/tests/src/memory/memory_devices/dimm_memory_hot_unplug.py
xxxx-300403:Verify dimm memory device hot-unplug with different configs
```
avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 memory.devices.dimm.hot_unplug
(1/5) type_specific.io-github-autotest-libvirt.memory.devices.dimm.hot_unplug.default_mem.target_and_address: PASS (42.97 s)
(2/5) type_specific.io-github-autotest-libvirt.memory.devices.dimm.hot_unplug.default_mem.source_and_mib: PASS (40.64 s)
(3/5) type_specific.io-github-autotest-libvirt.memory.devices.dimm.hot_unplug.default_mem.unexisted_device: PASS (39.48 s)
(4/5) type_specific.io-github-autotest-libvirt.memory.devices.dimm.hot_unplug.online_movable_mem.target_and_address: PASS (187.86 s)
(5/5) type_specific.io-github-autotest-libvirt.memory.devices.dimm.hot_unplug. …
```
=> add case for dimm hot unplug

libvirt/tests/cfg/security/rng/libvirt_rng.cfg, libvirt/tests/src/security/rng/libvirt_rng.py
xxxx-17255 Snapshot of shutoff guest with random backend virtio-rng device. -- Use external snapshots in all steps instead of internal snapshot.
```
avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 libvirt_rng.rng_snapshot.back_rdm.snapshot_shutoff.device_assign
(1/1) type_specific.io-github-autotest-libvirt.libvirt_rng.rng_snapshot.back_rdm.snapshot_shutoff.device_assign: PASS (73.95 s)
```
Other related
```
avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 libvirt_rng
[root@dell-per740-08 tp-libvirt]# avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 libvirt_rng
(01/38) type_specific.io-github-autotest-libvirt.libvirt_rng.backend_builtin.hotplug_unplug.positive.no_options: PASS …
```
=> update internal snapshot with external snapshot

libvirt/tests/cfg/serial/serial_pty_log.cfg, libvirt/tests/src/serial/serial_pty_log.py
login prompt is changing
```
avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 serial.pty.log
(1/2) type_specific.io-github-autotest-libvirt.serial.pty.log.file: PASS (52.60 s)
(2/2) type_specific.io-github-autotest-libvirt.serial.pty.log.logd: PASS (56.60 s)
```
=> fix serial pty log case not found vm login prompt

libvirt/tests/cfg/memory/memory_devices/virtio_mem_hot_unplug.cfg, libvirt/tests/src/memory/memory_devices/virtio_mem_hot_unplug.py, provider/memory/memory_base.py
xxxx-300401:Virtio-mem memory device hot-unplug
Depend on https://github.com/avocado-framework/avocado-vt/pull/3941
x86+rhel9
```
avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 memory.devices.virtio_mem.hot_unplug
(1/9) type_specific.io-github-autotest-libvirt.memory.devices.virtio_mem.hot_unplug.detach.target_and_address: PASS (169.13 s)
(2/9) type_specific.io-github-autotest-libvirt.memory.devices.virtio_mem.hot_unplug.detach.source_mib_and_hugepages: PASS (186.35 s)
(3/9) type_specific.io-github-autotest-libvirt.memory.devices.virtio_mem.hot_unplug.detach.nonexistent_mem: PASS (183.88 s)
(4/9) type_specific.io-github-autotest-libvirt.memory.devices.virtio_mem.hot_unplug.detach.none_zero_current: PASS (183.64 s)
(5/9) …
```
=> add case for virtio memory hot unplug

libvirt/tests/cfg/memory/memory_devices/virtio_mem_dynamic_slots.cfg, libvirt/tests/src/memory/memory_devices/virtio_mem_dynamic_slots.py
xxxx-300535:Dynamic memory slots for virtio-mem device
Depend on https://github.com/avocado-framework/avocado-vt/pull/3934
```
avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 memory.devices.virtio_mem.dynamic_slots
(01/12) type_specific.io-github-autotest-libvirt.memory.devices.virtio_mem.dynamic_slots.default_mb.undefined_dynamic_memory_slots.basic_virtio: PASS (72.83 s)
(02/12) type_specific.io-github-autotest-libvirt.memory.devices.virtio_mem.dynamic_slots.default_mb.enable_dynamic_memory_slots.basic_virtio: PASS (98.43 s)
(03/12) type_specific.io-github-autotest-libvirt.memory.devices.virtio_mem.dynamic_slots.default_mb.disable_dynamic_memory_slots.basic_virtio: PASS (73.02 s)
(04/12) …
```
=> add case for virtio memory dynamic slots

v2v/tests/cfg/function_test_esx.cfg
=> v2v: only support 32 disks for v2v to rhev

libvirt/tests/cfg/cpu/vcpu_misc.cfg, libvirt/tests/src/cpu/vcpu_misc.py
add --memspec MEM_FILE when virsh snapshot-create-as
```
avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 vcpu_misc.positive_test.snapshot 
(1/1) type_specific.io-github-autotest-libvirt.vcpu_misc.positive_test.snapshot: PASS (75.38 s)
```
Other related
```
avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 vcpu_misc
(1/8) type_specific.io-github-autotest-libvirt.vcpu_misc.positive_test.snapshot: PASS (82.98 s)
(2/8) type_specific.io-github-autotest-libvirt.vcpu_misc.positive_test.vendor_id: PASS (53.61 s)
(3/8) type_specific.io-github-autotest-libvirt.vcpu_misc.positive_test.with_topology.vcpus_max_equal_topology: PASS (130.55 s)
(4/8) type_specific.io-github-autotest-libvirt.vcpu_misc.positive_test.mode …
```
=> add mem file for vcpu_misc: snapshot scenario

libvirt/tests/cfg/virtual_network/update_device/update_iface_with_unchangable.cfg, libvirt/tests/src/virtual_network/update_device/update_iface_with_unchangable.py
- VIRT-294999 - [update-device][link state] update link state with other exsiting unchangable configuration
Test result:
(1/1) type_specific.io-github-autotest-libvirt.virtual_network.update_device.with_unchangable: PASS (36.19 s)
=> Add new case of update iface with unchangable config

libvirt/tests/cfg/virtual_disks/virtual_disks_discard_no_unref.cfg, libvirt/tests/src/virtual_disks/virtual_disks_discard_no_unref.py
Automate cases of discard_no_unref attribute: VIRT-301646 VIRT-301647 VIRT-301651
=> Virtual_disk: add new cases for disk driver discard_no_unref attribute

libvirt/tests/src/virsh_cmd/nodedev/virsh_nodedev_list.py
after libvirt-10.5.0, virsh nodedev list will list out all ccw devices regardless of device state
=> Fix virsh nodedev list failure on s390x

v2v/tests/src/function_test_esx.py
Fix failed func cases. No "enable" option on rhel10.
Error: Unknown command: enable
=> v2v: fix verify_certificate func case on rhel10

libvirt/tests/src/migration/live_migration.py, libvirt/tests/src/migration/migrate_event.py, libvirt/tests/src/migration/migrate_service_control.py, libvirt/tests/src/migration/migrate_with_various_hostname.py, provider/migration/base_steps.py, provider/migration/migration_base.py
TypeError: do_migration() got an unexpected keyword argument 'vm'
=> migration: Fix parameters issue

libvirt/tests/cfg/virtual_device/filesystem_device.cfg, libvirt/tests/src/virtual_device/filesystem_device.py
1. For bug RHEL-7108, virtiofsd options format has been updated, we need to update the script.
2. In the commit for fix bug RHEL-7108, lock options are not allowed to config any more, so we need to remove them thoroughly.
3. Cache mode "none" can not be used from virtiofsd-1.11.1, it should be replaced as "never" from now on. RFE bug about mode "never" will be filed later.
=> Update the lock options and virtiofsd options format

v2v/tests/cfg/convert_from_file.cfg, v2v/tests/cfg/function_test_esx.cfg
Please refer bz#1541908. 
* Output to RHV would create the required metadata (<rasd:num_of_sockets> etc) for topology.  But the CPU vendor
and model cannot be passed to RHV.
*Use virt-v2v to convert guest to libvirt, and check cpu info in guest xml after conversion,v2v could parse guest's cpu topology in guest xml correctly
=> v2v: fix cpu-topology case on rhel10

v2v/tests/cfg/function_test_esx.cfg
update the newer version for ogac and check bz#1580452 for without_default_net
=> v2v: fix ogac and without_default_net cases on functional testing

libvirt/tests/cfg/libvirt_hooks.cfg, libvirt/tests/src/libvirt_hooks.py
Since a recent libvirt commit, the hook log for the hook "release end" provides a reason for the release.
```
/etc/libvirt/hooks/qemu guest_name release end <shutoff-reason>
```
The test currently looks for a logline that does not provide a reason for release. This appears like this:
```
/etc/libvirt/hooks/qemu guest_name release end -
```
This results in the test failing if a reason is provided. E.G. the test will fail if this log line is given:
```
/etc/libvirt/hooks/qemu guest_name release end shutdown
```
Alter test such that it only looks for "release end shutdown"
Console output showing this test passing
```
(.libvirt-ci-venv-ci-runtest-IDDz4J) [root@ampere-mtsnow-altramax-48 tp-libvirt]# avocado run --vt-type libvirt --vt-machine-type arm64-mmio --test-runner=runner …
```
=> libvirt_hooks.py: Fix string matching

libvirt/tests/cfg/memory/memory_devices/dimm_memory_hot_unplug.cfg, libvirt/tests/cfg/memory/memory_devices/dimm_memory_with_access_and_discard.cfg, libvirt/tests/cfg/memory/memory_devices/dimm_memory_with_auto_placement_numatune.cfg, libvirt/tests/cfg/memory/memory_devices/virtio_mem_access_and_discard.cfg
On s390x memory devices are not available. Disable test cases.
=> memory: disable memory device tests on s390x

libvirt/tests/src/passthrough/ap/libvirt_ap_passthrough_autostart.py, spell.ignore
Previously, the device was available immediately after login. Now, it can take another second. Expect a maximum of 5seconds for it to come up.
=> libvirt_ap_passthrough/autostart: wait for device come up

libvirt/tests/cfg/memory/memory_devices/dimm_memory_with_access_and_discard.cfg, libvirt/tests/src/memory/memory_devices/dimm_memory_with_access_and_discard.py
xxx-299048:Dimm memory device with access and discard settings
```
avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35  memory.devices.dimm.access_and_discard
(01/18) type_specific.io-github-autotest-libvirt.memory.devices.dimm.access_and_discard.cold_plug.undefined.file: PASS (118.76 s)
(02/18) type_specific.io-github-autotest-libvirt.memory.devices.dimm.access_and_discard.cold_plug.undefined.anonymous: PASS (121.92 s)
(03/18) type_specific.io-github-autotest-libvirt.memory.devices.dimm.access_and_discard.cold_plug.undefined.memfd: PASS (116.99 s)
(04/18) type_specific.io-github-autotest-libvirt.memory.devices.dimm.access_and_discard.cold_plug.shared_and_discard.file: PASS (122.33 s)
(05/18) …
```
=> add refining steps for dimm with access and discrad scenario

libvirt/tests/cfg/storage/virsh_pool.cfg, libvirt/tests/deps/cve_2023_3750.sh
Parallel package sometimes is not included in the new compose. So use xargs to have a stable test for this case.
=> storage_ceph: use xargs instead of parallel as a tool of parallel testing

.github/workflows/ci.yml, requirements-travis.txt
The systems can't be set up anymore for python versions
since 3.8. Update depdendencies.
There will be a later pylint version producing new errors.
Ignore these as we didn't check them before.
Update pip to latest to avoid other dependency issues.
Allow for pylint to exit with code 32 if there are no files to
check. Otherwise the build will fail.
For that, the exit-on-error must be temporarily switched off (set +e)
in the run commands.
=> requirements-travis: fix dependencies

libvirt/tests/cfg/virtio/virtio_page_per_vq.cfg, libvirt/tests/cfg/virtual_device/filesystem_device_unprivileged.cfg, libvirt/tests/src/virtio/virtio_page_per_vq.py
1. In the commit for fix bug RHEL-7108, lock options are not allowed to config any more, so we need to remove them thoroughly.
2. Cache mode "none" can not be used from virtiofsd-1.11.1, it should be replaced as "never" from now on.
3. syntax of test.log need to be updated, or it will report error like: "TypeError: not enough arguments for format string"
=> Remove lock options and update cache mode

libvirt/tests/src/virtual_network/update_device/update_iface_qos.py
Missing `:` from tc command
Test result:
```
(1/4) type_specific.io-github-autotest-libvirt.virtual_network.update_device.iface_qos.net_iface_default_net.update-device.delete.inbound_outbound: PASS (38.49 s)
(2/4) type_specific.io-github-autotest-libvirt.virtual_network.update_device.iface_qos.br_iface_linux_br.update-device.delete.inbound_outbound: PASS (59.31 s)
(3/4) type_specific.io-github-autotest-libvirt.virtual_network.update_device.iface_qos.br_iface_ovs_br.update-device.delete.inbound_outbound: PASS (69.51 s)
(4/4) type_specific.io-github-autotest-libvirt.virtual_network.update_device.iface_qos.direct_bridge_iface.update-device.delete.inbound_outbound: PASS (42.61 s)
```
=> update_iface_qos:Fix typo of tc command

libvirt/tests/cfg/memory/memory_devices/dimm_memory_hot_unplug.cfg
increase the memory size
Before fixed
`(1/1) type_specific.io-github-autotest-libvirt.memory.devices.dimm.hot_unplug.online_movable_mem.source_and_mib: ERROR: Not found event device-removed after 20 seconds (185.88 s)
`
After fixed
```
avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 memory.devices.dimm.hot_unplug.online_movable_mem.source_and_mib --vt-connect-uri qemu:///system
(1/1) type_specific.io-github-autotest-libvirt.memory.devices.dimm.hot_unplug.online_movable_mem.source_and_mib: PASS (169.05 s)
```
=> fix detach memory device event not found issue

libvirt/tests/src/virtual_network/driver/check_vhost_cpu_affinity_with_emulatorpin.py
When interface is configured with multiple driver queues, there would be more than one process of vhost. Update test code to check all vhost thread in test.
Test result:
```
PASS 1-type_specific.io-github-autotest-libvirt.virtual_network.check_vhost_cpu_affinity_with_emulatorpin
```
=> Check multiple vhost thread

libvirt/tests/src/virtual_network/attach_detach_device/attach_mtu_malformed.py, libvirt/tests/src/virtual_network/connectivity/connectivity_check_bridge_interface.py, libvirt/tests/src/virtual_network/connectivity/connectivity_check_bridge_interface_unprivileged.py, libvirt/tests/src/virtual_network/connectivity/connectivity_check_direct_interface.py, libvirt/tests/src/virtual_network/connectivity/connectivity_check_ethernet_interface.py, libvirt/tests/src/virtual_network/connectivity/connectivity_check_user_interface.py, libvirt/tests/src/virtual_network/elements_and_attributes/attribute_port_isolated.py, libvirt/tests/src/virtual_network/elements_and_attributes/element_coalesce.py, libvirt/tests/src/virtual_network/iface_stat.py, libvirt/tests/src/virtual_network/link_state/link_state_model_type.py, libvirt/tests/src/virtual_network/passt/passt_attach_detach.py, libvirt/tests/src/virtual_network/passt/passt_connectivity_between_2vms.py, libvirt/tests/src/virtual_network/passt/passt_function.py, libvirt/tests/src/virtual_network/passt/passt_negative_setting.py, libvirt/tests/src/virtual_network/passt/passt_reconnect.py, libvirt/tests/src/virtual_network/passt/passt_transfer_file.py, libvirt/tests/src/virtual_network/qos/check_bandwidth_by_domiftune.py, libvirt/tests/src/virtual_network/update_device/update_device_coalesce.py, libvirt/tests/src/virtual_network/update_device/update_iface_link_state.py, libvirt/tests/src/virtual_network/update_device/update_iface_qos.py, libvirt/tests/src/virtual_network/update_device/update_iface_source.py, libvirt/tests/src/virtual_network/update_device/update_iface_trustGuestRxFilters.py, libvirt/tests/src/virtual_network/update_device/update_iface_type_live.py, libvirt/tests/src/virtual_network/update_device/update_port_isolated.py, provider/virtual_network/passt.py
The original way is to get the 1st iface that is UP which is not reliable since an interface might be UP even if it doesn't have an ip address.
=> virtual_network:Use get_default_gateway to get host iface name

libvirt/tests/cfg/sriov/network/sriov_check_network_connections.cfg, libvirt/tests/src/sriov/network/sriov_check_network_connections.py
This PR adds:
VIRT-301829 - Check the number of connections on hostdev network during vm destroy/start
` (1/1) type_specific.io-github-autotest-libvirt.sriov.network.check_connections: PASS (151.23 s)
`
=> sriov: Add a case about network connections

libvirt/tests/cfg/memory/memory_backing/lifecycle_for_hugepage.cfg, libvirt/tests/src/memory/memory_backing/lifecycle_for_hugepage.py
vm destroy right after vm start may fail destroy cmd (when vm initial time need longer time, for instance using hugepage), then the failed destroy cmd may impact following guest save cmd.
Resuts: run 20 times all pass:
(1/1) type_specific.io-github-autotest-libvirt.memory.backing.lifecycle.memory_hugepage.default_hugepage_size: PASS (143.65 s)
=> Remove vm destroy right after vm start to avoid destroy cmd failure

libvirt/tests/cfg/virtual_disks/virtual_disks_multiattributes.cfg
multiattributes on disk is not supported on s390x
=> Fix multiattributes.file_disk.start_guest failure on s390x

libvirt/tests/cfg/virtual_disks/virtual_disks_iothreads_queue.cfg
Use wild matching characters to match expected result, instead of hard-coded string for specific arches
=> Fix iothread failures in s390x

libvirt/tests/src/cpu/vcpu_misc.py
mem_file param needs a default value to not influence other cases
Before fixed
`ERROR: stat: path should be string, bytes, os.PathLike or integer, not NoneType
`
After fixed
```
avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 vcpu_misc.positive_test.with_topology.vcpus_max_equal_topology vcpu_misc.positive_test.vendor_id vcpu_misc.positive_test.mode_max vcpu_misc.positive_test.managedsave_restore vcpu_misc.positive_test.with_maxphysaddr vcpu_misc.negative_test.with_topology.vcpus_max_exceed_topology vcpu_misc.negative_test.with_topology.vcpus_max_less_than_topology
(1/7) type_specific.io-github-autotest-libvirt.vcpu_misc.positive_test.with_topology.vcpus_max_equal_topology: PASS (9.43 s)
(2/7) …
```
=> vcpu_misc: fix default value issue for mem file

libvirt/tests/cfg/memory/gmap.cfg
Recent Libvirt versions don't allow for these attributes. As they are not needed in this test, remove them.
=> gmap: remove lock options

libvirt/tests/cfg/memory/memory_attach_device.cfg, libvirt/tests/cfg/memory/memory_update_device.cfg
result on aarch64 64k:
(1/1) type_specific.io-github-autotest-libvirt.memory_update_device.virtio_mem: PASS (60.10 s)
(1/2) type_specific.io-github-autotest-libvirt.memory_attach_device.virtio_mem.cold_plug: PASS (67.71 s)
(2/2) type_specific.io-github-autotest-libvirt.memory_attach_device.virtio_mem.hot_plug: PASS (66.78 s)
=> Increase numa memory to avoid guest start failure for lack of memory

libvirt/tests/cfg/virsh_cmd/nodedev/virsh_nodedev_dumpxml_chain.cfg, libvirt/tests/src/virsh_cmd/nodedev/virsh_nodedev_dumpxml_chain.py, provider/vfio/ccw.py
1. Fix test name, subtest should be nodedev_dumpxml.chain for better discoverability and set definition.
2. Update test to run against a specific device.
3. Allow for a list of devices to be physically present. The test will configure the first one to establish the test precondition.
=> virsh/nodedev: fix chain test

libvirt/tests/src/virtual_network/iface_network.py
Replace an ip6tables usage with nft for new product which use the default firewall_backend='nftables'.
=> iface_network: use nft for new product

libvirt/tests/src/numa/guest_numa_topology/change_vcpu_pin.py
For vcpuinfo would be impacted by numad changing cpu affinity of guest process, so we skip it.
=> Skip checking vcpuinfo when numad active

libvirt/tests/cfg/virtual_disks/virtual_disks_ccw_addr.cfg
attach_disk,attach_controller,attach_rng is supported on s390x, so it is positive cases
=> Fix ccw test cases failures in s390x

libvirt/tests/cfg/virtual_network/resolve_vm_hostname_by_resolvectl.cfg, libvirt/tests/src/virtual_network/resolve_vm_hostname_by_resolvectl.py, provider/virtual_network/network_base.py, spell.ignore
- VIRT-301738 - resolve guest hostname from host by resolvectl
Depends on:
- https://github.com/avocado-framework/avocado-vt/pull/3951
Test result:
```
(1/4) type_specific.io-github-autotest-libvirt.virtual_network.resolve_vm_hostname_by_resolvectl.yes: PASS (83.63 s)
(2/4) type_specific.io-github-autotest-libvirt.virtual_network.resolve_vm_hostname_by_resolvectl.no: PASS (66.31 s)
(3/4) type_specific.io-github-autotest-libvirt.virtual_network.resolve_vm_hostname_by_resolvectl.omitted: PASS (73.91 s)
(4/4) type_specific.io-github-autotest-libvirt.virtual_network.resolve_vm_hostname_by_resolvectl.localonly_no: PASS (8.65 s)
```
=> Add new case of resolvectl

libvirt/tests/cfg/event/virsh_event.cfg
Test results:
x86_64:
(1/2) type_specific.io-github-autotest-libvirt.virsh.event.positive_test.virsh_event.test_events.device-removal-failed_event.no_timeout.loop: PASS (96.89 s)
(2/2) type_specific.io-github-autotest-libvirt.virsh.event.positive_test.qemu_monitor_event.pretty_option.device-removal-failed_event.no_timeout.loop: PASS (97.23 s)
aarch64 4k:
(1/2) type_specific.io-github-autotest-libvirt.virsh.event.positive_test.virsh_event.test_events.device-removal-failed_event.no_timeout.loop: PASS (126.71 s)
(2/2) type_specific.io-github-autotest-libvirt.virsh.event.positive_test.qemu_monitor_event.pretty_option.device-removal-failed_event.no_timeout.loop: PASS (118.64 s)
aarch64 64k:
(1/2) type_specific.io-github-autotest-libvirt.virsh.event.positive_test.virsh_event.test_events.device-r …
=> Decrease memory size to make unplug memory device more reliable

libvirt/tests/src/virsh_cmd/domain/virsh_attach_device.py
fix the issue that guest boot failure with bidirectional pipe device. 
refers to https://bugzilla.redhat.com/show_bug.cgi?id=2106975
=> replace bidirectional pipe with 2 unidirectional pipes (in/out) 

libvirt/tests/src/virsh_cmd/host/virsh_hostname.py
Description: remote_ip was wrongly typed as rempte_ip. Have fixed it with this PR!
Signed-off By: Kowshik Jois B S<kowsjois@linux.ibm.com>
=> corrected a misspelled remote_ip

libvirt/tests/cfg/virtual_network/passt/passt_connectivity_between_2vms.cfg, libvirt/tests/src/virtual_network/passt/passt_connectivity_between_2vms.py
Get the iface name from the guest os instead of assume it's interface name.
=> Get the iface name from the guest os

v2v/tests/cfg/v2v_options.cfg
Confirm with developer, the patch is included upstream in virt-v2v >= 2.4.  Any version
above this doesn't need the separate patch.
=> v2v:fix v2v-options failed case -adding version control

libvirt/tests/src/virtual_disks/virtual_disks_multiattributes.py
For virtual_disks.multiattributes.block_disk.start_guest, the created sdb disk usually doesn't exist because of known exception. So change to use scsi_debug to setup scsi disk to test.
=> Virtual_disk: fix "unable to open /dev/sdb" error

libvirt/tests/src/cpu/vcpu_metrics.py
libvirt does not support more than one interface queue for hosts using \<interface type='user\'>
If the xml that is being used for this test sets the number of queues higher, then the test will fail.
We remove the part of the XML that specifies the number of queues. This way Libvirt can default to a correct number
Below is evidence this change works
```
(.libvirt-ci-venv-ci-runtest-KSgk7Y) [root@ampere-mtsnow-altramax-03 tp-libvirt]# avocado run --vt-type libvirt --vt-machine-type arm64-mmio --test-runner=runner virsh.vcpu_metrics.normal_test.with_unprivileged_user
No python imaging library installed. PPM …
```
=> vcpu_metrics.py: Multiqueue Not Supported for type='user'

v2v/tests/src/v2v_options.py
The check-version function failed on rhel10 cause the way to check versions is on the digital.
Fix the function and it can work both on rhel10 and rhel9.
=> v2v: fix failed case on checking v2v version for rhel10

provider/numa/numa_base.py
results:
(01/44) type_specific.io-github-autotest-libvirt.guest_numa_node_tuning.host_guest_mixed_memory_binding.memnode_mode_strict.mem_mode_strict.single_node: PASS (36.39 s)
(02/44) type_specific.io-github-autotest-libvirt.guest_numa_node_tuning.host_guest_mixed_memory_binding.memnode_mode_strict.mem_mode_strict.multiple_nodes: PASS (37.56 s)
(03/44) type_specific.io-github-autotest-libvirt.guest_numa_node_tuning.host_guest_mixed_memory_binding.memnode_mode_strict.mem_mode_interleave.single_node: PASS (44.92 s)
(04/44) type_specific.io-github-autotest-libvirt.guest_numa_node_tuning.host_guest_mixed_memory_binding.memnode_mode_strict.mem_mode_interleave.multiple_nodes: PASS (44.26 s)
(05/44) type_specific.io-github-autotest-libvirt.guest_numa_node_tuning.host_guest_mixed_memory_binding.m …
=> Change grep pattern to avoid occasional memory size and address conflict

libvirt/tests/cfg/memory/memory_devices/dimm_memory_hot_unplug.cfg, libvirt/tests/src/memory/memory_devices/dimm_memory_hot_unplug.py
Change memory size to make logic same as current memory. 
Change memory address to avoid conflict.
Change guest node to make memory device hot-unplug reject by guest.
Test results:
(1/5) type_specific.io-github-autotest-libvirt.memory.devices.dimm.hot_unplug.default_mem.target_and_address: PASS (32.86 s)
(2/5) type_specific.io-github-autotest-libvirt.memory.devices.dimm.hot_unplug.default_mem.source_and_mib: PASS (34.27 s)
(3/5) type_specific.io-github-autotest-libvirt.memory.devices.dimm.hot_unplug.default_mem.unexisted_device: PASS (39.88 s)
(4/5) type_specific.io-github-autotest-libvirt.memory.devices.dimm.hot_unplug.online_movable_mem.target_and_address: PASS (168.38 s)
(5/5) type_specific.io-github-autotest-libvirt.memory.devices.dimm.hot_unplug.online_movable_mem.source_and_mib: …
=> Change memory size, memory address and guest node

libvirt/tests/src/numa/guest_numa_topology/numa_topology_with_cpu_topology.py
the original logic will ignore cpu xml like` <cpu mode="host-model" check="partial" /> `after change, only no cpu element will go to else part.
Test results:
(1/2) type_specific.io-github-autotest-libvirt.guest_numa_topology.numa_topology_with_cpu_topology.vcpu_with_order: PASS (79.41 s)
(2/2) type_specific.io-github-autotest-libvirt.guest_numa_topology.numa_topology_with_cpu_topology.vcpu_without_order: PASS (48.76 s)
=> Change comparison logic, including xml element without child element

libvirt/tests/cfg/backingchain/blockcopy/blockcopy_with_different_dest_xml.cfg, provider/virtual_disk/disk_base.py
xxxx-294410: Do blockcopy with different dest XML - rbd with luks and auth
```
avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 backingchain.blockcopy.dest_xml.rbd_with_luks_and_auth
(1/1) type_specific.io-github-autotest-libvirt.backingchain.blockcopy.dest_xml.rbd_with_luks_and_auth.pivot_reuse_external: PASS (56.15 s)
(1/1) type_specific.io-github-autotest-libvirt.backingchain.blockcopy.dest_xml.rbd_with_luks_and_auth.finish_reuse_external: PASS (61.22 s)
```
Got error on rhel10 ,it's a bug 
```
2024-07-07 21:47:09,652 virsh            L0822 DEBUG| Running virsh command: blockcopy avocado-vt-vm1 vdb  --pivot  --xml /tmp/xml_utils_temp_jjulza25.xml --transient-job --reuse-external --verbose --wait
2024-07-07 21:47:09,652 …
```
=> add rbd with luks scenario in blockcopy with dest xml case

libvirt/tests/src/virsh_cmd/domain/virsh_console.py
When looking for a console prompt, the script uses a regex. However this regex will not match the prompt if there is garbage in the console.
This garbage often appears as kernel debug messages. EG:
```
[root@localhost ~]# [   24.552883] block dm-0: the capability attribute has been deprecated
```
Update the regex to allow for garbage in the console
Here is the relevant tests passing
```
[root@ampere-mtsnow-altramax-52 tp-libvirt]# avocado run --vt-type libvirt --vt-machine-type arm64-mmio --test-runner=runner virsh.console.normal_test.acl_test.valid_domuuid
No python imaging library installed. PPM image …
```
=> virsh_console.py: Fix prompt regex

libvirt/tests/cfg/passthrough/pci/ism_pci_passthrough.cfg, libvirt/tests/src/passthrough/pci/ism_pci_passthrough.py, provider/vfio/__init__.py
1. Extract check the device is ISM to reuse between hotplug and coldplug functions.
2. Create new test config and test step.
3. Add hotplug function.
4. Change provider function to create pci host device XML, too.
=> ism_pci_passthrough: add hotplug case

libvirt/tests/cfg/snapshot/snapshot_list_with_options.cfg, libvirt/tests/src/snapshot/snapshot_list_with_options.py
Automate case VIRT-16603 - [Disk snapshot][External] Get guest snapshot list with option
=> Snapshot: add new auto case for snapshot-list

libvirt/tests/cfg/memory/memory_attach_device.cfg
Test results:
x86_64:
(1/2) type_specific.io-github-autotest-libvirt.memory_attach_device.virtio_mem.cold_plug: PASS (69.72 s)
(2/2) type_specific.io-github-autotest-libvirt.memory_attach_device.virtio_mem.hot_plug: PASS (66.97 s)
aarch64 4k:
(1/2) type_specific.io-github-autotest-libvirt.memory_attach_device.virtio_mem.cold_plug: PASS (72.25 s)
(2/2) type_specific.io-github-autotest-libvirt.memory_attach_device.virtio_mem.hot_plug: PASS (70.91 s)
=> Add current memory config to replace default

libvirt/tests/cfg/memory/memory_devices/virtio_mem_device_lifecycle.cfg, libvirt/tests/src/memory/memory_devices/virtio_mem_device_lifecycle.py
test results:
(1/8) type_specific.io-github-autotest-libvirt.memory.devices.virtio_mem.lifecycle.all_requested_and_address.no_source.4k: PASS (156.87 s)
(2/8) type_specific.io-github-autotest-libvirt.memory.devices.virtio_mem.lifecycle.all_requested_and_address.nodemask.4k: PASS (167.96 s)
(3/8) type_specific.io-github-autotest-libvirt.memory.devices.virtio_mem.lifecycle.all_requested_and_address.pagesize.4k: PASS (166.47 s)
(4/8) type_specific.io-github-autotest-libvirt.memory.devices.virtio_mem.lifecycle.all_requested_and_address.nodemask_pagesize.4k: PASS (193.24 s)
(5/8) type_specific.io-github-autotest-libvirt.memory.devices.virtio_mem.lifecycle.part_requested_and_no_address.no_source.4k: PASS (162.86 s)
(6/8) type_specific.io-github-autotest-libvirt.memory.devices.virtio_mem.lifecycl …
=> Add virtio-mem device lifecycle test case

libvirt/tests/cfg/virtio_transitional/virtio_transitional_blk.cfg, libvirt/tests/cfg/virtio_transitional/virtio_transitional_mem_balloon.cfg, libvirt/tests/cfg/virtio_transitional/virtio_transitional_nic.cfg, libvirt/tests/cfg/virtio_transitional/virtio_transitional_rng.cfg, libvirt/tests/cfg/virtio_transitional/virtio_transitional_vsock.cfg, libvirt/tests/src/virtio_transitional/virtio_transitional_mem_balloon.py
With the default memory size, the guest can't boot in aarch64. So update it to be also covered in aarch64.
=> Transitional_memballoon: update memory size to test in aarch64

libvirt/tests/src/virtual_device/tpm_device.py
source_socket accessed when it's not exist, which blocking real vm start error.
=> tpm_device: fix source_socket error

libvirt/tests/cfg/sriov/vIOMMU/hotplug_device_with_iommu_enabled.cfg, libvirt/tests/src/sriov/vIOMMU/hotplug_device_with_iommu_enabled.py, provider/viommu/viommu_base.py
This PR adds:
VIRT-296710: [vIOMMU] hotplug/unplug devices with iommu enabled
**Test results:** The failed case is due to a known issue.
```
(01/12) type_specific.io-github-autotest-libvirt.vIOMMU.hotplug_device_with_iommu_enabled.e1000e.virtio: PASS (69.83 s)
(02/12) type_specific.io-github-autotest-libvirt.vIOMMU.hotplug_device_with_iommu_enabled.e1000e.intel: PASS (203.39 s)
(03/12) type_specific.io-github-autotest-libvirt.vIOMMU.hotplug_device_with_iommu_enabled.rtl8139.virtio: PASS (70.67 s)
(04/12) type_specific.io-github-autotest-libvirt.vIOMMU.hotplug_device_with_iommu_enabled.rtl8139.intel: PASS (209.17 s)
(05/12) type_specific.io-github-autotest-libvirt.vIOMMU.hotplug_device_with_iommu_enabled.virtio_muti_devices.vhost_on.virtio: PASS (75.64 s)
(06/12) …
```
=> vIOMMU: Add a hotplug case

libvirt/tests/cfg/daemon/conf_file/qemu_conf/set_virtlogd.cfg, libvirt/tests/src/daemon/conf_file/qemu_conf/set_virtlogd.py
Automate virtlogd maxclients related cases
xx-59118,xx-86131,xx-86144,xx-86515
=> Automate virtlogd maxclients related cases

libvirt/tests/cfg/sriov/vIOMMU/iommu_device_lifecycle.cfg, libvirt/tests/src/sriov/vIOMMU/iommu_device_lifecycle.py
This pr adds 'virsh reset' into viommu lifecycle testing.
```
(01/11) type_specific.io-github-autotest-libvirt.vIOMMU.iommu_device_lifecycle.save_restore.virtio_muti_devices.vhost_on.virtio: PASS (76.58 s)
(02/11) type_specific.io-github-autotest-libvirt.vIOMMU.iommu_device_lifecycle.save_restore.virtio_muti_devices.vhost_on.smmuv3: PASS (76.84 s)
(03/11) type_specific.io-github-autotest-libvirt.vIOMMU.iommu_device_lifecycle.suspend_resume.virtio_muti_devices.vhost_on.virtio: PASS (74.65 s)
(04/11) type_specific.io-github-autotest-libvirt.vIOMMU.iommu_device_lifecycle.suspend_resume.virtio_muti_devices.vhost_on.smmuv3: PASS (74.39 s)
(05/11) type_specific.io-github-autotest-libvirt.vIOMMU.iommu_device_lifecycle.suspend_resume.hostdev_iface.virtio: PASS (135.01 s)
(06/11) …
```
=> viommu: Add a test scenario about 'virsh reset'

libvirt/tests/src/virsh_cmd/domain/virsh_detach_device_alias.py
Tests rhel.virsh.detach_device_alias.live.input.passthrough and rhel.virsh.detach_device_alias.config.input.passthrough do not pass if there is not input device, as they require a device to passthrough to the vm
Skip the test if no input device can be found
```
[root@ampere-mtjade-altra-04 tp-libvirt]# avocado run --vt-type libvirt --vt-machine-type arm64-mmio --test-runner=runner virsh.detach_device_alias.config.input.passthrough
JOB ID     : …
```
=> virsh_detach_device_alias: Skip test when no input

libvirt/tests/cfg/guest_os_booting/boot_order/boot_from_usb_device.cfg
The test guest_os_booting.boot_order.usb_device.block_device looks for a regex to see if the usb boot device is being booted first.
If the usb device is blank, edk2 will reorder the boot order, to deprioritize the usb device. And it won't print it first in the boot order.
We can see that it attempts to boot from the usb if we see edk2 printing the "USB_BOOT_TEST_UNIT_READY" command output.
```
UsbBootExecCmd: Success to Exec 0x0 Cmd (Result = 1)
```
Cmd 0x0: Test Unit Ready Opcode (See [usb protocol documentation](https://usb.org/sites/default/files/usb_msc_boot_1.0.pdf))
Result = 1: The unit was ready for further commands
This is printed when edk2 is asking the USB device if it is ready to recieve further commands. We can simply test for this output to see if edk2 considered the usb …
=> boot_from_usb_device.cfg: Update regex

libvirt/tests/cfg/vm_create_destroy_concurrently.cfg, libvirt/tests/src/vm_create_destroy_concurrently.py
Libvirt provides unique UUIDs to every VM, in order to uniquely identify the VMs.
When transient VMs are created, libvirt allows it to have a non-unique name/UUID. So long as any other VM with the same name/UUID is a persistant VM, that is not running
If two transient VMs are created at the same time, with the same name/UUID, a race condition exists. We expect libvirt to create one VM, and prevent the creation of another. However, sometimes this is not what happens
If such a race condition occurs, Libvirt may crash, and orphan VMs may be created. This test checks for this.
1. Create several loops that continuosly start and destroy a transient VM. Python's GIL prevents the same bytecodes from executing at the same time. To ensure that a race condition can happen, and the GIL cannot prevent …
=> vm_create_destroy_concurrently: Reliability Test

libvirt/tests/cfg/virtual_network/hotplug/attach_detach_interface/attach_interface_with_model.cfg, libvirt/tests/src/virtual_network/hotplug/attach_detach_interface/attach_interface_with_model.py
On s390x, pcie-to-pci-bridge is not available. Don't attach this.
=> attach_interface_with_model: don't attach incompatible controller

libvirt/tests/cfg/virtio/virtio_page_per_vq.cfg, libvirt/tests/src/virtio/virtio_page_per_vq.py
Automate VIRT-293723 - [packed] Start vm with virtio packed attribute and check the bit. After discussion, we don't need to add the checkpoint of bit. Also because this attribute have already been covered in some devices but not filesystem, video and others. So I covered all them directly in the previous test script.
=> Virtio_packed: add new test scenarios of driver packed attribute

libvirt/tests/src/memory/memory_backing/lifecycle_for_hugepage.py
test results:
(1/3) type_specific.io-github-autotest-libvirt.memory.backing.lifecycle.memory_hugepage.default_page_size: PASS (141.77 s)
(2/3) type_specific.io-github-autotest-libvirt.memory.backing.lifecycle.memory_hugepage.2M: PASS (152.55 s)
(3/3) type_specific.io-github-autotest-libvirt.memory.backing.lifecycle.memory_hugepage.16G: CANCEL: Only can set 0 pages for 16777216 hugepage, but need 1 (34.41 s)
=> Add hugepage allocation checking

libvirt/tests/src/guest_os_booting/boot_order/boot_from_cdrom_device.py, libvirt/tests/src/guest_os_booting/boot_order/boot_with_multiple_boot_dev.py, libvirt/tests/src/guest_os_booting/boot_order/boot_with_multiple_boot_order.py
**Issue:**
VMStartError: VM 'avocado-vt-vm1' failed to start: error: Failed to start domain 'avocado-vt-vm1'error: Cannot access storage file '/var/lib/avocado/data/avocado-vt/boot.iso': No such file or directory(exit status: 1)
**Fix:**
This issue is caused by multiple repos being fetched and then their urls being concatenated together. The fix is to ensure that only 1 repo is fetched (the last result), which can in turn get the boot.iso file.
**Passing test results:**
```
[root@beaver-9 cfg]# /usr/local/bin/avocado run --vt-type libvirt --vt-machine-type q35 guest_os_booting.boot_order.boot_with_multiple_boot_order guest_os_booting.boot_order.boot_with_multiple_boot_dev guest_os_booting.boot_order.cdrom_device --vt-connect-uri qemu:///system
No python imaging library installed. …
```
=> boot_order: ensure only 1 repo is used to get boot.iso

libvirt/tests/src/virsh_cmd/host/virsh_capabilities.py
Attributes on s390x are: thread, core, book, drawer.
Skip check cluster information as it doesn't apply.
=> capabilities: don't check cluster_id on s390x

libvirt/tests/src/virtual_device/filesystem_device.py
Updated test.cancel to test.error in filesystem_device.py for the lsof command not being installed error and
the not the correct amount of vms error to ensure that the test fails (instead of skips) when expected.
=> Filesystem_device: updated test.cancel to test.error

libvirt/tests/cfg/guest_os_booting/boot_order/boot_from_usb_device.cfg, libvirt/tests/cfg/usb/usb_device.cfg, libvirt/tests/src/guest_os_booting/boot_order/boot_from_usb_device.py, libvirt/tests/src/usb/usb_device.py, provider/usb/usb_base.py
usbredirserver is updated to usbredirect
```
avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 guest_os_booting.boot_order.usb_device
(1/3) type_specific.io-github-autotest-libvirt.guest_os_booting.boot_order.usb_device.block_device: PASS (41.59 s)
(2/3) type_specific.io-github-autotest-libvirt.guest_os_booting.boot_order.usb_device.redirdev_device: PASS (15.60 s)
(3/3) type_specific.io-github-autotest-libvirt.guest_os_booting.boot_order.usb_device.hostdev_device: PASS (15.70 s)
avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 guest_os_booting.boot_order.usb_device.redirdev_device
(1/1) type_specific.io-github-autotest-libvirt.guest_os_booting.boot_order.usb_device.redirdev_device: PASS (15.28 s)
```
=> fix package upated for usb case

provider/bootc_image_builder/aws_utils.py, provider/bootc_image_builder/bootc_image_build_utils.py, virttools/tests/cfg/bootc_image_builder/bootc_disk_image_build.cfg, virttools/tests/cfg/bootc_image_builder/bootc_disk_image_install.cfg, virttools/tests/src/bootc_image_builder/bootc_disk_image_build.py, virttools/tests/src/bootc_image_builder/bootc_disk_image_install.py
Add bootc image builder case
utilities and case scripts are provided,
and cover Image type:ami vmdk qcow2 anaconda-iso raw
container image reference: quay.io/centos-bootc/centos-bootc:stream9,
quay.io/centos-bootc/fedora-bootc:eln, localhost/bootc:eln
=> Add bootc image builder case

libvirt/tests/cfg/vm_start_destroy_repeatedly.cfg, libvirt/tests/src/vm_start_destroy_repeatedly.py
Add variant to vm_start_destroy_repeatedly.py for handling a vm with hugepages. Bugs have been filed related to this
1) Set number of huge pages = vm_memory / hugepage size
2) Add necessary XML to define a vm with hugepages
3) Run start/stop loop as before
4) Check number of huge pages, to ensure the number is the same
Test passing with num_cycles = '1'
```
[root@ampere-mtjade-altra-04 tp-libvirt]# avocado run --vt-type libvirt --vt-machine-type arm64-mmio --test-runner=runner vm_start_destroy_repeatedly.hugepage
No python imaging library installed. PPM image conversion to JPEG disabled. In order to enable …
```
=> vm_start_destroy_repeatedly: Add Hugepage Variant

libvirt/tests/cfg/daemon/conf_file/libvirtd_conf/check_negative_parameter.cfg, libvirt/tests/src/daemon/conf_file/libvirtd_conf/check_negative_parameter.py
XXXX-34455 - [libvirtd][config]Start libvirtd with negative value for parameters which require positive integer value in libvirtd.conf
=> libvirtd: Add case about negative value for parameters in libvirtd conf

libvirt/tests/src/usb/usb_device.py
Fixes the regression from 1a20a4a3a. It will cause this error for non-redirect device caes:
UnboundLocalError: cannot access local variable 'usb_cmd' where it is not associated with a value
=> usb_device: Fix the unassigned variable 'usb_cmd'

libvirt/tests/src/sriov/vIOMMU/attach_iommu_device.py
Update to remove the iommu device before attaching it to avoid failures.
` (1/1) type_specific.io-github-autotest-libvirt.vIOMMU.attach_iommu_device.cold_plug.virtio: FAIL: Expect should succeed, but got: \n\nerror: Failed to attach device from /tmp/xml_utils_temp_rqu_qcdu.xml\nerror: Requested operation is not valid: domain already has an iommu device\n (6.65 s)
`
` (1/1) type_specific.io-github-autotest-libvirt.vIOMMU.attach_iommu_device.cold_plug.virtio: PASS (6.48 s)
`
=> vIOMMU: Remove the iommu device before attaching it

libvirt/tests/cfg/memory/memory_balloon/period_config_of_memory_balloon.cfg, libvirt/tests/src/memory/memory_balloon/period_config_of_memory_balloon.py
test results:
(1/6) type_specific.io-github-autotest-libvirt.memory.balloon.period.memory_allocation.undefined_period.virtio_model: PASS (38.63 s)
(2/6) type_specific.io-github-autotest-libvirt.memory.balloon.period.memory_allocation.undefined_period.virtio_trans_model: /PASS (39.18 s)
(3/6) type_specific.io-github-autotest-libvirt.memory.balloon.period.memory_allocation.undefined_period.virtio_non_trans_model: PASS (46.12 s)
(4/6) type_specific.io-github-autotest-libvirt.memory.balloon.period.memory_allocation.int_period.virtio_model: PASS (45.47 s)
(5/6) type_specific.io-github-autotest-libvirt.memory.balloon.period.memory_allocation.int_period.virtio_trans_model: PASS (45.95 s)
(6/6) type_specific.io-github-autotest-libvirt.memory.balloon.period.memory_allocation.int_period.virtio_non_t …
=> Change guest memory statistics checking timeline

libvirt/tests/src/cpu/vcpu_metrics.py
//os/loader* might not exist on the domain definition leading to an exception. In this case, skip the step that tries to remove those attributes.
=> vcpu_metrics: handle missing element

virttools/tests/src/virt_install/pxe_installation.py
Installation media might not have a valid certificate for our testing. This is not critical for the test case.
Append kernel parameter to skip verification.
=> pxe_installation: add flag to void certificate error

libvirt/tests/src/svirt/selinux/selinux_seclabel_per_device.py
Test result:
```
(1/6) type_specific.io-github-autotest-libvirt.svirt.selinux.seclabel.per_device.relabel_no.serial.cold_plug: PASS (7.05 s)
(2/6) type_specific.io-github-autotest-libvirt.svirt.selinux.seclabel.per_device.relabel_yes.without_label.serial.cold_plug: FAIL: Run '/bin/virsh start avocado-vt-vm1 ' expect fail, but run successfully. (7.71 s)
(3/6) type_specific.io-github-autotest-libvirt.svirt.selinux.seclabel.per_device.relabel_yes.label_legit.serial.cold_plug:
PASS (7.39 s)
(4/6) type_specific.io-github-autotest-libvirt.svirt.selinux.seclabel.per_device.relabel_yes.label_MCS.serial.cold_plug:PAASS (7.25 s)
(5/6) type_specific.io-github-autotest-libvirt.svirt.selinux.seclabel.per_device.relabel_yes.label_default.serial.cold_plug: PASS (7.21 s)
(6/6) …
```
=> selinux_seclabel_per_device:Fix UnboundLocalError

libvirt/tests/cfg/sriov/vIOMMU/viommu_transfer_file.cfg, libvirt/tests/src/sriov/vIOMMU/viommu_transfer_file.py
This PR adds:
VIRT-301880: Transfer a file between host and vm with iommu device
```
(1/2) type_specific.io-github-autotest-libvirt.vIOMMU.transfer_file.virtio_interface.virtio: PASS (79.73 s)
(2/2) type_specific.io-github-autotest-libvirt.vIOMMU.transfer_file.virtio_interface.smmuv3: PASS (49.39 s)
(1/4) type_specific.io-github-autotest-libvirt.vIOMMU.transfer_file.e1000e.virtio: PASS (184.21 s)
(2/4) type_specific.io-github-autotest-libvirt.vIOMMU.transfer_file.e1000e.intel: PASS (339.61 s)
(3/4) type_specific.io-github-autotest-libvirt.vIOMMU.transfer_file.virtio_interface.virtio: PASS (184.73 s)
(4/4) type_specific.io-github-autotest-libvirt.vIOMMU.transfer_file.virtio_interface.intel: PASS (321.49 s)
```
=> viommu: Add a case for file transfers

libvirt/tests/cfg/sriov/vIOMMU/iommu_device_settings.cfg, libvirt/tests/src/sriov/vIOMMU/iommu_device_settings.py, provider/viommu/viommu_base.py
The disk and scsi controller may enable iommu by default, so update to use the proper disk and controller settings.
Depends on:
- https://github.com/avocado-framework/avocado-vt/pull/3999
**Test results:** The failed case is caused by a known issue.
```
(1/7) type_specific.io-github-autotest-libvirt.vIOMMU.hotplug_device_with_iommu_enabled.virtio_muti_devices.vhost_on.virtio: PASS (78.88 s)
(2/7) type_specific.io-github-autotest-libvirt.vIOMMU.hotplug_device_with_iommu_enabled.virtio_muti_devices.vhost_on.smmuv3: PASS (81.11 s)
(3/7) type_specific.io-github-autotest-libvirt.vIOMMU.hotplug_device_with_iommu_enabled.virtio_muti_devices.vhost_off.virtio: PASS (80.84 s)
(4/7) type_specific.io-github-autotest-libvirt.vIOMMU.hotplug_device_with_iommu_enabled.virtio_muti_devices.vhost_off.smmuv3: …
```
=> viommu: Fixup incorrect disk xml issues

libvirt/tests/src/virsh_cmd/domain/virsh_domif_setlink_getlink.py
'driver' is only supported by virtio
Depends on:
- https://github.com/avocado-framework/avocado-vt/pull/3999
Test result:
```
(01/12) type_specific.io-github-autotest-libvirt.virsh.domif_setlink_getlink.positive_test.e1000e.interface_net.no_config.domain_name.running_guest.domif_setlink.setlink_down: PASS (82.74 s)
(02/12) type_specific.io-github-autotest-libvirt.virsh.domif_setlink_getlink.positive_test.e1000e.interface_net.no_config.domain_name.running_guest.domif_setlink.stable_test.setlink_down.restart_libvirtd: PASS (193.15 s)
(03/12) type_specific.io-github-autotest-libvirt.virsh.domif_setlink_getlink.positive_test.e1000e.interface_mac.no_config.domain_name.running_guest.domif_setlink.setlink_down: PASS (72.76 s)
(04/12) type_specific.io-github-autotest-libvirt.virsh.domif_setlink_ge …
```
=> virsh_domif_setlink_getlink:Remove driver settings from iface when model is not virtio

libvirt/tests/src/memory/memory_devices/virtio_mem_device_lifecycle.py
result:
(1/8) type_specific.io-github-autotest-libvirt.memory.devices.virtio_mem.lifecycle.all_requested_and_address.no_source.4k: PASS (132.09 s)
(2/8) type_specific.io-github-autotest-libvirt.memory.devices.virtio_mem.lifecycle.all_requested_and_address.nodemask.4k: PASS (132.80 s)
(3/8) type_specific.io-github-autotest-libvirt.memory.devices.virtio_mem.lifecycle.all_requested_and_address.pagesize.4k: PASS (132.09 s)
(4/8) type_specific.io-github-autotest-libvirt.memory.devices.virtio_mem.lifecycle.all_requested_and_address.nodemask_pagesize.4k: PASS (179.90 s)
(5/8) type_specific.io-github-autotest-libvirt.memory.devices.virtio_mem.lifecycle.part_requested_and_no_address.no_source.4k: PASS (135.37 s)
(6/8) type_specific.io-github-autotest-libvirt.memory.devices.virtio_mem.lifecycle.part …
=> Add debug info and libvirt daemon restart check

libvirt/tests/cfg/virtual_network/passt/passt_lifecycle.cfg, libvirt/tests/src/virtual_network/passt/passt_lifecycle.py
- VIRT-297078 - [user][passt] Test the lifecycle of the vm with passt backend interface
```
(1/3) type_specific.io-github-autotest-libvirt.virtual_network.passt.lifecycle.ip_portfw.non_root_user.save_restore: PASS (243.39 s)
(2/3) type_specific.io-github-autotest-libvirt.virtual_network.passt.lifecycle.ip_portfw.non_root_user.managedsave_start: PASS (243.84 s)
(3/3) type_specific.io-github-autotest-libvirt.virtual_network.passt.lifecycle.ip_portfw.non_root_user.suspend_resume: PASS (241.78 s)
```
=> Add network case of passt lifecycle

libvirt/tests/src/virsh_cmd/domain/virsh_change_media.py
Fix change media update device failure
This may happen in case VM is not real ready to update device
=> Fix change media update device failure

libvirt/tests/src/virtual_network/passt/passt_negative_setting.py
Test result:
```
(01/36) type_specific.io-github-autotest-libvirt.virtual_network.passt.negative_setting.log_no_permission.start_vm.root_user: PASS (5.49 s)
(02/36) type_specific.io-github-autotest-libvirt.virtual_network.passt.negative_setting.log_no_permission.start_vm.non_root_user: PASS (8.74 s)
(03/36) type_specific.io-github-autotest-libvirt.virtual_network.passt.negative_setting.log_no_permission.hotplug.root_user: PASS (5.48 s)
(04/36) type_specific.io-github-autotest-libvirt.virtual_network.passt.negative_setting.log_no_permission.hotplug.non_root_user: PASS (8.72 s)
(05/36) type_specific.io-github-autotest-libvirt.virtual_network.passt.negative_setting.rm_passt_pgk.start_vm.root_user: PASS (64.66 s)
(06/36) type_specific.io-github-autotest-libvirt.virtual_network.passt.negative_s …
```
=> Fixup:passt_negative:sync vmxml after deleting vm ifaces

libvirt/tests/src/svirt/selinux/selinux_seclabel_per_device.py
`status_error` expected to be `yes` on invalid configuration, that is, either during xml setup
a) through `vmxml.sync` which undefines and tries to define the VM, or b) through attach through `virsh.attach_device`.
Both will raise LibvirtXMLError on failure. So, if as expected this error is raised for coldplug, we can stop the test execution by returning and considering the test PASS.
=> svirt/selinux/per_device: return if expected error is found

libvirt/tests/cfg/virtual_network/update_device/update_iface_with_identifier.cfg
On s390x, virtio addresses are ccw not pci. Disable test case.
=> update_iface_with_identifier: disable test on s390x

libvirt/tests/src/memory/memory_misc.py
test result:
(1/1) type_specific.io-github-autotest-libvirt.memory_misc.memorybacking.mount_hp_running_vm.64k.524288.16777216: PASS (50.82 s)
=> Fail test case when huge page is not enough, and add huge page cleanup.

libvirt/tests/cfg/memory/memory_backing/lifecycle_for_hugepage.cfg
test results for other archs:
x86
(1/5) type_specific.io-github-autotest-libvirt.memory.backing.lifecycle.memory_hugepage.default_page_size: PASS (116.40 s)
(2/5) type_specific.io-github-autotest-libvirt.memory.backing.lifecycle.memory_hugepage.default_hugepage_size: PASS (109.78 s)
(3/5) type_specific.io-github-autotest-libvirt.memory.backing.lifecycle.memory_hugepage.1G: PASS (114.96 s)
(4/5) type_specific.io-github-autotest-libvirt.memory.backing.lifecycle.memory_hugepage.0: PASS (24.76 s)
(5/5) type_specific.io-github-autotest-libvirt.memory.backing.lifecycle.memory_hugepage.scarce_mem: PASS (38.21 s)
aarch 64 4k:
(1/9) type_specific.io-github-autotest-libvirt.memory.backing.lifecycle.memory_hugepage.default_page_size: PASS (103.16 s)
(2/9) …
=> Change memory size according to case update

libvirt/tests/cfg/security/rng/libvirt_rng.cfg, libvirt/tests/src/security/rng/libvirt_rng.py
Only external snapshot is officially supported, and it supports
revert now. Update rng cases to use this. Since every step is
external snapshot now, no need to do the 3rd snapshot test which
was called snapshot_with_rng.
=> libvirt_rng: update rng to use external snapshot

libvirt/tests/cfg/virtual_device/tpm_device.cfg, libvirt/tests/src/virtual_device/tpm_device.py
Cleaning audit logs should be before vm start, and need clean all
audit.log*(.1, .2, etc) files. Also move it later to wait more time.
And replace ausearch cmd since it can not capture well sometimes,
audit.log can reflect actual info instead.
=> tpm_device.py: clean audit before vm start

libvirt/tests/src/guest_os_booting/boot_order/boot_from_cdrom_device.py, libvirt/tests/src/guest_os_booting/boot_order/boot_with_multiple_boot_dev.py, libvirt/tests/src/guest_os_booting/boot_order/boot_with_multiple_boot_order.py, provider/guest_os_booting/guest_os_booting_base.py
**Issue:**
VMStartError: VM 'avocado-vt-vm1' failed to start: error: Failed to start domain 'avocado-vt-vm1'error: Cannot access storage file '/var/lib/avocado/data/avocado-vt/images/boot.iso': No such file or directory(exit status: 1)&#10;
**_More specifically:_**
```
L0087 INFO | Fetching http://download.eng.pek2.redhat.com/rhel-9/composes/RHEL-9/RHEL-9.5.0-20240924.2/compose/BaseOS/x86_64/os/images/boot.iso -> /var/lib/avocado/data/avocado-vt/images/boot.iso
L0059 DEBUG| Updated HWADDR (34:48:ed:f9:e2:20)<->(10.73.178.185) IP pair into address cache
L0050 ERROR| Timeout was reached: timed out
L0702 DEBUG| [stderr] Failed to get file. Probably timeout was reached when connecting to the server.
```
**Fix:** 
This issue is likely due to the download.get_file() failing to get the boot.iso …
=> boot_order: waiting for the boot.iso file to download

libvirt/tests/cfg/memory/memory_devices/virtio_memory_with_numa_node_tuning.cfg, libvirt/tests/src/memory/memory_devices/virtio_memory_with_numa_node_tuning.py, provider/memory/memory_base.py
xxxx-299159 Virtio-mem memory device with numa node tuning
```
avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35  memory.devices.virtio.with_numa_tuning
(01/12) type_specific.io-github-autotest-libvirt.memory.devices.virtio.with_numa_tuning.cold_plug.with_source_virtio_mem.strict: PASS (90.77 s)
(02/12) type_specific.io-github-autotest-libvirt.memory.devices.virtio.with_numa_tuning.cold_plug.with_source_virtio_mem.interleave: PASS (111.33 s)
(03/12) type_specific.io-github-autotest-libvirt.memory.devices.virtio.with_numa_tuning.cold_plug.with_source_virtio_mem.preferred: PASS (109.53 s)
(04/12) type_specific.io-github-autotest-libvirt.memory.devices.virtio.with_numa_tuning.cold_plug.with_source_virtio_mem.undefined: PASS …
```
=> add case for virtio mem with numa node tunning

libvirt/tests/src/libvirt_hooks.py
Before libvirt 10.5.0, hook_str is '...release end -'. After libvirt 10.5.0, hook_str is '...release end shutdown'.
Reference: https://github.com/autotest/tp-libvirt/pull/5782
=> libvirt_hooks: Fix string matching

libvirt/tests/cfg/virtual_network/update_device/update_iface_link_state.cfg
Need to run this test against the second interface on our host.
=> update_iface_link_state: make host_iface configurable

libvirt/tests/cfg/backingchain/blockcopy/blockcopy_with_different_dest_xml.cfg, provider/virtual_disk/disk_base.py
xxxx-294410:Do blockcopy with different dest XML
```
avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 backingchain.blockcopy.dest_xml.block_disk.finish_reuse_external --vt-connect-uri qemu:///system
(1/1) type_specific.io-github-autotest-libvirt.backingchain.blockcopy.dest_xml.block_disk.finish_reuse_external: PASS (60.01 s)
```
Others related
```
avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 guest_os_booting.boot_order.hotplug backingchain.blockcopy.zero_length_disk snapshot_revert.xml_updated virtual_disks.discard_no_unref
(01/19) type_specific.io-github-autotest-libvirt.guest_os_booting.boot_order.hotplug.disk_device: PASS (24.58 s)
(02/19) …
```
=> case update: blockcopy dest xml for block disk with iscsi preparation

libvirt/tests/cfg/security/virt_what_cvm.cfg, libvirt/tests/src/security/virt_what_cvm.py, spell.ignore
Since virt-what-1.25-9, there's an additional command 'virt-what-cvm' that gives information about if and which confidential VM mode is running.
The test per default assumes that the VM runs without confidentiality. It can be configured to cover other values depending on the guest. The supported outputs are listed on the man virt-what-cvm.
=> security/virt_what: add test for expected value

libvirt/tests/cfg/virsh_cmd/domain/virsh_guestvcpus.cfg, libvirt/tests/src/virsh_cmd/domain/virsh_guestvcpus.py
Case ID: VIRT-301878
Automates the case that verifies that the maximum vcpu (numbers = #host_online_cpu - 1) in the guest can be disabled and then enabled. This is done by modifying the existing virsh_guestvcpus.py test file.
Evidence of tests passing:
```
[root@ampere-mtsnow-altra-07 /]# avocado run --vt-type libvirt virsh.guestvcpus.max_test
JOB ID     : 1b1991ea18284ce10f02306864ac7f7bfbdbb903
JOB LOG    : …
```
=> Guestvcpus: enable/disable max vcpu by guest agent

libvirt/tests/cfg/sriov/vIOMMU/intel_iommu_virtio_device_with_ats.cfg
The value of disk driver will be removed before setting disk xml, so add driver settings in cfg.
` (1/1) type_specific.io-github-autotest-libvirt.vIOMMU.intel_iommu.virtio_device_with_ats.scsi_controller: PASS (169.67 s)
`
=> vIOMMU: Fix incorrect disk driver setting issue

libvirt/tests/cfg/cpu/vcpu_max_topology.cfg, libvirt/tests/src/cpu/vcpu_max_topology.py
Case ID: VIRT-301882
Automates the case that verifies the vm can start with vcpus which is equal to host online cpu number and vm topology is consistent to those configured.
- https://github.com/avocado-framework/avocado-vt/pull/4006
**Scenarios + sub-scenarios considered:**
- Only 1 socket
- No clusters defined, so default is 1
- clusters = 2n, like 2, 4, 6
- Only 1 core per socket
- More than one core per socket
- More than one socket, clusters defaults to 1
- clusters = 2n, like 2, 4, 6 ...
**Evidence of tests passing:**
```
[root@ampere-mtsnow-altra-11 /]# avocado run --vt-type libvirt vcpu.max_topology
No python imaging library installed. Screendump and Windows guest BSOD detection are disabled. In order to enable it, please install python-imaging or the equivalent …
```
=> Max_vcpus_topology: ensure that the VM gets correct topology with maximum vcpus	

libvirt/tests/cfg/migration/async_ops/destroy_vm_during_performphase.cfg, libvirt/tests/src/migration/async_ops/destroy_vm_during_performphase.py
XXX-298199 - [VM migration][async ops] destroy vm during PerformPhase of migration
=> migration: Add case about destroy vm

libvirt/tests/src/passthrough/ap/libvirt_ap_passthrough_autostart.py
Fix libvirt_ap_passthrough_autostart failure due to incorrectly string format in LOG.debug
Typically, it will throw TypeError: not all arguments converted during string formatting
=> Fix libvirt_ap_passthrough_autostart failure due to incorrectly string

libvirt/tests/src/virsh_cmd/domain/virsh_domif_setlink_getlink.py
Issue:
LoginTimeoutError: Login timeout expired    (output: 'exceeded 240 s timeout')&#10;
More specifically:
L0941 ERROR|   File "/var/lib/avocado/data/avocado-vt/virttest/test-providers.d/downloads/io-github-autotest-libvirt/libvirt/tests/src/virsh_cmd/domain/virsh_domif_setlink_getlink.py", line 259, in run    session = vm.wait_for_serial_login(username=username,
L0941 ERROR|   File "/var/ci/libvirt-ci/runtest/avocado-vt/avocado-vt/virttest/virt_vm.py", line 1523, in wait_for_serial_login    raise remote.LoginTimeoutError("exceeded %s s timeout" % timeout)
L0941 ERROR| aexpect.remote.LoginTimeoutError: Login timeout expired    (output: 'exceeded 240 s timeout')
Fix:
Run `vm.cleanup_serial_console()` and `vm.create_serial_console()` to close (if necessary) and then establish a …
=> Domif_setlink_getlink: closing and establishing connection with serial console before login

libvirt/tests/cfg/virtual_network/iface_stat.cfg, libvirt/tests/src/virtual_network/iface_stat.py
1. No ACPI, remove from definition
2. Our domain uses security driver 'dac' which is not available for unprivileged users. Remove it.
=> iface_stat: fix test on s390x

libvirt/tests/src/numa/guest_numa_node_tuning/auto_memory_nodeset_placement.py
test result:
1. all numa node have cpu:
(01/36) type_specific.io-github-autotest-libvirt.guest_numa_node_tuning.auto_memory_nodeset_placement.without_iothread.nodeset_defined.mem_mode_strict.vcpu_auto: PASS (33.24 s)
(02/36) type_specific.io-github-autotest-libvirt.guest_numa_node_tuning.auto_memory_nodeset_placement.without_iothread.nodeset_defined.mem_mode_strict.vcpu_static: PASS (32.48 s)
(03/36) type_specific.io-github-autotest-libvirt.guest_numa_node_tuning.auto_memory_nodeset_placement.without_iothread.nodeset_defined.mem_mode_interleave.vcpu_auto: PASS (42.53 s)
(04/36) type_specific.io-github-autotest-libvirt.guest_numa_node_tuning.auto_memory_nodeset_placement.without_iothread.nodeset_defined.mem_mode_interleave.vcpu_static: PASS (36.52 s)
(05/36) …
=> Ignore the numa node without cpu

libvirt/tests/cfg/viommu_netperf.cfg, libvirt/tests/cfg/virtual_network/connectivity/netperf_nat_interface.cfg, libvirt/tests/src/sriov/vIOMMU/viommu_netperf.py, libvirt/tests/src/virtual_network/connectivity/netperf_nat_interface.py, provider/virtual_network/network_base.py
This PR adds:
VIRT-302078 - Do netperf stress test for iommu enabled interface 
VIRT-301971 - Do netperf stress test for nat network interface
```
_aarch64:_
(01/18) type_specific.io-github-autotest-libvirt.vIOMMU.netperf.TCP_STREAM.guest2guest.virtio_interface.virtio: PASS (106.22 s)
(02/18) type_specific.io-github-autotest-libvirt.vIOMMU.netperf.TCP_STREAM.guest2guest.virtio_interface.smmuv3: PASS (103.64 s)
(03/18) type_specific.io-github-autotest-libvirt.vIOMMU.netperf.TCP_STREAM.host2guest.virtio_interface.virtio: PASS (96.00 s)
(04/18) type_specific.io-github-autotest-libvirt.vIOMMU.netperf.TCP_STREAM.host2guest.virtio_interface.smmuv3: PASS (96.35 s)
(05/18) type_specific.io-github-autotest-libvirt.vIOMMU.netperf.TCP_STREAM.guest2host.virtio_interface.virtio: PASS …
```
=> network: Add netperf testing

libvirt/tests/cfg/memory/memory_backing/hugepage_nodeset.cfg, libvirt/tests/src/memory/memory_backing/hugepage_nodeset.py
command shows no result
`# avocado list --vt-type libvirt memory `
After the fix:
```
avocado-vt type_specific.io-github-autotest-libvirt.memory.devices.invalid_nvdimm.with_numa.exceed_slot
avocado-vt type_specific.io-github-autotest-libvirt.memory.devices.invalid_nvdimm.with_numa.max_addr
avocado-vt type_specific.io-github-autotest-libvirt.memory.devices.invalid_nvdimm.with_numa.unexisted_node
avocado-vt …
```
=> Change variants name to avoid avocado list test case failure

libvirt/tests/cfg/memory/memory_backing/hugepage_nodeset.cfg, libvirt/tests/src/memory/memory_backing/hugepage_nodeset.py
The variant 'config' in hugepage_nodeset.cfg makes avocado impossible to obtain normal cases.
```
```
` (8/8) type_specific.io-github-autotest-libvirt.memory.backing.nodeset.without_numa.nodeset_not_exist.64k.524288: PASS (5.93 s)
`
=> memory: Fixup 'No case to run' issue

libvirt/tests/src/libvirt_hooks.py
There is know error behind this behavior, where the VM will not start for first time in RHEL-10.0. 
In *hook tests we get the test result "VM Failed to start for some reason!"
Just added more info get proper details and have it linked with correct tasks with same failure.
Failed test:
- rhel.libvirt_hooks.vm.start_stop (from avocado-vt)
=> Added better logging of VM start error

libvirt/tests/cfg/virtual_network/connectivity/connectivity_check_ethernet_interface.cfg, libvirt/tests/src/virtual_network/connectivity/connectivity_check_ethernet_interface.py
- VIRT-296218 - [ethernet] Check connectivity for ethernet type interface with managed='no'
Test result:
```
(1/1) type_specific.local.virtual_network.connectivity_check.ethernet_interface.managed_no.positive_test.tap.two_ifaces.smaller_mtu_multi_ifaces.non_root_user: PASS (82.05 s)
```
=> Update case of connectivity check of ethernet interface

libvirt/tests/cfg/sriov/vIOMMU/viommu_unload_driver.cfg, libvirt/tests/src/sriov/vIOMMU/viommu_unload_driver.py
This PR adds:
VIRT-301883 - [vIOMMU] Test driver load/unload (disable/enable)
```
aarch64:
(1/4) type_specific.io-github-autotest-libvirt.vIOMMU.unload_driver.virtio_interface.vhost_on.virtio: PASS (82.89 s)
(2/4) type_specific.io-github-autotest-libvirt.vIOMMU.unload_driver.virtio_interface.vhost_on.smmuv3: PASS (74.05 s)
(3/4) type_specific.io-github-autotest-libvirt.vIOMMU.unload_driver.virtio_interface.vhost_off.virtio: PASS (94.98 s)
(4/4) type_specific.io-github-autotest-libvirt.vIOMMU.unload_driver.virtio_interface.vhost_off.smmuv3: PASS (73.13 s)
JOB HTML   : /var/log/avocado/job-results/job-2024-10-21T21.11-1e32ed4/results.html
x86_64:
(1/4) …
```
=> vIOMMU: Add a test about driver load/unload

libvirt/tests/src/numa/guest_numa_node_tuning/specific_numa_memory_bind_hugepage.py
test result:
(1/1) type_specific.io-github-autotest-libvirt.guest_numa_node_tuning.specific_numa_memory_bind_hugepage.scarce_numa_mem.mem_mode_preferred: PASS
=> Add numa node free memory page debug info

libvirt/tests/cfg/svirt/umask_value/svirt_umask_files_accessed_by_qemu.cfg, libvirt/tests/src/svirt/umask_value/svirt_umask_files_accessed_by_qemu.py
Configuration of test for aarch64 expects 64k default hp size,, therefore test is not able to start the machine for 4k. 
- added expected default_hp_size into configuration
- added check in the test that VM default_hp_size is same as expected, and update parameters otherwise.
=> Resolve test issue with aarch64 and 4k default hp size

libvirt/tests/cfg/sriov/vIOMMU/iommu_device_settings.cfg
1. Remove a case due to a WONTFIX issue(BZ2181309)
2. Remove incorrect checks
**Test results**
```
(1/2) type_specific.io-github-autotest-libvirt.vIOMMU.iommu_device_settings.pcie_to_pci_bridge_controller.virtio_non_transitional.virtio: STARTED
(1/2) type_specific.io-github-autotest-libvirt.vIOMMU.iommu_device_settings.pcie_to_pci_bridge_controller.virtio_non_transitional.virtio: PASS (42.27 s)
(2/2) type_specific.io-github-autotest-libvirt.vIOMMU.iommu_device_settings.pcie_to_pci_bridge_controller.hostdev_iface.virtio: STARTED
(2/2) type_specific.io-github-autotest-libvirt.vIOMMU.iommu_device_settings.pcie_to_pci_bridge_controller.hostdev_iface.virtio: PASS (55.49 s)
```
=> viommu: Fix pcie_to_pci_bridge_controller for aarch64

libvirt/tests/cfg/save_and_restore/restore_from_local_file.cfg, libvirt/tests/cfg/save_and_restore/save_with_options.cfg, libvirt/tests/src/save_and_restore/restore_from_local_file.py, libvirt/tests/src/save_and_restore/save_to_block.py, libvirt/tests/src/save_and_restore/save_to_nfs.py, libvirt/tests/src/save_and_restore/save_with_formats.py, libvirt/tests/src/save_and_restore/save_with_options.py, libvirt/tests/src/virsh_cmd/domain/virsh_managedsave.py
Test result:
```
(1/1) type_specific.local.save_and_restore.save_with_options.normal.running_vm.no_opt: STARTED
(1/1) type_specific.local.save_and_restore.save_with_options.normal.running_vm.no_opt: PASS (39.63 s)
(1/1) type_specific.local.save_and_restore.save_with_formats.positive_test.raw: STARTED
(1/1) type_specific.local.save_and_restore.save_with_formats.positive_test.raw: PASS (33.16 s)
(1/2) type_specific.local.save_and_restore.save_to_block.qemu_namespace.enabled: STARTED
(1/2) type_specific.local.save_and_restore.save_to_block.qemu_namespace.enabled: PASS (44.88 s)
(2/2) type_specific.local.save_and_restore.save_to_nfs.root_squash.dynamic_ownership_off: STARTED
(2/2) type_specific.local.save_and_restore.save_to_nfs.root_squash.dynamic_ownership_off: PASS (46.37 s)
(1/1) …
```
=> Workaround:Remove multi-queue setting

libvirt/tests/src/virsh_cmd/host/virsh_nodecpustats.py
**Issue:**
Failed to online host cpu 79
_Note: cpu num variable varies depending on the test_
**Fix:**
The cpu.py function online() returns True if the cpu is online and False if the cpu is offline (in other words, true/false is not tied to if the action performed successfully). This is also the case for def offline(cpu). Therefore, in the case when checking if the cpu is successfully turned online, the test should fail if online() returns False.
**Test Passing:**
```
(.libvirt-ci-venv-ci-runtest-1BjoYw) [root@ampere-one-01 ~]# avocado run --vt-type libvirt --vt-omit-data-loss --vt-machine-type arm64-mmio virsh.nodecpustats.disable_enable_cpu --vt-connect-uri qemu:///system
No python imaging library installed. Screendump and Windows guest BSOD detection are disabled. In order to enable …
```
=> virsh_nodecpustats: test_disable_enable_cpu() check if cpu online

libvirt/tests/cfg/migration/migrate_mem.cfg
1. cpu mode should be host-passthrough on aarch64
2. sve disabled feature is not needed on both aarch64 and x86_64
Test results:
```
2024-10-30 01:29:14,803 avocado.app human            L0129 DEBUG|  (1/1) type_specific.io-github-autotest-libvirt.virsh.migrate_mem.mem_device:
2024-10-30 01:29:14,803 avocado.app human            L0136 DEBUG| ^[[1D^[[92mPASS^[[0m (149.47 s)
```
=> migration: Fix cpu mode and feature for aarch64

libvirt/tests/cfg/daemon/qemu_monitor_socket_creation_delay.cfg, libvirt/tests/src/daemon/qemu_monitor_socket_creation_delay.py
Update cfg file to add a missing 'emulator_dict' parameter.
=> qemu_monitor_socket_creation_delay: Fix a parameter issue

libvirt/tests/cfg/migration/migrate_vm.cfg
To avoid clearing the nfs environment twice, clear storage_type in the test to skip setup/cleanup nfs parts.
` (1/1) type_specific.io-github-autotest-libvirt.virsh.migrate_vm.positive_testing.live_migration.cpuset.without_postcopy: ERROR: Failures occurred while postprocess:\nFailed to run: ssh root@10.6.8.64 -o StrictHostKeyChecking=no 'umount -l /var/lib/libvirt/migrate' (172.35 s)
`
```
(1/1) type_specific.io-github-autotest-libvirt.virsh.migrate_vm.positive_testing.live_migration.cpuset.without_postcopy: PASS (135.99 s)
(1/5) type_specific.io-github-autotest-libvirt.virsh.migrate_vm.positive_testing.live_migration.with_hugepages.without_postcopy: STARTED
(1/5) type_specific.io-github-autotest-libvirt.virsh.migrate_vm.positive_testing.live_migratio …
```
=> migrate_vm: Fixup umount failure

libvirt/tests/cfg/controller/pci_controller_memreserve.cfg, libvirt/tests/src/controller/pci_controller_memreserve.py
Case ID: XXXX-301516
Test scenarios: test memReserve option for a controller is functional.
- pcie-root-port
- pci-bridge
=> pci_controller_memreserve: add new case

libvirt/tests/cfg/memory/memory_devices/virtio_mem_with_memory_allocation_and_numa.cfg, libvirt/tests/src/memory/memory_devices/virtio_mem_with_memory_allocation_and_numa.py, provider/memory/memory_base.py
xxxx-299031 Virtio-mem device with various memory allocation and guest numa settings.
```
avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 memory.devices.virtio_mem.memory_allocation_and_numa
(01/27) type_specific.io-github-autotest-libvirt.memory.devices.virtio_mem.memory_allocation_and_numa.define_guest.virtio_mem_with_node.without_numa.no_maxmemory: PASS (40.78 s)
(02/27) type_specific.io-github-autotest-libvirt.memory.devices.virtio_mem.memory_allocation_and_numa.define_guest.virtio_mem_with_node.without_numa.with_maxmemory: PASS (75.51 s)
(03/27) type_specific.io-github-autotest-libvirt.memory.devices.virtio_mem.memory_allocation_and_numa.define_guest.virtio_mem_with_node.with_numa.no_maxmemory: PASS (42.39 s)
(04/27) …
```
=> add case for virtio memory with various memory allocation and guest numa

libvirt/tests/cfg/memory/memory_devices/virtio_mem_hot_unplug.cfg
unplug error msg needs to get compability
```
avocado run --vt-type libvirt --vt-machine-type arm64-mmio memory.devices.virtio_mem.hot_unplug.detach.none_zero_current --vt-connect-uri qemu:///system
(1/1) type_specific.io-github-autotest-libvirt.memory.devices.virtio_mem.hot_unplug.detach.none_zero_current: PASS (152.72 s)
avocado run --vt-type libvirt  --vt-machine-type arm64-mmio memory.devices.virtio_mem.hot_unplug.detach.none_zero_request --vt-connect-uri qemu:///system
(1/1) type_specific.io-github-autotest-libvirt.memory.devices.virtio_mem.hot_unplug.detach.none_zero_request: PASS (153.04 s)
```
=> fix virtio memory unplug case error msg compability issue

libvirt/tests/src/memory/memory_devices/virtio_memory_with_numa_node_tuning.py
give default value for clean file
```
avocado run --vt-type libvirt --vt-omit-data-loss --vt-machine-type arm64-mmio memory.devices.virtio.with_numa_tuning --vt-connect-uri qemu:///system
(01/24) type_specific.io-github-autotest-libvirt.memory.devices.virtio.with_numa_tuning.cold_plug.with_source_virtio_mem.strict: STARTED
(01/24) type_specific.io-github-autotest-libvirt.memory.devices.virtio.with_numa_tuning.cold_plug.with_source_virtio_mem.strict: CANCEL: Expect 2 numa nodes at least, but found 1 (29.23 s)
(02/24) type_specific.io-github-autotest-libvirt.memory.devices.virtio.with_numa_tuning.cold_plug.with_source_virtio_mem.interleave: STARTED
(02/24) type_specific.io-github-autotest-libvirt.memory.devices.virtio.with_numa_tuning.cold_plug.with_so …
```
=> fix memory case failed due to empty clean file in teardown

libvirt/tests/cfg/backingchain/virsh_domblk/domblkthreshold_with_backingchain_element.cfg, libvirt/tests/src/backingchain/virsh_domblk/domblkthreshold_with_backingchain_element.py
xxxx-294599: Do domblkthreshold for device with backing chain element
```
avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 backingchain.virsh_domblk
(1/2) type_specific.io-github-autotest-libvirt.backingchain.virsh_domblk.backing_target: PASS (117.66 s)
(2/2) type_specific.io-github-autotest-libvirt.backingchain.virsh_domblk.entire_disk: PASS (100.99 s)
```
=> case update: add new disk to check domblkthreshold

libvirt/tests/src/numa/numa_memAccess.py, libvirt/tests/src/numa/numa_node_tuning/auto_mem_placement_with_incompatible_host_nodeset.py
Test result:
(1/1) type_specific.io-github-autotest-libvirt.numa_memAccess.invalid: PASS (19.08 s)
(1/1) type_specific.io-github-autotest-libvirt.guest_numa_node_tuning.incompatible_host_nodeset.strict: PASS (20.61 s)
=> Fix test log related irregular usage

libvirt/tests/cfg/migration/destructive_operations_around_live_migration/kill_qemu_during_finishphase.cfg, libvirt/tests/cfg/migration/migration_performance_tuning/migration_timeout_action.cfg, libvirt/tests/src/migration/destructive_operations_around_live_migration/kill_qemu_during_finishphase.py, provider/migration/migration_base.py
When vm state is wrong, libvirt.check_vm_state don't report the error.
So update check_vm_status_during_mig() and use it to check vm state.
=> migration: Update check vm state method

libvirt/tests/cfg/virtual_network/connectivity/connectivity_check_ethernet_interface.cfg, libvirt/tests/src/virtual_network/connectivity/connectivity_check_ethernet_interface.py, provider/virtual_network/network_base.py
- VIRT-296218 - [ethernet] Check connectivity for ethernet type interface with managed='no'
Test result:
```
(01/11) type_specific.local.virtual_network.connectivity_check.ethernet_interface.managed_no.positive_test.tap.one_iface.no_mtu.non_root_user: STARTED
(01/11) type_specific.local.virtual_network.connectivity_check.ethernet_interface.managed_no.positive_test.tap.one_iface.no_mtu.non_root_user: PASS (69.17 s)
(02/11) type_specific.local.virtual_network.connectivity_check.ethernet_interface.managed_no.positive_test.tap.one_iface.larger_mtu.non_root_user: STARTED
(02/11) type_specific.local.virtual_network.connectivity_check.ethernet_interface.managed_no.positive_test.tap.one_iface.larger_mtu.non_root_user: PASS (72.34 s)
(03/11) …
```
=> Update case:connectivity check of ethernet type interface

libvirt/tests/cfg/migration/migration_uri/tls_migrate_tls_x509_verify_on_src.cfg, libvirt/tests/cfg/migration/migration_uri/tls_migrate_tls_x509_verify_on_target.cfg, libvirt/tests/src/migration/migration_uri/tls_migrate_tls_x509_verify.py
XXX-298257 - [VM migration] network data transport - TLS
- default/migrate_tls_x509_verify on src host
XXX-293815 - [VM migration] network data transport - TLS
- default/migrate_tls_x509_verify on target host(enable/disable verify client)
=> migration: Add two cases about migrate_tls_x509_verify

libvirt/tests/src/virsh_cmd/domain/virsh_managedsave.py
For the case "managedsave.status_error_no.name_option.paused_status" we need to prepare the VM to be in paused state before managedsave.
=> Prepare certain state before managedsave

libvirt/tests/src/virtual_network/iface_stat.py
Send control+c to cancel previous command to make sure the next command could be executed correctly.
Test result:
```
(1/1) type_specific.local.virtual_network.iface_stat.compare.ethernet_type.managed_no.macvtap: STARTED
(1/1) type_specific.local.virtual_network.iface_stat.compare.ethernet_type.managed_no.macvtap: PASS (222.66 s)
(1/1) type_specific.local.virtual_network.iface_stat.compare.direct_type: STARTED
(1/1) type_specific.local.virtual_network.iface_stat.compare.direct_type: PASS (209.92 s)
(1/2) type_specific.io-github-autotest-libvirt.virtual_network.iface_stat.compare.direct_type: STARTED
(1/2) type_specific.io-github-autotest-libvirt.virtual_network.iface_stat.compare.direct_type: PASS (222.56 s)
(2/2) type_specific.io-github-autotest-libvirt.virtual_network.iface_stat.compare. …
```
=> iface_stat:Fix error of command timeout

libvirt/tests/cfg/virtual_device/tpm_device.cfg, libvirt/tests/src/virtual_device/tpm_device.py
Add two classical values '5','20' test, and a negative '-1' test. Swtpm/libtpms debugging is very much non-stable/non-contract thing according to developer, our QE can first check sth different from non-setting, not sure the obvious difference between each level.
=> tpm_device: add swtpm debug logging test

libvirt/tests/src/virtio/virtio_page_per_vq.py
Fix the failure of "argument must be an int, or have a fileno() method" occasionally because the script didn't use an open session in utils_net function().
=> virtio_attributes: fix an argument failure for virtio_page_per_vq

libvirt/tests/cfg/security/rng/libvirt_rng.cfg, libvirt/tests/src/security/rng/libvirt_rng.py
Updated Case IDs:  VIRT-17260 RHEL-112509 VIRT-98364 VIRT-96327 VIRT-98408 VIRT-98365 RHEL-188620 VIRT-98425 
**Case Updates**
1.  From  kernel-5.14.0-298.el9, the default rng_current may not be virtio_rng if vm has other rng devices such as tpm, need manually switch to it
2. Ensure `[root@localhost ~]# cat /sys/devices/virtual/misc/hw_random/rng_available` does not include virtio rng device after it was detached
**This case update is due to the following issue:**
**Issue:**
Failed to check rng file on guest. The virtio device is not the current rng device.
**More specifically:**
L0333 DEBUG| rng avail:tpm-rng-0 virtio_rng.0, current:tpm-rng-0
**Tests passing:**
=> Libvirt_rng: update codes for hotplug rng_current check

libvirt/tests/src/sriov/vIOMMU/hotplug_device_with_iommu_enabled.py
Update to check the events to make sure the disk is attached correctly.
Test results: executed 20 times, all passed:
`  (1/1) type_specific.io-github-autotest-libvirt.vIOMMU.hotplug_device_with_iommu_enabled.scsi_controller.virtio: PASS (47.42 s)
`
=> vIOMMU: Update to wait events after disk is attached

libvirt/tests/cfg/daemon/conf_file/sysconfig_libvirt_guests/libvirt_guests.cfg, libvirt/tests/src/daemon/conf_file/sysconfig_libvirt_guests/libvirt_guests.py
xxxx-300726:suspend or shutdown VM with PERSISTENT_ONLY - via restarting libvirt-guests.service
Existed two bugs xxxx-56142 xxxx-56145
```
avocado run --vt-type libvirt --test-runner=runner --vt-machine-type q35 managedsave.libvirt_guests.positive_test..with_transient_vm
(1/8) type_specific.io-github-autotest-libvirt.managedsave.libvirt_guests.positive_test.no_parallel_shutdown.suspend_on_shutdown.default_vol.none_on_boot.with_transient_vm.persistent_only_none: PASS (79.00 s)
(2/8) type_specific.io-github-autotest-libvirt.managedsave.libvirt_guests.positive_test.no_parallel_shutdown.suspend_on_shutdown.default_vol.none_on_boot.with_transient_vm.persistent_only_true: PASS (98.31 s)
(3/8) type_specific.io-github-autotest-libvirt.managedsave.libvirt_gue …
```
=> add case for suspend or shutdown vm via libvirt-guest service

libvirt/tests/cfg/cpu/multi_vms_with_stress.cfg, libvirt/tests/src/cpu/multi_vms_with_stress.py
Case ID: VIRT-301893
Automates the case that tests that multiple vms can use #host_only_cpu to start when stress workload is running on the host.
**Test steps:**
1. Prepare 3 vms that each have even vcpu number around 2/3 of # host_online_cpu
2. Start stress workload on the host
3. Start all vms and verify vms could be logged in normally
4. Verify all vms could be gracefully shutdown successfully
**Evidence of tests passing:**
```
(.libvirt-ci-venv-ci-runtest-TSPbXe) [root@ampere-mtsnow-altramax-31 ~]# avocado run --vt-type libvirt multi_vms_with_stress
No python imaging library installed. PPM image …
```
=>  Multi_vms_with_stress: add a test about starting VMs with stress workload on host

libvirt/tests/src/memory/memory_allocation/define_value_unit.py
test results:
(1/7) type_specific.io-github-autotest-libvirt.memory.allocation.define_value_unit.without_numa.positive_test.bytes: STARTED
(1/7) type_specific.io-github-autotest-libvirt.memory.allocation.define_value_unit.without_numa.positive_test.bytes: PASS (17.34 s)
(2/7) type_specific.io-github-autotest-libvirt.memory.allocation.define_value_unit.without_numa.positive_test.KB: STARTED
(2/7) type_specific.io-github-autotest-libvirt.memory.allocation.define_value_unit.without_numa.positive_test.KB: PASS (14.56 s)
(3/7) type_specific.io-github-autotest-libvirt.memory.allocation.define_value_unit.without_numa.positive_test.KiB: STARTED
(3/7) type_specific.io-github-autotest-libvirt.memory.allocation.define_value_unit.without_numa.positive_test.KiB: PASS (14.50 s)
(4/7) …
=> Fix irregular usage of test log

libvirt/tests/src/virtual_network/iface_bridge.py, libvirt/tests/src/virtual_network/iface_network.py, libvirt/tests/src/virtual_network/iface_options.py, libvirt/tests/src/virtual_network/virtual_network_multivms.py
Test result:
```
(1/3) type_specific.io-github-autotest-libvirt.virtual_network.iface_options.iface_type.type_user.default: STARTED
(1/3) type_specific.io-github-autotest-libvirt.virtual_network.iface_options.iface_type.type_user.default: PASS (65.91 s)
(2/3) type_specific.io-github-autotest-libvirt.virtual_network.iface_options.iface_type.type_user.type_user_set_ip.ignore_prefix: STARTED
(2/3) type_specific.io-github-autotest-libvirt.virtual_network.iface_options.iface_type.type_user.type_user_set_ip.ignore_prefix: PASS (123.55 s)
(3/3) type_specific.io-github-autotest-libvirt.virtual_network.iface_options.iface_type.type_user.type_user_set_ip.set_prefix: STARTED
(3/3) type_specific.io-github-autotest-libvirt.virtual_network.iface_options.iface_type.type_user.type_user_set_ip.set_prefix: …
```
=> iface_options:Fix error of get wrong ip addr

libvirt/tests/src/virtual_network/passt/passt_connectivity_between_2vms.py, provider/virtual_network/passt.py
Depends on
- https://github.com/avocado-framework/avocado-vt/pull/4029
Test result:
```
(1/1) type_specific.io-github-autotest-libvirt.virtual_network.passt.reconnect.ip_portfw.root_user: STARTED
(1/1) type_specific.io-github-autotest-libvirt.virtual_network.passt.reconnect.ip_portfw.root_user: PASS (243.66 s)
(1/1) type_specific.io-github-autotest-libvirt.virtual_network.passt.interface_function.minimal.non_root_user: STARTED
(1/1) type_specific.io-github-autotest-libvirt.virtual_network.passt.interface_function.minimal.non_root_user: PASS (120.16 s)
(1/1) type_specific.io-github-autotest-libvirt.virtual_network.passt.connectivity_between_2vms.ip_portfw.root_user: STARTED
(1/1) type_specific.io-github-autotest-libvirt.virtual_network.passt.connectivity_between_2vms.ip_portfw.root_user: …
```
=> passt:Fix error of getting wrong gateway

provider/interface/interface_base.py
Depends on
- https://github.com/avocado-framework/avocado-vt/pull/4032
Test result:
```
(1/3) type_specific.io-github-autotest-libvirt.virtual_network.update_device.iface_link_state.network.virtio.add: STARTED
(1/3) type_specific.io-github-autotest-libvirt.virtual_network.update_device.iface_link_state.network.virtio.add: PASS (46.39 s)
(2/3) type_specific.io-github-autotest-libvirt.virtual_network.elements_and_attributes.model.default: STARTED
(2/3) type_specific.io-github-autotest-libvirt.virtual_network.elements_and_attributes.model.default: PASS (53.52 s)
(3/3) type_specific.io-github-autotest-libvirt.virtual_network.link_state.model.network.e1000e.initial_up: STARTED
(3/3) type_specific.io-github-autotest-libvirt.virtual_network.link_state.model.network.e1000e.initial_up: PASS (57.87 …
```
=> interface_base:Add --color=never to ip command

libvirt/tests/cfg/virtual_network/attach_detach_device/attach_iface_with_boot_order.cfg, libvirt/tests/cfg/virtual_network/iface_attach_detach.cfg, libvirt/tests/cfg/virtual_network/iface_update.cfg
On s390x, only per-device <boot/> is supported. Disable test expecting conflict with //os/boot
=> virtual_network: disable test cases with mixed boot order elements

libvirt/tests/src/daemon/crash_regression.py
Fix crash_regression_mix_boot_order_os_boot failure
os_xml.boots support list instead of dictionary
=> Fix crash_regression_mix_boot_order_os_boot failure

libvirt/tests/src/guest_os_booting/migration/migration_boot.py, libvirt/tests/src/migration/migration_with_vtpm/migration_with_external_tpm.py, libvirt/tests/src/migration/migration_with_vtpm/migration_with_shared_tpm.py, provider/migration/base_steps.py
Use migrate_vm_back option in avocado-vt/share/cfg/base.cfg to determine whether to migrate vm back to source host.
=> migration: Using migrate_vm_back option

libvirt/tests/src/memory/memory_devices/virtio_mem_with_memory_allocation_and_numa.py
missing one format label
```
avocado run --vt-type libvirt --vt-omit-data-loss --vt-machine-type q35 memory.devices.virtio_mem.memory_allocation_and_numa.define_guest.virtio_mem_with_node.without_numa.with_maxmemory memory.devices.virtio_mem.memory_allocation_and_numa.define_guest.virtio_mem_with_node.with_numa.with_maxmemory memory.devices.virtio_mem.memory_allocation_and_numa.define_guest.virtio_mem_without_node.without_numa.with_maxmemory   --vt-connect-uri qemu:///system 
(1/3) type_specific.io-github-autotest-libvirt.memory.devices.virtio_mem.memory_allocation_and_numa.define_guest.virtio_mem_with_node.without_numa.with_maxmemory: PASS (92.64 s)
(2/3) type_specific.io-github-autotest-libvirt.memory.devices.virtio_mem.memory_allocation_and_numa.d …
```
=> fix memory cases format output fail due regex issue

libvirt/tests/cfg/cpu/max_vcpus.cfg, libvirt/tests/src/cpu/max_vcpus.py
need change expected num after qemu bump up the max vcpu, due to feature updated by RHEL-11579
Before fixed 
`Test failed as the q35_max_vcpus_num in virsh_capa is wrong. Expected: 710 Actual: 4096.
`
After fixed
```
avocado run --vt-type libvirt --vt-omit-data-loss --vt-machine-type q35 max_vcpus.virsh_capabilities --vt-connect-uri qemu:///system
(1/1) type_specific.io-github-autotest-libvirt.max_vcpus.virsh_capabilities: PASS (6.79 s)
```
=> fix maxvcpu num due to qemu update

libvirt/tests/cfg/migration/migrate_network.cfg, libvirt/tests/src/migration/migrate_network.py
direct-macvtap uses host interfaces on source and target. Make them configurable by their name.
=> migrate_network: enable configuration of host interface

libvirt/tests/src/virsh_cmd/domain/virsh_detach_device_alias.py, libvirt/tests/src/virtual_disks/virtual_disks_gluster.py, libvirt/tests/src/virtual_network/iface_coalesce.py, libvirt/tests/src/vm_boot_with_kernel_param.py
test.skip is not used any more.
=> virsh_detach_device_alias: remove test.skip

libvirt/tests/cfg/virtio/virtio_page_per_vq.cfg, libvirt/tests/src/virtio/virtio_page_per_vq.py
Regarding /dev/input/event* files, there might be some different situation.
For example,
- No event file exsit at all
- Only /dev/input/event0 exists
- Only /dev/input/event1 exists
- Both /dev/input/event0 and /dev/input/event1 exists
- and more ...
So this patch is intending to support above situations instead of hardcoding with event1.
=> virtio_page_per_vq: enhance input event file

libvirt/tests/cfg/save_and_restore/save_with_options.cfg, libvirt/tests/src/save_and_restore/save_with_options.py
Add steps to monitor with domjobinfo and check domstate reason
Test result:
```
(1/3) type_specific.local.save_and_restore.save_with_options.readonly.running_vm.no_opt: STARTED
(1/3) type_specific.local.save_and_restore.save_with_options.readonly.running_vm.no_opt: PASS (24.44 s)
(2/3) type_specific.local.save_and_restore.save_with_options.normal.running_vm.no_opt: STARTED
(2/3) type_specific.local.save_and_restore.save_with_options.normal.running_vm.no_opt: PASS (39.92 s)
(3/3) type_specific.local.save_and_restore.save_with_options.normal.paused_vm.no_opt: STARTED
(3/3) type_specific.local.save_and_restore.save_with_options.normal.paused_vm.no_opt: PASS (48.85 s)
```
=> Update case of save_with_options

libvirt/tests/cfg/virtual_network/update_device/update_iface_qos_invalid.cfg, libvirt/tests/src/virtual_network/update_device/update_iface_qos_invalid.py
- VIRT-294768 - update-device qos Live update the QoS setting by update-device with invalid values
Test result:
```
(1/5) type_specific.local.virtual_network.update_device.iface_qos.invalid.neg_value: STARTED
(1/5) type_specific.local.virtual_network.update_device.iface_qos.invalid.neg_value: PASS (29.51 s)
(2/5) type_specific.local.virtual_network.update_device.iface_qos.invalid.big_value: STARTED
(2/5) type_specific.local.virtual_network.update_device.iface_qos.invalid.big_value: PASS (31.35 s)
(3/5) type_specific.local.virtual_network.update_device.iface_qos.invalid.max_value: STARTED
(3/5) type_specific.local.virtual_network.update_device.iface_qos.invalid.max_value: PASS (37.01 s)
(4/5) type_specific.local.virtual_network.update_device.iface_qos.invalid.no_mandatory_average: STARTED …
```
=> Update case of rejecting big inbound average values

libvirt/tests/cfg/virtual_network/iface_network.cfg, libvirt/tests/src/virtual_network/iface_network.py
- VIRT-63196 - [virtual network] define a network with forward mode 'open'
Test result:
```
(1/1) type_specific.local.virtual_network.iface_network.net_forward.net_open.negative_without_ip: STARTED
(1/1) type_specific.local.virtual_network.iface_network.net_forward.net_open.negative_without_ip: PASS (8.76 s)
```
=> Update network case of defining net without ip

libvirt/tests/cfg/virsh_cmd/domain/virsh_memtune.cfg
Expanding memtune values on ARM platforms
ID:2908
Signed-off-by: zhenyzha [zhenyzha@redhat.com](mailto:zhenyzha@redhat.com)
=> virsh_memtune: Expanding memtune values on ARM platforms

libvirt/tests/cfg/migration/abort_precopy_migration/abort_by_domjobabort_on_target.cfg, libvirt/tests/cfg/migration/migration_uri/migration_desturi.cfg
Several tests are failing with No migration result. 
The migration will continue till the test timoute (15min) is hit and the migration is interrupted.
As the test is not focused on the performance, the speed  can be enlarged. 
According my investigation, from the value migration-speed=12 is it working.
=> Resolve No migration result issue on aarch64 caused by low speed

libvirt/tests/cfg/virtual_network/network/net_update_dns.cfg, libvirt/tests/src/virtual_network/network/net_update_dns.py
- VIRT-298984 - [net-update] Add/delete dns section (dns-srv dns-txt dns-host) by net-update
Depends on:
- https://github.com/avocado-framework/avocado-vt/pull/4014
Test result:
```
(1/5) type_specific.local.virtual_network.network.net_update_dns.modify.dns-txt.default: STARTED
(1/5) type_specific.local.virtual_network.network.net_update_dns.modify.dns-txt.default: PASS (8.94 s)
(2/5) type_specific.local.virtual_network.network.net_update_dns.modify.dns-txt.incomplete.no_value: STARTED
(2/5) type_specific.local.virtual_network.network.net_update_dns.modify.dns-txt.incomplete.no_value: PASS (8.76 s)
(3/5) type_specific.local.virtual_network.network.net_update_dns.modify.dns-txt.incomplete.no_name: STARTED
(3/5) type_specific.local.virtual_network.network.net_update_dns.modify.dns-txt.incomp …
```
=> Add case update of net-update:

libvirt/tests/cfg/virtual_network/iface_bridge.cfg, libvirt/tests/src/virtual_network/iface_bridge.py
On our test environment we must use not the first host interface. Make configurable but maintain default behavior if not configured.
=> iface_bridge: make host interface configurable

libvirt/tests/cfg/sriov/vIOMMU/intel_iommu_with_dma_translation.cfg, libvirt/tests/src/sriov/vIOMMU/intel_iommu_with_dma_translation.py
Automate new dma_translation attribute for vIOMMU: 
VIRT-302220 - [vIOMMU][intel] Start VM with intel iommu and dma_translation attribute
=> SRIOV: add new test case of dma_translation for vIOMMU

libvirt/tests/cfg/virsh_cmd/domain/virsh_domiftune.cfg
RHEL-65372 has set clear boundary and error message
Test result:
```
(1/6) type_specific.local.virsh.domiftune.positive_testing.set_domif_parameter.running_guest.change_inbound.options.live.maximum_boundary: STARTED
(1/6) type_specific.local.virsh.domiftune.positive_testing.set_domif_parameter.running_guest.change_inbound.options.live.maximum_boundary: PASS (52.39 s)
(2/6) type_specific.local.virsh.domiftune.positive_testing.set_domif_parameter.running_guest.change_inbound.options.current.maximum_boundary: STARTED
(2/6) type_specific.local.virsh.domiftune.positive_testing.set_domif_parameter.running_guest.change_inbound.options.current.maximum_boundary: PASS (34.96 s)
(3/6) type_specific.local.virsh.domiftune.positive_testing.set_domif_parameter.running_guest.change_inbound.options.none.ma …
```
=> virsh_domiftune:Update max boundary test

libvirt/tests/src/backingchain/blockcopy/blockcopy_with_zero_length_disk.py
virsh cmd should use debug=True , not shell=True
=> fix virsh create use incorrect log operation

libvirt/tests/src/backingchain/blockjob/blockjob_with_raw_option.py
Current blockcopy will timeout in 100s. Extend the time to be 300s which is enough for the operation to finish.
=> Extend the time for blockcopy to finish

libvirt/tests/cfg/virtio_transitional/virtio_transitional_nic.cfg, libvirt/tests/src/virtio_transitional/virtio_transitional_nic.py
On s390x, pci bridge is not available. Don't attach this.
=> virtio_transitional_nic: don't attach incompatible controller

libvirt/tests/cfg/virtual_network/qos/check_actual_network_throughput_direct.cfg
Reduce average value to avoid test failure
Test result: 
```
(1/2) type_specific.io-github-autotest-libvirt.virtual_network.qos.check_actual_network_throughput.direct.with_network: STARTED
(1/2) type_specific.io-github-autotest-libvirt.virtual_network.qos.check_actual_network_throughput.direct.with_network: PASS (119.70 s)
(2/2) type_specific.io-github-autotest-libvirt.virtual_network.qos.check_actual_network_throughput.direct.without_network: STARTED
(2/2) type_specific.io-github-autotest-libvirt.virtual_network.qos.check_actual_network_throughput.direct.without_network: PASS (136.43 s)
```
=> check_actual_network_throughput_direct:Reduce average value

libvirt/tests/src/migration/migrate_vm.py
On s390x the /proc/cpuinfo output looks different from the one on x86_64.
This could apply to other archs, too. So, if the first regex doesn't match, try the other one.
Output on x86_64 F40 6.11 kernel:
```
grep processor /proc/cpuinfo
processor	: 0
processor	: 1
processor	: 2
processor	: 3
processor	: 4
...
```
Output on s390x RHEL 9 kernel 5.14:
```
processor 0: version = FF,  identification = 2EB428,  machine = 8561
processor 1: version = FF,  identification = 2EB428,  machine = 8561
processor 2: version = FF,  identification = 2EB428,  machine = 8561
processor 3: version = FF,  identification = 2EB428,  machine = 8561
```
=> migrate_vm: fix cpu list on s390x

libvirt/tests/src/migration/migrate_options_shared.py
The auto-converge test scenarios are brittle. In order to cause auto-converge to kick in we need to reduce allowed downtime and bandwidth and increase creation of dirty-pages. However, by setting unrealisticly restrictive values we might cause the migration to never converge. Therefore, once auto-converge has kicked in, reset bandwidth and maxdowntime so that the migration can finish more easily.
Furthermore, remove function `run_stress_in_vm` as it's not used
anywhere. Instead
avocado-vt/virttest/migration/run_stress_in_vm is used.
=> migrate_options_shared: stabilize auto-converge

libvirt/tests/cfg/migration/migrate_vm.cfg
The test creates an unbootable disk. On s390x, the VM will immediately stop running. So, the rest of the test steps can't execute.
=> migrate_vm: disable negative test

libvirt/tests/cfg/virtual_network/link_state/link_state_model_type.cfg
ethernet was missing host-iface and failed
move the parameter to the top to apply it to all tests
=> virtual_network/link_state: configure host_iface for all tests

libvirt/tests/src/snapshot/delete_external_snap_with_references.py, libvirt/tests/src/snapshot/revert_disk_external_snap.py, libvirt/tests/src/snapshot/revert_snapshot_after_xml_updated.py
Fix "No console available" issues in some snapshot scripts: 
1) delete_external_snap_with_references.py: this script starts the guest
twice. So I added an if statement to check vm.is_alive in the second
time.
2) Another two scripts, to make sure the second console is same and
pure. I added vm.cleanup_serial_console and vm.create_serial_console
before the second time.
=> Snapshot: fix console failure when using the console for the second time

libvirt/tests/cfg/virtual_network/update_device/update_iface_with_unchangable.cfg
On s390x ROM not available. Remove from config.
=> update_iface_with_unchangable: remove rom for s390x

libvirt/tests/src/migration/migrate_with_virtual_devices.py
As there might be other built-in rng devices, we only need to check
if attached virtio rng is in rng_available.
=> migrate_with_virtual_devices: fix rng check method

libvirt/tests/src/daemon/conf_file/sysconfig_libvirt_guests/libvirt_guests.py
If there is no "on_boot" setting in libvirt_guests.conf, the behavior will be the same with "on_boot=start" for running VM. Refer to libvirt.org: "By default, libvirt-guests will suspend running guests when the host shuts down, and restore them to their pre-shutdown state when the host reboots."
=> Update the expectation for libvirt_guests

libvirt/tests/cfg/virtual_network/update_device/unsupported_live_update_alter.cfg, libvirt/tests/cfg/virtual_network/update_device/unsupported_live_update_delete.cfg, libvirt/tests/src/virtual_network/update_device/unsupported_live_update.py
unsupported_live_update:Remove interface backend settings before setting
new value
Since the original dict value won't be deleted automatically, but we
want to remove one attribute.
And don't remove interfaces on vmxml before test setting.
And remove 2 test cases that are no need to test (bug won't do)
Test result:
```
(01/29) type_specific.local.virtual_network.update_device.unsupported_live_update.delete.acpi_index: STARTED
(01/29) type_specific.local.virtual_network.update_device.unsupported_live_update.delete.acpi_index: PASS (29.74 s)
(02/29) type_specific.local.virtual_network.update_device.unsupported_live_update.delete.sndbuf: STARTED
(02/29) type_specific.local.virtual_network.update_device.unsupported_live_update.delete.sndbuf: PASS (31.57 s)
(03/29) …
```
=> unsupported_live_update:Remove interface backend settings before setting new value

libvirt/tests/cfg/guest_os_booting/boot_order/boot_from_cdrom_device.cfg, libvirt/tests/src/guest_os_booting/boot_order/boot_from_cdrom_device.py
On aarch64, the vm will enter uefi if there's no cdrom device. This is as expected so updating the expected result.
`c (1/1) type_specific.io-github-autotest-libvirt.guest_os_booting.boot_order.cdrom_device.ovmf.os_dev.without_cdrom: FAIL: Login timeout expired    (output: 'exceeded 360 s timeout') (389.46 s)
`
(1/1) type_specific.io-github-autotest-libvirt.guest_os_booting.boot_order.cdrom_device.ovmf.os_dev.without_cdrom: PASS (328.10 s)
=> guest_os_booting: Fix up login timeout issue

libvirt/tests/src/guest_os_booting/boot_order/boot_with_multiple_boot_order.py
Extend timeout of checking vm boot up to make the script more stable
` (1/1) type_specific.io-github-autotest-libvirt.guest_os_booting.boot_order.boot_with_multiple_boot_order.network.cdrom.cdrom_bootable: PASS (332.98 s)
`
=> guest_os_booting: Extend timeout

libvirt/tests/cfg/virtual_network/driver/rx_tx_queue_size.cfg, libvirt/tests/src/virtual_network/driver/rx_tx_queue_size.py
Cannot get tx size from interface xml when it's not set
Test result:
```
(1/9) type_specific.local.virtual_network.driver.rx_tx_queue_size.positive.rx_256_tx_256: STARTED
(1/9) type_specific.local.virtual_network.driver.rx_tx_queue_size.positive.rx_256_tx_256: PASS (34.39 s)
(2/9) type_specific.local.virtual_network.driver.rx_tx_queue_size.positive.rx_512_tx_256: STARTED
(2/9) type_specific.local.virtual_network.driver.rx_tx_queue_size.positive.rx_512_tx_256: PASS (36.93 s)
(3/9) type_specific.local.virtual_network.driver.rx_tx_queue_size.positive.rx_1024_tx_unset: STARTED
(3/9) type_specific.local.virtual_network.driver.rx_tx_queue_size.positive.rx_1024_tx_unset: PASS (44.16 s)
(4/9) type_specific.local.virtual_network.driver.rx_tx_queue_size.negative.rx_128_tx_unset: STARTED
(4/9) …
```
=> rx_tx_queue_size:Skip getting tx size from interface xml

libvirt/tests/src/virtual_network/passt/passt_transfer_file.py
On RHEL 10, the utils_net.get_default_gateway() will get outputs with color, which will be malformed showed in text. Replace it with get_default_gateway_json() can fix the issue.
=> Fix the malformed default gatway

libvirt/tests/cfg/sriov/vIOMMU/intel_iommu_with_dma_translation.cfg, libvirt/tests/src/sriov/vIOMMU/intel_iommu_with_dma_translation.py
The numbers of guest vcpu is better little than the host vcpus' number. But we don't have this host to match 256 cpus. So after discussing we decided to use the same host cpus' number to test guest vcpus.
=> SRIOV: fix "Login timeout expired" because of 256 vcpus

provider/sriov/sriov_base.py
Relying on ipxe build in tests when cannot obtain VF pxe rom file is an unstable testing method. Because this case is mainly to test the xml but not the pxe function. So we decided to use the fixed virtio rom file to test.
The error message:
This test needs rom file: /usr/share/ipxe/8086154c.rom.
=> sriov: fix ipxe rom file issue

provider/bootc_image_builder/bootc_image_build_utils.py, virttools/tests/cfg/bootc_image_builder/bootc_disk_image_build.cfg, virttools/tests/cfg/bootc_image_builder/bootc_disk_image_install.cfg, virttools/tests/src/bootc_image_builder/bootc_disk_image_build.py, virttools/tests/src/bootc_image_builder/bootc_disk_image_install.py
Add new image type:vdh/gce support in bootc image builder
vhd/gce are newly introduced support disk image type, and is only supported on upstream
=> Add new image type:vhd/gce support in bootc image builder

libvirt/tests/cfg/migration/migration_uri/migration_network_data_transport_tls.cfg, libvirt/tests/cfg/migration/migration_with_vtpm/migration_with_shared_tpm.cfg, libvirt/tests/cfg/migration/p2p_keepalive/customized_keepalive.cfg, libvirt/tests/cfg/migration/p2p_keepalive/default_keepalive.cfg, libvirt/tests/cfg/migration/p2p_keepalive/src_and_dest_keepalive_disabled.cfg, libvirt/tests/cfg/migration/p2p_keepalive/src_keepalive_disabled.cfg, libvirt/tests/src/migration/p2p_keepalive/p2p_keepalive.py, provider/migration/base_steps.py, spell.ignore
XXX-298208 - [VM migration] p2p migration with default keepalive configuration
XXX-298209 - [VM migration] p2p migration with src keepalive disabled
XXX-298211 - [VM migration] p2p migration with src and target keepalive disabled
XXX-298214 - [VM migration] p2p migration with customized keepalive_* settings
=> migration: Add 4 cases about keepalive

libvirt/tests/src/virtual_network/connectivity/connectivity_check_user_interface.py
The value of mac getting from vmxml could be None when there's no interface on vm which could lead to Error when trying to set the value to new interface.
Test result:
```
before:
(1/1) type_specific.local.virtual_network.connectivity_check.user_interface.positive_test.default.non_root_user: STARTED
(1/1) type_specific.local.virtual_network.connectivity_check.user_interface.positive_test.default.non_root_user: ERROR: Error in Delter for property "mac_address", element tag "mac" not found on parent at xpath "/" in XML\n<interface type="user"><model type="virtio" /></interface>\n (13.52 s)
after:
(1/1) type_specific.local.virtual_network.connectivity_check.user_interface.positive_test.default.non_root_user: STARTED
(1/1) type_specific.local.virtual_network.connectivity_check.user_interface.p …
```
=> connectivity_check_user_interface:Fix error when setting mac_address

libvirt/tests/src/guest_os_booting/ovmf_firmware/ovmf_backed_nvram.py
The 'templateFormat' is automatically added in os xml and causes the xml comparison to fail.
` (1/1) type_specific.io-github-autotest-libvirt.guest_os_booting.ovmf_backed_nvram.file: FAIL: Configured os xml value {'template': '/usr/share/edk2/aarch64/vars-template-pflash.qcow2', 'type': 'file', 'format': 'qcow2'} doesn't match the entry {'template': '/usr/share/edk2/aarch64/vars-template-pflash.qcow2', 'templateFormat': 'qcow2', 'type': 'fi... (36.60 s)`
` (1/1) type_specific.io-github-autotest-libvirt.guest_os_booting.ovmf_backed_nvram.file: PASS (36.69 s)
`
=> guest_os_booting: Skip templateFormat when comparing os xml

libvirt/tests/cfg/guest_os_booting/ovmf_firmware/ovmf_nvram.cfg, libvirt/tests/src/guest_os_booting/ovmf_firmware/ovmf_nvram.py
1. nvram file should be cleared before the testing
2. error message changed
```
(1/1) type_specific.io-github-autotest-libvirt.guest_os_booting.ovmf_nvram.negative_test.nonexist_template: FAIL: Expect should fail with one of ['error: Failed to open file.+: No such file or directory'], but failed with:\n\n\nerror: Failed to start domain 'avocado-vt-vm1'\nerror: Operation not supported: conversion of the nvram template to another target format is not ... (10.01 s)
JOB HTML   : /var/log/avocado/job-results/job-2024-12-27T04.16-865d082/results.html
JOB TIME   : 11.99 s
Test summary:
1-type_specific.io-github-autotest-libvirt.guest_os_booting.ovmf_nvram.negative_test.nonexist_template: FAIL …
```
=> guest_os_booting: Fix the nonexist_template case error

libvirt/tests/cfg/memory/memory_devices/virtio_mem_with_memory_allocation_and_numa.cfg
test result:
(1/3) type_specific.io-github-autotest-libvirt.memory.devices.virtio_mem.memory_allocation_and_numa.define_guest.virtio_mem_with_exceed_size.without_numa.with_maxmemory: STARTED
(1/3) type_specific.io-github-autotest-libvirt.memory.devices.virtio_mem.memory_allocation_and_numa.define_guest.virtio_mem_with_exceed_size.without_numa.with_maxmemory: PASS (30.36 s)
(2/3) type_specific.io-github-autotest-libvirt.memory.devices.virtio_mem.memory_allocation_and_numa.cold_plug.virtio_mem_with_exceed_size.without_numa.with_maxmemory: STARTED
(2/3) type_specific.io-github-autotest-libvirt.memory.devices.virtio_mem.memory_allocation_and_numa.cold_plug.virtio_mem_with_exceed_size.without_numa.with_maxmemory: PASS (30.34 s)
(3/3) type_specific.io-github-autotest-libvirt.memory.devices.virti …
=> Change request size to fit for 512mb block size on aarch64 64k kernel

libvirt/tests/cfg/virsh_cmd/host/virsh_nodeinfo.cfg, libvirt/tests/src/virsh_cmd/host/virsh_nodeinfo.py
on aarch64 virsh nodeinfo could not get cpu frequency currently, so add skip logic.
test result:
(1/1) type_specific.io-github-autotest-libvirt.virsh.nodeinfo.no_option: STARTED
(1/1) type_specific.io-github-autotest-libvirt.virsh.nodeinfo.no_option: PASS (6.28 s)
=> Add skip logic for cpu frequency checking on aarch64

libvirt/tests/cfg/numa/numa_capabilities.cfg, libvirt/tests/src/numa/numa_capabilities.py
if specific cpu topology file from sysfs doesn't exist, defalut 0 would be used in virsh capabilities.
Depends on avocado-vt pr: https://github.com/avocado-framework/avocado-vt/pull/4047
Test result:
(1/1) type_specific.io-github-autotest-libvirt.numa_capabilities.default: STARTED
(1/1) type_specific.io-github-autotest-libvirt.numa_capabilities.default: PASS (9.83 s)
=> Add default value 0 when specific cpu toplogy file is missing

libvirt/tests/cfg/migration/migration_uri/migration_network_data_transport_tls.cfg, provider/migration/base_steps.py
There was wrong configuration for remote_log file, failing when trying to setup and check the remote log. (script was unable to eval provided value.
I've updated configuration and slightly improved the parameter evaluation, so the test will fail with more meaningful message.
There is no change in test logic.
manual run PASSED on testing environment for RHEL-9.6. ARM
=> Update wrong configuration for migration test for network data transport tls

libvirt/tests/cfg/migration/migration_uri/migration_desturi.cfg
Set 'server_info_ip' parameter to fix authentication failed issue.
=> migration: Fix authentication failed issue for ipv6 test

libvirt/tests/cfg/virsh_cmd/host/virsh_freepages.cfg, libvirt/tests/src/virsh_cmd/host/virsh_freepages.py
Previously, this case is checking cpu flag for 2M and 1G huge page only for x86_64, so it is not fit for aarch64. So the update code add aarch64 supported huge page sizes and remove the cpu flag checking.
test result after fix:
x84
(01/25) type_specific.io-github-autotest-libvirt.virsh.freepages.positive_test.no_pagesize.option_all: PASS (9.42 s)
(02/25) type_specific.io-github-autotest-libvirt.virsh.freepages.positive_test.no_pagesize.each_cells: PASS (8.91 s)
(03/25) type_specific.io-github-autotest-libvirt.virsh.freepages.positive_test.each_pagesize.option_all: PASS (9.10 s)
(04/25) type_specific.io-github-autotest-libvirt.virsh.freepages.positive_test.each_pagesize.each_cells: PASS (9.23 s)
(05/25) type_specific.io-github-autotest-libvirt.virsh.freepages.positive_test.pagesize_2M.optio …
=> Add adaption for aarch64 huge pages

libvirt/tests/src/guest_os_booting/boot_order/boot_from_virtiofs_device.py
rhel9:
```
(1/1) type_specific.io-github-autotest-libvirt.guest_os_booting.boot_order.virtiofs_device.start_guest: PASS (109.51 s)
JOB HTML   : /var/log/avocado/job-results/job-2024-12-20T06.32-4e45fbf/results.html
JOB TIME   : 110.96 s
(.libvirt-ci-venv-ci-runtest-qfudOX) [root@ampere-mtsnow-altramax-46 ~]# 
```
rhel10:
```
(1/1) type_specific.io-github-autotest-libvirt.guest_os_booting.boot_order.virtiofs_device.start_guest: PASS (162.49 s)
JOB HTML   : /var/log/avocado/job-results/job-2024-12-20T06.32-906cb89/results.html
JOB TIME   : 164.46 s
(.libvirt-ci-venv-ci-runtest-6DIx80) [root@nvidia-jetson-agx-orin-04 …
```
=> guest_os_booting: Remove unnecessary dhcp-client package

libvirt/tests/cfg/guest_os_booting/boot_order/boot_from_cdrom_device.cfg
There is no particular order in which devices with no bootindex property set will be considered for booting. So it is possible to enter the disk system even without cdrom.
```
(1/1) type_specific.io-github-autotest-libvirt.guest_os_booting.boot_order.cdrom_device.ovmf.os_dev.without_cdrom: PASS (41.63 s)
(1/1) type_specific.io-github-autotest-libvirt.guest_os_booting.boot_order.cdrom_device.ovmf.os_dev.with_cdrom_with_no_src: PASS (41.74 s)
```
=> guest_os_booting: Fix a case error

libvirt/tests/src/guest_os_booting/ovmf_firmware/ovmf_backed_nvram.py, libvirt/tests/src/guest_os_booting/ovmf_firmware/ovmf_seclabel_in_nvram.py
Test results: on x86_64:
```
JOB ID     : 919e67f1feb396b5ef4187047fb98302585391e7
JOB LOG    : …
```
=> guest_os_booting: Fix nvram_attrs xml comparison failure

libvirt/tests/src/guest_os_booting/boot_order/boot_with_multiple_boot_dev.py
Update the timeout to make the case stable.
` (1/1) type_specific.io-github-autotest-libvirt.guest_os_booting.boot_order.boot_with_multiple_boot_dev.network.cdrom.cdrom_bootable: PASS (268.03 s)
`
=> guest_os_booting: Extend timeout of vm start up

libvirt/tests/cfg/sriov/vIOMMU/intel_iommu_without_ioapic.cfg, libvirt/tests/src/sriov/vIOMMU/intel_iommu_without_ioapic.py, spell.ignore
Update to cover intremap on and off.
```
(1/2) type_specific.io-github-autotest-libvirt.vIOMMU.intel_iommu.without_ioapic.default: STARTED
(1/2) type_specific.io-github-autotest-libvirt.vIOMMU.intel_iommu.without_ioapic.default: PASS (124.25 s)
(2/2) type_specific.io-github-autotest-libvirt.vIOMMU.intel_iommu.without_ioapic.intremap_on: STARTED
(2/2) type_specific.io-github-autotest-libvirt.vIOMMU.intel_iommu.without_ioapic.intremap_on: PASS (132.04 s)
```
=> vIOMMU: Add tests of intel iommu without ioapic feature

libvirt/tests/cfg/virtual_network/hotplug/attach_detach_device/rollback_vdpafd_on_hotplug_failure.cfg, libvirt/tests/src/virtual_network/hotplug/attach_detach_device/rollback_vdpafd_on_hotplug_failure.py
This PR adds:
VIRT-302249: Check opened fd on vdpa device is closed when device
attaching failed
Test results:
` (1/1) type_specific.io-github-autotest-libvirt.virtual_network.hotplug.rollback.vdpa_interface: PASS (53.78 s)`
=> virtual_network: Add a vdpa test

libvirt/tests/src/virtual_network/connectivity/connectivity_check_ethernet_interface.py
ip command might print color codes causing comparison to fail. Use new json option to avoid.
=> ethernet_interface: fix color code on RHEL 10.0

libvirt/tests/cfg/virtual_disks/virtual_disks_multidisks.cfg, libvirt/tests/src/virtual_disks/virtual_disks_multidisks.py
1. Add aarch64 cpu required xml to minimal domain xml;
2. Add memory and current memory size parameters for aarch64 suggestion;
3. Add aarch64 machine type parameter;
Test result:
(1/1) type_specific.io-github-autotest-libvirt.virtual_disks.multidisks.coldplug.single_disk_test.disk_attach_with_minimal_xml: STARTED
(1/1) type_specific.io-github-autotest-libvirt.virtual_disks.multidisks.coldplug.single_disk_test.disk_attach_with_minimal_xml: PASS (7.50 s)
=> Add aarch64 adaption for minimal domain disk attach

libvirt/tests/cfg/migration/migration_with_vtpm/migration_with_shared_tpm.cfg
check_str_remote_log should be a string which could be parsed to a list by eval()
After fix test result:
(1/1) type_specific.io-github-autotest-libvirt.migration_with_vtpm.migration_with_shared_tpm.nfs.persistent_and_p2p: STARTED
(1/1) type_specific.io-github-autotest-libvirt.migration_with_vtpm.migration_with_shared_tpm.nfs.persistent_and_p2p: PASS (204.22 s)
=> Change parameter check_str_remote_log to support eval to python list

libvirt/tests/src/daemon/conf_file/libvirtd_conf/virt_admin_logging.py
**Issue:**
TestFail: Check message log:journal failed in log file:/var/log/messages&#10;
**More specifically:**
```
ERROR| VM fails to start with:command: "/usr/bin/virsh -c 'qemu:///system' start avocado-vt-vm1 "exit_status: 1duration: 0.02745846800007712interrupted: Falsepid: 155132encoding: 'UTF-8'stdout: '\n'stderr: "error: Failed to start domain 'avocado-vt-vm1'\nerror: Cannot access storage file '/var/lib/libvirt/images/no_existed_journal.qcow2' (as uid:107, gid:107): No such file or directory\n"
```
**Fix:**
Run create_local_disk() to ensure that no_existed_journal.qcow2 exists. 
Additionally, since in some cases, this test case checks the entirety of /var/log/messages (which contains logs from all test runs) for the key word "journal" to determine whether the test passes/fails, …
=> Virt_admin_logging: create local disk and clear messages log

libvirt/tests/cfg/virtual_network/update_device/unsupported_live_update_delete.cfg
On s390x, there's only one model. Trying to unset the type will be ignored.
=> update_device/iface: disable test on s390x

libvirt/tests/cfg/migration/migration_with_vtpm/migration_with_shared_tpm.cfg, libvirt/tests/src/migration/migration_with_vtpm/migration_with_shared_tpm.py
Use the new directory instead of the swtpm directory as the path to store the image.
=> migration: Update migration with shared tpm case

libvirt/tests/cfg/host_hypervisor/domcapabilities_output.cfg, libvirt/tests/cfg/virtual_network/connectivity/connectivity_check_user_interface.cfg, libvirt/tests/src/host_hypervisor/domcapabilities_output.py, libvirt/tests/src/virtual_network/connectivity/connectivity_check_user_interface.py
Since libvirt 10.8.0, to unify the xml for user type interface, for user type interface with backend as slirp, add the <backend type/> element, and the default backend is slirp.
=> Check the default backend for user type interface

v2v/tests/cfg/convert_vm_to_libvirt.cfg
adjust the guests and delete the drop guests.
=> v2v: adjust testing guests according to matrix of 9.6/10.0

libvirt/tests/cfg/serial/serial_functional.cfg, libvirt/tests/src/serial/serial_functional.py
Automate case: Connect to the guest console without serial device
xx-300602 - [console][negative] Connect to the guest console without serial device
=> Automate case: Connect to the guest console without serial device

libvirt/tests/src/virsh_cmd/snapshot/virsh_snapshot_create_as.py
Description: On v5.8.0 and later versions of libvirt, it is allowed to take the snapshot of guests created with 'autodestroy' option since semantically VIR_DOMAIN_START_AUTODESTROY doesn't really clash with snapshot operations as the VM stays on the same host and thus bound to the same connection.
Referrece commit: https://gitlab.com/libvirt/libvirt/-/commit/045a8e197c1e14faa1c32bd637033838269094a2
=> Qemu: snapshot: Don't forbid snapshot if autodestroy is registered!

v2v/tests/src/specific_kvm.py
To make ntpd service enable after rebooting.
=> v2v: fix the failed tc: specific_kvm..sync_ntp

libvirt/tests/cfg/virtual_network/mtu.cfg, libvirt/tests/src/virtual_network/mtu.py
If vm iface has 'driver queues' in xml, creating tap also need add multi_queue flag.
=> mtu: create tap with multi_queue flag

libvirt/tests/src/numa/guest_numa_topology/numa_topology_with_cpu_topology.py
Change cpu topology checking method, using get_cpu_topology_in_vm() instead. And this commit is depends on avocado-vt pr: https://github.com/avocado-framework/avocado-vt/pull/4038
results:
(1/2) type_specific.io-github-autotest-libvirt.guest_numa_topology.numa_topology_with_cpu_topology.vcpu_with_order: STARTED
(1/2) type_specific.io-github-autotest-libvirt.guest_numa_topology.numa_topology_with_cpu_topology.vcpu_with_order: PASS (66.80 s)
(2/2) type_specific.io-github-autotest-libvirt.guest_numa_topology.numa_topology_with_cpu_topology.vcpu_without_order: STARTED
(2/2) type_specific.io-github-autotest-libvirt.guest_numa_topology.numa_topology_with_cpu_topology.vcpu_without_order: PASS (66.78 s)
=> Change guest cpu topology checking method

libvirt/tests/cfg/security/rng/libvirt_rng.cfg, libvirt/tests/src/security/rng/libvirt_rng.py, spell.ignore
Refactor:
1. variant rng_snapshot always has 'test_snapshot', move to top
2. snapshot_name was used as indicator for snapshot test variants, hence synonymous with 'test_snapshot', remove it from config
3. 'modify_rng_xml' had a very complicated logic, split into two functions to make it simpler to understand; when there are snapshots then the VM can't by 'sync'd, ie. re-defined; in those cases, 'edit' is used instead - both are coldplug
4. check_snapshot didn't use bgjob, remove it from parameters
5. check_snapshot must revert to the first snapshot 's1' where there was no rng device
6. move logic into functions so that the test steps are clearer
- clear rng devices
- take snapshot if testing snapshots
- update xml in case of coldplug
- create fake egd if necessary (connect mode)
- start …
=> libvirt_rng: fix snapshot with egd

libvirt/tests/src/virsh_cmd/domain/virsh_managedsave.py
There could be scenario that existing VMs with the same name which block the following operations. Remove these VMs to clean the env.
=> Clean the env before vm clone

libvirt/tests/src/virt_cmd/virt_xml_validate.py
**Issue**
For virsh.event tests run under the function-misc job, the following error occured in a few of the test runs:
```
avocado.virttest.virsh virsh L1685 ERROR| Undefine VM avocado-vt-vm1 failed:Command '/usr/bin/virsh undefine avocado-vt-vm1 --keep-nvram' failed.
stdout: b'\n'stderr: b"error: Failed to undefine domain 'avocado-vt-vm1'\nerror: Requested operation is not valid: cannot delete inactive domain with 1 snapshots\n"additional_info: None
```
However, when simply running any of the virsh.event tests in isolation, they would consistently pass.
**Relation to virt_xml_validate**
Analysis showed that this error was due to `virt_xml_validate.domainsnapshot`. More specifically, when the function-misc job ran`virt_xml_validate.domainsnapshot` before the virsh.event tests, the …
=> virt_xml_validate: remove vm snapshot after use

libvirt/tests/cfg/virtual_network/iface_update.cfg
Bug RHEL-45200(libvirt-10.8.0) start to reject huge average values larger than '18014398509481984', so change the test value and error msg.
=> iface_update: change huge average value

libvirt/tests/cfg/virtual_device/filesystem_device.cfg, libvirt/tests/src/virtual_device/filesystem_device.py
Issue: VIRTUCT-387
avocado-vt: https://github.com/avocado-framework/avocado-vt/pull/4044
This is a trivial element, I did not add a specific pattern for this element. I just combine the test of the element to thread_pool test, otherwise the case pattern would be even longer
=> Add the cases of virtiofs openfiles

v2v/tests/cfg/specific_kvm.cfg
to libvirt will cause the error:
nbdkit: file.15: error: pwrite: No space left on device.
only to rhev can succeed.
=> v2v:fix the failed case: specific_kvm..no_space.esx..

libvirt/tests/cfg/virsh_cmd/domain/virsh_domtime.cfg, libvirt/tests/src/virsh_cmd/domain/virsh_domtime.py, spell.ignore
hwclock is not available on s390x and guest agent operators that modify the time either.
1. Don't try to restore time (with --now flag) during teardown.
2. Disable test cases that try to modify time.
3. Skip step that uses hwclock.
=> domtime: update for s390x

libvirt/tests/cfg/numa/guest_numa.cfg
Exclude unsupported 16M hugepage on aarch64 and x86_64
=> Exclude unsupported 16M hugepage test for aarch64 and x86_64

libvirt/tests/cfg/virsh_cmd/domain/virsh_hypervisor_cpu_compare.cfg
Before fixed
`Expect should fail but got:&#10;The CPU provided by hypervisor on the host is a superset of CPU described in /var/tmp/avocado_7em7bl6d/cpu.xml&#10;&#10;
`
After fixed
```
avocado run --vt-type libvirt --vt-omit-data-loss --vt-machine-type q35 virsh.hypervisor_cpu_compare.capa_xml --vt-connect-uri qemu:///system
(1/1) type_specific.io-github-autotest-libvirt.virsh.hypervisor_cpu_compare.capa_xml: PASS (6.96 s)
avocado run --vt-type libvirt --vt-omit-data-loss --vt-machine-type q35 virsh.hypervisor_cpu_compare.capa_xml --vt-connect-uri qemu:///system
(1/1) type_specific.io-github-autotest-libvirt.virsh.hypervisor_cpu_compare.capa_xml: PASS (6.96 s)
```
=> fix virsh hypervisor-cpu-compare case due to feature update

libvirt/tests/cfg/cpu/max_vcpus.cfg
Update two cases
-  ioapic_iommu case: maxvxpu num changes from 710 to 2096
-  no_iommu case: automatically configure iommu (if it is missing) in the right way if a user
requests >255 CPUs. Source defect xxxx -65844 - this would be positive scenario , because the ioapic would be added automatically
Before fixed
```
avocado run --vt-type libvirt --vt-omit-data-loss --vt-machine-type q35 max_vcpus.negative_test.ioapic_iommu --vt-connect-uri qemu:///system
(1/1) type_specific.io-github-autotest-libvirt.max_vcpus.negative_test.ioapic_iommu: FAIL: Expect should fail with one of unsupported configuration: Maximum CPUs greater than specified machine type limit|exceeds the maximum cpus supported, but succeeded: Domain 'avocado-vt-vm1' defined from …
```
=> fix maxvcpu increase makes the case checking maxvcpu failed

libvirt/tests/src/migration/migration_with_vtpm/migration_with_external_tpm.py, libvirt/tests/src/migration/migration_with_vtpm/migration_with_shared_tpm.py, libvirt/tests/src/migration/migration_with_vtpm/migration_with_vtpm_dev.py, provider/migration/base_steps.py
For aarch64, only supports migration tests between hosts with the same CPU, so no need to check the CPU.
For x86_64, update to use virsh hypervisor-cpu-compare command to compare CPU.
=> migration: Fix no element found issue

libvirt/tests/cfg/virtio_transitional/virtio_transitional_vsock.cfg
The test assumes that vsock is a PCI device with additional device information to be checked. Only one test variant applies to s390x (virtio).
We already have test vsock.* that covers this setup and more as it also covers functionality (establish communication).
Therefore, skip this test suite for s390x.
=> transitional_vsock: disable on s390x

libvirt/tests/cfg/sriov/vIOMMU/iommu_device_settings.cfg, provider/viommu/viommu_base.py
Update to use the correct controller, disk and interface addresses.
- https://github.com/avocado-framework/avocado-vt/pull/4055
```
(01/11) type_specific.io-github-autotest-libvirt.vIOMMU.iommu_device_settings.virtio_muti_devices.vhost_on.virtio: STARTED
(01/11) type_specific.io-github-autotest-libvirt.vIOMMU.iommu_device_settings.virtio_muti_devices.vhost_on.virtio: PASS (36.27 s)
(02/11) type_specific.io-github-autotest-libvirt.vIOMMU.iommu_device_settings.virtio_muti_devices.vhost_on.smmuv3: STARTED
(02/11) type_specific.io-github-autotest-libvirt.vIOMMU.iommu_device_settings.virtio_muti_devices.vhost_on.smmuv3: PASS (57.59 s)
(03/11) type_specific.io-github-autotest-libvirt.vIOMMU.iommu_device_settings.virtio_muti_devices.vhost_off.virtio: STARTED …
```
=> viommu: Fix up incorrect devices' address issue

libvirt/tests/src/virsh_cmd/domain/virsh_detach_device_alias.py
Currently the cases are skipped in most time because below error:
error: Failed to attach device from pci.xml
error: internal error: Non-endpoint PCI devices cannot be assigned to guests
This is because the incorrect pci device is used to attach to the vm. This fix is an enhancement to increase possiblities of finding the suitable pci device.
=> virsh_detach_device_alias: enhancement for pci

libvirt/tests/cfg/virsh_cmd/snapshot/virsh_snapshot_create_as.cfg
Description:
In my recent PR #6114, I had added required changes for autodestroy.
As per the comments received, modifying the test to be a positive scenario rather than a negative one.
=> Changing a negative scenario to positive

libvirt/tests/src/virtual_network/iface_network.py, provider/virtual_network/network_base.py
We use get_vm_ip to replace utils_net.get_guest_ip_addr in some test code to avoid potential risks, but it changes the original behavior which is to return None when cannot get valid ip address. Add an argument to choose between returning None or raising error to fix this problem.
Test result:
```
(1/1) type_specific.local.virtual_network.iface_network.net_macvtap.net_bridge.multi_guests: STARTED
(1/1) type_specific.local.virtual_network.iface_network.net_macvtap.net_bridge.multi_guests: PASS (98.11 s)
```
=> get_vm_ip:Return None if needed

libvirt/tests/src/virtual_network/passt/passt_transfer_file.py
The listen cmd may not be ready if we send the file immediately, wait 2 seconds after the listen cmd.
=> Wait 2 seconds after the listen cmd

v2v/tests/cfg/specific_kvm.cfg, v2v/tests/cfg/v2v_options.cfg
fix specific-kvm failed case with deprecated i440fx type img
=> v2v: fix the failed case with deprecated i440fx type img

libvirt/tests/src/virsh_cmd/volume/virsh_vol_download_upload.py
The disk was originally selected by its target name but those names are impersistent and might change in the guest.
The test would then sometimes fail as it would read (without I/O errors) from the system disk instead of the new disk when the system was at vdb.
Instead, discover the new disk as the one that doesn't have the root filesystem.
=> vol_download_upload: fix disk selection

libvirt/tests/cfg/guest_os_booting/boot_order/boot_from_virtiofs_device.cfg, libvirt/tests/src/guest_os_booting/boot_order/boot_from_virtiofs_device.py
Update to log serial message during the test.
```
(.libvirt-ci-venv-ci-runtest-5Kbze5) [root@dell-per730-61 1-type_specific.io-github-autotest-libvirt.guest_os_booting.boot_order.virtiofs_device.start_guest]# ls
data  debug.log  ip-sniffer.log  stderr  tmp_dir9jipvgg1  vm_info_avocado-vt-vm1_387044  whiteboard
```
**Before the fix:** vm serial messages are logged in serial-serial0-avocado-vt-vm1-Dnvv.log
```
(1/1) type_specific.io-github-autotest-libvirt.guest_os_booting.boot_order.virtiofs_device.start_guest: PASS (274.59 s)
RESULTS    : PASS 1 | ERROR (.libvirt-ci-venv-ci-runtest-5Kbze5) [root@dell-per730-61 1-type_specific.io-github-autotest-libvirt.guest_os_booting.boot_order.virtiofs_device.start_guest]# ls
data                                    stderr
debug.log …
```
=> guest_os_booting: Enable serial logs

libvirt/tests/cfg/virtio_transitional/virtio_transitional_mem_balloon.cfg, libvirt/tests/src/virtio_transitional/virtio_transitional_mem_balloon.py
On s390x, memballoon is a ccw device per libvirt default, not pci.
Make the command to detect the device configurable and set s390x-specific value.
=> virtio_transitional_mem_balloon: fix test on s390x

libvirt/tests/cfg/virtual_network/qos/check_actual_network_throughput.cfg, libvirt/tests/src/virtual_network/qos/check_actual_network_throughput.py
- VIRT-296327 - [Qos] Check the actual network throughput per bandwidth settings in network/interface
```
(1/2) type_specific.local.virtual_network.qos.check_actual_network_throughput.network.br.ovs_br: STARTED
(1/2) type_specific.local.virtual_network.qos.check_actual_network_throughput.network.br.ovs_br: PASS (123.85 s)
(2/2) type_specific.local.virtual_network.qos.check_actual_network_throughput.br.ovs_br: STARTED
(2/2) type_specific.local.virtual_network.qos.check_actual_network_throughput.br.ovs_br: PASS (102.41 s)
```
=> Update case of virtual network - qos

libvirt/tests/src/virtual_network/iface_update.py
Depends on 
- https://github.com/avocado-framework/avocado-vt/pull/4063
Test result:
```
(1/4) type_specific.io-github-autotest-libvirt.virtual_network.iface_update.positive_test.update_link: STARTED
(1/4) type_specific.io-github-autotest-libvirt.virtual_network.iface_update.positive_test.update_link: PASS (35.43 s)
(2/4) type_specific.io-github-autotest-libvirt.virtual_network.iface_update.positive_test.update_link_with_rom: STARTED
(2/4) type_specific.io-github-autotest-libvirt.virtual_network.iface_update.positive_test.update_link_with_rom: PASS (36.99 s)
(3/4) type_specific.io-github-autotest-libvirt.virtual_network.iface_update.positive_test.update_link_without_addr: STARTED
(3/4) type_specific.io-github-autotest-libvirt.virtual_network.iface_update.positive_test.update_link_without_a …
```
=> iface_update:Fix error when trying to get net interface

libvirt/tests/src/bios/boot_integration.py
aexpect will raise an error if the console contains certain control codes, s. https://github.com/avocado-framework/aexpect/issues/133
This happens in `get_stripped_output`. By using `get_output`, this can't happen and the test passes.
=> boot_integration: fix test for unexpected control codes

libvirt/tests/src/guest_os_booting/direct_kernel_boot/direct_kernel_boot.py
Increase timeout waiting for vm to boot since dracut-initqueue can occasionally take a long time to finish. This change helps make the test more stable.
Consistently passing tests:
```
(.libvirt-ci-venv-ci-runtest-GQXyvP) [root@nvidia-jetson-agx-orin-01 ~]# avocado run --vt-type libvirt --vt-omit-data-loss --vt-machine-type arm64-mmio guest_os_booting.direct_kernel_boot.start_guest --vt-connect-uri qemu:///system
JOB ID     : ab8692d1b86af4b770848ffda3f54bcf722612ab
JOB LOG    : /var/log/avocado/job-results/job-2025-02-13T10.52-ab8692d/job.log
(1/1) type_specific.io-github-autotest-libvirt.guest_os_booting.direct_kernel_boot.start_guest: STARTED
(1/1) type_specific.io-github-autotest-libvirt.guest_os_booting.direct_kernel_boot.start_guest: PASS (342.96 s)
RESULTS    : PASS 1 | ERROR 0 | …
```
=> direct_kernel_boot: increase wait time for booting

libvirt/tests/cfg/memory/memory_devices/dimm_memory_hot_unplug.cfg
test result:
(1/1) type_specific.io-github-autotest-libvirt.memory.devices.dimm.hot_unplug.online_movable_mem.source_and_mib: STARTED
(1/1) type_specific.io-github-autotest-libvirt.memory.devices.dimm.hot_unplug.online_movable_mem.source_and_mib: PASS (258.07 s)
=> Change audit log cmd to get rid of the time impact

libvirt/tests/cfg/virtual_network/qos/test_bandwidth_boundry.cfg, libvirt/tests/src/virtual_network/qos/test_bandwidth_boundry.py
- VIRT-303876 - [Qos][domiftune] Test bandwidth boundary of an interface via domiftune
Test result:
```
(1/8) type_specific.local.virtual_network.qos.test_bandwidth_boundry.boundry.inbound: STARTED
(1/8) type_specific.local.virtual_network.qos.test_bandwidth_boundry.boundry.inbound: PASS (8.28 s)
(2/8) type_specific.local.virtual_network.qos.test_bandwidth_boundry.boundry.outbound: STARTED
(2/8) type_specific.local.virtual_network.qos.test_bandwidth_boundry.boundry.outbound: PASS (10.95 s)
(3/8) type_specific.local.virtual_network.qos.test_bandwidth_boundry.over_boundry_average.inbound: STARTED
(3/8) type_specific.local.virtual_network.qos.test_bandwidth_boundry.over_boundry_average.inbound: PASS (18.91 s)
(4/8) type_specific.local.virtual_network.qos.test_bandwidth_boundry.over_boundry_av …
```
=> Add new case of qos: test bandwidth boundry

libvirt/tests/cfg/numa/numa_numanode_cpu_info.cfg, libvirt/tests/src/numa/numa_numanode_cpu_info.py
Test result:
(1/1) type_specific.io-github-autotest-libvirt.numa_numanode_cpu_info.default: STARTED
(1/1) type_specific.io-github-autotest-libvirt.numa_numanode_cpu_info.default: PASS (8.57 s)
=> Change fixed huge page size to default huge page size of host

libvirt/tests/src/sriov/vIOMMU/migration_iommu_device.py
Use migrate_vm_back option in avocado-vt/share/cfg/base.cfg to determine whether to migrate the vm back to the source host.
=> migration_iommu_device: using migrate_vm_back option

libvirt/tests/src/virtual_network/attach_detach_device/attach_user_type_iface.py, libvirt/tests/src/virtual_network/connectivity/connectivity_check_ethernet_interface.py, libvirt/tests/src/virtual_network/connectivity/connectivity_check_user_interface.py, libvirt/tests/src/virtual_network/passt/passt_attach_detach.py, libvirt/tests/src/virtual_network/passt/passt_connectivity_between_2vms.py, libvirt/tests/src/virtual_network/passt/passt_function.py, libvirt/tests/src/virtual_network/passt/passt_lifecycle.py, libvirt/tests/src/virtual_network/passt/passt_negative_setting.py, libvirt/tests/src/virtual_network/passt/passt_reconnect.py, libvirt/tests/src/virtual_network/passt/passt_transfer_file.py
The old cold uses virsh.VirshPersistent which requires active aexpect session which is unnecessary for these tests and might cause timeout error of unknown reason occasionally. Replace them with virsh.Virsh could avoid the errors.
```
(1/3) type_specific.local.virtual_network.connectivity_check.ethernet_interface.managed_no.positive_test.tap.one_iface.larger_mtu.non_root_user: STARTED
(1/3) type_specific.local.virtual_network.connectivity_check.ethernet_interface.managed_no.positive_test.tap.one_iface.larger_mtu.non_root_user: PASS (68.49 s)
(2/3) type_specific.local.virtual_network.connectivity_check.user_interface.positive_test.default.non_root_user: STARTED
(2/3) type_specific.local.virtual_network.connectivity_check.user_interface.positive_test.default.non_root_user: PASS (52.70 s) …
```
=> Replace virsh.VirshPersistent with virsh.Virsh to avoid error

libvirt/tests/src/memory/memory_devices/virtio_memory_with_numa_node_tuning.py
1. When the host has more than 2 host numa node with memory, the huge page could be allocated on all these nodes, this would impact the verification, so limit only 2 host numa node for huge page allocation.
2. Enable shell when executing cmd with '>'.
3. Add '-r' for remove cmd to delete directory correctly.
test results:
(01/24) type_specific.io-github-autotest-libvirt.memory.devices.virtio.with_numa_tuning.cold_plug.with_source_virtio_mem.strict: STARTED
(01/24) type_specific.io-github-autotest-libvirt.memory.devices.virtio.with_numa_tuning.cold_plug.with_source_virtio_mem.strict: PASS (94.73 s)
(02/24) type_specific.io-github-autotest-libvirt.memory.devices.virtio.with_numa_tuning.cold_plug.with_source_virtio_mem.interleave: STARTED
(02/24) …
=> Fix three issues for more than 2 available host numa node

libvirt/tests/src/migration/migrate_network.py
Before:
(1/1) type_specific.io-github-autotest-libvirt.virsh.migrate_network.direct.fake_macvtap_exists_dest.with_postcopy: ERROR: list index out of range (80.04 s)
After:
(1/1) type_specific.io-github-autotest-libvirt.virsh.migrate_network.direct.fake_macvtap_exists_dest.with_postcopy: PASS (286.50 s)
(1/4) type_specific.io-github-autotest-libvirt.virsh.migrate_network.direct.fake_macvtap_exists_dest.without_postcopy: STARTED
(1/4) type_specific.io-github-autotest-libvirt.virsh.migrate_network.direct.fake_macvtap_exists_dest.without_postcopy: PASS (231.38 s)
(2/4) type_specific.io-github-autotest-libvirt.virsh.migrate_network.direct.macvtap_exists_dest.with_postcopy: STARTED
(2/4) type_specific.io-github-autotest-libvirt.virsh.migrate_network.direct.macvtap_exists_dest.with_postcopy: …
=> migration: Add -color=never option

libvirt/tests/cfg/sriov/vIOMMU/hotplug_device_with_iommu_enabled.cfg, libvirt/tests/cfg/sriov/vIOMMU/iommu_device_settings.cfg, libvirt/tests/src/sriov/vIOMMU/hotplug_device_with_iommu_enabled.py, libvirt/tests/src/sriov/vIOMMU/iommu_device_settings.py, provider/viommu/viommu_base.py
This pr adds tests for pcie-downstream-port in below cases: 
VIRT-294579 - [vIOMMU] Start vm with iommu device
VIRT-296710 - [vIOMMU] hotplug/unplug devices with iommu enabled
**Test results:** 
aarch64:
```
(01/15) type_specific.io-github-autotest-libvirt.vIOMMU.iommu_device_settings.virtio_muti_devices.vhost_on.virtio: STARTED
(01/15) type_specific.io-github-autotest-libvirt.vIOMMU.iommu_device_settings.virtio_muti_devices.vhost_on.virtio: PASS (73.59 s)
(02/15) type_specific.io-github-autotest-libvirt.vIOMMU.iommu_device_settings.virtio_muti_devices.vhost_on.smmuv3: STARTED
(02/15) type_specific.io-github-autotest-libvirt.vIOMMU.iommu_device_settings.virtio_muti_devices.vhost_on.smmuv3: PASS (74.86 s)
(03/15) type_specific.io-github-autotest-libvirt.vIOMMU.iommu_device_settings.virtio_m …
```
=> vIOMMU: Add tests for downstream ports

v2v/tests/cfg/v2v_options.cfg
For esx7.0 issue on vmx+ssh, change the value of parameters to esx8.0.
=> v2v: fix failed case for vmx+ssh connection of esx7.0

libvirt/tests/cfg/sriov/vIOMMU/intel_iommu_virtio_device_with_ats.cfg
To avoid vm login timeout issue, the busNr of the pcie-expander-bus controller should be set to less than 254.
` (1/1) type_specific.io-github-autotest-libvirt.vIOMMU.intel_iommu.virtio_device_with_ats.pcie_root_port_from_expander_bus: PASS (206.10 s)`
=> vIOMMU: Fix up login timeout issue

libvirt/tests/src/guest_agent/unix_source_path/agent_auto_generated_unix_source_path_session_mode.py, libvirt/tests/src/virtual_device/filesystem_device_unprivileged.py, libvirt/tests/src/virtual_network/link_state/link_state_model_type.py
Same as e65a0b9
Test result
```
(1/3) type_specific.local.virtual_network.link_state.model.user.passt.unprivileged_user.virtio.initial_up: STARTED
(1/3) type_specific.local.virtual_network.link_state.model.user.passt.unprivileged_user.virtio.initial_up: PASS (56.48 s)
(2/3) type_specific.local.agent.auto_generated.unix_source_path.session_mode: STARTED
(2/3) type_specific.local.agent.auto_generated.unix_source_path.session_mode: PASS (57.27 s)
(3/3) type_specific.local.virtual_devices.filesystem_device_unprivileged.one_fs.with_hugepages.one_guest.hotplug: STARTED
(3/3) type_specific.local.virtual_devices.filesystem_device_unprivileged.one_fs.with_hugepages.one_guest.hotplug: PASS (64.84 s)
```
=> Replace virsh.VirshPersistent to avoid timeout error

libvirt/tests/cfg/virsh_cmd/domain/virsh_restore.cfg, libvirt/tests/src/virsh_cmd/domain/virsh_restore.py
The `xml_option` variant expects the VM to boot from //os/boot with dev="hd" and will skip otherwise.
Instead, allow for the test to configure the desired xml update for //os.
For s390x, //os/boot is not fully available, so set bootmenu for our xml instead.
=> virsh_restore: enable tests for VMs with boot order

libvirt/tests/src/virsh_cmd/domain/virsh_shutdown.py
Update timeout to make the case stable.
Before:
(1/1) type_specific.io-github-autotest-libvirt.virsh.shutdown.normal_test.remote_option.agent_mode.agent_test: FAIL: Run failed with right command (49.11 s)
After:
(1/1) type_specific.io-github-autotest-libvirt.virsh.shutdown.normal_test.remote_option.agent_mode.agent_test: PASS (48.37 s)
=> virsh_shutdown: Extend timeout of vm shutdown

libvirt/tests/cfg/virtual_network/connectivity/connectivity_check_ethernet_interface.cfg
On s390x ROM tuning is not supported.
=> ethernet_interface: remove unsupported rom for s390x

libvirt/tests/src/cpu/max_vcpus.py
LIBVIRT-1414 says case update
Before fixed:
```
avocado run --vt-type libvirt --vt-omit-data-loss --vt-machine-type q35 max_vcpus.negative_test.with_iommu --vt-connect-uri qemu:///system
(1/1) type_specific.io-github-autotest-libvirt.max_vcpus.negative_test.with_iommu: FAIL: Expect should fail with one of IOMMU interrupt remapping requires split I/O APIC \(ioapic driver='qemu'\), but succeeded: Domain 'avocado-vt-vm1' defined from /var/tmp/xml_utils_temp_91mfmfls.xml\n\n\n (6.13 s)
```
After fixed:
` (1/1) type_specific.io-github-autotest-libvirt.max_vcpus.negative_test.with_iommu: PASS (5.87 s)
`
=> fix iommu was added  automatically when cpus are bigger than 255

libvirt/tests/cfg/sriov/locked_memory_check/sriov_with_hotplug_memory.cfg, libvirt/tests/src/sriov/locked_memory_check/sriov_with_hotplug_memory.py
Automate: 
VIRT-299986 - hotplug memory to vm with hostdev type interface and check the memlock limit
=> SRIOV: add new case to test memory lock limit when hotplug memory with hostdev

libvirt/tests/src/virsh_cmd/domain/virsh_restore.py
cca78d281bbe06462aace28cbe59b120007a5aa3 introduced a new test parameter but didn't provide a default value, leading to problems when reading the value.
Add default value empty dictionary like the local parameter it replaced at some places. This way the added code is just skipped if not necessary.
=> virsh_restore: fix script by adding default value

libvirt/tests/cfg/virtual_network/passt/passt_negative_setting.cfg, libvirt/tests/src/virtual_network/passt/passt_negative_setting.py
With passt rebase, the behavior changes when passt interface with source dev as an inactive host interface. The vm can start successfully now.
=> Update the passt test as behavior changes

libvirt/tests/cfg/virtual_network/update_device/update_driver_non_virtio.cfg, libvirt/tests/src/virtual_network/update_device/update_driver_non_virtio.py
This is to cover the patch
https://patchew.org/Libvirt/20240704154454.3999218-1-mirlos@cisco.com/.
=> Handle the driver element for non-virtio interface

libvirt/tests/cfg/virt_cmd/virt_xml_validate.cfg, libvirt/tests/src/virt_cmd/virt_xml_validate.py
xxxx-17141:validate libvirt XML files against a virsh domcap schema
```
avocado run --vt-type libvirt virt_xml_validate.domcapabilities
(1/1) type_specific.io-github-autotest-libvirt.virt_xml_validate.domcapabilities: PASS (7.28 s)
```
=> add case for virt-xml-validate for virsh domcap

provider/virtual_network/passt.py
Remove irrelevant info such as "search" from output of resolv.conf to avoid inconsistency of nameserver between host and vm.
Test result:
(1/1) type_specific.io-github-autotest-libvirt.virtual_network.passt.interface_function.minimal.root_user: STARTED
(1/1) type_specific.io-github-autotest-libvirt.virtual_network.passt.interface_function.minimal.root_user: PASS (190.17 s)
=> passt:Update code of checking nameserver to fix error

libvirt/tests/src/virsh_cmd/domain/virsh_restore.py
Due latest changes in case configuration, there are now some variants, that doesn't have proper value set. 
and the test is failing. 
I cannot say if the solution is perfect .. but at least it is not failing. 
I'm running all variants on ARM now. (I will not run it on x86_64 or s390)
=> tests failing due missing default value 

libvirt/tests/cfg/migration/migration_misc/migration_with_special_cpu.cfg, libvirt/tests/src/migration/migration_misc/migration_with_special_cpu.py
XXX-301817 - [VM migration] migrate vm between 2 hosts with special CPU
=> migration: Add case to test migrate vm between 2 hosts with special CPU

libvirt/tests/cfg/sriov/vIOMMU/migration_iommu_device.cfg, libvirt/tests/src/sriov/vIOMMU/migration_iommu_device.py, provider/migration/base_steps.py
Check that the ping command can be executed continuously before and after the migration.
**x86_64:**
` (1/1) type_specific.io-github-autotest-libvirt.vIOMMU.migration.iommu_device.virtio_muti_devices.vhost_on.virtio: PASS (192.20 s)
`
**aarch64:**
` (1/1) type_specific.io-github-autotest-libvirt.vIOMMU.migration.iommu_device.virtio_muti_devices.vhost_on.virtio:PASS (260.41 s)
`
=> vIOMMU: Add a ping check before and after migration

libvirt/tests/cfg/numa/guest_numa_topology/migration_with_numa_topology.cfg, libvirt/tests/src/numa/guest_numa_topology/migration_with_numa_topology.py
Case ID: VIRT-301811
depends on pr https://github.com/avocado-framework/avocado-vt/pull/4016
Test results:
Notes: For there is warning or error msg logged in guest dmesg during the migration, to test the whole process, so the test result ignore these dmesg msg.
(1/4) type_specific.io-github-autotest-libvirt.guest_numa_topology.migration_with_numa_topology.with_back_migration.without_postcopy.base_options.one_cluster_on_numa: STARTED
(1/4) type_specific.io-github-autotest-libvirt.guest_numa_topology.migration_with_numa_topology.with_back_migration.without_postcopy.base_options.one_cluster_on_numa: PASS (448.59 s)
(2/4) type_specific.io-github-autotest-libvirt.guest_numa_topology.migration_with_numa_topology.with_back_migration.without_postcopy.base_options.multi_cluster_on_numa: STARTED …
=> Add case for migration with numa topology

libvirt/tests/cfg/memory/memory_devices/nvdimm_memory_turn_to_dram.cfg, libvirt/tests/src/memory/memory_devices/nvdimm_memory_turn_to_dram.py
xxxx-302271:Turned nvdimm to the regular DRAM
```
avocado run --vt-type libvirt --vt-omit-data-loss --vt-machine-type q35 memory.devices.nvdimm.turn_to_dram  --vt-connect-uri qemu:///system
(1/1) type_specific.io-github-autotest-libvirt.memory.devices.nvdimm.turn_to_dram: PASS (42.60 s)
```
Depend on https://github.com/avocado-framework/avocado-vt/pull/4073
=> add case for nvdimm turned to dram

libvirt/tests/cfg/serial/serial_functional.cfg, libvirt/tests/src/serial/serial_functional.py
This PR adds:
VIRT-304021: [aarch64 only][hotplug]hotplug/hotunplug
system-serial serial device
`  (1/1) type_specific.io-github-autotest-libvirt.serial.functional.type_file_system_serial: PASS (88.38 s)
`
=> serial: Add a hotplug/unplug case

libvirt/tests/cfg/virtual_network/lifecycle/restart_service.cfg, libvirt/tests/src/virtual_network/lifecycle/restart_service.py
When the network states become inconsistent since some abnormal situations, ensure the operation to restart virtnetworkd will fix it.
=> Restart virtnetworkd to make the states clear

provider/virtual_network/passt.py
For cases
"virtual_network.passt.attach_detach.ip_portfw.attach_detach" and "virtual_network.passt.interface_function.minimal", if the host ipv6 is not available, skip these test.
=> Skip if host ipv6 is not available

libvirt/tests/cfg/memory/memory_devices/dimm_memory_hot_unplug.cfg, libvirt/tests/cfg/memory/memory_devices/dimm_memory_hotplug.cfg, libvirt/tests/cfg/memory/memory_devices/virtio_mem_hot_unplug.cfg, libvirt/tests/cfg/memory/memory_devices/virtio_mem_hotplug.cfg, libvirt/tests/cfg/memory/memory_misc.cfg
ausearch cmd may not get result during automation, so change cmd to search audit log directly.
Test result:
(1/5) type_specific.io-github-autotest-libvirt.memory.devices.dimm.hotplug.target_and_address: STARTED
(1/5) type_specific.io-github-autotest-libvirt.memory.devices.dimm.hotplug.target_and_address: PASS (36.31 s)
(2/5) type_specific.io-github-autotest-libvirt.memory.devices.dimm.hot_unplug.online_movable_mem.source_and_mib: STARTED
(2/5) type_specific.io-github-autotest-libvirt.memory.devices.dimm.hot_unplug.online_movable_mem.source_and_mib: PASS (160.80 s)
(3/5) type_specific.io-github-autotest-libvirt.memory_misc.audit_size.at_dt_mem: STARTED
(3/5) type_specific.io-github-autotest-libvirt.memory_misc.audit_size.at_dt_mem: PASS (30.78 s)
(4/5) …
=> Change audit log search cmd

libvirt/tests/cfg/scsi/scsi_command_test_hostdev.cfg, libvirt/tests/src/scsi/scsi_command_test_hostdev.py
Automate case:
VIRT-302167 - [Host device assignment][SCSI] SCSI command passthrough test for hostdev scsi device
=> scsi_device: add new case of hostdev device for scsi commands testing

v2v/tests/cfg/function_test_esx.cfg
(1/1) type_specific.io-github-autotest-libvirt.function_test_esx.positive_test.non_int_disk.esx_80.libvirt.it_vddk.vpx_uri: PASS (505.09 s)
=> v2v:add new case on non-int-disk guest

libvirt/tests/cfg/guest_os_booting/boot_order/boot_from_cdrom_device.cfg, libvirt/tests/cfg/guest_os_booting/boot_order/boot_from_disk_device.cfg, libvirt/tests/cfg/guest_os_booting/boot_order/boot_with_multiple_boot_dev.cfg, libvirt/tests/cfg/guest_os_booting/boot_order/boot_with_multiple_boot_order.cfg, libvirt/tests/cfg/guest_os_booting/boot_order/hotplug_device_with_boot_order.cfg, libvirt/tests/cfg/guest_os_booting/direct_kernel_boot/direct_kernel_boot.cfg, libvirt/tests/cfg/guest_os_booting/firmware_configuration/os_acpi.cfg, libvirt/tests/cfg/guest_os_booting/firmware_configuration/smbios_mode.cfg, libvirt/tests/cfg/guest_os_booting/firmware_configuration/sysinfo_fwcfg.cfg, libvirt/tests/cfg/guest_os_booting/migration/migration_boot.cfg, libvirt/tests/src/guest_os_booting/boot_order/boot_from_cdrom_device.py, libvirt/tests/src/guest_os_booting/boot_order/boot_from_disk_device.py, libvirt/tests/src/guest_os_booting/boot_order/boot_with_multiple_boot_order.py, libvirt/tests/src/guest_os_booting/direct_kernel_boot/direct_kernel_boot.py, provider/guest_os_booting/guest_os_booting_base.py, provider/virtual_network/tftpboot.py, virttools/tests/src/virt_install/pxe_installation.py
The following features are not available on s390x:
* SMBIOS
* ACPI
* fw_cfg
* USB
* `<boot dev.../>`
* firmware settings
* SATA
For direct kernel boot, don't use hard coded kernel filename.
In our setup we'll use kernel.img, so just use the filename
from the download url.
Don't use ttyS0, it's the line mode console which is not useful.
Using ttysclp0 is the standard on s390x.
Cover also s390x-specific parameter @loadparm by allowing generically
to run a test command in the booted VM whose output should match an
expected regular expression.
On s390x, the VM will stop if no bootable medium - such as missing cdrom
file - is found.
Some tests were written assuming the VM would use the //os/boot element
instead of the per-device element by trying to remove only that element.
Instead just …
=> guest_os_booting: update tests for s390x

libvirt/tests/cfg/scalability/define_create_vm_with_more_vcpus.cfg, libvirt/tests/src/scalability/define_create_vm_with_more_vcpus.py
This PR adds:
VIRT-303993: Define/Create guest with more than 255 vcpus
```
(01/10) type_specific.io-github-autotest-libvirt.scalability.intel_iommu.define_create_vm_with_more_vcpus.define_vm.with_iommu.default.without_ioapic: STARTED
(01/10) type_specific.io-github-autotest-libvirt.scalability.intel_iommu.define_create_vm_with_more_vcpus.define_vm.with_iommu.default.without_ioapic: PASS (130.53 s)
(02/10) type_specific.io-github-autotest-libvirt.scalability.intel_iommu.define_create_vm_with_more_vcpus.define_vm.with_iommu.with_intremap_on.with_ioapic: STARTED
(02/10) type_specific.io-github-autotest-libvirt.scalability.intel_iommu.define_create_vm_with_more_vcpus.define_vm.with_iommu.with_intremap_on.with_ioapic: PASS (131.70 s)
(03/10) …
```
=> scalability: Add a case about iommu and ioapic setting

libvirt/tests/cfg/virsh_cmd/domain/virsh_save_image_define.cfg, libvirt/tests/cfg/virsh_cmd/domain/virsh_save_image_edit.cfg, libvirt/tests/src/virsh_cmd/domain/virsh_save_image_define.py, libvirt/tests/src/virsh_cmd/domain/virsh_save_image_edit.py
The test cases assume the guest uses `<boot dev='X'/>`. However, those are not supported on s390x.
Instead make the XML snippet that's updated configurable. On s390x, use `<boot order='n'/>` which is supported.
=> virsh_save_image: enable different domain xml

libvirt/tests/src/virtual_network/passt/passt_transfer_file.py
Replace the test command option '-a' with '-e', since '-e' is to check if the file exists.
=> Update the option for test cmd

libvirt/tests/cfg/virtual_network/update_device/update_iface_qos_invalid.cfg
Add more boundry test
Test result:
```
(1/7) type_specific.local.virtual_network.update_device.iface_qos.invalid.neg_value: STARTED
(1/7) type_specific.local.virtual_network.update_device.iface_qos.invalid.neg_value: PASS (29.96 s)
(2/7) type_specific.local.virtual_network.update_device.iface_qos.invalid.big_value.average: STARTED
(2/7) type_specific.local.virtual_network.update_device.iface_qos.invalid.big_value.average: PASS (32.23 s)
(3/7) type_specific.local.virtual_network.update_device.iface_qos.invalid.big_value.peak: STARTED
(3/7) type_specific.local.virtual_network.update_device.iface_qos.invalid.big_value.peak: PASS (39.19 s)
(4/7) type_specific.local.virtual_network.update_device.iface_qos.invalid.big_value.burst: STARTED
(4/7) …
```
=> Update case update_iface_qos_invalid

libvirt/tests/cfg/save_and_restore/managedsave_remove.cfg, libvirt/tests/src/save_and_restore/managedsave_remove.py
Remove saved file by managedsave-remove cmd with various situations. (automate VIRT-297775)
=> Remove saved file by managedsave-remove cmd

libvirt/tests/cfg/backingchain/blockcopy/blockcopy_with_different_qcow2_properties.cfg, libvirt/tests/src/backingchain/blockcopy/blockcopy_with_different_qcow2_properties.py, provider/virtual_disk/disk_base.py
xxxx-294532:Check qcow2 properties after blockcopy
```
avocado run --vt-type libvirt --vt-machine-type q35  backingchain.blockcopy.image_properties..with_datastore
(1/2) type_specific.io-github-autotest-libvirt.backingchain.blockcopy.image_properties.not_encrypt_disk.with_datastore: PASS (27.70 s)
(2/2) type_specific.io-github-autotest-libvirt.backingchain.blockcopy.image_properties.encrypt_disk.with_datastore: PASS (34.90 s)
```
Depend on https://github.com/avocado-framework/avocado-vt/pull/4072
=> add case for blockcopy with datafile property

libvirt/tests/cfg/virtio_transitional/virtio_transitional_blk.cfg
s390x
In s390x avocado-vt-vm1 guest, there is already one virto-scsi controller, but the code to libvirt.set_vm_disk(vm, params) to update it, but it throw error: XML error: Multiple 'scsi' controllers with index '0'
=> Filter virtio_transitional_blk on s390x

libvirt/tests/src/cpu/vcpu_affinity.py, libvirt/tests/src/libvirt_vcpu_plug_unplug.py, provider/cpu.py, spell.ignore
On s390x, override the avocado utility functions because on an LPAR they would return the number of CPUs available on the CEC but not on the LPAR.
Instead, use only the CPUs that are currently online on the LPAR before starting the test which will manipulate their state in some cases.
=> vcpu_affinity: override helper functions on s390x

libvirt/tests/src/virtual_network/link_state/link_state_model_type.py
(1/1) type_specific.local.virtual_network.link_state.model.user.passt.unprivileged_user.virtio.initial_up: STARTED
(1/1) type_specific.local.virtual_network.link_state.model.user.passt.unprivileged_user.virtio.initial_up: PASS (52.53 s)
=> link_state_model_type:Restore vmxml for non root vm

libvirt/tests/cfg/save_and_restore/abort_managedsave.cfg, libvirt/tests/src/save_and_restore/abort_managedsave.py
Check after aborting the managesave process, the vm should keep running and there is related events.
=> Abort the managedsave process and check the events

libvirt/tests/cfg/save_and_restore/abort_save.cfg, libvirt/tests/src/save_and_restore/abort_save.py
When the save process is aborted, the vm should keep running. (For VIRT-297049)
=> Test the scenario when abort the save process

provider/virtual_disk/disk_base.py
replace "=" with "append"
Before fix
```
~# avocado run --vt-type libvirt --vt-omit-data-loss --vt-machine-type arm64-mmio backingchain.blockpull.relative_path.file_disk.keep_relative --vt-connect-uri qemu:///system
(1/1) backingchain.blockpull.relative_path.file_disk.keep_relative: ERROR: list index out of range (22.62 s)
```
After fix
```
~# avocado run --vt-type libvirt --vt-omit-data-loss --vt-machine-type arm64-mmio backingchain.blockpull.relative_path.file_disk.keep_relative --vt-connect-uri qemu:///system
(1/1) backingchain.blockpull.relative_path.file_disk.keep_relative: PASS (23.55 s)
```
Some influenced cases
```
]# avocado run --vt-type libvirt --vt-omit-data-loss --vt-machine-type arm64-mmio  backingchain.blockcommit.relative_path …
```
=> fix get_source_list function missing some disk source paths

libvirt/tests/cfg/virsh_cmd/domain/virsh_managedsave_special_name.cfg, libvirt/tests/src/virsh_cmd/domain/virsh_managedsave_special_name.py
Check managedsave can work properly for VM with long name with 242 characters or non-ACSII name. (automate VIRT-297732)
=> Managedsave for VM with specific name

libvirt/tests/cfg/migration/pause_postcopy_migration_and_recover/pause_by_domjobabort_and_recover.cfg
Test would consistently timeout during migration. Since a migrate_speed of 5 is quite slow, increased to 15.
**Evidence of test passing:**
```
JOB ID     : 91f8831afbbb7fd1a12628fb80a777b59ef8740f
JOB LOG    : /var/log/avocado/job-results/job-2025-03-28T16.13-91f8831/job.log
(1/1) type_specific.io-github-autotest-libvirt.migration.pause_postcopy_migration_and_recover.pause_by_domjobabort_and_recover.migrateuri.tcp.p2p: STARTED
(1/1) type_specific.io-github-autotest-libvirt.migration.pause_postcopy_migration_and_recover.pause_by_domjobabort_and_recover.migrateuri.tcp.p2p: PASS (333.04 s)
JOB HTML   : /var/log/avocado/job-results/job-2025-03-28T16.13-91f8831/results.html
JOB TIME   : 334.60 s
```
=> pause_by_domjobabort_and_recover: increase migrate_speed to ensure test does not timeout

libvirt/tests/cfg/migration/migration_with_vtpm/migration_with_vtpm_state_on_block_dev.cfg, libvirt/tests/src/migration/migration_with_vtpm/migration_with_vtpm_state_on_block_dev.py, provider/migration/migration_vtpm.py
XXX-303897 - Migrate vm with vtpm state on block device
Test result:
(1/1) type_specific.io-github-autotest-libvirt.migration_with_vtpm.migration_with_vtpm_state_on_block_dev.auto_create_dir: STARTED
(1/1) type_specific.io-github-autotest-libvirt.migration_with_vtpm.migration_with_vtpm_state_on_block_dev.auto_create_dir: PASS (292.90 s)
(1/1) type_specific.io-github-autotest-libvirt.migration_with_vtpm.migration_with_vtpm_state_on_block_dev.manual_create_dir: STARTED
(1/1) type_specific.io-github-autotest-libvirt.migration_with_vtpm.migration_with_vtpm_state_on_block_dev.manual_create_dir: PASS (286.99 s)
(1/1) type_specific.io-github-autotest-libvirt.migration_with_vtpm.migration_with_vtpm_state_on_block_dev.auto_create_file: STARTED
(1/1) …
=> migration: Add case about vtpm state on block device

libvirt/tests/cfg/virtual_device/video_devices.cfg, libvirt/tests/src/virtual_device/video_devices.py
Case ID: VIRT-304063
Support resolution setting for video device.
```
<video>
<model type='virtio' heads='1' primary='yes'>
<resolution x='507' y='510'/>
</model>
</video>
```
=> video_devices: add case for resolution

libvirt/tests/cfg/virsh_cmd/domain/virsh_sosreport.cfg, libvirt/tests/src/virsh_cmd/domain/virsh_sosreport.py
Description:
Adding 2 new test cases for testing the below scenarios.
1. Running sosreport causes the system to crash and produce a dump on Ubuntu 24.04 Referrence Bug: https://bugs.launchpad.net/ubuntu/+source/sosreport/+bug/2068577
2. Kernel OOPS crash while trying to get data from sysfs file: /proc/fs/nfsd/pool_stats
Referrence Bug: https://bugs.launchpad.net/ubuntu/+source/sosreport/+bug/2070358
Both above scenarios have got patches merged in the main line kernel. Tests added will catch these scenarios if occurs again anytime in future.
=> sosreport: 2 new tests added

libvirt/tests/cfg/virsh_cmd/virsh_qemu_cmdline_core.cfg, libvirt/tests/src/virsh_cmd/virsh_qemu_cmdline_core.py
There was a bug reported where qemu command line was giving core dump error as below.
_# qemu-system-ppc64 -accel tcg -smp 10,maxcpus=9000
**
ERROR:../tcg/region.c:782:tcg_region_init: assertion failed: (region_size >= 2 * page_size)
Bail out! ERROR:../tcg/region.c:782:tcg_region_init: assertion failed: (region_size >= 2 * page_size)
Aborted (core dumped)_
A fix has been posted upstream and is merged with distros(Fedora and Ubuntu). Adding this test case to catch such a scenario in future.
Reference bug: https://bugs.launchpad.net/ubuntu/+source/qemu/+bug/2055003
Signed-off-by: Kowshik Jois B S<kowsjois@linux.ibm.com>
=> New test case: qemu_cmdline

libvirt/tests/cfg/libvirt_mem.cfg
1. On ppc64le arch, xml does not support numa with memory device same as x86_64 or aarch64. Hence, removing the testcase for ppc64le
2. Similarly, negative test scenario is added for checking the same on ppc64le
=> libvirt-mem: Update testcases for ppc64le arch

libvirt/tests/cfg/passthrough/pci/libvirt_pci_passthrough.cfg, libvirt/tests/src/passthrough/pci/libvirt_pci_passthrough.py
Tests perform PCI_PT of NIC devices and checks ping And Tests pci device persistent across Multiple Reboot of VM
1. Changes made to support ppc64 arch and perform pci PT of network devices
2. Perform ping to other server ip and check the device network connectivity
3. Added test to check the device availability after multiple reboots of guest is done
=> Tests perform PCI_PT of NIC devices and checks ping And Tests pci device persistent across Multiple Reboot of VM

libvirt/tests/src/cpu/aarch64_cpu_sve.py
The make check tests need more time, so this case needs bigger timeout
=> aarch64_cpu_sve: extend timeout

libvirt/tests/cfg/in_place_upgrade_guest.cfg, libvirt/tests/src/in_place_upgrade_guest.py
Case ID: VIRT-293757
Depends on: https://github.com/avocado-framework/avocado-vt/pull/4070
Automates the case that verifies that an in place upgrade can be successfully completed on a guest. This case has already been automated by /tp-qemu/qemu/tests/in_place_upgrade.py - this specific test in tp-libvirt exists such that an in place guest upgrade test can be accomplished without depending on 'kar'.
This test specifically supports upgrading from rhel X-1 -> rhel X on a rhel X host.
Tests passing:
```
(.libvirt-ci-venv-ci-runtest-ZbmaDy) [root@ampere-mtsnow-altra-09 ~]# avocado run --vt-type libvirt --vt-omit-data-loss --vt-machine-type arm64-mmio in_place_upgrade_guest --vt-connect-uri qemu:///system
JOB ID     : 3947dcc69ad9e030e06a3828ae35e8470aa508dc
JOB LOG    : …
```
=> in_place_upgrade_guest: automates the case that verifies in place upgrade on a guest

libvirt/tests/cfg/migration/migrate_mem.cfg
Test result:
(1/1) type_specific.io-github-autotest-libvirt.virsh.migrate_mem.mem_balloon: STARTED
(1/1) type_specific.io-github-autotest-libvirt.virsh.migrate_mem.mem_balloon: PASS (145.92 s)
=> Increase memory balloon size to avoid guest crash for short of memory

libvirt/tests/cfg/snapshot/revert_disk_external_snap.cfg, libvirt/tests/src/snapshot/revert_disk_external_snap.py
Automate case:
VIRT-303301 - [Disk snapshot][External] Create/revert/delete external snapshots for guest whose disk has data file
=> Snapshot: add datastore test scenarios to snapshot

libvirt/tests/cfg/sriov/locked_memory_check/sriov_with_hotplug_memory.cfg, libvirt/tests/src/sriov/locked_memory_check/sriov_with_hotplug_memory.py
Fix the unplug failure of dimm memory device by adding memhp_default_state=online_movable to guest kernel which is a common workaround.
=> Sriov: fix "unplug of device was rejected by the guest" failure

libvirt/tests/cfg/cpu/vcpu_feature.cfg, libvirt/tests/src/cpu/vcpu_feature.py
Case ID:  VIRT-304022
new TC implementation: 
1. Configure vm xml cpu section to disable the pauth feature.
2. Start the vm
3. Check the vm can be logged on
4.  Check the parameter 'pauth=off' could be passed to qemu command line
Reusing existing vcpu_feature.py with new configuration and new check option.
! be aware, that for RHEL-8 and RHEL-9 is the PAUTH feature by default disabled.
=> Add case to disable pauth cpu feature

libvirt/tests/src/cpu/max_vcpus.py
cpu max value increase in rhel10
Before fix:
` (1/1) type_specific.io-github-autotest-libvirt.max_vcpus.virsh_capabilities: FAIL: Test failed as the q35_max_vcpus_num for machine type:pc-q35-rhel10.0.0 in virsh_capa is wrong. Expected: 710, Actual: 4096. (7.74 s)
`
After fix
```
avocado run --vt-type libvirt --vt-omit-data-loss --vt-machine-type q35 max_vcpus.virsh_capabilities --vt-connect-uri qemu:///system
(1/1) type_specific.io-github-autotest-libvirt.max_vcpus.virsh_capabilities: PASS (6.44 s)
```
=> fix cpu max value increases

libvirt/tests/cfg/migration/migration_misc/canonical_paths_in_shared_filesystems.cfg, libvirt/tests/src/migration/migration_misc/canonical_paths_in_shared_filesystems.py
XXX-304029 - Migrate the guests with various tpm and firmware on canonical paths in shared_filesystems
Test result:
(1/3) type_specific.io-github-autotest-libvirt.migration.migration_misc.canonical_paths_in_shared_filesystems.bios.without_tpm: STARTED
(1/3) type_specific.io-github-autotest-libvirt.migration.migration_misc.canonical_paths_in_shared_filesystems.bios.without_tpm: PASS (199.98 s)
(2/3) type_specific.io-github-autotest-libvirt.migration.migration_misc.canonical_paths_in_shared_filesystems.statless_uefi.without_tpm: STARTED
(2/3) type_specific.io-github-autotest-libvirt.migration.migration_misc.canonical_paths_in_shared_filesystems.statless_uefi.without_tpm: PASS (193.06 s)
(3/3) type_specific.io-github-autotest-libvirt.migration.migration_misc.canonical_paths_in_shared_filesyst …
=> migration: Add case about shared_filesystems

libvirt/tests/cfg/virsh_cmd/host/virsh_cpu_models.cfg, libvirt/tests/src/virsh_cmd/host/virsh_cpu_models.py
xxxx-303288 Compare x86 cpu models with qemu-kvm
```
avocado run --vt-type libvirt --vt-machine-type q35 virsh.cpu_models.positive_test.local_host.specific_arch
(1/3) type_specific.io-github-autotest-libvirt.virsh.cpu_models.positive_test.local_host.specific_arch.arch_x86: STARTED
(1/3) type_specific.io-github-autotest-libvirt.virsh.cpu_models.positive_test.local_host.specific_arch.arch_x86: PASS (6.30 s)
(2/3) type_specific.io-github-autotest-libvirt.virsh.cpu_models.positive_test.local_host.specific_arch.arch_s390: STARTED
(2/3) type_specific.io-github-autotest-libvirt.virsh.cpu_models.positive_test.local_host.specific_arch.arch_s390: PASS (5.73 s)
(3/3) type_specific.io-github-autotest-libvirt.virsh.cpu_models.positive_test.local_host.specific_arc …
```
=> cpu: add case for virsh cpu models compare with qemu

libvirt/tests/cfg/daemon/conf_file/sysconfig_libvirt_guests/libvirt_guests.cfg
There are 4 skipped cases in the job related to managed-save feature and bug 56145
According developer resolution such cases doesn't make sense for transient VMs, so I've removed it from configuration. 
skipped cases:
libvirt_guests.positive_test.no_parallel_shutdown.shutdown_on_shutdown.none_on_boot.with_transient_vm.persistent_only_default
libvirt_guests.positive_test.no_parallel_shutdown.shutdown_on_shutdown.none_on_boot.with_transient_vm.persistent_only_false
libvirt_guests.positive_test.no_parallel_shutdown.shutdown_on_shutdown.none_on_boot.with_transient_vm.persistent_only_none
libvirt_guests.positive_test.no_parallel_shutdown.suspend_on_shutdown.default_vol.none_on_boot.with_transient_vm.persistent_only_false
=> resolving skipped cases: 56145

libvirt/tests/cfg/migration/migration_with_numa_topology.cfg
depends on: https://github.com/avocado-framework/avocado-vt/pull/4111
test results:
(1/6) type_specific.io-github-autotest-libvirt.migrate.migration_with_numa_topology.no_back_migration.without_postcopy.base_options.one_cluster_on_numa: STARTED
(1/6) type_specific.io-github-autotest-libvirt.migrate.migration_with_numa_topology.no_back_migration.without_postcopy.base_options.one_cluster_on_numa: PASS (414.32 s)
(2/6) type_specific.io-github-autotest-libvirt.migrate.migration_with_numa_topology.no_back_migration.without_postcopy.base_options.multi_cluster_on_numa: STARTED
(2/6) type_specific.io-github-autotest-libvirt.migrate.migration_with_numa_topology.no_back_migration.without_postcopy.base_options.multi_cluster_on_numa: PASS (414.07 s)
(3/6) …
=> Add required parameters for shared disk and tls setup

libvirt/tests/cfg/virsh_cmd/host/virsh_cpu_models.cfg
969ec9b13d2be9d88381d686601288c695a1cb94 restructured the tests introducing a named variant for each of the main architectures.
However, this requires additional filtering in CI.
Instead, use existing avocado-vt configuration parameters to keep having a single variant that applies to all considered archs.
=> virsh_cpu_models: add filters

libvirt/tests/cfg/migration/migrate_vm_in_various_status/migrate_paused_vm.cfg, libvirt/tests/src/migration/migrate_vm_in_various_status/migrate_paused_vm.py
Test result:
(1/2) type_specific.io-github-autotest-libvirt.migration.migrate_vm_in_various_status.migrate_paused_vm.migration_succeeds.precopy.p2p: STARTED
(1/2) type_specific.io-github-autotest-libvirt.migration.migrate_vm_in_various_status.migrate_paused_vm.migration_succeeds.precopy.p2p: PASS (206.03 s)
(2/2) type_specific.io-github-autotest-libvirt.migration.migrate_vm_in_various_status.migrate_paused_vm.migration_succeeds.precopy.non_p2p: STARTED
(2/2) type_specific.io-github-autotest-libvirt.migration.migrate_vm_in_various_status.migrate_paused_vm.migration_succeeds.precopy.non_p2p: PASS (205.74 s)
(1/2) type_specific.io-github-autotest-libvirt.migration.migrate_vm_in_various_status.migrate_paused_vm.cancel_migration.precopy.p2p: STARTED
(1/2) …
=> migration: Add migrate_vm_back for case

libvirt/tests/cfg/migration/migration_misc/non_canonical_paths_in_shared_filesystems.cfg, libvirt/tests/src/migration/migration_misc/non_canonical_paths_in_shared_filesystems.py
XXX-304031 - Migrate a guest on non-canonical paths in shared_filesystems
Test result: Case failed due to one bug.
(1/1) type_specific.io-github-autotest-libvirt.migration.migration_misc.non_canonical_paths_in_shared_filesystems: STARTED
(1/1) type_specific.io-github-autotest-libvirt.migration.migration_misc.non_canonical_paths_in_shared_filesystems: FAIL: error: this function is not supported by the connection driver: the running swtpm does not support migration with shared storage (115.74 s)
=> migration: Add case about non-canonical paths in shared_filesystems

libvirt/tests/src/virsh_cmd/monitor/virsh_domstats.py
fix domstats failures by adding "echo 1 > /proc/sys/kernel/sched_schedstats" before domststs command
=> domstats: fix failure by adding sched_schedstats

libvirt/tests/cfg/numa/guest_numa_hmat/hmat_info.cfg, libvirt/tests/src/numa/guest_numa_hmat/hmat_info.py
=> hmat_info: add case to set HMAT in vm

libvirt/tests/src/numa/guest_numa_node_tuning/memory_binding_setting.py
Libvirt daemon needs to be restarted after hugepage filesystem is mounted.
=> memory_binding_setting: fix daemon restart

libvirt/tests/src/passthrough/ccw/libvirt_ccw_passthrough.py
There have been changes in the kernel so that now, sometimes a device would show up, other times it wouldn't.
The test case was motivated by a critical issue where removing all channel paths led to an unusable system. Let's reduce our test condition to that.
=> libvirt_ccw_passthrough: relax test condition

libvirt/tests/cfg/virtual_network/network_misc.cfg, libvirt/tests/src/virtual_network/network_misc.py
- VIRT-298946 - [Zone] Define network with libvirt managed bridge zone
Test result:
```
(1/6) type_specific.local.virtual_network.network_misc.zone.libvirt_managed.nat: STARTED
(1/6) type_specific.local.virtual_network.network_misc.zone.libvirt_managed.nat: PASS (10.73 s)
(2/6) type_specific.local.virtual_network.network_misc.zone.libvirt_managed.route: STARTED
(2/6) type_specific.local.virtual_network.network_misc.zone.libvirt_managed.route: PASS (10.63 s)
(3/6) type_specific.local.virtual_network.network_misc.zone.libvirt_managed.isolated: STARTED
(3/6) type_specific.local.virtual_network.network_misc.zone.libvirt_managed.isolated: PASS (10.81 s)
(4/6) type_specific.local.virtual_network.network_misc.zone.libvirt_managed.open: STARTED
(4/6) …
```
=> Add new case of zone of network

libvirt/tests/cfg/virtual_network/iface_unprivileged.cfg, libvirt/tests/src/virtual_network/iface_unprivileged.py
Test result
```
(1/2) type_specific.local.virtual_network.iface_unprivileged.precreated.host_tap: STARTED
(1/2) type_specific.local.virtual_network.iface_unprivileged.precreated.host_tap: PASS (107.46 s)
(2/2) type_specific.local.virtual_network.iface_unprivileged.precreated.host_macvtap: STARTED
(2/2) type_specific.local.virtual_network.iface_unprivileged.precreated.host_macvtap: PASS (39.58 s)
```
=> iface_unprivileged:update case to use existing vm

libvirt/tests/src/numa/numa_config_with_auto_placement.py
The domain xml has no iothreadids config, so use iothreads instead
test results:
(1/1) type_specific.io-github-autotest-libvirt.numa_config_with_auto_placement.default: STARTED
(1/1) type_specific.io-github-autotest-libvirt.numa_config_with_auto_placement.default: PASS (68.33 s)
=> Fix error for nonexistent iothreadids

libvirt/tests/src/virsh_cmd/network/virsh_net_dhcp_leases.py
It was introduced by 0ad965d679a3801de0e.
`Failed to install dhcpcd in guest OS.
`
After the fix:
rhel 9.x
` (1/1) type_specific.io-github-autotest-libvirt.virsh.net_dhcp_leases.positive_test.attach_interface_after_vm_start: PASS (47.17 s)
`
rhel 10.x
` (1/1) type_specific.io-github-autotest-libvirt.virsh.net_dhcp_leases.positive_test.attach_interface_after_vm_start: PASS (65.08 s)
`
=> Virtual_network: Fixup dhcpcd installation issue

libvirt/tests/cfg/virtual_disks/virtual_disks_blockresize.cfg, libvirt/tests/src/virtual_disks/virtual_disks_blockresize.py
xxx-62472 - Resize a block size to a value that's not a multiple of 1024,it need align with multiple of 1024
=> Automate Resize a block size to a value that's not a multiple of 1024

libvirt/tests/src/sriov/locked_memory_check/sriov_with_hotplug_memory.py
```
(3/4) type_specific.io-github-autotest-libvirt.sriov.locked_memory_check.hotplug_memory.without_hardlimit.start_vm_without_hostdev.hostdev_device.pf_address: ERROR: Not found event device-removed after 7 seconds (199.32 s)
(4/4) type_specific.io-github-autotest-libvirt.sriov.locked_memory_check.hotplug_memory.with_hardlimit.start_vm_without_hostdev.hostdev_device.pf_address: STARTED
(4/4) type_specific.io-github-autotest-libvirt.sriov.locked_memory_check.hotplug_memory.with_hardlimit.start_vm_without_hostdev.hostdev_device.pf_address: ERROR: Not found event device-removed after 7 seconds (200.04 s)
```
```
(1/2) type_specific.io-github-autotest-libvirt.sriov.locked_memory_check.hotplug_memory.without_hardlimit.start_vm_without_hostdev.hostdev_device.p …
```
=> sriov: Extend event wait time

provider/bootc_image_builder/bootc_image_build_utils.py, virttools/tests/cfg/bootc_image_builder/bootc_disk_image_build.cfg, virttools/tests/cfg/bootc_image_builder/bootc_disk_image_install.cfg, virttools/tests/src/bootc_image_builder/bootc_disk_image_build.py, virttools/tests/src/bootc_image_builder/bootc_disk_image_install.py
Add new features support and enable more utils
1. Remove virt-manager package install since it is never necessary
2. Enable local storage as default since it is default behaviour after
bootc image builder feature updates
3. Enable -use-librepo when building out anaconda-iso since this is
default feature for anaconda-iso
4. Add util: podman_pull to support podman download image before run
bootc image builder
5. Add files and directories customization when creating json files
since it is new feature for bootc image builder
6. Enable vhd on rhel_9.6 and rhel_10.0 since this feature are
newly supported on those two releases
7. Add check_squashfs when anaconda-iso since it is new feature
requirement when building out anaconda-iso
=> Add new features support and enable more utils

libvirt/tests/cfg/gpu/hotplug_gpu.cfg, libvirt/tests/cfg/gpu/lifecycle_vm_with_gpu.cfg, libvirt/tests/cfg/gpu/start_vm_with_gpu.cfg, libvirt/tests/cfg/gpu/start_vm_with_gpu_managed_disabled.cfg, libvirt/tests/cfg/gpu/vm_cuda_sanity.cfg, libvirt/tests/cfg/gpu/vm_mig_sanity.cfg, libvirt/tests/cfg/gpu/vm_nvidia_gpu_driver.cfg, libvirt/tests/src/gpu/hotplug_gpu.py, libvirt/tests/src/gpu/lifecycle_vm_with_gpu.py, libvirt/tests/src/gpu/start_vm_with_gpu.py, libvirt/tests/src/gpu/start_vm_with_gpu_managed_disabled.py, libvirt/tests/src/gpu/vm_cuda_sanity.py, libvirt/tests/src/gpu/vm_mig_sanity.py, libvirt/tests/src/gpu/vm_nvidia_gpu_driver.py, provider/gpu/gpu_base.py
```
1..10
ok 1 type_specific.io-github-autotest-libvirt.gpu.lifecycle_vm_with_gpu.gpu_address
not ok 2 type_specific.io-github-autotest-libvirt.gpu.hotplug_gpu.gpu_address  <------------- reported a bug
ok 3 type_specific.io-github-autotest-libvirt.gpu.managed_disabled_gpu.define_start.gpu_address.managed_no
ok 4 type_specific.io-github-autotest-libvirt.gpu.managed_disabled_gpu.define_start.gpu_address.managed_ignore
ok 5 type_specific.io-github-autotest-libvirt.gpu.managed_disabled_gpu.hotplug.gpu_address.managed_no
ok 6 type_specific.io-github-autotest-libvirt.gpu.managed_disabled_gpu.hotplug.gpu_address.managed_ignore
ok 7 type_specific.io-github-autotest-libvirt.gpu.start_vm_with_gpu.gpu_address.managed_yes
ok 8 type_specific.io-github-autotest-libvirt.gpu.start_vm_with_gpu.gpu_address …
```
=> GPU: Add cases for aarch64

libvirt/tests/cfg/virtual_disks/virtual_disks_cdrom_device.cfg, libvirt/tests/src/virtual_disks/virtual_disks_cdrom_device.py
startuppolicy is set to optional
xx-38693 - [disk-change]Check the disk-change events when startuppolicy is optional
xx-112414 - start a guest with block type cdrom --bz1471225
xx-32763 - [audit log] Audit log related to guest CDROM
=> Automate Check the disk-change events for cdrom and disk when

libvirt/tests/src/virtiofs/virtiofs_unprivileged.py
bootc doesn't allow creating the hugepages user directory in the original path.
Add it to /var instead.
=> virtiofs.unpriviledged: fix hugepages tests for bootc

libvirt/tests/src/memory/virsh_setmem.py
As dmidecode is not available in ppc64 , removing it and replacing it with lshw as lshw is a standard way to get the resources details on ppc64 arch
Executed one of the test case that used the replaced package
JOB ID     : 347090eae84a282511330b796d50e9ea2737edfe
JOB LOG    : /root/tests/results/job-2024-09-18T05.37-347090e/job.log
(1/2) type_specific.io-github-autotest-libvirt.virsh.setmem.valid_options.inactive.half_mem.domname.dom_opt_size_opt.cmd_flag_config: STARTED
(1/2) type_specific.io-github-autotest-libvirt.virsh.setmem.valid_options.inactive.half_mem.domname.dom_opt_size_opt.cmd_flag_config: PASS (60.04 s)
(2/2) io-github-autotest-libvirt.remove_guest.without_disk: STARTED
(2/2) io-github-autotest-libvirt.remove_guest.without_disk: PASS (4.21 s)
RESULTS    : PASS 2 | ERROR 0 | …
=> Replacing Dmidecode with lshw package

libvirt/tests/src/virtiofs/virtiofs.py
QEMU cmdline check was always executed, also in negative scenario. Return test immediately when done.
=> virtiofs: fix negative scenarios

libvirt/tests/cfg/gpu/hotplug_gpu.cfg, libvirt/tests/cfg/gpu/vm_cuda_sanity.cfg, libvirt/tests/cfg/gpu/vm_mig_sanity.cfg, libvirt/tests/src/gpu/vm_cuda_sanity.py, libvirt/tests/src/gpu/vm_mig_sanity.py
1. Fix hotplug case's pattern and type
2. Update to download cuda sample file from storage server
` (1/1) type_specific.io-github-autotest-libvirt.gpu.vm_cuda_sanity.gpu_address: PASS (819.33 s)
`
=> gpu: Fix errors

libvirt/tests/cfg/virtual_network/passt/passt_reconnect.cfg, libvirt/tests/src/virtual_network/passt/passt_attach_detach.py, libvirt/tests/src/virtual_network/passt/passt_function.py, libvirt/tests/src/virtual_network/passt/passt_reconnect.py
Delete 2 checkpoints:
1) Check the socket dir, when vm destroyed, the passt socket dir is not cleared for passt+vhostuser. In CNV, this is not an issue, tracked in RHEL-80285. (We can restore the check after the bug is fixed)
2) When start vm with interface using passt, and the qemu support reconect parameter, there is "reconnect:5" or "reconnect=5" in qemu cmd once qemu support reconnect feature. But since qemu 10.1, the parameter change to "reconnect-ms:5000" or "reconnect-ms=5000". To make is simple, delete this qemu cmd check, and just check the function that if the passt process will reconnect after killed is enough.
=> Remove 2 checkpoints for passt

libvirt/tests/cfg/virsh_cmd/domain/virsh_guestinfo.cfg, libvirt/tests/src/virsh_cmd/domain/virsh_guestinfo.py
This is an update to RHEL-201783
"guest_bus" is added to the output of "virsh guestinfo --disk". Supported since libvirt-11.2.0
=> guestinfo: Check guest_bus in the output

libvirt/tests/cfg/memory/memory_devices/change_virtio_mem_request_size.cfg, libvirt/tests/cfg/memory/memory_devices/invalid_virtio_mem_config.cfg, libvirt/tests/cfg/memory/memory_devices/virtio_mem_access_and_discard.cfg, libvirt/tests/cfg/memory/memory_devices/virtio_mem_coldplug_and_unplug.cfg, libvirt/tests/cfg/memory/memory_devices/virtio_mem_device_lifecycle.cfg, libvirt/tests/cfg/memory/memory_devices/virtio_mem_dynamic_slots.cfg, libvirt/tests/cfg/memory/memory_devices/virtio_mem_hot_unplug.cfg, libvirt/tests/cfg/memory/memory_devices/virtio_mem_hotplug.cfg, libvirt/tests/cfg/memory/memory_devices/virtio_mem_with_memory_allocation_and_numa.cfg, libvirt/tests/cfg/memory/memory_devices/virtio_mem_with_memory_backing_type.cfg, libvirt/tests/src/memory/memory_devices/change_virtio_mem_request_size.py, libvirt/tests/src/memory/memory_devices/invalid_virtio_mem_config.py, libvirt/tests/src/memory/memory_devices/virtio_mem_access_and_discard.py, libvirt/tests/src/memory/memory_devices/virtio_mem_hot_unplug.py, libvirt/tests/src/memory/memory_devices/virtio_mem_hotplug.py, libvirt/tests/src/memory/memory_devices/virtio_mem_with_memory_allocation_and_numa.py, libvirt/tests/src/memory/memory_devices/virtio_mem_with_memory_backing_type.py
Test results:
(1/9) type_specific.io-github-autotest-libvirt.memory.devices.virtio_mem.access_and_discard.undefined.file.without_numa: STARTED
(1/9) type_specific.io-github-autotest-libvirt.memory.devices.virtio_mem.access_and_discard.undefined.file.without_numa: PASS (27.41 s)
(2/9) type_specific.io-github-autotest-libvirt.memory.devices.virtio_mem.access_and_discard.undefined.anonymous.without_numa: STARTED
(2/9) type_specific.io-github-autotest-libvirt.memory.devices.virtio_mem.access_and_discard.undefined.anonymous.without_numa: PASS (26.99 s)
(3/9) type_specific.io-github-autotest-libvirt.memory.devices.virtio_mem.access_and_discard.undefined.memfd.without_numa: STARTED
(3/9) type_specific.io-github-autotest-libvirt.memory.devices.virtio_mem.access_and_discard.undefined.memfd.without_ …
=> Enable virtio-mem on s390x

v2v/tests/src/nbdkit/nbdkit.py
the value:10s is supported after 1.40. So remove this value for 10.1.
DELAY FORMAT
In nbdkit ≥ 1.40, [nbdkit_parse_delay(3)](https://libguestfs.org/nbdkit_parse_delay.3.html) is used to parse the delay parameters, so a wide variety of formats are accepted, such as:
delay-read=1.5
delay-write=100ms
delay-zero=1.2μs
delay-trim=1000ns
In nbdkit ≤ 1.38, only a whole number of seconds, or a whole number of milliseconds (if suffixed by ms) were allowed.
=> nbdkit: fix the value which is supported after 1.40

libvirt/tests/cfg/virtual_network/passt/passt_attach_detach.cfg, libvirt/tests/cfg/virtual_network/passt/passt_function.cfg, libvirt/tests/cfg/virtual_network/passt/passt_lifecycle.cfg, libvirt/tests/cfg/virtual_network/passt/passt_reconnect.cfg, libvirt/tests/cfg/virtual_network/passt/passt_transfer_file.cfg, libvirt/tests/src/virtual_network/passt/passt_attach_detach.py, libvirt/tests/src/virtual_network/passt/passt_function.py, libvirt/tests/src/virtual_network/passt/passt_lifecycle.py, libvirt/tests/src/virtual_network/passt/passt_reconnect.py, libvirt/tests/src/virtual_network/passt/passt_transfer_file.py, provider/virtual_network/passt.py
In some environment, there are more than one default routes in ip route output, for example on ARM host.
This patch is to support this situation instead of only selecting the first default route which is not accurate.
For example:
"nexthops":[{"gateway":"fe80::4a5a:d00:6631:2920","dev":"eno1","weight":1,"flags":[]}, {"gateway":"fe80::4a5a:d00:6631:b20","dev":"eno1","weight":1,"flags":[]}
=> passt: support multiple default routes

libvirt/tests/src/virtiofs/virtiofs.py
For now, we do not need to use systemd-run to
run virtiofsd process any more, then there is
no need to change the selinux context of
/usr/libexec/virtiofsd
=> Remove systemd-run when run virtiofsd process

libvirt/tests/cfg/memory/memory_devices/nvdimm_memory_turn_to_dram.cfg
No NVDIMM nor DIMM on s390x, disable.
=> nvdimm: disable test on s390x

libvirt/tests/cfg/migration/migrate_vm.cfg, libvirt/tests/src/migration/migrate_vm.py
Replaced compilation of netperf with the netperf rpm for testing.
Test result:
(1/1) type_specific.io-github-autotest-libvirt.virsh.migrate_vm.positive_testing.live_migration.stress.host.netperf_network.without_postcopy: STARTED
(1/1) type_specific.io-github-autotest-libvirt.virsh.migrate_vm.positive_testing.live_migration.stress.host.netperf_network.without_postcopy: PASS (143.04 s)
=> migration: Update netperf

libvirt/tests/src/migration/migration_with_vtpm/migration_with_vtpm_state_on_block_dev.py
=> migration_with_vtpm_state_on_block_dev: fix syntax error

libvirt/tests/cfg/migration/migration_misc/migration_with_cpu_mode.cfg, libvirt/tests/src/migration/migration_misc/migration_with_cpu_mode.py
XXX-303279 - [VM migration] migrate vm with cpu mode
Test result:
(1/8) type_specific.io-github-autotest-libvirt.migration.migration_misc.migration_with_cpu_features.host_model.with_xml.p2p: STARTED
(1/8) type_specific.io-github-autotest-libvirt.migration.migration_misc.migration_with_cpu_features.host_model.with_xml.p2p: PASS (184.62 s)
(2/8) type_specific.io-github-autotest-libvirt.migration.migration_misc.migration_with_cpu_features.host_model.with_xml.non_p2p: STARTED
(2/8) type_specific.io-github-autotest-libvirt.migration.migration_misc.migration_with_cpu_features.host_model.with_xml.non_p2p: PASS (184.97 s)
(3/8) type_specific.io-github-autotest-libvirt.migration.migration_misc.migration_with_cpu_features.host_model.without_xml.p2p: STARTED
(3/8) …
=> migration: add case about migrate vm with cpu mode

v2v/tests/cfg/nbdkit/nbdkit.cfg
the package nbdkit on RHEL10 + has more than one rpm dependencies and it caused the rpmbuild failed.
Case on rhel9 can be passed successfully. 
Adding version control to skip this source pkg check on rhel10+.
=> nbdkit: fix the failed case with the version issue

libvirt/tests/cfg/migration/migrate_mem.cfg
a31e2c2cd3d7a1ad41c3a7164566ab1db2e3b1f3 apparently fixed the configuration value for a specific VM setup.
This now leads to test failure for s390x with 1GB RAM.
For s390x, restore the previous value.
=> migrate_mem: restore configuration for s390x

libvirt/tests/cfg/migration/migration_with_vtpm/migration_with_vtpm_state_on_block_dev.cfg, libvirt/tests/src/migration/migration_with_vtpm/migration_with_vtpm_state_on_block_dev.py
'utf-8' codec can't decode byte 0xff in position 1465040: invalid start byte
The ignoring will not impact some key strings matched in the log.
=> migration: Fix decode failure

libvirt/tests/src/virtual_disks/virtual_disks_multipath.py
The auto case virtual_disks.multipath.rawio_yes.sgio_filtered.hotplug has 20% failure rate. It maybe caused by using udev to scan the multipath device for too long, causing the device to be occupied. So add timeout before test.
Also because for multipath SAN, the scaning time between 10s to 30s. So use 15s here.
=> virtual_disks: fix sgio issue with multipath disk

libvirt/tests/cfg/sriov/vIOMMU/intel_iommu_aw_bits.cfg
The previous error message is "Supported values for aw-bits are", but in current version it's "supported values for aw-bits are". So update the script to include all of them.
=> SRIOV: fix an expected error message issue

libvirt/tests/cfg/virtual_network/update_device/update_iface_type_live.cfg, libvirt/tests/src/virtual_network/update_device/update_iface_type_live.py
- VIRT-298342 - [update-device] live update interface with different interface type - bridge/direct type
Furthermore, use get_iface_xml_inst instead because it contains the
get_devices function and logging, making code cleaner
=> Update case:update interface type live

libvirt/tests/cfg/migration/migration_with_vtpm/migration_with_vtpm_state_on_block_dev.cfg, libvirt/tests/src/migration/migration_with_vtpm/migration_with_vtpm_state_on_block_dev.py
Due to an incorrect restorecon path, the expected matching string could not be found. So update script.
Before:
Unable to find root root unconfined_u:object_r:default_t:s0.*.. in total 0&#10;drwxr-xr-x. 2 tss  tss  system_u:object_r:virt_var_lib_t:s0  6 Jun  5 07:11 .&#10;drwxr-xr-x. 3 root root system_u:object_r:var_t:s0          24 Jun  5 07:12 ..
After:
(1/1) type_specific.io-github-autotest-libvirt.migration_with_vtpm.migration_with_vtpm_state_on_block_dev.auto_create_file: STARTED
(1/1) type_specific.io-github-autotest-libvirt.migration_with_vtpm.migration_with_vtpm_state_on_block_dev.auto_create_file: PASS (276.74 s)
=> migration: Fix incorrect path issue

libvirt/tests/cfg/migration_with_copy_storage/async_job/query_domain_job_info.cfg
Add the SSH connection steps.
Before:
Not found 'migration statistics are available only on the source host' in 'error: failed to connect to the hypervisor&#10;error: Cannot recv data: Warning: Permanently added '10.72.132.24' (ED25519) to the list of known hosts. &#10;Permission denied, please try again. &#10;Permission denied, please try again. &#10;root@10.72.132.24: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).: Connection reset by peer
After:
(1/1) type_specific.io-github-autotest-libvirt.migration_with_copy_storage.async_job.query_domain_job_info.copy_storage_all.p2p: STARTED
(1/1) type_specific.io-github-autotest-libvirt.migration_with_copy_storage.async_job.query_domain_job_info.copy_storage_all.p2p: PASS (202.06 s)
=> migration: Fix the SSH connection issue

libvirt/tests/cfg/sriov/vIOMMU/iommu_repeated_reset.cfg, libvirt/tests/src/sriov/vIOMMU/iommu_repeated_reset.py
**!!! the test is using new functions added to the avocado-vt framework in 
https://github.com/avocado-framework/avocado-vt/pull/4095** 
the test is about running starting VM according matrix setting, 
1. start VM and wait till booted, then reboot the guest ad
2. do guest reset during guest rebooting required times (with some randomized sleep time to reset in different part of reboot) 
3. log into the VM
4. check the /var/log/libvirt/qemu/vm.log for virtio: zero sized buffers are not allowed
the test can be parametrized:
- max_wait_ms = 3000 # max number of miliseconds to wait between resets to provide some randomness in execution, the number should be less then expected time needed for reboot
- max_repeat = 10 # number of repetition 
- log_messages # single string or list of strings to …
=> automate VIRT-303225 - [vIOMMU] virsh reset when booting guest for 10+ times

libvirt/tests/cfg/cpu/vm_features.cfg
- RHEL-288471 - Start VM with hyperv passthrough mode
Test result:
(1/1) type_specific.local.vm_features.positive_test.hyperv.passthrough: STARTED
(1/1) type_specific.local.vm_features.positive_test.hyperv.passthrough: PASS (34.33 s)
=> Add new cpu case of hv-passthrough

contributor_reviewer_maintainer_guidelines.rst
Links to avocado-vt contributor guidelines. That file was moved. Fix url.
=> contributor guidelines: fix link

libvirt/tests/cfg/virtual_network/passt/passt_transfer_file.cfg
For RHEL image mode, the directory '/' is read-only. It will cause the case failures when trying to write a file on it. Fix it with the writable directory '/var/tmp'.
=> passt: Replace the test file dir '/' with '/var/tmp'

libvirt/tests/cfg/passthrough/ccw/libvirt_ccw_passthrough.cfg, libvirt/tests/cfg/passthrough/ccw/libvirt_ccw_passthrough_read_write.cfg, libvirt/tests/cfg/virtual_disks/virtual_disks_dasd.cfg, libvirt/tests/src/passthrough/ccw/libvirt_ccw_passthrough.py, libvirt/tests/src/passthrough/ccw/libvirt_ccw_passthrough_read_write.py, libvirt/tests/src/virtual_disks/virtual_disks_dasd.py, provider/vfio/ccw.py, provider/vfio/mdev_handlers.py, virttools/tests/cfg/virt_install/blk_installation.cfg, virttools/tests/cfg/virt_install/hostdev_mdev.cfg, virttools/tests/cfg/virt_install/vfio_installation.cfg, virttools/tests/src/virt_install/blk_installation.py, virttools/tests/src/virt_install/hostdev_mdev.py, virttools/tests/src/virt_install/vfio_installation.py
Depends on https://github.com/avocado-framework/avocado-vt/pull/4119
Our test environments now use DASD only for passthrough tests. Therefore it's safe to select the first DASD in Use. Select assume per default environments are set up with at least 1 DASD disk in Use.
=> passthrough/ccw: update disk selection

libvirt/tests/cfg/virtual_network/passt/passt_attach_detach.cfg, libvirt/tests/cfg/virtual_network/passt/passt_function.cfg
The cases will failed with error "FAIL: Host default ipv6 gateway not consistent with vm" for the host with multiple nexthops in default route like: default proto ra metric 100 pref medium
nexthop via fe80::4a5a:d01:f631:3320 dev eno1 weight 1
nexthop via fe80::4a5a:d01:f631:2420 dev eno1 weight 1
Allow multiple nexthops to fix the failures.
=> passt_function: Allow multiple nexthops

libvirt/tests/src/virtual_network/update_device/update_iface_source.py, libvirt/tests/src/virtual_network/virtual_network_multivms.py
dhclient is deprecated on RHEL 10 and will have to be removed from our
code base. Use avocado-vt functions instead of invoking it directly so
this can be handled from avocado-vt when needed.
=> Remove dhclient from tests

libvirt/tests/src/virtual_network/update_device/update_iface_type_live.py
That will fix the error:
'XMLTreeFile' object has no attribute 'str_out'
=> update_device: Replace str_out() with __str__()

libvirt/tests/src/memory/nvdimm.py
Snapshot revert is already supported since libvirt-9.9.0 , so this patch is to support this operation and retained the functionality to test older versions
Signed-off-by: Bolatbek Issakh <bissakh@redhat.com>
=> nvdimm: Add libvirt version check for snapshot revert

libvirt/tests/cfg/memory/memory_devices/invalid_nvdimm_memory_device_config.cfg, libvirt/tests/src/memory/memory_devices/invalid_nvdimm_memory_device_config.py
Test result:
(01/10) type_specific.io-github-autotest-libvirt.memory.devices.invalid_nvdimm.with_numa.exceed_slot: STARTED
(01/10) type_specific.io-github-autotest-libvirt.memory.devices.invalid_nvdimm.with_numa.exceed_slot: PASS (31.94 s)
(02/10) type_specific.io-github-autotest-libvirt.memory.devices.invalid_nvdimm.with_numa.max_addr: STARTED
(02/10) type_specific.io-github-autotest-libvirt.memory.devices.invalid_nvdimm.with_numa.max_addr: PASS (39.96 s)
(03/10) type_specific.io-github-autotest-libvirt.memory.devices.invalid_nvdimm.with_numa.unexisted_node: STARTED
(03/10) type_specific.io-github-autotest-libvirt.memory.devices.invalid_nvdimm.with_numa.unexisted_node: PASS (40.11 s)
(04/10) type_specific.io-github-autotest-libvirt.memory.devices.invalid_nvdimm.with_numa.unexisted_path: …
=> Optimize to accommodate multiple error msg

v2v/tests/cfg/specific_kvm.cfg
The error message is changed after 9.7/10.1. So modify the msg_content accordingly.
=> v2v:fix the failed no-shutdown case

libvirt/tests/cfg/migration/async_ops/query_info_during_migration.cfg, provider/migration/migration_base.py
Update loop time to ensure the VM is in running state when executing the command.
Test result:
(1/1) type_specific.io-github-autotest-libvirt.migration.async_ops.query_info_during_migration.with_postcopy.non_p2p: STARTED
(1/1) type_specific.io-github-autotest-libvirt.migration.async_ops.query_info_during_migration.with_postcopy.non_p2p: PASS (266.12 s)
=> migration: Update loop time

v2v/tests/cfg/specific_kvm.cfg, v2v/tests/src/specific_kvm.py
1. Adjust cases about no space scenarios
2. Change the error info for cases about running guest
3. Improve the checkpoint of cases about time sync
=> Fix some failures of v2v specific_kvm job

libvirt/tests/cfg/migration/pause_postcopy_migration_and_recover/pause_by_network_and_recover.cfg, libvirt/tests/src/migration/pause_postcopy_migration_and_recover/pause_by_network_and_recover.py
For libvirt layer network broken, recover postcopy migration step will fail because qemu migration still running. So updated auto script.
=> migration: Update pause by network test case

libvirt/tests/cfg/virtual_device/vsock.cfg, libvirt/tests/src/virtual_device/vsock.py
=> Add the case of ssh proxy for vsock

libvirt/tests/cfg/migration/pause_postcopy_migration_and_recover/pause_and_recover_and_disruptive.cfg, libvirt/tests/cfg/migration/pause_postcopy_migration_and_recover/pause_and_recover_twice.cfg, libvirt/tests/cfg/migration/pause_postcopy_migration_and_recover/unattended_migration.cfg, libvirt/tests/cfg/migration/pause_postcopy_migration_and_recover/unattended_migration_and_disruptive.cfg, libvirt/tests/src/migration/pause_postcopy_migration_and_recover/pause_and_recover_and_disruptive.py, libvirt/tests/src/migration/pause_postcopy_migration_and_recover/pause_and_recover_twice.py, libvirt/tests/src/migration/pause_postcopy_migration_and_recover/unattended_migration.py, libvirt/tests/src/migration/pause_postcopy_migration_and_recover/unattended_migration_and_disruptive.py
Update tcp configurations parameters to make tcp connections timeout more quickly.
Test result: 2 cases failed due to one bug.
(1/4) type_specific.io-github-autotest-libvirt.migration.pause_postcopy_migration_and_recover.unattended_migration.with_undefinesource_persistent.network_issue_libvirt_layer.p2p: STARTED
(1/4) type_specific.io-github-autotest-libvirt.migration.pause_postcopy_migration_and_recover.unattended_migration.with_undefinesource_persistent.network_issue_libvirt_layer.p2p: FAIL: Migrated VMs failed to be in failed to get domain state at source (367.11 s)
(2/4) type_specific.io-github-autotest-libvirt.migration.pause_postcopy_migration_and_recover.unattended_migration.with_undefinesource_persistent.network_issue_libvirt_layer.non_p2p: STARTED
(2/4) …
=> migration: Update tcp connections 

libvirt/tests/cfg/svirt/dac/dac_seclabel_per_device.cfg, libvirt/tests/src/svirt/dac/dac_seclabel_per_device.py
Device's <seclabel relabel='yes'/> with no <label/> will be rejected. So updating the case.
```
(1/4) type_specific.io-github-autotest-libvirt.svirt.dac.seclabel.per_device.relabel_yes.without_label.disk.cold_plug: STARTED
(1/4) type_specific.io-github-autotest-libvirt.svirt.dac.seclabel.per_device.relabel_yes.without_label.disk.cold_plug: PASS (3.72 s)
(2/4) type_specific.io-github-autotest-libvirt.svirt.dac.seclabel.per_device.relabel_yes.without_label.disk.hot_plug: STARTED
(2/4) type_specific.io-github-autotest-libvirt.svirt.dac.seclabel.per_device.relabel_yes.without_label.disk.hot_plug: PASS (24.25 s)
(3/4) type_specific.io-github-autotest-libvirt.svirt.dac.seclabel.per_device.relabel_yes.without_label.serial.cold_plug: STARTED
(3/4) …
```
=> svirt: Update to check error message for relabel without label device

libvirt/tests/cfg/migration/migration_numa/migration_numatune.cfg, libvirt/tests/src/migration/migration_numa/migration_numatune.py, provider/numa/numa_base.py
The case is to test guest migration when numatune is configured w/o hugepage setting.
Like:
```
<memoryBacking>
<hugepages/>
</memoryBacking>
...
<numatune>
<memory mode='restrictive' nodeset='0-1' />
<memnode cellid='0' mode='restrictive' nodeset='0'/>
<memnode cellid='1' mode='restrictive' nodeset='1'/>
</numatune>
```
Case ID: VIRT-298029 
=> migration_numa: add case

libvirt/tests/cfg/virsh_cmd/domain/virsh_guestinfo.cfg, libvirt/tests/src/virsh_cmd/domain/virsh_guestinfo.py
This is to support the scenario like below
$ virsh guestinfo rhel1 --load
load.1m             : 0.917969
load.5m             : 1.265625
load.15m            : 0.906738
=> virsh_guestinfo: add case for cpu load

libvirt/tests/cfg/virtual_network/network/virsh_cmds/virsh_net_desc.cfg, libvirt/tests/src/virtual_network/network/virsh_cmd/virsh_net_desc.py
xxxx-300439: Test virsh net-desc with different options to show or modify network description or title.
https://github.com/avocado-framework/avocado-vt/pull/4144 
```
avocado run --vt-type libvirt --vt-machine-type q35 virtual_network.network.net_desc
(01/28) type_specific.io-github-autotest-libvirt.virtual_network.network.net_desc.live.active_net.title.cmdline: STARTED
(01/28) type_specific.io-github-autotest-libvirt.virtual_network.network.net_desc.live.active_net.title.cmdline: PASS (9.34 s)
(02/28) type_specific.io-github-autotest-libvirt.virtual_network.network.net_desc.live.active_net.title.edit_space: STARTED
(02/28) type_specific.io-github-autotest-libvirt.virtual_network.network.net_desc.live.active_net.title.edit_space: PASS (11.44 s) …
```
=> add case for virsh net-desc cmd

libvirt/tests/cfg/virtual_network/network/virsh_cmds/virsh_net_metadata.cfg, libvirt/tests/src/virtual_network/network/virsh_cmds/virsh_net_metadata.py
xxxx-300498:'virsh net-metadata' with different options to show or modify the XML metadata of a network.
Depend on https://github.com/avocado-framework/avocado-vt/pull/4143
=> add case for virsh net-metadata cmd

libvirt/tests/cfg/guest_kernel_debugging/guest_kdump.cfg, libvirt/tests/src/guest_kernel_debugging/guest_kdump.py
The patch introduces guest kernel debugging via kdump mechanism. 
The script is used to test the kdump functionality of the guest(s).
1. Check if kdump.service is operational
2. Get the vmcores present in the guest
3. Load the stress app if specified
4. Trigger crash simultaneously in all guests
5. Debug vmcore using crash utility if specified
Using this patch the followng scenarios can be verified
1. single-guest: 
a. kdump with no stress 
b. kdump with stress 
c. kdump with stress with crash utility
3. multi-guests: 
a. kdump with no stress 
b. kdump with stress 
c. kdump with stress with crash utility
=> Add new test case: guest_kdump test

libvirt/tests/src/libvirt_mem.py
The following testcases are failing because because of the check for test_qemu_cmd is not added in the script
1. type_specific.io-github-autotest-libvirt.libvirt_mem. positive_test.align_256m.cold_plug:
FAIL: Qemu command check fail. (205.37 s)
2. type_specific.io-github-autotest-libvirt.libvirt_mem. positive_test.align_256m.hot_plug:
FAIL: Qemu command check fail. (209.51 s)
In the libvirt_mem.cfg, the following parameter is set to no - "test_qemu_cmd = no"
Hence, the check must be added in all places
=> libvirt-mem: Enable check for test_qemu_cmd

libvirt/tests/cfg/guest_kernel_debugging/virsh_dump.cfg, libvirt/tests/src/guest_kernel_debugging/virsh_dump.py
This Patch adds support for testing Crash Utility
for vmcore generated by "virsh dump" command.
Crash Utility is a tool that allows us to interactively analyze a running Linux system as well as a core dump created.
This crash_utility function works as following:
Check the working of crash utility tool to analyse the guest dump In order for the function to work, both the guest and the host must have the same kernel
- If crash tool or kernel debug libraries are not installed, the test returns error
- If crash tool cannot read into the vmcore, the test returns fail
- If crash tool can read the vmcore, the test returns pass
The Function returns:
0: Success
1: Crash command failed
2: Dependency installation failed or vmlinux not found
3: Kernel mismatch between host and guest
4: Guest kernel …
=> virsh-dump: Add Crash Utility Tests for vmcore

libvirt/tests/src/virsh_cmd/domain/virsh_domjobinfo.py
There is AVC denials in the audit log with privious code. After updating the lable of the *.fifo file, the issue can be fixed.
=> Fix the AVC denials in audit log

libvirt/tests/src/save_and_restore/restore_from_unqualified_file.py
In the script, it creates a new directory /var/tmp, and put the saved file into this directory. It causes avc denials log in the audit log since this directory is not configured with proper selinux lables, fix it.
=> Fix the avc denials

libvirt/tests/cfg/virtual_network/update_device/update_iface_with_options_active.cfg
It will fix the error like following when defining a domain: XML error: interface type='network' requires a 'source' element
=> update_device: Add the missing source network

libvirt/tests/src/migration/migration_with_virtiofs/migration_with_externally_launched_virtiofs_dev.py, libvirt/tests/src/migration/migration_with_vtpm/migration_with_external_tpm.py
Failed to run virtiofsd/swtpm command on target host which lead to 'Permission denied' error. So update case.
Before:
Command '/bin/virsh attach-device avocado-vt-vm1 /var/tmp/xml_utils_temp_0g89yjed.xml' failed.&#10;stdout: b'\n'&#10;stderr: b"error: Failed to attach device from /var/tmp/xml_utils_temp_0g89yjed.xml\nerror: internal error: unable to execute QEMU command 'chardev-add': Failed to add chardev 'chr-vu-fs0': Failed to connect to '/var/vm001-vhost-fs.sock': Permission denied\n"
VM 'avocado-vt-vm1' failed to start: error: Failed to start domain 'avocado-vt-vm1'&#10;error: internal error: process exited while connecting to monitor: 2025-06-09T16:59:09.005669Z qemu-kvm: -chardev socket,id=chrtpm,path=/var/tmp/guest-swtpm.sock: Failed to connect to '/var/tmp/guest-swtpm.sock': …
=> migration: Fix connect sock issue

libvirt/tests/src/virsh_cmd/domain/virsh_metadata.py
According to https://gitlab.com/libvirt/libvirt/-/commit/312088d9b62334c950310f369b2e0fe2302a74a3 the command will return an empty string instead of error message after libvirt-11.3.0
=> virsh_metadata: fix no option

v2v/tests/cfg/function_test_esx.cfg, v2v/tests/src/function_test_esx.py
Automate case for print blkhash of converted image in virt-v2v debugging output
Test results:
```
JOB ID     : 93c4b080d59b27c761ca3e917f3f9fba27b9f46e
JOB LOG    : /var/log/avocado/job-results/job-2025-07-11T06.27-93c4b08/job.log
(1/1) type_specific.io-github-autotest-libvirt.function_test_esx.positive_test.print_blkhash.esx_70.libvirt.it_vddk.vpx_uri: STARTED
(1/1) type_specific.io-github-autotest-libvirt.function_test_esx.positive_test.print_blkhash.esx_70.libvirt.it_vddk.vpx_uri: PASS (274.71 s)
JOB HTML   : /var/log/avocado/job-results/job-2025-07-11T06.27-93c4b08/results.html
JOB TIME   : 276.53 s
```
=> Add a case to test nbdcopy with blkhash in virt-v2v debugging output

libvirt/tests/cfg/virsh_cmd/nodedev/virsh_nodedev_persistence_mdev.cfg, libvirt/tests/src/virsh_cmd/nodedev/virsh_nodedev_persistence_mdev.py
11d5316 changed the standard device selection for ccw/dasd. This test was missed, fix it now.
Also, log the nodedev XML for easier debugging.
=> nodedev_persistence: fix default configuration

libvirt/tests/src/virsh_cmd/domain/virsh_domjobinfo.py
e94a92687fbebb0eaaab3c37d8f0560eea41470c fixes AVC denials by applying SELinux labels on test data. However, this doesn't apply on older RHEL versions like RHEL 9.2 where the command will fail
"""
chcon: failed to change context of '/var/tmp/avocado_3jwe6qnb/domjobinfo.fifo' to 'unconfined_u:object_r:virtqemud_t:s0': Invalid argument """
As it's difficult to control which RHEL version and which selinux policy this command actually applies to, let's just ignore if it fails assuming it will only fail in cases where the label is invalid and either not necessary or the test case needs to be updated with a new label anyway.
=> virsh_domjobinfo: don't fail on selinux labeling

libvirt/tests/cfg/migration/migration_numa/migration_numatune.cfg, libvirt/tests/src/migration/migration_numa/migration_numatune.py
Before:
eval() arg 1 must be a string, bytes or code object
After:
(1/8) type_specific.io-github-autotest-libvirt.migration.numa.numatune.mem_mode_strict.default: STARTED
(1/8) type_specific.io-github-autotest-libvirt.migration.numa.numatune.mem_mode_strict.default: PASS (165.93 s)
(2/8) type_specific.io-github-autotest-libvirt.migration.numa.numatune.mem_mode_strict.hugepage: STARTED
(2/8) type_specific.io-github-autotest-libvirt.migration.numa.numatune.mem_mode_strict.hugepage: PASS (229.78 s)
(3/8) type_specific.io-github-autotest-libvirt.migration.numa.numatune.mem_mode_interleave.default: STARTED
(3/8) type_specific.io-github-autotest-libvirt.migration.numa.numatune.mem_mode_interleave.default: PASS (168.31 s)
(4/8) type_specific.io-github-autotest-libvirt.migration.numa.numatune.mem_ …
=> migration: Fix eval arg error

libvirt/tests/cfg/in_place_upgrade_guest.cfg, libvirt/tests/src/in_place_upgrade_guest.py
From RHEL9.7, we need to keep the original upgrade-paths until devel-freeze, because it could happen the package could be released in advance when it's required, and such a released package must not officially support IPU form 9.7 to 10.1.
=> in_place_upgrade_guest: add LEAPP_DEVEL_SKIP_CHECK_OS_RELEASE variable

libvirt/tests/cfg/migration/memory_copy_mode/postcopy.cfg
Test result:
(1/1) type_specific.io-github-autotest-libvirt.migration.memory_copy_mode.postcopy.timeout_with_short_value.p2p: STARTED
(1/1) type_specific.io-github-autotest-libvirt.migration.memory_copy_mode.postcopy.timeout_with_short_value.p2p: PASS (229.24 s)
=> migration: Add case to test a short timeout

libvirt/tests/cfg/virtual_network/network/block_test/virtnetworkd_unblock_systemd_inibit.cfg, libvirt/tests/src/virtual_network/network/block_test/virtnetworkd_unblock_systemd_inibit.py
xxxx-304214:virtnetworkd should not block host OS shutdown when a virtual network is active
```
avocado run --vt-type libvirt --vt-machine-type q35 virtual_network.network.block_test
(1/4) type_specific.io-github-autotest-libvirt.virtual_network.network.block_test.active_net.default_net.virtnetworkd_unblock_systemd_inibit: PASS (6.71 s)
(2/4) type_specific.io-github-autotest-libvirt.virtual_network.network.block_test.active_net.define_net.virtnetworkd_unblock_systemd_inibit: PASS (6.60 s)
(3/4) type_specific.io-github-autotest-libvirt.virtual_network.network.block_test.inactive_net.default_net.virtnetworkd_unblock_systemd_inibit: PASS (6.68 s)
(4/4) type_specific.io-github-autotest-libvirt.virtual_network.network.block_test.inactive_net.define_net.vi …
```
=> add case for virtnetworkd not block host shutdown

libvirt/tests/cfg/virtual_network/network/block_test/virtnetworkd_unblock_systemd_inibit.cfg
Test config was missing newline. As such, the cartesian config wouldn't find any test cases anymore.
With the additional newline the test run works well again.
=> network/block_test: fix test config

provider/migration/base_steps.py
Reload firewall on source host during `cleanup_connection()` if migrate_desturi_port is set. Although this is technically unnecessary, as any test that modifies the firewall on the source host should clean it up within the test, in edge cases where the test fails early and cleanup isn't finished, this should ensure that the firewall is reset on both the target and the source.
=> base_steps: reload firewall on source host during cleanup

libvirt/tests/src/virtual_network/connectivity/connectivity_check_ethernet_interface.py
For the guest with multiple interfaces, the asymmetric routing may send the ICMP packets from one interface and receive them by another interface. For example:
\# ping 1.1.1.1 -I enp7s0
PING 1.1.1.1 (1.1.1.1) from 192.168.122.252 enp7s0: 56(84) bytes of data
Capturing on 'enp1s0'
1 0.000000000      1.1.1.1 → 192.168.122.252 ICMP 98 Echo (ping) reply    id=0x0007, seq=1295/3845, ttl=52
2 0.511943887      1.1.1.1 → 192.168.122.252 ICMP 98 Echo (ping) reply    id=0x000c, seq=29/7424, ttl=52
If the rp_filter[1] is enabled, Linux will refuse the replied ICMP packets and cause packets loss.
[1]: https://sysctl-explorer.net/net/ipv4/rp_filter/
=> connectivity: Disable Reverse Path Filtering for ping

libvirt/tests/cfg/daemon/conf_file/libvirtd_conf/check_negative_parameter.cfg, libvirt/tests/src/daemon/conf_file/libvirtd_conf/check_negative_parameter.py
Set invalid values for log_outputs in virtqemud.conf, check error
messages when virtqemud.service restarting fails.
=> check_negative_parameter: test invalid log_outputs

libvirt/tests/cfg/virtual_device/tpm_device.cfg, libvirt/tests/src/virtual_device/tpm_device.py
virsh domcapabilities should be able to expose vtpm info, such as
version, model, backend type, should be same as qemu-kvm or swtpm
supported. There's a bug RHEL-102057 in which the return code of
'qemu-kvm -tpmdev help' is 1, so collect stderr instead of stdout.
=> tpm_device: check vtpm support in domcapabilities

libvirt/tests/cfg/migration/pause_postcopy_migration_and_recover/pause_and_recover_twice.cfg, libvirt/tests/src/migration/pause_postcopy_migration_and_recover/pause_and_recover_twice.py, provider/migration/migration_base.py
1. Update error message.
2. Update to use migration port instead of fixed port when breaking the network.
3. Adjusted the code structure to improve maintainability.
=> migration: Fix some issues in pause_and_recover_twice

libvirt/tests/cfg/migration/migration_misc/canonical_paths_in_shared_filesystems.cfg
seabios and stateless firmware are not supported on arm.
=> canonical_paths_in_shared_filesystems: update for arm

libvirt/tests/cfg/guest_os_booting/ovmf_firmware/ovmf_backed_nvram.cfg
Updated cfg so that in all cases, on aarch64, the format is set to qcow2.
Before:
```
(.libvirt-ci-venv-ci-runtest-Eqr9Ec) bash-5.1# avocado run --vt-type libvirt --vt-omit-data-loss --vt-machine-type arm64-mmio guest_os_booting.ovmf_backed_nvram.file --job-timeout 1200 --vt-connect-uri qemu:///system
(1/1) type_specific.io-github-autotest-libvirt.guest_os_booting.ovmf_backed_nvram.file: STARTED
(1/1) type_specific.io-github-autotest-libvirt.guest_os_booting.ovmf_backed_nvram.file: FAIL: Configured os xml value {'template': '/usr/share/edk2/aarch64/vars-template-pflash.qcow2', 'type': 'file', 'format': 'raw'} doesn't match the entry {'template': '/usr/share/edk2/aarch64/vars-template-pflash.qcow2', 'type': 'file', 'format': 'qcow2'} in gu... (37.67 s)
RESULTS    : PASS 0 …
```
=> ovmf_backed_nvram: ensure qcow2 format specified on arm

libvirt/tests/src/numa/numa_capabilities.py
When sys file cluster_id is -1, libvirt will display 0 for cluster_id in virsh capabilities
=> numa_capabilities: fix negative cluster_id

libvirt/tests/src/libvirt_vcpu_plug_unplug.py
If the qemu-guest-agent installed in the base commit for bootc system of
guest, it cannot be removed. Stop its service for such a condition.
=> libvirt_vcpu_plug_unplug: Mask qemu-guest-agent instead of remove it 

v2v/tests/cfg/nbdkit/nbdkit.cfg
There's one file I missed in my last pr https://github.com/autotest/tp-libvirt/pull/6481 
we need make sure the nbdkit version is in the range nbdkit-1.26.5-1,nbdkit-1.45
=> change the version of nbdkit to latest

libvirt/tests/src/migration/migration_performance_tuning/migration_zerocopy.py
From qemu-kvm-10.0.0-8, postcopy + multifd is supported. So update script.
=> migration: Update migration_zerocopy case

libvirt/tests/src/virsh_cmd/domain/virsh_domjobabort.py
Take care of the *.fifo file since qemu needs to read from it.
=> Fix the AVC deny in audit log

libvirt/tests/src/memory/nvdimm.py
Since this is one public boot config check function, so use it instead.
test result:
(1/1) type_specific.io-github-autotest-libvirt.nvdimm.back_file.label.default: STARTED
(1/1) type_specific.io-github-autotest-libvirt.nvdimm.back_file.label.default: PASS (85.22 s)
=> Use common boot config check function instead the local implementation

libvirt/tests/cfg/memory/memory_devices/nvdimm_memory_turn_to_dram.cfg
Since numa memory dominate the guest memory size, increase it to avoid memory shortage.
Test result:
(1/1) type_specific.io-github-autotest-libvirt.memory.devices.nvdimm.turn_to_dram: STARTED
(1/1) type_specific.io-github-autotest-libvirt.memory.devices.nvdimm.turn_to_dram: PASS (188.81 s)
=> Increase numa memory

libvirt/tests/cfg/sriov/vfio/sriov_migration_vfio_variant_driver.cfg, libvirt/tests/cfg/sriov/vfio/sriov_vm_lifecycle_vfio_variant_driver.cfg, libvirt/tests/src/sriov/vfio/sriov_migration_vfio_variant_driver.py, libvirt/tests/src/sriov/vfio/sriov_vm_lifecycle_vfio_variant_driver.py, provider/sriov/sriov_vfio.py
This PR adds:
VIRT-299307 VM lifecycle with vfio variant driver
VIRT-299308 Migrate VM with vfio variant driver
```
(01/36) type_specific.io-github-autotest-libvirt.sriov.vm_lifecyle.vfio_variant_driver.start_vm.with_iommu.virtio.single_iface.hostdev_interface.managed_yes.default: STARTED
(01/36) type_specific.io-github-autotest-libvirt.sriov.vm_lifecyle.vfio_variant_driver.start_vm.with_iommu.virtio.single_iface.hostdev_interface.managed_yes.default: PASS (89.69 s)
(02/36) type_specific.io-github-autotest-libvirt.sriov.vm_lifecyle.vfio_variant_driver.start_vm.with_iommu.virtio.single_iface.hostdev_interface.managed_yes.mlx5_vfio: STARTED
(02/36) type_specific.io-github-autotest-libvirt.sriov.vm_lifecyle.vfio_variant_driver.start_vm.with_iommu.virtio.single_iface.hostdev_ …
```
=> sriov: Add migration and lifecycle test for vfio variant driver

libvirt/tests/cfg/storage/virsh_pool.cfg, libvirt/tests/cfg/storage/virsh_pool_autostart.cfg, libvirt/tests/cfg/virsh_cmd/pool/virsh_pool_acl.cfg, libvirt/tests/cfg/virsh_cmd/volume/virsh_vol_download_upload.cfg
In image mode, we can't create the target path /mnt for netfs pool, or it'll get error "Read-only file system". Updating it to /tmp/nfs-mount to fix this error.
=> Storage: update the target path of netfs pool

libvirt/tests/src/virsh_cmd/domain/virsh_detach_device_alias.py
Remove the wildcard from the yum command to avoid installing extraneous packages.
=> [virsh detach device]remove unnecessary package

libvirt/tests/cfg/cpu/setvcpus_check_node_id.cfg, libvirt/tests/cfg/cpu/vm_with_cpu_mode_in_domcapabilities.cfg, libvirt/tests/src/cpu/setvcpus_check_node_id.py, libvirt/tests/src/cpu/vm_with_cpu_mode_in_domcapabilities.py
- VIRT-86511 - [cmd/domcapabilities] Start VM with cpu mode in "virsh domcapabilities"
- RHEL-114636 - [setvcpus] Check node-id in qemu monitor command when hot-plug vcpu
Test result
(1/1) type_specific.local.setvcpus.check_node_id: STARTED
(1/1) type_specific.local.setvcpus.check_node_id: PASS (22.85 s)
(1/1) type_specific.local.vm_with_cpu_mode_in_domcapabilities: STARTED
(1/1) type_specific.local.vm_with_cpu_mode_in_domcapabilities: PASS (16.59 s)
=> Add new cpu cases

libvirt/tests/cfg/backingchain/blockjob/blockjob_pivot_after_irregular_operations.cfg, libvirt/tests/src/backingchain/blockjob/blockjob_pivot_after_irregular_operations.py
Do blockjob --pivot after forbid doing blockcopy to the same source device. Automate case VIRT-294594 S3 scenario.
=> Forbid doing blockcopy to the same source

libvirt/tests/cfg/save_and_restore/start_with_bypass_cache.cfg, libvirt/tests/src/save_and_restore/start_with_bypass_cache.py
Automate case VIRT-297730. There are 2 scenarios: start vm with '--bypass-cache' option, or set 'auto_start_bypass_cache = 1' in qemu.conf and check the function of it.
=> Start vm with --bypass-cache after managedsave

libvirt/tests/cfg/numa/guest_numa_hmat/hmat_info.cfg, libvirt/tests/src/numa/guest_numa_hmat/hmat_info.py
Since RHEL-70321 and RHEL-70322, the hmat msg moved to pr_debug(), so it could not be printed directly in dmesg. Adding kernel version checking for it.
on guest kernel version like kernel-6.12.0-116.el10.x86_64:
before fix :
(1/1) type_specific.io-github-autotest-libvirt.guest_numa_hmat.hmat_info.default:
FAIL: Expect 'Flags:00 Type:Access Latency Initiator' in guest dmesg, but not found (41.88 s)
after fix:
(1/1) type_specific.io-github-autotest-libvirt.guest_numa_hmat.hmat_info.default: STARTED
(1/1) type_specific.io-github-autotest-libvirt.guest_numa_hmat.hmat_info.default: PASS (211.04 s)
=> Add kernel version checking for hmat dmesg verification

libvirt/tests/cfg/memory/memory_devices/dimm_memory_with_memory_backing_type.cfg, libvirt/tests/src/memory/memory_devices/dimm_memory_with_memory_backing_type.py
Test results:
(01/14) type_specific.io-github-autotest-libvirt.memory.devices.dimm.memory_backing_type.cold_plug.ondemand.file: STARTED
(01/14) type_specific.io-github-autotest-libvirt.memory.devices.dimm.memory_backing_type.cold_plug.ondemand.file: PASS (38.33 s)
(02/14) type_specific.io-github-autotest-libvirt.memory.devices.dimm.memory_backing_type.cold_plug.ondemand.anonymous: STARTED
(02/14) type_specific.io-github-autotest-libvirt.memory.devices.dimm.memory_backing_type.cold_plug.ondemand.anonymous: PASS (35.46 s)
(03/14) type_specific.io-github-autotest-libvirt.memory.devices.dimm.memory_backing_type.cold_plug.ondemand.memfd: STARTED
(03/14) type_specific.io-github-autotest-libvirt.memory.devices.dimm.memory_backing_type.cold_plug.ondemand.memfd: PASS (38.17 s)
(04/14) …
=> New case VIRT-299049 for dimm memory with various backing types

libvirt/tests/cfg/memory/memory_devices/nvdimm_memory_with_access_and_discard.cfg, libvirt/tests/src/memory/memory_devices/nvdimm_memory_with_access_and_discard.py
Test results:
(01/18) type_specific.io-github-autotest-libvirt.memory.devices.nvdimm.access_and_discard.define_nvdimm.undefined.file: STARTED
(01/18) type_specific.io-github-autotest-libvirt.memory.devices.nvdimm.access_and_discard.define_nvdimm.undefined.file: PASS (12.67 s)
(02/18) type_specific.io-github-autotest-libvirt.memory.devices.nvdimm.access_and_discard.define_nvdimm.undefined.anonymous: STARTED
(02/18) type_specific.io-github-autotest-libvirt.memory.devices.nvdimm.access_and_discard.define_nvdimm.undefined.anonymous: PASS (12.60 s)
(03/18) type_specific.io-github-autotest-libvirt.memory.devices.nvdimm.access_and_discard.define_nvdimm.undefined.memfd: STARTED
(03/18) type_specific.io-github-autotest-libvirt.memory.devices.nvdimm.access_and_discard.define_nvdimm.undefined.memfd: …
=> Add new case VIRT-299196 for nvdimm with access and discard settings

libvirt/tests/cfg/migration/pause_postcopy_migration_and_recover/pause_and_recover_and_disruptive.cfg
Add error checking to ensure test only passes on expected errors.
=> migration: Add error checking in pause_and_recover_and_disruptive case

libvirt/tests/src/incremental_backup/incremental_backup_pull_mode.py
For some test with readonly disk, we need to create chekcpoint first. But now the condition affects other test cases, so we need to add another condition with_readonly to judge.
=> Inc_backup: fix checkpoint already existes when no readonly disk

libvirt/tests/src/virtiofs/virtiofs.py
1) Openfiles element is not supported in RHEL9.4.
2) The format of sandbox option in virtiofs is different.
Update the script to make it compatible with RHEL9.4 testing.
=> Update the script for RHEL 9.4 compatibility

libvirt/tests/cfg/virsh_cmd/domain/virsh_get_user_sshkeys.cfg, libvirt/tests/cfg/virsh_cmd/domain/virsh_set_user_sshkeys.cfg, libvirt/tests/src/virsh_cmd/domain/virsh_get_user_sshkeys.py, libvirt/tests/src/virsh_cmd/domain/virsh_set_user_sshkeys.py
Automate RHEL-203231 RHEL-264544
Add two negative test scenarios for set/get_user_sshkeys: 
1) acl_test:
Set libvirt API access dirver to polkit, but don't configure polkit rules for set/get_user_sshkeys. When set/get_user_sshkeys is called, such error will be reported:
error: access denied
2) no_start_qemu_guest_agent
Stop qemu guest agent in guest, then set/get_user_sshkeys is called, such error will be reported:
QEMU guest agent is not connected
Test results:
JOB ID     : e8c489abab4bafe62b76cd0d07d2b5c19fba067c
JOB LOG    : /var/log/avocado/job-results/job-2025-08-18T10.37-e8c489a/job.log
(1/4) type_specific.io-github-autotest-libvirt.virsh.set_user_sshkeys.negative.no_start_qemu_guest_agent: STARTED
(1/4) type_specific.io-github-autotest-libvirt.virsh.set_user_sshkeys.negative.no_star …
=> set/get_user_sshkeys: Add negative tests

libvirt/tests/cfg/migration_with_copy_storage/no_sufficient_disk_space_on_target.cfg, libvirt/tests/src/migration_with_copy_storage/no_sufficient_disk_space_on_target.py
Add case to verify that live migration with copying storage will fail when there is no sufficient disk space on target host.
VIRT-297909 - VM live migration with copy storage - no sufficient disk space on target host
=> migration: Add new case for copy storage migration

libvirt/tests/cfg/virtual_network/passt/passt_transfer_file.cfg
The cases will failed with error "FAIL: Host default ipv6 gateway not consistent with vm" for the host with multiple nexthops in default route Allow multiple nexthops and disable ipv6 address gateway comparing if addresses is link-local
=> passt:Allow multiple nexthops

libvirt/tests/cfg/cpu/vm_with_hyperv.cfg, libvirt/tests/src/cpu/vm_with_hyperv.py
- RHEL-185271 - [features][hyper] Start windows VM with hyper-v related features (runtime/synic/stimer/frequencies)
- VIRT-17925 - [features][hyper] Start windows VM with hyper-v related features (relaxed/vapic/spinlocks/vendor_id)
Depends on:
- https://github.com/avocado-framework/avocado-vt/pull/4237
Test result:
```
(1/3) type_specific.local.vm_with_hyperv.relaxed: STARTED
(1/3) type_specific.local.vm_with_hyperv.relaxed: PASS (7.91 s)
(2/3) type_specific.local.vm_with_hyperv.runtime.set_on: STARTED
(2/3) type_specific.local.vm_with_hyperv.runtime.set_on: PASS (10.04 s)
(3/3) type_specific.local.vm_with_hyperv.runtime.set_off: STARTED
(3/3) type_specific.local.vm_with_hyperv.runtime.set_off: PASS (18.23 s)
RESULTS    : PASS 3 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL …
```
=> Add new cpu case of hyper-v

libvirt/tests/cfg/guest_agent/domhostname.cfg, libvirt/tests/src/guest_agent/domhostname.py
Automate RHEL-246544
This is a negative test, no_start_qemu_guest_agent means "don't start qemu-guest-agent service in vm". In this scenario, an error will be printed.
Test result:
(1/1) type_specific.io-github-autotest-libvirt.guest_agent.domhostname.negative.no_start_qemu_guest_agent: STARTED
(1/1) type_specific.io-github-autotest-libvirt.guest_agent.domhostname.negative.no_start_qemu_guest_agent: PASS (84.54 s)
=> domhostname: Add no_start_qemu_guest_agent tests

libvirt/tests/cfg/sriov/plug_unplug/sriov_attach_detach_device_vfio_variant_driver.cfg, libvirt/tests/cfg/sriov/vfio/sriov_migration_vfio_variant_driver.cfg, libvirt/tests/src/sriov/plug_unplug/sriov_attach_detach_device_vfio_variant_driver.py, libvirt/tests/src/sriov/vfio/sriov_migration_vfio_variant_driver.py, libvirt/tests/src/sriov/vfio/sriov_vm_lifecycle_vfio_variant_driver.py, provider/sriov/sriov_vfio.py
The ping test is better to have. But we do not want to skip the test for detaching device when ping test fails. On some hosts, there is no NIC with cable for the vm to use, so ping test will fail as expected.
=> sriov_attach_detach_device_vfio_variant_driver: enhance test

libvirt/tests/src/in_place_upgrade_guest.py
Minor fix. `.*el%s*.*%sk`, specifically `el%s*` will match the `%s` (target major release number) 0 or more times, which is not wanted. Changed to `.*el%s.*%sk`, which ensures `el%s` is matched, as wanted.
=> in_place_upgrade_guest: minor fix to regex pattern

libvirt/tests/cfg/memory/memory_devices/nvdimm_memory_with_memory_allocation_and_numa.cfg
QEMU now reports "nvdimm is not enabled: add 'nvdimm=on' to '-M'" instead of the old "missing 'nvdimm' in '-M'". Updated the expected hot_plug_error in cfg (with_slot → hot_plug_nvdimm.with_node) so the test properly recognizes the failure again.
Committer: Bolatbek Issakh <bissakh@redhat.com>
=> nvdimm: update expected hot_plug_error to match new QEMU message

libvirt/tests/src/memory/memory_balloon/memory_balloon_freepagereporting.py
The test was failing because the host RSS drop did not reach the configured min_memory_difference within the default 30s window. Free Page Reporting can take longer to reclaim memory, especially on ARM hosts or under low memory pressure.
Committer: Bolatbek Issakh <bissakh@redhat.com>
=> Memory_balloon: Increase RSS sampling timeout
