libvirt/tests/src/virsh_cmd/domain/virsh_migrate_copy_storage.py
It was creating new img using qemu-img which overwrites the existing image
even in normal_test scenarios. After fix it is working fine.
=> Fixup: copy-storage migration

libvirt/tests/src/libvirt_mem.py
=> libvirt_mem: Fix for undeclared 'cur_mem'.

libvirt/tests/cfg/virsh_cmd/domain/virsh_migrate.cfg, libvirt/tests/src/virsh_cmd/domain/virsh_migrate.py
The current existing migration cases can't be ran automitically, you need manually setup sharing storage and enable virt_use_nfs seboolean if you're using a NFS storage to share VM image, in addition, if the migration URI transport is SSH, you also need to configure SSH passwordless manually, this patch is used for solving these question and let tester run migartion testing automitically with simple test configuration. Meanwhile, to add new test scenarios for migration testing.
1. Automitically setup NFS sharing ENV and enable virt_use_nfs seboolean
2. Delete complex testing scenarios, such as ping-pong migration, it needs we setup passwordless access
from local/remote to remote/local firstly, we may put these scenarios into ping-pong migration testing.
3. Add some new testing scenarios …
=> virsh_migrate: update basic migration test

libvirt/tests/cfg/virsh_cmd/domain/virsh_migrate.cfg, libvirt/tests/src/virsh_cmd/domain/virsh_migrate.py
This patch adds tests that will pin guest numa node with host numa 
node and performs live, online and live_there_and_back migration 
scenarios. It covers different memory modes strict, preferred and 
interleave. Memory placement is static currently.
=> Added Numatune scenarios for migration - Version 2

libvirt/tests/cfg/virsh_cmd/domain/virsh_migrate_copy_storage.cfg, libvirt/tests/src/virsh_cmd/domain/virsh_migrate_copy_storage.py
1. Apply the image pre-creation feature for RHEV
With qemu-kvm-rhev, it will use libvirt to help create the image on
target host.
With qemu-kvm, the user needs to manually create the image on target
host before storage migration.
2. Fix for multiple disks.
'added_disks_count' value has to be changed to match
libvirt.attach_disk().
'attach_disk_config' is added to make the disks are attached lively.
3. Search in the migration output and skip the test if a known error
message is found.
=> virsh_migrate_copy_storage: fix multi disks case

v2v/tests/cfg/specific_kvm.cfg, v2v/tests/src/specific_kvm.py
test result:
> JOB ID     : 8349bf05548986b520584bb1d44bf5ed67550127
> JOB LOG    : /root/avocado/job-results/job-2016-06-02T10.50-8349bf0/job.log
> TESTS      : 4
>  (1/4) type_specific.local.specific_kvm.positive_test.linux.network.multi_netcards.output_mode.rhev: PASS (835.10 s)
>  (2/4) type_specific.local.specific_kvm.positive_test.linux.network.virtio.output_mode.rhev: PASS (718.39 s)
>  (3/4) type_specific.local.specific_kvm.positive_test.linux.network.rtl8139.output_mode.rhev: PASS (707.81 s)
>  (4/4) type_specific.local.specific_kvm.positive_test.linux.network.e1000.output_mode.rhev: PASS (707.27 s)
> RESULTS    : PASS 4 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0
> JOB HTML   : /root/avocado/job-results/job-2016-06-02T10.50-8349bf0/html/results.html
> TIME       : 2968.57 …
=> Add 4 cases of virt-v2v network

libvirt/tests/src/migration/migrate_vm.py, libvirt/tests/src/virsh_cmd/domain/virsh_migrate_copy_storage.py
- To determine if a certain qemu capability is supported in current
environment, we check the cache directory which is not implemented on
RHEL6. This only works on RHEL7. So an exception will be raised out on
RHEL6 which we should handle it with correct logic.
- A logic error fix
There is a need to create image or create pool before migration.
=> Handle cache directory missing for qemu capability

libvirt/tests/src/virsh_cmd/domain/virsh_migrate_setmaxdowntime.py
utils_misc.wait_for function is invoked, so there is a need to import
utils_misc. Therefore, it seems no need to include
"from virttest.utils_misc import SELinuxBoolean".
=> virsh_migrate_setmaxdowntime: Fix syntax error

libvirt/tests/cfg/virtual_network/iface_options.cfg
Multiqueue is supported up to 256 by the kernel in RHEL7.3
instead of 8. So the number should be updated.
=> iface_options: update the max queue number

libvirt/tests/src/virsh_cmd/domain/virsh_migrate.py
To use default jeos image if migrate_shared_storage is not configured
=> Fixup virsh_migrate.py

v2v/tests/cfg/convert_vm_to_libvirt.cfg, v2v/tests/cfg/convert_vm_to_ovirt.cfg, v2v/tests/src/convert_vm_to_ovirt.py
And remove parameters that are no longer needed.
=> convert_vm_to_ovirt: assign None to parameters for hypervisor kvm

libvirt/tests/src/virtual_disks/at_dt_iscsi_disk.py
refer to beacb9d.
Signed-off-by: Wei Jiangang <weijg.fnst@cn.fujitsu.com>
=> Use interpolation for TestFail() to fix skip message

libvirt/tests/src/virsh_cmd/domain/virsh_domxml_to_native.py
For fixing bug:
https://bugzilla.redhat.com/show_bug.cgi?id=1182074
libvirt commit a1344f7 introduced default secret object created
with a random AES-256 key for domain, the key is under vm dir by
default which depends on the env, so add this part to filter list
and not check it.
=> domxml_to_native: Add '-object secret,id' to filter list

v2v/tests/cfg/specific_kvm.cfg, v2v/tests/cfg/v2v_options.cfg
Unify names of parameters in different cfg files but with same
function to reduce number of config lines of replace part in ci.
=> Sync paramters with earlier cases

libvirt/tests/cfg/migration/migrate_vm.cfg
For storage migration, the current timeout duration is too short which
will cause timeout exception. So now it is increased to a larger value.
=> migrate_vm: increase the migration timeout

libvirt/tests/src/virsh_cmd/host/virsh_nodeinfo.py
As libvirt commit 912813d in 2.0.0 change the api nodeGetInfo with
using common api nodeGetMemory to collect host memory size, current
check with nodeinfo memory size failed.
Update to collect memory size from online nodes meminfo to fix the
case.
=> nodeinfo: Get host memory size from numa nodes

libvirt/tests/src/virsh_cmd/domain/virsh_blockcopy.py
When wait for the block copy job finish, we need make sure the job
exist.
And remove a unused var.
=> blockcopy: make sure blockjob exist

provider/v2v_vmcheck_helper.py, v2v/tests/src/convert_vm_to_libvirt.py, v2v/tests/src/convert_vm_to_ovirt.py
1. Change the return value from number of failed checkpoints to the list of checkpoints to present clearer error message.
2. Move cleanup to final part. The cleanup part in original code is not placed in final part which will cause skipping cleaning up when test fails ahead of cleanup code. Move to final part will solve the problem.
=> Modify return message of v2v guest check

libvirt/tests/cfg/libvirt_mem.cfg
According to the linux kernel, backend memory size must be
multiple of 128MiB.
=> libvirt_mem: Change hotplug memory size to multiple of 128MiB

libvirt/tests/cfg/virsh_cmd/pool/virsh_pool.cfg, libvirt/tests/cfg/virsh_cmd/pool/virsh_pool_acl.cfg, libvirt/tests/cfg/virsh_cmd/volume/virsh_vol_resize.cfg, libvirt/tests/src/virsh_cmd/pool/virsh_pool_acl.py, libvirt/tests/src/virsh_cmd/volume/virsh_vol_create_from.py
For virsh_pool_acl test, iSCSI type pool always start, that because
libvirt just calling iscsiadm command to login the target which is not
discovery first. So hardcode the discovery command for it.
For virsh_vol_create_from test, the default volume in iSCSI pool is the
iSCSI lun, so the input volume size is the pool size, which require the
destination pool size should larger than the input volume size. And LVM
allocates storage in multiples of the physical extent size, which is 4MB
by default.
BTW, this patch also rename the pool/volume name in different tests to
make the debug message more clear.
=> Storage related cases fix and update

libvirt/tests/cfg/virtual_disks/virtual_disks_multidisks.cfg
It's a feature of qemu-kvm. Qemu will report "aio=native was specified,
but it requires cache.direct=on, which was not specified" if there is
no cache=directsync option.
=> Add cache=directsync option if io=native is used for disk driver.

libvirt/tests/src/virsh_cmd/host/virsh_capabilities.py
ubuntu1610 have /usr/bin/kvm instead of /usr/bin/qemu-kvm due to
which test got skipped, this fix enables it.
=> Fixup for virsh_capabilities

libvirt/tests/src/virsh_cmd/virsh_connect.py
In ubuntu libvirt_lxc driver is available in /usr/lib/libvirt which
skipped the test, this fix enables it.
=> Fixup virsh_connect

v2v/tests/cfg/convert_vm_to_libvirt.cfg, v2v/tests/cfg/convert_vm_to_ovirt.cfg
For some windows 8 guests could not be successfully installed on
xen host, remove the cases from matrix as manual team required.
=> Remove win8 on xen from matrix

libvirt/tests/src/virsh_cmd/host/virsh_hostname.py
For hostname with name abc.github.com, shell cmd "hostname" returns only
abc but "virsh hostname" returns full name abc.github.com, which fails
the test case, "hostname -f" fixes this error.
=> Fixup virsh_hostname

libvirt/tests/src/virsh_cmd/domain/virsh_dumpxml.py
If graphics device is not available "with_security.domname" testcases
errors out, this patch handles and skips it.
=> Fixup virsh_dumpxml.py

libvirt/tests/src/virsh_cmd/domain/virsh_cpu_compare.py
virsh_cpu_compare testcases which uses cpu features options present in host capabilities xml,
errors out incase of no features available in xml
domain/virsh_cpu_compare.py", line 63, in get_cpu_xml
libvirtxml.remove_feature(feature_num)
File "/usr/lib/python2.7/site-packages/avocado_plugins_vt-39.0-py2.7.egg/virttest/libvirt_xml/vm_xml.py", line 1562, in remove_feature
node.remove(self.get_feature(num))
File "/usr/lib/python2.7/site-packages/avocado_plugins_vt-39.0-py2.7.egg/virttest/libvirt_xml/vm_xml.py", line 1534, in get_feature
raise xcepts.LibvirtXMLError("Only %d feature(s)" % count)
LibvirtXMLError: Only 0 feature(s)
This patch adds a check for it and skips the test if no features are present.
=> cpu_compare: Add skip when no host features in xml

libvirt/tests/src/migration/migrate_vm.py
- "Cannot access storage file..." error message should not be skipped by
some cases. Fix the wrong matching method.
- Give the migration output to the final exception for more clear
recognition.
=> migrate_vm: Fix some message match mistakes

libvirt/tests/cfg/virsh_cmd/domain/virsh_edit.cfg, libvirt/tests/src/virsh_cmd/domain/virsh_edit.py
1. vpcu count is changed without topology check, so tests fails with,
"Maximum CPUs greater than topology limit\nFailed. Try again?
[y,n,i,f,?]"
2. mem_value assigned as 1000 for mem_unit M, but validating with
1024000 which fails the test - mem_value=1024 fixes it.
This patch fixes these issues and works with and without topology.
=> Fixup virsh_edit.py

libvirt/tests/src/virsh_cmd/network/virsh_net_dhcp_leases.py
We want to remove all the exist interfaces of the VM before test to make
sure the test env clean, but free_mac_address() is not the correct
function we should call, and the interface number may larger than 1.
After the new interface attached, the 'virtnet' attribute of the vm is
not updated automatically, which will lead to vm login fail, so we need
update it explicitly.
=> virsh_net_dhcp_leases: Fix VM login error

libvirt/tests/src/virsh_cmd/domain/virsh_domfstrim.py
Disk map could possible not changed due to disk cache exists in
guest. This will make the disk map got after executing commands
not up to date. Run `sync` after every commands to make sure cached
data is flushed into disk before checking disk map.
Also fixing a typo and making log more verbose.
=> domfstrim: Sync disk before checking disk map

libvirt/tests/src/virsh_cmd/snapshot/virsh_snapshot_dumpxml.py
Have fixed the test case where the exception was not handled when password was not None.
try:
vm_xml.VMXML.add_security_info(
vm_xml.VMXML.new_from_dumpxml(vm_name), passwd)
except Exception, info:
raise error.TestNAError(info)
=> snapshot_dumpxml: Handle exception for variant password is not None

libvirt/tests/cfg/conf_file/libvirtd_conf/host_uuid.cfg
Host UUID with all same digits should not be started and will be a
negative test case.
This bug has been fixed by following libvirt commit
6fe81c3: daemon: add option to read host uuid from /etc/machine-id
=> daemon.host_uuid: All same UUID is a negative case

libvirt/tests/src/virsh_cmd/domain/virsh_undefine.py
For testcase executed remotely with virsh -c qemu+ssh://\<test-mach-IP\>/system
test fail if autologin is not enabled from remote machine. This patch fixes it.
=> Fixup virsh_undefine

libvirt/tests/cfg/virsh_cmd/domain/virsh_migrate_multi_vms.cfg, libvirt/tests/src/virsh_cmd/domain/virsh_migrate_multi_vms.py
1. Reused avocado/avocado-vt libvirt.py for migration threading code
to avoid redundancy (API: MigrationTest()).
2. Thread timeout during migration was not handled to Fail, instead
considered as Error, reusing libvirt.py code fixes it.
3. Added support for unsafe option, and handled disk with cache=none
when --unsafe option is not used.
4. Added testcases for online migration and with --auto-converge option
5. Remote NFS mounting was not handled earlier, fixed it in this patch.
=> Fixup virsh_migrate_multi_vms

v2v/tests/cfg/v2v_options.cfg, v2v/tests/src/v2v_options.py
- Snapshot id in ovf file should not consists of '0's.
- Remove paramters of esx5.1 and esx5.5 for no longer needed.
- Update search pattern of uuids, for content of log changes from
"qemu convert" to "qemu 'convert'" with an extra pair of single
quote.
=> Add checkpoint of snapshot id when convert to rhev

libvirt/tests/cfg/virsh_cmd/domain/virsh_domtime.cfg, libvirt/tests/src/virsh_cmd/domain/virsh_domtime.py
This test virsh domtime command and its options.
1) Start a guest with/without guest agent configured;
2) Record guest times;
3) Do some operation to stop VM;
4) Run virsh domtime command with different options;
5) Check the command result;
6) Check the guest times against expectation;
7) Cleanup test environment.
This PR depends on https://github.com/autotest/virt-test/pull/1961, https://github.com/autotest/virt-test/pull/1963, and https://github.com/autotest/virt-test/pull/1964
=> Add test for virsh command domtime

libvirt/tests/cfg/virsh_cmd/domain/virsh_domfsfreeze_domfsthaw.cfg, libvirt/tests/src/virsh_cmd/domain/virsh_domfsfreeze_domfsthaw.py
This test virsh domfsfreeze and domfsthaw commands and their options.
1) Start a guest with/without guest agent configured;
2) Freeze the guest file systems with domfsfreeze;
3) Create a file on guest to see command hang;
4) Thaw the guest file systems with domfsthaw;
5) Check the file is already created;
6) Retouch the file the ensure guest file system are not frozen;
7) Cleanup test environment.
This PR depends on https://github.com/autotest/virt-test/pull/1961, https://github.com/autotest/virt-test/pull/1962, and https://github.com/autotest/virt-test/pull/1964
=> Add test for virsh command domfsfreeze and domfsthaw

libvirt/tests/cfg/virsh_cmd/domain/virsh_setvcpus.cfg, libvirt/tests/src/virsh_cmd/domain/virsh_setvcpus.py
1. getAttribute("current") will return an unicode type value, so need format it.
2. After set CPU topology, setvcpus should fail, then the VM can start
normally.
=> setvcpus: Fix a TypeError bug and move a case to negative part

libvirt/tests/cfg/libvirt_vcpu_plug_unplug.cfg, libvirt/tests/cfg/virsh_cmd/domain/virsh_setvcpus.cfg, libvirt/tests/src/libvirt_vcpu_plug_unplug.py, libvirt/tests/src/virsh_cmd/domain/virsh_setvcpus.py
Now libvirt support vcpu hotunplug, but the tactics is different with
the test case expected. For hotunplug, the original current vcpus are
non-hotpluggable after VM start, which means we can't hotunplug these
vcpus directly. So we can either hotplug more vcpus before we do
hotunplug, or modify the 'hotpluggable' attribute to 'yes' of the
vcpus except vcpu 0, to make sure libvirt can find appropriate
hotpluggable vcpus to reach the desired target vcpu count.
=> vcpu: case update for vcpu hotunplug

libvirt/tests/src/virsh_cmd/host/virsh_nodeinfo.py
Commit 5a145f3c change the way to check host memory size as 'nodeinfo'
using a different way to collect host memory size since 2.0.0, but for
older versions, we should check it in a different way.
=> virsh.nodeinfo: Using different ways to check host memory

libvirt/tests/cfg/virsh_cmd/domain/virsh_migrate.cfg, libvirt/tests/src/virsh_cmd/domain/virsh_migrate.py
Added test scenarios to perform memory hotplug and then migrate,
migration scenario includes live and online.
=> virsh_migrate: memory hotplug and migration

libvirt/tests/src/virtual_network/iface_options.py
In function create_iface_xml we assume if iface_model is not defined for perticular test then it's "virtio". But in 'run_cmdline_test' if iface_model is not defined then model_option chooses "device rtl8139".
I have made a small change now: if iface_model is not defined then it defaults to "virtio".
Without this patch test will fail looking for non-existant rtl8139 device :
23:42:22 DEBUG| New interface xml file: <?xml version='1.0' encoding='UTF-8'?>
<interface type="network">
<mac address="52:54:00:64:65:66" />
<model />
<source network="default" /><driver><guest /><host /></driver></interface>
23:42:22 DEBUG| Undefine VM virt-tests-vm1-mallesh
23:42:22 DEBUG| Define VM from /var/tmp/xml_utils_temp_yG2jxi.xml
23:42:22 DEBUG| Running 'modprobe vhost_net'
23:42:22 DEBUG| Starting vm …
=> Minor fix to avoid a false failure

libvirt/tests/src/virtual_network/iface_hotplug.py
Currently stress_test for at_iface had only attach_interface. This was causing test to fail after reaching 31 pci slots.. corrected by adding detach_interface as well under at_device stress run.
=> Fixed stress_run for at_iface

provider/v2v_vmcheck_helper.py, v2v/tests/cfg/function_test_xen.cfg, v2v/tests/src/function_test_xen.py
Update code: Add error list to collect errors during checking vm to
make sure all checkpoints are checked. Call vmcheck object as param
to avoid create it again and again or create and close session.
Add cases:
- convert guest with display type 'vnc' and 'sdl'
- with attirb 'autoport' enable
- with scsi disk and ide disk, with 2 'program file' on win guest
- with empty or wrong environment LIBGUESTFS_BACKEND
- with a same name guest at destination
- with no passwordless SSH access configured on host
- with no regular kernel installed
- with input mode 'libvirtxml' without image file
=> Update code of function test on xen and add cases

libvirt/tests/src/svirt/dac_start_destroy.py
libvirt is using "-name guest=" in the qemu command line by default from libvirt version 1.3.5. Added a libvirt version check in the testcase.
Signed-off-by: Sudeesh John <sudheeshjohn@gmail.com>
=> dac_start_destroy: libvirt version check added

libvirt/tests/src/virsh_cmd/host/virsh_maxvcpus.py
This reverts commit 8dac28a5855c82d2221ebd5907f69deb55d496f4.
This patch is not complete:
1). The 'maxCpus' in capabilities XML only for kvm type domain.
2). And it needs a remote virsh instance for remote host testing.
3). This also break the test for old version libvirt.
=> Revert "Fixup: Changed maxvcpus value based on libvirt commit"

libvirt/tests/cfg/virsh_cmd/network/virsh_net_dhcp_leases.cfg, libvirt/tests/src/virsh_cmd/network/virsh_net_dhcp_leases.py
Remove interfaces outside the VM is not enough to update the virtnet
info. Actually, there's no need to remove all the interfaces before
testing , as we will also create a new network for the testing.
And if login VM by IP address failed, we should try serial and run
'dhclient' inside the VM to assign a new IP address for the NIC.
=> virsh_net_dhcp_leases: Don't remove the original interfaces

libvirt/tests/src/virsh_cmd/domain/virsh_attach_detach_disk.py
For config option, the expected change will be in the inactive XML.
Checking active XML will not be reliable here since it'll last for
a while for the XML to be changed.
=> virsh.attach_detach_disk: Check invalid XML for config option

libvirt/tests/src/libvirt_rng.py, libvirt/tests/src/virtual_disks/virtual_disks_multidisks.py, libvirt/tests/src/virtual_network/iface_hotplug.py, libvirt/tests/src/virtual_network/iface_network.py, libvirt/tests/src/virtual_network/iface_options.py, libvirt/tests/src/virtual_network/iface_ovs.py
This will make debugging the cause of failure more easier. We don't
have to go through the log to find out why the VM can't be started.
Also used some simpler logic to check status and changed some syntax
in except clause which will be work on both python 2&3.
=> Raise more clear error when VM can't be started

libvirt/tests/src/migration/migrate_vm.py
The fix will check the existence of the target pool on remote host
before creating it. If it already exists, we prefer to reusing it
instead of recreating.
=> migrate_vm: Check the pool existence

libvirt/tests/cfg/virsh_cmd/volume/virsh_vol_create_from.cfg
Older version of libvirt don't support --prealloc-metadata option. We'll
miss all qcow2 test cases when testing these version of libvirt. So the
best way to solve this is to split these cases.
=> virsh.vol_create_from: Split with/without prealloc

libvirt/tests/src/daemon/kill_qemu.py
10 sec waiting is not enough if the abrtd is configured and enabled. 
Increasing the timeout to 60 sec as a quick fix.
Signed-off-by: Sudeesh John <sudheeshjohn@gmail.com>
=> 10 sec waiting is not enough if the abrtd is configured and enabled.

libvirt/tests/cfg/virsh_cmd/domain/virsh_edit.cfg, libvirt/tests/src/virsh_cmd/domain/virsh_edit.py
1. Better way of handling topology and fixed the failure.
2. edit_error = "no" is the positive test case to test \<rng model='virtio'\>\<backend model='random' >/dev/urandom\</backend\>\</rng\> to be edited and saved.
=> Fixup virsh_edit

libvirt/tests/cfg/migration/migrate_vm.cfg, libvirt/tests/src/migration/migrate_vm.py
1. Use '--unsafe' option to avoid unsafe migration error when cache
!= none
2. Fix the raw disk should be migrated correctly with same size on
target host
3. Remove 'error.TestFail' usage
Signed-off-by: Dan Zheng dzheng@redhat.com
=> migrate_vm: multiple fixes for attached disks

libvirt/tests/src/numa/numad_vcpupin.py
Test vcpupin with only online host cpus, also as the bug is not
valid anymore, move it into error log and raise the command fail
error msg instead.
=> numad_vcpupin: only test pin vcpu to host online cpus

v2v/tests/cfg/specific_kvm.cfg, v2v/tests/src/specific_kvm.py
Including
- 2 of setting service firewalld start or stop on host
- 1 of checking service firewalld status before and after v2v
- 1 of removing securetty file on guest and convert it
- 2 of check time keeping after convertion
Modify case of converting win8 guest with unclean file system for
windows guests are mounted and define from an NFS storage to which
test process doesn't have the writing permission.Therefore, it would
not be possible to power up vm and power off to make unclean file
system.Instead, we'll prepare a vm and store it in the NFS storage.
=> Add v2v function cases

provider/v2v_vmcheck_helper.py, v2v/tests/src/specific_kvm.py
A virsh instance is needed in check_graphics function.Creating a
virsh persistent object inside the function seems not appropriate.
For the virsh persistent object will be destroied after the function
being called, which will close living virsh session and make future
call on the function not available.Therefore move the virsh instance
creation from check_graphics funciton to __init__ function.
=> Create virsh instance while initiate vmchecker object

libvirt/tests/src/virsh_cmd/domain/virsh_console.py
On some older systems like RHEL6, virsh.console test cases will fail
like:
TestFail: Expect shell terminated, but found Could not get exit
status of command ...
That's because on newer OS like RHEL7, 'shutdown -h now' will not exit
before machine shutdown. But on RHEL6, 'shutdown -h now' will exit and
allow user to execute another command. This next command will not
exit before machine shutdown.
This fix use cmd_output to replace cmd_status_output to avoid aexpect
to call "echo $?" and raise a different error. Instead of that. Call
"echo $?" after "shutdown -h now" to make this work on both newer and
older machines.
=> virsh.console: Shutdown may exit on older system

libvirt/tests/src/virsh_cmd/domain/virsh_domjobabort.py
Since it's not very reliable to remove file after checking this file
exists. It's possible that this file is removed between these two
lines. And this did happened.
=> virsh.domjobabort: Ask forgiveness than permission

v2v/tests/cfg/convert_from_file.cfg
Replace 'ova_vmdk_gz' by 'ova_vmdk_gz_zip'
=> Update cfg to make case name more accurate

libvirt/tests/cfg/npiv/npiv_nodedev_create_destroy.cfg, libvirt/tests/src/npiv/npiv_nodedev_create_destroy.py
Added npiv nodedev create/destroy test cases which covers following scenarios:
1.libvirt.npiv.nodedev_create_destroy.positive_testing.create_destroy_device
2.libvirt.npiv.nodedev_create_destroy.negative_testing.frequently_create_destroy_vhbas.fixed_wwnn
3.ibvirt.npiv.nodedev_create_destroy.negative_testing.frequently_create_destroy_vhbas.random_wwnn
4.libvirt.npiv.nodedev_create_destroy.negative_testing.create_max_vhbas
5.libvirt.npiv.nodedev_create_destroy.negative_testing.create_more_destroy_less
Based on #797 
Signed-off-by: Harish harisrir@linux.vnet.ibm.com
Signed-off-by: Yi Sun lentosun@163.com
=> Added npiv nodedev create/destroy test cases

libvirt/tests/src/virsh_cmd/domain/virsh_attach_device.py
Currently, test case maps disks attached to guest in same order
disk_VirtualDiskBasic_rcmM_0.raw -> vda, 1.raw -> vdb, 2.raw -> vdc
When guest starts, disks are attached in reverse order, i.e.
disk_VirtualDiskBasic_rcmM_2.raw may correspond to vda etc.
Test cases fails in this scenario. This patch fixes it.
Signed-off-by: Harish S <harisrir@linux.vnet.ibm.com>
=> Fixup: virsh_attach_device.py

v2v/tests/cfg/v2v_options.cfg, v2v/tests/src/v2v_options.py
And update cfg to move similar cases into same group
=> Add case:Remove reference info about --dcpath in virt-v2v manual page

libvirt/tests/src/virsh_cmd/domain/virsh_suspend.py
On old version libvirt(<1.0), when suspend a vm which name is '', the
command will fail without any error message output, but it's a really
low priority problem and the fix on new version will not backport, so
let it pass also.
=> Fix a no error messge condition

libvirt/tests/src/libvirt_rng.py
The operations need guest to collect enough random entropy to proceed.
Default timeout will be too short for it if testing machine is a
headless server that don't have too much noise source.
=> libvirt_rng: Extend timeout for RNG related guest operations

libvirt/tests/src/virsh_cmd/domain/virsh_change_media.py, libvirt/tests/src/virsh_cmd/domain/virsh_domiflist.py, libvirt/tests/src/virtual_network/iface_hotplug.py
For old version libvirt(RHEL6), these cases may fail as virsh command
not support specific option, so check them before run test and raise
TestSkipError if needed.
=> Check virsh command option before run test

libvirt/tests/src/virsh_cmd/monitor/virsh_domstate.py
The vm coredump name updated with start with number, update the
regex for 'ls' command, which also works on prior libvirt.
=> domstate: Fix coredump file path

libvirt/tests/src/libvirt_mem.py
It could be 1 for newer version of libvirt
=> libvirt_mem: DIMM for memory is not always zero

libvirt/tests/cfg/virsh_cmd/domain/virsh_resume.cfg, libvirt/tests/src/virsh_cmd/domain/virsh_resume.py
libvirt commit 3e044e6:
qemu, lxc: Raise error message when resuming running domain
fixed a bug: https://bugzilla.redhat.com/show_bug.cgi?id=1009008
So the test cases should be changed accordingly.
Another commit in this PR is to add a negative case testing
resuming a VM with read-only permission. 
=> virsh.resume: Resuming a running guest should be negative

libvirt/tests/src/virsh_cmd/domain/virsh_attach_device.py
attach_device returns empty list instead of True/False and test fails to FAIL. This patch fixes it.
=> attach_device: return True/False instead of list

libvirt/tests/cfg/virsh_cmd/domain/virsh_migrate.cfg, libvirt/tests/src/virsh_cmd/domain/virsh_migrate.py
virsh_migrate_desturi param can be set using API with existing param, instead declaring
in cfg
=> virsh.migrate: Update set virsh_migrate_desturi params

libvirt/tests/src/virsh_cmd/domain/virsh_attach_detach_disk_matrix.py, libvirt/tests/src/virsh_cmd/domain/virsh_attach_detach_interface_matrix.py, libvirt/tests/src/virsh_cmd/domain/virsh_attach_device_matrix.py
The after detach xml check ppc prone to fail base on machine
and arch, use wait_for for it in the check method with waiting
more time for it.
=> Adjust active xml detach check for matrix attach detach cases

libvirt/tests/src/migration/migrate_vm.py
The vda disk should be non-shared image when used by --migrate-disks,
otherwise the vda image data will be corrupted which may cause the VM
can not be logged in later.
=> migrate_vm: Fix a bug for --migrate-disks case

v2v/tests/src/convert_vm_to_libvirt.py
For a new bridge created for the v2v conversion, the old 'netdst' value
is outdated.In some cases it will cause connection failure of the
converted vm.Therefore update the netdst value with the new bridge.
=> Fix connection failure of converted vm by update netdst in params

libvirt/tests/cfg/virsh_cmd/host/virsh_uri.cfg, libvirt/tests/src/virsh_cmd/host/virsh_uri.py
1. change the target_uri get from param because complete_uri also call virsh uri, we can not use virsh to verify virsh
2. resolve the local uri execute issues, the previous change cause local execute disappear.
=> Fix uri test issues

libvirt/tests/src/migration/migrate_vm.py
This fix is to load stress tool on the host before migration with
stress on host.
=> migrate_vm: Load stress tool on host

v2v/tests/cfg/function_test_xen.cfg, v2v/tests/src/function_test_xen.py
Add cases of:
- unset env param of VIRTIO_WIN
- set VIRTIO_WIN to custom dir
- set VIRTIO_WIN dir to the mount point of virtio-win.iso
- set VIRTIO_WIN dir to path of file virtio-win.iso
- check md5 and sha1 of rhsrvany.exe
=> Add cases of loading virtio-win drivers from iso or custom dir

libvirt/tests/src/migration/migrate_vm.py
The old way sometimes will make the migration result unstable.
Simply sending SIGINT to the migration process can work in the fix.
=> Fix the way to cancel migration process

libvirt/tests/src/virsh_cmd/domain/virsh_attach_device.py
Get the index of the attaching disk based on existing disks of guest in VirtualDiskBasic class.
=> attach_device: Handle devidx based on guest disks

libvirt/tests/cfg/npiv/npiv_pool_regression.cfg, libvirt/tests/src/npiv/npiv_pool_regression.py
Added NPIV pool-regression test case. This test attaches lun of the wwpn pool to the guest and mounts and performs a dd operation on it before and after reboot.
Dependent on #868 and https://github.com/avocado-framework/avocado-vt/pull/702
Signed-off-by: Harish harisrir@linux.vnet.ibm.com
=> Added NPIV pool-regression test case

libvirt/tests/cfg/npiv/npiv_pool_vol.cfg, libvirt/tests/src/npiv/npiv_pool_vol.py
this PR depends on avocado-framework/avocado-vt#812 and https://github.com/avocado-framework/avocado-vt/pull/826
Test PASSED
Tested on x86 arch machine with 8 "Intel(R) Xeon(R) CPU E3-1265L v3 @ 2.50GHz" cpus
MemTotal: 16103372 kB
Physical HBA card is "Emulex Corporation Saturn-X: LightPulse Fibre Channel Host Adapter"
Tested with related packages:
kernel-3.10.0-514.el7.x86_64
libvirt-2.0.0-10.el7_3.2.x86_64
qemu-kvm-rhev-2.6.0-27.el7.x86_64
[root@bootp-73-75-161 npiv]# avocado run --vt-type libvirt type_specific.lento.npiv.pool_vol.positive_test
JOB ID     : 86d49696a77b8220cc3f0ee565e138d7ff558261
JOB LOG    : /root/avocado/job-results/job-2016-11-29T18.27-86d4969/job.log
TESTS      : 2
(1/2) type_specific.lento.npiv.pool_vol.positive_test.from_pre_def_pool.scsi_pool: PASS (29.21 s) …
=> Add script to cover npiv pool and volume related checkpoints

libvirt/tests/cfg/libvirt_mem.cfg
Guest is now able to boot without numa, moving it as a positive test case in libvirt_mem.cfg
Signed-off-by: Harish harisrir@linux.vnet.ibm.com
=> libvirt_mem: Add without_numa as positive test

libvirt/tests/cfg/virsh_cmd/domain/virsh_resume.cfg
virsh resume of running domain will returns 0, so it should be
in normal_test variant.
=> Fix virsh_resume

libvirt/tests/cfg/virsh_cmd/domain/virsh_migrate_stress.cfg, libvirt/tests/src/virsh_cmd/domain/virsh_migrate_stress.py
Tests got failed as migration of nfs shared storage vms without
configuring nfs in the remote machine. This patch fixes it
=> virsh_migrate_stress: enabled setup nfs in remote machine

libvirt/tests/src/virt_cmd/virt_top.py
This patch enables the test-case to install the "virt-top" package, before test-case execution.
It's ideal to initially check for the package installed and later the command present, before execution.
=> virt_top.py: Added option to install "virt-top" package, if missing.

libvirt/tests/src/virsh_cmd/domain/virsh_vncdisplay.py
To deal with the situation that the guest do not support cirrus graphic device and the xml can be recovered
=> Mov "Try" to upper place

libvirt/tests/cfg/conf_file/libvirtd_conf/unix_sock.cfg, libvirt/tests/src/conf_file/libvirtd_conf/unix_sock.py
In Ubuntu there is no group called "nobody", "nogroup" instead.
Signed-off-by: Sudeesh John <sudeesh@linux.vnet.ibm.com>
=> In Ubuntu there is no group called "nobody", "nogroup" instead.

libvirt/tests/cfg/virsh_cmd/domain/virsh_resume.cfg
libvirt commit 3e044e6e fix the running VM can resume issue, so
we can't do it anymore.
=> virsh.resume: Now resume running VM is invalid

libvirt/tests/cfg/virtual_disks/virtual_disks_multidisks.cfg, libvirt/tests/src/virtual_disks/virtual_disks_multidisks.py
IOThreads are properly validated while a domain is defined, so for
these 3 negative cases, define VM fail is expected.
=> virtual_disks_multidisks: Add a new expected condition

libvirt/tests/cfg/virtual_disks/virtual_disks_multidisks.cfg
Previous ioeventfd cases combined with without_controller_model failed
So need filter them out
=> Ioeventfd is only supported by virtio-scsi controller

libvirt/tests/src/virsh_cmd/domain/virsh_migrate_copy_storage.py
The fix will check the existence of the target pool on remote host
before creating it. If it already exists, we prefer to reusing it
instead of recreating.
=> virsh_migrate_copy_storage: Check the pool firstly

libvirt/tests/src/virtual_disks/virtual_disks_multivms.py
vms_list is used to released resouces in finally block,and
sometimes create_scsi_disk failure leads to enter finally block
before vms_list is initialized
=> Fixed local variable 'vms_list' referenced before assignment issue

libvirt/tests/src/virsh_cmd/domain/virsh_migrate_multi_vms.py
using rsa_key to configure passwordless ssh with remote host
for migration
=> virsh_migrate_multi_vms: configure ssh_key in remote host

libvirt/tests/cfg/virtual_disks/virtual_disks_iscsi.cfg, libvirt/tests/src/virtual_disks/virtual_disks_iscsi.py
After Virtio 1.0 is enabled,virtio-scci config need to
be used for lun device instead of virtio
Details refer to https://bugzilla.redhat.com/show_bug.cgi?id=1365823
=> Enable virtio-scsi config on lun device

libvirt/tests/cfg/virtual_disks/virtual_disks_ceph.cfg, libvirt/tests/src/virtual_disks/virtual_disks_ceph.py
Internal snapshot doesn't support raw disk format
=> Filter out raw format internal snapshot cases

libvirt/tests/cfg/migration/migrate_vm.cfg, libvirt/tests/cfg/virsh_cmd/domain/virsh_migrate.cfg, libvirt/tests/cfg/virsh_cmd/domain/virsh_migrate_setmaxdowntime.cfg, libvirt/tests/src/migration/migrate_vm.py, libvirt/tests/src/virsh_cmd/domain/virsh_migrate.py, libvirt/tests/src/virsh_cmd/domain/virsh_migrate_setmaxdowntime.py
Using --postcopy option when migration should not impact the migration
result. This is to enable this option for most existing migration cases.
=> Enable --postcopy options for migration cases

libvirt/tests/cfg/migration/migrate_vm.cfg
There are some differences between RHEL7.3 and RHEL7.4 in qemu command
line when setting write-bytes-sec, read-bytes-sec, total-bytes-sec and
total-iops-sec.
Take total-iops-sec for example:
RHEL7.3: qemu command line: iops=1000
RHEL7.4: qemu command line: iops-total=1000
So the fixes are to adjust the grep string to meet both scenarios.
=> migrate_vm: Update the grep string

libvirt/tests/cfg/virsh_cmd/domain/virsh_migrate.cfg, libvirt/tests/src/virsh_cmd/domain/virsh_migrate.py
This patch adds test scenarios to test migration with CPU Hotplug
and Hotunplug. It covers live, online, there and back, postcopy migration
with different configurations of Numa, Numa pinning, Hugepage, Hugepage pinning,
memory hotplug and default without any of above with following cases,
1. CPU Hotplug before migration
2. CPU Hotplug after migration
3. CPU Hotplug & Hotunplug before migration
4. CPU Hotplug & Hotunplug after migration
5. CPU Hotplug before and Hotunplug after migration
6. CPU Hotplug & Hotunplug before and Hotplug & Hotunplug after migration
=> virsh.migrate: Perform cpu hotplug/hotunplug with migration

libvirt/tests/cfg/virsh_cmd/volume/virsh_vol_create.cfg, libvirt/tests/src/virsh_cmd/volume/virsh_vol_create.py
sign-off by: Yi Sun (lentosun@163.com)
Test on x86_64 with libvirt-3.1.0-2.el7.x86_64, passed 
root@localhost # avocado run --vt-type libvirt type_specific.lento.virsh.vol_create.positive_test.fs_like_pool.vol_format.v_raw_luks..
JOB ID     : c5b8734a4655327122916c7b72761c0bfb741931
JOB LOG    : /root/avocado/job-results/job-2017-03-14T13.53-c5b8734/job.log
TESTS      : 4
(1/4) type_specific.lento.virsh.vol_create.positive_test.fs_like_pool.vol_format.v_raw_luks.src_pool_type.dir.non_acl: PASS (6.75 s)
(2/4) type_specific.lento.virsh.vol_create.positive_test.fs_like_pool.vol_format.v_raw_luks.src_pool_type.dir.acl_test: /PolicyKit daemon disconnected from the bus.
We are no longer a registered authentication agent.
PASS (8.97 s)
(3/4) …
=> Add case to cover vol-create for luks encrypted volume

libvirt/tests/src/virsh_cmd/domain/virsh_migrate.py
If host numa doesn't have enough memory to guest, then skip to use other
numa node to avoid test failure.
=> virsh_migrate: avoid guest to pin its numa with host numa having low memory

libvirt/tests/cfg/virtual_disks/virtual_disks_gluster.cfg, libvirt/tests/src/virtual_disks/virtual_disks_gluster.py
As per bugzilla bug:https://bugzilla.redhat.com/show_bug.cgi?id=1247521
gluster volumes support multiple volume hosts
=> Add cases to cover support multiple volume hosts for gluster volumes

libvirt/tests/cfg/virsh_cmd/monitor/virsh_domstats.cfg, libvirt/tests/src/virsh_cmd/monitor/virsh_domstats.py
list of vms can be defaulted from existing param vms for all_domains and
param main_vm can be used for specific domain, use test.fail(),
test.error() and test.cancel() instead of using error from autotest.
=> virsh_domstats: default vms and main_vm can be used for vm_list

libvirt/tests/src/virsh_cmd/domain/virsh_migrate.py
using remote virsh instance to new_from_dumpxml() for retrieving the
guest xml from remote machine
=> virsh_migrate: virsh instance for dumpxml of guest in remote machine

libvirt/tests/src/libvirt_mem.py
Fix the memory detach assertion after restore, the check need use
new_max_mem rather than original max_mem to minus detached memory.
=> libvirt_mem: Fix memory assertion for detach

libvirt/tests/cfg/virsh_cmd/domain/virsh_cpu_compare.cfg, libvirt/tests/src/virsh_cmd/domain/virsh_cpu_compare.py
1. Skipped unsupported tests
2. Addressed failing CPU compatibility model for ppc64le
3. Removed autotest dependency for assertion.
=> Fixup ppc64le tests and assertion refactor

libvirt/tests/cfg/virsh_cmd/domain/virsh_migrate.cfg, libvirt/tests/src/virsh_cmd/domain/virsh_migrate.py
The purpose of this patch is to make sure '--postcopy' option will not impact other existing test cases. The exising test cases should have same behavior as before even though with '--postcopy'.
=> Recover postcopy option for all migration

libvirt/tests/cfg/virtual_disks/virtual_disks_encryption.cfg
Multiple same name cases are generated for this case, while total
cases should be 3.
Need avoid use 'qcow2' and 'raw' as case name as they are disk type
also used in avocado-vt cfg files, which cause cartesian problem.
=> virtual_disks_encryption: Adjust cfg to avoid duplicate generation

libvirt/tests/cfg/virsh_cmd/domain/virsh_migrate.cfg
Replace '-' with '_' for one case name.
=> virsh.migrate: fix case name

libvirt/tests/cfg/libvirt_vcpu_plug_unplug.cfg, libvirt/tests/src/libvirt_vcpu_plug_unplug.py
1. Added topology support
2. Skipped power management tests for power
3. Changed cpus count method to make it work in all platforms 
Earlier, it was failing if the guest has topology
definition.
=> Added topology support, removed few tests for ppc64le

libvirt/tests/src/virtual_disks/virtual_disks_gluster.py
Need wrap transport attribute into host instead of standalone attribute
=> Fix transport tcp failure in gluster disk

libvirt/tests/cfg/virsh_cmd/domain/virsh_sendkey.cfg, libvirt/tests/src/virsh_cmd/domain/virsh_sendkey.py
tty[1] fails to grep available tty and test specific to Linux, Windows are
filtered out.
=> virsh_sendkey: regex to grep tty console errors for available tty

libvirt/tests/cfg/virsh_cmd/domain/virsh_blockcopy.cfg
Negative tests for https://bugzilla.redhat.com/show_bug.cgi?id=1300177
=> Add cases: Forbid using relative path on blockcopy

libvirt/tests/src/virsh_cmd/domain/virsh_migrate.py
set_vm_vcpus() is a static method of class VMXML. So this is to fix the
incorrect usage.
=> virsh.migrate: Fix incorrect usage of one function

libvirt/tests/src/resource_abnormal.py, libvirt/tests/src/virtual_disks/virtual_disks_encryption.py, libvirt/tests/src/virtual_disks/virtual_disks_multidisks.py, libvirt/tests/src/virtual_disks/virtual_disks_multivms.py
Address issue:CmdError: Command 'parted -s /dev/sdb print' failed (rc=1)&#10;
Jira link:https://projects.engineering.redhat.com/browse/LIBVIRTAT-1341
=> Fix parted disk error without mklabel

libvirt/tests/cfg/virsh_cmd/domain/virsh_domdisplay.cfg
filtered spice graphic test cases for ppc64le
=> virsh_domdisplay: spice graphic is not supported by ppc64le

libvirt/tests/cfg/virtual_disks/virtual_disks_encryption.cfg, libvirt/tests/src/virtual_disks/virtual_disks_encryption.py
1. in virtual_disks_encryption.cfg:
- change qcow2_t to qcow2_internal
- change raw_t to raw_luks
which will better describe the case content in a test run
- add qcow2_internal under error_test
RAW with LUKS encrypted img can be used by VM even if we
do not provide a <encryption> in xml, VM will just use it
as RAW file and a mkfs will erase all LUKS header
- add hotplug=yes/no cases
2. in virtual_disks_encryption.py
- add hotplug/unplug steps for luks/qcow2 virtual disk
sign-offed by: Yi Sun (yisun@redhat.com)
=> Add cases for LUKS img hotplug/unplug

.travis.yml
Sphinx 1.4.9 is the last version that supports Python 2.6.
=> travis: lockdown Sphinx version for python2.6

libvirt/tests/src/virsh_cmd/domain/virsh_migrate.py
Incorrect logic causes '--postcopy' is not inserted into the migration
options for '--postcopy_after_precopy'
=> virsh.migrate: Fix the postcopy option

libvirt/tests/cfg/graphics/graphics_functional.cfg, libvirt/tests/src/graphics/graphics_functional.py
For new version libvirt, there are some changes, so update test case
to adapt them:
1. A new listen type 'none' is added. When no port given and autoport is
'no', libvirt will add listen type='none' automatically, so these two
autoport='no' and insecure mode/channel spice cases are valid now.
2. Now spice port accept negative number less than -1, If spice port
less than -1, the VM can start normally, but both listen address and port
will be omitted when pass to qemu.
3. Some error messages and vnc socket path also changed, so add new
match patterns and change two boolean values to string type to use
re.match for result compare.
Signed-off-by: Yanbing Du ydu@redhat.com
=> graphics_functional: Case update for some new changes

libvirt/tests/cfg/virtual_disks/virtual_disks_multidisks.cfg, libvirt/tests/src/virtual_disks/virtual_disks_multidisks.py
If cold plug,attach expect succeed,but throw error:Found duplicate drive address for disk
when redefine VM.
On the other hand, if hot plug,attach expect fail with error:internal error:
unable to execute QEMU command '__com.redhat_drive_add': Duplicate ID '
Details refer bug:https://bugzilla.redhat.com/show_bug.cgi?id=1036715
=> Add disk with duplicate controller index

libvirt/tests/src/virtual_disks/virtual_disks_encryption.py
It need mklabel in Vm internal instead of host.
=> Fixed mklabel issue in luks encryption cases

libvirt/tests/cfg/virtual_disks/virtual_disks_multidisks.cfg, libvirt/tests/src/virtual_disks/virtual_disks_multidisks.py
If update cdrom or floppy with different boot order value,
it expect fail,details see:https://bugzilla.redhat.com/show_bug.cgi?id=1007228
=> add cdrom and floppy update boot order case

libvirt/tests/cfg/daemon/crash_regression.cfg, libvirt/tests/src/daemon/crash_regression.py
This PR depends on https://github.com/autotest/virt-test/pull/1948 and https://github.com/autotest/virt-test/pull/1947
This test runs various regression tests and check whether libvirt
daemon crashes.
Signed-off-by: Hao Liu hliu@redhat.com
=> Add test for libvirtd crash regression bugs

libvirt/tests/src/migration/migrate_vm.py
=> migrate_vm: Fix a syntax error

libvirt/tests/cfg/virtual_disks/virtual_disks_ceph.cfg
since rbd disk with snapshot need set readonly attribute explicitly
=> Fix the issue that Vm failed to be started

libvirt/tests/cfg/virtual_disks/virtual_disks_multidisks.cfg
IDE disk can not always be placed before virtio/scsi disks
=> Add case to validate bugzilla bug:521053

libvirt/tests/cfg/virtual_disks/virtual_disks_multidisks.cfg, libvirt/tests/src/virtual_disks/virtual_disks_multidisks.py
This is used to validate bugzilla:1046267 issue where
address attribute need to be fit in automatically after
usb disk plug in.
=> Add usb disk auto fit address attribute case

libvirt/tests/src/virsh_cmd/domain/virsh_domblkerror.py
In finally block, nfs_service may be one None object,and add
None check before start
=> Fix local variable 'nfs_service' referenced before assignment

libvirt/tests/src/virtual_network/iface_options.py
The original prompt is inaccurate which causes the log on guest failure.
This is to make the prompt more accurate.
=> iface_options: Fix inaccurate prompt

libvirt/tests/cfg/virsh_cmd/domain/virsh_event.cfg, libvirt/tests/src/virsh_cmd/domain/virsh_event.py
Before this fix, getting all the vms will cause some events belonging
to the second vm been not tracked, as virsh event is one-shot by
default. Hence, errors will be reported when get all the vms.
Thus submit a patch to fix it.
=> Get only 1 vm for the virsh event cases, unless otherwise noted

libvirt/tests/src/conf_file/qemu_conf/set_virtlogd.py
In test environment,beside avocado-vt-vm1
some annoyed VMs may be there too.
=> Fix annoyed VMs disturbing issue

libvirt/tests/cfg/virsh_cmd/domain/virsh_blockcopy.cfg, libvirt/tests/src/virsh_cmd/domain/virsh_blockcopy.py
Since patches of https://bugzilla.redhat.com/show_bug.cgi?id=1300177
were merger after 3.0.0. Add skip codes for 3.0.0 lower libvirt.
=> Skip blockcopy relative path for libvirt < 3.0.0

libvirt/tests/src/virtual_disks/virtual_disks_multidisks.py
The default timeout for session cmd is 60 which might not enough
for dracut command to finish. As --force is used, it will
overwrite initramfs image and corrupt the vm if failed, so set
the timeout longer to avoid such corruption.
=> virtual_disks_multidisks: Fix dracut timeout corrupt vm problem

libvirt/tests/src/virsh_cmd/volume/virsh_volume_application.py
The default format of the created volume is 'raw', but attach_disk will
treat it as qcow2 image as default. That will cause the guest can not
recognize this disk. So the fix is to specify the disk format when
attaching it.
=> virsh_volume_application: Fix the image format

libvirt/tests/src/virsh_cmd/volume/virsh_vol_create_from.py
qemu-img refuses creating a volume's device less than 8M on PPC, 4M on
X86. So the fix is to adjust the image size to fit for both PPC and X86.
=> virsh_vol_create_from: Fix image size for qemu-img

libvirt/tests/cfg/vm_boot_with_kernel_param.cfg, libvirt/tests/src/vm_boot_with_kernel_param.py
1. edit_kernel_param_only can be used to change the kernel param
inside the guest image and proceed with other tests, similar to
guest_import for exercising the testcase with different kernel param options
for all archs
- add_kernel_param: adds the kernel param and reboots the guest
- remove_kernel_param: removes the kernel param and reboots the guest
2. Added testcases for bringing up POWER9 guest in radix or hpt MMU based on
the kernel param for PowerPC arch.
=> Booting guest with kernel param testcase

libvirt/tests/src/libvirt_hooks.py
The managedsave image used to exist after test finished, which may
affect test result of the next cases. Therefore, add clean up step
to remove the image.
=> Clean up managedsave img after test finished

v2v/tests/src/convert_vm_to_libvirt.py, v2v/tests/src/convert_vm_to_ovirt.py
Since the bug is fixed, this workaround no longer needs to cover
all hypervisors, only xen still needs it.
=> Only set LIBGUESTFS_BACKEND for xen

libvirt/tests/cfg/virsh_cmd/domain/virsh_qemu_agent_command_fs.cfg, libvirt/tests/src/virsh_cmd/domain/virsh_qemu_agent_command_fs.py
Fix by change to using another disk instead of local disk to do cp operation to generate
dirty memory which may cause guest hang and agent command have no response. Also remove
the redundant sleep as it may deal with in get_dirty func. Also the tmp_file removed from cfg file as it need to in /mnt dir and no need to do configure in cfg
=> Fix qemu_agent_comand_fs fsfreeze failure issues

libvirt/tests/src/virsh_cmd/domain/virsh_domxml_to_native.py
libvirt will detect qemu support cpu during start guest,
so the cpu flags in domxml-to-native output won't equal
the real qemu command cpu flags
Signed-off-by: root <yanqzhan@redhat.com>
=> XMLToNative: Don't compare -cpu

libvirt/tests/src/virsh_cmd/domain/virsh_attach_detach_disk_matrix.py
Adjust the sleep time for the VM to be stabe after detaching disk on
PPC.
=> virsh_attach_detach_disk_matrix: Fix sleep time

libvirt/tests/src/virsh_cmd/domain/virsh_attach_detach_interface_matrix.py
Adjust the sleep time for the VM to be stable after detaching the
interface on PPC.
=> virsh_attach_detach_interface_matrix: Fix wait time

libvirt/tests/src/virsh_cmd/domain/virsh_dumpxml.py
When the host is AMD vendor , the guest default vendor is "intel",
but virsh dumpxml rhel7 --update-cpu can not change the
<vendor>Intel</vendor> part, the vendor has conflicts with cpu features.
So delete the <vendor> part.
Signed-off-by: jishao <jishao@redhat.com>
=> virsh_dumpxml: remove vender check

libvirt/tests/src/svirt/dac_nfs_disk.py, libvirt/tests/src/svirt/dac_start_destroy.py, libvirt/tests/src/svirt/dac_vm_per_image_start.py
In Ubuntu SELinux is not working at the moment.
So Skipping testcases which needs the SELinux to be in
Enforcing mode. This patch will skip(insted of ERRORing out)
the the testcase if SELinux is disabled.
Signed-off-by: Sudeesh John sudeesh@linux.vnet.ibm.com
=> Enabling SELinux mode check

libvirt/tests/src/svirt/svirt_install.py
Check the domain status after svirt-install completed to avoid the possibilies 
that 'virsh domstate' will get the paused status while virt-install executing 
even if virt-install failed.
=> Check the domain status after svirt-install completed

libvirt/tests/src/svirt/dac_nfs_disk.py
the nfs path used for pool preparation is not the one as for exportfs. So 'access denied' is reported while mounting nfs server. Fix by change the path to be unified.
Sign-off-by: Yan Li <yannli@redhat.com>
=> dac_nfs_disk: Fix the issue that failed to create nfs pool

libvirt/tests/src/virtual_network/iface_network.py
This issue is caused by process.system which has two cmds in one line.
After add shell=True, this issue resolved.
=> iface_network.py: Fix "cp" CmdError

libvirt/tests/cfg/virsh_cmd/host/virsh_freepages.cfg
set hugepage_force_allocate = "yes" to avoid error in calculating
and allocating when Hugepagesize is 2048 kB which is common for p9
hosts
=> virsh_freepages:force allocate hugepage

libvirt/tests/src/virtual_disks/virtual_disks_multidisks.py
this judgement error always set disk.readonly to True, which blocks the snapshot creation.
=> fix a conditional judgement error

libvirt/tests/src/virtual_network/iface_hotplug.py
resolve problem:  polltime = time.time() + poll_timeout
TypeError: unsupported operand type(s) for +: 'float' and 'str'
=> fix iface_hotplug failure

libvirt/tests/src/virtual_disks/virtual_disks_ceph.py
make sure the cloned VM is running before attaching a disk, this change only affects `disk_shareable` test.
=> make sure the additional vm is running

libvirt/tests/src/virsh_cmd/domain/virsh_dump.py
Use SIGKILL to avoid the following failure:
SystemExit: Test interrupted by SIGTERM
=> virsh_dump: Use SIGKILL to terminate the forked process

libvirt/tests/src/virsh_cmd/domain/virsh_domblkerror.py
nfs mount point could not be unmounted for not all necessary params
are provided including export_dir and mount_dir.
=> virsh_domblkerror:add params for cleanup step

libvirt/tests/src/virtual_disks/virtual_disks_ceph.py
fix a minor mistake in libvirt/tests/src/virtual_disks/virtual_disks_ceph.py
=> virtual_disks_ceph: fix snapshot xml

libvirt/tests/cfg/libvirt_mem.cfg
when libvirt mem testing with hugepages, it shall not use the system available memory to set hugepages. Otherwise vm may fail to start because the target mem can't allocate  
=> Fix mem allocate failure

libvirt/tests/src/virsh_cmd/domain/virsh_qemu_agent_command.py
When with no guest agent, wait_for_login shall not be performed.
=> qemu_agent_command: fix no_ga issue

libvirt/tests/cfg/resource_abnormal.cfg, libvirt/tests/src/resource_abnormal.py
One case tests for save/domstats/blkdeviotune operations when
VM's nfs storage disconnected.
Signed-off-by: hhan <hhan@redhat.com>
=> Add cases for VM operations when nfs disconnected

libvirt/tests/cfg/npiv/npiv_concurrent.cfg, libvirt/tests/src/npiv/npiv_concurrent.py
2 VMs has 2 different luns which is connected by 2 vhbas.
Concurrently create files in 2 VMs and check the files created
correctly without vhba errors.
Signed-off by: Yi Sun (lentosun@163.com)
depend on: https://github.com/avocado-framework/avocado-vt/pull/826
=> Add script to cover concurrent vms' operations over vhbas

libvirt/tests/src/virsh_cmd/domain/virsh_migrate.py
The nfs export dir needs to be kept after test.
=> virsh_migrate: Forcely keep nfs export dir

libvirt/tests/src/virsh_cmd/domain/virsh_vcpupin.py
1. Fix the difference due to the migration from virttest to avocado-vt
The function returned a string list in virttest, but it return an  int list after migration
2. Fix the max online cpu for PPC
=> Update code for vcpupin case

libvirt/tests/cfg/virsh_cmd/domain/virsh_migrate.cfg, libvirt/tests/src/virsh_cmd/domain/virsh_migrate.py
Some cases need migration process to turn slow down in order to get
sufficient time to handle special matters. So one way is to load stress
within the VM.
=> virsh.migrate: Load stress in VM

libvirt/tests/src/virtual_disks/virtual_disks_ceph.py
this change affects the following 4 tests:
```
virtual_disks.ceph.hot_plug.with_auth.disk_attach.json_pseudo_protocol
virtual_disks.ceph.hot_plug.without_auth.disk_attach.json_pseudo_protocol
virtual_disks.ceph.cold_plug.with_auth.disk_attach.json_pseudo_protocol
virtual_disks.ceph.cold_plug.without_auth.disk_attach.json_pseudo_protocol
```
I checked them, all passed on my local machine.
=> pass different json string according to the auth config

libvirt/tests/src/virsh_cmd/domain/virsh_setvcpus.py
=> virsh_setvcpus: fix local variable 'result' referenced before assignment

libvirt/tests/cfg/virsh_cmd/domain/virsh_sendkey.cfg
Since the 'virsh send-key' send all the keys simulataneously, so the
string contains the same keys will have the possibility that the key
only received one time by the guest.
=> Modify the keycode 'touch abc\n' to 'touch ab\n'

libvirt/tests/src/svirt/dac_start_destroy.py
Since the guest failed to start as expected when the seclabel having
no access to the image, so mark the cases pass.
=> Don't skip the case with seclabel having no access to the image

libvirt/tests/cfg/virsh_cmd/host/virsh_uri.cfg
Remove remote_ip/remote_user/remote_pwd params from virsh_uri.cfg.
Use remote_ip/remote_user/remote_pwd params in base.cfg.
=> virsh_uri: Remove remote_ip parameter from virsh_uri.cfg

libvirt/tests/src/virsh_cmd/domain/virsh_numatune.py
There is a possibility of online numa nodes without memory
and it is expected to fail, this patch skips those nodes
being used.
=> Fixup: Handle systems with empty memory numanodes

libvirt/tests/cfg/virtual_disks/at_dt_iscsi_disk.cfg
Virtio1.0 bus disk do not working well with
"disk_device = lun" settings, it's one know issue,
see BZ1365823 for reference. The scenario of updated cfg
is mainly testing hotplug/unplug ipv6 protocal iscsi
network backend disk, no need to specify one special
disk_device. So, remove "disk_device = lun", and use
the general default disk_device value "disk".
Signed-off-by: Xuesong Zhang <xuesong.zhang1986@gmail.com>
=> Update disk_device to disk for virtio disk scenario

libvirt/tests/src/virsh_cmd/domain/virsh_domblkerror.py
When stop nfs on host, it is expected guest could be paused
automatically. But this sometimes doesn't work, since seemingly
vm can't detect the nfs status timely. Fix by add one more write
to the vm mnt disk if vm is not paused so that vm can know the 
nfs has gone.
=> virsh.domblkerror: fix guest not paused after nfs stop

libvirt/tests/src/virtual_disks/at_dt_iscsi_disk.py, libvirt/tests/src/virtual_disks/virtual_disks_encryption.py, libvirt/tests/src/virtual_disks/virtual_disks_multidisks.py
Add the sleep time for the VM to recognize the attached disk on PPC.
=> virtual_disks: Add wait time for PPC

libvirt/tests/src/smt.py
Moved xml backup method before vm login
as it can errorout during vm login causing below issue
L0797 ERROR| UnboundLocalError: local variable 'org_xml' referenced before assignment
=> Fixup: Move xml backup method before vm login

libvirt/tests/src/remote_access/remote_access.py
The VM should be shutdown after all tests are done. Otherwise running vm
will cause following cases to fail.
=> remote_access: Destroy VM after tests

libvirt/tests/cfg/remote_access/remote_with_ssh.cfg, libvirt/tests/cfg/remote_access/remote_with_tcp.cfg, libvirt/tests/cfg/remote_access/remote_with_tls.cfg, libvirt/tests/cfg/remote_access/remote_with_unix.cfg, libvirt/tests/src/remote_access/remote_access.py
In configuration, vms = "" will cause env.get_vm to return zero vms.
=> remote_access: correct configuration to get vm

libvirt/tests/src/migration/migrate_vm.py
"Expected Downtime" is newly added in domjobinfo on source host for
migration and "Total Downtime" for target host, too. Currently we do not
need to compare this two fields. So they are skipped for comparison.
=> migrate_vm: skip to compare 'expected downtime'

libvirt/tests/src/migration/migrate_vm.py
This is a new fix for tp-libvirt pr 1243.
"Expected Downtime" is newly added in domjobinfo on source host for
migration and "Total Downtime" for target host, too. Currently we do not
need to compare this two fields. So they are skipped for comparison.
=> migrate_vm: fix to not compare 'expected downtime'

libvirt/tests/cfg/virtual_disks/virtual_disks_multidisks.cfg
Boot disk couldn't be set readonly
=> Fix virtual_disk_multidisks case

libvirt/tests/cfg/virsh_cmd/volume/virsh_vol_resize.cfg
To trigger no_space_allocation, it shall set the new vol capacity
by using the pool capacity, rather than some hard coding in cfg file.
The old way can fail the case too, but for "invalid argument" not for 
"no space left". 
=> virsh_vol_resize: Correct the configuration for no_space_allocation

libvirt/tests/cfg/libvirt_vcpu_plug_unplug.cfg, libvirt/tests/src/libvirt_vcpu_plug_unplug.py
Add hot(un)plug tests with following scenarios
1. save/restore with hotunplug
2. managedsave/restore with hotunplug
3. suspend/resume with hot(un)plug.
=> Add more scenarios with cpu hot(un)plug

libvirt/tests/src/virsh_cmd/domain/virsh_migrate.py
Old exceptions catching can not catch the exception objects, like
TestCancel, TestFail. So this is to fix it.
=> virsh_migrate: Fix the incorrect exception

libvirt/tests/cfg/cpu/guestpin.cfg, libvirt/tests/src/cpu/guestpin.py
Add guest vcpu thread and emulator thread affinity
to host cpu with multiple combinations like
i) save/restore
ii) suspend/resume
iii) stress inside guest
iv) host cpu hotplug(smt changes- ppc only)
v) guest cpu hotplug
vi) multiple iterations
=> Add guest cpu affinity tests with different scenarios

libvirt/tests/src/graphics/graphics_functional.py
Before libvirt version 3.1.0, the valid VNC port is
[5900, 65535] and -1, the VNC port will be assigned one
valid port number automatically if set to -1.
Since libvirt version 3.1.0, -1 is removed from the valid
port number, it means VM will failed to be started if VNC
port number is -1.
Cancel the test for VNC port = -1 if libvirt version large
than 3.1.0, since there is already one negative test for
VNC port = -2, the test for -1 and -2 are equivalence class
Signed-off-by: Xuesong Zhang <xuesong.zhang1986@gmail.com>
=> [v2 1/1] graphics_functional: Cancel the test for VNC port = -1

libvirt/tests/cfg/virsh_cmd/domain/virsh_dompmsuspend.cfg, libvirt/tests/src/virsh_cmd/domain/virsh_dompmsuspend.py
In x86 pm tags of guest xml is to enable support for (suspend-to-mem) and
S4 (suspend-to-disk) ACPI sleep states, but it is not supported and pm tags
in guest xml are not required for PowerPC.
=> virsh_dompmsuspend: PowerPC doesn't support ACPI sleep states

libvirt/tests/src/virsh_cmd/monitor/virsh_list.py
Ip check only used for 'remote' scenarios, remove the head extra
ip check since one already exists in later lines.
=> Remove extra ip check for virsh list tests.

v2v/tests/src/convert_vm_to_libvirt.py
Qemu-kvm package not support win2016 better,so modify win2016's cpu
to 'host-modle'
Signed-off-by: Kun Wei <kuwei@redhat.com>
=> Set cpu mode to 'host-modle' for win2016.

libvirt/tests/cfg/virsh_cmd/domain/virsh_sendkey.cfg, libvirt/tests/src/virsh_cmd/domain/virsh_sendkey.py
Test fails when keystrokes are sent in a shot it gets missed or received in
random order, provision is given for multiple invocations to avoid the failures
param sendkey_simultaneous can be set to "no" to invoke each keystroke separately
and can be set to "yes" if all the keystrokes to be invoked at a time.
with_holdtime: holdtime with keystrokes will emulate keys in different count
for the milliseconds eachtime and will create filename with different name,
we can't validate the filename when keys are pressed with holdtime milliseconds
as it is not persistent
=> virsh_sendkey: keystrokes get missed if all of them are sent simultaneously

libvirt/tests/cfg/virsh_cmd/domain/virsh_dump.cfg, libvirt/tests/src/virsh_cmd/domain/virsh_dump.py
The original way of forking a new process is quite confusing and
won't give fail reason when it comes as bypass cache fail.Therefore
replace it with multiprocessing which is much clearer and will
throw out the correct errors.
=> Replace os.fork with multiprocessing for background bypass check

libvirt/tests/src/numa/numad_vcpupin.py
Instead of setting a fixed value of '0-1', we choose 2 from the
online nodes: the max and the minium. For numa node is not
continuous on power hosts.
=> Update nodeset for numad test

libvirt/tests/cfg/virsh_cmd/domain/virsh_blockcopy.cfg
Blockcopy with 1M/s could not be completed within 1200s
=> Update blockcopy timeout

provider/v2v_vmcheck_helper.py
In case got in-accurate test result if drivers not fully installed
yet.
Sleep 60 seconds during each check.
Log the failure if still couldn't find driver after checks run out.
=> Check multiple times for windows guests drivers after conversion

libvirt/tests/cfg/virsh_cmd/nodedev/virsh_nodedev_dumpxml.cfg, libvirt/tests/cfg/virsh_cmd/nodedev/virsh_nodedev_reset.cfg, libvirt/tests/src/virsh_cmd/nodedev/virsh_nodedev_dumpxml.py, libvirt/tests/src/virsh_cmd/nodedev/virsh_nodedev_reset.py
For different hosts have different devices, device address is not the
same one written in cfg, this patch can  get the device_name from the host on testing not from the cfg.
=> Dump/reset  the specific nodedevice from different host

libvirt/tests/src/virsh_cmd/domain/virsh_migrate_setmaxdowntime.py
The nfs export dir needs to be kept after test.
=> virsh_migrate_setmaxdowntime: Keep nfs export dir

v2v/tests/src/convert_vm_to_ovirt.py
Since there's an unresolved issue for v2v conversion.
=> Set LIBGUESTFS_BACKEND=direct for kvm guests

libvirt/tests/src/storage_discard.py
existing test case ported to avocado from auto test. but miss the port import statement. in auto test lv_list() expected an argument and lv_list_all() not. while porting lv_list_all()
code copied to lv_list() and called lv_list. so it is expecting argument and errored out
Signed-off-by: Prudhvi Miryala <mprudhvi@linux.vnet.ibm.com>
=> Fix for porting eroor

libvirt/tests/src/virsh_cmd/monitor/virsh_domstate.py
avoid configuring address attribute to panic device as it is forbidden in
pseries
=> virsh_domstate: using address for Panic device is forbidden in pseries

libvirt/tests/src/virsh_cmd/host/virsh_domcapabilities.py
Attributes used to verify the capabilites are associated with virttype,
so handle them appropriately to test in right way,
Example:
/bin/virsh -c 'qemu:///system' domcapabilities  --virttype qemu \
--emulatorbin /usr/libexec/qemu-kvm --arch ppc64le --machine '40p'
or
/bin/virsh -c 'qemu:///system' domcapabilities  --virttype kvm \
--emulatorbin /usr/libexec/qemu-kvm --arch ppc64le --machine 'pseries'
=> virsh_domcapabilities: machine and emulator are associated with virttype

libvirt/tests/src/virsh_cmd/domain/virsh_migrate.py
guest_ip variable assignment moved to outer scope to avoid vaiable reference
before assignment issus and handling the test skip to cancel instead of error
=> virsh_migrate: variable assignment issue during hotplug/hotunplug before migration

libvirt/tests/src/virtual_disks/at_dt_iscsi_disk.py
For empty domain operation, just skip related test step is ok,
no need to log it as an error, it's confusing. Now change it to
logging.debug.
=> Empty domain operation should not trigger logging.error

libvirt/tests/cfg/virsh_cmd/nodedev/virsh_nodedev_detach_reattach.cfg, libvirt/tests/src/virsh_cmd/nodedev/virsh_nodedev_detach_reattach.py
(1) Get the device_name from the host on testing not from the cfg
(2) Check the driver with vfio or pci-stub according to libvirt version
=> Fix nodedevices detach/reattach issues

v2v/tests/src/convert_vm_to_libvirt.py, v2v/tests/src/convert_vm_to_ovirt.py
Modify convert_vm_to_libvirt and convert_vm_to_ovirt files,because
auto jobs were blocked by bug 1518517
Signed-off-by: weikunzz <1525690718@qq.com>
=> Modify v2v LIBGUESTFS_BACKEND temporarily

libvirt/tests/src/virsh_cmd/host/virsh_capabilities.py
There are some differences between s390x and other archs in
/proc/cpuinfo file. This is to correctly identify the cpu information
from the file on s390x.
=> virsh_capabilities: Fix cpuinfo checking on s390x

libvirt/tests/src/conf_file/qemu_conf/set_virtlogd.py
Make sure lsof is available before using it.
=> qemu_conf/set_virtlogd: Prepare lsof package

libvirt/tests/src/virsh_cmd/domain/virsh_schedinfo_qemu_posix.py
VM is not destroying forcefully. Then verify_guest_dmesg
is performed in postprocess. However, the vm has not been
able to login already. So "VM dead" is reported. Fix by
set gracefully=False for vm.destroy.
Signeg-off-by: Yan Li <yannli@redhat.com>
=> schedinfo_qemu_posix: Fix "VM dead"

libvirt/tests/src/graphics/graphics_functional.py
The format of vnc relevant arguments in qemu command line varies
in different RHEL versions, see below:
In RHEL6.9, like '-vnc unix:/var/lib/libvirt/qemu/*.vnc'.
In RHEL7.3, like '-vnc unix:/var/lib/libvirt/qemu/*vnc.sock'
In RHEL7.5, like '-vnc vnc=unix:/var/lib/libvirt/qemu/*vnc.sock'
Note, for RHEL7.5, 'vnc=' is added before regular arguments.
For compatibility, one more handling is added for this change.
Signed-off-by: czhang0 <47047802@qq.com>
=> One more handling is added for RHEL7.5 vnc argument change

libvirt/tests/src/virtual_network/iface_options.py
match string from "macvtap  mode xxx" changed to "macvtap mode xxx", so it should be compatible with old version
=> fix the problem for macvtap mode match method

libvirt/tests/src/virsh_cmd/host/virsh_uri.py
set_remote_ssh_key is used to setup remote machine to login other
host or to be logged in. In virsh_uri, need to setup autologin
for ssh to remote machine. So change to setup_ssh_key.
=> virsh_uri: Use setup_ssh_key

v2v/tests/cfg/v2v_options.cfg, v2v/tests/src/v2v_options.py
In case vm with same name exists.
Also extend timeout to 2400s for esx cases since it will usually
take more time than 1200s.
=> Rename vm name when converting disk

v2v/tests/src/convert_vm_to_ovirt.py
To avoid conflict when converting to rhvm. Add sufix of 3 letters string
to original vm name.
=> Rename vm in v2v conversion

libvirt/tests/cfg/virsh_cmd/host/virsh_cpu_models.cfg, libvirt/tests/cfg/virsh_cmd/host/virsh_domcapabilities.cfg
Use '${remote_ip}' replace 'EXAMPLE.COM' in virsh_cpu_models.cfg
and virsh_domcapabilities.cfg.
=> Use remote_ip replace 'EXAMPLE.COM'

libvirt/tests/src/virsh_cmd/domain/virsh_save_image_edit.py
Two changes:
1) matched string is not last line, so change to match any line
2) use more precise match pattern words to improve case credibility
Match string is like below:
[u'[root@localhost aexpect]# \x0c\x1b[24;1H"/tmp/virsh0thCpN.xml" 67L,
2481C written', u'State file /var/tmp/avocado_uK2uJ_/vm.save edited.',
u'[root@localhost aexpect]# ']
Signed-off-by: czhang0 <47047802@qq.com>
=> Fix expect match issue

libvirt/tests/cfg/numa/numa_memory.cfg, libvirt/tests/src/numa/numa_memory.py
https://projects.engineering.redhat.com/browse/LIBVIRTAT-859
https://projects.engineering.redhat.com/browse/LIBVIRTAT-1047
cfg part:
1. Delete the interleave when nodeset=0
2. Change the memory_nodeset = "0-1" instead of "2-3"
3. Change the vcpu_cpuset = "2,4" instead of "0,8"
py part:
When the memory_mode = "preferred" or "interleave", the orignal
checkpoint on memory allocation is not good and exact enough, so the
result will pass or fail according to the host. So I add the exact
checkpoint after communicated with lhuang.
=> Fix several issues on numa_memory part

libvirt/tests/src/daemon/init_scripts.py
Exit code is Access denied(4) after input a error
password, but exit code is Interactive authentication
required(1) with no ask password
=> Fix init_scripts the expected exit code

libvirt/tests/cfg/cpu/guestpin.cfg, libvirt/tests/src/cpu/guestpin.py
This patch adds a test to validate the host cpu statistics
with respect to affinity changes while guest under load.
=> Add test to validate the cpu affinity change with load

libvirt/tests/cfg/virtual_disks/virtual_disks_multivms.cfg
when native is set, only no disk cache or directsync cache mode are supported
=> fix disk driver native io cache mode issue

libvirt/tests/src/virsh_cmd/nodedev/virsh_nodedev_detach_reattach.py
Add the check point "intel_iommu=on" or "amd_iommu=on" in kernel cmdline
if the server is not enabled iommu option, then skip the case.
=> Add the check point of iommu=on in kernel cmdline

libvirt/tests/cfg/virsh_cmd/domain/virsh_attach_detach_disk.cfg, libvirt/tests/src/virsh_cmd/domain/virsh_attach_detach_disk.py
QEMU image locking, which should prevent multiple runs of QEMU
or qemu-img when a VM is running.
https://bugzilla.redhat.com/show_bug.cgi?id=1378241
=> Update case for new qemu feature

libvirt/tests/src/virtual_disks/virtual_disks_ceph.py
its expect result is to external snapshot failures
=> fix readonly disk snapshot issue

libvirt/tests/src/virsh_cmd/domain/virsh_domxml_to_native.py
For validating virsh domxml-to-native with /proc/\<pid\>/cmdline returns qemu
command line with /usr/bin/qemu-kvm instead of /usr/bin/qemu-system-ppc64, so
handle it for PowerPC
=> virsh_domxml_to_native: /proc/<pid>/cmdline returns with qemu-kvm

libvirt/tests/src/remote_access/remote_access.py
From libvirt 3.2.0, default mechanism changed from
digest-md5 to gssapi
=> Update remote_access case

libvirt/tests/cfg/virsh_cmd/volume/virsh_vol_create.cfg
=> Fix the virsh_vol_create case spelling mistake

libvirt/tests/cfg/virsh_cmd/domain/virsh_qemu_attach.cfg, libvirt/tests/src/virsh_cmd/domain/virsh_qemu_attach.py
Test case creates qemu vm to validate virsh qemu-attach, so disable
preprocess of libvirt vm for avoiding env_process error. Secondly, actual
fail is considered as test.cancel which is handled and caught in right way.
=> virsh_qemu_attach: disable preprocess libvirt vm and consider actual fail

libvirt/tests/src/serial/serial_functional.py
'model' is newly added into target tag since libvirt 3.10.
So modify code to adapt this change.
Signed-off-by: czhang0 <47047802@qq.com>
=> Add 'model' subelement into target for serial element

libvirt/tests/cfg/svirt/dac_start_destroy.cfg, libvirt/tests/src/svirt/dac_start_destroy.py
testcase would change the dynamic_ownership and verify whether guest
is able to boot when dynamic_ownership is 1 and guest should fail
to boot when dynamic_ownership is 0.
=> dac_start_destroy: add no qemu user group testcase

libvirt/tests/cfg/virtual_disks/virtual_disks_encryption.cfg, libvirt/tests/src/virtual_disks/virtual_disks_encryption.py
Now libvirt support to add <encryption> inside disk source element,
add code to cover this scenario for this script.
=> Add cases to cover <encryption> inside disk <source> scenarios

libvirt/tests/cfg/libvirt_vcpu_plug_unplug.cfg, libvirt/tests/src/libvirt_vcpu_plug_unplug.py
1. Add maxvcpu(240) hot(un)plug test
2. Add a param to adjust topology information for positive
tests to avoid testfailures due to vcpu param values mismatch in
different configs.
3. Remove autotest dependancy, thereby need to move helper functions
inside run method.
=> Add maxvcpu hotplug test and remove autotest dependancy

libvirt/tests/cfg/virsh_cmd/monitor/virsh_domstate.cfg, libvirt/tests/src/virsh_cmd/monitor/virsh_domstate.py
perform virsh reset after crashing vm with preserve as crash action, VM
will be in preseved debug state and virsh reset is expected to reboot
the guest and domstate should change from crashed to running.
=> virsh_domstate: add new test case virsh reset for preserve on crash action

libvirt/tests/src/virsh_cmd/domain/virsh_reboot.py
When framwork clear the env, the reboot operation
might not complete.
=> Fix reboot case imperfect

libvirt/tests/cfg/virsh_cmd/host/virsh_cpu_models.cfg, libvirt/tests/src/virsh_cmd/host/virsh_cpu_models.py
Restart remotely libvirtd to avoid test failed.
=> virsh_cpu_models: restart libvirtd for remote test

libvirt/tests/cfg/numa/numa_memory.cfg, libvirt/tests/src/numa/numa_memory.py
To avoid influence from original cpuset while checking results.
Also remove test cases with memory_placement as 'auto' while mode
as 'preferred'. The reason is that with both attribs setup, system
will eventually return 2 nodes which will cause the failure of
'NUMA memory tuning in 'preferred' mode only supports single node'.
Therefore these cases are not legitimate.
=> Remove cputune from xml before test

libvirt/tests/src/libvirt_vcpu_plug_unplug.py
Specific parameters can not be completed within 60s
e.g: add vcpu from 1 to 240
=> Update for cpu hotplug timeout

libvirt/tests/src/virsh_cmd/host/virsh_cpu_models.py
Local host test don't need set remote_ip and remote_pwd. So change the code order for remote test.
=> virsh_cpu_models: Change the order for remote test

libvirt/tests/src/libvirt_mem.py
Added 'ram-node' to 'check_qemu_cmd' function, this observed in
hugepages backed guest.
And in latest qemu 'memory-backend-ram' and 'size' are not
continuous so separated them as well.
=> Modify check_qemu_cmd to handle different id

libvirt/tests/src/libvirt_mem.py
Fix E722 do not use bare except
in libvirt_mem.py
=> Fix - E722 do not use bare except in libvirt_mem.py

libvirt/tests/src/virsh_cmd/domain/virsh_blockcopy.py
In case making invalid snapshot that has not 'source' attrib
=> blockcopy:Ignore non-disk disks

libvirt/tests/cfg/libvirt_mem.cfg, libvirt/tests/src/libvirt_mem.py
This patch round memory values to 1024 multiples, this requires
for ppc64le architecture. With out these 1024 multiplesi, most of
the tests fail.
=> Round memory values to 1024 multiples

libvirt/tests/cfg/bios/virsh_boot.cfg, libvirt/tests/src/bios/virsh_boot.py
The script can support boot OVMF or Seabios Guest
by using different guest image. The main test flow is like:
1) Edit VM xml with specified boot options
2) For OVMF secure boot mode, boot VM from
cdrom first, set the secure key, then switch
boot from disk device
3) For Seabios, directly boot VM from given device
4) Verify if Guest can boot as expected
=> Add new case: "Boot OVMF/Seabios Guest" with options

libvirt/tests/src/virsh_cmd/domain/virsh_domblkerror.py
using closed session object cause test to get interrupted, handle it
appropriately by new session and have check to close session on cleanup
if test interrupted after opening session.
=> virsh_domblkerror: traceback due to using of closed session object

libvirt/tests/src/libvirt_vcpu_plug_unplug.py
Only apply to x86_64 and i386 for s3 setting.
=> vcpu_plug_unplug: Avoid s3 setting in ALT archs

libvirt/tests/cfg/virsh_cmd/domain/virsh_migrate.cfg, libvirt/tests/src/virsh_cmd/domain/virsh_migrate.py
1. Enable migration testcases to work for POWER8 compat guest on POWER9
host.
2. cpu hotplug/hotunplug scenarios can be shrinked to live migration
there and back migration, postcopy migration and online migration
for better confined coverage
=> virsh_migrate: enable POWER8 compat guest migration on POWER9 host

v2v/tests/cfg/convert_vm_to_libvirt.cfg, v2v/tests/cfg/convert_vm_to_ovirt.cfg
v2v i386 x86_64 variants are  easy to repeat.
In latest auto job testing will cause the some issue.
Signed-off-by: weikunzz <kuwei@redhat.com>
=> v2v matrix matching problems in v2v cfg

libvirt/tests/src/virsh_cmd/domain/virsh_attach_device.py
From 7.4 release, the virtlogd is used and only could write /var/log
=> Fix the serial log path

libvirt/tests/src/virsh_cmd/domain/virsh_attach_detach_interface_matrix.py
For virsh detach should be executed after vm booted up in case it
won't take effect.
=> Wait for vm to booted up before detaching interface test

libvirt/tests/cfg/virsh_cmd/domain/virsh_migrate.cfg
improper filter caused migration to get lost on x86 platform,
fixed it in the patch.
Signed-off-by: Junxiang Li junli@redhat.com
Signed-off-by: Yi Sun yisun@redhat.com
Reported-by: Yi Sun yisun@redhat.com
=> virsh_migrate: fix improper filter for migration tests

libvirt/tests/cfg/virsh_cmd/volume/virsh_vol_create.cfg, libvirt/tests/src/virsh_cmd/volume/virsh_vol_create.py
expand the test case to cover vol-create-as. Since vol-create and vol-create-as have similar functions, I only have to add some variants to cfg file, and change the py code according to the cfg file.
the original test cases and newly added test cases PASS on my local machine, the origin test results are the same with Jenkins result, so this change doesn't break old tests
Signed-off-by: yachang <yachang@redhat.com>
=> expand virsh_vol_create to cover vol-create-as

libvirt/tests/src/virsh_cmd/domain/virsh_attach_device.py
The whole procedure is to count disks in vm first, generate target
for the to be attached disk, attach disk, then check the status of
the attached disk.
If there's a cdrom disk in original vm, let's say its target is sda,
The attached disk will be 'sdb'. The checking step will try to find
certain string in vm device '/dev/sdb' which does not exist, since
the disk supposed to be 'sda' is acctually 'cdrom' in /dev.
Therefore remove any non-disk disks before test starts.
=> Remove non-disk disks before test

libvirt/tests/cfg/virsh_cmd/host/virsh_freepages.cfg, libvirt/tests/src/virsh_cmd/host/virsh_freepages.py
virsh_freepages: add new cases and more stictly result checking
New cases:
1. cover 3 type pagesizes testing, ranging from 4K, 2M, 1G
2. cover severl pagesize formates
4 is same with 4K, 4k, 4Kib, 4KIB
2048 is same with 2048K, 2M, 2m, 2048Kib and so on
1048576 is same with 1G, 1048576k, 1048576Kib and so on
New checking points:
1. Check if hugepages feature is supported by CPU
2. Check if hugepages can be available by current system
3. Check allocated pagesize number for each available pagesize
4. Compare free pagesize number with allocated pagesize number for
each available  pagesize
=> virsh_freepages: add new cases and more strictly result checking

libvirt/tests/src/virsh_cmd/domain/virsh_blockcopy.py, libvirt/tests/src/virsh_cmd/domain/virsh_blockjob.py, libvirt/tests/src/virsh_cmd/domain/virsh_undefine.py
For UEFI boot VM, the --nvram option required to undefine vm.
For bios VM, use the option bring no harm.
Update case undefine and blockcopy first as they are in
acceptance test scope.
=> Add --nvram option for undefine

libvirt/tests/src/virsh_cmd/snapshot/virsh_snapshot_disk.py
To avoid performing snapshot to non-disk disks such as 'cdrom'
=> Ignore disks whose 'device' is not 'disk'

libvirt/tests/cfg/virsh_cmd/domain/virsh_vcpupin.cfg
vms' names should not be hard coded here, it should be replaced in
CI or provided manually by end users.
=> Remove vms in vcpu pin config file

libvirt/tests/src/virsh_cmd/volume/virsh_vol_create.py
This PR is to fix PR  #1211 for tp-libvirt,
where the exception shall be skipped instead
of test.fail
=> vol_create: Skip bug 106028

libvirt/tests/cfg/virsh_cmd/domain/virsh_domfsinfo.cfg, libvirt/tests/src/virsh_cmd/domain/virsh_domfsinfo.py
This script to test Command virsh.domfsinfo
with following cases support:
virsh.domfsinfo.positive_tests.no_freezed_fs
virsh.domfsinfo.positive_tests.nfs
virsh.domfsinfo.positive_tests.quite_mode
virsh.domfsinfo.positive_tests.hotplug_unhotplug
virsh.domfsinfo.negative_tests.no_agent
virsh.domfsinfo.negative_tests.vm_shutdown
virsh.domfsinfo.negative_tests.ga_unavailable
virsh.domfsinfo.negative_tests.readonly_mode
virsh.domfsinfo.negative_tests.fs_freezed
=> Automate manual case of virsh.domfsinfo

libvirt/tests/cfg/virsh_cmd/monitor/virsh_domstate.cfg, libvirt/tests/src/virsh_cmd/monitor/virsh_domstate.py
guest with huge memory takes more time for dumping core which timeout
the testcase and cause error, instead configuring less memory would
ensure test to work properly
=> virsh_domstate: configure less guest memory for coredump testcase

libvirt/tests/src/smt.py
Removed host_threads check for guest smt as it is independant
now, the change got introduced in the below qemu commit.
Reference: https://github.com/qemu/qemu/commit/03ee51d3548f5f553a3089f466483c1c6d5c666b
=> Remove host_threads check for guest smt

libvirt/tests/src/virtual_disks/virtual_disks_multivms.py
At the time of testing, the same virtual hard disk is loaded
because of the two VM, which causes vm2 to not start.
Add a piece of code to the virtual_disks_multivms.py
file so that the XML of the second virtual disks added
during the test has a shareable attribute,
which solves the problem of the vm2 start failure
=> virtual_disks_multivms: Fix the error:Fail to start domain vm2 

libvirt/tests/src/migration/migrate_vm.py
The changed variable was not assigned expected value before which
causing the cdrom disk and floopy disk have some source file name
incorrectly. But the problem was not exposed as the case luckily passed
in the past, while the qemu image lock caused this case to fail in
RHEL7.5 now. So we need correct the wrong logic here to make it use
different image names.
=> migrate_vm: Fix incorrect logic

libvirt/tests/src/migration/migrate_vm.py
After canceling migration, we do migration again without any dealy which
causes the qemu has no enough time to clean up the guest on target host.
So new migration will fail with founding guest on target host. This is
to fix this problem by adding some waiting seconds.
=> migrate_vm: Fix cancel migration

libvirt/tests/cfg/virsh_cmd/domain/virsh_migration.cfg, libvirt/tests/src/virsh_cmd/domain/virsh_migration.py
use migration_setup param to perform pre/post migration setups instead
from testcase
=> virsh_migration: optimize migration testcase by using migration_setup

v2v/tests/cfg/function_test_esx.cfg, v2v/tests/src/function_test_esx.py
- Update value of 'vm_name' after vm is set new name
- Update pattern of log for a successful match
- Set debug=True while starting vm with virsh
- Update option value for cases of 'root' option
=> Update code for v2v function case of esx

libvirt/tests/src/virsh_cmd/domain/virsh_domblkerror.py
For unspecified_error test would require nfs packages to be installed and
available in host, commit 4f78942 checks and installs in guest which breaks
the test.
=> virsh_domblkerror: Fixup to check nfs package availablity in host, n

libvirt/tests/src/bios/virsh_boot.py
vm.serial_console changed to ConsoleSession from
ShellSession. So did some adaptation to meet this
change, otherwise "No console available" will be
threw out
=> virsh_boot: Adaptation to console session

libvirt/tests/src/virsh_cmd/host/virsh_capabilities.py
PR #1443 replaced autotest 'os_dep.command' with
avocado 'path.find_command', but missed to update
the returned exception, So case would be failed when
cmd can't be found
=> Python 3: Fixup virsh.capabilities failure

libvirt/tests/src/virsh_cmd/domain/virsh_emulatorpin.py
Replace autotest cpu_online_map with avocado
cpu_online_list. Since cpu_online list return int
sequence while cpu_online_map return str sequence,
so some extra convertion needed here.
=> Python 3: Fixup cpu_online_list replacement issue

libvirt/tests/cfg/virsh_cmd/volume/virsh_vol_clone_wipe.cfg, libvirt/tests/src/virsh_cmd/volume/virsh_vol_clone_wipe.py
sing-offed by: Yi Sun (yisun@redhat.com)
Tested with libvirt-3.1.0-2.el7.x86_64
Failed cases are due to libvirt's behavior changed during 3.0.0-x, and we need to update
avocado-vt/virttest/utils_test/libvirt.py:pre_pool(), which is being fixed.
~## avocado run --vt-type libvirt type_specific.lento.virsh.vol_clone_wipe.positive_test.luks_encrypt..
JOB ID     : f018b2e4d027b627a16d3ae393bd525cf9864135
JOB LOG    : /root/avocado/job-results/job-2017-03-28T18.34-f018b2e/job.log
TESTS      : 4
(1/4) type_specific.lento.virsh.vol_clone_wipe.positive_test.luks_encrypt.non_acl.vol_format.raw_f.pool_type.dir: PASS (6.44 s)
(2/4) type_specific.lento.virsh.vol_clone_wipe.positive_test.luks_encrypt.non_acl.vol_format.raw_f.pool_type.fs: PASS (37.90 s)
(3/4) …
=> Add cases to cover luks vol-wipe/vol-clone

libvirt/tests/src/virsh_cmd/volume/virsh_vol_resize.py
Wrongly put 'test' in to os.path.join(), fixed.
=> Fix a parameter position error

libvirt/tests/cfg/virsh_cmd/monitor/virsh_domstate.cfg
initialize err_msg to fix the TypeError at L283,
TypeError: not all arguments converted during string formatting
=> virsh_domstate: err_msg is not initialized tracebacks TypeError

libvirt/tests/src/virsh_cmd/domain/virsh_dompmsuspend.py
After triggering domspmsuspend, have a check and raise the failure if vm fails
to change current state to pmsuspended.
=> virsh_dompmsuspend: raise test fail if vm fails to change state to pmsuspended

libvirt/tests/src/controller/controller_functional.py, libvirt/tests/src/daemon/crash_regression.py, libvirt/tests/src/daemon/daemon_functional.py, libvirt/tests/src/daemon/init_scripts.py, libvirt/tests/src/daemon/kill_qemu.py, libvirt/tests/src/daemon/kill_started.py, libvirt/tests/src/daemon/kill_starting.py, libvirt/tests/src/daemon/restart_consist.py, libvirt/tests/src/graphics/graphics_functional.py, libvirt/tests/src/guest_kernel_debugging/nmi_test.py, libvirt/tests/src/libvirt_bench/libvirt_bench_domstate_switch_by_groups.py, libvirt/tests/src/libvirt_bench/libvirt_bench_domstate_switch_in_loop.py, libvirt/tests/src/libvirt_bench/libvirt_bench_domstate_switch_with_iozone.py, libvirt/tests/src/libvirt_bench/libvirt_bench_domstate_switch_with_unixbench.py, libvirt/tests/src/libvirt_bench/libvirt_bench_dump_with_netperf.py, libvirt/tests/src/libvirt_bench/libvirt_bench_dump_with_unixbench.py, libvirt/tests/src/libvirt_bench/libvirt_bench_serial_hotplug.py, libvirt/tests/src/libvirt_bench/libvirt_bench_ttcp_from_guest_to_host.py, libvirt/tests/src/libvirt_bench/libvirt_bench_usb_hotplug.py, libvirt/tests/src/libvirt_bench/libvirt_bench_vcpu_hotplug.py
1) Porting python2 to python3 compatible each other
2) Remove autotest dependency
=> Python 3: Port libvirt_bench, daemon and misc dirs

libvirt/tests/cfg/libvirt_pci_passthrough_hotplug.cfg, libvirt/tests/src/libvirt_pci_passthrough_hotplug.py
This test case will test the virsh dump feature for KVM guest which is having hotplugged adapter.
Signed-off-by: prudhvi <mprudhvi@linux.vnet.ibm.com>
=> Test virsh dump feature

libvirt/tests/src/virsh_cmd/domain/virsh_sendkey.py
check for VM distribution and use /var/log/syslog for ubuntu instead
of /var/log/messages for the test to proceed seamless
=> virsh_sendkey: adopt sysrq tests to use /var/log/syslog for ubuntu

libvirt/tests/cfg/virtual_disks/virtual_disks_luks.cfg, libvirt/tests/src/virtual_disks/virtual_disks_luks.py
Test steps as follow:
1.Prepare backend storage (blkdev/iscsi/gluster/ceph)
2.Use luks format to encrypt the backend storage
3.Prepare a disk xml indicating to the backend storage with valid/invalid
luks password
4.Start vm with disk hot/cold plugged
5.Check some disk operations in vm
6.Check backend storage is still in luks format
7.Recover test environment
sign-offed by: Yi Sun(yisun@redhat.com)
=> Add cases for luks block/iscsi/gluster/ceph device

libvirt/tests/cfg/conf_file/sysconfig_libvirt_guests/libvirt_guests.cfg, libvirt/tests/src/conf_file/sysconfig_libvirt_guests/libvirt_guests.py
1. set the values in /etc/sysconfig/libvirt-guests
2. restart libvirt-guests service
3. check the domains states, and the guests' save files
=> Add the case for shutdown guests in parallel using libvirt-guests

libvirt/tests/cfg/virtual_device/sound_device.cfg, libvirt/tests/src/virtual_device/sound_device.py
Add the test cases for virtual sound device. Sound model includes
ac97, ich6, ich9. And codec type includes micro and duplex for
latter two models.
=> Add the test cases for sound device

libvirt/tests/src/virtual_network/iface_hotplug.py
Clean up the serial console and reuse it after that
=> Iface_hotplug: Fixup the serial bug

libvirt/tests/cfg/nwfilter/nwfilter_vm_start.cfg, libvirt/tests/src/nwfilter/nwfilter_vm_start.py
The clean-traffic nwfilter should include filter 'no-other-l2-traffic'.
Fix the referred filter index typo to correct it. 'kill -SIGTERM' is not
recommended and it cause 'invalid signal specification' error. Modify
the cmd to 'kill -s TERM'.
=> Fix a typo of filter definition and fix kill cmd

libvirt/tests/src/libvirt_pci_passthrough.py
Modified the SR-IOV setup by implementing the existing PciAssignable class.
The existing setup for SR-IOV requires the driver and no.of VF's to be hardcoded.
We can reuse the PciAssignable class for setting up the SR-IOV VF's, independent of the
driver.
Also based on the PF device specified, all the VF's belonging to the same iommu group
will be pass-throughed.
=> Modified the SR-IOV setup by implementing the existing PciAssignable class

libvirt/tests/cfg/virsh_cmd/domain/virsh_cpu_baseline.cfg
Skip guest dmesg check for tests that do
not need to start guest.
=> Skip guest dmesg check for tests without guest start

.travis.yml
This PR is to fix issue below during inspekt style check,
so many failures raised with '\'. However it has ever been
successful before
.../virsh_net_create.py:120:44:
W605 invalid escape sequence '\>'
=> Travis.yaml: Add filter W605

libvirt/tests/src/virsh_cmd/monitor/virsh_domstate.py
kill_process_tree() performs safe_kill() and test checks the domstate
and fails before kill would send the signal.SIGKILL
=> virsh_domstate: timing issue cause to check domstate before prior action

libvirt/tests/src/libvirt_qemu_cmdline.py
config_feature_*() need 3 parameters, so fix it to add
missing 'test' argument.
=> Python 3: Fix missing call parameter issue

libvirt/tests/src/svirt/dac_nfs_disk.py, libvirt/tests/src/virsh_cmd/domain/virsh_attach_detach_disk.py, libvirt/tests/src/virsh_cmd/interface/virsh_iface.py, libvirt/tests/src/virtual_disks/virtual_disks_ceph.py, libvirt/tests/src/virtual_disks/virtual_disks_usb.py
Refix for commit d910ba9. Previously test.tmpdir is used by tp-libvirt
to store test images for case running. However avocado master 60 did
some changes(avocado #2543), where the tmpdir isn't accessable by public
user anymore. So need to change to virttest.data_dir.get_tmp_dir to
provide public access. This PR only updated the acceptance test, and
will apply to all tp-libvirt test cases after acceptance test passed in CI
=> Python 3: Permission denial re-fix for acceptance test

libvirt/tests/src/virsh_cmd/pool/virsh_pool.py
The stdout has been stripped, so no need to
match whitespace or "\n" at the end of the
string
=> virsh_pool:Fixup virsh_pool_test not found

libvirt/tests/cfg/virtual_network/iface_coalesce.cfg, libvirt/tests/src/virtual_network/iface_coalesce.py
virtual_network: add new cases for coalesce setting check
new cases:
iface_coalesce.positive_testing.net_default.iface-bridge
iface_coalesce.positive_testing.net_default.iface-network
iface_coalesce.positive_testing.net_bridge.iface-bridge
iface_coalesce.positive_testing.net_bridge.iface-network
iface_coalesce.positive_testing.net_ovs.iface-bridge
iface_coalesce.positive_testing.net_ovs.iface-network
iface_coalesce.positive_testing.net_macvtap.iface-network
iface_coalesce.negative_testing.iface_direct
iface_coalesce.negative_testing.hotplug_direct
iface_coalesce.negative_testing.hotplug_invalid
iface_coalesce.negative_testing.model_type_e1000
iface_coalesce.negative_testing.model_type_e1000e
iface_coalesce.negative_testing.model_type_rtl8139 …
=> virtual_network: add new cases for coalesce setting check

libvirt/tests/src/virsh_cmd/pool/virsh_pool.py, libvirt/tests/src/virsh_cmd/pool/virsh_pool_acl.py, libvirt/tests/src/virt_cmd/virt_xml_validate.py, libvirt/tests/src/virtual_disks/at_dt_iscsi_disk.py, libvirt/tests/src/virtual_disks/startup_policy.py, libvirt/tests/src/virtual_disks/virtual_disks_multidisks.py
Since stdout are stripped during Porting, the old
pattern matching "\n" shall be removed. Bundles of
cases are failed by this
=> Remove "\n" matching pattern in stdout

libvirt/tests/src/virtual_network/iface_network.py
virtual_network/iface_network.py: the unit of the filter policy can be
'Mb' in addition to 'b', so add the check.
=> Fix issue "Can't find any filter policy"

libvirt/tests/src/libvirt_pci_passthrough_hotplug.py, libvirt/tests/src/limit.py, libvirt/tests/src/migration/migrate_vm.py, libvirt/tests/src/nwfilter/nwfilter_update_vm_running.py, libvirt/tests/src/nwfilter/nwfilter_vm_attach.py, libvirt/tests/src/nwfilter/nwfilter_vm_start.py, libvirt/tests/src/smt.py, libvirt/tests/src/svirt/dac_vm_per_image_start.py, libvirt/tests/src/virsh_cmd/domain/virsh_domxml_to_native.py, libvirt/tests/src/virsh_cmd/domain/virsh_migrate.py, libvirt/tests/src/virsh_cmd/monitor/virsh_domifstat.py, libvirt/tests/src/virsh_cmd/pool/virsh_find_storage_pool_sources.py, libvirt/tests/src/virsh_cmd/pool/virsh_find_storage_pool_sources_as.py, libvirt/tests/src/virsh_cmd/pool/virsh_pool_acl.py, libvirt/tests/src/virtual_network/iface_network.py, v2v/tests/src/v2v_options.py
As process.system_output return bytes instead of
string with Python 3, need to convert it to text
with method compatible py2 and py3
=> Python 3: Replace process.system_output

libvirt/tests/cfg/virsh_cmd/domain/virsh_memtune.cfg, libvirt/tests/src/virsh_cmd/domain/virsh_memtune.py
memtune: add some new cases and more strict result checking
Newly added checking point:
1) check memtune value from the output of "virsh dumpxml"
2) check vm is alive
New added test cases:
1) normal case:
-1(unlimited),
positive value
negative value(unlimited),
0 for soft_limit,
both set 3 limits in one command line
restart testing
2) invalid case:
0 for hard_limit
hard limit is bigger than swap_hard_limit
non-integer
invalid suffix
=> memtune: add some new cases and more strict result checking

libvirt/tests/src/virtual_disks/virtual_disks_multidisks.py
If we want to clean up the snapshots successfully in the recover process of the test, we need to destroy vm.
=> fix delet snapshot error in multidisks

libvirt/tests/cfg/virsh_cmd/domain/virsh_migrate.cfg, libvirt/tests/src/virsh_cmd/domain/virsh_migrate.py
- refactor virsh_migrate to adopt migration_setup from pre/postprocess
- check and validate VM uptime to ensure it is not rebooted during migration
- consider VM network not reachable after migration as a failure
=> virsh_migrate: refactor to use migration_setup and validate uptime patches

libvirt/tests/src/virsh_cmd/domain/virsh_migrate.py
Earlier ssh was being used to send cmds to guest from remote machine after
migrating the guest, but going further using virsh uri makes it robust.
=> virsh_migrate: use virsh uri to handle guest cmd from destination machine

libvirt/tests/src/virsh_cmd/monitor/virsh_domstate.py
When middle state is caught, it needs to overwrite the value of 'cmd_output'.
Signed-off-by: yafu <yafu@redhat.com>
=> Fix the domstate check if middle state is caught

libvirt/tests/cfg/virsh_cmd/nodedev/virsh_nodedev_detach_reattach.cfg, libvirt/tests/src/virsh_cmd/nodedev/virsh_nodedev_detach_reattach.py
Check the driver of device and remove the driver.
Then detach the node device and reattach it.
=> Dettach node device from host without device driver

provider/v2v_vmcheck_helper.py, v2v/tests/cfg/convert_vm_to_libvirt.cfg, v2v/tests/cfg/convert_vm_to_ovirt.cfg
Modify  "provider/v2v_vmcheck_helper.py" file ,resolve the uefi guest fail to check "device.map" part.
Signed-off-by: Kun Wei kuwei@redhat.com
=> V2V: Resolve uefi guest fail to check device.map

v2v/tests/cfg/convert_vm_to_libvirt.cfg, v2v/tests/cfg/convert_vm_to_ovirt.cfg
1.Modify the special version to flexible,
libvirt_ci jobs.yaml can replace it quickly
include rhel7 and rhel6, expect rhel5,it has been stable.
Signed-off-by: kuwei <kuwei@redhat.com>
=> v2v:Modify the special version to flexible

libvirt/tests/cfg/libvirt_vcpu_plug_unplug.cfg
##avocado run --vt-type libvirt libvirt_vcpu_plug_unplug.negative_test.guest_plug.more_than_max
JOB ID     : ea900dc21801f3e82f549ec95939d66acfe3979a
JOB LOG    : /root/avocado/job-results/job-2017-12-27T13.41-ea900dc/job.log
(1/1) type_specific.io-github-autotest-libvirt.libvirt_vcpu_plug_unplug.negative_test.guest_plug.more_than_max: PASS (55.64 s)
JOB TIME   : 59.58 s
##avocado run --vt-type libvirt libvirt_vcpu_plug_unplug.negative_test.guest_plug.more_than_current
JOB ID     : e6256a0d404e07bf73fde0beba228e0838db6658
JOB LOG    : /root/avocado/job-results/job-2017-12-27T13.42-e6256a0/job.log
(1/1) type_specific.io-github-autotest-libvirt.libvirt_vcpu_plug_unplug.negative_test.guest_plug.more_than_current …
=> Add missing negative cases for setvcpus with guest agent

libvirt/tests/src/virsh_cmd/domain/virsh_domfsinfo.py
s.encoding returns bytes instead of str in python3, and it caused
str comparing like str1 != str2 is True always, and then case failed
all the time
=> Python 3: domfsinfo encoding fix

libvirt/tests/src/virsh_cmd/domain/virsh_sendkey.py
guest session might be invalidated/expired after sysrq tests as
it might reboot the guest, cause test to error during cleanup.
=> virsh_sendkey: reinitialize session to cleanup

libvirt/tests/src/virsh_cmd/domain/virsh_dompmsuspend.py
on fail/error, log the result output/error instead of object name
appropriately.
=> virsh_dompmsuspend: log appropriate stdout/stderr instead of object

libvirt/tests/cfg/virtual_network/iface_network.cfg
Fix the timeout failue when login vm by ssh to use serial login.
In the test 'net_dns_host', it set the dns forward server as
8.8.8.8, which will be used when OpenSSH login. It takes longer
to use other dns forward server than the default setting.
=> Use serial login when test dns related cases

libvirt/tests/src/virsh_cmd/domain/virsh_domxml_to_native.py
ubuntu uses /usr/bin/kvm in qemu commandline that errors the test as
it is not handled.
=> virsh_domxml_to_native: ubuntu uses /usr/bin/kvm in qemu commandline

libvirt/tests/cfg/virsh_cmd/nodedev/virsh_nodedev_create_destroy.cfg, libvirt/tests/src/virsh_cmd/nodedev/virsh_nodedev_create_destroy.py
Create/destroy node device which is not fibre channel HBA, it will get
the error as expected.
=> Negative case : create node device which is not fibre channel HBA

libvirt/tests/src/virsh_cmd/volume/virsh_volume.py
TypeError: '>' not supported between instances of 'int' and 'str'
=> Python 3: virsh_volume TypeError fixup

libvirt/tests/cfg/virsh_cmd/domain/virsh_domjobabort.cfg, libvirt/tests/src/virsh_cmd/domain/virsh_domjobabort.py
Reconstruct virsh_domjobabort.cfg file to be more clear and easier
to extend scenarios. Also add crash dump scenario here.
=> Reconstruct and enrich domjobabort cfg file

libvirt/tests/cfg/virsh_cmd/domain/virsh_domiftune.cfg, libvirt/tests/src/virsh_cmd/domain/virsh_domiftune.py
Fix the name issue in cfg file and the condition judgement.
As the value is unicode type, (u'0' is not '0') will return Ture,
update it to be (u'0' != '0') which will return False, and it is
expected.
=> Fix issue in clear inbound/outdound for domiftune

libvirt/tests/src/virsh_cmd/domain/virsh_domfsinfo.py, libvirt/tests/src/virsh_cmd/secret/virsh_secret_set_get.py, libvirt/tests/src/virtual_disks/at_dt_iscsi_disk.py, libvirt/tests/src/virtual_disks/virtual_disks_iscsi.py, libvirt/tests/src/virtual_disks/virtual_disks_multidisks.py
This PR is to fix below issue when with base64 encode and decode:
TypeError: a bytes-like object is required, not 'str'
=> Python 3: Type error fix for base64

libvirt/tests/src/virsh_cmd/domain/virsh_vcpupin.py
In Python3, map returns an iterator not a list
=> Python 3: TypeError: object of type 'map' has no len()

libvirt/tests/src/virsh_cmd/domain/virsh_cpu_compare.py
Open file with "w+b" is incorrect
=> virsh.cpu_compare: TypeError: a bytes-like object is required

libvirt/tests/cfg/controller/controller_functional.cfg, libvirt/tests/src/controller/controller_functional.py
Add the USB3.0 controller test. Before Adding the test, 
some mistakes in the script and cfg file is also been fixed.
Fix the following mistakes:
(1) the usb_controller params in cfg file is never been used in
the script.
(2) the usb controller can be used in both i440fx and q35 machine.
(3) the companian controller models, such as ich9-uhci[123], are
usually used only with ich9-ehci1 all together, rather than used with
ich9-ehci1 alone.
(4) qemu cmdline is never been checked in usb controller tests.
=> Add the Usb controller 3.0 test, and fix some mistakes

libguestfs/tests/guestfish_file_dir.py, libvirt/tests/src/cpu/vcpu_hotpluggable.py, libvirt/tests/src/migration/migrate_vm.py, libvirt/tests/src/sriov/sriov.py, libvirt/tests/src/virsh_cmd/domain/virsh_migrate.py, libvirt/tests/src/virsh_cmd/domain/virsh_migrate_virtio_scsi.py, libvirt/tests/src/virsh_cmd/host/virsh_capabilities.py, libvirt/tests/src/virsh_cmd/host/virsh_hostname.py, libvirt/tests/src/virsh_cmd/host/virsh_uri.py
cmp function is gone from Python3. So use"==" or "!="
as alternative
=> Python 3: NameError: name 'cmp' is not defined

libvirt/tests/src/migration/migrate_vm.py, libvirt/tests/src/virsh_cmd/domain/virsh_domblkerror.py, libvirt/tests/src/virsh_cmd/domain/virsh_dompmsuspend.py, libvirt/tests/src/virsh_cmd/domain/virsh_migrate_multi_vms.py, libvirt/tests/src/virsh_cmd/domain/virsh_migration.py, libvirt/tests/src/virsh_cmd/domain/virsh_qemu_agent_command_fs.py, libvirt/tests/src/virsh_cmd/domain/virsh_update_device_matrix.py, libvirt/tests/src/virsh_cmd/volume/virsh_vol_create.py, libvirt/tests/src/virtual_network/iface_coalesce.py
To fix errors like below when with python3 :
2018-05-03 12:03:43,141 test             L1019 ERROR|     except
virt_vm.VMStartError, info:
2018-05-03 12:03:43,141 test             L1019 ERROR|
^
2018-05-03 12:03:43,141 test             L1019 ERROR| SyntaxError:
invalid syntax
=> Python 3: SyntaxError fix for except clause

libvirt/tests/src/virtual_disks/virtual_disks_encryption.py
When prepare for sesecret_string, it need call base64.b64encode() to return
one string, but on python 3,it will return bytes instead.
Fix it by forcedly decoding by locale preferred encoding
=> python 3: fix base64.b64encode() return bytes instead of string issue

libvirt/tests/cfg/migration/migrate_options_shared.cfg, libvirt/tests/src/migration/migrate_options_shared.py
Add new cases for options '--comp-mt-threads' and '--comp-xbzrle-cache'
and etc in migration.
In RHEL7.3, there is newly way to specify the compression method during
migration. In the past, there is only 'xbzrle' method used as default.
But in the new release, 'mt' method is newly supported as well as its
following parameters to define the number of compression and
decompression threads on source and target host respectively. And also a
new option for 'xbzrle' method that is '--comp-xbzrle-cache' to support
to define the page cache used for compression.
For '--timeout-postcopy', the VM on target host should be running at
once after waiting for timeout seconds.   
Add case for qemu native TLS support in migration.
=> migrate_options_shared: Add new cases for migration

libvirt/tests/cfg/virsh_cmd/domain/virsh_setvcpus.cfg, libvirt/tests/src/virsh_cmd/domain/virsh_setvcpus.py
Add topology correction argument as provided by
test, to correct if topology mismatch in guest xml
=> Add topology correction if provided by test

libvirt/tests/src/libvirt_pci_passthrough.py
For Infiniband Controllers, we have to set the link for the VF's before pass-through.
If the links are not enabled before pass-through, then the interfaces would be 
in down state in the VM.
=> For Infiniband Controllers, we have to set the link for the VF's before pass-through.

libvirt/tests/cfg/virsh_cmd/network/virsh_net_destroy.cfg, libvirt/tests/src/virsh_cmd/network/virsh_net_destroy.py, libvirt/tests/src/virsh_cmd/network/virsh_net_edit.py
virsh_net_destroy: add the test about destroy transisent network.
After destroy, the network will disappear. virsh_net_edit: add 2
checkpoint, one is check the status after define network and libvirtd
restart, another is check active xml do not change after edit.
=> Add test scenario about destroy transient network

libvirt/tests/src/virsh_cmd/domain/virsh_domrename.py
For negative scenario: rename vm to an exist vm2, if clone fail,
the rename will succeed, and remove the vm2 will remove the
original one. This patch is to fix this.
=> Fix vm-clone risk

libvirt/tests/cfg/controller/controller_functional.cfg, libvirt/tests/src/controller/controller_functional.py
The default usb controller on PPC is 'qemu-xhci'. This is to test this
feature.
=> controller.functional: Add case for PPC usb

libvirt/tests/src/cpu/guestpin.py
Fixed incorrect format specifier was used for
test.fail
=> Fixup: incorrect format specifier for test.fail- Minor hotfix

libvirt/tests/cfg/multivm_stress/multivm_cpustress.cfg, libvirt/tests/src/multivm_stress/multivm_stress.py
This patch adds tests which would use multiple vms in
the environment and run tests in parallel in all those
vms, which stresses vcpupin, vcpu hotplug, suspend/resume
with guest running stress tests, and it stresses boot of
guests in parallel.
=> Add multi vm cpu stress tests

libvirt/tests/cfg/migration/migrate_vm.cfg, libvirt/tests/src/migration/migrate_vm.py
stress_type may not be set in normal cases, and only set under stress
therefore stress_type.split("_")may throw NoneType exception
The way to fix it is to add variable as precondition before call stress_type.split("_")
=> Fix migration VM failure due to stress_type NoneType issue

libvirt/tests/src/virsh_cmd/domain/virsh_migrate_set_get_speed.py
In Python 3, / is float division
In Python 2, / is integer division (assuming int inputs)
In both 2 and 3, // is integer division
=> Python3: Fix division operator

libvirt/tests/src/multivm_stress/multivm_stress.py
This patch fixes below error as args passed to stress function has
been misplaced.
TestFail: Error running stress in vms: 'str' object has no attribute 'params'
=> Fixup: stress functions args position - Minor-Hotfix

libvirt/tests/src/migration/migrate_vm.py
This will fix the error below for some cases.
AttributeError: 'NoneType' object has no attribute 'split'
=> migrate_vm: Fix missing check for stress_type

libvirt/tests/cfg/virsh_cmd/network/virsh_net_destroy.cfg, libvirt/tests/src/virsh_cmd/network/virsh_net_destroy.py
net_destroy: add test cases to check the status of libvirtd service.
libvirtd should not crash after destroy network or vm.
=> libvirtd should not crash after destroy network/vm

libvirt/tests/src/virsh_cmd/domain/virsh_migrate.py
For dname cases, as the domain name is changed on target host, the
original vm console can not work correctly which is created with
original domain name. So we need avoid of using serial console login the
guest, otherwise the login timeout error will be raised.
=> virsh.migrate: Avoid of using console sometime

libvirt/tests/src/virsh_cmd/domain/virsh_guestvcpus.py
Add topology correction inorder to handle incorrect topology
incase of config mismatch situations.
=> Fixup: To handle incorrect topology incase config mismatch

libvirt/tests/src/virsh_cmd/domain/virsh_domjobabort.py
If open file with 'r' mode in python3, hardcoded UTF-8 encoding can not
handle byte 0xff issue.
The way to fix it is to use 'rb' mode,and decode it with locale.getpreferredencoding()
=> Fix utf-8 can not decode byte 0xff issue

libvirt/tests/cfg/timer_management.cfg, libvirt/tests/src/timer_management.py
Tsc is support timer after this patch:commit 7373c4e48f293fb4d361b1bf2d0986166d8480be.
And disabling it by present=no in xml doesn't work according to feature testing, so
close this auto scenario.
=> Timer_Management: support tsc timer, and close its present=no scenario

libvirt/tests/cfg/virsh_cmd/domain/virsh_domblklist.cfg, libvirt/tests/src/virsh_cmd/domain/virsh_domblklist.py
Automate domblkinfo command cases
RHEL-113539
Add 2 cases in domblklist
[root@localhost zongqing]# avocado run --vt-type libvirt --vt-machine-type i440fx virsh.domblklist.normal_test.domblkinfo
JOB ID     : 09e24b79132061dd38419451b3c655a280b68d0d
JOB LOG    : /root/avocado/job-results/job-2018-05-24T15.19-09e24b7/job.log
(1/1) type_specific.io-github-autotest-libvirt.virsh.domblklist.normal_test.domblkinfo: PASS (214.67 s)
JOB TIME   : 219.26 s
[root@localhost zongqing]# avocado run --vt-type libvirt --vt-machine-type i440fx virsh.domblklist.normal_test.domblkinfo_human
JOB ID     : d1181f04261f135c4c49bdeeff73910d888c3852
JOB LOG    : /root/avocado/job-results/job-2018-05-24T15.23-d1181f0/job.log
(1/1) …
=> Automate domblkinfo command cases

libvirt/tests/src/libvirt_vcpu_plug_unplug.py, libvirt/tests/src/virsh_cmd/domain/virsh_setvcpu.py
Add a check for vcpu hotunplug feature as there is
no support in certain qemu package versions and accordingly
skip the test.
=> Add a check for feature support and skip test

libvirt/tests/cfg/npiv/npiv_restart_libvirtd.cfg, libvirt/tests/src/npiv/npiv_restart_libvirtd.py
The vhba create methods are:
1. echo wwpn:wwnn > /path/to/scsi_host#/vport_create
2. virsh nodedev-create nodedev.xml
And vhba delete methods are:
1. echo wwpn:wwnn > /path/to/scsi_host/vport_delete
2. virsh nodedev-destroy scsi_host#
The case steps are:
1. create a vhba
2. restart libvirtd
3. check the vhba's xml not changed
4. delete the vhba
sign-off by Yi Sun (lentosun@163.com)
This PR depends on https://github.com/avocado-framework/avocado-vt/pull/826
=> Add cases to check vhba'x xml before and after libvirtd restarted

libvirt/tests/cfg/cpu/powerpc_hmi.cfg, libvirt/tests/src/cpu/powerpc_hmi.py
Add test to validate Pseries HMI error injection with KVM guest
running in the given cpu core.
=> Add test to validate Pseries HMI error injection with KVM guest active

libvirt/tests/cfg/virsh_cmd/network/virsh_net_autostart.cfg, libvirt/tests/src/virsh_cmd/network/virsh_net_autostart.py
net_autostart: add 2 negative scenarios, set transisent network to be
autostart; and undefine a persistent&autostart network, which will make
the network to be not autostart.
=> Add case about setting a network to be autostart

libvirt/tests/cfg/virtual_network/iface_hotplug.cfg, libvirt/tests/src/virtual_network/iface_hotplug.py
Add more plug optinos "--config" "--current" and the combination of
them for attach-device and attach-interface. And test the options both
when vm is running or inactive.
=> Add more plug options for interface

libvirt/tests/cfg/virsh_cmd/domain/virsh_memtune.cfg
Affect case virsh.memtune.negative_test.invalid_1, where the error
msg is different between RHEL7 and RHEL8. So fix it to make them
compatible
=> virsh_memtune: Error msg differ between rhel7 and rhel8

libvirt/tests/cfg/virsh_cmd/domain/virsh_domjobinfo.cfg, libvirt/tests/src/virsh_cmd/domain/virsh_domjobinfo.py
Domjobinfo is used for returning info about running domain jobs.
Modify domjobinfo.py file to do the async job by involving
get_subprocess refered from domjobabort.py. Thus domjobinfo can
get both running and completed job info. Also Reconstruct and
enrich domjobinfo.cfg file to be more clear and easier to extend
scenarios.
=> Reconstruct domjobinfo.cfg and modify its .py

libvirt/tests/cfg/migration/migrate_vm.cfg, libvirt/tests/src/migration/migrate_vm.py
In RHEL7.6, if migration without nfs setup and --copy-storage-all will
be blocked and return error "Unsafe migration: Migration without shared
storage is unsafe", while permitted in previous release.
=> migrate_vm: Fix unsafe migration error

libvirt/tests/src/virsh_cmd/domain/virsh_blockjob.py
No interval between blockcopy and blockjob --abort will cause unexpected
failure and also is not like real human activity. The fix is just give a
few seconds to wait before abort the job.
=> virsh_blockjob: wait a while before abort

libvirt/tests/cfg/svirt/dac_start_destroy.cfg, libvirt/tests/src/svirt/dac_start_destroy.py
Add two tests about dac_start_destroy:
1.Test for setting non-existing user in qemu.conf
2.Test for disable_dynamic_ownership with non_root user
Signed-off-by: yafu <yafu@redhat.com>
=> Add two tests about dac_start_destroy

libvirt/tests/cfg/virsh_cmd/domain/virsh_blockpull.cfg, libvirt/tests/src/virsh_cmd/domain/virsh_blockpull.py
Keep-relative option need to be added when doing virsh blockpull command
=> Add cases to cover blockpull with relative path backing files

libvirt/tests/src/conf_file/qemu_conf/set_virtlogd.py
In some situations, after VM shutdown,it may need additional
times to syn underlying VM data
Therefore,the solution to fix it is to add timeout sleep
=> Add sleep a few seconds before checking virtlogd pipe

libvirt/tests/src/numa/numa_memory.py, libvirt/tests/src/numa/numa_memory_migrate.py
In some cases, libvirtd may not be completely restarted sucessfully,
therefore use utils_misc.wait_for to allow for more time for libvird to be restored
=> add more wait time to allow libvirtd restarted sucessfully

libvirt/tests/src/numa/numa_memory.py, libvirt/tests/src/numa/numa_memory_migrate.py
When judge result for utils_misc return, it need use if not ret,
rathen than if ret
=> Minor fix logic error in numa_memory

libvirt/tests/cfg/virtual_disks/virtual_disks_multipath.cfg
It should be 'rawio_no' but not 'sgio_unfiltered' for this branch.
=> Fix a variant error in virtual_disks_multipath.cfg file

libvirt/tests/src/virsh_cmd/host/virsh_freepages.py
int("5.0") will raise ValueError in Python 3
=> Minorfix: float num with str type could not be int in Python 3

libvirt/tests/cfg/multivm_stress/multivm_iostress.cfg
This commit will add the required configuration for running network and disk
hotplug operations as stress events in existing multivm test.
=> Configuration to add network and disk hotplug into multivm tests

libvirt/tests/cfg/bios/virsh_boot.cfg, libvirt/tests/src/bios/virsh_boot.py
Install qemu-kvm according to the os version. For RHEL-7, install qemu-kvm-rhev,
otherwise install qemu-kvm
=> virsh.boot: Adaption to qemu-kvm update

libvirt/tests/cfg/libvirt_bench/libvirt_bench_vcpu_hotplug.cfg, libvirt/tests/src/libvirt_bench/libvirt_bench_vcpu_hotplug.py
1. Removed few tests as it is not supported test scenario,
refer https://bugzilla.redhat.com/show_bug.cgi?id=1587974
2. Modified failure messages
3. Added logic to check hot(un)plug cpus inside guest
until given timeout as it would take little longer in
some guests(older distributions) while stress is running.
=> libvirt_bench.vcpu hotplug: multiple fixups

libvirt/tests/src/virsh_cmd/domain/virsh_cpu_stats.py
The case needs the number of SC_NPROCESSORS_CONF for total host cpu
number instead of SC_NPROCESSORS_ONLN for online cpu number
=> virsh_cpu_stats: Use total host cpu number

libvirt/tests/src/virtual_disks/virtual_disks_ceph.py
/etc/libvirt/qemu-sanlock.conf exists after if libvirt-lock-sanlock and
sanlock packages have been installed.
Therefore fix this issue just by moving initializing LibvirtSanLockConfig
after packages install.
=> fix sanlock qemu-sanlock.conf not found issue

libvirt/tests/src/virsh_cmd/domain/virsh_iothreadadd.py, libvirt/tests/src/virsh_cmd/domain/virsh_iothreaddel.py, libvirt/tests/src/virsh_cmd/domain/virsh_iothreadpin.py, libvirt/tests/src/virsh_cmd/domain/virsh_update_device_matrix.py
dict.has_key method removed from python3. 
All issued files in tp-libvirt files are fixed in this PR
=> Python3: Fixup dict object has no attribute 'has_key'

libvirt/tests/src/virsh_cmd/snapshot/virsh_snapshot_create_as.py
qemu image locking feature support since qemu-kvm 2.10.
when VM is running, qemu img need add "-U" suboption otherwise
it will get failed
=> snap_shot_create_as: Fixup "No snap info in image"

libvirt/tests/src/virsh_cmd/domain/virsh_domif_setlink_getlink.py
ifdown and ifup not supported in new release
Fix them by alternative commands:ip link set up/down
=> Fix could not bring up interface enp1s0 inside guest issue

libvirt/tests/src/libvirt_bench/libvirt_bench_serial_hotplug.py, libvirt/tests/src/libvirt_bench/libvirt_bench_vcpu_hotplug.py, libvirt/tests/src/migration/migrate_vm.py, libvirt/tests/src/multivm_stress/multivm_stress.py, libvirt/tests/src/timer_management.py, libvirt/tests/src/virsh_cmd/domain/virsh_migrate_set_get_speed.py, libvirt/tests/src/virsh_cmd/domain/virsh_qemu_monitor_blockjob.py
Recently stress method from utils_test has been updated
and that requires changes to be done for testcase aswell,
this patch address it.
=> Fixup: Update test cases to adhere to library changes

libvirt/tests/src/virsh_cmd/domain/virsh_attach_device.py
File opened with wb, so need encode the writing data
to bytes to get it compatible with py2 and py3
=> Python3: Fixup error a bytes-like object is required

libvirt/tests/src/cpu/powerpc_hmi.py
Update cpuidle method name to match library,
as previous used got changed as part of review
and testcase missed update.
=> Fixup: Update cpuidle method name to match library

libvirt/tests/cfg/cpu/guestpin.cfg, libvirt/tests/src/cpu/guestpin.py
Updated testcases to use stress utils library instead
of avocado for stress testcases.
=> guestpin: Updated testcases to use stress utils library

libvirt/tests/cfg/libvirt_mem.cfg
Default hugepage size is 2MB, replaced 4KB with 2MB.
Tests now runs with out any failures.
=> update hugepage size for pagesize.

libvirt/tests/src/conf_file/qemu_conf/set_virtlogd.py
On newly release, pipe number returned by lsof is changed in field format
=> fix pipe not cleanup issue in setvirtd

libvirt/tests/src/cpu/powerpc_hmi.py
Updated library utils for running stress cases and fixed
the cpuidle method call during the end of test.
=> Updated library utils for running stress cases and minor fixup

v2v/tests/src/specific_kvm.py
string.lowercase doesn't exist in python3, replace it with string.ascii_lowercase
for compatibility of python2 and python3
=> Replace string.lowercase with string.ascii_lowercase

libvirt/tests/src/virsh_cmd/domain/virsh_cpu_baseline.py
Fix error as before as new version of libvirt have some update
error: File '/var/tmp/avocado_rCvZEW/cpu.xml' does not contain any <cpu> element or valid domain XML, host capabilities XML, or domain capabilities XML
=> Fix cpu-baseline error

libvirt/tests/src/libvirt_vcpu_plug_unplug.py, libvirt/tests/src/multivm_stress/multivm_stress.py
Add check for guest uptime to detect unexpected reboot
inbetween test.
=> Add check for guest uptime to detect unexpected reboot

.travis.yml
Since in real tp-libvirt runtime environment, python 2.6.x is not used now,
and new version 3.4 need support
=> remove python 2.6.9 travis and add 3.4 support

libvirt/tests/cfg/migration/migrate_options_shared.cfg, libvirt/tests/src/migration/migrate_options_shared.py
Qemu-kvm's new behaviour will raise the error for --comp-xbzrle-cache:
Parameter 'xbzrle_cache_size' expects is invalid, it should be bigger than target page size
and a power of two
So this is to use valid number for --comp-xbzrle-cache.
=> migrate_options_shared: Fix xbzrle_cache_size issue

libvirt/tests/src/virtual_device/watchdog.py
The current domrename method comes from the virsh module,
it only the the real vm'name, but the vm object's name is
not changed. Now, we adopt the domrename method inner avocado-vt.
=> Modify the domrename method

v2v/tests/src/v2v_options.py
When running v2v case RHEL7-84978, An exception will be raised.
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xed in position 140:
invalid continuation byte
The fix needs: https://github.com/avocado-framework/avocado-vt/pull/1658
=> Fix decode exception when running a special v2v case

v2v/tests/cfg/v2v_options.cfg, v2v/tests/src/v2v_options.py
1) Replace "--network ovirtmgmt" with "ovirtmgmt"
In virt-v2v-1.38.2-2.el8+7.x86_64, it is "--bridge ovirtmgmt" instead
of "--network ovirtmgmt". Let's just follow the description in bz1429491,
and only check string "ovirtmgmt".
2) Python3: Decode bytes-like object to string
Decode bytest-like object to string in check_result to avoid
exception in underlying functions if they do not hanlde bytes-like
problems correctly.
3) Python3: Replace string.replace with str.replace
=> Fix v2v scripts errors on rhel8

v2v/tests/src/v2v_options.py
when vm is running, then checking the image of the vm by
qemu-img, '-U' argument is needed.
=> Fix checking image issue with qemu-img

libvirt/tests/cfg/multivm_loadstress.cfg, libvirt/tests/src/multivm_loadstress.py
Users can :
1. Add 'n' number of server and clients [in pairs]
2. Provide their own customized uperf profiles, samples provided @ avocado-vt : shared/deps/uperf/
3. Custom uperf server and client commands
4. IPtable rules required for succesful network stress run
The test will
1. Create 'n' uperf server-client pairs,
2. Configure iptables in guest and install uperf
3. Kick start uperf run, wait for duration [customized given in uperf profile]
4. After run, test will check for errors and make sure all guests are reachable.
5. Cleanup temp files and iptable rules added before
=> Add generic multivm server-client stress scenarios

libvirt/tests/cfg/virsh_cmd/secret/virsh_secret_define_undefine.cfg, libvirt/tests/src/virsh_cmd/secret/virsh_secret_define_undefine.py
```
JOB ID     : 58cd8f0e57654d3e7bf040ae411f78a106c16f5f
JOB LOG    : /root/avocado/job-results/job-2018-07-14T16.58-58cd8f0/job.log
(1/2) type_specific.io-github-autotest-libvirt.virsh.secret_define_undefine.error_test.readonly.define: PASS (4.17 s)
(2/2) type_specific.io-github-autotest-libvirt.virsh.secret_define_undefine.error_test.readonly.undefine: PASS (4.47 s)
JOB TIME   : 29.82 s
```
=> Add readonly for secret define/undefine test

libvirt/tests/cfg/virsh_cmd/network/virsh_net_create.cfg, libvirt/tests/src/virsh_cmd/network/virsh_net_create.py
This PR depends on avocado-vt PR #1638. To support
create network from xml file when readonly enabled
=> virsh_net_create: Add readonly test

libvirt/tests/cfg/virsh_cmd/pool/virsh_pool.cfg, libvirt/tests/src/virsh_cmd/pool/virsh_pool.py
```
Previously:
1. After adding  <initiator> into p_xml, we didn't set
poolxml = p_xml.xml, so actually, the new pool xml is not used.
2. The case is to set iscsi initiator IQN, so we don't need
to prepare a second iscsi target to prepare a target IQN.
```
=> Fix iscsi pool multiple iqn issues

libvirt/tests/src/migration/migrate_options_shared.py, libvirt/tests/src/virsh_cmd/domain/virsh_migrate.py
Due to avocado-vt commit b43df1ff, all functions using migrate() may need adjust the parameters.
=> virsh.migrate: Adjust param for calling vm.migrate

v2v/tests/src/v2v_options.py
If don't specify any output option for virt-v2v, it will convert
guest to 'default' pool. But 'default' pool does not exist in work-
er host. Just create it if output option is none and leave it there.
It has no side-effect when it is there.
=> Create 'default' pool when output_mode is none

libvirt/tests/cfg/virsh_cmd/domain/virsh_screenshot.cfg
Previous no screen option test do not really work
```
#avocado run --vt-type libvirt virsh.screenshot.normal_test.acl_test.screen_0.name_option
JOB ID     : cc64bd5c12256c1cd7efe0585776733c436ebe54
JOB LOG    : /root/avocado/job-results/job-2018-07-09T12.15-cc64bd5/job.log
(1/1) type_specific.io-github-autotest-libvirt.virsh.screenshot.normal_test.acl_test.screen_0.name_option: PASS (41.49 s)
JOB TIME   : 69.00 s
```
=> Modify no screen option test

libvirt/tests/src/virsh_cmd/host/virsh_hostname.py
The old condition will cause other cases skipped when with remote ip not configured.
=> virsh_hostname: Update judgement for remote_ip

libvirt/tests/src/migration/migrate_vm.py
There is a migration different result from libvirt 4.3.0-1 when
migrating without shared storage and --copy-storage-all
Before: migration succeeds with image preallocation on target
host.
After: migration is forbidden.
=> migrate_vm: Compatible with old behavior

libvirt/tests/src/virsh_cmd/pool/virsh_pool_edit.py
Other functions use methods provided in libvirt_storage which gives exception
handling and inturn calls methods in virsh.py. Same should be done for build
pool
=> Minor fix: Use libvirt_storage build pool 

libvirt/tests/src/virsh_cmd/domain/virsh_domxml_from_native.py
Bring from commit 7ef2975429ca3dead6ded1e2181965372f839887
can not get qemu-kvm absolute path as it is in /usr/libexec
=> Fix issues for domxml_from_native

libvirt/tests/src/migration/migrate_vm.py
This is to update the message of canceling by client of migration.
=> migrate_vm: cancel message changed

v2v/tests/cfg/function_test_xen.cfg
V2V uses unicode single quote character instead of ascii single quote
character in error message. The original matching expression needs to
be updated.
=> Update matching expression in function_test_xen

libvirt/tests/src/virsh_cmd/domain/virsh_attach_device.py
Since legacy python (2.4-2.6) is no longer supported by avocado-vt,
now it is the time to drop the package `virttest.staging.backports`
as it is used for backward compatibility.
Signed-off-by: Xu Han <xuhan@redhat.com>
=> Drop the package virttest.staging.backports

libvirt/tests/cfg/virsh_cmd/domain/virsh_blockjob.cfg
do operations for a non-existing block job,and
expected result should fail
=> add not existing block job test case

libvirt/tests/cfg/virsh_cmd/nodedev/virsh_nodedev_detach_reattach.cfg, libvirt/tests/src/virsh_cmd/nodedev/virsh_nodedev_detach_reattach.py
Support detach nodedevice from its device driver when readonly
is enabled
=> virsh_nodedev_detach_reattach: Add readonly test for detach

libvirt/tests/cfg/multivm_stress/multivm_cpustress.cfg
Add support for parallel host events like switching
cpu frequency governor, cpu idlestates, cpu online
states.
=> Add support for host stress events

libvirt/tests/src/virsh_cmd/domain/virsh_guestvcpus.py
Make sure qemu guest is present in guest xml,
if not let's add it as it needed for test to
proceed.
=> Make sure guest agent is present in guest xml

libvirt/tests/cfg/virsh_cmd/domain/virsh_setmaxmem.cfg, libvirt/tests/src/virsh_cmd/domain/virsh_setmaxmem.py
1. Add readonly test
2. Add inactive vm test with no option
3. Fix error test matrix as they should not use Cartesian in error test
=> Add test for setmaxmem

libvirt/tests/cfg/virsh_cmd/domain/virsh_attach_detach_interface.cfg, libvirt/tests/src/virsh_cmd/domain/virsh_attach_detach_interface.py
if virsh attach or detach interface in readony mode, permission will be denied
=> add attach-detach interface with readonly case

libvirt/tests/cfg/virsh_cmd/domain/virsh_dompmsuspend.cfg, libvirt/tests/src/virsh_cmd/domain/virsh_dompmsuspend.py
Currently specific domsuspend duration value is not supported,therefore
the error message "argument unsupported: Duration not supported" is thrown
=> add specific domsuspend duration value test case

libvirt/tests/src/cpu/vcpu_hotpluggable.py
cgroup utils package is needed by `lscgroup`
command, so lets check and install if not present.
=> Install dependancy package, cgroup utils

libvirt/tests/cfg/virsh_cmd/domain/virsh_migrate_stress.cfg, libvirt/tests/src/virsh_cmd/domain/virsh_migrate_stress.py
This patch enables new stress migration scenarios,
- stress source host and migrate VMs(without stress) from source <-> target
- stress source host and migrate VMs(with stress) from source <-> target
- stress remote target host and migrate VMs(without stress) from source <-> target
- stress remote target host and migrate VMs(with stress) from source <-> target
- stress source and stress target and migrate VMs (without stress) source <-> target
- stress source and stress target and migrate VMs (with stress) source <-> target
currently stress and stress-ng tools are added and given place holder to use
any stress tool like iozone, kselftest, ltp etc., by using HostStress and VMStress
APIs directly instead of using load_stress().
=> virsh_migrate_stress: Enable stress migration scenarios

libvirt/tests/cfg/virsh_cmd/network/virsh_net_update.cfg, libvirt/tests/src/virsh_cmd/network/virsh_net_update.py
#avocado run --vt-type libvirt net_update
RESULTS    : PASS 296 | ERROR 1 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 87
1 Error because of existing bug - Connections for other interfaces will be gone in net-dumpxml when live delete physical interface in macvtap network 
87 CANCEL because not support operation
Detailed test result
https://pastebin.com/G8Jy3xHD
It depends on PR https://github.com/avocado-framework/avocado-vt/pull/1097
=> Add new cases for net-update testing

libvirt/tests/cfg/virsh_cmd/domain/virsh_blockcopy.cfg
add exclusive options scenarios cases into blockcopy
and command should throw error when mix use of exclusive options
=> add invalid exclusive option cases into blockcopy

libvirt/tests/cfg/sriov/sriov.cfg, libvirt/tests/src/sriov/sriov.py
device attached by persistent option should be there after VM reboot
=> add case to cover attach hostdev with --persistent option

libvirt/tests/src/virsh_cmd/domain/virsh_console.py
PAPR guests don't usually have a true serial device (ttyS0),
they only have the hypervisor console (/dev/hvc0). Using invalid
device configured in guest kernel cmdline cause killing init
panic during guest boot.
Kernel panic output:
[  117.056098] shutdown: 7 output lines suppressed due to ratelimiting
[  117.058785] Kernel panic - not syncing: Attempted to kill init! exitcode=0x00000100
[  117.058785]
[  117.060152] CPU: 6 PID: 1 Comm: shutdown Not tainted 4.11.0-44.2.1.el7a.ppc64le #1
[  117.061281] Call Trace:
[  117.061645] [c0000000fda83c60] [c000000000c095c8] dump_stack+0xb0/0xf0 (unreliable)
[  117.062786] [c0000000fda83ca0] [c000000000bfd624] panic+0x150/0x31c
[  117.063726] [c0000000fda83d30] [c00000000012d5ec] do_exit+0xcdc/0xce0
[  117.064688] [c0000000fda83df0] …
=> virsh_console: use hypervisor console hvc0 for PAPR guests

v2v/tests/src/convert_vm_to_ovirt.py
1.add win2016 windows version to liwq
Signed-off-by: weikun <weikunzz@qq.com>
=> v2v: Add win2016 to windows version list in convert_vm_ovirt file

libvirt/tests/src/virtual_network/iface_network.py
The test-cases are failing due to incorrect package name for Ubuntu.
=> Fixed distro specific issues for "iface_network.dnsmasq_test".

libvirt/tests/src/nwfilter/nwfilter_vm_start.py
The "nwfilter_vm_start" test-cases are failing due to distro specific commands.
Made the code more generic for the package installation.
=> Fixed "nwfilter_vm_start" test-case for package installation issue

libvirt/tests/cfg/virsh_cmd/domain/virsh_migrate.cfg, libvirt/tests/src/virsh_cmd/domain/virsh_migrate.py
Test should not just cancel when "unsupported conf" error happens 
during migration, because it is expected for some test cases. Add
a variable to distinguish when error "unsupported conf" is expected
=> Add variable unsupported_conf

libvirt/tests/src/virsh_cmd/domain/virsh_change_media.py
In case 'disk_alias' referenced before assignment
=> virsh_change_media: Minor fix

libvirt/tests/cfg/virsh_cmd/domain/virsh_blockjob.cfg
blockjob --info and --bandwidth can combine with bytes options
and expected output unit is bytes
=> add blockjob bytes options cases

libvirt/tests/src/virsh_cmd/host/virsh_hostname.py
use `hostname -f` command to get fully qualified domain name which
have to be asserted with virsh hostname, otherwise test fails with,
```
TestFail: Virsh cmd gives hostname hostname.domain.name.com != hostname
```
=> virsh_hostname: virsh hostname returns fully qualified domain name

libvirt/tests/cfg/migration/migrate_options_shared.cfg, libvirt/tests/src/migration/migrate_options_shared.py
Multiple PHB is supported in papar guest already. This is to test the migration
with multiple PHB between two PPC hosts.
=> migrate_options_shared: Add new case for mPHB migration

libvirt/tests/cfg/libvirt_rng.cfg
Encountered rate exceeds failure, reduce period to check more
accurate rng rate, since bug1205141 said rate exceeds is
acceptable when period is big.
=> Reduce rng period per bug1205141

libvirt/tests/src/virsh_cmd/domain/virsh_migrate.py
Disk cache mode can be either "none" or "directsync" for a safe migration
=> Add disk cache mode "directsync" to unsafe migration check

libvirt/tests/src/libvirt_vcpu_plug_unplug.py
expected vcpu check result gets stored in a boolean variable,
so there is a chance that we will loose the initial failure
status, hence this patch addresses it by replacing it with a
integer and increase the failure count and failout appropriately.
=> Fixup: Avoid missing initial failure status

libvirt/tests/cfg/migration/migrate_vm.cfg
The parameter can provide the migration setup which help control
firewalld ports before and after migration.
=> migrate_vm: Add one parameter for setup

libvirt/tests/cfg/virsh_cmd/domain/virsh_domiftune.cfg, libvirt/tests/src/virsh_cmd/domain/virsh_domiftune.py
1) Add 'config' option test
2) Add set_domiftune by interface name or by MAC address
3) Add outside boundary test
=> virsh_domiftune: Support 'config' option with mac address

libvirt/tests/cfg/migration/migrate_vm.cfg
The original name "no_create_target_image" for the negative case
in live storage migration is not proper any more and is ambiguous,
as libvirt has been able to create target image automatically as long
as storage pool exists on target host.
=> Rename case *.no_create_target_image.*

libvirt/tests/cfg/virsh_cmd/volume/virsh_vol_create.cfg
1. Luks encrypted volume can be created in disk and logical
pool now (bz1560946 and bz1427049), cases added.
2. Virsh cmd 'vol-create-as' doesn't have encryption related
parameters, remove useless cases.
3. Reconstruct the cfg file to make it more clear for
luks_encryption/non_encryption level.
=> Add vol creation cases for disk and logical pool

libvirt/tests/cfg/virsh_cmd/monitor/virsh_domstate.cfg, libvirt/tests/src/virsh_cmd/monitor/virsh_domstate.py
Even after libvirtd restart, domstate --reason still can return correct boot information
=> add check domstate reason case after restart libvirtd

libvirt/tests/src/serial/serial_functional.py
This might be happening when a client program doesn't wait
till all the data from the server is received and simply closes a socket
=> fix brokenpipeerror when close socket

libvirt/tests/cfg/remote_access/remote_with_ssh.cfg
Add the remote access case of ssh connection between two hosts with
the same libvirt version via ipv4
=> Add the cases of ssh connection via ipv4

libvirt/tests/src/numa/guest_numa.py
All of the 2M, 16M and 1G will work with the _update_qemu_conf.
so remove the hp_cl.setup
=> Update the guest_numa

v2v/tests/cfg/convert_from_file.cfg, v2v/tests/cfg/convert_vm_to_ovirt.cfg, v2v/tests/cfg/function_test_esx.cfg, v2v/tests/cfg/function_test_xen.cfg, v2v/tests/cfg/specific_kvm.cfg, v2v/tests/cfg/v2v_options.cfg
When importing some guests which have large images, like windows
guests, in some special conditions, the speed is slow and 1200s
is not enough. Let's update the value to 2400s to verify it.
=> Update v2v_timeout value

provider/v2v_vmcheck_helper.py, v2v/tests/cfg/function_test_esx.cfg, v2v/tests/cfg/function_test_xen.cfg
Since win2003 is out of service, the testing guest should be
updated.
Replace Auto-xen-win2003-2ProgramFiles with Auto-esx6.7-win2016-2ProgramFiles
=> Replace win2003 guest with win2016

libvirt/tests/src/virsh_cmd/volume/virsh_vol_create.py
In python3, stderr_text is required instead of
stderr when with process.run
=> Python 3 fix: a bytes-like object is required

libvirt/tests/src/conf_file/qemu_conf/auto_dump.py
Avoid to raise CmdError "that process can not found" when trying
to kill the dump process when dump already accomplished
=> auto_dump: Add exception handling to kill process

libvirt/tests/cfg/migration/migrate_options_shared.cfg, libvirt/tests/src/migration/migrate_options_shared.py
Libvirt supports <htm state='xxx'/> feature on PPC now. So this is to
test the migration with htm feature setting.
=> migrate_options_shared: Add case for htm migration

libvirt/tests/src/virtual_network/iface_network.py
The test-case was failing in Ubuntu during 'libvirt' package installation.
=> Fixed distro specific issues for "iface_network"

libvirt/tests/cfg/virsh_cmd/interface/virsh_iface_bridge.cfg, libvirt/tests/src/virsh_cmd/interface/virsh_iface_bridge.py
The script required to manually configure the iface_name in cfg file,
but it's hard when CI running, cos the iface_name is varied from servers,
so it's better to get the iface_name by script instead of manual configuration.
besides fix some other issues during this PR testing, as this script never
been successfully executed
=> virsh_iface_bridge: Fix Interface 'HOST_INTERFACE' not exists

libvirt/tests/src/virtual_device/watchdog.py
Fix in two aspect:
1) The name of i6300esb watchdog in dmesg has been changed to "i6300ESB", so
ignore case distinctions for grep patterns by adding the option "-i"
2) Change the method of getting the last reboot time. Since the original
method was to get the day of the last reboot time, it will always be the
same with the ones of last reboot time.
=> Fix the cases of watchdog

libvirt/tests/cfg/svirt/svirt_attach_disk.cfg, libvirt/tests/src/svirt/svirt_attach_disk.py
Add checkpoint for disk selinux context after guest started:
1.Enable namespaces(default setting) and check；
2.Disable namespaces and check;
=> Add checkpoint for disk selinux context after guest started

libvirt/tests/src/npiv/npiv_restart_libvirtd.py
The vhba created by echo command is not synced with virsh command.
So libvirt may not get its fabric name at once. Add a 2 seconds
sleep to avoid info missing. A waitfor method is not necessary
for such a short sleep.
=> fix vhba fabirc not setting issue

libvirt/tests/cfg/npiv/npiv_hostdev_passthrough.cfg
Should set status_error as 'no' for positive cases.
=> Fix a wrong setting of status error in npiv hostdev case

libvirt/tests/cfg/virsh_cmd/network/virsh_net_edit.cfg, libvirt/tests/src/virsh_cmd/network/virsh_net_edit.py
The old script only covered "modify changeable attributes", and hard 
coded the attribute to modify. This PR extended the cases to be more
flexible as follows:
1. support 'delete' operation
2. support "unchangeable" attributes. 
3. net_edit_readonly supported
4. configurable params
=> virsh_net_edit: Add extensive cases for more edit operations

libvirt/tests/cfg/virsh_cmd/domain/virsh_event.cfg, libvirt/tests/src/virsh_cmd/domain/virsh_event.py
Enrich lifecycle events. And optimize the check_output function to
compare output with expected ones in order, to avoid matching
duplicated ones. Also remove timeout for lifecycle events, no need
to test it everywhere.
=> virsh_event: Enrich lifecycle events

libvirt/tests/cfg/migration/migrate_vm.cfg, libvirt/tests/src/migration/migrate_vm.py
Migration should be done on both hosts running firewalld if any. So this
is to enable special port on target host which is not done before.
=> migrate_vm: Enable port on target host

libvirt/tests/src/virsh_cmd/network/virsh_net_update.py
virsh_net_update.py: modify the kill command to always return 0.
Kill the dhclient process only when it exists. This avoid the "no option"
error for kill command, and always return 0.
=> Fix the error when there is no process to kill

libvirt/tests/src/virsh_cmd/volume/virsh_vol_clone_wipe.py
Previously the vol-clone expects failure for luks image, since
it was not supported. But this function is supported in latest
libvirt, so remove the clone_status_error=True and use blacklist
to filter it out in unsupported libvirt version.
=> Remove the clone_status_error=True when disk is luks format

libvirt/tests/cfg/virsh_cmd/domain/virsh_blockcommit.cfg, libvirt/tests/cfg/virsh_cmd/domain/virsh_blockcopy.cfg, libvirt/tests/cfg/virsh_cmd/domain/virsh_blockpull.cfg, libvirt/tests/cfg/virsh_cmd/snapshot/virsh_snapshot_disk.cfg
We'll meet bz1656306 if we still use the fsid=0, so remove it
from current cases.
=> Remove fsid=0 for nfs export

libvirt/tests/src/virsh_cmd/network/virsh_net_start.py
To make sure 'default' network will be started after test executed
Update old way of executing virsh command with negative acl tests
to avoid polkit error
=> Add try-except to old test code

libvirt/tests/cfg/virsh_cmd/network/virsh_net_define_undefine.cfg, libvirt/tests/src/virsh_cmd/network/virsh_net_define_undefine.py
Define nat network should check the nat port, and the dhcp range. The
address should in the same subnet of the dhcp range and the sequence of
the dhcp range and port range should also be checked.
=> Add negative test for define nat network

libvirt/tests/cfg/svirt/dac_nfs_disk.cfg, libvirt/tests/cfg/svirt/dac_vm_per_image_start.cfg, libvirt/tests/src/svirt/dac_nfs_disk.py, libvirt/tests/src/virsh_cmd/snapshot/virsh_snapshot_disk.py
fsid=0 misused here, in nfsv4, the path to the export dir will be
missing with current code. Cause a access denied error.
=> remove fsid=0 for nfs prepare

libvirt/tests/src/virtual_disks/virtual_disks_multidisks.py
Since allow_disk_format_probing is removed from libvirt-4.5, we will not
test it in tp-libvirt.
=> virtual_disks: Check auto disk format probe 

libvirt/tests/src/virsh_cmd/domain/virsh_managedsave.py
Set ignore_bg_processes=True while running flag check
=> Fix issue of Checking flags failure of managedsave cases

libvirt/tests/cfg/virsh_cmd/domain/virsh_shutdown.cfg, libvirt/tests/src/virsh_cmd/domain/virsh_shutdown.py
filter out acpi mode test for PowerPC and fix argument error for
fail(),
```
ERROR: fail() takes at most 2 arguments (3 given)
```
xml sync() in finally block fails due to timing issue, so ensure
libvirtd is in running status and the sync the xml.
```
018-12-07 01:06:46,995 vm_xml           L0637 DEBUG| Failed to backup virt-tests-vm1.
2018-12-07 01:06:47,026 virsh            L1434 WARNI| VM virt-tests-vm1 does not exist
2018-12-07 01:06:47,027 virsh            L1381 DEBUG| Define VM from /var/tmp/xml_utils_temp_ZLJFNT.xml
2018-12-07 01:06:47,058 vm_xml           L0627 DEBUG| Define virt-tests-vm1 failed.
Detail: error: failed to connect to the hypervisor
error: Failed to connect socket to '/var/run/libvirt/libvirt-sock': Connection refused
.
2018-12-07 01:06:47,166 stacktrace       L0041 …
```
=> virsh_shutdown: acpi is not supported in PowerPC

libvirt/tests/cfg/virsh_cmd/domain/virsh_migrate_copy_storage.cfg, libvirt/tests/src/virsh_cmd/domain/virsh_migrate_copy_storage.py
Since libvirt-4.4, --copy-storage-{all,inc} can work together with
--tls. Add variants for tls.
Libvirt bug reference: https://bugzilla.redhat.com/show_bug.cgi?id=1300772
=> virsh_migrate_copy_storage: Add tls option tests

libvirt/tests/src/virsh_cmd/network/virsh_net_update.py
After pkill, the process may still exists in a short time. So add a
sleep time after the kill command.
=> Add sleep time in the commands to avoid failure

libvirt/tests/cfg/virsh_cmd/network/virsh_net_define_undefine.cfg, libvirt/tests/src/virsh_cmd/network/virsh_net_define_undefine.py
Define network with multiple ip sections including ipv4 and ipv6 is
accepted. And define network with multiple dhcp sections is not allowed.
=> Define network with multiple ip/dhcp sections

provider/v2v_vmcheck_helper.py, v2v/tests/cfg/convert_vm_to_libvirt.cfg, v2v/tests/cfg/convert_vm_to_ovirt.cfg, v2v/tests/src/convert_vm_to_libvirt.py, v2v/tests/src/convert_vm_to_ovirt.py
1) Update rhel7 and rhel6 testing guests to latest version
2) Add win2019 guest support
3) Update cfg variant name for rhel7 and rhel6 to a fixed name,
this can avoid case name changes when testing version changes.
=> Update testing guests for V2V

libvirt/tests/src/migration/migrate_vm.py
Existing logic has issues which make case result not statble. The cache
setting can be done when installing the remote guest.
=> migrate_vm: Remove remote disk cache setting

libvirt/tests/cfg/virsh_cmd/domain/virsh_domtime.cfg, libvirt/tests/src/virsh_cmd/domain/virsh_domtime.py
Fixup domtime issue due to guest's time zone difference
due to day light savings in certain regions, so it affects
the guest time considerably when we change time for tests and
add param for vm stop duration.
=> Fixup: virsh domtime issue due to guest's time zone differences

libvirt/tests/src/virsh_cmd/domain/virsh_vcpupin.py
From libvirt 4.9, the output is changed from 'a:b' to
'a     b'
=> Minorfix: Fixup the split key

libvirt/tests/cfg/virsh_cmd/domain/virsh_event.cfg, libvirt/tests/src/virsh_cmd/domain/virsh_event.py
Add 'tray-change' event. Modify 'edit' with act on 'description',
to avoid cpu topology error when edit vcpu. Fix 'shutdown' event
order issue due to time delay by adding time sleep.
=> virsh_event: Add tray-change event and fix issues

libvirt/tests/src/nwfilter/nwfilter_vm_attach.py
When hotplug interface, the default model type is rtl8139 which is a pci
device not a pcie device. This will cause "no pcie slots" issue on q35
machine type. And virtio model has higher priority than rtl8139.
=> Fix the hotplug interface failure

libvirt/tests/src/migration/migrate_vm.py
This is required for migration with --disk-port option.
=> migrate_vm: Enable a port on remote host

libvirt/tests/src/virsh_cmd/domain/virsh_migrate.py
In Python 3, / is float division
In Python 2, / is integer division (assuming int inputs)
In both 2 and 3, // is integer division
=> Python3: Fix division operator in virsh_migrate.py

libvirt/tests/src/virsh_cmd/domain/virsh_event.py
when attach a interface to a q35 guest, 'virtio' model type should
be used, the default 'rtl8139' will meet error "No more available
PCI slots".
=> virsh_event.py: fix q35 adapt for attach-device

libvirt/tests/src/virsh_cmd/domain/virsh_migrate.py
virsh console session is used to take vcpu count after guest is migrated
to target host, so other dmesg printed on console due to cpu hotplug event
is taken along with lscpu value cause validation to fail. use wait_for()
to avoid while loop and check the vcpu count after 5 sec of hotplug event
so that appropriate value is considered for validation.
=> virsh_migrate: check hotplug vcpu using wait_for()

libvirt/tests/src/serial/serial_functional.py
Fix following error msg caused by two 'None' type variables
in re.match(exp_ser_dev, ser_dev) when testing virtio console
TypeError: first argument must be string or compiled pattern&#10;
Signed-off-by: jiyan <jiyan@redhat.com>
=> Fix "TypeError: first argument must be string" failure in virtio console

libvirt/tests/src/npiv/npiv_restart_libvirtd.py
When directly restart libvirtd, sometimes the daemon is not started
completely, and followed up commands will be failed. So change to
use the restart() in utils_libvirtd.Libvirtd class, which will
resolve the problem.
=> Use utils_libvirtd's restart instead of directly restart libvirtd

libvirt/tests/src/serial/serial_functional.py
Add spice 'graphics' device when testing spiceport 'serial' device
Signed-off-by: jiyan <jiyan@redhat.com>
=> Fix "TypeError: expected string or buffer&#10;" failure in spiceport serial

libvirt/tests/src/serial/serial_functional.py
Computing 'string' type variable and 'bytes' type varible,
when testing console_type is 'tcp' or 'unix'.
Signed-off-by: jiyan <jiyan@redhat.com>
=> Fix "UnicodeDecodeError: 'utf-8'..." failure in tcp_server and unix serial

libvirt/tests/src/graphics/graphics_functional.py
rally defect LIBVIRTAT-3267
test case failed with strange syntax error as follows:
ValueError: invalid interpolation syntax in
'0000:0000:0000:0000:0000:0000:0000:0001%1' at position 39&#10;
expected_result is a list of IPAddress which has a addr attribute.
Therefore, it is correct to use .addr to get correct ipv6 address.
=> libvirt autotest vnc ipv6 series case failed

libvirt/tests/cfg/virsh_cmd/domain/virsh_detach_device.cfg
On q35 machine type, only virtio bus can be supported
=> Fix detach_device cdrom test cases

libvirt/tests/src/virsh_cmd/domain/virsh_migrate_stress.py, libvirt/tests/src/virsh_cmd/domain/virsh_migration.py
We need to update the parameter passed to check_vm_state() accordingly
after the defination changed in avocado-vt
=> Update the parameter passed to check_vm_state()

libvirt/tests/cfg/virsh_cmd/domain/virsh_change_media.cfg, libvirt/tests/src/virsh_cmd/domain/virsh_change_media.py
IDE controller is not supported on q35,and sata and scsi are preferred.
=> Fix change media failure cases on q35 machine type

libvirt/tests/cfg/virsh_cmd/domain/virsh_event.cfg, libvirt/tests/src/virsh_cmd/domain/virsh_event.py
On q35 machine type, IDE controller type is not supported, and
scsi or sata are preferred.
Moreover, some hardcarded string match is removed with self adapted parameter
=> Fix virsh event case failures due to unsupported IDE controller on q35

libvirt/tests/cfg/virsh_cmd/volume/vol_concurrent.cfg
test case vol_concurrent is designed to check whether libvirt throw
a error when there is simultaneous volume operations
This commit change the number of new volumn to be created during vol
deleting to 100 so that simultaneous volume operation will definitely
happen
=> fix vol_concurrent: change the number of new volumn to 100

libvirt/tests/cfg/virtual_network/mtu.cfg, libvirt/tests/src/virtual_network/mtu.py
As mtu is only supported by virtio model type, so add the model type in
the interface xml setting. And delete the openvswitch bridge after test.
And sleep for 5s after detach, then check to avoid the check failure.
=> Fix some script issue in mtu.py

libvirt/tests/cfg/libvirt_mem.cfg
Hotplug xml will have node tag by default, due to which the test
fails to hotplug on non numa systems. Patch will not add node tag
for non numa systems.
=> Ignore numa node for non-numa systems

libvirt/tests/src/virsh_cmd/domain/virsh_domjobinfo.py
Add new item 'Postcopy requests' in expected info_list, which is
involved from libvirt-5.0.0 version.
=> virsh_domjobinfo.py: add 'Postcopy requests' item

libvirt/tests/src/virsh_cmd/domain/virsh_attach_detach_interface.py, libvirt/tests/src/virsh_cmd/domain/virsh_migrate_copy_storage.py, libvirt/tests/src/virsh_cmd/domain/virsh_qemu_agent_command.py
fix runtime error as follows:
AttributeError: module 'avocado.core.exceptions' has no
attribute 'TestNAError'
=> replace the deprecated exception TestNAError with TestCancel

libvirt/tests/src/graphics/graphics_functional.py
The test case failed with ValueError: invalid interpolation syntax in
'2620:0052:0000:49e0:6651:06ff:fe0e:2db0%2' at position 39
The error was found when trying to get ipv6 addr from a list of
IPAddress which has a addr attribute. Instead of using IPAddress
to get ipv6 address directly, the .addr should be used to get
correct ipv6 address
=> fix libvirt test spice_listen_ipv6

v2v/tests/cfg/function_test_esx.cfg, v2v/tests/cfg/v2v_options.cfg, v2v/tests/src/v2v_options.py
1) extend v2v_timeout value
2) Modify USER.V2V_EXAMPLE to USER_V2V_EXAMPLE
3) Modify the way of checking '-q' option, even if '-q' is used, warning
or errors still can be printed.
4) Modify ovmf checking for rhel8
=> Fix some v2v problems

libvirt/tests/cfg/virsh_cmd/domain/virsh_attach_detach_interface.cfg, libvirt/tests/src/virsh_cmd/domain/virsh_attach_detach_interface.py
When attach interface, use recommended 'virtio' model instead of
the default rtl8139. Also it can avoid rtl8139 not working for q35
machine type.
=> Use recommended 'virtio' model for interface

v2v/tests/cfg/function_test_esx.cfg
In 3306b3b93436209a2c86ea98abdcb74dc107b2c6, some format error was
involed. This patch fixes the error.
=> Fix some format error in cfg file

libvirt/tests/src/virsh_cmd/domain/virsh_event.py
Set ignore_status=False for event actions, to show detail errors
as failure msgs, since no event will be caught if action fails.
=> virsh_event.py: dont ignore action failure

libvirt/tests/cfg/virtual_disks/virtual_disks_multidisks.cfg
disks_attach_option is not initialized correctly in the cfg file,
which leads to wrong attach option
=> Fix virtual disk attach failures due to uninitialized variable value

libvirt/tests/src/virsh_cmd/network/virsh_net_dhcp_leases.py
Replace split('\n') with splitlines()
=> Fix issue of passing empty string as pid to be killed

libvirt/tests/src/migration/migrate_vm.py
Default timeout 60 seconds is not practical sometimes in migration. This
is to allow more seconds for migration to finish from target host to
source host.
=> migrate_vm: Add timeout for migration

libvirt/tests/cfg/cpu/guestpin.cfg
fix a typo in cpuset_vcpupin cfg file
pin_type --> pintype
=> fix a typo in cpuset_vcpupin cfg file

libvirt/tests/cfg/libvirt_mem.cfg
The test binding method is not fit for hugepages cases since the memory
is binded when it is startup
=> Fix the ramdom failure for libvirt_mem.positive_test.hugepages

libvirt/tests/src/virsh_cmd/domain/virsh_reboot.py
asserting the domstate in negative tests is not required
so avoid it for them.
=> virsh_reboot: avoid check for domstate in negative tests

libvirt/tests/cfg/cpu/max_vcpus.cfg, libvirt/tests/src/cpu/max_vcpus.py
- Guest vcpu > 255 is supported on q35 guest with extended
interrupt mode enabled on the iommu device
=> Add case of maxvcpus

libvirt/tests/cfg/migration/migrate_vm.cfg, libvirt/tests/src/migration/migrate_vm.py
IDE controller is deprecated for q35 machine type; while scsi
controoler is available for both i440fx and q35 machine type.
=> Attach cdrom device to scsi controller instead of IDE controller

libvirt/tests/src/cpu/max_vcpus.py, libvirt/tests/src/virsh_cmd/domain/virsh_managedsave_extra.py
The purpose of using the expression "if 'result' in locals()" is
to check 'result' only if there is a 'result' to be checked. But
the var name 'result' is too common, too much risk to be used in
another way, being another var and not need to be checked.
Therefore, we rename this var to make it unique.
=> Rename result in case the name being used in other ways

libvirt/tests/src/virsh_cmd/domain/virsh_cpu_compare.py
Libvirt error message has been changed in newer libvirt
versions, so let's handle all possible error message strings.
=> virsh.cpu_compare: Handle libvirt error message check

libvirt/tests/src/virsh_cmd/domain/virsh_sendkey.py
Ensure VM boots in text only mode, so that sendkey keystrokes
succeed to create a file and validate it accordingly.
=> virsh_sendkey: sendkey fails to create file if VM boots in GUI

libvirt/tests/src/virtual_disks/virtual_disks_multipath.py
Set variable default to False and change 'mpath_conf_exist' to
'multipath_conf_exist' to avoid conflicting with existing variable
name.
=> Fix a variable referenced before assignment issue

libvirt/tests/cfg/cpu/cpuset_offline_hostcpu.cfg, libvirt/tests/src/cpu/cpuset_offline_hostcpu.py
This testcase is based on defect
https://bugzilla.redhat.com/show_bug.cgi?id=852688
Test whether kvm guest can start after offlining part of unrelated host cpus
1. online 4 host cpus
2. config a vm with cpuset='0-1'
3. shutdown vm
4. offline unrelated host cpu '2-3'
5. start the vm
Expected results:
vm start successfully after offlining part of unrelated host cpus
=> add new test case cpuset_offline_hostcpu

v2v/tests/cfg/specific_kvm.cfg, v2v/tests/src/specific_kvm.py
Virtio is only supported by redhat VM, it's not a valid scenario
for converting a virtio guest to rhv or other redhat systems.
=> Delete invalid scenarios for virtio releated cases

libvirt/tests/src/virtual_disks/virtual_disks_ceph.py
A 'rbd info attach.img' action before qemu-img convert is not a
checkpoint for function, and 'no such file' is as expected since
it will be removed in previous steps even it exists. So hide this
redundant error to avoid confusing testing result msgs.
=> virtual_disks_ceph.py: hide redundant error

libvirt/tests/cfg/virtual_network/iface_update.cfg, libvirt/tests/src/virtual_network/iface_update.py
depends on 
https://github.com/avocado-framework/avocado-vt/pull/1205
https://github.com/avocado-framework/avocado-vt/pull/1207
1. Forbid to update/modify queues value of interface element
2. Update mtu in interface or network, save and restore with mtu setting
3. Update interface setting in running domain with update-device include
model type, driver, rom, floor, bandwidth, link state, source network,
target name, right mac with wrong pci address, fileter
=> Add test for interface update with update-device

libvirt/tests/cfg/virsh_cmd/domain/virsh_setvcpus.cfg, libvirt/tests/cfg/virsh_cmd/monitor/virsh_dominfo.cfg, libvirt/tests/cfg/virsh_cmd/monitor/virsh_domstate.cfg, libvirt/tests/src/virsh_cmd/domain/virsh_setvcpus.py, libvirt/tests/src/virsh_cmd/monitor/virsh_dominfo.py, libvirt/tests/src/virsh_cmd/monitor/virsh_domstate.py
Fix following error for dominfo remote test:
ShellTimeoutError: Timeout expired while waiting for shell
command to complete: 'virsh -c qemu+ssh://10.73.224.52/system
dominfo avocado-vt-vm1'    (output: &quot;root@10.73.224.52's
password: &quot;)
=> Fix 'ShellTimeoutError' for dominfo remote test

libvirt/tests/src/numa/numa_memory.py
Numa nodes list has node numbers in int, while printing the same
it has TypoError, Hence before printing coverting it to string.
=> Fix TypoError while printing numa nodes.

libvirt/tests/src/virsh_cmd/domain/virsh_attach_detach_disk.py
For detach disk when vm is suspend, vm needs some time to clean the
detached disk after resume. Add waiting code for that.
=> attach_detach_disk: Wait for few seconds after resume

libvirt/tests/src/serial/serial_functional.py
Use re to match different pci bus for pci serial device
=> Fix expected qemu cmd line err for pci serial

libvirt/tests/cfg/virsh_cmd/domain/virsh_console.cfg, libvirt/tests/src/virsh_cmd/domain/virsh_console.py
Adding 'guest kernel option console=ttyS0,115200' is not necessary
when these options are already in VM image file
Deleting these parameters also causes problems
Failing to remove guest kernel option occurs occasionally
Besides, the later auto jobs demanded 'virsh console' usage
can not succeed once removing guest kernel option successfully.
=> Fix "failed to remove tty related kernel cmd line" issue

libvirt/tests/cfg/migration/migrate_options_shared.cfg, libvirt/tests/src/migration/migrate_options_shared.py
- cache safe/unsafe test
Safe cache mode:
none
directsync
Unsafe cache mode(must add --unsafe in order to migrate successfully):
writeback
unsafe
writethrough
default
without cache element in domain xml
- migrate-uri tcp:
=> migrate_options_shared: Add migration cases

libvirt/tests/src/numa/guest_numa.py
'n' is a local var that only effect in the loop, therefore
referencing var 'n' outside the loop is illegal.
Replace 'n' with the value that 'n' should be after the loop to
fix the problem.
=> Fix the problem of local variable 'n' referenced before assignment

libvirt/tests/src/virsh_cmd/domain/virsh_detach_device.py
1. Change the tmp dir to avoid permission issues
2. Add short sleep to make sure detach_device operation succeed
=> Fix detach_device failures

v2v/tests/src/v2v_options.py
1) Remove '-v -x' options for '--machine-reable' because in latest
v2v it will print some debug info like "rm -rf '/var/tmp/xxx'".
2) Only check the items is in output is enough, v2v may inserts
some new options in old output, it will fail in old checking way.
=> Update the way of checking machine_readable options

provider/v2v_vmcheck_helper.py
In rhel8 guest, when it boots up, no 'qxl' in /var/log/Xorg.0.log.
We just check if it contains 'qxl' by lspci command.
=> Fix Video driver checking in Xorg log for rhel8 guest

libvirt/tests/src/virtual_disks/virtual_disks_ceph.py
Libvirt reports more detail error message on readonly disk snapshot
since v5.0(commit 067aad26). Adjust error message expectation for that
change.
=> virtual_disks_ceph: Adopt new err msg for readonly disk snapshot

libvirt/tests/src/virtual_disks/virtual_disks_ceph.py
When guest OS is not initialized sufficiently, it is likely that
hot-plug will return success but nothing attached. To avoid this known
issue, wait for OS boot before hot-plug.
The known issue reference:
https://www.redhat.com/archives/libvirt-users/2019-March/msg00008.html
=> virtual_disks_ceph: Wait os boot before hot-plug disk

libvirt/tests/cfg/cpu/setvcpu.cfg, libvirt/tests/src/cpu/setvcpu.py
Test setvcpu feature as follows:
positive test:
1. run virsh setvcpu with option --enable and --disable on inactive vm
and check xml
2. run virsh setvcpu with option --enable and --disable on active vm and
check xml and number of online vcpu
3. run virsh setvcpu with option --enable, --disable and --config on
active vm and check inactive xml
negative test:
1. run virsh setvcpu with more than one vcpu on active vm and check error
=> add new test case setvcpu

v2v/tests/cfg/convert_from_file.cfg
As previous win2008r2 can't login after v2v conversion, use 
win2019 to replace it.
=> Replace the old windows guest for virt-v2v aws testing

libvirt/tests/cfg/virtual_network/iface_hotplug.cfg, libvirt/tests/cfg/virtual_network/iface_network.cfg, libvirt/tests/src/virtual_network/iface_hotplug.py, libvirt/tests/src/virtual_network/iface_network.py
Add a new attribute in rom element "enabled" and it can be "yes" or "no", default if no set is "yes". Set to "no" to disable network boot.
1. Test for xml and related combination with <rom enabled='no'>, <rom enabled='yes'>
2. Test for update-device, hotplug, define, start
=> Add test for rom enable updating

libvirt/tests/src/virsh_cmd/domain/virsh_vcpupin.py
If the cpus_list has too many cpus, then only test the
cpus of the head, middle and tail part
=> Shorten the cpus_list if it's too long

provider/v2v_vmcheck_helper.py
If the image's OS system is installed with bus=IDE, the device.map
will be '(hd0) /dev/sda'. Then if users create a new vm by this image,
and specify the bus to virtio, and after converting by virt-v2v,
v2v will give a warning and doesn't update /dev/sda to /dev/vda in
device.map.
This is a scenario only occurs when converting from KVM. Let's update
the checkpoint and just give a warning instead of fail the case for
this scenario.
=> Update checkpoint for device.map if converting from KVM

libvirt/tests/src/virsh_cmd/domain/virsh_event.py
Do not destroy vm when 'edit', otherwise later 'shutdown' action
can not be executed.
=> virsh_event.py: fix 'edit' condition

libvirt/tests/cfg/migration/migrate_options_shared.cfg, libvirt/tests/src/migration/migrate_options_shared.py
Add some native tls migration cases
- not verify client
- inconsistent server_cn and server host name
- verify client + postcopy-after-precopy
=> migrate_options_shared: add tls migration cases

libvirt/tests/cfg/multivm_stress/multivm_cpustress.cfg, libvirt/tests/src/multivm_stress/multivm_stress.py
Added a custom stress event subtest to have custom user defined
guest and host events, it would help user not to mislead when
we want override the default param setting for a test, and let's
skip uptime check for guest reboot test.
=> Add custom stress event test and skip uptime check for reboot test

libvirt/tests/cfg/controller/pcibridge.cfg, libvirt/tests/src/controller/pcibridge.py
- pcie-to-pci-bridge has 31 available slots
- [Negative]Attach device with invalid slot to pcie-to-pci-bridge
- [negative] Define a guest by setting pcie-to-pci-bridge model name
!=pcie-pci-bridge.
- [Negative] Invalid controller index for pcie-to-pci-bridge
- [negative] Define a guest with pcie-to-pci-bridge controller's
index <=bus
- Define & start an VM with/without pcie-to-pci-bridge
=> Add new case of pcie

libvirt/tests/src/timer_management.py
=> Fix typo: replace ',' with '%' in 'test.error'

libvirt/tests/cfg/virsh_cmd/domain/virsh_attach_detach_disk.cfg, libvirt/tests/src/virsh_cmd/domain/virsh_attach_detach_disk.py
- Add debug info for attaching disk
- Replace virtio bus with scsi bus for attaching/detaching disk on s390x
Sometimes after cold pluging a disk, the disk names in guest may
change either when booting up or hotunpluging that disk, for
example, before cold pluging, the disk names are 'vda', 'vda1',
'vda2', 'dm-0', 'dm-1', and after coldpluging and hotunpluging the
same disk, the disk names are 'vdb', 'vdb1', 'vdb2', 'dm-0',
'dm-1'. So this fix is intending to avoid of using same bus
'virtio' and the unexpected changes on s390x.
=> virsh_attach_detach_disk:

libvirt/tests/cfg/virsh_cmd/domain/virsh_attach_detach_disk.cfg
Change disk target attached on s390x to make the case stable.
=> virsh_attach_detach_disk: change dist target

libvirt/tests/cfg/cpu/max_vcpus.cfg, libvirt/tests/src/cpu/max_vcpus.py
1> Check the output of 'virsh maxvcpus'
2> Check the output of 'virsh capabilities' about vcpus_num and machine_type
3> Start i440fx VM with 240 vcpus
4> Hot-plug vcpus to i440fx VM until the num of online vcpus is 240
5> Start i440fx VM with more than 240 vcpus (Negative)
=> Add 5 scenarios about max_vcpus

libvirt/tests/src/virsh_cmd/domain/virsh_vcpupin.py
"Shorten the cpus_list if it's too long" commit caused this failure
For the initial vcpupin checking, should use all active host cpus
=> Fix 'virsh vcpupin' initial checking failure

libvirt/tests/cfg/cpu/setvcpu.cfg, libvirt/tests/src/cpu/setvcpu.py
This subcase is based on bug
https://bugzilla.redhat.com/show_bug.cgi?id=1459785
enable/disable vcpu0 when vm is active/inactive and check error
=> add subcase enable/disable vcpu 0

libvirt/tests/src/virsh_cmd/domain/virsh_blockresize.py
Since Qemu version >2.11, zero_size shrink can be supported
Therefore fix it by filter it out of status_error==true
=> Fix zero size resize block issue

libvirt/tests/cfg/libvirt_mem.cfg, libvirt/tests/src/libvirt_mem.py
Initially hotplug was performed without  --live in test, added
--live explicitly.
Random reboot was displayed for normal tests too, fixed the same.
=> Add --live hotplug option to the test and fixed debug messages.

libvirt/tests/cfg/migration/migrate_vm.cfg
Failed to define domain in migration vm_without_video test.
The reason is that same PCI address used in XML file.
Provide a free slot for interface attached.
=> migrate_vm: Fix domain define failure

libvirt/tests/cfg/cpu/vcpu_affinity.cfg, libvirt/tests/src/cpu/vcpu_affinity.py
This test case is based on bug
https://bugzilla.redhat.com/show_bug.cgi?id=1306556
This case specify vcpu affinity for inactive vcpu and check result
=> add subcase inactive vcpu affinity check

libvirt/tests/src/migration/migrate_options_shared.py
Hpt of vm features is now put as an xml object instead of just one
value(resizing). Update the value assignment in migration test code
to keep correct.
based on: https://github.com/avocado-framework/avocado-vt/pull/2045
=> Update value assignment of hpt of vm features

libvirt/tests/cfg/cpu/vcpu_affinity.cfg, libvirt/tests/src/cpu/vcpu_affinity.py
this case is based on bug
https://bugzilla.redhat.com/show_bug.cgi?id=1316371
this bug report that libvirt auto remove the vcpu affinity config
when unplug vcpu with "setvcpus --config"(cold-unplug)
=> vcpu_affinity sub case - check vcpu affinity after cold-unpluging vcpu

libvirt/tests/cfg/controller/controller_functional.cfg, libvirt/tests/src/controller/controller_functional.py
These cases are 'only i440fx',and get an error 'Invalid PCI address 0000:04:00.0. slot must be >= 1 ' if run with q35 machine type.
Hence skip there cases for q35.
=> Skip pci_bridge_auto_add cases for q35 machine type

libvirt/tests/src/libvirt_pci_passthrough_hotplug.py, libvirt/tests/src/usb_device.py
change the attribute "hostdev_type" of class Hostdev to "type" and
make the corresponding change in libvirt test case
=> fix the attribute name "hostdev_type" used in libvirt test case

libvirt/tests/src/virsh_cmd/domain/virsh_migrate.py
provide `connect_uri` to the APIs to assert hotplug/coldplug cpu
inside VM after migrating to target host.
=> virsh_migrate: handle to check vcpu of migrated VM in target host

libvirt/tests/src/migration/migrate_vm.py
It reports an error "failed to initialize gluster connection" while
doing migration if gluster server is setup locally.
So enable ports in firewall before migration to resolve it.
=> migrate_vm: Fix gluster connection issue

libvirt/tests/src/virtual_network/mtu.py
If mtu is only set in network, it will not take effect in the vm. If we
want vm to get the setting, the only way is to set it in device. Update
the script to avoid check mtu in vm if no mtu in interface.
=> Do not check the mtu in vm if no mtu in interface

libvirt/tests/cfg/virsh_cmd/domain/virsh_blockcopy.cfg, libvirt/tests/src/virsh_cmd/domain/virsh_blockcopy.py
bandwidth can be specified in various values in blockcopy parameter,and
correct bandwidth should be displayed during blockcopy operation.
=> add specify copying bandwidth limit cases in blockcopy

libvirt/tests/src/virsh_cmd/domain/virsh_event.py
Per libvirt patch e3389d8, remove the duplicated 'suspend paused'
event from libvirt-5.3.0
=> virsh_event.py: adapt suspend per libvirt version

libvirt/tests/cfg/usb_device.cfg, libvirt/tests/src/usb_device.py
this case is based on bug
https://bugzilla.redhat.com/show_bug.cgi?id=1552127
configure usb controllers with alias and check the name of controller,
masterbus and device id
=> add usb device sub case - start vm with usb controller alias configured

libvirt/tests/cfg/virsh_cmd/domain/virsh_reboot.cfg, libvirt/tests/src/virsh_cmd/domain/virsh_reboot.py
Extend waiting time to 10s. Use 'wait_for' to handle waiting operation
instead of time.sleep()
=> Modify waiting time of ppc64le tests

libvirt/tests/cfg/migration/migrate_vm.cfg, libvirt/tests/src/migration/migrate_vm.py
Add some new checking points to the case, such as
- Checking domjobinfo with --completion option to find default cache
- Checking the libvirtd.log with desired string
Replace exceptions.Test* with test.* according to the strategy
=> migrate_vm: update default compression case

libvirt/tests/cfg/virsh_cmd/domain/virsh_attach_detach_disk.cfg
IDE controllers are unsupported for q35,update it to scsi.
=> Attach cdrom device to scsi

libvirt/tests/cfg/migration/migrate_options_shared.cfg, libvirt/tests/src/migration/migrate_options_shared.py
The cases are to test '--auto-converge' option for migration:
- default -auto-converge
- specified with auto-converge-initial and auto-converge-increment
=> migrate_options_shared: Add auto converge mig cases

libvirt/tests/src/virsh_cmd/domain/virsh_domjobinfo.py
'Memory bandwidth' appears sometimes in running domjobinfo output,
accept items like it. And optimize test fail branches when output
does not match expected list, according to differences between sets.
=> domjobinfo: accept randomly appeared items

libvirt/tests/src/migration/migrate_vm.py
In original script, it reports test failure "Failed to find default
compression cache None". Update checking condition to proper one.
=> migrate_vm: fix compression cache None issue

libvirt/tests/src/npiv/npiv_hostdev_passthrough.py, libvirt/tests/src/virsh_cmd/domain/virsh_attach_detach_disk.py, libvirt/tests/src/virsh_cmd/domain/virsh_domfsinfo.py, libvirt/tests/src/virsh_cmd/domain/virsh_qemu_agent_command_fs.py, libvirt/tests/src/virsh_cmd/nodedev/virsh_nodedev_event.py, libvirt/tests/src/virtual_disks/startup_policy.py, libvirt/tests/src/virtual_disks/virtual_disks_ceph.py, libvirt/tests/src/virtual_disks/virtual_disks_encryption.py, libvirt/tests/src/virtual_disks/virtual_disks_iscsi.py, libvirt/tests/src/virtual_disks/virtual_disks_luks.py, libvirt/tests/src/virtual_disks/virtual_disks_multipath.py, libvirt/tests/src/virtual_disks/virtual_disks_usb.py
The method get_parts_list() is moved from virttest/utils_test/libvirt.py
to virttest/utils_disk.py. Hence updating accordingly.
=> Update cases which call get_parts_list

libvirt/tests/cfg/usb_device.cfg, libvirt/tests/src/usb_device.py
- by default, cold-plug/hot-unplug usb redirdev device to/from guest
- add usb redirdev device by type spicevm or tcp
- hot-plug/unplug usb redirdev device to/from guest
=> add usb redirdev device test case

libvirt/tests/cfg/multivm_loadstress.cfg, libvirt/tests/src/multivm_loadstress.py
Changing the test case to use the api to load multi vm
server client stress
=> Change mutlivm stress test to use utils_test api

libvirt/tests/cfg/migration/migrate_options_shared.cfg, libvirt/tests/src/migration/migrate_options_shared.py
This patch adds 2 tests that could check domjobinfo output during and
after migration.
=> migration: Add 2 domjobinfo cases

libvirt/tests/cfg/virtual_network/iface_hotplug.cfg
There is no qemu-kvm-rhev package on rhel8 any more, so the file
"/usr/share/qemu-kvm/pxe-virtio.rom" which is a symbol link for
"/usr/share/ipxe/1af41000.rom" will not exists. Update the rom
path to "/usr/share/ipxe/1af41000.rom" to avoid the file not found
issue.
=> Fix the rom path issue

libvirt/tests/src/migration/migrate_options_shared.py
In auto-converge case, it checks "Auto converge throttle" in
domjobinfo's output during migration. The problem is that command
"virsh domjobinfo" reports error "Requested operation is not valid:
domain is not running" if run it after migration completed. In this
case, need execute "virsh domjobinfo --completed" to see if
migration is done.
=> migration: Fix domjobinfo command failure in auto-converge case

libvirt/tests/cfg/controller/pcibridge.cfg, libvirt/tests/src/controller/pcibridge.py
Specify a fixed pci address to pci bridge controller: the pci device was hotplugged to the pci-root controller by default but not pci-bridge when we didn't assign the fixed pci address. So it will attach device failed when it judge whether the device is hotplugged to pci bridge.
Signed-off-by: MeinaLi <meili@redhat.com>
=> Fix the hotplug issue in pci bridge controller

libvirt/tests/cfg/virtual_device/sound_device.cfg, libvirt/tests/cfg/virtual_device/watchdog.cfg
Devices are not supported by pseries
=> Remove unsupported cases from pseries tests

libvirt/tests/src/daemon/restart_consist.py
The original 30s is sometimes not enough for ppc machines.
=> Update timeout to 60 to avoid channel not being connected

libvirt/tests/cfg/virtual_disks/virtual_disks_scsi3_persistent_reservation.cfg, libvirt/tests/src/virtual_disks/virtual_disks_scsi3_persistent_reservation.py
SCSI-3 Persistent Reservation starts to be supported by libvirt 4.4.0
and qemu-kvm-rhev 2.10.0. Add test cases for this function. Including:
1. qemu-pr-helper managed by libvirt.
2. qemu-pr-helper managed by script.
3. Hotplug/coldplug disk with <reservations> tag.
4. Check if SCSI-3 Persistent Reservation commands can be issued to
that disk in vm.
5. Hot unplug that disk.
=> Add cases for virtual disk reservations test

libvirt/tests/src/virsh_cmd/domain/virsh_domfsinfo.py
Debug the issue of the virsh_domfsinfo.py
Fix the error “expect matched pattern ‘/mnt\s+vdb\s+ext3\s+vdb\s+’
did not match the virsh.domfsinfo input".
Fix the error about failing to run virsh.domfsinfo after disk unplug.
the error message are as followed:
(1) Unable to get filesystem information”
(2) unable to execute QEMU agent command 'guest-get-fsinfo':
realpath("/sys/dev/block/252:16"): no such file or directory”
=> Debug the issue of the virsh_domfsinfo.py

libvirt/tests/src/serial/serial_functional.py
It will generate address if it's pseries machine, which will make
a difference to expected xml.
=> Skip checking serial xml if it's pseries machine

libvirt/tests/src/virsh_cmd/domain/virsh_attach_detach_interface.py
The the tmp xml file sometimes get lost before used. This fix is
to make sure the tmp filed used just after it's generated.
=> Make sure the tmp file existing until used

libvirt/tests/cfg/channel/channel_functional.cfg, libvirt/tests/src/channel/channel_functional.py
It's to test if a port id is not given when hotplug a channel, port id can
be generated automatically
=> Add auto generate port id when hotplug channel device

libvirt/tests/src/npiv/npiv_hostdev_passthrough.py
Sometimes the script cannot get the attached disk in vm just after
the hotpluging, the disk will show up after a short time. So change
to use a wait_for() to make sure attached disk can be captured by
script.
=> Fix a npiv scsi hostdev hotplug issue

libvirt/tests/cfg/usb_device.cfg, libvirt/tests/src/usb_device.py
this typo is found When there are  3 or more usb devices
=> fix a typo in usb test case

libvirt/tests/src/virtual_disks/virtual_disks_multipath.py
If multipath devs not created without this message, case will be
failed with error "IndexError: list index out of range" which will
cause the failure report merged into other failures with same error
message.
=> Add clear failure message when no newly mpath dev found

libvirt/cfg/build.cfg
Add libvirt build test config to support virttest.libvirt_installer
enablement.
comment `no build` line from this config and can be used as below
to build, install libvirt package from git source
Usage: avocado run --vt-config build.cfg
=> Add libvirt build test config

libvirt/tests/cfg/virsh_cmd/domain/virsh_vcpupin.cfg, libvirt/tests/src/virsh_cmd/domain/virsh_vcpupin.py
Testcase `cpu_list.cpu_list_x` iterates over all
the available host cpus for each guest vcpu, this
becomes a huge number when host has more cpus, lets
introduce a check by reducing the iterations
and still have the coverage by introducing some
randomness.
In test run with 32 guest vcpus and 128 host cpus
,test got interrupted due to test timeout of 4 hours.
virsh.vcpupin.offline.positive_test.cpu_list.cpu_list_x: INTERRUPTED (14401.76 s)
=> vcpupin: Reduce test iterations for certain scenarios

libvirt/tests/src/migration/migrate_options_shared.py
…tion
In cross migration, the output of domjobinfo in source and destination
may different which makes script fail. The reason is the item "Postcopy
requests" is introduced in libvirt 4.10. So in some case, it returns different
domjobinfo result in source and dest. So need to check the libvirt version in
both to see if "Postcopy requests" should be in expected_list or not
=> migration: Update to check libvirt version both in source and destina

libvirt/tests/src/cpu/setvcpu.py
the ast.literal_eval("{0}") will raise ValueError in the python27.
using eval to be compatible with python2 and python3
=> fix ast.literal_eval ValueError: malformed string

libvirt/tests/cfg/migration/migrate_options_shared.cfg, libvirt/tests/src/migration/migrate_options_shared.py
Automate 2 migration cases in this PR.
Theses cases check libvirt statistics command during migration
with/without postcopy. Besides that, fix a minor issue while checking
libvirt version.
=> Migration: Add cases to check statistics command during live migration

libvirt/tests/cfg/virsh_cmd/domain/virsh_migration.cfg, libvirt/tests/src/virsh_cmd/domain/virsh_migration.py
currently migration is performed with default machine type using which
guest is booted, this patch queries all the machine types supported by
source and target host and uses all the supported machine types common
for both source and target to migrate.
=> virsh_migration: Enable migration with all supported machine types

libvirt/tests/src/migration/migrate_options_shared.py
In some case, "Time elapsed w/o network" and "Downtime w/o network"
are not displayed in domjobinfo's output. Hence update to skip
checking on these.
=> migration: Fix an issue for domjobinfo cases

libvirt/tests/src/virtual_disks/virtual_disks_multidisks.py
Fedora27 iso download link is expired, using Fedora30 instead.
=> virtual_disks_multidisks: Fix expired iso link

libvirt/tests/src/virsh_cmd/domain/virsh_blockresize.py
The disk attachment is a key step here. Without the info, it's
hard for debugger to manually check what happened according to
the log.
=> Add log info for disk attachment in block resize cases

libvirt/tests/cfg/virsh_cmd/domain/virsh_change_media.cfg, libvirt/tests/src/virsh_cmd/domain/virsh_change_media.py
Floppy device can be emulated as RO or RW device. Add readonly variants
to make floopy RW or RO.
=> virsh_change_media: Add readonly variants for floppy

libvirt/tests/src/virsh_cmd/domain/virsh_blockcommit.py, libvirt/tests/src/virsh_cmd/domain/virsh_blockpull.py
Previoulsy, the script didn't remove the ceph image it created.
This will casue a 'error rbd create: File exists' error when execute
next case.
=> Fix ceph image issue for blockpull/blockcommit cases

libvirt/tests/cfg/virsh_cmd/domain/virsh_migrate.cfg
The existing configuration only supports P9 <-> P9 migration. So this is
to add P8 <-> P9 migration.
=> [WIP]virsh_migrate: Enable P8 <-> P9 migration

libvirt/tests/cfg/virsh_cmd/domain/virsh_migrate.cfg, libvirt/tests/src/virsh_cmd/domain/virsh_migrate.py
Sometimes, postcopy migration finished before switch to postcopy
or other checks. To do other operations during migration, need
to make it slow.
=> Fix: slow down migration process to do other operations

libvirt/tests/cfg/virsh_cmd/domain/virsh_reboot.cfg, libvirt/tests/src/virsh_cmd/domain/virsh_reboot.py
filter out acpi mode testcases for powerpc in virsh reboot
testcases, vm reboot time often varies each time so give
sufficient time of 60sec to check for vm domstate.
=> virsh_reboot: acpi is not supported for PowerPC

libvirt/tests/src/virsh_cmd/domain/virsh_migrate_stress.py
The arguments of check_vm_state() in libvirt are updated, hence
update related script.
=> Update check_vm_state for virsh_migrate_stress

libvirt/tests/cfg/migration/migrate_options_shared.cfg, libvirt/tests/src/migration/migrate_options_shared.py
This patch adds one test that kill qemu process on target during
migration with postcopy
=> migration: new case to kill qemu process during migration

libvirt/tests/cfg/migration/migrate_vm.cfg, libvirt/tests/src/migration/migrate_vm.py
If nfs setup is not enable for RDMA migration, it will reports:
"Unsafe migration: Migration without shared storage is unsafe"
=> Enable nfs setup for RDMA migration

libvirt/tests/cfg/virsh_cmd/domain/virsh_edit.cfg
Noise guest dmesg checking will leads to cases failures
=> Fix virsh_edit case failure by removing noise dmesg checking

libvirt/tests/cfg/virsh_cmd/domain/virsh_blockcommit.cfg, libvirt/tests/src/virsh_cmd/domain/virsh_blockcommit.py
virsh snapshot-list --tree will dump out snapshot lists like a tree
=> add cases to cover snapshot list check with --tree parameter

libvirt/tests/cfg/virsh_cmd/domain/virsh_blockcopy.cfg
--wait --async options case is missed, this option will pull operation
into mirroring phase
=> add --wait --async option into block_copy

libvirt/tests/src/virsh_cmd/domain/virsh_blockresize.py
it need validate the size returned by qemu info is equals to primitive expected size
=> add qemu-img info validation after block resize

libvirt/tests/src/usb_device.py
In libvirt usb test, the existing pci bus controller will be replaced
by the one configured in cfg file and the device which use these pci
bus may have conflict with the new pci bus in the following scenario:
pci bus_controller = "pcie-root,pcie-root-port,pcie-to-pci-bridge,pci-bridge"
<controller type='virtio-serial' index='0'>
<address type='pci' domain='0x0000' bus='0x03' slot='0x00' function='0x0'/>
</controller>
Therefore, the device address should be cleaned when the address type of device
is pci. The device address will be allocated automaticly when the vm is defined
=> clean device address when the address type of device is pci

provider/v2v_vmcheck_helper.py
The return was removed by mistake in ea984489f06bc058b03a8bc6951328c989da1672.
We should add it back.
=> Fix missing return error by mistake

libvirt/tests/src/migration/migrate_vm.py
The logic is: if the device_type is neither cdrom nor floppy, test
should be cancelled. So the if expression should be:
if device_type != 'cdrom' and device_type != 'floppy':
=> Fix a logic error in add_disk_xml()

libvirt/tests/src/migration/migrate_vm.py
It reported error "UnboundLocalError: local variable 'host_ip'
referenced before assignment" if lost connection to gluster server
at beginning of test. Fix it in 'finally' block.
=> migrate_vm: fix UnboundLocalError: host_ip

libvirt/tests/cfg/papr_hpt.cfg, libvirt/tests/src/papr_hpt.py
- Fix that passing the wrong params to function:set_hpt.
- Update expected error message since the actual error message is
changed.
=> hpt:Fix failed cases on x86

libvirt/tests/cfg/virsh_cmd/volume/vol_concurrent.cfg, libvirt/tests/src/virsh_cmd/volume/vol_concurrent.py
increase volume size and change volume type to give enough time for
the last working thread to make volume operation after the creation of volume
=> fix volume test case vol_concurrent

v2v/tests/cfg/function_test_esx.cfg, v2v/tests/src/function_test_esx.py
Use latest guests with secure boot to replace the old one and
there is no need to install OVMF by manual now.
=> Update guest for virt-v2v case84637 and case18973

libvirt/tests/src/migration/migrate_options_shared.py
Got 'Timeout expired' issue with default timeout value(20s), so
increase the timeout.
=> migration: update timeout to 60s

provider/v2v_vmcheck_helper.py, v2v/tests/cfg/convert_from_file.cfg, v2v/tests/cfg/convert_vm_to_libvirt.cfg
1) Remove vmxml info in log_err that will make a long error log
2) Add more guests for genid and libosinfo
=> Add more genid and libosinfo cases for v2v

libvirt/tests/src/migration/migrate_vm.py
QEMU_CAPS_DRIVE_MIRROR became default qemu caps from v5.3.0 and no
longer present in '/var/cache/libvirt/qemu/capabilities/xx.xml'.
So update the condition.
=> migration: Fix pool issue

libvirt/tests/src/migration/migrate_options_shared.py
The value of 'Postcopy requests' in domjobinfo's output is hard to
predict when to change during postcopy migration.
So update to check it once migration's done.
=> Fix: check Postcopy requests's value after migration is done

libvirt/tests/src/migration/migrate_vm.py
Before check 'domjobinfo --completed', needs to check if migration is
done. If not, it reports unclear error message. Update to provide
proper error message in this case.
=> migration: update to check migration result before domjobinfo checking

libvirt/tests/src/libvirt_vcpu_plug_unplug.py
=> libvirt_vcpu_plug_unplug: Check if var 'bt' is None before calling

libvirt/tests/cfg/serial/serial_functional.cfg, libvirt/tests/src/serial/serial_functional.py
To avoid conflict with another var named 'serial_type'
=> Rename 'serial_type' to 'serial_dev_type' to avoid conflict

libvirt/tests/src/virsh_cmd/domain/virsh_blockresize.py
When qemu supports lock, the 'qemu-img info' cmd will be failed.
So fix it.
=> Check qemu lock for blockresize cases

libvirt/tests/src/virtual_device/watchdog.py
When waiting for vm rebooting, it has a chance for Shell*Error
exception to happen. The exception needs to be caught, or the
test case will fail.
=> Catch Shell*Error exception when waiting for vm rebooting

libvirt/tests/src/migration/migrate_options_shared.py
Sometimes, migration result is still not returned when the code
starts to check the result.
=> Check whether 'result' is None before referencing it.

libvirt/tests/cfg/virsh_cmd/domain/virsh_setvcpus.cfg, libvirt/tests/src/virsh_cmd/domain/virsh_setvcpus.py
The precondition for this case is to have one topology element in vmxml,
Therefore, by adding one topology element before executing any further action
=> Fix setvcpus error_test shut_off error option with topology case fail

v2v/tests/cfg/function_test_esx.cfg, v2v/tests/cfg/function_test_xen.cfg, v2v/tests/src/function_test_esx.py, v2v/tests/src/function_test_xen.py
Change the destination of case84568 from libvirt to rhv, change
the source of case12986 from Xen to VMware and modify 
corresponding function of checkpoint as previous result is not 
expected.
=> Change destination for v2v case84568 and source for v2v case12986

v2v/tests/src/v2v_options.py
As rhel8 slow train doesn't support '-ip' option, add function to
replace the option 'ip' using '--password-file', and modify the
expected log info for case80271 and case80272.
=> Fix incompatible options and modify two cases for v2v_option job

libvirt/tests/cfg/migration/migrate_vm.cfg, libvirt/tests/src/migration/migrate_vm.py
For qemu-kvm>=2.10.0, storage migration with shared storage can succeed;
For qemu-kvm<2.10.0, storage migration with shared storage will fail.
=> Difference the expected result of storage migration per qemu version

libvirt/tests/src/virtual_disks/virtual_disks_multivms.py
This commit makes testcase use new api to check for specific labels
in the selinux context.
=> Use new api for check selinux context of file

libvirt/tests/cfg/bios/boot_integration.cfg, libvirt/tests/cfg/bios/virsh_boot.cfg, libvirt/tests/src/bios/virsh_boot.py
1. Change ide bus to scsi bus in cfg to support seabios-q35
2. Add bootmenu in os element to make sure case can get CDROM prompt
Signed-off-by: meinaLi <meili@redhat.com>
=> BIOS: fix ide bus issue and CDROM issue in seabios option

libvirt/tests/cfg/cpu/vcpu_affinity.cfg, libvirt/tests/src/cpu/vcpu_affinity.py
There are 2 failures for the following test case:
vcpu_affinity.negative_test.cputune.offline_hostcpu
1> For some machines; can not operate host cpu0; which will cause unexpected err msg
2> For negatively set vcpu affinity; the err msg has changed for both RHEL-7 and 8
=> Fix err msg pattern and hostcpu 0 operation for vcpu_affinity case

provider/v2v_vmcheck_helper.py, v2v/tests/cfg/function_test_xen.cfg
The video driver is cirrus if virtio_win is unset during v2v
windows conversion.
=> Fix result for auto case 'virtio_win.unset' of v2v case18974

libvirt/tests/cfg/virtual_device/watchdog.cfg, libvirt/tests/src/virtual_device/watchdog.py
Now, only support hotplug and hotunplug operation to i6300esb
watchdog device
And also cancel the ib700wdt watchdog device cases on guest with
q35 machine type
=> Add hotplug and hotunplug cases into i6300esb watchdog device

provider/v2v_vmcheck_helper.py, v2v/tests/cfg/function_test_esx.cfg
Users can set a checkpoint for UEFI guest by biostype in cfg files.
It has value 0-3. 0 is default now. In futrue, after v2v supports
converting all guest to q35 by default, The default value can be
updated to 1 for adapting the change.
All possible values of 'biostype' can be set by users:
0: ['i440fx', 'bios', False]
1: ['q35', 'bios', False]
2: ['q35', 'uefi', False]
3: ['q35', 'uefi', True]
The checking for biostype.
- check chipset and boot type in vm xml
- check if guest boots with uefi if boot type is UEFI
=> Add UEFI checkpoint for v2v

libvirt/tests/src/libvirt_vcpu_plug_unplug.py
Earlier VM uptime variable in reboot
test was not getting properly updated, which
resulted in false failure of test,
FAIL: Unexpected VM reboot detected in between test (221.54 s)
Let's handle it updating the variable in global scope.
=> Fixup: VM uptime variable update for reboot test

libvirt/tests/src/remote_access/remote_access.py
If ssh pubkey of source host is present on remote, it accesses
without password which makes some cases fail. So remove it.
=> remote_access: remove ssh pubkey on remote

libvirt/tests/src/remote_access/remote_access.py
It reports "error: failed to connect to the hypervisor" while
connecting to libvirtd if it's not up. So need to make sure
if libvirtd is running before connection attempts.
=> remote_access: fix remote libvirtd connection issue
